### ISSUE TITLE
metrics: wanted: histograms for skewed distributions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10015]
Found in #9259: we'd like to keep histograms for the distribution of session memory sizes, which has a lot of small values but a few very large values. Unfortunately if one creates a histogram with a large maximum value (the maximum SQL memory size, which for the internal executor is MaxInt64 and for normal SQL session can run into gigabytes) two problems occur: 

1) a bug in the current implementation: the server hangs trying to create a very large array to support the histogram values.

2) precision loss: all the small sizes end up in a single bucket because the range is very large.

Currently in #9259 the problem is worked around by tracking an histogram of the logarithm of the sizes, but it would be nice to have a new histogram type that does this natively.

Jira issue: CRDB-6145

**Comment by a6802739** [comment]
@knz, I could have a see on it now.

**Comment by tschottdorf** [comment]
@knz I assume you tried using our `metrics` histogram type? I'm surprised that you would see 2) because the point of that histogram is precisely spacing buckets relative to the size of the value at which it is centered.
TBH, tracking the logarithm of the size seems pretty sane and going out on a tangent and implementing a new special-cased histogram type seems hardly justified.

**Comment by ajwerner** [comment]
@knz this feels stale. Can it be closed?

**Comment by knz** [comment]
I feel the issue is still current but the problem is owned by Obs infra now.

@dhartunian what do you think?

**Comment by dhartunian** [comment]
@knz yep I'd like us to triage this and see what we can do. I'm be curious to replicate the issue.

**Comment by ajwerner** [comment]
Ah right so for our histograms, we tend to use a hard-coded config that (as discussed in #64962) use a very large number of buckets near zero and cannot really represent anything above hundreds of seconds and even then, barely. The things with HDR histograms (roughly the only form of distribution supported by prometheus and the likes which can be combined to produce meaningful statistics, see https://prometheus.io/docs/practices/histograms/).

That issue and this one end up being quite similar. HDR histograms and its relatives (it doesn't really matter how you pick the buckets -- it'll be somewhere between logarithmic and linear) will only be able to cover a finite span at a given precision and the precision vs. size is a direct tradeoff. Histograms must be configured up front.

There are other approaches to distribution sketching (often called summaries). Generally these summaries can be more compact and dynamic. The problem with them tends to be that that either don't compose or, more to the point, that they do not have a decomposed storage format supported by the time-series databases we care about. Another knock against summaries is that they tend not to have a valid notion of subtraction (in fact, this feels like a philosophically deep property of the dynamism of these sketches). Prometheus and generally tools like it, given monotonically increasing bucket counts, are able to provide an understanding of the distribution between any two samples; that's a very powerful property. Something has to give; you can be accurate, precise, and compact over a wide and dynamic range with the tradeoff of requiring less precise time range (accumulating t-digests over time windows), or you can have the histogram tradeoffs we have today (which would benefit form better tuning). You can bend the tradeoff curve a bit by using different time windowing schemes to use more space in order to get more precise time windows. 

Cockroach internally just stores the percentiles, but those cannot be aggregated across nodes (see https://github.com/cockroachdb/cockroach/issues/7896). They become even more meaningless in a serverless world.

**Comment by knz** [comment]
The issue at top was also me suggesting to implement a histogram type with a built-in logarithmic function, which would go 70% of the way.

**Comment by ajwerner** [comment]
Yeah, HDR histograms are already logarithmic. The library we're using is not super flexible to configure, but that's fine. I'd do something like `hdrhistogram.New(128, 1<<40 /* 1 TiB max value*/ , 1)` which has fewer buckets that our existing latency histograms.

https://play.golang.org/p/txCn3RSj7Zk

**Comment by ajwerner** [comment]
https://github.com/beorn7/histogram_experiments seems smart

**Comment by tbg** [comment]
@lunevalex I'm not working on this.
