### ISSUE TITLE
Forget to adds to the write timestamp cache for EndTransaction

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#10019]
```
case *roachpb.EndTransactionRequest:
	// EndTransaction adds to the write timestamp cache to ensure replays
	// create a transaction record with WriteTooOld set.
	key := keys.TransactionKey(header.Key, cr.txnID)
	cr.txn = roachpb.Span{Key: key}
```
seems not add to `cr.writes`

**Comment by nvanbenschoten** [comment]
Hi @changrui82, thanks for the report. You're correct that `EndTransactionRequest`s are not added to the `writes` field in the `cacheRequest`, however they are set on the `cacheRequest.txn` field. If we look [into the timestamp cache](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/pkg/storage/timestamp_cache.go#L582), we can see that this field, if set, is also added to the write timestamp cache, but is separated because it has slightly different semantics for the txnID. As the comment explains, because of the nature of an end transaction request, we set the txnID to nil to effectively protect against replays.
