### ISSUE TITLE
sql: parallelize multi-region scans in more cases

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#100496]
Currently, we can only perform multiple scans in parallel if both of the following are true:

1. There are no hard nor soft limits.
2. We must know at planning time that we're guaranteed to read less than 10k rows.

It's hard to satisfy both these cases. The most common way is when scanning a bounded range of a unique index.

Our inability to parallelize scans more often is particularly detrimental in multi-region environments. The latency of performing a scan in each of `r` regions with a round-trip time `t` is `O(r * t)`. If we can perform the scans in parallel, the latency is simply `O(t)`. 

Jira issue: CRDB-26466

gz#16552

Epic CRDB-25448

**Comment by yuzefovich** [comment]
Here is a quick summary of the ideas we discussed during the triage:
- **option A**: the long-term solution to this ticket is extending the Streamer to be used by the `TableReader` processors (tracked [here](https://github.com/cockroachdb/cockroach/issues/82164)). However, that is likely non-trivial amount of work and won't be backportable, so it'd be 23.2 at the earliest
- the short-term solution involves enabling the parallelism across ranges by disabling the usage of `BatchRequest`'s limits for scans. This can result in increased memory usage and could lead to OOMs, but given that we have GOMEMLIMIT enabled by default in 23.1 it shouldn't be too destabilizing of a change. There a few options how to enable the parallelism here:
  - **option B**: add an explicit session variable for this; backportable to 22.2
  - **option C**: extend SQL syntax to provide the "parallel" hint directly in the query, this can be safer to roll out than the session variable, but it'll require the app change, so likely less desirable than the previous option; also probably backportable to 22.2
  - **option D**: extend our heuristic to decide when it is safe to parallelize (i.e. adjust requirement 2. from the issue description), perhaps by using estimated row count (rather than guaranteed row count) or allowing certain query shapes; this seems trickier to implement than the previous two options, but this can have the potential of helping in more cases by default, without having to opt in; probably backportable to 23.1, off by default.

I believe the right course of action here is to implement **option B** and then try to do **option A** in 23.2. If **option A** doesn't happen for whatever reason, then do **option D** in 23.2. cc @rytaft

**Comment by rytaft** [comment]
Thanks @yuzefovich! Can you also add some info about the query requirements for each case? e.g., Option A will work if the query has a LIMIT but B-D will not?

**Comment by yuzefovich** [comment]
Yes, your comments are all spot on. I edited my previous comment to incorporate these details.

**Comment by michae2** [comment]
[triage meeting] we think option B is sufficient for now, @michae2 to ask account team about usage of the session variable

**Comment by michae2** [comment]
We did option B, and are now waiting for the long-term fix ([using the streamer in TableReader](https://github.com/cockroachdb/cockroach/issues/82164)). Closing this.
