### ISSUE TITLE
perf: provide batching mechanism for SQL statements

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#10057]
Need to implement a mechanism for batching multiple SQL statements for parallel execution. Currently, use of a SQL driver implies serial execution of SQL statements. Where replicas have high link latencies, serial execution of multiple statements within a single transaction can become prohibitive in aggregate latency.

See #2210, #4403, #4703, #5259

Here's a simple test driver which reads two values and then updates each value as well as inserting three additional values within a single transaction:

```
package main

import (
    "database/sql"
    "flag"
    "fmt"
    "log"
    "math/rand"
    "net/url"
    "os"
    "sync/atomic"
    "time"

    // Import postgres driver.
    "github.com/cockroachdb/cockroach-go/crdb"
    _ "github.com/lib/pq"
)

const initialBalance = 100

var maxTransfer = flag.Int("max-transfer", 999, "Maximum amount to transfer in one transaction.")
var numAccounts = flag.Int("num-accounts", 100, "Number of accounts.")
var concurrency = flag.Int("concurrency", 16, "Number of concurrent actors moving money.")
var balanceCheckInterval = flag.Duration("balance-check-interval", 1*time.Second, "Interval of balance check.")

var txnCount int32

type measurement struct {
    read, write, total time.Duration
}

func moveMoney(db *sql.DB, readings chan measurement) {
    for {
        var readDuration, writeDuration time.Duration
        var fromBalance, toBalance int
        from, to := rand.Intn(*numAccounts), rand.Intn(*numAccounts)
        if from == to {
            continue
        }
        amount := rand.Intn(*maxTransfer)
        start := time.Now()

        if err := crdb.ExecuteTx(db, func(tx *sql.Tx) error {
            startRead := time.Now()
            rows, err := tx.Query(`SELECT id, balance FROM account WHERE id IN ($1, $2)`, from, to)
            if err != nil {
                return err
            }
            readDuration = time.Since(startRead)
            for rows.Next() {
                var id, balance int
                if err = rows.Scan(&id, &balance); err != nil {
                    log.Fatal(err)
                }
                switch id {
                case from:
                    fromBalance = balance
                case to:
                    toBalance = balance
                default:
                    panic(fmt.Sprintf("got unexpected account %d", id))
                }
            }
            startWrite := time.Now()
            if fromBalance < amount {
                return nil
            }
            insert := `INSERT INTO transaction (id, txn_ref) VALUES ($1, $2);`
            txnID := atomic.AddInt32(&txnCount, 1)
            _, err = tx.Exec(insert, txnID, fmt.Sprintf("txn %d", txnID))
            if err != nil {
                return err
            }
            insert = `INSERT INTO transaction_leg (account_id, amount, running_balance, txn_id) VALUES ($1, $2, $3, $4);`
            if _, err = tx.Exec(insert, from, -amount, fromBalance-amount, txnID); err != nil {
                return err
            }
            if _, err = tx.Exec(insert, to, amount, toBalance+amount, txnID); err != nil {
                return err
            }
            update := `UPDATE account SET balance = $1 WHERE id = $2;`
            if _, err = tx.Exec(update, toBalance+amount, to); err != nil {
                return err
            }
            if _, err = tx.Exec(update, fromBalance-amount, from); err != nil {
                return err
            }
            writeDuration = time.Since(startWrite)
            return nil
        }); err != nil {
            log.Printf("failed transaction: %v", err)
            continue
        }
        if fromBalance >= amount {
            readings <- measurement{read: readDuration, write: writeDuration, total: time.Since(start)}
        }
    }
}

func verifyTotalBalance(db *sql.DB) {
    var sum int
    if err := db.QueryRow("SELECT SUM(balance) FROM account").Scan(&sum); err != nil {
        log.Fatal(err)
    }
    if sum == *numAccounts*initialBalance {
        log.Printf("The total balance is %d.", sum)
    } else {
        log.Printf("The total balance is incorrect: %d.", sum)
        os.Exit(1)
    }
}

var usage = func() {
    fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
    fmt.Fprintf(os.Stderr, "  %s <db URL>\n\n", os.Args[0])
    flag.PrintDefaults()
}

func main() {
    flag.Usage = usage
    flag.Parse()

    if flag.NArg() != 1 {
        usage()
        os.Exit(2)
    }

    dbURL := flag.Arg(0)

    parsedURL, err := url.Parse(dbURL)
    if err != nil {
        log.Fatal(err)
    }
    parsedURL.Path = "test"

    db, err := sql.Open("postgres", parsedURL.String())
    if err != nil {
        log.Fatal(err)
    }
    defer func() { _ = db.Close() }()

    if _, err := db.Exec("CREATE DATABASE IF NOT EXISTS test"); err != nil {
        log.Fatal(err)
    }

    // concurrency + 1, for this thread and the "concurrency" number of
    // goroutines that move money
    db.SetMaxOpenConns(*concurrency + 1)

    if _, err = db.Exec(`
CREATE TABLE IF NOT EXISTS account (
  id INT,
  balance BIGINT NOT NULL,
  name STRING,

  PRIMARY KEY (id),
  UNIQUE INDEX byName (name)
);

CREATE TABLE IF NOT EXISTS transaction (
  id INT,
  booking_date TIMESTAMP DEFAULT NOW(),
  txn_date TIMESTAMP DEFAULT NOW(),
  txn_ref STRING,

  PRIMARY KEY (id),
  UNIQUE INDEX byTxnRef (txn_ref)
);

CREATE TABLE IF NOT EXISTS transaction_leg (
  id BYTES DEFAULT uuid_v4(),
  account_id INT,
  amount BIGINT NOT NULL,
  running_balance BIGINT NOT NULL,
  txn_id INT,

  PRIMARY KEY (id)
);

TRUNCATE TABLE account;
TRUNCATE TABLE transaction;
TRUNCATE TABLE transaction_leg;
`); err != nil {
        log.Fatal(err)
    }

    for i := 0; i < *numAccounts; i++ {
        if _, err = db.Exec("INSERT INTO account (id, balance, name) VALUES ($1, $2, $3)",
            i, initialBalance, fmt.Sprintf("account %d", i)); err != nil {
            log.Fatal(err)
        }
    }

    verifyTotalBalance(db)

    lastNow := time.Now()
    readings := make(chan measurement, 10000)

    for i := 0; i < *concurrency; i++ {
        go moveMoney(db, readings)
    }

    for range time.NewTicker(*balanceCheckInterval).C {
        now := time.Now()
        elapsed := time.Since(lastNow)
        lastNow = now
        transfers := len(readings)
        log.Printf("%d transfers were executed at %.1f/second.", transfers, float64(transfers)/elapsed.Seconds())
        if transfers > 0 {
            var aggr measurement
            for i := 0; i < transfers; i++ {
                reading := <-readings
                aggr.read += reading.read
                aggr.write += reading.write
                aggr.total += reading.total
            }
            d := time.Duration(transfers)
            log.Printf("avg read time: %v, avg write time: %v, avg txn time: %v", aggr.read/d, aggr.write/d, aggr.total/d)
        }
        verifyTotalBalance(db)
    }
}
```

**Comment by vivekmenezes** [comment]
Anyone interested in picking this up?

**Comment by petermattis** [comment]
I think we need to decide on what sort of intra-statement parallelization we're targeting and how we're going to achieve it. The above example is executing the following statements within a transaction:

```
SELECT id, balance FROM account WHERE id IN ($1, $2);
INSERT INTO transaction (id, txn_ref) VALUES ($1, $2);
INSERT INTO transaction_leg (account_id, amount, running_balance, txn_id) VALUES ($1, $2, $3, $4);
UPDATE account SET balance = $1 WHERE id = $2;
UPDATE account SET balance = $1 WHERE id = $2;
```

We can combine the 2 `UPDATEs` into a single statement with same `CASE` trickery. Then we have 3 mutating statements to 3 different tables which conceptually could be executed concurrently. Let's assume the user has to opt-in to this behavior because we'll almost certainly have to change error semantics. The user will have to send all 3 statements at the same time, but that's already feasible by separating them with semicolons. What other error checking should we do? At one extreme we could be try and guarantee that the statements are touching independent rows/tables. At the other extreme, we could do no additional error checking, perform the reads for each statement as a single batch and then the writes for each statement as a single batch. 

Something interesting to note here: the `UPDATE` statements usually require a read of the existing row, but we already selected that row earlier in the query, though I don't see an obvious way to utilize that knowledge to optimize away the read. Perhaps an `UPSERT` and an appropriately configured table could change the read+write into a `CPut`.

**Comment by spencerkimball** [comment]
As an alternative to sending the updates separated by semi-colons, I was thinking we might just return a successful return value immediately from the server, while batching the requested mutation. On a read or a commit, we'd send the accumulated write batch and at that point return the first received error. This would probably work a lot better with existing ORMs and the like. Batching up all writes into a single SQL statement will require existing apps to be more completely rewritten.

Also, I suggest we not focus on optimizing this particular use case, but instead on the general case.

**Comment by bdarnell** [comment]
> We can combine the 2 UPDATEs into a single statement with same CASE trickery.

It's possible, but I think it's beyond most users' SQL knowledge (at least when the queries get more complicated) and it more or less requires them to write queries by hand instead of using any ORM or higher-level framework. We should focus on ways to batch statements that are impractical to combine into one. 

> Then we have 3 mutating statements to 3 different tables which conceptually could be executed concurrently.

If there is a foreign key from `transaction_leg` to `transaction`, then it may be tricky to execute these concurrently. (but I guess that's for the SQL planner to decide; this issue is just about how we can collect multiple statements from the client so we could hand them to the planner all at once)

> As an alternative to sending the updates separated by semi-colons, I was thinking we might just return a successful return value immediately from the server, while batching the requested mutation. On a read or a commit, we'd send the accumulated write batch and at that point return the first received error.

Yeah, I think this is the right approach. 

For `INSERT` (without `RETURNING`), I think we could probably get away with returning success immediately without waiting for execution and deferring the error until later. This would break apps that rely on catching an error from insert to determine whether an error exists, so we might want to make it opt-in, but I don't think that exception-catching pattern works well with our transaction model (we don't let you continue after the constraint violation without restarting the whole transaction, do we?), so it might be OK to do it by default.

For `UPDATE` and `DELETE`, there is always a return value (the number of rows affected if no `RETURNING` clause is used), so I don't think we could defer these without an opt-in. The opt-in could take the form of a tweak to the statement (`RETURNING NOTHING`?), or a session variable. (it seems cleaner to put it in the statement, but a session variable might be easier for ORM compatibility).

> Batching up all writes into a single SQL statement will require existing apps to be more completely rewritten.

Do we know this? It looks like ORMs often do have some sort of batch support, although in many cases it's limited to simple cases like multiple inserts to the same table (and support for statements separated by semicolons is often disabled as a guard against SQL injection).

**Comment by nvanbenschoten** [comment]
I think this can be closed now. A lot of progress has been made on the implementation of https://github.com/cockroachdb/cockroach/pull/13160. `RETURNING NOTHING` syntax is now fully supported inside (https://github.com/cockroachdb/cockroach/pull/14188) and outside (https://github.com/cockroachdb/cockroach/pull/14803) transactions. Course grained data dependency analysis has been added (https://github.com/cockroachdb/cockroach/pull/14553) so that parallelism can safely and transparently be exploited even in the presence of dependent commands. Finally, parallel statement execution was demonstrated to provide the expected speedups for [target workloads](https://github.com/cockroachdb/examples-go/pull/103) (near-linear speedup for fully-independent statement sequences).

Before vocalizing the support too much, we should make sure that the terminology is switched in all places to "parallel statement execution" instead of "pipelined statement execution", per https://github.com/cockroachdb/cockroach/issues/14413.

Future development will include:
- [ ] A blog post
- [ ] Documentation (https://github.com/cockroachdb/docs/issues/1290)
- [ ] Finer-grained dependency analysis for INSERTs (https://github.com/cockroachdb/cockroach/issues/14953)

cc. @dianasaur323
