### ISSUE TITLE
kvserver: audit replication upgrade tests

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#100687]
See #100552.

The following are owned by replication:

- [x] TestBiDirectionalRangefeedNotUsedUntilUpgradeFinalilzed
- [x] TestMigrateWaitsForApplication
- [x] TestLeaseUpgradeVersionGate
- [x] TestRangeMigration

Marking as release blocker since the main issue is, but this feels more like a GA blocker.

Jira issue: CRDB-26556

**Comment by aliher1911** [comment]
`TestRangeMigration` - is ok, it is using made up versions to verify that below raft migration infrastructure works and doesn't test any actual migrations.
`TestLeaseUpgradeVersionGate` - is ok as it only needs version to test version gates, we can bootstrap with latest data and do tests regardless.
`TestMigrateWaitsForApplication` - is ok as it is testing migration machinery rather than actual migration effects.
`TestBiDirectionalRangefeedNotUsedUntilUpgradeFinalilzed` - is ok, we only need version gate regardless of data.

**Comment by aliher1911** [comment]
All good.

**Comment by erikgrinaker** [comment]
Thanks, can you mirror that on #100552 please?
