### ISSUE TITLE
Surface a metric to enable users to alert on when a client's cert age is close to expiring

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#100699]
This issue tracks adding a metric that allows users to alert when client's cert age is close to expiring. 

Per Sean-

Hypothetically, a server-side VerifyConnection function such as https://pkg.go.dev/crypto/tls#example-Config-VerifyConnection will allow us to poke at the [peer's ConnectionState](https://pkg.go.dev/crypto/tls#ConnectionState), which has the [NotAfter](https://pkg.go.dev/crypto/x509#Certificate) attribute, and we can use time.Now().Sub(crt.NotAfter) to emit an aggregate time.Duration that can be polled via a prom endpoint that customers can alert on now that this information has been exposed._

Related issue: https://github.com/cockroachdb/cockroach/issues/99422

Jira issue: CRDB-26585

**Comment by kevin-v-ngo** [comment]
@abhinavg6, does identity have a project board on github?

**Comment by abhinavg6** [comment]
I don't think so Kevin. 

@zaneteh-crl - This is a CRDB specific certs related issue which is being escalated by a key SH customer. And based on internal discussions between @duoclikebook and others, Identity team maybe on the hook for such things. So Kevin is asking if he could assign it to a Identity team board on Github.

**Comment by zaneteh-crl** [comment]
I'm not aware of a project board on github for Identity. We can track things through the JIRA ticket.

**Comment by maryliag** [comment]
Some pointers for the Identity team:

There are already some metrics created for some types of certificates here: 
https://github.com/xinhaoz/cockroach/blob/77d9d01aff6e42e58c9ea9b47e4be81a66a852a7/pkg/security/certificate_manager.go#L29

but there are no metrics for this one, which I assume if the ask for this issue: https://github.com/cockroachdb/cockroach/blob/77d9d01aff6e42e58c9ea9b47e4be81a66a852a7/pkg/security/certificate_manager.go#L124

You who is working on this might start on that.

**Comment by cameronnunez** [comment]
The pointers look right to me, I imagine it should look something like:
```
metaUserClientExpiration = metric.Metadata{
    Name:        "security.certificate.expiration.user-client",
    Measurement: "Certificate Expiration",
    ...
}
```

Looks like the mapping `clientCerts` has the necessary info. We'll need ensure this metric gets exposed (maybe this is done through `metric.PrometheusExporter`?) and is on the list of exported metrics for self-hosted.

Looks like this work might fall under Observability Infra, they might know more about this area @nkodali @abarganier

**Comment by cameronnunez** [comment]
The tricky part is we'll need to partition the metric by SQL username it seems. 

The amount of dev work seems light, so I'd estimate it is ~0.5–1 week

**Comment by bdarnell** [comment]
Any monitoring we do on the server side will be flawed, but it still seems worth making an effort here if we can get something "good enough" that is substantially easier than setting up monitoring on the client side (where I'm not aware of common tools or practices that we can easily advocate)

Here are a few straw proposals to consider:
1) The server keeps metadata about all client certificates used in the last 24h and exports a metric for the *minimum* time-to-expiration in that set. This is a conservative approach to find certificates that are near expiration as reliably as possible, but it may have false positives since we will remember the old certificate until the 24h window expires (because even when we see a newer certificate for the same username, we cannot be certain that there are not other client processes that are still holding on to the old one)
2) The server keeps a map from username to *maximum* expiration time of any certificate used by that user. This strategy avoids false positives by assuming that the application's deployment discipline is reliable enough to replace all certificates for a user at once, but if a stray client process were missed it would not be detected.
3) The server keeps a map from username to the expiration of the *most recent* certificate used for that user. This is an ugly method that produces a metric that jumps around a lot, but can probabilistically detect one client out of the pool that has an out-of-date cert. 
4) Use logging instead of metrics: when a client authenticates with a certificate that is close to expiration, log a message on a suitable channel. "Close to expiration" probably needs to be configurable given the wide range of practices seen in the wild, although maybe we could come up with some heuristics (I believe both the creation and expiration timestamp of a certificate are known so we could perhaps do something based on a fraction of the certs lifespan)

Another thing worth considering is to encourage some sort of "client instance ID" in a certificate so that we could tell reliably when one certificate completely replaces another instead of having to make guesses about whether or not other copies of the certificate may still be in use.

**Comment by knz** [comment]
Internal discussion here: https://cockroachlabs.slack.com/archives/CGA9F858R/p1682366134421889
