### ISSUE TITLE
sql: Implement pg_catalog.pg_proc as a virtual table

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10075]
See https://www.postgresql.org/docs/9.6/static/catalog-pg-proc.html.

@mjibson This made me think of you, because of all the work you've done with documenting builtins functions.

**Comment by jordanlewis** [comment]
This is a pretty complex spec, some of which we can't correctly support without a completed `ARRAY` implementation. I gathered from speaking with @cuongdo that the intent of this task (and the other related ones) is not to achieve 100% compliance with Postgres. If that's the case, what of `pg_proc` do we need to support to support Hibernate?

I tried to see where Hibernate uses `pg_proc`, but I couldn't actually find anything (using [this GitHub search query](https://github.com/search?utf8=%E2%9C%93&q=pg_proc+user%3Ahibernate&type=Code&ref=searchresults)) - what am I missing?

**Comment by cuongdo** [comment]
I can merge the `ARRAY` change. 

However, what's the complexity? AFAICT this table contains info on user-defined functions, which we don't support yet. So, it looks like this task boils down to creating a new virtual table with the appropriate columns but no actual rows. What am I missing @jordanlewis & @nvanbenschoten?

**Comment by jordanlewis** [comment]
It also contains builtin functions. `select count(*) from pg_catalog.pg_proc` returns 2821 on a fresh, empty postgres instance.

It would be pretty easy to hook up our builtins to a few of the columns in `pg_proc`, but there are many that we won't know how to fill in without investing a bunch of extra effort. That's why I was trying to figure out which of the columns actually get used by Hibernate.

**Comment by jordanlewis** [comment]
Okay, thanks for the pointers. I've already begun making a few small changes to `Builtin`.

This is related to #10072, because we need to reference rows in the `pg_type` table. @nvanbenschoten, I assume you're planning to use `oidhasher.TypeOid(parser.Type)` for the `oid` keys of `pg_type`? If so, it seems like we'll need to decide on a placeholder or special type for the types inside an `AnyType` type list so that `pg_proc` can properly represent the type of `AnyType` functions like `least` or `greatest`. Thoughts on this? For now, I'll probably just pretend that those functions are the same as variadic string functions for simplicity.

**Comment by nvanbenschoten** [comment]
The `pg_type` table PR is actually going to change that a bit because type oids are the only oids that need to be compatibly with Postgres. I wouldnt worry about it on your end though. For now just call `oidhasher.TypeOid(parser.Type)` and we can update it if the `pg_type` change goes in first.

It looks like postgres returns a separate row for each type compatible with an `AnyType` function. I'd assume we would want to do the same. Are there any complications with that?
