### ISSUE TITLE
sql: Problems with DROP COLUMN and DROP CONSTRAINT behavior

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10122]
While changing / playing around with DROP COLUMN this morning, I noticed a few issues / questions:
1. Drop behavior (RESTRICT/CASCADE) is totally ignored by the implementation of DROP COLUMN
2. Drop behavior isn't even saved by the parser if using the IF EXISTS form of DROP COLUMN.
3. We restrict the dropping of columns that are used in an index. That's probably correct behavior, but it's different from postgres, which will happily delete any column regardless of whether it's used in an index or even in the primary key.
4. Drop behavior (RESTRICT/CASCADE) is totally ignored by the implementation of DROP CONSTRAINT

I'll fix up the first two points.

As for the third, I kind of like our behavior better than postgres's, but is it something that we should call out explicitly anywhere if we want to stick with it?

As for DROP CONSTRAINT, I'm not quite as into that code right now, but can fix it up as well if desired.

@knz

**Comment by a-robinson** [comment]
Also, regarding point 3, it's not clear that we could support dropping of columns that are part of primary keys even if we wanted to without some serious effort.

**Comment by knz** [comment]
Points 1 and 2 are a bug and I think your PR #10124 addresses that.

Related to point 3 and 4:
- #8497 dropping foreign keys
- #7537 drop and constraints
- #6463 drop a unique colum
- #8036 dropping interleaved child
- #6122 drop database


Regarding point 3 I foresee there are two schools of thought. Mine (and PostgreSQL's, and Oracle's, and I suspect MySQL's) is to say "if the user has permission to issue ALTER and especially if CASCADE is specified, they know what they are doing and we should not get in their way by preventing the operation." The other school of thought is "users care about their data more than their education and we probably prefer to prevent them from shooting themselves in the foot than having to deal with complaints about data loss." I think that's more or less where the discussion in #6122 has stalled.

I think what we should really do is implement the full cascading behavior for all these cases (as long as the code to do so is not overly intricate), and wait and see if users complain. We can always add a "help me not shoot myself in the foot" session flag later if needed.

**Comment by knz** [comment]
cc @dt for the discussion about UX around these issues.

**Comment by a-robinson** [comment]
I haven't thought about it all that much so take this with a grain of salt, but it seems like this general class of problem already has a pretty good solution that's pretty well known -- by default you'll get an error if anything depends on what you're deleting, but you can override the error with CASCADE. The only issue I have with using that approach everywhere is that postgres behavior differs from that in some cases, so we have to make a more conscious choice in those cases.

I agree with implementing cascade behavior as an option for all the cases as long as it's not overly complicated.

Also, another relevant issue for your list:

* #3943 - drop database cascades to all dependent objects without any confirmation or restrict option

**Comment by dt** [comment]
= @a-robinson. Default is  always`RESTRICT`, meaning you can't drop anything that is _depended_ on by something else (a view or a constraint) *that you might be unaware of*. `CASCADE` automatically drops direct dependencies, but we do caution against blindly using it because, as mentioned above, it could drop something you didn't expect.

Columns included in an index though arguably aren't _depended_ on by the index -- the point of the index is to speed up reading the col, but if the col is dropped, that is no longer an issue -- so ideally we'd magically just fix the index, but that seems like a nice-to-have, and until then, restricting those seems fine too.

**Comment by vivekmenezes** [comment]
I agree with the sentiment that this is a nice to have. I worry that we're building out too much rather than fixing all the corner cases/performance issues for what we currently support. I'd much prefer us spend time adding more tests than adding in more complex functionality that is likely to be brittle. I like this issue from the perspective that it allows us to think about what is next on the horizon, as well as allows us to point a customer at an issue for their opinion, and can guide some of the refactoring cleanup efforts.

**Comment by a-robinson** [comment]
Yeah, I'm a little worried from a usability perspective as well. If our early features don't handle all the cases that our early users care about, then they may not stick around long enough for our later features to matter.

**Comment by spencerkimball** [comment]
@vivekmenezes re-assign this if necessary so it's on someone's plate for 1.0.

**Comment by vivekmenezes** [comment]
taken out of 1.0 milestone

**Comment by jordanlewis** [comment]
Closing this - it's pretty stale and I think consensus says we're not going to get to it soon. If a watcher on this issue cares particularly, I'd be open to reopening with a more concrete proposal or use case.
