### ISSUE TITLE
is non-http2 transport available?

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#10150]
Go 1.7.3 is out. It fixed a serious bug in Go's http2 implementation.

https://github.com/golang/go/issues/17071

However, http2 is still fairly under-tested, and I wouldn't be surprised if there were addition issues before it can be considered production worthy.

Does cockroachdb have the option to use a less bleeding edge transport?

**Comment by bdarnell** [comment]
No other transport is available, and we don't have any plans to change our transport layer (I think that at this point doing so would be more difficult than fixing whatever bugs may remain in the HTTP/2 implementation). Note that we use GRPC as a layer on top of HTTP/2, and GRPC uses some lower-level interfaces so I don't think it's vulnerable to the bug fixed in 1.7.3.
