### ISSUE TITLE
23.1 Acceptance testing: Index details page fails to load SQL Activity

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#101704]
Go to our 23.1 test cluster and navigate to the index details page. See the following error:

![image](https://user-images.githubusercontent.com/81193618/232652105-9af896f8-a777-4d18-bc2c-da6310fe82a8.png)

Other flows (e.g., Explain plan, Hot ranges) take users to the index details page (with the same error) so it's critical to get this resolved. 

FYI @maryliag 

Jira issue: CRDB-27094

**Comment by kevin-v-ngo** [comment]
This fails on other indexes as well. 

Question: Why didn't we catch this sooner? Do we have proper tests here?

**Comment by maryliag** [comment]
This failure is because the api reached the max size limit. The numbers of rows returned already had a limit of 20, so during tests this was never caught (presumably because the text query were small), but if there was a lot of info per statement, looks like it could still reach the max size limit of the api.  
It's a quick fix.
