### ISSUE TITLE
kvserver: expiration lease acquisition does not invalidate epoch

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#101836]
When acquiring a new lease, we only invalidate the outgoing leaseholder's epoch if both the old and new leases were epoch-based. However, this can lead to an outgoing leaseholder continuing to believe that its stale lease record is still valid on its next heartbeat, resulting in overlapping leases. We need to invalidate the lease for all non-cooperative lease acquisitions.

https://github.com/cockroachdb/cockroach/blob/186a85ce5d6a5485f4f9585d6412df11efefa52d/pkg/kv/kvserver/replica_range_lease.go#L435-L440

Jira issue: CRDB-27149

Epic CRDB-25199

**Comment by pavelkalinnikov** [comment]
Can this issue be actually the reason of failures we're seeing in #98698 and #100101?

See a bit of logs analysis: https://github.com/cockroachdb/cockroach/issues/100101#issuecomment-1516873311.

**Comment by erikgrinaker** [comment]
>Can this issue be actually the reason of failures we're seeing in https://github.com/cockroachdb/cockroach/issues/98698 and https://github.com/cockroachdb/cockroach/issues/100101?

It's possible there's some interaction here, but it isn't immediately obvious that it's this issue -- I think both nodes were heartbeating liveness (so the leases shouldn't have expired), and it isn't clear that we'd get into a situation where the old leaseholder thought it held onto an epoch lease while the new leaseholder saw either an old or a new expiration lease during the non-cooperative acquisition. I'll have to look into the specifics around here.

**Comment by erikgrinaker** [comment]
Going to keep this open until the backport in #101985 lands.

**Comment by pavelkalinnikov** [comment]
> it isn't clear that we'd get into a situation where the old leaseholder thought it held onto an epoch lease while the new leaseholder saw either an old or a new expiration lease during the non-cooperative acquisition

The lease transfer from n5 (the blackholed node) to n6 was cooperative (the "acquisition_type" is 1 in [lease history](https://github.com/cockroachdb/cockroach/issues/100101#issuecomment-1515232494)). On n5 it was epoch-based, on n6 it was expiration-based. If the code path in this issue is involved while transferring the lease, this could be it?

But you're saying that this code path is only for non-cooperative transfers?

**Comment by pavelkalinnikov** [comment]
Apparently this code path is reachable from [here](https://github.com/cockroachdb/cockroach/blob/ecc931becdeca6a5563f291489d5b1ed4389a2cb/pkg/kv/kvserver/replica_range_lease.go#L190), so this checks out.

**Comment by erikgrinaker** [comment]
This code path is hit for all lease requests, but only when the outgoing leaseholder is dead from the point of view of the one issuing the transfer.

And I guess it was in this case, because `blackhole-recv` will prevent n5 from getting gossip updates from other nodes, so all epoch leases will be expired from its point of view.

**Comment by pavelkalinnikov** [comment]
> If n5 issued the transfer it should see itself as live.

I think it does see itself as live, because it's an epoch-based lease, and network is blocked only on the way in. So it happily sends liveness pings, and never learns that this lease had been obsoleted. (because a. the in-traffic is blocked, b. it incorrectly transferred the lease without bumping the epoch)

**Comment by erikgrinaker** [comment]
Backports are in.
