### ISSUE TITLE
schemachanger: System.jobs table failed to persist the jobs from multiline schema update statement

### ISSUE THREAD

**Issue by lyang24** [cockroachdb/cockroach#102051]
**Describe the problem**
system.job table failed to persist the schema change job on multiline input schema updates.

**To Reproduce**

start demo from master
run in two seperate executions
`create table a(c int);`
`alter table a rename to b;`
we should see table b created and if we check system.jobs
```
demo@127.0.0.1:26257/demoapp/movr> SELECT status, job_type, description FROM crdb_internal.jobs where description like '% RENAME TO b%';                                                                                                                    
   status   |   job_type    |        description
------------+---------------+----------------------------
  succeeded | SCHEMA CHANGE | ALTER TABLE a RENAME TO b
```

now to reproduce the bug
we run following in the same line of the sql shell

`create table a(c int); alter table a rename to z;`

the table z is created but there are no schema update jobs in the system.jobs table.
```
demo@127.0.0.1:26257/demoapp/movr> SELECT status, job_type, description FROM crdb_internal.jobs where description like '% RENAME TO z%';                                                           
 status | job_type | description
---------+----------+--------------
(0 rows) 
```
**Expected behavior**
system.jobs should record the schema change event

**Environment:**
 - CockroachDB version current master
 - Server OS: all
 - Client app sql, postgres-client

**Additional context**
What was the impact?
compatibility issues to upgrade to the new version. one of the observations is all of this used to work on 22.1.0

Jira issue: CRDB-27243

**Comment by lyang24** [comment]
turning off `enable_implicit_transaction_for_batch_statements` solved the problem

**Comment by Xiang-Gu** [comment]
Thanks for filing this and I am glad to see you figured out a workaround :) I just want to add on an comment here that this behavior is expected in CRDB. The main reason that we didn't see the job entry when we put those two stmts in one line is because we have changed CRDB to treat such multiple-statement single line query as a transaction. In other words, it is equivalent to
```
BEGIN;
CREATE TABLE t (i INT);
ALTER TABLE t RENAME TO t2;
COMMIT
```
while issuing those two stmts separately, one line at a time, means each stmt is run as its separate transaction:
```
CREATE TABLE t (i INT);  -- a transaction with only this stmt
ALTER TABLE t RENAME TO t2;  -- another transaction with only this stmt
```

In the former case (both stmts are in the same transaction), the RENAME stmt would recognize this table is created within the same transaction and will *not* create a job because it knows no other transaction can see and use that table, so we don't need to go through some extra rigor as done in the job (e.g. maintaining the two-version invariant).

In the latter case (one stmt per stmt), RENAME is performed on a *public* table (which means other transaction might be using it). In this case, we do need to create a schema change job to complete this rename work for correctly maintaining some invariants.
