### ISSUE TITLE
storage: clean up `local range addressing` terminology

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#10226]
From https://github.com/cockroachdb/cockroach/pull/10173#issuecomment-256209085 (and discussed previously in that thread, but going to reviewable from the link gives the right posts):

We currently call keys for which `keys.Addr` is not the identity "range-local". This terminology is maximally confusing and we should come up with a better one (a few are discussed in the link above), and rename everything accordingly.

**Comment by a6802739** [comment]
@tschottdorf , maybe I could do this.

**Comment by tschottdorf** [comment]
Sounds good! The first step would be making suggestions for what the new terminology should be, the second one sending a PR (after consensus has been reached).

**Comment by a6802739** [comment]
@tschottdorf, how about change `local` to `internal` or `inside` For keys which will replicate to other node, for keys which will not replicate to other node, I recommend `self`.

**Comment by benesch** [comment]
I'm going to propose that we move this to the 2.1 milestone. "Range local" keys continue to bend my mind every time I see them.

I'll propose "metakey" as an alternative name. Range local keys are just keys about a key, no?

**Comment by tschottdorf** [comment]
Yeah, move to 2.1

"metakey" is super confusing because of the meta key ranges... 😄 

> Range local keys are just keys about a key, no?

Kinda, but not sure what this really means. I think of them as a second dimension of keys. In pseudo-go:

```
keyspace := map[string]struct{
  key string
  rangekeys map[string]string 
}

keyspace["a"].key                                     // roachpb.Key("a")
keyspace["a"].rangekeys["range-desc"] // keys.RangeDescriptorKey("a")

address("a.range-desc") == "a"
address("a") == "a"
```

I'm not sure that inspires a better terminology, but you could call it a wrapped key, a subkey, an anchoredkey, you name it.

**Comment by bdarnell** [comment]
> I think of them as a second dimension of keys.

Me too (or maybe "planes" to borrow a term from unicode). They're more "adjacent to" other keys than "about" them. I think this is a useful concept because it can generalize beyond the "local" and "global" planes we have now. Maybe we introduce a new "archive" plane for old MVCC versions to address our tombstone problem, for example.

We have ~4 kinds of keys today, depending on how you look at it:
- "Global" for regular data. This includes user table data, and also timeseries, node liveness, meta ranges, etc.
- "Range-local" for *addressable* keys that live adjacent to global keys. "Addressable" means they can be used as the target of RPCs sent through the DistSender. This includes range descriptors and transaction records, and QueueLastProcessedKey (I'm not sure why that last one needs to be addressable). 
- "RangeID-local" for *non-addressable* keys associated with a range. They can be replicated or not. These keys can't be referenced through the DistSender, but the replicated ones can be used normally at command evaluation time. This includes a lot of stuff, like the raft log, MVCCStats, and the abort span. 
- "Store-local" for non-addressable keys associated with a store. These are used for tracking things like the cluster ID and version/migration status. 

If I were starting from scratch, instead of having keys.Addr be the identity function for global keys and map local keys into the global keyspace, I'd add an explicit "data plane" marker to regular keys so that taking the address of a key resolves to a (addrKey, plane) tuple.
