### ISSUE TITLE
--alsologtostderr, --logtostderr flags are parsed incorrectly

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1022]
they default to false (in cockroach) but it looks like they're not passed to clog correctly.
unfortunately there's another bug (in clog) that prints anything logged from cockroach to stderr regardless (which I'll fix shortly) so you can't really see this right now.

To verify: Print the actual `flag` values for `logtostderr` and `alsologtostderr` (probably `stderrthreshold` is also affected) for those two commands. The output should be the same, but it's not.
`/cockroach start --logtostderr=false --alsologtostderr=false --stderrthreshold=2`
`/cockroach start # logs everything`

**Comment by bdarnell** [comment]
While we're at it I'd kind of like to get rid of the `--logtostderr` flag completely, and make it the default when `--log_dir` is not specified (instead of the current default, which is `--log_dir==os.TempDir()`). I think stderr makes more sense as a default (any real deployment will want to write to something like /var/log instead of /tmp), and it would let us remove silly hacks like https://github.com/cockroachdb/cockroach/blob/fbe348965ff7bab720c8adb472b4054f4ab6ca6d/sql/parser/parse_test.go#L14

**Comment by tschottdorf** [comment]
Good idea. I'm going to rework the flag parsing anyways, taking out the flags package from clog. Just as an FYI. But the change you mention and the issue here did be in our pflags coffee anyways.

**Comment by petermattis** [comment]
I'm pretty sure the logging flags are being parsed correctly. The behavior you're seeing is due to the hack in `main.go` to set `--alsologtostderr=true` if `--log_dir` is not specified. See https://github.com/cockroachdb/cockroach/blob/master/main.go#L32

I agree with Ben that we should change the logging defaults. If `--log_dir` is not specified we should log to stderr.
