### ISSUE TITLE
Error: table "xyz" is being added...while attempting INSERT in DDL file.

### ISSUE THREAD

**Issue by andymans** [cockroachdb/cockroach#102874]
**Describe the problem**

In latest version 22.2.8 I see the following error when executing an SQL ddl script that includes 'INSERT' statements alongside CREATE TABLE statements.

Error: table "xyz" is being added...

I would expect that the execution of an INSERT is dependent on the result of the CREATE being available; but for some reason there is no 'wait' and the INSERT attempts (unsuccessfully) to start.

This is odd - I have not noticed this in any previous version of cockroach - and I've been a user since pre-v1.0 days.

A workaround is obviously to shift all DML statements into their own script - but many users are quite likely to want to populate some data inline while creating tables - lookUp tables are a case in point.

Jira issue: CRDB-27707

**Comment by chengxiong-ruan** [comment]
Thanks for reporting the issue, what do you get if you run `show enable_implicit_transaction_for_batch_statements`? I hunch is that setting it to false would solve your problem.

**Comment by rafiss** [comment]
@andymans The behavior change that @chengxiong-ruan mentioned is described more here: https://www.cockroachlabs.com/docs/stable/transactions.html#batched-statements. The change was done so that we match PostgreSQL behavior.

I think that should explain the behavior, so I'll close this, but feel free to re-open it if you are still blocked.
