### ISSUE TITLE
sql: smoothen the experience of importing data from MySQL

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10291]
User chinglin on the Forum has reported the script chinglin is using to convert MySQL's SQL dump to something that CockroachDB can ingest:
https://forum.cockroachlabs.com/t/why-sql-shell-load-data-from-mysqldump-is-so-slow/327/7?u=knz
Namely:

```
  sed -i -e 's/`//g' \
      -e 's/int(.*)/int/' \
      -e 's/ENGINE=InnoDB //' \
      -e 's/DEFAULT CHARSET=utf8//' \
      -e 's/DEFAULT NULL//' \
      -e 's/^LOCK/--LOCK/' \
      -e 's/^UNLOCK/--UNLOCK/' \
      -e 's/COMMENT=.*$/;/' \
      -e 's/COMMENT\ .*$/,/' \
      -e 's/int NOT NULL AUTO_INCREMENT/SERIAL NOT NULL/' \
      -e 's/AUTO_INCREMENT=.* //' \
      -e 's/COLLATE utf8_unicode_ci//' \
      -e 's/COLLATE=utf8_unicode_ci//' \
      -e '/PRIMARY/!s/KEY/index/' \
      -e 's/tinyint/SMALLINT/' \
      -e 's/int NOT NULL DEFAULT \x270\x27/int NOT NULL DEFAULT 0/' \
      -e 's/USING BTREE//' \
      -e 's/\x27\\\x27\x27/e\x27\\x27\x27/g' sql.file
```

Should we want to accompany users with taking data from MySQL we could 1) ship such a script in the CockroachDB repo (following up to #10261) and 2) fold some of MySQL's syntax into what CockroachDB supports, when that makes sense and/or is neutral to semantics. A couple examples:
- ignore COMMENT and LOCK directives
- ignore DEFAULT NULL
- map AUTO_INCREMENT to `DEFAULT unique_int()`
- alias PRIMARY KEY to INDEX in CREATE TABLE

etc

**Comment by bdarnell** [comment]
See also [pgloader](http://pgloader.io/howto/mysql.html) which can import data from mysql (and other sources) into postgresql, with various rules and options for massaging the schema. When I first looked at it, we couldn't use it because we didn't support the COPY protocol. Now that we do, we should take another look and see if it would be a good fit for importing into cockroachdb (or could be forked and adapted to do so)

**Comment by dianasaur323** [comment]
this conversation seems potentially relevant to @mjibson @dt @paperstreet

**Comment by whatvn** [comment]
unsigned int is not supported too.
since mysql allows a value with numeric/decimal type can be insert as string, it then convert to correct type, but cockroachdb does not, example: 

`sql
amount_paid decimal(20,6) NOT NULL DEFAULT '0.000000'
`
must be modified to 

`sql
amount_paid decimal(20,6) NOT NULL DEFAULT 0.000000,
`
I cannot find a good way to import mysqldump file directly to cockroachdb without modifying dump file manually.

**Comment by damienhollis** [comment]
I just tried pgloader to migrate from mysql to cockroachdb.  It fails very early on (before even starting the migrate) with the following error:
```
ERROR Database error XX000: syntax error at or near ")"
select word
                   from pg_get_keywords()
                                        ^
QUERY: select word
                   from pg_get_keywords()
                  where catcode IN ('R', 'T')
```

So at this stage is does not look like pgloader is a viable option.  Do you plan to spend sometime building out support for pgloader or another migration tool?

**Comment by damienhollis** [comment]
Looking over the lisp code (a language I have very limited knowledge of), the pg_get_keywords call is used to get the reserved keywords and, as far as I can tell, there are no options to avoid this call.  There is code to default the list for Amazon Redshift (presumably AWS does not allow access to that function and throws some kind of access denied exception).

**Comment by dianasaur323** [comment]
@damienhollis thanks for looking into pgloader for us. Yes, we would love to make it easier for people to migrate to CockroachDB, and that is an item open on the roadmap for 1.2. I'm currently actively scoping that out, and should have more info for you soon. If you have suggestions, would love to field them here.

**Comment by damienhollis** [comment]
@dianasaur323 The way pgloader works looks quite good.  In our case we can generate the schema using hibernate, so we just need to be able to load the data.

**Comment by dianasaur323** [comment]
@damienhollis Great to hear! I might try that for myself at some point :)

**Comment by mjibson** [comment]
This has been pretty smoothened. Closing.
