### ISSUE TITLE
Transaction query unavailable error on Transactions page

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#103618]
**Describe the problem**

In the Transactions column, instead of a Transaction Fingerprint, `Transaction query_` is displayed with the tip `Transaction query unavailable`.  When `Transaction query_` is clicked, on the Transaction Details page, the black query box is blank. See attached images.

<img width="1154" alt="Screenshot 2023-05-18 at 2 08 18 PM" src="https://github.com/cockroachdb/cockroach/assets/58752716/60593551-7ee2-43b2-9081-b33d321bafa6">
<img width="1255" alt="Screenshot 2023-05-18 at 2 20 27 PM" src="https://github.com/cockroachdb/cockroach/assets/58752716/af775ee1-2b07-4a26-b591-8640e132de0c">

**To Reproduce**
I was not able to reproduce this issue from scratch, but it can be reproduced using the test cockroach-data directory in the zip file.

1. unzip cockroach-data-bug.zip (I will attach to the internal JIRA issue) which contains movr workload data in same directory as cockroach 23.1.1 binary
2. run a single-node cluster with
```
./cockroach start-single-node --insecure --listen-addr=localhost:36257 --sql-addr=localhost:26257 --http-addr=localhost:8080 --background
```
3. open DB Console in browser with url: http://localhost:8080/#/overview/list
4. Click on **SQL Activity**, **Transactions** tab with Time Range "Past 6 Hours"

**Expected behavior**
Transactions column displays Transaction Fingerprint. Transaction detail page displays Transaction Fingerprint.

**Environment:**
 - CockroachDB version: v23.1.1
 - Server OS: Mac

Jira issue: CRDB-28098

**Comment by florence-crl** [comment]
In repro step #4 depending on when you unzip the `cockroach-data`, you may have to select an older Time Range rather than "Past 6 Hours".

**Comment by xinhaoz** [comment]
This happens when we decide to service the request from `system.transaction_activity` The issue was that the stmtFingerprints field which we use to construct the txn query was not present in the payload when we queried from transaction_activity. It seems the UPSERT statement is using the `merge_stats_metadata` internal function which only applies to statement stats. The metadata column in the `transaction_activity` table gets overwritten with the empty stmt metadata object and does not contain relevant txn information.

Since the info in this table gets updated periodically I believe we should be fine just fixing this by removing the aggregation and not have to worry about fixing the existing data.
