### ISSUE TITLE
roachtest: artifacts are not published immediately after failure

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#103778]
It was observed recently (internal thread [1]) that the publishing of artifacts immediately after failure doesn't seem to be working:

![image](https://github.com/cockroachdb/cockroach/assets/103441181/ff780ace-8dd4-4e49-bbbe-ad640568f201)

`roachtest` attempts to publish the artifacts immediately after failure so that they are available in the TC UI before the entire build finishes [2]. While the path in the logs above does look right, the publish is still failing for some reason. We need to investigate the reason for the failure and fix it.

[1] https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1684840081950479
[2] https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/pkg/cmd/roachtest/test_runner.go#L933-L941

Jira issue: CRDB-28197

**Comment by smg260** [comment]
The failure message is the result of the teamcity service message `##teamcity[publishArtifacts…` and happens on all local roachtests.

It looks like its being caused because we don’t pass a `--artifacts-literal` flag in [local_roachtest_impl.sh](https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/build/teamcity/cockroach/ci/tests/local_roachtest_impl.sh) which we do for [roachtest_nightly_impl.sh](https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh#L4)

**Comment by srosenberg** [comment]
> It looks like its being caused because we don’t pass a `--artifacts-literal` flag in [local_roachtest_impl.sh](https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/build/teamcity/cockroach/ci/tests/local_roachtest_impl.sh) which we do for [roachtest_nightly_impl.sh](https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh#L4)

Right. Both are executed inside bazel's docker container (via `run_bazel`) which effectively has this volume mapping,

```
--volume $root/artifacts:/artifacts"
``` 

Inside roachtest, `literalArtifactsDir` is the path on the host, i.e., `$root/artifacts`, and `artifactsDir` is inside the container. Technically, we could add some introspection code to discover `literalArtifactsDir` without having to explicitly pass it. It would eliminate the confounding factor, but I am not sure it's worthwhile, considering this is one of those things you fix and forget, then occasionally scratch your head for a few mins to remember why it's there in the first place :)
