### ISSUE TITLE
server: admin UI communicates on server's default hostname only

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10374]
### Steps to repro
1. Create node certificates not including server's hostname
2. Start node using `--advertise-host=<node internal IP address>`
3. Access admin UI.

### Expected Results
Admin UI loads data from cluster.

### Actual Result
Admin UI does not load data from cluster because it attempts to communicate using the server's `hostname` value as the host name.

**Comment by a-robinson** [comment]
So I'm not totally sure what path it's bubbling up from, but we have a habit of defaulting to using the hostname for things if the `--host` flag isn't specified:

https://github.com/cockroachdb/cockroach/blob/776c68838bb47ae32acd15bbb67de279f78b585a/pkg/server/server.go#L846
https://github.com/cockroachdb/cockroach/blob/776c68838bb47ae32acd15bbb67de279f78b585a/pkg/gossip/resolver/resolver.go#L65

We'll either need to carefully rethink that, bubble up `--advertise-host` through the relevant path instead, recommend that users always specify `--host` when setting up a secure cluster, or recommend that users put the hostname into their certs.

**Comment by bdarnell** [comment]
Even `--advertise-host` is not quite correct; that's an internal hostname that the nodes use to talk to each other, but the admin may only have access to the cluster via a load balancer on a different name. But I'm not sure that's the issue here. It looks like it may be the browser's security paranoia about the self-signed certificate. It seems to be using different rules for loading assets even after you've clicked through the warning and accepted the cert. If that's the case I'm not sure what we can do besides recommending that certs be issued for all the names that a node might be accessed under.

**Comment by glycerine** [comment]
@sploiselle you do have finer control using  the`--http-host` flag. Does that provide a workaround?

**Comment by mrtracy** [comment]
This is not a UI issue, it is a server issue.  Retitled, assigning to @petermattis for assignment to correct owner.

**Comment by a-robinson** [comment]
Pinging this because [a user on our forums ran into this recently](https://forum.cockroachlabs.com/t/accessing-admin-ui-on-docker-swarm/770), but not bumping the priority until hearing back on whether they could work around it.
