### ISSUE TITLE
Statement Page with Database filter returns no results even when there are statements that exist for the filtered database

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#103895]
**Describe the problem**

The SQL Activity, Statements page, allows the user to Filter by database. However, when a database is selected, no results are returned even though statements exist for the selected database.

**To Reproduce**

1. Start a 23.1.1 single-node local cluster
2. Run statements in 3 databases (defaultdb, movr, kwikshoppr)
3. In the DB Console, navigate to the SQL Activity, Statements page with a time interval that contains statements from multiple databases.
4. In the Columns picker, add the database column to show that there are statement from multiple databases.

<img width="1517" alt="Screenshot 2023-05-25 at 11 41 15 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/648edd40-a4c9-4357-aeb0-ebcc914f403c">

5. In the Filter picker, select `movr` and click Apply. The message `No SQL statements in the selected time interval` is displayed.

<img width="1652" alt="Screenshot 2023-05-25 at 11 43 59 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/be9bc149-265a-4bd7-a486-35d0de83c564">

**Expected behavior**
The statements run in the filtered database are displayed.

**Environment:**
 - CockroachDB version: v23.1.1
 - Server OS: Mac arm
 - Client app: DB Console

Jira issue: CRDB-28247

**Comment by maryliag** [comment]
Already fixed on https://github.com/cockroachdb/cockroach/pull/101268
Is available on 23.1.2

**Comment by florence-crl** [comment]
I tested the above scenario with the same cluster upgraded to 23.1.2, I still get  the message `No SQL statements in the selected time interval` displayed even when I select multiple databases.

<img width="1649" alt="Screenshot 2023-05-30 at 9 23 57 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/73ec0d9a-ab25-4e7e-af99-5f9f93792e39">

**Comment by florence-crl** [comment]
I tested on a cluster created with 23.1.2 and the filter works:
<img width="1469" alt="Screenshot 2023-05-30 at 10 17 28 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/eafeda3f-91a4-4e7f-b091-8fc3edc0d9c6">

**Comment by xinhaoz** [comment]
Thank you for filing this! This does indeed still occur on master when we service the query using `system.statement_activity`.
The `statement_activity` table stores the metadata in its aggregated form, thus the db field is already a string array. When we perform an additional `crdb_internal.merge_stats_metadata` (which is required for the system.statement_statistics` table), it results in a 2D array which the frontend doesn't parse correctly.

The desired solution here is probably fixing the server side code to not perform the aggregation on the activity table rather than addressing this on the frontend, as other fields could be affected too.
