### ISSUE TITLE
TestBackupMixedVersionElements_base_drop_column_basic/backup/restore flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#103896]
See  bors CI flake https://teamcity.cockroachdb.com/viewLog.html?buildId=10245851&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-28248

**Comment by rafiss** [comment]
Failed here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10516718?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by herkolategan** [comment]
@rafiss Pardon the messiness above, the skip [1] was not as trivial as I thought since I missed the fact that it is a generated test initially. I've added the ability to skip it, although it might end up being a bit broader than required. I'll let the team decide on the approval of the skip:

[1] https://github.com/cockroachdb/cockroach/pull/104864

**Comment by rafiss** [comment]
unskipped in https://github.com/cockroachdb/cockroach/pull/105222
