### ISSUE TITLE
sql: hash join for non-distsql queries

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10397]
For parity with the distributed SQL world, we should have a non-distributed version of the hash join.

@knz: any other details to add here about motivations, etc.?

**Comment by irfansharif** [comment]
I recall reading something about starting off with only `USING` and `NATURAL` predicates and keeping the current nested-loop implementation for `ON`s due to hairy predicate extraction. Also there was further discussion to repurpose @RaduBerinde's work for index joins. 
Let's collate all the discussion here before starting off with anything.

**Comment by knz** [comment]
Yes starting with USING and NATURAL is the best entry point.

Predicate extraction is actually not that complicated, I think most of the code is already available via the `splitFilter` function that we use for the index join.

**Comment by irfansharif** [comment]
Closing this now, relevant PR: #10618.
