### ISSUE TITLE
sql: update upgrade unit tests to bootstrap from 23.1 (or 22.2)

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#103956]
Currently, all of our upgrade unit tests (mostly logic tests outside of the `cockroach-go` config) bootstrap the cluster at `V22_2`. Since the `release-23.1` branch has been cut, master should now be considered 23.2 work (#103551). As such, we should be writing our upgrade tests to bootstrap the cluster from `V23_1`.

This is made more complex in this release, as we intend to keep `BinaryMinSupportedVersionKey` at `V22_2` in `release-23.2` [1]. This means that, ideally, we should start testing our upgrades both from `V22_2` and from `V23_1`.

This work will involve creating initial_values for the 23.1 release: see [2].

Assigning @cockroachdb/sql-foundations, as a lot of our upgrade tests are logic tests. Migration and tenant upgrade tests are also among tests that should be updated. Corrresponding teams are free to create separate issues to handle those changes.

[1] https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/2762309867/Version+Skipping+to+Enable+Long-Term+Support+LTS
[2] https://github.com/cockroachdb/cockroach/blob/bc6b0566d840162736b141825e5016294313a03b/pkg/sql/catalog/bootstrap/initial_values.go#L76-L83

Jira issue: CRDB-28269

**Comment by postamar** [comment]
Ideally this should be straightforward TDD so that someone who isn't myself can update this straightforwardly: update all the config definitions for mixed-version tests and see what breaks and fix it. 

In practice, some things are missing in the `bootstrap` package tests for that to be possible. I should add a test that checks that each supported major version has hardcoded initial values, instead of only the latest version. I'll file a PR which should, in turn, make it possible for anyone to address this present issue.

**Comment by postamar** [comment]
I'll unassign myself at this point, now that the initial values for 23.1 have been added. The remaining work in the scope of this issue and this team is adding and/or updating the following to involve the 23.1 release somehow:

- [ ] mixed-version logic test configs
- [ ] tenant creation/upgrade tests
- [ ] roachtests involving mixed-version clusters that the team owns
- [ ] declarative schema changer corpus tests

Feel free to edit this list accordingly

**Comment by rafiss** [comment]
@fqazi can you work on the corpus tests and mixed version schema change test? i will work on the mixed version logic tests.

**Comment by rafiss** [comment]
@postamar I still find myself a little bit lost. Do you know what it would take to unskip the `mixed_version_can_login` test?

When I try, it fails on this query due to getting the wrong results.
```
SELECT
          k,
          is_present_in,
          CASE
            WHEN k = '/Table/6/1/"version"/0'
            THEN '<volatile>' -- this value is volatile due to the "lastUpdated" column
            ELSE v
          END AS v
        FROM bootstrapped_tenant_data
        ORDER BY 1, 2
```

Do the expected results just need to be rewritten? (Aside: that test probably should be in a different file, since it's testing something much lower level than being able to login.)
