### ISSUE TITLE
stability: fix command queue for proposer-evaluated KV

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#10413]
See #10084. With commands evaluated in parallel before being proposed to Raft, it becomes (more) important that the command queue tracks all keys read and written during command evaluation. A first exploration is in #10084; the command queue was already split to track user and internal keys separately.

Ideally a better mechanism for getting a list of spans which need to be locked for a certain command than a brittle ad-hoc one (#10084) would be introduced, but initially it seems sufficient to turn #10084 into a functioning solution. This might necessitate special-casing some frequent keys to avoid bottlenecking operations; these aspects are discussed in detail in #10084.

Assigning @petermattis for proper reassignment.

**Comment by bdarnell** [comment]
With #14524, the command queue now tracks nearly all keys accessed during a request. The exceptions are some of the special cases called out in the description of PR #10084 (which I'll quote here because github often serves errors trying to load that old and large thread):

- Every command needs to read FrozenStatus, RangeLastGCKey and writes
  MVCCStats. Unless we are smart about it, that already completely kills off
  any proposal parallelism. We will have to be smart about it because that's
  pretty bad. Especially the stats update is interesting because that is
  both  frequent and a write operation. The obvious solution here is to make use
  of  the commutativity of stats delta updates (though `ContainsEstimates` needs
  to  be taken into account conservatively).
- Every transaction reads its AbortCacheKey and reads or writes its
  transaction  record (see discussion in #6290 on why the latter makes sense).

FrozenStatus, RangeLastGCKey, and the abort cache have something in common: the only affect they have on the command is whether it runs at all. It either applies as it did when it was evaluated or it fails. Because of this, I believe it is safe to process them entirely downstream of raft without blocking in the command queue (similar to the way we don't block everything on the applied index keys). The downside of doing this is simply that there is more logic downstream of raft which is difficult to change. Is it worth it? For RangeLastGCKey (and FrozenStatus, if it doesn't get removed completely), I think the answer is yes. For the abort cache (which uses per-txn keys, and is more subtle and therefore more likely to change), probably not. 

By the same logic, most commands no longer need to read the range descriptor (they only need it to see if a concurrent split has resulted in them becoming out of bounds).

**Comment by dianasaur323** [comment]
@bdarnell given that the initial issue has been addressed, and it seems like there is just remaining work on corner cases (FrozenStatus and RangeLastGCKey), I've updated the issue to be more specific regarding the actual action item attached to the issue. Please feel free to change back if you'd like.

**Comment by bdarnell** [comment]
I think the title is still appropriate, especially since #14434 has revealed that the command queue is not yet fully working for propEvalKV.
