### ISSUE TITLE
stability: switch to proposer-evaluted KV

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#10431]
Once the [remaining proposer-evaluated KV issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+label%3Aproposer-evaluated-kv) are addressed, we should make a timely switch to proposer-evaluated KV as default (and only) mode of operation. Other than the issues, prerequisites here are:

- [ ] reliably passing the Jepsen test suite and all others we have at that point in time
- [ ] shows no performance regressions (we expect improvements in most tests, unless they are  `DeleteRange`-heavy)
- [ ] check in on contention tests as well (those should definitely improve, anything else would be a surprise)
- [ ] stabilized the `proposer_kv` proto (i.e. the fat trimmed, needless dependencies eliminated, final tag numbers assigned)
- [ ] a migration story in place. We will be using the same on-the-wire proto, so a stop-the-world upgrade with `ClusterFreeze` should be enough, but this should definitely be exercised by tests.

**Comment by bdarnell** [comment]
For the migration story: Flipping the switch to turn on proposer-evaluated KV is fairly safe: it would require a stop-the-world upgrade if you're coming from a version that is too old, but as long as the downstream-of-raft propEvalKV code hasn't changed since the version that you're updating from, you could even do it as a rolling upgrade. (there hasn't been any change to this code in a while, although I'm planning a change this week)

The second step is the tricky one: we want to be able to remove the non-prop-eval mode. This requires freeze-cluster to be completely bulletproof, but I think that at this point it's not worth working out the kinks in the freeze-cluster implementation. We should just document that clusters must run the version that enables propEvalKV for a while (an hour? It shouldn't take long for the last non-prop-eval commands to flush through a healthy system, although there is no limit of how long it could take if it is unhealthy) before upgrading to the version that requires it.
