### ISSUE TITLE
catalog: update RunPostDeserializationChanges to fix common cases of orphaned jobs

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#104425]
We have seen more examples of corruption caused by https://github.com/cockroachdb/cockroach/issues/93010 (bug where the planner would autocommit incorrectly, without cleaning up schema change jobs).

So far we have been resolving them using manual descriptor surgery. We should be able to add an automatic repair step into RunPostDeserializationChanges so that anytime a descriptor is read, it will attempt to repair the problem if it is able to. This can be best-effort, since there are likely some cases that we can't fix automatically.

Jira issue: CRDB-28522

Epic CRDB-28665

**Comment by rafiss** [comment]
@postamar would you be able to take a look at this? @rimadeodhar and I are wondering if this approach might be an OK stopgap, since it could be a bit too risky to modify any 22.2 upgrade jobs. If we just limit this to RunPostDeserializationChanges, it should be safe to backport, is that right?

**Comment by postamar** [comment]
Sure. Could you cross-reference a support issue featuring said surgery? I'm not finding anything.

**Comment by rafiss** [comment]
The items labeled with "autocommit planner" in this spreadsheet should be an exhaustive list. https://docs.google.com/spreadsheets/d/1ICVjdVgixZOUR1CeS49BImLdQTA0szHfnC6UqB1Xi7A/edit#gid=0

**Comment by postamar** [comment]
Thanks for granting me access to that spreadsheet. I had a look at the issues and the corruptions we'd like to auto-repair all involve references to either jobs or other descriptors, which `RunPostDeserializationChanges` can't de-reference. This is by design. We'll have to think of something else.

**Comment by postamar** [comment]
Here's where I'm leaning towards. Let's add a builtin `crdb_internal.strip_descriptor_backrefs(descriptor BYTES, desc_ids INT[], non_terminal_job_ids INT[])` which takes a serialized descriptor protobuf to work on, a set of valid descriptor IDs and a set of valid job IDs, and returns a serialized protobuf of the descriptor minus any back-references to IDs which don't appear in either allow-list. This builtin would effectively delegate down to `catalog` functions and methods (perhaps in `descbuilder` idk).

These sets of IDs can be obtained quite easily with 
`SELECT id FROM system.descriptor` and `SELECT id FROM system.jobs WHERE status IN ('failed', 'succeeded', 'canceled', 'revert-failed')`. Diagnosis consists of running that builtin on `system.descriptor` and checking whether the output is always the same as the input. If not, dangling back-refs are present. Repair consists in feeding the output to `unsafe_upsert_descriptor`.

For diagnosing and repairing dangling entries in the namespace table we don't need a built a builtin at all.

**Comment by postamar** [comment]
^^ I feel the above PR is a step in the right direction. Once this construct is in place (and backported) we can think about how to use it. The general idea is to repair this kind of descriptor corruption automatically. There are several things that make this not straightforward:
1. This new builtin requires a full table scan of system.descriptor and system.jobs to collect the allow-lists of valid IDs. If we're only using it for diagnostics then we can get away with using AOST queries but if any repair is attempted then a full table scan is inevitable. In my opinion this rules out performing this as part as a recurring scheduled job, which I also find distasteful for other reasons I'll get into in the next point.
2. For on-prem customers in particular, I prefer having all repair queries run by the initiative of the cluster operator, rather than trying to be clever and running them under their noses. Besides, I think there's a greater need here for some more programmatic way to run diagnostic and repair queries as published in technical advisories. There's got to be a better way rather than copy pasting text into a SQL prompt.
3. We now have a cluster upgrade precondition check which queries the invalid_objects vtable. We can't do the repair as part of the cluster upgrade because any potential repair will be screened by that precondition check. The check verifies more than just dangling back-references so I think it's pretty important that it stays in place.

This makes me think that a nice entry point for cluster repair would be a documented builtin which triggers a new type of non-recurring job, let's call it a "repair job". The repair job can be parameterized to run certain classes of repair queries by passing some kind of allow-list as an argument to the builtin. When the job runs it gently performs the repairs until there's nothing left to repair, or it runs into an error in which case it gives up.

A nice complement to that would be a new virtual table which when queried performs all known diagnostics queries (such as published in TAs, but also checking for dangling back-references) and publishes records keyed by repair identifier (to be fed to the repair job builtin mentioned above) and where the value could be some summary of the problems found.

Thoughts?

**Comment by postamar** [comment]
I think I've come up with something decent in https://github.com/cockroachdb/cockroach/pull/105832
Cluster upgrades trigger the auto-repair during the precondition check. It's perhaps slightly icky for the precondition check to have side-effects but this is the cleanest way I can think of to backport something into 23.1 that doesn't require manual descriptor repair.
