### ISSUE TITLE
db console: high watermark missing from jobs table

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#104619]
The high watermark information is missing in the db console. Even when clicking the column in the column dropdown, it does not appear. This information is critical to changefeed users. 

https://github.com/cockroachdb/cockroach/assets/13264141/9c98bed5-1fd6-442f-b68c-7ae9849ad41e

To reproduce, log into the telemetry cluster's db console and go to the jobs table.

Alternatively, we could nix the high watermark column and include that information in the status column instead.

Jira issue: CRDB-28638

**Comment by maryliag** [comment]
the column shows once the Apply is clicked: https://www.loom.com/share/344aba8d2aa6465d8299d4a8a1f09d37
this issue is about making sure the column selector is not cut so the Apply always show. On the SQL Activity page we had to add a min height for the table area to solve this issue. A similar behaviour needs to be added to this page.

**Comment by amruss** [comment]
Thank you!
