### ISSUE TITLE
ui: percentage of runtime not populating correctly

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#104605]
**Describe the problem**

Service latency values are populated but do not seem to be surfacing correctly in the console's SQL Activity page, in the % of all runtime column. See [support issue](https://github.com/cockroachlabs/support/issues/2348) for context.
![image](https://github.com/cockroachdb/cockroach/assets/15315413/2596db3e-a4c5-4520-a907-b94fe399e082)

Items that need to be addressed for this issue:
- [x] Add % of All Runtime as one of the options on the top activity tables
- [x] Add more precision to small percentages
- [x] Clarify when the total include just the top vs all data OR always use all data to get the total

Jira issue: CRDB-28625

**Comment by maryliag** [comment]
More details:
Is showing 0, but only because we're fixing to just 1 decimal point, when changing to something like 10 we can see the actual values, such as:
<img width="381" alt="Screenshot 2023-06-15 at 5 13 47 PM" src="https://github.com/cockroachdb/cockroach/assets/1017486/a7b690d4-ce7b-447c-bbab-fe3d27650048">

To repro, run just a few queries on the database and let a bunch of internal queries get executed.
But this issue has a few other parts:
- When selecting an option that *is* on the top activity table, the total workload will be small, because there are less rows and those don't include internal statements, so when the % is calculated, is a small value on top of the total that is also small, so you can see the high percentages on the UI
- When selecting an option that is *not* on the top activity table, it will go to the persisted table that includes internal statements, so the total workload value will be big, and consequently the % per statement will be small. This was the case for this issue, where the majority of statements were internal, so the % value per fingerprint was very small.

A few suggestions:
- Have a more fluid value, where if the value is >1%, continue to use one decimal point, but if starts with 0, use the amount necessary until you reach a non-zero (but show just 0 if the value is indeed 0)., so you would have `10.4%`, `0.00004%` and `0%` 
- Clarify when the percentage is calculated including only the top vs all (we might need some design for this @dongniwang )

This behaviour can be seen here (top values show percentage and the "more" options, show 0%):
https://www.loom.com/share/2835d7d28f5f4d549e1baa557261b647

The only columns that is not working as expected is the `%of All Runtime`, and that is because is missing from the list of `isSortOptionOnActivityTable` here: https://github.com/cockroachdb/cockroach/blob/3ce3629b3a1ae179eb56b9c0d66975c178aeb50d/pkg/server/combined_statement_stats.go#L375
a new line should be added there with `serverpb.StatsSortOptions_PCT_RUNTIME `

**Comment by maryliag** [comment]
I updated the description to list the 3 items that need to be addressed. Fixes for the first 2 are already up, just the third one that needs to be look into
