### ISSUE TITLE
acceptance: Add traffic to all rebalancing tests

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#10465]
During all the nightly rebalancing tests, the nodes come up, load data, and then rebalance the replicas in the absence of any SQL traffic. We should add SQL traffic into the mix and verify that SQL traffic performance is not negatively affected by rebalancing.

**Comment by cuongdo** [comment]
In the past, adding load meant that rebalancing never quite finished. That was partly due to our inability to rebalance away from the leaseholde. If the leaseholder had more replicas than the other nodes, that would always remain true, because under load, the leaseholder tends to hang on to its leases.

That said, it's worth trying out and seeing what happens.

**Comment by cuongdo** [comment]
Also see #8190

**Comment by vivekmenezes** [comment]
Can you explain why the leaseholder tends to give up its leases in the absence of traffic?

**Comment by tschottdorf** [comment]
Leases aren't renewed when there is no traffic, so they won't get in the way as much.
