### ISSUE TITLE
admission: clearrange test induces IO overload starving out foreground traffic

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#104862]
**Is your feature request related to a problem? Please describe.**

I see the [following](https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&var-cluster=irfansharif-clearrange-flowcontrol&var-instances=All&from=1686464091088&to=1686467778347), running:
```
roachtest run 'clearrange/checks=true/rangeTs=false' --cockroach ~/cockroach-fixed --cluster irfansharif-clearrange-flowcontrol --debug-always --port 8081
```

<img width="1669" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/fd655875-689f-4617-9c03-7edbfea890d2">
<br> <br>   
This shouldn't be as impactful as it is. Few notes from internal discussions:

- [Oleg] When we drop tables/indices we should have a range tombstone dropped over the full range of keys. It would also add a gc hint onto range state indicating that this range is no more. Subsequently, when gc time is reached, once gc will hit first range with such hint it will try to find all ranges with the hint and enqueue them with high priority meaning, there's an alternative pacing delay for them. When doing GC, if range has hint and all data is covered with range tombstone it will issue clear range pebble op to remove all data. The reason for increased pace (smaller delay) for hinted ranges is to reduce compaction costs. Tests shown that if we have usual pacing, gc of deleted tables could take long time while pebble is constantly compacting because of cleared ranges. And if we issue clear range requests faster, then compaction per sec stays the same, but time compactions are run is significantly reduced.
- [Sumeer] It’s possible that compactions in pebble are trying to prioritize range dels. So L0 is not being compacted, and we don’t have L0 tokens to grant to AC work queues.

Jira issue: CRDB-28757

**Comment by bananabrick** [comment]
Ran the experiment once
<img width="856" alt="Screenshot 2023-06-19 at 6 21 13 PM" src="https://github.com/cockroachdb/cockroach/assets/12527258/10ffc2ae-10e2-492d-a91d-8c6d544dbbc0">

The drop in throughput from ~21:42 to ~21:50 seems to coincide with a bunch of merges being completed at once. Not sure what is meant by a merge here. Will investigate.
```
21:22:51 clearrange.go:201: test worker status: waiting for ~1868 merges to complete (and for at least 45m0s to pass)
21:22:51 clearrange.go:218: test worker status: waiting for ~1868 merges to complete (and for at least -44m59.464220006s to pass)
21:27:51 clearrange.go:218: test worker status: waiting for ~1868 merges to complete (and for at least -39m59.454364012s to pass)
21:32:51 clearrange.go:218: test worker status: waiting for ~1824 merges to complete (and for at least -34m59.467065155s to pass)
21:37:51 clearrange.go:218: test worker status: waiting for ~1785 merges to complete (and for at least -29m59.473854082s to pass)
21:42:52 clearrange.go:218: test worker status: waiting for ~1766 merges to complete (and for at least -24m59.432180765s to pass)
21:47:51 clearrange.go:218: test worker status: waiting for ~367 merges to complete (and for at least -19m59.497035832s to pass)
21:52:51 clearrange.go:218: test worker status: waiting for ~270 merges to complete (and for at least -14m59.482402285s to pass)
21:57:52 clearrange.go:218: test worker status: waiting for ~114 merges to complete (and for at least -9m59.462233738s to pass)
```

**Comment by bananabrick** [comment]
Flushing some additional details after discussion on [slack](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1687295629743389).

There's 2 problems here:
1. We're not prioritizing L0 compactions even though L0 is inverted because of the L5->L6 and L6->L6 compactions. Note that some of the compactions are wasted because we aren't able to delete data because of open LSM snapshots.
2. We're making L0 sublevel count worse than it should be because of tiny flushes. Tiny flushes might be happening due to ingestions overlapping with the memtable.

**Comment by bananabrick** [comment]
I'm going to add this to storage investigations too, since part of the fix is in storage land.

**Comment by jbowens** [comment]
Have we considered throttling range merges? I suspect we would see a different story if ranges weren't merged so aggressively in parallel to GC. It would avoid the small flushes + overlapping ingests that quickly increase read-amp.

Might be worth running the test with the merge queue disabled just to observe what impact there is on the workload.

**Comment by jbowens** [comment]
> Might be worth running the test with the merge queue disabled just to observe what impact there is on the workload.

I tried this here: https://grafana.testeng.crdb.io/d/StorageAvKxELVz/storage?orgId=1&var-cluster=jackson-1691678632-01-n10cpu16&var-instances=All&from=1691678892879&to=1691684075941

The workload was still affected:
<img width="987" alt="Screenshot 2023-08-10 at 12 17 56 PM" src="https://github.com/cockroachdb/cockroach/assets/867352/fcca32f2-4b6e-44d5-81a3-c9b610ea7dd7">

Although interestingly read-amplification stayed reasonable, with one node reaching 23:
<img width="996" alt="Screenshot 2023-08-10 at 12 18 37 PM" src="https://github.com/cockroachdb/cockroach/assets/867352/00fefa07-edbe-4283-a3dc-6b039ed9bf50">

Comparing to a [recent CI run](https://grafana.testeng.crdb.io/d/StorageAvKxELVz/storage?orgId=1&from=1691238146523&to=1691242736948&var-cluster=teamcity-11200326-1691214430-60-n10cpu16), disabling merges reduced the magnitude and duration of the impact to foreground throughput, but didn't eliminate it. The run with concurrent range merges shows substantially higher read amplification.

Is the impact to the foreground traffic driven by higher IO read latencies because compactions are saturating the disk, not because we're choosing the wrong compactions?

**Comment by bananabrick** [comment]
Done in https://github.com/cockroachdb/pebble/pull/2917
