### ISSUE TITLE
storage: Remove StoreTestingKnobs.TestingEvalFilter

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#10493]
From `storagebase/base.go`, posted here for visibility. The below TODO should be addresses rather sooner than later (since folks will need to write new tests and shouldn't have to be confused by half-baked refactorings):

```go
// ReplicaCommandFilter may be used in tests through the StorageTestingMocker to
// intercept the handling of commands and artificially generate errors. Return
// nil to continue with regular processing or non-nil to terminate processing
// with the returned error. Note that in a multi-replica test this filter will
// be run once for each replica and must produce consistent results each time.
//
// TODO(tschottdorf): clean this up. Tests which use this all need to be
// refactored to use explicitly a proposal-intercepting filter (not written
// yet, but it's basically this one here when proposer-evaluated KV is on) or
// a ReplicaApplyFilter (see below).
type ReplicaCommandFilter func(args FilterArgs) *roachpb.Error

// A ReplicaApplyFilter can be used in testing to influence the error returned
// from proposals after they apply.
type ReplicaApplyFilter func(args ApplyFilterArgs) *roachpb.Error

// ReplicaResponseFilter is used in unittests to modify the outbound
// response returned to a waiting client after a replica command has
// been processed. This filter is invoked only by the command proposer.
type ReplicaResponseFilter func(roachpb.BatchRequest, *roachpb.BatchResponse) *roachpb.Error
```

@andreimatei assigning you since you know these things, but feel free to toss this to someone else.

**Comment by bdarnell** [comment]
Specifically, the action to be done here is to remove TestingEvalFilter, because it runs either before or after raft depending on the propEvalKV configuration, and requires the original request to be preserved for use downstream of raft even when propEvalKV is enabled. Tests that use TestingEvalFilter should be migrated to either a yet-to-be-implemented TestingProposalFilter which will always run before raft or a TestingApplyFilter that runs downstream of raft but no longer sees the original request (in most cases, the former is most appropriate). 

I'll leave this for a post-1.0 cleanup but in #14773 I've made a change so that we're only preserving the request in the raft command for tests that use TestingEvalFilter.

**Comment by andreimatei** [comment]
Some uses of `RaftCommand.BatchRequest` remain in non-test code, I think due to vestiges of non-prop-eval-KV. I'm trying to get them out.

**Comment by tschottdorf** [comment]
I've since made my peace with this filter.
