### ISSUE TITLE
sql: Implement pg_catalog.pg_depend as a virtual table

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10521]
See https://www.postgresql.org/docs/9.6/static/catalog-pg-depend.html.

This is needed for Hibernate.

**Comment by jordanlewis** [comment]
Postgres prepopulates pg_depend with thousands of rows that detail dependencies between other pg_catalog tables. I don't think we need to do this, and I think it would be quite a daunting task.

I'm planning to only implement support for user-defined "normal" relationships that get generated by foreign key references. Any objections?

**Comment by cuongdo** [comment]
Does the Hibernate code give any clues as to how `pg_depend` rows are used? Is it just foreign key references?

**Comment by jordanlewis** [comment]
It is used in (one monstrous query)[https://github.com/pgjdbc/pgjdbc/blob/8be516d47ece60b7aeba5a9474b5cac1d538a04a/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2391], inside a function called `getImportedExportedKeys`:

```
      sql += " pg_catalog.pg_depend dep, pg_catalog.pg_class pkic "
          + " WHERE pkn.oid = pkc.relnamespace AND pkc.oid = pka.attrelid AND pka.attnum = con.confkey[pos.n] AND con.confrelid = pkc.oid "
          + " AND fkn.oid = fkc.relnamespace AND fkc.oid = fka.attrelid AND fka.attnum = con.conkey[pos.n] AND con.conrelid = fkc.oid "
          + " AND con.contype = 'f' AND con.oid = dep.objid AND pkic.oid = dep.refobjid AND pkic.relkind = 'i' AND dep.classid = 'pg_constraint'::regclass::oid AND dep.refclassid = 'pg_class'::regclass::oid ";
```

There's a comment that might be kind of helpful:

**Comment by jordanlewis** [comment]
Whoops, cut that off too soon. The comment isn't really very helpful, though. I'll work on unpacking what this means.

**Comment by jordanlewis** [comment]
Here's a query that will show you what's in `pg_depend` for a default postgres install, excluding dependencies from tables that we don't support and excluding those rows that have no referent object (there's a row in `pg_depend` that sets up a dependency from oid 0 to every system oid, signifying that you can't drop those ever, but I don't think we need those rows for our purposes):

`select pg_depend.*, cla.relname as claname, refcla.relname as refname from pg_depend join pg_class refcla on refclassid=refcla.oid left join pg_class cla on classid=cla.oid where cla.relname not in ('pg_rewrite', 'pg_conversion', 'pg_ts_config', 'pg_ts_dict', 'pg_ts_template', 'pg_trigger');`

The result is (here)[https://gist.github.com/jordanlewis/25fc378dd791d588338bb83e5ccd4aae]. The last two columns signify the system catalog of the depending object and the system catalog of the depended object respectively. Out of those rows, the only ones that are used by Hibernate are those that represent a `pg_constraint` row depending on a `pg_class` row. Since each of these rows seem to be heavily special cased in postgres, I'm planning on only implementing those `pg_constraint` -> `pg_class` dependency rows unless someone has an objection.

**Comment by jordanlewis** [comment]
Good news! It turns out that `pgjdbc` doesn't need to use `pg_depend` at all since Postgres 9.0 - all of the required information is in `pg_constraint`. I've submitted pull request https://github.com/pgjdbc/pgjdbc/pull/689 to remove usage of `pg_depend` from `pgjdbc` when the postgres backend is new enough.

In the meantime, I suppose we'd might as well still support this feature. Now that I understand pretty well what needs to happen, I will add the bare minimum support to `pg_depend` to support this query with the understanding that we should be able to remove it if that pull request gets merged.

**Comment by cuongdo** [comment]
Good detective work. Yeah, add the bare minimum for now. Also, other ORMs
may need `pg_depend`. For example:

https://github.com/rails/rails/search?utf8=%E2%9C%93&q=pg_depend

Hmm, this `DELETE FROM` looks interesting:

https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb#L173

Anyway, I wouldn't worry about ActiveRecord too much for now, but just keep
the other ORMs we want to support in mind.

**Comment by jordanlewis** [comment]
Thanks for the links.

The first query you linked uses `pg_depend` in the same way that `pgjdbc` does, so we should we safe there.

Those `DELETE` queries are certainly interesting. Implementing support for them will require additional work because I believe that our virtual table implementation has no support for modifications like this.
