### ISSUE TITLE
sql: REPEAT built-in can crash the server

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10545]
`select repeat('abc', 100000000000);` -> boom

(out of memory)

The builtins that allocate stuff should be equipped with memory accounting. This means plumbing a monitor into all of them.

**Comment by knz** [comment]
cc @mjibson

**Comment by justinj** [comment]
Commenting here after discussion with Raphael because there's a bit of subtlety I didn't immediately recognize and I'd like to have it documented:

This is probably more extensive than needed but I'm writing it down anyway to make sure my thoughts are clear, so might as well have it in an accessible place :)

The subtlety here is that it's not clear in what account to log memory and at what point to release it. There are a couple of options:

1. Log memory in an account that only exists for the duration of the evaluation of the one function call. This would defend against certain specific cases like the title of this issue, because the account would be able to determine that the memory needed to evaluate the `REPEAT` was unavailable, and would error out. However, this fails in cases with queries like `CONCAT(REPEAT(...), REPEAT(...))`, where each individual `REPEAT(...)` is fine, but together they overflow the memory budget.
2. Create an account for the duration of the computation of a result row, request everything from there, and then once the row is computed, close the account as the row is sent off to where it goes next. This is also not perfect, because it is overly restrictive, and there are cases like `LENGTH(REPEAT(...)) + LENGTH(REPEAT(...))` where this method will unnecessarily count the memory required by each `REPEAT` at the same time, even though they can be discarded immediately.
3. Do something more sophisticated/complicated, like holding each expression node responsible for tracking the memory of its inputs in addition to the memory it generates (or something else).

We decided after discussing that option 2 is the most reasonable at this time, for the reason that it's better to incorrectly reject queries than incorrectly accept them, and the over-counting can be made more fine-grained in the future.

wrt implementation, it's worthwhile to note that there is another issue with overcounting in this model: if we implement this by creating the account in the executor and clearing it upon processing of each result row, certain nodes like `sortNode` and `GROUP BY` expressions can take in multiple rows before they output any result rows, and they do the memory accounting for these intermediate rows themselves. Since data accumulated in something like `REPEAT` will be tracked both by the enclosing account originating from the executor *and* this intermediate row accumulation, we are overly restrictive in this case. There might be something that can be done to mitigate this, but I haven't investigated yet.

**Comment by petermattis** [comment]
#15657 provided a stop-gap solution for 1.0. Punting to 1.1 for the real fix.

**Comment by cuongdo** [comment]
@justinj do you think you'll get to this as part of 1.1?

**Comment by justinj** [comment]
@cuongdo yes for sure, #15402 just needs a bit more review, I think.

**Comment by justinj** [comment]
Fixed by #15402, as stated in the comments here it's not a perfect fix, but #15295 tracks the desired eventual solution.
