### ISSUE TITLE
cli: remove password prompt for `cockroach user set` on insecure clusters

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10543]
On an insecure cluster (both with and without the `--insecure` flag), `cockroach user set` prompts the user to enter a password, even though that password is never used. Explaining that on insecure clusters the password is both required and useless in the documentation is very strange.

I propose only prompting the user for a password on the CLI when we detect that the command is being run on a secure cluster (e.g. there's also a `--ca-cert` flag).

Per @asubiotto's suggestion, CCing @bdarnell and @knz for feedback.

**Comment by knz** [comment]
I'm surprised this didn't show up with other CLI commands too

**Comment by asubiotto** [comment]
To clarify, consider a scenario where userA wants to create a new user, userB. Since userA is using the ```user set``` command, prompting happens for userB's password, not userA's. ```getPasswordAndMakeSQLClient``` in ```pkg/cli/sql_util.go``` handles not prompting the user using the CLI command in insecure mode.
This behavior is specific to the ```user set``` command. The confusion for the user stems from userA wanting to create userB and having to create a password for this new user even though on an insecure cluster, this password is effectively irrelevant.

**Comment by knz** [comment]
ah but! An insecure cluster can later be turned into a secure cluster, do we want to disallow setting up passwords entirely while it's insecure?

**Comment by sploiselle** [comment]
@knz Maybe the best-of-all-worlds behavior is to default insecure cluster users to blank passwords but honor the `--password` flag if it's present.

If the cluster becomes secure and the user does want to create passwords for users, they can always go back in and set passwords for existing users.

**Comment by knz** [comment]
:+1:
