### ISSUE TITLE
Multi-node testing: killing first node after sentinel replication wedges entire cluster

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1056]
Steps taken:
- init node 0
- start nodes 1, 2, 3
- wait until sentinel range is replicated (by watching /_status/gossip, confirm 3 replicas)
- kill node 0
- after approx 90s, nodes 1, 2 and 3 log: "missing sentinel gossip X; assuming partition and reconnecting"
- restart node 0
- node 0 tries to connect to the gossip network but fails with the same message.

Result: all nodes are assuming partition and are attempting to reconnect to gossip. Cluster is dead.

**Comment by MBerhault** [comment]
restarting all nodes also does not help. All the ones holding the sentinel range are stuck on:
"node 200000002 failed to send message to 400000004: gossip.go:203: unable to lookup address for node: 4" (obviously different values for each node).
The single node (out of 4) that did not have the sentinel range is just waiting to connect to gossip.

**Comment by petermattis** [comment]
It should be possible to write a test for this. Might need to add some more testing infrastructure to make starting and controlling multi-node test clusters easier.

**Comment by MBerhault** [comment]
As far as I can tell, this is due to the fact that nodes don't gossip the sentinel if they don't hold the leader lease. If we're just starting up, they have no way of finding the other nodes holding the range.
So that's for the startup problem.

The other problem is dropping out of the cluster entirely. Does something bad happen when one of the nodes drops off the map? Shouldn't one of the other two grab the leader lease and gossip the sentinel?

**Comment by tschottdorf** [comment]
What should happen when you kill the node with the lease is that the lease times out and then one of the other nodes will start gossiping. It's possible that this fails since the replication screws up the `store.rangesByKey` slice (it inserts when the range does not yet know its `StartKey`). Then the store, which is in charge of letting the ranges gossip the sentinel, may screw up the lookup somehow. That's pure speculation though.

**Comment by tschottdorf** [comment]
There are other things that are very likely to go wrong here in the DistSender:

- the leaderCache invalidates only when a `NotLeaderError` is received. That will obviously never happen if you try to get to the dead node as your cache suggests. We should aggressively timeout calls (currently the client has a 15s timeout...) and invalidate the cache.
- if the nodes have attribute lists, then we send in stable order (the replicas are rearranged a little bit, but the order will always be the same). Really we should always be randomizing the nodes within their common attribute prefix.

I'll work with Mark to cook up a one-off version of Cockroach that works around some of those issues to see if there are further bugs down the line (surely will).

**Comment by tschottdorf** [comment]
The fact that we can't recover from a (planned or unplanned) complete downtime of the first range is also troubling, but at least makes sense. As long as the first range is only on one node, that node can start and get the leader lease on its own. If it requires the help of the majority to get the lease, we're screwed because the other nodes can't even get past bootstrap and won't aid us in getting the leader lease for Gossip.

**Comment by tschottdorf** [comment]
After yesterday's session (with the open PRs outstanding) I think the open part of this issue is that once you shutdown the cluster and the sentinel gossip expires, the cluster can not restart again (since nobody will get far enough to gossip the sentinel).

**Comment by bdarnell** [comment]
I'm going to take a stab at the gossip bootstrapping problem.
