### ISSUE TITLE
kvserver: config change proposals can hang forever

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#105797]
In https://github.com/cockroachdb/cockroach/issues/104709#issuecomment-1609474175 we see a replica circuit breaker continually (un)tripping on a stuck proposal.

During an `ALTER TABLE SCATTER`, three replicas on n6 trip circuit breakers because of a slow proposal. In all cases, the proposals are `EndTxn(commit change-replicas)`, i.e. they are attempting to commit an conf change, and all of the replicas are followers.

```
E230627 12:51:40.782735 148856 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r1039/7:‹/Table/106/1/65{32837…-51266…}›] 30842 breaker: tripped with error: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870297.597281357,0 (2023-06-27 12:51:37); raft status: {"id":"7","term":12,"vote":"e","commit":135,"lead":"e","raftState":"StateFollower","applied":135,"progress":{},"leadtransferee":"0"}: have been waiting 63.00s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor›], [txn: 494e1e1e]
E230627 12:51:43.283167 149136 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r307/6:‹/Table/106/1/-68{2769…-0926…}›] 30847 breaker: tripped with error: replica unavailable: (n6,s6):6 unable to serve request to r307:‹/Table/106/1/-68{27690988321067808-09262672563116208}› [(n9,s9):7, (n7,s7):8, (n4,s4):4, (n3,s3):11, (n6,s6):6, next=12, gen=52, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870300.196827941,0 (2023-06-27 12:51:40); raft status: {"id":"6","term":12,"vote":"b","commit":127,"lead":"b","raftState":"StateFollower","applied":127,"progress":{},"leadtransferee":"0"}: have been waiting 60.50s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹-6827690988321067808›/‹RangeDescriptor›], [txn: 321479c5]
E230627 12:51:44.282776 149410 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r885/6:‹/Table/106/1/53{16569…-34997…}›] 30854 breaker: tripped with error: replica unavailable: (n6,s6):6 unable to serve request to r885:‹/Table/106/1/53{16569096169036592-34997411926988192}› [(n8,s8):11, (n4,s4):9, (n7,s7):12, (n5,s5):4, (n6,s6):6, next=13, gen=68, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870301.210269924,0 (2023-06-27 12:51:41); raft status: {"id":"6","term":13,"vote":"9","commit":122,"lead":"9","raftState":"StateFollower","applied":122,"progress":{},"leadtransferee":"0"}: have been waiting 61.50s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹5316569096169036592›/‹RangeDescriptor›], [txn: 336523e8]
```

After being tripped, we continually see these replicas re-tripping the circuit breakers every 3 seconds, as they try to repropose these EndTxns. However, the Raft groups are fully functional, and the circuit breakers also reset immediately, but keep re-tripping on these proposals that don't appear to be going through.

<img width="960" alt="Screenshot 2023-06-29 at 07 55 12" src="https://github.com/cockroachdb/cockroach/assets/644420/5655eaee-550d-45f9-856f-42ec495fb120">

We even see it after n6 regains leadership of the Raft group:

```
E230627 13:08:34.784088 650606 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r1039/7:‹/Table/106/1/65{32837…-51266…}›] 34156 breaker: tripped with error: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687871114.188750889,0 (2023-06-27 13:05:14); raft status: {"id":"7","term":13,"vote":"7","commit":963,"lead":"7","raftState":"StateLeader","applied":963,"progress":{"5":{"match":963,"next":965,"state":"StateReplicate"},"7":{"match":963,"next":964,"state":"StateReplicate"},"b":{"match":963,"next":965,"state":"StateReplicate"},"d":{"match":963,"next":965,"state":"StateReplicate"},"e":{"match":963,"next":965,"state":"StateReplicate"}},"leadtransferee":"0"}: have been waiting 1077.00s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor›], [txn: 494e1e1e]
```

We also see the transactions being cancelled:

```
I230627 12:51:40.785010 124952 kv/txn.go:878 ⋮ [T1,n6] 30843 async rollback failed: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870297.597281357,0 (2023-06-27 12:51:37); raft status: {"id":"7","term":12,"vote":"e","commit":135,"lead":"e","raftState":"StateFollower","applied":135,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/6551266251951793792›@1687870207.598066812,0: "change-replica" meta={id=494e1e1e key=/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor› iso=Serializable pri=0.06378614 epo=0 ts=1687870207.598066812,0 min=1687870207.598066812,0 seq=2} lock=true stat=PENDING rts=1687870207.598066812,0 wto=false gul=1687870208.098066812,0
I230627 12:51:43.285782 124887 kv/txn.go:878 ⋮ [T1,n6] 30848 async rollback failed: replica unavailable: (n6,s6):6 unable to serve request to r307:‹/Table/106/1/-68{27690988321067808-09262672563116208}› [(n9,s9):7, (n7,s7):8, (n4,s4):4, (n3,s3):11, (n6,s6):6, next=12, gen=52, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870300.196827941,0 (2023-06-27 12:51:40); raft status: {"id":"6","term":12,"vote":"b","commit":127,"lead":"b","raftState":"StateFollower","applied":127,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/-6809262672563116208›@1687870210.148120953,0: "change-replica" meta={id=321479c5 key=/Local/Range/Table/106/1/‹-6827690988321067808›/‹RangeDescriptor› iso=Serializable pri=0.02487111 epo=0 ts=1687870210.148120953,0 min=1687870210.148120953,0 seq=2} lock=true stat=PENDING rts=1687870210.148120953,0 wto=false gul=1687870210.648120953,0
I230627 12:51:44.285303 124854 kv/txn.go:878 ⋮ [T1,n6] 30855 async rollback failed: replica unavailable: (n6,s6):6 unable to serve request to r885:‹/Table/106/1/53{16569096169036592-34997411926988192}› [(n8,s8):11, (n4,s4):9, (n7,s7):12, (n5,s5):4, (n6,s6):6, next=13, gen=68, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870301.210269924,0 (2023-06-27 12:51:41); raft status: {"id":"6","term":13,"vote":"9","commit":122,"lead":"9","raftState":"StateFollower","applied":122,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/5334997411926988192›@1687870210.000120522,0: "change-replica" meta={id=336523e8 key=/Local/Range/Table/106/1/‹5316569096169036592›/‹RangeDescriptor› iso=Serializable pri=0.00570728 epo=0 ts=1687870210.000120522,0 min=1687870210.000120522,0 seq=2} lock=true stat=PENDING rts=1687870210.000120522,0 wto=false gul=1687870210.500120522,0
```

Jira issue: CRDB-29202

**Comment by tbg** [comment]
This is interesting. I think at a high level, the replica circuit breaker is behaving as expected: it trips because a proposal isn't going through in 60s. Then, it sends a probe. The probe goes through! It resets. But the proposal that had originally tripped the breaker is still present. So after `refreshAtDelta` ticks (=3s), the breaker trips again. Goto beginning. This is maybe not ideal - the breaker should either stay tripped, or stay untripped - but fundamentally the breaker is not the issue here.

What do we know about this ill-behaved proposal? I was hoping to have some kind of hypothesis before wading into the logs. We know it's an `EndTransaction` with a `ChangeReplicasTrigger`. What could be a reason that it never goes through? Perhaps we're rejecting it every time before it goes into the log.

Such rejections generally happen here, in `propBuf.FlushLockedWithRaftGroup`:

https://github.com/cockroachdb/cockroach/blob/33c7754064f94a2a9bd81792882d4ed1340e72f3/pkg/kv/kvserver/replica_proposal_buf.go#L444-L448

Note that there are a few other checks in the vicinity, but they are all fatal if they fail (we propagate `firstErr` to the caller, which is fatal except when `firstErr` is `errRemoved`, which is not the case we're hitting here or the replica would have self-destructed).

Unfortunately, `maybeRejectUnsafeProposalLocked` will only ever reject `TransferLease` or `RequestLease`, and here we have neither.

So, where else could the proposal have been dropped? Probes are small but not zero-size, and change replicas isn't large either. So a possible explanation, namely that the leader's uncommitted log was too large, doesn't seem likely.

----

So, no conjecture and we just have to look at logs. I am looking at r1039, where the breaker trips on (at the end) leaseholder n6.

When the breaker trips for the first time, it mentions that the proposal is for txn `494e1e1e`. It trips at 12:51:40 mentioning that the proposal has been inflight for 63s, which would imply that the proposal was inserted for the first time at around **12:50:37**. Looking for `494e1e1e` in the logs, we also see that at `12:50:24` latches for that txn had been held (and not released) for 15s, which puts the conf change at 12:50:09 instead. Since conf changes get proposed by the leader, we can simply look up the last conf change carried out by n6 and find that it was proposed at `12:50:11`, so the latter timestamp is fairly accurate. I have no good explanation for the difference; in my view, the proposal ought to have been inserted and then flushed from the proposal buf pretty soon after 12:50:11.

```
teamcity-10689032-1687844707-66-n10cpu2-0006>
I230627 12:50:11.016800 41451 13@kv/kvserver/replica_raft.go:381 ⋮ [T1,n6,s6,r1039/7:‹/Table/106/1/65{32837…-51266…}›] 4447
proposing LEAVE_JOINT: after=[(n3,s3):8 (n6,s6):7 (n5,s5):9LEARNER (n7,s7):10 (n9,s9):5 (n8,s8):11] next=12
```

We see that this is a LEAVE_JOINT proposal; n5 is getting demoted from voter to learner and n8 is an incoming voter.

Here is the lease history:

```
n6 from 1687870199645317000 = Tuesday, June 27, 2023 12:49:59.645 PM (acquisition type Request)
n9 from 1687870234400426000 = Tuesday, June 27, 2023 12:50:34.400 PM (acquisition type Request)
n4 from 1687870251517290200 = Tuesday, June 27, 2023 12:50:51.517 PM (acquisition type Transfer)
     to 1687870257517054200 = Tuesday, June 27, 2023 12:50:57.517 PM
n4 from 1687870251517290200 = Tuesday, June 27, 2023 12:50:51.517 PM (acquisition type Request)
n6 from 1687870558282677500 = Tuesday, June 27, 2023 12:55:58.282 PM (acquisition type Request)
```

We see that n6 lost the lease pretty soon after proposing this config change. n9 picks up the lease; it carries out a large number of configuration changes, starting with what n6 is attempting to do (leaving the joint config). All the while, n6 is helplessly reproposing the command every couple of seconds. What _should_ have happened is that the proposal enter the log on n9, at which point it would apply with an error (proposed under invalid lease), and the proposal would be finished.

Instead, after a minute, it trips the circuit breaker on n6. n6 has no lease at this time nor is it raft leader; but a few minutes later, the lease and leadership actually get sent back to it, and crucially, it also applies this lease, meaning it has retained the ability to apply the raft log. At time of debug.zip, n6 is fully caught up, and so are all of the followers. Nevertheless, it's not managing to get this proposal through.

----

This is really tricky. Thanks to the repeated breaker trips, we have snapshots of the raft state every 3s and in particular can gauge the growth of the log. It does seem as though we're adding ~2 entries per refresh cycle. These are unlikely to come from a foreground workload, since commits generally acquire a read latch on the range descriptor, and the conf change holds a write latch; we have zero intents on the range.

I currently suspect that this proposal went through replication just fine, many times over the period covered in the logs, but that it somehow failed to properly signal the proposer.

We likely won't figure it out from this repro, so I'll try to reproduce with additional logging that describes all rejected proposals in detail, etc.

**Comment by tbg** [comment]
I think I've got somewhere from staring more. So the proposal that never goes through is a conf change. Raft has special logic for validating a conf change. Concretely, it rejects configuration changes that don't fit its internal configuration. For example, if the config isn't joint, it won't let you propose an entry that leaves a joint config.

We would then hit this path and propose an empty entry instead:

https://github.com/etcd-io/raft/blob/115946606301da0fcf300f8790e847d641699225/raft.go#L1250-L1259

But an empty entry of course doesn't map back to our proposal! I think this explains everything.

1. we make a LEAVE_JOINT conf change.
2. due to chaos reasons, this proposal doesn't go through initially and leadership is lost; it gets dropped or whatever (waiting to get reinserted).
3. The new leaseholder+leader has already done a few config changes, which n6 has applied. The RawNode is no longer in a joint config.
4. n6 tries to reinsert the proposal. Raft proposes an empty entry instead.
5. repeat forever

The problem is that raft refuses an entry that we would also refuse (due to the stale proposer lease). However, *we* need to be the ones to refuse it to avoid leaking the proposal, as we have here.

**Comment by erikgrinaker** [comment]
Right, that checks out, thanks for digging! However, where does that leave us? Would this always fail the first time we propose it, such that we can catch `ErrProposalDropped` and cancel the proposal? Or (more likely) would it be possible that the first proposal is actually sent, never shows up in the log, and then the reproposal fails without any way for us to detect that and cancel it.

**Comment by erikgrinaker** [comment]
I guess we can duplicate the logic up in CRDB, or return some specific error code, such that we can detect when reproposals are futile and error out. If we know that the conf change is no longer compatible with the current conf, and we didn't see the proposal applied, then we can reasonably assume that it didn't go through.

**Comment by renatolabs** [comment]
This looks a lot like what we're seeing in #105970, but correct me if it's something else.

**Comment by tbg** [comment]
Reopening since I'm about to revert, due to https://github.com/cockroachdb/cockroach/issues/106172#issuecomment-1623568845.
