### ISSUE TITLE
Add unittest which reproposes a command

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#10640]
When we we repropose a command, we return `proposalData.ShouldRetry=true` and no error. For the `Replica.addWriteCmd` execution path, this unittest must verify that we do not update the timestamp cache. This was a bug which I fixed in #10639.

**Comment by bdarnell** [comment]
We already have a couple of tests for this, but one of them is skipped (#8422) and neither of them is sensitive to this timestamp cache issue since they are write-only. I'll work on fixing the skipped test and adding a test where the timestamp cache matters.

I wonder if it would be possible to add some sort of flag to make *every* command fail on the initial proposal and be reproposed, since it seems unlikely that we'll get complete coverage of all the edge cases in any other way.

**Comment by spencerkimball** [comment]
This unittest should also verify that if the re-proposal experiences an eventual error, we return `AmbiguousResultError`.
