### ISSUE TITLE
kv: Should return OpRequiresTxnError after ba.Split

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#10666]
In `DistSender.divideAndSendBatchToRanges`, it will generate `OpRequiresTxnError` if the BatchRequest spans ranges.
But the  BatchRequest in `DistSender.divideAndSendBatchToRanges` come from the `parts[i]` in `DistSender.Send`, `parts` is come from `ba.Split()`. So, maybe BatchRequest before `ba.Split()` spans ranges, but each part after `ba.Split()` not spans ranges. But I think we still need `OpRequiresTxnError` on this condition.
For example, we has a BatchRequest like "put A, get B, put C", and A,B,C belong to different ranges. After `ba.Split()`, we has 3 parts(get B not compatible with put A, and put C not compatible with get B), and each part belong to only one range. So there is no `OpRequiresTxnError`, but the whole BatchRequest spans ranges.

**Comment by bdarnell** [comment]
You're right that there's something funny going on here. In fact, if `ba.Split` (which splits requests based on their type rather than their keys) gives us multiple chunks, we need to return OpRequiresTxnError whether all those keys are in different ranges or not. 

Or maybe we should just get rid of OpRequiresTxnError and stop guaranteeing atomicity of requests sent in a single batch without an explicit transaction. Now that we have the 1PC optimization, there's no harm in including the transaction every time. I don't think we're currently relying on OpRequiresTxnError anywhere; the SQL layer always uses an explicit transaction.

**Comment by dianasaur323** [comment]
assigning to @bdarnell. Feel free to reassign!

**Comment by bdarnell** [comment]
No urgency here; removing from 1.0.
