### ISSUE TITLE
sql: flakes in TestBackupSuccessMixedVersion

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#107552]
Seen here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11043373?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Stack trace: https://gist.github.com/mgartner/cbf8e6346ee8a5e89f5f5c9023e75bae

Jira issue: CRDB-30105

**Comment by nvanbenschoten** [comment]
I also just saw `TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid` fail here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11053930?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true.

**Comment by knz** [comment]
here too https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11054962?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rafiss** [comment]
This is the test that was just refactored in https://github.com/cockroachdb/cockroach/pull/106743. cc @Xiang-Gu I think this issue now replaces https://github.com/cockroachdb/cockroach/issues/106349, so I will close that one.

**Comment by postamar** [comment]
This issue tracks many cases now. I'll just mention that when it comes to `alter_table_add_primary_key_drop_rowid`, tests involving this case may time out sort of legitimately, because it's a very large test case, the largest in fact.

I suggest it be skipped it by adding an if-check at the start of `sctest.BackupSuccess` (or whatever `sctest` entrypoint is involved) that compares the path to see if it ends in that string and `skip.WithIssue` if it does.

**Comment by knz** [comment]
I'm skipping alter_table_add_primary_key_drop_rowid in  #107590

**Comment by rafiss** [comment]
> What about the test makes it so slow? It looks fairly brief:

It's slow because during each "stage" of the schema change, the test will perform a backup. The ALTER PRIMARY KEY schema change has 15 stages, which is very high compared to most schema changes. Before a recent refactor (https://github.com/cockroachdb/cockroach/pull/106743) some of the backups were randomly skipped in order to save time.
