### ISSUE TITLE
changefeedccl: flake in TestChangefeedKafkaMessageTooLarge

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#107591]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11056281?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill
    helpers_test.go:745: still waiting for job status; current reverting
        --- FAIL: TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill (45.75s)
```

Jira issue: CRDB-30118

Epic CRDB-11732

**Comment by jayshrivastava** [comment]
It seems that the job get's stuck in status `REVERTING` for 45s which causes the test to time out. This call to `closeFeed` hangs. 
https://github.com/cockroachdb/cockroach/blob/28e02cf2a8a2297082819ce20c69f68441658358/pkg/ccl/changefeedccl/changefeed_test.go#L7701

It looks like the cancel succeeds, setting the job state to `reverting`.
https://github.com/cockroachdb/cockroach/blob/912983cc0b2218d62d1b3b4231d7f06356bb6038/pkg/jobs/adopt.go#L587-L621

However, it doesn't look like the registry ends up calling `OnFailOrCancel`. https://github.com/cockroachdb/cockroach/blob/9d59881056d7e77813543371d39563c1d7069d21/pkg/jobs/registry.go#L1751

**Comment by jayshrivastava** [comment]
I'm convinced there is a deadlock. That goroutine above deadlocks with this one 
```
1 @ 0x49c176 0x4ac45c 0x4c88f0a 0x4c6b512 0x4c6b635 0x4ba655f 0x4ba5ab4 0x4ce321
# labels: {"job":"CHANGEFEED id=885823367427489793", "n":"1"}
#	0x4c88f09	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*fakeKafkaSink).Dial.func3.1+0xe9	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:1712
#	0x4c6b511	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*syncProducerMock).SendMessage+0x31	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_test.go:99
#	0x4c6b634	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*syncProducerMock).SendMessages+0x94	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_test.go:108
#	0x4ba655e	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).handleBufferedRetries+0x3be	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:653
#	0x4ba5ab3	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).workerLoop+0x6b3		github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:569
```
This is pointing to https://github.com/cockroachdb/cockroach/blob/418c72a253e102b8d51a938c18238f1ca764da45/pkg/ccl/changefeedccl/testfeed_test.go#L1712-L1716

**Comment by jayshrivastava** [comment]
This is my branch https://github.com/jayshrivastava/cockroach/tree/debug-kafka

[10.goroutinesJAYANT.txt](https://github.com/cockroachdb/cockroach/files/12177139/10.goroutinesJAYANT.txt)
[10.logTestChangefeedKafkaMessageTooLarge406588501.zip](https://github.com/cockroachdb/cockroach/files/12177142/10.logTestChangefeedKafkaMessageTooLarge406588501.zip)

**Comment by jayshrivastava** [comment]
It looks like the test deadlocks bc the buffer here fills up. 
https://github.com/cockroachdb/cockroach/blob/5c3f96d38cdc3a2d953ca3ffb1e39e97d7e5110e/pkg/ccl/changefeedccl/testfeed_test.go#L1819

Even though `TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill` should be reading and writing 2000 messages, we end up writing >14689 messages. The reason is that each of the 2000 messages fails with a retryable error 20% of the time. The retry and subsequent retries also fail with a retryable error 20% of the time. This makes the total number of messages blow up and fill the buffer.

I also thought about why `handleBufferedRetries` keeps trying to send messages even after the test has finished and asserted that the 2000 expected messages have been seen. You would think that there are no retries left to perform. My answer at the moment is that resolved messages are also in the buffer, which take up space and can get stuck retrying.
