### ISSUE TITLE
storage: need metric for # quorum-less ranges

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10769]
`Store.updateReplicationGauges` is called to periodically update replica and range metrics, such as raft-leader-count and lease-holder-count. But there is a gap in these metrics: if a range does not have quorum and the lease has expired it won't show up in raft-leader-count, lease-holder-count or any other metric other than the raw replica-count.

I propose we use the node liveness table to compute the availability of the replicas for a range. If the range has a leader, the leader computes this info. If the range is leader-less, the smallest "live" replica ID computes this info (i.e. every "live" replica would compute it, but only the smallest replica ID would report it).

Cc @cockroachdb/stability

**Comment by tamird** [comment]
> But there is a gap in these metrics: if a range does not have quorum and the lease has expired it won't show up in raft-leader-count, lease-holder-count or any other metric other than the raw replica-count.

More specifically, I believe the gap is present when the range does not have a raft leader. Do you agree?

> I propose we use the node liveness table to compute the availability of the replicas for a range. If the range has a leader, the leader computes this info. If the range is leader-less, the smallest "live" replica ID computes this info (i.e. every "live" replica would compute it, but only the smallest replica ID would report it).

Seems reasonable. Let's see where this road leads.

**Comment by petermattis** [comment]
> More specifically, I believe the gap is present when the range does not have a raft leader. Do you agree?

Yes. A range that is below quorum will lose its leadership after the raft election timeout (~3s).

**Comment by spencerkimball** [comment]
I thought about just the scheme you're proposing, @petermattis. My thought for #11213 was just to change as little as possible, because the scheme where the smallest counts will still have under-counting and over-counting on node liveness transitions. Nevertheless, if you think it's worthwhile to advance this, I'm going to also create a new `rangeCount` stat to go with the `availableRangeCount` stat. At the moment `availableRangeCount` is really based off of `raftLeaderCount`.
