### ISSUE TITLE
tsdump: histograms are missing

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#107701]
In the tsdump in https://github.com/cockroachdb/cockroach/issues/106140#issuecomment-1653391782, the histogram quantiles are not recorded. For example, `exec.latency` is not there. I remember this working at some point; unclear if it's an issue with this particular tsdump or a regression.

tsdump.gob.yaml (July 5-6)

```
1: 1
2: 2
3: 3
4: 4
5: 5
6: 6
7: 7
8: 8
```

Jira issue: CRDB-30167

**Comment by ericharmeling** [comment]
We're not actually constructing the histogram names for most histograms in the tsdump code path. 

`GetInternalTimeseriesNamesFromServer` checks the `meta.MetricType` of the metadata for each metric here:
https://github.com/cockroachdb/cockroach/blob/62e59ec852bda61ad6d00519f9e81595c41f865b/pkg/server/serverpb/admin.go#L83

The zero value for the `MetricType` in the prometheus go client is `COUNTER`: https://github.com/prometheus/client_model/blob/62e59ec852bda61ad6d00519f9e81595c41f865b/go/metrics.pb.go#L41

The histogram mentioned in this issue (`exec.latency`) does not specify a `MetricType`:
https://github.com/cockroachdb/cockroach/blob/62e59ec852bda61ad6d00519f9e81595c41f865b/pkg/server/node.go#L93-L108

In fact, the only metrics for which we do specify a `MetricType` are `ttljob_metrics`: https://github.com/cockroachdb/cockroach/blob/62e59ec852bda61ad6d00519f9e81595c41f865b/pkg/sql/ttl/ttljob/ttljob_metrics.go#L102-L134

And these are the only histogram metrics that actually show up in the `tsdump`.

Rather than explicitly specify a metric type for each histogram, we should be assigning this type on histogram creation, or returning it on metadata introspection. This PR should resolve this issue: https://github.com/cockroachdb/cockroach/pull/108597
