### ISSUE TITLE
sql: TestRelocateNonVoters failed

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#108081]
Failed in [this CI build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11168783?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) with the following error:

```
Failed
=== RUN   TestRelocateNonVoters/ALTER_RANGE_x_RELOCATE_NONVOTERS
    test_server_shim.go:98:
        Test server was configured to route SQL queries to a secondary tenant (virtual cluster).
        If you are only seeing a test failure when this message appears, there may be a problem
        specific to cluster virtualization or multi-tenancy.
        To investigate, consider using "COCKROACH_TEST_TENANT=true" to force-enable just
        the secondary tenant in all runs (or, alternatively, "false" to force-disable), or use
        "COCKROACH_INTERNAL_DISABLE_METAMORPHIC_TESTING=false" to disable all random test variables altogether.
    testcluster.go:416:
        Test server was configured to route SQL queries to a secondary tenant (virtual cluster).
        If you are only seeing a test failure when this message appears, there may be a problem
        specific to cluster virtualization or multi-tenancy.
        To investigate, consider using "COCKROACH_TEST_TENANT=true" to force-enable just
        the secondary tenant in all runs (or, alternatively, "false" to force-disable), or use
        "COCKROACH_INTERNAL_DISABLE_METAMORPHIC_TESTING=false" to disable all random test variables altogether.
    multitenant_admin_function_test.go:369: condition failed to evaluate within 3m45s: from multitenant_admin_function_test.go:392: expected "trying to add a non-voter to a store that already has a NON_VOTER" contains "ok" tenant=secondary query=`ALTER RANGE (SELECT min(range_id) FROM [SHOW RANGES FROM TABLE t]) RELOCATE NONVOTERS FROM 2 TO 3;` leaseholder=1 replicas=[1 2 4 5] voting_replicas=[1 4 5] non_voting_replicas=[2] fromReplica=2 toReplica=3 row=0 col=2
    --- FAIL: TestRelocateNonVoters/ALTER_RANGE_x_RELOCATE_NONVOTERS (433.62s)
```

Jira issue: CRDB-30305

**Comment by andrewbaptist** [comment]
This is a pretty tricky situation. The issue has to do with the fact that `ALTER RANGE` is a very complex command and it is hard to tell from a failure whether it worked or not. The command will queue it up with the allocator, however, it can fail on the first attempt and return failure to the user even though it succeeded internally. Additionally, the replicate_queue can move replicas around at any point so you can't assume that the chosen destination store doesn't already have the replica (actually looking more the replicate queue is disabled). 

There are a few ways to make this test more reliable:
1) Create a zone configuration so that the location of all the replicas and leases is known beforehand, issue the command, and check if the replicas/leases are in the "final destination" rather than looking at the returned error
2) More complex parsing of the error messaging to look for "already has" and consider that a success
3) Ignore the error from the `ALTER` command and instead look at the replica placement using `SHOW RANGES` to see if it succeeded.
4) Change the behavior of the replica_command.validateReplicationChanges to return success if the operation would be a no-op.

Short term, the easiest fix is probably 2 from above. 1 is better but will require more work. I don't think 4 is the right change to make.

Moving this back to multitenant for now - let me know if you have questions.

**Comment by pavelkalinnikov** [comment]
Caught this again on master @ b4623a51:

```
--- FAIL: TestRelocateNonVoters (704.70s)
    test_log_scope.go:167: test logs captured to: /tmp/cockroach/_tmp/883ff9e8b9b96cda71ea23ecb5e4fcdc/logTestRelocateNonVoters362065654
    --- FAIL: TestRelocateNonVoters/ALTER_RANGE_x_RELOCATE_NONVOTERS (355.43s)
        multitenant_admin_function_test.go:369: condition failed to evaluate within 3m45s: from multitenant_admin_function_test.go:392: expected "trying to add a non-voter to a store that already has a NON_VOTER" contains "ok" tenant=system query=`ALTER RANGE (SELECT min(range_id) FROM [SHOW RANGES FROM TABLE t]) RELOCATE NONVOTERS FROM 2 TO 4;` leaseholder=1 replicas=[1 2 3 5] voting_replicas=[1 3 5] non_voting_replicas=[2] fromReplica=2 toReplica=4 row=0 col=2
    --- FAIL: TestRelocateNonVoters/ALTER_RANGE_RELOCATE_NONVOTERS (349.26s)
        multitenant_admin_function_test.go:369: condition failed to evaluate within 3m45s: from multitenant_admin_function_test.go:392: expected "trying to add a non-voter to a store that already has a NON_VOTER" contains "ok" tenant=system query=`ALTER RANGE RELOCATE NONVOTERS FROM 5 TO 2 FOR (SELECT min(range_id) FROM [SHOW RANGES FROM TABLE t]);` leaseholder=4 replicas=[1 3 4 5] voting_replicas=[1 3 4] non_voting_replicas=[5] fromReplica=5 toReplica=2 row=0 col=2
    multitenant_admin_function_test.go:925: -- test log scope end --
FAIL
```

while stressing under race as follows:

```bash
$ dev test pkg/sql:sql_test -f=TestRelocateNonVoters --stress --count=100 --race --cpus=4 -- --test_env=COCKROACH_TEST_TENANT=true
```

**Comment by yuzefovich** [comment]
After #108497, `COCKROACH_TEST_TENANT=true` is effectively ignored, so the failure you observed seems legitimate.
