### ISSUE TITLE
util/timeutil/ptp: add end-to-end test

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#108273]
We should add an end-to-end test for the PTP clock using an actual PTP device (or at the very least, a mocked device file). This would possibly be a roachtest.

Jira issue: CRDB-30405

**Comment by andrewbaptist** [comment]
Just as a note as I was looking at this, to reproduce a "vMotion move" - you can run something like:

`kill -STOP $PID ; sleep .5; kill -CONT $PID`

Modifying the sleep time to simulate how long you want to freeze the process. 

I did verify that if `server.clock.forward_jump_check_enabled` is enabled and this is run it will cause a process crash even though the clock stays perfectly synced on a node. 
This is somewhat expected, because any place where we read the current clock and then process it after we pause will cause the problem. 

We should be careful about claiming that a PTP clock with vMotion will not result in stale reads (this was one of their questions to us) - as when a node is stalled, it can return a result that is inconsistent with the physical clock. 

I did not see the process panic when the setting was disabled.

**Comment by nicktrav** [comment]
I'm going to pick this up.

I was able to get the following to work:

```
# Spin up roachprod instance.
$ ./bin/roachprod create travers-test -n 1 -c gce
$ ./bin/roachprod stage travers-test release v23.1.11
$ ./bin/roachprod ssh travers-test:1

# Install package including ptp_kvm.
$ sudo apt-get install -y linux-modules-extra-$(uname -r)

# Activate kernel module.
$ sudo modprobe ptp_kvm

# Confirm existence of PTP device.
$ ls -l /dev/ptp*
crw-r--r-- 1 root root 246, 0 Oct  6  2023 /dev/ptp0
lrwxrwxrwx 1 root root      4 Oct  6  2023 /dev/ptp_kvm -> ptp0

# Alter perms - cockroach needs to be able to read from the device.
$ sudo chmod 0644 /dev/ptp0

# Alter the system time to something far enough in the past.
$ sudo date --set '20200101 00:00'
$ date -u
Wed Jan  1 00:00:01 UTC 2020

# Boot cockroach, using the PTP device.
$ ./cockroach start-single-node --store $(mktemp -d) --insecure --logtostderr --clock-device /dev/ptp0

# In a second shell, fetch the time.
$ ./cockroach sql --insecure
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v23.1.11 (x86_64-pc-linux-gnu, built 2023/09/27 01:53:43, go1.19.10) (same version as client)
# Cluster ID: ea4d78dc-ebe0-4883-b2c2-1cdb74a470cd
#
# Enter \? for a brief introduction.
#
root@localhost:26257/defaultdb> select now();
               now
---------------------------------
  2023-10-06 21:46:09.445993+00
(1 row)

Time: 1ms total (execution 0ms / network 0ms)
```

Confirm that the time is obtained from the PTP device.

---

Next step, turn this into a roachtest.

**Comment by pavelkalinnikov** [comment]
@nicktrav Nice!

> Next step, turn this into a roachtest.

Another good test would be to run a two-node cluster, where VMs of both nodes are at a large time offset from each other. If both are using the PTP clock though, it should all work fine?

**Comment by erikgrinaker** [comment]
Yeah, we'd also want to run a workload on the cluster for a little while to ensure nothing bad happens.

I wonder if we can make this metamorphic across all/most roachtests, by injecting a PTP clock device and messing up the system clock. That way, we can check that other functionality doesn't have implicit dependencies on the system/external clocks, stuff like backups/changefeeds/etc.

**Comment by tbg** [comment]
I worked on this a bit today. I have a basic roachtest (#129123) that sets up  the ptp0 device (following Nick's recipe above), starts without it, stops, starts but pointing at an invalid file for a ptp device and verifies startup fails, then starts again this time pointing at the correct device.
I still have to see what can be added to verify that we're actually using the ptp device. Messing with the system clock as "proof" of that is something I expect to be brittle. I'd much rather install a "pipe" device that we can intercept, or use bpf, or whatever. But if we're trying to be comprehensive I'm not sure we can do much better than messing with the system clock.
We may find a need to be pragmatic about how deeply we test this.

**Comment by nicktrav** [comment]
> I'm not sure we can do much better than messing with the system clock

This might require some diving into PTP devices and Linux clock, but it looks like we could do something like mount a "slave" device and point it at the "master" PTP clock device (`/dev/ptp0`). The [`phc2sys`](https://linux.die.net/man/8/phc2sys) tool could then be used to re-synchronize the "slave" with an arbitrary offset (`-O` flag).

I could imagine a test doing something like:
- Mount a slave into each node, each with offset 0 from the master.
- Boot CRDB.
- Assert everything functioning a-ok.
- Pick a node and re-synchronize it's slave clock with some nasty offset.
- Assert that node panics due to clock drift.

One could also conceivably set all nodes' slave PTP clocks well into the future / past with a well known offset (i.e. set all a year into the future). That gives you a means of asserting that the PTP clock is being used (i.e. check that `select now()` is within some bounds of `time.Now() + KNOWN_OFFSET`). This would also flush out any dependencies on the system clock.
