### ISSUE TITLE
A SQL query used for introspecting a large database schema got 200x slower 

### ISSUE THREAD

**Issue by Jolg42** [cockroachdb/cockroach#108781]
**Describe the problem**

Prisma has an introspecting feature that looks at a database and creates a Prisma schema out of it, it is called `prisma db pull`
One of the introspection SQL query is now very slow, 500s+ for `discourse` which has 140 tables (see link in To Reproduce).

I do not know exactly at the moment for which version it started, my best guest is v23.1.x 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up a serverless CockroachDB cluster in the Cloud UI
2. Use https://github.com/prisma/database-schema-examples/blob/main/postgres/discourse/schema.sql to create a database
3. Run the following SQL query on that database
```sql
SELECT
  oid.namespace,
  info.table_name,
  info.column_name,
  format_type(att.atttypid, att.atttypmod) AS formatted_type,
  info.numeric_precision,
  info.numeric_scale,
  info.numeric_precision_radix,
  info.datetime_precision,
  info.data_type,
  info.udt_schema AS type_schema_name,
  info.udt_name AS full_data_type,
  pg_get_expr(attdef.adbin, attdef.adrelid) AS column_default,
  info.is_nullable,
  info.is_identity,
  info.character_maximum_length,
  description.description
FROM
  information_schema.columns AS info
  JOIN pg_attribute AS att ON att.attname = info.column_name
  JOIN (
      SELECT
        pg_class.oid, relname, pg_namespace.nspname AS namespace
      FROM
        pg_class
        JOIN pg_namespace ON
            pg_namespace.oid = pg_class.relnamespace AND pg_namespace.nspname = ANY (ARRAY['public'])
    )
      AS oid ON
      oid.oid = att.attrelid AND relname = info.table_name AND namespace = info.table_schema
  LEFT JOIN pg_attrdef AS attdef ON
      attdef.adrelid = att.attrelid AND attdef.adnum = att.attnum AND table_schema = namespace
  LEFT JOIN pg_description AS description ON
      description.objoid = att.attrelid AND description.objsubid = ordinal_position
WHERE
  table_schema = ANY (ARRAY['public']) AND info.is_hidden = 'NO'
ORDER BY
  namespace, table_name, ordinal_position
```
5. Wait for 500~ seconds for it to complete
6. Note that removing this part of the query `table_schema = ANY (ARRAY['public']) AND` and running it again makes it succeed in 2s.

**Expected behavior**
It should be (a lot?) faster to execute.

**Additional data / screenshots**
Diagnostic archive from the Cloud UI, from https://cockroachlabs.cloud/cluster/6fcad804-83d9-4f9b-b80b-b5b7b789a93c/statement/true/11919201472824938241?appNames=%28unset%29&cluster-type=serverless&tab=overview :
[stmt-bundle-890298509353746433.zip](https://github.com/cockroachdb/cockroach/files/12346113/stmt-bundle-890298509353746433.zip)

<img width="1197" alt="Screenshot 2023-08-15 at 18 02 16" src="https://github.com/cockroachdb/cockroach/assets/1328733/03a2a52b-67cf-473b-95cd-06f58bb0d4d8">
<img width="1055" alt="Screenshot 2023-08-15 at 18 02 30" src="https://github.com/cockroachdb/cockroach/assets/1328733/cbc282e3-5498-4367-9fc9-a063883be5b8">

<img width="287" alt="Screenshot 2023-08-15 at 18 22 05" src="https://github.com/cockroachdb/cockroach/assets/1328733/2df8b608-92a2-40e5-a472-a0bbf95aac40">
<img width="511" alt="Screenshot 2023-08-15 at 18 21 28" src="https://github.com/cockroachdb/cockroach/assets/1328733/fa2efc5c-0165-4f2f-94e4-f355470d93bd">

**Environment:**
 - CockroachDB version: v23.1.8 - cockroachlabs.cloud / Serverless
 - Server OS: Linux - Ubuntu - GitHub Actions  
 - Client app: Prisma Client

**Additional context**
The CockroachDB server is https://cockroachlabs.cloud/cluster/6fcad804-83d9-4f9b-b80b-b5b7b789a93c/overview?cluster-type=serverless
It's only used for tests, feel free to take a look, there is no data, only schemas we gathered for running tests.

Shared in our shared [Slack channel](https://prisma-company.slack.com/archives/C01CSQXTNJ3/p1691768436839419)

Jira issue: CRDB-30636

Epic CRDB-27601

**Comment by rafiss** [comment]
Thanks for this report. I'll leave notes here as I discover things -- this is the slow part from the statement bundle:
```
            └── • virtual table lookup join
                │ nodes: n1
                │ actual row count: 1,286
                │ sql cpu time: 14m43s
                │ table: pg_namespace@pg_namespace_oid_idx
                │ equality: (relnamespace) = (oid)
                │ pred: (nspname = table_schema) AND (nspname = 'public')
```

**Comment by mgartner** [comment]
Here's a simple reproduction:

The CPU profile (here: [discourse.cpu.zip](https://github.com/cockroachdb/cockroach/files/12432791/discourse.cpu.zip)) shows that most of the time is spent fetching all the descriptors for each lookup of the virtual table lookup join:

<img width="1180" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1128750/028ca699-d973-483e-81dd-452d759af64c">

This query got slower in v23.1 because the `pg_namespace@pg_namespace_oid_idx` was added. The optimizer now selects a plan that performs lookup joins with that index. #55833 was supposed to reduce the likelihood of selecting plans with virtual table lookup joins. It's possible that the fixed cost added for each lookup doesn't sufficiently represent the real cost of each lookup, which seems to scale as a function of the number of descriptors. I'll continue to investigate why the optimizer is picking this plan.

**Comment by mgartner** [comment]
I no longer believe the optimizer is to blame here. The execution of this query appears to be way slower that it should be.

Here's another reproduction: https://gist.github.com/mgartner/4f01c3d61898e015bd2487e34b68edab

```
                    info
---------------------------------------------
  planning time: 944µs
  execution time: 5.9s
  distribution: local
  vectorized: true
  maximum memory usage: 590 KiB
  network usage: 0 B (0 messages)
  sql cpu time: 5.3s
  regions: us-east1

  • virtual table lookup join
  │ nodes: n1
  │ regions: us-east1
  │ actual row count: 20,056
  │ sql cpu time: 5.3s
  │ table: pg_class@pg_class_oid_idx
  │ equality: (attrelid) = (oid)
  │
  └── • hash join
      │ equality: (column_name) = (attname)
      │
      ├── • virtual table
      │     table: columns@primary
      │
      └── • virtual table
            table: pg_attribute@primary
(25 rows)
```

I'm confused because when I remove the virtual table scan that's under the virtual lookup join, the lookup join is not slow, even when performing 50,000 lookups:

```sql
EXPLAIN ANALYZE
SELECT * FROM (
  SELECT CASE WHEN i > 0 THEN 4294966982::OID ELSE 0::OID END AS oid, 'table name' AS table_name
  FROM generate_series(1, 50000) i(i)
) g
INNER LOOKUP JOIN pg_catalog.pg_class ON pg_class.oid = g.oid;
--                  info
-- --------------------------------------
--   planning time: 242µs
--   execution time: 344ms
--   distribution: local
--   vectorized: true
--   maximum memory usage: 1010 KiB
--   network usage: 0 B (0 messages)
--   sql cpu time: 337ms
--   regions: us-east1
-- 
--   • virtual table lookup join
--   │ nodes: n1
--   │ regions: us-east1
--   │ actual row count: 50,000
--   │ sql cpu time: 329ms
--   │ table: pg_class@pg_class_oid_idx
--   │ equality: (oid) = (oid)
--   │
--   └── • render
--       │
--       └── • project set
--           │ nodes: n1
--           │ regions: us-east1
--           │ actual row count: 50,000
--           │ sql cpu time: 8ms
--           │ estimated row count: 10
--           │
--           └── • emptyrow
--                 nodes: n1
--                 regions: us-east1
--                 actual row count: 1
--                 sql cpu time: 1µs
-- (31 rows)
```

It seems like there's some issue when iterating over descriptors in the lookup join while also iterating over descriptors in the virtual scan that causes execution to grind to a halt. Pinging @cockroachdb/sql-foundations incase y'all have any ideas.

**Comment by rafiss** [comment]
I have three somewhat unrelated points. See below.

---

Thanks to @mgartner's profile, I realized that the problem is with `syntheticprivilegecache.(*Cache).Get`. 

https://github.com/cockroachdb/cockroach/blob/87fc44f15e40c8e3af5207e73955f42c278c0b2b/pkg/sql/syntheticprivilegecache/cache.go#L71-L77

This is called whenever we need to access privileges for virtual tables - which is something we need to do when populating `pg_class`. The issue is that each call to the cache includes that call to `descs.PrefixAndTable` in order to get the descriptor version for the internal `system.system_privileges` table.

That's fine when doing a one-off privilege check, like what would happen for a `SELECT * from pg_roles`. But it becomes much more problematic when it is called once for each of the thousands of rows in the result of the query in the initial issue report.

Luckily, we can actually avoid accessing the synthetic privilege cache with this change:
```
diff --git a/pkg/sql/authorization.go b/pkg/sql/authorization.go
index 22bff759daa..24c3a0729d9 100644
--- a/pkg/sql/authorization.go
+++ b/pkg/sql/authorization.go
@@ -363,6 +363,9 @@ func (p *planner) CheckGrantOptionsForUser(
 func (p *planner) getOwnerOfPrivilegeObject(
 	ctx context.Context, privilegeObject privilege.Object,
 ) (username.SQLUsername, error) {
+	if d, ok := privilegeObject.(catalog.TableDescriptor); ok && d.IsVirtualTable() {
+		return username.NodeUserName(), nil
+	}
 	privDesc, err := p.getPrivilegeDescriptor(ctx, privilegeObject)
 	if err != nil {
 		return username.SQLUsername{}, err
diff --git a/pkg/sql/information_schema.go b/pkg/sql/information_schema.go
index 7e8e7f1973c..444a6282870 100644
--- a/pkg/sql/information_schema.go
+++ b/pkg/sql/information_schema.go
@@ -2931,26 +2931,23 @@ func userCanSeeDescriptor(
 		return false, nil
 	}
 
+	// Users can see objects in the database if they have connect privilege.
+	if parentDBDesc != nil {
+		if ok, err := p.HasPrivilege(ctx, parentDBDesc, privilege.CONNECT, p.User()); err != nil {
+			return false, err
+		} else if ok {
+			return true, nil
+		}
+	}
 	// TODO(richardjcai): We may possibly want to remove the ability to view
 	// the descriptor if they have any privilege on the descriptor and only
 	// allow the descriptor to be viewed if they have CONNECT on the DB. #59827.
-	canSeeDescriptor := false
 	if ok, err := p.HasAnyPrivilege(ctx, desc); err != nil {
 		return false, err
-	} else {
-		canSeeDescriptor = ok
-	}
-	// Users can see objects in the database if they have connect privilege.
-	if parentDBDesc != nil {
-		if !canSeeDescriptor {
-			if ok, err := p.HasPrivilege(ctx, parentDBDesc, privilege.CONNECT, p.User()); err != nil {
-				return false, err
-			} else {
-				canSeeDescriptor = ok
-			}
-		}
+	} else if ok {
+		return true, nil
 	}
-	return canSeeDescriptor, nil
+	return false, nil
 }
 
 func descriptorIsVisible(desc catalog.Descriptor, allowAdding bool) bool {
```

With these two changes, the latency goes back down to 117ms when I tried locally. (It was several minutes locally before.)

---

I think the example in https://gist.github.com/mgartner/4f01c3d61898e015bd2487e34b68edab is different than the original issue.

- It takes 6.197s on 23.1.8
- It takes 7.442s on 22.2.8 (so this is not a 23.1 regression)
- My patch above makes it take 5.020s (so the cause of the slowness is clearly different)

---

I tried @mgartner's example with the `generate_series` trick on v22.2, and it was quite slow. But indeed, it is much faster on v23.1. The 22.2 EXPLAIN is:
```
root@localhost:26257/defaultdb> explain analyze SELECT * FROM (
                             ->   SELECT CASE WHEN i > 0 THEN 4294966982::OID ELSE 0::OID END AS oid, 'table name' AS table_name
                             ->   FROM generate_series(1, 50000) i(i)
                             -> ) g
                             -> INNER LOOKUP JOIN pg_catalog.pg_class ON pg_class.oid = g.oid;;
                 info
--------------------------------------
  planning time: 1ms
  execution time: 3m10s
  distribution: local
  vectorized: true
  maximum memory usage: 540 KiB
  network usage: 0 B (0 messages)

  • virtual table lookup join
  │ nodes: n1
  │ actual row count: 0
  │ table: pg_class@pg_class_oid_idx
  │ equality: (oid) = (oid)
  │
  └── • render
      │
      └── • project set
          │ nodes: n1
          │ actual row count: 50,000
          │ estimated row count: 10
          │
          └── • emptyrow
                nodes: n1
                actual row count: 1
(23 rows)

Time: 190.152s total (execution 190.151s / network 0.001s)
```

So this is also some other (possibly a third) issue.

**Comment by rafiss** [comment]
I have created the PR for the above. It still does seem potentially worthwhile to figure out if the lookup join to `pg_namespace` could be avoided though. I think that would reduce latency even further, since there would be fewer descriptor lookups. Any thoughts on that @mgartner ?

**Comment by mgartner** [comment]
I believe the issue is that we don't collect statistics on virtual tables, so the optimizer makes some incorrect assumptions about how many rows will be produced at each step of the query plan. This causes the optimizer to choose a bad plan. Work to improve this is tracked by https://github.com/cockroachdb/cockroach/issues/27611.
