### ISSUE TITLE
backupccl: TestBackupRestoreAppend can hang under race on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#108800]
Observed in a CI run [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=11329876&problemId=4196) -- see the artifacts. The cluster used by this test was up for 3 hours.

Jira issue: CRDB-30644

**Comment by stevendanna** [comment]
One note is that the logs are filled with:

```
QueryIntent(ErrorIfMissing=true) found no intent, but did not error
```

But that was fixed in 8b71fdd740be and shouldn't be the actual problem(https://github.com/cockroachdb/cockroach/issues/108539#issuecomment-1675312955).

It also looks like we have an under-replicated range.

But, I'm wondering if we got stuck here: 

```
		sqlDB.RunWithRetriableTxn(t, func(txn *gosql.Tx) error {
			return txn.QueryRow("UPDATE data.bank SET balance = 200 RETURNING cluster_logical_timestamp()").Scan(&ts2)
		})
```

I added this retriable txn because the test was failing with txn refresh errors.  But, what if it is so contended that it never completes....
