### ISSUE TITLE
rangefeed: enable and improve rangefeed connection class

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#108992]
We have a separate RPC connection class for rangefeeds, but it's disabled by default via `kv.rangefeed.use_dedicated_connection_class.enabled`.

Rangefeeds can be high-volume during e.g. initial/catchup-scans, and have a high restart cost if they e.g. hit `NetworkTimeout`. We should consider enabling this class by default, plumbing it through not only for the DistSender connections but also the DistSQL flow, and use a higher network timeout since they're not as sensitive to availability following outages.

Jira issue: CRDB-30735

Epic CRDB-32846

**Comment by erikgrinaker** [comment]
cc @cockroachdb/cdc

**Comment by pav-kv** [comment]
Currently raft messages for a `Replica` are sent under `SystemClass` or `DefaultClass` which is [determined](https://github.com/cockroachdb/cockroach/blob/51f8f8e84d3075643bd8725f7e10d9af41fa4cbb/pkg/kv/kvserver/replica_init.go#L396) from the range's key span.

We can introduce a separate `RaftClass` that is independent of the range, then `RaftTransport` would operate only under this class instead of [all the classes](https://github.com/cockroachdb/cockroach/blob/8f975693228f7a676204594540973de9494c54fb/pkg/kv/kvserver/raft_transport.go#L152).

Do we want to preserve the system/default distinction at this level though, to separate raft traffic for system ranges vs other ranges? I.e. do we want just a single `RaftClass`, or add some combinatorics and have `SystemRaftClass` and `DefaultRaftClass`?

In the latter case, do we want to replace the enum by a bitmask so that more combinatorics is possible?

```golang

// ConnectionClass is a bitmask:
//	- 1 bit for system/default distinction
//	- 2 bits for ConnectionStream (or more if we want to "reserve" for more types)
type ConnectionClass int8

// ConnectionStream is the "logical" class for the connection.
// Can be Rangefeed, Raft, Snapshot, or "all other" RPCs.
type ConnectionStream int8

func (c ConnectionClass) IsSystem() bool {
	return int8(c) & 1 == 0
}

func (c ConnectionClass) Stream() ConnectionStream {
	return ConnectionStream((int8(c) >> 1) & 3)
}

... // other helpers
```

**Comment by pav-kv** [comment]
NB: more classes means more TCP connections per pair of nodes. We shouldn't introduce too many.

**Comment by pav-kv** [comment]
My understanding of #74222 is that the `RangefeedClass` is a stopgap for mitigating OOMs in the older rangefeed architecture where every range had a dedicated gRPC stream.

If I understand correctly, the premise of this issue is to "promote" this class from a stopgap to something that gives more benefits. SGTM.

From https://github.com/cockroachdb/cockroach/issues/111262#issuecomment-1878607078, my take is that we can remove the [special casing](https://github.com/cockroachdb/cockroach/blob/0be08e7e78bd8c6e42885bf374ff604f0ea8926e/pkg/rpc/context.go#L1787-L1793) of the window size for `RangefeedClass`. Can be done as part of this issue.

**Comment by erikgrinaker** [comment]
Yeah, I think the specific actions we can take here are:

* Remove the setting, and always use a separate rangefeed connection class.
* Remove the window special casing, now that mux rangefeeds are used unconditionally.
* Consider higher network and heartbeat timeouts -- we don't need to aggressively detect failures and fail over for rangefeeds, since they are less latency sensitive and have a high restart cost (have to restart the entire changefeed).
* Use the rangefeed class for the DistSQL flows too (otherwise, only node-local traffic from the DistSQL processor will use the rangefeed class in the common case, and inter-node DistSQL traffic will use the default class).

Wdyt @miretskiy?

Why use a separate rangefeed class? I think we want to split off the main classes of "bulk" traffic (rangefeeds and Raft) from foreground RPC requests, such that e.g. large bulk transfers will have less of an impact on read requests.

**Comment by pav-kv** [comment]
- [ ] Move some critical rangefeeds to the system class

**Comment by pav-kv** [comment]
> Use the rangefeed class for the DistSQL flows too (otherwise, only node-local traffic from the DistSQL processor will use the rangefeed class in the common case, and inter-node DistSQL traffic will use the default class).

@miretskiy Could you give some code pointers to where these `DistSQL` connections happen?

**Comment by miretskiy** [comment]
@pav-kv -- I believe that happens when you make a `transport.NextInternalClient` (newTransportForRange) in dist sender rangefeed.

**Comment by pav-kv** [comment]
Yeah, that would be the line that I updated here: https://github.com/cockroachdb/cockroach/pull/117730/files#diff-0774117800fc8884b0ef1dc4344112bea392a465c5ea9b0903ac3369d711bf33R758. Though it seems like Erik means some other RPC connection (in `DistSQL` rather than `DistSender`).

**Comment by pav-kv** [comment]
I browsed the code for a bit to see if there is an easy way to plumb the connection class, but it's not apparent to me. Help from SQL and changefeed teams would be appreciated. @miretskiy @yuzefovich

My understanding:
1. [startDistChangefeed](https://github.com/cockroachdb/cockroach/blob/0b1f895f4cdd1e7787bb2507044d34e6e245e30b/pkg/ccl/changefeedccl/changefeed_dist.go#L220-L220) is roughly where the changefeed flow originates from
2. it creates a [plan](https://github.com/cockroachdb/cockroach/blob/0b1f895f4cdd1e7787bb2507044d34e6e245e30b/pkg/ccl/changefeedccl/changefeed_dist.go#L255-L256) and a bunch of other things, and
3. [runs](https://github.com/cockroachdb/cockroach/blob/0b1f895f4cdd1e7787bb2507044d34e6e245e30b/pkg/ccl/changefeedccl/changefeed_dist.go#L312) the plan
4. which [sets up some flows](https://github.com/cockroachdb/cockroach/blob/55a7848cf47ac961688419b970ba3e28d82b93c6/pkg/sql/distsql_running.go#L863-L865)
5. which creates [runnerRequests](https://github.com/cockroachdb/cockroach/blob/55a7848cf47ac961688419b970ba3e28d82b93c6/pkg/sql/distsql_running.go#L552-L573) and runs them
6. which, finally, [sets up](https://github.com/cockroachdb/cockroach/blob/55a7848cf47ac961688419b970ba3e28d82b93c6/pkg/sql/distsql_running.go#L120) and RPC connection

Currently step (6) uses `rpc.DefaultClass` for the connection. We would like it to be `rpc.RangefeedClass` for changefeeds.

This can be achieved by passing some information down to step 6 (unless it already has some information in its various fields that makes this distinction possible). A couple of approaches:
- [worse?] Step 6 understands that this is a **changefeed** plan/flow/request/connection/whatever, so uses a custom connection class for it. This seems like a leaky abstraction approach.
- [better?] Have a more generic way of passing just **the connection class** from steps 1-3 (changefeed) all the way down through 4-6 (DistSQL).

---

I haven't looked at the outbox side of things. I'm guessing I would need help there too.

**Comment by erikgrinaker** [comment]
FWIW, I think the main concern is getting the outbox connection class right, since this is where the actual rangefeed data stream is sent. I don't think it's a big deal if the flow setup goes across `DefaultClass`, since it's a small request and not particularly latency-sensitive -- but if we're going to be plumbing through the connection class anyway, we may as well use it for the setup too, and I think it's more understandable that way.

**Comment by erikgrinaker** [comment]
Btw, there's also another source of bulk rangefeed traffic: changefeed initial scans, which emit existing table data to the changefeed before starting the actual rangefeeds. These should probably go across the rangefeed class too, to fully separate off changefeed traffic. These are just plain `Export` RPC requests that are sent here:

https://github.com/cockroachdb/cockroach/blob/c926799fced26385d2bd2804e7fcdb7ff8b5b7a6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L217

Unfortunately, there's currently no way to specify which class to use, the determination is made inside the DistSender based on the keyspan -- so we'll need some plumbing for this too:

https://github.com/cockroachdb/cockroach/blob/b2b8d7839ff564ad8fb5699d1f4ecc81926aa94a/pkg/kv/kvclient/kvcoord/dist_sender.go#L2291

**Comment by yuzefovich** [comment]
I agree with Erik - in DistSQL we establish connections at two different steps in the flow lifecycle:
- during the setup of the distributed plan - the gateway node establishes connections to all other nodes to perform the setup (`SetupFlowRequest`). This is done only once and almost no information is communicated on this connection.
- each DistSQL "producer" processor ("outbox") establishes a connection to a DistSQL "consumer" processor ("inbox") on another node - this is done in `GetConnForOutbox`. This is done by each pair of connected processors in the distributed plan, and this is where all of the intermediate information gets sent in the DistSQL flow.

Teaching only the latter about a different connection class would be sufficient.

**Comment by pav-kv** [comment]
Discussed with the team offline. Punting the last 2 action items from [this](https://github.com/cockroachdb/cockroach/issues/108992#issuecomment-1878775104) list, for reasons:

#### DistSQL flows

We realized that changefeed sends the bulk traffic directly to the **sink** (that's what makes it scale). `DistSQL` flows only transfer control information, like checkpoints. In the common case, the amount of this data is small.

Exception: core changefeed (see [comparison](https://www.cockroachlabs.com/docs/v23.1/change-data-capture-overview) with the enterprise changefeed). For core changefeeds, the bulk traffic goes through `DistSQL` and the gateway node. It potentially could carry large amount of data, but is not recommended for use in such cases (production use, or with large / frequently updated tables) - because it's bottlenecked by the gateway.

#### Custom RPC settings and timeouts

There is no evidence timeouts happen frequently, esp. after we increased the default timeout in #109578.

**Comment by pav-kv** [comment]
@erikgrinaker considering this done for now? We could also tweak gRPC settings for the `RANGEFEED` class (timeouts etc), but I don't know if it's needed - do we have any data?

**Comment by erikgrinaker** [comment]
Let's punt that for now. We don't have a pressing need for it with mux rangefeeds. We can revisit as needed.
