### ISSUE TITLE
kvserver: TestProcessSplitAfterRightHandSideHasBeenRemoved failed with panic on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#109230]
See failure on unrelated [CI build](https://teamcity.cockroachdb.com/viewLog.html?buildId=11434673&problemId=4141).

Jira issue: CRDB-30836

**Comment by pavelkalinnikov** [comment]
```
a panic has occurred!
runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  |     GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  |     GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  |     GOROOT/src/runtime/signal_unix.go:839
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).runPrelude
  |     github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:490
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
  |     github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:451
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
  |     github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*StoreGossip).asyncGossipStore
  |     github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_gossip.go:334
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*StoreGossip).MaybeGossipOnCapacityChange
  |     github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_gossip.go:414
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).leasePostApplyLocked
  |     github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:500
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleLeaseResult
```

Looks like the `Stopper` here is nil: https://github.com/cockroachdb/cockroach/blob/32a9468acfcdfb85cef465101677200dfd34dbc5/pkg/util/stop/stopper.go#L490

Doesn't seem replication-related, but I will look a bit more.

**Comment by pavelkalinnikov** [comment]
This stopper is only inited in one place. And can be left nil: https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvserver/store.go#L2121-L2124

This is probably what happened.

**Comment by pavelkalinnikov** [comment]
@kvoli (tagging you since you did some refactoring in #93945)

Do you have an intuition why the `stopper` can be nil while `storeGossip` is not nil? This looks strange because both are initialized only in one place, and both are gated by `s.cfg.Gossip != nil` check:

https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvserver/store.go#L1549-L1550

My only guess is that we start raft a bit before this `s.storeGossip.stopper` is initialized: https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvserver/store.go#L2097

So raft processors can see nil.

**Comment by kvoli** [comment]
Nice find @pavelkalinnikov. The refactor of system gossip was mostly mechanical here, so I don't have much intuition on it.
