### ISSUE TITLE
server: the "nodes" status API endpoint should work with secondary tenants with capability `can_view_node_info`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#110023]
Found while investigating #110001.

**Describe the problem**

When `TestNodeStatusResponse` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/nodes` endpoint:

```
    nodes_test.go:113: expected privilege error, got status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method Nodes not implemented",
          "code": 12,
          "message": "method Nodes not implemented",
          "details": [
          ]
        }, error: <nil>
```

**How to reproduce**

from #110008 reset `DefaultTestTenant` in `TestNodeStatusResponse`, run the test with a test tenant and observe the failure.

**Expected behavior**

Once the tenant is granted a suitable capability, the endpoint should work properly. It should retrieve the node details over the KV tenant connector over the network.

Epic CRDB-38968

Jira issue: CRDB-31228

**Comment by knz** [comment]
NB: the test `TestNodesGRPCResponse` is also affected.

**Comment by shubhamdhama** [comment]
@stevendanna, @dhartunian I've a small clarification for this and related issues like https://github.com/cockroachdb/cockroach/issues/110019 and https://github.com/cockroachdb/cockroach/issues/110018. Do we want to show nodes, ranges and range/{id} only for that particular tenant or should it behave just like system tenant behind an appropriate capability?

**Comment by dhartunian** [comment]
@shubhamdhama I think it should behave like the system tenant since we can't really partition "node" information by tenant. This information is used to populate the overview page in DB Console which doesn't really have a "tenant" view.

**Comment by dhartunian** [comment]
Not quite. I think range information can be partitioned by tenant since the keyspace is tenant-scoped, but, for instance, "gossip" is a node-to-node system and has no tenant-level meaning.

Looking at the API list in the epic, I think only range-related stuff should be partitioned, the rest of the items are system-tenant node-level data.

**Comment by cthumuluru-crdb** [comment]
`_status/nodes` endpoint was not implemented by `statusServer` which is used by secondary tenants. With changes in https://github.com/cockroachdb/cockroach/pull/131644, `_status/nodes` and `_status/nodes/{node-id}` endpoints work with secondary _shared_ tenants. Since nodes are shared by all secondary tenants, the behavior of these endpoints is similar to that of system tenant.

_External_ tenants only run SQL instances. Node information must be fetched using RPC calls. To enable `_status/nodes` and `_status/nodes/{node-id}`, `statusServer` implementation must be modified to make an RPC call using tenant connector. 

https://github.com/cockroachdb/cockroach/blob/d183df0301b3221b145780b73a1eb0052fb0a016/pkg/server/status.go#L1864-L1876

Similarly, profile (CPU, Heap) endpoints are also broken for _external_ tenants. In case of _external_ tenants, these endpoints should allow collecting profiles from SQL instances too. We may (most likely) need new endpoints to support such functionality. We have to spend sometime thinking about the user experience before implementing them for _external_ secondary tenants.

cc: @stevendanna, @dhartunian
