### ISSUE TITLE
sql: Passing multiple values in "IN clause" performance degradation

### ISSUE THREAD

**Issue by DHazel-CRL** [cockroachdb/cockroach#110175]
"SET optimizer_use_improved_computed_column_filters_derivation = true;" helps only cases like follows

select * from orders where order_nbr in ('XXXXXXXXXX','YYYYYYYYYYYYY')

but this doesn't work with following

select * from orders where order_nbr in (select order_nbr from orders where root_order_nbr='XXXXXXXXXXXXXXXX')

Related to:
[https://github.com/cockroachdb/cockroach/pull/103818](url)
[https://cockroachdb.zendesk.com/agent/tickets/16587](url)

**Environment:**
 - CockroachDB version 23.1.5

Jira issue: CRDB-31303

**Comment by mgartner** [comment]
@DHazel-CRL Do we have any more clarity on what the ask is here? I don't understand why this setting would be related to the query they provide, and what they mean by "this doesn't work".

If they have a slow query, please ask them to provide a statement bundle captured with `EXPLAIN ANALYZE (DEBUG) SELECT ...` so that we can investigate.

**Comment by msirek** [comment]
Hi @DHazel-CRL, the `optimizer_use_improved_computed_column_filters_derivation` setting only applies to IN lists which specify constant literal values.  For the query:
`select * from orders where order_nbr in (select order_nbr from orders where root_order_nbr='XXXXXXXXXXXXXXXX')`
This statement has an IN subquery, which is not supported for derivation of filters on computed columns.
