### ISSUE TITLE
schemachanger: investigate "could not validate removal of enum value" error

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#110827]
Investigate the following error.
```
TYPEDESC SCHEMA CHANGE job 900246837663891457: stepping through state failed with unexpected error: could not validate removal of enum value ‹×›: ‹×›
```

https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=1694444400&latest=1695052553&q=search%20index%3Dcc-app-crdb*%20severity%3DERROR%20%22schema%20change%20job%22%20%22stepping%20through%20state%20failed%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&workload_pool=standard_perf&sid=1695052686.480275

If it should have a PG error code, then add it, and stop logging it as an ERROR.

Jira issue: CRDB-31640

**Comment by Xiang-Gu** [comment]
This error is added [in this commit](https://github.com/cockroachdb/cockroach/commit/fe888db42f4b6e9c28117bc5a2f0e1b3e5160c26) with the intention of preventing the dropping of an enum value if that value is used in a column of ARRAY type.

It's actually already returned as a pg error [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/type_change.go#L1160-L1162). The culprit is that the query it used to determine "whether an enum value is being used in any row in the column in a table" uses `QueryRowEx`, which returns an error "unexpected multiple results" if there is more than one row, which is perfectly possible. 

I can take on this one.

**Comment by rafiss** [comment]
Thanks! nice find
