### ISSUE TITLE
storage: 23.2 premortem followups

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#110854]
In the premortem, we determined a few action items. I created a single issue to track these.

- [x] @sumeerbhola Double check the metamorphic test code coverage for the obsolete bit code paths.
- [x] @jbowens Double check multi-level compactions are exercised readily in the metamorphic tests. Consider boosting the probability of multi-level compactions in some metamorphic test runs to improve coverage.
- [x] @jbowens Give the sync.Pool use in LogWriter a second look.
- [x] @cockroachdb/storage audit all your TODOs ([pebble](https://gist.github.com/jbowens/528bebef0d24e4d2e1c21811e6b78922), [Cockroach](https://gist.github.com/jbowens/bc8651d04bc5677c49202a91a65c8256)):
  - [x] @sumeerbhola 
  - [x] @bananabrick 
  - [x] @itsbilal
  - [x] @RaduBerinde
  - [x] @jbowens
- [x] @itsbilal https://github.com/cockroachdb/cockroach/pull/111437

Non-blocking issues, as the testing here pertains to pieces that aren't shipping in 23.2:

- [ ] @itsbilal https://github.com/cockroachdb/pebble/issues/2711
  - [ ] https://github.com/cockroachdb/pebble/pull/2984
- [ ] @bananabrick Add metamorphic test support for excise ops
  - [ ] https://github.com/cockroachdb/pebble/pull/2924

Jira issue: CRDB-31649

**Comment by RaduBerinde** [comment]
Hi @jbowens - the script you used is problematic because it shows many TODOs that were later removed (and there are a lot of these when developing a new feature). Here are some that only look at what TODOs have been added since we branched from 23.1:
[pebble](https://gist.github.com/RaduBerinde/53d6235c4c93dc5d5cb59e4b1f49bbf6)
[cockroach](https://gist.github.com/RaduBerinde/616ace281f9d8114fe49a609ea808dd9)

**Comment by nicktrav** [comment]
@bananabrick @itsbilal - reminder about the TODO audit.

**Comment by nicktrav** [comment]
I shuffled around some of the tasks to indicate that some items shouldn't block GA.

**Comment by nicktrav** [comment]
We're all good here.
