### ISSUE TITLE
streamingccl: TestStreamPartition failed

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#111146]
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11894188?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-31789

**Comment by adityamaru** [comment]
@stevendanna can i randomly give this one to you, feel free to throw it back if you don't have the cycles.

**Comment by stevendanna** [comment]
I think what is going on here is a problem in the assumption with the test.  Namely, I don't think we can possibly detect a ClearRange if it was applied when the rangefeed isn't running.  While the test _usually_ sends the result when the rangefeed is running, in at least one case I've seen this happen:

1. Rangefeed start
2. Rangefeed shutdown because of a split
3. ClearRange sent
4. Rangefeed restarted

We don't observe the ClearRange because we weren't connected to raft at the time it comes in.  I'll look at how we can make this less flakey, but I don't think it is correctness issue.

**Comment by dt** [comment]
#112260
