### ISSUE TITLE
Unexpected Error for ascii()

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#111474]
**Describe the problem**

**To Reproduce**

```sql
CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
INSERT INTO t0 (c0) VALUES(1);

SET SESSION VECTORIZE=on;
SELECT * FROM t0, t1 WHERE ASCII('')>0; -- ERROR: ascii(): the input string must not be empty
SET SESSION VECTORIZE=off;
SELECT * FROM t0, t1 WHERE ASCII('')>0; -- {}
```

**Expected behavior**
The second query should return an error as well.

**Environment:**
 - CockroachDB version [CockroachDB CCL v23.2.0-alpha.00000000-dev-d7738743c955be36b1c9304a40d9e4e7b3edc4ad]
 - Server OS: [Ubuntu]
 - Client app [`cockroach sql`]

Jira issue: CRDB-31914

**Comment by yuzefovich** [comment]
Thanks for the report! This difference happens because the vectorized cross joiner doesn't short circuit consuming the left input in some cases (like when the right input is empty for INNER join). I'll have a patch shortly.

**Comment by DrewKimball** [comment]
@bajinsheng It's worth mentioning that while this case uncovered an inefficiency in the vectorized execution engine, it isn't considered a correctness bug. This is because CRDB intentionally doesn't guarantee that an expression will be evaluated if it doesn't contribute to the result of the query. It doesn't guarantee that the expression _won't_ be executed in that case, either.

There are some guarantees, that don't apply to this example:

- CASE/IF branches are only evaluated if their guard condition evaluates to true, unless they are leakproof.
- A volatile CTE will be executed exactly once, even if it's referenced more or less than one time.

**Comment by bajinsheng** [comment]
@DrewKimball Thanks for the explanation! I will cancel other bug reports about unthrown exceptions.
