### ISSUE TITLE
session_transfer: investigate failure to prepare a statement during session migration

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#111592]
**Describe the problem**

A serverless cluster is logging the message:
```
could not prepare statement during session migration: AS OF SYSTEM TIME must be provided on a top-level statement
```

whenever it attempts a session migration.

**To Reproduce**

Don't have a repro yet.

**Expected behavior**

The statement should be properly prepared.

**Additional context**
https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search%20index%3Dcc-app-crdb*%20%22could%20not%20prepare%20statement%20during%20session%20migration%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&workload_pool=standard_perf&sid=1696267040.759938

Jira issue: CRDB-31981

**Comment by andyyang890** [comment]
Dumping some preliminary findings from last week:

---

When I was investigating this, I thought it might be because this code does not call `handleAOST`:
https://github.com/cockroachdb/cockroach/blob/a2eb9022fd86e09e38217294a7e9498a253c9536/pkg/sql/conn_executor_prepare.go#L312-L321
and then later this code does not call `handleAOST` either:
https://github.com/cockroachdb/cockroach/blob/6cd3fa8960cf4fd504aa1df011cd7450830f3486/pkg/sql/conn_executor_exec.go#L923-L930

I haven't been able to come up with a repro to verify this hypothesis though.

---

Also, the error seems to come from here:
https://github.com/cockroachdb/cockroach/blob/108568e6e4cfdc2392a78e9282dcab19df0913e0/pkg/sql/render.go#L103-L115

which appears to only be used for `SCRUB` statements:
https://github.com/cockroachdb/cockroach/blob/14301f0d88112f04749bec5ad23a06269a3c74a2/pkg/sql/scrub.go#L212

It could also come from here, but I noticed this one was a panic so I initially ruled it out, but I guess it could have been `recover`-ed?
https://github.com/cockroachdb/cockroach/blob/b387ed027c9e5358e475ffddbe3e53200b74ab4d/pkg/sql/opt/optbuilder/select.go#L1423-L1426

**Comment by rafiss** [comment]
I don't have a way to repro this, so I am adding more logs, and we will debug this further when we see it again: https://github.com/cockroachdb/cockroach/pull/114444
