### ISSUE TITLE
Cockroach CLI wont work.

### ISSUE THREAD

**Issue by kakarot-dev** [cockroachdb/cockroach#111924]
**Describe the problem**
I downloaded the v23.1.10 and v23.1.11 versions, extracted it, and moved it the bin file as told. But when i run it, it doesnt give any output,just that the process keeps running.

**To Reproduce**
Just extract using `tar -xvzf` and move it to the 

**Expected behavior**
 I expect it to atleast respond.

**Additional data / screenshots**
![image](https://github.com/cockroachdb/cockroach/assets/76399483/46042a40-51e6-4318-9da6-78a540b806da)
![image](https://github.com/cockroachdb/cockroach/assets/76399483/498afb8d-147f-4963-b9c8-18cbc19d09a6)

**Environment:**
 - CockroachDB version 23.1.10,23.1.11
 - Server OS: Ubuntu
 - Client app cockroach

CPU info if this is of any help 
![image](https://github.com/cockroachdb/cockroach/assets/76399483/980f7275-a139-4af3-87d0-e636ae03483a)

Jira issue: CRDB-32135

**Comment by yuzefovich** [comment]
What happens when you run `which cockroach`?

**Comment by kakarot-dev** [comment]
im closing this issue, as ive switched to mongo db. Ive tried all installation methods, none were working. You have a good prodcut for the cloud, but doesnt really help when your support team isnt respondant and self hosting is a pain! 
Anyways thanks for responding ig

Also, "which cockroach" just shows the directory i had set the cockroach executable in.

**Comment by dikshant** [comment]
@kakarot-dev  It's not clear what you are trying to do here. Since you moved cockroach binary to `/usr/local/bin`, the next step would be one of two:

1) start a cockroachdb server. You can start a simple server by doing:
```
cockroach start-single-node --insecure
```
Also documented here: https://www.cockroachlabs.com/docs/stable/cockroach-start-single-node

2) Connect to a existing cockroachdb server. You can do this by:
```
cockroach sql --url $COCKROACHDB_URL
````

You can also do 1) followed by 2 by opening another terminal and running `cockroach sql` from there.
