### ISSUE TITLE
server: server orchestrator can fail to start tenant

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#112077]
Seen [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12121007&buildTypeId=Cockroach_BazelExtendedCi) on #110932 that shouldn't cause this flake:
```
Failed
=== RUN   TestRevertTenantToTimestamp/reverts_changes_inside_a_tenant
    stream_ingestion_manager_test.go:85: condition failed to evaluate within 45s: pq: service unavailable for target tenant (target)
    --- FAIL: TestRevertTenantToTimestamp/reverts_changes_inside_a_tenant (46.91s)
```
I'm assuming we want to skip this test under stress.

Jira issue: CRDB-32225

**Comment by stevendanna** [comment]
Thanks for taking a look. I won't surprise me if we see some flakes here under stressrace since this test depends on starting and stopping shared process tenants which I think we've seen occasionally take a very long time under stressrace.

**Comment by stevendanna** [comment]
I'm reopening this as I've now seen it on a few other CI runs.

**Comment by stevendanna** [comment]
It doesn't appear to me to be a problem with the revert but rather a problem with the service startup not detecting the service change.

**Comment by stevendanna** [comment]
OK. This test has two problems. The first will be fixed by:

https://github.com/cockroachdb/cockroach/pull/112166

However, I believe the second is a bug in this change: 

https://github.com/cockroachdb/cockroach/pull/112001

Namely, because shutdown is managed by the server SQL process itself, the following can happen:

1. Shutdown tenant 1
2. Watcher gets notification of shutdown but doest nothing with it
3. Tenant 1 starts shutdown but does not fully complete it
4. Startup tenant 1
5. Watcher gets notification of startup but sees that tenant 1 is still an active server so does nothing
6. Tenant 1 finishes shutdown
