### ISSUE TITLE
c2c: high water mark does not advance during c2c/BulkOps/full roachtest

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#112737]
It seems unacceptable to fall behind by an hour during a series of 30GB imports and rollbacks. We import the bulk of the data as the imports are happening, but for whatever reason, about half of the partitions spans according to the replication-frontier grind to a halt — the HWM does not advance for the duration of the workload.
![image](https://github.com/cockroachdb/cockroach/assets/35438895/9aef7f7e-091a-4674-9a2a-1268f2d12f08)
![image](https://github.com/cockroachdb/cockroach/assets/35438895/51204d82-64a1-471e-bf9f-7b1b95247d51)

Jira issue: CRDB-32568

**Comment by stevendanna** [comment]
My current theory for why this happens is that a combination of:

1) Rapid splits caused by both range growth and explicit splitting during the IMPORT; and
2) Destination-side replanning

leads to a large number of catchup scans getting queued up all at once.  Until those catchup scans complete, the replicated timestamp doesn't move since we don't get resolved timestamps during a catchup scan.

**Comment by msbutler** [comment]
closing as #114070 merged
