### ISSUE TITLE
changefeedccl: faulty Changefeeds Commit Latency graph and metric

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#112947]
See internal [Slack thread](https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1697484030130899).

Following a changefeed restart, the Changefeeds → Commit Latency p99 graph (`changefeed.commit_latency-p99`) climbed to 12 minutes, and took 4 hours to drop back down to the nominal 3 seconds. There are at least two problems here:

1. The graph uses a sum across all nodes, which is non-sensical for this metric. The max value across any node is ~2 minutes, and this is a 6-node cluster, so the metric is off by a factor of 6. I don't know if there's a good way to aggregate histograms across nodes (we'll have to account for the different distributions across nodes), but at the very least we can use e.g. the max value across nodes.

2. The catchup scans completed in about 10 seconds, so it's not clear why the metric would report several-minute commit latencies for emitted events for hours afterwards. Is this metric computed correctly?

<img width="945" alt="Screenshot 2023-10-24 at 11 08 10" src="https://github.com/cockroachdb/cockroach/assets/644420/fc471fcb-9b60-49bb-86a6-448c1d3b2df2">

<img width="956" alt="Screenshot 2023-10-24 at 11 08 19" src="https://github.com/cockroachdb/cockroach/assets/644420/4c330498-6df1-4fbc-b49d-25b6f35ef37f">

Jira issue: CRDB-32686

**Comment by jayshrivastava** [comment]
The max commit latency is very high. 

<img width="985" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/28dd2e92-c244-4ea0-9982-f0735c699028">
<img width="1211" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/25029027-af66-4e6d-a07b-1914bf5f943a">

**Comment by amruss** [comment]
Thanks Eric, we're considering a larger observability improvement initiative, which would include this issue, as part of the 24.1 planning cycle

**Comment by amruss** [comment]
Moving back into triage since we've had another customer run into this

**Comment by erikgrinaker** [comment]
As a simple first step, could we use max aggregation instead of sum aggregation? That's still not entirely correct, but it's far less wrong, and is a one-line change.

**Comment by jayshrivastava** [comment]
I ran a tpcc 1000 test from this [branch](https://github.com/jayshrivastava/cockroach/commits/debug/commit-latency). 

The main log line is this
https://github.com/jayshrivastava/cockroach/commit/f62760729fa5c04bce06ea400ed1d1dab6928ed4

This is the graph: 

<img width="1197" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/c862ab3c-17bf-4379-928e-7f67b5e1c986">

The latencies logged are here:
https://drive.google.com/file/d/1_6P1mnezz8hTo8LJx1gGn8u-kMPcy6bR/view?usp=sharing

I need more time to analyze the logs, but it seems that there are a lot of rows which have identical mvcc values.

**Comment by jayshrivastava** [comment]
Spent the last couple days investigating this. 

1. The reason that the graphs cap at 5 minutes is because that's the max histogram bucket. We should increase this upper bound because its possible to have high commit latencies. After call, the commit latency is emit timestamp - mvcc timestamp, where the mvcc timestamp is old.
2. See https://cockroachlabs.slack.com/archives/C063CP41TG9/p1699455877083339. There is some difference between histograms (not used by changefeeds) and agg histograms (used by changefeeds). It looks like the graphs generated from the agg histograms can be wrong. See below - `commit_latency_2` is a normal histogram. `commit_latency` is an agg histogram

![image](https://github.com/cockroachdb/cockroach/assets/18633281/98c104ae-76a1-49b7-aa6a-ce84a21926be)
![image](https://github.com/cockroachdb/cockroach/assets/18633281/c7289b75-03cd-462c-b6e0-a03d0288865b)

![image](https://github.com/cockroachdb/cockroach/assets/18633281/25a07ae1-6b91-4fcd-bc32-b6c39789efc3)

**Comment by jayshrivastava** [comment]
I want to understand the discrepancy with histograms. It undermines every graph of commit latency we see, such as the one Eric posted originally in this issue.

**Comment by abarganier** [comment]
I'll be fixing this as part of https://github.com/cockroachdb/cockroach/issues/114175

**Comment by abarganier** [comment]
Did https://github.com/cockroachdb/cockroach/issues/114175 fix this? Can we close?
