### ISSUE TITLE
Redact the API secret for Confluent Cloud sinks from show jobs output

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#113503]
**Describe the problem**

When you run `SHOW CHANGEFEED JOB {job id};` on a changefeed to a `confluent-cloud` sink, the API secret is not redacted in the `SHOW` output. This is also the case for regular `SHOW JOBS`.

**To Reproduce**

1. Create a Confluent Cloud kafka sink, and create API keys.
2. Create a changefeed to the sink passing the API key and secret.
3. Run `SHOW CHANGEFEED JOB` on that changefeed job.

**Expected behavior**
The `api_secret` parameter value is redacted for a `SHOW` command.

CockroachDB v23.2.0-alpha.4

Jira issue: CRDB-33028

**Comment by wenyihu6** [comment]
It looks like the api_key and api_secret do not show up if we create an external connection before creating the changefeed. But it does show up if we create the changefeed using sinkURI directly. 
```
CREATE EXTERNAL CONNECTION confluent1 AS 'confluent-cloud://nope?api_key=fee&api_secret=bar'
CREATE CHANGEFEED FOR foo INTO 'external://confluent1/
SHOW CHANGEFEED JOBS
```
gives 
```
[[921728271371862017 CREATE CHANGEFEED FOR TABLE foo INTO 'external://confluent1/' root running NULL 2023-11-30 15:52:25.316143 +0000 UTC NULL NULL 2023-11-30 15:52:25.323003 +0000 UTC NULL  external://confluent1/ {d.public.foo} NULL json]]
```

But it does show up if we create changefeed using the sinkURI directly. 
```
CREATE CHANGEFEED FOR foo INTO 'confluent-cloud://nope?api_key=fee&api_secret=bar'
```
gives
```
[[921728158211244033 CREATE CHANGEFEED FOR TABLE foo INTO 'confluent-cloud://nope?api_key=fee&api_secret=bar' root running NULL 2023-11-30 15:51:50.782255 +0000 UTC NULL NULL 2023-11-30 15:51:50.782255 +0000 UTC NULL  confluent-cloud://nope?api_key=fee&api_secret=bar {d.public.foo} NULL json]]
```

Is this the intended behaviour or should we redact api_secret? `SHOW CREATE EXTERNAL CONNECTION` also does not redact the secrets but it seems to be the intended behaviour since it is admin only.
