### ISSUE TITLE
ui, server: don't use activity tables if sql.stats.response.show_internal.enabled is true

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#114460]
The activity tables don't allow internal statements to be written to them. When users turn on the cluster setting `sql.stats.response.show_internal.enabled` they would expect to see internal statements returned in their sql stats response but will not see any if we service requests using the activity table. The CombinedStatementStats api chooses to service requests using the activity tables as its first choice but if `sql.stats.response.show_internal.enabled` is true we should disallow the activity tables from being used to service the request.

Jira issue: CRDB-33518

**Comment by maryliag** [comment]
This is by design. This issue should be instead: check the request value for internal, and if true, skip the select on the activity table. 

This can be done by adding a new check [here](https://github.com/cockroachdb/cockroach/blob/392a28ba25eba61aaf7805b9d32b000820b610a8/pkg/server/combined_statement_stats.go#L226-L236) and return false is the request is requesting internal

https://github.com/cockroachdb/cockroach/blob/392a28ba25eba61aaf7805b9d32b000820b610a8/pkg/server/combined_statement_stats.go#L226-L236

**Comment by xinhaoz** [comment]
Good catch @maryliag. I updated the issue to prescribe the change above.
