### ISSUE TITLE
Blank error message field on error when clicking databases page

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#114582]
@nicktrav reported that while testing, he clicked on the "databases" page in the console and saw the following. Note the error message is empty. This looks like a bug as I would expect something that can help the user figure out / understand what the issue is.

![image](https://github.com/cockroachdb/cockroach/assets/110843721/30ec346b-0d15-491a-89e8-d8ccf8994b99)

Jira issue: CRDB-33576

Epic CRDB-20791

**Comment by abarganier** [comment]
These pages are fueled by the sql-over-http API. 

Seems that many of the queries issued are timing out. My guess is that the issue is with the queries themselves, rather than with the API.

When loading the Databases page, the network tab provides some good insight into the queries causing timeouts. For example, here's just one that I cherry-picked:
```
SELECT * FROM (SELECT
  ti.created_at,
  us.last_read,
  us.total_reads,
  '168h0m0s' as unused_threshold,
  '168h0m0s'::interval as interval_threshold,
  now() - COALESCE(us.last_read AT TIME ZONE 'UTC', COALESCE(ti.created_at, '0001-01-01')) as unused_interval
FROM "kv".crdb_internal.index_usage_statistics AS us
JOIN "kv".crdb_internal.table_indexes AS ti ON (us.index_id = ti.index_id AND us.table_id = ti.descriptor_id)
WHERE $1 != 'system' AND ti.is_unique IS false)
WHERE unused_interval > interval_threshold
ORDER BY total_reads DESC;
```

If I had to guess, some of the `crdb_internal` handlers used to serve these queries are not scaling well in clusters that have large numbers of nodes. That could make the bug tricky to track down. Maybe there are some crdb_internal tables that all the queries timing out have in common - that would be a good place to start.

**Comment by williamkulju** [comment]
FYI, the problem described here is closely related if not the same: https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1701120348498899
