### ISSUE TITLE
Unavailable metrics on the Databases page

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#114690]
On our scale testing cluster, there are unavailable metrics on the Databases page.

Visit the Databases page on our scale cluster and notice the following:

<img width="1009" alt="image" src="https://github.com/cockroachdb/cockroach/assets/81193618/b7e337d0-f654-4847-8c15-069ed2e4c633">

Jira issue: CRDB-33630

**Comment by koorosh** [comment]
Resolved by updating `cluster-ui` version to correct 23.2 version.
Now, only empty databases show regions/nodes as `(unavailable)`.

**Comment by koorosh** [comment]
Requests times out on Databases page.
Cluster with 12 nodes
Range count for single DB: 36945

**Comment by abarganier** [comment]
Note: once we have this fix, there are requests to provide some external guidance regarding the page/fixes to help shore up confidence. We can discuss once we get there how to best approach.

**Comment by xinhaoz** [comment]
Just wanted to update with some progress from investigation, and so I don't lose track of the todos.

There are misc. improvements that can be made to improve response times, some of them are lower hanging fruit and some of them need more refactoring / additions to some builtins. I will add more improvements as I find them.

Databases overview page
- [ ] Improve [getDatabaseReplicaAndRegions query](https://github.com/cockroachdb/cockroach/blob/b106b81ab88bee19de121463195f5cfa27f2faae/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L365-L378). Currently this query is slow as it appears to be performing some string manipulation gymnastics on the entire ranges table `replica_localitites` column - we can rewrite using `substring()` with a regex and ensure that it runs only on the result set for the requested db's ranges.
- [ ] The `getDatabaseReplicaAndRegions` from the previous point is currently batched with up to 5 other queries. It can run a lot slower than the oher queries in the batch causing the entire request to timeout. When that timeout is hit we lose the entire response. We should separate this slower query into its own request so we at least get other db details quickly.
- [ ] Requesting span stats can be an expensive operation when there are lots of ranges, the response containing [db's span stats](https://github.com/cockroachdb/cockroach/blob/b106b81ab88bee19de121463195f5cfa27f2faae/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L506) is under utilized. The only fields used for the overview page are `approximate_disk_bytes` and `range_count`. The range count can be obtained using the alternative query `SELECT count(*) FROM [SHOW RANGES FOR DATABASE 'db']`
- [ ] Additional to the above, `approximate_disk_bytes` is not part of MVCC stats calculation. When requesting span stats, we can provide a flag to skip MVCC stats calculation. If we're just requesting `approximate_disk_bytes` for the overview page we can skip calculating mvcc stats. This improvement needs to tweak the builtin being used to accept this flag to plumb down to the server requests.

Tables overview page
- [ ] The [getTableReplicas query](https://github.com/cockroachdb/cockroach/blob/b106b81ab88bee19de121463195f5cfa27f2faae/pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts#L440-L447), which is used to produce a unique set of stores for the table, can cause a max size exceeded error as it is currently returning 1 row per table range. This query should be rewritten so that only a single list of distinct store ids is produced.

**Comment by xinhaoz** [comment]
Closing this since improvement to nodes/region query merged. Additional improvemetns are detailed in a new issue:
https://github.com/cockroachdb/cockroach/issues/120064
