### ISSUE TITLE
*,storage: avoid block cache evictions by large/background scans

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#114661]
Currently operations like backup, table stats computations and internal scans for the consistency checker will read all of the data in a range or ranges or entire table/cluster en masse, and in a pattern (full scan) unrelated to the workload access pattern of foreground traffic on the cluster. Such scans could potentially be evicting cached data that _is_ being accessed by the workload, causes spikes in cache misses after they run.

We should potentially set a flag on the read operations done by these bulk operations, potentially even on sql full table scans of larger tables, indicating that they are bulk scans and should thus not cause cache evictions. This would presumably need to be added to the batch request/header and then passed to every storage access/iterator creation (or added to the ctx?) and plumbed internally in pebble as well to the block cache.

Maintaining high block cache hit rates is anticipated to be increasingly important when we start having more files in the lsm hosted on slower external storage.

Jira issue: CRDB-33616

**Comment by jbowens** [comment]
Pebble's block cache uses a "scan-resistant" algorithm called Clock-PRO. In practice, we haven't seen foreground traffic's block cache hit rates suffer due to bulk operations. For example, on the telemetry cluster, the effect of a full backup on the overall block cache hit ratio is stark:

<img width="831" alt="Screenshot 2023-11-21 at 4 41 33 PM" src="https://github.com/cockroachdb/cockroach/assets/867352/5a018c62-358a-45e6-b6a5-74c5b6788432">

But it appears to be driven by the backup's misses, as the volume of hits remains largely unperturbed.

<img width="832" alt="Screenshot 2023-11-21 at 4 41 39 PM" src="https://github.com/cockroachdb/cockroach/assets/867352/20704040-898f-49d0-a7ee-0eb58ee48adf">

**Comment by dt** [comment]
Ah, good to know. I'll close this for now and we can re-open it if we find that isn't working as expected.
