### ISSUE TITLE
kv: include conflicting request information in latch manager traces/logs

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#114601]
The latch manager contains trace events and logs for conflicts in `Manager.waitForSignal`. This observability uses `latch.String` to present the span and the strength of the conflicting latch. However, it does not present information about the specific requests holding the latch or the requests acquiring the latch.

We should push down `*BatchRequest`s into the `spanlatch.Manager` and include the output from `BatchRequest.SafeFormat` in `latch.SafeFormat`.

Jira issue: CRDB-33589

Epic CRDB-34227

**Comment by nvanbenschoten** [comment]
When doing this, we should store the `*BatchRequest` on the `Guard` and change `latch` from storing a `*signals` to a `*Guard`. This will avoid bloating the size of the `latch` struct.

**Comment by nvanbenschoten** [comment]
Will go nicely with https://github.com/cockroachdb/cockroach/issues/114475.

**Comment by lyang24** [comment]
Hi Nathan, I thought about two ways of implementing the push down of `*BatchRequest`, which path do you recommend?

1.  Make `SequenceReq` that take `*BatchRequest` as new parameter
2. Since majority of fields in Request struct at pkg/kv/kvserver/concurrency/concurrency_control.go are derived from batchRequest we can refactor Request struct to below this will require us changing how request is constructed in test.
```
type Request struct {
	BatchRequests *kvpb.BatchRequest
	MaxLockWaitQueueLength int
	PoisonPolicy poison.Policy
	LatchSpans *spanset.SpanSet
	LockSpans *lockspanset.LockSpanSet
}
```
