### ISSUE TITLE
SQL Activity session unable to find session

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/cockroach#114821]
**Describe the problem**

When you go to `SQL Activity` and click on `Sessions`, a list of sessions is displayed. You can filter these by idle, closed or active. By default, this page displays all sessions, and if you click on a session that's been closed, it takes you to a different page with the session details, it shows the session details for about 2 seconds and then the page errors out saying it is unable to find session.

This behavior is only observed if you choose to view the details for a closed session. If you click on a idle or active session, the session details are shown and do not disappear after a 2 seconds.

**To Reproduce**

Go to `SQL activity` -> `Sessions tab` -> `Click on any closed session` -> Session details are displayed with all information then without clicking anything the session details go away and the following is shown:

![Screenshot 2023-11-21 at 12 14 12 PM](https://github.com/cockroachdb/cockroach/assets/78774369/17a02ee0-b56e-436b-b1c2-711eb720c426)

**Expected behavior**

To be able to view the session details and it not disappear from the screen.

**Environment:**
 - CockroachDB version `23.1.12`
 - Server OS: `CockroachDB Dedicated`

Jira issue: CRDB-33698

**Comment by maryliag** [comment]
@daniel-crlabs do you have a cluster that I can have access that is having this issue? I'm not being able to repro (locally or on staging)

If you're able to repro yourself, can you send a screenshot of the browser console logs error?

**Comment by maryliag** [comment]
Also, do you have a sense of how many sessions they are displaying?

**Comment by daniel-crlabs** [comment]
The problem is not the number of sessions being displayed, the sessions page does not have any errors or problems.. The problem is when you click in 1 session, it takes you to a different page (as the screenshot above) and then this is the page that shows the error.

<img width="350" alt="Screenshot 2023-11-21 at 1 04 18 PM" src="https://github.com/cockroachdb/cockroach/assets/78774369/716fb046-2f71-4b8f-8b7f-186eecddae61">

**Comment by maryliag** [comment]
The reason why I asked the number is to see if was large, which meant that older data is getting deleted, so there is a chance that:
- we list the session
- you click on it
- the details page populates with data that it had available (is just passes some info we had from the overview)
- when tries to retrieve everything else the data is removed from cache
- at this point we return that we couldn't find the session

Because this error doesn't happen with all of the closed ones, that is my assumption. So the fix is to change the page to a loading state until we check if we still have the data, so there is no blinking of the page, but the bheaviour will still be the same, meaning you will get the message about non having info on that session anymore

**Comment by maryliag** [comment]
You can confirm my assumption when filtering by only closed ones, if you click on any of the most recent, they will open normally, if you select the older ones, it will fail, which means they're being deleted while you tried to check on them

**Comment by daniel-crlabs** [comment]
Working as expected as per internal discussion, issues filed to provide better error message, status as to why the page could not be loaded and better documentation.

**Comment by maryliag** [comment]
Assing extra context: the amount of closed session stored in-memory is controlled by cluster setting  `sql.closed_session_cache.capacity`, and the data is also deleted following the cluster setting `sql.closed_session_cache.time_to_live`
