### ISSUE TITLE
Operators not working as expected with ttl_expiration_expression

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#115630]
Per [this](https://cockroachlabs.slack.com/archives/C067NG669KJ/p1701760455936689) thread, the row level ttl docs indicate operators should work (e.g. ttl_expiration_expression = '((end_date::TIMESTAMP) + INTERVAL ''30 days'') AT TIME ZONE ''UTC'''). However, the following returns an error which seems to be a bug:

```
ALTER TABLE kv SET (ttl_expiration_expression = $$(expire_ttl::TIMESTAMPTZ + INTERVAL '7 days')$$);
ERROR: +: context-dependent operators are not allowed in TTL EXPIRATION EXPRESSION
SQLSTATE: 0A000
```

Jira issue: CRDB-34134

**Comment by rafiss** [comment]
This is not a bug. The schema of this table is:
```
CREATE TABLE public.kv (
  k INT8 NOT NULL,
  v BYTES NOT NULL,
  expire_ttl TIMESTAMPTZ NULL DEFAULT statement_timestamp():::TIMESTAMPTZ - '7 days':::INTERVAL,
  expire_ttl12 TIMESTAMPTZ NULL DEFAULT statement_timestamp():::TIMESTAMPTZ - '7 days':::INTERVAL,
  CONSTRAINT kv_pkey PRIMARY KEY (k ASC)
)
```

As per the docs you linked, you should use the following for a TIMESTAMPTZ column:
```
ALTER TABLE kv SET (ttl_expiration_expression = $$((expire_ttl AT TIME ZONE 'UTC') + INTERVAL '7 days') AT TIME ZONE 'UTC'$$);
```

The example you gave tried to do `expire_ttl::TIMESTAMPTZ` which is a context-dependent operation if `expire_ttl` is a TIMESTAMP, since the cast depends on the configured time zone.

---

Furthermore, note that in v23.2 a change was made to make an exception for the timestamptz + interval operator (https://github.com/cockroachdb/cockroach/pull/102974), so you can just do this:
```
ALTER TABLE kv SET (ttl_expiration_expression = $$(expire_ttl + INTERVAL '7 days')$$);
```

The docs issue for that change is: https://cockroachlabs.atlassian.net/browse/DOC-7687
