### ISSUE TITLE
sql: BEGIN statement logs have incorrect txnCounter

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#115610]
It seems that at the time of logging BEGIN statements, the txn counter has not yet been incremented causing the txn counter for BEGIN to be off by 1.

Example of what we'd see today:
```
{ Statement: "SELECT 1", TxnCounter: 1, Session: "aaaa" } // Implicit txn, so no BEGIN.
{ Statement: "BEGIN TRANSACTION", TxnCounter: 1, Session: "aaaa" 
{ Statement: "SELECT 2", TxnCounter: 2, Session: "aaaa'  }
{ Statement: "COMMIT TRANSACTION", TxnCounter: 2, Session: "aaaa"  }
```
We'd expect the BEGIN log to have a TxnCounter of 2, not 1.

Jira issue: CRDB-34123

**Comment by rafiss** [comment]
This behavior is semi-intentional, but I also don't think it's that intuitive. The reason is that the transaction does not start until _after_ BEGIN is executed, so in some sense, it doesn't make sense to include BEGIN statements in the txnCounter.

 See https://github.com/cockroachdb/cockroach/pull/109655 for where this decision was made.
