### ISSUE TITLE
pkg/sql/physicalplan: TestFakeSpanResolver fails under remote execution

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#115619]
I suspect this is an OOM.

Example invocation: https://tanzanite.cluster.engflow.com/invocations/default/664ea78e-40a4-4e00-bc76-05ed574dcd8a?testReportShard=44&testReportRun=3&testReportAttempt=0#highlights

Epic: CRDB-8308

Jira issue: CRDB-34130

**Comment by yuzefovich** [comment]
It doesn't look like it's an OOM, rather it seems that the executor is overloaded. The test creates 3 node cluster and then starts (due to randomization) shared-process tenant, so another 3 SQL servers. The package uses the "default" pool, so we only have 1 CPU executor. I think the answer is something that Steven mentioned - disable tenant randomization under race, I'll send a patch.
