### ISSUE TITLE
kvserver: runtime assertions for double-application and duplicate proposals

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#115771]
In the context of #114421, we should ensure we have sufficient runtime assertions to detect double-application/replays of Raft proposals. This may already exist, but we should confirm. Ideally, this would be enabled in roachtests.

Jira issue: CRDB-34202

Epic CRDB-32846

**Comment by pavelkalinnikov** [comment]
Which again leads me to conclude that the reproposals area needs a cleaner lifetime tracking. There are things "common" across all the (re-)proposals of a single proposal, and things that are unique. The previous design put everything into a single mutable struct, the new design put everything into separate semi-immutable structs but copies/moves the shared things between them. The design that we need: a shared part for the "logical" proposal, and a set of per-reproposal structs that link into it.

The "shared" proposal struct then makes it possible to track the entire state of a single proposal rather than piece it together from multiple structs. It also makes invariant checks more reliable, like the "applied only once" check. Issue #115759 is a stepping stone towards such a restructure - we can first build a solid set of invariants in test-only environment, plus cover it with tests, and then slowly transition it to better code with inline assertions.

Previous problem that we had because of this copying: #108775.

**Comment by erikgrinaker** [comment]
Downgrading to non-blocker, test coverage.

**Comment by erikgrinaker** [comment]
>The "shared" proposal struct then makes it possible to track the entire state of a single proposal rather than piece it together from multiple structs. It also makes invariant checks more reliable, like the "applied only once" check. Issue https://github.com/cockroachdb/cockroach/issues/115759 is a stepping stone towards such a restructure - we can first build a solid set of invariants in test-only environment, plus cover it with tests, and then slowly transition it to better code with inline assertions.

That's a longer-term change though. We need something in the next week to try to track down #114421. Thoughts on this, @pavelkalinnikov?

**Comment by erikgrinaker** [comment]
So we already have this assertion: 

https://github.com/cockroachdb/cockroach/blob/f5800498f4339f979a3db645ae6c8e46af5f0b40/pkg/kv/kvserver/replica_application_decoder.go#L95-L109

I know Tobi added a bunch of other assertions that were later removed because they weren't actually invariant. I'll try to dig that up just to see what we've already tried.

**Comment by pavelkalinnikov** [comment]
In a general sense, asserting/detecting double-apply situations is a costly problem. It basically requires a global map of all the proposal IDs ever, and checking that an applied command is not yet in this map.

On the leaseholder, we can reduce the scope of this checking to a single lease epoch. The `Replica.mu.proposals` sort of plays the role of "all the proposal IDs ever" (scoped to this lease epoch), but it forgets the proposals after application. And that's the "problem", because what if there is another application soon after we forgot the proposal?

So we can't use this simple map-based ID checking approach. Instead, we must rely on maths (e.g. see INVARIANT things quoted above).

**Comment by erikgrinaker** [comment]
`Replica.mu.proposals` also only tracks proposals which were submitted by the local node, so it won't catch double-application on followers. It also won't detect double-application with snapshot application.

**Comment by pavelkalinnikov** [comment]
Sort of things that we rely on are along the lines of: there is always at most one appliable proposal in flight; we only repropose it with a new LAI if it came back from the application pipeline (and now there is exactly zero appliable proposals in flight).

**Comment by pavelkalinnikov** [comment]
> so it won't catch double-application on followers. It also won't detect double-application with snapshot application

Exactly. On the followers detecting this is costly: we basically need to introduce a map by some ID to detect dups. On the leaseholder this is somewhat free because we need this map for other purposes. But this isn't exactly the map that would detect all dups flawlessly, because we remove from it.

Snapshot application can happen on followers and (as I learned recently) on the leaseholder, so yeah, this additionally makes it impossible to observe all the applied IDs even on the leaseholder.

**Comment by erikgrinaker** [comment]
>asserting/detecting double-apply situations is a costly problem. It basically requires a global map of all the proposal IDs ever, and checking that an applied command is not yet in this map.

We could assume that double-apply is most likely to happen for recent operations though, and keep a ring buffer of e.g. the last 100k proposal IDs. We could persist this ring buffer in the state machine, such that it's propagated in snapshots.

Clearly, we could only do this in test builds, since it's likely going to be too costly otherwise. But it doesn't seem terribly complicated to implement something like this (famous last words).

**Comment by pavelkalinnikov** [comment]
For test-only purposes (esp. small-/mid-size unit-tests), we can just have a global map of all the proposals, track their lifetime transitions, and check all the invariants and semantical expectations. This is adjacent to #115759.

**Comment by erikgrinaker** [comment]
Sure, that covers the proposal lifecycle, but doesn't fully address the double-apply problem does it? Because of snapshots, lease transfers, etc.

**Comment by pavelkalinnikov** [comment]
In tests we can intercept all the apply events, both on leaseholders and followers. Every log index will be applied explicitly (not via a snapshot) at least once, so we can build a global picture of applied commands by joining the lifetimes across replicas.

**Comment by erikgrinaker** [comment]
I think we want something we can assert in roachtests and test clusters, which exercise a wider range of scenarios.

**Comment by pavelkalinnikov** [comment]
I guess the same technique can be done in a distributed env. Periodically dump all the applied command IDs to a log/table/whatever. At the end of the test, do a global join of these things and see if there are command ID dups.

**Comment by pavelkalinnikov** [comment]
If this "applied commands" is a SQL table, things could be detected timely by inserting batches of recently applied commands to this table, and have some clever key constraints that would detect dups for us.

**Comment by erikgrinaker** [comment]
Maybe we can build something like this into kvnemesis. It already does similar tracking and analysis for serializable transaction schedules.

**Comment by pavelkalinnikov** [comment]
Does `kvnemesis` use `TestCluster`? In this case, we could inject a testing knob that dumps all the applied (command ID, raft index) pairs to us, which we then immediately can put into a Go `map[commandID]index`.

We basically need the `TestingPostApplySideEffectsFilter` interceptor from PR #114191 or somesuch (crucial: it has to be called on every replica that applies the command, not just the leaseholder).

**Comment by erikgrinaker** [comment]
Yes, it uses `TestCluster`. I think we already have what we need in `ReplicaApplyFilter`, assuming we can get the log index from `ReplicatedEvalResult.State.RaftAppliedIndex` or `LeaseAppliedIndex` or some such.

We'll also want to track this across splits/merges.

**Comment by pavelkalinnikov** [comment]
Command ID (or proposal IDs, need to check how they are called) are likely globally unique, so the across splits/merges aspect should come automatically.

**Comment by erikgrinaker** [comment]
> likely globally unique

They're not, they're a random 8-byte sequence, so there is a non-zero collision probability.

> the across splits/merges aspect should come automatically

If we're going to tie them to log indexes, the log indexes will change with splits/merges.

**Comment by pavelkalinnikov** [comment]
> But I don't know if it even makes sense to track command IDs across ranges, since proposals, logs, and applications are range-local by definition. I don't see how a proposal/command could leak to a different Raft group.

That's right. I don't think a (re-)proposal crosses over to another range. It may stick to the LHS after a split though, and be inherited from an LHS during a merge, but that's within the same range ID.

The uniqueness aspect is interesting though. The proposal ID being a random int64 means there is a 50% chance of a collision after 4 billion proposals. We are probably fine to assume it won't happen at the unit test scale. But to be safer we can mix in the range ID into the key, so that we find dups for (rangeID, commandID).

**Comment by erikgrinaker** [comment]
>We are probably fine to assume it won't happen at the unit test scale. But to be safer we can mix in the range ID into the key, so that we find dups for (rangeID, commandID).

If it ever becomes a problem, we can inject a different command ID generator that's guaranteed to be unique in unit tests, e.g. UUIDv1.

**Comment by pavelkalinnikov** [comment]
Apparently github can double-apply proposals too. I sent a comment, it appeared twice in the timeline. So I removed the second one. Now there is none :)

I was saying that the proposals can be carried across ranges (stay with the LHS during splits, and inherited from LHS during merges), but will be associated with the same rangeID because the LHS keeps it.

The proposal being a [random int64](https://github.com/cockroachdb/cockroach/blob/42d9987459b301e28c0b754b27045b379cb8df51/pkg/kv/kvserver/raftlog/encoding.go#L176-L181) can become a problem if there were too many proposals that we were tracking at the same time. The probability of a collision is ~50% if we reach ~4 billion proposals (see "birthday paradox").

We are probably fine to assume it won't happen at the unit test scale. But to be safer we can mix in the range ID into the key, so that we find dups for (rangeID, commandID).

I am slightly concerned that this can happen in prod though. We [detect it](https://github.com/cockroachdb/cockroach/blob/59ad05a0e43d4c00307a0011d80e76f50549eb39/pkg/kv/kvserver/replica_proposal_buf.go#L1358-L1360) and panic at the insertion time. But since we're removing from this map too, it's possible that 2 different proposals have had the same ID after a while. We're probably fine since it won't happen within a short period. But.

Relying on thi Go's random number generator for crucial correctness properties seems incorrect by design. It would better be a UUID, a cryptosecure hash of the command content, or (best of all) the commands would be identified by LAI and processed sequentially [#116020]. A random ID like this should be best used for sanity checking rather than relied upon.
