### ISSUE TITLE
storage: wal fsync latency histogram different between prometheus and db console

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#115825]
**Describe the problem**

The `storage.wal.fsync.latency` metric is different when viewed in grafana (querying prometheus) vs DB Console. The DB Console chart appears to be incorrect as the values are overly smoothed.

**To Reproduce**
```
export cluster=austen-fsync-latency-hist-repro
roachprod create $cluster -n 3 --local-ssd=false
roachprod stage $cluster release v23.2.0-beta.1
roachprod start $cluster
roachprod run $cluster -- './cockroach workload run kv --min-block-bytes=4048 --max-block-bytes=4048'
# - open up db-console page and navigate to custom metrics
# - check the custom metric `storage.wal.fsync.latency-p99`
# - check grafana:
histogram_quantile(0.99, sum by (instance,le) (rate(storage_wal_fsync_latency_bucket[15s])))
```
**Expected behavior**

DB Console and prometheus are comparable.

**Additional data / screenshots**

![image](https://github.com/cockroachdb/cockroach/assets/39606633/595dee4c-0fb9-4f9c-8900-64f48a5612aa)
![image](https://github.com/cockroachdb/cockroach/assets/39606633/61192964-5035-4fff-a49d-64f0a35e0086)

**Environment:**
 - CockroachDB version v23.2.0-beta.1
 - Server OS: Ubuntu
 - Client app KV workload

**Additional context**

Fsync metric on DBConsole is not usable. This is unfortunate as it is a relied upon signal for disk saturation.

Jira issue: CRDB-34231

**Comment by abarganier** [comment]
I was poking around the Histogram code today to do some optimizing for allocations, and I noticed some weirdness that led me here.

I believe https://github.com/cockroachdb/cockroach/pull/104088 broke the `ManualWindowHistogram`, which is what's causing this. 

When grabbing a window to calculate a quantile against, we are using the cumulative histogram. Shouldn't we just be using the current one? 

https://github.com/cockroachdb/cockroach/blob/50a47aa0b457821da7ec3831f32eee8d397fe4d0/pkg/util/metric/metric.go#L669

As of the linked PR, the `cur` window that's part of the `ManualWindowHistogram` is written to, but never used.

**Comment by aadityasondhi** [comment]
Yep, I noticed those things too. Putting up a fix soon.

**Comment by aadityasondhi** [comment]
This bug was introduced in https://github.com/cockroachdb/cockroach/commit/4a2d06a293412f62f5f05a3b0b799d30080592e7 and then was exemplified by some of the changes in https://github.com/cockroachdb/cockroach/commit/bae5045069c9f39cf3365dd87538fceb1a38228c.

There are two main problems (one from each):
1. The original commit was not windowing the newly introduced histogram using the same logic as the default one does. We have a prev and cur windowed histogram that cover the duration of the histogram. At every tick, we rotate them and we use a merged view to calculate derivative statistics. This is the same as using rate over 1m in Grafana.
2. The next change incorrectly was merging the cumulative and prev histogram. This is incorrect for obvious reasons and surfaced the problems that we see above.

In addition, both changes were missing tests for the windowing logic for manual histograms.

I made a fix that is within the confines of the current interface. I still strongly believe we should strongly consider taking on https://github.com/cockroachdb/cockroach/issues/116584 to make this interface easier to use so such bugs are difficult to introduce.

Below is a test I ran using the same workload @kvoli mentioned above.

DB Console:
<img width="988" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/89c07ddc-8b1e-4ff2-a5ab-2b40230fad4b">

Grafana:
<img width="1074" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/9b7a2157-9b14-4459-9bde-c4e2efd85fd1">

I will put a PR with these fixes soon.
