### ISSUE TITLE
lease: determine optimal primary and secondary indexes for new lease table

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#116675]
https://github.com/cockroachdb/cockroach/pull/111462 added a new lease table that ties leases to SQL liveness sessions.

Let's make sure the table has the proper primary and secondary indexes. Sometimes the table is queried by descID, sometimes by nodeID, and sometimes by sessionID. (And maybe also by crdb_region.)

Let's determine which ones are important in hot paths, and use a primary index that will make those queries quicker. For non-hot-path queries, we can still add secondary indexes to avoid a full scan.

Jira issue: CRDB-34711

Epic CRDB-35665

**Comment by fqazi** [comment]
Digging into this I think the right answer here is to optimize the queries for the non-multiregion system database case, with the hot ones being WaitForNoVersion and CountLeases. The primary key prefixes all make sense, but in a single region system database we are always forced into full scans because the crdb_region column is first. So, I'm going to optimize the query so that constrained scans are used with the default region.

**Comment by fqazi** [comment]
This was completed when we merged the leasing work to optimize the query
