### ISSUE TITLE
always print "allocator.go:207: unable to allocate a target store for {[] }" after cockroach start

### ISSUE THREAD

**Issue by blackcat242** [cockroachdb/cockroach#1167]
I just try to start cockroach as README.md write below:

./cockroach cert create-ca
./cockroach cert create-node 127.0.0.1 localhost $(hostname)
./cockroach init --stores=ssd=/cockroachData
./cockroach start --stores=ssd=/cockroachData --gossip=self= &

it start success. but it continuously print error:
I0528 11:19:48.477489   68187 range.go:936] gossiping first range from store 1, range 1
I0528 11:19:48.477534   68187 range.go:944] gossiping sentinel from store 1, range 1
E0528 11:19:53.552037   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 11:20:03.553710   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 11:20:13.555554   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 11:20:23.556700   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 11:20:33.558529   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 11:20:43.560681   68187 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }

**Comment by tschottdorf** [comment]
Hi @blackcat242, that's expected behaviour but I can understand your confusion. You're running a single node cluster, but the standard setup for Cockroach is to run on three or more nodes. So there's something running that tries to put two extra copies of the data on your single node somewhere, but there are no other nodes, hence no place to put the copies. That's the message you're seeing every ten seconds.
We'll update the README soon to make it easy to start three nodes using Docker and interact with it. For now, just ignore the warning message.
Best,
Tobias
