### ISSUE TITLE
sql: optimize joins with roaring bitmaps

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#11687]
I realize fast joins have taken a backseat. Once they come to the forefront, consider using this compressed bitmap indexing library; it has been used to good effect in Lucene and Druid, and now there is a Go port available. See https://github.com/RoaringBitmap/roaring and [1].

[1] http://roaringbitmap.org/

**Comment by knz** [comment]
Thanks for the suggestion!

We talkled briefly about this today. We'll need quite some infrastructure before we can use bitmaps; in particular bitmaps only make sense when we can assume a stable and non-sparse row numbering for the duration of a query; so this will probably not be applied until we use temp tables for intermediate results. (#5807)

**Comment by glycerine** [comment]
@knz: cool. I'll note that roaring bitmaps in particular are very good at sparse row numbering, because they substitute (transparently to the user) one of three representations as appropriate (run-length encoding, simple array of integers, or a bitmap) over each 16-bit wide block of the rowid space.

**Comment by knz** [comment]
Thanks for confirming that sparsity is not a major issue. What is still an obstacle though is that unless the primary key is an int or is at least fixed width it's not enumerable and thus won't map to bitmap positions. That's why I suggested that maximal reuse of this optimization requires copying the data to a temp table (with int rowids).
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jordanlewis** [comment]
Joins have come a very long way in CockroachDB, most recently with the vectorized engine. This might "roar back" into the forefront if we run into performance problems with joins again, but I don't see us doing this in the foreseeable future.
