### ISSUE TITLE
CREATE EXTERNAL CONNECTION IF NOT EXISTS does not work as expected

### ISSUE THREAD

**Issue by mmack** [cockroachdb/cockroach#116997]
**Describe the problem**
I have some sql scripts which i run inside a kubernetes job for DB Setup on every deployment. Goal is to run them idempotent.

**To Reproduce**
Run create external connection twice:
```
CREATE EXTERNAL CONNECTION IF NOT EXISTS azure AS "azure://${AZURE_STORAGE_CONTAINER}/${NAMESPACE}?AUTH=specified&AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}&AZURE_TENANT_ID=${AZURE_TENANT_ID}&AZURE_CLIENT_ID=${AZURE_CLIENT_ID}&AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}&AZURE_ENVIRONMENT=AZUREPUBLICCLOUD";
```

I would have not created that issue if not i found that file for test data in the repo:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/testdata/create_external_connection#L10

The docs state that "IF NOT EXISTS" does not work:
https://www.cockroachlabs.com/docs/stable/create-external-connection#synopsis

However the SQL Command fails with:
```
ERROR: failed to create external connection: external connection with connection name 'azure' already exists                                                                                                                                  
SQLSTATE: 42710
```

Please clarify if "CREATE EXTERNAL CONNECTION IF NOT EXISTS" does exist or how to reach idempotency here.

Cockroach Version is: v23.1.5

Jira issue: CRDB-34893

**Comment by stevendanna** [comment]
Thanks for the well defined bug report. 

Unfortunately, it appears that while `IF NOT EXISTS` is accepted at a syntactic level, the actual external connection creation code does not properly handle it.  The code you found is just testing the parser which is why those test pass and why your statement doesn't receive a parse error. 

I've opened a fix for this bug here: https://github.com/cockroachdb/cockroach/pull/117312.

**Comment by mmack** [comment]
Thank you!
