### ISSUE TITLE
Nodes with --locality-advertise-addr do not show pings/latency/heartbeats between each other (in the same zone)

### ISSUE THREAD

**Issue by world2mark** [cockroachdb/cockroach#117418]
Multi-region cluster does not properly apply pings when **--locality-advertise-addr** is specified.

This worked perfectly in v23.1.13, and after an upgrade to V23.2.0-RC.1, suggesting this is a regression.

The _**network tab**_ does not show pings/heartbeats between nodes in the same network.

![image](https://github.com/cockroachdb/cockroach/assets/38871577/0b85f6ec-d024-437e-b5d0-94f146f28fc2)

**Environment:**
 - CockroachDB version: V23.2.0-RC.1
 - Server OS: OpenShift

Jira issue: CRDB-35165

**Comment by world2mark** [comment]
An example of a node start-command:
```
cockroach start
  --locality=region=CA-Central,zone=Zone-2
  --sql-addr=:26257
  --listen-addr=:26357
  --advertise-addr=172.23.0.4:31360
  --locality-advertise-addr=zone=Zone-2@zlamal-172-23-0-4-mesh-local.crdb-rbr-ca-central:26357
  --join 172.23.0.4:31350,172.23.0.6:31351,172.23.0.5:31352

```
Note the **locality-advertise-addr** setting.  Are there new settings specific to locality-awareness that have been introduced into 23.2 that we should be aware of?

**Comment by nvanbenschoten** [comment]
My understanding is that this is an observability issue on the DB console's overhauled Network page, and nothing more severe. If there are indications that nodes are actually having trouble communicating, please correct me @world2mark.

Looking through the code, it seems like this is due to this logic:
https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/server/status.go#L2028-L2034

This was rewritten in v23.2 as part of af1aec27. The logic is not using the `NodeDescriptor.AddressForLocality` method, so it will ask for the `ConnHealth` of an address that is not used when `--locality-advertise-addr` is in use.

We should either switch this to use `NodeDescriptor.AddressForLocality` or use `Dialer.ConnHealth` (which internally reaches back into gossip).

**Comment by nvanbenschoten** [comment]
One open question is whether `NetworkConnectivityResponse_Peer.Address` ([set here](https://github.com/cockroachdb/cockroach/blob/5bd4ca0cce6bf2358f05ee0cb2a6cd2533ad435c/pkg/server/status.go#L2044)) should be set to the default advertise address or the locality advertise address in these cases.
