### ISSUE TITLE
workload/schemachange: consider if function already exists when creating

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#117421]
Successive calls to `schemachange` workload may decide to create a function with the same name. If that happens, the second call could get an error of the form `function \"udf_24\" already exists with same argument types`.

Instead, the `schemachange` workload could check if the function already exists and avoid this error. 

Jira issue: CRDB-35167

**Comment by annrpom** [comment]
Interesting - it does look like we do try to keep the function names unique in order to not encounter this: https://github.com/cockroachdb/cockroach/blob/ecb7bf553ccd3029d78468aad7b5086e255a6c72/pkg/workload/schemachange/operation_generator.go#L3917

but looking at the failures, udf_24 was indeed created before this 

`"sql": "CREATE FUNCTION udf_24()\n\tRETURNS VOID\n\tLANGUAGE SQL\n\tAS $$ SELECT NULL WHERE TRUE $$"`
created before
"sql": "CREATE FUNCTION udf_24()\n\tRETURNS VOID\n\tLANGUAGE SQL\n\tAS $$ SELECT NULL $$"

I'll need to understand more about what is going on; however, I have a hunch that this comment might be the reason:
https://github.com/cockroachdb/cockroach/blob/6f56f0cb849d1389820128cadb813113272481cc/pkg/workload/schemachange/schemachange.go#L300-L305

used here in the schemachange workload:

https://github.com/cockroachdb/cockroach/blob/6f56f0cb849d1389820128cadb813113272481cc/pkg/workload/schemachange/schemachange.go#L252
