### ISSUE TITLE
kv: pipeline replicated lock acquisition

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#117978]
Replicated lock acquisition currently replicates through Raft synchronously. This can impose a high latency on read committed transactions which perform a large number of SELECT FOR UPDATE operations or a large number of FK lookups.

This was discussed in the Read Committed RFC under the [Row-Level Locks > Reliability and Enforcement](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20230122_read_committed_isolation.md#reliability-and-enforcement) section. That section also outlined a collection of [possible optimizations](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20230122_read_committed_isolation.md#alternative-replicate-locks) that we could make to avoid this latency penalty.

The most promising of the optimizations is to pipeline this lock acquisition using the using `AsyncConsensus` infrastructure. This will require client-side tracking and a new protocol to validate pipelined lock acquisition. It is analogous to our existing [write intent pipelining](https://www.cockroachlabs.com/blog/transaction-pipelining/) approach.

Jira issue: CRDB-35440

**Comment by arulajmani** [comment]
@nvanbenschoten, @miraradeva and I just spoke about this issue at length. I'll capture some of this discussion below. 

We should be able to use most of our existing infrastructure for write pipelining here. One tricky point is how this issue interacts with parallel commits. A transaction qualifies for a parallel commit if all in-flight intents in the last batch (the one which includes the `EndTxn` request) successfully replicate at a timestamp at or below the transaction's commit timestamp. When we kick off recovery for a `STAGING` transaction, and we find an intent did not successfully evaluate (yet), we also bump the timestamp cache to ensure it can't land in the future. 

We discussed two options here:
1. We would need something similar for locks -- that is, a way to check whether any locking requests in the last batch were successfully able to acquire replicated locks at or below the transaction's commit timestamp. This should be doable, given we store the entire `TxnMeta` for the lock. Additionally, if we found that a lock hadn't successfully been acquired, we would need some way to ensure it doesn't happen later. This would probably involve bumping the timestamp cache for replicated locking requests. The room had mixed to negative feelings about this special case handling for replicated locks.

2. Disallow parallel commits entirely if there are locking requests in the `EndTxn` batch. This should be fine given we never expect SQL to construct a batch which contains both a locking read and `EndTxn` in it. Crucially, it allows us to side-step the concerns about replicated lock acquisition attempts coming along after the transaction has been recovered. This is because we know they've already been evaluated and proposed to Raft -- they can't be in-flight concurrent to the `EndTxn` batch. We're only validating whether the Raft proposal succeeded or not. 

We settled on approach 2 as the ways to go here. 

----

We also discussed https://github.com/cockroachdb/cockroach/issues/64723, and how it is tangentially related to the issue at hand. The reason we don't pipeline `DeleteRange` requests is because we don't know all the keys that'll be deleted before evaluation[*]. This means we can't construct the parallel commit condition if the last batch also includes a `DeleteRange` request. However, we're being overly aggressive here by disallowing pipelining of `DeleteRange` requests entirely -- if we follow the logic from point 2 above, we could pipeline batches containing `DeleteRange` requests as long as we don't try to perform a parallel commit if the last batch contains a `DeleteRange` request. 

[*] The same logic will apply to `Scan` and `ReverseScan` requests, where we won't know all the locks that will be acquired. This means we're not gaining too much by trying to follow the approach described in option 1 above. 

----

The other thing we noted on the call is there might be some trickiness involved with lock re-acquisitions. If we've got a pipelined replicated lock, and its being re-acquired, we want the lock re-acquisition to ensure the pipelined lock replication was successful. We do something similar for intents when a key is being written to multiple times. 

We noted that replicated lock re-acquisition can sometimes be no-ops, so we'll have to be careful to think through some of those cases.

@nvanbenschoten, @miraradeva, feel free to add more details I may have missed here!
