### ISSUE TITLE
ttl: job failure due to "no inbound connection stream"

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#117985]
Seeing a TTL job issue on the DRT cluster (`cct-232`) for job 935605994824925191.  The job starts up and makes some progress but then stumbles due to a rolling upgrade (failing on several nodes before being restarted on node 10).  Finally, it fails with the error seen below.

```
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975  ROW LEVEL TTL job 935605994824925191: stepping through state reverting with unexpected error: no inbound stream connection
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +(1) attached stack trace
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  -- stack trace:
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.init
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_registry.go:32
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.doInit1
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:6757
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.doInit
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:6724
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.main
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         GOROOT/src/runtime/proc.go:249
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  | runtime.goexit
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +  |         src/runtime/asm_amd64.s:1650
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +Wraps: (2) no inbound stream connection
E240118 21:26:04.729236 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68975 +Error types: (1) *withstack.withStack (2) *errutil.leafError
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976  ROW LEVEL TTL job 935605994824925191: stepping through state failed with unexpected error: no inbound stream connection
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +(1) attached stack trace
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  -- stack trace:
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.init
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_registry.go:32
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.doInit1
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:6757
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.doInit
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:6724
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.main
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         GOROOT/src/runtime/proc.go:249
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  | runtime.goexit
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +  |         src/runtime/asm_amd64.s:1650
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +Wraps: (2) no inbound stream connection
E240118 21:26:04.880779 771020 jobs/registry.go:1546 ⋮ [T3,Vapplication,n10] 68976 +Error types: (1) *withstack.withStack (2) *errutil.leafError
E240118 21:26:05.127384 771020 jobs/adopt.go:461 ⋮ [T3,Vapplication,n10] 68977  job 935605994824925191: adoption completed with error no inbound stream connection
```

Not sure if this is an code issue or not, so opening this issue for tracking purposes.  Sending to Queries for a first crack.  Please reassign as necessary.

Jira issue: CRDB-35444

**Comment by yuzefovich** [comment]
I don't think there is any action to do by Queries team, so I'm reassigning to Foundations to triage this issue further. My reading of the situation is that some failures are expected during rolling upgrades (e.g. backups fail too) and there is not much we can do.

----

Copying some relevant context from the [slack thread](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1705683745313969).

The failures of TTL jobs around the rolling upgrade window seem expected to me. TTL job under the hood sets up a distributed plan with TTL job processors, and each of those processors issues a couple of queries, a SELECT and a DELETE (the SELECT can also be distributed). So any of those 2 types of distributed plans might result in `no inbound stream connection` or `registry is draining` errors since some nodes are no longer accepting incoming distsql requests, yet they might be chosen for distsql planning. This doesn’t seem problematic per se - once the cluster stabilizes (i.e. when the rolling upgrade completes), the next time the TTL job runs (and I think it runs on a schedule, so there should be the next time), it’ll delete rows that would have been deleted by the failed queries.

Note that retry-as-local mechanism introduced in 23.2 is applicable only to the "main query" path, so it would help only with distributed SELECTs which leaves the original TTL job processors distributed plan that might fail to be set up.

Also note that currently, due to #118284, even when the distributed plan with TTL processors results in a failure due to "no inbound stream" errors, some TTL processors still can make progress by deleting rows that were assigned to them.

**Comment by rafiss** [comment]
I'll lower this to a P-3, since this error would stop occurring once the cluster stabilizes. Since the next run of TTL would delete the rows it needs to, there isn't a permanent problem here.
