### ISSUE TITLE
`SELECT FOR UPDATE` blocks reading request from another transaction

### ISSUE THREAD

**Issue by TheZeroSlave** [cockroachdb/cockroach#118107]
**Describe the problem**

Hi. It seems like "select for update" construction blocks row for any operation including non-lockable reading.

**To Reproduce**
Run cockroach in docker-compose  as single-node:
https://github.com/cbuschka/cockroach-docker

Connect to container from 2 different tabs and exec commads:

**tab1**
root@localhost:26257> begin; 
root@localhost:26257> select * from rirs where id=-1 for update;
  id | created_at 
-----+------------
  -1 | NULL

Now the second:

**tab2**
root@localhost:26257/aincore> begin;
root@localhost:26257/aincore> select * from rirs where id=-1;

The second tab will hang until first rooback or commit.

**Expected behavior**
As far as i understand the second readonly select shoudn't be locked.

**Environment:**
**version:**
                                                                                                         
----------------------------------------------------------------------------------------------
  CockroachDB CCL v23.1.13 (aarch64-unknown-linux-gnu, built 2023/12/01 22:21:24, go1.19.13)
(1 row)

Jira issue: CRDB-35544

**Comment by yuzefovich** [comment]
This behavior is expected given that by default CRDB runs under serializable isolation. The good news, however, is that in 23.2 version (which is already available on CockroachCloud and will be shortly available to everyone else) we implemented Read Committed isolation level (although in preview). If you were to enable the read committed level at the cluster level with
```sql
SET CLUSTER SETTING sql.txn.read_committed_isolation.enabled = true
```
and then start the txn in the 2nd shell with
```sql
BEGIN ISOLATION LEVEL READ COMMITTED;
```
then the regular SELECT in the 2nd shell will not block, as you expected.

Please feel free to check out our docs around this https://www.cockroachlabs.com/docs/dev/read-committed, and I'm closing this issue as expected behavior.
