### ISSUE TITLE
storage: test replicate queue behavior

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#11987]
#11982 fixed an issue where the replicate queue was retrying lease transfers for a range repeatedly because the available target replica was behind and thus not a candidate. The replicate queue code does not make testing this easy. We should either refactor it or create infrastructure to make such tests feasible.

**Comment by petermattis** [comment]
@a-robinson tossing your way as this likely ties in with other rebalancing work you're doing.

**Comment by tschottdorf** [comment]
Is there anything left to do here?

**Comment by a-robinson** [comment]
Well, we're still missing the tests and test infrastructure for the replicate queue that were desired when the issue was created. I think it's fair to leave open, especially given that the purpose of the replicate queue is changing slightly as part of https://github.com/cockroachdb/cockroach/issues/26059
