### ISSUE TITLE
kvcoord: DistSender circuit breaker testing

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#119918]
The DistSender circuit breakers added in https://github.com/cockroachdb/cockroach/pull/118943 have almost no direct testing, and need much more. In particular:

* Unit tests: we should add unit tests for most/all of the circuit breaker logic in isolation. This probably requires restructuring the code to make it more easily testable, and adding test hooks (e.g. for probe introspection and management).

* Integration tests: add tests for a few main cases we care about, for example partial partition, quorum loss, disk stall, replica stall, with variations for read/write requests and with/without request timeouts. Maybe also some for follower reads (see #119923). We currently only have this:

    https://github.com/cockroachdb/cockroach/blob/1df21ee3844ec542ffdb4ef955b514d33adea505/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go#L37-L39

* End-to-end tests: I think we have decent coverage in the `failover` suite of tests, particularly `disk-stall` and `deadlock`.

* Manual testing: we should make sure the probes don't cause problems at scale. Try running e.g. kv95 with high concurrency on 50k replicas/node, put all the leases on one node and stall its disk. How many concurrent probes do we launch? How many goroutines? Does the volume cause significant problems? How soon do the probes shut down as the leases move elsewhere?

Jira issue: CRDB-36387

**Comment by andrewbaptist** [comment]
Some testing results. For all the tests, the system is a 12 node cluster with 100K ranges (so 25K ranges/node) using epoch leases.
Setup steps (runs with ~50% CPU and very consistent 6K writes/sec)
```
roachprod create $CLUSTER -n 12
roachprod put $CLUSTER artifacts/cockroach
roachprod start $CLUSTER -e COCKROACH_ENABLE_UNSAFE_TEST_BUILTINS=true
roachprod ssh $CLUSTER:1 "./cockroach workload init kv --splits 100000 $(roachprod pgurl $CLUSTER:1)"
roachprod ssh $CLUSTER:1-12 "./cockroach workload run kv --max-rate 500 --concurrency 100 $(roachprod pgurl $CLUSTER:1-12)"
```

First test - impact of turning circuit breakers on/off - total CPU impact = ~3.2%, latency impact noticeable (off from 20:25 to 20:35 in the image, on for the first 5 and last 5 minutes):
`SET CLUSTER SETTING kv.dist_sender.circuit_breaker.enabled = [TRUE|FALSE];`

Second test - stalling one range  (with circuit breakers enabled). The entire cluster still locks up :( The service latency jumps to max and the metrics stop publishing. Somewhat unexpected but might be due to epoch leases. 
`SELECT crdb_internal.unsafe_lock_replica(25941, true);`
 
Attempt with expiration leases (dropping max rate to 100/node since there is >50% CPU overhead with just expiration based leases):
still fails with the system hung - need to investigate more tomorrow...

**Comment by andrewbaptist** [comment]
I'm marking this as completed. We haven't completed scalability, but I've added unit tests and done some manual testing of the feature.
