### ISSUE TITLE
dev: `lint --short` should run the `lintonbuild` tests, or doctor should advise of consequences of `nolintonbuild`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#119927]
**Is your feature request related to a problem? Please describe.**

I have learned never to run `dev lint` without `--short` because it uses an absurd amount of memory and slows my machine to a crawl. But I've just discovered that this is the only way to get the linters that are run in the `lintonbuild` configuration if you take `dev doctor`'s encouragement to use `nolintonbuild`

**Describe the solution you'd like**

Either:
- `lint --short` should run the linters that are used in `lintonbuild`
- or `dev doctor` should tell that if you set `nolintonbuild`, you should also run `lint` without `--short`

I'd prefer to have `lint --short` do more than have to remember something that I saw once when I was clicking through a setup process, although I haven't done any tests to see how expensive that would actually be. But intuitively, any linters that are cheap enough that some folks like to run them as part of the build should be cheap enough to run in `lint --short`

**Describe alternatives you've considered**

Remove the linter(s) that need tens of gigs of ram so we don't have to be afraid of non-short lint runs. I don't know what it's doing but it seems kind of absurd and I don't know if it's worth it. 

Jira issue: CRDB-36393

**Comment by rickystewart** [comment]
> But I've just discovered that this is the only way to get the linters that are run in the lintonbuild configuration if you take dev doctor's encouragement to use nolintonbuild

Maybe the first problem is that `dev doctor` seems to *encourage* you to use `nolintonbuild`. That was certainly not my intention when I wrote that text.

For the record, I have always used `lintonbuild`, have encouraged people to use it, and have expressed *some* confusion when people choose not to. Yes, it slows down your build somewhat (<10% when I checked last), but IMO having to "drop everything" to lint your code either in CI or with `dev lint` (without `--short`) is slower cumulatively across the entire dev cycle.

In any case the description from `dev doctor` is supposed to be accurate, complete, and non-judgmental about which of these options you choose, so if that does not seem to be the case, that should be fixed.

> `lint --short` should run the linters that are used in lintonbuild

This requires building everything which also takes a lot of time and uses a lot of memory, so to me this seems to not be in the spirit of `--short`. Some of the lint checks are just expensive, and `--short` is meant to skip those. I don't know why we would make an exception for some checks rather than others.

> or dev doctor should tell that if you set nolintonbuild, you should also run lint without --short

I've just noticed that `dev lint --short` does not tell you what work it's skipping. If you pass a test filter with `-f`, you get the message: `Skipping building cockroach-short with nogo due to provided test filter`. To be fair, this message *also* should probably be reworked, since it is basically useless if you don't already know what `nogo` is. But if you pass `--short`, there is no similar message. That is trivial to fix and we should do that.

> But I've just discovered that this is the only way to get the linters that are run in the lintonbuild configuration

You can also do the same on the command line, which is exactly what `dev lint` (without `--short`) would do anyway: `./dev build -- --//build/toolchains:nogo_flag`

> Remove the linter(s) that need tens of gigs of ram so we don't have to be afraid of non-short lint runs. I don't know what it's doing but it seems kind of absurd and I don't know if it's worth it.

This is mainly `staticcheck` (and I think to a lesser extent `gcassert`). I would love an alternative to these if you have them.

**Comment by rickystewart** [comment]
I suppose another command line argument, which would be like `--short`, but you also build with `nogo` as if you didn't pass `--short`, could be another solution. Or an extra argument to force building with `nogo` even if you pass `--short` or `-f`.

**Comment by bdarnell** [comment]
> Maybe the first problem is that dev doctor seems to encourage you to use nolintonbuild. That was certainly not my intention when I wrote that text.

Yes, I read the text (and even the fact that it was asking the question at all) as encouragement to use nolintonbuild. I assumed it would lead to at least a doubling of build times (I was expecting "lintonbuild" to mean something like "whenever you run `dev build`, also run `dev lint --short` on the same packages). If it's only 10%, I'd rather just have `lintonbuild` on and not debate what belongs in which mode of `dev lint`. 

> This requires building everything which also takes a lot of time and uses a lot of memory

Building the selected packages, not everything, right? Or is there something in "nogo" that requires analyzing the whole thing? My experience is that building is generally faster than linting in practice because there's been a lot more work on avoiding redundant builds than redundant work in linting. 

> Some of the lint checks are just expensive, and --short is meant to skip those. I don't know why we would make an exception for some checks rather than others.

My mental model (which may not be shared) is that `--short` is kind of misnamed, since it's more about removing linters that take a lot of memory than ones that take a long time. I'm not super sensitive to the running time of `dev lint` as long as it's not crippling the rest of the machine. 

It doesn't make sense to me that a check that adds 10% to build time is "just expensive" and can't be run in short mode. But I also never run lint without also building the packages in question, so I'm fine with `lintonbuild` and would prefer that to building everything a second time.

> This is mainly staticcheck (and I think to a lesser extent gcassert). I would love an alternative to these if you have them.

StaticCheck is an umbrella framework with many sub-checks. Only some of them are expensive. Last time I looked at this (years ago), the most expensive one was looking for unused exported symbols (which is one of the rare checks that can't be satisified without a global view). I've always thought this was a low-value check and I wouldn't mind getting rid of it entirely.

> Generally, lint checks are slow because they require building everything (or, if not actually emitting compiled code, doing everything up until that point) so we can perform static analysis.

But most lints don't need *everything*. Most of them can be run on a package at a time, and then they're reasonably efficient. What I really want in my workflow is "run all the lints that can be run on the package I'm working on in isolation". And maybe we have that and I've just gotten rusty and wasn't running the right commands? IIRC at least in the makefile days running `make lint PKG=foo` would disable the "global" lints so `--short` wasn't necessary.

**Comment by rickystewart** [comment]
> I assumed it would lead to at least a doubling of build times 

To be fair, the text says this:

```
The former will run lint checks while you build. This will make incremental builds slightly slower
```

I don't think this text suggests that your build runtime would be doubled or more. While the meaning of the word "slightly" is not precisely defined, I don't think a 100+% increase is a plausible reading. However, the wording could stand to be updated to be more precise. (However, I don't want to include a reference to any particular figure, as build performance will vary between machines and use cases.)

> Building the selected packages, not everything, right? Or is there something in "nogo" that requires analyzing the whole thing?

I see -- so one problem you've identified is that at the end of `dev lint` (without `--short`), we unconditionally build `cockroach` (plus a few other binaries), instead of the packages specified on the command line. That would be quite easy to fix. However, building even only the selected packages can be very expensive and take a long time (if you do not have a cached build of all the dependencies), thereby making it inappropriate AFAICT to run under `--short`.

> It doesn't make sense to me that a check that adds 10% to build time is "just expensive" and can't be run in short mode.

To be clear, assuming you're using `nolintonbuild`, what takes a long time is the fact that you need to build *everything* including any packages the package in question you may depend on. This can take several minutes (and indeed can use a lot of memory) so `--short` is inappropriate in this case. Assuming you have already built all your dependencies in the `lintonbuild` configuration, then you are correct that it is relatively "quick" to do this.

> StaticCheck is an umbrella framework with many sub-checks. Only some of them are expensive. Last time I looked at this (years ago), the most expensive one was looking for unused exported symbols (which is one of the rare checks that can't be satisified without a global view). I've always thought this was a low-value check and I wouldn't mind getting rid of it entirely.

I think the unused check is considered valuable, but would love to drop `staticcheck` if we could. If you want to push for that, I would say open a separate issue specifically on that topic, or else open a conversation in #db-engineering, etc.

**Comment by rickystewart** [comment]
If `dev lint --short ./pkg/a ./pkg/b` built `./pkg/a` and `./pkg/b` with `lintonbuild` (while not changing the current behavior that `dev lint --short` *does not* build `cockroach` with `lintonbuild`), would that match up to your intuition about how it's supposed to work and "fix" this?

**Comment by bdarnell** [comment]
> While the meaning of the word "slightly" is not precisely defined, I don't think a 100+% increase is a plausible reading

That's fair. I read it as a larger increase because I jumped to the conclusion that the way it worked was that after every `dev build` it would run the corresponding `dev lint`. 

> However, building even only the selected packages can be very expensive and take a long time (if you do not have a cached build of all the dependencies)

Yes. A workflow that runs `lint --short` without also frequently running builds feels very strange to me, though.

> (and indeed can use a lot of memory)

It's a lot of memory, but we give our engineers laptops with enough memory to build without being too disruptive to other activities. We don't give them enough memory to run the full linter suite comfortably.

> If dev lint --short ./pkg/a ./pkg/b built ./pkg/a and ./pkg/b with lintonbuild (while not changing the current behavior that dev lint --short does not build cockroach with lintonbuild), would that match up to your intuition about how it's supposed to work and "fix" this?

Yes.
