### ISSUE TITLE
server: server controller leaking sql tempdirs

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#120233]
The cluster on which #120201 was observed was subsequently noticed to have thousands of tempdirs in each store dir, which seem likely to be the result of #120201 plus a failure to clean up the tempdir after failed service start:

```
✗ scripts/drtprod ssh ua-2 -- "ls /mnt/data1/cockroach | grep cockroach-temp | wc -l"
ua-2:[1 2 3 4 5 6 7 8 9]: ls /mnt/data1/cockroach | g... 9/9
   1:   <ok>
        1

   2:   <ok>
        20585

   3:   <ok>
        20508

   4:   <ok>
        20613

   5:   <ok>
        20621

   6:   <ok>
        20558

   7:   <ok>
        20660

   8:   <ok>
        20572

   9:   <ok>
        20586
```

Jira issue: CRDB-36562

**Comment by michae2** [comment]
[triage] We create a temp directory on server startup, maybe not cleaning it up?

**Comment by yuzefovich** [comment]
I looked into this for a bit, and it seems likely that #120201 is the root cause of a problem, and this was just one manifestation. Here is what happened:
- we have a server controller component that attempts to start an in-process tenant (i.e. UA mode) indefinitely (until the storage node is shut down)
- each attempt to start a tenant failed due to #120201
- on each attempt in `newServerForOrchestrator` we call `makeSharedProcessTenantConfig` which creates a new temp storage directory
- that directory is removed whenever the server's stopper is closed (the corresponding closure is added in `newSQLServer` for both single-tenant and multi-tenant code paths)
- however, because the stopper is actually never closed, we simply accumulate a new closure on each attempt without invoking it. In other words, I think when a particular storage node is shutdown, then we should see all these temp storage directories to be removed.

We could add some custom code to clean up the temp storage directory explicitly after each failed attempt to start a tenant, but I don't think it'd be worth it. Rather we should improve the tenant starting loop to be less aggressive and _perhaps_ have some optional state that performs the opt-in cleanup (temp storage dir removal would be one step of the cleanup, probably there would be others as well).

I'll close this issue as being a manifestation of #120201. cc @stevendanna in case you have thoughts on this topic
