### ISSUE TITLE
What is "live bytes"?

### ISSUE THREAD

**Issue by roy-work** [cockroachdb/cockroach#120528]
**Describe the problem**

If you look at the "Storage" dashboard, you'll see a graph "live bytes". But what is it?

The docs don't answer the question adequately. It is documented [here](https://www.cockroachlabs.com/docs/stable/ui-storage-dashboard#live-bytes), which reads:

> The Live Bytes graph displays the amount of data that can be read by applications and CockroachDB.

I have a CRDB cluster; it contains a single database, with two tables. One table has << 1 KiB of data, and the other is empty. So, to me, "the amount of data that can be read by applications" is << 1 KiB. Possibly (<< 1 KiB) · `$cluster_size`, but this is the graph I am presented with:

![image](https://github.com/cockroachdb/cockroach/assets/53838718/ff8775e7-0678-4a14-a631-208e4e46a9a3)

This is a basically empty DB, and no I/O is occurring on it aside from whatever CRDB might do itself. Why is live bytes increasing, and why is it 4 GiB? That's more than Cockroach says it is using:

![image](https://github.com/cockroachdb/cockroach/assets/53838718/33eb52c9-3d29-4b63-b0b3-b54238ce0f72)

(From the "capacity" graph.)

The docs also mention,

> Live: Number of logical bytes stored in live [key-value pairs](https://www.cockroachlabs.com/docs/v23.2/architecture/distribution-layer#table-data). Live data excludes historical and deleted data.

But again, how can this exceed the total amount of storage the DB is using…?

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up a new CockroachDB cluster ...
2. Add minimal tables & data
3. (Shrink cluster, because the defaults were huge.)
4. Look at UI, be confused.

**Expected behavior**
The docs need to explain CRDB's concepts in sufficient detail to understand them.

**Additional data / screenshots**

N/A

**Environment:**
 - CockroachDB version [e.g. 2.0.x] v23.2.2
 - Server OS: [e.g. Linux/Distrib] Linux
 - Client app [e.g. `cockroach sql`, JDBC, ...] (The dashboard?)

**Additional context**

My live bytes metric has continued to climb, and is now greater than the total amount of storage assigned to the cluster…

Jira issue: CRDB-36732

**Comment by jbowens** [comment]
Hi @roy-work,

Live bytes records the size of all live, logical KV pairs across the database. This includes user tables, like your two tables, but also internal tables and data. The bulk of your volume of live bytes is likely from timeseries data. See this documentation: https://www.cockroachlabs.com/docs/stable/operational-faqs#why-is-disk-usage-increasing-despite-lack-of-writes

Live bytes may be larger than the physical disk usage because live bytes is a _logical_ accounting of the size, not physical. It's calculated before compression and does not include metadata within the storage engine's format.

I'm going to close out this issue, but feel free to reply here with additional questions.
