### ISSUE TITLE
server: expose the ability to shutdown after a drain

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#120520]
**Is your feature request related to a problem? Please describe.**
After a drain operation, a node needs to be shut down manually. In certain container environments, the shutdown procedure can cause latency spikes if the node is not shut down manually after the drain but before the container is killed. Ideally a single command could drain the node and then execute the shutdown of the process.

**Describe the solution you'd like**
The `DrainRequest` already contains and honors a `shutdown` parameter, however the CLI doesn't expose any ability to set it. We should add this ability. 

**Describe alternatives you've considered**
One alternative (possibly a good idea regardless of this) is if dist sender looked at the drain state and invalidated any cache entries against drained nodes. We may want to do this even if we implement this feature. 

**Additional context**
In customer environments that use container management systems, it is hard to get the scripting right to handle draining of nodes. Also draining is almost exclusively used in the context of node shutdown, so there is usually no reason to keep the node running after the drain has completed.

From support issue: https://github.com/cockroachlabs/support/issues/2866

Jira issue: CRDB-36727

**Comment by rafiss** [comment]
Currently, sending a SIGTERM or using a process manager is the documented way to drain a node then shut it down:
- https://www.cockroachlabs.com/docs/stable/node-shutdown#process-termination
- https://www.cockroachlabs.com/docs/stable/node-shutdown#drain-the-node-and-terminate-the-node-process

Note that we used to have a command that would shutdown the node (`cockroach quit`). It was [removed](https://github.com/cockroachdb/cockroach/pull/82988) because we specifically started recommending SIGTERM instead, for the reasons mentioned in https://github.com/cockroachdb/cockroach/pull/47758 and https://github.com/cockroachdb/cockroach/pull/49668. cc @bdarnell

**Comment by bdarnell** [comment]
> One alternative (possibly a good idea regardless of this) is if dist sender looked at the drain state and invalidated any cache entries against drained nodes. We may want to do this even if we implement this feature.

Yes, this seems like a good idea regardless - even with a `drain --shutdown` flag won't you want to avoid the draining node while it is mid-drain?

As @rafiss said, this directly reverses a previous decision - `drain` used to take a `--quit` flag, but we found this was error prone because orchestration software would often restart the program immediately after it exited and it would be complicated to coordinate binary or CLI flag updates. 

I'm open to reconsidering this decision (I think `cockroach quit` was a mistaken design, but `drain --quit` is less problematic), but if so we should be clear about why. We have a solution for drain-then-quit already: have your process manager send a SIGTERM to the process. Why is this not sufficient?

**Comment by andrewbaptist** [comment]
I agree with @bdarnell and @rafiss that we may not need this functionality since SIGTERM exists[. We likely need a scrub of existing documentation and advice about customers usage of SIGTERM as [this page](https://www.cockroachlabs.com/docs/stable/node-shutdown) is still confusing although it is improved as of this PR https://github.com/cockroachdb/docs/pull/18424.

The only realistic difference between SIGTERM and drain is the notification of process completion. Specifically the customer wants to write a script that looks something like:
```
cockroach drain <node>
stop-container
```
But this ran into the problem with the DistSender RangeCache being out of date because the stop-container commend would drop the network interface and require a 3-4s TCP timeout on a few requests to a node with a stale cache since a TCP FIN wasn't sent.

So they now need to either write:
```
cockroach drain --self
kill -TERM $PID
stop-container
```
or
```
kill -TERM $PID
while [ -e /proc/$PID ]
do
    sleep 1
done
stop-container
```
Both are suboptimal. The first (which is what they are doing now) has a "redundant" drain in it since the SIGTERM would have sent a drain anyway, the second requires a loop (or a fixed length sleep and then terminate).

What they really want to do is the simpler:
```
cockroach drain --self --shutdown
stop-container
```

For this customer they were fine with the SIGTERM option, they were only unhappy because it wasn't at all clear that it was necessary.

**Comment by bdarnell** [comment]
What is the parent process of cockroach? In general running cockroach with a parent of pid 1 is an anti-pattern and it should have some parent process (systemd, kubelet, etc) that is responsible for watching its exit status. Then you don't need to poll the PID to see when it exits. 

> because the stop-container commend would drop the network interface

Yuck. People do such awful things with container networking. Destroying a network interface is an extremely disruptive thing to do while the host network is still available (and could be refusing connections on behalf of the process that exited)

**Comment by andrewbaptist** [comment]
I'm not 100% how they set this up and am definitely not a container expert.

The customer wasn't using kubernetes, they were using Nomad, but I think it should be similar. 

In our docs for "directly" using docker we do show an example of starting a container directly using https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac#step-3-start-the-cluster. I couldn't easily tell how we set things up using https://github.com/cockroachdb/cockroach-operator/ but it probably does use a start script.

The container network teardown is really unfortunate as you mentioned. It was really hard to tell why they were hitting the latency and it was due to shutting down a container with the process still running. I'm not sure if our cockroach operator has the same problem. Looking at https://github.com/cockroachdb/cockroach-operator/issues/502 it seems likely that we do manually issue drain and then send a SIGTERM.
