### ISSUE TITLE
ERROR: unknown signature: length(string) (desired <string>)

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#120612]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Run the following statements.
```sql
SELECT ('a') > ALL (LENGTH('b'), ('c'));
```

**Expected behavior**
The following error message was a bit confusing.
```sql
ERROR: unknown signature: length(string) (desired <string>)
SQLSTATE: 42883
```

**Environment:**
Server version: CockroachDB CCL v23.2.2 (x86_64-pc-linux-gnu, built 2024/02/26 21:06:09, go1.21.5 X:nocoverageredesign) (same version as client)

Jira issue: CRDB-36776

**Comment by yuzefovich** [comment]
Thanks for filing the issue!

I agree that the error message is confusing. What it tries to tell you is that `length` builtin function that takes `string` argument and returns `string` result doesn't exist. This particular wording has existed in CRDB for a long time, but I'll send a patch to change it to `ERROR: unknown signature: length(string) (returning <string>)` to see what my colleagues think about such a change.

Our type checking login requires the result to be `string` type because that's the type of the expression `expr` in the `expr operator ANY ()` construct. You can make the query work by applying a cast, e.g.
```sql
SELECT ('a') > ALL (LENGTH('b')::STRING, ('c'));
```

**Comment by sayJason** [comment]
Thanks for your reply. The word `returning` could be much easier to know that it stands for a returning type.
