### ISSUE TITLE
changefeedccl: Add sink Round Trip Time histogram metric

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#121058]
It would be useful to have a histogram metric that reports RTT latency for delivering changefeed data to whichever sink has been configured.  There doesn't appear to be any metrics that would allow a changefeed operator to detect a slow webhook / http / etc. receiver from within Cocrkoach or to distinguish slow receivers from other disfunctions.

Jira issue: CRDB-37052

**Comment by rharding6373** [comment]
There is a metric `changefeed.flush_hist_nanos` that already captures this information (including the time to get an ack from the sink), but there's currently a bug (https://github.com/cockroachdb/cockroach/issues/121248) in the cloud storage sink that limits its usefulness. I'm going to close this issue since once this bug is fixed, it should be able to provide this information.
