### ISSUE TITLE
drt: disk stall testing

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#121942]
On the drt cluster we should stress disk stall. Specifically there should be an operation to temporarily pause a data disk and then unpause it. By varying the time from a second up to 60 seconds we can stress various parts of the system.

For short pauses (<3s), the system should react normally and not lose leases or fail heartbeats. Requests against that node may be slow for a max of 3s. 

For medium pauses (4-20s), the node should lose all the leases, but all operations should recover fully within 10s.

For longer pauses (>20s), the node should terminate due to the disk stall detector.

This overlaps with the storage project to fail over to another drive.

Jira issue: CRDB-37635

**Comment by jbowens** [comment]
I'm going to remove the GA blocker, because I don't think at the least the storage testing element is a GA blocker. We have pretty good coverage of WAL failover and the fataling disk-stall detection through existing nightly roachtests.

For medium pauses, KV has those failover nightly roachtests too, right?

Agreed we should test this all on DRT, but don't want to hold up RC.
