### ISSUE TITLE
restore database failed

### ISSUE THREAD

**Issue by wuwo1952368901** [cockroachdb/cockroach#122168]
CockroachDB version 23.2.2 

Restoring database error with REVERTING prompt. Restore failed. Database cannot be deleted or accessed, error message:

ERROR: internal error while retreving user account memberships: internal error while retrieving user account: get default settings error: database "xxxxxxxxx" is offline: restoring
ERROR: node is running secure mode, SSL connection required

Jira issue: CRDB-37736

**Comment by stevendanna** [comment]
@wuwo1952368901 Apologies for the delay here. Are you able to provide a bit more information to help us debug this problem? The most comprehensive way to get us more information would be to create a "debug.zip" file with `./cockroach debug zip` and submit it to our support system. 

However, you may also be able to get some insight into why the job is failing by connecting to the `defaultdb` or `system` database and then running `SHOW JOBS`, finding the RESTORE job and looking at the particular error that job is reporting.

**Comment by wuwo1952368901** [comment]
After running SHOW JOBS, I obtained the Error log:

**Comment by stevendanna** [comment]
Thanks for the initial information.

It looks like there are at least 2 problems here.

1) The RESTORE is failing because of an S3 timeout reading the data in the bucket. To understand this error we would likely need to look at further CRDB logs and, if you are using a non-AWS S3 compatible service, look into some details of that service.

2) The failed RESTORE is not properly reverting the table descriptors because of a bug in GC TTL handling. I've described the bug and started work on a potential fix here: https://github.com/cockroachdb/cockroach/pull/123202.

In order to bring those table descriptors into a state where they can be manually dropped will likely require the use of some internal debugging tools.  The procedure to fix the descriptors will require inspecting data in your system tables.  The debug.zip command I mentioned in my last message will include the information required. The debug.zip may contain sensitive information, so I recommend submitting it via our customer support system.

**Comment by wuwo1952368901** [comment]
How to delete databases and restore tasks that have already gone wrong?

**Comment by stevendanna** [comment]
(Apologies on this issue getting closed. The PR above merged which was listed as a fix for the underlying bug here.)

> How to delete the database that has been restored with errors and the restoration task?

To delete this database we'll first need to bring it back online. To bring the database back online I'll need to generate some SQL statements for you to run. However, the exact SQL statements depend on the state of your system.  If you generate a debug.zip using `cockroach debug zip` (https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip) you can then send it to us securing in a support ticket: https://support.cockroachlabs.com/hc/en-us/requests/new. From that artifact, I'll be able to generate the required SQL statements for you.  When opening the ticket, please reference this github issue.

**Comment by stevendanna** [comment]
I'm closing this issue as the underlying bug has been fixed. However, if your database still needs to be repaired, please do reach out to support as we will be happy to work with you on the remediation procedure.
