### ISSUE TITLE
import: TestImportPgDumpSchemas/target-table-schema.sql times out under stress on 24.1 release branch

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#122126]
I'm trying to merge a backport but my CI runs keep failing with `TestImportPgDumpSchemas/target-table-schema.sql` timeouts under stress.  [Here's](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14777424?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) the latest example.  

Should we be disabling this test under stress? Or increase the timeout?

Jira issue: CRDB-37716

**Comment by yuzefovich** [comment]
The artifacts for the build are now gone. We had this:
```
panic: test timed out after 3m36s
running tests:
	TestImportPgDumpSchemas (20s)
	TestImportPgDumpSchemas/target-table-schema.sql (3s)
```
IIUC this means that some other test in `sql/importer` package might have taken too long, but it's unclear what that test was. The failure was in `stressrace` config. This is not essential for passing CI and to merge things, and we haven't seen this happen since AFAICT, so I'm closing as a flake.
