### ISSUE TITLE
sql: connection to server consistently fails if started too soon

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12314]
Found by trying to use the [testserver](https://github.com/cockroachdb/cockroach-go/tree/master/testserver)

The tests run a real cockroach binary to create a new single-node cluster and waits until `SHOW DATABASES` does not throw an error to ensure that we are properly initialized.

However, the testserver started failing recently with the query returning: `pq: database "information_schema" does not exist` at every attempt. Creating a new connection is successful.

A little bit of bisecting shows that the testserver was fine at `beta-20161201` but is failing with `beta-20161208`

**Comment by mberhault** [comment]
see https://github.com/cockroachdb/cockroach-go/pull/22 for an easy way to reproduce:
```
~/cockroach/src/github.com/cockroachdb/cockroach-go/testserver $ go test ./... --cockroach-binary cockroach-beta-20161201.linux-amd64/cockroach 
ok  	github.com/cockroachdb/cockroach-go/testserver	0.537s

~/cockroach/src/github.com/cockroachdb/cockroach-go/testserver $ go test ./... --cockroach-binary cockroach-beta-20161208.linux-amd64/cockroach 
2016/12/13 09:03:38 Using custom cockroach binary: /store/cockroach-binaries/cockroach-beta-20161208.linux-amd64/cockroach
2016/12/13 09:03:38 process 1978 started: /store/cockroach-binaries/cockroach-beta-20161208.linux-amd64/cockroach start --logtostderr --insecure --port=0 --http-port=0 --socket=/tmp/cockroach-testserver608683055/.s.PGSQL.26257 --store=/tmp/cockroach-testserver608683055
2016/12/13 09:03:38 WaitForInit: pq: database "information_schema" does not exist
2016/12/13 09:03:38 WaitForInit: pq: database "information_schema" does not exist
<SNIP>
2016/12/13 09:03:43 WaitForInit: pq: database "information_schema" does not exist
2016/12/13 09:03:43 WaitForInit: pq: database "information_schema" does not exist
--- FAIL: TestRunServer (5.53s)
	testserver.go:149: pq: database "information_schema" does not exist
FAIL
FAIL	github.com/cockroachdb/cockroach-go/testserver	5.529s
```

**Comment by tamird** [comment]
I think we should prioritize getting this fixed for this week's beta.

**Comment by mberhault** [comment]
git bisect with `make build && go test ../cockroach-go/testserver/... --custom-binary=./cockroach` tells me that sha 358e8b5589a66f766d8f450f324c7ac56a19c8a1 is the culprit.

**Comment by tamird** [comment]
Nice work tracking this down.

**Comment by nvanbenschoten** [comment]
Yeah that's what we were expecting, but I pretty confident that that change didn't actually introduce the issue, it just surfaced it. I'm still in the middle of investigating, but I've seen situations where [`virtualSchemaHolder.getVirtualTableEntry`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/virtual_schema.go#L224) is called before [`virtualSchemaHolder.init`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/virtual_schema.go#L137). This shouldn't be possible, because `virtualSchemaHolder.init` is called in `Executor.Start`, so something strange is happening.

**Comment by nvanbenschoten** [comment]
So after a lot of confusion, the issue seems to be related to what I brought up [here](https://github.com/cockroachdb/cockroach-go/pull/22#issuecomment-265587865). We initialize the [sql executor](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L639) after we begin [serving the pgServer connection](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L513). If I bring the `s.sqlExecutor.Start` line above, the issue seems to go away, and I'm no longer ever seeing uninitialized `virtualSchemaHolders`.

**Comment by nvanbenschoten** [comment]
I'm preparing a fix now.

**Comment by tamird** [comment]
I started typing:

That's very strange, since actual serving doesn't start until
> https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L650


But then I noticed that unix sockets have their own very special handling.
Nice find.
