### ISSUE TITLE
jwtauthccl : http client missing support for proxies

### ISSUE THREAD

**Issue by BabuSrithar** [cockroachdb/cockroach#123575]
**Describe the problem**

The new JWKS Auto fetch feature introduced through https://github.com/cockroachdb/cockroach/pull/117054 ignored http transport env vars like HTTP_PROXY. As a result, the outbound connection to fetch jwks url would fail. 

**To Reproduce**

Set `server.jwt_authentication.jwks_auto_fetch.enabled` cluster setting to True in an environment with HTTP_PROXY setup. 

**Expected behavior**
The JWT Auth should work as expected, but it returns error: "JWT authentication: unable to validate token"

**Environment:**
 - CockroachDB version : v23.1.17, v24.1 

**Additional context**
This is similar to https://github.com/cockroachdb/cockroach/issues/32803

Jira issue: CRDB-38408

gz#21355

Related to : https://github.com/cockroachdb/cockroach/issues/123605

**Comment by bdarnell** [comment]
This has happened a couple of times, and there are other inconsistencies in the HTTP clients we use (notably, the OIDC client library uses the default http transports which support proxies but don't have the lower timeouts we use elsewhere). We should try to centralize our use of http clients in 1 (or a few) places. This is tricky because some libraries access the default client directly. We need to either modify the global defaults to have the configuration we want (such as timeouts) or do something to disallow the use of global defaults (installing some sort of poisoned objects that will crash when used?)

**Comment by BabuSrithar** [comment]
> This has happened a couple of times, and there are other inconsistencies in the HTTP clients we use (notably, the OIDC client library uses the default http transports which support proxies but don't have the lower timeouts we use elsewhere). We should try to centralize our use of http clients in 1 (or a few) places. This is tricky because some libraries access the default client directly. We need to either modify the global defaults to have the configuration we want (such as timeouts) or do something to disallow the use of global defaults (installing some sort of poisoned objects that will crash when used?)

Is there something we can do on lint check side? at least for direct HTTP client usage in our code.

**Comment by souravcrl** [comment]
the following backports were merged:
[release-24.1: ccl,sql,util: Fix jwt auth and add sensitive error logs #124103](https://github.com/cockroachdb/cockroach/pull/124103)
 [release-23.1: ccl,sql,util: Fix jwt auth and add sensitive error logs #124130](https://github.com/cockroachdb/cockroach/pull/124130)
[release-23.2: ccl,sql,util: Fix jwt auth and add sensitive error logs #124140](https://github.com/cockroachdb/cockroach/pull/124140)
