### ISSUE TITLE
sql: cannot override built-in functions using search_path

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#124538]
In PostgreSQL it's possible to override built-in functions by moving `pg_catalog` to the back of the search_path. Here's a demonstration with PostgreSQL 16.3:

```
michae2=# CREATE FUNCTION now() RETURNS TIMESTAMP STABLE LANGUAGE SQL AS $$ SELECT TIMESTAMP '1999-12-31 23:59:59.999999'; $$;
CREATE FUNCTION
michae2=# SELECT now();
              now
-------------------------------
 2024-05-21 16:36:29.446258-07
(1 row)

michae2=# SHOW search_path;
   search_path
-----------------
 "$user", public
(1 row)

michae2=# SET search_path = public, pg_catalog;
SET
michae2=# SELECT now();
            now
----------------------------
 1999-12-31 23:59:59.999999
(1 row)
```

This doesn't work in CockroachDB, at least as of v24.1.0-rc.2:

```
demo@127.0.0.1:26257/defaultdb> CREATE FUNCTION now() RETURNS TIMESTAMP STABLE LANGUAGE SQL AS $$ SELECT TIMESTAMP '1999-12-31 23:59:59.999999'; $$;
CREATE FUNCTION

Time: 14ms total (execution 10ms / network 5ms)

demo@127.0.0.1:26257/defaultdb> SELECT now();
               now
---------------------------------
  2024-05-21 23:41:11.600083+00
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SHOW search_path;
    search_path
-------------------
  "$user", public
(1 row)

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SET search_path = public, pg_catalog;
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT now();
               now
---------------------------------
  2024-05-21 23:41:36.592942+00
(1 row)

Time: 0ms total (execution 0ms / network 0ms)
```

The only way to get the override is to qualify the function name with a schema:

```
demo@127.0.0.1:26257/defaultdb> SELECT public.now();
             now
------------------------------
  1999-12-31 23:59:59.999999
(1 row)

Time: 4ms total (execution 4ms / network 0ms)
```

Jira issue: CRDB-38945

Epic CRDB-37763

**Comment by rafiss** [comment]
I haven't looked into what the code is doing right now, but the thing we want it to use when resolving the name is `(sessiondata.SearchPath).Iter()`: 
https://github.com/cockroachdb/cockroach/blob/d4957b30ae09582c47d2edc6b6f101ef48655b1e/pkg/sql/sessiondata/search_path.go#L133-L159

**Comment by rafiss** [comment]
The code that needs to be fixed is: https://github.com/cockroachdb/cockroach/blob/45771c65f603c36d044506f9b60762c8ee1ed739/pkg/sql/schema_resolver.go#L455-L467

as well as possibly other implementations of `ResolveFunction`. I think the `MergeWith` function should be updated so that it orders the overloads by search path.

**Comment by Vidyap23** [comment]
Hi @rafiss I would like to work on this issue, if no one has picked it up yet

**Comment by rafiss** [comment]
@Vidyap23 sure, feel free to submit a PR. Review our contribution guidelines here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072641/What+is+a+Good+CockroachDB+PR

I recommend fixing this by modifying the `MergeWith` function so that it accepts a SearchPath parameter. https://github.com/cockroachdb/cockroach/blob/41cb9747916da3e1aa71f68407ad3b6b82f22a04/pkg/sql/sem/tree/function_definition.go#L236-L238

When it combines the two lists, it should make sure they are ordered by the order the schemas appear when using `SearchPath.Iter()`.

To test this, you can use the example that @michae2 wrote above. You can add that test to `pkg/sql/logictest/testdata/logic_test/udf`.

**Comment by XiaochenCui** [comment]
@michae2 @rafiss 
Hi, I just opened a pr https://github.com/cockroachdb/cockroach/pull/126048 to fix this issue, can you take a look and give some suggestions? Thanks a lot!
