### ISSUE TITLE
db: IncrementValRetryable can retry endlessly under contention

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#124756]
**Describe the problem**
The `IncrementValRetryable` [method](https://github.com/cockroachdb/cockroach/blob/8a6696ab7f6ca85b8f75c793dbd0b3f9de619762/pkg/kv/db.go#L1188) attempts to increase a key's value and retries under certain conditions. However, we don't set the `MaxRetries` option within `RetryOptions` to cap the number of retries. Under high contention, this can result in infinite retries. See [this issue](https://github.com/cockroachlabs/support/issues/2957) for more context.

**Expected behavior**
We should error out after some threshold number of retries.

Jira issue: CRDB-39064

**Comment by nvanbenschoten** [comment]
I'm going to close this out. `IncrementValRetryable` should not retry indefinitely due to transaction contention because of server-side refreshes. Neither a write-write conflict nor a read-write conflict will require a client-side retry, so starvation should not be possible.

What we saw in the linked support ticket was slightly different. The loop was spinning due to a cancelled context, but it also wasn't breaking out due to that cancelled context. This has since been fixed in https://github.com/cockroachdb/cockroach/pull/120655.
