### ISSUE TITLE
sql: int4 support

### ISSUE THREAD

**Issue by kerneldump** [cockroachdb/cockroach#12481]
Current build information:
Build Tag:   beta-20161215
Build Time:  2016/12/15 15:10:48
Platform:    linux amd64
Go Version:  go1.7.3
C Compiler:  gcc 4.9.2

Hello, I’m trying to replace MySQL/PostgreSQL with CockroachDB for RunDeck (http://rundeck.org/). Having issues with “int4” and “create sequence”. Would it be possible to add an alias for int4 (similar to what you have for  int8) and “create_sequence” support. Here are my logs when trying to start rundeck daemon => http://pastebin.com/yMqJGEUd

Relevant lines:
2016-12-17 09:08:14,570 [main] ERROR hbm2ddl.SchemaUpdate  - ERROR: syntax error at or near "int4"
2016-12-17 09:08:14,952 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create sequence hibernate_sequence

**Comment by bdarnell** [comment]
`CREATE SEQUENCE` is tracked in #5811. 

We support `int8` but not other sized integer types because our integers are in fact 8 bytes. So it would be slightly misleading for us to implement `int4` backed by a 64-bit integer, but maybe it's worthwhile for the compatibility (it seems likely that most users specify the minimum size they need and don't care too much if the actual type has more range than specified). I suppose we could even turn the smaller integer types into integers with a `CHECK` constraint that their values are in range.

**Comment by mjibson** [comment]
We are already subtly broken here:

postegres:

```
postgres=# select -1234135568 << 2;
  ?column?  
------------
 -641574976
```

cockroach:

```
root@:26257/> select -1234135568 << 2;
+---------------------+
| (- 1234135568) << 2 |
+---------------------+
|         -4936542272 |
+---------------------+
```

This is happening because Postgres leaves that number as an "integer" (32-bits), resulting in shifting away of a 1 in the high bit.

**Comment by mjibson** [comment]
I vote we move this issue to the 1.1 milestone because I think it'll be hard to tackle it correctly in 2 days before the feature freeze.

**Comment by dianasaur323** [comment]
Well, this is apparently a compatibility issue that a user has encountered, so we may have to provide a bug fix before 1.1 if it becomes a blocker.

**Comment by vivekmenezes** [comment]
potential startup project for masha.

**Comment by jordanlewis** [comment]
See also #14493, which if solved could be a potentially more holistic solution for this kind of thing.
