### ISSUE TITLE
DB Console UI shows "undefined" when role session variable is altered

### ISSUE THREAD

**Issue by osmes** [cockroachdb/cockroach#124871]
**Describe the problem**

DB Console UI shows message "Role Altered: User root altered role <role_name> with options undefined" when altering a role to change session variables like with `ALTER ROLE test SET timezone = 'America/New_York';`. The `undefined` keyword implies that there is a problem in the reporting even if the intention is to not convey specific details of a session variable change.

<img width="1088" alt="Screenshot 2024-05-30 at 12 16 26 PM" src="https://github.com/cockroachdb/cockroach/assets/11637300/e1105ba9-189a-4d3f-ba20-e7c602016fd1">

**To Reproduce**

1. Started `cockroach demo`
2. `CREATE ROLE test;`
3. `ALTER ROLE test WITH CONTROLCHANGEFEED;`
4. `ALTER ROLE test SET timezone = 'America/New_York';`
5. Observe `with options CONTROLCHANGEFEED` for step 3, but `with options undefined` for step 4.

**Expected behavior**
The UI should either:
- include the session variable change performed by the command
- indicate that a session variable was set rather than report as `with options undefined`
- omit `undefined` to leave the UI reporting for session variable changes looking like "Role Altered: User root altered role <role_name> with options".

**Environment:**
 - CockroachDB version 23.1, 23.2, 24.1

Jira issue: CRDB-39120

**Comment by rafiss** [comment]
This looks like it should be fixed in the frontend. The code here is assuming that `info.Options` will be set.
https://github.com/cockroachdb/cockroach/blob/9e61527e7dbdbd4da0de94a424a8d938c5ce1f36/pkg/ui/workspaces/db-console/src/util/events.ts#L180-L181

But for `ALTER ROLE ... SET`, we only populate `info.SetInfo`: https://github.com/cockroachdb/cockroach/blob/c4065c065c0cf086cdeff5b26d0af0920498598e/pkg/sql/alter_role.go#L501-L506

This was done in 0a0271c7ac9c6aab609c700763109f90c0df1b80.

Before that, this would get logged similar to other `ALTER ROLE` statements: https://github.com/cockroachdb/cockroach/blob/c4065c065c0cf086cdeff5b26d0af0920498598e/pkg/sql/alter_role.go#L270-L275

--- 

Changing the frontend code to check if `info.Options` is defined sounds like the right fix.
