### ISSUE TITLE
storage: Check lease before command queue for write commands

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#12490]
@petermattis noticed in #12465 that we're not checking the lease until after a command has been through the command queue. We should probably be checking the lease first (and then maybe again after the command queue, in case it expired in between)

**Comment by petermattis** [comment]
I believe this is only a performance optimization and we don't currently have a workload for which we've seen a need to fix this. @bdarnell Please correct if I'm mistaken. Pushing to push Later.

**Comment by bdarnell** [comment]
Yup, definitely post-1.0.

**Comment by petermattis** [comment]
@tschottdorf is more of an expert on leases (and this code), than I am.

**Comment by nvanbenschoten** [comment]
@andreimatei and I were discussing this a few days ago after noticing that where leases are checked is inconsistent between read and write code paths. We came up with an explanation that sounded somewhat reasonable after some discussion - for reads the top priority is to reject them ASAP, for writes to top priority is to avoid proposing a write that will just end up being rejected after replication because of an invalid lease. The thing that was the least clear was whether this decision was mostly arbitrary, whether it was required for correctness, or whether the answer is somewhere in between.

I don't have a strong opinion on if there are any changes to be made here, but I think we should have a clear answer to why the lease checks are where they are and we should make this clear in the code. Once we do that, we can probably close this issue because it looks sufficiently stale.

**Comment by bdarnell** [comment]
When leases were first introduced (#604) we acquired the lease before the command queue for both reads and writes. This was reversed (for both) in #831, and I think it was a correctness issue at the time but I'm not sure that still applies due to subsequent changes to the timestamp cache. Reads and writes diverged in #4847, in which reads switched to check the lease before the command queue. This appeared to be motivated mainly by code cleanliness. 

I think we can just close this. Adding a second pre-command-queue lease check for writes might be a small performance optimization but given the age of this issue it doesn't seem to be worth the complexity.
