### ISSUE TITLE
storeliveness: scalability testing with multi-store

### ISSUE THREAD

**Issue by miraradeva** [cockroachdb/cockroach#125057]
The main non-functional requirement for leader leases is:
```
Performance and scalability: No workload regression when compared to epoch based leases on 100 node cluster, where each node has 8 stores and 32 vCPUs
```

To validate that, run a test like this after the prototype is finished, and again after the production code is complete:
- Disable the lease- and raft-level changes and turn store liveness on.
- Set up a roachprod cluster with 100 nodes, 8 stores each, 32 vCPUs, 1 region, 1AZ.
- Run kv50 with 500k splits. This will ensure on average each store needs to heartbeat every other store.
- Grab a CPU profile.
- Turn off store liveness and observe changes in: CPU utilization, network bytes sent and received.

Jira issue: CRDB-39239

Epic CRDB-37522

**Comment by nvanbenschoten** [comment]
I picked up where @miraradeva left off on this testing to determine whether the current architecture of store liveness in the leader lease prototype (https://github.com/cockroachdb/cockroach/pull/123789) will be sufficiently scalable. I used the following script, adapted to a slightly larger cluster than before:
```
# Create a 120-node 12-store cluster.
roachprod create nathan-store-liveness --nodes=120 --gce-machine-type='n2-standard-32'
for i in {2..12}; 
do 
  roachprod run nathan-store-liveness -- "mkdir /mnt/data1/data$i"; 
  roachprod run nathan-store-liveness -- "sudo ln -s /mnt/data1/data$i /mnt/data$i"; 
done
roachprod put nathan-store-liveness artifacts/cockroach

# Quiescence is currently disabled in the prototype; enable it here.
roachprod start nathan-store-liveness --store-count=12
roachprod sql nathan-store-liveness:1 -- -e 'SET CLUSTER SETTING kv.storeliveness.enabled = false'

# 300,000 ranges should be enough to have all-to-all store communication
roachprod run nathan-store-liveness:1 -- './cockroach workload init kv --splits=300000 {pgurl:1}'

# Grab a CPU profile

# Turn on store liveness
roachprod sql nathan-store-liveness:1 -- -e 'SET CLUSTER SETTING kv.storeliveness.enabled = true'

# Watch for changes in the CPU and Network graphs.
```
With that script and some tweaks to the prototype, I first confirmed that stores were almost entirely connected due to the 1M ranges with random replication:
```
I240607 20:06:30.488308 1386615 kv/kvserver/storeliveness/support_manager.go:227 ⋮ [T1,Vsystem,n1,rangefeed=‹settings-watcher›] 65110  store {1 12} sent heartbeats to 1331 remote stores
I240607 20:06:30.488939 1386621 kv/kvserver/storeliveness/support_manager.go:227 ⋮ [T1,Vsystem,n1,rangefeed=‹settings-watcher›] 65111  store {1 8} sent heartbeats to 1328 remote stores
I240607 20:06:30.489021 1386614 kv/kvserver/storeliveness/support_manager.go:227 ⋮ [T1,Vsystem,n1,rangefeed=‹settings-watcher›] 65112  store {1 10} sent heartbeats to 1316 remote stores
I240607 20:06:30.489048 1386619 kv/kvserver/storeliveness/support_manager.go:227 ⋮ [T1,Vsystem,n1,rangefeed=‹settings-watcher›] 65113  store {1 3} sent heartbeats to 1321 remote stores
```

Next, I measured the cost of store liveness in an unoptimized version of the prototype in a cluster with 1,440 stores.

<img width="432" alt="Screenshot 2024-06-07 at 4 33 48 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/93e4608a-9fa5-413e-89b0-41658ed8f69c">
<img width="995" alt="Screenshot 2024-06-07 at 4 34 10 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/f0e8755d-5daa-4047-902e-76730cc84821">
<img width="1000" alt="Screenshot 2024-06-07 at 4 33 56 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/a435e393-91a3-4c74-a297-9e71797c90d5">
<img width="1764" alt="Screenshot 2024-06-07 at 4 30 49 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/830fdfad-be9f-4682-9cfd-c14e5566b979">

[off_profile.pb.gz](https://github.com/user-attachments/files/15744999/off_profile2.pb.gz)
[on_profile.pb.gz](https://github.com/user-attachments/files/15745000/on_profile.pb.gz)

We see that on 32 vCPU machines, store liveness communication results in an increase in CPU utilization from **4.1%** to **5.45%**, or about `(5.45-4.1)/100 * 32 = 0.43 cores`. In a cluster of this size, that's actually pretty good, but there is some low hanging fruit here, even without changing the store liveness architecture.

From the CPU profile, we see that the CPU time is split pretty evenly between sending messages, receiving messages, and processing messages.

I [added a commit to the prototype](https://github.com/cockroachdb/cockroach/pull/123789/commits/f92706175096e1b28473685eb56ee91d26f04127) to add a small (10ms) delay in the store liveness transport to promote batching of messages from the same source node to the same target node. Doing so has the following effect:

<img width="441" alt="Screenshot 2024-06-07 at 5 23 35 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/3a6945bb-2f5b-4ab9-8e4c-f3ba539c1edc">
<img width="998" alt="Screenshot 2024-06-07 at 5 24 00 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/fa7e6458-b79b-4616-a359-a6305a0f558f">
<img width="1002" alt="Screenshot 2024-06-07 at 5 23 54 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/784a7a50-38e7-457b-b413-32697cce8d2a">
<img width="1767" alt="Screenshot 2024-06-07 at 5 02 40 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/a369685e-1293-406a-8595-f629f626121a">

This change cuts the cost of store liveness by about 75%. We now see an change in CPU utilization from **3.95%** to **4.25%**, or about `(4.25-3.95)/100 * 32 = 0.096 cores`.

With store liveness using less than 10% of a single vCPU on each node in a 1,440 store cluster (orders of magnitude beyond usual scale), this cost seems reasonable.

Other possible optimizations that we have discussed are:
1. persist a `max_supported` timestamp in each `handleMessage` batch, instead of an `end_time` timestamp for each supporting store.
2. drive heartbeats from all stores on a given node using the same timer. Doing so will naturally result in more batching over the wire, to the supporter's disk, and back over the wire.

My conclusion from this is that:
1. the current store liveness architecture is sufficiently scalable.
2. we have concrete ideas for how to optimize it further for multi-store deployments, if we decide that we need to.

**Comment by miraradeva** [comment]
I re-ran the above experiment with the production implementation of store liveness. Unlike the prototype, store liveness heartbeats are no longer started upon store startup; instead, they are driven by Raft if leader leases are enabled. So we can't really do the same comparison of `cr.node.sys.cpu.combined.percent-normalized` as with the prototype because the increase will be attributable to store liveness but also the rest of the Raft and lease layers. 

```
# Create a 120-node 12-store cluster.
roachprod create mira-store-liveness --nodes=120 --gce-machine-type='n2-standard-32'
for i in {2..12}; 
do 
  roachprod run mira-store-liveness -- "mkdir /mnt/data1/data$i";  
  roachprod run mira-store-liveness -- "sudo ln -s /mnt/data1/data$i /mnt/data$i"; 
done
roachprod put mira-store-liveness artifacts/cockroach
roachprod start mira-store-liveness --store-count=12

# Turn store liveness off.
roachprod sql mira-store-liveness:1 -- -e 'SET CLUSTER SETTING kv.store_liveness.enabled = false'

# 300,000 ranges should be enough to have all-to-all store communication.
roachprod run mira-store-liveness:1 -- './cockroach workload init kv --splits=300000 {pgurl:1}'

# Scatter the ranges since otherwise, due to the sequential splits, we don't get all-to-all store liveness communication.
roachprod sql mira-store-liveness:1 -- -e 'alter table kv.kv scatter'

# Grab a before CPU profile.

# Turn store liveness on.
roachprod sql mira-store-liveness:1 -- -e 'SET CLUSTER SETTING kv.store_liveness.enabled = true'

# Grab an after CPU profile and watch the CPU and Network graphs.

```

This resulted in each store heartbeating ~800-900 other store, so not quite all-to-all communication (all to all: `120 nodes * 12 stores = 1,440`). Running with 500k splits should help increase that. 

Here's a CPU profile for n1, which was at 8.58% CPU utilization at the time.

<img width="1725" alt="Image" src="https://github.com/user-attachments/assets/5fe7259a-1b5d-483c-a02d-dc380062aa65" />

So, `8.58% of 16 cores = 1.37 cores`. Store liveness used 11.9% of that, yielding `11.9 % of 1.37 cores = 0.16 cores` used by store liveness. This is slightly higher than the value of `0.096` measured in the prototype but still a good result (in a second run of this test I observed `0.098`, so very close).

**Comment by miraradeva** [comment]
I re-ran this again, this time with store liveness on at first and then off, and also getting a closer to all-to-all communication by using RF=5 and 400k splits.

```
# Create a 120-node 12-store cluster.
roachprod create mira-store-liveness --nodes=120 --gce-machine-type='n2-standard-32'
for i in {2..12}; 
do 
  roachprod run mira-store-liveness -- "mkdir /mnt/data1/data$i";  
  roachprod run mira-store-liveness -- "sudo ln -s /mnt/data1/data$i /mnt/data$i"; 
done
roachprod put mira-store-liveness artifacts/cockroach
roachprod start mira-store-liveness --store-count=12

# Initialize kv.
roachprod run mira-store-liveness:1 -- './cockroach workload init kv {pgurl:1}'

# Set RF=5.
roachprod sql mira-store-liveness:1 -- -e 'alter database kv configure zone using num_replicas = 5;'

# 400,000 ranges should be enough to have all-to-all store communication.
roachprod run mira-store-liveness:1 -- './cockroach workload init kv --splits=400000 {pgurl:1}'

# Grab a before CPU profile.

# Turn store liveness off to see change in CPU and Networking.
roachprod sql mira-store-liveness:1 -- -e 'SET CLUSTER SETTING kv.store_liveness.enabled = true'
```

This time I managed to get closer to all-to-all communication. Each store sent out ~ 1.1k - 1.2k heartbeats. I looked at CPU profiles from two nodes and they looked very similar to the one above. Doing the same approximation of the CPU usage of store liveness, I got `0.16` cores.

[cpu-on-n2-9-87.pb.gz](https://github.com/user-attachments/files/19186022/cpu-on-n2-9-87.pb.gz)
[cpu-on-n3-10-32.pb.gz](https://github.com/user-attachments/files/19186023/cpu-on-n3-10-32.pb.gz)

After turning store liveness off, we see quite a change in CPU. This includes the entire leader lease stack.

<img width="964" alt="Image" src="https://github.com/user-attachments/assets/da599343-4e9d-4ba5-a244-a505a2b2389f" />
