### ISSUE TITLE
raft: support disabling heartbeats

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#125248]
Raft fortification over Store Liveness present the opportunity to remove raft heartbeats. We should do so once these concepts have been migrated in and once the role of raft heartbeats to drive commit index propagation has been removed (https://github.com/cockroachdb/cockroach/issues/122100).

Jira issue: CRDB-39337

Epic CRDB-37522

**Comment by pav-kv** [comment]
#122100 is not so much about removing the dependency on heartbeats to drive commit index - the issue makes the latter more efficient.

Today, we have 2 mechanisms: `Commit` is delivered in `MsgApp`s and heartbeats. Heartbeats mostly close the liveness gap, in cases when `MsgApp`s are dropped. We should probably have another issue to make `MsgApp` commit index propagation reliable, so that we don't need heartbeats to close the gap.

**Comment by nvanbenschoten** [comment]
Addressed by [#128497](https://github.com/cockroachdb/cockroach/pull/128497) and [#131976](https://github.com/cockroachdb/cockroach/pull/131976).
