### ISSUE TITLE
distsql: support outer hash joins 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12550]
The outer join bug fixed by #12364 is still present in distsql. This needs to be addressed/propagated.

**Comment by knz** [comment]
cc @RaduBerinde @jordanlewis

**Comment by RaduBerinde** [comment]
Because of that issue (and a couple others), the distsql doesn't yet support outer joins. Changing the title accordingly and making a list of the TODOs:

- [ ] fix the outer join implementation to use the "on" expression correctly
- [ ] support merged columns in the joiner (both in expressions and in the output columns)
- [ ] enable planning for outer joins

**Comment by jordanlewis** [comment]
I don't have the bandwidth to re-learn this in time: @arjunravinarayan @RaduBerinde?

**Comment by arjunravinarayan** [comment]
I can handle this (but not immediately).

**Comment by RaduBerinde** [comment]
I don't think it's a hard requirement to support outer joins in distsql initially. I think we are missing some filtering optimizations there too.

**Comment by cuongdo** [comment]
I'd suggest leaving this out for 1.0. We should focus on quality and stability for the queries we already support for distsql.

**Comment by arjunravinarayan** [comment]
Closed by #17017.
