### ISSUE TITLE
ui: duplicate nodes show up in nodes view

### ISSUE THREAD

**Issue by cppforlife** [cockroachdb/cockroach#12587]
Version used: 

```
Build Tag:   beta-20161215
Build Time:  2016/12/15 15:10:48
Platform:    linux amd64
Go Version:  go1.7.3
C Compiler:  gcc 4.9.2
```

Somehow I ended up with duplicate nodes (3 and 4). Cluster page also states that there are 4 nodes. I always had 3 nodes from the start. There was no scaling up or down. Note that no 3 and no 4 have same identifiers.

![screen shot 2016-12-27 at 11 22 22 pm](https://cloud.githubusercontent.com/assets/185847/21516276/8abd0db0-cc8b-11e6-935e-b9ea1f9995d7.png)

I got the data from the nodes some time after the screenshot. Let me know if someone wants to take a look at it (don't want to share it publicly).

**Comment by a-robinson** [comment]
I assume that if you click into the two nodes with the same hostname that they have different IDs (e.g. "Node 1" vs "Node 4").

The most likely way that this would happen is if you had a 3-node cluster up, then brought at least one of the nodes down and brought it back up without its original storage directory/data. The node's ID is tied to its storage -- if it loses its storage, then it has to re-register with the cluster and get a new ID, even though it's at the same address. Does this sound like something that may have happened, @cppforlife?

This is something that we should be able to improve the UX around, since it is indeed very confusing.

Related to #10365

@kuanluo @maxlang

**Comment by mrtracy** [comment]
@kuanluo This is the issue where we may want a nodeID column in the nodes list

**Comment by kuanluo** [comment]
@mrtracy Yes, let's add the nodeID column as the first one on the left.
