### ISSUE TITLE
sql: Can set column default that fails column's check constraint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#12601]
You can set a column to default to a value that fails its check constraint. If possible, we should not allow such a default value to be set in the first place. Or, if the default is set before the check constraint, we should not allow the check constraint to be set.

~~~ shell
root@:26257> show columns from test.t1;
+-------+------------+-------+---------+
| Field |    Type    | Null  | Default |
+-------+------------+-------+---------+
| a     | INT        | false | NULL    |
| b     | STRING(10) | true  | 'fa'    |
| c     | INT        | true  | NULL    |
| d     | INT        | true  | NULL    |
+-------+------------+-------+---------+
(4 rows)

root@:26257> ALTER TABLE test.t1 ADD CONSTRAINT b_check CHECK (b = 'boo');
ALTER TABLE

root@:26257> ALTER TABLE test.t1 ALTER COLUMN b SET DEFAULT 'fa';
ALTER TABLE

root@:26257> INSERT INTO test.t1 VALUES (4);
pq: failed to satisfy CHECK constraint (b = 'boo')
~~~

**Comment by dt** [comment]
While we can evaluate the default expr at creation time to see if the value it produced then violates any CHECKs, we can't be sure that that will then also hold for all subsequent evaluations... an easy example is a default value of `NOW()` that could easily pass a some `CHECK` expressions at creation but then fail them later (e.g. WEEKDAY or something). Since we thus can't actually provide any strong guarantees that a `DEFAULT` will never fail a `CHECK` at evaluation time, it might be confusing to appear to do so part of the time?

**Comment by jseldess** [comment]
Good points, @dt. I thought it might be possible to validate a check constraint against a default, and vice versa, whenever either are created or changed. But we can't do this consistently, or don't want to add this complexity, let's just close. Once back from vacation, I can check how this works in postgres, just for context.
