### ISSUE TITLE
docs: join behaviour & restarts

### ISSUE THREAD

**Issue by cppforlife** [cockroachdb/cockroach#12612]
this is more of a general question (wasn't clear from the docs):

does cockroach instance maintain some state (in its persistent data directory) that it is part of a cluster? is it ok to restart node that didnt & doesn't have --join flag set if other nodes joined it before the restart? if it does maintain internal joined state, in which cases does cockroach decide to form a new cluster?

alternatively can i just provide --join for the first node with its future peers that do not exist yet? (that would ideal)

**Comment by knz** [comment]
Hi @cppforlife thanks for your question. Great suggestion for our documentation.

To answer your questions:

> does cockroach instance maintain some state (in its persistent data directory) that it is part of a cluster?

yes, membership is persisted in the data files. It is only guaranteed to be persisted if the node has started and joined successfully though -- if you interrupt the start-up before the node is ready, the membership may not be persisted yet.

> is it ok to restart node that didnt & doesn't have --join flag set if other nodes joined it before the restart? 

yes; once other nodes have joined this node, it will "know" about this membership to a cluster and persist it, even remembering the network addresses of these other nodes. This way when you restart this node, it will spontaneously reach out to reconnect to the other nodes that had joined it.

> if it does maintain internal joined state, in which cases does cockroach decide to form a new cluster?

This happens only when you start a node 1) `without --join` 2) with no data directory, or with one where no other nodes has joined yet.

> alternatively can i just provide --join for the first node with its future peers that do not exist yet? (that would ideal)

You can do this, *however* you need to start, then stop, that initial node at least a first time so that it initializes the "cluster identity". If *all* the nodes start with `--join` and never have started without `--join` before, they have no own cluster identity and will wait on each other to discover one.

**Comment by dianasaur323** [comment]
assigning @jseldess

**Comment by knz** [comment]
Dup https://github.com/cockroachdb/docs/issues/3138
