### ISSUE TITLE
core: revisit panic on clock skew

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12655]
we're argued about this before (eg: #3779, #7326), but I'd like to bring it up again.

We currently refuse to handle clock skew by crashing the nodes. While this is a good way to make sure we don't proceed, this can cause problems in particular bad clock cases (eg: the recent leap second which caused crashes on almost all Azure test clusters).

We may want to look into putting the node in some sort of unavailable state while clocks are out of sync, then bring the node back in once the clock has caught up.

This is of course not a simple change, but with proper alerting (in metrics and in the admin UI), this would allow nodes to rejoin automatically as opposed to being restarted manually, or crash-looping (if auto-restart is enabled).

**Comment by petermattis** [comment]
An intermediate approach between crashing looping and moving a node to an unavailable state would be to have a node wait at startup until its clock has caught back up. So when a clock skew event occurs we'd see a single crash and then the node would start back up and wait until its clock was ok. This is likely a lot more feasible to implement than putting a running node into an unavailable state.

**Comment by a-robinson** [comment]
Agreed that waiting on startup sounds like a much nicer change to start with. It doesn't solve for the auto-restart-disabled case, but I expect that our test clusters are probably in the minority with respect to that configuration.

**Comment by a-robinson** [comment]
Doing something smoother here would also be very nice for our tests. We're consistently having a few test failures every night caused by clock issues on Azure. Handling this on node startup would even help them, since a number of the failures come from migration attempts failing due to clock skew.

**Comment by tamird** [comment]
Does anyone have a good grasp of the various ways in which we use
MaxOffset? There are 17 non-test callers, and the usage has definitely
spilled beyond the original transaction gating mechanism.

Perhaps now is the time to have something more intelligent than a fixed
ceiling across the cluster.

**Comment by bdarnell** [comment]
What problem does waiting at startup solve? Just preventing crash-looping after a backwards jump like leap seconds?

We crash the servers on clock offsets because if we have clock offsets that are out of bounds, we may have *already* served inconsistent data. If these crashes are occurring, then we must increase MaxOffset instead of papering over the problem by preventing the nodes from crashing. 

Leap seconds are a little different from normal clock offsets. We could handle them the same way, by increasing MaxOffset to over a second. Or we could require deployments to handle leap seconds in a sane way (slewing instead of stepping backwards; I would very strongly prefer to do things this way but I'm not sure how reasonable this is to require). Or, since leap seconds are known in advance (as long as people keep their zoneinfo files up to date), we might be able to adjust for them automatically (it's tricky, though - I don't think the system clock gives us a way to query whether we're on the first or second occurrence of 23:59, so we may just need to suspend service during that second)

> Does anyone have a good grasp of the various ways in which we use
MaxOffset?

The one that really matters is read leases: we must ensure that there is a gap between consecutive lease holders that is greater than any clock offsets that nodes may have experienced at around that time. (lease transfers are exempt from this rule since they can agree about the handoff time; the offset is only necessary for leases transferred after an unclean failure. So maybe now with the modern lease handling it wouldn't be too bad to just increase MaxOffset)

How exactly are the clocks behaving on azure?

**Comment by a-robinson** [comment]
The most common problem I see on azure (with respect to failing tests) is backward clock jumps that immediately cause too large of a skew.

**Comment by bdarnell** [comment]
I haven't done an exhaustive search of the azure test failures, but the ones I've looked at have all been less than 500ms. Maybe we should just increase the MaxOffset when running tests there? Maybe we should increase the default for production usage too? The current value of 250ms was chosen without any real data so maybe real-world deployments can see higher clock offsets than that.

**Comment by a-robinson** [comment]
With respect to the test failures, the first thing we should probably do (as mentioned in chat) is make sure all the VMs brought up for the nightly tests get synced via `ntpdate` before starting any tests (so that they hopefully don't get knocked backward in time after running for 30-40 minutes). That may or may not fix things, and won't help long-running clusters, but certainly seems worth a try. @jordanlewis, can you point to where the config for the nightly worker initialization process is?

**Comment by tamird** [comment]
There isn't one. Probably the best place to do this for now is in the
teamcity-{test,testrace,stress,...} scripts.

**Comment by jordanlewis** [comment]
There's no initialization script for the Azure workers. They are run from a static disk image that's hosted on Azure.

We could try adding an `ntpdate` invocation to the TeamCity "Install Prerequisites" step that gets run before every job. That's available here: https://teamcity.cockroachdb.com/admin/editProject.html?projectId=Cockroach&tab=metaRunner&editRunnerId=Cockroach_InstallPrerequisites

I've had a todo for a while to get the Azure workers to initialize via a hosted script so we can change their behavior without rebaking an image, but I haven't gotten to it.

**Comment by a-robinson** [comment]
@jordanlewis once you get back to the office let's chat so that we can get such a step added. I don't currently know how to get onto an agent (or even create an identically configured agent of my own) to test things out. I think we'll still want it even with https://github.com/cockroachdb/cockroach/pull/12821 in place.

**Comment by a-robinson** [comment]
Quick summary of my findings from playing around with an azure VM:

* Ubuntu 16.04 uses `systemd-timesyncd` as its NTP service rather than the old `ntp` program
* `systemd-timesyncd` is meant to be controlled via the `timedatectl` command
* `systemd-timesyncd` is already supposed to be syncing us when we boot
* There doesn't appear to be a `timedatectl` command to force a synchronization
* `systemd-timesync` is configured to use the ntp.ubuntu.com ntp servers
```
$ systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: active (running) since Wed 2017-01-11 17:07:29 UTC; 12min ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 1910 (systemd-timesyn)
   Status: "Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com)."
   CGroup: /system.slice/systemd-timesyncd.service
           └─1910 /lib/systemd/systemd-timesyncd

Jan 11 17:07:28 alex-test systemd[1]: Starting Network Time Synchronization...
Jan 11 17:07:29 alex-test systemd[1]: Started Network Time Synchronization.
Jan 11 17:07:29 alex-test systemd-timesyncd[1910]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
```

We could force a time sync by disabling and re-enabling ntp syncing (`sudo timedatectl set-ntp false; sudo timedatectl set-ntp true`), or by installing ntpdate and running it against the same NTP servers that `systemd-timesyncd` is using.

I'd add this to the teamcity config, but it appears as though teamcity doesn't allow you to run commands that require root, so I don't know that there's much we can do. @jordanlewis is taking a brief look at whether there's some way to run such commands that I'm missing, but if he doesn't find anything I think we'll just punt on this and see whether https://github.com/cockroachdb/cockroach/pull/12821 is sufficient.

**Comment by a-robinson** [comment]
Scratch most of the details from the above comment -- apparently our build image is actually based off debian jessie, which does things a little differently. Teamcity still doesn't allow root commands and I'm still going to not take action until tests start failing again, though.

**Comment by jordanlewis** [comment]
So the TeamCity agents do in fact run `ntp`, which is started before any build work is performed. The configuration (which I believe is the default for Debian Jessie) is as follows, if anyone knows `ntp` well enough to divine an issue therein:

```
# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help

driftfile /var/lib/ntp/ntp.drift


# Enable this if you want statistics to be logged.
#statsdir /var/log/ntpstats/

statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable


# You do need to talk to an NTP server or two (or three).
#server ntp.your-provider.example

# pool.ntp.org maps to about 1000 low-stratum NTP servers.  Your server will
# pick a different set every time it starts up.  Please consider joining the
# pool: <http://www.pool.ntp.org/join.html>
server 0.debian.pool.ntp.org iburst
server 1.debian.pool.ntp.org iburst
server 2.debian.pool.ntp.org iburst
server 3.debian.pool.ntp.org iburst


# Access control configuration; see /usr/share/doc/ntp-doc/html/accopt.html for
# details.  The web page <http://support.ntp.org/bin/view/Support/AccessRestrictions>
# might also be helpful.
#
# Note that "restrict" applies to both servers and clients, so a configuration
# that might be intended to block requests from certain clients could also end
# up blocking replies from your own upstream servers.

# By default, exchange time with everybody, but don't allow configuration.
restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery

# Local users may interrogate the ntp server more closely.
restrict 127.0.0.1
restrict ::1

# Clients from this (example!) subnet have unlimited access, but only if
# cryptographically authenticated.
#restrict 192.168.123.0 mask 255.255.255.0 notrust


# If you want to provide time to your local subnet, change the next line.
# (Again, the address is an example only.)
#broadcast 192.168.123.255

# If you want to listen to time broadcasts on your local subnet, de-comment the
# next lines.  Please do this only if you trust everybody on the network!
#disable auth
#broadcastclient
```

**Comment by mberhault** [comment]
This hasn't been touched in over a year and was pretty vague to begin with. Closing.
