### ISSUE TITLE
sql: allow tables to be marked read-only

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12672]
Restoring a table from a backup involves restoring the backed up data into a temporary table and, as a final step, removing the original table and renaming the temporary table. During the restore process, we should prohibit writes to the table being restored as they will be lost during the remove/rename step. 

In addition to the restore scenario, an administrator might want to mark a table read-only to prevent a misbehaving application from corrupting table data. 

Prohibiting writes to a table could be accomplished by adjusting privileges, but we'd want to restore the original privileges at some point. It seems more straightforward to add an additional bit to the table privilege descriptor. 

Cc @mjibson, @dt, @danhhz

**Comment by bdarnell** [comment]
A related request from a discussion on gitter today: It may be useful to have small "reference" tables which are available on every node to be used by JOINs (this pattern is common in sharded SQL databases for nearly-static data like a list of countries or time zones). We can't easily make use of such a table today because we always need to talk to the leader to ensure we're getting a consistent view, but if a table was in a read-only state we could safely read from our local replica.

**Comment by cuongdo** [comment]
@danhhz please reassign or change milestone if needed

**Comment by danhhz** [comment]
We don't restore over existing tables yet, so don't need this for 1.0 (at least for backup/restore)

**Comment by andreimatei** [comment]
Re: the suggestion to have "reference tables" that are replicated on every
node: what we want to do in distsql is identify small tables (or, more
generally, small data sources) used in a join and distribute it to every
node that has data for the other side of the join. This would be done at
runtime.

On Apr 5, 2017 7:50 AM, "Cuong Do" <notifications@github.com> wrote:

@danhhz <https://github.com/danhhz> please reassign or change milestone if
needed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/issues/12672#issuecomment-291867309>,
or mute the thread

**Comment by ajwerner** [comment]
This is the adding state, more or less. This issue is no longer relevant.
