### ISSUE TITLE
Cannot install up cockroachdb under docker on OS X

### ISSUE THREAD

**Issue by thegeorgelee** [cockroachdb/cockroach#1268]
On MAC OS X (10.8.5)
Using Kitematic (0.6.3)
Installed command line tools (Docker version 1.6.2, build 7c8fca2)

Ran this command and got error:

    docker pull cockroachdb/cockroach
    FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=cockroachdb%2Fcockroach%3Alatest: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by bdarnell** [comment]
To use docker on a mac you have to set certain environment variables. If you are using boot2docker (which is what most of us use), you'd run `$(boot2docker shellinit)`. From kitematic, it looks like you need to start your terminal from within kitematic instead of the normal way: https://kitematic.com/docs/using-docker-cli/
