### ISSUE TITLE
sql: indexes on expressions of ENUM types causes "column does not exist" errors

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#127365]
If a table exists with an index expression that will require validation via synthetic check constraints:
```
CREATE TYPE typ_127147 AS ENUM ('a', 'b', 'c');
CREATE TABLE t (x TEXT PRIMARY KEY, INDEX ((x::typ_127147)));
INSERT INTO t VALUES ('a');
```

Then delete statement on the table can fail with:
```
DELETE FROM t where x='a';
ERROR: column "crdb_internal_idx_expr" does not exist
SQLSTATE: 42703
```

This happens because a synthetic check constraint is inject into the statement to ensure that crdb_internal_expr is a valid enum value of "typ".

Jira issue: CRDB-40415

**Comment by fqazi** [comment]
Yeah, this was found while working on a fix that issue on the schema changer side. I noticed that we couldn't delete values in the first place in that example table :/

**Comment by DrewKimball** [comment]
[triage] Marcus will take a look, and figure out where this issue should live.

**Comment by mgartner** [comment]
You don't need `DELETE` to hit this. `SELECT` works fine:

```sql
CREATE TYPE foobar AS ENUM ('a', 'b', 'c');
CREATE TABLE t (x TEXT PRIMARY KEY, INDEX ((x::foobar)));
SELECT * FROM t where x='a';
```

**Comment by mgartner** [comment]
This is somewhat related to #61298: using column names to resolve columns in "table expressions", i.e., check constraint expressions, computed column expressions, partial index predicates, etc., is fragile.

In this case, it breaks because there is an implicit `CHECK` expression `crdb_internal_idx_expr IN ('a', 'b', 'c')` where `crdb_internal_idx_expr` is an **inaccessible** computed column with the expression `x::foobar`.

I have a few ideas on how to solve this in the short-term that I'll explore.

**Comment by mgartner** [comment]
Thanks for the report @fqazi! This was a nasty rough edge. #129080 fixes it.
