### ISSUE TITLE
util/sdnotify: a listen error should not prevent the server from starting

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12755]
Reported in https://github.com/cockroachdb/cockroach/issues/12593#issuecomment-270994961:

> The cockroach binary actually runs in the Linux sub-system environment (on Windows 10) but when trying to start a node via `cockroach start --background` you get a Unix datagram socket error `listen unixgram /tmp/sdnotify*/notify.sock: setsockopt: invalid argument.` I think it is trying to send data through a listening socket?

My opinion:
- systemd notification is a "bonus" and should not prevent a server from running in the background.
- if a system doesn't support unix sockets, so be it, just report it and continue.

cc @bdarnell

**Comment by bdarnell** [comment]
Unfortunately the unix socket is key to the operation of `start --background`. The reason this flag exists (instead of the universal `start &`) is that the parent process exits when and only when the child process is initialized and ready to serve. If we silently skipped the unix sockets when they're not supported, the parent process wouldn't know when to exit (a unix socket isn't the only way to do this parent/child process coordination, but none of the alternative idioms I'm familiar with work on windows either). The `--background` flag will just have to be posix-only for now.

**Comment by knz** [comment]
It's also possible to signal readiness by writing to a PID to a location specified by a flag.

A process manager can then specify a named fifo as target, to synchronize without busy wait. 

(There was a world before systemd!)

**Comment by bdarnell** [comment]
Does that work on windows? Windows has "named pipes" but AIUI they live in a separate namespace from the filesystem.

**Comment by knz** [comment]
IIRC yes you can open existing fifos using a path e.g. https://msdn.microsoft.com/en-us/library/windows/desktop/aa365783(v=vs.85).aspx

**Comment by knz** [comment]
also: https://en.wikipedia.org/wiki/Named_pipe#In_Windows

**Comment by knz** [comment]
Note: `--pid-file` now supported (#13996)

**Comment by tamird** [comment]
util/sdnotify is stubbed out on windows as of 2555400b3247be44815d0081b3afd1fb106bfe4e.
