### ISSUE TITLE
ui: tool tips numbers are not correct

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12856]
<img width="1099" alt="screen shot 2017-01-11 at 14 34 12" src="https://cloud.githubusercontent.com/assets/1614265/21863358/22077cc0-d80b-11e6-8cf6-b946d747642b.png">
<img width="961" alt="screen shot 2017-01-11 at 14 34 24" src="https://cloud.githubusercontent.com/assets/1614265/21863359/22080762-d80b-11e6-8fa4-f494995f190e.png">

Look at the replica counts, there are 0s where there shouldn't be.  If I move the mouse around, the 0s appear for different nodes.

**Comment by mrtracy** [comment]
This is going to happen only at the very leading edge of data. The issue is, some nodes report the latest available datapoint before others, and thus there can be some series which do not have the last datapoint.

The nodes table just displays the last available value for each node; for some nodes, that last available value is older.

The most appropriate thing to do here would be to display no value at all for those series; they should not even appear in the tooltip

**Comment by BramGruneir** [comment]
I was able to move the mouse left and right to different points, and there were a number of zeros.  So it wasn't that the data was bleeding edge, it just had gaps I guess.  Look at the highlighted location on the graph, it is not at the latest point, but one before it.

The correct thing to do here is to have the tooltip show what's on the graph.

**Comment by mrtracy** [comment]
Alright, I now think that there simply is no point for that series at that time.  This is tricky.

Basically, there is no value available for two of those 4 series at that time point, but it *appears* that there is a point because the graph connects the two points on either side of it with a line.  So, the tooltip has nothing to display.

I'll investigate a fix.

**Comment by mrtracy** [comment]
Related: #7319

**Comment by dianasaur323** [comment]
assigning to @mrtracy

**Comment by BramGruneir** [comment]
I still see this behaviour quite often sadly.

**Comment by a-robinson** [comment]
I'm seeing this locally on a recent build:

<img width="966" alt="screen shot 2017-10-06 at 1 59 27 pm" src="https://user-images.githubusercontent.com/7085343/31291749-cb1c46d6-aa9e-11e7-8bee-36b08b861690.png">

I brought a 4th node online a few minutes after the original 3, and there's a line for the 4th node in the graph that indicates its value is hovering around 9 or 10 but the tooltip shows a value of 0 for all of the timestamps.

**Comment by a-robinson** [comment]
Still seeing some combination of this and/or https://github.com/cockroachdb/cockroach/issues/16505 and/or some other issue where some nodes incorrectly show 0s in the per-store graphs:

<img width="1098" alt="screen shot 2018-02-11 at 12 46 07 am" src="https://user-images.githubusercontent.com/7085343/36070259-43505d92-0ec5-11e8-9ce9-eb9b696ed493.png">

<img width="933" alt="screen shot 2018-02-11 at 12 48 35 am" src="https://user-images.githubusercontent.com/7085343/36070265-5f29debc-0ec5-11e8-85ce-f517db84556b.png">

<img width="1075" alt="screen shot 2018-02-11 at 12 48 51 am" src="https://user-images.githubusercontent.com/7085343/36070267-62d3643e-0ec5-11e8-8d9d-7a119a448af9.png">

For reference, the time I have highlighted in the last screenshot is roughly one minute in the past, so still having zeros for so many data points seems bad. There's nothing in the nodes' logs about them failing to write their timeseries data.

**Comment by a-robinson** [comment]
Should I open a separate issue for this?

**Comment by couchand** [comment]
@a-robinson without having looked into this at all, I don't think we need another issue at the moment.

We probably won't get to it very soon, so if you could describe in a bit more detail what you were doing when you saw this, we could at least record it for future investigation.  Thanks!

**Comment by couchand** [comment]
Moving this up to 2.0 because it fits into the "trustworthiness" theme we talked about.  Not sure if we'll get to it, but it seems to make sense to include on our list.

**Comment by a-robinson** [comment]
As far as reproduction, I just followed the steps on https://www.cockroachlabs.com/docs/training/locality-and-replication-zones.html and then started looking through the UI.

**Comment by vilterp** [comment]
Unable to repro this after going through the docs training. @mrtracy @couchand possible that it's been fixed with any recent work to graphs?

**Comment by mrtracy** [comment]
I would keep this open, I'm not at all confident this is fixed. The only recent graph change was making node ID names unique, that doesn't cover this. 

Incidentally, this is basically exactly why I created the redux state debug page. If anyone is looking at this issue and has reproduced it, could you please navigate to #/debug/redux in the admin UI and post the redux state? I would really like to see the data values producing these weird conditions.

**Comment by petermattis** [comment]
FWIW, tooltip badness was easily reproducible when working through the training examples using Cockroach 1.1.5. I don't recall the specific example that caused a problem, but it was something with stopping and restarting nodes. I would recommend walking through the training examples on 1.1.5, finding where this occurs and then seeing if it has been fixed in 2.0.

**Comment by vilterp** [comment]
Ok, I will give that a try.

**Comment by couchand** [comment]
@vilterp thanks for taking another look at this.  That's not great behavior, though it's nice to hear that you can't repro on 2.0.

What @BramGruneir and @a-robinson reported, however, is data points in the middle of the series.  Leaving aside the original report (since it's so old), the screenshots from @a-robinson clearly show a hover over the middle of the chart.  Are you able to repro that?

**Comment by piyush-singh** [comment]
@jseldess encountered this again today when walking through training.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/21692034/50851566-31c54e80-134b-11e9-89ad-1195b6d0863b.png">

After killing a node in a cluster, Jesse expected the tooltip to reflect that the number of replicas on the node would show as 0 based on previous behavior. The tooltip instead seems to report the most recent value reported by the killed node before it went down.

After some discussion, the correct solution here seems to be to show either "No Data" or to just eliminate the node from the tooltip over the portion of the graph that it is no longer live.
