### ISSUE TITLE
ui: feature request - set update interval

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12860]
Would be nice to be able to set it, pause it, and show how long until the next update.

**Comment by vivekmenezes** [comment]
What do you want?

**Comment by BramGruneir** [comment]
An update interval.  Similar to grafana.

Set it to update every x mins/x seconds/x hours, not update, or pause updating.  Also, a little timer/icon to show how long until the next update.

**Comment by bdarnell** [comment]
And unlike grafana, whatever refresh setting you choose should follow you from page to page, instead of being reset to some per-page persisted value. 

I'm not sure whether a freely-selectable refresh interval is necessary. When would you ever want a value other than "off" or "update at the same frequency as the underlying data"? (I'm also -1 on showing this interval or the time until next update to the user)

**Comment by BramGruneir** [comment]
Yeah, I'm good with some presets, doesn't have to be freely selectable.

For visualization, I was thinking something like a small circle that slowly traces and when it gets all the way around, the refresh happens.  When you update once a minute or every 10 mins, it would be nice.  Seeing the actual time is overkill.

**Comment by vivekmenezes** [comment]
What's being asked here is the ability to freeze the UI at a particular timestamp and observe all UI graphs/pages at that timestamp. This is useful when debugging a particular event at a particular time. This might be solved using a freeze/unfreeze button in the UI.

**Comment by bdarnell** [comment]
Or a "snapshot" button that freezes everything and changes the url to a shareable permalink for that point in time.

**Comment by BramGruneir** [comment]
Ok, a snapshot link to share would be amazing!

**Comment by mrtracy** [comment]
#### Regarding Snapshots
In terms of graphs, this is already possible with historical time windows; we do not have a "pause" button, but one could be added. AFAIK, we also do not refresh automatically if you are viewing a historical time.

The data that would be difficult to snapshot here is the node table; we can't show historical values there without significant modifications. The data in that table is based on the current node status, not time series, and node status is not retained historically. The current plan was for the upcoming "Cluster Atlas" visualization to also rely on this data, since it quickly provides a "vertical" view of all metrics at the latest timestamp.

A historical cluster status can be synthesized from time series, but involves considerably more queries. However, that is likely appropriate for a static link; it would only become burdensome for the quickly-refreshing node status pages which update every ten seconds.  The implementation of this would add some complexity to the front end query code.

#### Regarding Configurable Cluster Refresh
In the case of all refreshes, we currently refresh when the next datapoint is expected. That is, the node table always refreshes every ten seconds (it always displays current data), while the graphs refresh based on the time window being viewed (they refresh when the next point is expected; less often for longer time windows, more often for shorter time windows.)  

Is there a concrete use case for making the refresh time different than that? Are we concerned about query load on the cluster somehow?
