### ISSUE TITLE
cli: add --max-offset flag

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#12878]
As discussed in https://github.com/cockroachdb/cockroach/pull/12821, given that users may need to change the max clock offset depending on their cloud environment, we should probably add a `--max-offset` flag to `cockroach start`. This flag would be similar to `--raft-tick-interval` in that it would need to be set identically across all nodes. Eventually, we might want a different way to handle such global configs, but for now, we can just be clear about this in the documentation.

Also, once we've figured out the optimal max offset per cloud provider through our own testing, we can integrate this recommendation into our cloud deployment tutorials. 

@petermattis, @bdarnell

**Comment by cuongdo** [comment]
We already have the `COCKROACH_MAX_OFFSET` environment variable. Does that suffice?

I do agree we should have recommendations for the different cloud providers -- or at least provide a recommendation when the max offset needs to be higher than the default of 500 ms.

**Comment by bdarnell** [comment]
Our philosophy is that all documented settings should be accessible with (at least) command line flags, with selected flags (mainly client-side ones) also duplicated as environment variables. The reason is that environment variables fail silently - if you misspell one, you'll never know. If this is something we want to document for end users (and I think we have to), we should make it a flag instead of an environment variable. (The only reason we're using environment variables for our "experimental" options is because they don't show up in `--help`)

I think that with the default of 500ms we are (correctly) erring on the high side to be safe; users are more likely to want to lower it than raise it.

**Comment by cuongdo** [comment]
For our nightly load tests that spin up transient clusters in Azure, I've
had to increase `COCKROACH_MAX_OFFSET` to `1s`. Would that be needed for
regular deployments, or do things already work fine for longer-lived
clusters?

**Comment by cuongdo** [comment]
(specifically referring to Azure here)

**Comment by bdarnell** [comment]
Our long-lived azure clusters seem to be fine with the default.

**Comment by jseldess** [comment]
If we decide not to add this as a flag, we should probably add docs on the env variable in the off-chance that users do want/need to change the default.

**Comment by dianasaur323** [comment]
@jseldess I added a known-limitation flag so that we can document this. However, I think it sounds like a change that we should fix, even if it doesn't make it into the 1.0. Once we add a section in docs about this, let's move the milestone to Q2 2017 so that we get it done.

**Comment by jseldess** [comment]
@dt, @knz, @bdarnell, are we adding this to `system.settings` for 1.0? Also, what about removing `--raft-tick-interval` from `cockroach start` and adding it to `system.settings` as well?

**Comment by bdarnell** [comment]
No, this can't be a system setting because it must be the same for all nodes from the beginning and can't change at runtime. `--max-offset` and `--raft-tick-interval` will need to remain command-line flags, if we make them changeable at all (I think we need to keep `--max-offset`; the need for `--raft-tick-interval` is less certain and we might be able to get rid of it)

**Comment by knz** [comment]
Technically MaxOffset can always grow, right?

**Comment by bdarnell** [comment]
No, I don't think it's safe to increase MaxOffset while the cluster is online. This will weaken our suicide-on-clock-offset mechanism without increasing the safety margin allowed in lease durations (until the next round of leases takes effect).

**Comment by petermattis** [comment]
@bdarnell Should we remove `--raft-tick-interval` for 1.0?

**Comment by bdarnell** [comment]
Probably a good idea.

**Comment by a-robinson** [comment]
The discussion above is somewhat unclear -- did we want to get a `--max-offset` flag into 1.0? Or just document the environment variable?

**Comment by bdarnell** [comment]
I would prefer to add a `--max-offset` flag instead of documenting the environment variable. Should be easy to do the inverse of #15547.

**Comment by a-robinson** [comment]
Yup, I'm on it.
