### ISSUE TITLE
backupccl: determine if full cluster restore from old version should add bootstrap zone configs that were added in later versions

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#129084]
**Describe the problem**

This may not be an actual problem, but I'm filing this ticket to track the question.

When doing a full cluster restore, the zone configs are copied from the backup. There currently is no logic that adds in additional zone configs that have been added as part of the bootstrap process in later versions.

**To Reproduce**

We already have tests for restoring from a backup from an old version.

Add the following diff:
```
diff --git a/pkg/ccl/backupccl/restore_old_versions_test.go b/pkg/ccl/backupccl/restore_old_versions_test.go
index 83b4cbd78dc..1645ef2386d 100644
--- a/pkg/ccl/backupccl/restore_old_versions_test.go
+++ b/pkg/ccl/backupccl/restore_old_versions_test.go
@@ -254,6 +254,15 @@ ORDER BY
 			{"data", "public", "100129", "add(int8, int8)", "public", "EXECUTE", "false"},
 			{"data", "public", "100129", "add(int8, int8)", "root", "ALL", "true"},
 		})
+
+		// Verify that the timeseries range has a zone config.
+		sqlDB.CheckQueryResults(t, "SELECT target FROM [SHOW ZONE CONFIGURATIONS] ORDER BY 1", [][]string{
+			{"RANGE default"},
+			{"RANGE liveness"},
+			{"RANGE meta"},
+			{"RANGE system"},
+		})
 	}
 }
```

Then run `./dev test pkg/ccl/backupccl -f=TestRestoreOldVersions/cluster-restore`.

**Expected behavior**
Not sure. Should the above output also include the zone configs for the system database and other tables that have a zone config added during bootstrap?

https://github.com/cockroachdb/cockroach/blob/a5b8e0c19d0237009d5c5eab953b165051bd1f0b/pkg/sql/catalog/bootstrap/metadata.go#L537-L541

This may be fine as-is, but I just wanted to confirm what is expected. Feel free to close as `won't fix` if that's the answer.

Changing this would require adding a `customRestoreFunc` for the system.zones table here:
https://github.com/cockroachdb/cockroach/blob/a5b8e0c19d0237009d5c5eab953b165051bd1f0b/pkg/ccl/backupccl/system_schema.go#L627

**Additional context**
This question came up while working on #128032 with @arulajmani. 

Jira issue: CRDB-41369

**Comment by dt** [comment]
Typically when we modify bootstrap, we also add an upgrade migration so that existing clusters, during upgrade to the version that introduced the changed bootstrap, will update its configuration to match that of a cluster created on the new version. The author of any upgrade migration is expected to determine if and what steps need to be performed on restored data, and attests that they have done so in the `RestoreBehavior` field when they define the migration.

https://github.com/cockroachdb/cockroach/pull/128032 stated that it was not relevant to restore: `upgrade.RestoreActionNotRequired("this zone config isn't necessary for restore"),`
