### ISSUE TITLE
sql: bigserial doesn't give serial numbers

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#12911]
@knz thanks for the new `show indexes` code. One nit:

at tip, 62f24f8c218083eb96c0e5a103618d8fb5aff42e, the bigserial attribute (the postgres equivalent of the auto_increment in mysql) is not revealed in `show indexes` request.

~~~
cockroach version
Build Tag:   62f24f8-dirty
Build Time:  2017/01/13 15:13:51
Platform:    darwin amd64
Go Version:  go1.8rc1
C Compiler:  4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
~~~

transcript:
~~~
~/go/src/github.com/cockroachdb/cockroach (beta-20170112) $ cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
[Jroot@:26257> create database tt;
CREATE DATABASE
[Jroot@:26257> set database = tt;
SET
[Jroot@:26257> create table a (b int not null primary key, c varchar(10), d int);
CREATE TABLE
[Jroot@:26257> desc a;
invalid syntax: statement ignored: syntax error at or near "desc"
desc a;
^

[Jroot@:26257> show indexes a;
invalid syntax: statement ignored: syntax error at or near "a"
show indexes a;
             ^

[Jroot@:26257> show columns a;
invalid syntax: statement ignored: syntax error at or near "a"
show columns a
             ^

[Jroot@:26257> show columns from a;
+-------+------------+-------+---------+
| Field |    Type    | Null  | Default |
+-------+------------+-------+---------+
| b     | INT        | false | NULL    |
| c     | STRING(10) | true  | NULL    |
| d     | INT        | true  | NULL    |
+-------+------------+-------+---------+
(3 rows)
[Jroot@:26257> show indexes from a;
+-------+---------+--------+-----+--------+-----------+---------+----------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing | Implicit |
+-------+---------+--------+-----+--------+-----------+---------+----------+
| a     | primary | true   |   1 | b      | ASC       | false   | false    |
+-------+---------+--------+-----+--------+-----------+---------+----------+
(1 row)
[Jroot@:26257> \d a;
Suggestion: use the SQL SHOW statement to inspect your schema.
invalid syntax: \d a;. Try \? for help.
[Jroot@:26257> show a;
pq: unknown variable: "A"
[Jroot@:26257> show b;
pq: unknown variable: "B"
[Jroot@:26257> create table a2 (b bigserial not null primary key, c varchar(10), d int);
CREATE TABLE
[Jroot@:26257> show indexes from a2;
+-------+---------+--------+-----+--------+-----------+---------+----------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing | Implicit |
+-------+---------+--------+-----+--------+-----------+---------+----------+
| a2    | primary | true   |   1 | b      | ASC       | false   | false    |
+-------+---------+--------+-----+--------+-----------+---------+----------+
(1 row)
[Jroot@:26257> # where is the bigserial attribute shown?
~~~
 bigserial (and serial and smallserial) are really important attributes for the database administrator and developer to be able to discover/inspect.

reference: https://www.tutorialspoint.com/postgresql/postgresql_using_autoincrement.htm

**Comment by bdarnell** [comment]
"Serial" is a property of the column, not the index. It shows up as the column's default value in `SHOW COLUMNS`:

```
root@:26257> create table test.ser (a bigserial primary key);
CREATE TABLE
root@:26257> show columns from test.ser;
+-------+------+-------+----------------+
| Field | Type | Null  |    Default     |
+-------+------+-------+----------------+
| a     | INT  | false | unique_rowid() |
+-------+------+-------+----------------+
(1 row)
```

**Comment by glycerine** [comment]
Ugh. Please give that a new name. Serial means serial (one after another, in sequence), and is a critical feature for doing things like locating gaps in data and restarting a read from a particular point row after an interruption. We know it is expensive, but sometimes that is required and we want/have to pay for it.

**Comment by petermattis** [comment]
@glycerine Serial in Postgres (and auto_increment in MySQL) does not mean serial as most people intuitively understand it. See the section in that doc @bdarnell referred to that ends with:

```
In summary, the SERIAL type in PostgreSQL and CockroachDB, and the AUTO_INCREMENT type in MySQL, all behave the same in that they do not create strict sequences. CockroachDB will likely create more gaps than these other databases, but will generate these values much faster.
```

Depending on transaction commit order and transaction aborts, your Postgres serial column can see gaps and rows appearing out of serial order.

**Comment by glycerine** [comment]
Hi @petermattis: is there any workaround/facility to model situations where (1) you need to detect gaps in a sequence; (2) you need a logical clock; or (3) when you do require a serial number ordering in order to "serialize" your events -- this being the entire point storing certain types of data in a database.

**Comment by petermattis** [comment]
The only workaround I'm aware of is to have the serial ID value stored in a table and have each transaction read and increment it. This will be particularly slow with CockroachDB at the moment because we don't handle high contention scenarios very well.

> this being the entire point of storing certain types of data in a database

It is quite curious that serial/auto_increment can have gaps and mis-ordering. I wonder how many apps out there have a rare bug due to this.

**Comment by glycerine** [comment]
> ... a rare bug due to this.
mysql always does max(id)+1, so it can be counted on as long as you never manually write an id.

**Comment by petermattis** [comment]
> mysql always does max(id)+1, so it can be counted on as long as you never manually write an id.

I haven't tested this recently, but my memory is that both Postgres and MySQL initialize the ID used for a statement when the statement is executed, not when the transaction the statement is associated with commits. So no matter how MySQL initializes the ID, if a transaction aborts you can get gaps and if transactions commit in a different order than the `INSERT` statements execute you can get mis-orderings. The fundamental problem is that the sequences used by Postgres and MySQL are not transactionally updated. The reason for the lack of transactional updates on the sequence is that doing so is too expensive. 

It's been a while since I looked at this area of Postgres / MySQL, so my memory might be faulty or something good have changed. I'd be very interested in hearing if it has.

**Comment by bdarnell** [comment]
MySQL lets you configure how it locks the auto-increment counter, but none of the modes hold a lock for the duration of the transaction and so gaps are possible in all modes: http://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html

If you require that there not be any gaps, you can achieve this by inserting `max(id)+1` with a subquery instead of relying on `auto_increment` or `serial` doing this for you. This will have the desired result on all databases (assuming serializable isolation; I haven't worked out how it will behave in the reduced isolation levels used by default in other DBs), but it will eliminate any possibility of parallelism in your transactions (and will perform particularly poorly under contention in CRDB).

**Comment by glycerine** [comment]
right. I would always want to avoid that unsafe `innodb_autoinc_lock_mode = 2 (“interleaved” lock mode)` because then recovery/replay of the binlog is not deterministic. From http://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html

> In this lock mode, no “INSERT-like” statements use the table-level AUTO-INC lock, and multiple statements can execute at the same time. This is the fastest and most scalable lock mode, but it is not safe when using statement-based replication or recovery scenarios when SQL statements are replayed from the binary log. 

As the page Ben referenced indicates, unless you set this unsafe setting, in mysql/mariadb the table-level lock on the inserts guarantees consecutive numbering.

**Comment by knz** [comment]
@glycerine perhaps you want to check  #12907 and see if that's perhaps a better direction.

**Comment by bdarnell** [comment]
The table-level lock is held for the duration of the *statement*, not the *transaction*. So you can still see reorderings if you ever insert into an auto_increment table inside a transaction, no matter which locking mode you use.

**Comment by glycerine** [comment]
sure you can manually introduce gaps. but if you never mention the id field explicitly, then mysql takes care of it and you are fine.

**Comment by glycerine** [comment]
So the upshot is that really basic modeling facility just isn't going to be available in crdb? Without consecutive integer ordering, I can't readily use crdb to replicate/replace Kafka, for instance.

**Comment by knz** [comment]
Again you are free to create your own sequential indices by means of `insert into ... ((select max(id) + 1 from t), ...)`. That is guaranteed to work, albeit slowly.

There is not a single db engine that we know of that offers both sequences and also proper performance scalability over multiple servers. If you know of any, let us know and we'd be happy to investigate how to offer the same!

**Comment by glycerine** [comment]
Kafka...

**Comment by knz** [comment]
But it's a bit comparing apples and oranges, isn't it?
CockroachDB is providing you table-oriented data access with transactional updates and consistency guarantees over the order of such updates; kafka provides you messages queues with ordering and delivery guarantees. There's no law of the universe that guarantees you can faithfully simulate the behavior and guarantees of one using the other (in either way) while preserving its cost model (how fast operations are performed).

**Comment by petermattis** [comment]
> sure you can manually introduce gaps. but if you never mention the id field explicitly (in a write), then mysql takes care of it and you are fine (gapless).

In case it wasn't clear from the other comments, my claim is this isn't correct. Txn-1 starts and inserts a row into a table with an auto_increment column but does not commit. Then, txn-2 starts and inserts a row into a table with an auto_increment column and does commit. At this point, other transactions can scan the table and they will see a gap in the auto_increment columns values. When txn-1 commits it will fill that gap. If txn-1 aborts the gap will persist.

From the MySQL docs:

> In all lock modes (0, 1, and 2), if a transaction that generated auto-increment values rolls back, those auto-increment values are “lost”. Once a value is generated for an auto-increment column, it cannot be rolled back, whether or not the “INSERT-like” statement is completed, and whether or not the containing transaction is rolled back. Such lost values are not reused. Thus, there may be gaps in the values stored in an AUTO_INCREMENT column of a table.

**Comment by glycerine** [comment]
okay. Putting aside the obvious and trivial workaround of not rolling back your inserts -- which is typical standard operating procedure --  mariadb/mysql auto_increment still gives one a logical clock, which is incredibly useful. From https://mariadb.com/kb/en/mariadb/auto_increment/

> Thus AUTO_INCREMENT values can be used to sort results in a chronological order, but not to create a numeric sequence.

**Comment by bdarnell** [comment]
Rollbacks are always possible in a transaction - what if there is a network or machine failure between the INSERT and COMMIT? 

If there are any other constraints on the table, gaps are possible even if you're using auto-commit statements instead of multi-statement transactions:

```
mysql> create table autoinc_gap (a int auto_increment primary key, b int unique);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into autoinc_gap (b) values (42);
Query OK, 1 row affected (0.00 sec)

mysql> insert into autoinc_gap (b) values (42);
ERROR 1062 (23000): Duplicate entry '42' for key 'b'
mysql> insert into autoinc_gap (b) values (43);
Query OK, 1 row affected (0.00 sec)

mysql> select * from autoinc_gap;
+---+------+
| a | b    |
+---+------+
| 1 |   42 |
| 3 |   43 |
+---+------+
2 rows in set (0.00 sec)
```

So yes, MySQL and its derivatives provide a monotonic and gapless sequence in certain limited circumstances (auto-committed statements with no other constraints on the table. I think the mariadb doc you're quoting is misleading since it doesn't talk about out-of-order commits if the transaction involves multiple statements). CockroachDB does not provide this particular set of guarantees (and it is unclear to me whether postgres does). You can either have weaker guarantees with the `SERIAL` type (which has gaps and is only approximately ordered), or stronger guarantees by selecting `MAX(id)+1` explicitly in a transaction (which will always provide a gapless monotonic sequence without the limitations around transaction structure and other constraints on the table).

**Comment by glycerine** [comment]
This has been a super informative and useful discussion.

I don't see anything that is outstanding work to-do, and the system appears to be "functioning per  design". I really would prefer to see the name "snowflake" instead of the misleading "serial" be used to describe such column attributes, but that's a documentation and re-education burden that seems to have been already been untaken. So, closing ticket.
