### ISSUE TITLE
ui: don't show decimal places for integral values

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#12973]
### Steps to Repro
1. Create a 3-node cluster.
2. Go to admin UI.
3. View **Node count** graph.

### Expected Result

Because you cannot have partial nodes, the scaling of the values is represented only as integers.

### Actual Result

The scale of number of nodes includes decimal values, insinuating that a partial node has some kind of meaning.

![screen shot 2017-01-18 at 12 41 27 pm](https://cloud.githubusercontent.com/assets/19260003/22075860/b006c678-dd7b-11e6-82b9-adf880cda940.png)

**Comment by dianasaur323** [comment]
@vivekmenezes I noticed you removed a couple of these admin UI ux clean-ups out of 1.0. Do you mind explaining your methodology behind it? I'm trying to assign a milestone for everything, so I'm moving these to 1.1.

**Comment by dianasaur323** [comment]
Moving out to 1.2 so that @mrtracy can focus on finishing up the final features for 1.1

**Comment by rmloveland** [comment]
I think this ticket should be generalized to cover all cases of using floats to display what are conceptually integers in the UI, e.g., ranges, etc.

As a new user, I have been finding it confusing/distracting to see floats displayed in so many places since decimals imply a certain precision that isn't usually intended (I think? Related: "significant digits" from Chemistry class).  My eye keeps "hanging up" on the decimals that end in `.00` and really wants them to be integers, especially `0.000`.

**Comment by jseldess** [comment]
To piggyback on Rich's comment, when we show floats on the **Replicas per Store** graph, that could be misinterpreted by users to mean that it's possible for a store to have only part of a replica, which I don't think is possible (perhaps except when a range is rebalancing).
