### ISSUE TITLE
PCR: enable simultaneous r/w ops on primary and backup clusters

### ISSUE THREAD

**Issue by wuwo1952368901** [cockroachdb/cockroach#130070]
At present, physical cluster replication can only be synchronized from the primary cluster to the backup cluster. 
But in the event of a failure in the main cluster, commands still need to be executed to handle cluster switching. 
In practical use, we prefer that the primary and backup clusters can perform read and write operations simultaneously, so that in the event of a failure in the primary cluster, only the database configuration of the application needs to be modified without the need to switch databases through redundant commands.

Jira issue: CRDB-41863

**Comment by alicia-l2** [comment]
Thanks for this feedback! Responding to some of your comments:

> But in the event of a failure in the main cluster, commands still need to be executed to handle cluster switching.

Commands are executed from the standby cluster, so in the event of a cluster failure, you would use the standby cluster's SQL shell to initiate the cutover. See docs on how to initiate this [here](https://www.cockroachlabs.com/docs/stable/cutover-replication). 

> In practical use, we prefer that the primary and backup clusters can perform read and write operations simultaneously, so that in the event of a failure in the primary cluster, only the database configuration of the application needs to be modified without the need to switch databases through redundant commands.

In PCR, you are correct in that you will have to initiate a manual cutover from the standby cluster. 
We are currently working on asynchronous replication tooling that will enable read/write operations to be performed on both clusters so that the only the database config of the app needs to be modified. This is coming this fall 2024.
