### ISSUE TITLE
interplay Error.{Retryable,TransactionRestart} & Goisms

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1300]
Remarks about our main `Error` proto:
Ignoring the ErrorDetail, it comes with a bool `Retryable` and an enum `TransactionRestart` (which defaults to `ABORT`, but can be `BACKOFF` or `IMMEDIATE`). It seems like we're making it hard for other clients to generally follow the Go client's lead.

- I think the current Go client bails if it receives an error which is retryable but not a TransactionRetryError within the Txn loop, which is probably not the right thing to do (after all, hitting a draining node would be retryable, you'd just send the same thing to another gateway).
- the Go client gets the TransactionRetryError information through an interface which the various errors stored in `Error.Detail` implement, which seems odd given that those are the most important errors to handle for clients. Someone who writes another client seems to be forced to pull that stuff from various interface implementations in `api.go`.
- Ideally our Go-centric handling carries over to other clients, it shouldn't be necessary to have the control flow rely on presence or absence of optional fields.

I think the Go client should stop using the `Detail` for its retry handling and we should discuss the desired semantics of `Retryable`.

A behaviour that seems reasonable to me is that any transaction restart error should have `Retryable=true`, so that that is the only thing the retry loops have to look at. If retryable, the clients would use the `TransactionRestart` field  (defaulting to `ABORT`) to determine what to do with their active transaction, if any, and to restart/backoff appropriately.

```
// Error is a generic representation including a string message
// and information about retryability.
message Error {
  // Message is a human-readable error message.
  optional string message = 1 [(gogoproto.nullable) = false];

  // If retryable is true, the error condition may be transient and the failed
  // operation may be retried (within the same transaction).
  optional bool retryable = 2 [(gogoproto.nullable) = false];

  // If transaction_restart is not ABORT, the error condition may be handled by
  // restarting the transaction (with or without a backoff).
  optional TransactionRestart transaction_restart = 4 [(gogoproto.nullable) = false];

  // If an ErrorDetail is present, it may contain additional structured data
  // about the error.
  optional ErrorDetail detail = 3;
}
```

**Comment by tschottdorf** [comment]
#1301 suggests that it's a good idea to distinguish the case `Retryable=true && TransactionRestart=ABORT` further. With the above suggestion, the case of an aborted transaction is not distinguishable from that of a simple retryable error that has nothing to do with the txn (unless you check for presence of the field), but a client will probably want to have easy access to that info. Adding the default values `TransactionRestart=NONE` for errors which are unrelated to transaction restarts would be the obvious solution.

**Comment by bdarnell** [comment]
I added the `Error.Retryable` and `Error.TransactionRestart` fields to address this case. My intention was that all non-go clients would use those fields and would mostly be able to ignore the details (the one exception is transaction_aborted; all clients need to reach into that error detail to get their new minimum priority).

Go is unfortunately different; it currently ignores the fields of `Error` in favor of extracting types from the detail field (each type has hard-coded retry/restart behavior). I'd like to change this to make the go client more consistent with the others but it's tricky because these error types are also how the Retryable and TransactionRestart fields get set in the first place. 

Right now retryable errors and transaction restart errors are disjoint sets, and I think it would be better to keep it that way than to make transaction restart errors a subset of retryable errors. The problem is that they are retried at different levels: retryable errors (which do not restart the transaction) can be retried by the sender, but any error which restarts the transaction must be propagated all the way out to the client.

**Comment by tschottdorf** [comment]
I see the point about separating the two types of errors. Our Go code needs to act based on the ErrorDetail in a lot of places (though where it only needs to know about retryability or transaction restart behaviour, we could simply use the generic error, which implements all of those interfaces as well). I still think there's value in other clients never having to consider the `ErrorDetail` in normal operation; that's certainly the case if we add an additional top-level field which contains the conflicting transaction (if any). The denormalization this incurs is not ideal, but seems worth it, at least to me.

**Comment by tschottdorf** [comment]
since `*proto.Error` doesn't implement `error` any more and has seen some more cleanup, I'm going to  close this.
