### ISSUE TITLE
ui: storage capacity graph y-axis legend incorrectly labelled "count"

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13002]
![screen shot 2017-01-19 at 11 56 52 am](https://cloud.githubusercontent.com/assets/6201335/22116422/6ee52572-de3e-11e6-9416-9e65711d9e42.png)

The storage capacity graph y-axis legend is labelled "count", but it is in gigabytes similar to the "live bytes" graph directly below it. 

Also, showing "Available" space is a bit surprising to me as it makes the yellow line scarier than it is. Should this graph show "Used" space?

**Comment by mrtracy** [comment]
The graph cannot show used space without fairly significant work in the time series system. We only record available space. Grafana was showing (total - available) as used.

My suggestion would be to just record the used space directly as a time series. Otherwise, we are going to need to augment the time series system with multiple-series math, which starts to get complicated really quickly.

**Comment by mrtracy** [comment]
I am going to close this issue after fixing the problem in the title - the incorrectly labeled axis.

The other issue, "Available" vs. "Used" space, is an issue throughout the UI and is better captured in #13548
