### ISSUE TITLE
add make testshort that excludes some longer tests

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13025]
I am about to post a PR that adds a variant of TestLogic with DistSQL turned on.

Given that this test is ~30 seconds and it's testing functionality that is not on by default, I think it would be good to avoid having it run on every `make test`. Instead we could have it run only in TeamCity runs (including the automated runs for PRs).

Do people think this is a good idea (as a general practice for such tests)? And if yes, what's the simplest way to achieve this? Perhaps we can use the `-test.short` flag and have it be set on `make test` (conditional on a variable which is changed in TeamCity)?

CC @tamird @petermattis @jordanlewis

**Comment by jordanlewis** [comment]
I'm not super crazy about widening any gaps between what we run locally and what we run on TeamCity because I'm afraid that the concept of "run the full test suite" is going to get more and more confusing and dilute the more we do stuff like that. I don't think it's so bad to add time to `make test` because, as far as I know, most of us during development iterate by running individual tests, not the full test suite.

I'd much prefer putting efforts into figuring out how to speed up the test suite in general. I'm not completely opposed to your idea though if you feel strongly about it.

**Comment by RaduBerinde** [comment]
Then how about adding a `make testshort` target as a version of `make test` that avoids some longer tests? That would allow folks to do a run that covers all packages without waiting for all the tests.

**Comment by jordanlewis** [comment]
I like that idea better!
