### ISSUE TITLE
roachtest: flake detection does not work when used with `require` API

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#131094]
Roachtest has automatic failure detection that relies on annotated errors to identify the types of flake, which team to assign the issue to, whether to report it or not, etc. See [github.go](https://github.com/cockroachdb/cockroach/blob/e08158eb9784e78927c960dca05879f4f3467689/pkg/cmd/roachtest/github.go#L179) for more details.

However, this does not work when the test uses the `require` API to ensure the absence of errors. For instance, if test code runs something like the following:

```go
require.NoError(t, c.SomeClusterFunction())
```

then, if `SomeClusterFunction` fails due to a flake (`registry.ErrorWithOwner` where `InfraFlake` is true), the failure will _not_ be handled as a flake. This has to do with how `require` reports errors and our implementation not being able to see the underlying error when reporting the failure.

I'm pretty sure there should be a way to fix this and support `require` in roachtests, but this will require (pun intended) some investigation.

Jira issue: CRDB-42369

**Comment by srosenberg** [comment]
The issue is essentially this `Sprintf` [1], so we end up losing the `err` object. Short of instrumenting `require`, that leaves the only option of matching on strings of the form "TRANSIENT_ERROR(ssh_problem): exit status ..." in order to recover the `err` object expected by `failuresMatchingError`.

[1] https://github.com/stretchr/testify/blob/c4b8421a1fb1a1eed787101978a3bcf7ae8a5d0f/assert/assertions.go#L1584
