### ISSUE TITLE
Q: uint64 value support

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#13161]
Just a small, minor question. I noticed recently that the Go database sql layer is rather absurdly specified to crash on uint64 values with the high bit set.

references:
http://go-database-sql.org/surprises.html

https://golang.org/src/database/sql/driver/types.go  line 243

https://github.com/golang/go/issues/6113

https://github.com/golang/go/issues/9373

Since this a rather common need (or least it is for me) -- I frequently handle uint64 values that may the high bit set because they are generated randomly -- I'm hoping that cockroachdb will have a much saner story here. The question then is simply: how can I reliably get such values into and out of cockroachdb from a Go client?

comment: One thing I was looking at as an alternative to the Go standard library's database/sql is 
https://github.com/jackc/pgx which seems like it may provide a workaround via a slightly different api.

**Comment by bdarnell** [comment]
The code in database/sql/driver is provided as a default; specific database drivers could handle uint64s differently if they wanted to. But [PostgreSQL doesn't have unsigned column types](https://github.com/lib/pq/issues/72#issuecomment-12677099), so the postgres driver doesn't support them (and neither does CockroachDB, so what server-side type were you planning to use for these uint64s?). 

The "saner story" is to use bytes instead of integers for identifiers. If you're not doing math with it, it might as well be a blob and not a number. Personally I'd go with 128-bit UUIDs just so I don't have to do the birthday paradox math.

**Comment by glycerine** [comment]
thanks Ben
