### ISSUE TITLE
sql: timeout on PG_CATALOG.GENERATE_SERIES

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#13164]
```
panic: func exec timeout: SELECT PG_CATALOG.GENERATE_SERIES(-3304644259572761738::int, 1930704601241603668::int)
```

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=128842#_

Found with RSG.

**Comment by jordanlewis** [comment]
Hmm, we might need to teach the RSG to not generate queries with `5235348860814365406` rows.

**Comment by tamird** [comment]
Or we might want to reject such queries? Wonder what pg does.

**Comment by jordanlewis** [comment]
Postgres happily accepts the query :)

**Comment by tamird** [comment]
```
psql
psql (9.6.1)
Type "help" for help.

tamird=# SELECT PG_CATALOG.GENERATE_SERIES(-3304644259572761738::int, 1930704601241603668::int);
ERROR:  integer out of range
```

**Comment by jordanlewis** [comment]
That error is caused by the cast to integer. Try issuing it without the cast.

**Comment by tamird** [comment]
Oh boy.

```
tamird=# SELECT PG_CATALOG.GENERATE_SERIES(-3304644259572761738, 1930704601241603668);
psql(2265,0x7fffb229e3c0) malloc: *** mach_vm_map(size=18446744056529682432) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

**Comment by mjibson** [comment]
With other queries that could produce lots of results or processing time (`pow(x, y)`), I added some internal checks to return an error quickly. I'm not opposed to adding a similar restriction here. However I'm not familiar with this function. If it does indeed need to take arguments like this then I am ok with restricting RSG to not test this specific function.

**Comment by knz** [comment]
large argument values are acceptable for this function and there are even cases where a large value would not necessarily cause a timeout -- therefore there is no design space for us to limit the range of its acceptable arguments.

I believe the best thing RSG can do is to lower the SQL maximum memory limit (`-max-sql-memory`) so that this type of query fails earlier instead of running into the test timeout. I think a limit of 3MB would be sufficient.
