### ISSUE TITLE
storage: keep a per-range history of replica and lease changes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13210]
[brainstorming]

Knowing the history of a range (when replicas are added/removed, who the Raft leader is, when lease transfers occur) is useful for debugging problems with operations that get stuck or have performance hiccups, yet the current state-of-the-art is grep'ing log files. We keep some of this information around in the `system.rangelog` table, but almost never consult it. And that table is not indexed for quickly retrieving the events for a particular range. What I'd like is a /debug endpoint which allowed me to retrieve the (truncated) history of leases for a range given its ID. 

The specifics of the /debug endpoint and/or UI is a separate discussion. This issue is a proposal for a mechanism to maintain this history. Currently, the lease for a range is stored in a non-versioned key in the range-id-local key space. Similarly, the range descriptor is stored in a non-versioned key in the range-local key space.  Whenever the range lease or descriptor changes, we update the on-disk state and promptly forget about the previous state. Yet the encoded size of the `roachpb.Lease` and `roachpb.RangeDescriptor` protos is minimal (~50-100 bytes each). Keeping the last 100 leases and range descriptors in the range-id-local key space would consume ~20KB of storage. 

Alternately, we could keep add a per-range history mechanism that is more freeform: a circular buffer of string "log" entries. Lease transfers and changes to the range descriptor could add to this log, but we could also include bits such as Raft leadership changes. 

Cc @bdarnell

**Comment by bdarnell** [comment]
The range descriptor *is* versioned (that's how it is able to participate in transactions). The `cockroach debug range-descriptors` command already dumps the history of a range's descriptor.

If we want to keep history of leases, I think I'd prefer to make a freeform log (or extend the use of `system.rangelog` - we should probably add an index on rangeID, but even without an index it should be affordable for a debug page to scan a time range on that table) instead of converting the lease key to mvcc storage.

**Comment by petermattis** [comment]
Ah, thanks for correcting me about the versioned part, though I'm not sure if that gives adequate history as we GC old versions. 

I wasn't proposing converting the lease key to MVCC storage, but to instead have a separate set of "lease-history" keys. Or perhaps "range-history". One anxiety about using `system.rangelog` or similar for lease history is that it introduces a distributed transaction on what was previously a Raft request. That seems undesirable. Another part of my thinking for storing the history next to the range was to make it colocated with the range data so that it could be accessed during post-mortem debugging (i.e. when we can't run SQL operations). Trying to find the contents of `system.rangelog` if a cluster isn't running is quite a bit more difficult.

**Comment by a-robinson** [comment]
I've also wished for historical lease information on multiple occasions.
Even just logging when a lease changes hands would make debugging much
easier than today, although maybe that'd create too much log spam.

On Jan 28, 2017 12:49 PM, "Peter Mattis" <notifications@github.com> wrote:

Ah, thanks for correcting me about the versioned part, though I'm not sure
if that gives adequate history as we GC old versions.

I wasn't proposing converting the lease key to MVCC storage, but to instead
have a separate set of "lease-history" keys. Or perhaps "range-history".
One anxiety about using system.rangelog or similar for lease history is
that it introduces a distributed transaction on what was previously a Raft
request. That seems undesirable. Another part of my thinking for storing
the history next to the range was to make it colocated with the range data
so that it could be accessed during post-mortem debugging (i.e. when we
can't run SQL operations). Trying to find the contents of system.rangelog
if a cluster isn't running is quite a bit more difficult.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/issues/13210#issuecomment-275873698>,
or mute the thread

**Comment by bdarnell** [comment]
We used to log whenever the lease changed hands, but it was noisy so we put it behind V(1) (in replica_proposal.go; the message looks like `new range lease %s following %s [physicalTime=%s]`)

**Comment by BramGruneir** [comment]
An in memory version of this is done.  If we want to reopen this to use persistent storage, we can reopen and assign to 1.1

**Comment by petermattis** [comment]
I think we will almost certainly want persistent history.

**Comment by BramGruneir** [comment]
I'm going to move this to 1.2.  It's a relatively easy change, but I'm not going to get a chance to get to it before feature freeze.

**Comment by BramGruneir** [comment]
Is this still wanted?  Have we had any issues where a persistent history would have helped?

**Comment by petermattis** [comment]
I think it would still be useful, though I also think we can punt this to 2.1.

**Comment by BramGruneir** [comment]
Probably be a good starter project.  It's not too involved, but touches a bunch of different areas.

**Comment by a-robinson** [comment]
I can't recall any instances recently where `system.rangelog` and the in-memory lease history haven't been sufficient for my needs. I know that historically there were some times when more lease history would have been valuable, but it's been quite a while for me, so I'm in no rush for this.

**Comment by BramGruneir** [comment]
We already have a setting to keep a longer in-memory lease history, but the node has to restarted for it to take effect.  This could be improved without restarting, but it seemed like a waste of time to implement that if we were going to toss it for a persistent solution.
