### ISSUE TITLE
While importing a csv file tables go offline.

### ISSUE THREAD

**Issue by sushilr007** [cockroachdb/cockroach#132631]
**Describe the problem**

I was importing a CSV file containing 4 rows, but the process was taking a long time (around 20 minutes), so I interrupted it using CTRL + C. After that, when I tried to access the table using SELECT * FROM table_name;, I encountered the following error:

ERROR: relation "table_name" is offline: importing

**Expected behavior**
tabke_name.csv should be imported in that table. 

**Additional data / screenshots**

Command - cockroach start-single-node --certs-dir=/opt/etc/cockroach/certs --store=/opt/data --cert-principal-map=user.com:node,userts:root

Connection command - cockroach sql --certs-dir=/opt/etc/cockroach/certs/ --host=abhijit:26257
 
**Environment:**
Build Tag:        v24.2.3
Build Time:       2024/09/23 22:30:53
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.22.5 X:nocoverageredesign
C Compiler:       gcc 6.5.0
Build Commit ID:  217b43e69da61e9712d73e3e19fd5076fbdb26df
Build Type:       release
Enabled Assertions: false
![Screenshot 2024-10-15 110431](https://github.com/user-attachments/assets/d340e870-8886-44d5-baff-75bb9bef4f55)

Jira issue: CRDB-43187

**Comment by DrewKimball** [comment]
Hi @sushilr007, thanks for the report. It's expected that the table be taken offline while an import is in progress. What isn't expected is that the import is taking so long. Most likely, the import job encountered a retryable error, and was paused to wait for the user to either cancel or resume the job. You can view the import job with `SHOW JOBS`, and then cancel or resume it with `CANCEL JOB` and `RESUME JOB` respectively. [Here](https://www.cockroachlabs.com/docs/v24.2/import-into.html#view-and-control-import-jobs) is the relevant docs section for reference.

[Here](https://github.com/cockroachdb/cockroach/issues/114807) is a tracking issue for improving the observability of cases like these, so that they're easier to troubleshoot.

**Comment by DrewKimball** [comment]
Hi @sushilr007 , I'm going to close this out - feel free to open another issue if you have more questions.
