### ISSUE TITLE
setting: Add cluster setting for the draining node changes in UA

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#133166]
This is a placeholder issue to determine whether we should add a cluster setting for the draining node changes added for the distributed SQL UA work. This decision will likely be determined based on the outcome of https://github.com/cockroachdb/cockroach/issues/133165. If we decide that adding a cluster setting is not needed, we should document it on this issue prior to closing it out as non actionable.

Jira issue: CRDB-43489

Epic CRDB-43487

**Comment by shubhamdhama** [comment]
I think we can skip a cluster setting here. The PR has two major aspects: upgrade and dist physical planning. Both of them are well tested using unit tests. The scope is further limited because it's going to impact only multi-tenant deployments for the distsql aspect. Also, a cluster setting would only be able to control the distsql component where we already have higher confidence. And the upgrade itself is much simpler than the ones done in the past because it's a nullable column. Personally I feel cluster setting should be added for bigger feature release where we are more nervous.

The worst case for this PR I could think of is when drain fails half way through. Then that particular sql instance will be excluded from the plans even if node doesn't go down. But it's okay since expectation is if a drain fails it should be retried or more practically the whole node is forcefully shutdown. A half drain node is in sort of a undefined state.
