### ISSUE TITLE
ui: provide every/important graphs with a hover that shows you a histogram 

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#13389]
As part of #13184 

The idea is to provide a visualization of a node's contribution towards a point in the graph. 

Each bar on the X-axis on the histogram represents some range of stat contribution, and the Y-axis is the number of nodes in that bucket. Here's a drawing from @petermattis for reference:

![](https://cloud.githubusercontent.com/assets/6201335/22483438/4149b4de-e7cb-11e6-9b83-419e97ccd275.jpg)

> The histogram on the right is intended to show the point in time of the vertical line of the graph. If the user is not hovering over the graph, the histogram would show the rightmost time of the graph.

cc @vivekmenezes

**Comment by vivekmenezes** [comment]
I think this can be useful when looking at the latency of SQL queries by node. 
https://github.com/cockroachdb/cockroach/issues/13232 is going to move leases closer to requests so as to reduce latency, this graph/histogram can help visualize the effect of that.

**Comment by dianasaur323** [comment]
@kuanluo @mrtracy @vivekmenezes  I don't think this is making it into the 1.0 milestone. I see a couple bugs that I think are higher priority than changing visualization at this point. Shifting over milestone unless you all disagree.

**Comment by dianasaur323** [comment]
I think we might be taking a different approach at this point. @josueee not sure how far along you are on actual monitoring designs, but should we close this out and re-open new issues depending on what you decide to do?

**Comment by dianasaur323** [comment]
I think we can close out this issue since we aren't taking this approach anymore. Feel free to re-open if you disagree.

**Comment by piyush-singh** [comment]
@couchand interesting concept; this would be an alternative to showing latency with individual time series for each statement type right? Do you envision using it in a different scenario? Some thoughts on this approach:

- I like the progressive disclosure to the user. A user can see a high level view of the information at a glance and can drill in to see additional information with a hover. Not having to navigate to a different page saves time and improves discoverability.
- Histograms for a single point in time do sacrifice the ability to see trends or variation over time.
- We'd need to think about the hover interaction here. Some way of keeping the tooltip for a specific timestamp pinned open (e.g. clicking on a point on the time series) would be helpful when exploring so that this data doesn't disappear when you move your mouse. 

Caveats aside, I like this as a solution!
