### ISSUE TITLE
sql: inconsistent printing of decimals

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13384]
When using distsql I noticed that decimal results sometimes print differently when a query is distributed. This probably has to do with them going through an encoding and decoding cycle over the wire.

```
query RRRR
SELECT AVG(k::decimal), AVG(v::decimal), SUM(k::decimal), SUM(v::decimal) FROM kv
----
5.0000000000000000 2.8000000000000000 30 14

    		expected:
    		    5.0000000000000000 2.8000000000000000 30 14
    		    
    		but found (query options: "") :
    		    5  2.8  30  14  
```

Haven't looked at the details but I'm guessing we end up with a different but equivalent `inf.Dec` (different scale I guess?). Perhaps a sufficient solution is to always trim away any unnecessary 0s when printing.

Blocks #13377.
CC @nvanbenschoten @mjibson

**Comment by mjibson** [comment]
When decimals are encoded trailing zeros are indeed removed, which would explain this behavior if they go through the encode/decode cycle.

Removing trailing zeros when displaying decimals would alleviate this problem and bring the display in line with the encoding.

However, one of the huge benefits to decimals is to be able to have significant zeros that don't just disappear. Saying it's `21` degrees is different than saying it's `21.00` degrees. The difference is worse when discussing money, which (we think) is a normal use for decimals.

I am of the opinion that trailing zeros should be encoded on disk instead of truncated. This allows users to set and maintain a precision of their choosing. We should (not sure if we do currently or not, but certainly the new apd package can/will) round decimals to whatever precision/scale is specified by the column's data type and leave any zeros. This is different behavior than postgres, but I think is better, and would fix the problem you describe.

**Comment by RaduBerinde** [comment]
Interesting proposal. I am not sure we need to change the encoding itself to achieve this though; we should always know the type of the column so we could set the precision right after decoding.

If we change the encoding we need to make sure we always round to the same number of decimals before encoding keys (we don't want `21` to encode differently than `21.00` in an index); and it would be ideal if the encoding would somehow be backward compatible.

**Comment by mjibson** [comment]
Setting the precision after decoding isn't quite safe either since that could add 0s that weren't there before encoding, but maybe that is still better than what we have now. The index point is interesting. The decimal spec describes the `21` vs `21.00` case you list, and concludes that those are different numbers. Obviously that data stored in an index should be the same, which is maybe why the 0s are removed in the first place? (Postgres removes the 0s too. Not sure if it's the spec or if they also remove them due to index reasons.)

But the query you have above doesn't have a column type for these, since `AVG` and friends produce decimals, so it's unclear to what precision to round them to. The 16 zeros are there because that's what inf.Dec adds. It is *possible* that switching to apd will fix this problem because it's more consistent. (See https://github.com/mjibson/cockroach/commit/307ad6cd78cf391ef26e8b39c4608a926b3f1840#diff-81d506ba99f236e164c1d1871f63c5b3 - which is the apd branch in cockroach where these 0s are removed from these kinds of queries)

**Comment by RaduBerinde** [comment]
Ah, I see. I guess we want to replicate this kind of behavior:

```sql
postgres=# INSERT INTO t VALUES (1.00::decimal), (2.0::decimal), (3::decimal);
INSERT 0 3
postgres=# SELECT * FROM t;
  v   
------
 1.00
  2.0
    3
```

This `1` is different than `1.00` and yet equal to it is tricky w.r.t. indexes. I think this is a case where we want the encoding to have a "key" part and a "value" part, similar to collated strings (#2473).

**Comment by RaduBerinde** [comment]
PR #13706 temporarily adds some logic test magic to trim extra decimals. That should be reverted when we can be consistent.
