### ISSUE TITLE
raft: address the microbenchmark regression in Proposal3Nodes

### ISSUE THREAD

**Issue by iskettaneh** [cockroachdb/cockroach#133973]
The benchmark Proposal3Nodes shows a significant regression:

for metric: sec/op
• pkg/raft/rafttest→Proposal3Nodes-32 :95500893.13%

Jira issue: CRDB-43852

**Comment by iskettaneh** [comment]
I can see that this commit `91d4c7f4` changed the test a little bit:
Before that commit: `BenchmarkProposal3Nodes           175898              6981 ns/op`
At that commit:        `BenchmarkProposal3Nodes                1        5033266909 ns/op`

**Comment by pav-kv** [comment]
This benchmark wasn't waiting for the right thing before that commit - it just scanned all the nodes once and waited for nothing. After the commit, it does wait for what it wants. Not sure it's worth optimizing this benchmark, consider closing. A proper way to minimize this wait would be making it event-driven rather than time-paced. As an alternative, could reduce 100ms to something more granular.

**Comment by pav-kv** [comment]
Alternatively, consider removing this benchmark. It benches a test-only type that we don't use. A better benchmark would use `RawNode` directly.

**Comment by iskettaneh** [comment]
Actually the 5033266909 ns/op is because we wait for the commit to converge by running 50 iterations, and sleeping 100ms in between. 50 * 100ms = 5000ms.

I think the benchmark isn't even waiting for what it wants, as its finishing before actually waiting for the commit to converge
