### ISSUE TITLE
observability: sorting based on replicas doesn't work

### ISSUE THREAD

**Issue by vidit-bhat** [cockroachdb/cockroach#134197]
On the [cluster overview page](https://drt-scale-0001.drt.crdb.io:26258/#/overview/list) for the `drt-scale` 150-node cluster, sorting by `Replicas` doesn't work.

https://github.com/user-attachments/assets/e8a9a5fc-1098-4d0e-a082-1dd192eafe08

Jira issue: CRDB-43970

**Comment by kyle-a-wong** [comment]
This bug isn't related to scale testing and isn't new to 24.3. In addition to the replicas column, the nodes column sorting doesn't do anything for single region clusters (the sorting on this column sorts regions and not nodes, but since this is a single region cluster, there are no regions visible) and uptime doesn't work. We should go through this table and fix / remove sort on any applicable columns

Removing related labels.
