### ISSUE TITLE
util/encoding: span pretty-printer behaves strangely with decimal endkey 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13412]
Found while investigating #13373:

```sql
CREATE TABLE foo (x DECIMAL PRIMARY KEY, y DECIMAL);
EXPLAIN SELECT * FROM foo WHERE (x,y) = (12,123);
+-------+------+-------+-----------------------------------------------------+
| Level | Type | Field |                     Description                     |
+-------+------+-------+-----------------------------------------------------+
|     0 | scan |       |                                                     |
|     0 |      | table | foo@primary                                         |
|     0 |      | spans | /12-/<did not find terminator 0x0 in buffer 0x1801> |
+-------+------+-------+-----------------------------------------------------+
```

This "did not find terminator" thingy is ... unsettling.

cc @dt @nvanbenschoten.

**Comment by nvanbenschoten** [comment]
The `did not find terminator` part is a known result of our use of `Key.PrefixEnd` when transforming exclusive end keys into inclusive end keys in `sql/index_selection.go`. The following example demonstrates why this happens:

```
root@:26257> CREATE TABLE foo (x INT PRIMARY KEY, y INT);
CREATE TABLE
root@:26257> EXPLAIN SELECT * FROM foo WHERE (x,y) = (12,123);
+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | scan |       |             |
|     0 |      | table | foo@primary |
|     0 |      | spans | /12-/13     |
+-------+------+-------+-------------+
(3 rows)
```

In order to minimize the number of keys scanned, we scan the primary index only over the keyspace where the IN predicate can be true. In this case, that segment of the index is only where `x = 12`. Because Spans are encoded in the form `[start_key, end_key)`, we can't transform this into a scan over `[12, 12)`. Instead, we increment the end_key before encoding and scan `[12, 13)`. However, some data types like DECIMAL and INTERVAL don't have a discrete "next" value, so this trick won't work. Instead, we use `PrefixEnd` on the encoded key to find the next possible key to use for the exclusive end key. This interaction is all in [`encodeInclusiveEndValue`](https://github.com/cockroachdb/cockroach/blob/6a7b1ffb001e6ec0b795f8680bf724a87bf67ca3/pkg/sql/index_selection.go#L950). Unfortunately, in many cases, doing so brings the encoded key out of bounds for the datum type, so when we later try to decode it during pretty printing we are unsuccessful.

The results are actually worse in cases where the `Key.PrefixEnd` can be decoded, because in those cases the results may look incorrect when printing (but will still evaluate correctly):

```
root@:26257> CREATE TABLE bar (x INTERVAL PRIMARY KEY, y INTERVAL);
CREATE TABLE
root@:26257> EXPLAIN SELECT * FROM bar WHERE (x, y) = ('12', '123');
+-------+------+-------+--------------------------+
| Level | Type | Field |       Description        |
+-------+------+-------+--------------------------+
|     0 | scan |       |                          |
|     0 |      | table | bar@primary              |
|     0 |      | spans | /0m0d12s-/0m1d-23h59m48s |
+-------+------+-------+--------------------------+
```

**Comment by knz** [comment]
Thank you for your detailed explanation. This clarifies the mechanism that causes the current output.

I think however that the overall UX of this behavior is poor and could be improved. 

The first possible improvement is to replace the error "did not find terminator" by a simple "???" so that the display becomes "/12-/???"

The second possible improvement is to annotate the types which are handled by appending `PrefixEnd` for their "next value", and for these types look whether there is a `PrefixEnd` to decide how to pretty-print the value.

**Comment by nvanbenschoten** [comment]
I agree. I created #13637 as a temporary patch to this issue. 

However, I don't think we should close this yet even with that change because I think in the long term we will want to revisit your second suggestion. The reason that suggestion is tricky is because "looking at whether there is a `PrefixEnd`" is not trivial. Imagine an encoded decimal with a `PrefixEnd` applied, for instance. This will increment the null terminator `0x00` to a `0x01`. I'm not sure how we would detect this reliably during decoding of an arbitrary key where the decimal may or may not be the value. It would require us to pass around a good amount more context about keys, at least to the places where we want to pretty-print them. This alone also wouldn't fix the cases where the encoded value with a `PrefixEnd` is kept in-bounds, in which case the pretty-printed value does not throw an error, but is just incorrect. That actually may be a bigger issue.

**Comment by knz** [comment]
What about maintaining the length of the encoded data in the key alongside with the key value?

**Comment by nvanbenschoten** [comment]
Yeah, something like that could work, although at that point it might make more sense to just ship around the `Datum` value and an `inclusive` flag with the encoded key instead.

**Comment by jordanlewis** [comment]
```
CREATE TABLE foo (x DECIMAL PRIMARY KEY, y DECIMAL);
EXPLAIN SELECT * FROM foo WHERE (x,y) = (12,123);
```

**Comment by jordanlewis** [comment]
er, I missed the result, which demonstrates that this problem is solved:

```

Time: 3.856ms

  tree | field  | description
+------+--------+-------------+
  scan |        |
       | table  | foo@primary
       | spans  | /12-/12/#
       | filter | y = 123
(4 rows)
```
