### ISSUE TITLE
stability: node crashing and not able to recover after running out of memory

### ISSUE THREAD

**Issue by jeffreims** [cockroachdb/cockroach#13424]
### Dev machine specs:

8 GB memory
2 vCPU
20 GB disk

### DB

2 million~ rows

Columns look like this: 

``
id SERIAL PRIMARY KEY, 
col1 string(1500), 
col2 string(100), 
col3 string(50), 
col4 string(500), 
col5 int, 
col6 string(100), 
col7 string(30), 
col8 int,
col9 int
``

# The problem

So I inserted 2 million feeds into cockroachdb this will take like 1.5 gig of memoy usage.

Now we forgot to insert the value for col5, and it says NULL. So i'll do
``
update table set col5 = 30
``

Now after a while it will lose connection to the DB and according to the log files CockroachDB ran out of memory.

When restarting CockroachDB it will continue on doing something big using 50-80% CPU and 8 GB of ram + 4 GB off swap this will continue for like an hour, than suddenly it will take the remaining 4 GB swap space and crash again.

**Comment by petermattis** [comment]
Thanks for the report, @jeffreims.

A transaction which modifies 2 million rows is going to be problematic. The immediate problem is that there are places in transaction handling where we keep track of all of the keys the transaction has touched in memory. 2 million keys * O(100 bytes/key + other overhead) could easily lead to the out of memory issue you're experiencing.

In the short term, we should do a better job at prohibiting such operations. In the longer term, perhaps we can add a form of `ALTER TABLE` that can do this work in pieces similar to other schema change operations.

Cc @knz, @vivekmenezes

**Comment by knz** [comment]
@petermattis  In the longer term we should use disk-based temporary storage on each node, to support this together with session-level temporary tables, large sorts & joins, etc. 

@jeffreims  In the mean time, if you are ok with running the update non-transactionally, you could issue multiple UPDATE statements with constraints on your primary key, to updates smaller sets of rows at a time.

**Comment by petermattis** [comment]
> @petermattis In the longer term we should use disk-based temporary storage on each node, to support this together with session-level temporary tables, large sorts & joins, etc.

Besides the memory issue, a large mutating transaction that is operating on an active system will be unlikely to ever finish due to being restarted. It doesn't sound like that is the case for @jeffreims was hitting, but wanted to point out that using temporary on-disk storage won't completely solve the problem for mutating transactions.

**Comment by knz** [comment]
Ok, but then we're having a different discussion -- that an optimistic system with restarts is increasingly unable to commit transactions as their mutation set becomes larger. If that really becomes an issue in production systems we'll need a separate mechanism for that, orthogonal to node-local temp disk storage.

**Comment by petermattis** [comment]
> If that really becomes an issue in production systems we'll need a separate mechanism for that, orthogonal to node-local temp disk storage.

Yep.

**Comment by bdarnell** [comment]
The problem here appears to be that the huge EndTransaction request has made it into the raft log, and once it's in the raft log we have to process it (or to fail consistently on all replicas). There are several things we could do to mitigate this:
- Prevent the command from entering the raft log (easy). Either impose a size limit on all commands or make TxnCoordSender abort transactions as soon as they accumulate too many intents.
- Make the EndTransaction intent processing more efficient. We must have held all the intents in memory in the TxnCoordSender for them to have made it to the raft log. We're doing something while processing the EndTransaction that is blowing up the memory requirements; we can probably do better here.
- Store intents outside the main transaction record for large transactions (hard). If the TxnCoordSender flushed intents to a separate location when it got large, we could avoid ever having all the intents for a transaction in memory and could lift this limit on transaction size. (this could also open the door to lifting the single-coordinator limit)

**Comment by dianasaur323** [comment]
assigning to @knz. Feel free to reassign.

**Comment by knz** [comment]
From @andreimatei: 

> about the previous discussion about the memory limits around EndTransaction requests, I’ve talked to Rafa and Ben and I think we’re all on the same page now. What I was missing is that, at least part of the problem, is that the size of the EndTransaction matters downstream of Raft, where we can’t have any dynamic checks against, say, a memory monitor - every replica needs to behave the same. So we can only have checks upstream of raft ensuring that we don’t propose an EndTransaction that’s too large. So some sort of row/intent limit seems like the way to go, for now. Longer term, we should find ways of taking the intents out of the EndTransaction request/command

**Comment by knz** [comment]
Discussed with @cuongdo: neither @andreimatei nor I can address this competently and without compromising stability without serious/close-by handholding by either @bdarnell or @tschottdorf.

**Comment by knz** [comment]
@cuongdo says I assign to peter for re-assign.

**Comment by petermattis** [comment]
@bdarnell Should we put in a stop-gap solution for 1.0? For example, a limit on the number of intents enforced at the `TxnCoordSender` level.

**Comment by bdarnell** [comment]
Yes, I think we should limit the number of intents at the TxnCoordSender before 1.0. (Even better if we could express this limit in terms of "rows" instead of "intents", but in any case we should try to get some limit in place)

**Comment by petermattis** [comment]
@bdarnell Do you have bandwidth to do this?

**Comment by petermattis** [comment]
`TxnCoordSender.update` and `TxnCoordSender.Send` are the two places where `txnMetadata.keys`is updated.

**Comment by bdarnell** [comment]
Yes, I can take this one.

**Comment by bdarnell** [comment]
propEvalKV has made this much less severe: the downstream-of-raft processing is now pretty dumb and doesn't blow up the command beyond what was written to disk. So while it's still good to trap very large transactions as early as possible, you shouldn't get stuck as easily with commands in the log that can't be replayed. I'll add a couple of settings to trap large transactions in TxnCoordSender and large individual commands (will also catch large DeleteRange blowups) in Replica.propose.
