### ISSUE TITLE
Insights page is not loading on the scale cluster

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#134225]
Visit the Insights page and view the "Failed to fetch" error:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/fa3b660a-f251-4365-ba5b-07acda4e9502">

Jira issue: CRDB-43980

**Comment by kyle-a-wong** [comment]
I believe this happens when there is a high contention insight. For these insights, db-console does an additional request to get get contention info, which has very poor performance due to doing a cluster wide fan out. In the scale cluster specifically, this query takes ~2.5-3 minutes to complete, and there is a timeout of 3s on the request.
