### ISSUE TITLE
storage: consider adding configurable guardrails against disk exhaustion

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#134333]
Is it possible to extend the `vfs` API so that we wouldn't be able to create new files once more than 95% of the underlying disk space is used? Ditto something similar for the pebble API that we use in the row-by-row engine for temp storage.

Jira issue: CRDB-44024

**Comment by yuzefovich** [comment]
I've looked into this, and I don't think we can do better from Queries perspective. I set up a 3 node cluster, with 2 stores on each node having 50GB, and imported TPCH SF50 dataset. This made it so that each store used up about 40GB (80%) of capacity, and then I ran TPCH Q1 with different concurrency.

With concurrency 1, via `sql.disk.distsql.spilled.bytes.written` metric I confirmed that what we account for against `--max-disk-temp-storage` limit (which is 32GiB by default) matches actually used up capacity from disk. One caveat here is that the temporary disk storage usage **does not** count against `used` number; instead, it reduces `usable` number.
<img width="457" alt="Screenshot 2024-11-12 at 5 30 39 PM" src="https://github.com/user-attachments/assets/0a23cbbf-a9ff-4a31-a78f-6c30bd7efd1e">

This way used percentage will be increased, but slowly - we do have the same amount of space available on the second stores on each node.

Then, I issued Q1 with concurrency 10, and it led to disk exhaustion on store 1 on n2 and store 1 on n3, killing `cockroach` processes on both nodes and making cluster unavailable. Our disk space accounting didn't help because we didn't reach 32GiB limit on either node (we only had free 10GB on each store).

----

At this point, I'll re-route this issue for storage team to see whether we can put some guardrails to prevent this type of a crash. In particular, I wonder whether it is possible to extend the `vfs` API so that we wouldn't be able to create new files once more than 95% of the underlying disk space is used? Ditto something similar for the pebble API that we use in the row-by-row engine for temp storage.

**Comment by jbowens** [comment]
Guardrails are tricky for the primary storage engine. Specifically, we can't stop writing to disk because:
1. Stopping the commit of new raft log entries has a similar effect to a disk stall. This results in unavailability of all ranges the node is leaseholder to, even if the disk capacity issue is local to this specific node. If the capacity issue is local to the node, it's preferable for us to crash and allow leases to move then stay up and incapable of making progress.
2. In order to reclaim space, we need to write new files. Tombstones (including range deletion tombstones written during replica removals) must be compacted to be able to delete data.

#74104 and #79210 discuss the generalized problem of preventing out-of-disk in scenarios where storage is underprovisioned in the context of the configured zone configurations.

In the context of _spilling to disk_, it seems more reasonable to forcefully reject writes. Writes to the row-based temp engine however are shared across queries, and the LSM would need to be able to write new files in order to delete old files. For the vectorized spilling to disk that just uses a vfs.FS directly, I think we could reasonably error out if the disk is approaching capacity.

**Comment by dshjoshi** [comment]
@jbowens whose responsibility is it to reject the writes in case disk exhaustion - is it admission control, storage or KV?

cc: @nicktrav

**Comment by jbowens** [comment]
There's no support for it today, so we would need to decide whether it belongs with admission control or KV. See https://github.com/cockroachdb/cockroach/issues/74104.

I'm going to close this issue out in favor of #74104 which addresses the generalized problem of handling out-of-disk scenarios.
