### ISSUE TITLE
Invisible Indexes still being used by the planner

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/cockroach#134825]
**Describe the problem**

Despite marking the index as `NOT VISIBLE`, it still appears to be used in certain situations. It seems that it shows up in the plans specifically for inserts, not for selects.

**To Reproduce**

The conditions used to reproduce this were adopted from a customer reproduction. I'm unsure what elements of the schema below are absolutely essential, so I've included all of them. The full reproduction details along with two statement bundles that reproduce can be found here: https://upload.cockroachlabs.com/receive/?thread=V42W-V3WP&packageCode=eUqNHwFHpAw0fY03uwG0YIforD7G6agb1Xgi0TqTdmQ#keyCode=hyYsNQ97A7BuAG9GiK4bc4wX1o8iay-3ee6Y4m3Dh0U

I've included them in a sendsafely link so that only internal folks can access it. This is because a customer statement bundle was used to reproduce it.

Navigating to the DB Console -> Databases -> Table -> clicking on the `NOT VISIBLE` index will show that queries are using this index, despite no index hint being used.

Ticket: https://cockroachdb.zendesk.com/agent/tickets/24366

**Expected behavior**

`NOT VISIBLE` indexes should not be chosen unless an index hint is provided.

**Environment:**

The customer environment where it reproduces is on 23.2.14. This also reproduces on master.

**Additional context**

User cannot use invisible indexes as intended.

Jira issue: CRDB-44274

**Comment by mgartner** [comment]
The `NOT VISIBLE` index used in the reproduction is defined as:

```sql
UNIQUE INDEX identity_credential_identifiers_storing
  (nid ASC, identifier ASC, identity_credential_type_id ASC)
  STORING (identity_credential_id)
  WHERE identifier != '':::STRING NOT VISIBLE
```

in the `REGIONAL BY ROW` table `identity_credential_identifiers`. 

A `UNIQUE`, `NOT VISIBLE` index still maintains uniqueness of its columns, just like a `UNIQUE`, `VISIBLE` index. This is required to prevent data corruption and incorrect results, especially in the case that the index is made `VISIBLE` again in the future. In order to maintain the index's uniqueness, a read is performed during an `INSERT` to the `identity_credential_identifiers` table as a post-query validation check. This read is the read tracked in the DB console.

The docs mention that a `UNIQUE` index may be read from [here](https://www.cockroachlabs.com/docs/stable/indexes#performance):

> Indexes that are not visible are still used to enforce UNIQUE and FOREIGN KEY [constraints](https://www.cockroachlabs.com/docs/v24.2/constraints).

And [here](https://www.cockroachlabs.com/docs/v24.2/alter-index#not-visible):

> Indexes that are not visible are still used to enforce UNIQUE and FOREIGN KEY [constraints](https://www.cockroachlabs.com/docs/v24.2/constraints).

I've created a PR to make the documentation more explicit that reads and writes on `UNIQUE`, `NOT VISIBLE` may be necessary to maintain uniqueness and will be tracked by the system, see https://github.com/cockroachdb/docs/pull/19117. 

I've also created an issue for the team to discuss disallowing invisible `UNIQUE` indexes, see https://github.com/cockroachdb/cockroach/issues/134856. They have limited use cases and their existence may be a source of the confusion.

**Comment by mgartner** [comment]
I'll go ahead and close this issue, and you can follow along with potential changes to invisible indexes described in https://github.com/cockroachdb/cockroach/issues/134856 and the docs changes in https://github.com/cockroachdb/docs/pull/19117.

**Comment by aeneasr** [comment]
Hello, thank you for the quick turnaround.

While the UNIQUE INDEX explanation makes sense, we also shared on regular invisible index that showed no queries in the statement view but still showed as being used. We assume it was used as part of CASCADE DELETE but can’t prove it.

We have another index that also covers the column with the CASCADE DELETE which is why we made the original index invisible (to see if we can drop it).

**Comment by mgartner** [comment]
> While the UNIQUE INDEX explanation makes sense, we also shared on regular invisible index that showed no queries in the statement view but still showed as being used. We assume it was used as part of CASCADE DELETE but can’t prove it.

Yes, that is possible as mentioned in the docs [here](https://www.cockroachlabs.com/docs/v24.2/alter-index#not-visible):

> Indexes that are not visible are still used for foreign key cascades.

This is not technically necessary for correctness, but it avoids full table scans to find rows to cascade updates/deletes to. So in practice, it helps avoid horrible performance impacts from setting an index as invisible.

> In our view the invisible index should not be used at all (there is another index indexing the same thing)

I have an idea about why that might be happening. I'll try to reproduce this, and I'll re-open this issue for now. If you have a reproduction you can share, that would be helpful.

**Comment by mgartner** [comment]
@aeneasr I was able to reproduce a few cases similar to what you described above. I've documented them in https://github.com/cockroachdb/cockroach/issues/135018. You can follow along there for future updates, and I'll close this issue. Thanks again for the report!
