### ISSUE TITLE
handle WriteIntentError at the engine

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1352]
We currently have two distinct semantics for handling `WriteIntentError`s:
- When reading consistently, a `WriteIntentError` is a real error, and aborts the operation.
- When read inconsistently, a `WriteIntentError` is not really an error, because the read is inconsistent, but is still propagated up from the Engine through the Range to the Store as a signal that an unresolved write intent was found and should be cleaned up (because the Engine cannot itself resolve the intent).

The second case is pretty ugly, and requires careful handling away from the source (the Engine). We should refactor this such that `WriteIntentError`s are never propagated up from the Engine on inconsistent reads, for example by initializing the Engine with a dealing-with-intents callback that closes over the store. See #1351.

**Comment by tschottdorf** [comment]
This isn't as easy as it sounds: We want to handle intents only once per replica set, for the replica which proposed the command. That means that a) you'll end up passing that information all the way down the call stack (which seems weird as you shouldn't be aware of where you're running the command down at the execution level or b) you'll end up passing up the intents all the way to the range (above `r.executeCmd()`), which is also awkward. I'm currently giving b) a try nevertheless since I agree that the current handling is error prone.

**Comment by tamird** [comment]
Closed by #1367, sorta.
