### ISSUE TITLE
Function name conflicts with C library <time.h>

### ISSUE THREAD

**Issue by LasTshaMAN** [cockroachdb/cockroach#13543]
I was trying to build Cockroach from its source code on Windows 8.1 using MinGW(x86_64-6.3.0-posix-seh-rt_v5-rev1) as a GCC provider.
When I run `make test` I get the following error:

![image](https://cloud.githubusercontent.com/assets/7031569/22861497/226e66fe-f12b-11e6-940c-9f4c81630051.png)

From what I understand, `ftime` function defined in `import "C"` block has the same name as the function that comes from <time.h> library. Hence, compiler can't resolve them.

I ask on Gitter about it and @knz suggested to create an issue. So, here it is ;)
As a workaround I tried to rename `ftime` to something else. But, if I do so, I get another error:

![image](https://cloud.githubusercontent.com/assets/7031569/22861515/8b13dd1a-f12b-11e6-8b2a-cf7aad2b0a0a.png)

After googling for some time about the second error, I didn't find the exact origin for it. I suspect it has something to do with the fact that I'm using MinGW and Windows instead of Linux.

**Comment by bdarnell** [comment]
We do not currently support mingw or windows at all; this is being tracked in #3830.

**Comment by LasTshaMAN** [comment]
Ok, you should probably mention that Windows currently is not supported in your prerequisites [here](https://github.com/cockroachdb/cockroach/blob/master/CONTRIBUTING.md).

**Comment by knz** [comment]
@LasTshaMAN to follow up on the issue you found after you applied my workaround. The problem is that your mingw library apparently does not provide `strptime`. However `strptime` is a standard POSIX function.

As ben said we do not support Windows indeed, but the more general issue is that CockroachDB currently requires a POSIX environment. If your Windows environment is sufficiently close to POSIX it may work, otherwise it will definitely not work. In particular: 

- Linux subsystem for Windows 10 will likely work, 
- linking with the libraries of Windows services for UNIX (Windows Vista+7) *may* work 
- linking with the Cygwin libraries *might* work (probably not though).
- anything else likely won't work.

I am sorry I didn't make these requirements explicit earlier.
