### ISSUE TITLE
Unable to pull cockroachdb/cockroach:v20.2.8 from docker hub

### ISSUE THREAD

**Issue by Swanoff** [cockroachdb/cockroach#135789]
Docker error: 
```Error response from daemon: manifest for cockroachdb/cockroach:v20.2.8 not found: manifest unknown: manifest unknown```

I am unable to find v20.x tags in docker hub. Is it completely removed from the hub? Also couldn't find any relevant posts or articles explaining the reason behind this removal.

Could someone provide clarification on whether older versions like v20.2.8 are no longer supported or if they have been deprecated for a specific reason?

Jira issue: CRDB-44708

**Comment by alyshanjahani-crl** [comment]
We removed EOL versions of CockroachDB older than 4 years after their original .0 release because these EOL versions are not recommended for use due to lack of security updates.

After receiving feedback from users, we are restoring the Docker images for releases 20.1 and 20.2 but will remove them in May 2025 (in 6 months from now). We will also remove releases of 21.1 at that time.

We recommend that all users upgrade to a newer release of CockroachDB if currently using an EOL release due to lack of bug fixes or security updates. The release support policy and EOL dates for all CockroachDB releases are available here:
https://www.cockroachlabs.com/docs/releases/release-support-policy#end-of-life-eol-versions
