### ISSUE TITLE
roachtest: add the option to enable continuous (cpu) profiling

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#135972]
Cluster-wide automatic cpu profiling can be enabled via cluster setting [1]. There are multiple use-cases, including (manual) performance debugging, and profile-guided optimization [2].

Ideally, this option could be enabled _metamorphically_ for any (eligible) roachtest. However, at this time, we don't have a general mechanism for _metamorphic_ cluster settings [3]. As a temporary workaround, we could (randomly) enable cpu profiling before a given test is executed (i.e., `TestSpec.Run`). Additionally, we could consider adding a CLI option, e.g., `roachtest run --enable-cpu-profling ...` to force the corresponding cluster settings.

[1] https://www.cockroachlabs.com/docs/stable/automatic-cpu-profiler
[2] https://go.dev/doc/pgo
[3] https://github.com/cockroachdb/cockroach/issues/105807

Jira issue: CRDB-44802

**Comment by srosenberg** [comment]
Note, at this time I'm finding three existing roachtests which enable cpu profiles,

```
find pkg/cmd/roachtest/tests -name "*.go" |xargs grep -i "cpu_profile" |awk '{print $1}' |sort -u
pkg/cmd/roachtest/tests/kv.go:
pkg/cmd/roachtest/tests/rebalance_load.go:
pkg/cmd/roachtest/tests/restore.go:
```

E.g., in `kv.go`, we enable it unconditionally for the `kv/gracefuldraining` roachtest [1]. 

**NOTE**:  `.pprof` files will be available under the `artifacts` directory upon test failure, only; e.g., [2].

[1] https://github.com/cockroachdb/cockroach/blob/5c5c9d6803d47848aa1960dd6642d5f2c1926814/pkg/cmd/roachtest/tests/kv.go#L537
[2] https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestNightlyGceBazel/17734111:id/kv/gracefuldraining/cpu_arch%3Darm64/run_1/artifacts.zip!/logs/1.unredacted/pprof_dump/cpuprof.2024-11-13T12_01_54.544.23.pprof

**Comment by tbg** [comment]
This issue is about continuous profiling (at least according to title), but the built-in CPU profiler is not exactly that. It's traditional profiling, enabled according to some heuristics. For pgo, we should start with a small stable set of profiles. I wouldn't source these from the automatic profiler, as it's going to be unpredictable exactly when these are taken. Instead, we can pick a few nightly benchmarks, and change them so that after completion, they immediately run for another couple of minutes and take a CPU profile in the middle. These (from nightlies) can then be picked up by pgo at some interval. I assume somewhere down the road we might also throw in some profiles from Cloud.

Re: "it's useful to metamorphically enable the CPU profiler", I'm not sure. Sure, why not, but if they're not reliably there on failure, then is there really a point? Certainly for benchmarks we want to make sure they are _not_ metamorphically enabled.

So I'm not exactly sure what we're after here. If it's pgo, I'd rather we took a less roundabout and more controlled approach.

**Comment by srosenberg** [comment]
> Certainly for benchmarks we want to make sure they are not metamorphically enabled.

Why? Does a specific set of benchmarks capture _exactly_ many of the customer workloads? Since we don't have an ideal distribution, taking the union over many sampled runs may identify common "hot" paths.

**Comment by tbg** [comment]
I worry that we'll water down the hot paths that actually matter. As a contrived example, take 100 profiles that exercise backup/restore, and one that exercise the fundamental hot paths in the OLTP paths. If we merge them, on the whole the hot paths for OLTP might be diluted enough to not be optimized.
Your argument would apply if we took a combined profile sourced from our Cloud fleet: whatever looks hot there is closer to what matters. But I'd rather we started with targeted profiles that we know are valuable.
