### ISSUE TITLE
Update configHashes and other fields when a new range is created by a range split

### ISSUE THREAD

**Issue by kkaneda** [cockroachdb/cockroach#1362]
https://github.com/cockroachdb/cockroach/pull/1337 makes a fix so that MaxBytes is correctly set for a new range. We would need a similar fix to other fields such as `configHashes`.

**Comment by bdarnell** [comment]
We also need to ensure that all of these things are set when we create a new range via replication. This probably means a new function to be called from both ApplySnapshot and SplitRange. (see #1526)

**Comment by kkaneda** [comment]
I'm not sure, but I wonder it would be easier to reason about the correctness if we use Raft to send the config information relevant to a range (e.g., whenever the max bytes changes, a leader replica proposes a Raft command to update the max bytes) as we have deterministic order on how Raft commands are applied.

**Comment by bdarnell** [comment]
I like the idea of using a raft command to ensure that all the replicas update at the same time, and storing the current value in the range-local data instead of only in gossip. It doesn't completely avoid the problem discussed here (we still need to sync the in-memory state with the on-disk state on ApplySnapshot and SplitRange), but it means that the solution will follow the same pattern as RangeDescriptor and AppliedIndex, instead of introducing direct access to gossip in these methods.

**Comment by kkaneda** [comment]
Thanks for the feedback! I'll give a shot.

**Comment by kkaneda** [comment]
As discussed in #1672, we don't need to copy any other range in-memory states.
