### ISSUE TITLE
Poor performance when filtering on more than one JSON property 

### ISSUE THREAD

**Issue by cward-titanhq** [cockroachdb/cockroach#136315]
**Describe the problem**

When working with JSON data types covered by a GIN or inverted index:
SELECT queries that include more than one property of a JSON column in the WHERE clause perform badly. The performance gets worse as more filters are added. Equivalent queries in Postgres perform better.

**To Reproduce**

Create the following test table, populate  with 100k rows, and update the stats:

```sql
CREATE TABLE test (
  id UUID NOT NULL AS ((doc->>'id':::STRING)::UUID) STORED,
  doc JSONB NOT NULL,
  PRIMARY KEY (id),
  INVERTED INDEX doc_contents (doc)
);

INSERT INTO test (doc)
SELECT ('{"id" : "' || gen_random_uuid() || 
      '", "timestamp" : "' || (now() + (n || ' microseconds')::INTERVAL) || 
      '", "flag1" :  ' || (case when (n % 2 = 0) then 'true' else 'false' end) || 
      ', "flag2" :  ' || (case when (n % 23 = 0) then 'true' else 'false' end) || 
      ', "string1" : "testa' || (n % 13) || 
      '", "string2" : "testb' || (n % 23) || 
      '"}')::json
FROM
(select generate_series(1, 100000) as n) AS x;

ANALYSE test;
```

Run the following queries, note the count in all cases is 4347:
```sql
SELECT COUNT(*) FROM test WHERE doc->'flag2' = 'true'::JSONB;
SELECT COUNT(*) FROM test WHERE doc->'string2' = '"testb0"'::JSONB;
SELECT COUNT(*) FROM test WHERE doc->'flag2' = 'true'::JSONB AND doc->'string2' = '"testb0"'::JSONB;
```
### WHERE with 2 filters

Now run these same queries again, prefixing with EXPLAIN ANALYSE . Note that for the initial scan against the index `test@doc_contents`, the first two queries return `actual row count: 4,347`, while the last query returns `actual row count: 8,694`.

This same behaviour also occurs using the alternative syntax:
```sql
EXPLAIN ANALYSE SELECT COUNT(*) FROM test WHERE doc @> '{"flag2": true, "string2": "testb0"}';
```

### WHERE with 3 filters
```sql
EXPLAIN ANALYSE SELECT COUNT(*) FROM test WHERE doc->'flag2' = 'true'::JSONB AND doc->'string2' = '"testb0"'::JSONB AND doc->'string1'  = '"testa0"'::JSONB;
```

The initial scan against `test@doc_contents` in the above query shows   ` actual row count: 16,386`, even though the number of rows returned by the query is only 334.

**Expected behavior**

As the filters are being ANDed together, the number of rows retrieved from the GIN index should decrease as as additional filters are added to the WHERE clause, not increase. 

Running the equivalent queries against a Postgres 16 database, you can see that the correct number of rows is returned by the initial index scan :

```
test=> EXPLAIN ANALYSE SELECT COUNT(*) FROM test WHERE doc @> '{"flag2": true, "string2": "testb0"}';
                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=2577.67..2577.68 rows=1 width=8) (actual time=7.121..7.122 rows=1 loops=1)
   ->  Bitmap Heap Scan on test  (cost=66.60..2572.62 rows=2020 width=0) (actual time=2.694..6.814 rows=4347 loops=1)
         Recheck Cond: (doc @> '{"flag2": true, "string2": "testb0"}'::jsonb)
         Heap Blocks: exact=2500
         ->  Bitmap Index Scan on test_doc_idx  (cost=0.00..66.10 rows=2020 width=0) (actual time=2.384..2.384 rows=4347 loops=1)
               Index Cond: (doc @> '{"flag2": true, "string2": "testb0"}'::jsonb)
 Planning Time: 0.115 ms
 Execution Time: 7.164 ms
(8 rows)
```
  

**Additional data / screenshots**

EXPLAIN ANALYSE output for CockroachDB:
[cockroachdb-explain-analyse.txt](https://github.com/user-attachments/files/17938303/cockroachdb-explain-analyse.txt)

SQL to setup on PostgreSQL 16:
[postgresql-setup-test.txt](https://github.com/user-attachments/files/17938314/postgresql-setup-test.txt)

EXPLAIN ANALYSE output for PostgreSQL:
[postgresql-explain-analyse.txt](https://github.com/user-attachments/files/17938309/postgresql-explain-analyse.txt)

**Environment:**
 - CockroachDB version:  v24.2.4
 - Server OS: Linux
 - Client app  `cockroach sql`

```
colm@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/touchy-falcon-3164/defaultdb> select version();
                                                  version
-----------------------------------------------------------------------------------------------------------
  CockroachDB CCL v24.2.4 (x86_64-pc-linux-gnu, built 2024/10/14 17:20:56, go1.22.5 X:nocoverageredesign)
(1 row)     sql nodes: n1
            kv nodes: n2
Time: 9ms total (execution 0ms / network 8ms)
```

**Additional context**
This is a scenario I have created for testing, but it accurately describes a real problem I am seeing in production. While CockroachDB has JSON support, I am concerned about the performance of tables that use JSON datatypes in practice.

Jira issue: CRDB-44969

**Comment by mgartner** [comment]
Thanks for the report. One thing to point out that is confusing in inverted index scans in  `EXPLAIN` is that the row counts are not referring to logic row counts. They are instead the counts of inverted index keys scanned. Each logical row in the table can have multiple inverted index keys. So it is expected that additional filters will scan over and produce more physical keys.

When filtering with two or more filters, scanning for multiple keys can be detrimental to performance, especially when one or more of the keys is not very selective. #131784, which will be included in v24.3.0 addresses this by trying to plan scans over just the most selective keys. Using your same setup, this leads to a measurable improvement in the query below:

```sql
SELECT COUNT(*) FROM test WHERE doc->'flag1' = 'true'::JSONB AND doc->'string2' = '"testb0"'::JSONB;
-- v24.2.4: 43ms, scan actual row count: 54,347
-- v24.3.0: 34ms, scan actual row count:  4,347
```

However, there is a trade-off with this approach. The less select filter(s) that is not incorporated into the scan still needs to be applied after the scan. However, the inverted index scan doesn't produce the logical value of the indexed column—it only produces part of the indexed value that matches the scan's span(s). So in order to apply the less selective filter(s), we must fetch the entire column value from the primary index. The index join that performs this fetch can have a high cost, especially as the number of fetched rows increases.

You can see this trade-off in your last query. The change in #131784 actually caused a regression in performance. Less rows are scanned but it doesn't make up for the additional overhead of the index join.

```sql
SELECT COUNT(*) FROM test WHERE doc->'flag2' = 'true'::JSONB AND doc->'string2' = '"testb0"'::JSONB AND doc->'string1'  = '"testa0"'::JSONB;
-- v24.2.4: 16ms, scan actual row count: 16,386
-- v24.3.0: 78ms, scan actual row count:  4,347
```

I created #136854 to track this regression. I think that's the only action item here, so I'll close this ticket. I'm happy to answer any further questions you have—just reply here, in the other ticket, or open a new one. Thanks again for the report!
