### ISSUE TITLE
Instrumenting / Tracing CockroachDB with Opentracing

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#13682]
In the light of the performance effort you are going through at the moment, I was wondering if had considered using something like http://opentracing.io/ to instrument/trace CockroachDB ? Given the distributed nature and the layer approach of CockroadDB, it seems like it could be a good idea.

People building app with CockroachDB could also use opentracing and have a full picture of what is happening within their whole stack. There is even an OpenTracing Tracer implementation for GCloud StackDriver.

**Comment by tlvenn** [comment]
![opentracing_io](https://cloud.githubusercontent.com/assets/3340262/23153618/8e630d72-f844-11e6-9116-3e569940848b.jpg)

That made me laugh ;) So looks like it's already taken care of :)

**Comment by tschottdorf** [comment]
Hi Christian,

yep, CockroachDB is indeed using OpenTracing already. 😀
Try it out -- I'd be curious to hear whether it gives you the info you're looking for.

**Comment by andreimatei** [comment]
If you have a lightstep account, you can start crdb with the `COCKROACH_LIGHTSTEP_TOKEN=<xxx>` env var, and you'll get distributed traces in Lightstep. Otherwise, opentracing is also what `EXPLAIN TRACE (SELECT ...)` uses to gather its results. We're also working on niftyer built-in query tracing capabilities.

**Comment by tlvenn** [comment]
awesome, thanks for the additional info @andreimatei !
