### ISSUE TITLE
sql,distsql: inconsistent aggregation results with DistSQL

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13689]
I am seeing a few aggregation logic tests occasionally fail when DistSQL is enabled on a 3 node cluster (with fake span resolver). This happens both with and without the apd change #13551.

```
query RRR
SELECT VARIANCE(x), VARIANCE(y::decimal), VARIANCE(z) FROM xyz
----
9.00 4.5 6.333333333333333
We get:
9.00 4.5 6.333333333333334  
```
This comes just from STDDEV/VARIANCE processing arguments in a different order. Indeed, we can reproduce on regular sql using:
```
SELECT VARIANCE(x), VARIANCE(y::decimal), VARIANCE(z) FROM (SELECT x,y,z FROM xyz ORDER BY random())
```

This is an incorrect<sup>1</sup> result. I think that whatever output precision `p` we want for the result, `decimalVarianceAggregate` must use higher precision for its internal calculations (e.g. `p + 3`). Technically we may need something like `p + O(log count)` - we could increase the precision of the internal calculations as the count increases.

Another one is:
```
query RRR
SELECT STDDEV(x), STDDEV(y::decimal), STDDEV(z) FROM xyz
----
3  2.121320343559643  2.516611478423583
We get:
3  2.121320343559643  2.5166114784235836
```

Here we have an inconsistency in the number of decimals we output, and the result is also incorrect, the following decimal should be `2` not `6` (the correct result is: `2.51661147842358323241...`).

CC @mjibson @nvanbenschoten @knz

[1]: It can be argued that this is not incorrect, just "imprecise". My point of view is that we are choosing how many decimals to output; if we only compute to 14 accurate decimals, we should output just 14..  In this sense if the true value is `1.242`, it's imprecise but not incorrect to output `1.24`, but it's incorrect to output `1.23` or `1.25`.  Of course things that are on the "edge" like `1.25499xy..` or `1.25000xy..` could go either way - both `1.25` and `1.26` are correct.. I don't quite know what the formal guarantee should be.

**Comment by knz** [comment]
It's a bug, and it's bad :)

**Comment by mjibson** [comment]
I'll work on this after the apd branch gets in.

**Comment by RaduBerinde** [comment]
Note that PR #13706 temporarily comments out these tests; they should be re-enabled when the issue is fixed.

**Comment by mjibson** [comment]
These kinds of functions are, in the decimal spec we implement, allowed to have 1ulp (one unit in last place) of error and still be considered correct. This covers the 1.25 vs 1.25499999 case you describe and allows the implementation to correctly return either. Our solution could do something similar.

Looking at this, the problem is in both the decimal and float implementations. I've been thinking about solutions to this for a while and I can't come up with one that scales well. There's a simple solution to add 1 internal precision every 9 `Add` calls, which would prevent the last displayed digit from changing, but this doesn't scale well at all.

I don't understand how the `log(count)` solution would work either. I get the idea behind it, which is that every 10, then 100, then 1000, etc `Add` calls the precision increases which means it would take that many more to change the last displayed digit. But this doesn't work because in order to achieve that you have to clear the results past the last displayed digit, but that changes the result, so you can't do that either.

I think a good solution for now is to just use a context with the desired precision + 3, which will work pretty well. You would have to have 1000 `Add` calls in a row all with worst case data for this to produce the errors above, I think. I believe the float implementation will have to use big.Float to fix this.

**Comment by RaduBerinde** [comment]
> These kinds of functions are, in the decimal spec we implement, allowed to have 1ulp (one unit in last place) of error and still be considered correct. This covers the 1.25 vs 1.25499999 case you describe and allows the implementation to correctly return either. Our solution could do something similar.

This makes sense. But there has to be some caveat to the "1ulp" allowance no? It should be disallowed, for example, to add 1.1 and 2.2 and get 3.3000001. Or if we work with money (2-digit decimals), to add 6.50 + 2.50 and get 8.99.

> I don't understand how the log(count) solution would work either. I get the idea behind it, which is that every 10, then 100, then 1000, etc Add calls the precision increases which means it would take that many more to change the last displayed digit. But this doesn't work because in order to achieve that you have to clear the results past the last displayed digit, but that changes the result, so you can't do that either.

I'm not understanding what you are saying here, let me just be more explicit about what I had in mind. Let's say we do all the calculations with `X` digits after the decimal point (I realize this isn't quite the same as "precision"): every time we add and retain only `X` digits, we potentially add an error of at most `10^-X`. If we do this `N` times, the total error is at most `N * 10^-X = 10^(log10(N)-X)`. So if we want e.g. 15 digits of precision after the decimal point, we need to use `X = 15 + log10(N)` and round down the final sum to 15 digits.

Now since we don't know `N`, the idea would be to increase `X` as `N` increases. Meaning that the first `N1` operations would have some precision `X`, the following `N2` would have precision `X+1` and so on. The total error here is harder to calculate, it's something like `N1*10^(-X) + N2*10^-(X+1) + ..` but based on it we can come up with a formula for N1, N2. (they will likely be close to, but smaller than 10, 100, 1000).

There is another dimension of difficulty w.r.t precision vs number of digits after the decimal point. The same reasoning might apply directly but it's definitely harder to think about it.
