### ISSUE TITLE
sql/mr: investigate why setting zone config extension requires a RF of 8 for zone_survival

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#136860]
We can start a cluster:

```
cockroach demo --nodes=30 \
--demo-locality=region=NA_NE:region=NA_NE:region=NA_NE:region=NA_NE:region=NA_NE:region=NA_MW:region=NA_MW:region=NA_MW:region=NA_MW:region=NA_MW:region=NA_NW:region=NA_NW:region=NA_NW:region=NA_NW:region=NA_NW:region=IN:region=IN:region=IN:region=IN:region=IN:region=ID:region=ID:region=ID:region=ID:region=ID:region=CN:region=CN:region=CN:region=CN:region=CN
```

Then we can create our DB:
```
DROP DATABASE IF EXISTS mrdb;
CREATE DATABASE IF NOT EXISTS mrdb;
USE  mrdb;

ALTER DATABASE mrdb SET PRIMARY   REGION "NA_NE";
ALTER DATABASE mrdb ADD           REGION "NA_MW";
ALTER DATABASE mrdb ADD           REGION "NA_NW";
ALTER DATABASE mrdb ADD           REGION "IN";
ALTER DATABASE mrdb ADD           REGION "ID";
ALTER DATABASE mrdb ADD           REGION "CN";
```

Now we want the following setup for data domiciling. We want 5 replicas in each region. We want regional survival in the US region. Zone survival is sufficient in the other regions (IN, ID, CN).

We use zone config extensions:
```
ALTER DATABASE mrdb ALTER LOCALITY REGIONAL IN "NA_NE" CONFIGURE ZONE USING
    num_replicas = 5,
    num_voters = 5,
    constraints = '{+region=NA_NE: 2, 
                    +region=NA_MW: 1, 
                    +region=NA_NW: 2}',
    lease_preferences = '[[+region=NA_NE], [+region=NA_NW]]';
ERROR: zone config extension cannot set num_replica 5 that is lower than the one required for the survival goal: 8 with goal ZONE_FAILURE
```

Question 1: Why is the error saying we need num_replica=8 for ZONE_FAILURE? Shouldn't zone failure only require RF=3?

If we try to do regional failure.

```
ALTER DATABASE mrdb SURVIVE REGION FAILURE;
```
And then try and run the zone config extension changes again, the error message changes

```
ALTER DATABASE mrdb ALTER LOCALITY REGIONAL IN "NA_NE" CONFIGURE ZONE USING
    num_replicas = 5,
    num_voters = 5,
    constraints = '{+region=NA_NE: 2, 
                    +region=NA_MW: 1, 
                    +region=NA_NW: 2}',
    lease_preferences = '[[+region=NA_NE], [+region=NA_NW]]';
ERROR: zone config extension cannot set num_replica 5 that is lower than the one required for the survival goal: 7 with goal REGION_FAILURE
```

Question 2:  Why is the error saying we need num_replica=7 for REGION_FAILURE? Shouldn't region failure only require RF=5? Also how come surviving REGION_FAILURE requires less replicas than zone failure?

Jira issue: CRDB-45278

**Comment by dikshant** [comment]
I traced the error message to
https://github.com/cockroachdb/cockroach/blob/30ea1ee6b2927fb1947a3bf98a6e29b86861eebc/pkg/sql/catalog/multiregion/region_config.go#L190

**Comment by rafiss** [comment]
The calculation for zone survival with default placement is here: https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/region_util.go#L321-L326

`numVotersForZoneSurvival` is always 3, since if a zone in the primary region fails and a voter is lost, we want to make sure there still is a quorum of voters in the primary region.

So with 6 regions like we have in the example given, we end up with a result of `numReplicas = 3 + (6-1) = 8`.

---

The calculation for region survival is here: https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/region_util.go#L332-L342

`numVotersForRegionSurvival` is always 5. However, not all of those voters are going to be in the primary region. We actually want the other voters distributed throughout the other regions, so that if a region goes down, there still are enough voters in other regions. The number of voters in the primary region is `maxFailuresBeforeUnavailability(5) = 2`

So with 6 regions in the database, we end up with a result of `numReplicas = 2 + (6-1) = 7`.

---

The intuitive way to think of this is that when the region survival goal is being used, we actually want to spread the voters across the other regions rather than keeping them in the primary region like we need to do with zone survival.
