### ISSUE TITLE
sql: probably shouldn't allow BIT(n) greater than BIT(64)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13791]
You can define a `bit(n)` column with a bit limit higher than 64:

```
root@:26257/test> CREATE TABLE bits (a BIT(100));
CREATE TABLE
```

However, we check that inserted values are not larger than 64-bit signed ints:

```
root@:26257/test> INSERT INTO bits VALUES (9223372036854775808);
pq: value type decimal doesn't match type INT of column "a"
```

Given that we have that implicit limit, it seems misleading to let users define `bit(65)` and up.

@nvanbenschoten, @knz

**Comment by knz** [comment]
I have two remarks, and I'm not sure the title of this issue report is capturing what's going on really.

1) setting a maximum bit width larger to 64 (for example 100) is not incorrect because the bit limit will be enforced correctly: all values you will restrict to that maximum width are guaranteed to fit in that number of bits. (That is the definition of the maximum width. *how* this maximum width is enforced is not part of the definition. Here it just so happens the maximum width is enforced by virtue of `int` never being larger than 64 bits, but that specific reason is inconsequential to the general definition of "maximum bith width"). Perhaps this can be clarified by developing the definition of "maximum width" further in the doc.

2) we have automatic typing rules for numeric literals. These are explained in the blog post on typing, but also in the section on [numeric literals](https://www.cockroachlabs.com/docs/sql-constants.html#numeric-literals) of the docs: "any numeric value entered with a value outside of the range of -2^63..2^63-1 (#1123) gets type FLOAT or DECIMAL", so certainly not INT or BIT.

3) so in effect the example here is trying to add a DECIMAL value to an INT column, which is (correctly) disallowed.

**Comment by knz** [comment]
Fixed with the new BIT type.
