### ISSUE TITLE
stability: zero QPS for 2 minutes during block_writer and photos tests

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#13880]
In the last week, [a nightly photos test](https://teamcity.cockroachdb.com/viewLog.html?buildId=165980&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours&tab=buildLog#_focus=2015) and [a nightly block_writer test](https://teamcity.cockroachdb.com/viewLog.html?buildId=160766&buildTypeId=C_BW_4Nodes_6Hours&tab=buildLog#_focus=1597) failed because no queries were executed in a 2 minute period.

For the `block_writer` test, [node.0](https://teamcity.cockroachdb.com/repository/download/C_BW_4Nodes_6Hours/160766:id/node.0/cockroach.stderr) reports these warnings:

```
W170224 07:24:14.198263 1911925 kv/dist_sender.go:1173  [n1] have been waiting 1m0s sending RPC for batch: 1 Gc
W170224 07:24:14.660881 795 kv/dist_sender.go:1173  [client=127.0.0.1:37332,user=root,n1] have been waiting 1m0s sending RPC for batch: 1 CPut, 1 BeginTxn, 1 EndTxn
W170224 07:24:14.661846 723 kv/dist_sender.go:1173  [client=127.0.0.1:37322,user=root,n1] have been waiting 1m0s sending RPC for batch: 1 CPut, 1 BeginTxn, 1 EndTxn
W170224 07:24:14.661966 763 kv/dist_sender.go:1173  [client=127.0.0.1:37336,user=root,n1] have been waiting 1m0s sending RPC for batch: 1 CPut, 1 BeginTxn, 1 EndTxn
...
```

[node.2](https://teamcity.cockroachdb.com/repository/download/C_BW_4Nodes_6Hours/160766:id/node.2/cockroach.stderr) has more interesting log messages. First, a string of these:

```
I170224 07:23:13.743752 63 storage/replicate_queue.go:228  [replicate,n3,s3,r3/3:/Table/1{1-2},@c420180000] snapshot failed: r3: remote declined snapshot: reservation rejected
I170224 07:23:13.800277 63 storage/replica_raftstorage.go:414  [replicate,n3,s3,r3/3:/Table/1{1-2},@c420180000] generated preemptive snapshot b6ddef56 at index 80
```

then these:
```
W170224 07:24:14.672990 399 kv/dist_sender.go:1173  [client=127.0.0.1:49428,user=root,n3] have been waiting 1m0s sending RPC for batch: 1 CPut, 1 BeginTxn, 1 EndTxn
W170224 07:24:14.682280 436 kv/dist_sender.go:1173  [client=127.0.0.1:49432,user=root,n3] have been waiting 1m0s sending RPC for batch: 1 CPut, 1 BeginTxn, 1 EndTxn
...
```

Meanwhile, [node.4](https://teamcity.cockroachdb.com/repository/download/C_BW_4Nodes_6Hours/160766:id/node.3/cockroach.stderr) reports:

```
W170224 07:24:26.665226 455239 storage/replica.go:1115  [n4,s4,r11/3:/{Table/51/1/6…-Max},@c424e78e00] have been waiting 1m0s attempting to acquire lease
W170224 07:24:26.665255 455292 storage/replica.go:1115  [n4,s4,r11/3:/{Table/51/1/6…-Max},@c424e78e00] have been waiting 1m0s attempting to acquire lease
W170224 07:24:26.665267 455200 storage/replica.go:1115  [n4,s4,r11/3:/{Table/51/1/6…-Max},@c424e78e00] have been waiting 1m0s attempting to acquire lease
```

Unfortunately, I don't see any similar smoking guns for the `photos` test. So, that may actually be a different issue.

**Comment by cuongdo** [comment]
Assigning to @petermattis for triage

**Comment by cuongdo** [comment]
Another `photos` test failure here:

https://teamcity.cockroachdb.com/viewLog.html?buildId=167476&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours&tab=buildLog

**Comment by a-robinson** [comment]
So I just started looking at this today, and unfortunately the node logs from the original occurrences have been garbage collected or otherwise lost. There was one recent photos failure still with logs around](https://teamcity.cockroachdb.com/viewLog.html?buildId=177639&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours&tab=buildResultsDiv), but it's no more informative about the issue than the excerpts you collected originally.

The only interesting bits in the photos logs are a number of very large backward time jumps while the nodes were initializing and connecting to each other:

* Node 1 saw backward jumps of .30s and .50s, spaced almost exactly 20s apart
* Node 2 saw backward jumps of .59s, .62s, .63s, .63s, and .63s all very precisely spaced out from each other (10s, 10s, 5s, and 5s apart, respectively)
* Node 3 saw backward jumps of 62s, .81s, .82s, and .82s all spaced almost exactly 5s apart
* Node 4 didn't see any backward jumps

I'm not sure what to make out of all of these or whether they're related to the inability to serve requests. The jumps happened before requests stopped being served, and none of them seem to have caused crashes, although the delays between each node getting its node ID allocated and logging the "node has connected to cluster via gossip" are surprisingly large.

It'd be nice to see an instance of this without all the clock jumps, but at the same time I don't think there's enough logging to really tell what's going on. @petermattis, have you thought at all about enabling easier debugging of clusters that are no longer running? There are easy things we can do, like logging which range each slow request is blocked on, but there are also potentially more involved things we could do, like periodically polling and logging some of the signals that we've built for the admin UI and debug pages that otherwise would go unlogged (e.g. unavailable ranges, leader-not-leaseholder, etc.).

**Comment by petermattis** [comment]
> have you thought at all about enabling easier debugging of clusters that are no longer running?

I've thought about it briefly, but don't have anything concrete. We do have metrics for unavailable ranges, leader-not-leaseholder, etc. I wonder if we should add a mode where we periodically log the metrics to a file.

**Comment by cuongdo** [comment]
Update: this hasn't happened in > 2 weeks

Do we have any reason to suspect that this has been fixed?

**Comment by petermattis** [comment]
> Do we have any reason to suspect that this has been fixed?

I don't know what was causing the problem originally, so difficult to say. It is certainly possible that something was fixed.

**Comment by cuongdo** [comment]
I wonder if this went away after various clock issues were fixed. In any case, I'm closing this as currently unreproducible.
