### ISSUE TITLE
update our handling of stack traces for Go's mid-stack inlining proposal

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13920]
From https://docs.google.com/presentation/d/1Wcblp3jpfeKwA0Y4FOmj63PW52M_qmNqlQkNaLj0P5o/edit#slide=id.p

> Avoid FuncForPC, use CallersFrames

(Scheduled for Go 1.9)

**Comment by tamird** [comment]
I looked at this briefly, I think we already do the right thing here.

**Comment by knz** [comment]
Just checked with `git grep 'runtime\.Callers'`, found this:

```
pkg/storage/track_raft_protos.go:               numCallers := runtime.Callers(0, pcs)
pkg/storage/track_raft_protos.go-               if numCallers == len(pcs) {
pkg/storage/track_raft_protos.go-                       panic(fmt.Sprintf("number of callers %d might have exceeded slice size %d", numCallers, len(pcs)))
pkg/storage/track_raft_protos.go-               }
pkg/storage/track_raft_protos.go-               for _, pc := range pcs[:numCallers] {
pkg/storage/track_raft_protos.go-                       funcName := runtime.FuncForPC(pc).Name()
```

**Comment by tamird** [comment]
Ah, thanks. I'll fix this.

**Comment by bdarnell** [comment]
#13941 removes all uses of runtime.Callers, but we still have some [uses of runtime.FuncForPC](https://github.com/cockroachdb/cockroach/search?q=funcforpc&type=Code&utf8=%E2%9C%93), which is the function named in the presentation. Do those still need to be fixed, or was the presentation wrong in naming FuncForPC instead of runtime.Callers?

**Comment by tamird** [comment]
The presentation called out iterating over PCs, not FuncForPC specifically,
afaik.
