### ISSUE TITLE
sql: allow rejecting a query if a full table scan is involved

### ISSUE THREAD

**Issue by scode** [cockroachdb/cockroach#13969]
It would be great to support SQL syntax that causes a query to be rejected/fail if it would cause a full table scan to be performed.

For production use cases, in many situations it's always wrong to perform a table scan. This is often known at the time the code is written that executes queries. Yet things like forgetting to add an index or indexing the wrong thing or using slightly incorrect WHERE clauses can happen. It's generally useful for a database to be able to operate in a mode where such queries are rejected, rather than potentially taking down the database and impacting other traffic.

**Comment by knz** [comment]
Thanks for filing this.

Just to clarify: do you want this per query, or for parts of a query? I could see this as an annotation next to each table name involved in a query, that verifies that specific table is not scanned. I can imagine some queries running joins with one join operand scanned fully but where it does not matter because the table is small.

Thoughts?

**Comment by scode** [comment]
I think it's a matter of how far to take it. Being able to reject if there's *any* table scan is definitely useful; many cases are going to exist where there isn't much complicated going on. But of course as you point out, this would not be usable in certain cases where it is intended.

In terms of per-table, one might consider something like Spanner's index directives (https://cloud.google.com/spanner/docs/secondary-indexes) would also work, though it requires specificity in knowing which index would be used.

**Comment by scode** [comment]
As a rule of thumb, automated "magic" that selects indexes can be dangerous in production low latency systems. But on the flip side, forcing the programmer to select exactly which index to use puts more burden on the developer, and in some cases the best index to use may in fact be known better by the database. That said, it's a way of forcing the developer to consciously think about the performance impact of a query.

I'm not sure what's best if going beyond a simple global disallow of table scans. One could go far enough to require a query to specify either an explicit index or explicitly allowing the engine to make a decision on every single table, but eventually that likely pollutes SQL queries to an extent that they're much less readable. I don't have enough experience with complex queries in these sorts of latency critical situations to know how acceptable it would be.

If in doubt, it might be worthwhile to just support the simplest case first and see if users end up wanting more flexibility.

**Comment by bdarnell** [comment]
@scode We do support index hints similar to spanner's: https://www.cockroachlabs.com/docs/select.html#force-index-selection-index-hints.

Let me suggest another way of framing this issue: what we want to prevent is not *scans* but *filtering*. In a well-indexed query, every row that is retrieved from storage is returned to the client; in a poorly-indexed one we may have to read much more data from disk than we return (whether that means doing a full table scan or using an index which is not selective enough). And the cost of filtering is not otherwise visible to the application. If you're doing queries that return 1000 results even though you're only displaying 10, you can notice that at the application layer. But if you filter those records out at the database instead of the application, you can't really tell what's going on except that your queries get slower. 

So how about if we added an option that causes the query to fail if the resulting plan includes a "filter" step?

**Comment by knz** [comment]
That's certainly easier to do.
Although your explanation suggests something else instead: keep track of how many rows are read in at each level of the query plan, and error out if the number of rows in the final result is significantly smaller than the maximum number of rows read in any of the query nodes. Thoughts?

**Comment by bdarnell** [comment]
> Although your explanation suggests something else instead: keep track of how many rows are read in at each level of the query plan, and error out if the number of rows in the final result is significantly smaller than the maximum number of rows read in any of the query nodes. Thoughts?

That would be data-dependent - you could end up with a query that works in testing/development because there are no skipped rows, then it starts failing in production. I think if we're going to do this it should be something that we can check statically before the query execution starts.

**Comment by knz** [comment]
Ack.

will let it simmer and see if we can come up to a good implementation.

**Comment by knz** [comment]
@scode we discussed this internally and we are not planning soon to add a flag that directly prevents a query from running. It would be too much special casing at this stage of our development.

What you can do however is to use our special CockroachDB-specific SQL extension to **filter specific items out of the output of EXPLAIN**.

You would use this as follows:

```sql
> select exists(select * 
                from [explain <yourquery>] 
                where field='spans' and description='ALL') 
         as fullscan
```

For example:
```sql
> select exists(select * 
                from [explain select * from t.kv where v=3] 
                where field='spans' and description='ALL') 
         as fullscan
```
```
+----------+
| fullscan |
+----------+
| true     |
+----------+
(1 row)
```

```sql
> select exists(select * from [explain select * from t.kv where k=3] where field='spans' and description='ALL') as fullscan
```
```
+----------+
| fullscan |
+----------+
| false    |
+----------+
(1 row)
```

Would this be a proper workaround to your requirement to analyze queries?

**Comment by knz** [comment]
Similarly, you can use filtering on the output to EXPLAIN to detect filter stages, as Ben suggested.

**Comment by jordanlewis** [comment]
@RaduBerinde kicking to your team to prioritize or close.

**Comment by RaduBerinde** [comment]
Seems very doable and sounds like it could be useful.

**Comment by knz** [comment]
see #41352 for a discussion on how to inform users

**Comment by awoods187** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/issues/49617#issuecomment-665799491
