### ISSUE TITLE
stability: nightly test gossip failures

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#13983]
Two tests failed after waiting for 2 minutes for the full cluster to be visible in the gossip state:
* https://teamcity.cockroachdb.com/viewLog.html?buildId=172570&buildTypeId=Cockroach_AllocatorTest3to510g
* https://teamcity.cockroachdb.com/viewLog.html?buildId=172573&buildTypeId=C_BW_4Nodes_6Hours

A quick scan of the [3->5 allocator/load test node.2 log](https://teamcity.cockroachdb.com/repository/download/Cockroach_AllocatorTest3to510g/172570:id/allocator_test_logs/node.2/cockroach.stderr) shows these errors early on:

```
W170308 07:13:34.185513 130 storage/store.go:1405  [n3,s3] could not gossip system config: [NotLeaseHolderError] range 331: replica {3 3 3} not lease holder; lease holder unknown
I170308 07:13:34.707229 278 gossip/client.go:131  [n3] started gossip client to rebal-3to5s-happywilliams-cockroach-2:26257
I170308 07:13:34.708890 278 gossip/client.go:138  [n3] closing client to rebal-3to5s-happywilliams-cockroach-2:26257: rpc error: code = 2 desc = duplicate connection from node at {tcp rebal-3to5s-happywilliams-cockroach-3:26257}
```

**Comment by spencerkimball** [comment]
OK, I see what's going on here. We have five nodes. Node 1 has no `--join` host specified, so it stalls in gossip. Node 2 has `--join=node1`, node 3 has `--join=node2`, etc.

What happens is that node 1 takes a fairly long time to come up, as RocksDB processes the data in it (presumably iterating over range descriptors – note that in these tests, we starting new clusters on top of pre-existing data). During the time node 1 is processing, node 2 tries to connect to it via gossip but fails (we now actually close these connection attempts due to @tamird's change b15f64a98b5db1b13f1ac6c0decfe8dd79b72ad9. Meanwhile, node3 connects to node 2, so node 2 is no longer stalled in gossip and doesn't bother trying to connect to node 1.

So node 1 remains dormant throughout the test and it times out.

**Comment by spencerkimball** [comment]
A simple fix would be to make sure that every node has a `--join` specified.

**Comment by tamird** [comment]
Another solution would be to start servicing heartbeat RPCs ahead of the RocksDB scan, but that would require much rejiggering.

The subtlety here is a result of us *not* using `grpc.WithBlock` which causes grpc to retry indefinitely. Normally, we'd see the connection refused on the `Dial` call and this issue would surface even before b15f64a, but here we are.
