### ISSUE TITLE
sql: `SELECT 'decimal(18,2)'::regtype::oid` no worky

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#13993]
Discovered when adding a default value to a column in a rails app:
```
    create_table :orders do |t|
      t.decimal :subtotal, precision: 18, scale: 2, null: false, default: 0
    end
```

Somehow, this resulted in AR issuing the query:
```
SELECT 'decimal(18,2)'::regtype::oid
```
which came back with
```
PG::InternalError: ERROR:  type 'decimal(18,2)' does not exist
```

This query works in PG.

I've also confirmed that `decimal(18,2)` is indeed a type in CRDB:
```
root@:26257/company_activerecord> CREATE TABLE foo (id int, value decimal(18,2));
CREATE TABLE
root@:26257/company_activerecord> select * from foo;
+----+-------+
| id | value |
+----+-------+
+----+-------+
(0 rows)
```

**Comment by tamird** [comment]
The query reported here still doesn't work. Note that #14030 added a test for `SELECT 'numeric(10,3)'::REGTYPE`, but the query mentioned here is `SELECT 'decimal(18,2)'::regtype::oid`.

Looks like `decimal` is missing as an alias of `numeric`, somewhere.

**Comment by jordanlewis** [comment]
Hmm, this is troublesome. Up until now, it's been sufficient to have entries in `pg_type` with the Postgres type names - e.g. `numeric` instead of `decimal` - because many ORMs seem to either have those names hardcoded or have their corresponding OIDs hardcoded.

Now, since ActiveRecord seems to want to use the CockroachDB-native type names in its OID casts, we would need to duplicate those rows in `pg_type` that have differences in their type names between CockroachDB and Postgres. The trouble is that doing so would violate the unique constraint on the OID column in that table, which would break other assumptions.

The way out that I see is to introduce more special logic to the `regtype` cast method that first translates CockroachDB type names to their Postgres equivalents, but that's pretty messy. Do you have any thoughts on this, @nvanbenschoten?
