### ISSUE TITLE
storageccl: tmp files written outside data-dir

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14021]
Currently our ExportStorage implementations for the various cloud storage providers require writing temp files to disk before uploading them. Right now, those files are allocated using go's `os.TempDir` with no prefix, meaning they use the system tempdir (i.e. /tmp).

Operators already configure nodes with one or more directories to store files in though, and may not expect their data to be written elsewhere -- potentially with different access control, permissions, storage allocation/quotas, io capacity, etc.

A simple heuristic might be to just use the first store's data dir, but eventually we might want to use all of them / whichever has most available space?

**Comment by dt** [comment]
After discussion with @bram:
* We should add a GetTmpDir to node that picks the store with most free space
* we should `mkdir tmp` in data dir and then alloc tmpdirs _under that_ to make it easy to blow away en masse without worrying about the ssts along side it.

**Comment by dt** [comment]
@BramGruneir so this is easy enough for the replicaCmd, where I have `Replica` and thus a `Store`, but in sql-land I can't really count on even having a Store on the node. I guess I could have a `DefaultTempDir` pkg-level somewhere and then we set it to the first store's tmpdir?

**Comment by bdarnell** [comment]
We originally noticed this because we were leaking temporary files. Once that's fixed and we clean up after ourselves, I think it's reasonable to prefer the default `$TMPDIR` instead of a directory under our store. We should be able to assume enough space in `$TMPDIR` for temporary copies of a few ranges, and if that's not available it's easy for the admin to fix. 

It may be desirable to specifically separate temp file storage from the main store. It reduces the performance impact that backups have on regular traffic, and in the event of a crash that leaves temporary files behind, they'll be in a place where there is likely to be an existing process that will clean them up (instead of letting them accumulate indefinitely in `cockroach-data/tmp`).

**Comment by dt** [comment]
@bdarnell eh, i'm still somewhat uncomfortable writing unencrypted data outside the path the operator specified -- they could be assuming full-disk encryption or other security measures, or other capacity/performance provisioning.

w.r.t. to io device capacity, I think when we see that is when we dig in to named pipes, custom rocksdb env or other disk-less transport options, rather than hoping TMPDIR happens to be a different device?

**Comment by bdarnell** [comment]
Encryption is a good point, although it seems like running with full-disk encryption on one disk but still leaving `$TMPDIR` unencrypted is asking for trouble. Encrypting these temporary files is also very easy (as easy as crypto ever gets), since we control the writer and reader and it's all in the same process. Just generate a symmetric key in memory. (we'd only be able to do this with truly temporary files that are destined to be read back and uploaded to the cloud; the ones that get renamed into place when they're done will need to be written unencrypted)

For performance you're right that we'll probably want to get disk out of the loop completely. But there's still the question of who cleans up temporary files after a crash.

**Comment by danhhz** [comment]
Closing as we no longer use temp files in backup/restore.
