### ISSUE TITLE
UI: fail to show table information if the table name is upper case

### ISSUE THREAD

**Issue by masayoshi-louis** [cockroachdb/cockroach#14056]
Please describe the issue you observed:

- What did you do?
1. Execute the following SQL:
  CREATE database test1;
  SET database = test1;
  CREATE TABLE T1 (k INT PRIMARY KEY);
  CREATE TABLE t2 (k INT PRIMARY KEY);
2. In the admin UI
  In "DATABASES" tab, database "test1", click table "T1".

- What did you expect to see?
The information of the table "T1" including the DDL to create this table.

- What did you see instead?
"No results."

**Comment by xphoniex** [comment]
Upper case tables wouldn't work because the table name is transformed into lower case before it's inserted into system.namespace `line 30: pkg/sql/sqlbase/keys.go`

Hence why on API end points, you'll encounter `namespace T1 with ParentID 50 not found` error

Can we change the normalize function @tamird ?

**Comment by tamird** [comment]
@xphoniex that doesn't seem like the right solution to me, not least because it will it break existing stored tables. I guess we just need to normalize the table name the same way when it comes in from the UI.
