### ISSUE TITLE
Build failure with git 1.7.1 on CentOS

### ISSUE THREAD

**Issue by kkaneda** [cockroachdb/cockroach#1409]
@jusongchen wrote:

I followed CONTRIBUTING.md to build cockroach from source code on a CentOS 6.5 box with git 1.7.1 installed. All worked well except that the cmd 'make build' hanged after 'golang.org/x/tools' compiled.

Further tracking found that 'gopkg.in/yaml.v1' package (which is right after golang.org/x/tools) causes git 1.7.1 to hang.

The workaround is to run the following command then run 'make build':
git clone https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v1

**Comment by bdarnell** [comment]
According to https://groups.google.com/d/msg/golang-nuts/RKz9ASmJm3o/DEG-DdR-o5YJ, the relevant bug was fixed in [git 1.7.3.4](https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.3.4.txt) in 2010. We should just require a reasonable version of git instead of documenting workarounds to build with an ancient one. Using CentOS is no excuse; if you can install go 1.4 then you can install git 2.0.

**Comment by kkaneda** [comment]
Ah, I see. git 1.8 or above would be good? https://github.com/cockroachdb/cockroach/pull/1412
