### ISSUE TITLE
server: debug endpoint with list of ranges with zone config constraint violations

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14113]
This will help a lot with rebalancing and diagnosing issues

We should have both a status endpoint so the ui can grab it, and add it as a part of a list of troubled ranges.

**Comment by cuongdo** [comment]
@BramGruneir by "constraint violation" do you mean zone config constraint violations? (as opposed to SQL constraint violations)

**Comment by BramGruneir** [comment]
Exactly.

**Comment by a-robinson** [comment]
+1 to this, and we may want event want it to be more prominent than just a debug endpoint. It'll help users track whether or not their zone config changes have finished, which is becoming more important with partitioning.

**Comment by dianasaur323** [comment]
@BramGruneir how long do you think this will take? I'm asking so that we can properly allocate projects so that you don't get overloaded with things not reflected in Airtable. One thing that I wanted to mention is that going into 1.3 and 1.4, it's likely that we'll start pulling these "alerts" out to surface in the admin UI and cluster viz, so to the extent that you could make this more extensible, that would be great!

**Comment by cuongdo** [comment]
Assigning to @benesch, who's already working on zone config changes needed for partitioning. As discussed in person, I think that some form of this (a page or a count of constraint violations) would be helpful for usability of partitioning.

**Comment by dianasaur323** [comment]
@vilterp perhaps worth you staying in the loop on this issue for the admin UI work you are doing

**Comment by knz** [comment]
@tbg I think this is a KV issue not admin UI.

**Comment by tbg** [comment]
@andreimatei what's left of this now that we have the constraint conformance reports?

**Comment by knz** [comment]
Let's call this done with the constraint conformance report.

@irfansharif may have an opinion about the "next best thing" if we're moving to a new constraint system.
