### ISSUE TITLE
cli: add command for generating an haproxy.cfg

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14194]
Add a `cockroach gen-haproxy` command for generating an `haproxy.cfg` for a cluster. The command would grab the list of nodes from the cluster and generate an `haproxy.cfg` with reasonable defaults.

**Comment by jseldess** [comment]
Nice! I'm getting ready to open a haproxy docs PR. This will make the process way easier.

**Comment by mberhault** [comment]
I haven't touched haproxy yet. @petermattis, @arjunravinarayan, are there any specific things to note about the denim config?
the current denim haproxy.cfg is:
```
global
  maxconn 4096
  pidfile /tmp/cockroach-loadbalancer.pid

defaults
    mode                tcp
    log                 global
    option              dontlognull
    retries             2
    timeout connect     10s
    timeout client      5s
    timeout server      2m
    maxconn             4096

listen psql
    bind 0.0.0.0:27183
    mode tcp
    balance roundrobin
    server cockroach1 cockroach-denim-0001:26257
    server cockroach2 cockroach-denim-0002:26257
    etc...
```

**Comment by arjunravinarayan** [comment]
No, this is a fairly barebones haproxy (and I set those timeout values without firm precedent to guide me). All that really needs to happen is for a `server ...` line to be added for each cluster node. We aren't doing health checks or anything else right now.

**Comment by jseldess** [comment]
@arjunravinarayan, when we talked through haproxy, we landed on these timeout settings:

```
timeout connect     10s
timeout client      1m
timeout server      10s
```

Though I don't understand exactly why these are better than what's on denim. 

- I think we increased `timeout client` because our built-in sql client doesn't send keep alive packets, so when testing with that, the connection was restarting a lot...? Not sure if this is a concern for production scenarios, though.
- I don't remember why we reduced `timeout server`, but the [haproxy docs](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-timeout%20server) do say: 
  > In TCP mode (and to a lesser extent, in HTTP mode), it is highly
recommended that the client timeout remains equal to the server timeout in
order to avoid complex situations to debug.

**Comment by arjunravinarayan** [comment]
What you have is better than what's currently on denim. The short client timeout is not causing a problem because the ycsb workers hammer the connections continuously, so they never get dropped. But this would not be the case for other workloads, so we should stick to the 1 minute client timeout. I think we should stick to the symmetric client/server lengths as haproxy recommends that.

**Comment by mberhault** [comment]
@jseldess: the `gen haproxy` command is in.
It needs to be told how to reach the cluster (much like the nodes/quit/freeze commands) and an output file (or "-" for standard out).
eg:
```
$ cockroach gen haproxy --host=indigo.crdb.io --ca-cert=ca.crt --cert=root.crt --key=root.key --out output.cfg
$ cat output.cfg
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26257
    mode tcp
    balance roundrobin
    server cockroach1 cockroach-indigo-0001.crdb.io:26257
    server cockroach2 cockroach-indigo-0003.crdb.io:26257
    server cockroach3 cockroach-indigo-0004.crdb.io:26257
    server cockroach4 cockroach-indigo-0006.crdb.io:26257
    server cockroach5 cockroach-indigo-0005.crdb.io:26257
    server cockroach6 cockroach-indigo-0009.crdb.io:26257
    server cockroach7 cockroach-indigo-0007.crdb.io:26257
    server cockroach8 cockroach-indigo-0008.crdb.io:26257
    server cockroach9 cockroach-indigo-0002.crdb.io:26257
```

The default file is `haproxy.cfg`. haproxy can then be run with:
`haproxy -f haproxy.cfg`

With more experience, we may tweak the generated config, this one is fairly minimal.

**Comment by jseldess** [comment]
Great. Thanks, @mberhault.
