### ISSUE TITLE
sql: schema changes in SQL transactions don't make sense

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14280]
Currently we allow CREATE, DROP, RENAME TABLE inside a sql txn (e.g. BEGIN, CREATE TABLE, COMMIT), but doing so has some confusing semantics, namely many schema changes need to wait at points for cached older versions of schemas to expire (i.e.`waitForOneVersion`), but those caches do not start to expire until newer versions are committed.

Having some schema changes appear to work inside a txn while others mysteriously fail (or hang) is confusing. Should we just error if a schema change is attempted in a (non-implicit) txn?

**Comment by knz** [comment]
I concur!

We need schema leases.

**Comment by bdarnell** [comment]
I'm fine with disallowing schema changes inside transactions (with the exception of temporary tables, when we support those). Many other databases do the same thing, although many of them do it by auto-committing any in-progress transaction when a schema change is issued. This seems ugly, but is it perhaps necessary to accommodate client drivers that implicitly start transactions and make it difficult to use a plain statement outside of a transaction?

**Comment by knz** [comment]
What we can do easily is to reject transactions that contain anything else *in addition to* a single schema change statement.

**Comment by knz** [comment]
I wonder however how far we can go by leasing entire schemas (dbs + tables) at a time instead of individual tables.

**Comment by vivekmenezes** [comment]
leasing entire schemas (dbs + tables) at a time seems orthogonal to this issue. As long as you permit caching of descriptors on nodes you will not be able to change them transactionally

**Comment by vivekmenezes** [comment]
We always allow two versions of a descriptor in the system until all nodes have converged to the latest change. After proposing a schema change, it takes time to process and one cannot assume the next statement following the schema change can use the schema change. We do hold the schema change statement until it has completely executed, but that happens in many transactions, and a failure in the sequence results in the rest of the sequence executing on another node.

We can engineer to reduce surprises here (for example we hold the statement until its execution is complete today), but I don't think we can engineer for no surprises :-)

And yes since schema changes are actually executed as many transactions, running more statements after a schema change in the same transaction doesn't make sense.

Let me play with this a bit and see what works well.
