### ISSUE TITLE
sqlccl: BACKUP and RESTORE should return affected row counts

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14296]
listing restored tables and their row counts seems like it'd be nice.

**Comment by benesch** [comment]
@danhhz is #14861 sufficient? It's not quite what's described here.

**Comment by benesch** [comment]
(Ping for tomorrow morning.)

**Comment by danhhz** [comment]
I really do think row counts would be nice. For restore, we're going to have to parse out the interleaved tables anyway to fix https://github.com/cockroachdb/cockroach/issues/14856. On the other hand, if we added it to RESTORE, we would also likely want it in BACKUP to match. And I'm more concerned about the extra parsing there since we want that to be as light as possible.

Tables also would be nice but it feels like we'd want one per row and we're already committed to a status update per row. None of the DDL statements return the affected tables (`DROP TABLE CASCADE` for example). @dt @mjibson thoughts?

**Comment by benesch** [comment]
One benefit of returning the job ID is that it's dead simple to attach more information via a new view in `crdb_internal`:

    SELECT name, schema FROM crdb_internal.job_affected_tables WHERE job_id = $1

What's your expected use case for number of rows? Can we expose a cheaper-to-compute metric instead?

**Comment by danhhz** [comment]
> One benefit of returning the job ID is that it's dead simple to attach more information via a new view in crdb_internal

Good call, we already have this info denormalized into the jobs table. Let's skip including affected tables

> What's your expected use case for number of rows? Can we expose a cheaper-to-compute metric instead?

To match UPDATE/INSERT/DELETE which return the number of rows affected (if you don't specify a RETURNING clause)

**Comment by vivekmenezes** [comment]
I agree that this is nice to have. Do we really need it for 1.1 though? Thanks

**Comment by danhhz** [comment]
This was done in https://github.com/cockroachdb/cockroach/commit/10cd048cb44d7e409ec8836706eb2cd5ad3426b8
