### ISSUE TITLE
sql: unnest panics when used on virtual tables

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#14353]
The following query causes a panic 😢: 

```
SELECT unnest(conkey) FROM pg_constraint;
```

[Backtrace available here.](https://gist.github.com/benesch/b6cf498d259688eba83faec1774eca4a) I extracted the test case from #12785, but I discovered this because I'm adding my own virtual table that has an array I want to unnest.

**Comment by jordanlewis** [comment]
Thanks! Unfortunately this is worse than your issue description makes it out to be, although you wouldn't be able to tell because we don't support storing arrays in physical tables yet.

In reality, none of the set-returning functions work with column references at the moment, because of our deficient support for correlated subqueries and similar constructions. I believe there's already an issue tracking this, but it may not be tracking this panic, so thanks for the report.

**Comment by benesch** [comment]
Closing in favor of #13156—where you describe exactly this issue, including the panic. Thanks for pushing me to search a little harder!
