### ISSUE TITLE
ui: reads are not represented in graphs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#14505]
Bug: Reads aren't visually represented in admin ui graphs, although on hover, the **Total Reads** looks accurate in the tooltip.

In my case, I used `block_writer` to insert data.

<img width="1241" alt="screen shot 2017-03-30 at 9 51 49 pm" src="https://cloud.githubusercontent.com/assets/15893490/24533113/75a3227e-1593-11e7-84f3-b21cca443d60.png">

<img width="1247" alt="screen shot 2017-03-30 at 9 51 27 pm" src="https://cloud.githubusercontent.com/assets/15893490/24533110/713300b0-1593-11e7-8637-d701b7b65eb7.png">

```
~/src/github.com/cockroachdb/cockroach$ grep -F '[config]' cockroach-data/logs/cockroach.log
I170330 21:34:42.923119 1 util/log/clog.go:991  [config] file created at: 2017/03/30 21:34:42
I170330 21:34:42.923119 1 util/log/clog.go:991  [config] running on machine: JESSEs-MacBook-Pro
I170330 21:34:42.923119 1 util/log/clog.go:991  [config] binary: CockroachDB CCL 4ced589 (darwin amd64, built 2017/03/30 17:39:21, go1.8)
I170330 21:34:42.923119 1 util/log/clog.go:991  [config] arguments: [cockroach start]
```

**Comment by dianasaur323** [comment]
@jseldess do you mind confirming if this is still an issue?

**Comment by mrtracy** [comment]
@jseldess so the "100m" label actually means "100 milli", or 0.1; this is a bit confusing, and we've since created a better experience by eliminating fractional prefixes for count graphs (this would now just read 0.1).

So, we would expect to see this graph if there was 1 read every 10 seconds.  Does that match up with your expectation of how many reads there were in this scenario?

**Comment by jseldess** [comment]
Ah, yes, this makes sense now. I just retested, and `0.1` in such a case is a lot clearer. Thanks!
