### ISSUE TITLE
sql: literal values sometimes don't get implicitly converted

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#14527]
There appear to be situations in SQL queries where values will not get implicitly converted to match the column type they're being compared (or assigned) to.

CockroachDB (as of `0499d0d51f0bfb332fd4d69e943812845e9eae99`):
```
root@:26257/> CREATE TABLE d.t (b TIMESTAMP);
CREATE TABLE
root@:26257/> INSERT INTO d.t VALUES ('2015-09-18 00:00:00');
INSERT 1
root@:26257/> SELECT * FROM d.t WHERE b = '2015-09-18 00:00:00';
pq: unsupported comparison operator: <timestamp> = <string>
```

Postgres:
```
template1=# CREATE TABLE t (b TIMESTAMP);
CREATE TABLE
template1=# INSERT INTO t VALUES ('2015-09-18 00:00:00');
INSERT 0 1
template1=# SELECT * FROM t WHERE b = '2015-09-18 00:00:00';
          b
---------------------
 2015-09-18 00:00:00
(1 row)
```

**Comment by nvanbenschoten** [comment]
This issue here is that our untyped literal handling is a little inconsistent for string literals. We made the decision a while ago to treat string literals as resolved string types during overload resolution. This decision was made because it simplified certain logic, avoided ambiguities in a few cases, and allowed a certain class of errors to be more specific.

I have a branch from a while ago that removed this distinction and gave string constants the same treatment as numeric constants during overload resolution. This change addresses cases like this, at the cost of introducing a limitation that we already had for numeric constants (namely, ambiguities in constant coercion between parent expressions). I've rebase the branch and opened up #14593 to make this change because I think this issue demonstrates that the tradeoffs will be worth making. I also like that the change will make string and numeric untyped constants more consistent.
