### ISSUE TITLE
stability: investigate ledger slow performance under contention

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14670]
Moved from https://github.com/cockroachdb/examples-go/issues/101 (I verified this is still happening as of 38c7c5b6f041bdd784bcb5e9e3f97ed54482c80e):

On current master (a092861e47331a2cbd19e98dd69eb34d19196d2d), run the following:

```
rm -rf cockroach-data; ./cockroach start --alsologtostderr # separate terminal
go run $GOPATH/src/github.com/cockroachdb/examples-go/ledger/main.go --concurrency 5 --sources 0 --destinations 1 postgres://root@localhost:26257?sslmode=disable
```

Note that this is a contended workload (on `account_id=0`), essentially five writers running the following: 

```sql
SELECT causality_id, balance FROM accounts `+
		`WHERE account_id = 0 ORDER BY causality_id DESC LIMIT 1;
INSERT INTO accounts (
  posting_group_id,
  amount,
  account_id,
  causality_id, -- strictly increasing in absolute time. Only used for running balance.
  balance
) VALUES (/* touching both account_ids */);
```

You should (or rather, are forced to) see the following type of performance:

```
2017/03/17 02:22:04 5 postings/sec
2017/03/17 02:22:05 0 postings/sec
2017/03/17 02:22:06 0 postings/sec
2017/03/17 02:22:07 7 postings/sec
2017/03/17 02:22:08 48 postings/sec
2017/03/17 02:22:09 28 postings/sec
2017/03/17 02:22:10 36 postings/sec
2017/03/17 02:22:11 39 postings/sec
2017/03/17 02:22:12 8 postings/sec
2017/03/17 02:22:13 0 postings/sec
2017/03/17 02:22:14 0 postings/sec
2017/03/17 02:22:15 0 postings/sec
2017/03/17 02:22:16 0 postings/sec
2017/03/17 02:22:17 0 postings/sec
2017/03/17 02:22:18 0 postings/sec
2017/03/17 02:22:19 0 postings/sec
2017/03/17 02:22:20 0 postings/sec
2017/03/17 02:22:21 0 postings/sec
2017/03/17 02:22:22 0 postings/sec
2017/03/17 02:22:23 1 postings/sec
2017/03/17 02:22:24 0 postings/sec
2017/03/17 02:22:25 0 postings/sec
2017/03/17 02:22:26 0 postings/sec
2017/03/17 02:22:27 0 postings/sec
2017/03/17 02:22:28 0 postings/sec
2017/03/17 02:22:29 0 postings/sec
2017/03/17 02:22:30 0 postings/sec
2017/03/17 02:22:31 0 postings/sec
2017/03/17 02:22:32 0 postings/sec
2017/03/17 02:22:33 0 postings/sec
2017/03/17 02:22:34 0 postings/sec
2017/03/17 02:22:35 0 postings/sec
2017/03/17 02:22:36 0 postings/sec
2017/03/17 02:22:37 0 postings/sec
2017/03/17 02:22:38 0 postings/sec
2017/03/17 02:22:39 0 postings/sec
```

Lowering `--concurrency` I think avoids these really bad stalls, but may only exhibit them less frequently.

I assume these recover, but I haven't checked and am running out of juice.

**Comment by spencerkimball** [comment]
Looks like this particular client application is creating deadlocks as a matter of course. The deadlock detection can take a bit of time, especially when they're 5 deep, as is sometimes the case with `--concurrency 5` specified for the ledger. I'm going to tighten up the checking for that.

I've also found a bug related to pushing the transaction in that we're not updating the `PushTxnRequest.Now` timestamp to the current time, which is a good idea after the txn might have been waiting for longer than the txn heartbeat expiration. But that's not the real problem here.

The real problem seems to be that one of these txns is failing to heartbeat and times out. I've seen various suspicious txn behavior in the unit / stress testing as well that's making me think there's a real bug hiding in here. Still working to find out what's causing it.

**Comment by spencerkimball** [comment]
Found a few more issues. The biggest problem leading to the poor performance was that the pushee's txn was being upgraded to a higher priority and we weren't seeing that. After changing the code around to consolidate the querying of the pusher and pushee together, the performance increases dramatically:

```
2017/04/11 10:11:11 114 postings/sec
2017/04/11 10:11:12 105 postings/sec
2017/04/11 10:11:13 127 postings/sec
2017/04/11 10:11:14 113 postings/sec
2017/04/11 10:11:15 70 postings/sec
2017/04/11 10:11:16 92 postings/sec
2017/04/11 10:11:17 102 postings/sec
2017/04/11 10:11:18 110 postings/sec
2017/04/11 10:11:19 112 postings/sec
2017/04/11 10:11:20 65 postings/sec
2017/04/11 10:11:21 56 postings/sec
2017/04/11 10:11:22 115 postings/sec
2017/04/11 10:11:23 90 postings/sec
2017/04/11 10:11:24 87 postings/sec
2017/04/11 10:11:25 88 postings/sec
2017/04/11 10:11:26 89 postings/sec
2017/04/11 10:11:27 68 postings/sec
2017/04/11 10:11:28 80 postings/sec
2017/04/11 10:11:29 72 postings/sec
2017/04/11 10:11:30 85 postings/sec
2017/04/11 10:11:31 106 postings/sec
2017/04/11 10:11:32 97 postings/sec
2017/04/11 10:11:33 90 postings/sec
2017/04/11 10:11:34 81 postings/sec
2017/04/11 10:11:35 63 postings/sec
2017/04/11 10:11:36 67 postings/sec
2017/04/11 10:11:37 99 postings/sec
2017/04/11 10:11:38 95 postings/sec
2017/04/11 10:11:39 70 postings/sec
2017/04/11 10:11:40 60 postings/sec
2017/04/11 10:11:41 58 postings/sec
2017/04/11 10:11:42 76 postings/sec
2017/04/11 10:11:43 107 postings/sec
2017/04/11 10:11:44 207 postings/sec
2017/04/11 10:11:45 178 postings/sec
2017/04/11 10:11:46 144 postings/sec
```

The variations are due to the exponential backoff. Sometimes we must query for longer dependency cycles to find the deadlocks. I've changed the backoff to start at 10ms and increase by a factor of 1.5 on each subsequent backoff / retry.
