### ISSUE TITLE
sql: decimals operations truncate numbers within the int64 range

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14817]
```
root@:26257/> SELECT ((- 9223372036854775807::BIGINT) - 1) / (- 1);
+--------------------------------+
| ((- 9223372036854775807::BIGINT) - 1) / (- 1) |
+--------------------------------+
|            9223372036854776000 |
+--------------------------------+
(1 row)
```

Because we define `int / int -> decimal`, the decimal code is called but truncates the last few digits.

**Comment by mjibson** [comment]
It's not trivial to just use HighPrecisionCtx here either because then you get 2000 digits in your division. A solution for this needs to have some parity to whatever the other decimal divisions do.

**Comment by mjibson** [comment]
Also note this is the `INT_MIN / -1` case that Go returns `INT_MIN` for, but we don't/won't because we use decimal division. Postgres does:

```
postgres=# select (-9223372036854775807::bigint-1) / -1;
ERROR:  bigint out of range
```

**Comment by mjibson** [comment]
One fix for this is to bump the default precision from 16 to 20. That would affect all inexact decimal operations globally, but maybe that's fine. @knz @eisenstatdavid thoughts?

**Comment by knz** [comment]
It seems to me that because +/- 2^63 has 19 digits that we should have used at least 19 from the beginning -- the fact the default was 16 sounds like a bug. I'd be ok with 20, of course. 

(I would suggest to clarify the issue description -- because you use an explicit cast on the large operand, the cast remains and the entire expression is typed as decimal; there is no int/int operation anywhere, I can only see a decimal/decimal subtraction and division).

**Comment by eisenstatdavid** [comment]
I think that's fine.

**Comment by mjibson** [comment]
The 16 was there because that's what our previous decimal package used, and I thought that's what postgres used. However, in postgres:

```
postgres=# select 1::decimal/3::decimal;
        ?column?        
------------------------
 0.33333333333333333333
```

Which is 20 decimals of `3`s, so I think switching to 20 globally is safe. I'll make this change.
