### ISSUE TITLE
Table not exists when transactions content for a key

### ISSUE THREAD

**Issue by ggaaooppeenngg** [cockroachdb/cockroach#14887]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. 

```
I170413 16:56:55.483776 1 util/log/clog.go:1007  [config] file created at: 2017/04/13 16:56:55
I170413 16:56:55.483776 1 util/log/clog.go:1007  [config] running on machine: gaopengdeMacBook-Pro
I170413 16:56:55.483776 1 util/log/clog.go:1007  [config] binary: CockroachDB CCL unknown (darwin amd64, built , devel +ea7d9e6 Thu Jan 19 23:06:54 2017 +0000)
I170413 16:56:55.483776 1 util/log/clog.go:1007  [config] arguments: [cockroach start]
```

2. Please describe the issue you observed:

- What did you do?
```
package main

import (
	"database/sql"
	"errors"

	_ "github.com/lib/pq"
)

func t() error {
	db, err := sql.Open("postgres", "postgresql://root@localhost:26257?sslmode=disable")
	if err != nil {
		return err
	}
	if _, err := db.Exec("CREATE DATABASE IF NOT EXISTS " + "test"); err != nil {
		return err
	}
	if _, err := db.Exec("SET DATABASE = " + "test"); err != nil {
		return err
	}
	if _, err := db.Exec("CREATE TABLE IF NOT EXISTS kvt (key BYTES PRIMARY KEY, value BYTES)"); err != nil {
		return err
	}
	if _, err := db.Exec("UPSERT INTO kvt VALUES ($1, $2)", []byte("foo"), []byte("bar")); err != nil {
		return err
	}
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	if _, err := tx.Exec("UPSERT INTO kvt VALUES ($1, $2)", []byte("foo"), []byte("bar1")); err != nil {
		return err
	}
	row := db.QueryRow("SELECT value FROM kvt WHERE key = $1", []byte("foo"))
	var v []byte
	if err := row.Scan(&v); err != nil {
		return err
	}
	if string(v) != "bar" {
		return errors.New("not equal to bar")
	}
	return nil
}

func main() {
	err := t()
	if err != nil {
		panic(err)
	}
}

```
- What did you expect to see?
For default SSI, I want to see a deadlock between tx and db.
- What did you see instead?
Got error `pq: table "kvt" does not exist`

I am not sure if it's a BUG, maybe I missuse it.

**Comment by petermattis** [comment]
The `SET DATABASE = test` statement applies to a specific DB connection/session and with the go `database/sql` interface you don't have control of which connection is used. In your code above, a single connection is used for the initial set of statements and that same connection is bound to the transaction by `db.Begin()`. The subsequent call to `db.QueryRow()` requires a new connection (because the original one is still being used by the transaction) which is why you see the failure on that statement.

Try replacing all of your `kvt` references with `test.kvt`. Or change the URL to contain the default database for connections: `postgresql://root@localhost:26257test?sslmode=disable`

**Comment by ggaaooppeenngg** [comment]
it works, thx!

**Comment by ggaaooppeenngg** [comment]
```
package main

import (
	"database/sql"
	"errors"

	_ "github.com/lib/pq"
)

func t() error {
	db, err := sql.Open("postgres", "postgresql://root@localhost:26257?sslmode=disable")
	if err != nil {
		return err
	}
	if _, err := db.Exec("CREATE DATABASE IF NOT EXISTS " + "test"); err != nil {
		return err
	}
	if _, err := db.Exec("SET DEFAULT_TRANSACTION_ISOLATION TO SNAPSHOT"); err != nil {
		return err
	}
	if _, err := db.Exec("SET DATABASE = " + "test"); err != nil {
		return err
	}
	if _, err := db.Exec("CREATE TABLE IF NOT EXISTS test.kvt (key BYTES PRIMARY KEY, value BYTES)"); err != nil {
		return err
	}
	if _, err := db.Exec("UPSERT INTO test.kvt VALUES ($1, $2)", []byte("foo"), []byte("bar")); err != nil {
		return err
	}

	for i := 0; i < 2; i++ {
		tx, err := db.Begin()
		if err != nil {
			return err
		}
		if _, err := tx.Exec("UPSERT INTO test.kvt VALUES ($1, $2)", []byte("foo"), []byte("bar1")); err != nil {
			return err
		}
		println("before db")
		row := db.QueryRow("SELECT value FROM test.kvt WHERE key = $1", []byte("foo"))
		var v []byte
		if err := row.Scan(&v); err != nil {
			return err
		}
		println("before commit")
		if err := tx.Commit(); err != nil {
			return err
		}

		if string(v) != "bar" {
			return errors.New("not equal to bar")
		}
	}
	return nil
}

func main() {
	err := t()
	if err != nil {
		panic(err)
	}
}

```

@petermattis I set default isolation to SSI, and repeat the trasaction for 2 times, and it prints.

```
before db
before commit
before db
```
It seems it is blocked, is this also a issue with underlying connections pool? 

I find your tx code, https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go 
and I am wondering if the second try of txn needs a retryable error handling, to avoid this block?
Any documents detailed about would help, thx.

**Comment by bdarnell** [comment]
Just like `SET DATABASE`, `SET DEFAULT_TRANSACTION_ISOLATION` is a session-level variable, but there is no guarantee in Go's `database/sql` package that you'll be running in the same session when you execute your transaction. You need to run `SET TRANSACTION ISOLATION SNAPSHOT` as the first statement of the transaction itself. (or use `BeginTx(context.Background(), sql.TxOptions{Isolation: sql.LevelSnapshot})` instead of `Begin()`). 

Also, `SSI` means "serializable snapshot isolation". `SI` is "snapshot isolation".

However, none of this should matter since you're running your transactions one at a time instead of concurrently. The problem is that you're calling `QueryRow` *outside* the transaction (`db.QueryRow` instead of `tx.QueryRow`). This is effectively a second concurrent transaction that can't proceed because it's blocking the execution of the transaction created by `tx.Begin`. Change `db` to `tx` and the transaction can proceed.

**Comment by ggaaooppeenngg** [comment]
Thx!

I use db and tx as two concurrent access of data since there are two sessions even in serialized loop.

I tried `tx, err := db.BeginTx(context.Background(), &sql.TxOptions{Isolation: sql.LevelSnapshot})`, it says `isolation levels not supported`, maybe my version is out of date.

When I set `SET TRANSACTION ISOLATION LEVEL SNAPSHOT` before tx starts, it works as db sees a consistent view of foo, no matter what writes before commit. 

Everything sounds reasonable now.
