### ISSUE TITLE
bulkio: enable using HDFS for external storage

### ISSUE THREAD

**Issue by a6802739** [cockroachdb/cockroach#14884]
**FEATURE REQUEST**

we should support backup/restore cockroach cluster from hadoop. @bdarnell

**Comment by dt** [comment]
When we first looked at storage provider options, I think we thought we'd initially support HDFS via our `http` option hitting an HDFS cluster's webhdfs/httpfs endpoint. 

However right now, our `http` storage scheme won't quite work out of the box against webhdfs, since we just use standard HTTP verbs `GET` and `PUT` rather than the hdfs-specific `?op=blah` params. 

We could add an `http-hdfs` scheme pretty easily to switch those though?

Adding a native hdfs client (rather than hitting the webhdfs/httpfs endpoint) seems a little more involved -- I haven't looked too recently, but I seem to recall there are things to handle like breaking wire protocol changes between versions, name node failover, etc, thus our initial plan to start with leaving responsibility for that to an existing tool like the webhdfs gateway.

**Comment by a6802739** [comment]
@dt, So our plan is to use httpFS gateway to process the `backup`?

**Comment by dt** [comment]
Yes, that was my initial reaction: rather than bundling an hdfs client directly -- and then dealing with which versions are supported (iirc they made breaking changes in the wire protocol), correctly handling the various name node failover / ha configurations, etc -- we'd just make a variant of the current HTTP client that knowns how to interact with the webhdfs or httpfs API (i.e. using the `?op=` params).

That said, relying on a gateway does add some operational complexity, namely for deployments that don't already have httpfs or webhdfs gateways deployed, and of course the overhead / throughput limitations of said gateways, so I could also see an argument for supporting HDFS directly, if you think it would be operationally easier, more reliable or faster.

(I wish Go plugin support were further along -- would be ideal for this kind of thing. Oh well.)

**Comment by a6802739** [comment]
Okay, so I will try to use httpfs first to support `backup to hadoop`. Thank you for your reference.

**Comment by dianasaur323** [comment]
ok, this was a suggestion to work on in 1.2, but given our current ongoing list, let's but this in 1.3, until someone has time to implement this.

**Comment by dt** [comment]
No current plans to add this as we've heard little interest from the community. Anyone who's interested in HDFS support can comment here though to make sure we're aware of that going forward.
