### ISSUE TITLE
sql: constant folding produces different results than postgres

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14940]
cockroach:

```
root@:26257/> select 1.0 - 1 / 2;
+---------------+
| 1.0 - (1 / 2) |
+---------------+
|           0.5 |
+---------------+
```

postgres:

```
postgres=# select 1.0 - 1 / 2;
 ?column? 
----------
      1.0
```

This is because the `1 / 2` in postgres is evaluated as an integer, and thus truncates to 0. Is this known and intended behavior?

@nvanbenschoten @knz

**Comment by jordanlewis** [comment]
I think we intended to make `int / int` a non-integer division. This is one of the chief causes for output mismatch in `sqllogictest` for CockroachDB.

I would personally be happy to see `int / int` be changed into integer division, but I'm not sure if it's too late for that.

**Comment by mjibson** [comment]
We do have `//` for int division:

```
root@:26257/> select 1.0 - 1 // 2;
+----------------+
| 1.0 - (1 // 2) |
+----------------+
|              1 |
+----------------+
```

So maybe we are ok with this? It's still in the camp of "math queries in postgres giving different results in cockroach" though, which makes me :(

**Comment by jordanlewis** [comment]
It appears that in this case we went with MySQL compatibility over Postgres, judging by their docs: https://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html

I'm not sure why this was done, honestly. I don't think it's a great idea to try to straddle MySQL and Postgres in terms of compatibility - that will just lead to a bad user experience for people as their expectations are met or not met depending on the particular situation.

I would prefer that we change this as well, but I'd like to get a little more consensus on this first. I wonder who implemented these first - perhaps @petermattis or @nvanbenschoten? Opinions from either of those two folks?

**Comment by mjibson** [comment]
We had a big discussion about this long ago in #3308. It's unclear if we need to change our minds because we are now trying to get the ORMs to work correctly.

**Comment by petermattis** [comment]
I'm a little anxious about targeting exact compatibility with PostgresSQL, though it seems ORMs are pushing us in that direction. Do we have any examples were compatibility at this level is necessary for ORMs?

**Comment by mjibson** [comment]
I expect that there's some ORM out there that converts an AST into a query, like C# linq-to-SQL or maybe ruby or something. So you write some expression in your ORM like `db.Select(a from d where b = 1 / 2)` (i.e., the expression stuff isn't a string), and the ORM converts that ruby/C# AST node into a SQL expression. I'm going to dig and see if I can find a concrete example.

**Comment by dianasaur323** [comment]
assigning to @mjibson for now as you investigate. feel free to reassign once we decide what path to take.

**Comment by petermattis** [comment]
> I expect that there's some ORM out there that converts an AST into a query, like C# linq-to-SQL or maybe ruby or something.

Possibly, though you'd get different results if you were running against MySQL or PostgresSQL too.

**Comment by jordanlewis** [comment]
> Possibly, though you'd get different results if you were running against MySQL or PostgresSQL too.

I don't think so - ORMs are generally aware of the differences between MySQL and PostgreSQL and create queries correspondingly. Those are the main 2 adapters that exist for most ORMs we've looked at, in fact.

The issue here is that, although we advertise PostgreSQL compatibility, we behave like MySQL. That will lead to incorrect results if an ORM constructs a query expecting `/` to mean integer division, like it should if it thinks its talking to PostgreSQL.

**Comment by petermattis** [comment]
> The issue here is that, although we advertise PostgreSQL compatibility, we behave like MySQL. That will lead to incorrect results if an ORM constructs a query expecting / to mean integer division, like it should if it thinks its talking to PostgreSQL.

I will be very surprised if an ORM actually knows about the difference in division between MySQL and PostgreSQL and constructs different queries. Please surprise me.

**Comment by nvanbenschoten** [comment]
The result here is expected, and was very much an active [design decision](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/typing.md#second-pass-constant-folding) of our typing system. Our goal has never been to be 100% compatible with Postgres, and this is an instance where both @knz and I felt strongly that they had made the wrong choice. Unexpected integer division bugs cause all kinds of issues, and we didn't want to provide more surface area for users to unintentionally shoot themselves in the foot. If they want to perform integer division, we instead provide an explicit operator to do so: `//`. While maintaining compatibility with Postgres is important in that it helps us support ORMs, it would be a mistake to make bad decisions strictly because Postgres made them 30 years ago. 

Note though that there are actually two different questions at play here:
1. Should untyped numeric values perform integer division? (ie. `1/3 = 0`)
2. Should typed integer values perform integer division? (ie. `1::INT/3::INT = 0`)

I don't think I can see any good argument (outside of blind compatibility with Postgres) for the answer to the first question to be "yes", especially when we have a notion of untyped constants. The second question is a little more difficult to answer, which was what prompted https://github.com/cockroachdb/cockroach/pull/3308 and https://github.com/cockroachdb/cockroach/issues/3271.

I'll also echo Peter's skepticism about this ever coming up in practice for an ORM. I'd even say that if it does come up, then integer division probably wasn't the actual intended result and that our (and MySQLs) approach is preventing a subtle bug. I would be very interested to see if we can find a case where that prediction is wrong and where PGs behavior is relied upon.

**Comment by knz** [comment]
So what about we make a little reality check here. We are talking about expressions using literal constants, not placeholders or columns. What automatically-generated code do you know produces a sub-expression with only literals? Why would a framework or ORM produce and send the string "1/2" to a server instead of "0.5"? Think about it: 

- either the value comes from the framework itself, in which case the programmer probably will disambiguate by writing explicitly 0.5 (most likely) or 0 (think again: there's literally no possible reason a programmer would decide to send the string "1/2" to a server when they mean to send the value 0). 
- or the value comes from the client of the framework, in which case the constant will be enclosed in a placeholder (otherwise, their code is broken!!!) which does not suffer from any ambiguity here

**Comment by bdarnell** [comment]
> What automatically-generated code do you know produces a sub-expression with only literals?

Some frameworks don't support proper prepared statements and do parameter substitution on the client side (this is partly because mysql has historically had poor support for prepared statements, and partly because if the statement will not be reused it's often faster to do it this way than to do a prepare/execute/deallocate sequence). This could result in a SQL statement containing only literals even though the query was not written that way. 

But in any case, I'm OK with the fact that we define `int / int -> float` instead of being perfectly compatible with postgres, unless we have concrete evidence that this is a problem.

**Comment by mjibson** [comment]
We've decided this is fine and we'll just document it.
