### ISSUE TITLE
sql: float -> int conversion should detect overflow

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14947]
postgres:

```
postgres=# SELECT 1e300::FLOAT::int;
ERROR:  integer out of range
```

cockroach:

```
root@:26257/> SELECT 1e300::FLOAT::int;
+----------------------+
|  1e300::FLOAT::INT   |
+----------------------+
| -9223372036854775808 |
+----------------------+
```

**Comment by knz** [comment]
Conceptually I am not completely sure about this.
On the one hand from an arithmetic perspective you're right, but this exclusive focus on correctness omits two aspects:

1) people who use a floating-point, approximate data type should know (and we can teach them) to expect iffy situations at the boundaries of the range of representable values. For example in C, the kind of conversions you're concerned about here are simply "undefined behavior" which means the compiler can choose to make the computer explode if the program evaluates such an expression. Not to say we should do like C does, but there is precedent for the perspective "here be dragons"
2) people who use a floating-point type are *usually* interested foremost in performance, and will care more about the performance of the common case than result correctness on the edge cases. In particular, to this audience **it is distasteful to introduce mandatory overhead in the common case for checks that are only relevant in the edge case**. (Culture of "don't pay for what you don't use", etc) I mention this because your proposed change in #14967 introduces such an overhead.

I would encourage you in these types of issues (and the corresponding commit messages) to provide more motivation for the changes other than appealing to "pg does it this way".

**Comment by knz** [comment]
(And assuming pg does indeed make the best choice, then at least copy-paste the motivation from pg's docs and/or the corresponding commit message in pg's source code history or source code comments)

**Comment by nvanbenschoten** [comment]
I think both of @knz's arguments are valid and deserve discussion. In particular, this issue could be resolved without the added overhead (the intermediate cast to a decimal) if we're willing to compromise on correctness in an edge case. The issue and PR discuss why the intermediate cast is necessary if we want to be strictly correct, but nowhere is it made clear whether PG would actually detect the case either. From my testing, it doesn't look like it would:

```
postgres=# SELECT (9223372036854775805::real)::int8;
ERROR:  bigint out of range
```
