### ISSUE TITLE
security: determine good certificate lifetime defaults

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#14985]
CC: @a-robinson, @bdarnell 

We need to figure out what our default should be for certificates.
With #14703, the CA cert defaults to 5 years, the server and client certs to 1 year.

These specific values we picked to:
* avoid having both CA certs and dependent certificates expire at the same time
* make lifetime limited, but not incredibly short-lived

On the con side, one year still comes pretty quickly and can be surprising if not expected.

As much as we can clarify the lifetimes in the docs, we should decide if we want to default to near-unlimited lifetimes and call things out more clearly for security-conscious folks, keep the current default, or anywhere in-between.

Marking this as 1.0 as it would be nice not to change this later. Code-wise, this is two constants in `pkg/cli/cert.go`

**Comment by mberhault** [comment]
Let me make a few proposals and let's settle on one if we can:

1. keep the defaults: `CA lifetime: 5 years, node/client lifetime: 1 year`. These are mostly arbitrary and picked by me. It's rather long for security-conscious people, or those with existing PKI infrastructure. At the same time, one year comes quickly and can be surprising/annoying for people who want SSL but don't care about the security of their keys/certs.
1. make them practically unlimited: the limit is the year 9999 (should be good enough). We can print a large warning on the cert commands for values greater than some amount, or unchanged defaults. A nice advantage of unlimited certs is that rotation can still be done quickly.
1. less than the defaults: this seems like a year may not even be enough for non-security-conscious people, making it less would most likely just cause additional headaches.
1. anything between the default and unlimited is as arbitrary as the default.

@a-robinson: I think I'm starting to lean in your direction on this one. I would like to have very visible warnings in the docs and in the cert commands though.

**Comment by bdarnell** [comment]
In the future, we'll have smoother processes in place for cert rotation (could be integration with tools like Vault, could be something like letsencrypt, could just be better scripts). Let's make the 1.0 defaults high enough that the first time rotation is needed will be after we have better support in place. So working backwards, if we make the default cert lifetime be a year, we should try to get better rotation in place for 1.1. If we think it might take longer to get that done, it's probably better to increase the default lifetime. 5 years CA, 2 years for others sounds good to me, even though it is still fairly arbitrary. I'd also be OK with "effectively unlimited" for now, since a multi-year expiration window isn't worth very much for security. 

And I'll stand by my leap year pedantry: if we tell people that certs last 5 years, they should be able to set up a calendar alert 5 years in the future and handle rotation then. 5 * 365 days doesn't do that.

**Comment by mberhault** [comment]
Ok, narrowing down to two options:
* practically unlimited
* 5y/2y (with 366 day years)

We may want warnings on the certs command in both cases, or more generally: warn for any lifetime greater than 1 year (completely arbitrary, but enough to cover our defaults).

**Comment by a-robinson** [comment]
I did a bit of research on this, and have a few points to report back:

* RethinkDB doesn't have its own tooling, but its docs create certs that last 10 years (without even warning you): https://rethinkdb.com/docs/security/
* Cassandra's tooling reportedly defaults to 90 days, but its docs have you create a CA/cert that lasts 100 years: https://docs.datastax.com/en/cassandra/2.1/cassandra/security/secureSSLCertificates_t.html
* Postgres basically just points you at openssl and gets out of the way: https://www.postgresql.org/docs/current/static/ssl-tcp.html
* Kubernetes' [default scripts set up CAs/certs with a 10 year expiration](https://github.com/brendandburns/easy-rsa/blob/e11310d2e8dfdf01910185abc944e78053ae2bfe/easyrsa3/easyrsa#L1006-L1007), but all of its different "distributions" can do their own thing (I believe GKE certs had a 5 year expiration):
* Kubernetes still doesn't have great rotation support, though, so I doubt providers are all that aggressive.
* CoreOS had [a good conversation](https://github.com/coreos/coreos-kubernetes/issues/621) about this for their Kubernetes distro, [motivated by "overwhelming user feedback" about their default 90 day policy](https://github.com/coreos/coreos-kubernetes/issues/627). They went with a 10 year default for both the CA and the certs: https://github.com/coreos/coreos-kubernetes/pull/645

I'd still favor longer than 5 years / 2 years (10 years for each seems pretty common), but it's also interesting to see how documentation is sometimes used to guide people to do something different than the command's default.

**Comment by a-robinson** [comment]
As a nice example of how to do it better, [Swarm renews its own certificates every 90 days by default](https://docs.docker.com/engine/swarm/how-swarm-mode-works/pki/). The difference there is that they don't have to worry about redistributing certs to clients, since it's pretty much assumed you'll be communicating with it locally.

**Comment by a-robinson** [comment]
And it's interesting that none of these seem to differentiate between CA expiration and cert/key expiration, unless I've missed it.

**Comment by mberhault** [comment]
Thanks for looking into this. your 10y change seems fine. The discussions seem to be similar to our own, with a desire to get users to rotate more frequently, but not cause too many surprises for people who don't care (most).

Our job in the future is probably to make cert generation/deployment/rotation (and eventually revocation) as simple as possible.
