### ISSUE TITLE
sql: use Vault with CockroachDB

### ISSUE THREAD

**Issue by mytototo** [cockroachdb/cockroach#14988]
Hi,

I use [Vault](https://www.vaultproject.io/) for almost all of my projects. I have 2 questions regarding using both Vault and CockroachDB in tandem.

1. Is it possible to use CockroachDB as data storage for Vault?
2. Is it possible to link CockroachDB users with Vault users for secret backends?

Thanks.

**Comment by bdarnell** [comment]
1. It might work with [Vault's postgres backend](https://www.vaultproject.io/docs/secrets/postgresql/), but I don't know if anyone has tried this.
2. Not at this time, although it's also been discussed in #14012.

**Comment by jordanlewis** [comment]
The [PostgreSQL storage backend](https://www.vaultproject.io/docs/configuration/storage/postgresql.html) looks fairly simple. I believe we support all of [the queries](https://github.com/hashicorp/vault/blob/master/physical/postgresql.go) that it generates, with the exception of the `string_to_array` builtin.

I've opened #15042 to track that missing builtin function.

**Comment by mytototo** [comment]
This is great @bdarnell and @jordanlewis. Thank you for your answers. Keeping this issue open so we can track the feature request.

**Comment by sean-** [comment]
FYI, there's an open PR for using CockroachDB as a non-HA backend for Vault right now: https://github.com/hashicorp/vault/pull/2713

@andreimatei and I are exchanging emails now re: [advisory locks](https://www.postgresql.org/docs/9.6/static/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS) and what it would take to add CockroachDB as an HA backend:

https://github.com/hashicorp/vault/blob/9d013a0707a8fe9e1a891abcc4e3a2105bd97fcb/physical/physical.go#L46-L56
https://github.com/hashicorp/vault/blob/master/physical/consul.go#L446-L450
https://github.com/hashicorp/vault/blob/master/physical/consul.go#L424-L444

**Comment by mytototo** [comment]
Thanks for the updates @sean-. This is great news!

Do you have any plans to support a minimalist UI for Vault inside the Cockroach UI?
I'm not talking about adding the Vault features in the Cockroach UI because it's not the purpose but just notice the end-user this is a Vault, data is encrypted and just point out the back-end types (approle, github, etc.) maybe?

**Comment by sean-** [comment]
I've come around in my thinking about the use of advisory locks since I posted this above.  From my [review of the PostgreSQL HA backend](https://github.com/hashicorp/vault/pull/2700#pullrequestreview-48765978):

> I've actually come full circle on the advisory locks for PostgreSQL HA. In order to perform correct hand-off between two different PostgreSQL backends when a failover happens faster than a lock duration, or using something like pl_paxos, or CockroachDB, use of a heartbeat table like this is actually the most stable way to go.
>
> In the future I can see an additional configuration parameter that would possibly modify this behavior to do something backend specific, but for the time being, the most universally useful and reliable way to do HA PostgreSQL is to use a heartbeat table and poll the database every poll_interval.

Hopefully that PR will also make Vault usable for CRDB.  I deliberately kept the SQL in my review simple and did not suggest the use of wCTEs to perform the `DELETE` + `INSERT` in order to allow the backend to be compatible with CRDB.

**Comment by sean-** [comment]
It would be really nice if someone from CockroachDB ( @bdarnell ?) could comment on the use of range types (specifically timestamp with timezone ranges).

https://github.com/hashicorp/vault/pull/2700/files/b957d7c6963b8b11a95cb2022ef1f0451af9dcc9#r127361754

**Comment by knz** [comment]
cc @BramGruneir to integrate in the meta lists

**Comment by mberhault** [comment]
@bram: I'll move this to your plate for now. This seems like third-party compatibility.

**Comment by rolandcrosby** [comment]
I'm looking into this with a customer who is interested in running Vault with CockroachDB instead of Postgres as the backend. I believe #28045 can be worked around -- newer versions of the Postgres auth backend allow the user to specify a custom query for the `CREATE USER` statements issued by Vault, bypassing `VALID UNTIL` -- but now it looks like we're hitting a timezone name issue.

Specifically, [this logic](https://github.com/hashicorp/vault/blob/master/plugins/helper/database/connutil/sql.go#L121-L128) introduced in hashicorp/vault#607 explicitly sets the connection timezone to "utc", overriding any existing timezone setting in the connection string. Since our time zone implementation is case-sensitive and only accepts `UTC`, this causes the Vault connection to fail before the connection can even be established, emitting the error `pq: invalid value for parameter "TimeZone": "utc"`. 

I'm happy to open an upstream issue or PR on Vault to fix this, but would also be interested to know if this is something we'd be willing to special-case for Postgres compatibility.

**Comment by bdarnell** [comment]
If postgres accepts lowercase `utc`, I think we should too. Are all time zone names case-insensitive, or just UTC? Try `edt` or `america/new_york`.

**Comment by rolandcrosby** [comment]
On Postgres 11, 'set timezone' works case-insensitively:

```
postgres=# set timezone=utc;
SET
postgres=# show timezone;
 TimeZone
----------
 UTC
(1 row)

postgres=# set timezone='america/new_york';
SET
postgres=# show timezone;
     TimeZone
------------------
 America/New_York
(1 row)

**Comment by knz** [comment]
The discussion on time zones should continue on #36864.

**Comment by rubenoost** [comment]
A simple workaround if you have access to the system(s) running cockroachdb is to create the timezone data yourself:

```
cp /usr/share/zoneinfo/UTC /usr/share/zoneinfo/utc
```

**Comment by jordanlewis** [comment]
This seems to be solved - cursory testing shows that you can startup a vault server against CockroachDB with the instructions [here](https://www.vaultproject.io/docs/configuration/storage/cockroachdb.html), and do basic commands. @mytototo and @sean- thanks for the input - please try this out more and file more issues as problems come up.

Thank you!

**Comment by jordanlewis** [comment]
For the record, I used the config:

```
storage "cockroachdb" {
  connection_url = "postgres://root@localhost:26257/defaultdb?sslmode=disable"
}
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}
```

and startup command `./vault server -config config`
