### ISSUE TITLE
settings: multi-node acceptance tests

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#15053]

**Comment by vivekmenezes** [comment]
What is this issue about?

**Comment by benesch** [comment]
We currently only have unit tests for the `system.settings` table and its associated infrastructure. We eventually want some acceptance tests that actually spin up a few nodes and ensure that system settings are gossiped between the nodes. (Since settings use a global mutable map, `TestCluster` servers all share the same settings and don't exercise the gossip path.)

**Comment by tschottdorf** [comment]
We do this in the version change tests. Surely we could do more, but the basic mechanism is definitely exercised (i.e. we change a setting on node 1 and wait that node 2 and 3 learn about it).
