### ISSUE TITLE
sql: enhance constant folding

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#15055]
We could do constant folding on expressions involving casts and function applications with constant arguments. Detecting errors earlier is always better (#13873 was the proximate cause for me filing this issue), and performance of some queries will be better (unless the folded expression was expensive yet not needed).

Per offline conversation with @jordanlewis , we don't need to worry about errors resulting from constant folding in branches that won't be evaluated at run time, since PostgreSQL folds conditionally evaluated constant expressions.

**Comment by jordanlewis** [comment]
Example from Postgres that demonstrates the above:

```
jordan=# create table fnord (c decimal default (case when now() < '2018-04-18 18:00:00' then 2 else '3-1'::numeric end));
ERROR:  invalid input syntax for type numeric: "3-1"
```

**Comment by justinj** [comment]
Some random input from me since I've been in this area lately:

* AFAIU we currently *do* fold function applications with constant arguments for functions which are not tagged as `impure`, as checked in the `isConstVisitor`'s `VisitPre` method.
* We currently do handle the case where paths that are not reached get constant folded, and there are tests which verify this, but as Jordan said, it doesn't seem especially important, but there is a relevant section of the [docs](https://github.com/justinj/docs/blob/0390ede7c4ba1e361d05caeb522a7c2513f34095/sql-expressions.md#conditional-expressions-and-boolean-short-circuit-operations) that may or may not need to be addressed alongside this.

**Comment by justinj** [comment]
I'm not sure that this issue is the correct approach to #13873, as we currently do fold casts:
```
root@:26257/> EXPLAIN (EXPRS) SELECT 1::INT + 2::DECIMAL;
+-------+---------+----------+-------------+
| Level |  Type   |  Field   | Description |
+-------+---------+----------+-------------+
|     0 | render  |          |             |
|     0 |         | render 0 |           3 |
|     1 | nullrow |          |             |
+-------+---------+----------+-------------+
(3 rows)
```
and pure functions calls with constant arguments:
```
root@:26257/> EXPLAIN (EXPRS) SELECT REPEAT('a', 2);
+-------+---------+----------+-------------+
| Level |  Type   |  Field   | Description |
+-------+---------+----------+-------------+
|     0 | render  |          |             |
|     0 |         | render 0 | 'aa'        |
|     1 | nullrow |          |             |
+-------+---------+----------+-------------+
(3 rows)
```
and this problem can manifest with simpler expressions:
```
root@:26257/d> CREATE TABLE t (a DECIMAL DEFAULT 1/0);
CREATE TABLE
root@:26257/d> INSERT INTO t VALUES (DEFAULT);
pq: division by zero
```

Regarding what is a correct solution to #13873, I'm not sure, but postgres has the same problem afaict:
```
template1=# CREATE TABLE t (a INT DEFAULT 1/0);
CREATE TABLE
template1=# INSERT INTO t VALUES (DEFAULT);
ERROR:  division by zero
```

I think I lean on the side of this being the correct behaviour, but interested to hear if anyone else has any thoughts.

One option is that we could do a check to see if the expression used is constant (code for this already exists), and then reject if its evaluation errors (this is not perfect though, since it will not reject things like `1/(now()::int * 0)`).

**Comment by justinj** [comment]
After some more investigating it seems like what Postgres *might* be doing is just checking if literals can be coerced their expected types (but just literals, not constant expressions in general). For example, these are accepted:
```
CREATE TABLE t (a INT DEFAULT CONCAT('f', 'oo')::INT);
CREATE TABLE t (a INT DEFAULT ('f' || 'oo')::INT);
```
but this isn't:
```
CREATE TABLE t (a INT DEFAULT 'foo'::INT);
```
and this also isn't, so it's not just an explicit coercion thing:
```
CREATE TABLE t (a INT DEFAULT (case when 1 = 1 then 1 else 'foo' end));
```
We could possibly do a similar check.

**Comment by justinj** [comment]
Closing in favour of #13873, because constant-folding isn't the issue.
