### ISSUE TITLE
rpc: remove the need to deal with `rpc.Client` directly

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1521]
Previously, we had backoff logic for this in rpc/client; this was removed in #1285 and then refined in #1394. The result is that each raft message will spawn a new rpc client and attempt to connect. This is a lot of log, goroutine, and network thrash.

**Comment by tschottdorf** [comment]
I agree that the way `rpc.Client` works is kind of icky and reworking it so that each `Client` deals with its internal connection better and doesn't just self-destroy is a good idea. Usability is also somewhat awkward in the current state: after `NewClient` you have to check the `Closed` and `Ready` channels, and you have to wonder whether you're supposed to recheck them on every send, ... - it's unclear. Clients just want to send, and they want to know whether it worked. It would be good to have just the following:

```
c := rpc.NewClient(...) // do this once, even if there's a message sending loop below
call := c.Go("X.Y", args, reply, nil /* or done chan */)
```

and if everything works as expected, this behaves just like the Go's built-in client. If the client knows it's unhealthy, it could just error out your call immediately, i.e. set `call.Error`, close `call.Done` (or submit to the `done` channel, if that form was used), without ever attempting to send. Callers would either return that error just like any other, or, in the case of the Raft client, they could wait for a `client.Ready()` channel to be signaled when the remote's health comes back to life. That way the raft transport would behave quite nicely.

Unused connections should self-destroy, but the timeout can be rather high.
The fact that clients self-destroy (necessarily, we don't want to keep a one-off connection open forever) also means that when you call `NewClient`, you kind of don't want to hold on to it for too long. Plus, clients get cached, but `NewClient` gets options (not any important ones, of course), so a lot of times you'll get a client back that doesn't correspond to the options you passed. So `NewClient` shouldn't even be used by the average caller. It seems more reasonable to call `rpc.Go(addr, "X.Y", args, reply, nil /* or done */)` instead. You'll still have to make sure the address doesn't change, but if it does you'll get an error, and re-resolving the address on such errors (usually a quick Gossip lookup in our case) is enough.

@bdarnell wants to rewrite the Raft transport btw, so I recommend against this being the primary motivator though. We should also start using the part of the Raft interface which allows marking nodes as down (so they get less traffic).

**Comment by bdarnell** [comment]
I agree that it makes sense to move to an interface where we pass an address and a request in the same call instead of having the caller first get a client object for an address and then call an rpc method. I'd introduce an explicit `ClientPool` object instead of just doing everything through static methods.

**Comment by tamird** [comment]
The original issue is alleviated with #1523. Changing the title to reflect the ongoing discussion.

**Comment by petermattis** [comment]
@tamird I imagine this issue will be obsoleted by the switch to gRPC. Feel free to close if you agree.

**Comment by tamird** [comment]
I'm less certain. Constructing gRPC clients still requires a connection, so
if we want to share the underlying connections I believe we'll still need
some abstraction.
