### ISSUE TITLE
sqlccl: backups should keep track of the creating cluster's ID

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#15231]
We should be able to report an error if a user specifies `BACKUP... INCREMENTAL FROM foo` where `foo` is a backup (potentially of identical tables) from a different cluster.

**Comment by bdarnell** [comment]
Is that really an error? If I backup, destroy my cluster, and restore the backup into a new cluster, can I make an incremental backup based on the same one I just restored, or is there some reason I need to make a new full backup first?

**Comment by benesch** [comment]
cc @danhhz. There's no technical reason (that I'm aware of) that would require a new full backup after a restore.

My initial issue description didn't explain the problem well. The case I'm worried about is where you have one database per customer/project, and so each database has an identical schema modulo version skew. If someone fat fingers a `BACKUP... INCREMENTAL FROM foo` command, running the statement on Customer A's database but specifying a `foo` that was created from Customer B's database, they'll end up with a backup over a potentially too-short timespan. If we care about this, it should be relatively easy to associate a UUID with each table (since now that I think about it, the cluster UUID is far too broad) and make `RESTORE` maintain these UUIDs.

This is admittedly not likely to be a frequent problem.

**Comment by danhhz** [comment]
I think there is value in storing the cluster id in backups. Both for some future `SHOW BACKUP foo` command and potentially if we wanted to make it harder to shoot yourself in the foot (what @benesch describes is one scenario). IIRC, the scope of the conversation that inspired this issue was purely about saving the cluster id in the backup and not about using it for anything yet.

@bdarnell At the moment, what you describe wouldn't be handled because restore only consider one set of table descriptors and the tables might have different table ids in the two clusters.
