### ISSUE TITLE
sql: type rules create some weird errors

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15257]
```
root@:26257/> select 'a' + 0;
pq: error type checking constant value: could not parse 'a' as type date
```

This is obviously an error, but probably shouldn't be this one. Assigning this to ya'll for triage or closure.

**Comment by nvanbenschoten** [comment]
This was introduced and discussed in https://github.com/cockroachdb/cockroach/pull/14593.

> This strange error is a result of the \<date\> + \<int\> overload and because
  of the limitation described on StrVal.AvailableTypes.

We should try to improve the error string, but it's a little unclear what the best approach to doing so is. One idea might be to expose a little more information from the `Constant` interface so that we can work around the limitation in `StrVal.AvailableTypes`.

**Comment by knz** [comment]
An alternative (perhaps simpler and more edifying for the user too) would be to explain where the error comes from. For example by prepending the operator candidates that caused the desired type to the typing error. We'd then get: `pq: error while typing <+> (candidates: date+int, int+int, ...): could not parse 'a' as type date)` or something like that.

**Comment by jordanlewis** [comment]
That's a good idea - while we're at it, we should add an error like this to the case where function overload resolution fails to narrow the list down to exactly 1 match.

**Comment by knz** [comment]
:+1:

**Comment by knz** [comment]
(We'll play the assignment game when we scan through the list of all 1.1 issues)

**Comment by cuongdo** [comment]
@knz please triage

**Comment by knz** [comment]
A change in this area at this stage classifies as "risky" according to Pete's definition. Bumping to 1.2 instead.

**Comment by knz** [comment]
This has been fixed, the SQL now reports:

```
root@:26257/t> select 'a' + 0;
pq: unsupported binary operator: <string> + <int>
```
