### ISSUE TITLE
distsql: flow <id> not found

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#15289]
build: 5ada9d7
config: 6-node cluster (Standard_D3 Azure VMs)

Somehow, this cluster has gotten into a persistent bad state where all DistSQL queries hang indefinitely. The gateway node has this error message:

```
E170424 14:55:42.408616 3023265 sql/distsqlrun/server.go:286  [n1] flow 6549a37e-c02e-4219-8ce8-588e46325eaf not found
```

The other nodes *sometimes* have logs like these:
```
E170424 14:22:49.182542 3666338 sql/distsqlrun/flow_registry.go:189  [n6] flow id:3ce92c07-51b3-458f-8615-ae044dcfbf6a : 2 inbound streams timed out after 10s; propagated error throughout flow
```

**Comment by RaduBerinde** [comment]
Shouldn't there be traces at https://app.lightstep.com/tpch-test/latest ?

**Comment by RaduBerinde** [comment]
@cuongdo can you provide a few more details about the workload - is it one query at a time? does the query run against the same node every time?

**Comment by cuongdo** [comment]
There was just one query at a time, issued to node 1.

**Comment by asubiotto** [comment]
Were you running only one query at a time since starting the cluster? If not, one thing that could have happened is that a bunch of concurrent queries somehow got into a deadlock despite the reduction of probability of this scenario (see #14948). Even though the concurrent load is not running, a bunch of streams might still be stuck, resulting in these new ones timing out in setting up the flow because they can't use the connection. Checking for any goroutines stuck in `distsqlrun` should show us if this could be the case. If no concurrent load was run at any point since cluster initialization, I'm not sure what could be happening.

**Comment by cuongdo** [comment]
Yes, prior to my restarting the whole cluster, there was a bunch of concurrent load. Also, some of that load caused OOMs, which is a form of chaos.

**Comment by cuongdo** [comment]
This hasn't happened in a long time and after several load / chaos tests, so closing.
