### ISSUE TITLE
server: registration update error

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15399]
Saw this in a log file while running a local single node cockroach cluster:

```
W170427 09:48:55.390372 212 server/updates.go:301  [n1] failed to report node usage metrics: status: 500 Internal Server Error, body: failed to record status report 325a21f3-68b7-4ce1-89e2-2253ee4382f5:  pq: duplicate key value (uuid,nodeID,timestamp)=(b'2Z!\xf3h\xb7L\xe1\x89\xe2"S\xeeC\x82\xf5',1,'0001-01-01 00:00:00+00:00') violates unique constraint "primary", error: <nil>
```

**Comment by benesch** [comment]
@dt is this solved by https://github.com/cockroachdb/cockroach/pull/15393/files#diff-3104fe8850948156f24eb45757ea16e1R112?

**Comment by dt** [comment]
don't think so: that timestamp is just used internally for how often to send them, it isn't included in the report itself AFAIK.

reg server should:
a) set the timestamp to when it received the report
b) 200 OK a report, even if it thinks it already has it (i.e. PK collision), instead of 500ing.

I'll hopefully look at doing those later today.

**Comment by benesch** [comment]
Oh you're so right. Now that I look at it I cannot find where the timestamp is ever set. In fact...

```
> SELECT timestamp FROM registration.nodes GROUP BY timestamp;
+---------------------------+
|         timestamp         |
+---------------------------+
| 0001-01-01 00:00:00+00:00 |
+---------------------------+
(1 row)

```

...the registration server has never stored a single non-default timestamp in the `nodes` table.

**Comment by knz** [comment]
Perhaps we could start doing so :)
