### ISSUE TITLE
sql: extend rsg_test to check the round-tripping of pretty-prints

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15469]
Suggested in https://github.com/cockroachdb/cockroach/pull/15457#issuecomment-297990715:

For every generated statement *that is already known to run successfully*, we can check that the following sequence of steps:
1. parse the statement
2. pretty print the result
3. check that the pretty-printed code can be executed too (if the pretty-print was incorrect, it is likely to fail execution)
4. parse the pretty printed code generated at step 2
5. pretty-print that
6. check that both pretty printed ASTs are the same

**Comment by eisenstatdavid** [comment]
> check that the pretty-printed code can be executed too

This might not be the case for impure statements.

**Comment by eisenstatdavid** [comment]
I'm also wondering if there's a sensible way to get at the node structure as first parsed. As a first cut, we could probably use `Walk` to serialize the shape of the parse tree. I'm wondering if we could use reflection to peek inside the various non-recursive fields of each node.

**Comment by eisenstatdavid** [comment]
#15876 was the low-hanging fruit here. Comparing parse trees by how they re-serialize isn't ideal, but verifying semantic equivalence of the abstract syntax trees is difficult because grammar rewrites some constructs to (hopefully) semantically equivalent constructs. Comparing the actual parsed structures is thus more difficult than it looks (or seems worth right now).
