### ISSUE TITLE
ui: "staggered version" banner considers dead nodes

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#15534]
In the current incarnation of blue.crdb.io, node 7 was recreated and was reborn as node 11, meaning that node 7 is permanently dead. However, since the cluster version was updated since then, the admin UI now displays the staggered version banner, presumably because node 7's node status still has the old version (and will never be updated).

It's also pretty annoying that this banner doesn't provide more detailed information (which nodes? which versions?).

**Comment by dianasaur323** [comment]
will be fixed by https://github.com/cockroachdb/cockroach/issues/16359
@kuanluo

**Comment by tschottdorf** [comment]
This is pretty annoying actually, because if you end up with this problem then the warning remains forever, and it doesn't seem that decommissioning the nodes changes anything. I *think* there should be an easy fix here? All customers who decommission a node and update the patch releases will have this problem, and it's such an obvious blemish.

**Comment by tschottdorf** [comment]
cc @pmwebster who also reported this in https://github.com/cockroachdb/cockroach/issues/18478#issuecomment-331925934.

**Comment by cuongdo** [comment]
Redistributing bug load

**Comment by dianasaur323** [comment]
In addition to fixing the dead banner, we also need to fix the UX of how decommissioned nodes show up in the admin UI -> mentioned here in this issue: https://github.com/cockroachdb/cockroach/issues/18478 It involves basically decommissioning and killing the node before it's actually considered decommissioned. We should probably think of a better way to alert users that nodes with 0 replicas are "decommissioning" but aren't fully decommissioned until they are killed. This should reflect in the admin UI, since it's important for users to know the status of their node health. I'm ambivalent on how we should fix it, but I do think the behavior is odd in the admin UI.

**Comment by tschottdorf** [comment]
@dianasaur323 You mean that nodes which are still live but are in the process of being decommissioned (whether successfully so or not) are shown as live nodes always, and that's not intuitive, they should at least be marked somehow, right? #18478 has a lot of other stuff going on.

I filed https://github.com/cockroachdb/cockroach/issues/19179 for that issue specifically.

**Comment by tschottdorf** [comment]
Another user just reported this: https://github.com/cockroachdb/cockroach/issues/19217

We should fix it. This can't be too hard.

**Comment by cuongdo** [comment]
@dianasaur323 I think this should be high on our list to fix for 1.2.

**Comment by dianasaur323** [comment]
Yes, we should 100% fix it. @couchand let's chat about what this actually needs to look like before we implement. Let's do this in our bugfixing phase

**Comment by tschottdorf** [comment]
Maybe I'm missing something, but isn't this trivial to fix? Just ignore nodes that are dead for the "staggered version" warning?

**Comment by dianasaur323** [comment]
@tschottdorf I think you're right. I was conflating everything into a large meta issue of -> I don't think decomissioned nodes are showing up properly in the admin UI, but I think https://github.com/cockroachdb/cockroach/issues/19179 covers that larger issue.

**Comment by tschottdorf** [comment]
Another user just noticed this, in personal communication related to #19216.

**Comment by dianasaur323** [comment]
@couchand do you mind seeing if we could do a quick fix for this?

**Comment by tschottdorf** [comment]
Opening a PR.

**Comment by dianasaur323** [comment]
thank you thank you :)
