### ISSUE TITLE
sql: sql compilation can produce execution stages producing empty rows

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15574]
... and this seems like a failure to recognize an opportunity to do something better.

For example, the query `SELECT COUNT(1) from x,y` produces `scanNode`s with no `resultColumns`. In the DistSQL world, #15420 introduces support for empty projections to support these. On the surface, passing empty rows from one place to another seems non-sensical; the only information that the consumer can possibly extract is the number of such rows, which could be more directly communicated by the producer and more explicitly used by the consumer. In the case above, the logical transformation we want is, I think `select count(1) from x * select count(1) from y`.

I think it'd be fantastic if such cases wouldn't exist and #15420 was not needed. So I'm hoping this issue will guide us to figure out if this is indeed a worthy goal and how hard it'd be to achieve.

The first thing I'm unsure of is how general the need for such empty rows is. Is it confined to outer joins?
Another similar case is simply `select count(*) from x`. I'm not sure how this is executed in without DistSQL, but with DistSQL this doesn't actually result in empty streams as we add a render of a dummy constant to the `TableReader`.

cc @knz @RaduBerinde

**Comment by RaduBerinde** [comment]
Here's how this works with classic SQL (spoiler: it's not pretty).

The `scanNode` actually always exposes all columns for the table, however some (in this case, all) of them are marked as "not needed" and the datums for not-needed columns may not be populated. Similarly, the `joinNode` exposes all columns, with some of them perhaps not being populated.

So internally we never store or return empty rows. The rows are always as wide as the `resultColumns` (which include not needed columns). Of course, this can be wasteful. This could be resolved by adding `renderNode`s as necessary. The model could also be changed so that nodes don't emit unneeded columns at all, but that involves a lot of refactoring (and it makes some things harder).

**Comment by knz** [comment]
Yeah also this sounds like premature optimization. I'd really like to know how common this type of situation is before we do something about it.
