### ISSUE TITLE
distsql: better handling of failures and dead nodes

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15637]
In 1.0, we avoid hosts that known to be dead, but we may fail the first attempt of a query if we don't know the host is dead.

This issue tracks implementing better handling of these situations. The idea is to support multiple flows for the same query on a single node, and to reschedule flows (which we failed to schedule) on the gateway node.

One important aspect of "error" in this discussion is version mismatch: if we can reschedule flows that can't run on a host because of its version, we can provide query availability (with decreased performance) during an upgrade even when there are incompatible changes in distsql.

**Comment by cuongdo** [comment]
how is this looking for 1.1?

**Comment by RaduBerinde** [comment]
We have a good idea of what we want to do here but nothing is implemented at this point.

**Comment by arjunravinarayan** [comment]
This is being addressed by #17497, which should merge in the 1.1 timeframe.

**Comment by andreimatei** [comment]
The version mismatched problem has been address some. The node failed recently case remains open.

**Comment by vivekmenezes** [comment]
Probably obvious but this is a high priority issue for us to fix.

**Comment by vivekmenezes** [comment]
radu and andrei are thinking about this problem and trying to figure out what to do in the next release.

**Comment by nstewart** [comment]
This issue is preventing me from doing standard reporting. Is there an update? I'm getting `psycopg2.InternalError: [n3] communication error: rpc error: code = Canceled desc = context canceled` and I see in my 5 node cluster a couple nodes restarted. Happy to create a new ticket but I see #19882 was closed in favor of this one.

**Comment by jordanlewis** [comment]
@nstewart, does the query complete if you try it again? Or are you never able to complete your query?

**Comment by nstewart** [comment]
My script runs ~10 queries serially. Each query runs for about several minutes (but not hours). I've run the script several times over the weekend and it fails at queries places with `context canceled`. 

I'm betting if I added retry loops this thing would eventually complete (I'm going to do this in the short term so I'm not blocked), but since these aren't serializable retries and there is only one, single-threaded client for this database, I wonder if that would be masking a bigger problem.

**Comment by jordanlewis** [comment]
Yes, surely doing that would be masking a problem. During your script's run, are nodes restarting a lot?

**Comment by nstewart** [comment]
Yes, I am running a 5 node cluster and I saw 1 node restart once and another restart 4 times. I saved the debug zip here: https://github.com/cockroachdb/cockroach/issues/28278
