### ISSUE TITLE
sql: TRUNCATE limitations

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15723]
Forked from #15702:

`TRUNCATE` issues a single `DeleteRange` operation for the entire table within a single transaction! For a large enough table, that will run afoul of the max command size limit. But for a table that is ~1 range and with small column values, `TRUNCATE` can generate a `DeleteRange` that is very large (60+ MB). For example, run `kv --max-ops 600000`. This will create a table with a single very large range. Then execute `TRUNCATE test.kv`. With an instrumented binary, this created a Raft command that was 62 MB in size.

Not that `DROP TABLE` does not exhibit this same behavior as it chunks the deletion into transactions that delete 600 keys per transaction.

**Comment by petermattis** [comment]
Even if we fix `TRUNCATE` to delete in chunks (which is actually fairly straightforward to do), we'd simply be pushing the problem of a large Raft command to the subsequent EndTransaction.

Also, note that a naked `DELETE FROM <table>` (without a `WHERE` clause) has the same issue as `TRUNCATE`.

**Comment by petermattis** [comment]
Perhaps `TRUNCATE` should be implemented via the schema change machinery. Is there any expectation that it can be performed transactionally? Cc @vivekmenezes 

@jseldess In the short term, we need to document the shortcomings of `TRUNCATE`. `DROP TABLE` and then recreating the table is preferable.

**Comment by a-robinson** [comment]
To stay postgres-compatible, `TRUNCATE` has to be performed transactionally (["TRUNCATE acquires an ACCESS EXCLUSIVE lock on each table it operates on"](https://www.postgresql.org/docs/9.6/static/sql-truncate.html)).

That means that to support `TRUNCATE` and `DELETE` correctly we really need to make kv more capable of handling large range deletes in a propEvalKV world. I mean, we could implement a locking mechanism on top of kv (yuck) to ensure exclusive access without doing everything in a single transaction, but that seems pretty disgusting.

Since `TRUNCATE` works on whole tables and is allowed to remove all old MVCC records, we could potentially come up with a mechanism for invalidating an entire kv range of data and replacing it with a new one for the same key span, but that wouldn't help with `DELETE` since it's supposed to keep around the old MVCC info.

**Comment by petermattis** [comment]
Do we need to stay Postgres-compatible for `TRUNCATE`? I seem to recall that MySQL (and perhaps Postgres) implement `TRUNCATE` by removing the underlying database files. That really isn't an option for us. 

@spencerkimball and @danhhz have been brainstorming adding range tombstones at the MVCC level to speed up `DROP TABLE`. Perhaps that could be used here.

**Comment by spencerkimball** [comment]
Yes, @danhhz and I have designed a way to handle both `DROP` and `TRUNCATE`
efficiently and transactionally.

**Comment by jseldess** [comment]
Some addition insight on this from a Slack with @a-robinson: 

> basically, running truncate can break your cluster by causing OOMs on the nodes containing the range being truncated. if you have enough memory to spare, they won’t OOM, but they’ll have elevated memory and CPU usage (and thus worse performance)

**Comment by jseldess** [comment]
Limitation documented in https://github.com/cockroachdb/docs/pull/1381

**Comment by vivekmenezes** [comment]
TRUNCATE is now dropping the table and therefore using the chunked drop path used by DROP TABLE. Closing
