### ISSUE TITLE
docs: mistake in the date/time function documentation?

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#15740]
I am not sure but maybe I found a mistake.
On this site:

https://www.cockroachlabs.com/docs/functions-and-operators.html#date-and-time-functions

The documentation states that many time / date functions return the type timestamp and timestamptz. I wonder how this is possible.

The Postgres documentation makes much more sense to me:

CURRENT_TIME and CURRENT_TIMESTAMP deliver values with time zone; LOCALTIME and LOCALTIMESTAMP deliver values without time zone.

**Comment by dianasaur323** [comment]
@WhiteTrashLord Thanks for reporting that. @jseldess can take a look

**Comment by jseldess** [comment]
The function docs are generated from the code, so I believe they are correct. @dt, can you confirm?

**Comment by dt** [comment]
our type system allows multiple overloads -- variants of a function with the same name but different input and output types -- and picks based on the types supplied or expected when the function is called. postgres allows implicitly casting between timestamp types -- meaning that if a timestamptz (returned by `now`, but cockroach does

**Comment by dt** [comment]
Our type system allows multiple overloads -- variants of a function with the same name but different input and output types -- and picks based on the types supplied or expected when the function is called.
Postgres allows implicitly casting between timestamp types -- meaning that if a `timestamptz` (e.g. returned by `now()`) is supplied as the value for a `timestamp` column, postgres will just convert between the two types. Cockroach does not support implicit casting since it can sometimes be confusing or lead to unexpected loss of precision for some types. Thus, to make something like the above example work out of the box, so a query that uses `now()` as the value for  a `timestamp` column without requiring an explicit cast, we have multiple versions of `now()` and then pick the one that returns the type needed in a given context, so we don't need to then convert between the types.

**Comment by jseldess** [comment]
Given @dt's explanation, there doesn't seem to be any errors in the functions doc, so I'll close this issue. @WhiteTrashLord, please let us know if you have any other questions.
