### ISSUE TITLE
stability: Support for large transactions

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15849]
Forked from @andreimatei's comment on #15713:

> Unfortunately the "transaction is too large to commit" is by design - currently an EndTransaction carries all the intents, and so we need to be reasonably sure that each replica will have enough memory to process the corresponding Raft command.
> 
> This is a topic that I've randomly discussed at the watercooler with the likes of @bdarnell and @tschottdorf at times. Dumping stuff here for institutional memory.
> There are various things we could do: one way or another, intents (or, at least, all intents) shouldn't have to be attached to an EndTransaction request. They could be stored in the db and the cleanup happening after EndTransaction has marked the txn record as committed could retrieve them from there. For example, they could be stored in the transaction record itself. The TxnCoordSender could keep appending intent spans when it heartbeats the record, for example. That might not be sufficient, since you'll end up with a humongous txn record. What'd be better is to store them adjacently to the txn rec, such that the range can be split, etc. But then you prolly need to be careful with the orchestration of the cleanup process and the cleanup of these intent records themselves.
> 
> Without, or besides, storing the intents into the db, the client (the client.Txn layer) could be more involved in the cleanup of such large txns; it could store intents in memory and not attach them to EndTransaction, but do cleanup afterwards. It could keep the intents below a memory budget by having a limited-size interval tree and merging spans when it needs to - trading pessimistic scanning at cleanup time for memory at execution time. This would probably work great for cases as the one here (I assume): copying a table.
> An approach like this would probably be made more feasible by the merging of the TxnCoordSender (which currently keeps track of intents) and client.Txn that I'm hoping to do.
> 
> @petermattis, I'm assigning back to you... But I will keep an eye on supporting work here when I do TxnCoordSender refactorings.
> 
> Incidentally - here's one idea about the codelab we were talking about: implement CREATE TABLE AS <query>, or a version of INSERT INTO... SELECT... that does some limited version of the above - doesn't accumulate intents and scans the whole table for cleanup.

**Comment by andreimatei** [comment]
Note that it's exceedingly easy to get yourself into one of \`em "large transactions" by doing something like a `INSERT INTO... SELECT ...` (#15713) or a `TRUNCATE` (#15723) or through the GC queue (https://github.com/cockroachdb/cockroach/issues/15756#issuecomment-299924227) - but this last one may be FUD.

**Comment by tschottdorf** [comment]
Yeah, the GC queue issues (which at this point are hypothetical - the current issues seem to be more basic) can be addressed without this issue.

But I agree that it's too easy to accidentally run a large transaction. We should discuss what users really need in practice and how to make transparent what statements are a bad idea to run. For example, for many large transactions users may often not care about their transactionality, examples being deleting old data, or copying a table (where you can use `AS OF SYSTEM TIME` for the read and write in chunks, if you're willing to accept that if something goes wrong half-way through you end up with a partially copied table).

**Comment by petermattis** [comment]
Large transactions implies long-running transactions, which will hit `MinTSCacheWindow` (10s). And long-running transactions seem to run afoul of the desire to support a min-safe-timestamp for reading from followers.

**Comment by tschottdorf** [comment]
@petermattis I agree, and while we probably don't want to try to explicitly support large transactions anytime soon, playing around generates them "accidentally" and I think that's really what we need to find a way of handling (probably not by enabling large transactions). Of course the issue title suggests otherwise. Perhaps we should make this issue more concrete (or push this to "Later" and make another issue that is more concrete).

**Comment by andreimatei** [comment]
But the timestamp cache is not a problem for new ranges such as what you get when you copy a table (or at least _shouldn't_ be a problem, the comments around `MinTSCacheWindow` and `defaultTimestampCacheSize` are confusing to me).

**Comment by tschottdorf** [comment]
It probably won't be in practice because we're doing lazy eviction in the timestamp cache, but if you spend 10 minutes writing to an initially empty range, then your timestamp will be very old and could easily be bumped by the timestamp cache if it did decide that 10s in the past was actually enough. I'm also not clear on the actual guarantees given in tsCache without looking. But essentially where @petermattis is going is that long-running transactions are inherently problematic and also stand in the way of other things we may want to do, and that it's best to avoid them rather than trying to make them work in general.

**Comment by tschottdorf** [comment]
While chatting with @andreimatei the other day, he suggested one strategy to
deal with large transactions: in most cases, we don't have to keep track of the
exact set of intents; keeping a superset is acceptable too.

For example, picture a transaction that writes one million keys randomly across
some part of the keyspace. We track, say, the first 100 intents as usual. Then,
we begin "coagulating": the 101st write turns one of the first 100 writes into
a key range that encompasses both of them (which one? Probably
longest-prefix-match). Repeat this, and at the end of the million writes, we
have 100 key ranges stored up for this transaction. These get send with
EndTransaction, and the corresponding `ResolveIntentRange` requests touch many
ranges, but this is just a large distributed batch which we can handle (though
we don't necessarily do it super well today).

Conversely, a scan running into 1 million intents would do the same (on
a per-txn basis, limiting intent collection to O(1) conflicting txns at a time)
and thus end up sending `ResolveIntentRange` instead of (too many) individual
`ResolveIntent`. Or a scan doesn't even collect intents, but collects only the
transactions found to conflict, and when they are pushed and the Scan retries,
it implicitly prepends `MVCCResolveIntentRange` commands in its batch for each
of the conflicting and pushed txns, and goes through Raft (WIP on clockless
reads suggests that we can send mixed batches through Raft without
insurmountable obstacles).

**Comment by spencerkimball** [comment]
Stellar idea! This will likely work very well with many big txns. I can
imagine some exceptions though: especially txns which are deleting based on
a where clause which is selecting items from a uniformly distributed
secondary index. We'd end up in these cases with what amounts to a full
table scan.

An alternate idea would be to allow 1,000 intents, after which we just mark
the txn record's intents as indeterminate, which means the txn record must
stick around for the maximum intent GC duration.

**Comment by tschottdorf** [comment]
> An alternate idea would be to allow 1,000 intents, after which we just mark
the txn record's intents as indeterminate, which means the txn record must
stick around for the maximum intent GC duration.

I don't think we can do that, intents written by a committed transaction can potentially stick around forever, and unless you have a rough idea where to go look for them then we're back to needing a cluster-global low water mark which I'd really like to avoid.

To add some more color to the intent coagulation: An interesting case is that in which a transaction writes a lot of intents into two (or more) non-adjacent tables. We definitely want to avoid coagulating key ranges which belong to non-adjacent tables (or even databases). So a workable model would be to bin intents based on their databaseID+tableID prefix (we can do this efficiently) and coagulate only within a bin (while allowing adjacent table's bins to merge, but that's probably premature optimization). We probably also need some balancing between bins: if one bin already has many coagulated key ranges and the other one many individual writes, then we should prefer coagulating point intents over ranges (there are scenarios in which that is worse, but I'd guess they're exceptional) no matter which bin the write goes in.

**Comment by petermattis** [comment]
Support for large transactions is not on the 1.1 roadmap and given that there is not yet a solid design, I'm punting to 1.2.

**Comment by petermattis** [comment]
> To add some more color to the intent coagulation: An interesting case is that in which a transaction writes a lot of intents into two (or more) non-adjacent tables. We definitely want to avoid coagulating key ranges which belong to non-adjacent tables (or even databases). 

Could the intent coagulation (love that term) be done at the range level? This naturally prevents coagulation across table boundaries. `TxnCoordSender` would have to peek into the range descriptor cache or have some other way to understand range boundaries. That doesn't sound horrible.

**Comment by tschottdorf** [comment]
I'm sure we could make that work, though if we tell it enough about our SQL encoding (just a bit) then we can also avoid splitting across table boundaries. That seems a little less involved and if it worked about as good, I think I'd prefer that. Haven't thought about it much, though.

**Comment by dianasaur323** [comment]
If we want to get this done in 1.2, we probably want to track it on the roadmap, especially since it's relatively user facing and I've read a couple user-filed bugs that point to these errors. I've stuck in a placeholder text that others can fill out in Airtable for now with a S t-shirt size. cc @nstewart since this falls under his area.

**Comment by petermattis** [comment]
This is very likely a L or XL size project.

**Comment by cuongdo** [comment]
It's also worth noting that there are short-term workarounds we can develop support for, such as implementing LIMIT for DELETEs.

**Comment by tschottdorf** [comment]
There's a fairly natural hierarchy here, I think.

1. `DELETE ... WHERE predicates LIMIT X`
1. `DELETE ... WHERE predicates NONTRANSACTIONAL`: runs chunked transactions that each leave the touched tables in consistent state. Roughly equivalent to `LIMIT X` in a loop until nothing remains (but hopefully more parallel, faster, etc).
1. make the above more efficient or handy, perhaps masquerading as a schema change and using some of that infrastructure
1. *actual* large transactions. Possibly we'll never ever really need this.

Doing the first two steps doesn't seem too onerous.

**Comment by petermattis** [comment]
Making `DELETE ... WHERE` non-transactional (even with additional syntax) seems surprising. If we want to use the schema change infrastructure for deleting a large number of rows, I'd suggest something using the `ALTER TABLE` syntax. 

My statement about this being an "L or XL size project" was in reference to supporting large transactions. Agreed that there might be some much easier tasks that mitigate that need for large transactions.

**Comment by tschottdorf** [comment]
#21078 has improved the situation, but I'd still call this open, unless we're tracking the remaining work somewhere else?

**Comment by spencerkimball** [comment]
I only meant to mention this issue not close it.

**Comment by netice** [comment]
I  also get  
```
transaction is too large  
```
errors when import data from my app.
I not posibble to commit the transaction beside all data are imported without errors.
is there any solution to deal with this use case? @tbg

**Comment by netice** [comment]
I  also get  
```
transaction is too large  
```
errors when import data from my app.
It is not posibble to commit the transaction besides all data are imported without errors.
Is there any solution to deal with this use case? @knz

**Comment by knz** [comment]
@netice make multiple smaller transactions, or use the IMPORT statement.
