### ISSUE TITLE
Restoring into a non-empty cluster leaves one node in the dust

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#15861]
When performing a restore into a local four-node cluster, I can reliably reproduce rebalancing badness whereby three nodes have an equal number of replicas, but the last node falls way behind. This only happens when the cluster contains data before the restore begins.

The full setup is this. I took the one node, 10GB allocator test data (`gs://cockroach-test/allocatortest/1node-10g-262ranges`), joined three additional nodes to the cluster, and let it balance itself out for about ten minutes until all four nodes had an essentially equal number of replicas and leases. I shutdown the cluster and saved each store's data. In short, this is 10GB of `datablocks.blocks` data, distributed over four nodes, with 3x replication.

Then, I started a new four-node cluster using the same data. After running for 30s, I ran a restore of TPCH data with a scale-factor 10. I'm running a modified cockroach binary that doesn't actually ingest data on RESTORE; it merely performs the requisite splits and scatters.

I did this experiment three times; screenshots of the replication dashboard from each iteration are below.

## Experiment 1 with existing data in the cluster

Note the 30s of balance before the restore begins. Ranges begin splitting at 20:19:49. Scattering begins as 20:20:30. Replicas per store are identical on 57, 61, 63, but 59 sees essentially none of the new replicas. Scatter appears to have no effect.

![screenshot 2017-05-10 16 24 48](https://cloud.githubusercontent.com/assets/882976/25919604/2f0ae638-359d-11e7-8659-3d7b663dbc0f.png)

## Experiment 2 with existing data in the cluster

Similar. I lost the exact times, but ranges appear to have started splitting at 20:26:45 and scattering at 20:27:35. Scattering appears to have some effect. Most notably, it causes a bunch of underreplicated ranges. Yikes!

![screenshot 2017-05-10 16 34 32](https://cloud.githubusercontent.com/assets/882976/25920171/0f54b696-359f-11e7-98c1-94fbbe3872a1.png)

## Experiment 3 with existing data in the cluster

Ranges begin splitting at 20:37:50. Scattering begins at 16:38:30. Scatter actually seems to do a decent job, though again causes massive underreplication and only impacts three of the nodes.

![screenshot 2017-05-10 16 41 25](https://cloud.githubusercontent.com/assets/882976/25920309/875d86e0-359f-11e7-9b86-f7119f3ebadf.png)

Now for the weird part. Without existing blockwriter data in the cluster, the ranges are split perfectly evenly across all four nodes. Then scatter runs, which unbalances the replicas and causes massive underreplication to boot.

In the following three experiments, the setup is the same as above, except that the cluster has no data at the start.

## Experiment 1 without existing data in the cluster

Splitting begins at 20:45:14. Scattering begins at 20:45:55.

![screenshot 2017-05-10 16 49 19](https://cloud.githubusercontent.com/assets/882976/25920646/a5ce214c-35a0-11e7-9af9-8c226ad55e3e.png)

## Experiment 2 without existing data in the cluster
Splitting begins at 20:51:03. Scattering begins at 20:51:44.

![screenshot 2017-05-10 16 55 15](https://cloud.githubusercontent.com/assets/882976/25920910/73922272-35a1-11e7-942f-21dce56b39ff.png)

## Experiment 3 without existing data in the cluster
Splitting begins at 20:58:28. Scattering begins at 20:59:09.

![screenshot 2017-05-10 17 02 02](https://cloud.githubusercontent.com/assets/882976/25921146/628ad748-35a2-11e7-9873-25358ce9d4f4.png)

@a-robinson, would you mind triaging? Would love to know if someone has insight into why this performs so much better with no existing data. 

/cc @danhhz

**Comment by danhhz** [comment]
In particular, I believe the "this" that @benesch is referring to in "insight into why this performs so much better with no existing data" is the balance of replicas and leaseholders during the pre-split and before scatter. (Scatter is best-effort at the moment and I'm fairly sure all its various problems are because it's best-effort, so I wouldn't read too much into that part.)

**Comment by a-robinson** [comment]
Do you have logs from any of these runs? They look as if the node isn't even being considered during rebalancing, which could be related to the discussion in #14955 about how a store can be "throttled" from further replicate queue actions for a little while.

**Comment by benesch** [comment]
I don't, but I can easily re-run a with-existing-data experiment!

**Comment by a-robinson** [comment]
Let's do that then, and we might as well turn the logging verbosity up a couple notches while we're at it.

**Comment by benesch** [comment]
Sorry to make you follow up. I meant to get this to you last night but ran
out of time. I'm mostly OOO today, but should be able to get you the logs
by this afternoon. Do you have a desired log verbosity/vmodule
specification?

**Comment by a-robinson** [comment]
Turning it up across the board wouldn't be terrible, but if you want a more focused invocation then I'd try `--vmodule=allocator=3,replicate_queue=3,queue=3,store=2,replica_command=2,replica=1`

**Comment by benesch** [comment]
Ok, here's a debug zip from a new run of a with-existing-data experiment:

[gh15861.zip](https://github.com/cockroachdb/cockroach/files/993709/gh15861.zip)

FYI the binary I'm running has some additional logging, plus an early return during `RESTORE` to avoid actually ingesting any data. Patch:

```diff
diff --git a/pkg/ccl/sqlccl/restore.go b/pkg/ccl/sqlccl/restore.go
index 0b59c33f8..77b4b9e96 100644
--- a/pkg/ccl/sqlccl/restore.go
+++ b/pkg/ccl/sqlccl/restore.go
@@ -686,6 +686,9 @@ func Restore(
 	if err != nil {
 		return 0, errors.Wrapf(err, "making import requests for %d backups", len(backupDescs))
 	}
+	if log.V(1) {
+		log.Infof(ctx, "making import requests for %d backups", len(backupDescs))
+	}
 
 	for _, desc := range newTableIDs {
 		jobLogger.Job.DescriptorIDs = append(jobLogger.Job.DescriptorIDs, desc)
@@ -713,6 +716,9 @@ func Restore(
 			return 0, errors.Errorf("failed to rewrite key: %s", r.Key)
 		}
 	}
+	if log.V(1) {
+		log.Infof(ctx, "presplitting %d ranges", len(importRequests))
+	}
 	if err := presplitRanges(ctx, db, splitKeys); err != nil {
 		return 0, errors.Wrapf(err, "presplitting %d ranges", len(importRequests))
 	}
@@ -725,6 +731,9 @@ func Restore(
 				req := &roachpb.AdminScatterRequest{
 					Span: roachpb.Span{Key: span.Key, EndKey: span.EndKey},
 				}
+				if log.V(1) {
+					log.Infof(ctx, "scattering range %+v", req.Span)
+				}
 				res, pErr := client.SendWrapped(gCtx, db.GetSender(), req)
 				if pErr != nil {
 					return pErr.GoError()
@@ -744,6 +753,7 @@ func Restore(
 			return 0, errors.Wrapf(err, "scattering %d ranges", len(importRequests))
 		}
 	}
+	return 0, nil
 
 	// We're already limiting these on the server-side, but sending all the
 	// Import requests at once would fill up distsender/grpc/something and cause
diff --git a/pkg/storage/allocator.go b/pkg/storage/allocator.go
index 9c3bcf038..2cb8284dc 100644
--- a/pkg/storage/allocator.go
+++ b/pkg/storage/allocator.go
@@ -383,6 +383,10 @@ func (a Allocator) RebalanceTarget(
 	// also affects tests.
 	newQuorum := computeQuorum(len(existing) + 1)
 	if len(existing) > 1 && len(existingCandidates) < newQuorum {
+		log.Infof(ctx,
+			"not rebalancing because won't be able to make quorum (existing %d, existingCandidates %d, newQuorum %d)",
+			len(existing), len(existingCandidates), newQuorum,
+		)
 		// Don't rebalance as we won't be able to make quorum after the rebalance
 		// until the new replica has been caught up.
 		return nil, nil
@@ -390,6 +394,7 @@ func (a Allocator) RebalanceTarget(
 
 	// No need to rebalance.
 	if len(existingCandidates) == 0 {
+		log.Infof(ctx, "not rebalancing because no existing targets")
 		return nil, nil
 	}
```

**Comment by benesch** [comment]
If I'm not mistaken, node 2 got left behind this time around.

**Comment by a-robinson** [comment]
Thanks, taking a look.

**Comment by a-robinson** [comment]
Well, at the time the zip was taken, things look pretty even:

```console
~/nikhil/debug/nodes 0 $ grep range_count */status
1/status:          "range_count": 841,
2/status:          "range_count": 804,
3/status:          "range_count": 849,
4/status:          "range_count": 841,
~/nikhil/debug/nodes 0 $ grep lease_count */status
1/status:          "lease_count": 255
2/status:          "lease_count": 245
3/status:          "lease_count": 248
4/status:          "lease_count": 265
```

**Comment by a-robinson** [comment]
Also:

```
~/nikhil/debug/nodes 128 $ grep underrep */status
1/status:        "ranges.underreplicated": 0,
2/status:        "ranges.underreplicated": 0,
3/status:        "ranges.underreplicated": 0,
4/status:        "ranges.underreplicated": 0,
```

So I'm guessing you did the zip after things had stabilized.

But it does look like `StorePool` throttling was an issue. Nodes 1 and 4 have a lot of log messages indicating that some of the candidate stores were throttled. We need to do something about `Scatter` running into store throttling, since it seems to be a very common occurrence. It's odd that it's more prevalent on clusters with existing data, though. Was there existing activity in the replicate queue ongoing when you started the restore?

And as a side note, I kind of butchered the vmodule flags. The beginning of the logs got truncated because I specified too much (particularly `replica_command`), and I missed the logs from the store pool about actually starting the throttling. If we were to do it again, I'd probably use `--vmodule=allocator=3,replicate_queue=3,queue=3,store_pool=2,store=2,,replica=1`.

**Comment by benesch** [comment]
Thanks again for looking into this, @a-robinson, and sorry I've been MIA since Thursday. I've pushed the scripts I've been using to https://github.com/benesch/crdb-playground-scatter in case you have a burning desire to run one of these experiments yourself.

Re-running an experiment now with the modified vmodule spec to answer your question about the replicate queue!

**Comment by benesch** [comment]
No existing activity in the replicate queue!

![screenshot 2017-05-15 11 04 22](https://cloud.githubusercontent.com/assets/882976/26064191/4039dcba-395e-11e7-9f1c-50b7e954936a.png)

![screenshot 2017-05-15 11 04 48](https://cloud.githubusercontent.com/assets/882976/26064208/4906d294-395e-11e7-8042-6528dd73c8d6.png)

Generated a debug zip around 15:03:30 this time.

[debug.zip](https://github.com/cockroachdb/cockroach/files/1001464/debug.zip)

Looking through the logs myself now. I believe node 2 got left behind this time around.

**Comment by a-robinson** [comment]
Have you been running all these experiments without wiping the disk? All these nodes have logs going back to May 10, with every restart using the same cluster ID. After you brought it up for this run, node 2 crashed twice with the error

```
F170515 11:00:39.089105 63 storage/replica.go:1353  [n2,s2,r331/3:/System/{-tsd}] on-disk and in-memory state diverged:
```

Although, beyond that, the latest zip indicates part of what was going on. Node 2 started streaming a 46MB preemptive snapshot to node 3 right around when the scatter happened, and that snapshot took 20 seconds. Shortly after it finished that snapshot, it started streaming another 40MB preemptive snapshot to node 3 which took another 18 seconds. After those two snapshots, it was way behind the other three nodes. While I'm not sure there's specific evidence in the logs of it, presumably the reason node 3 didn't lag behind in number of replicas is that it had a member of the range that kept getting split, and thus didn't need to be rebalanced to in order to have a large number of replicas.

There's clearly work to be done to "ruggedize" Scatter, but I'm not sure how much to take away from these single-machine experiments where there may have been interference slowing down snapshots. I'll dig in more tomorrow.

**Comment by tschottdorf** [comment]
@benesch and I chatted about this today, and I think we understood the behavior, so better check in with him before you duplicate effort!

**Comment by a-robinson** [comment]
Thanks for the heads up, let's chat tomorrow @benesch.

**Comment by benesch** [comment]
Yeah, that was exactly the conclusion that @tschottdorf and I came to during core office hours today! 
Considering snapshots are limited to 2MB/s taking 20s to transfer a 40MB snapshot sounds exactly right. Thanks for all your help, @a-robinson. I'm not sure it's worth digging in to this particular problem further.

Would you have time tomorrow to discuss how we can make scatter more effective without interfering with the replication queue?

**Comment by a-robinson** [comment]
Yup, let's talk tomorrow!

**Comment by tschottdorf** [comment]
to publicize one of the gists of the discussion briefly: when you have previous data in the cluster, the splits for the new import all hit one range of the previous data (usually the first or the last, since they have different table prefixes) and so one range will turn into many, and the nodes that have that range then suddenly have a lot more. The imbalance is then slow to go away because a cluster that actually has data will have many rebalances that actually move data, and then get throttled. If the cluster is initially empty, the rebalance queue never tries to move a lot of data and hence does not get throttled.
