### ISSUE TITLE
DB doesn't start again. --insecure

### ISSUE THREAD

**Issue by atilkan** [cockroachdb/cockroach#15889]
I am testing version 1 by following through [documentation](https://www.cockroachlabs.com/docs/start-a-local-cluster.html) and after stopping, it doesn't start again.

**Steps i did as docs says:**
- I created a node.
- I added 2 more nodes. 
- I inserted some record.
- I stopped first node `cockroach quit --insecure`
- I stopped other node `cockroach quit --insecure --port=26258`
- I stopped the other node by kill command. Search `ps | grep cockroach` and `kill -9 <the ps id>` (What is -9 flag does here.)

When i try to follow first steps again it gives errors.
![screen shot 2017-05-12 at 14 44 48](https://cloud.githubusercontent.com/assets/1254613/25998200/85508a2a-3728-11e7-99f2-cc2e88d69fcc.png)

**Comment by tamird** [comment]
@atilkan it seems you didn't pass `--insecure` the second time. Could you try that?

**Comment by atilkan** [comment]
@tamird That is my point. It doesn't start neither you pass it or not. Tried again anyways and, well, surprise. It gives the same error.

**Comment by mberhault** [comment]
It looks like the first call (with `--insecure`) worked fine. The `WARNING: running in insecure mode` is only a warning, the server should have started up.
The `CTRL-C` shows that you then stopped it manually.

The second call failed because you did not pass `--insecure` and cockroach could not find certificates.

**Comment by atilkan** [comment]
@mberhault But it doesn't exit from where it enters looks like sub shell. 
![screen shot 2017-05-12 at 16 34 52](https://cloud.githubusercontent.com/assets/1254613/26000145/7ba7128e-3730-11e7-957f-e3398b39e86a.png)

**Comment by mberhault** [comment]
Ah, that part is a little odd. What system are you running on? (OS, version, kernel, etc..).
Are there any logs in `cockroach-data/logs/`? If so, could you attach them here.

Thank you.

**Comment by a-robinson** [comment]
It's not starting because a node requires a quorum of nodes to be running before it can finish the startup process. Because you at one point had three nodes in your cluster, you're going to need to have two nodes running before either can successfully start up again. If you were to also start one of the other nodes in a separate terminal, they should both successfully finish coming up

**Comment by a-robinson** [comment]
cc @jseldess since I'm not sure how well this is documented or what we should be doing better here.

**Comment by jseldess** [comment]
Thanks, @a-robinson. Perhaps, to make this clearer, we should add another "restart the cluster" step to the tutorial. I avoided this initial so as to keep the tutorial lean, but this question is an important one and likely to come up more. Thoughts?

**Comment by atilkan** [comment]
@a-robinson Thank you. I understand now. 
I did nothing more than docs says. I just tried to do it again. 
Should i share my logs? There are lots of them. 
![screen shot 2017-05-12 at 17 09 04](https://cloud.githubusercontent.com/assets/1254613/26001461/21e939f2-3735-11e7-81bc-fe90ba86df06.png)

**Comment by a-robinson** [comment]
@atilkan are you saying that trying to start two nodes at once didn't work? If so, I'd be interested in the logs.

@jseldess perhaps we should, or add it to the FAQ and link to it at the end of the tutorial. This is at least the second, I think the third, time that I've seen someone get confused by it.

**Comment by atilkan** [comment]
@a-robinson I think users get confused because Error Message doesn't explain the situation. I did not start two node at once. I am looking to it, guess that is the only way to start at this point.

Here my logs: 
https://www.dropbox.com/sh/m9ep32ciue5s751/AADsxO6ZsJlEPI4UExrAQTeJa?dl=0

**Comment by jseldess** [comment]
Added a [docs issue](https://github.com/cockroachdb/docs/issues/1403) to improve the Start a Cluster tutorial.

**Comment by a-robinson** [comment]
Yup, and we should do more to improve the experience for folks who aren't looking at the docs as well. I've opened #15894 for that.

Thanks a bunch for your feedback here, @atilkan! Can you close the issue if you're able to get the cluster running by starting two nodes at once? I'll make sure we follow up on #15894 and @jseldess is on top of the docs issue.

**Comment by bdarnell** [comment]
`--background` has some subtle properties that mean it's probably not what you want most of the time (so it's unfortunate that we use it so heavily in our docs). It's designed for one purpose: testing frameworks in which you want to start a single server and wait for it to become ready before continuing. In multi-node clusters, you probably want to use the shell's `&` instead of `--background` (or run everything in the foreground of different shells).

**Comment by atilkan** [comment]
@bdarnell You should definitely make your examples as close as to the real world situations. Or alternatively make some videos, might.
@a-robinson  I am closing  this now. Thanks.

**Comment by jseldess** [comment]
@bdarnell, I'll experiment with removing the `--background` flag from the quickstart docs.
