### ISSUE TITLE
sql/parser: scanner does not support e'\\xDEADBEEF` binary input format

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#15880]
The test case in https://gist.github.com/davestgermain/7eae5c1b148a1e0dfa09d3818fdd1cfb (run with python 3.6 and psycopg2 2.7.1) shows that binary data is getting returned as a SQL hex-encoded string (`\\xffd8ffe00010`), and the python psycopg2 driver doesn't know how to decode that back to the raw bytes. I'm not sure at what level things are going wrong, but the test works as expected when run against postgresql.

**Comment by bdarnell** [comment]
Further testing has revealed that the data is being converted to an escaped string on *input*, not output. 

```
root@:26257/> SELECT * FROM test.test_bt;
+----------------+
|       v        |
+----------------+
| \xffd8ffe00010 |
+----------------+
(1 row)
```

**Comment by jordanlewis** [comment]
Simplified test case in https://gist.github.com/jordanlewis/d36d6cf455fe2ba64dd51c47112271a5 shows that the table is not important - even `SELECT %s::BYTEA` produces the issue.

**Comment by davestgermain** [comment]
`Cursor.mogrify` will show you the query sent to the server:

    print(c.mogrify('select %s', (b'hi',)))
    b"select '\\x6869'::bytea"`

**Comment by jordanlewis** [comment]
Thanks, @davestgermain!

I believe the trouble is that we do not support the Postgres `bytea Hex format` detailed in section 8.4.1 of [the Binary Data Type documentation](https://www.postgresql.org/docs/9.1/static/datatype-binary.html).

This input format causes strings of the form `e'\\xDEADBEEF'` to be parsed the same as the hexadecimal literal equivalent, `\x'DEADBEEF'`.

**Comment by davestgermain** [comment]
@jordanlewis The [psycopg2 documentation](http://initd.org/psycopg/docs/faq.html) has a recommendation: 

> * set the bytea_output parameter to escape in the server;
> * execute the database command SET bytea_output TO escape; in the session before reading binary data;

Unfortunately, cockroachdb doesn't support those parameters.

**Comment by jordanlewis** [comment]
Thanks - I don't think that would solve your problem even if we supported it, though, because it seems like that parameter controls the output escaping, not the input escaping as we'd need here.

It won't be too hard for us to add support for that input format.

In the meantime, you should be able to work around this issue by sending the bytes in the `x'DEADBEEF'` format.

**Comment by davestgermain** [comment]
I'm assuming that the conversion is happening either in the psycopg2 C module, or in libpq. How would I force psycopg2 to send the bytes in the escaped format?

By the way, the documentation says that the hex format has been the default since postgresql 9.0, which was released 7 years ago...

**Comment by jordanlewis** [comment]
I'm not sure how to force psycopg2 to send the bytes in the escaped format. I was thinking that you could do the translation yourself, in Python, and send the result to Postgres:

```
c.execute('SELECT %s::BYTEA', "\\x'%s'" % b'\xff\xd8\xff\xe0\x00\x10'.hex())
```

I'm sorry you're encountering this difficulty! It's certainly true that we should support this input format since it's the default, as you say.

**Comment by cuongdo** [comment]
assigning to @vivekmenezes for triage
