### ISSUE TITLE
rsg: parse -> format round trip needs normalization

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15926]
From a recent failure:

`rsg_test.go:294: Parse followed by Format is not idempotent: "SELECT EXISTS (TABLE repeatable.*.*) AS ident FROM ((over@cluster WITH ORDINALITY AS by NATURAL LEFT JOIN [EXPLAIN (IDENT) DROP DATABASE IF EXISTS ident] WITH ORDINALITY AS \"decimal\" (strict, value))) WITH ORDINALITY AS deallocate (following, ident, \"nullif\") AS OF SYSTEM TIME false WHERE ARRAY[ARRAY[ARRAY[]], ARRAY[], ARRAY[ARRAY[ARRAY[ARRAY[], ARRAY[]]]]]" != "SELECT EXISTS (TABLE repeatable.*.*) AS ident FROM (over@cluster WITH ORDINALITY AS by NATURAL LEFT JOIN [EXPLAIN (IDENT) DROP DATABASE IF EXISTS ident] WITH ORDINALITY AS \"decimal\" (strict, value)) WITH ORDINALITY AS deallocate (following, ident, \"nullif\") AS OF SYSTEM TIME false WHERE ARRAY[ARRAY[ARRAY[]], ARRAY[], ARRAY[ARRAY[ARRAY[ARRAY[], ARRAY[]]]]]"`

**Comment by eisenstatdavid** [comment]
More `TableExpr` misery -- the parens are off. I can think of three solutions, ordered by how much I like them descending.

1. Change the `| '(' joined_table ')' opt_ordinality alias_clause` production in `sql.y` to use a `ParenTableExpr`. Remove the special case in `AliasedTableExpr` to emit parens for a join subexpression. I like that this is "obviously" correct; I dislike that this can't serialize arbitrary ASTs properly.

2. Normalize matching multiple parens to single parens in `rsg_test.go`. I like this because it's non-invasive; I dislike this because parse followed by format really shouldn't be messing with parens.

3. Remove `ParenTableExpr` entirely. Modify the formatting to emit parens as needed (effectively normalizing paren usage for table expressions). I dislike this because it seems error prone given the complexity of the table expression grammar.

What do you think?
