### ISSUE TITLE
sql: cannot drop database with view that contains a union

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#15953]
When a db contains a view with a union the db cannot be deleted without deleting the view first, the following sql replicates.

```
CREATE DATABASE DbWithView;
SET DATABASE  = DbWithView;

CREATE TABLE Test (a int, b int);
CREATE VIEW "Test View" AS SELECT a, b FROM Test UNION SELECT a, b FROM Test;

DROP DATABASE DbWithView;
```

It just says `XX000: table "Test View" is being dropped`

**Comment by jordanlewis** [comment]
Sorry you're encountering this difficulty and thanks for the nice report. As a workaround, if you drop the view, you should be able to successfully drop the database even after you've gotten into this state.

This problem also occurs when a view depends on more than one table:

```
root@:26257/test4> create database test4;
CREATE DATABASE
root@:26257/test4> create table test (a int);
CREATE TABLE
root@:26257/test4> create table test2 (b int);
CREATE TABLE
root@:26257/test4> create view v as SELECT test.a, test2.b FROM test, test2;
CREATE VIEW
root@:26257/test4> drop database test4;
pq: table "v" is being dropped
```

There are two problems here. In the first case, the problem is that the table descriptor got a duplicate `DependedOnBy` entry for this view, causing the drop code to try to drop the view twice. In the second case, the proximal cause is revealed, which is that we try to drop a view even if it's already been dropped during another `DROP TABLE` operation within the `DROP DATABASE`.

**Comment by jrote1** [comment]
@jordanlewis Sorry yeah this does happen with two different as you found above this is how i discovered it. This was just the easiest way to replicate that I found. Thanks for the quick fix do you think this will make it into the next release?

**Comment by jordanlewis** [comment]
It'll likely land in 1.0.1, yes.
