### ISSUE TITLE
Some nodes hang when performing a query

### ISSUE THREAD

**Issue by jethrogb** [cockroachdb/cockroach#16007]
My cluster is in a state where everything appears to be working fine, and some nodes do work fine, but on others queries hang indefinitely.

```
I170517 13:33:27.984347 222 util/log/clog.go:908  [config] file created at: 2017/05/17 13:33:27
I170517 13:33:27.984347 222 util/log/clog.go:908  [config] running on machine: us-west-eqsv2-1
I170517 13:33:27.984347 222 util/log/clog.go:908  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170517 13:33:27.984347 222 util/log/clog.go:908  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --advertise-host 10.197.64.1]

I170517 13:32:47.873543 187 util/log/clog.go:908  [config] file created at: 2017/05/17 13:32:47
I170517 13:32:47.873543 187 util/log/clog.go:908  [config] running on machine: us-west-eqsv2-2
I170517 13:32:47.873543 187 util/log/clog.go:908  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170517 13:32:47.873543 187 util/log/clog.go:908  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --join 10.197.64.1 --advertise-host 10.197.64.2 --verbosity 10]

I170517 12:04:19.651918 1 util/log/clog.go:1011  [config] file created at: 2017/05/17 12:04:19
I170517 12:04:19.651918 1 util/log/clog.go:1011  [config] running on machine: us-west-eqsv2-3
I170517 12:04:19.651918 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170517 12:04:19.651918 1 util/log/clog.go:1011  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --join 10.197.64.1 --advertise-host 10.197.64.3]

I170517 03:17:35.445846 1189 util/log/clog.go:908  [config] file created at: 2017/05/17 03:17:35
I170517 03:17:35.445846 1189 util/log/clog.go:908  [config] running on machine: us-west-eqsv2-4
I170517 03:17:35.445846 1189 util/log/clog.go:908  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170517 03:17:35.445846 1189 util/log/clog.go:908  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --join 10.197.64.1 --advertise-host 10.197.64.4]

I170515 14:50:28.026651 1 util/log/clog.go:1011  [config] file created at: 2017/05/15 14:50:28
I170515 14:50:28.026651 1 util/log/clog.go:1011  [config] running on machine: us-west-eqsv2-5
I170515 14:50:28.026651 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170515 14:50:28.026651 1 util/log/clog.go:1011  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --join 10.197.64.1 --advertise-host 10.197.64.5]

I170515 14:50:31.725435 1 util/log/clog.go:1011  [config] file created at: 2017/05/15 14:50:31
I170515 14:50:31.725435 1 util/log/clog.go:1011  [config] running on machine: us-west-eqsv2-6
I170515 14:50:31.725435 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170515 14:50:31.725435 1 util/log/clog.go:1011  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --join 10.197.64.1 --advertise-host 10.197.64.6]
```

Log from a node that has this issue (query used is SHOW DATABASES): [log.zip](https://github.com/cockroachdb/cockroach/files/1009070/log.zip) with vmodule set to v3=4,types=4,txn_coord_sender=4,txn=4,tablereader=4,table=4,store_pool=4,store=4,split_queue=4,session_mem_usage=4,session=4,server=4,scanner=4,runtime=4,rule_solver=4,replicate_queue=4,replica_raftstorage=4,replica_command=4,replica=4,recorder=4,range_iter=4,raft_log_queue=4,raft=4,queue=4,planner=4,node_liveness=4,mvcc=4,mem_usage=4,log=4,gossip=4,flow=4,executor_statement_metrics=4,executor=4,db=4,clog=4,clock_offset=4,allocator=4.

**Comment by petermattis** [comment]
@a-robinson Can you take a look?

**Comment by a-robinson** [comment]
Yup, looking.

**Comment by a-robinson** [comment]
Thanks for the logs, @jethrogb. I can't quite tell what's going on from just this 4 minute chunk of logs and what you've told me. The two interesting things I see are that

1. The range that contains the data descriptors currently has 4 replicas rather than 3. That doesn't break anything by itself, but a range normally shouldn't be in that situation for long.
1. Something appears to have happened to node/store 3. Multiple attempts to split a timeseries range have failed with the error that "store 3 was not found". It's worth noting that the timeseries range in question also has 4 replicas rather than 3.

Would you mind sharing logs from the other nodes, and for a wider time range rather than just one file?

**Comment by a-robinson** [comment]
You haven't been changing the addresses or advertised addresses of the nodes, have you?
 
The underlying issue here is a confusion of identity. Somehow the cluster has gotten into a state where:

* The node on the `...-3` hostname has node ID and store ID 6
* The node on the `...-4` hostname has node ID and store ID 3
* The gossip network appears to have gotten confused and decided that store 3 is located at the `...-3` node's address, so all attempts to talk to store 3 are being sent to `...-3`.
* The `...-4` host (i.e. the real node 3) has the lease for the range needed to serve your request, but since some of the nodes think the storeID 3 is on the `...-3` host, requests for it are failing.

Because your nodes' logging verbosity is up so high, the place where this trouble first happened has been mostly rotated away. There may be more going on than just this, but this is pretty odd.

It'd be great to see the contents of the `http://<address>:8080/debug/gossip/local` page for each node so I could inspect exactly what's happened to the gossip network. If addresses have been getting changed around or the network has been behaving strangely, it's possible that something has gone wrong (and that #15928 would have prevented it).

After you grab the gossip info, I think that the cluster may fix itself if you were to just restart all the nodes to clear up the confusion.

**Comment by jethrogb** [comment]
I assume you mean `/_status/gossip/local`?

Output here: [gossip.zip](https://github.com/cockroachdb/cockroach/files/1012296/gossip.zip)

I don't *think* we ran with the same cockroach-data directory and different `--host --advertise-host` parameters on the same host. However there were some issues getting the cluster to work at all after upgrading to 1.0, forcing specification of those command-line parameters where that wasn't necessary in some beta version we were using before.

**Comment by jethrogb** [comment]
I think what might have happened is the original master node was restarted at some point without `--join`

**Comment by a-robinson** [comment]
Judging by the gossip info, all the nodes have the same cluster ID, so it actually doesn't look like that was the cause. At this point I do think it's most likely that the `--advertise-host` parameters got changed around in ways that messed with the gossip network (or, less likely, something is messed up with your network).

If you can remember or look up what command-line changes you made, I'd be very interested. Otherwise, I don't think we can get any more info out of the running cluster, so want to try restarting all the processes?

**Comment by jethrogb** [comment]
Proposing to close this? I have been unable to reproduce since and you don't have enough logs to fix bugs (if any).

**Comment by a-robinson** [comment]
Yeah, I think so. Thanks for reporting your problem and following up!
