### ISSUE TITLE
storage: larger command size amplification for keys

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#16075]
Most likely not a bug, posted here as suggested by @tschottdorf to just cross check why the following behavior is so.

For the following minimal test case (add to any of the `pkg/storage/client_*_test.go` files):
```go
func TestCommandSizeAmplification(t *testing.T) {
	defer leaktest.AfterTest(t)()

	const rangeID = 1
	mtc := &multiTestContext{}
	mtc.Start(t, 1)
	defer mtc.Stop()

	ctx := context.Background()
	repl := mtc.getRaftLeader(rangeID)
	big := bytes.Repeat([]byte("a"), 10000)
	small := []byte("a")

	if _, pErr := client.SendWrapped(ctx, repl, putArgs(small, big)); pErr != nil {
		t.Fatal(pErr)
	}

	if _, pErr := client.SendWrapped(ctx, repl, putArgs(big, small)); pErr != nil {
		t.Fatal(pErr)
	}
}
```

And the following debug statement in `Replica.propose` after `proposal, pErr := r.requestToProposal(ctx, idKey, ba, endCmds, spans)`
```
	log.Infof(ctx, "CMD SIZE: %d", proposal.command.Size())
```

We get the following:
```
I170522 19:09:19.572545 10 storage/replica.go:2677  [s1,r1/1:/M{in-ax}] CMD SIZE: 10361
I170522 19:09:19.573194 10 storage/replica.go:2677  [s1,r1/1:/M{in-ax}] CMD SIZE: 30362
```

Note that for keys there's ~3x factor blow up in command size. This may not be an issue if we don't have large keys but it isn't immediately obvious why this is the case.

**Comment by petermattis** [comment]
For a put request, we store the key 3 times in the resulting `RaftCommand`:
1. `RaftCommand.WriteBatch`
2. `RaftCommand.ReplicatedEvalResult.StartKey`
3. `RaftCommand.ReplicatedEvalResult.EndKey`

**Comment by irfansharif** [comment]
Feel free to close if this isn't something we're looking to condense.

**Comment by tschottdorf** [comment]
One use of the key span (there may be more) downstream of Raft is to return a `RangeKeyMismatchError` for requests whose span reaches outside the range. I *think* that's a situation that we can avoid (if we don't already do it today) since a proposal with that issue would have to be issued from the lease holder, and the lease holder would have had to have issued a split before, but that split should block the key range in the command queue, after which the mismatching request would've seen it's out of bounds before entering Raft. (If it doesn't happen today, making a downstream of Raft change should be safe).

**Comment by bdarnell** [comment]
Yes, that's all those fields are used for (they're recently added). I'm not sure whether it's possible for this to occur or if it's already prevented by other safeguards. The fact that splits block the entire range in the command queue is unfortunate and we may want to change that at some point, although there's only so much we can do here (splits unavoidably interfere with writes on the RHS, so it's just a question of what we do on the LHS).

We could avoid the size blowup by adding a sequence number to the range descriptor that gets incremented on any change and pass that instead.

**Comment by tschottdorf** [comment]
This could be a good (starter) issue for someone diving into core internals as the actual change would be fairly small, but a good understanding of proposer-evaluated KV is necessary (and obtaining it would thus be incentivized).

**Comment by petermattis** [comment]
Is the proposal here to add a `RangeDescriptor.sequence_num` field? The only major complication would be that we'd still have to pass `ReplicatedEvalResult.{Start,End}Key` until all nodes in the cluster have been upgraded. I haven't had exposure to the version upgrade mechanism yet, but hopefully this isn't too difficult.

We should also add `Lease.sequence_num` for checking lease validity down-stream of Raft. My [observation](https://github.com/cockroachdb/cockroach/issues/18659#issuecomment-331250341) in #18659 that we only need the epoch number for epoch-based leases was incorrect as `Lease.Equivalent` also checks the start timestamp and replica descriptor.

**Comment by bdarnell** [comment]
There's a theory that we can just remove these fields because the situation they're designed to prevent is already prevented by the command queue. This needs further investigation. If we do need to keep some sort of validation here, then the best way is probably to introduce a RangeDescriptor.sequence_num. (which would have been easy to do up front; now the hard part is the migration)

**Comment by petermattis** [comment]
Just removing `{Start,End}Key` would also require a dance with the cluster version as old binaries require those fields to be set. Any clues on how to verify that they aren't necessary?

**Comment by bdarnell** [comment]
Removing them would be a simple use of the cluster version setting. Introducing sequence numbers may or may not be more complicated.

**Comment by petermattis** [comment]
As a data point, adding a fatal error when `requestCanProceed()` fails in `Replica.processRaftCommand` due to the range span not containing the request span never fires for any of our tests (i.e. `make test`).

That said, I think I'd be more comfortable adding a sequencer to `roachpb.RangeDescriptor` as it feels more future proof. My thought for doing this is to add a `RangeDescriptor.split_sequencer` field. The sequencer would be incremented during a split. A change replicas operation would initialize the sequencer to `1` if it wasn't set, otherwise it would leave the value unchanged. Raft proposals would continue to send the `{Start,End}Key` until a new `VersionRangeDescriptorSplitSequencer` version is active. 

The upshot is that existing clusters would slowly add split sequencers to range descriptors as ranges rebalanced and split. This would happen as soon as the new binaries were added to the cluster. Old binaries will naturally ignore the sequencer, stripping it from `RangeDescriptors` during splits and rebalances.

Please poke holes in the above. I'd like to do something similar for `roachpb.Lease` by adding a `Lease.sequencer` field so that we can replace `RaftCommand.proposer_lease` with `RaftCommand.proposer_lease_sequencer`.

**Comment by bdarnell** [comment]
The sequencer idea seems sound to me, although I don't think we need to initialize it to 1 on ChangeReplicas. Just let it default to zero and set it to 1 for the first split performed by a version aware of this field.

**Comment by petermattis** [comment]
Yes, we don't need to initialize the sequencer to 1 on ChangeReplicas. I added that in order to speed up the addition of sequencers because rebalancing is more common than splitting. The extra complexity may not be worth it.

**Comment by petermattis** [comment]
@nvanbenschoten this is done, right?

**Comment by nvanbenschoten** [comment]
I have been sitting on https://github.com/cockroachdb/cockroach/pull/20647 to give the assertion it removes time to catch any logic errors. It's been over a month and it hasn't fired. I'll merge it today and close this issue.

**Comment by nvanbenschoten** [comment]
Closed via https://github.com/cockroachdb/cockroach/pull/20647 and https://github.com/cockroachdb/cockroach/pull/20953.
