### ISSUE TITLE
Graphs do not display in secure mode

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#1609]
In the admin UI, Graph queries do not work in secure mode (i.e. the normal mode without `--insecure`).   An SSL error is returned instead.

**Comment by MBerhault** [comment]
In secure mode, we require valid certs, although we do not yet check the
user:
server/server.go:
s.mux.HandleFunc(ts.URLPrefix, s.authenticateRequest(s.tsServer))

**Comment by mrtracy** [comment]
I can't figure out how to get the browser to send a client certificate; is there a way for the server to ASK for a client certificate as part of the TLS process?  I think that might be necessary for this to work in the browser.

**Comment by tamird** [comment]
FWIW this isn't an SSL error, it's a 401 unauthorized.

**Comment by MBerhault** [comment]
Certificates are a massive pain in browsers. They need to be added
manually. The appropriate client cert is then chosen at request time (and
usually prompt for the passphrase).

In this case, we need to remove the certificate check on those endpoints
and use cookie-based authentication when we have it.
I put those in there because I didn't think javascript was calling the TS
endpoints directly, I figured it was an internal thing only for now.

**Comment by MBerhault** [comment]
Should be fixed now.
