### ISSUE TITLE
tracing: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#16107]
Reverting d54dd9396a151d137e03eff6c4732c366450a67b fixes this so looks like a regression.

I'm able to repro at master with `make test PKG=./pkg/ccl/sqlccl TESTS=Local`

The panic is at
```
goroutine 2436 [running]:
runtime.throw(0x5577859, 0x21)
	/usr/local/Cellar/cockroach-go/1.8/libexec/src/runtime/panic.go:596 +0x95 fp=0xc422f37fe8 sp=0xc422f37fc8
runtime.mapaccess1_faststr(0x53809c0, 0xc422363ad0, 0x554da4a, 0x2, 0xc423081200)
	/usr/local/Cellar/cockroach-go/1.8/libexec/src/runtime/hashmap_fast.go:217 +0x4cf fp=0xc422f38048 sp=0xc422f37fe8
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Tracer).StartSpan(0xc42008e400, 0x55667e3, 0x16, 0xc4231052f0, 0x1, 0x1, 0xc420b06820, 0xc422f383f8)
	/Users/dan/Dropbox/Projects/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:143 +0x222 fp=0xc422f383a8 sp=0xc422f38048
github.com/cockroachdb/cockroach/pkg/util/tracing.ForkCtxSpan(0x6fbb900, 0xc42147de00, 0x55667e3, 0x16, 0x556e649, 0x1b, 0xc422f388b8, 0x3)
	/Users/dan/Dropbox/Projects/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:348 +0x17d fp=0xc422f38448 sp=0xc422f383a8
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc42218acd0, 0x6fbb900, 0xc42147de00, 0xc422f84000)
	/Users/dan/Dropbox/Projects/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:234 +0xf0 fp=0xc422f384a8 sp=0xc422f38448
```

**Comment by RaduBerinde** [comment]
We need to copy the baggage map in span.Context. Should be an easy fix, unfortunately I'm out until Mon. Maybe @andreimatei has a bit of time.

**Comment by danhhz** [comment]
Aha. Disabling tracing works around this, so there's no rush from my end

**Comment by andreimatei** [comment]
Do you need to stress `TestBackupRestoreLocal` to repro? Or how come it's not a problem on TC?
Even stress doesn't do it for me yet...

In any case, looking.

**Comment by benesch** [comment]
Apologies if this is obvious, but you've enabled tracing locally, yeah?

**Comment by danhhz** [comment]
Yes, this happened for me every time

**Comment by andreimatei** [comment]
ah, forgot about `COCKROACH_ENABLE_TRACING`. Thanks!

**Comment by andreimatei** [comment]
Copying the baggage item in `span.Context()` is needed indeed, but that's not the (main?) issue here. The thing is we need more synchronization around accessing the `BaggageItems` even within a single Span. There can be concurrent readers and writers. In particular, the `TxnCoordSender` unfortunately sets a `TxnID` baggage item while other crap can be doing stuff with the span - like forking it.

This seems to happen in backup because, I think, a `jobProgressLogger` can run multiple progress updates at a time. Dan, is that right? (and, if so, is this intended? I see a `shouldLogProgress` based on the last fraction that was reported, but apparently that's not enough in this test to ensure there's not multiple in-flight updates at a time).

Anyway, I'll send a fix tomorrow.

**Comment by benesch** [comment]
Yup, that's expected. The `shouldLogProgress` will allow multiple concurrent progress updates through provided each is updating the progress by more than 5%. We run small backups in tests, so the progress updates by quite a bit on each tick.

It'd be easy enough to serialize that—we already have the lock to do so—but I assume if it's causing problems here, it's also causing problems somewhere else.
