### ISSUE TITLE
storage: purge GC'ed keys inconsistently, in the background

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#16132]
The GCQueue's `process` method currently scans the replica from a snapshot, assembles the keys to be deleted, and then passes that to the Replica as a proposal.

This is a change from its initial design which didn't have explicit replicated GC but simply threw out values that were no longer visible - I think we abandoned that in an attempt to make replica divergence easier to check. However, I think we should sit down and reconsider whether that approach wouldn't make more sense. We are already making sure that GC'ed data can't be read (the GC threshold), and if we excluded GCable versions from consistency checks those would continue working as expected. Bonus is we can omit this data from snapshots as well.

With that design, an explicit GCQueue would still be necessary (think Txn and Abort spans, as well as deleted, old keys), but frequently-activated keys would amortize their GC overhead over their writes.

It seems that for the workloads tested so far, the GCQueue is reasonably successful at cleaning up, so marking this for later (read: perhaps never).

Forked from https://github.com/cockroachdb/cockroach/issues/16068.

**Comment by petermattis** [comment]
If we wanted to get really fancy here, we would GC old versions during RocksDB compaction. I seem to recall that there were some recent enhancements to RocksDB compaction filters to allow considering multiple keys during a compaction.

**Comment by a6802739** [comment]
Could  I have a try for this? @tschottdorf

**Comment by tschottdorf** [comment]
@a6802739 this is more of an aspirational issue with a larger migration story - let's wait until this becomes current (if ever). Perhaps take a look at #15989 for now? Could use some help there.

**Comment by a6802739** [comment]
@tschottdorf, thank you very much.

**Comment by tschottdorf** [comment]
The GC queue bit us again on the node liveness table - only 8 keys, but due to TTL experiments the table was able to rack up 111mb of non-live data. What happened for these proposals is that `MVCCGarbageCollect` (which is called when evaluating the GCRequest for the 8 keys) makes a huge `WriteBatch` (~58mb) and takes so long that the node loses its liveness. Even worse, other nodes lose their liveness as well, since the GCRequest blocks the whole key range while it's evaluating. Note that

1. the key-based chunking in #15989 doesn't help much (it would send 8 individual batches, but each of these would still be very large, and you cook up the same situation with only one key), and
2. We still block the whole range for the meat of the GCRequest since #7880 hasn't been implemented, but in this case, even with #7880 we'd have the same trouble as all requests to that range would want to touch one of the keys actually being GC'ed (i.e. things would block just the same).

In the case of the user affected by this particularly inconvenient example (liveness table) we have put up a diff that changes `MVCCGarbageCollect` to simply stop accruing deletes after the ~10kth key. But we need a better general strategy.

**Comment by tschottdorf** [comment]
Moving this to 1.1 milestone. cc @petermattis

**Comment by petermattis** [comment]
This needs to be fleshed out a bit more. In particular, what is the migration story? In a mixed-version cluster, `GCRequest` would still need to propose all of the keys to be deleted, right? Excluding keys outside of the GC threshold from consistency checks and snapshots seems straightforward in comparison.

**Comment by tschottdorf** [comment]
Sorry, what I did was confusing. I did not mean to suggest that we should implement the suggestion in the first post for 1.1, but to only address the issue of large GC requests. https://github.com/cockroachdb/cockroach/pull/16637 has already achieved that. I'm taking the milestone off.

**Comment by tbg** [comment]
Every time I pull this up again, it seems like something we ought to be doing. We'd need to teach the consistency checker to ignore versions made invisible by the GCThreshold, but after that I don't see what's stopping us from doing the actual work. It'll still be complicated: the compactions need to learn the GCThresholds of the replicas whose data is touched by the compactions, and then get to selectively remove only the versions/tombstones not visible at or above the threshold any more. And we need to make sure that values are also removed in L6, which may not be compacted into for a very long time.

**Comment by nvanbenschoten** [comment]
@petermattis @sumeerbhola one of you two should take a look at https://github.com/cockroachdb/cockroach/pull/41806 from the perspective of enabling this future enhancement. Specifically, let's make sure we're not preventing ourselves from making the change due to the tighter coupling between Replica state and GC decisions. If the plan is to have the GC queue bump the GCThreshold (using #41806) and let the actual GC be handled lazily (by this enhancement) then I don't see any issues, but it's worth double-checking.

cc. @ajwerner

**Comment by petermattis** [comment]
I don't see anything in #41806 which would prevent performing GC during compaction. We'd have to communicate the protected timestamp to the compaction filter, but there is no particular difficulty in doing so as far as I can see. Even if the plan for #41806 involves more complex logic for determining whether to GC a key or not, as long as that logic can be encapsulated I think we can perform it inconsistently on replicas and then eventually move it to a compaction filter.

**Comment by sumeerbhola** [comment]
I believe this is subsumed by the more detailed https://github.com/cockroachdb/cockroach/issues/57260

**Comment by tbg** [comment]
Agreed
