### ISSUE TITLE
Start process with background flag simply hangs

### ISSUE THREAD

**Issue by BHouwens** [cockroachdb/cockroach#16162]
Followed the intro process to getting started with a cluster (copy-pasted commands as well), but the cluster start process simply hangs. Visiting the admin UI works but no data loads (just loading spinners).

Output of running `cockroach version`:
```
Build Tag:    beta-20170330
Build Time:   2017/03/30 15:17:20
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  f0f5783cc67f9cda16cedf1b88ca0691b0b65884
Build Type:   release
```

Command I entered that hangs:
```
cockroach start --insecure --host=localhost --background
```

**Comment by tschottdorf** [comment]
Is this a single-node cluster you're starting for the first time or a node in a cluster you were running before? Note that if you had a cluster consisting of multiple nodes, you will typically have to start a few nodes before they are able to completely start when using the `--background` flag (with this flag the process only forks after the cluster is operational, and you need at least half of your replication factor to be up for that to be possible).

**Comment by BHouwens** [comment]
@tschottdorf Is it not possible to kill a cluster I've run before?

**Comment by a-robinson** [comment]
It certainly is possible to kill and restart a cluster, but the cluster won't work on restart unless you start up at least a majority of the nodes that were in the cluster. Meaning that if you had a 3 node cluster and shut them all down, you'll need to restart at least two of the nodes before either of them will be able to do anything.

Using the `--background` flag can make this a little confusing, since it waits until the node has joined/rejoined the cluster and is able to serve queries before returning. If there aren't enough nodes up for the cluster to start doing work again, `--background` will hang forever (or until you start another node).

**Comment by dianasaur323** [comment]
@m-schneider did your recent warning message edit address this issue? If so, perhaps we should close this out.

**Comment by a-robinson** [comment]
There isn't enough information to do anything here. It looks like https://github.com/cockroachdb/cockroach/pull/17997 still needs to be submitted, but either it'll fix this or we don't have enough information to do anything else here.
