### ISSUE TITLE
cli: mechanism to set initial cluster settings

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16202]
When setting up a "fresh" local cluster (either single-node, or via `roachdemo`), it would be useful to be able to somehow set initial cluster settings (like `server.remote_debugging.mode`). It could be a command line switch or env var which causes the node to run `SET CLUSTER SETTING` after joining the cluster.

**Comment by RaduBerinde** [comment]
Ah, I guess one can just do something like this:

```
( sleep 5s; echo "SET CLUSTER SETTING server.remote_debugging.mode = 'any';" | ./cockroach sql --insecure ) &

./cockroach start --insecure --logtostderr
```

**Comment by dt** [comment]
dupe #15301 ?

**Comment by dt** [comment]
Also, if you didn't want to be dependent on sleeping the magic number of seconds, you could do `./cockroach start  --background && ./cockroach sql -e "SET CLUSTER SETTING server.remote_debugging.mode = 'any';"`, since `--background` is supposed to block until startup is complete.

Taking that even further, If you wanted to be *sure* your cluster was using your new settings before moving on to serve other traffic, you could use a short-lived server just to provision and then stop it before starting your real server on top of its initialized data  -- i.e. `cockroach start --background && cockroach sql -e && cockroach quit && cockroach start ...`. This is basically mocking out an explicit init step, but is probably overkill just for a debug setting.

**Comment by RaduBerinde** [comment]
Ah, thanks, I looked for an issue but did not find #15301. Closing.
