### ISSUE TITLE
sql: allocation regression by `SHOW SESSIONS` commit

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16531]
I've bisected a regression in the number of allocations on a decent SQL benchmark to the following commit:
f95a4702 - Add SHOW SESSIONS and SHOW QUERIES statements - Add node-local session registry - Make Session struct partially thread-safe (with mu sub-struct) - Add Sessions and LocalSessions RPC endpoints, called upon SHOW  {SESSIONS,QUERIES}

Peter doesn't like it when there's new allocations :P
The increase is large enough that I think some investigation is in order to see if we can reduce the allocs, or at least understand if they're really needed. I can help with the memory profiling tools.

```
make bench PKG=./pkg/sql BENCHES=KV/Scan1_SQL TESTFLAGS="-benchmem"
    5000	    252865 ns/op	   29566 B/op	     292 allocs/op
```

The previous commit, 79f65ab, had:
```
    5000	    243949 ns/op	   29229 B/op	     278 allocs/op
```

Note that at HEAD the number of allocs is even higher until I fix #16518.

**Comment by itsbilal** [comment]
Base commit 79f65ab7e :
```
make bench PKG=./pkg/sql BENCHES=KV/Scan1_SQL TESTFLAGS="-benchmem -count 1 -memprofilerate=1 -memprofile=/tmp/memprofile-old"
    1000	   1574717 ns/op	   29906 B/op	     288 allocs/op
```

My commit f95a470 without any modifications:
```
    1000	   1648115 ns/op	   30180 B/op	     297 allocs/op
```

[This line](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/session.go#L672) in session.go is responsible for the bulk of the difference. Replacing it `sql := "TEST"` brings the number of allocations down to:

```
    1000	   1652583 ns/op	   29964 B/op	     289 allocs/op
```

The remaining extra allocation is the [creation of `queryMeta`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/session.go#L678) which is reasonable. 

Generating the sql string from the AST is pretty costly for long queries, and very wasteful in this scenario because we're gonna be truncating it to 1000 characters _after_ it has been pretty-printed anyway. One way is to store the user provided query string (truncated to 1000 chars) in `sql.Statement` beside the AST (which would be my preferred way to fix it), or add a `fmtFlag` to stop stringifying the AST at 1000 characters.

**Comment by petermattis** [comment]
> Generating the sql string from the AST is pretty costly for long queries, and very wasteful in this scenario because we're gonna be truncating it to 1000 characters after it has been pretty-printed anyway. One way is to store the user provided query string (truncated to 1000 chars) in sql.Statement beside the AST (which would be my preferred way to fix it), or add a fmtFlag to stop stringifying the AST at 1000 characters.

In this case, the query is less than 1000 characters so the truncation is not a problem. Using the user provided query string is mildly problematic as that string might contain multiple statements. Is it possible for `queryMeta` to store the `Statement`? I realize there will be some locking issues to contend with, but I don't think those are insurmountable.

**Comment by itsbilal** [comment]
@petermattis That makes more sense - generating the statement only when we need to print it. `queryMeta` can store the statement. I'll make that change.

**Comment by andreimatei** [comment]
I repeatedly see `278 allocs/op` (sometimes 279) at 79f65ab, not 288...

**Comment by itsbilal** [comment]
@andreimatei Setting `-memprofilerate=1` makes the difference, it seems.
