### ISSUE TITLE
storage: refactoring needed around errors from reordered Raft commands

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16771]
This code seems nonsensical:
https://github.com/cockroachdb/cockroach/blob/c4d7e90642e30ff5ed681130df8dcb305b94500f/pkg/storage/replica.go#L3915-L3920

First of all, the `defer` is not needed. Second, the null-ing of the ctx is useless if other functions have captured it.

Third, the point of calling early `proposal.finish()` early is unclear; we should return the error and rely on a higher-level `finish()`.

**Comment by petermattis** [comment]
Looks like that code was refactored into nonsensicalness.

**Comment by bdarnell** [comment]
We nil out the context here not because another function might have captured it but because another defer in this function might try to use it. There's no such defer now, but there apparently was in the past. I think this is mostly detritus from when this function was inlined in `processRaftCommand`.

**Comment by tschottdorf** [comment]
When I looked at this with @andreimatei, it seemed that we should just return the proposal retry info to the caller and then things would clear up naturally.
