### ISSUE TITLE
core: user-provided cluster name.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#16784]
A user-provided cluster name would be very helpful for in a lot of cases:
* could be provided by every node on startup and be required to match when joining a cluster (would prevent unitialized nodes from joining the wrong cluster)
* could be used in certificates to easily identify the object of the certificate. The certificate field could be checked against the actual cluster name to disallow certs for other clusters that were signed with the same CA (common for people with established pki infrastructure: they'll have a single org CA)
* included as a label in metrics. This makes multi-cluster monitoring much simpler, skipping the need for cluster names in the monitoring config. see #15888

All three cases above would require a strict verification of the cluster name. This would mean that **should** be provided at cluster initialization and never changed. An empty name could be supported (making supporting existing cluster much simpler). Changing the name would be possible for all the listed cases, just very very tedious (coordinate node flags, regenerate all certificates, manually relabel metrics to preserve history).

**Comment by dt** [comment]
I think the human-readable displayed name should be changeable.

This includes the name used to export metrics. yes, that might cause discontinuity in history, but that's up to an operator -- maybe they prefer that over the cognitive overhead of it being misnamed? Also some metrics storage allows rewriting collected metrics. Either way, I think this is a call for the operator to make.

For use in join, having the name match at the time of `join` might be enough, but it is a little odd then if you bounce the proc and it fails to rejoin after a rename. Also, name collisions are easily possible, so we might get more safety from using the shortened cluster ID instead.

**Comment by mberhault** [comment]
Using an automatically-generated ID to ensure join safety or to put in certs doesn't help, both of those need to be known before you even start the cluster.

**Comment by mberhault** [comment]
And as mentioned, it would be possible to change it, just insanely tedious and would most likely make your cluster stop serving for a while.

**Comment by bdarnell** [comment]
I tend to agree with David that a display name should be easily changeable. I think we want three separate values: the cluster id (same as today), a `cluster_name` setting for display purposes, and a new command-line flag for the hard-to-change name used in certs and join checks. I don't know what we'd call the third thing, though. `--join-name`?

**Comment by mberhault** [comment]
CC: @knz

**Comment by mberhault** [comment]
Having a field in the certificates that must match the cluster name would help towards #28408 as well (when one CA is used to sign certificates for multiple clusters).

**Comment by knz** [comment]
Replying to https://github.com/cockroachdb/cockroach/issues/16784#issuecomment-312076991

> we want three separate values:
> - the cluster id (same as today),
> - a cluster_name setting for display purposes, 
> - a new command-line flag for the hard-to-change name used in certs and join checks. I don't know what we'd call the third thing, though. --join-name?

Regarding the third thing: ISTM that this would be akin to the "shared key" used in other distributed systems. The term "shared key" has been widely used for this purpose in other places so I'd propose to use it.

I have two remaining questions:

1) to @bdarnell about the new join thing (shared key): do we need this to persist? It sounds to me that the only thing that matters is that the value agrees across all nodes that are up. It would be simpler to implement if it was just a command-line flag, not stored, and merely gossipped (and perhaps checked by the dialer when establishing GRPC connections). What do you think?

2) to @mberhault regarding the cert validation thing, do we want to check certs against the display `cluster_name`, or do we want to check certs against the new join thing (shared key)?

The latter is the easiest to implement. If we want to use the display cluster_name, that will constraint the implementation to use something else than our existing cluster setting infrastructure, because it needs to be available before the cluster has been initialized.

**Comment by mberhault** [comment]
I'm still not convinced about the "display name" and "hard-to-change name" being different things.
People are accustomed to system names that are hard to change. If we want something easily changeable to display, call it `motd` and don't do anything other than display it. Everything else (cert checks, join checks, monitoring labels) should be a hard-to-change name.

The name should be passed on the command line (or env) as we can't even talk to another node until we've validated that the name is in the cert (if this check is enabled).

**Comment by knz** [comment]
> The name should be passed on the command line (or env) as we can't even talk to another node until we've validated that the name is in the cert (if this check is enabled).

Ok but should it be stored too? i.e. does it matter that if you stop all nodes in the cluster, then restart them all, the second time around the name is the same as the first? 

(If it was just about certs, I'd say no, we could rotate all certs when power-cycling the entire cluster. but maybe there are other reasons?)

**Comment by mberhault** [comment]
I think it's fine not to store it. The idea would be that you would set it once in your configs (supervisor, kubernetes, or other) and leave it there forever. If you want to change it, you can shut down the cluster, change your configs, and start everything up again (the full shutdown would be the "hard to change" part).

**Comment by knz** [comment]
ok I know how to work with that

**Comment by knz** [comment]
(I'll also do the "motd" thing separately because there's demand for this to distinguish two clusters in the admin UI)

**Comment by mberhault** [comment]
I think the motd would fit well in cluster settings. Assuming everyone is ok with an easily changeable field for display purposes only.

**Comment by knz** [comment]
Another thing that was discussed before: a prefix for prometheus metrics

Should this use the cluster setting, the cmdline thing, or another thing entirely?

- using the cmdline thing: pro: simple to implement; con: if the users change their conf, that will break their monitoring

- using the setting thing: pro: simple to implement; con: it ties the UI/motd element (a human concern) with the monitoring (a programming concern), thus making it perhaps too easy to break the monitoring.

**Comment by bdarnell** [comment]
> I'm still not convinced about the "display name" and "hard-to-change name" being different things.

Neither am I. I think if we have something called a display name, it should be easy to change and not used for anything but display purposes, but I'm not sure we really need it. I'd just make a CLI-only "join name" flag, and if it's set, show it in the UI. I don't think we need a separate motd/display-name.

> Another thing that was discussed before: a prefix for prometheus metrics

I'd use a setting for this, and wouldn't share the setting with anything else. Doesn't prometheus have a "label" concept? Should we use that instead of prefixing the names?

One more related thing: If we kept the "join name" a secret, it becomes like a "join password/key", and gives insecure clusters a little bit of security (which might be enough for us to turn on password auth for insecure clusters). Maybe that just muddies the water, though.

**Comment by knz** [comment]
marc suggests I collect these various points into a RFC. I'll do that next

**Comment by knz** [comment]
rfc in #39196
