### ISSUE TITLE
scatter: downreplication takes a long time

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#17000]
Discovered while implementing a proper scatter in #16249. `AdminScatter` is able to very quickly upreplicate (e.g., in a few minutes), but the replicate queue can take ten minutes to downreplicate. Figure out why; @a-robinson claims the downreplication should take approximately as long as the upreplication.

This behavior is easy to reproduce with a four-node local cluster with preeexisting data: https://github.com/benesch/crdb-playground-scatter

**Comment by a-robinson** [comment]
Was this fixed by your `DeleteRange` change?

**Comment by benesch** [comment]
Don't think so, but you'd know better. Here's the downreplication after a 15GB restore with ~1k ranges.

![screenshot 2017-07-17 14 44 56](https://user-images.githubusercontent.com/882976/28284412-e5b1f7aa-6afe-11e7-930f-190f54defb86.png)

Takes about 10m.

**Comment by benesch** [comment]
And here's a screenshot that's, like, actually useful:

![screenshot 2017-07-17 14 48 17](https://user-images.githubusercontent.com/882976/28284449-00bbd78c-6aff-11e7-91f9-659a8f9468b5.png)

**Comment by benesch** [comment]
Try not to look too hard at the leaseholders per store graph.

**Comment by a-robinson** [comment]
Assuming I'm squinting properly at that graph, it looks like it took around 7 minutes, so I guess it's still not fixed.

**Comment by benesch** [comment]
Yeah, sorry, it's ~10m. How long would you expect it to take?

**Comment by a-robinson** [comment]
About the same amount of time as up-replicating. The problem, though, is that's the wrong graph to be looking at, since it's including not just the down-replication time, but also the replica GC time, since the metric behind the replicas-per-store graph only gets decremented when a replica gets GC'ed, not when it gets removed from the consensus group. Usually those events are close together, but they aren't guaranteed to be. The "Range Operations" graph would be more useful.

I'll check it out sometime, but it doesn't seem urgent.

**Comment by benesch** [comment]
That is incredibly useful to know. Yeah, no rush at all; I may look into it too.

**Comment by tschottdorf** [comment]
I wouldn't be surprised if this were fixed now. Don't the decommissioning tests verify something similar?
