### ISSUE TITLE
tracing: mark tracing http2 headers not-cacheable.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#17083]
Due to a bug in golang http2 hpack (see #17052), we noticed that the tracing-related http2 headers were cached.
Since those are both big and unique, we should mark those as non-cacheable, leaving the cache free to fulfill its function.

I haven't started digging through this, it could be a trivial change or not.
@RaduBerinde: any idea where to start digging?

**Comment by RaduBerinde** [comment]
The tracing headers aren't big. There are a handful of short keys and values (they just contain some IDs).

The code that injects the headers is in an external repository, we need to file an issue upstream if they need to do something differently.

https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc

This is the code that injects the tracing info:
https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/client.go#L60

**Comment by mberhault** [comment]
Thanks, I'll poke around.
They may not be big but they still pollute the cache, forcing more frequent headers to be evicted.

**Comment by bdarnell** [comment]
This would need a lot of plumbing. The go hpack implementation implements the "sensitive" flag to hide things from the cache, but the http2 package doesn't use or expose it. I don't think it's crucial to do this - since the cache is based on size (instead of number of entries), all it costs us is a little extra cache churn. The cache is reasonably smart about this (it's lru-ish), so the frequently-used things will stay in the cache.
