### ISSUE TITLE
distsql: distributed plans can deadlock

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#17097]
I am filing this "master" issue to keep track of our discussions on this problem.

One instance of the problem is described in https://github.com/cockroachdb/cockroach/issues/16875#issuecomment-315939351

Another possible instance is illustrated below:
![image](https://user-images.githubusercontent.com/16544120/28340346-6c3c5070-6bdd-11e7-8d45-57dcb7287440.png)
We have a table reader that's feeding input to two Merge Joiner shards. These output their results to a final processor, which uses an "ordered" synchronizer to maintain ordering. Now suppose that we read a bunch of rows that all go to hash bucket 1 (can easily happen if they all have the same value). Also assume that the merge joiner already produced some rows and is blocked trying to send rows to the ordered synchronizer. The ordered synchronizer needs to read a row from both sides to decide which row to let through first. So the synchronizer is blocked trying to read a row from the right input. But the only way this will ever receive any rows is if the table reader sends something to the merge join on the right; which it won't because it is blocked.

One proposal from @knz is to introduce buffering wherever multiple inputs go to a single processor (joiners, ordered synchronizer). Deciding when it is necessary is not trivial however.

@arjunravinarayan points out that we can alternatively buffer on the output side, only when we have multiple consumers and some are blocked and others aren't. We currently only have a single case where a processor outputs to multiple consumers: the hash router.

**Comment by arjunravinarayan** [comment]
Here's a copy of my thoughts from earlier discussion:

1. In DistSQL we push rows, not pull, so there's no "demand rows".
2. If a processor pushes a bunch of rows, and the consumer doesn't eat them, they build up in a GRPC buffer.
3. If this buffer gets built up, at some point the "push" operation gets blocked on the GRPC send command. All of this is opaque to the processor programming. It pushes a row, it gets blocked. Deadlock.
4. In order to unblock this, we need a way for the "push" operation to never block.

5. we can do this by adding buffering somewhere in there.
5a. Option A is to add buffering on the input, so that the rows are always consumed.
5b. Option B is to add buffering on the output, so that rows are always produced.

Option A has a complication: when do we know we should start buffering? We don't know who is our "sibling" processor, so always buffering is a wasteful heuristic - if we are the only consumer of this stream, there was no need. Instead you have to do this complicated jig of sending metadata backwards along the dataflow graph, like Raphael describes. This sets of alarm bells in my head. Propagating backpressure is one of those things if not done in a careful principled fashion can result in all sorts of cyclical dependencies because we now have information flows in two directions, and if we don't have a clear fixpoint proof of progress tracking, who knows what the thing is actually doing.

Option B has a simple heuristic: if we have more than 1 consumer and if 1 consumer is blocked, we start spilling rows into an external buffer. If we have just 1 consumer, there's no need - just block. Done.

6. I vote we do this using a fixed size in-memory buffer, spilling to external storage after the in-memory buffer is filled. 
7. This means we now have buffers of theoretically infinite size, fulfilling Raphael's theoretical requirement to avoid deadlocks. 
8. This is a quick fix, because we already have the mechanisms for sandboxed temp storage.

This is a quick and dirty fix. This fix may not be the permanent one-true-fix, but it will fix things with minimal code changes and we can get it done in time for the 1.1 feature freeze.

**Comment by arjunravinarayan** [comment]
@RaduBerinde I noticed you assigned this to yourself, are you planning on working on the fix now?

**Comment by RaduBerinde** [comment]
I was planning to start, but if you want to work on it, that's great (we can talk about some details offline).

**Comment by arjunravinarayan** [comment]
@knz adds the thought that we should keep track of the high watermark as we spill to disk, as it will be good to have metrics to detect for a later date when we would implement backpressure on our dataflow graphs.

**Comment by arjunravinarayan** [comment]
@RaduBerinde you can start, why don't you implement the in-memory buffer. After you're done, I can extend the design to use external storage once the in-memory buffer runs out.

**Comment by RaduBerinde** [comment]
I posted a short RFC for how to implement the buffering hash router in #17105.
