### ISSUE TITLE
server: configuring NTP in Heterogeneous platform 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#17122]
A CockroachDB cluster where one node is running on MacOS, 2nd node on Linux, and 3rd node on Windows is possible.  Some adjustments maybe required such as using common NTP time source for all platforms and Windows w32tm /resync to fine tune.   

A potential follow-up maybe additional research on heterogeneous platform support and documenting the best practice.

@bdarnell

**Comment by bdarnell** [comment]
Best practice is to not do that :)  It just adds extra complexity and CockroachDB performs better (and is more thoroughly tested) on linux than on macos or windows. 

We need to research the windows clock sync issue anyway (since I think that's necessary for an all-windows cluster), but I don't think there's anything special about the heterogenous configuration.
