### ISSUE TITLE
storage: write a test for double ingestion

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17215]
See https://github.com/cockroachdb/cockroach/pull/17201.

**Comment by tschottdorf** [comment]
This should be easy enough for someone with light core skills to pick up. Moving to 1.2 and unassigning, for now.

**Comment by yaojingguo** [comment]
I will have a look at this.

**Comment by gshirishfree** [comment]
Hi there I want to learn about cockroach db and this seems to be good issue to start. Can someone assign this to me ?

**Comment by gshirishfree** [comment]
@tschottdorf I am trying to work on this, but having trouble creating store on disk. Below is my test case looks like.

.....
store, _ := createTestStore(t, stop.NewStopper())
store.getOrCreateReplica(ctx, rangeID, 1, &creatingReplica)

key, value := "don't", "care"
data, _ := MakeSSTable(key, value, hlc.Timestamp{}.Add(0, 1))
sst := engine.MakeRocksDBSstFileReader()

sst.IngestExternalFile(data)

call addSSTablePreApply with needed argument
......

But the problem is **createTestStore is creating engine in Memory** engine.NewInMem(roachpb.Attributes{}, 10<<20), and to test double ingestion we need to have engine on disk, otherwise value will always return from below condition and newer reach double ingestion code path
if inmem, ok := eng.(engine.InMem); ok {
path = fmt.Sprintf("%x", checksum)
if err := inmem.WriteFile(path, sst.Data); err != nil {
   panic(err)
}

So, the question is there any createTestStore that will create store on disk or you think this can be solved with another approach ?

**Comment by yaojingguo** [comment]
@gshirishfree I have also been working on this recently. Here are my thoughts.

The high-level steps for my test case are:

1. Extract the ingestion pathname for an earlier `AddSSTable` from the trace `log.Eventf(ctx, "ingested SSTable at index %d, term %d: %s", index, term, path)`. The ingestion pathname should be something like `/var/folders/qd/wj_djys9219cyj4l9c2qw6g80000gn/T/TestDBAddSSTable_store=on-disk211227580/auxiliary/sideloading/6/6.1/i23.t6.ingested`. The index for this `AddSSTable` is `23`.
2. The next index will be `24`. The ingestion pathname for index `24` will be `/var/folders/qd/wj_djys9219cyj4l9c2qw6g80000gn/T/TestDBAddSSTable_store=on-disk211227580/auxiliary/sideloading/6/6.1/i24.t6.ingested`. Create this ingestion file and write `bcc->3` into it.
3. Do another `AddSSTable` for the data `bccc->4`.
5. Verify that `bcc->3` does not exist and `bccc->4` does exist with `db.Get`.

And I think that we can add the test case to `pkg/ccl/storageccl/add_sstable_test.go`.

**Comment by tschottdorf** [comment]
The momentum for doing this has been lost.
