### ISSUE TITLE
sql: resolve the sql directory naming

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1722]
The naming of the directories within `sql` is disturbingly inconsistent: `sql/driver`, `sql/parser`, `sql/sqlserver` and `sql/sqlwire`. Either all of the directories should start with `sql` or none of them should.  On the one hand, we have the camp that wants the directory name to match the package name. But that results in stuttering such as `sql/sqlserver`. On the other hand, we could have a directory named `sql/server` with a package name of `sqlserver` (to avoid using the too general package name of `server`), but that offends the strict package name == directory name folks. 

A compromise that hopefully makes nobody happy would be to get rid of the `sql` directory and have top-level packages named `sqldriver`, `sqlparser`, `sqlserver` and `sqlwire`.

**Comment by petermattis** [comment]
@bdarnell, @tamird, @vivekmenezes care to weigh in on these options?

**Comment by tamird** [comment]
Another option is to have the majority of this stuff in a single package. I'm not sure what the separation between `sql{parser,server,wire}`. Perhaps the end state could be `sql` (containing today's `sql{server,wire}`, `sql/driver`, and `sql/parser`.

**Comment by petermattis** [comment]
I'm not clear what you're proposing. We definitely want `sql/driver` to be separate so that users of the driver don't have to link in all of our server code. We also need to keep `sql/sqlwire` (i.e. the client proto definitions) separate for similar reasons. We could merge `sql/parser` and `sql/sqlserver`, but we're still left with 3 packages. Am I misunderstanding your proposal?

**Comment by tamird** [comment]
Ah, I had overlooked `sql/driver`'s dependency on `sql/sqlwire`. I propose we rename: `sql/sqlwire` -> `sql/wire` and `sql/server` -> `sql` (we don't actually have a `sql` package at the moment).

**Comment by bdarnell** [comment]
I'm in the package name == directory name camp, just because it's a surprise to me every time I re-learn that the alternative is even possible. As long as goimports understands it, though, I won't object. I'm not bothered by the stuttering, or the fact that some of the packages start with sql and some don't (it can be a case-by-case decision based on anticipated likelihood of collisions). I wouldn't even mind too much if there were four top-level directories starting with `sql` (although in the long run I'd wager we move the `driver` and `sqlwire` packages into a separate repo entirely so client's don't have to download our server codebase).

My opinions in this area are all pretty weak and I defer to those of you who work in this codebase, but my colors for the bikeshed are to merge `sql/sqlwire` into `sql/driver` (unless there's some reason to keep these separate that I'm missing), move `sql/server` to `sql` as @tamird suggested, and leave `sql/parser` as-is.

**Comment by petermattis** [comment]
`sql/sqlwire` and `sql/driver` can be merged, though doing so will require linking `sql/driver` into the server. I suppose that already happens via the SQL shell Marc recently added.

**Comment by vivekmenezes** [comment]
I believe the only strong opinion I have is that the language code and its
implementation be under SQL. I think the driver should be separate and
perhaps placed at the top level in driver. Perhaps the server can just be
dumped into SQL for now as a part of the language implementation. I think
we should leave wire alone to allow other language client code to link with
it.
