### ISSUE TITLE
kv: request sequence numbers are broken when using client.Txn concurrently

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#17249]
There's a suspicion that we might reuse sequence numbers when different batches are sent by concurrent users of a `client.Txn` (think SQL `parallelizeQueue`). These sequence numbers have a role in replay protection.
The sequence numbers are assigned by the `DistSender`, using a counter that's in a forked `Transaction` proto. Racing batches might reuse numbers.

This is probably not OK? I'll let @tschottdorf fill in.

Relatedly, if concurrent requests are sent to the same range, then some of them will erroneously be considered replays. But the `parallelizeQueue` currently only parallelizes statements that work on different ranges.

**Comment by nvanbenschoten** [comment]
As discussed in person with @andreimatei and @tschottdorf, sequence numbers are only enforced when a higher or equal one is found in a write intent on the exact key a `Batch` is writing to. The assumption underpinning this issue was that these sequence numbers would be enforced at the range level, meaning that two concurrent requests for the same `client.Txn` sent to the same range would conflict. Instead, this means that two concurrent requests for the same `client.Txn` will only conflict if the specific keys each one touches overlap.

Currently, the `parallelizeQueue` will never even write to the same range because its dependency analysis is naive. However, the goal is to improve the granularity of its dependency analysis (see #16862). Even with these desired improvements, as long as the queue does not allow two users of a `client.Txn` to conflict on the same key concurrently, it should be safe.

Still, sequence numbers are something we should be careful about in the future as we further embrace some form of concurrent `Txn` usage. It will be up to the users of these concurrent `Txn` handles to assure that writes to the same keys are never allowed concurrently. I doubt this will be problematic though because the result of concurrent writes to the same key would be undefined, so there probably aren't any good reasons to try to make it work.
