### ISSUE TITLE
kv: duplicate BeginTransactionRequests can be sent by parallel sql statements

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#17250]
`Txn.Send()` adds a `BeginTransactionRequest` to a batch if the txn proto's `Writing` field is not set. The field is set on the server side, when processing the `BeginTransactionRequest`.
When doing parallel writes through the sql `parallelizeQueue`, it's possible to have two concurrent clients send different batches that both get a `BeginTransaction`. I believe catastrophe ensues, because now intents will be split between the two transaction records.
It's true that the `TxnCoordSender` will error on a `BeginTransaction` sent after it became aware of `Writing` being set, but that's not sufficient.

Because of this, and #17197 and #17249, I think we should patch 1.0 and disable the parallel processing of `RETURNING NOTHING` statements, as I don't trust their correctness at all. @bdarnell @petermattis what do you think?

cc @tschottdorf @cockroachdb/sql-execution

**Comment by tschottdorf** [comment]
> I believe catastrophe ensues, because now intents will be split between the two transaction records.

On second thought, that may not happen currently because of the shared mutex and because the key is set eagerly (enough, I hope?). However, it would certainly happen if we were to "fork" the proto as discussed for #17197. The `BeginTransactionRequest`s are also a real issue but would cause spurious errors, not inconsistencies. The sequence number issues are mitigated by the fact that we don't tend to touch the same range concurrently, but there's a chance that we can already get anomalies with the current parallelization under weird circumstances.

I would be more comfortable disabling this parallelization for now and working on fully excavating the rabbit holes. We are surely planning to use transactions concurrently more in the future and we should put that on solid footing now. I predict that it won't be straightforward.

**Comment by andreimatei** [comment]
> On second thought, that may not happen currently because of the shared mutex and because the key is set eagerly (enough, I hope?)

The key is set by `client.Txn.Send()` when the `BeginTransaction` is inserted. So duplicate `BeginTransaction` => two different anchors.

**Comment by andreimatei** [comment]
I think I was wrong here: looks like care has been put into not sending two `BeginTransaction`s -
- there's a `Txn.writingTxnRecord` member which protects from sending a second request.
https://github.com/cockroachdb/cockroach/blob/aa9a078d7b37253777cd7261bcac518b18d2571d/pkg/internal/client/txn.go#L949

The other two issues linked above remain, but I retract my opinion that we should disable the parallelize queue.
