### ISSUE TITLE
sql: CREATE TABLE/VIEW works on non-serializable transactions, but shouldnt

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17404]
Both CREATE TABLE and CREATE VIEW can modify descriptors of *other* tables/views than the one being created, to update either their depended-on list (for CREATE VIEW) or their index list (for CREATE TABLE with FKs).

This is done by using `planner.avoidCachedDescriptor` to disable use of the descriptor cache, so that the descriptor is read from KV in the same transaction. Then the descriptor is modified in-place, UpVersion is set, and written back in the same txn.

However, if the isolation level is SNAPSHOT, we run the risk of working with an outdated descriptor when committing!

It is important that DDL statements are rejected when the txn level is not at least SERIALIZABLE. 

cc @cockroachdb/sql-async 

Found by @andreimatei in #17310.

**Comment by knz** [comment]
cc @andreimatei too

@vivekmenezes can you triage and assign?

**Comment by cuongdo** [comment]
since @vivekmenezes is on vacation, @knz, can you find an owner?

**Comment by jordanlewis** [comment]
As a stop-gap, we should prevent all DDL statements from SNAPSHOT isolation transactions.

**Comment by dianasaur323** [comment]
sounds like we might want to mark this as a known limitation for 1.1

**Comment by m-schneider** [comment]
I'm going to looking into this today and implementing the stop-gap that
Jordan mentioned.

**Comment by andreimatei** [comment]
This bug was created as a reaction to my comment here:
https://reviewable.io/reviews/cockroachdb/cockroach/17310#-KqVMwfOgc7OFOEDvlVp

I think I was confused; I think I was afraid of a lost update anomaly corrupting descriptors but, of course, our SNAPSHOT transactions don't permit lost update, only write skew. It's much harder to imagine a write skew anomaly on descriptors cause by schema change transactions. It's probably doable, but I don't really know. I'll close this :)

Other suggestions in that review comment - about improving a comment to clarify that we should read the descriptors we're writing (and ensure that we did by running a CPut) still stand.
