### ISSUE TITLE
cockroachdb won't build on a FAT32 filesystem under ubuntu

### ISSUE THREAD

**Issue by thrasymache** [cockroachdb/cockroach#17472]
**BUG REPORT**
This is the output from `make build` on an SD card formatted with FAT32 running Ubuntu-Mate 17.10

> GOPATH set to /media/ubuntu-mate/2984-1FD9/go
> /bin/bash: ./build/jflag.sh: Permission denied                                                  
> GEN pkg/cli/zcgo_flags.go                                                                       
> GEN pkg/server/status/zcgo_flags.go                                                             
> GEN pkg/storage/engine/zcgo_flags.go                                                            
> GEN pkg/ccl/storageccl/engineccl/zcgo_flags.go                                                  
> installing githooks/post-rewrite                                                                
> ln: failed to create symbolic link '.git/hooks/post-rewrite': Operation not permitted           build/common.mk:137: recipe for target '.git/hooks/post-rewrite' failed                         
> make: *** [.git/hooks/post-rewrite] Error 1

The same system successfully builds cockroachdb on a partition formatted with ext4. It's possible that this is an issue with the `@ln -s ../../$(basename $<) $(dir $@)` line in the makefile, but my guess is that it's just an undocumented build requirement.

**Comment by benesch** [comment]
FAT32 doesn't support symlinks, I'm afraid. You'll need to use a filesystem which supports symlinks (like ext4).

Looks like you're building in a Git clone, though. I'm curious to know if you can build from our source tarballs, since the symlink that causes the error in your message is only created if building in a Git clone. See the "Build from Source" tab in our docs: https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html#build-from-source.

**Comment by knz** [comment]
Since this is an unsupported configuration I'm afraid we'll close the issue. However, if you find something that works for you feel free to explain how you did it on the forum at `http://forum.cockroachlabs.com` so other users can benefit from the experience!

Thanks for reporting this issue.
