### ISSUE TITLE
distsql: node OOM due to inadequate memory accounting in memRowContainer called by hashRouter

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#17594]
Not sure what is going on here and was curious if anybody had any ideas. I took over navy and pushed 3563d3ea512591d5e4e9602a041852a535f397f6 to test out external storage. I ran TPC-H query 3 with scalefactor 10 at 19:19 which completed fine at 19:47. At 00:54 node `2` dies with an OOM error. The [memory profile](https://github.com/cockroachdb/cockroach/files/1218659/profile001.pdf) indicates that the bulk of the memory is used up by a `memRowContainer` in a `hashRouter` used by a `tableReader` but there was no load running against the cluster (unless someone was using the cluster at that time). I am seeing blips of activity every so often so there might be something going on that I don't know about, but the OOM is still worth thinking about (because this memory is technically accounted for).
<img width="915" alt="screen shot 2017-08-11 at 11 46 19 am" src="https://user-images.githubusercontent.com/10560359/29225427-3c92a528-7e9c-11e7-9647-c1a70e28f659.png">
The other weird thing is the dramatic increase of ranges:
<img width="554" alt="screen shot 2017-08-11 at 1 53 29 pm" src="https://user-images.githubusercontent.com/10560359/29225511-9f93c3c8-7e9c-11e7-8f5a-76cb65859c1c.png">
at 18:51 (so before query 3 was executed) which drops again when node 2 crashes. I'm going to wipe the cluster and try again.

cc @cockroachdb/distsql

**Comment by arjunravinarayan** [comment]
It looks like there is a codepath in `memRowContainer` that is not properly accounted for, since the `memRowContainer` in `hashRouter` is growing to a very large size, right before the OOM killer kills the cockroach process.

This could be related to #15194.

Note that this is occurring on TPC-H query 9, which is not a query we've run earlier, due to its expected use of lots of memory and disk (which we did not support earlier).
Query 9 is a 6 way join, which requires clever join ordering in order to get merge joins to run on every level (which we do not yet do). The other queries which stressed hash joins should now be running with merge joins, which results in them no longer testing large hash joins which spill to disk. For reference, the single node query plan is [here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzMldtr2zAUxt_3VxhBqdOdQmTnKhiorN3mrU1Hkj2NPGjxmWtwLCPL0FDyvw85IRenVmbIQ96sy8_f9-kcpDeSyhBHYoE5Yb8JJTMgmZJzzHOpzNR6QxC-EtYGEqdZoc30DMhcKiTsjehYJ0gYmYo_CY5RhKgIkBC1iJPyp5mKF0IteSaUJkC-xIlGxRzuOY_Bjwfn-krJpUiurhljk-k4GH0lQJ4LzRxOgXtktgIiC70TzrWIkDC6gjOay4ssS-JydavdqdX2zqqdxCnGGhcHuYH7wLvAe8D7tT78s_owBTLnUPFRfwyds8pLFaLK98W7tcrdsyqnQscy_b-269Uq7wSLtMyC4YHczJCntrxj_5vIX77LOK26r_RKfZn6F2v5dIcPLsZ7gn-1a1x7wGnrk4qjF-2WA-Cd1rZ5KsmGwCkFTs0-vzbl8MJSmgrtRxzs8u1uJeCDTb76O7p9acG2qaiJNMY0LN-iITj4qpWYa_d6iULtHiMTHhyXd29cyhi7f_gcPN093vJeq3Xr8v6NqX1t_EZv1F0UKYyElhXn6_sISHD_MJpujG--PfM9-fXkct_iotFrNZFKV8-O04_Avdt6hUbv0BjzTKY5Vsv97q_bpsYYRrjumVwWao4_lZyXMuvhc8mVEyHmer1KN6MgLdfKSuzT1EoP7bBnhQd22LfCfTvcscI9O9xtAHtVuNfA9hHcb3BgR_CgQamO4GGTLjmi6Ykmowd4-wi3dxn1TuD2PqN-BZ-tPvwLAAD__6Um0ts=).

**Comment by arjunravinarayan** [comment]
Even if we solve this accounting problem (stopping the node OOM-killing), the query would still get gracefully errored out for lack of memory, unless we add some backpressure to the `hashRouter`, or we address the `TODO` in `routers.go` to fall back to a `diskRowContainer` when that happens.

**Comment by arjunravinarayan** [comment]
My prior diagnosis was incorrect. This query (query 9) will always gracefully error out until we plan join orderings intelligently - this feature is precisely what the TPC-H query is testing. There is perhaps some other query where backpressure in the hashrouter is useful, but it is not immediately evident to me, so please discard the previous comment.

**Comment by RaduBerinde** [comment]
Any idea what is the accounting memory limit? Any log messages indicating how much memory is accounted for?

**Comment by arjunravinarayan** [comment]
Here is the memory profile before its OOM killed. It indicates ~3gb of allocated memory: 
[profile001.pdf](https://github.com/cockroachdb/cockroach/files/1226237/profile001.pdf)

The log message is in line - the memory monitor only logs when it doubles, and the last log line is:
`I170815 07:24:05.284352 982377 sql/mon/bytes_usage.go:580  flow: bytes usage increases to 2.0 GiB (+288)`

**Comment by RaduBerinde** [comment]
So the limit is at least 2Gb. There may not be an accounting problem; this might be the problem we've seen before with GC not kicking in frequently enough.

**Comment by asubiotto** [comment]
Added some instrumentation to print out the memory budget increases to compare with actual memory usage and the query successfully errored out:
```
Starting TPC-H load generator
2017/08/15 21:42:41 connecting to db: postgresql://root@localhost:26257/tpch?ssl-mode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.root.crt&sslkey=certs/client.root.key
2017/08/15 21:42:41 [0] running query 9
2017/08/17 10:58:57 [0] error running query 9: pq: distsql-tempstorage disk budget exceeded: 37 bytes requested, 52810659840 bytes in budget
```
I think this is indeed a problem of the GC not kicking in frequently enough since a failure to account for memory would imply that this query always fails with an OOM (assuming the leases are spread out evenly in all cases). Adding instrumentation (log messages) probably adds enough latency for the GC to kick in in time. Closing.
