### ISSUE TITLE
[Performance] Is Update slower than Upsert?

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#17621]
I have seen some behavior that made me wondering, so that an update that updates 5000 was finished in just a range from a ms to a s while updating 5000 values actually takes quite a while. This is yet only a question, I have not put up any tests yet, but most probably going to do that soon. But for now I am just asking.

So up to the question:

Is it possible that Upsert is actually faster than issueing updates? For instance: Creating one upsert statement with 1000 records to change vs 1000 update statements within a single transaction.

**Comment by petermattis** [comment]
Yes, a single upsert statement with 1000 records will be faster than 1000 update statements in a single transaction. There are several factors here:
1. The single upsert statement is processed in a single round-trip to the server and internally the updates to the 1000 rows are both batched and performed in parallel.
2. The straightforward implementation of 1000 updates within a single transaction involves 1000 RPCs to the server and the server must sequentially process each update (in order to return whether the update modified a row or not).
3. An optimized implementation of 1000 updates within a single transaction which sends all of the statements in a single RPC is currently implemented by sequentially processing each update. This last bit could be optimized on the server so that we batch all of the updates together and then take care to report which rows were updated. This task is on our radar and we hope to get to it in the next release.

**Comment by wzrdtales** [comment]
@petermattis Perfect, do you believe that considering 3 you will reach a similar performance? Otherwise I will look to "optimize" huge update batches into upsert queries instead. The traffic overhead generated through this would be still worth the performance though :)

**Comment by petermattis** [comment]
@wzrdtales Yes, we should eventually be able to reach similar performance with 3. In the short term, I'd recommend optimizing huge update batches into upsert queries.

**Comment by wzrdtales** [comment]
@petermattis Alright thank you.

**Comment by knz** [comment]
We have made improvements to this in CockroachDB 2.0 and 2.1. I will close this issue now, and if there are new concerns we can open more specific issues accordingly.
