### ISSUE TITLE
Array functions in docs are overly verbose

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#17742]
Each [array function](functions-and-operators.html#array-functions) in our auto-generated function docs has an entry for each element type:

![screen shot 2017-08-17 at 4 44 09 pm](https://user-images.githubusercontent.com/15893490/29432920-5002c362-836b-11e7-90d4-138f27abffd8.png)

**Comment by justinj** [comment]
cc @dt, @knz, (the title of this issue was my doing) I think this is a limitation of our type system. The doc generator is doing what we would expect but the issue is that we don't have a way to define functions of type `([a], a) -> [a]`, rather, we define a new function for each element type, which works but leads to what you see here. Not sure if there's a workaround possible on the doc generator side.

**Comment by knz** [comment]
No opinion. For this CockroachDB should really implement Hindley-Milner, with a single method with type signature `forall a, ([a], a) -> [a]` and be documented as such. I am thoroughly uninterested in fixing doc issues in systems that want to implement generic functions but lack parametric types.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I'm not sure about Hindley-Milner, but without having a proper way to express arbitrary parameterization for builtin functions (eg. **not** just cases like `parser.HomogeneousType`), I don't see how we can approach. I do agree with @knz that we shouldn't try to hide this in the docs if it's not fixed in the system itself.

**Comment by jseldess** [comment]
Thanks, all. No need to keep this open if there's nothing we can do.
