### ISSUE TITLE
ui: Range IDs not displayed on raft range debug page

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#17745]
On `/#/raft/ranges`, the warning icons in this screen shot are supposed to be accompanied by range IDs. 

![image](https://user-images.githubusercontent.com/160562/29435540-6fb20aa6-8375-11e7-98e1-6c6f1bb0ac43.png)

**Comment by bdarnell** [comment]
Further down the page, *something* starts to show up in this area. It looks like the range IDs are being interpreted as character codes instead of integers:

![image](https://user-images.githubusercontent.com/160562/29435823-8ab7cde4-8376-11e7-955a-d2fa907832f6.png)

**Comment by dianasaur323** [comment]
@BramGruneir do you mind taking a quick look, or punting to whoever is appropriate?

**Comment by BramGruneir** [comment]
This page has rotted and has never been officially supported.
That being said, these seem like quick fixes, so I'll take a look.

If the fixes require a lot of work, I'll punt this to 1.2

That being said, there's an argument to just outright remove this page:
1 - It hasn't been updated since it was originally added, and hidden because it was never considered finished.
2 - The problem range page performs the same task in a much cleaner way.
3 - It will be nearly un-loadable in larger clusters.

**Comment by bdarnell** [comment]
Yeah, if the problem range page does the same thing we should just get rid of this one. This page is currently reporting problems that the problem range page is not, but they may all be false positives.
