### ISSUE TITLE
distsql: test that external storage deletion on node startup occurs even with full disks

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17862]
Cockroach nodes fail to startup if the configured store is full. However, as part of the node bootstrap process, the node is supposed to delete outstanding temporary storage.

A node crash could occur because the temporary storage location fills up during a large query execution. If this is not sanely cleared up on restart (due to a failure to get to the point of deleting the existing temporary store), this requires manual intervention, which is not documented.

We should test that node startup on a full disk successfully clears the temporary storage directory. 

Additionally, we want to also explore hard killing queries with large storage footprints once we get close to a 95%+ full disk, although we probably won't get to this in the 1.1 timeframe.

**Comment by vivekmenezes** [comment]
document this issue for 1.1 and perhaps cherry pick a fix later.

**Comment by dianasaur323** [comment]
@arjunravinarayan it sounds like you've got some work to finish up with external storage that isn't allocated in our current roadmap. I do have an item open to incorporate temp storage metrics into the admin UI, but that's about it. 

Not to open up a can of worms, but something that has been top of mind for me is that temp storage needs to honor our zone configs. We can document that as a known limitation for now, but at some point when we move towards operationalizing partitioning, this will become very important.

That being said, is temporary storage also a feature that we would be better off marking as beta?

cc @nstewart so that he is aware of this convo.

**Comment by bdarnell** [comment]
Temp storage is used for intermediate steps of query processing; it cannot easily be associated with a table or zone. I think even documenting this as a "known limitation" is too much - it implies that if temporary storage were disabled zone configs are enforced much more strictly than they currently are.

**Comment by dianasaur323** [comment]
Ah, I see what you mean. I think in that case it's definitely out of scope for this current discussion.

**Comment by vivekmenezes** [comment]
@arjunravinarayan are you saying that we do have a mechanism to clear up temp storage on restart but it hasn't been tested when it fills up.
