### ISSUE TITLE
sql: func exec timeout GENERATE_SERIES

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18021]
`panic: func exec timeout: SELECT GENERATE_SERIES(9223372036854775807::int, -9223372036854775807::int, -9223372036854775807::int)`

The above error (it's not a real panic, just a timeout enforced by RSG) occurred. It's possible this isn't a bug and that function is supposed to take >10s to complete (see https://github.com/cockroachdb/cockroach/blob/6151997b9ca391811144e89e5544ede2a13ddac5/pkg/sql/rsg_test.go#L204). But filing here for triage or closure.

https://teamcity.cockroachdb.com/viewLog.html?buildId=338204&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by knz** [comment]
This is caused by an integer overflow:

- 1st iter: start = 9223372036854775807, start < end is still false
- 2nd iter: start = 0 (9223372036854775807 + (-9223372036854775807)), start < end is still false
- 3rd iter: start = -9223372036854775807, start < end is still false
- 4th iter: start underflows back to 9223372036854775806, start < end is still false
- ...
- 7th iter: starts underflows back to 9223372036854775805, start < end is still false
etc

(this loop never ends btw, because start < end can never be true: -9223372036854775807 is MinInt64)
