### ISSUE TITLE
sql: RSG func timeout: GENERATE_SERIES

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18070]
`func exec timeout: SELECT GENERATE_SERIES(-5191672249363875821::int, 2::int)`

The above query starts running and quickly consumes a full core and way more memory than the --max-sql-memory flag allows, so I assume we're missing some memory accounting here. This is a pretty easy query to DOS a server with. I tried to fix it but was not convinced about the correct way to memory account generators.

https://teamcity.cockroachdb.com/viewLog.html?buildId=339406&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by knz** [comment]
Generators do not accumulate data in memory server-side. The specific case of memory problem that this query could have caused in the past was fixed in d974d819eaaa87699fe79834d8431990739afc4a (#17835).

The stack trace here shows a simple timeout. This specific query would produce many results so I'm not surprised by the timeout. @mjibson are you sure there is a problem to fix? Perhaps what we should do here is have the RSG consume the results produced by a test query, and simply stop the processing (by closing the client connection) if, say, more than 1000 rows are received.

**Comment by mjibson** [comment]
Ahh the memory blowup was occurring in the client, not the server. Ok, yes, no bugs here.
