### ISSUE TITLE
sql: overloaded comparison to multiple elements in tuples and/or arrays

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#18088]
In queries that involve comparisons to elements in tuples or arrays, we support overloaded comparisons (e.g. `TypeInt` and `TypeDecimal`) for **constants**:
```
SELECT 1 IN (1.5, 2.5);
+-----------------+
| 1 IN (1.5, 2.5) |
+-----------------+
| false           |
+-----------------+
(1 row)

Time: 513.196µs
```

This however will not work if we explicitly cast the left as `::INT` or if we use an `INT` column and there exists at least one non-`INT` in the tuple:
```
SELECT 1::INT IN (1.5, 2.5);
pq: unsupported comparison operator: 1::INT IN (1.5, 2.5): expected 1.5 to be of type int, found type decimal

CREATE TABLE foo (bar INT);
CREATE TABLE

Time: 6.47495ms

SELECT * FROM foo WHERE bar IN (1, 2.5);
pq: unsupported comparison operator: bar IN (1, 2.5): expected 2.5 to be of type int, found type decimal
```
And similarly for operations such as `<left> <op> (ANY|SOME|ALL)(<array>)`.

Postgres overloads correctly:
```
CREATE TABLE foo (bar INT);
CREATE TABLE

INSERT INTO foo VALUES (1);
INSERT 0 1

SELECT * FROM foo WHERE bar IN (1, 2.5);
 bar
-----
   1
(1 row)

```

cc: @justinj @knz

**Comment by vivekmenezes** [comment]
We try our best to not do any implicit type conversion. There are a few exceptions we make but INT to FLOAT and back is not one of them.

**Comment by knz** [comment]
This is not a bug IMHO. I suggest you read the typing RFC and review it -- if you think it should be improved, you should start there not with bug reports :)

**Comment by jordanlewis** [comment]
Hmm, I'm not sure I agree with @knz or @vivekmenezes here - we do actually permit heterogeneous comparisons between the various numeric types:

https://github.com/cockroachdb/cockroach/blob/7dc6ca7ee699c5975228885758428fc97f45ada4/pkg/sql/parser/eval.go#L1179-L1208


BTW @richardwu this is definitely a confusing part of the code - the reason why your first example works while the explicitly casted one doesn't is that we have a separate set of rules for implicit casts of constants than we do of ordinary datums. You can see those special rules in `constant.go`.

In general, the reason for this bifurcation of rules is to make it easy to insert constant values or compare constant values, while preserving some semblance of a strong type system. For example, check out how the following example works:

```
root@:26257/test> CREATE TABLE m (a FLOAT, b timestamp, c string);
CREATE TABLE

Time: 9.377169ms

root@:26257/test> INSERT INTO m VALUES (2, '2017-08-20 01:02:03', '2017-08-20 01:02:03');
INSERT 1

Time: 7.289756ms

root@:26257/test> select * from m where b > c;
pq: unsupported comparison operator: <timestamp> > <string>
```

We allow the loose upcasting from string to timestamp since we're looking at a constant input, but we can't compare a string column to a timestamp since we're not looking at constants anymore.

Anyway, in your particular example if you changed the types from int/decimal to string/timestamp, I'd agree with @knz's and @vivekmenezes's assessment that we shouldn't support what you're asking for. I think in the case of mixed-numeric-type comparisons though we should definitely make an effort to support this use case, because not doing so would be inconsistent with the comparison operators that we already have.

**Comment by richardwu** [comment]
This was discussed recently during a typing meeting and the consensus was that we explicitly spec. out heterogeneity rules in an upcoming "typing" tech note.
