### ISSUE TITLE
server: "No Raft leader" problem range is inaccurate

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18154]
On `blue`, the "Problem Ranges" debug page lists 10 ranges as having "No Raft Leader". For 9 of these ranges, the problem seems to actually be an un-GC'd replica:

![screen shot 2017-09-01 at 2 15 44 pm](https://user-images.githubusercontent.com/6201335/29982534-14374bee-8f20-11e7-8847-9ed0ebcc9022.png)

I'm not sure why the replica on `n6` isn't getting GC'd, but it is inaccurate to describe this range as not having a Raft leader. And doing so hides the 1 range on the cluster that actually does lack a Raft leader.

**Comment by a-robinson** [comment]
> I'm not sure why the replica on n6 isn't getting GC'd

This looks like an unfortunate side effect of trying to avoid making RangeLookup calls in `replicaGCQueue.shouldQueue`. We only check the replica's copy of the descriptor to determine if it belongs rather than checking with the meta ranges, and [even that is an improvement over how it behaved in 1.0](https://github.com/cockroachdb/cockroach/commit/fc5ef3eeafef3c0a4687c23cc7b51245d4cda500). We could switch to doing consistent lookups or to doing them at least once in a while, but as you know there shouldn't be any inherent harm to having a replica like this around, just some annoyance in the debug pages.

I'm not sure why this has been popping up lately, though. I don't think I had ever seen it until a week or two ago, and now it's happened multiple times in quick succession. It's probably not just a coincidence.

**Comment by petermattis** [comment]
Well, the replica eventually got cleaned up so something did notice it eventually. The debug page issue could be rectified. We should notice that the replica that doesn't know about the leader is not a current member of the range. The range should be classified as having an "un-GC'd replica", not as having "No Raft Leader".

**Comment by BramGruneir** [comment]
So worst case, the replicaGC queue should scan and find it after what 10days?

And yes, the we can special case this in the range debug and problem ranges pages.  
But I'm not certain about the single node's problem ranges page.  As far as node6's replica is concerned, it just doesn't have a raft leader.  

This would be better solved server side to avoid having to do this special casing.  Is there any way for a replica to know that it's no longer part of the raft group and that it should be GCed?  (besides a RangeLookup?)

**Comment by bdarnell** [comment]
We should distinguish between range-level problems ("no leader", "multiple leaders", "underreplicated"...) and replica-level ones like this "replica doesn't know leader" (which in this case is really "replica needs GC"). 

To determine that a replica needs to be GCed, you can either do a consistent RangeLookup (which the replica GC queue does) or talk to the most current replica (which you have here). If the range descriptor of the replica with the highest commit index doesn't know anything about a particular replica, and the replica has a replicaID that is lower than the NextReplicaID of that descriptor, then it needs to be GC'd.

**Comment by bdarnell** [comment]
> I'm not sure why this has been popping up lately, though. I don't think I had ever seen it until a week or two ago, and now it's happened multiple times in quick succession. It's probably not just a coincidence.

It's possible that PreVote is interfering with the messages that normally trigger an immediate GC. With pre-vote turned off, this replica would become a candidate, send MsgVote to the replicas that it believed to be its peers, and when its votes get rejected it would schedule a replica GC. With PreVote, there are at least some cases when messages get dropped instead of an explicit rejection.

**Comment by a-robinson** [comment]
That makes sense, thanks for explaining the possibility.

**Comment by arjunravinarayan** [comment]
@BramGruneir is this going to be addressed in the 2.0 timeframe?

**Comment by petermattis** [comment]
@BramGruneir Is this a Web UI issue, or something that would be fixed on the backend which populates the data for the range debug page?

**Comment by BramGruneir** [comment]
A combo, but in all cases, most of the work will be on the server side.

For the most part the UI changes will be fairly trivial.  Even in the case where we split the problems ranges into two categories, which would require the most web ui work.

**Comment by petermattis** [comment]
Ack. Moving this into Core F&S where it will likely find traction in 2.2.
