### ISSUE TITLE
ui: Login Flow for Admin UI

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18206]
The Admin API now fully supports cookie-based authentication, which will restrict admin functions to authenticated users.  However, the UI does not currently provide a way for a user to authenticate, so that system has been disabled in 1.1.

A login page should be added to the frontend, and all other activities on the Admin UI should be protected by that login.  Details are available in the "web_session_login" RFC found under `/docs/RFCS`.

Works towards #6307

**Comment by dianasaur323** [comment]
Draft Acceptance Criteria - Accepting Comments

**User Story**
This is an important open source and enterprise user request. Currently, you have to some manual workarounds to block access to the admin UI. 

**Feature Scope**
Given that we will be implementing RBAC in 1.2, we will need to update user login to match that use case. For now, we will release user login as a beta feature before rolling it out permanently. The beta feature will be composed of:
- [ ] Simple login page that allows a user to log into the admin UI
- [ ] Talks to the backend, which authorizes any user with a password to log into the admin UI
- [ ] We will need a cluster setting to turn this on. It should be off by default so as not to effect our existing users and their workflows

**Required States**
- [ ] Login page
- [ ] Loading state
- [ ] Some sign of logged in status in the admin UI

**PM Acceptance Testing**
- [ ] Create a user and password
- [ ] Login as that user
- [ ] Observe the different states that the admin UI gets into
- [ ] Try accessing the admin UI from a different node
- [ ] Try chrome, safari, mozilla, IE
- [ ] Observe what happens when you close out the window

**Comment by couchand** [comment]
Closed in #28416
