### ISSUE TITLE
backup/restore: support SELECT FROM <backup>

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#18209]
This is a placeholder issue for this idea that @danhhz  had. We can start working on it once we figure someone is interested.

Jira issue: CRDB-6014

**Comment by dianasaur323** [comment]
Acceptance Criteria - Accepting Comments

**User Story**
As a DBA, I want to be able to know what timestamp I should restore my database to in the case of a disaster event.

Currently, users might restore the full database into a testing environment, query for the timestamp they want to get to, and then run the restore. We can provide a significant usability with with select from backup. Also, we can provide the E and L in ETL, to some extent.

**Ongoing Questions that need additional scope**
- [ ] Are we going to be able to support the entire syntax of CockroachDB? (I'm assuming yes?)
- [ ] What would the user experience be of querying a backup?
- [ ] What would our performance look like? 

@danhhz I'm going to rely on you to help me flesh this out and make those design decisions since you are the one who knows best, but those are some questions that I'll be thinking about when I move onto...

**PM Acceptance Testing**
- [ ] Backup TPCH Cluster
- [ ] Set up select from backup
- [ ] Run some select queries
- [ ] Run some selects with joins
- [ ] What do the error messages look like?
- [ ] How could users potentially mess up, and do we provide some safety guards for them?

**Comment by danhhz** [comment]
This has been moved to 2.1

**Comment by danhhz** [comment]
I had a prototype PR for this that was out for a year and clearly isn't going anywhere, so I'm closing it. There were a few good initial review comments on it, so I wanted to make note of that here. See https://github.com/cockroachdb/cockroach/pull/20664

**Comment by shermanCRL** [comment]
Quick Bulk IO team feedback: a valuable feature, keep it in the backlog.
