### ISSUE TITLE
sql: Add ASYNC/AWAIT or futures for parallel statements

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#18226]
This will allow a client to issue sql statements that can be executed asynchronously.

We can start working on this once there is a need.

**Comment by bdarnell** [comment]
SQL [cursors](https://www.postgresql.org/docs/current/static/plpgsql-cursors.html) are a SQL-standard way of executing queries without blocking on them. We should consider implementing (and extending if necessary) the cursor statements instead of introducing foreign concepts like async/await to SQL.

**Comment by jordanlewis** [comment]
+1, I don't think it's a good idea to introduce a brand new concept to our SQL dialect unless absolutely necessary. I think it would make interop with existing drivers and tools quite difficult.

**Comment by jordanlewis** [comment]
We're planning to add pgwire-level cursors at some point, so I'm closing this as wontfix.
