### ISSUE TITLE
`(*TxnCoordSender).cleanupTxn` is sometimes called twice and deadlocks

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1823]
`make CPUS=4,4,4,4,1,2,3,5,6,7,8,9,10 TESTFLAGS='--verbosity=2' PKG=./kv TESTTIMEOUT=5m TESTS=TestTxnDB`

Run that a few times and you'll eventually get https://gist.github.com/65836cb3f0c0e9ca3776

**Comment by bdarnell** [comment]
`cleanupTxn` may be called either from the sender's thread (after EndTransaction returns or we see certain errors) or from the heartbeat thread (after a heartbeat fails), so we need to make it thread-safe and idempotent. I think we should just keep the `txnMeta.txnEnd = nil` and exit early from `cleanupTxn` if `txnEnd` is nil.

**Comment by tamird** [comment]
`txnMeta.txnEnd = nil` is dangerous because sending on nil channels blocks forever. We could use a `select` with an empty `default` though.

**Comment by bdarnell** [comment]
And sending on a closed channel panics, but we (unnecessarily) close the channel here. We use `txnEnd == nil` as a signal that `cleanupTxn` has already been called; the one place where we send to txnEnd should be guarded by an explicit check of the variable instead of a non-blocking send (because we don't want to double-trace the cleanup when this happens either).

**Comment by tamird** [comment]
Sounds reasonable.
