### ISSUE TITLE
sql: TestTrace: slow ALTER TABLE ... SPLIT AT

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18246]
From [a comment](https://github.com/cockroachdb/cockroach/issues/17798#issuecomment-327346140) on #17798:

> I see waiting for replication take ~500ms, creating the database and tables taking <100ms and splitting the table taking >3s. I wonder why the split is so slow. 

In other testing recently, I've seen clusters performing hundreds of splits per second. Seems likely this is some test anomaly, but worth tracking down in case it isn't.

**Comment by petermattis** [comment]
The test is doing the following:

```
CREATE TABLE test.bar (id INT PRIMARY KEY);
ALTER TABLE test.bar SPLIT AT VALUES (5);
```

After creating the table, the split queue is immediately trying to split it. This occurs just before the manual split performed by the `ALTER TABLE` statement causing the `ALTER TABLE` split to need to be retried. I'm not sure if there is anything easy to be done here.

**Comment by bdarnell** [comment]
Even if the split gets retried, it shouldn't take 3s. 

Maybe `CREATE TABLE` should perform the split synchronously? An immediate `ALTER TABLE SPLIT` is most severely affected by this, but any insert to the new table will have to wait for the split to complete (unless it finishes before the split starts)

Alternately, we could very easily pre-split a few empty ranges at the end of the keyspace (add N to GetLargestObjectID in [ComputeSplitKey](https://github.com/cockroachdb/cockroach/blob/9ab2e8c0fb3238c0f168b11736fa91135604341e/pkg/config/config.go#L512). This allows `CREATE TABLE` to start using an existing empty range immediately, and the split queue will asynchronously split off a new range for the next new table. This would improve the perceived latency of `CREATE TABLE` followed by an action on the table, although it would probably be counterproductive for our tests since it adds additional splits to be performed at cluster initialization.

**Comment by petermattis** [comment]
You're correct that it shouldn't take 3s for the split to get retried. Something else seems to be going wrong. Right now I'm seeing:

`I170906 12:58:30.242170 2283 storage/replica_command.go:2710  [n1,s1,r17/1:/{Table/50-Max}] initiating a split of this range at key /Table/51/1/5 [r18]`
`I170906 12:58:34.808152 2283 storage/replica_command.go:2612  [n1,s1,r17/1:/Table/5{0-1}] retrying split: unexpected value: raw_bytes:"\352\244\252\272\003\010\021\022\001\272\032\001\273\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\002\"\006\010\003\020\003\030\003(\004" timestamp:<wall_time:1504717114272091654 logical:1 >`

I need to add some more logging to see what else is happening on `r17` during that time.

**Comment by petermattis** [comment]
The underlying problem seems to be we don't have a Raft leader for `r17` when the split starts. Currently, there are 16 ranges created at start. `r17` is created following the `CREATE DATABASE test` statement. For some reason we're not campaigning this range. After the `CREATE TABLE test.bar ...` statement arrives we try to split `r17` and that split hangs along with the split from an `ALTER TABLE`. Question is why didn't we eagerly campaign `r17` after it was created.

**Comment by bdarnell** [comment]
Are you sure we didn't campaign? (as opposed to campaigning and that campaign somehow failing)

The campaign logic in `Replica.withRaftGroupLocked` is subtle. I think what we may be seeing here is that a newly-started store won't automatically campaign for new replicas unless it's been up for at least an election timeout (to ensure that a restarted store won't be disruptive). That doesn't work well in tests (I don't think we have many tests that split an already-replicated range). I thought we already had some sort of special case for tests that would apply here but I can't find it now.

If this is the case, a potential for a safe special case is for a store which is the only member of a cluster to backdate its startup timestamp so that it can campaign immediately for new replicas. That wouldn't cover everything but I think it would cover this test.

**Comment by petermattis** [comment]
Yep, I'm sure we didn't campaign. You're on the right track with your
suggestion, though we already have such logic. Problem is there is a hole
in that logic for the node which bootstrapped a cluster. Easy to fix and it
shaves 80s off the runtime of our tests. I'll send out a PR after dinner.
