### ISSUE TITLE
sql: can't CAST untyped empty arrays

### ISSUE THREAD

**Issue by ivan** [cockroachdb/cockroach#18420]
Not sure if a feature request or a bug.  This came up while trying to find a PostgreSQL-compatible workaround for #18419.

PostgreSQL 9.5.8:

```
postgres=# SELECT CAST(ARRAY[] AS int[]);
 array 
-------
 {}
(1 row)
```

CockroachDB 5fedec7e39f1a558c7f705ea82de2df9fc413a60:

```
root@:26257/> SELECT CAST(ARRAY[] AS int[]);
pq: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
```

**Comment by justinj** [comment]
Thanks for the report @ivan! In the interim, there are two workarounds I'm aware of you could try to use:

1. As the message says, you can use the Cockroach-specific syntax `ARRAY[]:::INT[]`, which tells Cockroach to infer the expression to be of the given type (rather than casting it after-the-fact).

2. I realize that's insufficient if you want something compatible with Postgres, the only thing I can think of offhand would be to create the array in some other way (something like `ARRAY_REMOVE(ARRAY[1], 1)` for an array of ints, or in your specific case you could do `ARRAY_REMOVE(ARRAY[1::OID], 1::OID)`).

Obviously neither of these options are ideal, I'll look what can be done to resolve this in a more satisfactory way. Thanks for sharing your use-case with us!

**Comment by dianasaur323** [comment]
@justinj I stuck a milestone on this so that it doesn't get lost in the shuffle.
