### ISSUE TITLE
ui: make per-node views actually per-node

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18452]
On the per node view in the admin UI, we are showing node list. This is confusing from an information architecture perspective, since that is a cluster-wide metric.

![image](https://user-images.githubusercontent.com/5768024/30336078-1e173b8e-97b2-11e7-96bd-8cfca66f8304.png)

**Comment by a-robinson** [comment]
This actually has a use, though. Each node has its own view of how many live nodes there are in the cluster at a time. If a node is far behind or partitioned away from the others, its reported node count will be different from the count reported by the other nodes.

We'd probably be better of calling the graph "Live Node Count" rather than just "Node Count", but I don't think we want to change what it shows.

**Comment by dianasaur323** [comment]
Ok, that makes sense, although it begs the question of if having this as a time series graph is really the right approach. It makes me think that we should have a view that shows what each node currently sees as cluster state. We are unlikely to have time to do this in 1.2, so I think your approach of calling it that, and perhaps adding a tooltip of why it matters would be an appropriate first step.

**Comment by couchand** [comment]
This naturally rolls into some bigger IA questions.  Notably, some charts show aggregates for the cluster as a whole and other show a breakdown by node.  Some charts (such as latency) have several different percentile charts, where having a single chart showing multiple percentiles would be more valuable.

**Comment by dianasaur323** [comment]
haha, don't open the can of worms @couchand! jk, but yes agree that we should approach this problem holistically when we get to it.
