### ISSUE TITLE
storage: replica write QPS computation seems incorrect

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18607]
I was working on #15997 when I wondered why I was getting the following suspiciously low stats for a replica that was serially plowing through batches of 100 ResolveIntent each:

```
“stats”: {
        “queriesPerSecond”: 2.140486885553871,
        “writesPerSecond”: 0.15809450129414426
      },
```

Spelunking a bit, it seems that we use the following to compute the write QPS:

```go
r.writeStats.recordCount(math.Max(float64(rResult.Delta.KeyCount), 1), 0)
```

But `rResult.Delta` is the MVCC stats diff. That is, if you write a version of an existing key, nothing changes. Similarly, when you resolve an intent, nothing changes.

This computation just doesn't seem right except when the operation exclusively creates new keys. I think for the right value we need to look at the `BatchRequest`. It doesn't seem trivial to compute the intuitively "correct" quantity, and perhaps we should clarify further what that means.

**Comment by tschottdorf** [comment]
Also, I think it's intentional, but note how `0` (as a NodeID) is passed as the second parameter. That deserves commentary either there or on `record{,Count}`.

**Comment by a-robinson** [comment]
Oh, nice find! This value doesn't really have to use keys written per second. In fact, it originally just tracked the number of commands applied per second (#16664). I don't know that it's worth doing anything expensive or fancy here, perhaps changing to a different unit would be sufficient. Do you have thoughts on trying to fix the semantics of tracking keys vs switching to tracking commands applied vs switching to tracking bytes written?

Also, you're right that passing a 0 `NodeID` is intentional, but I can add a comment there.

**Comment by tschottdorf** [comment]
It really depends what we want to track -- obvious candidates are

1. number of applied Raft commands (you seemed to have wanted more than that)
1. number of "changed" keys -- this isn't so easy to track; for example, `DeleteRange` can touch 0 to 1 trillion keys
1. just track the number of requests in a batch (i.e. a `DeleteRange` is a write; a `Put` is a write, etc)

I think the last option makes the most sense, but can't be properly populated on the followers unless we augment the replicated proposal.

**Comment by tschottdorf** [comment]
(I'd also be fine with 1. if we renamed the metric to `raftQPS`, though I think that for stats-based rebalancing you'll want something that isn't as dependent on how well the user's application batches).

**Comment by petermattis** [comment]
@tschottdorf Exactly as you observe, the concern with 1 is that it doesn't adequately reflect the different load from a Raft command writing 1 key vs a command writing 1000 keys.

**Comment by a-robinson** [comment]
@petermattis do you think counting the size of the write batches instead of the number of keys written would be a reasonable replacement? The big benefit of that is that no additional info needs to be passed along in the proposal to make it work, and it does approximate the I/O load caused by the range. @tschottdorf didn't have any reasons against changing to that, but we didn't dwell on it for very long.

I'm asking before constructing the entire PR because I proliferated variants of the name `WritesPerSecond` through a lot of code, and don't want to go through and all of them unless the core idea is alright.

**Comment by petermattis** [comment]
@a-robinson The count of the number of keys (well, the number of mutations) is present in the proposal: 

```
  batchReader := engine.NewRocksDBBatchReader(RaftCommand.WriteBatch.Bytes)
  log.Infof(ctx, "batch count: %d", batchReader.Count())
```

I'm not sure if counting keys or bytes is better. Certainly, there is per-key overhead at the RocksDB level. But bytes could possibly be a good approximation and also captures the overhead of writing more data. I don't have a strong preference.
