### ISSUE TITLE
jobs, cli: do not surface table/view IDs, and instead report names

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#18623]
Table/view descriptor IDs are currently still an "internal" property of CockroachDB.

It is thus a UX error to report them in the job details.

**Comment by bdarnell** [comment]
"Leaking" table IDs in admin RPC responses isn't a problem. They're an implementation detail, but they're not sensitive and they're useful for interpreting the `/debug/` pages which are full of implementation details (including keys starting with table IDs). We should always show table names instead of ids in the main UI, but we don't have to worry about erasing all traces of the IDs.

**Comment by knz** [comment]
Nothing to see here.
