### ISSUE TITLE
ui: table disappears during TRUNCATE

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#18666]
Split out of #18657.

> Doing a TRUNCATE TABLE bench; while inserts are running, results in the table not being displayed in the admin UI. It re-appears once the TRUNCATE is finished.

**Comment by dianasaur323** [comment]
@cuongdo, during our bug bash, it appears that this would require some backend investigation. Could you assign someone with that context to take a look?

**Comment by vivekmenezes** [comment]
TRUNCATE internally does a DROP/CREATE of the table. Any reason for wanting this fixed in 1.2

**Comment by dianasaur323** [comment]
No, this just appeared to be a bug and I know we have some weird behavior on showing what tables are in the database at the UI level. Based on that, I'm not sure this is a bug?

**Comment by jordanlewis** [comment]
cc @tschottdorf @spencerkimball for re-triage after your drop/truncate work is complete

**Comment by tschottdorf** [comment]
I *think* that after addressing some of the concerns in #20601 it may actually be possible to just truncate the existing table in-place (i.e. avoid the drop-create), but that would kill time travel which I think we don't want at this point.

Given that constraint, I think the UX concern here stays the same. I am also of the general opinion that tables become "invisible" too early in the DROP cycle. Perhaps addressing that can also address this issue here. If we "grayed out" tables in the UI (marking them as "being dropped") the UX would be much better, and being able to see the stats until the tables are really gone is a big win.

**Comment by dianasaur323** [comment]
murgh, it is looking increasingly unlikely we will have time to get to this in the 2.0 release cycle. You may see the milestone silently slip to 2.1 soon.
