### ISSUE TITLE
improve configuration of rebalance timing for maintenance events (acceptance criteria)

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18696]
--- FINAL Acceptance Criteria ---

Users running maintenance events on nodes do not want planned node outages to impact the throughput and performance of ongoing application traffic. 

We currently offer several solutions to this - either using kv.snapshot_rebalance.max_rate to limit how much bandwidth rebalancing consumers, or server.time_until_store_dead to increase the amount of time a node can be dead before the cluster marks it as dead and beings rebalancing.

Both of these options increase the possibility of user error - users could forget to readjust the settings after maintenance events.

**Proposed Feature Scope**
- [x] Go with the server.time_until_store_dead approach, since it directly maps to being able to control when CockroachDB recognizes that a node is dead
- [x] Highlight cluster settings in the cluster settings table that are not default for better usability (I think we can punt on this for now until we figure out a holistic approach)
- [x] Document how to handle maintenance events using these feature flags @jseldess (status -> passed on to docs)

**PM Acceptance Testing**
- [x] Set server.time_until_store_dead to something greater than 5 minutes -> set to '1h' and killed at 4:18PM Sunday
- [x] Take a node down
- [x] Observe rebalancing behavior
- [x] Observe how non-default values are highlighted (punt)

In acceptance testing, it was hard to directly observe rebalancing when bringing a node down, since that action caused issues with the cluster admin UI. That being said, once I brought the node back up, I did observe that it did not appear that rebalancing had occurred at all.

**Comment by cuongdo** [comment]
This might have an interaction with #14768.

**Comment by jseldess** [comment]
@dianasaur323, the second and third checkboxes under proposed features scope are the potential new developments, right? If so, since we do already "allow" this type of configuration, should we perhaps rename this title to be something more about informing users of impending rebalancing?

Btw, in terms of docs, I recently expanded the 1.1 docs with [an explanation of what happens when a node is stopped and a recommendation to increase the `server.time_until_store_dead` setting in cases where a node is expected to be offline for longer than 5 minutes](https://www.cockroachlabs.com/docs/dev/stop-a-node.html#how-it-works). I considered adding this tip to the 1.1 rolling upgrade docs, but @bdarnell discouraged it in that context, since nodes should never be offline for long during an upgrade.

**Comment by bdarnell** [comment]
> would anyone want to permanently set this to be longer than 5 min?)

Yes. When a store is recognized as dead, a relatively expensive rebalancing process begins. If your inter-DC bandwidth is expensive and your nodes are individually reliable (e.g. because you're using RAID), you might want to defer the repair process until an admin manually decommissions the node (after verifying that the machine is really dead to avoid false positives, and maybe waiting until off-peak for cheaper bandwidth). 

Running with a lower time_until_store_dead might make sense too - it could waste resources with unnecessary rebalancing, but it would be a bit more robust since you'd be less likely to hit two failures too close together (but the effect would probably be small since the thing that really matters is time_until_store_dead plus the time it takes to complete the repair process. This depends on the amount of data per node and the number of nodes in the system).

The choice of 5 minutes as the default was fairly arbitrary. In talking to users who want to use this setting, do they want to change it temporarily or permanently (and to what)? Would a different default make sense?

**Comment by dianasaur323** [comment]
@jseldess yes, items two and three would require some feature work, but perhaps the title should be tweaked a bit as you suggested. The one note on your docs is that it would be great to add the key word maintenance, so that it is searchable. Apologies if I missed it while I was skimming.

@bdarnell exactly, those are the questions I have - what is the usability downside of only providing a permanent instead of temporary change to the config? I can take a look through my list of user feedback to see if we can get anything before we do additional work. Regarding the default, my sense is that we can keep the default for now since we have limited data on how people are actually setting things up, and we could make a better decision later on with more data.

**Comment by jseldess** [comment]
@dianasaur323, I agree that those instructions aren't very findable. I'll work on that.

**Comment by mberhault** [comment]
I'm not sure we want to automatically revert config changes. Even if we do, we'll have to provide yet another config setting to disable reverts.
A good first step would be to expose the cluster settings and highlight any non-default values. Surfacing it higher (eg: a banner on the entire admin UI) may be overkill unless we can find a good way to determine that it is causing issues.

**Comment by dianasaur323** [comment]
hmm.. @mberhault I agree with your sentiments fully. I'll update the specs in the first comment to reflect that. I'm assuming highlighting non-default values in the cluster settings would be something like SHOW NONDEFAULT or something like that?

**Comment by robert-s-lee** [comment]
is it acceptable to set server.time_until_store_dead = '2m0s' for example?  Below is an example where "2m0s" was used on v1.2-alpha.20171211.  The database recovered at 2 minute mark, but UI seems to wait for 5 minute mark to update the dead count.

<img width="1280" alt="screen shot 2017-12-11 at 9 07 36 pm" src="https://user-images.githubusercontent.com/6315124/33864130-2fe64866-deb9-11e7-80b3-bae019e05839.png">
<img width="1280" alt="screen shot 2017-12-11 at 9 06 18 pm" src="https://user-images.githubusercontent.com/6315124/33864131-2ff35fba-deb9-11e7-81dd-db689ebc6e09.png">
<img width="1280" alt="screen shot 2017-12-11 at 9 04 15 pm" src="https://user-images.githubusercontent.com/6315124/33864132-2fff24b2-deb9-11e7-996a-1644f30f829b.png">

**Comment by dianasaur323** [comment]
Hmm... we do tell people to change that toggle if they want to run maintenance jobs. That means that the node being recognized as dead might be hard coded. cc @mrtracy is this true? We might want to tie that number to this setting?

**Comment by a-robinson** [comment]
Yeah, the UI value is still hard-coded since the duration wasn't always configurable: https://github.com/cockroachdb/cockroach/blob/8cde1b1a9ed30296eb10cf69d78f10862d008ea2/pkg/ui/src/redux/nodes.ts#L15

**Comment by dianasaur323** [comment]
thanks @a-robinson I think we may need to make that value not hardcoded then. @couchand could we squeeze this in in this release? should i open a separate issue for tracking purposes?

**Comment by dianasaur323** [comment]
Ok, I've finished QA-ing this, with some notes of the process / observations in the first comment. It is a bit odd to observe how the recognition of dead nodes in the admin UI does not match the cluster setting (I set the cluster setting to 1m, and it took 5m for the admin UI to recognize the node as dead). I've opened a separate issue here, and closing this since everything else looks good. 

https://github.com/cockroachdb/cockroach/issues/21632
