### ISSUE TITLE
sql: make EncDatum comparisons safer

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#18726]
#18702 revealed that it's easy to mess up comparisons on encodings, since we pack so much information into our various encodings. @richardwu suggested declaring a preferred global encoding, @andreimatei suggested making `EncDatum.Compare` always re-encode if the given encoding is potentially suspect (i.e. a `ValueEncoding`). Tracking any remaining discussion here, to speed up merging of #18702.

**Comment by andreimatei** [comment]
I think the EncDatum.Compare check could have been in your previous PR. If it works, then it's a one line change. If it doesn't, the we have more bad bugs like the one you've found that need fixing.

**Comment by arjunravinarayan** [comment]
I just wanted to get the fix out into the release binary as fast as possible. We can fix this on Monday.

**Comment by danhhz** [comment]
We encode the column ids in the value using diffs (which could save a bit of space since the varints are smaller for smaller numbers). And we omit NULLs. Concretely, for columns with ids 1 and 3, the rows `('10', '20')` and `(NULL, '20')` would be `/1:INT:10/2:INT:20` and `/3:INT:20` respectively.

I strongly recommend that we adjust these diffs to be the column ids in RowFetcher when they're returned as VALUE encoded EncDatums. This would have avoided the #18702 bug and is likely to keep biting us if we don't fix it, it's quite unintuitive.

**Comment by arjunravinarayan** [comment]
Thanks @danhhz: So if we just forced RowFetcher to wipe ColumnIDs from ValueEncoded `EncDatum`s, with a 

`encValue.encoded[0] = encValue.encoded[0] & byte(encoding.SentinelType)`

that should fix everything, right?
