### ISSUE TITLE
sql: KV requests done for schema changes and backups shouldn't affect follow-the-sun request stats

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18768]
Currently all requests set the `BatchRequest.GatewayNodeID` field which is then used to compute access statistics and decide where a range should be placed so that it's close to the users accessing it.
There's some category of operations that produce requests that shouldn't affect these stats, and so we should have a mechanism for them to indicate so. 

cc @a-robinson

**Comment by knz** [comment]
cc @vivekmenezes for triage

**Comment by rolandcrosby** [comment]
let's just do this for ExportRequest

**Comment by dt** [comment]
I'm not eager to add special cases if we don't need them - a backup usually only sends one exportrequest to each range and that alone shouldn't cause it to move. Plus in 20.2 BACKUP will likely switch to using a distsql flow with partitioned processors sending local requests instead of central coordinator sending ExportRequests directly to each range which would make this moot.
