### ISSUE TITLE
cli: regression in test Example_sql_format

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#18774]
I simply ran `make test PKG=./pkg/cli` on a recent master on my Linux system - no other changes.
This seems to have regressed with #18676.

```
--- FAIL: Example_sql_format (0.15s)
got:
sql -e create database t; create table t.times (bare timestamp, withtz timestamptz)
CREATE TABLE
sql -e insert into t.times values ('2016-01-25 10:10:10', '2016-01-25 10:10:10-05:00')
INSERT 1
sql -e select * from t.times
bare    withtz
2016-01-25 05:10:10+00:00       2016-01-25 15:10:10+00:00
# 1 row
want:
sql -e create database t; create table t.times (bare timestamp, withtz timestamptz)
CREATE TABLE
sql -e insert into t.times values ('2016-01-25 10:10:10', '2016-01-25 10:10:10-05:00')
INSERT 1
sql -e select * from t.times
bare    withtz
2016-01-25 10:10:10+00:00       2016-01-25 15:10:10+00:00
# 1 row
```

**Comment by knz** [comment]
Related error:
```
--- FAIL: TestDumpRow (0.12s)
        test_log_scope.go:78: test logs captured to: /tmp/logTestDumpRow497595155
        test_log_scope.go:61: use -show-logs to present logs inline
        dump_test.go:135: expected: dump d t
                CREATE TABLE t (
[...]
                INSERT INTO t (i, f, s, b, d, t, n, o, e, u, ip, tz, e1, e2, s1) VALUES
                        (1, 2.3, 'striiing', b'a1b2c3', '2016-03-26', '2016-01-25 10:10:10+00:00', '2h30m30s', true, 1.2345, 'e9716c74-2638-443d-90ed-ffde7bea7d1d', '192.168.0.1', '2016-01-25 10:10:10+00:00', 3,\ 4.5, 's'),
[...]
                got: dump d t
                CREATE TABLE t (
[...]
                INSERT INTO t (i, f, s, b, d, t, n, o, e, u, ip, tz, e1, e2, s1) VALUES
                        (1, 2.3, 'striiing', b'a1b2c3', '2016-03-25', '2016-01-25 05:10:10+00:00', '2h30m30s', true, 1.2345, 'e9716c74-2638-443d-90ed-ffde7bea7d1d', '192.168.0.1', '2016-01-25 10:10:10+00:00', 3,\ 4.5, 's'),
[...]
```

Same error as above, different test.

**Comment by knz** [comment]
This is on GNU/Linux; my `/etc/timezone` contains `America/New_York`.

I'd wager you haven't noticed before because both your Docker image and our builder VMs don't have `/etc/timezone` or have it configured to UTC.

**Comment by knz** [comment]
If my suspicion is right, I think we should still default to UTC wherever the code would otherwise fall back to the timezone on the node's host system.

**Comment by knz** [comment]
(FWIW, I just checked with the builder image: indeed inside the builder the test doesn't fail. The builder's `/etc/timezone` is UTC.)

**Comment by knz** [comment]
I bet your removal of the `else` branch in `pgwire/types.go` line 415. If I add it back, the tests passes.

Either that code needs to be changed back (I'm 99% sure that's the correct solution), or the tests need to be modified.

**Comment by dt** [comment]
Hm.

If you have a timestamptz and cast it to a timestamp (no-tz), SQL expects it to print exactly the same - - i.e. same localized hour/minute - just without the offset string on the end. It *also*, based on the example in #16228, apparently expects the cast to use the session offset.  Having the cast to a `.In(sessionLoc)` to the underlying time.Time satisfies the later, but if we then `.In(UTC)` it during formatting, we'll incorrectly print a non-offset hour/min. If we leave the time.Time's offset intact, we'll correctly format the hour/min and then just not print the offset, satisfying both expected behaviors (and, I suspect, when we add support for the `AT <offset>` syntax, we'll want to carry around and respect these offsets even more).

I think the issue is the time.Time should have been `.UTC()`ed before it ever even made it into a datum, as it was being decoded, and indeed, I think if we did that in `NewDTimestamp` and `MakeDTimestamp` we'd be okay.

That said, there are *a lot* of `time.Unix` calls around the codebase, each of which is a potentially host-dependant `time.Time` waiting to sneak in because it implicitly applies `time.Local`. Given that we expect clusters made of geographically diverse but supposedly interchangeable nodes, the fact that that this behavior is host dependent makes me antsy, and I almost wonder if we shouldn't just `time.Local = time.UTC` in `init()` ? The only place where I think we intentionally use `time.Local` is logging.

**Comment by dt** [comment]
@knz I wonder how we should add a ci/osx-friendly test to repro this... mess with `/etc/timezone` in a docker test? mess with `time.Local` ?

**Comment by knz** [comment]
Mess with `/etc/timezone` in a docker test is OK in my book.

I would be :+1: on `time.Local = time.UTC` in `init()`. I don't care that the logs then become UTC, actually it makes them more comparable across nodes with different timezones. We can always propose a utility to shift them by an offset (and/or do that in the admin UI viz). @bdarnell  OK for this blunt approach that would solve the problem throughout?

**Comment by dt** [comment]
we could also wrap `time.Unix` in `timeutil.Unix` and lint for it like `time.Now`, which might be friendlier towards anyone who tries to depend on cockroach as a lib.

**Comment by knz** [comment]
FWIW, although the initial issue description above pertained to cli tests only, that's because those were the only two tests I was running. I just checked with the rest of the test suite, and there's brokenness everywhere. I think just bumping the standard timezone in the builder image to something non-UTC will catch a lot of bugs in the future.
