### ISSUE TITLE
sqlccl: better verification of partial backup when job resumes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18873]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/sqlccl/backup.go#L798

**Comment by mjibson** [comment]
@benesch What is the user-facing impact of this? Will the backup fail, or will it re-do some work?

**Comment by benesch** [comment]
A broken or missing checkpoint simply means the backup resumes from the very beginning. The concern is that the checkpoint is somehow corrupted, rather than just missing because the first attempt didn't make it far enough to write out a checkpoint, and we can't currently return an error to that effect.
