### ISSUE TITLE
sqlccl: AddSSTable 1x write amplification

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18888]
Talk to Toby.

**Comment by mjibson** [comment]
Dup of #16937

**Comment by dt** [comment]
recent developments here: 

a rough draft branch from @benesch in #26347 that rewrote the seq no on the fly, but that looked scary to many.

More recently, @petermattis pointed out we could fix this in rocksdb itself, by avoiding modifying the file altogether, by instead storing the seqno in the mutable metadata (that needs to be updated anyway to add the sstable).

**Comment by petermattis** [comment]
This has already been fixed upstream in RocksDB by https://github.com/facebook/rocksdb/pull/4172. I don't think that PR is in a RocksDB release yet. We can either pull it into our fork our wait. There is also a new setting that we need to enable in order to take advantage of it, though we need to be careful as that setting will prevent downgrading (perhaps we tie it to a cluster setting).

**Comment by petermattis** [comment]
@dt This can be closed, right?

**Comment by dt** [comment]
Yep, done.
