### ISSUE TITLE
`client.Batch.Results` doesn't get filled on error

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1891]
For a batch containing multiple calls, it's impossible to determine which call failed. This happens because the error case short-circuits the execution of `client.DB.Run`:
```
func (db *DB) Run(b *Batch) error {
	if err := b.prepare(); err != nil {
		return err
	}
	if err := db.send(b.calls...); err != nil {
		return err
	}
	return b.fillResults()
}
```

**Comment by tschottdorf** [comment]
When moving to the `(reply, error)` pattern we need to do more here.
First of all, there's a problem in 2dcd8f1 itself: errors are only taken from the calls themselves, but `send()` can generate its own errors (failed proto merges). That could be fixed, but intrinsically the code relies on there being errors on the individual requests in a call, which is not something that carries over well to `(reply, error)`, where you don't want to return a reply when there's an error.
I ran into this on my WIP #2141 but will postpone fixing it to avoid chaos.

The most logical fix, I think, would be
```go
pErr := &proto.Error{Index: i}; pErr.SetResponseGoError(err)
```
This should work well except that many type assertions on errors need to be careful. To avoid subtle bugs, it would be better to change the response type to `*proto.Error` from `store.ExecuteCmd` upwards; all type assertions can change to `.GoError()` and be fine. We'll potentially lose a little bit of `err` shadowing logic in some places, but I don't think much. Explicitly using `*proto.Error` could even be clearer since right now, an `error` could either be from the `ErrorUnion` or a `*proto.Error`, and it's always a bit sketchy not knowing which one you're working with. Potentially we could avoid implementing `error` on `*proto.Error` in this way.

Other options are returning the index along with a separate error or bundling them up into a new type which is not `proto.Error`, but I think those would wind up more confusing (esp. the latter, since that potentially makes more confusing nestings of errors legal). Or, of course, continuing to provide responses even when there's an error, but I'd rather not.

**Comment by bdarnell** [comment]
Returning `*proto.Error` when that type implements `error` is risky because of the nil interface problem (https://golang.org/doc/faq#nil_error). If we can remove `Error()` from `(*proto.Error)` then I'd be in favor of doing that but I'm not sure how common it is to mix `proto.Errors` and other errors.
