### ISSUE TITLE
docs: Markup languages for docs/rfcs

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18985]
Currently, all our docs are written in (github-flavored) markdown. There have been two attempts to write RFCs or docs in RestructuredText (ReST or `.rst`) (#18575 and #18977); this issue will serve as the decision point to either
1. Reiterate our use of markdown and insist on it for all docs/rfcs
2. Allow both markdown and ReST for new docs according to the author's preference
3. Make ReST the preferred format for new docs (possibly also migrating existing docs)

If we start using ReST, we should also standardize on a toolchain (#18977 uses docutils and graphviz and some ad-hoc scripts). 

cockroachdb/docs#1716 discusses moving the docs repo away from markdown; it would be nice to move in the same direction here.

**Comment by bdarnell** [comment]
My opinion: I like sphinx, but only tolerate ReST (and I especially dislike context-switching between markdown and ReST). If the docs team decides to adopt sphinx, then I think there is merit to standardizing on ReST everywhere (except in places like the GH issue tracker where markdown is the only supported format). Otherwise, I'd prefer to stick to markdown due to its ubiquity.

I'd rather *not* make this decision on a doc-by-doc basis, because we sometimes make bulk changes to the RFCs (updating links, etc) and using multiple formats just complicates that.

**Comment by knz** [comment]
Ack.

The discussion here should take into account the reasons why rst is being considered instead of markdown. The issue at cockroachdb/docs#1716 lists reasons that pertain to the docs site; those reasons that pertain specifically to RFCs and tech notes are:

- Need to auto-generate tables of contents.
- Need to generate inter-doc and inter-section references that are impervious to title renames.
- Need to automatically number sub-sections for faster navigation/discussion.
- Need to provide code examples with syntax highlighting inside a table.
- Need to provide tables containing multiple paragraphs in one cell.

All of these are non-starters with markdown and non-issues with rST.

**Comment by knz** [comment]
Regarding the use of graphviz in #18977 and custom toolchains in general.

I think that it is only natural that as we grow we will need more and more agility for management. 

In this particular case I have searched, but failed to find, off-the-shelf tooling which provides the DAG view I am looking for and automatic tables of sections for sub-sections to ease navigation. For me the argument "well then don't use TOCs / a DAG if our tools cannot generate them" is a non-starter, this would be as the British say "the tail wagging the dog". There's a need to get this view, and given that I didn't find something off the shelf I decided to make it myself. We can argue on the implementation, that's OK, but the need remains. Incidentally, with rST it is rather doable to create plug-ins that add new markup syntax in a way that integrates well with other doc generators. If/when we use a generator we could convert the Makefile/awk combination in that PR to a native rST plugin.

In general in the future we should expect more needs to arise for which the simple GH implementation of markdown/rST is inadequate. DAGs were just one example. With CockroachDB contextual help / SQL reference doc we'll also want to assemble doc pages from pieces, so as to concentrate common text across pages into a single file, and have a generator assemble them. Again markdown does not do this natively. Perhap's we'll use rST `..include` but perhaps also not (e.g. if we end up wanting to render the things separately in the CLI) in which case I suppose we'll cook a custom something.

Making new tools because we're not happy about what exists, without compromising on reaching tangible goals (in this case, making docs easy(easier) to work on and maintain), seems a generally sound attitude to me.

**Comment by petermattis** [comment]
I'm agnostic towards the chosen markup format, but feel strongly that we should have a standard. rST certainly looks more flexible than markdown given the documents produced with it so far, though a real comparison would require seeing the documents in markdown. I'm not convinced we need the additional power for RFCs and tech-notes. Now I'm going to step back and let the bike shedding continue.

**Comment by bdarnell** [comment]
I'm OK with the custom tools for the images - requiring graphviz to render them is a nuisance, but it's much more hacker-friendly than the opaque pngs we currently have in the docs/RFCS/images directory, which is the likely alternative if we take a strict stance on how images may be generated. I'd like to see us converge on a small and infrequently-changing set of tools here (and bake them into the builder image, for example), but graphviz is pretty reasonable (and we already rely on it for pprof). FWIW, sphinx has [built-in support for graphviz](http://www.sphinx-doc.org/en/stable/ext/graphviz.html) 

I'm more concerned about standardizing the workflow for the documents themselves. Do we use github rendering or check in HTML (or render HTML somewhere else)? Do we expect future editors of these docs to know and switch between multiple formats? What if the docs team ends up switching to asciidoc?

> For me the argument "well then don't use TOCs / a DAG if our tools cannot generate them" is a non-starter

I disagree that it's a non-starter. This document is indeed a bit better in some respects than it would have been if it were written in markdown. But it's also a bit more expensive because it's non-standard. Is that a net win? This is a reasonable subject for debate. 

Personally I don't think that *this* document benefits enough from rST to be a special case. If we want to standardize on rST and encourage it going forward, then so be it. But I must push back on the creation of special cases for such marginal benefit.

**Comment by couchand** [comment]
Allow me to speculate a bit: making a strict policy of only allowing GH-flavored markdown in RFCs and tech notes will lead us to think in GH-flavored markdown (c.f. [linguistic relativity](https://en.wikipedia.org/wiki/Linguistic_relativity)).  I think that's unacceptably limiting.

We shouldn't hesitate at all to think about a document build workflow.  The examples raised above show that it's possible for our tech discussion docs to be much richer than what would be allowed by GH.  If the cost is investing a little bit in tooling that's independent of GH, it's worth it, and all the better for us to be less coupled to GH.

**Comment by petermattis** [comment]
<contentious_opinion>
The two recent documents that have used rST are certainly better looking that what we can achieve easily with markdown (e.g. the TOC, graphs and sidebars), yet I question whether this is more than a surface difference. The meat of these documents is in the text. I mostly read RFCs in reviewable/github-changes anyways, so I never even see the rendered output. I don't think RFCs and tech-notes would be substantially worse if we restricted ourselves to plain text.
</contentious_opinion>

Putting the above opinion aside, I primarily want standardization. I'm fine with markdown, or rST, or plain text, or shiny-new-format. I'm not fine with using all of them at the same time.

**Comment by petermattis** [comment]
Related to my previous comment about only reading RFCs in reviewable, @knz just mentioned elsewhere:

> I understand the technical argument but I for one only read RFCs in the source form, never as HTML. I think it is reasonable when you have small lists to pre-number them.

**Comment by knz** [comment]
Hah! Good catch.
This argument btw is also working against markdown when we have slightly complex content, I am thinking in particular about *tables* -- any time one wants to make a *useful* table in markdown the markup becomes horrendously broken. not so with rST.

**Comment by knz** [comment]
Some more info to help people make their opinion:

- [rST vs markdown shootout in HTML](http://random.vodka-pomme.net/pub/markup.html).
- [same doc, rST sources](http://random.vodka-pomme.net/pub/markup.rst) - note, you couldn't make such a document in markdown, because markdown tables ... well...
- [if you want to regenerate the doc yourself, use this archive](http://random.vodka-pomme.net/pub/markup.zip).

**Comment by bdarnell** [comment]
This has basically been settled in favor of the status quo of markdown for everything.
