### ISSUE TITLE
sql: report drop and truncate in jobs table

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#19004]
Both operations can take a long long long time. For added visibility, we should include those in the jobs table.
eg: I dropped the only user table in a 1.7TB (total data used) cluster. Hours later, I can't see much change in usage (it's there, just subtle) and there's absolutely no visibility into the progress or even whether it's doing anything (other than a single goroutine on the node executing the drop).

**Comment by mberhault** [comment]
tentatively adding 1.2 milestone.

**Comment by dianasaur323** [comment]
odd... I guess I always assumed those were considered schema changes... off the top of my head, I don't know what we would take off to do this, so I think a "tentative" add sounds good. I'll follow up once I figure out what capacity looks like. Thanks for filing.

**Comment by cuongdo** [comment]
+1 on this. From a logical point of view, all SQL statements belong in either SHOW QUERIES or SHOW JOBS. Since the other schema changes show up in SHOW JOBS, that seems like a reasonable place to put DROP and TRUNCATE.

**Comment by vivekmenezes** [comment]
Seems okay. The only difference from other schema changes is that the DROP and TRUNCATE are complete as far as the user is concerned (The table is gone/or the table is empty). In other words the schema change is complete. It's just the deleted data being GC-ed in the background after the schema change and the expectation that the disk usages goes down significantly after the operation that is surprising.

**Comment by tschottdorf** [comment]
In our production testing, where clusters are bound to run out of disk space eventually, we've found that the currently functionality is insufficient. It turns out that `DROP TABLE` is essentially never fast enough to thwart impending doom, even with aggressive GC TTLs. This could be due to the actual background deletion or slowness of the GC queue in purging the deletions, but either way it's not acceptable that there is no indication of the progress even though the background task is still ongoing.

There is likely performance that we need to optimize, but knowing how far the actual deletion has processed is a baseline that doesn't seem too difficult to achieve.

See also https://github.com/cockroachdb/cockroach/issues/19329#issuecomment-339336024 where we discuss using `DROP` for that purpose.

**Comment by dianasaur323** [comment]
This begs to question why we count certain commands as schema changes while other are not. We currently define them based on whether or not the operation requires backfilling, but I've been getting feedback (and I'm personally confused) since it matches the technical implementation, not how users would expect things to be classified.

**Comment by vivekmenezes** [comment]
@dianasaur323 commands that change the schema are called schema changes. Some of these commands need to backfill data and thus take time to execute. In the case of DROP once SQL stops referencing the data SQL responds back to the user that it has completed the schema change, which it indeed has. The only problem is that users also expect the command to delete all the data associated with the table, which we do asynchronously. We do the same with TRUNCATE, where we don't delete the all the underlying data immediately, just provide the illusion via SQL that it's gone.

**Comment by dianasaur323** [comment]
@vivekmenezes On that point, the reason why I'm asking is because in the jobs table, we only show progress of schema changes that require backfilling, hence the confusion. Both the things you mentioned (DROP and TRUNCATE) have confused some users out in the field. I'm wondering if we should do something about that?

**Comment by vivekmenezes** [comment]
The reason why we did it this way is because users were complaining about DROP/TRUNCATE being too slow. The correct solution is to drop this data quickly which we can't accomplish in the near term. There is also the added concern that users need to query the old data using AS OF SYSTEM TIME which prevents us from just blowing away the ranges.

I agree we need to do something

**Comment by tschottdorf** [comment]
I think we want to rely on `AS OF SYSTEM TIME` as a recovery mechanism for fat-fingering a drop table. I don't think that's principally in the way of removing the data more quickly if desired, though (a bit of care has been taken that the quick-delete can't be fat-fingered easily).

I'd really just like to track the status of the deletion (which is a kind of backfill) in the jobs tab. I think it's OK that `DROP` returns and the job is still running. After all, the DB is gone.

**Comment by dianasaur323** [comment]
I'm tentatively marking this as 1.3 right now. I don't think we have capacity to fix this now, and I think it might make sense to wrap it into some jobs work that is going to tentatively get scheduled for 1.3...

**Comment by vivekmenezes** [comment]
This has become a much higher priority because a DROP TABLE still takes a lot of time and we want users to be able to have some visibility into the progress made in GC-ing the underlying data.

1. When the GC TTL hasn't expired for the DROP TABLE, the Job should say that the table is waiting for the GC TTL to expire before moving forward with GC-ing the data.
2. Once the TTL expires, the Jobs table can provide visibility into the progress being made by the calls to ClearRange.
3. Once ClearRange has completed, The Jobs table should reflect the progress being made to reclaim the data through RocksDB compactions.

**Comment by vivekmenezes** [comment]
@petermattis , @tschottdorf ^

**Comment by vivekmenezes** [comment]
another example where this would have been useful 

https://github.com/cockroachdb/cockroach/issues/26422
