### ISSUE TITLE
raft: NPE in TestRaftAfterRemoveRange

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1911]
Found in #1839.

https://circleci.com/gh/cockroachdb/cockroach/5336
https://circle-artifacts.com/gh/cockroachdb/cockroach/5336/artifacts/0/tmp/circle-artifacts.yDWyPPv/testrace.log

**Comment by bdarnell** [comment]
The problem is that in the `Store.processRaft` thread, while processing the `EndTransaction`, we update the range descriptor and then tell raft to apply the configuration change. The test thread calls `RemoveRange` as soon as the descriptor is updated. If this happens before the raft `ApplyConfChange`, it will cause this panic. 

We need to make `RemoveRange` atomic with respect to commands being processed in `Store.processRaft`, either by adding a mutex that is held while processing each command, or adding a new channel to the `processRaft` select loop so that the meat of `RemoveRange` can be done in that thread.

**Comment by iankronquist** [comment]
Hey, I'm interested in investigating this issue.

**Comment by tamird** [comment]
Great, go ahead!

**Comment by iankronquist** [comment]
@tamird Your IRC channel looks pretty empty. If I want to get a hold of you is there somewhere else I can ask you questions other than here?

**Comment by tamird** [comment]
Heh, I didn't even know about the IRC channel. I'm in there now.

**Comment by iankronquist** [comment]
@tamird So when I try and build a developing environment I encounter issues:
```
$ docker build -t cockroachdb/test .
Sending build context to Docker daemon 36.04 MB
Sending build context to Docker daemon 
Step 0 : FROM cockroachdb/cockroach-devbase:latest
Pulling repository cockroachdb/cockroach-devbase
Error: image cockroachdb/cockroach-devbase:latest not found
$
```
There seems to be an image called `cockroachdb/cockroach-dev`, but this seems to be different.

**Comment by tamird** [comment]
Another one of these in TestRangeGCQueueDropReplica

https://circleci.com/gh/cockroachdb/cockroach/6249
https://circle-artifacts.com/gh/cockroachdb/cockroach/6249/artifacts/0/tmp/circle-artifacts.IUfuplx/test.log
