### ISSUE TITLE
storage: Load-based splitting

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19154]
Split ranges that have a lot of load on them in situations where we think that splitting them would improve cluster performance. This is particularly impactful on new clusters during the data loading phase.

A number of ideas for this have been discussed previously, most notably in and on https://github.com/cockroachdb/cockroach/pull/16296. A particularly interesting suggestion would be to make tables split much more aggressively when they're new up until there are at least as many ranges for the table as there are nodes in the cluster.

If we do want to split on load itself, [recent experience](https://github.com/cockroachdb/cockroach/issues/18657) has suggested that [dropped raft requests](https://github.com/cockroachdb/cockroach/blob/a7ba751dd9aa453785aacf7b93bfe62d094ca5e3/pkg/storage/store.go#L2927) would be a very good metric for write-heavy workloads, since we start dropping raft requests for a range when that range isn't processing them quickly enough.

Tentatively assigning to @nvanbenschoten and milestone 1.3 based on the roadmap, but this may be a nice performance win in the shorter term.

**Comment by petermattis** [comment]
I'm 👍  on doing this sooner. Telling users to split their table manually or wait a significant time for the table to split automatically is unsatisfactory. 

One drawback to using dropped raft requests as the signal is that we won't split based on read load. Perhaps that isn't problematic because we can perform reads concurrently on a range, while writes are serialized by the Raft log. Another drawback is that the dropped raft request signal might disappear if we change how we buffer requests. 

We should probably be tentative in how we performing load-based splitting given that we don't perform range merging yet. Can we get ourselves into a situation where a table has lots of small ranges? For example, consider a table being used as a log. The last range in the table would be continually split due to load creating tons of small ranges.

**Comment by bdarnell** [comment]
I'd rather have range merging in place before we introduce load-based splitting. Making irreversible decisions based on heuristics seems like a bad idea, given what we've seen about the cost of a new range.

Another wrinkle here is that splitting a heavily-loaded range could push some single-range 1PC transactions into multi-range ones, making them much more expensive. I'm not sure how often that would be an issue or if it's worth doing anything about.

**Comment by a-robinson** [comment]
I take back the idea of using dropped raft messages as a signal. They're mostly gone as of https://github.com/cockroachdb/cockroach/pull/19540.

**Comment by bdarnell** [comment]
Anything left to here or can we just close this?

**Comment by nvanbenschoten** [comment]
We can close this. Load-based splitting is on by default in 19.1 and hasn't caused any issues in the last few months.
