### ISSUE TITLE
Checking index validity using distSQL

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#19221]
There are two questions being asked here.
1) What is the best way to do index checks?
2) Is there a way that can do index checks which can share work for schema change index backfilling?

Problem 1 already has a solution at the bottom (kudos to @richardwu for the
help). I'd like to also discuss if the first idea (or others) is feasible which will help with problem 2.

Consider the following situation. You have a table `t1`,
```
CREATE TABLE t1 (
   pkey int primary key,
   id int,
   name string,
   INDEX id_idx (id ASC),
   INDEX name_idx (id ASC)
)
```

And you want to check the indexes `id_idx` and `name_idx`.

# Idea 1: Building custom processors

![img_20171011_174310](https://user-images.githubusercontent.com/1161183/31511915-3d09b7bc-af57-11e7-93c6-a479de9917ae.jpg)

The situation in the picture (partially) describes the idea of the
physical plan to do this.
1) A `TABLE READER` for each node reads off the data required for
   constructing the index(es). This includes: the index values; extra
   values or stored values.
2) An `AGGREGATOR` for each index, where the input stream are only the
   columns reqired to construct the index. It uses a pass-through router
   to the next processor and it will also need to send the results
   through a sorter.
   
   Represented in the picture is a monolithic aggregator. An
   optimization is if there is a group key where index contents are
   routed to the processor that contains those KV pairs.
3) A processor that we call "Index Check Processor" that is similar to a
   `JOIN READER` in that will do sequentual lookups for the index KV pairs
   on-disk. It will output something signifying any errors found --
   essentially any mis-matches in all the data from the input stream and
   the lookups.

   Alternatively, this could be a `MERGE JOINER` where the second input
   stream is a `TABLE READER`. The joiner can then pass the values
   through an evalutor that filters contents to mimic a `FULL OUTER
   JOIN`.

The first 2 steps help with problem 2, schema change index backfilling,
as read all of the table data at a specific timestamp and construct the
index for a specific timestamp. To my understanding, the current problem
is that we scan through the table data in batches and so we cannot write
the entire index at a specific timestamp.

# Idea 2: Using just a SQL logical plan

Ignoring problem 2, after discussing with @richardwu offline we have
concluded that checking can achieved by a logical plan similar
```sql
SELECT p.pkey, p.id, s.pkey, s.id
FROM t1@primary as p
  FULL OUTER JOIN
    (SELECT * FROM t1@id_idx ORDER BY pkey) as s
  ON p.id = s.id AND p.pkey = s.pkey
WHERE p.pkey == NULL OR s.pkey == NULL
```
which produces [the following distSQL plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJyskjFr-zAQxff_pxC3ZPjfENuZBAVNbVOCU5x0Kqao1pEKHMlIMqSEfPdiaUhjkrSBjne633t3D-3BWEWl3JIH_goZ1Aidsw15b93QSgNztQM-RdCm68PQrhEa6wj4HoIOLQGHtXxvqSKpyAGCoiB1G0U7p7fSfYqQAcKyD5yJDEUO9QHB9uGo6IPcEPDsgH_gqtWbVrtfm-a3mK6sC2M_kf2_KF5cFD9q9sY6RY7UiWw9kD-NnNnwUfqPJ6vNeMtlyUTG7pgoAOFet4EcZ-XLYgEIFRk1lJMU3YRzvlpX8_IBh-yYyDFOIhMFMjFL1cWbZ7cEWpHvrPE0vv2s8nQ4mNSGUoDe9q6hZ2ebaJPKZeRiQ5EP6bVIxdzEp_jNvsPZVTg_gadjOL_BOR_DxVV4NnKuD_--AgAA___vMDTp):
1) We read the primary KV pairs and the secondary index KV pairs.

   If checking multiple indexes we will have a `MIRROR` router to send
   this to the multiple `JOINER`s
2) They are fed into a `JOINER`. We need to sort each secondary index stream if we'd like to use a `MERGE JOINER`, which may be more performant.
3) The output of each `JOINER` is sent through an `EVALUATOR` that
    returns rows where the contents are not completely equal. i.e. `FULL
    OUTER JOIN`. This is not correctly reflected in the example distSQL plan.

- Can this proposed plan be constructed only with a SQL logical plan?
- Is there anything in this proposed plan that seems incorrect?

**Comment by lego** [comment]
cc: @arjunravinarayan @andreimatei

**Comment by richardwu** [comment]
RE: Idea 2, I think what you want to do is join just on the `pkey`, but `JOIN` between the `@primary` and `@id_idx, @name_idx` indexes.

For example, given your `TABLE t1`, you might have some like
```
SELECT prim.pkey, prim.id, sec.pkey, sec.id 
FROM
  t1@primary AS prim 
  FULL OUTER JOIN 
    t1@id_idx AS sec
  ON prim.pkey = sec.pkey)
WHERE prim.pkey = NULL or sec.pkey = NULL
```
which produces [the following DistSQL plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJyskUFrwzAMhe_7FUFnHepkJ8PAp7GOkoyynUYYXiw6Q2oH2YGOkv8-4hy6hHZbYUdL-t7Tk4_gvKFS7ymAfAUBNULHvqEQPI-laWBtDiBXCNZ1fRzLNULjmUAeIdrYEkh41u8tbUkbYkAwFLVtk2jHdq_5U0UBCFUfZaYEqhzqAcH38aQYot4RSDHgP7ha82bN4c-m-UXTk1fvPBtiMjOneiR_Gzmz-YMOH4_euuXiVZkpkd1lqgCEe9tGYpmVL5vNLAiqAtXtxTjFNTfcUui8C7SMdVZ5NWYhs6PpNsH33NAT-ybZTM8qcalgKMSpm0-PtUut9MnfYXEFnC_h_Ee4mMGroR5uvgIAAP__yDn4EQ==).

Notice how it uses just a hash joiner instead of the more ideal merge joiner. You'll have to sort the by the `pkey` on `t1@id_idx`
```
SELECT prim.pkey, prim.id, sec.pkey, sec.id 
FROM
  t1@primary AS prim 
  FULL OUTER JOIN 
    (SELECT * FROM t1@id_idx ORDER BY pkey) AS sec
  ON prim.pkey = sec.pkey)
WHERE prim.pkey = NULL or sec.pkey = NULL
```
@RaduBerinde mentions that merge joiner doesn't support `FULL OUTER JOIN`s yet (it still needs to be implemented! *wink wink nudge nudge*). For example sakes, I'll use a regular `JOIN` to generate [the DistSQL plan for what it would look like (ignore the `NULL` filter being pushed down since it doesn't know it's a `FULL JOIN`](https://cockroachdb.github.io/distsqlplan/decode.html?eJyskkFLw0AQhe_-ijInpXvoJj0tCHsSKrWVqicJErNjXEizYXYCldL_Ltk91C5tteAtOzPfe2-GbKF1BhflGj2oV5BQCOjIVei9o6EUB2ZmA2oiwLZdz0O5EFA5QlBbYMsNgoLn8r3BFZYGCQQY5NI2QbQjuy7pS7MEAXe2YSQ1WrzM5yBg2bMaaSl0BsVOgOt5b-C5rBGU3Il_CGHNmzWbmOEPptklpk-OOPXTcnxSPD8pvtfsW0cGCc2BbDGQv40cSfiAVOO9s20as8EPvtZyfHNLtv6MnwcXEjoXenpylekld1qh71zrMV3pqPJk2ANNjfEu3vVU4SO5KtjE5zJwoWDQc-zm8TFrQyv8PT9heRbODuBJCmcXOGcpnJ-Fp4lzsbv6DgAA__9gyS7x).

**Comment by lego** [comment]
Thanks, I accidentally omitted the index selection and sorts from our chat :).

**Comment by lego** [comment]
If we have multiple indexes we will need some way to combine the results. Without `UNION` support, I think this can be achieved if all the results are aggregated to the gateway node. Is this possible? This sounds like we need to start modifying the physical plan to achieve this.

Other minor details is the need to identify which index is associated with the error and filling any columns not in the steam (i.e. not contained in the index) with `NULL`.

The psuedo-SQL query I'm imaging for this would be the following, where `UNION` is in place of "aggregate into gateway". The distSQL plan is the same as the one mentioned by @richardwu, with the literals rendered in the join processors.
```sql
(SELECT 'id_idx', prim.pkey, prim.id, NULL, sec.pkey, sec.id, NULL
FROM
  t1@primary AS prim 
  FULL OUTER JOIN 
    t1@id_idx AS sec
  ON prim.pkey = sec.pkey
WHERE prim.pkey = NULL or sec.pkey = NULL)
UNION
(SELECT 'name_idx', prim.pkey, NULL, prim.name, sec.pkey, NULL, sec.name 
FROM
  t1@primary AS prim 
  FULL OUTER JOIN 
    t1@name_idx AS sec
  ON prim.pkey = sec.pkey
WHERE prim.pkey = NULL or sec.pkey = NULL)
```

**Comment by lego** [comment]
Closing as the results were brought into https://github.com/cockroachdb/cockroach/pull/19327.
