### ISSUE TITLE
cli: check the server version

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19245]
The CLI for v1.1 does not work against v1.0—it uses all sorts of v1.1-only features. It should print a warning, and maybe error completely, if the server it connects to has a different version.

This has confused our users on more than one occasion; see, for example: https://forum.cockroachlabs.com/t/cannot-dump-upgraded-database/1003

**Comment by benesch** [comment]
@knz assigning you in case you have or know someone who has some spare cycles. Quite a few folks are getting tripped up by this on Gitter/the forum.

**Comment by knz** [comment]
This error is a 1.0 client binary against a 1.1 server. We can't teach 1.0 to do version checks any more... Unless you suggest we publish a new 1.0 release just for this purpose?

**Comment by knz** [comment]
cc @bdarnell for opinion

**Comment by knz** [comment]
NB: when 1.2 is out, this should be less of a problem. The CLI now already prints out the server and client versions if they differ, as a reminder to the user.

**Comment by benesch** [comment]
Ah, I'm not suggesting that we change 1.0 behavior, but that we make it impossible to use a 1.2+ client against incompatible servers. We had a user on Gitter report

```
does anyone got this error 'Error: pq: unknown variable: "sql_safe_updates"'?
```

which happens when you use a 1.1 client against a 1.0 server. This occurs before the versions are printed, so it's not clear what's gone wrong. (A fix for that might be cherry-pickable to the 1.1 client, too.)

**Comment by knz** [comment]
Ok we can fix the 1.1 client so that it works with 1.0 servers, and is more explicit about problems when connecting to a higher version too.

**Comment by bdarnell** [comment]
We should add a version check to 1.1.2. I wouldn't do a 1.0.7 just for this, but it would be nice to backport that change to release-1.0 when/if we do.

More importantly, we should be better about version compatibility in the CLI. Users shouldn't have to install multiple versions of the client binary (or coordinate their upgrade between servers and clients) just because they need to talk to servers of different versions. The server should continue to support features that old clients rely on, and the client should fall back gracefully when it's talking to an older server.

**Comment by benesch** [comment]
We currently do some cross-version acceptance testing (see reference_test.go) by baking in old binaries to the postgres-test Docker image.
