### ISSUE TITLE
Emit correct error to load generator when node dies

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19262]
From user: I shut down node 3 via "cockroach quit" which made the load generator get stuck. No errors. After restarting the load generator, it quickly becomes stuck again. Once I brought node 3 back up, queries continued. That's a real problem for a production setup. Note that the load generator only connects to node 1. The admin UI correctly identified node 3 as dead.

**Comment by a-robinson** [comment]
Yeah, that's really bad if it isn't just a load generator issue. The title of this issue doesn't make much sense to me, though.

**Comment by arctica** [comment]
Note that I filed #19236 which is the same failure scenario as I initially described in #18657 but was done with v1.1 and I saw a severe performance degradation but not a complete halt. I am not sure if I in my original ticket had mistaken the degradation for a halt. I would need to re-test with v1.0. And either way it could also be bad luck in terms of which nodes have what leases or other factors that turn a crawling speed into complete halt.

In essence, I think it's all the same root cause and this ticket can be closed in favor of #19236 which has a bit more detail

**Comment by dianasaur323** [comment]
hmm.. ok - let's defer to issue #19236 then. Thanks, @arctica.

**Comment by a-robinson** [comment]
The load generator doesn't handle errors well - in my first attempt to reproduce this/#19236, the QPS dropped to 0 because the load generator received an ambiguous error and `log.Fatal`ed. Have you ever produced a result like this with the `log.Fatal(err)` line in your code replaced by `log.Print(err)`?

**Comment by arctica** [comment]
@a-robinson Yes the load generator quits upon any error from the DB. In my testing, I made sure the load generator was still running when the qps dropped. But as mentioned, maybe I had mistaken a crawling speed for a complete halt. I would have to test the old version again. v1.1 just gets really really slow but not totally stuck.
