### ISSUE TITLE
ui: "Other" graph in raft debug page hard to read in a screenshot

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19271]
![image](https://user-images.githubusercontent.com/160562/31617615-a50350f4-b25d-11e7-9387-775f3ca9b364.png)

Without taking care to include a legend in the screenshot, it's difficult to tell which message types we're seeing in this graph (fortunately the color assignments are stable so we can get the legend from another cockroach node running the same version). This graph should have an always-visible legend like most of the other graphs on this page do.

Even with the legend, the colors here can also be difficult to distinguish sometimes. I'm not sure if there's a better palette we could be using or if we should just split it up into two separate graphs. The most natural split point is probably to make one graph for Raft Votes (for Vote, VoteResp, PreVote, PreVoteResp) and one for the rest.

**Comment by dianasaur323** [comment]
it looks like we have a legend consistency problem.. The below graph also doesn't have a legend.
![image](https://user-images.githubusercontent.com/5768024/31618195-4701f44a-b25f-11e7-8b66-5c8fc272e32d.png)
Bucketing into 1.2 for fixing.

**Comment by couchand** [comment]
I'd suggest that trying to investigate these things from a static screenshot isn't the way to go, and we should focus on #16584 rather than working too hard trying to make this fly.

However, this does highlight a more general issue: trying to put too many series on a single chart, which hurts understanding while browsing live, not just looking at a screenshot.  To that end, I think we should establish a maximum number of series that we're happy supporting and, as suggested above, split those with more into multiple charts.

Regarding the legend showing/not showing: the current behavior is to only show the legend when the number of series on a chart is in the interval (1, 4] (see [here](https://github.com/cockroachdb/cockroach/blob/f5ce1cea4202d1bffacecb91cb8e91f455829fad/pkg/ui/src/views/cluster/util/graphs.ts#L458)).  I believe this is because the legend grows kind of crazy big if there are more listed (particularly on the charts that break a metric out by node), but this just highlights the general usability problem with many-series charts.

Regarding the color scheme: I'm a bit unclear on the rationale for the current selection.  In ec0d535c it replaced the previous `d3.scale.category10()` (that commit also upped the legend limit from 3 to 4).  It seems to be somewhat loosely based on that scale from D3, but the exact color values are different, and there are some strange collisions as a result (which I think is what your comment was referring to @bdarnell).  The D3 scale is itself based on ColorBrewer's Paired set.

I'd recommend that, rather than rolling our own color scheme, we pick one of the [stock D3 ones](https://github.com/d3/d3-scale-chromatic), since they are based on [ColorBrewer](http://colorbrewer2.org/) and thus have the weight of research behind them.  Ideally we pick a scale that is colorblind-friendly, though as far as I can tell there's only three schemes with 3 options and one scheme with 4 options that are definitively safe.  We can get up to 8 options if we're willing to accept "possibly not colorblind friendly".

As a point of interest, here is the screenshot above with simulated deuteranopia: 
<img width="1122" alt="screen shot 2017-10-16 at 1 41 51 pm" src="https://user-images.githubusercontent.com/793969/31626477-d3de8d84-b277-11e7-8828-a7c0d0ee4a9b.png">

**Comment by dianasaur323** [comment]
@couchand ok, i'm fine with all of your approaches. That being said, it appears that this might require a bit more thinking vs just a simple bug fix. It's prioritized in 1.2, although in the medium bucket, which is basically the bucket of things that we might not be able to get to. Okay with the high potential that this might not make it into 1.2?
