### ISSUE TITLE
How to change the lease expire duration?

### ISSUE THREAD

**Issue by phifty** [cockroachdb/cockroach#19318]
In [this](https://www.cockroachlabs.com/blog/limits-of-the-cap-theorem) blog post, it's mentioned that after a network failure, a node can serve read operations until it's lease expires (default is set to 9 seconds). Because of the *default* value, I assume that this can be configured. How can I do that?

Thanks in advance

**Comment by dianasaur323** [comment]
hi @phifty, thanks for the question! Unfortunately, it is not currently configurable, apologies if the blog post made that unclear. We are working on making that lease expiration duration shorter, but for now, you'll have to use the default. You can check out the cluster settings we have (listed in a comment here) https://github.com/cockroachdb/cockroach/issues/17536 and the configs we have here https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cliflags/flags.go. For user-facing flags though, I would stick with the docs, since those are the ones we recommend to users. https://www.cockroachlabs.com/docs/stable/cluster-settings.html

**Comment by phifty** [comment]
Hi! Thanks for the quick and helpful reply.

My intention was to extend the expiration duration to something around 24h! The background is that I would like to read the data, even if the majority of replicas are not available and just deny writes (that would violate the consistency constrain).

**Comment by dianasaur323** [comment]
ahhhhh you want to be able to do inconsistent reads on non-voting replicas. You won't be able to get that, since you have to go through the lease holder in order to do either a read or a write. We are considering allowing something like that eventually, and the first step towards that is discussed here https://github.com/cockroachdb/cockroach/pull/19222. Essentially, we track the safest timestamp in which you can make a safe read to a follower, although this would be a consistent read. We might eventually extend things to inconsistent reads, but not yet. 

If what you are looking for is fast reads across a highly distributed database, you might want to consider using zone configs to improve performance. We do load-based lease rebalancing, so you can actually have reads serviced closer to where they will be accessed. For example, if you have a table that is mainly accessed from the West Coast, you can set that table with a zone config to live in the West Coast, and then the lease will move over to the West Coast based on traffic. Eventually, we will be able to do this at a row-level (coming up in 1.2). I know this isn't exactly what you are looking for, but hopefully it does improve latency a bit.

**Comment by phifty** [comment]
Ok, I'll follow up the other discussion too.

But performance is not the issue here. We have currently two data-centers where we can set up any number of nodes. But if one data-center fails, half of the nodes will be gone and the other data-center might loose the quorum. In our tests, cockroach stops any work in this case (even the web ui shuts down?!?). I understand, that this a fundamental property of any CP-store, but we wonder if we could "at least" read the data from the remaining replicas. Like in your blog post, we consider it very unlikely that the communication between the two data-centers fails while the clients communication with both.
Or is there any other way - besides adding a new data-center? :-)

Well, we're still investigating. We would really like to use cockroach since it's has really nice design-approaches and is easy to handle, but maybe a AP-store is a better fit for us and we handle consistency on the application level.

**Comment by dianasaur323** [comment]
@phifty Ahh, I see! that's a problem that we've heard from other users as well. I mean, the best case scenario is to have three data centers, but in the case of you having two data centers, at least you'll be able to survive node failures (if not a full data center failure). --> not what you want, I know! You could potentially add a third data center in the cloud?

That being said, the best option for you at this point would actually be to rely on backup / restore. Basically backup a CockroachDB database and restore it into another stand-by database. You might not get an immediate recovery point, since your backup will be behind depending on how often you take it. 

I wish I had a better answer for you at this point, since I'm sure you know, an AP-store comes with a bunch of other baggage as well. In case you're interested, we are working on change data capture (although this won't be released in our next release) to support real-time streaming of changes, and this might be able to get you to where you need to be. Not sure what your timeline for this project is though.

**Comment by phifty** [comment]
The cloud is not an option here. So it would mean a physical data-center :-)

I could not follow you on the last part. I understand what "real-time streaming of changes" is, but how can it be used to solve this issue? Do you mean, we could use it to have a always-up-to-date backup?

**Comment by phifty** [comment]
I think our main problem is, that cockroach shuts down completely in case the majority of replicas are lost. I understand that SQL queries are blocked in order to keep consistency. But why does anything shuts down? It's definitely a showstopper for us.

It would be really helpful to be able to **manually** decommission dead nodes to get back in a working state again. Is this a bug? A design decision? Or am I missing something?

Thanks for the detailed answers anyway.

**Comment by dianasaur323** [comment]
@phifty No worries, it's helpful to discuss this since I get to bounce ideas off with you! 

On the last part (which isn't available yet), you would be able to have more like and active-active replication between clusters, so you could theoretically store all three replicas in a single datacenter, and then have a separate CockroachDB cluster that is a couple seconds behind that gets all the changes from your first datacenter. If your first datacenter went down, you would be able to send traffic over to the other datacenter, and if you kept things at reads, you would only potentially lose the writes to the first datacenter that haven't made it over to the other datacenter yet. However, this is just me brainstorming, and it isn't something you can do yet.

The problem with running CockroachDB across two datacenters is that it is probably better if you run CockroachDB in just a single datacenter, and have a standby backup in a second datacenter. That way if you do have a datacenter failure, you'll at least be able to serve "something" with your second datacenter. 

Regarding manually decommissioning nodes, yes! You can do that. We just released it in 1.1. Does this do what you want it to? https://www.cockroachlabs.com/docs/v1.1/remove-nodes.html

**Comment by bdarnell** [comment]
> But why does anything shuts down? It's definitely a showstopper for us.

Everything shuts down when you lose a majority of the nodes because it's impossible to tell whether those nodes are down or whether they're still running on the other side of a network partition. Any reads served by a minority of nodes could be stale and lead to inconsistent results, so we shut everything down until the other nodes are recovered. 

Note that massively increasing the lease timeout to 24h would be a bad idea - it would let you continue to serve reads while riding out (some) network errors, but if a machine crashed, it would be 24h before any other node could pick up that range. 

In the future, we may allow the application to opt in to (potentially) stale reads, and allow those reads to proceed from a replica that has lost contact with the leader. The first phase of work to enable this is described in #19222. 

Decommissioning won't help here - it's not a way to recover from under-quorum situations, it's just for instructing the system that a dead node won't be coming back, or to prepare the system for a live node to go away.

**Comment by phifty** [comment]
Ok, I guess I was not clearly enough about what I mean with "complete shutdown". I'm aware of the network-split/stale reads/consistency problem. I know that after a network-split, no data can be guaranteed to be consistent. Our problem is more, that in case the majority is lost, the remaining nodes stop responding to anything. There is no web UI, no metrics, no command-line commands and no manual decommissioning. *That* is the showstopper for us.

In our current test-scenario we run 6 nodes with `num_replicas: 3` and cockroach version 1.1.0. The first three with `--locality=datacenter=dc-1` and the last three with `--locality=datacenter=dc-2`. When I kill the last three, the cluster stops working as expected. But the remaining nodes don't respond to any status request/command at all.
Ideally, I would like to solve this situation by **manually decommission** the three dead nodes, so that all three replicas exist on the first three working nodes. I understand, that this can't be an automatic process, but I think it could be a manual one. When the three failed nodes get back online, they would need to be recommissioned, which would invalidate their outdated data-set. The data would be consistent all the time.

Does this make sense?

**Comment by bdarnell** [comment]
Yes, it's a reasonable request, although we're using the word "decommission" differently. Our decommission feature is a safe and lossless way to permanently remove a node from a cluster. You're using it to describe what I would call a "lossy repair", where you're trying to salvage something from a cluster that has lost data. The trouble with offering something like this is that even if your application may be able to handle a certain level of inconsistency, CockroachDB internally relies on strong transactional consistency for things like managing range splits and keeping indexes in sync with their tables. We can't offer a lossy option that would violate any of these internal guarantees.  This is why you must use backup/restore to recover from a catastrophically damaged cluster instead of bringing it back from its under-replicated state.

**Comment by phifty** [comment]
Thanks for the insight. We'll definitely keep watching the development of cockroach. But for now, we'll pick an AP-store. I'll close the issue. Best regards
