### ISSUE TITLE
backup: consider default behavior for revision history option

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19341]
`WITH revision_history` stores all MVCC revisions rather than just the latest, allowing a `RESTORE... AS OF SYSTEM TIME` query to restore to an arbitrary time in the backup rather than to just the time at which the backup was taken.

Currently the default is the initial implementation, of just storing the latest version, and the user must opt-in to storing all revisions. This means that, by default, backups are smaller but only support restores to discrete backups, not to arbitrary times in-between them. Switching the default would make backups bigger, but add flexibility.

Obviously a user can pick, but for those that don't, we have to choose a default.

**Comment by dt** [comment]
Prior discussion in https://github.com/cockroachdb/cockroach/pull/18547

**Comment by dianasaur323** [comment]
Ok, so I finally got the chance to think about this. My biggest concern with offering ``` WITH revision_history ``` as the default is that there will definitely be a point where having the revision history makes the backup significantly larger than one would expect. This means that a backup of a small-ish table with lots of MVCC history could take longer than one would expect, and the storage of the backup would be bigger than one would expect. We already get questions like, "how do I know how much storage to provision for a backup?" And this might make it worse. 

That being said, I do get the story around basically offering users the safest option available by making revision history the default. I also think that in most cases, it would be better for users to just backup the full MVCC history and be done with it. However, this seems to overly enforce safety at the cost of an unexpected user experience (where users typically expect just a snapshot of data). For certain customers who **need** the full MVCC history though, would it make sense to offer them a cluster setting where they could toggle the default?

cc @spencerkimball since he had thoughts here

**Comment by dt** [comment]
I'm -1 on a cluster setting changing the behavior -- as much as possible, I'd rather the same query do the same thing, without having to know what the settings are to reason about it.

**Comment by dianasaur323** [comment]
Ah, that's a good point. In that case, I'm still in the camp of making just snapshot the default.

**Comment by dt** [comment]
@dianasaur323 says we'll stick with the current behavior for now.
