### ISSUE TITLE
Table dropped only partially

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#19371]
Running v1.2-alpha.20170901-801-g5282759 on a 3 node cluster. I ran the load test from #19236 and issued a `DROP TABLE test.bench;` while the load generator was still running. This seemed to hang or take a long time so I cancelled this statement via ctrl-c in the cli. Then I stopped the load generator. I saw the table disappeared and I could create a new table.

The admin UI though indicates that the data of the old table is still there. Disk storage is still being used, the Replicas graph still shows 150k replicas and the Replication page shows 150k ranges while the new table has only a few dozen.

<img width="1166" alt="screen shot 2017-10-19 at 17 29 21" src="https://user-images.githubusercontent.com/870630/31779368-478e4efe-b4f3-11e7-84b9-d799bedcf04b.png">
<img width="1254" alt="screen shot 2017-10-19 at 17 29 54" src="https://user-images.githubusercontent.com/870630/31779369-47d10a96-b4f3-11e7-8e79-040a4f823055.png">

**Comment by arctica** [comment]
Thinking about it, might this have to do with the time travel support in CockroachDB? Does it keep the data around for 24h and if so, is it possible to get the table back?

**Comment by a-robinson** [comment]
> Thinking about it, might this have to do with the time travel support in CockroachDB? Does it keep the data around for 24h and if so, is it possible to get the table back?

Yes, that's why the storage usage hasn't dropped. Although even after the 25 hour TTL, it could still take a little longer to truly get cleared off the disk due to how deletions in RocksDB (our underlying embedded KV store) work. https://github.com/cockroachdb/cockroach/issues/19329 was recently filed to allow for speeding this up when necessary.

**Comment by a-robinson** [comment]
> the Replicas graph still shows 150k replicas and the Replication page shows 150k ranges while the new table has only a few dozen.

This part won't change, though. The data in the ranges will get GC'ed, and the ranges will "quiesce", but they'll still exist. We don't yet support merging small/empty ranges back together, and deleting them entirely would leave holes in the KV keyspace. Having them around shouldn't cost much, since they won't ever have anything to do and thus shouldn't take up memory or much processing power within your nodes, but they'll still be there in the graphs.

**Comment by a-robinson** [comment]
I'm going to close this as being covered by #19329 and https://github.com/cockroachdb/docs/issues/2077, but reopen if there's anything you think isn't covered elsewhere!
