### ISSUE TITLE
Feature request: make CockroachDB survive datacentre reboots

### ISSUE THREAD

**Issue by jeremyvisser** [cockroachdb/cockroach#19427]
Currently, when you stop all CockroachDB nodes in a cluster, it is totally impossible to recover that cluster. This is because when starting a node, it attempts to find other nodes it has previously talked to. However, when it finds none, it simply hangs forever and never starts up, leading to a Catch-22 situation with all nodes deadlocked.

This is a total blocker for anything but the most basic of use cases, meaning something like a datacentre power outage requires reinitialising the cluster and restoring data from backup.

Please consider implementing a feature such that CockroachDB nodes can start up in a state where they are able to respond to requests from other nodes before they have found their own first node in order to bootstrap a quorum state.

Also please consider documenting this, as this situation is not documented anywhere and is suspiciously absent from any troubleshooting guides.

**Comment by tschottdorf** [comment]
Thanks for filing this! It's correct that reasoning about cluster connectivity isn't as straightforward as we'd like to have it yet. We're discussing this over at https://github.com/cockroachdb/cockroach/issues/18027 and https://github.com/cockroachdb/cockroach/issues/18056.

Note though that for static deployments of smaller clusters specifying all join flags should work. In dynamically provisioned environments, there's usually a load balancer that can be pointed to that should also work (there are some remaining issues, but they are rare to hit in practice).

If you have a minute, could you briefly describe your deployment (cluster size, how nodes are provisioned, join flags for each node)?

**Comment by a-robinson** [comment]
> Currently, when you stop all CockroachDB nodes in a cluster, it is totally impossible to recover that cluster. This is because when starting a node, it attempts to find other nodes it has previously talked to. However, when it finds none, it simply hangs forever and never starts up, leading to a Catch-22 situation with all nodes deadlocked.

That isn't true in most configurations. As @tschottdorf mentioned, there are situations where IP addresses / hostnames changing between restarts can cause problems if you don't change the join flags correspondingly, but it shouldn't affect standard situations like stopping and restarting all nodes/processes.

More info on your configuration that's having this problem would be helpful.

**Comment by bdarnell** [comment]
This sounds like it might be the `--background` confusion - a node started with `--background` stays in the foreground until it has established contact with the cluster, so for a cold restart you need to start everything at once instead of one node at a time. Depending on how you're managing your deployment, some tools have difficulty with this pattern. For multi-node clusters, you may want to use shell backgrounding (add `&` at the end of the command) instead of `--background`.

**Comment by jeremyvisser** [comment]
Thanks for pointing me towards #18027 and #18056. Those definitely reflect the theme of problems I've been having.

Regarding my deployment, I was mainly testing on my local workstation (although I got the same effect running each node on separate nodes on Google Compute Engine).

When node size was 1, I could stop/start no problems, and it would come right up and start serving.

However, when node size was >= 3, I could reproduce the problem simply by doing this:

1)  Start all nodes

    ```
    # First node without --join
    $ cockroach start --insecure --host ::1 \
        --port 9000 --http-port 8000 \
        --store /tmp/roach.1 &

    # Subsequent nodes with --join
    $ for i in {1..9} ; do
        cockroach start --insecure --host ::1 \
          --port $((9000 + $i)) --http-port $((8000 + $i)) \
          --store /tmp/roach.$i \
          --join localhost:9001 &
      done
    ```

2)  Verify ranges have been balanced appropriately across cluster so we're in a known good state

3)  Stop all nodes, simulating a datacentre power outage:

    ```
    $ killall cockroach
    ```

    (In my testing, it doesn't make any difference whether SIGTERM or SIGKILL is used.)

4)  Start all nodes (not passing `--join` flag because all nodes are remembered which can be verified by seeing connection attempts in logs):

    ```
    $ for i in {0..9} ; do
        cockroach start --insecure --host ::1 \
          --port $((9000 + $i)) --http-port $((8000 + $i)) \
          --store /tmp/roach.$i &
      done
    ```

5)  Observe that all nodes are deadlocked. Browsing to the HTTP port shows "404 page not found" errors. Looking at log files shows repeated attempts to contact each other but they never succeed. The cluster is now hosed.

**Comment by tschottdorf** [comment]
Thanks for reporting back. What you're doing is interesting because it looks like it *should* work (even though I wouldn't recommend intentionally omitting join flags). We'll look into this.

**Comment by tschottdorf** [comment]
There's definitely a bug in your snippet, though. In the very first invocation (node 1), you use the data directory `roach.1`, but it should be `roach.0`. As a result, when you restart the first node, it bootstraps a new cluster that then the other nodes may try to join. I'm going to try to reproduce your issue, but with that problem fixed.

**Comment by tschottdorf** [comment]
Seems to work here. I ran [this code](https://gist.github.com/tschottdorf/3f87829d1995e6c858cf9d1e1caba1b9)

**Comment by jeremyvisser** [comment]
Okay interesting. Using your script and running this very clinically the issue doesn't occur and the cluster starts itself up with no problems.

This is embarrassing, but attempting to reproduce this once more, even copying verbatim from my prior bash history, I can no longer reproduce this.

Clearly I'm missing something, but it's probably a variable I've failed to eliminate on my end.

My original premise, that a node does not listen for other nodes until it has found a neighbour, appears to be incorrect, as I can clearly observe nodes doing this now, while I swear that I wasn't seeing that before.

It's possible I'll be able to reproduce this again in which case I will try to identify the missing variable, but until then this issue deserves to be closed as invalid. Apologies for not being careful enough.

**Comment by tschottdorf** [comment]
Let's keep this open @jeremyvisser -- I *think* there's actually a case where this would hang, which is [described here](https://github.com/cockroachdb/cockroach/issues/18027#issuecomment-326117722).

I'll update the script to "force" that badness a little more aggressively.

**Comment by tschottdorf** [comment]
[Here's a script that reproduces a failure similar to the one I believe you experienced](https://gist.github.com/tschottdorf/d786298c88a0ecaac9d98784398f7394).

It configures node0 to hold no data (i.e. it gets rid of its data as fast as it can once the cluster is up). Then, after having killed all nodes, it restarts the cluster in a way that leaves node0 on the same port, but moves all others to yet unseen ports.

The effect is that it exposes the following:

- node0 out of its own volition can't reach any other peer, since the persisted addresses are all wrong
- node0 does not have a replica of the first range (so it doesn't automatically consider itself connected)
- nodes 1+ can still talk to node0, and try to do that
- but node0 won't even allow incoming gossip until it itself has completed bootstrap

so nothing ever happens. This is the scenario outlined in https://github.com/cockroachdb/cockroach/issues/18027#issuecomment-326117722.

Now you didn't change the ports, but the way gossip address persistence works is that it's absolutely an *additional* crutch and nothing to be relied upon (which is why I've made the case that we should [remove it](https://github.com/cockroachdb/cockroach/issues/18056)). Depending on how you stopped the cluster, the first node may have wiped the addresses, in particular if you killed the first node last. That is because we have code that prunes the persisted addresses to contain only those actually "seen" in the gossip network (to remove since removed nodes). Shutting down the rest of the cluster first makes them look "dead" enough so that their persisted addresses are potentially wiped from the first node, so that when it restarts, it doesn't have anyone to talk to, similar to my my example above.

Note that one problem we're definitely going to address is that a node which hasn't connected to Gossip doesn't accept incoming gossip connections. This asymmetry is unintentional and silly. Once addressed, the "deadlock" would be rarer, but it could still occur on a smaller scale: Now other nodes *can* talk to the first node and could in principle unblock it, but nodes don't try to connect to *all* other nodes (we want the gossip graph to be sparse) and so there's a good chance the first node could just sit there without ever receiving an incoming connection (this happens regularly in tests).
