### ISSUE TITLE
storage: Dropped raft messages

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19423]
Certain workloads result in a steady stream of "dropped" raft messages (measured [at the server](https://github.com/cockroachdb/cockroach/blob/c82e2c816f45a8984b6f7f0ee68f4cf3a368a4ff/pkg/storage/store.go#L2931) after receiving the messages from the network). #18657 is one such workload; I also have a binary load generator from a customer that exhibits this symptom. 

It is unclear whether these dropped messages are having any significant impact - increasing buffer sizes causes the dropped messages to go away without changing the performance of the workload in #18657. Still, there shouldn't be any dropped messages in normal usage so we should figure out what's going on here.

**Comment by a-robinson** [comment]
Dropped messages happen when a single range can't process raft messages fast enough. That much seems self-evident from how the metric is defined/measured.

In #18657, the core issue that was causing the queue of raft messages for a range to fill up (which in turn causes new messages to be dropped) was the downstream-of-raft bottleneck on `raftMu` (https://github.com/cockroachdb/cockroach/issues/19156). I've had other work keeping me from getting back to those experiments, but my expectation is that if you speed up the downstream-of-raft processing enough, the dropped messages will go away.

Simply splitting the hot range always worked as a workaround for #18657. Have you tried it with your workload generator? In #18657, splitting the one hot range into two would significantly reduce the number of dropped messages, and splitting it up into a few more more would always get rid of them entirely. This makes sense, because it allows for the work to be parallelized better and spreads any queued requests across more queues. This is why I suggested using dropped raft messages as a signal for load-based splitting in #19154.

**Comment by bdarnell** [comment]
> Have you tried it with your workload generator?

Not yet. It's a black-box binary and I haven't looked into its key distribution patterns to know where to split.

> Dropped messages happen when a single range can't process raft messages fast enough. That much seems self-evident from how the metric is defined/measured.

Right. So things to look at include
- Do we need all these messages or are we sending something unnecessarily?
- We currently drop the tail when the queue fills up; can we be smarter? (e.g. drop older heartbeats to save queue space for other messages)
- Instead of a 100-slot queue per range, should we have a shared pool of queue capacity?
- If we're routinely filling up the queue we probably need some sort of backpressure signal to the senders.

**Comment by bdarnell** [comment]
OK, I've gotten some more instrumentation here (in the customer workload I referred to earlier). The queue overflows are all happening on the leader, and the messages are nearly all (>99%) `MsgAppResp`. We see a sequence of messages with `Index` increasing one at a time (in batches by follower ID - we'll get 10-20 messages from replica 2, then 10-20 messages from replica 3).

For successful `MsgAppResp`, the only thing that matters is the monotonically-increasing index. There's no reason to keep more than one in the queue; only the latest one matters. Raft currently maintains a one-to-one relationship between MsgApp and MsgAppResp - each MsgApp gets its own response. (Why are we seeing queue drops on the leader but not the followers? The leader handles twice as many messages since it gets responses from both followers. There's also some flow control in effect for MsgApp that doesn't apply to other messages because MsgApps are the only "large" messages).

I think we can address this pretty easily by scanning for redundant MsgAppResps in the outbound queue of handleRaftReady. I don't think it's going to make much difference for performance (as we've seen, "solving" the problem by making the buffers bigger doesn't do much), but it will make this anomalous metric go away.

**Comment by a-robinson** [comment]
SGTM. Also, handling it in the outbound queue may *slightly* help performance by virtue of cutting down the amount of time we spend sending messages (https://github.com/cockroachdb/cockroach/issues/19156#issuecomment-335821920).
