### ISSUE TITLE
RESTORE ... AS OF SYSTEM TIME syntax

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#19454]
In https://github.com/cockroachdb/cockroach/pull/18547#issuecomment-330315884 @bdarnell raised a concern that AS OF SYSTEM TIME might not be appropriate for commands that are not read only. We should see if anyone else shares that concern and, if so, come up with a new syntax

**Comment by dianasaur323** [comment]
Looks like Oracle does INSERT INTO... (SELECT AS OF TIMESTAMP)
https://docs.oracle.com/cd/B28359_01/appdev.111/b28424/adfns_flashback.htm#i1009447

Alternatively, Oracle has a TO RESTORE POINT syntax, which we might not want to use since restore points mean something else entirely, but it could be TO SYSTEM TIME. Honestly, I don't feel too strongly about this.

**Comment by dt** [comment]
Closing on @dianasaur323's instruction unless someone has a concrete suggestion for an alternative.
