### ISSUE TITLE
build: consider removing generated protobufs from version control

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19552]
See #19482 for a discussion. Courtesy of Tobi:

>pros:
>
>- no need to re-run CI because the protos changed
>- no merge conflicts because of proto changes (unless the conflict is in .proto)
>- never pushing these rather large diffs, which is nice on bad connections
>
>cons:
>- Makefile really needs to work well so that switching branches auto-regenerates ;-)
>- can't see the generated code in diffs

Epic CRDB-10447

Jira issue: CRDB-5967

**Comment by andreimatei** [comment]
One big con is missed here, I think: one has to regenerate the code when switching branches. Besides getting the makefile correct for this, you have to pay time on every switch.

Also, the first pro is actually a con I think. You *want* to run the CI on proto changes.

**Comment by dt** [comment]
Cons += makes much of our code harder (nearly impossible) to use elsewhere
(user plugins/integrations, experiments / PoCs / tools / side projects),
since it would no longer compile with std tool chain.

This was already the case for c-deps, but those appear in the dependency
closure of far fewer packages, while nearly whole codebase depends on
protos, at least transitively.

**Comment by RaduBerinde** [comment]
It looks like currently even though the generated code is checked in, the files get rebuild when switching branches. So if we're paying that cost anyway, we might as well reconsider removing the files from the repo.

The other con of not being able to build cockroach with std tool chain - that is also already the case (because of sql.go generation).

**Comment by dt** [comment]
yeah, since sql.go switched to auto-generate, we broke consuming almost all our packages outside cockroach, and now, since #21402,  we re-generate everything on the fly, so there's little reason left to keep these checked in.

**Comment by dt** [comment]
(though I think we should wait at least until 2.0 is stabilized before making a big, conflict-y change like removing them)

**Comment by RaduBerinde** [comment]
If we leave them checked in, we should add a flag that prevents `make` from rebuilding them (and anything else it builds that's checked in). I very rarely modify any protos but I see them getting built very often.

**Comment by rickystewart** [comment]
Post-Bazelfication we will remove protobufs from version control.

**Comment by jordanlewis** [comment]
This is done 🎉
