### ISSUE TITLE
Bytea arrays break in queries

### ISSUE THREAD

**Issue by rendaw** [cockroachdb/cockroach#19558]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

Running from docker 1.1.1:
```
$ docker exec -it microraw_dbgateway_1 ./cockroach version
Build Tag:    v1.1.1
Build Time:   2017/10/19 15:31:46
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f3bc578c89627d02f2ca30f02b835388278a1c83
Build Type:   release-gnu
```

No env variables, running in insecure mode.

2. Please describe the issue you observed:

- What did you do?

```
final PreparedStatement s = r.connection.prepareStatement("SELECT ?");
s.setArray(1, r.connection.createArrayOf("bytea", new byte[][] {"hi".getBytes()}));
s.execute();
```

- What did you expect to see?

No error.

- What did you see instead?

The error `org.postgresql.util.PSQLException: ERROR: nested arrays not supported` is raised at `execute()`.

Changing the array to
```
s.setArray(1, r.connection.createArrayOf("bytea", new String[] {"hi"}));
```
seems to work, or at least no exception is thrown, so it may be a viable workaround.  I'm a bit worried that charset encodings might mess with the data.

I'm running into this since I'm trying to do `DELETE FROM x WHERE id in ANY(?)` with a bunch of generated bytea ids.

**Comment by rendaw** [comment]
Using strings to create the array didn't work either:
```
final PreparedStatement s =
	r.connection.prepareStatement("select count(1) from (select ? as x) where x = any(?)");
final byte[] clip = new byte[] {0, 44, 13, (byte) 227};
s.setBytes(1, clip);
s.setArray(
	2,
	r.connection.createArrayOf(
		"bytea",
		new String[] {new String(clip, StandardCharsets.US_ASCII)}
	)
);
final ResultSet res = s.executeQuery();
res.next();
System.out.format("%s\n", res.getLong(1));
```
output
```
0
```

I tested with integer arrays and string arrays, both worked.  Changing the encoding didn't help here.

**Comment by rendaw** [comment]
Found a real workaround for the time being:
```
final PreparedStatement s =
		r.connection.prepareStatement("select count(1) from (select ? as x) where x = any(?)");
final byte[] clip = new byte[] {0, 44, 13, (byte) 227};
s.setBytes(1, clip);
final StringBuilder hex = new StringBuilder();
hex.append("\\x");
for (final byte b : clip)
	hex.append(String.format("%02x", b));
s.setArray(2, r.connection.createArrayOf("varchar", new String[] {hex.toString()}));
final ResultSet res = s.executeQuery();
res.next();
System.out.format("%s\n", res.getLong(1));
```
output
```
1
```

**Comment by justinj** [comment]
Hi @rendaw, I'm not sure even Postgres will do what you want here unfortunately, unless I misunderstand, the array constructed by your query in Postgres is
```
{{'104','105'}}
```
Because jdbc is interpreting your `byte[][]` as a 2-dimenstional array of bytes rather than a 1-dimensional array of `BYTEA`s (the 2x1 array of bytestrings "104" and "105", corresponding to the ascii values of 'h' and 'i'). I think your best bet would be to manually construct the `\x...` form of the string as you're doing in your most recent comment. My jdbc knowledge is somewhat limited but I can't see an obvious way to make it behave as we'd like here.

**Comment by rendaw** [comment]
Ack, I think you're right.  https://stackoverflow.com/questions/14914365/creating-an-array-of-bytea-in-java-to-pass-to-a-postgresql-stored-procedure suggests the same, I actually read this before but misinterpreted the statements.

Glad to close this, but if you happen to know and don't mind another question, is this a limitation of SQL, the PostgreSQL protocol, or JDBC?  Would this be an issue with other languages' libraries?

**Comment by justinj** [comment]
I think it's hard to pin the blame on any one thing here, since JDBC could in theory provide a workaround, but this confusion is a consequence of the strange property of Postgres arrays where the *type* doesn't have a specified dimensionality (`{{1,2,3},{4,5,6}}` and `{1,2,3}` are both valid `INT[]`s!) that this ambiguity exists.

In my experience, JDBC does much fancier things with respect to introspecting on types than other drivers do, but it's possible that this would crop up in other drivers as well.

**Comment by rendaw** [comment]
Thanks, that makes sense.
