### ISSUE TITLE
config: zone configs on interleaved tables

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19560]
These shouldn't work, because interleaved tables share their parent's ranges, but nothing in the current system will tell the user that.

**Comment by tschottdorf** [comment]
What's this issue about? Should something be done?

**Comment by a-robinson** [comment]
The issue is that when a table is interleaved in a parent, its replication can only reasonably be controlled by zone configs on its parent, yet we will happily let you set a zone config on it directly even though that zone config will never have any effect. Ideally we'd return an error on attempts to set zone configs for interleaved tables.
