### ISSUE TITLE
sql: permit placeholdered ordinal references in`ORDER BY` clauses

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#19595]
```
root@:26257/test> prepare x as SELECT * FROM bar ORDER BY $1;
pq: could not determine data type of placeholder $1
```

This should work fine, since the only available constant datatype for `ORDER BY` is integer.

**Comment by jordanlewis** [comment]
So I submitted a similar bug to Postgres, only to be told by Tom Lane that this isn't really a bug: see the post at https://www.postgresql.org/message-id/31441.1509129192%40sss.pgh.pa.us. The reasoning goes that the syntax `ORDER BY 2` that orders the query by column 2 is somehow special and can't be achieved with a placeholdered value without risking some sort of injection error. I'm not sure I really buy it. Can't integer placeholders be treated as a special case and used in the same fashion as integer literals in an `ORDER BY`? I suppose this doesn't really matter too much, but it's interesting to think about.

I'll probably close this in a few days as wontfix.

**Comment by bdarnell** [comment]
I don't see the injection risk here either. In fact, I'd say the lack of placeholder support in `ORDER BY` is an injection risk, because when people want to be able to run the same query with different orderings they have to fall back to string manipulation (i've found live SQL injection vulnerabilities due to this before). I would be in favor of supporting placeholders for references to output columns.

**Comment by jordanlewis** [comment]
@bdarnell are you suggesting adding support for column names in `ORDER BY` placeholders as well as column indexes? That's quite a new feature - AFAIK, databases don't usually support sending database object names via placeholders.

**Comment by bdarnell** [comment]
No, just ordinal references. I think I'd be OK with column names too, but since there's no precedent for it that I'm aware of we'd need to think about it carefully (for example, it would probably have to be restricted to the names of columns rendered by the query; you shouldn't be able to inject an ordering on a column not otherwise included in the query).

**Comment by jordanlewis** [comment]
SGTM.

**Comment by a-robinson** [comment]
Not to rain on the parade, but is this something that anyone has asked for or needed? It seems weird to add our own custom functionality without any real motivation for doing so.

**Comment by jordanlewis** [comment]
Yeah, nobody has asked for this. The motivation for submitting this issue was an experiment I was doing to automatically check whether statements in our logic test suite work properly when their leaf data was replaced with placeholders and sent via the pgwire-level PREPARE/EXECUTE pathway.

This scenario doesn't work for us but does in Postgres. I reported this before I realized that Postgres's actual behavior on execute is the unhelpful "sort-by-constant" method. So in fact there's no risk of non-compatibility here for sane queries.

**Comment by bdarnell** [comment]
This is low priority because apparently no other database supports it, but I'm hereby asking for it since I've seen SQL injection bugs that would have been prevented if this had existed :)

I suspect that a big part of the reason that other databases don't do this, though, is efficiency (not injection concerns). If the order can be changed with a query parameter, you can't do as much planning at PREPARE time.
