### ISSUE TITLE
sql: memory accounting budget error when running large query

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19686]
I am getting the following error message:
`pq: temp disk storage: disk budget exceeded: 61 bytes requested, 0 bytes in budget`

Running: 
`select distinct(...),age(...::timestamptz,...::timestamptz),...,... from ... left join ... on ...::bytes=... where ... like '...' group by ...,...,... LIMIT 20;`

Running the most recent master.

cc @justinj

**Comment by justinj** [comment]
FWIW I don't think this is related to the size of the query, the error message implies to me that there's some memory budget that's not being initialized properly somewhere.

**Comment by dianasaur323** [comment]
Ok, I was curious whether or not this error would only be thrown when certain conditions were met, but I just reproduced it again. You have access to the cluster if you want to take a look.

**Comment by asubiotto** [comment]
This is the temporary storage disk budget that is being exceeded (it is set to 0). You can use the `-max-disk-temp-storage` flag to set it to something like `64GB`. It's kind of weird that it was set to 0 (I assume that it was initialized to this), maybe @andreimatei or @richardwu could provide more insight.

**Comment by dianasaur323** [comment]
@richardwu would it be a better usability experience if we also added an error message along the lines of "this query requires additional disk memory" or something like that. Whatever you think makes sense?

**Comment by richardwu** [comment]
Definitely. I'll try to look into where it makes the most sense to wrap the error with the more UX-friendly message. 

This is a general observation but it seems that sometimes it's hard to tell when it's appropriate to wrap an error with a user-friendly error messages. Because of how Go treats errors as return values, on one hand it's tedious (and probably less UX-friendly) to wrap an error message at each part of the call stack. On the other hand, it's ambiguous when an error should be wrapped and whether or not it deserves a more human readable message prefix.

**Comment by andreimatei** [comment]
There's a place in sql where we recognize certain errors and slap better messages and pg codes on them - see `convertToErrWithPGCode`
