### ISSUE TITLE
timeutil: time.Now().UTC() removes monotonic wallclocks

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19781]
Any call to setLoc strips the monotonic info. This means we aren't protected by go 1.9's monotonic protection. Found in #19769.

Jira issue: CRDB-5953

**Comment by dt** [comment]
Ooooof. We don't want non-UTC timestamps floating around, so we'd ideally like to keep the linter that ensures all the timestamps we create are `UTC()`ed, but the fact that that calls `stripMonos`, and in a internal helper we can't control, is unfortunate.

An alternative to `.UTC()`ing everything would be to try to change the default loc, but as we've noted before, to ensure consistent behavior of e.g. pkg/sql/parser, we'd need to do this in `init` in those packages which is pretty gross.

**Comment by dt** [comment]
in offline discussion, it sounds like the best idea we can come up with is setting `time.Local = time.UTC` in timeutil's `init` (and then maybe asserting it stays that way just in case any deps have the same idea?).

Another approach would be to use separate time types for those where we want monotonic behavior versus caring about wall time rendering behavior... we'd write the SQL functions that operate on user-facing times to take the renderable type and then work backwards from there. This seems like a pretty significant yak, so the pkg state hack, gross as it is, looks like it might be the more reasonable approach for now?

**Comment by dt** [comment]
oh, and for completeness, I guess we could have time.Time be our renderable type and tag monotonic times instead and just require those for Since and Sub with listing. However, go makes it easy to lose the monos (by calling UTC) but hard to get them back, so that way doesn't seem to make as much sense.

**Comment by danhhz** [comment]
@mjibson @dt does something need to be done here before 2.0? if so, we should add the milestone so it doesn't get lost

**Comment by mjibson** [comment]
Probably a question for the core team. I only found the issue. I have no idea of its impact.

**Comment by bdarnell** [comment]
Do we need to do anything here? We don't rely on Go 1.9's time monotonicity AFAIK. The HLC does its own monotonic ratchet across nodes. I don't understand how the division by zero errors in the linked test failures relate to the backwards time jumps.

**Comment by mjibson** [comment]
The division by zero code has been removed due to unrelated changes. (However its presence is what alerted us to this bug.) A time jump would occur, a thing would do `something/(end-start)`, `end-start` was 0, and it'd result in the panic. I think it's worth keeping this issue even if we don't fix it for 2.0 because the above pattern will likely be used in the future to measure how long something took and it could fail in this same way if the programmer has an assumption of monotonicity. But I agree it doesn't affect system correctness, just benchmark measurements.

**Comment by bdarnell** [comment]
A monotonic clock doesn't guarantee that `end - start` is non-zero, only that it's non-negative.

**Comment by dt** [comment]
This came up again recently. I'm still not a huge fan of messing with time.Local, but it would also solve the unfortunate `Parse` vs `ParseInLocation` default vs local for parsing abbreviations issue. Ultimately though, it also just makes sense since Cockroach is expected to be deployed in geographically distributed clusters, no single node should be changing its behavior based on its local TZ value, so `time.Local` shouldn't really be env-controlled. In light of that, nuking the global in init seems like it might actually make sense.

**Comment by knz** [comment]
Moving this back into server queue
