### ISSUE TITLE
sqlccl: IMPORT -  support filling in SERIAL or DEFAULT columns

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19869]
Currently every column must be given an explicit value in the CSV data -- i.e. unlike INSERTs, columns cannot be left unspecified to have the DEFAULT value filled in. This difference is perhaps most likely to be encountered for SERIAL ids, where the expectation is that the DB fills them in.

**Comment by danhhz** [comment]
We also had a request for DEFAULT columns on the forum: https://forum.cockroachlabs.com/t/import-does-not-support-default-values-very-annoying

**Comment by ikzelf** [comment]
One thing about the serial ....... if data is moved from one to an other database, you had better use the data read in from the csv .... otherwise, referential constraints will fail. It might be helpful to give an option to reset the SERIAL to the value needed after the import completes. In postgres we use a reset value for the serial in this case.

**Comment by knz** [comment]
See #25486 for another community request.

**Comment by rolandcrosby** [comment]
Should be solved by IMPORT INTO.
