### ISSUE TITLE
ui: establish browser support policy

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#19904]
We've been operating under a somewhat informal browser support policy for the admin UI: generally we support Chrome (and maybe Firefox?), but we only really do much testing of Chrome (and maybe Firefox?) on OS X (and maybe Ubuntu?).

We should establish a policy on what browsers on which platforms are supported, document it, and then implement a automated test infrastructure to watch for regressions, particularly for browser/platform combinations that the admin UI team isn't personally running.

**Comment by dianasaur323** [comment]
Ok, I can spend the next week looking into this and report back

**Comment by dianasaur323** [comment]
hmm.. I thought I responded back, but clearly I didn't. Chrome and Safari are commonly used, and since our Windows support is for testing only, I think it makes sense for us to target OS X users, at least for now. Let's wait to get more actual user feedback before changing anything beyond checking for Chrome and Safari on OS X?
