### ISSUE TITLE
cli,sql: sql shell can access database that isn't there

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19927]
I killed my cluster and restarted, and ran the typical sql command I usually run:

cockroach sql --certs-dir=certs -d old_db

Which gets me to:

root@:26257/old_db>

However, old_db doesn't exist. Should we do some error checking so that you can't get into that state?

**Comment by bdarnell** [comment]
`old_db` doesn't exist yet, but since you're root you can create it and then start using it immediately. This is a useful convenience feature for testing frameworks (without it you often have to make one connection to create the database, then close it and reconnect to use the database you just created). It's admittedly only useful if you can run as root (which means a local/throwaway DB) and other databases don't work this way, but I find it quite handy.

We should probably make it an error if you get into this state as a non-root user, though, since you won't be able to create the database.

**Comment by dianasaur323** [comment]
ah, that's interesting and makes sense. I'll keep this open for now in case we decide to error out for a non-root user, but bumping priority down to later.

**Comment by knz** [comment]
Next action item: warn/error if current value of `database` points to non-existent db and user is not root

**Comment by knz** [comment]
This has been addressed in 2.1.
