### ISSUE TITLE
sql docs: add detail to documentation for transaction_timestamp

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20075]
The documentation for the built-ins`current_timestamp()`, `now()`, and `transaction_timestamp()` says simply "Returns the current transaction’s timestamp."  This is a source of confusion, since the phrase "transaction’s timestamp" seems to indicate that it is the same value as described in [the transaction docs](https://www.cockroachlabs.com/docs/stable/transactions.html) and [the architecture docs](https://www.cockroachlabs.com/docs/stable/architecture/transaction-layer.html#time-hybrid-logical-clocks) ("Whenever a transaction's timestamp is mentioned, it's an HLC value.").  It's not, but we don't make that very clear.

We should expand that documentation to include more detail around exactly what timestamp is returned from these built-ins, and how that differs from the internal transaction timestamp.

**Comment by couchand** [comment]
Assigning to @awoods187 for triage.

**Comment by bdarnell** [comment]
I was also tripped up by this - I thought that `transaction_timestamp()` was just `cluster_logical_timestamp()` truncated to sql timestamp resolution. I don't remember why we made this decision and I'm sure there was a good reason, but it would be great if these two could be made consistent instead of just documenting the difference between them.

**Comment by couchand** [comment]
@ben for context, here's the issue where the change was made: #5767
