### ISSUE TITLE
sql: parity between local SQL and distSQL in JOINs

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#20173]
We want to eventually get feature parity between local SQL execution, and distSQL execution, but one particular feature gap stands out: JOIN execution in local SQL is far behind.

First, local SQL does not plan merge joins, but distSQL does, so turning off distSQL increases the potential memory usage by JOIN queries quite a bit.

Second, local SQL does not have the ability to use external storage for large queries, we cannot run large JOINs without distSQL (since one needs either merge joins or external storage, and local SQL execution has neither).

Workarounds such as greatly increasing the amount of memory available to SQL processing (through the use of `--max-sql-memory`) is not great, since CockroachDB's overall memory footprint becomes much larger, and this memory does not seem to be proactively released (see e.g. #20078) until memory pressure is applied to the machine through other means.

This situation should be remedied when the two execution engines are unified, but for now, large JOIN queries require the use of DistSQL. We might require some intermediate work to bring local SQL execution up to parity with respect to JOIN execution.

**Comment by jordanlewis** [comment]
It makes sense to me that large joins should always be planned with DistSQL.

Having not played around with profiling small joins (joins that have small spans to read on both sides), it's hard for me to say whether there's a performance reason to plan small joins in local SQL. Has there been any profiling work on that front?

**Comment by petermattis** [comment]
> It makes sense to me that large joins should always be planned with DistSQL.

Agreed, though the lack of feature parity between local SQL and dist SQL leaves us in an awkward position right now. We can't use dist SQL in write operations, including operations which perform a query in order to insert into a table. And we can't use dist SQL after a transaction has performed a write operation (the precise reason escapes me, but @andreimatei would know). Lastly, we can't use dist SQL for certain queries which use functionality not supported by the dist SQL processors. 

There is a medium term plan to address all these shortcomings in dist SQL. Question is whether there is a short term fix to address the shortcomings of local joins.

**Comment by jordanlewis** [comment]
This issue seems to be about work on local joins. We're not planning to do that, so closing.
