### ISSUE TITLE
sql: encodeIndexKey needs to verify datum type matches column type

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2033]
Currently `encodeIndexKey` encodes the key using the datum's type which might not match the column type. See https://github.com/cockroachdb/cockroach/blob/master/sql/table.go#L164.

This currently results in a panic during `INSERT`:

```
CREATE TABLE foo (k CHAR PRIMARY KEY)
INSERT INTO foo VALUES (1)
```

The panic occurs in [prepareVal](https://github.com/cockroachdb/cockroach/blob/master/sql/table.go#L284) due to the values datum being of type `DInt` while the column type requires a `DString`.

**Comment by tamird** [comment]
This is going to be a fairly large amount of somewhat tedious work. For instance, the example you posted works in postgres because `1` is implicitly converted to `'1'`. Inserting `"hello"` fails, though, because `value too long for type character(1)`. So we're gonna need `O(inputTypes * columnTypes)` cases here.

**Comment by petermattis** [comment]
I think we've decided to differ from postgres in our handling of conversions and not allow implicit ones. We're certainly not allowing implicit conversions in expression evaluation.
