### ISSUE TITLE
k8s cluster init error

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#20427]
I built a docker image on master (+ a patch only affecting SQL land), and deployed it with the insecure k8s stuff on fresh disks. I then ran the cluster-init job, which failed. Its logs:

```
$ k logs cluster-init-7ww7c
E171203 07:27:33.134707 1 cli/error.go:68  address cockroachdb-0.cockroachdb:tcp://10.55.254.194:8080: too many colons in address
Error: address cockroachdb-0.cockroachdb:tcp://10.55.254.194:8080: too many colons in address
Failed running "init"
```

**Comment by mjibson** [comment]
This appears to be a cockroach problem and not a k8s or .yaml problem. If I docker exec into the image and run `./cockroach init` I get the same error.

**Comment by a-robinson** [comment]
I'm guessing you've created a service in your kubernetes cluster named "cockroach", which isn't included in our provided configurations. This is a problem because [Kubernetes injects a bunch of environment variables into pods for each service in the same namespace](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables), including an environment variable called `<SERVICENAME>_PORT`. This happens to tickle the `COCKROACH_PORT` environment variable recognized by client cockroachdb commands.

To unbreak this, I'd recommend not naming a service `cockroach`. But if you want to keep that, you can either specify a `--port` flag on all client comands that you run or manually overwrite the environment variable before running the client command.

**Comment by mjibson** [comment]
Ah yes. I had the admin ui configured under the name cockroach. k8s is tricky. I worked around it by starting a cluster with 1 replica and no join argument, shut it down, then did the normal thing. Thanks.
