### ISSUE TITLE
sql: allow the ability to force a hash/merge join on a query

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#20544]
The planner can be configured to use/not use certain strategies using
run time configuration as listed below. This issue is about implementing
turning on/off hash-join or merge join on a session.

```
SET enable_hashjoin off
SET enable_mergejoin off
```

https://www.postgresql.org/docs/9.2/static/runtime-config-query.html

**Comment by richardwu** [comment]
So it seems that `SET enable_hashjoin` will have the same caveat as `SET enable_nestloop` in Postgres since hash joins are our "default" join method if all else fails
> It is impossible to suppress ~~nested-loop~~ hash joins entirely, but turning this variable off discourages the planner from using one if there are other methods available.

I think that caveat is more relevant for when we actually do plan optimization and costing on physical plans (re: query optimizer), since currently a hash join will never be considered if a merge join (the "other method") is possible (i.e. this implies `SET enable_hashjoin off` requires no implementation).

**Comment by robert-s-lee** [comment]
A session could run a various query that may require different hints for each.  Does Postgres support per query hint syntax we can leverage?

**Comment by jordanlewis** [comment]
Postgres has a very similar "hint" system to the kind that we're discussing here. There are many knobs that are tunable to permit or ban various kinds of plans from being created.

https://www.postgresql.org/docs/current/static/runtime-config-query.html

**Comment by robert-s-lee** [comment]
Database selected plans should be good in most cases; however, the plan cannot be optimal in all cases.  The statistics and/or rules used to determine the plan cannot correctly anticipate every edge conditions.  Developers and Production DBA need a mechanism to override the plan as required.   

Following the Postgres hint system, for now, would allow easier customer adoption.  However, tuning strategy between single instance database and distributed database are different.  Some caution would be in order.  

Hints are generally used by advanced users to maximize performance.  The documentation on when to use and not use each hint would be sufficient initially --  what it does, when could it be helpful, how does it help, statistics or measurements that could aid in determination.   For example, below two settings could be considered hints.

SET CLUSTER SETTING sql.defaults.distsql = 1;
SET sql.distsql.merge_joins.enabled = (true|false)

In the long term, the ideal method would be to decouple the hint (or modified plan) from the SQL.    Changing the queries in order to add hint would require application-level adjustment most customers don't have access.

**Comment by vivekmenezes** [comment]
I wonder if the lack of application level adjustments was the main reason why postgres implemented these hints as session variables. I'm tempted to say that we should not implement any of these hints in 2.0 and only implement them as part of the new SQL optimizer.

**Comment by petermattis** [comment]
> I'm tempted to say that we should not implement any of these hints in 2.0 and only implement them as part of the new SQL optimizer.

I agree. Anything we do for 2.0 would be fairly minimal in comparison to the possible tunables in 2.1.

**Comment by awoods187** [comment]
I thought we agreed to do merge-join only hints in 2.0 (I believe @RaduBerinde mentioned it was lower hanging fruit)

**Comment by petermattis** [comment]
I just perused the internal roadmap and see that comment but don't recall the rationale behind merge-join only hints. Would the idea be that you can force or prohibit a merge-join? Would this be a setting or an actual hint on the query? I'm sure we can answer these questions, but given the limited scope of a merge-join hint, I think our energies would be better directed at working on the SQL optimizer.

PS Note that we already have a setting (`SET sql.distsql.merge_joins.enabled = (true|false)`). I don't think this is particularly useful outside of testing as merge joins are preferable to hash joins when available.

**Comment by petermattis** [comment]
@awoods187 I followed up with @robert-s-lee and he is fine with the existing `sql.distsql.merge_joins.enabled` setting for 2.0 as long as it is documented but stressed the need for something more sophisticated for 2.1.

**Comment by awoods187** [comment]
alright i'll list this as descoped for 2.0 in favor of the next generation sql query planner

**Comment by andy-kimball** [comment]
Andy, assigning to you, since you'll be coming up with the spec describing the expected syntax.

**Comment by jordanlewis** [comment]
@RaduBerinde i think you can close this
