### ISSUE TITLE
sql: remove `planner.avoidCachedDescriptors` and all uses

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#20551]
As discussed in #20267 this is not necessary any more because the descriptor cache now knows to not used cached descriptors if the txn timestamp is in the past.

cc @andreimatei @vivekmenezes

**Comment by andreimatei** [comment]
We need to be careful here because I seem to remember that something was still not complete in the implementation of the master plan of the caches properly respecting timestamps. But I lost track on where Vivek stopped on that front.
I'm gonna remove the 3 (LOL) "help wanted" labels from this one.

**Comment by vivekmenezes** [comment]
The work done for using an arbitrary timestamp and receiving a table descriptor that is valid for the timestamp is complete!

**Comment by andreimatei** [comment]
Ah, great!

**Comment by jordanlewis** [comment]
@vivekmenezes is this still relevant..?

**Comment by andreimatei** [comment]
I still see the `p.avoidCachedDescriptors` field... What's the story?

**Comment by vivekmenezes** [comment]
there is nothing actionable in this issue. if someone wants to improve the code through refactoring they can go ahead and do it. It doesn't need to be captured in an issue.

**Comment by andreimatei** [comment]
Well there is something kinda actionable in this issue. The issue is complaining that that the `p.avoidCachedDescriptors` shouldn't exist. And yet it does exist. I'm pretty sure we should get rid of it, but how to do that exactly / why does it exist is not clear to me.
I dunno; I think the issue was serving a valid purpose for gathering discussion about it and for keeping the hope alive.
