### ISSUE TITLE
distsql: investigate modeling an inbound stream as a RowSource

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#20553]
Related to #20550.

Inbound streams in distsql are currently processed in their own goroutine. `ProcessInboundStream` loops, reading from a grpc stream, decoding rows and pumping the resulting rows into a `RowReceiver` (usually/always a `RowChannel`). It looks feasible to invert this by hooking up the inbound stream to the flow registry as a `RowSource`. Calls to `RowSource.Next()` on the inbound stream would have to call `stream.Recv()`, decode a batch of rows and then return them.

The upside to this change is the removal of a `RowChannel` between an inbound stream and the processor. The downside is that we wouldn't concurrently decode rows with executing the downstream processor. Any change needs to be validated by benchmarking.

@RaduBerinde thinks the benefit of this change will be reduced if the `RowSource` interface is changed to return batches of rows, so this issue should probably be tackled after that change.

**Comment by RaduBerinde** [comment]
One thing to consider here is that if we have multiple input streams connected to the same unordered synchronizer, we use a shared `MultiplexedRowChannel`. Implementing an unordered synchronizer with a `RowSource` model is problematic, because we don't want to block on one stream while the other is producing data.

**Comment by petermattis** [comment]
Yeah, I think `MultiplexedRowChannel` would need to continue to exist. This could be done with an adapter goroutine that connects the `RowSource` to the `MultiplexedRowChannel`. Do you have a sense for how often plans have an unordered synchronizer with a single input vs multiple inputs? If single inputs are relatively infrequent, this change isn't terribly interesting.

**Comment by RaduBerinde** [comment]
I don't have a good sense.. I'd expect in most cases to have multiple inputs (due to tablereaders on multiple nodes), though some those are going to be ordered synchronizers.

**Comment by arjunravinarayan** [comment]
Single input unordered synchronizers are pretty common in my experience. It's quite frequent e.g. when joining tables and one table is small. In the future world where we have table statistics and are taking them into account when physical planning, you want to send the smaller table over the network, rather than the larger one, so you would in fact increase the probability of single input remote data.

**Comment by jordanlewis** [comment]
No longer relevant since we introduced vectorized.
