### ISSUE TITLE
util/mon: reduce overhead of memory accounting

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#20591]
See #20590. 

```
name                time/op
BoundAccountGrow-8  61.6ns ± 5%
```

The benchmark in that PR shows that calling `BoundAccount.Grow()` is quite expensive. This is primarily due to the locking in `BytesMonitor.reserveBytes()`. If that locking is removed (for benchmarking purposes), the numbers change to:

```
name                time/op
BoundAccountGrow-8  14.8ns ± 1%
```

Much better, though still higher than I'd want to see for memory accounting. I would naively imagine memory accounting to look like incrementing a variable and checking it against a limit in the common case.

**Comment by knz** [comment]
Copy pasting my comment from https://github.com/cockroachdb/cockroach/pull/20590#issuecomment-350469810:

I know! 

1) Originally when I wrote this code in #9259 I was very adamant that only the connection between one monitor and another should use a mutex (via a separate abstraction `MemoryPool`) but not the connection between an account and a monitor. The original design was saying "a monitor is going to allocate in chunks from a pool, and pools against each other, so that the accounts that bill against a monitor can use more fine grained grow operations without the mutex overhead". You can check the commit history in #9259 to verify this is true. Then Andrei came after me and said "this is too complicated, we want accounts to bill against monitors concurrently, so put a mutex in the monitor already and drop the pool". I knew this was bad but at that point I was tired from arguing.

2) I suspect the `if log.V(2)` in there is also not helping. I am not sure how to make this better -- we (at least, I) have found the conditional logging useful in the past, but `log.V` is not exactly cheap.

**Comment by petermattis** [comment]
Disabling the `log.V(2)` helps after the locking is removed:

```
name                time/op
BoundAccountGrow-8  9.51ns ± 2%
```

But that is minor in compared to the locking. Looking at this code, despite the detailed commentary I'm struggling to understand the connections. `BytesMonitor` seems to be both thread-specific and shared between threads when acting as a "pool". Would it be sufficient to change `BytesMonitor.pool` to a new `SharedBytesMonitor` object that is thread-safe?

**Comment by knz** [comment]
The original design had BytesMonitor.pool point to a separate `MemoryPool` struct (itself linked hierarchically to other `MemoryPool`s). Access to `pool` was locked, access to `BytesMonitor` by accounts was not.

**Comment by knz** [comment]
For the sake of historical accounting, the separate `MemoryPool` was considered "premature optimization". I guess I should have published my own benchmarks in the commit message back then already. Lesson learned.

**Comment by knz** [comment]
Here's the code with separate pool btw: https://github.com/cockroachdb/cockroach/commit/0777067f9c0c37b2d182e3288aa86d9063e984cc

**Comment by petermattis** [comment]
This is kind of a mess now as various places in `distsqlrun` are sharing monitors across goroutines when they really should be creating new monitors. That is, they are using monitors as pools when they really need/want processor-specific monitors. For example, `FlowCtx.diskMonitor` and `FlowCtx.EvalCtx.Mon`. Untangling this correctly will require insight from someone more familiar with distsql than I am.

**Comment by petermattis** [comment]
Btw, one option I explored before running into the above difficulty is to change `BytesMonitor.mu.Mutex` to a pointer:

```diff
 type BytesMonitor struct {
        mu struct {
-               syncutil.Mutex
+               *syncutil.Mutex
```

We would then only initialize the mutex when using the monitor as a pool, which can mostly be done automatically. However, `distsqlrun` uses monitors concurrently. I explored this approach because it seemed like it could address the performance without sweeping changes. But it seems better to add an explicit `Pool` object and make `BytesMonitor` explicitly unsafe for concurrent access. That will be a large change, though.

**Comment by arjunravinarayan** [comment]
cc @asubiotto who is the expert here: what would per-processor memory monitors not give us? Why do we currently do per-query limits sharing our monitors across processors?

**Comment by asubiotto** [comment]
I don't think we have per-query limits. What we currently have in place is a limit across all SQL operations with extra per-processor limits on processors that can fall back to disk. Note that monitors do not imply limits, they just help you track what kind of operations are doing the allocation.

The reason to share monitors is to be able to limit operations all belonging to a certain group (i.e. the user has the ability to specify "set my sql max memory usage to x"). If we were to not share any monitors we wouldn't be able to limit this using monitors.

**Comment by petermattis** [comment]
@asubiotto Is correct that we don't have per-query limits. `ByteMonitors` can imply limits, though. See `ByteMonitor.limit`. 

Please take a look at #20590 which fixes the performance problem by adding pool allocation to `BytesAccount`. I believe all of SQL accesses memory accounting via `BoundAccount` (which embeds a `BytesAccount`), so that is a universal fix that is also fairly small.
