### ISSUE TITLE
sql: Move projection out of sortNode by adding a parent renderNode

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20659]
This was briefly [noted in `simplifyOrderings` for the `sortNode`](https://github.com/cockroachdb/cockroach/blob/4afe80e27b5b9627f409da3408e09f457fbfeae8/pkg/sql/expand_plan.go#L547).

This fix would also fix propagation of physical properties, [which we are accidentally projecting out of the `sortNode`](https://github.com/cockroachdb/cockroach/blob/4afe80e27b5b9627f409da3408e09f457fbfeae8/pkg/sql/plan_physical_props.go#L101) e.g. [weak/strong keys](https://github.com/richardwu/cockroach/blob/ffec33995ca68a379b87ac8e6a87e78a149dcfcd/pkg/sql/logictest/testdata/logic_test/distinct_on#L337-L342).

The implementation will be very similar to [the recent refactor of the `distinctNode`](https://github.com/richardwu/cockroach/blob/ffec33995ca68a379b87ac8e6a87e78a149dcfcd/pkg/sql/distinct.go#L171#L184) in #20463.

**Comment by heyihong** [comment]
Hi @richardwu, I once tried to work on this issue following the example, but failed to pass logic test. The problem I am concerning is whether render node is able to keep the order of data compared with sort node without needSort flag. For the test below:
```
statement ok
CREATE TABLE p (
  a STRING COLLATE en_u_ks_level1 PRIMARY KEY
)

statement ok
CREATE TABLE c1 (
  a STRING COLLATE en_u_ks_level1 PRIMARY KEY,
  b STRING COLLATE en_u_ks_level1
) INTERLEAVE IN PARENT p (a)

statement ok
INSERT INTO c1 VALUES ('A' COLLATE en_u_ks_level1, 'apple' COLLATE en_u_ks_level1)

statement ok
INSERT INTO c1 VALUES ('b' COLLATE en_u_ks_level1, 'banana' COLLATE en_u_ks_level1)

statement ok
INSERT INTO c1 VALUES ('p' COLLATE en_u_ks_level1, 'pear' COLLATE en_u_ks_level1)

query T
SELECT b FROM c1 ORDER BY a
----
apple
banana
pear
```

It generates the plan like this by replacing sort node, however the execution could not guarantee the order of output. 
```
0  render  ·         ·           (b)              ·
        		    0  ·       render 0  b           ·                ·
        		    1  render  ·         ·           (b, a[omitted])  a!=NULL; key(a)
        		    1  ·       render 0  test.c1.b   ·                ·
        		    1  ·       render 1  NULL        ·                ·
        		    2  scan    ·         ·           (a[omitted], b)  a!=NULL; key(a)
        		    2  ·       table     c1@primary  ·                ·
        		    2  ·       spans     ALL         ·                ·
```

**Comment by richardwu** [comment]
I believe the semantically-correct option here is to modify the `simplifyOrdering` code to not elide/remove the `sortNode` even if the sort order is provided by the child plan. It will simply render it as `nosort` in the plan and render all of its original columns.

`sort.go:sortNode.Next` (this is for the local execution engine) seems to skip the actual sorting if `!sortNode.needSort`. You would have to modify the distributed execution planner (`distsql_physical_planner.go:addSorters`) to avoid adding a `sorter` processor if `!n.needSort`.

Perhaps @RaduBerinde or @knz wants to chime in here.

**Comment by RaduBerinde** [comment]
One function in the distsql planner does check `needSort`, it looks like an omission that the main one doesn't.

I think the root of the problem that was pointed out is that instead of starting with `usefulOrdering`=nil when calling `simplifyOrderings`, we should extract the query's ordering requirement, and pass that. Then we won't need `nosort` nodes. However, this is a pretty big change, in that we will ignore `ORDER BY`s in subqueries, e.g. `SELECT .. FROM (SELECT .. ORDER BY)`. Ignoring them is actually fine according to the SQL standard, but there may still be compatibility issues or other repercussions (plus we use subqueries like this in some cases, e.g. as a workaround to force merge-joins).

In the short term, I think we should do as @richardwu suggests and keep the `nosort` nodes in the plan (while replacing the projection functionality with a renderNode).

**Comment by jordanlewis** [comment]
This is no longer a problem in the CBO, and the relevant code will be deleted when the HP is removed. Closing.
