### ISSUE TITLE
storage: rocksdbmap underlying storage is being removed

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#20673]
After running some distributed IMPORTs they error with:

pq: IO error: While open a file for appending: /home/mjibson/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp671511287/000006.log: No such file or directory

That directory no longer exists, but another temp dir does. It seems like something is causing the temp storage to clear itself and remake another one. Unsure what's causing this.

**Comment by mjibson** [comment]
This happened because I ran "cockroach start" in another shell in the same directory and it deleted the temp store directory. We should make this not happen because it's pretty bad.

cc @andreimatei @richardwu

**Comment by richardwu** [comment]
So the rationale behind clearing the temp directory before the server actually start is to clean out disk space for a server in case the server crashed previously due to an out-of-disk error.

It's difficult to know when a server is already running: we could check if the configured port is in use and avoid clearing out the temp directory if it is. Thoughts @andreimatei ?

**Comment by andreimatei** [comment]
It's not particularly difficult to know when a server is running -> that's what file locking is for. RocksDB already uses this mechanism to prevent double opens; we should attempt to lock it's `LOCK` file before deleting the temp dir, and report to the user that they might be screwing up if we fail.

**Comment by knz** [comment]
So my apologies for coming late to the game but I would like to discourage thinking about and using locks for this purpose. Locks have this nasty habit of not working well if the user decides (and that's reasonable) to have their temp dir on a filesystem that doesn't support locks.

My recommendation would be to consider the following instead:
1. report an error if a previous temp dir still exists, and let the user deal with it manually
2. write the PID of the owner process to the temp dir; fail to start if a process with this PID is still running
3. name the temp dir after the PID of the owner process; simply report a warning (for the user to deal with manually) if a temp dir for another PID exists already

My own preference goes for 3.

**Comment by knz** [comment]
@bdarnell @mberhault can you chime in and share your thoughts about the issue at hand? What do you think would be the best approach? I am very much against introducing complexity just because that's the first thing one person could think about, instead I think this may warrant a mini-RFC.

**Comment by andreimatei** [comment]
Does RocksDB (which is our temp storage and uses file locks) work on a file system that doesn't support them?

**Comment by bdarnell** [comment]
Since rocksdb already uses file locks, it should be fine for us to do the same (as long as we do *exactly* the same thing, ideally by calling in to the rocksdb code). 

I don't think "leave it for the user to deal with manually" is an acceptable option - this will just lead to a proliferation of subtly-broken scripts and cron jobs to try to automate the task away.

**Comment by mberhault** [comment]
I'm with @bdarnell on this one, we should just use roksdb's lockfile implementation for this. Requiring manual (or cron) cleanup of node disk is a terrible idea. Ultimately, all local disk access will be through cgo, where the rocksdb FS interface is available.
