### ISSUE TITLE
clusterviz: alpha release acceptance criteria

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20686]
cc @josueeee @mrtracy @couchand 

Taking what you guys decided in your meeting and wrapping them into acceptance criteria / user stories
- I want a high-level overview of my cluster so that I know whether or not to take further action
   - [ ] Geo map providing a graphical view of where nodes are located
   - [ ] Aggregated metrics (disk, memory, CPU utilization, qps, service latency) at the locality level
- I want to identify and preempt any scenarios (including changing configurations) that might cause downtime, service issues, or otherwise negatively impact cluster health
   - [ ] Disk utilization shown in the cluster overview
   - [ ] Visibility into underreplicated ranges in the cluster overview
   - [ ] Visibility into unavailable ranges in the cluster overview
   - [ ] Observe QPS across nodes to observe how queries are rerouted on node failures
   - [ ] Allow drill down into specific nodes using the tree map
- I want to confirm that the database is balanced so that I am utilizing my resource effectively
   - [ ] Show storage across localities and nodes
   - [ ] Show QPS across localities and nodes to identify hot spots or degrading performance

- GTM to dos
   - [ ] Confirm that Segment is working
   - Marketing campaign:
      - [ ] Link to a google survey
      - [ ] Blog post
      - [ ] Twitter / LinkedIn / Product Release text

**Comment by dianasaur323** [comment]
@swatikumar16 just added a couple things for marketing. excited!

**Comment by josueeee** [comment]
Worked on a few variations to the node component based on feedback from the past few weeks. I ran with Kuan's initial design and made some improvements to the component's usability and visual design consistency. 

Out of the 5 versions, Spencer and I aligned on pushing Version E for further refinement. This version makes it easier to understand the data being visualized, while also making it easier to compare values across a map. Version E is also effective at providing enough differentiation between a node and an aggregate of nodes by the use of iconography and labeling. 

Next steps:

1. Refine iconography to use more common symbols for nodes and datacenters etc. 
2. Explore using read/writes as secondary metrics (instead of cpu/mem)
3. Explore alerting for the node component 
4. Hand-off design to engineering

![nodecomponentversions](https://user-images.githubusercontent.com/29442020/34161325-52a8b93e-e49e-11e7-9626-86c4bf0a6129.png)

<img width="1027" alt="nodecomponentversione" src="https://user-images.githubusercontent.com/29442020/34161394-7e940ecc-e49e-11e7-904e-e758313391d4.png">

![versione_map](https://user-images.githubusercontent.com/29442020/34161327-52c8637e-e49e-11e7-85b4-b217a7038d18.png)

**Comment by dianasaur323** [comment]
This looks great! I'm a fan of how the gauges have been adjusted. Regarding CPU / Mem, I would hesitate to take it completely off the front page, since those are metrics that users consistently bring up as things they care about. QPS though, as you mentioned, should probably be surfaced here. For alerts, did you mean decommissioning / dead / live nodes? That seems like a reasonable next step. Thanks so much for this, I'm feeling good about it.

**Comment by nstewart** [comment]
![image](https://user-images.githubusercontent.com/894257/34172410-f887854e-e4bf-11e7-8e95-7002544724ba.png)

What is the relationship between nodes and weeks? I don't understand this

**Comment by josueeee** [comment]
To leave further feedback please go to https://invis.io/4XEZJ13CE

**Comment by couchand** [comment]
Closing this in favor of #20685
