### ISSUE TITLE
sql: implicit casts sometimes allowed

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2071]
to my knowledge, the sites are:
- [ ] concat operator `||` accepts non-strings: https://github.com/cockroachdb/cockroach/blob/master/sql/parser/eval.go#L244:L264
- [ ] `CONCAT` accepts non-strings (after #2055 is merged): https://github.com/cockroachdb/cockroach/pull/2055/files#diff-74eeff841a0488dbfb9b804729361666R137
- [x] integer division returns a float (postgres does integer division, and so should we): https://github.com/cockroachdb/cockroach/blob/master/sql/parser/eval.go#L226:L228

**Comment by bdarnell** [comment]
The fact that integer division returns a float is not an implicit cast. It's still rigidly typed (we require either two ints or two floats instead of mix-and-match), it's just that the output type is not necessarily the same as the input type. That's unconventional for a binary operator, but I'd argue that it's the right signature for operator `/`. In fact, our avoidance of implicit casts makes it even more important to always return a float from operator `/`: in most languages you can cast one of the arguments to a float and rely on an implicit conversion for the other, but for us you'd have to explicitly cast them both. Integer division is mostly a trap for the unwary, so I'd rather require `cast(a/b as integer)` for integer division instead of `cast(a as float)/cast(b as float)` for true division of integers.

**Comment by XisiHuang** [comment]
implicit casts not allowd doesn't mean the function cannot convert its arguments .
Just like in golang, functions can have ```interface{}``` arguments!
the same reason  for the ```||``` operator, just like java's ```+``` operater

**Comment by petermattis** [comment]
@XisiHuang `interface{}` arguments do not actually perform a cast, though. The argument type is still available via reflection, type assertions and type switches. What we're trying to decide here is whether we want to allow a limited set of conversions between types (e.g. for `||` and `CONCAT`), or be very strict about type conversions like Go.

**Comment by XisiHuang** [comment]
@petermattis  from postgres' doc, http://www.postgresql.org/docs/9.4/static/functions-string.html
```concat(str "any" [, str "any" [, ...] ])``` accepts "any" which i think is just like go's ```interface{}```, while functions like ```repeat(string text, number int)``` require more specific type.

I don't think there are implicit conversion involved,  the conversion is done manuly inside function```concat```'s implentaion , not implictly outside.

**Comment by petermattis** [comment]
@XisiHuang I suppose you can look at it either way. Are the arguments to `concat` getting implicitly converted to strings or is that conversion explicit in the definition of `concat`? Either way, the arguments were converted without an explicit `cast(expr as type)` or `expr::type`.
