### ISSUE TITLE
distsql: too much buffering in output routers

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#20761]
IMPORT CSV has a problem that only occurs on multi-node cluster (i.e., everything works correctly on a 1-node cluster). When running a distributed IMPORT, each node pushes data to the range router. Each node is also a consumer for some number of KV ranges, which they write to a rocksdb store. However the data is produced much faster than it is consumed, resulting in the heap use growing quickly (a few GB per node in just a few minutes), which triggers the sql memory accounting before the work can complete. This isn't happening in the 1-node case because (we believe) the communication is implemented using a buffered chan, which produces appropriate back pressure.

@andreimatei mentioned that this was a changed done a few months ago in distsql. We've just started testing larger distributed IMPORTs which is why we only saw this bug now. What can we do to address this situation? I assume the unbuffered change was done because something is producing back pressure, but the range router (used by IMPORT) doesn't meet some assumption that was made during that decision. Can we add back pressure here somehow, or allow IMPORT to manually specify a buffer size or something?

cc @andreimatei @RaduBerinde @knz @asubiotto

**Comment by andreimatei** [comment]
Let's clarify this issue: the problem isn't about local communication versus remote communication and is only incidentally related to one node versus many. The issue is about flows with multiple consumers connected to an output router versus single consumers (which also probably means no router). It doesn't matter whether the consumers are local or remote.
The issue is that output routers buffer data whenever one output is blocked but others aren't.
The current buffering strategy seems quite imperfect: if a router has consumers progressing at different speeds, it'll essentially buffer the difference between the fastest and the slowest. This seems like it can get us in trouble quite easily.

Of course, the reason why this buffering was introduced is that, without it, you can easily get into deadlocks: if outputs from a router are joined later in the flow and the join point needs to read alternatively from the streams, then, if one of the streams is full (with the backpressure having reached the router) and the other is empty, the empty one will never get new data because the router is blocked.

But what we're doing with unbounded buffering is pessimistic: we're always assuming that there will be a deadlock unless the router constantly produces data for all the outputs. That's not always the case: a processor downstream of the router might not be consuming data temporarily because it might be blocked on a completely different stream.

So I have a suggestion. Assume no special buffering in output routers. The join point is always in a position to know what input it needs to read from in order to make progress. Because the dataflow network is static, said join point can also know the (complete) provenance of the data from that input - in particular, it can know what upstream routers contribute to it. If one of those routers is also contributing to another input which is full of data (but is not being read), the join point can conclude that we *might* be in a deadlock situation. If this situation is detected, the system as a whole needs to answer the following question: is the reason why the input in question is not getting any data the router that we detected to be in the possible deadlock, or is it not getting data because of another reason? In the former case, increasing the buffer of the output router to the point where some data is produced on one of its outputs will help the flow make progress. In the latter case, the router is not our problem, so buffering will not help.
How to answer this question? Well, I think the processors in the flow could collaborate to answer it. The join point can propagate a signal (downstream towards upstream) on the input that it's trying to read from, signaling the id of the hazard router. That information would propagate upstream to the router; whenever a processor receives the signal, it inspects which of its inputs are receiving data from the hazard router. If the input in question currently has data, then the signal stops there -> it means that some other stream is the slow poke. However, if the input does not have data, the signal is propagated on that input.
When (and if) the signal reaches the hazard router, the router would increase its buffer until data is produced for the output on which the signal came.

For example, we could start with output routers having no particular buffer, and then exponentially increasing the buffer every time a signal is received. A processor (or input sync) that's not able to read from an input and detects the condition stated above (that a router *r* contributes to that input but also to another input that's full), it sends a signal every millisecond or so.

Here's a diagram suggesting how it'd work:

![flow deadlock](https://user-images.githubusercontent.com/377201/34219578-a16c24f2-e57f-11e7-84f6-880ae336e98f.png)

Routers are circles; thick lines are channels that are full (and so backpressure happened). The dotted lines pointing upstream are the path of the signal. The downstream links are labeled with the ids of the routers that contribute to data flowing on the link.

So here *r1* is a router and its outputs are later joined by *n4*. The right output is full and so *n1* doesn't produce any more data. The left output is empty.
Now, we're *n4*. We're trying to read from the left input and we're getting no love. The routers contributing to that input are *r1, r2*. The right input has data, and the router contributing to it is *r1*. Thus, *r1* appears in both places - it's a deadlock hazard. So, *n4* propagates a signal asking *r1* to produce more data on its left input. *n3* receives the signal, looks at whether it itself is blocked (it is), looks at whether *r1* contributes to the input on which it is blocked (it does), and so it propagates the signal. *n2/r2* receive the signal, and runs the same steps. Note here that if *n2* would be blocked on its input from *n6*, this would be the end of the signal. But let's say it's not; let's say it's blocked on its input from *n1* (or both... I'm not sure yet what to do if it's blocked on both). So, it propagates the signal. Now *r1* receives the signal asking it to produce data on its first output. And so it increases its buffer according to the policy, but no less than what's required to produce at least a row of data on that output.

Does this sound like something?

**Comment by RaduBerinde** [comment]
@andreimatei At a high level, the solution you propose sounds correct. But I think there are a lot of non-trivial implementation details (eg how the signals travel downstream-to-upstream, how the router listens for the signal, how the joiner figures out that one of the other inputs has data).

Even if we implement something like this, we should implement fallback to disk when buffering because there can be cases where we still need to buffer a lot. Fallback to disk plus simple static determination of when we definitely don't need to buffer might go a long way.

**Comment by andreimatei** [comment]
Yeah... I agree that buffering to disk is needed in any case.
I'm not exactly jumping to actually implement something here, but I have a feeling that this is not the last we hear of this issue.

**Comment by vivekmenezes** [comment]
@mjibson my understand is that this is not longer a relevant issue worth fixing.

**Comment by jordanlewis** [comment]
@asubiotto added spill-to-disk in the routers, so this can be closed.
