### ISSUE TITLE
sql: incorrect handling of stars with zero-column data sources

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20830]
Check out what happens in the first query, when the RETURING keyword is missing:
```
root@:26257/t> select * from [insert into tt values (5)];
pq: cannot use "*" without a FROM clause
root@:26257/t> select * from [insert into tt values (5) returning x];
+---+
| x |
+---+
| 5 |
+---+
(1 row)
```

@knz, @jordanlewis would you mind routing this? Please pass it back if none of you can find it a home.

**Comment by knz** [comment]
Checked in `psql`: a FROM clause without any column is valid for `*`, whereas no FROM clause at all is invalid.

**Comment by jordanlewis** [comment]
I figured this bug was to fix the ambiguous-sounding error message! The behavior makes sense to me.

**Comment by knz** [comment]
No it's not correct. The `[input ...]` data source is a valid input for FROM, and a `*` on it should just select zero columns.

**Comment by knz** [comment]
I'll take it

**Comment by knz** [comment]
I have some code at https://github.com/knz/cockroach/tree/20171218-fix-from-error to address the problem properly -- the star expansion should simply expand to zero columns as soon as there is a FROM clause, regardless of the data source's number of columns.

That patch currently breaks however, because of how the "returning helper" works. 

The proper solution is IMHO to kill the weird returning helper once and for all and have a renderNode do the work for RETURNING. This is a larger patch however. Will followup in a bit.

**Comment by knz** [comment]
This has been fixed in the latest code.
