### ISSUE TITLE
Make configs aware of structured data layout

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2090]
Zone and accounting configs need to be aware of the structured data layout.
At the very least, we need table-level granularity for both.

**Comment by petermattis** [comment]
We need to redesign the configs. Prefix maps make a lot less sense when the objects the user sees are database, table and user. I'd like to see accounting automatically performed at the database, table and user levels and for zones to be configurable at those levels.

**Comment by spencerkimball** [comment]
:+1: I think zone configs listed by key prefix should be phased out and added instead to database and table descriptors.

I think accounting configs can be removed entirely because the database / table structure already properly delimits the key prefixes which we'd want to keep accounting information over.

The permission configs are actively being replaced by @MBerhault with the SQL privileges.

**Comment by MBerhault** [comment]
@thschroeter: fyi, this is purely about the location of the configs and their layout.
while they won't be in their current locations, but probably attached to the db/table descriptors (or similar), we'll still need to gossip them to avoid extra lookups everytime. Any work done on the gossiping part should be reasonably easy to adapt to other locations.

Still, there's a decent amount of thought to be put into this, so as of yet I have no idea what this will look like, just vague ideas. The first step of this will most likely be a quick RFC.

**Comment by thschroeter** [comment]
@MBerhault: thanks for the explanation.
