### ISSUE TITLE
sql: multi-use common table expressions

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21084]
Split from #7029 which was closed when we merged support for single-use common table expressions in #20359.

Support common table expressions whose clauses are used more than once in the statement. This may require temporary tables or other novel infrastructure, since each referenced statement should be run at most once in the case of DML statements, and in the case of read-only statements, should probably be run at most once anyway for efficiency.

For example,

```
WITH x AS (SELECT ... FROM table ...),
          y AS (SELECT ... FROM x ...)
SELECT ... FROM table2 JOIN x ON ...
```

In this statement, the `x` clause is referenced more than once, which is not currently supported.

**Comment by petermattis** [comment]
> Support common table expressions whose clauses are used more than once in the statement. This may require temporary tables or other novel infrastructure, since each referenced statement should be run at most once in the case of DML statements, and in the case of read-only statements, should probably be run at most once anyway for efficiency.

Note that the decision on whether to run a read-only statement once (and cache the results) or more than once is cost-based. Also, if a read-only statement is used more than once, it may be useful to "unnest" the statement in order to push-down filters or merge projections. I don't have examples on hand, but this is discussed in academic literature regarding optimizing CTEs.

**Comment by stevenross** [comment]
Would I be correct in saying this would allow the [introspection query used in Postgraphile](https://raw.githubusercontent.com/graphile/graphile-build/master/packages/graphile-build-pg/res/introspection-query.sql) to run on CockroachDB?

The expressiveness of GraphQL for API development has seen the Postgraphile project gain considerable traction. Being able to use it with a database such as CockroachDB for its cloud native features would be very compelling.

I understand that this alone may not allow Postgraphile to run. Maybe a seperate issue could be created and tracked within #25468?

**Comment by BramGruneir** [comment]
@stevenross I added PostGraphile to #25470.

**Comment by Bessonov** [comment]
I'm trying to get the total count of matched rows, but return only a subset of them for pagination, like described in: https://stackoverflow.com/a/28888696/926620 :

```SQL
WITH cte AS (
   SELECT *
   FROM   tbl
   WHERE  /* whatever */
   )
SELECT *
FROM  (
   TABLE  cte
   ORDER  BY col1
   LIMIT  ?
   OFFSET ?
   ) sub
RIGHT  JOIN (SELECT count(*) FROM cte) c(full_count) ON true;
```
but I get:
```
pq: unimplemented: unsupported multiple use of CTE clause "cte"
HINT: See: https://github.com/cockroachdb/cockroach/issues/21084
```

Is there any way to efficiently do that in CockroachDB?

BTW AFAIK `OFFSET` is very inefficient in Postgres. It's true for CockroachDB too? Colud it be avoided if instead of `OFFSET` something like ` WHERE id > ${lastId from previos page} ORDER BY id ASC LIMIT 10` is used?

**Comment by Bessonov** [comment]
@awoods187 thank you for your response! I was not able to build cockroachdb from sources. But now tested with 19.2 image and it does work as you stated!

Do you have any thoughts on `OFFSET` in last part of my question?

**Comment by awoods187** [comment]
We haven't yet written up docs but good information can be found here https://github.com/cockroachdb/docs/issues/3743
