### ISSUE TITLE
engine: error out when timestamp.WallTime < 0

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#21112]
https://github.com/cockroachdb/cockroach/pull/21070 found that we don't prohibit MVCC writes at negative timestamps. Such writes permanently corrupt the MVCC history and we should prohibit them.

Once that is done, `TestMVCCStatsRandomized` should be changed to allow negative timestamps (simply to have coverage for this error case).

**Comment by jmininger** [comment]
Hello @tschottdorf 
I have begun work on this issue. I have two questions I was hoping you might be able to help me out with: 

In addition to deleting the "documentation" test `TestMVCCStatsDocumentNegativeWrites()` and fixing `TestMVCCStatsRandomized()` to allow for negative timestamps, does it also make sense to add a unit test `TestMVCCPutNegativeTimestamp()` to add coverage? Or is the randomized testing coverage enough? (Perhaps because this is an issue that would only come up during testing?) 

Secondly, I am still making my way through the txn system, but am I correct in assuming that a negative timestamp for a key would likely mean that the entire txn needs to be aborted/restarted (because all timestamps from the same txn have to match)?

**Comment by tschottdorf** [comment]
Hi @jmininger, thanks for looking at this! I'd like to change my initial approach a little bit. I think it makes sense (as you suggested) to change `TestMVCCStatsDocumentNegativeWrites` and leave the randomized test alone. As for the actual changes, you'd just need to return an error from [mvccPutInternal](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/mvcc.go#L1154) and [mvccGetInternal](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/mvcc.go#L817). You shouldn't need to change anything else.

**Comment by jmininger** [comment]
Hi @tschottdorf , thank you for the suggestions. I have submitted an incomplete PR against my own fork (as suggested by first-pr.md), and have left some questions at the bottom. Your insight would be appreciated. Thank you

**Comment by palash25** [comment]
Hi @tbg I don't see any progress on the PR referenced. If the original assignee has stopped working on this issue I would like to take this up.
