### ISSUE TITLE
docs: clarify that LIMIT is probably meaningless unless ORDER BY also specified

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#21153]
In the subquery, if there is "order by" in there, the return looks correct, but if the subquery is not with the "order by", the answer of "5" looks weird to me.

```sql
create table inttest (value int primary key);
insert into inttest values (1),(2),(3),(4),(5);
select * from (select * from inttest limit 3);
```

correct output:
```
+-------+
| value |
+-------+
|     1 |
|     2 |
|     3 |
+-------+
```

```sql
select max(value) from (select * from inttest limit 3);
```

~Erroneous~ **surprising** output:
```
+------------+
| max(value) |
+------------+
|          5 |
+------------+
```

```sql 
select max(value) from (select * from inttest order by value limit 3);
```

Again correct output:
```
+------------+
| max(value) |
+------------+
|          3 |
+------------+
```

Thanks.

**Comment by knz** [comment]
cc @petermattis @RaduBerinde since we were discussing this recently

**Comment by knz** [comment]
Dear @leomkkwan 
Thanks for your interest in CockroachDB.

The behavior is surprising but it is entirely correct. In SQL, the order of results is non-deterministic unless an ORDER BY clause is present. That is, which rows are returned by LIMIT on a sub-clause can change every time unless you also specify ORDER BY on the same sub-close.

Arguably we may not be *documenting* this well.

**Comment by knz** [comment]
@leomkkwan I have created a docs issue to clarify what's going on: https://github.com/cockroachdb/docs/issues/2326

Also note that PostgreSQL has the same behavior, see e.g. https://www.postgresql.org/docs/10/static/queries-limit.html "When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. You might be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? The ordering is unknown, unless you specified ORDER BY."

Does this clarify your situation?

**Comment by leomkkwan** [comment]
@knz  Got you! Thank you very much! Coming from Mysql world is a lot of surprise and fun here; indeed.

**Comment by knz** [comment]
I will close this issue and leave the (separate) docs issue open for resolution.
