### ISSUE TITLE
sql: provide visibility into total transaction time

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21241]
The current SQL statement statistics track per-statement timings. But applications often care about the total transaction time which includes time spent on the network between the client and cockroach and in the application itself. We do not currently provide any per-transaction timings, though tracking that information does not seem difficult. For a given transaction we can track both the total time and the time Cockroach spent executing statements for a transaction. And then a bit of math:

```
total_transaction_time - statement_execution_time = application_time + network_time
```

The end goal is to provide insight to users as to both transaction time and where that time is being spent. There is integration with the UI that should also be considered. The statement statistics are currently not exposed on the UI. We should provide both visibility into slow queries as well as slow transactions.

**Comment by knz** [comment]
All right. Looking into this, it is indeed completely tractable to track the txn duration server-side. I can also readily add a couple columns to `node_statement_statistics` accordingly and then help documenting them (or "socializing" them). Further than that, I'm a bit fuzzy on how we'll recommend folk to use this -- is there some kind of design discussion ongoing already on the UX?

**Comment by petermattis** [comment]
There is no ongoing UX discussion, only this issue which seems as good a forum as any to have the discussion in.

**Comment by knz** [comment]
:+1: understood

**Comment by vilterp** [comment]
Related: #17353 (build a UI around `node_statement_statistics`).

**Comment by knz** [comment]
I just realize we already support the built-in function `transaction_timestamp()`. The formula `clock_timestamp() - transaction_timestamp()` gives the current transaction age to a running SQL client.

**Comment by knz** [comment]
@vilterp see my first attempt in #21351

**Comment by knz** [comment]
So the approach I'm using in #21351 is keying transaction stats per application_name and whether they are implicit or explicit.

It does not distinguish performance of transactions that execute different sequences of statements. Is that desired? I would like to know who are the stakeholders and what they would prefer here.

**Comment by knz** [comment]
cc @robert-s-lee @petermattis ^^

**Comment by petermattis** [comment]
I haven't put enough thought into what should be done here. Hopefully @robert-s-lee has.

**Comment by robert-s-lee** [comment]
if crdb_internal.node_txn_statistics and node_statement_statistics both reported the same set of columns, then we have good initial monitoring to work from.   

keying txn stat question. assume we have

`start; select 1;insert into xyz valules (1); commit;`
`start; insert into xyz valules (1); select 1; commit;`

is the output something like below?

select * crdb_internal.node_txn_statistics
cockroach `start; select 1;insert into xyz valules (1); commit;` 1 2 3 ...
cockroach `start; insert into xyz valules (1); select 1; commit;` 3 2 1 ...

select * crdb_internal.node_statement_statistics
cockroach `select 1` 1 2 3 ...
cockroach `insert into xyz valules (1)` 3 2 1 ...

**Comment by knz** [comment]
I am very confused right now. Or rather, I think you seriously under-estimated the amount of guidance you need to provide about the result you expect.

The title of this issue is "provide visibility into total transaction time". So the feature I implemented in #21351 does exactly this: measure the time from the start of a transaction to the end of a transaction.

The resulting data has the following columns: 
- **transaction type** (explicit/implicit), 
- **number of transactions**, 
- **average total transaction duration**, 
- **variance of the duration**.

The examples you mention suggest you are absolutely not interested in the total transaction latency, but rather something else entirely. Can you specify what you want? 

I *think* (reverse-engineering from your examples) that you want to compute the sum of per-statement individual phase latencies across all statements in a transaction (i.e. sum of latencies of all parse phases, sum of latencies of all execution phases, etc), and report all these sums as separate columns, per transaction. If that is the case, it is thus probably critical that the data is keyed by a sort of "transaction signature" so that txns running different statements have different buckets in the statistics. Is that correct? 

Please, spend more time explaining what is needed here. You can perhaps also provide several more examples.

**Comment by robert-s-lee** [comment]
In terms of steps, having a fingerprint of transactions such as below wold be very useful for workload visibility

- txn 1234 is composed of select ..., insert ..., delete ... 
- txn 1234 in total took 1 sec
- step 1 took .1
- step 2 tool .3
- step 4 took .1
- remainder is non database wait time

**Comment by vilterp** [comment]
I was thinking along these lines as well. Statements page could show
transactions at the top level, then expand or click through to see
individual statements.

Wrote up an example workflow in which I could have used this here:
https://docs.google.com/document/d/1BodHYxsT6Lw5LgpH6BjPbuzM2wFr3rwo0MvhQEFJBZA/edit#

**Comment by knz** [comment]
@piyush-singh putting this in your radar if not already there

**Comment by awoods187** [comment]
We landed https://github.com/cockroachdb/cockroach/pulls?page=2&q=is%3Apr+is%3Aclosed+author%3Ayuzefovich in 19.2 but it doesn't cover the full scope of this whole issue

**Comment by awoods187** [comment]
@solongordon I think we've fully addressed with the transactions page. Do you see anything missing?

**Comment by awoods187** [comment]
Ping on this @solongordon

**Comment by jordanlewis** [comment]
Feels done.
