### ISSUE TITLE
cli: Error when `cockroach zone` is running v2.0 and server is running v1.1.x

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#21323]
```
~/cockroach-2.0/cockroach-v2.0-alpha.20171218.darwin-10.9-amd64$ ./cockroach zone get .default --insecure
# Client version: CockroachDB CCL v2.0-alpha.20171218 (darwin amd64, built 2017/12/18 21:51:13, go1.9)
# Server version: CockroachDB CCL v1.1.3-71-gbb985e938 (darwin amd64, built 2018/01/08 17:53:13, go1.9)
# Cluster ID: cec887ed-f08a-474d-a626-aa8f1a9c3996
Error: pq: syntax error at or near "experimental"
Failed running "zone"
```

**Comment by jseldess** [comment]
@benesch, assigning to you at @knz's request. Please let me know if you need additional details.

**Comment by benesch** [comment]
Oh boy. I think we might need to live with this incompatibility. The logic for updating zones lives has moved to the server in 2.0, and that logic simply doesn't exist in 1.1.

At any rate, we can certainly make the error message better.

@bdarnell do you have thoughts here? The crux of the problem is that the zone CLI is now a simple wrapper around `ALTER ... EXPERIMENTAL CONFIGURE ZONE`, which doesn't exist in 1.1.

**Comment by bdarnell** [comment]
In general, our policy is that new clients should remain compatible with older servers, so ideally we'd retain the old behavior for use with older servers. How hard would it be to put the old code back in with a version check?

**Comment by benesch** [comment]
Doable, but far from trivial. The entire CLI command was basically rewritten: https://github.com/cockroachdb/cockroach/commit/f98fbcbfd8058c214b4d0457753bf7586204a980#diff-48081c5dadf8b43990a58593cc8b4754

If we do put the old code back, how many versions back do we need to support? It's certainly not the kind of thing we want to maintain long-term. The big benefit of making these client-side commands dumb wrappers around SQL statements is that we can largely sidestep these version incompatibilities in the future, since the server handles all the logic.

Now that I look at it, I believe `cockroach user` is broken in the same way because `CREATE USER IF NOT EXISTS` doesn't work in Cockroach v1.1. Paging @knz.

**Comment by bdarnell** [comment]
> how many versions back do we need to support?

Ideally our latest client would support full functionality on any server that was still supported when it was released (so two versions back in our current policy). This isn't strictly required by our support policy, but the alternative (users sometimes need to install multiple versions of the client and switch between them depending on which server they're using) is really messy. 

I think that given our current usage (and in particular the usage of the zone config feature) we can get away with some compatibility breaks here, but we need to get into the habit of ensuring that we make these changes in a backwards-compatible way.

**Comment by knz** [comment]
Maybe we should migrating as much logic as possible from the CLI utilities server-side. So that e.g. `cockroach zone` regardless of version delegates the work to do to the server and merely gets the console output as a tcp stream from the server.

**Comment by knz** [comment]
We could probably even perform this change in v1.1 retroactively.
