### ISSUE TITLE
sql: audit errors and use pgerror everywhere.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#21350]
At first glance, we return a lot of non-pgerror errors:
```
$ grep errors\.Errorf *.go|wc -l
203
```

(some of them may be properly wrapped, I have not checked).

I'll start by auditing user/role/privilege code paths since I'm familiar with those.

In the long term, we may want to find a way to catch non-pgerror returns.

**Comment by jordanlewis** [comment]
I thought we already had linting for this, somewhere. @justinj probably remembers more.

**Comment by justinj** [comment]
We do, although I guess it got partially lost when we split everything up into a bunch of packages since it specifically refers to the `parser` package.

It lives [here](https://github.com/cockroachdb/cockroach/blob/b5338ac5730fe523c653d2f33c190371cef0061a/pkg/testutils/lint/lint_test.go#L355), we'll need to add it to whatever packages we currently have that correctly use pgerror.
