### ISSUE TITLE
sql: Expose a way to manually transfer a range lease

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#21420]
Since we don't currently balance leaseholders based on the load on each node (https://github.com/cockroachdb/cockroach/issues/21419), it can be possible for all the hot ranges in a cluster to end up with their leaseholder on the same node. This is made worse by the fact that [scatter doesn't work as it used to](https://github.com/cockroachdb/cockroach/issues/17341). If we reworked scatter to spread leases around even if the cluster is already balanced, this would perhaps be less necessary. Doing this would fix, https://github.com/cockroachdb/cockroach/issues/21399, though.

The inherent problem with this kind of mechanism is that it may end up fighting against the replicate queue -- the admin may move a lease, just to have the replicate queue move it right back.

**Comment by nvanbenschoten** [comment]
This may deserve a separate issue, but I've recently been reminded of a longterm desire of mine to expose some mechanism to manually "pin" certain leases to certain nodes (or localities, or whatever else this would allow this to play nicely with zone configs). Doing so would not only attempt to manually transfer the lease but would also give the lease a degree of affinity to a certain node such that specified ranges would do their best to retain their leases on that node whenever possible. 

Functionality like this fits into a more broad trend of giving operators manual overrides into our "intelligent" processes in order to improve predictability when desired.

**Comment by a-robinson** [comment]
Yeah, and you aren't the first person to ask for that either - https://github.com/cockroachdb/cockroach/issues/17119
