### ISSUE TITLE
sql/sem/tree: investigate reducing allocations during expression evaluation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21424]
Scalar expression evaluation is currently allocation heavy because we treat the input `Datums` to every `tree.Expr` as immutable. So an expression like `a + 1` needs to allocate a datum for the result of the addition. Assuming `a` is an integer column type, that expression hits this code:

```
		BinOp{
			LeftType:   types.Int,
			RightType:  types.Int,
			ReturnType: types.Int,
			fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
				a, b := MustBeDInt(left), MustBeDInt(right)
				r, ok := AddWithOverflow(int64(a), int64(b))
				if !ok {
					return nil, errIntOutOfRange
				}
				return NewDInt(DInt(r)), nil
			},
		},
```

For a given overload, the type of the return datum is known. Before evaluating an expression for the first time, we could walk over the expression and assign each node which needs to generate a new datum a "slot" in some structure in `EvalContext`. During execution, we would pass the slot (or slots) to the the evaluation function and it could grab the datum from `EvalContext` rather than allocating it.

**Comment by knz** [comment]
Note that a preliminary investigation of this item was made here: https://github.com/cockroachdb/cockroach/pull/16686

With code experiments by myself and peter.

**Comment by knz** [comment]
@jordanlewis Vivek is suggesting that I also contribute to this item. I'd be happy to help! In my view this is work that benefits from 2+ people working closely together.

**Comment by jordanlewis** [comment]
In my opinion, this item could be independent of a complete (or even partial) query compilation project. I think we would do well to investigate whether this is possible using the technique that Peter alluded to in the description of the issue.

If we could demonstrate that removing these allocations alone would have a large benefit to SQL execution, there's an argument to be made for implementing this simplified suggestion without going down the full query compilation route.

**Comment by solongordon** [comment]
After doing some profiling here I'm somewhat unconvinced that we would see a big benefit from implementing this change. For queries like `SELECT COUNT(*) FROM table WHERE col1 + 1 = col2`, we allocate one int per row, which is a large number of allocations but a small fraction of the total space allocated during execution. (In a test query on a TPC-H table it was 70% of the allocated objects but 5% of the space.) `buildScanResults` and `decodeUntaggedDatum` dominate.

The exception was when I tried joins with scalar expressions in the ON condition, e.g. `SELECT COUNT(*) FROM t1 JOIN t2 ON t1.col + 1 = t2.col`. In that case there are so many allocations that it approached 50% of the allocated space in my test queries. However, this seems to be mainly an issue of hitting an unoptimized `HashJoiner` path. The join is O(nm) due to all rows ending up in the same hash bucket (as explained by @RaduBerinde), and furthermore it looks like the scalar expression is evaluated n*m times. If we address this inefficiency to make the join O(n+m), the allocation picture should look more like the previous case I described. (And these joins would not be as painfully slow as they are today.)

My only other thought is that we could see bigger benefits for operations with larger return types, like string concatenation or JSON operations. But I'm not sure those are typical enough to warrant optimization right now.

**Comment by jordanlewis** [comment]
I agree with the outcome of your analysis, although I hope that one day we can eliminate the large source of other allocations in your test (copying from C++ to Go, and creating KeyValue slices - I think those show up in the profile as `copyFromSliceVector` and `buildScanResults`) - and at that point these per-row allocations would become more prominent.

Can you think of any other ways to evaluate this idea besides `pprof`? Perhaps the number of allocations is low, but it still hurts performance to do them.

One comes to mind for me, and there are probably more:

1. Change the implementation of Int+Int to return one if its input datums instead of allocating a new one
2. Compare the throughput of a query like that `COUNT(*)` before and after this change

**Comment by solongordon** [comment]
Yeah, I tried what you described and didn't see any difference in the query latency. But I guess the performance improvement we're looking for would be due to fewer/shorter GCs, so I can try running one of these queries repeatedly over a longer interval and see if I notice any throughput difference.

**Comment by petermattis** [comment]
@solongordon You're distinguishing between allocated objects and allocated space, but I'm curious why you think allocated space is more important. In my experience, reducing the number of allocated objects is more important because GC overhead is related to the number of allocated objects, not the amount of allocated space.

Can you benchmark `SELECT COUNT(*) FROM table WHERE col1 + 1 = col2` vs `SELECT COUNT(*) FROM table WHERE col1 = col2` on a table where both will return the same number of rows? The `col1 + 1 = col2` query should allocate a lot more objects than the latter and give us a sense if eliminating those allocations is a performance win. This isn't quite an apples-to-apples comparison, but the overhead of the `+` should be minimal other than the allocation.

**Comment by bdarnell** [comment]
The size of allocated objects does matter somewhat for Go's GC. The frequency of GC is based on the total number of bytes allocated. The cost of each GC is based more on the number of live objects and pointers. Overall the number of objects tends to matter more than the number of bytes.

**Comment by solongordon** [comment]
I tried running the `SELECT COUNT(*) FROM table WHERE col1 + 1 = col2` query repeatedly against a single local node for 5 minutes with 8 workload threads, with and without the optimization. The throughput/latency results were basically indistinguishable.
```
# without optimization
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  300.0s        0           4163           13.9    576.2    570.4    805.3    939.5   1208.0

# with optimization
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  300.0s        0           4147           13.8    578.7    570.4    805.3    973.1   1342.2
```
The GC Runs and Pause TIme graphs in Admin UI look comparable as well. (Is there a better way of comparing GC stats?)

**Comment by solongordon** [comment]
Yes, according to `pprof` there's a 75%+ reduction in allocated objects. Here's the `top` output from running a 1 minute workload before and after the optimization. (`tree.glob..func16` is the integer addition `BinOp`.)
```
before:
$ go tool pprof -alloc_objects ./cockroach http://localhost:8080/debug/pprof/heap?debug=1
(pprof) top
Showing nodes accounting for 88496511, 97.25% of 90995465 total
Dropped 570 nodes (cum <= 454977)
Showing top 10 nodes out of 51
      flat  flat%   sum%        cum   cum%
  70419506 77.39% 77.39%   70419506 77.39%  github.com/cockroachdb/cockroach/pkg/sql/sem/tree.glob..func16
  17713266 19.47% 96.85%   17713266 19.47%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.decodeUntaggedDatum
     69635 0.077% 96.93%     585262  0.64%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*Descriptor).Unmarshal
...

after:
$ go tool pprof -alloc_objects ./cockroach http://localhost:8080/debug/pprof/heap?debug=1
(pprof) top
Showing nodes accounting for 18955144, 88.48% of 21422048 total
Dropped 547 nodes (cum <= 107110)
Showing top 10 nodes out of 103
      flat  flat%   sum%        cum   cum%
  18045082 84.24% 84.24%   18045082 84.24%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.decodeUntaggedDatum
    180225  0.84% 85.08%     180225  0.84%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*IndexDescriptor).Unmarshal
...
```

**Comment by petermattis** [comment]
I am shocked that a 75% reduction in allocated objects did not lead to any performance benefit. Shocked!

**Comment by solongordon** [comment]
One thing to note is that based on the `gctrace` output (thanks for the tip), GC pressure was low in the first place for this workload: less than 1% of CPU time. So it doesn't seem like there was much performance to be gained from relieving it. However, I also compared the total GC CPU time before and after the optimization and it was virtually the same. Based on that, it seems like you need a much bigger allocations reduction to see an improvement, and/or there are other GC scaling factors I'm not exercising here (heap size?).

**Comment by jordanlewis** [comment]
This investigation feels closed. Let's make sure to capture its results in our performance work this milestone, but I don't think there's anything else to do on this for now, do you @solongordon?

**Comment by solongordon** [comment]
Agreed.
