### ISSUE TITLE
config: single-node cluster shows all ranges as under-replicated

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21429]
I assume this topic has a longer history than I'm aware of. Mainly opening to discuss.

At the moment, a single-node cluster is initialized with a zone-config that defaults to 3-way replication. As a result of this, we mark all ranges in the cluster as "under-replicated". 

<img width="1169" alt="screen shot 2018-01-12 at 6 06 57 pm" src="https://user-images.githubusercontent.com/5438456/34898897-7183a3a4-f7c3-11e7-8acb-6298da04886a.png">

We also log various messages that call this out, like:
```
E180110 04:34:11.439278 415 storage/queue.go:738  [n1,replicate] 221 replicas failing with "0 of 0 stores with all attributes matching []; likely not enough nodes in cluster"
```

A user can modify the zone-configs to specify a replication factor of 1, which should avoid this issue, but that it's the easiest thing to do. Is this the experience we want to require of users who want just a single-node cluster? I think a strong argument can be made for "yes", because we want to make sure any misconfigurations that prevent up-replication are called out when a multi-node cluster is desired.

**Comment by bdarnell** [comment]
Historically, we thought a once-every-ten-minutes log message was reasonable for this, but that was before "under-replicated ranges" was displayed so prominently in the UI.

I've been in favor of treating single-node clusters as more distinct from multi-node clusters. For example, we could have a `cockroach start-single-node` command that would set the target replication factor to 1, and maybe also give other parameters different defaults (`--host=localhost`, for example). Then we could make `--join` and the `init` command mandatory for the multi-node case. Then instead of extra steps in our "start a single-node cluster" docs, we'd have a page on "upgrading a single-node cluster to multi-node" that would have you set `num_replicas` back.

**Comment by bdarnell** [comment]
This was fixed a while back as a part of adaptive zone configs.
