### ISSUE TITLE
Batches should not be `proto.Request`s

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2143]
with our push to batch as much as possible, we should consider moving away from having `RequestHeader` on `BatchRequest` and all individual requests.
We wanted to refactor those headers anyways, and now might be a good way to fix a goal since we've got to deal with them in the refactors a lot (having duplicated header information between a batch and its requests is error-prone). See #2141 and the issues linked within.

Here's a rough suggestion what that might look like. Notably timestamp handling has changed a lot and I'd like some feedback from the point of view of the command execution path.
The need for a Timestamp on an individual request may not be necessary, but there are a lot of places in which timestamps increase, and I suspect we'll require the individual ones since technically, the operations still happen one after another. But I haven't thought this through completely.

```go
// RequestHeader is part of each individual request.
type RequestHeader struct {
	// Starts out empty, but may be increased with retries at the Store.
	// If empty, timestamp taken from batch.Txn (if any), otherwise chosen
	// at Store.ExecuteCmd.
	// Reading at past timestamp still possible with read-only Txn at the
	// desired timestamp. Inconsistent reads at past timestamp are not, though.
	// We can have RequestWithTimestamp on the Batch to avoid leaking this to
	// the user.
	IntTimestamp Timestamp
	Key, EndKey  Key
}

// IntBatchHeader is the part of the header which is only used internally.
// Note that there isn't a Key or EndKey. Batches will be split along range
// boundaries, but but the Requests within contain all the information already.
type IntBatchHeader struct {
	// Replica specifies the destination for the request. This is a specific
	// instance of the available replicas belonging to RangeID.
	Replica Replica
	// RangeID specifies the ID of the Raft consensus group which the key
	// range belongs to. This is used by the receiving node to route the
	// request to the correct range.
	RangeID RangeID
	// CmdID is optionally specified for request idempotence
	// (i.e. replay protection).
	// This is the internal variant: For batches which we split up, we'll
	// have to create own ones deterministically from the one supplied by
	// the client and populate this field. For batches which aren't split,
	// of course, this is going to be identical to the client's.
	CmdID ClientCmdID
}

// ExtBatchHeader is the externally visible header (i.e. to the Client).
type ExtBatchHeader struct {
	*IntBatchHeader // enforce `nil` at suitable boundary to outside world
	// Type is the type of batch sent. Defaulting to Auto, it can only be set
	// for a non-transactional request which contains only read operations,
	// in which case those reads can be carried out for any replica.
	Type BatchType // Auto, Inconsistent (internally: ReadOnly, WriteOnly, ReadInconsistentOnly)
	// Reverse is optionally specified to indicate that range operations in
	// this batch use reverse semantics.
	Reverse bool
	// As before
	CmdID        ClientCmdID
	User         string
	UserPriority *int32
	Txn          *Transaction
}
```

**Comment by bdarnell** [comment]
+1 on the idea; here are a bunch of notes on the details.

I'd really like to get rid of the per-request timestamp if we can. I'm not entirely clear on where it is used - Store-level retries would only see batches, right? (the batches aren't broken apart until the replica runs them, post-raft)

The comment on `BatchType` suggests that it takes on different values internally than externally, but we reuse the same field. For `CmdID`, we use different fields when it is changed internally. I feel like both of these things are backwards. We should just modify each sub-batch's CmdID rather than create a similar field that just invites us to use the wrong one. For `BatchType`, if the set of available values is different, we should have separate external and internal fields.

How exactly are batch types determined? Is a read from one range and a write to another considered a read-only batch and a write-only batch, or do both sub-batches inherit the parent batch's mixed status? If the former, the internal batch status seems redundant since the recipient can simply recompute it from the contents of the batch. 

The `Reverse` header field doesn't seem to correspond to anything that exists now. It seems like it belongs on the per-request header along with the keys; we shouldn't require that all requests in a batch share the same direction.

We've been moving away from internal/external naming since the entire KV api is becoming internal. It might be nice to use more semantic names: `KeyHeader` contains `Key, EndKey, Reverse`, `RoutingHeader` contains `Replica` and `RangeID`, `ExecutionHeader` contains txn, priority, cmdID, etc. And a batch should probably contain several types of headers as top-level fields, instead of containing one header which contains another.

**Comment by tschottdorf** [comment]
> I'd really like to get rid of the per-request timestamp if we can.

We might be able to. Off the top of their head @spencerkimball might have a better idea. Otherwise we'll have to sift through the code. I was thinking that when you group a bunch of writes, then the timestamp of each among retries would depend on the key. We can ratched everyone forward at the same pace though, if there aren't any unintended side effects. I'm hoping we can do that.

> How exactly are batch types determined?
 
I personally would hope to avoid BatchType altogether, but the discussions in #2052 indicated that we're headed in a direction which mandates that batches at the `Store` level are "pure": Only reads (maybe mixing inconsistent reads in is OK) or only writes (i.e. Raft vs non-Raft). So from the "public" header, we can either remove the type but add an `INCONSISTENT` flag, or we keep it as is. There needs to be some way to go inconsistent, but unfortunately it'll always be at (possible) odds with other options you could specify in the header.
Internally, due to the above restriction, we're going to have to cut batches into Raft vs non-Raft.
Given your concerns, probably better to stay with the flag and only use an internal `BatchType` (which could be `Raft`, `Leader` or `Inconsistent`) only.

> We should just modify each sub-batch's CmdID rather than create a similar field that just invites us to use the wrong one. For BatchType, if the set of available values is different, we should have separate external and internal fields.

ack.

We'll also have to cut batches internally into Reverse vs non-Reverse (since that affects which replica we're sending to first in the case of multi-range). That's where the `Reverse` flag comes from. Since any Range operation has a `Reverse` equivalent (and they might be useful, a reverse `DeleteRange` for example is certainly useful for certain SQL deletes (DELETE FROM ... LIMIT 50) when the index goes the other direction) and conceptually simpler. But this again could be done internally, so that clients have `ReverseX` exposed for any range command `X` and internally it goes into a reverse batch containing `X`.

> We've been moving away from internal/external naming since the entire KV api is becoming internal.
Sounds good, I'm going to update the above with your suggestions and post a link here.

**Comment by tschottdorf** [comment]
> Given your concerns, probably better to stay with the flag and only use an internal BatchType (which could be Raft, Leader or Inconsistent) only.

though here eventually we'll have a conflict if we implement `CONSENSUS` reads (which would force everything through Raft anyways).

If that level is something we still want (i.e. if we want it for anything internally) we should factor that into our replica-batch decision, because it means we'll definitely need to be able to route reads through `Raft`, which renders work to avoid it now moot.

**Comment by tschottdorf** [comment]
see #2155 for the updated example.

**Comment by tschottdorf** [comment]
this is done, request headers have been thoroughly scrubbed (#2730, #2742) . We could clean up the response header, but there's barely any confusion on how those fields are used so I'm not going to pursue it further for now.
