### ISSUE TITLE
sql: investigate alternatives to EncDatum/EncDatumRow

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21523]
In DistSQL, rows move between processors as `EncDatumRow` (which is a `[]EncDatum`). An `EncDatum` contains either a `[]byte` of the encoded datum or a `Datum` (and sometimes it contains both). This flexibility of representation means that higher level processors are not concerned with the format of the datum, but it pushes type compatibility checks down into the lowest levels of our code. Additionally, there is space overhead for this flexibility. Consider:
* `sizeof(Dint) == 8`
* `sizeof(Datum) == 16`
* `sizeof(EncDatum) == 48`
* `sizeof(EncDatumRow) == 24`

So in order to pass an 8-byte column from one processor to another, we wrap that 8 bytes in 88 bytes of abstraction. Note that we're not actually allocating or copying that much memory, but the number is still illustrative. Another illustrative bit of info are the following benchmark numbers:

```
name                       time/op
DIntIsSorted-8              336ns ± 1%
DatumIsSorted-8            1.02µs ± 2%
EncDatumDecodedIsSorted-8  1.71µs ± 2%
EncDatumEncodedIsSorted-8  1.12µs ± 2%
EncDatumRowIsSorted-8      2.14µs ± 2%
```

The benchmarks are comparing how long it takes to run `sort.IsSorted` on a sorted slice of various values. The `Datum` variants are using the `.Compare()` methods. For the comparisons, JIT-ing comes to mind and would likely give a significant win. This issue is not about JIT-ing, but about improving our representation of rows/datums.

Rather than pass around `[]EncDatum`, we could pack datums into a `[]byte` and use `unsafe` when we need to access the datum as a `Datum`. We'd want to align primitive datums so that they can be retrieved efficiently. We'd need to include offsets for variable length datums. We'd need to include a bitmap of NULL values. This all starts to feel similar to a PAX-like layout, but at the single row-level. This idea is only half-formed right now and may not pan out.

Cc @arjunravinarayan, @RaduBerinde

**Comment by asubiotto** [comment]
I think there are two main points to tackle:
1) We have redundant information in the `EncDatum` with the `encoding` field.
2) We sometimes use `encoded`, sometimes `Datum`.

Some ideas:
1) Remove the `encoding` field and somehow pass that around as metadata before rows that follow the same encoding. Local processors can be initialized with this information just like this information is currently passed remotely to a `StreamDecoder` through a `DatumInfo`.
2) Since the idea behind having `encoded` and `Datum` was to only decode when necessary, we could always send around a `[]byte` with the encoded bytes with an optional  datum representation (based on your suggestion) and whenever a processor needs to decode anything, it would populate this mirror datum slice with the decoding and pass it around as well. This whole process would start again once a remote barrier is crossed. Whenever the order of the Datums change we would need to find a way to do the same with the encoded bytes. However, there could be cases where lacking datums, we could reencode the encoded bytes if necessary to facilitate sorting (similar to what the `hashDiskRowContainer` does) and potentially avoid fully decoding rows.

I've done experiments with 1) by removing `encoding` from `EncDatum` and modifying `BenchmarkCount` to run a sort on an additional `INT` field:
```
name               old time/op    new time/op    delta
Count/Cockroach-8     179ms ± 7%     176ms ± 3%    ~     (p=0.113 n=10+9)

name               old alloc/op   new alloc/op   delta
Count/Cockroach-8    34.8MB ± 1%    31.9MB ± 0%  -8.54%  (p=0.000 n=10+9)

name               old allocs/op  new allocs/op  delta
Count/Cockroach-8      252k ±10%      228k ± 0%    ~     (p=0.499 n=10+8)
```

Which gives us an allocation benefit but no performance benefit. We could look into 2) but I haven't validated this approach. What do you think?

cc @jordanlewis

**Comment by petermattis** [comment]
There is also the abstraction overhead of `Datum`. Notice how 8-bytes of `DInt` becomes 24 bytes when we wrap it in a `Datum`. We suffer from the space overhead and from the memory indirection. I don't have a concrete proposal yet, but for the fixed datum types, it would be great if we could pass them by value. This ties into columnarization, but I think it is also separate.

**Comment by jordanlewis** [comment]
@asubiotto could you make a PR out of the new benchmark you added? That sounds like a pretty good one to keep around.

**Comment by RaduBerinde** [comment]
I think that small fixed-size datums (8 bytes) should always be stored decoded inside a `[]byte` and a `Datum` handle can be created on-demand.

For the large datums, the first important thing would be to evaluate how useful the functionality to avoid unnecessary encode/decode really is. Is the extra overhead of EncDatum outweighed by the benefit or not? One important case to evaluate this is a TableReader that sends data to another node - EncDatum allows us to send out what we read from KV directly. It would be good to have an idea of what is the perf difference if we always decode the Datum and re-encode.

Even if we want to keep the EncDatum functionality for large datums, we can be more efficient. We could store just a pointer instead of the `encoded` slice and use unsafe to create a slice when we need it (we don't need the length to decode).

This applies to single rows as well as batches. Batches allow the extra possibility of consolidating information across a column. For example, we can decide for the entire column if we are going to represent it as an encoding or as a Datum. We could also store the type of that Datum once per column and just store an `unsafe.Pointer` for each value, and create a Datum handle as necessary.

**Comment by petermattis** [comment]
FYI, I'm experimenting with some ideas similar to what @RaduBerinde mentions. We can have something like:

```
type Row struct {
	data  unsafe.Pointer
	ptrs  unsafe.Pointer
}
```

Fixed sized datums like `DBool`, `DInt`, and `DFloat` would be packed into `Row.data`. Variable size datums or ones which contain pointer data would be stored in `Row.ptrs` which is an array of pointers. Accessor methods would exist to get the typed value at a particular column index. It would be up to the caller to remember the types (though we could have safety checks in race builds). 

The beginning of the `Row.data` would contain a number of columns "offsets" which point into either `Row.data` or `Row.ptrs`. For a single row containing a `DInt`, we'd be using 16 bytes for the `Row` itself, plus 16 bytes for `Row.data` (2 bytes for the offset + 8 bytes for the integer + 6 bytes for alignment), for a total of 32 bytes. This compares to 96 bytes for the current `Datum/EncDatum/EncDatumRow` approach.

On my TODO list for experimentation here is to extend the above to a `RowBatch` because we can get extra space savings by packing multiple columns more tightly. This would be a columnarized layout. For example, if a row contains a bool we'd pack those bool columns together and avoid unnecessary padding. All this seems to be feasible so far, though there would be a huge lift retrofitting this into the system.

**Comment by jordanlewis** [comment]
Our work in `pkg/sql/exec` subsumes this.
