### ISSUE TITLE
ui: Ability to graph arbitrary timeseries metrics

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#21531]
There are times that it would be really nice to be able to graph one of the many timeseries metrics stored in cockroach but that isn't on any of the standard admin UI dashboards. This is what I miss most when running a roachprod cluster compared to the old prometheus/graphana setup for prod clusters.

It looks like this was mentioned by Pete in the last admin UI meeting notes, and I know I would have appreciated  it when looking into https://github.com/cockroachdb/cockroach/issues/21528. It's really tough to get a historical sense of a metric that we don't include in the admin UI by default, which kind of makes it a waste to even store them, but it'd be unreasonable to include all of our metrics (unless we put them on hard-to-discover debug pages).

**Comment by vilterp** [comment]
Yeah, I think @petermattis, @couchand and I would all like this to be a thing. Unfortunately it's a sizable refactor, since (a) the metrics are currently hardcoded in JSX, and (b) that JSX contains some info that's not present in the raw metric definitions on the Go side.

Anyway, the steps to do this are something like:
- Expose an endpoint that gives a "metrics manifest" (like `/_status/vars` but without the values, and in proto format), which would be loaded by the frontend at startup so it knows what metrics are available.
- Move chart config out of JSX, into a JSON object that can (a) live in the redux store and be edited at runtime, and (b) potentially be persisted to a system table (or at least saved to localStorage or pasted in and out)
- Figure out where extra metadata (axis labels, etc) lives. Does it exist just for the curated charts? Can you add it to arbitrary charts, in a little text box? etc

**Comment by a-robinson** [comment]
Thanks for the details, it helps to know how hard this would be. Since it's presumably quite out of scope to do anything like this for 2.0, I may try hard-coding a few more "hidden" debug dashboards along the lines of our hidden raft dashboard.

**Comment by vilterp** [comment]
Yeah, definitely out of scope for 2.0. Hopefully we can do it in 2.1.

**Comment by couchand** [comment]
closed by #23070
