### ISSUE TITLE
sql: typing of null arrays seems off

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#21590]
Not sure what's going on here, but it doesn't seem right.

```
root@:26257/firehose> select array[NULL]::string[];
pq: invalid cast: NULL[] -> STRING[]
root@:26257/firehose> select nullif(array_agg(a), '{NULL}'::string[]) from foo;
pq: NULLIF("$0", ARRAY[NULL]): incompatible NULLIF expressions: expected ARRAY[NULL] to be of type string[], found type NULL[]
```

Postgres:

```
benesch=# select array[NULL]::text[];
 array  
--------
 {NULL}
(1 row)

benesch=# select nullif(array_agg(a), '{NULL}') from foo;
 nullif 
--------
 
(1 row)

benesch=# select nullif(array_agg(a), '{NULL}'::text[]) from foo;
 nullif 
--------
 
(1 row)
```

**Comment by abhimadan** [comment]
Looking through `type_check.go`, this might just be a casting problem with arrays in general.

Testing with Cockroach, this also doesn't work:
```
root@:26257/> select array['hi']::name[];
pq: invalid cast: string[] -> NAME[]
```

Postgres for comparison:
```
test=# select array['hi']::name[];
 array
-------
 {hi}
(1 row)
```

**Comment by abhimadan** [comment]
I traced the issue to this piece of code in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/eval.go#L2817-L2820:
```go
...
case *DArray:
  if (*v).ParamTyp == coltypes.CastTargetToDatumType((*typ).ParamType) {
    return d, nil
  }
...
```

Basically, when casting from one array type to another array type, we only handle the case where the array's param type is equal to the cast's param type (i.e., a no-op cast). We probably want to extend this so that array casts work when the corresponding scalar cast with the param types works.

**Comment by benesch** [comment]
Oooh, nice!
