### ISSUE TITLE
ts: implement timeseries rollup

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21601]
Implement timeseries rollup as described in https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160901_time_series_culling.md

**Comment by mrtracy** [comment]
I've been working on this a lot in the background, so a brief overview of what I've been doing and what I plan to do:

+ I am re-writing the test model used throughout the time series tests. The current test model re-uses too much code from the real system, and is also too closely tied to the 10 second resolution. Instead, I am writing an in-memory model which sacrifices some memory and computational efficiency in exchange for a much simpler and easier-to-understand model. The results from this model will be used to verify complicated results from the real system, which will be using numerous optimizations.
+ After the test model, I will be refactoring many of the internal interfaces of the time series system (not the external API) in order to better support roll-ups, and in general to pay down some technical debt. There are functions with more than ten parameters in the current code, it's become difficult to test as a result.
+ I will be changing the on-disk protocol buffer format for time series in a backward-compatible way. The new model will be columnar and should provide significant on-disk savings (better encoded size) along with better data locality when loaded into memory.
+ I will be adding first-class support for resolutions other than ten seconds. Current thinking is that there will be a 1-hour resolution, but this support should be general for a reasonable number of resolutions in the case that many are desired. This will include support for both storage of low-resolution *rollup* data and querying across multiple resolutions in a single query.
+ Finally, we will begin rolling up ten-second resolution data into a much lower resolution after a pre-configured boundary.  This will replace the current culling system. It is unclear a this time if we will retain the eventual culling of low-resolution data, as it represents a much smaller amount of data.

**Comment by petermattis** [comment]
The plan sounds good.

 > I will be changing the on-disk protocol buffer format for time series in a backward-compatible way. The new model will be columnar and should provide significant on-disk savings (better encoded size) along with better data locality when loaded into memory.

I'm curious to know more details about this.

**Comment by mrtracy** [comment]
Sure, let me describe the proposed format.  The current format looks something like this (using pseudo-proto code):

```proto
// Structure containing a slab of data samples at regular intervals.
message TimeSeriesDataSlab {
  int64 start_timestamp_nanos = 1;
  int64 sample_duration_nanos = 2;
  repeated TimeSeriesDataSample samples = 3;
}

// Structure representing a single data period. Notice how it is equipped to contain roll-up data as well with the max and min field.
message TimeSeriesDataSample {
  int32 offset = 1;
  double sum = 2;
  uint32 count = 3;
  optional double max = 4;
  optional double min = 5;
}
```

Notice the clear row orientation: a slab of data contains multiple samples, and each sample contains several fields - the offset, along with several values. We use multiple values to store pre-computed aggregates at low resolutions (e.g. one sample per hour) based on the original high-resolution samples  - for example, the min and max value over the period.

However, this has several disadvantages if we want to add more aggregates:

1. At low resolutions we are using all of the fields in each sample, but at original high resolutions (e.g. sample every ten seconds) we are not storing aggregates because there is only one data point per sample. However, these unused aggregates still take up struct space (in the form of nil pointers) when we load these into memory.  For every aggregate we add, we add one more nil pointer per sample.
2. This structure does not pack very efficiently when encoded, because each sample needs to encode the field number for every field it contains.  With a different layout, we could take better advantage of packed repeated fields.
3. When querying over aggregates, a single query is typically interested in only one aggregate; however, this row-based structure forces us to iterate over the space for all aggregates, which reduces data locality.

So, the proposed new structure is a columnar layout:

```proto
// Structure containing a slab of data samples at regular intervals.
message TimeSeriesDataSlab {
  int64 start_timestamp_nanos = 1;
  int64 sample_duration_nanos = 2;
  repeated int32 offset = 4;
  repeated int32 count = 5;
  repeated float64 sum = 6;
  repeated float64 max = 7;
  repeated float64 min = 8;
  repeated float64 variance = 9;
  repeated float64 first = 10;
  repeated float64 last = 11;

  // Backwards compatibility
  repeated TimeSeriesDataSample samples = 3;
}
```

This has a columnar layout, made up of parallel arrays. This gives us all of the advantages we were missing in the previous layout:

+ High-resolution data can leave the aggregate fields completely empty; we'll likely just store the "last" aggregate field, which matches what we currently do.  This will reduce the in-memory size of each sample from the full Sample structure down to an int32 and a float64.  This also means we can add several more aggregates without inflating the size of each sample.
+ This takes full advantage of repeated field packing, which should save considerable space for the encoded on-disk format.
+ When querying, we can iterate directly over the data fields we need, which should considerably improve data locality (and thus cache-miss performance).

We retain the old samples in the message for backwards compatibility; we will not be storing these samples anymore, but the query system will be able to read from it in order to handle data recorded before the swap-over.

**Comment by petermattis** [comment]
Thanks for the write-up. 

I'm a little worried about the backward compatibility story. When will you convert from one format to the other? I believe all of the replicas have to have the same format in order to not violate the consistency checker. I'm sure this is a solvable problem and perhaps you've already thought through it. Perhaps chat with @nvanbenschoten since he is working on some changes to merge a few replicated keys into one which also requires a compatibility story for the consistency checker.

For these new repeated fields, you should specify the `[packed=true]` protobuf option which uses a smaller encoding.

**Comment by mrtracy** [comment]
I was just writing in sort of a protobuffer pseudo-code; we'll be using the packed option.

The new version will be able to read data from either the old or new protobuffer format, which can be recognized by the presence of the row-oriented samples field.  This means that we will not be converting the format for existing data (it will all be deleted eventually), and I think this means we are safe from consistency checker errors.

There are two tough details I foresee:

+ When exactly to start writing the new format, which should only be done when the entire cluster is switched over to the new version.  This is primarily because old versions will not know how to merge the data correctly.  However, I was assuming this would just be done when the cluster version setting is upgraded.
+ There is, as expected, one fairly tricky part, which is that you might end up with a data slab with some data in Samples and some data in the column fields.  I'll see what I can do about this.

**Comment by tschottdorf** [comment]
> However, I was assuming this would just be done when the cluster version setting is upgraded.

Yeah, that's seems like exactly the kind of thing this is there for.

**Comment by mrtracy** [comment]
An update on this: Now that this is approaching completion, I am able to run some benchmarks to illustrated the expected disk-size savings.  I wrote the following benchmark-like test to compute the data size of row-formatted data, column-formatted data, and a 1 hour data rollup.

```go
// TestInternalDataSizes computes and outputs the sizes of various formats of
// disk.
func TestInternalDataSizes(t *testing.T) {
	defer leaktest.AfterTest(t)()

	now := timeutil.Now().UnixNano()
	interval := time.Second.Nanoseconds() * 10

	// Compute size for 360 merged samples in both row and column format, simulating
	// one hour of data.
	var samples []dataSample
	var value roachpb.Value
	for i := 0; i < 360; i++ {
		samples = append(samples, dataSample{now + interval*int64(i), float64(i)})
	}
	rowData := makeInternalRowData(now, interval, samples)
	if err := value.SetProto(&rowData); err != nil {
		t.Fatal(err)
	}
	rowDataSize := len(value.RawBytes)

	columnData := makeInternalColumnData(now, interval, samples)
	if err := value.SetProto(&columnData); err != nil {
		t.Fatal(err)
	}
	columnDataSize := len(value.RawBytes)

	t.Logf("ROW SIZE 1HR: %d", rowDataSize)
	t.Logf("COLUMN SIZE 1HR: %d", columnDataSize)
	t.Logf("SAVINGS: %f%%", (1-float64(columnDataSize)/float64(rowDataSize))*100)
	t.Logf("******")

	// Compute size of 24 hours of rollup data.
	samples = samples[:0]
	interval = time.Hour.Nanoseconds()
	for i := 0; i < 24; i++ {
		for j := 0; j < 360; j++ {
			samples = append(samples, dataSample{now + interval*int64(i), float64(i + j)})
		}
	}
	rollupData := makeInternalColumnData(now, interval, samples)
	if err := value.SetProto(&rollupData); err != nil {
		t.Fatal(err)
	}
	rollupDataSize := len(value.RawBytes)

	t.Logf("ROW SIZE 24HRS: %d", 24*rowDataSize)
	t.Logf("ROLLUP SIZE 24HRS: %d", rollupDataSize)
	t.Logf("%d %d %d %d", len(rollupData.Last), len(rollupData.Count), len(rollupData.Variance), len(rollupData.Max))
	t.Logf("SAVINGS: %f%%", (1-(float64(rollupDataSize)/float64(24*rowDataSize)))*100)
	t.Fail()
}
```

Output:

```
	iterator_test.go:835: ROW SIZE 1HR: 5653
	iterator_test.go:836: COLUMN SIZE 1HR: 3499
	iterator_test.go:837: SAVINGS: 38.103662%
	iterator_test.go:838: ******
	iterator_test.go:854: ROW SIZE 24HRS: 135672
	iterator_test.go:855: ROLLUP SIZE 24HRS: 1268
	iterator_test.go:856: 24 24 24 24
	iterator_test.go:857: SAVINGS: 99.065393%
```

As you can see, the column format by itself is almost a 40% disk-size savings, while the column-formatted rollups offer an impressive 99% size savings (when rolling up from ten seconds to 1 hour).  This is so significant that we may want to consider rollups only to 30 minutes or even 10 minutes - 10 minute rollups would offer far higher granularity while still offering 94% disk space savings.

**Comment by petermattis** [comment]
Nice numbers!

The rollups are beneficial to both reduce disk space as well as to reduce query time when all you want to view is less granular time frames. Was their a proposal for what the default rollup settings would be? There are 8640 10s buckets in a week. But in order to view a week's worth of data we downsample that to ~1000 buckets ~1m buckets.

**Comment by mrtracy** [comment]
Based on nothing more than round numbers, the original thought had been rolling up into 1 hour buckets, with each key holding 24 hours of data.  However, in order to benefit smaller time spans with the additional speed, I think we should do at least 30 minutes - that would allow us to consult the rollups for the one week timespan and higher at the resolution currently being used in the UI graphs.

**Comment by tschottdorf** [comment]
@mrtracy one thing I've been wondering is what impact you expect this to have on the MVCC stats. I think (please correct me) that the MVCCStats for timeseries ranges overcount quite a bit.

Now that the on-disk format becomes more space efficient, the difference will be larger. Is there a heuristic formula that we can put in the merge code to "dampen" the overcounting appropriately?

We rely, somewhat, on the fact that splits recompute the LHS which has the effect that most ranges have these estimates purged. There's also the consistency queue, which is supposed to spot these differences and fix them up. So I'm not sure this is super important, but anecdotally the timeseries have repeatedly confused users (and us) because they contribute lots of live bytes with no matching disk usage. They may also be involved in #26568, though that's only something I assume.

**Comment by mrtracy** [comment]
Completed via #27121 and numerous earlier PRs.

**Comment by mrtracy** [comment]
@petermattis @bdarnell @tschottdorf Some numbers on this:

Currently *434* Time series per a node.

Per-node, the disk space needed to store all time series data:
30 minute resolution data for 1 year = ~395M.
10 second resolution data for 1 week = ~255M.

Total space per-node at default retention = *650M*

If this is too much, we can adjust the default retention thresholds. Keep in mind that both thresholds will be user-configurable, this is just the default.

**Comment by petermattis** [comment]
Is this replicated or unreplicated data size? I'm wondering if we want to make the default 30m resolution retention shorter. I can't recall ever looking 1 year in the past. I have looked a few months in the past. Setting the default retention for the 30m resolution to 3 months feels reasonable to me.

@bdarnell, @tschottdorf opinions?

**Comment by tschottdorf** [comment]
That sounds fine to me personally, but when it comes to monitoring I'd trust @bdarnell and @mberhault more.

**Comment by mberhault** [comment]
One year seems reasonable, although so would 6 months. You could decrease the defaults to lower the extra storage surprise for users but just calling the settings out in the FAQ should be enough to override that.

**Comment by petermattis** [comment]
> You could decrease the defaults to lower the extra storage surprise for users but just calling the settings out in the FAQ should be enough to override that.

This would be my preference. We'd default to 3 months of storage but give the user the ability to opt for more if they want.

**Comment by mberhault** [comment]
That would be fine with me. One thing to file to "later" is to have some visibility in the admin UI about how much data we keep and whether we're deleting anything. Just surfacing the deletion period close to the graphs would be a great start to let users figure it out on their own.

**Comment by bdarnell** [comment]
+1 to defaulting to 3 months for the low-resolution data. I'd keep the high-resolution data for 8 or 10 days instead of a week - comparisons against the week-ago time period are very useful (i wish our high-resolution weren't quite so high). 

Another UI nice-to-have would be to show how much space the timeseries data will eventually take up (maybe showing it as "reserved" instead of "available")
