### ISSUE TITLE
sql: Values() on UPSERT RETURNING complains about empty row container

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#21651]
https://sentry.io/cockroach-labs/cockroachdb/issues/438312252/

```
*log.safeError: stopper.go:179: session.go:1366
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 423, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/session.go", line 1381, in maybeRecover
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go", line 275, in At
  File "github.com/cockroachdb/cockroach/pkg/sql/insert.go", line 642, in Values
  File "github.com/cockroachdb/cockroach/pkg/sql/union.go", line 141, in Values
...
(21 additional frame(s) were not displayed)

stopper.go:179: session.go:1366
```

**Comment by benesch** [comment]
@knz can you triage? This happened on v1.1.3, so it's possible it was fixed in v1.1.4. But I didn't see anything obvious in the release notes.

**Comment by knz** [comment]
The error is that the `Values()` method is called on an UPSERT ... RETURNING plan while its rowsUpserted row container is empty.

This is possible, I think, if the `finalize()` method at line 357 returned an empty row set without error. I don't know how that can be -- also no local fix is possible there, because if `finalize()` can ever return without doing any work, then the `Next()` method has no way to tell this to the caller. It should have been caught by the previous call to Next(), noting that there was no work left to do for the next call.

Unfortunately I am not competent (currently) with the logic for row batching around this area.

@andreimatei @couchand it seems to me you have most recently paged-in on this knowledge. Any hints?

**Comment by knz** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/446481507/

**Comment by jordanlewis** [comment]
Closing in favor of the better-specced issue in #22300.
