### ISSUE TITLE
sql: IS DISTINCT FROM $1 is rewritten incorrectly when $1 is NULL

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21704]
Found this while working on #21701:
```
statement ok
CREATE TABLE kv (k INT PRIMARY KEY, v INT)

statement ok
INSERT INTO kv VALUES (1, 1), (2, 2), (3, 3)

statement ok
PREPARE x21701b AS SELECT * FROM kv WHERE k IS DISTINCT FROM $1

query II
EXECUTE x21701b(NULL)
----
```

When index selection happens, the filter expression is `(k != $1) OR (k IS NULL)` (seen by adding a Printf in `selectIndex`). This is incorrect. `IS DISTINCT FROM NULL` is the same as `k IS NOT NULL` and this query should return results.

Note that this query will probably crash on master without #21705.

CC @nvanbenschoten @knz @jordanlewis

**Comment by RaduBerinde** [comment]
To clarify - this is not an issue in the new index constraints code. It seems like an incorrect expression normalization.

**Comment by nvanbenschoten** [comment]
Nice catch! So I think the issue here is that the normalization rules [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/normalize.go#L448) and [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/normalize.go#L466) are invalid if the right operand is `NULL`. We try to catch this, but don't take into account placeholders. Does this work properly if we change:

```
if expr.TypedRight() != DNull {
```

to

```
if r := expr.TypedRight(); r != DNull && !r.ResolvedType().FamilyEqual(types.FamPlaceholder) {
```

**Comment by RaduBerinde** [comment]
I am OOO and not at a computer. You can fetch 21705 and try (or wait until it merges).
