### ISSUE TITLE
sql: inverted indexes should handle array @> scalar

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#21783]
The `@>` has special semantics for array containment of a scalar: `[..., x, ...] @> x` is true when `x` is `true`, `false`, `null`, a string, or a number (this is distinct from the behaviour of `@>` in every other case). Inverted indexes currently don't handle this:
```
root@:26257/d> create table j (b jsonb);
CREATE TABLE
root@:26257/d> create inverted index on j (b);
CREATE INDEX
root@:26257/d> insert into j values ('[3]');
INSERT 1
root@:26257/d> select * from j where b @> '3';
+---+
| b |
+---+
+---+
(0 rows)
root@:26257/d> select '[3]' @> '3';
+--------------+
| '[3]' @> '3' |
+--------------+
|     true     |
+--------------+
(1 row)
```

**Comment by jordanlewis** [comment]
We won't be able to handle this with the index without teaching the index about result intersection. That's because JSON arrays can have duplicate entries, so an index scan over `/ARR/3` might result in several copies of a single primary key.

We need to teach index selection that this kind of query cannot be handled with an ordinary inverted index lookup for the 2.0 release.
