### ISSUE TITLE
cli/sql: trigger history search by typing a prefix + up arrow

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#21825]
I want the history search to be activated when I press the up arrow after typing a statement prefix. The search should be initialized with that prefix. So, if I type "alt" then up arrow, I want to search for the last statement that started with "alt". And then up arrow and down arrow would cycle through commands with that prefix.

You get that in bash with this:
```
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
```
I think it's inspired by Matlab's console, and it's so good! I never want to use a terminal without it again.

Jira issue: CRDB-5874

**Comment by andreimatei** [comment]
cc @knz

**Comment by knz** [comment]
You can customize bindings with libedit in your `~/.inputrc`. Feel free to dig into libedit and figure out what's the equivalent way to do this.

Offhand remark: we've made the choice to rely on a 3rd party moderately standard library precisely because we don't want to be baking custom code around an area of unix which is extremely hard to get right. I am not keen to go and tweak that code to address every need under the sun. In my opinion: if libedit supports this with a custom inputrc, then use that. If it doesn't, tough luck.

If it works in bash and not in libedit, that's just a sign that GNU readline is better. But we knew that already. If it was not for licensing, we'd use GNU readline too.
