### ISSUE TITLE
error upon server startup: could not cleanup temporary directories from record file [...]: no such file or directory

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#21856]
I made a data dir on my gceworker and tried to start a server from it on my laptop (where I have a different homedir).

```
ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /home/tschottdorf/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp261203114, may still be in use: IO error: while open a file for lock: /home/tschottdorf/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp261203114/TEMP_DIR.LOCK: No such file or directory
```

This is likely because we're using an absolute path somewhere. This shouldn't happen as this makes it impossible to move the data directories.

PS: something we should have a test for.

Assigning @arjunravinarayan as the resident temp storager.

Jira issue: CRDB-12014

**Comment by tschottdorf** [comment]
```
$ cat cockroach-data/temp-dirs-record.txt
/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp261203114
```

**Comment by arjunravinarayan** [comment]
So the error is that we save the location of the temp storage, so that we can clean it up on node-restart if the node crashed. We check if the file does exists, and if it doesn't, we presume it was cleaned up. We do this by querying `os.IsNotExist(err)` (where `err` is from the `Open` call). However, when you move the data directory, something weird is happening.

We don't store the absolute path - in fact we simply recreate the path by calling `filepath.Join(firstStore.Path, server.TempDirsRecordFilename)`. So it's not that. Instead, it's the mechanism introduced in #20854.


Reproduction instructions:

1. Start a cockroach instance.
2. `kill -9` it, so that the temp storage cleanup doesn't happen on node shutdown.
3. move the data directory, e.g. `mv cockroach-data cockroach-data2`.
4. start the new node with the new store directory, e.g. `./cockroach start --insecure --background --store=path=cockroach-data2`
5. You will see the above error, since the LOCK file exists.

We should clean this up without locking. I was not part of the long discussion in #20854. Looking over it, I don't quite see why we want to lock in the first place, something is escaping me. Any thoughts @bdarnell on how to get the LOCK mechanism to not barf upon a data directory move and node restart?

**Comment by arjunravinarayan** [comment]
My bad. You're right. The absolute path is stored in `temp-dirs-record.txt`.

I don't want to change what's stored this late in the game. Especially given there are so many ways to set this (relative, absolute, set by default to inside the first store directory, set explicitly at start time). How about the following: we attempt to delete the temp directory. If we can't find it, we simply give up.

This would only come into play if:
1) the cockroach server was not gracefully shut down
2) immediately after, the cockroach data directory was moved
3) the cockroach server was started back up in the new location.

In such an instance, the temporary storage would remain. I don't think that's that bad of an outcome. We could print a warning in such an instance, saying "unable to clean up temporary storage, temporary storage already cleaned up or data directory moved". Does that work @bdarnell ?

**Comment by bdarnell** [comment]
Yeah, in the short term we should just downgrade ENOENT from this deletion to a log.

**Comment by arjunravinarayan** [comment]
OK, I've gone ahead and done that. Sent you a PR.

**Comment by arjunravinarayan** [comment]
The remaining work is not 2.0, so moving the milestone.

**Comment by jordanlewis** [comment]
This looks like it's been finished, or close enough to finished (and old enough) that I'm closing.

**Comment by andreimatei** [comment]
I think this issue shouldn't have been closed, because there's still issues with the recording of absolute paths for the temp dir. In #74231, a user is complaining that the deletion of the absolute path recorded for the temp dir has unintended consequences in the case when the temp dir was supposed to be inside the store dir, and the store dir was moved in between restarts. In this case, on restart we end up deleting a dir from outside the store. I think that is a fairly clear bug; if the `--temp-dir` flag is not used (and so all the files are supposed to be neatly contained within the store dir), I think there shouldn't be any interactions with files outside the store on restart. I assume that, in such a case where the store is moved, we also have the opposite problem in that we don't clean up the temp files inside the store that we should be cleaning up.

It seems to me that, at the very least, in the case when `--temp-dir` is not used, we shouldn't be recording an absolute path for the temp dir; we should be recording a path relative to (and inside) the store, if at all.

@knz what do you think? I've put this on the server team's plate.

**Comment by knz** [comment]
I agree the issue needs to be solved. I disagree this is a SQL issue, and I also think it's not a server issue. This looks more like Storage.

@mwang1026 what do you think? How to best route this and #74231?
