### ISSUE TITLE
sql: random query generation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21852]
We have a [Random Syntax Generator](https://github.com/cockroachdb/cockroach/blob/master/pkg/internal/rsg/rsg.go) tool which continues to find crashes in parsing and planning. The idea of randomly generating queries has come up in the past. Other kids or doing it: [RQG](https://github.com/RQG/RQG-Documentation/wiki) is a MySQL tool, [sqlsmith](https://github.com/anse1/sqlsmith) runs against Postgres. It isn't clear if we can or should use either tool directly, but we should add Random Query Generation and Random Data Generation to our testing tool belt.

Related to random query and data generation: can we fuzz a specific query against a specified schema? The idea would that [go-fuzz](https://github.com/dvyukov/go-fuzz) would be used to generate a corpus of test data given a query and schema. The details are a bit hazy (how would the input to the `Fuzz` function be interpreted), but this seems feasible at a high level.

**Comment by petermattis** [comment]
[A genetic approach for random testing of database
systems ](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.97.3435&rep=rep1&type=pdf) is an interesting read. The TLDR is that it is a domain specific fuzzing. The paper doesn't use code coverage per-se, but does you information returned from execution about which code paths were used.

See also [Massive Stochastic Testing of SQL](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.108.6963&rep=rep1&type=pdf) which is an earlier paper that describes something similar to the Random Syntax Generator (stochastic query generation from a grammar).

**Comment by petermattis** [comment]
Cc @andy-kimball, @RaduBerinde

**Comment by jordanlewis** [comment]
I got https://github.com/anse1/sqlsmith working after adding several new compatibility features and fixing a bug.

It needed #15006, an implementation of `pg_operator`, several smaller fixes to our introspection catalog, and a fix for #23652.

So far, it's found a single actual panic: #23664.

It's also currently mostly generating queries with syntax errors due to our lack of support of typenames like `int_`, which are supposed to be the array type of `int` in this case.

It's pretty clear we should spruce this up and get it added to our test suite.

**Comment by jordanlewis** [comment]
cc @mjibson

**Comment by jordanlewis** [comment]
Once #24190 is merged, `sqlsmith` will work nicely. It's already caught several panics.

`sqlsmith` operates by running introspection queries on the database that you point it at. It discovers the tables in the database, as well as their column types. It also discovers the available types in the system, as well as the available type operators.

Because of this mode of operation, the coverage percent of `sqlsmith` depends entirely on the schema of the database that you point it at.

To make `sqlsmith` into a really powerful tool for CockroachDB, we therefore need to spend some time coming up with a schema that uses as many features of CockroachDB as possible. Ideally, the tables would represent all combinations of CockroachDB features as well. For example, we might want a table that contains collated strings, a table that is interleaved, as well as a table that contains collated strings and is also interleaved.

**Comment by jordanlewis** [comment]
#28900 encapsulates that last point.

**Comment by jordanlewis** [comment]
Sqlsmith exists now, in our codebase.
