### ISSUE TITLE
qa: Encryption at rest

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21880]

**Comment by mberhault** [comment]
@dianasaur323: are we agreed this is now targeted for 2.1?

**Comment by dianasaur323** [comment]
@mberhault tentative yes, although we haven't talked formally about it yet. We'll be discussing today and tomorrow.

**Comment by a-robinson** [comment]
Alright, let me know when it's ready for testing.

**Comment by vivekmenezes** [comment]
@mberhault when this is ready for QA I can reassign it to someone else.

**Comment by mberhault** [comment]
This is ready. Master has the latest features (see details in the tracking issue: #19783).

Draft docs are available at https://www.cockroachlabs.com/docs/dev/encryption.html

**Comment by vivekmenezes** [comment]
@solongordon reminder to QA this item soon.

**Comment by solongordon** [comment]
Thanks, QA is in progress.

**Comment by solongordon** [comment]
I haven't run into any functional issues so far, but I kept some notes on docs and usability:

- I'm sure the Docs team will handle this but I think the documentation delves into implementation details too quickly, and it would be clearer if the basic usage instructions were towards the beginning rather than the end.
- Nit: The name of the feature is inconsistently capitalized: "Encryption at Rest", "Encryption At Rest", "encryption at rest".
- Maybe nice to make the first mention of AES a link to a spec or Wikipedia.
- Not clear how the user should go about choosing their key length. It would be nice to discuss trade-offs.
- The required `old-key` parameter is somewhat confusing. It is not obvious that it should be set to "plain" when enabling encryption for the first time. And it is still required (and apparently ignored) if you are not changing the encryption key. Maybe just make it an optional parameter which defaults to "plain"?
- Would be good to document the default `rotation-period` value in both the docs and `cockroach start --help`. It's mentioned in the prose but not the table documenting the --enterprise-encryption components. Users might incorrectly assume that the default is not to rotate.
- The error message when you don't specify --enterprise-encryption for an encrypted store could be more helpful and less alarming: `* ERROR: cockroach server exited with error: failed to create engines: could not open rocksdb instance: Corruption: CURRENT file does not end with newline`
- If you point `cockroach gen encryption-key` at an existing file it just overwrites it. Seems dangerous. I think we might as well bail out if the destination already exists, just in case it stops someone from blowing away an extant key.
- Already discussed with Marc, but there is currently nothing to alert non-enterprise users that they are using an enterprise-only feature. Sounds like we will add something to Admin UI later, but maybe nice to emphasize this on the docs page as well?

**Comment by mberhault** [comment]
Thanks for the feedback. The docs do need a lot of work, I'll integrate your comments. The very first one may be more on the docs team when they get to their polish phase. I'm ok at documenting the details but not very good at a well organized, easy-to-grok document.

For the other issues, I'm agree with the last two. I'll tweak `gen encryption-key`. Not sure there's a good place for the enterprise check in the admin UI.

The error message **should** be different as of approximate 5 days ago ([this pr](https://github.com/cockroachdb/cockroach/pull/28710). Could you check that you were using a binary that has it, and paste the exact commands if you were?

**Comment by solongordon** [comment]
Yes, I noted the confusing error message last week but verified it's fixed now. Thanks!

**Comment by mberhault** [comment]
Summarizing issues raised before and status. Will keep updating this comment:

Addressed:
- Nit: The name of the feature is inconsistently capitalized: "Encryption at Rest", "Encryption At Rest", "encryption at rest": **fixed in https://github.com/cockroachdb/docs/pull/3569**
- Maybe nice to make the first mention of AES a link to a spec or Wikipedia: **fixed in https://github.com/cockroachdb/docs/pull/3569**
- Would be good to document the default `rotation-period` value in both the docs and `cockroach start --help`. It's mentioned in the prose but not the table documenting the --enterprise-encryption components. Users might incorrectly assume that the default is not to rotate: **docs fixed in https://github.com/cockroachdb/docs/pull/3569**
- I'm sure the Docs team will handle this but I think the documentation delves into implementation details too quickly, and it would be clearer if the basic usage instructions were towards the beginning rather than the end. **suggested in https://github.com/cockroachdb/docs/issues/3526**
- Not clear how the user should go about choosing their key length. It would be nice to discuss trade-offs. **suggested in https://github.com/cockroachdb/docs/issues/3526**
- The error message when you don't specify --enterprise-encryption for an encrypted store could be more helpful and less alarming: `* ERROR: cockroach server exited with error: failed to create engines: could not open rocksdb instance: Corruption: CURRENT file does not end with newline`. **fixed in https://github.com/cockroachdb/cockroach/pull/28710, available on master and next beta release**

TBD:
- Would be good to document the default `rotation-period` value in both the docs and `cockroach start --help`. It's mentioned in the prose but not the table documenting the --enterprise-encryption components. Users might incorrectly assume that the default is not to rotate. **the CLI flag usage still needs to be filled in**
- If you point `cockroach gen encryption-key` at an existing file it just overwrites it. Seems dangerous. I think we might as well bail out if the destination already exists, just in case it stops someone from blowing away an extant key. **will fix**

Up-in-the-air:
- The required `old-key` parameter is somewhat confusing. It is not obvious that it should be set to "plain" when enabling encryption for the first time. And it is still required (and apparently ignored) if you are not changing the encryption key. Maybe just make it an optional parameter which defaults to "plain"? **I intentionally made it required to make sure transitions were handled properly. Since key rotation involves changing the key files and making sure they're being used properly (eg: don't delete your old key until cockroach has rotated), I prefer to make the flag as conservative as possible. I'm happy to revisit this if it proves to be a pain point**
- Already discussed with Marc, but there is currently nothing to alert non-enterprise users that they are using an enterprise-only feature. Sounds like we will add something to Admin UI later, but maybe nice to emphasize this on the docs page as well? **not much here for now. The debug page is the only admin UI component that shows encryption status. It's pretty bare-bones and supposed to eventually contain more generic information about the stores. I think once we get a polished page for encryption (eg: cluster-wide reports) we'll want to lock that down. That said, there may be an easy way to just put up a warning on the report page when we don't have an enterprise license. I'll check in the UI team.**

**Comment by solongordon** [comment]
>  I intentionally made it required to make sure transitions were handled properly.

The main confusion from my standpoint was that it's still required even when there is no transition happening. But I agree this is a minor issue and better to err on the side of being explicit.
