### ISSUE TITLE
sql: can't control time of actual deletion after DROP/TRUNCATE is issued

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21887]
Discussed with @vivekmenezes.

The scenario went as follows:
1. cluster says "disk full"
2. I go and look and see a large table
3. I run "DROP TABLE", *expecting this to release disk space*
4. the disk space doesn't get released
5. I ask around and I learn "oh there is a GC period by default 25 hours"
6. so I *change the zone config to lower the GC period*
7. disk space still doesn't get released - what up with that?

Problem: **the deletion of entire tables goes via a separate mechanism than the GC period in the zone config**: a periodic task by the schema manager iterates through all dropped table descriptors and, if the delay has expired, calls RocksDB  "ClearRange" on that table's entire range.

That deletion GC delay *is stored in the table descriptor itself* (the descriptor marked for deletion). It is populated at the time the TRUNCATE/DROP is issued by the `ttlseconds` field from the zone config, but the zone config is not used further beyond this point.

**in particular if the zone is modified after DROP is issued, this will have no impact on when the data gets actually deleted.**

This also manifest in another scenario:
1. I truncate a table.
2. A couple hours later, my coworker says "hmm, we're looking into it, but we might still have a couple legacy orders that were in that table -- we'll check and use AS OF SYSTEM TIME to get what we need"
3. I've read about TTLs so I say "oh, okay, well, we have until the TTL to read the old data, so I'll extend the TTL on that table to 7 days"
4. 28 hours later, `AS OF SYSTEM TIME` starts failing on the GC Threshold, even though, according to my TTL, it shouldn't have deleted it yet?

Two main UX problems:
- there is no way to say "drop this table data now!" regardless of current zone config
- can't change "drop this table data in 25 hours" to "drop this table data now" after TRUNCATE/DROP has been issued

Idea by @vivekmenezes: instead of marking table descriptors as "deleted", rename them to go in a special "trash" database (knz: I assume with limited permissions so they also become invisible to app queries). Then if + when desired issue DROP on the "trash" database to actually do ClearRange *synchronously*.

**Comment by knz** [comment]
@awoods187 this is a sql issue that probably needs some attention

**Comment by dt** [comment]
I also have this concern in the opposite direction -- if I drop something and, while still well within the TTL window, I extend the TTL window, I'd expect that to buy me more time to potentially `AS OF SYSTEM TIME` or point-in-time backup/restore it.

I think either way, we want to record the GC window start time, rather than eagerly compute the end time, so that the schema changer can periodically check if, according to the _current_ TTL, it is time to GC.

**Comment by bdarnell** [comment]
@dt It's not just DROP TABLE. Extending the TTL window is not generally safe. Consider a regular table with the default 24h TTL. Set the TTL to 1 hour, and the GC queue starts working and deleting things that are over an hour old. If you then set the TTL back to 24h, that doesn't make it safe to issue queries with a timestamp of `now - 12h`, because older data may have already been deleted. Increasing the TTL doesn't truly take effect until you've waited for `new TTL - old TTL`. 

For DROP TABLE, we can kind of support increasing the TTL, since we know that the deletion happens all at once instead of incrementally as the GC queue works, but I'm not sure if we should, since it's inconsistent with the way TTL extensions work in other cases. We could use some way to undrop a table (such as the suggested "trash" database), but I don't think we need a way to extend the time that a table can exist in the dropped state.

**Comment by dt** [comment]
@bdarnell right, I think it makes intuitive sense that anything older than the current TTL may already be gone, so extending from 1h to 12h can’t preserve data deleted 2h before extending it, but I would expect that e.g. 6h after extending it, i’d be able to read at 30min before I extended it, right?

**Comment by bdarnell** [comment]
Yes, that's true.

**Comment by dt** [comment]
I guess what I meant there was that I'd expect similar semantics with a dropped table -- if I extend the TTL _before_ reaching `drop time + TTL` , such that at no point was `now - current ttl > drop time`, I'd be surprised if it was then gc'ed anyway?

**Comment by bdarnell** [comment]
Yeah, you're right. I had it backwards; this makes dropping a table more like regular deletions, not less.

**Comment by awoods187** [comment]
On a related topic, we are also discussing using partitioning for deleting data in 2.1. This would be the enterprise "fast" way to delete a large amount of data vis a vis drop table.
