### ISSUE TITLE
sql: batch writes until a read is required

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#2210]
Compared with 2PC, cockroach applies log to replications directly before commit. This may lead to high latency: 
For example, if sql txn has seven write statements(update or insert), The latency is > 7*(replicated time+writed time).  I think maybe we could cache the write statements and commit them at last。

**Comment by tschottdorf** [comment]
@Frank-Jin what exactly is your situation/suggestion? A quick look at the code reveals that a statement such as
`INSERT INTO t1 VALUES(...); INSERT INTO t1 VALUES(...); ....;` would have that issue, but `INSERT INTO t1 VALUES (...), (...), ...;` would be executed in a batch.

**Comment by bdarnell** [comment]
I think the idea is that because some language's SQL driver interfaces have poor support for batching, we could improve performance for these clients by buffering write-only operations at the gateway. The tricky thing is that UPDATE and INSERT are not purely write-only: they return a row count or an auto-assigned ID. We can't know at the gateway whether these return values will be needed or not (unless we do something like postgresql's `INSERT ... RETURNING ...` to let the application explicitly decline the return value)

**Comment by spencerkimball** [comment]
There's more work to be done here, but #14188 begins to solve this problem and we're tracking it in other newer issues, so I'm closing this one.
