### ISSUE TITLE
storage: Load shedding in command queue

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#22340]
In https://github.com/cockroachdb/cockroach/issues/20114, we observed that a cluster could get stalled for hours due to a thundering herd of requests to a single range. Hundreds of thousands of commands built up in the command queue (which, IIRC, scales worse than linearly as it grows) and took hours to all execute. Because this was on the SQL table lease range, no SQL table leases could be acquired while this was all happening, blocking user requests.

We fixed the cause of the thundering herd of table lease deletions, but it's still fairly concerning that this is how the system behaves when under such load. Load shedding doesn't have to be the solution, but letting the command queue build up such a large queue of work that hours are needed to clear it is clearly not great.

**Comment by nvanbenschoten** [comment]
I was able to produce a similar situation by performing a large number of splits at the same time on a large cluster. After about 60,000 splits, everything slowed down and I could see `replica.beginCmds` as the dominant function in CPU profiles on the node with a disproportionate amount of CPU utilization. After a bit of searching I found a SQL data range with about 9000 local writes in its command queue and 4000 local reads. The `/commandQueue` debug page wasn't working because of #28966 so I wasn't able to see exactly what these operations were (@tschottdorf any ideas?). 

The replica mutex locking in `beginCmds` was a major chunk of all blocking in a blocking profile. A smaller but still visible part of the blocking profile was in `removeCmdsFromCommandQueue`, which makes sense because they're competing for the same lock. I think this is part of why things get wedged so hard once the command queue gets above a certain critical size. `beginCmds` starts to take longer and longer because of the super-linear complexity in `CommandQueue.getPrereqs`. This causes `removeCmdsFromCommandQueue` to slow down, meaning that fewer commands are able to escape the `CommandQueue`, even when they're done executing. Together, this means that commands pile up to enter the `CommandQueue` but nothing is able to leave! I think the solution to this is to introduce some kind of prioritization mechanism between the locking in `beginCmds` and `removeCmdsFromCommandQueue`. If a command wants to leave the `CommandQueue`, it should never need to wait for all command that are already waiting to enter the queue. I don't think Go has any notion of locking with priority, but we can accomplish what we want with a condition variable and an atomic counter:
```go
var cmdQLock Mutex
var cmdQCond Cond // associated with cmdQLock
var cmdQWaitingToExit int64

func beginCmds() {
    cmdQLock.Lock()
    for atomic.LoadInt64(&cmdQWaitingToExit) > 0 {
        cmdQCond.Wait()
    }
    ...
    cmdQLock.Unlock()
}

func removeCmdsFromCommandQueue() {
    atomic.AddInt64(&cmdQWaitingToExit, 1)
    cmdQLock.Lock()
    ...
    cmdQLock.Unlock()
    if atomic.AddInt64(&cmdQWaitingToExit, -1) == 0 {
        cmdQCond.Broadcast()
    }
}
```

If that alone doesn't help, we can try to attack the algorithmic complexity of `CommandQueue.getPrereqs` head-on. One idea is to create a "staging queue" with a constant complexity but reduced granularity and enter this queue first if the interval tree gets too large. For instance, `beginCmds` could grab the `cmdQLock` and quickly check the tree's size. If it's too large (maybe 1024 commands) then the command could quickly enter a secondary queue backed by a linked list and unlock. Commands entering the main `CommandQueue` would then simply need to notify the head of the staging queue that the tree is now small enough to enter. We could use a condition variable for this instead, but that could lead to starvation. The downside here is the loss of granular locking in this staging queue - even commands with no overlapping prerequisites would still need to wait. The upside is that we would prevent the `CommandQueue` from ever entering the regime where its complexity explodes. I can't think of any prior-art that looks like this, so I'm curious if it's a worthwhile idea or if there are better alternatives. If you squint, it kind of looks like a more general admission control policy, so maybe this doesn't even belong tied to the `CommandQueue` at all.

Before making any changes here though, I'd like to find an access pattern that easily reproduces this badness. That will allow us to be more confident about any adjustments we make. @a-robinson any ideas about this?

**Comment by nvanbenschoten** [comment]
I was able to create some of this badness by performing writes to a handful of keys in an open loop against a single replica with its Raft proposal function mocked out. Once the number of writes reached around 100k the replica was not able to keep up and the command queue began to grow, slowing everything else in the test down. CPU and mutex profiling confirmed that the slowdown was due to the command queue. With this reproduction, I did a bit of experimenting.

First, I looked into the theory of prioritizing `removeCmdsFromCommandQueue` over `beginCmds` using the approach laid out above. This sped the test up by about 75%, dropping the time to perform 500k writes in this configuration from 35 minutes down to about 8. This demonstrated that such a fix would improve the situation, but it's not sufficient by itself. Even if we do prevent queue insertion from slowing down queue removal, that alone can't prevent an unbounded number of requests from hitting the queue at the same time before any can be removed in the first place.

I then looked at a "low-resolution" (i.e. all commands are dependent) staging queue that requests entered if the command queue interval tree got too large. This sped things up tremendously, dropping the runtime of the same 500k write test down to about 30 seconds. Of course, the workload didn't experience any of the downsides of such a queue because it was only writing to a few keys so no writes were suddenly artificially blocked. I'm starting to think that isn't the right way to think about things though because even in a workload with disparate keys, a scenario where the command queue gets too large will still artificially block writes because they won't ever even be able to enter the command queue because things will be too slow!

So I think it's pretty clear that we need to add some form of admission control to replica access. The easiest way would actually be to just add a semaphore acquisition to `Replica.Send`. This avoids having to complicate the command queue because it can operate independently. A strawman proposal would be to limit the number of concurrent requests that operate on a `Replica` to 1024, as this seems to be well below the range where the command queue starts to struggle.

@petermattis you've thought about admission control at various layers in Cockroach before. Anything you'd like to add here?

**Comment by petermattis** [comment]
I've been thinking about admission control at the SQL level. I suppose it can make sense at the replica level as well. Perhaps even more sense because a single SQL statement can translate into thousands of KV ops. The numbers above are very compelling. Definitely seems worthwhile to at least experiment with some sort of admission control at the replica level.

Are there any concerns about new deadlock scenarios? You'd want to make sure to make lease acquisition requests bypass admission control. Anything else?

Sort of interesting that we have Raft proposal quota and are considering another level of admission control (this time before the command queue). Not sure what to make of that, just pointing it out.

**Comment by nvanbenschoten** [comment]
> Definitely seems worthwhile to at least experiment with some sort of admission control at the replica level.

Agreed, although I still would like to find a case where we can reproduce this badness on a realistic workload. At the moment I still see this as nothing more than a safety measure to prevent cascading failures.

> Are there any concerns about new deadlock scenarios? You'd want to make sure to make lease acquisition requests bypass admission control. Anything else?

Lease acquisition requests are the only important case I could think of that blocks beneath the command queue for another request to evaluate on the same range. There are other cases that block beneath `Replica.Send` for other requests (mainly admin requests), but none that should ever be correlated across all requests beneath the command queue at the same time. Still, we probably should ignore admin requests because they don't even enter the command queue.

> Sort of interesting that we have Raft proposal quota and are considering another level of admission control (this time before the command queue). Not sure what to make of that, just pointing it out.

I had the same thought and rationalized it as replica-level admission control vs. Raft-level admission control. I don't see any glaring issues with them being separate.

**Comment by a-robinson** [comment]
> Agreed, although I still would like to find a case where we can reproduce this badness on a realistic workload.

You could potentially argue it's unrealistic, but something like the issue that motivated this one (https://github.com/cockroachdb/cockroach/issues/20114) in which tens or hundreds of thousands of DMLs are issued all at once seems like a good way to repro. A poorly written client system which doesn't implement exponential backoff properly could cause a similar query load on accident.

**Comment by nvanbenschoten** [comment]
The spanlatch manager dramatically improved the degree of concurrency which we can sustain while sequencing requests on a range. Any improvement past this point will likely be part of a more general admission control policy.
