### ISSUE TITLE
sql: CTE name resolution can't pass through VALUES or UNION clauses

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#22418]
WITH outermost(x) AS (
      SELECT 1
      UNION (WITH innermost as (SELECT 2)
             SELECT * FROM innermost
             UNION SELECT 3)
    )
    SELECT * FROM outermost ORDER BY 1;

expected:

     x 
    ---
     1
     2
     3
    (3 rows)

actual:

    relation "innermost" does not exist

**Comment by jseldess** [comment]
Documented as a known limitation in https://github.com/cockroachdb/docs/pull/2823.

**Comment by jseldess** [comment]
@jordanlewis, I'm trying to document this for 2.0, but I can't quite understand it. Does `CTE name resolution can't pass through VALUES or UNION clauses` mean CTEs can't be used `VALUES` or `UNION` clauses? Or is it more specific? Can you perhaps draft up a sentence or two for me?

**Comment by jseldess** [comment]
Ah, I think this was documented by @knz here? https://www.cockroachlabs.com/docs/dev/common-table-expressions.html#use-ctes-at-most-once

**Comment by knz** [comment]
No this is a different issue.

Jesse I can volunteer to document this known limitation, together with the other one you found yesterday.

**Comment by jseldess** [comment]
Thanks, @knz! To save extra git work, please just add your writeup as a comment on this PR: https://github.com/cockroachdb/docs/pull/2823

**Comment by knz** [comment]
done

**Comment by sploiselle** [comment]
@jordanlewis Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by knz** [comment]
This has been fixed in the new opt code -- it's only a limitation in the heuristic planner.

"""
title: Using common table expressions in VALUES and UNION clauses

When the cost-based optimizer is disabled, or when it does not support a query, a common table expression defined outside of a VALUES or UNION clause will not be available inside it. For example `WITH a AS (...) SELECT ... FROM (VALUES(SELECT * FROM a))`. This limitation will be lifted when the cost-based optimizer covers all queries. Until then applications can work around this limitation by including the entire CTE query in the place where it is used.
"""

**Comment by jordanlewis** [comment]
Closing due to fixed on CBO status.

**Comment by jseldess** [comment]
@jordanlewis, can I resolve/remove this known limitation from the 20.1 docs? https://www.cockroachlabs.com/docs/dev/known-limitations.html#using-common-table-expressions-in-values-and-union-clauses

**Comment by jordanlewis** [comment]
Yes!

**Comment by jseldess** [comment]
Thanks, @jordanlewis.
