### ISSUE TITLE
sql: experimental syntax must not use separate "experimental" keyword

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22538]
So there's a proximate technical problem and a more general policy/process problem.

As to the proximate problem:

- Good: `SHOW EXPERIMENTAL_REPLICA`, `
- Bad: `ALTER TABLE ... EXPERIMENTAL CONFIGURE ZONE`
- Good: `ALTER TABLE ... EXPERIMENTAL_ZONE CONFIGURE`, perhaps `ALTER TABLE ... ZONE EXPERIMENTAL CONFIGURE ...`

Why is the second bad? Currently that rule lives in the non-terminal `alter_zone_table_stmt`. 
Say, if I want to add another rule in `alter_table_cmds` (the command part of the generic form of `ALTER TABLE`) that also has an experimental feature, for example `ALTER TABLE ... EXPERIMENTAL FROBNICATE`, well...  I can't! my grammar is then ambiguous.

In general, in any grammar context where there are multiple non-terminals with similar structures, the rules must not use more than 1 token to distinguish the non-terminals.

The solution here is to have the ZONE keyword first to enter the non-terminal `alter_zone_table_stmt`. I'd say even avoid `CONFIGURE` (because we might want to configure other things, and then the parser generator will be annoyed again). 
Then If you really want the human word "experimental" in there, use either `ZONE EXPERIMENTAL...` or `ZONE CONFIGURE EXPERIMENTAL..`. But I'd simply recommend `EXPERIMENTAL_ZONE`

Now on to the general problem:

The addition of experimental features to the SQL grammar has been a bit too wild in general. I think we have not been successful at taking a principled approach that makes future additions easier. I had made a proposal on this (being worked on by @dianasaur323), but the corresponding RFC (#19175) is still being worked on and the particular problem indicated above is not yet comprehensively addressed by that RFC.

I think that 1) everyone in the SQL team should be more mindful of this class of problem 2) we must come up with a document that provides both an understanding of the problem and clear guidelines on how to design robust, future-proof grammar rules for experimental syntax.

cc @cockroachdb/sql @cockroachdb/sql-ccl

**Comment by benesch** [comment]
I'd also like to see discussed a concern not mentioned here: the coherency of the SQL language, distinct from our particular implementation of a SQL grammar.

For example, `ALTER TABLE...` commands tend to start with verbs: `ALTER TABLE ... ADD COLUMN`, `ALTER TABLE ... RENAME TO`, et al. Thus the choice of `ALTER TABLE ... CONFIGURE ZONE`. I'd hate to instead use inconsistent grammar like `ALTER TABLE ... ZONE EXPERIMENTAL_CONFIGURE` just because it makes the grammar simpler. I think we should prefer SQL syntax that is as consistent as possible, and only compromise on that goal when it makes the grammar terribly unworkable.

In a similar vein, `ALTER TABLE ... CONFIGURE EXPERIMENTAL_ZONE` suggests, to my ear, that the _zones_ are experimental. But the zones themselves aren't experimental—just their configuration via SQL! So I propose that we use:

```
ALTER TABLE ... EXPERIMENTAL_CONFIGURE ZONE 'blah'
```

Are there problems with this that I'm not foreseeing? If someone wants to add another `EXPERIMENTAL_CONFIGURE` command, they can refactor the grammar:

```
alter_table_stmt: alter_onetable_stmt | ... | alter_experimental_configure_table_stmt
alter_experimental_configure_table_stmt: ALTER TABLE table_name EXPERIMENTAL_CONFIGURE choice
choice: ZONE name | FOOBARBAZ name
```

And in fact I think the same refactoring would suffice if `EXPERIMENTAL_CONFIGURE` were spelled `EXPERIMENTAL CONFIGURE`, no?

**Comment by knz** [comment]
yes `EXPERIMENTAL_CONFIGURE` is better.

Using separate words `EXPERIMENTAL CONFIGURE` does not, however, suppose I wanted to create a new `alter_table_cmd` that also uses `CONFIGURE` I'd still be stuck.

(This particular example evaporates if CONFIGURE ZONE was actually an `alter_table_cmd` instead of its own statement node, which I think would be better -- Nikhil you may want to look into this -- but the general problem remains).

**Comment by benesch** [comment]
Yeah, the only reason it's not an `alter_table_cmd` is because `alter_split_stmt` and `alter_testing_relocate_stmt` and `alter_scatter_stmt` are not `alter_table_cmd`s, so I followed what seemed to be convention. Should they all be `alter_table_cmd`s?

**Comment by benesch** [comment]
Actually, now that I look at it, it seems the SQL standard only makes `alter_table_cmd`s out of things that make sense if specified multiple times. So `ADD COLUMN` is an `alter_table_cmd`, but `RENAME` is not. Or perhaps this is just historical baggage.

**Comment by knz** [comment]
No you have it right; rename tends to be on its own because it's not so clear that subsequent alters can still operate on the descriptor after a rename.

But the scatter, relocate, split and configure zone could definitely processed together in a single ALTER TABLE statement together with other descriptor mutations.
