### ISSUE TITLE
ui: clusterviz map layout gets crowded easily

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#22557]
E.g.
<img width="988" alt="screen shot 2018-02-09 at 6 27 28 pm" src="https://user-images.githubusercontent.com/7341/36054934-1a37cf3e-0dc7-11e8-8f9f-28d91a7759a4.png">

Unable to scroll the map up higher, although it seems like I should be able to.

**Comment by couchand** [comment]
This is caused by the arbitrary choice of `maxLatitude` here: https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L37

I spoke with Matt about this a while back, it sounds like that choice was made because the Mercator projection starts to look *really* crazy north of there.  I think we should remove that limit, because of course it's possible for data centers to be further north (what if we had a customer in Iceland, for instance?).  And if that makes the map look weird, we should investigate an alternate projection.  Mercator is pretty crappy by almost any criteria.

But even with the above, this still might be a problem.  I think a somewhat related problem is what happens when two locations are nearby one another.  In both cases, it seems like the solution is to shift things around some to make sure everything is visible.  This goes squarely in the bucket of "things that we were worried about when we first started discussing this project".

I think the simple change of relaxing the latitude restriction is doable for 2.0, but I doubt the real fix will be, so I'm moving this to 2.1.

**Comment by couchand** [comment]
There's also a max zoom factor, which means no matter what I do, I can't get these guys apart:

<img width="521" alt="screen shot 2018-02-13 at 12 12 38 pm" src="https://user-images.githubusercontent.com/793969/36163408-55b1588a-10b7-11e8-9869-e60267f54731.png">

**Comment by vilterp** [comment]
I don't really have the problem of a high-latitude node getting cut off anymore, which is the original issue. Going to close.

**Comment by couchand** [comment]
My problem is still a problem, and I updated the title to reflect the more general concern, so re-opening.

**Comment by piyush-singh** [comment]
@timveil pointed out that there is no way to tell whether multiple datacenters are stacked right on top of one another.

![image](https://user-images.githubusercontent.com/21692034/54280040-e3ac1180-456c-11e9-84f3-40731837f544.png)

Each region on the above map actually has two datacenters with the same lat/long coordinates, and it is impossible to tell from the map.
