### ISSUE TITLE
acceptance: TestVersionUpgrade times out

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#22581]
https://gist.github.com/benesch/e652cc39b600430353d24e7a3f796ed1

**Comment by benesch** [comment]
Seems related to #22518.

/cc @bdarnell

**Comment by bdarnell** [comment]
Maybe not - my revert of #22518 (#22620) is also experiencing hangs in the acceptance tests.

**Comment by bdarnell** [comment]
#22620 had three CI hangs in a row when I un-skipped this test, so this appears to be unrelated to #22518.

**Comment by bdarnell** [comment]
Looking at the teamcity logs, this became flaky after #22487 went in (the other merges around this time seem unlikely to be an issue; they're mostly affecting the UI and optimizer). CC @nvanbenschoten 

This test has rotted - it tests an upgrade from 1.0.5 to master without going through 1.1. It *should* be failing; the question is why it is flaky rather than failing every time.

**Comment by nvanbenschoten** [comment]
Closing now that https://github.com/cockroachdb/cockroach/pull/22637 is merged. We can re-open if we see this fail again.

**Comment by nvanbenschoten** [comment]
I'm going to re-enable this test and look into improving it with suggestions from https://github.com/cockroachdb/cockroach/issues/15851#issuecomment-358019822.

**Comment by benesch** [comment]
Heads up that v1.1.0 is busted; it reports its version as v1.0-3. You may want to start with v1.1.1 instead.
