### ISSUE TITLE
sql: investigate handling of duplicate rows in spans

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#22631]
@m-schneider and @pbardea observed separately that if we pass duplicate values through an indexJoin or a joinReader, we don't get duplicate results as expected. This can hide bugs, and would break general uses of joinReader.

We should handle this correctly, or error out. If we error out, we will need special handling in joinReader.

It's unclear at this point if the problem is inside KV, or inside the kv/row fetchers. It should be easy to repro and debug as a joinReader test, I think.

**Comment by RaduBerinde** [comment]
CC @vivekmenezes

**Comment by pbardea** [comment]
Adding a bit more detail:

Currently it seems that no processor is currently using the `rowFetcher` in such a way that the bug is exposed to the user, and hence cannot write a logic test exposing it. The issue is only exposed when a slice of spans is generated which have 2 spans identical and adjacent to each other in the list.

Currently, `rowFetcher`s are initialized with either a single span of a large range or with a collection of spans over the primary index, which do not contain duplicates (e.g. the `joinReader` is restricted to use only a primary index).

The issue can be exposed by creating a `joinReader` test which specifies duplicate rows adjacent to each other in the `input`. The argument is that this should produce the same output whether or not the reader (and thus underlying fetcher) is initialized with a batch of spans, or with each span individually. Additionally, right now the `joinReader` behaves differently when the identical spans are adjacent to each other and when they are not. This should not be the case. The underlying issue is that the `rowFetcher` is not detecting the completion of a row while reading KVs (since the index key prefix had not changed, even though it was reading from a new span).

**Comment by solongordon** [comment]
Looked into this a bit. Even now that `joinReader` supports secondary indexes, this should not be an issue, since it enforces that the spans passed to `rowFetcher` are unique.

Is it correct to say that the spans passed to `rowFetcher` should never overlap? That seems like the case based on https://github.com/cockroachdb/cockroach/blob/45b1dc11ced0b4d1345c750f29539c717f099252/pkg/sql/sqlbase/kvfetcher.go#L317-L320 but I don't see that restriction mentioned elsewhere. It would be easy to add a check to enforce that, though it would be O(n^2) in the number of spans so I don't know if that's worth it.
