### ISSUE TITLE
"did not find terminator 0x0 in buffer" error from interleave join

### ISSUE THREAD

**Issue by fastest963** [cockroachdb/cockroach#22655]
From #22647

Running version `v2.0-alpha.20180212 (linux amd64, built 2018/02/12 20:00:23, go1.9.3)`

Tables:
```
CREATE TABLE IF NOT EXISTS users (
	region STRING,
	uuid   STRING,
	lp     STRING,
	lfv    INT,
	PRIMARY KEY (region, uuid)
)
```
```
CREATE TABLE IF NOT EXISTS sessions (
	region STRING,
	uuid   STRING,
	id     STRING,
	fv     INT,
	lv 	   INT,
	nv 	   INT,
	lda    INT,
	f      INT,
	sf     INT,
	b      BOOL,
	hab    BOOL,
	u      STRING,
	ip     STRING,
	ua     STRING,
	PRIMARY KEY (region, uuid, id),
	CONSTRAINT fk_user FOREIGN KEY (region, uuid) REFERENCES users
) INTERLEAVE IN PARENT users (region, uuid)
```

Running the following query:
```
SELECT s.id AS id, u.* FROM sessions AS s JOIN users AS u ON ((s.region=u.region) AND (s.uuid=u.uuid)) WHERE (s.region='gce-us-central1');
```
returns an error:
```
pq: did not find terminator 0x0 in buffer 0x126763652d75732d63656e7472616c310002
```

If I turn off interleave joins then the query completes successfully without error.

**Comment by arjunravinarayan** [comment]
@nvanbenschoten could you please help me triage who I should send this to? I haven't seen this encoding issue crop up before. I'm just making a guess on relevance based on code commits. Thank you.

**Comment by solongordon** [comment]
Running low on free cycles at the moment but I should be able to look into it next week. If someone familiar with interleaved tables wants to help look into it that would be welcome.

**Comment by jordanlewis** [comment]
@fastest963, thanks for the excellent bug report. The issue is easily reproducible and occurs even without any data in the provided tables, so it has nothing to do with the state of your database.

Here's the stack trace. I'll follow up with details and hopefully a bugfix patch soon.

```
github.com/cockroachdb/cockroach/pkg/util/encoding.getBytesLength(0xc424c6ec02, 0x13, 0x13, 0x1200ff0100, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:623 +0x1e8
github.com/cockroachdb/cockroach/pkg/util/encoding.PeekLength(0xc424c6ec02, 0x13, 0x13, 0x1, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:1143 +0x3c8
github.com/cockroachdb/cockroach/pkg/sql.maximalJoinPrefix(0xc424b8e300, 0xc424b8e000, 0xc424c6ec00, 0x15, 0x15, 0xc424c6ebc0, 0x15, 0x20, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_join.go:505 +0x126
github.com/cockroachdb/cockroach/pkg/sql.joinSpans(0xc42696a6e0, 0xc424d6c6c0, 0x1, 0x1, 0xc424bc5cb0, 0x0, 0x0, 0x50d4096, 0x40140d7)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_join.go:752 +0x1f4
github.com/cockroachdb/cockroach/pkg/sql.alignInterleavedSpans(0xc42696a6e0, 0xc424d6c6c0, 0x1, 0x1, 0xc424d6c700, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_join.go:568 +0xa2
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).tryCreatePlanForInterleavedJoin(0xc4208da9c0, 0xc426f05ff8, 0xc42696a6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_join.go:145 +0x99b
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc4208da9c0, 0xc426f05ff8, 0xc42696a6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1610 +0x1446
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc4208da9c0, 0xc426f05ff8, 0x6d26ba0, 0xc42696a6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1751 +0x1219
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc4208da9c0, 0xc426f05ff8, 0x6d26ce0, 0xc42696a580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1754 +0x823
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc4208da9c0, 0x6d2fc60, 0xc425024ec0, 0xc425810b60, 0x6d26ce0, 0xc42696a580, 0xc420812900, 0xc4207b3bc0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:509 +0x138
<snip>
```

**Comment by jordanlewis** [comment]
The minimal reproduction appears to be:

```
CREATE TABLE a (a string, b string, primary key (a, b));
CREATE TABLE b (a string, b string, primary key (a, b)) interleave in parent a (a, b);
SELECT * FROM a JOIN b ON a.a=b.a AND a.b=b.b WHERE a.a='foo';
```

The underlying problem here is the same as the one I pointed out in https://github.com/cockroachdb/cockroach/pull/21889#issuecomment-363267694. We're passing in a `PrefixEnd`'d key to the string decode function. Recall that `PrefixEnd` may simply increment the final byte of the key. For strings, this is invalid: strings in the key encoding must always include a string-terminator value that can be used to find the end of the string.

This is kind of a tricky situation to be in. In general, it's invalid to do any kind of semantic analysis on keys that have been modified by `PrefixEnd` or other encoding-unaware methods.

One way to fix this problem would be to teach `PeekLength` to ignore errors that it encounters because of missing string terminators, but that could cause other problems to go unnoticed. Alternatively, we could introduce a variant that can be called on key components at the end of keys used in spans, that knows about this kind of issue.

I'm interested in what @RaduBerinde thinks about this issue, since I know he collaborated with @richardwu on this project and the introduction of `UndoPrefixEnd`, which exists exactly to prevent this problem from happening when we try to pretty-print keys. But what about when we try to normally manipulate them?

**Comment by RaduBerinde** [comment]
I think that in this code path it's safe to assume the value is the entire remaining key if we applied `PrefixEnd`. But indeed, we would need a version of `PeekLength` that is able to tell us it failed. The question is: is it possible to take a valid key, `PrefixEnd` it and have the result look like a valid, but shorter value (in which case `PeekLength` wouldn't fail, but would return an incorrect value)? I'm not sure (and even if no, it's still a fairly fragile mechanism).

I wonder if it would be feasible to change the representation of keys throughout `sql` to augment them with a `PrefixEnd` flag. Instead of doing PrefixEnd on a key, we would just set the flag, and only call PrefixEnd very late in the game (e.g. before handing off to `kv`).

**Comment by petermattis** [comment]
Ugh, I referenced the wrong issue in the pull-request message. This issue is unrelated to #22832.

**Comment by jordanlewis** [comment]
> The question is: is it possible to take a valid key, PrefixEnd it and have the result look like a valid, but shorter value (in which case PeekLength wouldn't fail, but would return an incorrect value)? I'm not sure (and even if no, it's still a fairly fragile mechanism).

No, I don't think this is possible.

A valid string always has an `0x00 0x01` at the end of it. `PrefixEnd` will always turn that suffix into `0x00 0x02` - there is no danger of modifying any earlier bytes in the string, because `PrefixEnd` doesn't do that unless the last byte is `0xff` which causes a carry.

I agree that it's fragile.

> I wonder if it would be feasible to change the representation of keys throughout sql to augment them with a PrefixEnd flag. Instead of doing PrefixEnd on a key, we would just set the flag, and only call PrefixEnd very late in the game (e.g. before handing off to kv).

This is a good idea, but it's definitely not possible in the short term.
