### ISSUE TITLE
sql/sem: investigate using strings.Builder (go1.10) in FmtCtx

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#22777]
`sql/sem/tree.FmtCtx` currently embeds a `bytes.Buffer` as a target for the formatted statement. Once we switch to go1.10, we should investigate replacing the `bytes.Buffer` with a `strings.Builder` which is almost equivalent except that it avoids an allocation and a copy in the call to `Builder.String()`.

**Comment by BramGruneir** [comment]
I'm actually going to reopen this.  I must have messed up somewhere as these number don't make sense.

I'll do some profiling and see if I accidentally added some new allocations.

**Comment by BramGruneir** [comment]
After spending in more time on this, I think at this point, without a significant re-write of `pkg/sql/pgwire/write_buffer.go` there is no way to make this work.  The `variablePutbuf` relies on `writeTo` to copy the bytes from one buffer another in the function `writeLengthPrefixedVariablePutbuf()`.  `strings.Builder` purposefully abstracts away the underlying `bytes.Buffer` and does not provide a `writeTo()` function or its equivalent.  There are also no functions to write from one string builder to another.  So doing so always requires an extra allocation of writing the buffer to a string, then adding that string to the wrapper buffer.

**Comment by BramGruneir** [comment]
To get there, I first simply replaced the the bytes buffer in /tree, but everything is built upon that.  So I went through and functions that used it needed to be converted as well.  This went on and on as tree has really deep tendrils.  I ended up changing buffers in the opt code as well.

It might be possible to decide where to wall it off, but I didn't see a clear dividing line.  

In the end, I think I've spent too much time on this already.

**Comment by knz** [comment]
I'll reopen but file for later then.

**Comment by BramGruneir** [comment]
Sure, the work I did is still in my [branch](https://github.com/BramGruneir/cockroach/tree/22777)

**Comment by knz** [comment]
Awesome thanks

**Comment by jordanlewis** [comment]
Tried this out a little today and it turns out it's a pessimization, because `strings.Builder` instances can't be reset the way `bytes.Buffer` instances can be - they have to throw away their backing buffers. This leads to more allocations overall, despite the fact that we remove the big allocation at the end during `.String()`, because we reuse `FmtCtx` in lots of places and expect that backing array to be reusable. So effectively this change trades off one big allocation for a few more smaller ones - and the first, original strategy that we use today is better.

Closing this issue.
