### ISSUE TITLE
Cockroach Transaction Implementation vs Warp Transactions

### ISSUE THREAD

**Issue by atrniv** [cockroachdb/cockroach#2279]
I'm interested in knowing how the transaction approach taken by Cockroachdb would compare to [Warp](http://dl1.frz.ir/FREE/papers-we-love/distributed_systems/warp-multi-key-transactions-for-key-value-stores.pdf) transactions in terms of performance. I've taken a look at the Calvin paper which I believe is the source of inspiration for cockroach. How would Warp compare to Calvin's approach ?

**Comment by vivekmenezes** [comment]
It's going to be very hard to compare these without having an
implementation for Warp. Nonetheless I don't see anything in the paper
suggesting that it would be an improvement. In particular a description of
the flow of a transaction in the absence of contention would be useful in
understanding the non-contention case and making a guess as to how it would
perform. In the case of cockroach the non-contention case overhead is one
extra write to mark the transaction record as committed.

Thanks for pointing the paper out.

Vivek

**Comment by spencerkimball** [comment]
A fairly big difference with warp transactions (IIRC) is that they progress
sequentially through all affected nodes, which could feel inefficient in
the case of a distributed txn which touches many keys.

**Comment by atrniv** [comment]
@vivekmenezes , I believe HyperDex has an implementation of Warp called [Hyperdex Warp](http://hyperdex.org/download/), which they [claim](http://hyperdex.org/performance/warp/) introduces almost no serious performance overhead (only 1.8% slowdown).

@spencerkimball, I'm guessing the actual propagation delay could be quiet tolerable especially if all the nodes existing with the same data center. I'm not sure too sure how well it would work in a Multi DC setup though. Also they claim that multiple machines lead to increased throughput when there are a large number of keys since the work gets distributed. There would also be an upper limit to the latency which would depend on the total number of servers in the system.

**Comment by mrtracy** [comment]
I would approach that particular benchmark with skepticism, as there is no information given on how to repeat that experiment.  In particular, there is no information on how they synthesized a result in plain HyperDex for a transactional benchmark (TPC-C) even though it does not have transactions. They must have somehow ran the equivalent operations in a non-concurrent environment, but their method is unclear.

Comparing Warp and CockroachDB's transaction strategy, they're different enough that I would expect them to have different performance profiles for different transactional loads.  Warp involves a thicker client which builds up a list of read keys and a list of writes, and then submits them to the server in a single message when the transaction is committed.  Cockroach actually performs work on the server while the transaction is in progress, and when it calls commit() all values have already been persisted. 

Both use optimistic concurrency control, although cockroach may abort a transaction sooner whereas Warp will only detect an aborted transaction during commit.  However, Warp will never persist data until it is sure that the transaction will succeeds, which may give it an advantage in the case of highly contentious writes.

That said, CockroachDB keeps historical values for every key, allowing consistent historical reads across the database at a timestamp, *without* a transaction.  Even if HyperDex recorded historical values (it doesn't), it's unclear that Warp would support this scenario without an additional mechanism for synchronizing timestamps. Consistent reads across the datastore would provide a considerable performance advantage for many workloads.

My biggest issue with Warp is that it depends on a deterministic sequential processing of transactions across the nodes involved in a transaction; overlapping transactions have to access nodes in the same order or it will not work correctly.  This ordering is provided by a central coordinator node; however, details are relatively sparse on how that ordering is maintained as the cluster changes due to failures or rebalances. This is a *very* complicated problem to get correct, and i'm surprised to see so little detail about it in their papers. From a cursory reading, I also question whether Warp's basic commit process is sufficiently resilient; the "backwards pass" looks like it could partially commit a transaction in the event of a significant data center outage in the middle of that pass.

On the surface Warp would likely offer improved performance in the case of highly contentious writes, because it would not persist anything to disk that doesn't commit; however, Cockroach's model will offer much better performance for read-only transactions. The performance on non-contentious operations seems likely be a wash between the two strategies, although Cockroach may actually prove better because it will involve less network overhead.  That said, I have much more confidence in the resiliency of Cockroach's model in the face of cluster changes and misfortunes.
