### ISSUE TITLE
sql: identify the queuing time separately in query stats

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22896]
Prior to #22277 there was no server-side input queue so queries would get executed as soon as they were reused. With #22277 now a query can stay in a queue server-side for a little while before it gets processed. 

This waiting time can and should be measured and reported.

(Requested by @andreimatei )

**Comment by jordanlewis** [comment]
@andreimatei where is this input queue? Do you want to do this for us? Seems like you could probably knock it out more quickly than others.

**Comment by andreimatei** [comment]
The "input queue" is the `StmtBuf` - that's where queries (and generally, commands) sit in between being read from the network (by `pgwire.conn`) and being processed (by `connExecutor`).
Realistically, I can't take care of this issue; my stack is way to deep at the moment, sorry.
I think there's a bit more to the context then "requested by @andreimatei" would let you believe. If memory doesn't fail me, I was arguing that we're measuring too many latencies that I didn't think they were valuable and then I used this as an example of something we don't measure. So I think I was arguing against some other measurements, not for more of them. However, I don't think this issue is necessarily invalid. I'm basically washing my hands :).

**Comment by jordanlewis** [comment]
Any clues on what the "too many measurements" part was about?

**Comment by andreimatei** [comment]
Maybe parsing time... although now I wouldn't argue against that one. I don't remember well; I think there was some measurements structure that was in my way when refactoring the Executor that I was hating on.

**Comment by jordanlewis** [comment]
We don't think this is necessary to track for now.
