### ISSUE TITLE
Multiraft: coalesced heartbeats

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#229]
To reduce the overhead of heartbeats when there are a large number of raft groups, we want to ignore outgoing MsgHeartbeats sent by raft. Instead, we want to send a single heartbeat message for each pair of servers, and then expand those on the receiving side into a heartbeat for each matching group.

**Comment by tschottdorf** [comment]
will try to make timely progress, evaluating the work needed for beta in the progress.

**Comment by tschottdorf** [comment]
@bdarnell: Is the procedure below what you had in mind for grouping outgoing heartbeats? Am I missing something?
- for each node, count the ticks since the last grouped heartbeat was sent (map[uint64]int), updating on every tick
- outgoing heartbeats addressed to a node with idle tick count below heartbeat timeout are discarded.
- any outgoing message resets the above heartbeat counter for the recipient node, triggering a heartbeat if the counter was above threshold.

Everything would happen in `state#start`.

**Comment by bdarnell** [comment]
We don't need to track the time since the last heartbeat was sent on a per-node basis. Just send heartbeats every N ticks to all connected nodes at once. Just ignore all outgoing heartbeat messages in Ready.Messages. Whenever we get a heartbeat response, create a MsgHeartbeatResp message for each group and send it into raft. 

In the long run we may actually want to reverse this - only inform raft when a heartbeat has been missed, instead of when one has been received. However, let's keep it simple for now, to avoid complication the implementation of leader leases.

**Comment by tschottdorf** [comment]
doesn't a node pair that's busy talking to each other technically not require any heartbeats at all? With the above, we'd always send heartbeats, and then even to all hosts at the same time. Sounds like something to avoid, but probably it just doesn't matter at this point?

**Comment by bdarnell** [comment]
That's true, but your third bullet point has it backwards - we reset the heartbeat counter for any incoming message, and send heartbeats on tick whenever the counter reaches a threshold. I think I'd save this for a future optimization.

**Comment by tschottdorf** [comment]
I've run into one more minor complication, namely the need to come up with CommandIDs. They're owned by the client and must be unique per group. The best I can really do (unless I want to do excessive bookkeeping on my discarded heartbeats) is pick a random string and a) risk that I'm colliding with an earlier command that is still pending or b) check my random id against all pending commands (in which case I could still have a later user command collide with me, but alas). Is either of those good enough?

**Comment by bdarnell** [comment]
No, you don't want to go through propose(). Heartbeat messages should have Type, From, and To set, with all other fields left at zero. I wouldn't construct a Ready object (since handleRaftReady is probably where you'll drop the raft-generated outgoing heartbeats); just call client.raftMessage directly.

**Comment by tschottdorf** [comment]
Another issue:

The only possible location to fan out an incoming heartbeat appears to be multiraftServer.RaftMessage but the nodes and groups are hidden away in the internal state, which isn't accessible and wouldn't support exposing that information well without adding a lock. How should I go about this?
We might also want to split up the groups by node so that the list of groups per node doesn't require a full sweep of all groups.

Also I've noticed that raft/multinode doesn't check the group IDs of incoming messages in step(). Is that something that can't be an issue?

**Comment by bdarnell** [comment]
I think multiraftServer.RaftMessage should pass the incoming message on a channel into the state's select loop (This is how it used to work. I pulled out the channel when it didn't seem necessary, but this is a good enough reason to add it back).

Adding a map of groups by node seems like a good idea.

MultiNode.step probably does need to check the group IDs of incoming messages.

**Comment by tschottdorf** [comment]
@bdarnell WIP is here: https://github.com/tschottdorf/cockroach/tree/coalesced_heartbeats
It's unfinished, but if you have comments that could reduce the amount of rewriting later. Could you take a look?
