### ISSUE TITLE
roachtest: rework interface for test registration

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#22942]
roachtest sets up tests in a way that leaves no good place to document them. We should consider changing that, so that `godoc` and `roachtest run --help` show what individual tests are trying to accomplish.

@petermattis wrote:

> I've been wondering if the interface for registering tests is too narrow. Perhaps we should view this more like how cobra commands are registered. That is, there is a cobra.Command struct that you file in. Easy to go overboard here.

**Comment by petermattis** [comment]
Do we think a test will ever need to spin up more than a single cluster? Currently, every test has a few lines like the following:

```
c := newCluster(ctx, t, nodes)
defer c.Destroy(ctx)
```

Rather than this programmatic cluster creation, I think we should change tests to declare what type of cluster they want. The advantage to doing so is that we can enhance the test runner to schedule tests. Currently, we have a `--parallelism` flag, but what we really want is to be able to specify how many cpus (and in which zones) are available for use. Tests would then declare what resources they need and the scheduler would dole them out, making sure we don't exceed the limits. This sadly is starting to sound like the type of resource scheduling that container orchestration systems use, but I don't see a way of using something off the shelf. I'd try to keep the scheduling simple to start with (i.e. greedy, just make sure we don't exceed the quotas).

A declarative interface to cluster creation would tie into a reworked interface for test registration. I'm imagining something like:

```
type TestSpec struct {
  Name string
  Help string
  Nodes []NodeOptions
  Run func(t *test, c *cluster)
}
```

There would be helper functions to construct `[]NodeOptions`, specifying machine type, zone constraint, geo distribution, etc.

@benesch, @danhhz, @tschottdorf Thoughts?

**Comment by tschottdorf** [comment]
> Do we think a test will ever need to spin up more than a single cluster? Currently, every test has a few lines like the following:

Yes, that's conceivable, for example when checking that linking two clusters accidentally does not lead to any problems. However, whatever abstraction you introduce, that test could just peel it back.

**Comment by petermattis** [comment]
> Yes, that's conceivable, for example when checking that linking two clusters accidentally does not lead to any problems. However, whatever abstraction you introduce, that test could just peel it back.

Ah, good point, though I don't think there is any restriction here with my proposal. Recall that cluster refers to a set of machines. Given that set of machines, you can create 1, 2 or N cockroach clusters.
