### ISSUE TITLE
server: Raft proposals hang indefinitely when node runs out of disk space

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#23119]
It appears that a node running out of disk space can cause raft proposals to hang indefinitely.

On one of our test clusters, one node ran out of disk space rapidly due to issue #23117.  Before crashing, the node was in a bad state for about 2 hours where several requests hung indefinitely.  By checking the current goroutines, we determined that many of these requests were hung waiting for a proposal in `replica.tryExecuteWriteBatch()`; however, the node crashed, and took all debug information with it (no logs were recorded due to lack of disk space), so we have no further information on where other threads may have been stuck.

Once the node crashed, the cluster quickly recovered; however, before it crashed, it was causing requests to hang indefinitely (over two hours in this case).  This had the effect of causing all time series writes and queries to hang on the cluster, meaning that diagnosing this problem was somewhat difficult.

**Comment by bdarnell** [comment]
We should set up a separate partition for logging so we can get some information when this happens.

The node is supposed to crash whenever we have a failure writing to disk. Maybe an error inside a rocksdb background compaction is leaving the DB in a weird state?

**Comment by bdarnell** [comment]
The test cluster that experienced this hang A) was configured with `--logtostderr` and B) `stderr` was a pipe, the other end of which was connected to `supervisord`. My guess is that for whatever reason, `supervisord` stopped reading from the pipe when the disk filled up. Then when cockroach got its `ENOSPC` error in `handleRaftReady`, it calls `log.Fatal` which tries to write to `stderr` before exiting. If the write to `stderr` failed, the process would go on to crash, but since it's just blocked waiting for the other side of our pipe to be consumed. 

Once we're in the log.Fatal path (or panic handlers; I'm not sure how many places we need to do this), we need to call SetWriteDeadline on stderr to put a bound on how long we can wait here. Or we could call `alarm(3)` or `setitimer(2)` to set a more complete limit on the whole process (which would cover the sentry reporting, etc). Unfortunately go's aversion to posix means that I don't think these calls are exposed (and even if they were, the experience of hitting these deadlines is not the best).
