### ISSUE TITLE
cli/conn+config: ux annoyance: ui shows "host:port"; cli takes --host, --port separately

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/cockroach#23277]
While trying to decommission a dead node following the instructions in the [Remove nodes doc](https://www.cockroachlabs.com/docs/stable/remove-nodes.html#remove-a-single-node-dead), the `./cockroach node decommission 4 --wait=live --insecure --host=localhost:26257` command gave the following error even though localhost:26257 is a live node: 

```
Error: unable to connect or connection lost.
Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).
Failed to connect to the node: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Failed running "node" 
```

Whereas `./cockroach node decommission 4 --wait=live --insecure` did decommission the node.

**Comment by vilterp** [comment]
Looks like you're supposed to split out `--host` and `--port`: `cockroach node decommission 4 --wait=live --insecure --host=localhost --port=26257`.

This could use a better error message; something like "couldn't connect to `localhost:26257:26257`", which is probably what it tried…

**Comment by Amruta-Ranade** [comment]
Interesting. Wouldn't the user go to the Admin UI, check the hostname, and use that in the command though? In any case, we need to make the syntax clearer in the Docs then.

**Comment by vilterp** [comment]
Hm yeah the commands in the docs say `--host <address of live node>`. They should probably say `--host <host of live node> --port <port of live node>`. Filing a docs issue is in order I think.

**Comment by vilterp** [comment]
But yes, it's annoying that you can't just copy/paste the `host:port` from the UI into the command.
- We don't want to change the UI, since `host:port` is nice and compact and easy to read.
- Could change the command, e.g. to take `--address <host:port>` instead of `--host <host> --port <port>`, but we'd have to make the change backwards compatible (to avoid breaking scripts that use the old flags). Could have both forms, but having two sets of flags that specify the same information seems bad.

**Comment by bdarnell** [comment]
The UI could hide the port if it's the default. 

We could also encourage the use of the `--url` flag which incorporates all the client flags (host, port, insecure, etc). We already have two sets of flags that specify the same information.

**Comment by vilterp** [comment]
Maybe a little "copy to clipboard" icon next to the `host:port` in the UI which copies the URL to your clipboard would be useful. Then you can paste that into CLI commands for the `--url` flag.

**Comment by couchand** [comment]
I did not even know `--url` was a thing.  We should definitely encourage that for most commands.  There doesn't seem to be much of a reason to advertise separate flags.  In fact, can we just deprecate them?  Is there a use case that the more general `--url` flag doesn't solve?

I'm not keen on the other suggestions here, mostly because they wouldn't really address this issue.

**Comment by a-robinson** [comment]
> In fact, can we just deprecate them? Is there a use case that the more general --url flag doesn't solve?

Having the same flags on the client commands as on `cockroach start` makes them easier to use for newcomers, since they can just specify the same flags for e.g. `cockroach sql` that they did for `cockroach start`.

There's also the issue that the URLs are confusing, at least for secure mode. Every time I want to run `kv` against a secure cluster I have to spend a couple minutes figuring out the right incantations for including each certificate file in the URL and then another minute or two painstakingly typing out the paths to each file. If I'm lucky, I can find it in my bash history, otherwise I have to come up with something like `postgres://root@localhost:26257/?sslmode=verify-ca&sslrootcert=/Users/alex/.cockroach-certs/ca.crt&sslcert=/Users/alex/.cockroach-certs/client.root.crt&sslkey=/Users/alex/.cockroach-certs/client.root.key`.

**Comment by couchand** [comment]
Oh that's unfortunate.  I had hoped that the URL flag would just be shorthand for the host and port flags, where you could omit defaulted fields, like:

- set host and port `--url=foobar:26258`
- set just host, default port `--url=foobar`
- set just port, default host `--url=*:26258`?

But now that I think about it, of course it's the connection string-style URLs.  That's unfortunate.
