### ISSUE TITLE
ui: inconsistent drop down placement

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23403]
<img width="651" alt="screen shot 2018-03-05 at 3 02 37 pm" src="https://user-images.githubusercontent.com/6201335/36997067-7beef9ce-2086-11e8-8b3c-5aa0132abb83.png">

<img width="663" alt="screen shot 2018-03-05 at 3 02 29 pm" src="https://user-images.githubusercontent.com/6201335/36997081-7f0e9f2e-2086-11e8-98d7-a9895bf0923a.png">

Notice in the above screenshots that the vertical distance of the drop down differs. Eye-balling, it looks like the second drop down has twice the vertical displacement as the first. I'm guessing this is a one line change, but feel free to push to 2.1 if it is more significant.

**Comment by couchand** [comment]
Hmmm, this appears to have been an issue for quite a while (at least since last fall, investigating back into embedded.go seems like more trouble than it's worth).  In theory it shouldn't be a big change, but tracking down exactly where it's coming from may be a small undertaking.  We can keep it in 2.0 for now, but it seems like a low priority investigation.

**Comment by petermattis** [comment]
> We can keep it in 2.0 for now, but it seems like a low priority investigation.

The lowest of low priorities.

**Comment by vilterp** [comment]
Ugh. Maybe while we're mucking around with the CSS to fix this we can also fix #20818

**Comment by vilterp** [comment]
Worth noting that the menu also shows up below the click box in the cluster viz toggle:

![image](https://user-images.githubusercontent.com/7341/36999588-954ec5e0-208e-11e8-84b5-264510cefec7.png)
