### ISSUE TITLE
Thrift API Suggestion

### ISSUE THREAD

**Issue by froderick** [cockroachdb/cockroach#2341]
Exposing a thrift  interface rather than protobuf would open this datastore up to a much larger audience as many more languages have thrift support out of the box. Cassandra, BigTable, and HBase all do this and it has worked quite well for them.

**Comment by petermattis** [comment]
Hi froderick,

We don't have any active plans for a thrift interface, but would be happy to see one contributed. We're also considering whether we can co-opt one of the existing database protocols (e.g. postgres). I'd also note that adding a thrift interface should not be particularly challenging as the (SQL) client protocol itself is fairly simple.

**Comment by bdarnell** [comment]
I don't think adding a thrift interface would be a good idea. Supporting new input formats means new dependencies to keep up to date and potential vectors for security problems (see for example the multiple rails vulnerabilities from a couple of years ago: http://www.kalzumeus.com/2013/01/31/what-the-rails-security-issue-means-for-your-startup/). Each new input format should be carefully justified. 

Right now we have protocol buffers as the preferred option, with json as a fallback when protobufs are unavailable. Introducing thrift wouldn't open the doors to any new users since those users could always use json instead. It would just be a performance improvement for users who can use thrift but can't use protobufs, and that doesn't seem like a large enough audience to target for an invasive performance optimization.

**Comment by petermattis** [comment]
I'm not seeing the connection between the ruby-on-rails vulnerabilities with using yaml and cockroach db supporting alternate transport protocols. Yes, each additional transport protocol enlarges the security surface, but the risk seems manageable. Have there been security vulnerabilities due to protobuf, Thrift or cap'n proto (or any another transport/message format)?

**Comment by bdarnell** [comment]
The rails/yaml vulnerability was an extreme case because the ruby yaml implementation was so egregiously insecure, but in general features that are exposed to the network but are less commonly used are prone to vulnerabilities (the SSL heartbleed and renegotiation bugs come to mind). I'm less concerned about the thrift parser itself than the parts we'd have to layer on top of it (integration with authentication, etc).

The risk is certainly manageable, but it will have to be managed, which involves cost/benefit tradeoffs. How large is the audience for whom thrift would be the preferred interface, and how much better is it for them than the alternatives? And the costs are not just security-related - the thrift code generator would be another component to add to our build system.

**Comment by tamird** [comment]
It also bears mentioning that the underlying protocol will likely be unimportant for nearly all users, who will consume Cockroach via a language-specific SQL driver, so adding `{thrift,capnp}` support will only affect driver authors, which is a tiny audience to begin with.

**Comment by froderick** [comment]
Thanks for the responses. Creating language-specific drivers makes sense to me.
