### ISSUE TITLE
ui: cluster capacity usage inaccurate when multi-node cluster runs on same machine

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#23596]
When running a cluster with only one live node the admin ui looks like this and reports the capacity usage correctly.

![screen shot 2018-03-08 at 1 38 39 pm](https://user-images.githubusercontent.com/507390/37169548-34d4ab40-22d6-11e8-8ea1-f5dbc6c5b803.png)

However, when I enable more nodes the capacity usage reports

![screen shot 2018-03-08 at 1 38 57 pm](https://user-images.githubusercontent.com/507390/37169586-4d96b524-22d6-11e8-91b3-d4914c994af0.png)

I'm assuming the capacity of the cluster is going down when more nodes are added to the same machine. I'm not sure if this is expected, but seeing a cluster capacity usage over 100% feels odd.

Note: labelled it under UI because that's where I saw it, but it may be a deeper issue.

**Comment by tschottdorf** [comment]
We could fingerprint the store directories and deduplicate based on that. I'm not aware of a simple way to do that though, and the cockroach process may not have sufficient privileges to do so. I'm also not sure this isn't just a WONTFIX, though it comes up from time to time. It turns out it's what we do most of the time...

**Comment by petermattis** [comment]
I believe there are OS specific mechanisms to determine a UUID per device. I don't recall the details off hand. It doesn't seem worth fixing, though this does come up periodically.

**Comment by tschottdorf** [comment]
https://liquidat.wordpress.com/2007/10/15/short-tip-get-uuid-of-hard-disks/
https://apple.stackexchange.com/questions/107953/list-all-devices-connected-lsblk-for-mac-os-x

**Comment by bdarnell** [comment]
We could also address this with our "start a local cluster" docs (since the only time it's ever a good idea to start multiple nodes on one machine is when you're following along with that doc). Setting all of the `--store` flags to something like `--store=path=node1,size=10GB` would adjust the way the UI displays this, right?

**Comment by couchand** [comment]
We've previously discussed this decided to document it and not do anything further.  I'm closing, but if someone feels strongly that we need to do something more, feel free to reopen.

**Comment by couchand** [comment]
@Amruta-Ranade it may be worth incorporating @bdarnell's suggestion into the docs updates as well.

**Comment by Amruta-Ranade** [comment]
@couchand Created #2706 to track the doc update
