### ISSUE TITLE
backupccl: very slow at end

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23685]
Near the end of a backup the progress stalled around 95% for 10s of minutes. It has since progressed a bit, but is taking a much higher expected amount of time. Attached are the stack dumps from the 4 nodes in the cluster. Notably only the first file has anything from backup.go.

[1.txt](https://github.com/cockroachdb/cockroach/files/1798477/1.txt)
[2.txt](https://github.com/cockroachdb/cockroach/files/1798478/2.txt)
[3.txt](https://github.com/cockroachdb/cockroach/files/1798479/3.txt)
[4.txt](https://github.com/cockroachdb/cockroach/files/1798480/4.txt)

**Comment by dianasaur323** [comment]
Hmm.. the backup eventually failed with this error message in show jobs: exporting 2 ranges: batch timestamp 1520628334.075470582,0 must be after GC threshold 1520630724.527421605,0

I'm running another backup, and it seems to be having the same problem since it has been running for a while. I can't tell if this is because the cluster itself is unhealthy, or if there is some other backup problem. I'm going to run this today on a single machine and see what happens.

**Comment by mjibson** [comment]
That message can occur if the backup's AS OF time (which is `now()` if unspecified) is older than the GC time (default 25 hours). So if the backup takes a really long time to execute, it can get into this state.

**Comment by dianasaur323** [comment]
ah, yes you're right. So I ran this on a healthier cluster with no under-replicated ranges, and the backup / restore worked successfully, and was uber fast. That makes me think that backup / restore just doesn't work well on unhealthy clusters. I'm leaning towards closing this, since that behavior honestly isn't that unexpected?

**Comment by mjibson** [comment]
I agree.
