### ISSUE TITLE
ui: remove all back links everywhere

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#23682]
When you click into the aggregated node, and see just the nodes in a circle, and then click into a node, it takes you to this screen:

![image](https://user-images.githubusercontent.com/5768024/37229270-7bfd0216-23b1-11e8-833b-72a98092509a.png)

The back button takes to back to the node list instead of the drilled down nodes in a circle, which is what I would expect. Pressing the browser back button does what I would expect though.

**Comment by couchand** [comment]
We actually talked about this previously (I can't remember where...) and the decision was made to remove all of those back links everywhere.  Haven't gotten to that yet, I'd forgotten about that conversation until you brought it up.

@josueeee I think it was you that suggested removing the back link?

**Comment by nstewart** [comment]
Just so we have a record of this in case it comes up again: was the decision to remove all backlinks because it will take too long to make them route correctly, or because we think they are no longer a good idea in general? Or something else?

**Comment by couchand** [comment]
@nstewart the explicit back-links are fine when pages form a strict hierarchy -- we always know where "back" is.  they fall apart when you have a richly-connected web, where pages can freely link among one another.  we could handle that with some effort, but since they don't add value above what's provided by default by the browser, they don't seem to pull their weight.

**Comment by kuanluo** [comment]
Removing all back links doesn't seem to be right solution, despite how it might solve this particular issue. 

> they fall apart when you have a richly-connected web, where pages can freely link among one another. 

This implies that we need to spend time on thinking this through in 2.1, and less on feature development. 

cc: @josueeee @piyush-singh

**Comment by couchand** [comment]
As a general rule I think we should spend zero time building things that the browser already provides.

**Comment by vilterp** [comment]
It's an "up" link, not a back link. Not the same as what the browser provides.

**Comment by couchand** [comment]
As I said above, it makes sense only as long as the pages are organized as a strict hierarchy, which is rare in general.  The original bug report is a great example:  @dianasaur323 got to the node details page not from the node list, but from a specific locality on the node map.  Having a link at the top of the page that claims to go back, but actually takes you to a different place makes no sense.  What is "up" from node details -- the node list or the node map?

**Comment by vilterp** [comment]
Reopening since that commit was changed to only removed them from some pages.

**Comment by vilterp** [comment]
@couchand you're right that "should 'up' from node details be map (& which locality) or list" is a question with no good answer. That's why I hope we can find a way to fit both the map and the nodes treetable on the same page! (like in @josueeee's early designs and [my old prototype](http://petevilter.me/dashboard-prototype/)) Then (a) you can see the whole hierarchy, including the node you came from, at a glance, and (b) the question of what state the page should be in goes away, since there is less page state. Let's play around and see what we can do…

Re: a hierarchy being rare in general: you can fit just about anything into a normalized structure where you have top-level tables, and detail pages that link to each other (and back up to their tables). e.g.

```
- localities/nodes treetable & map
  - node detail
- databases/tables/partitions treetable
  - table detail (link to nodes, queries, jobs, zone configs)
- jobs table
  - job detail (link to tables)
- queries table
  - query detail (link to tables, nodes)
- zone configs table
  - link to nodes, partitions, tables
- etc
```

This is what the [admin-ui-as-airtable experiment](https://airtable.com/shrcpm6BrNRlTC2Ep/tblia4ZwJIHCy4IH8/viwUIr5akU5RXTZ9i) is trying to show.

**Comment by josueeee** [comment]
I agree that all the up buttons should be removed since they are confusing in terms of navigation; more so now that we have a node map and figuring out how to define what "up" means is not a priority. As @couchand mentioned, web browsers provide the support a user needs to move back and forth between different page states. @vilterp has some great ideas in terms of how we can rethink our IA and utilize stronger UI patterns to create a rich, contextual experience that doesn't abstract away relevant information while drilling down to the details. And this seems like an issue to explore for 2.1 while we think through usability problems with our UX or as Andrew said "eating our vegetables".

**Comment by vilterp** [comment]
Here's a somewhat contrived example user flow (pardon my janky google docs viz):
![image](https://user-images.githubusercontent.com/7341/37734665-38d059c8-2d22-11e8-9eba-6b592ed636c4.png)

0. User starts on queries table
1. "down" to a specific query (to see why it was slow)
2. "across" to a table that was read by a query (to look at schema, indices, etc)
    - see that a backup or restore job was running on this table
3. browser back to the query to see when it was running
4. browser forward to the table again
5. "down" to job detail to see exactly what it was doing
6. "up" to jobs, to see how frequently a job like that runs
7. on jobs page, see that it's every night; my queries probably won't be slow that often.

Maybe it doesn't make sense because we don't have a job detail page, but I think this example shows how "up" is different than "back". I suppose they're redundant since you can click in the sidebar to get to the top-level "index" view, but I still like always having "up" in the top left, like in the GCP console.

This example also relies on something else we should do: on detail pages, show a filtered table of related objects. E.g. on table detail page, show jobs and events affecting it. (Captured in #6304 and #6305).

**Comment by jordanlewis** [comment]
Most people on this issue don't work here anymore, and I don't think we have consensus on doing this work.
