### ISSUE TITLE
sql: stabilize configuring zones through SQL

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23791]
Our current syntax for configuring zone configs through SQL is clunky and very much intended to be temporary:

```
ALTER TABLE ... EXPERIMENTAL CONFIGURE ZONE 'constraints: ["+foo=bar"]
num_replicas: 2'
```

I propose stabilizing a very similar command with a thin layer of syntax sugar:

```
ALTER TABLE ... CONFIGURE ZONE WITH gc.ttlseconds = 90, num_replicas = 5;
```

This reuses the `WITH ...` options syntax that we use in `BACKUP` and `RESTORE`, and feels very similar to cluster settings. The only sticking point is handling constraints. The simple approach is to keep the existing constraint syntax:

```
ALTER TABLE ... CONFIGURE ZONE WITH constraints = '{"+a=1,+b=2": 2}';
```

That's pretty gross, though. We could introduce custom syntax:

```
ALTER TABLE ... CONFIGURE ZONE ADD POSITIVE CONSTRAINT a = 1 AND b = 2 FOR 2 REPLICAS;
```

Or we could just call the `constraints` field a JSON config value. That opens some cool possibilities

```
ALTER TABLE ... CONFIGURE ZONE WITH constraints = zone_constraint("+a=1, +b=2", 2) || zone_constraint("region=germany");
```

where `zone_constraint(reqs[, num_replicas])` is a built-in that produces the JSON object `{"reqs": num_replicas}`. I think I have a preference for this option.

/cc @petermattis @a-robinson @BramGruneir

**Comment by a-robinson** [comment]
> I propose stabilizing a very similar command with a thin layer of syntax sugar:

LGTM

> That's pretty gross, though. We could introduce custom syntax:

I'm not a big fan of introducing custom syntax in addition to the JSON/YAML.

> Or we could just call the constraints field a JSON config value. That opens some cool possibilities

This is pretty interesting, assuming that providing the existing syntax would still work. I don't have a good gauge for how much clearer it really is than the JSON, but I've already spent time familiarizing myself with that so I'm pretty biased. If you think this is clearer, I'm ok with it.

**Comment by petermattis** [comment]
> `ALTER TABLE ... CONFIGURE ZONE ADD POSITIVE CONSTRAINT a = 1 AND b = 2 FOR 2 REPLICAS;`

I have an aversion to this syntax. Either of the other proposals for specifying constraints looks fine. For simplicity and consistency with the command line syntax, we could start with `constraints = '{"+a=1,+b=2": 2}'`.

**Comment by tschottdorf** [comment]
@awoods187, when you know which team will tackle this issue, could you update the `A-` label and remove the CF&S project? Thanks!

**Comment by knz** [comment]
I looked into this and thanks to a broken/incomplete implementation of the Go yaml package, it is not possible to marshal a value using the single-line YAML syntax standalone.

This means that if we choose to accept single-line YAML input for individual zone config settings, it won't be possible to pretty-print a valid SQL statement that achieves the same. That's quite a bummer.

(I don't want to modify the `yaml` package to fix this!)

So personally I'd go for:

```sql
ALTER ... ZONE SET gc.ttlseconds = 90, num_replicas = 5, constraints = '{...}' ; -- constraints use JSON
```

and

```sql
ALTER ... ZONE USING '{...json...}'; -- to set all values
-- for example:
ALTER ... ZONE USING '{"gc":{"ttlseconds":90},"num_replicas":5,"constraints":{...}}';
```

and if we really want to preserve YAML (I'm personally :-1: but could be convinced otherwise):

```sql
ALTER ... ZONE USING 'yaml: ...yaml...';
-- for example:
ALTER ... ZONE USING 'yaml: {gc: {ttlseconds:90}, num_replicas: 5, constraints: {...}}';
```

The `yaml:` prefix unambiguously determines that the rest of the string will be yaml, since it cannot appear at the beginning of a JSON zone config. The advantage of this approach is that we can also assemble YAML strings programmatically.

Again, I repeat, it will not be wise to support the syntax `ALTER ... ZONE SET constraints = '...yaml...'` because of the yaml marshaler problem I wrote initially. So if we do want to continue supporting YAML, this must be restricted to the top-level assignment.

**Comment by benesch** [comment]
Seems silly to make decisions based on what our YAML package supports. I'd prefer to fix the YAML package. I'll volunteer myself to do so!

**Comment by knz** [comment]
What's needed is a `Marshal()` method that calls the non-exported `marshal()` method with a tag set to "flow" (instead of the empty string).

But in addition to that yaml compatibility problem, it is the case that we support many more functions and operators to manipulate JSON values, and (in comparison) none for YAML. I'd rather support a single built-in function `yaml_to_json(string) -> json` which produces a json object with the right structure given the (backward-compatible) yaml string, and make all the SQL interfaces use JSON. This will open up, as you initially suggested, opportunities for even more expressive constructs. 

WDYT?

**Comment by benesch** [comment]
I submitted a PR upstream that allows creating a YAML encoder that always encodes values with a particular flow style: https://github.com/go-yaml/yaml/pull/381

But I'm also OK with your `yaml_to_json` proposal!

**Comment by benesch** [comment]
By the way, I'd prefer if we kept the existing constraint syntax where the constraints field is either a map from constraint specifiers to num_replicas or an array of constraint specifiers:

```sql
ALTER ... ZONE SET ..., constraints = '{"+foo,+bar": 2, "+baz" :1}'
ALTER ... ZONE SET ..., constraints = '["+foo", "+bar"]'
```

**Comment by a-robinson** [comment]
Thanks for fixing upstream, @benesch. Using that along with the `ALTER ... ZONE SET gc.ttlseconds = 90, num_replicas = 5, constraints = '{...}' ;` syntax sounds great.

And I agree with @benesch about keeping the existing constraints syntax.
