### ISSUE TITLE
sql: introduce PUBLIC pseudo-role for virtual schema privileges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#23818]
Virtual schemas (`information_schema`, `pg_catalog`, etc.) are a little funky when it comes to privileges. All users have permission to query them, but they do not actually [store](https://github.com/cockroachdb/cockroach/blob/523c056ba5ef398ce4e54467ae1c7db408b4dc7e/pkg/sql/virtual_schema.go#L199) any privileges on their descriptor. This leads to [strange cases](https://github.com/nvanbenschoten/cockroach/blob/94c25be0f5dcbde7d64d1caa15c93d0b5c4cff83/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L670) where certain places show that users don't have sufficient privileges to SELECT from them. We should fix this.

The reason why this is a little tricky is that privileges are stored on descriptors as `(user, privilege)` pairs. We could add a privilege pair for every user in existence at the time of virtual table initialization, but this still creates an issue for new users created after virtual table initialization. We could work around this by modifying the privilege list when we create a new user, but this is a bad path to start going down.

Luckily, Postgres has the same issue and has solved it with their `PUBLIC` pseudo-role. Documented [here](https://www.postgresql.org/docs/current/static/sql-grant.html#SQL-GRANT-DESCRIPTION-OBJECTS), the keyword indicates that
> the privileges are to be granted to all users/roles, including those that might be created later. PUBLIC can be thought of as an implicitly defined group that always includes all roles.

We should introduce a similar concept and use this to correct the privileges we expose for virtual schemas.

**Comment by mberhault** [comment]
This is definitely the right approach and should be straightforward enough. We'll have to be careful with any existing user named `public`, and see if any real tables need their descriptors migrated (if it's all virtual tables, I think we're in the clear, otherwise we'll need migrations).

The privilege check itself should be straightforward enough, just inject `public` as a role the user is a member of in the permission check logic. Privilege-related builtins often exclude `public`, but that should be fine too.

I suspect this probably falls on my plate.
@awoods187: I'm not sure if we want to track this roadmap-wise, but you should at least know about it. Assuming no complications (famous words!), this should be small.

**Comment by awoods187** [comment]
got it--and is this different than moving privileges to the system table that we discussed before?

**Comment by mberhault** [comment]
Very, this is only about adding a semi-fake role (semi-fake in the sense that all users are assumed to be members of it without explicit memberships). This is needed for making something (eg: the information tables) accessible to all users without some weird hacks.

**Comment by awoods187** [comment]
Got it--can we do both in 2.1? (right now system tables are in)

**Comment by mberhault** [comment]
Who's on point for system tables? (and don't look at me)
