### ISSUE TITLE
Can a RocksDB MANIFEST file get lost when the file system runs full?

### ISSUE THREAD

**Issue by jgehrcke** [cockroachdb/cockroach#23899]
One of our customers reported that their file system ran full, resulting in an on-disk corruption of the database state. That occurred with CockroachDB 1.0.6.

We are not entirely sure how exactly they extended the file system but after what they claim to be a "disk extension" they saw the following error:
```
cli/error.go:68 cockroach server exited with error: failed to create engines: could not open rocksdb instance: IO error: /path/to/cockroach/MANIFEST-268898: No such file or directory
```

The claim is that they did not manually mess with anything in `/path/to/cockroach/...`. Since we did not control this environment and are not 100 % sure about all steps performed this is not a bug report. My main intention is to ask: Are we certain that CockroachDB/RocksDB retains the last known good state on disk in the event of write failures of all kinds? Is there any known way of losing a MANIFEST file?

Notably, this MANIFEST file appears to be the only file lost during the incident. That is, I believe that the 'full disk' event and the subsequent file system extension was handled properly from an ops perspective.

**Comment by bdarnell** [comment]
I've never heard of the MANIFEST file getting lost. In any case, the last good file should be preserved (that's why the filename is actually `MANIFEST-268898`. The only file rocksdb ever overwrites in place is the CURRENT file, which contains the name of the latest manifest. The old manifest shouldn't get deleted until the new manifest has been written under its new name and the CURRENT file has been updated to point to it).

I believe the writing of the MANIFEST file is pretty robust, although we have had reports of other problems after a disk runs out of space (either causing the server to hang when the error occurs or to crash immediately when restarted), so this is an area in which we're currently building out better testing.

**Comment by jgehrcke** [comment]
Thank you for the feedback! I am closing this because there is no specific action item left I believe.

> so this is an area in which we're currently building out better testing.

Great to hear that. In the real world we seem to have have more full file systems than we'd hope for ...
