### ISSUE TITLE
sql: accessing a system table always requires a database read; there's no caching

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#23937]
This code makes us not cache descriptors for system tables:
https://github.com/cockroachdb/cockroach/blob/ea5c8c66df2475f8827a6ba8848e3bbafe2942cb/pkg/sql/table.go?utf8=%E2%9C%93#L237-L241

This seems unfortunate to me - every time a lease is acquired we need to read the descriptor of the "system.lease" table. Moreoever, if I try to acquire a lease using a prepared statement (for the internal `insert into system.lease...` statement, the preparing does yet another read - which is how I've noticed this because some test freaks out because there's now more reads. It's unfortunate that I have to think about these things.
I feel like surely there must be something we can do - the descriptors for tables that change the least we read the most...
For example, could we cache the "system.lease" descriptor and condition it on the cluster version? Schema changes to this table already have to be hella special, if they're even possible at all.
@knz, what do you think?

**Comment by knz** [comment]
Just for context, note that "reading the descriptor from KV" for a system table is not too costly -- the data for these descriptors is gossiped and is always cached in RAM.

**Comment by knz** [comment]
But I agree we should think making this better.
I think this is one of the use cases that will improve once we advance @vivekmenezes 's agenda on descriptor usage.

**Comment by andreimatei** [comment]
> Just for context, note that "reading the descriptor from KV" for a system table is not too costly -- the data for these descriptors is gossiped and is always cached in RAM.

Is that true? Maybe the descriptor are cached, but the "name to id" mapping I don't think is. Check out this trace: https://github.com/cockroachdb/cockroach/blob/5dfa16cdd279ddd5a794e95b0aae145cfbe2978c/pkg/sql/logictest/testdata/logic_test/show_trace#L297-L300
The highlighted lines show us resolving the name for the "system" database (I think) and for the "lease" table. And that'll happen every time a lease on the "lease" table is requested. Maybe I was wrong above about the `tableCollection` code being the cause, but I think someone's doing something silly somewhere.

**Comment by vivekmenezes** [comment]
One area of silliness is in TableDescriptor.validateCrossReferences() which is called from TableDescriptor.Validate. We need to really consider not running this check. I'd originally thought TableDescriptor.Validate only running validation within the TableDescriptor protobuf but it's calling out to the store and also validating the database.

**Comment by petermattis** [comment]
> Is that true? Maybe the descriptor are cached, but the "name to id" mapping I don't think is. Check out this trace:

The "name to id" mapping is the contents of the `system.namespace` table which is gossiped. Whether that is actually used is a different question.

**Comment by nvanbenschoten** [comment]
> The "name to id" mapping is the contents of the system.namespace table which is gossiped. Whether that is actually used is a different question.

We're almost certainly not.

When running a million splits on a 128 node cluster I noticed that logging to the rangelog was responsible for a majority of time spend in AdminSplit. Tracing showed that executing the `INSERT INTO system.rangelog` statement resulted in 4 namespace table lookups (id 2) and 5 descriptor table lookups (id 3). This is pretty terrible.

https://github.com/cockroachdb/cockroach/blob/30031b2e19353af33811ace08094248f121ede73/pkg/sql/table.go#L219-L229

says that we can't use the normal lease mechanism for system tables because of a circular dependency there. Avoiding the cache entirely in these situations seems like a pretty blunt instrument and I'm worried about the phrasing there that implies that this decion was made in order to allow tests to pass. @vivekmenezes we should take another look at this and determine exactly which system tables fundementally need to avoid the cache. We should then match against exactly those tables in this check.

In the meantime, I'm going to run the same test with this check adjusted to allow use of the cache when accessing the rangelog.

**Comment by nvanbenschoten** [comment]
> In the meantime, I'm going to run the same test with this check adjusted to allow use of the cache when accessing the rangelog.

Doing so sped up my pre-splitting by about 60%, dropping it from around 20 minutes to around 8. It also didn't look like splits were getting clogged up anymore, although that's hardly scientific and is coming from me staring at the `performing split %d of %d` logs and finding that there were no longer any long pauses.

**Comment by vivekmenezes** [comment]
@nvanbenschoten when adding RoleMembersTable exception in there I believe I did try using the cache with other tables and it did seem to work at the time. It's just that there was some observed flakiness and I was not sure, and I didn't have any particular performance concerns. If there are performance issue I think we can add to the whitelist and consider eventually opening this up with a more thoughtful change.

**Comment by vivekmenezes** [comment]
I'm cool with allowing caching of the rangelog schema for sure!

**Comment by vivekmenezes** [comment]
#35555

**Comment by knz** [comment]
yeah #35555 indeed closes this.
