### ISSUE TITLE
ui: QPS inconcsistent on metrics summary, node map, and time series

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#23967]
Cluster viz qps is off by a factor of 3. Are we using a different methodology for this page vs the metrics dashboard?

![image](https://user-images.githubusercontent.com/894257/37544019-ee135480-2939-11e8-9930-bc656a55ad40.png)

![image](https://user-images.githubusercontent.com/894257/37544035-020a7cf2-293a-11e8-972d-3d2817f61183.png)

**Comment by nstewart** [comment]
Actually it looks like the metrics dashboard is inconsistent. The timeseries chart shows 1/3 the qps as the summary

![image](https://user-images.githubusercontent.com/894257/37544155-6a798ae4-293a-11e8-935c-2cf0f12583cf.png)

I know the time series chart is a 10s moving average, but this load is stable so this discrepancy is confusing

**Comment by couchand** [comment]
The apparent inconsistency here is due to the different things being measured.  The Summary shows the total of all statements executed, which includes the queries listed in the SQL time series chart to the left, but also includes DDL statements and transaction boundaries.  The QPS listed for nodes & localities on the node map is the sum of these basic SQL statement types, not including the DDL & transaction statements.

Specifically, the summary uses the metric `cr.node.sql.query.count`, which includes begin, commit, rollback, as well as DDL statements (and "miscellaneous" statements).  The time series chart SQL Queries shows `cr.node.sql.select.count`, `cr.node.sql.insert.count`, etc. but not the DDL or transaction statements.  If you navigate to the SQL dashboard and scroll to the bottom, the Transactions chart shows `cr.node.sql.txn.begin.count` and other transaction handling statements, and the Schema Changes chart shows `cr.node.sql.ddl.count`. There isn't a chart showing the miscellaneous statements (which is probably fine since they're not likely to be very significant?).  Add all of those up and you'll get the total listed on the summary.

The confounding factor here is that the query count on the node map just uses the sum of the selects, inserts, updates, and deletes, but does not include the DDL or transaction managing statements.

There's probably some usability improvements we could make here: in particular we should always use the same definition for QPS.  It's probably alright for that not to match the SQL Queries chart (it seems like DDL almost certainly should be included).  I'm not as certain about transaction statements, those don't seem like queries in the same way.  We should perhaps see what other systems use to report QPS, decide what to define it as, and use that everywhere.

**Comment by couchand** [comment]
I assigned this to 2.1 initially, but the change won't be significant, so we could potentially add it to a 2.0 patch release.

**Comment by nstewart** [comment]
Ping on this one. @piyush-singh can we get some sort of fix, even if its just a label change so the two charts don't have the same label if they are measuring different things (and do some of the things @couchand suggested in a future release)? It is really hard to demo the web ui in public with these two numbers potentially being significantly out of sync. Right now MovR shows 1,179 QPS in the summary, but only 250 "Queries" in the overview dashboard. 

Having to explain that and answer questions around it distracts from whatever performance points we were trying to make in a live situation. 

cc @vilterp
