### ISSUE TITLE
backupccl: write to google cloud: context deadline exceeded

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23983]
While running a backup to GCS on master I saw:

`exporting 3655 ranges: write to google cloud: context deadline exceeded`

Maybe our write deadlines aren't actually per request? Dunno what's going on here.

**Comment by mjibson** [comment]
We possibly need to wrap the writes in a retry loop with a short timeout instead of a long timeout with a single try?

**Comment by bobvawter** [comment]
The way that [`gcsStorage.WriteFile`](https://github.com/cockroachdb/cockroach/blob/5b336cef9f086009ff9ea61191d8513562cbeaa8/pkg/ccl/storageccl/export_storage.go#L657), we create the deadline context before constructing the retry loop for an individual operation.  I think this is correct, since if we set the deadline inside of the retry loop, we'd actually take up to `maxAttempts * timeoutSetting`.

I'm thinking at this point what we really need is some kind of minimum-throughput setting for read and write operations, and not a timeout per se.  If the throughput is less than so many Mbits/sec for the last N minutes, fail the request.  Perhaps that's what #23859 really ought to be about?

**Comment by benesch** [comment]
This happened in the backup test last night, but only on master:

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/579134:id/20180319-579134/backup2TB/test.log

I'm extremely perplexed, though. How are we hitting a 30 _minute_ timeout? We're only writing max 64MB, right?

**Comment by mjibson** [comment]
The connection is maybe cut or stalled by something in the middle and it has to be restarted, is our current guess. We don't think it's a bandwidth issue. This other PR should fix that.

**Comment by benesch** [comment]
That makes a lot of sense.
