### ISSUE TITLE
`client.Txn`: set status for elided `EndTransaction`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2399]
`client.Txn.send` may silently drop `EndTransaction` calls if the transaction is read-only. The client may reasonably expect `Txn.Proto.Status` to be in a terminal state (committed or aborted) after sending an `EndTransaction` call, so when `Txn.send` drops an `EndTransaction`, it should update its in-memory `Transaction.Status` (to committed if there were no errors, or aborted if there were).

This would let us remove the setting of `Status` in sql/server.go.

From #2396.

**Comment by tamird** [comment]
Minor correction: `Transaction.Status` should be set to `proto.COMMITTED` if the elided `EndTransactionRequest` had `Commit: true` and to `proto.ABORTRED` if the elided `EndTransactionRequest` had `Commit: false`.

**Comment by tschottdorf** [comment]
Why don't we just set `txn.Proto = nil` and use that as the condition? After all, you're not supposed to use the `Txn` object for anything after the transaction has ended, and hand-changing the proto feels awkward. If that doesn't pan out, and if we make sure that hand-changing the proto (which isn't something we ought to do) remains limited to this one place and properly documented, I'm ok with it.

**Comment by bdarnell** [comment]
Setting `txn.Proto` to nil seems to leak more implementation details than modifying the proto. If we don't believe that `client.Txn` can accurately modify the proto, how can we be confident that eliding the EndTransaction is the right thing to do?

Other options include unexporting `client.Txn.Proto` and providing a `Status()` method, or figuring out how to remove the use of `Transaction.Status` from the sql package entirely.

**Comment by tamird** [comment]
> Other options include unexporting client.Txn.Proto and providing a Status() method

This isn't an option since the `sql` package needs to set `Txn.Proto` from the session.

> or figuring out how to remove the use of Transaction.Status from the sql package entirely.

This is probably a sane thing to do, but if we had some other package that used transactions the way `sql` does, we'd need to duplicate `Status` there too. I think the original suggestion in this issue is the way to go.

**Comment by tschottdorf** [comment]
After some reflection I also think the original idea is best. We can check
the incoming txn status easily in TxnCoordSender, and it's a good
compromise between avoiding the call and having weird client state. Sorry
about the back and forth.
On Sep 8, 2015 18:16, "Tamir Duberstein" <notifications@github.com> wrote:

Other options include unexporting client.Txn.Proto and providing a Status()
method

This isn't an option since the sql package needs to set Txn.Proto from the
session.

or figuring out how to remove the use of Transaction.Status from the sql
package entirely.

This is probably a sane thing to do, but if we had some other package that
used transactions the way sql does, we'd need to duplicate Status there
too. I think the original suggestion in this issue is the way to go.

—
Reply to this email directly or view it on GitHub
<https://github.com/cockroachdb/cockroach/issues/2399#issuecomment-138617214>
.
