### ISSUE TITLE
server: /_admin/v1/settings endpoint exposes settings values to un-authed users

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#24028]
So far we've treated settings values as sensitive and visible to `root` only -- e.g. `SHOW ALL CLUSTER SETTINGS` is super-user only and we even scrub the values out of the event log for settings  changes so that they don't show up in the un-authed UI.

The current endpoint returns everything to any client that has network access, which does not seem in-line with the above, or the recent push to gate the cluster's data behind at least `remote_debugging`.

It seems like we should a) restrict http access based remote_debugging b) scrub values in a way [similar to the scrubbing we do for diagnostics reporting](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/updates.go#L318).

I think the endpoint was added for `debug zip` -- if we can tell it apart from other traffic (grpc vs http? write a nonce to the store dir?), we could let it keep dumping un-scrubebd values for all types while scrubbing for all other callers. 

cc @a-robinson

**Comment by a-robinson** [comment]
As discussed with @dt offline, for this to be consistent with our past decisions we'll need to completely disallow serving this via HTTP regardless of the `server.remote_debugging.mode` setting, since otherwise it'd be exposing to anyone with UI access information that we've already deemed too sensitive to include in the event log.

It'd be really nice if we were able to systematically distinguish between sensitive and nonsensitive settings to expose them in more places for debugging, but that's a separate conversation.

**Comment by a-robinson** [comment]
For 2.0, we either need to reuse the diagnostic reporting scrubbing or disable the endpoint.

Are you going to handle that or should I?

**Comment by dt** [comment]
I'll add the scrub tonight for 2.0, and it'll just redact the string values for `debug zip` too if we're okay with that?
