### ISSUE TITLE
client: remove `TestConcurrentIncrements`

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2409]
This seems to duplicate what's already tested in `TestTxnDBWriteSkewAnomaly`.

**Comment by tschottdorf** [comment]
Isn't that one of the correctness tests? Those are not really fun if they
fail. Would be nice to keep the simple test is we can afford it. Besides,
in my wip I'm seeing failures which are only caught by acceptance tests
(TestSingleKey) , so I would like to hijack this issue to instead update
TestConcurrentIncrements so that it catches that bug if that's OK with
everyone.

**Comment by tamird** [comment]
I guess I'd have to see the bug and update you're proposing before I could comment further.

**Comment by tschottdorf** [comment]
above comment now applies to #743.
As for the test, I don't think we should remove it. The anomaly test may verify the same thing, but it's much harder to reason about.

**Comment by tschottdorf** [comment]
This looks like it can close. @tamird?

**Comment by tamird** [comment]
sure
