### ISSUE TITLE
sql: add memory budget info to node_statement_statistics

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24216]
The `crdb_internal.node_statement_statistics` table keeps a blueprint of each type of query encountered along with latency information.

It would be helpful to feed memory accounting information into this table as well. For each individually executed query, I think it's enough to hold on to the maximum budget used by the respective query (on the local node), and to track the average, variance, and perhaps max of that.

@knz does this seem straightforward to implement and/or do you have a better suggestion for where this should live? There's interest from an external contributor to tackle this.

**Comment by knz** [comment]
I think this needs to keep the high water mark in each monitor, which we haven't done so far. It's doable, but will need some benchmarking to evaluate the overhead.

Once the metric is in place, adding the stuff to node_statement_statistics is relatively trivial and well-contained, so indeed a good project for an external contributor.

**Comment by tschottdorf** [comment]
Thanks @knz! So two steps here, track the high water mark in each monitor and see whether that shows up in profiling (what would we profile?) and, pending success of that, do the `crdb_internal` plumbing.

cc @garvitjuniwal in case this is something you're interested in tackling on your end.

**Comment by knz** [comment]
I wasn't thinking about profiling but rather a straight before/after latency delta measurement.

**Comment by dianasaur323** [comment]
Should we consider whether or not we want to continue building out crdb_internal.node_statement_statistics? I think it may be time for us to consider making this more user facing, and include some toggles in case people don't want to track all of this profiling all the time?

**Comment by neeral** [comment]
@tschottdorf @knz I've started looking at this.
I've some questions on what we want to measure, that you could help clarify.
- Completed statements in-scope (at least for first cut) - this is in-line with existing latency measurements.
- How do we measure distSQL statements? From reading, the latency measurements are computed only on the gateway node. What would be appropriate for memory usage? Some ideas: only consider memory usage on gateway node, aggregate mem usage across all nodes that participate in the distSQL flow, show breakdown of mem usage by node.

**Comment by knz** [comment]
cc @asubiotto who has been working on collecting this info for distsql queries. Alfonso perhaps you can provide some feedback / guidance?

**Comment by asubiotto** [comment]
I recently put up a PR to collect this information in the `hashJoiner`: https://github.com/cockroachdb/cockroach/pull/24909, however, I'm going to go with a simpler approach of adding a high watermark to a memory account. This will allow us to collect the high water mark of memory used per processor participating in a distsql query.

I think it's important to note that this sort of statistic collection should not be on by default and thus should not appear in the `node_statement_statistics` table due to the cost of collecting this information. The general approach we discussed a couple of weeks ago that I still agree with is that node_statement_statistics should offer a high level view by default which can provide information for deeper dives into a query's execution by tracing it. These statistics could be collected by some form of `EXPLAIN (DISTSQL,ANALYZE)` that would annotate a visual query plan with processor statistics, aggregate node statistics, and general query statistics.

The nice thing that `node_statement_statistics` does is make this collection relatively automatic so I think that the step after the above is to allow the user to specify some sampling rate which would cause some queries to be traced and have some execution stats output to the table. I believe sampling is part of the opentracing specification so this would not be too much work.

I'm actively working on all this stuff except the last paragraph. Here is a tracking issue: https://github.com/cockroachdb/cockroach/issues/19476.

**Comment by neeral** [comment]
Great @asubiotto. I'll wait for  #19476.

**Comment by jordanlewis** [comment]
This is done.
