### ISSUE TITLE
backupccl,importccl: support open source storage servers for backup / restore / import

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#24224]
Minio is an object storage server released under Apache License v2.0. It is compatible with Amazon S3 cloud storage service.

**QUESTION**

Can [Minio](https://github.com/minio/minio) be used for as a CockroachDB backup / import / restore source and target?

**Comment by dianasaur323** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/21412, which looks like you already found. This should work, but we would have to test to make sure. I can take a quick look at what this entails in terms of testing - if it doesn't take too long, I can run it quickly. otherwise, we can see if Premier already has anything set up, and see if it works with their existing setup. I should have time to look into this on Friday.

**Comment by knz** [comment]
cc @tim-o for next steps. what is the demand?

**Comment by tim-o** [comment]
@robert-s-lee - is this still needed?

**Comment by robert-s-lee** [comment]
Premier wanted to see if this would work.  Let me check if they ever tested.

**Comment by mjibson** [comment]
We can fix this today with a docs entry. If it's a higher priority and many people are having problems with it we can do a larger fix.

**Comment by mjibson** [comment]
Here's the comment with the necessary docs info: https://github.com/cockroachdb/cockroach/issues/21412#issuecomment-366524740
