### ISSUE TITLE
workload: add option to load fixtures without the use of an enterprise license

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#24331]
Currently, loading workload fixtures requires an enterprise license, since it uses RESTORE. However, we should have the option to also use IMPORT directly, at least for modestly sized datasets like TPC-C 1000. Without this, enterprise is required for all performance reproduction.

Assigned to @danhhz for triage and sanity checking. I'm happy to do the work if I got a little help on the details of what exactly this would entail.

**Comment by jordanlewis** [comment]
+1, this was also suggested in https://github.com/cockroachdb/loadgen/issues/176.

**Comment by danhhz** [comment]
The existing `IMPORT` that powers `workload fixtures make` is [hardcoded with the `WITH transform=<path>` option](https://github.com/cockroachdb/cockroach/blob/f7191bb7eb5926a53f45137e70c721b7d2d4be9b/pkg/ccl/workloadccl/fixture.go#L382), which writes out the backup files to `<path>` and exits. If this option is not used, then the cluster running the `IMPORT` will finish the data ingestion (and not write the backup anywhere external), which is what this issue is looking for.

My strawman for how to expose this on the cli is for `workload init` to take a new `--import` boolean flag that triggers this behavior instead of calling `workload.Setup`. `workload run --init` currently does the same thing as `workload init`, but `workload run --init --import` seems pretty odd to me (plus presumably the import will take a while which would be weird to sneak in before running the queryload), so I think we make people use `workload init` if they want this new import behavior.

One important thing to note is that `IMPORT ... WITH transform=` is currently rock solid, whereas the one without `transform=` is just coming out of experimental, so it's worth actually testing this end to end before telling people to use it.
