### ISSUE TITLE
libroach: Evaluate other compression options

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#24362]
RocksDB supports [several kinds of compression](https://github.com/facebook/rocksdb/blob/89d989ed75ed89e756156d1f82e123b24591be8c/include/rocksdb/options.h#L56-L77). We currently use snappy, but that may not be the best choice. According to [benchmarks by facebook](https://github.com/facebook/zstd#benchmarks), LZ4 is faster, and several algorithms compress better (zstd does well on both the compression ratio and speed dimensions, and the ubiquity of zlib is appealing). 

It's also possible (as noted in #24243) to use different compression for different levels of the sstable stack. It might make sense to use higher compression for L6 sstables and faster options for the higher levels.

Note that we tried LZ4 in the RPC layer (way back in #804) with mixed results. Since adding a new C dependency is a pain we should hack together some benchmarks before we decide to integrate any of these libraries. 

Jira issue: CRDB-5770

**Comment by petermattis** [comment]
I recall experimenting with using `LZ4` for RocksDB compression a long time ago and not being able to measure a performance difference vs snappy, but I can't find any notes on precisely what I did or what workload I was testing. Definitely worthwhile to revisit this.

**Comment by mqudsi** [comment]
If I may butt in here, snappy's true benefit is if using a custom dictionary. I'm not sure what kind of data you're compressing, but that might be something to explore. 

If you don't know what type of data you're going to get either (i.e. user-defined), zstd is probably the best all-around compression library you could go with right now for "generic" content. zlib's ubiquity aside, it's not a good choice for any modern technology.

(Also note that snappy delineates between the framing and the compressed content. A lot of libraries claiming compatibility are upstream compatible with the compression content but not the framing, so that could break things for you down the line.)

**Comment by benesch** [comment]
> It's also possible (as noted in #24243) to use different compression for different levels of the sstable stack. It might make sense to use higher compression for L6 sstables and faster options for the higher levels.

https://github.com/facebook/rocksdb/wiki/Compression suggests there might some performance cost to this, as RocksDB can no longer perform "trivial moves" between levels that use different compression. Tradeoff might still be worth it, of course.

> If I may butt in here, snappy's true benefit is if using a custom dictionary. Otherwise, there are definitely better options. I'm not sure what kind of data you're compressing, but that (a custom dictionary) might be something to explore.

@mqudsi, I'm not sure I follow. What do you mean by custom dictionary? AIUI Snappy builds a dictionary on the fly out of its input.

**Comment by mqudsi** [comment]
Un-stale: Still relevant.

**Comment by jbowens** [comment]
Closing in favor of cockroachdb/pebble#1582 and cockroachdb/pebble#1585.
