### ISSUE TITLE
roachtest: basic visualization of perf test output

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24366]
We have roachtests that are running `tpcc` and `kv` nightly, but no way to visualize the performance of these tests, either individually or over time. The `roachprod web` command does some simple visualization of either a single test or comparison of 2 tests. The current plan is to extract and adapt that functionality from `roachprod` and have `roachtest` generate a web page on its nightly runs.

Cc @jordanlewis

**Comment by tschottdorf** [comment]
I think it's worth taking a small step back here. Visualization of the results is one aspect, but lots of the roachtests would ideally also want to programmatically assert something about the metrics collected from a workload. They don't want to have to scrape a HTML page.

Can we come up with a shared interface through which any workload (or any other binary) can communicate with the test runner? Ideally this is possible while the workload is still running, so that the test can be aborted early.

Using prometheus is one such option but it's a pretty heavy one. Perhaps workload can open an http port and export a prometheus endpoint that we then check manually. This prevents aggregation, but `workload` can simply export gauges only, and these can then be checked. I imagine `prometheus` has a Go lib somewhere that parses `/_status/vars`. Or we can just use `debug/metrics` which uses json.

Workload can dump the endpoint to a suitable location when the test has finished. Visualizing the results should then take that dump as an input, making everything reusable.

@petermattis thoughts?

**Comment by petermattis** [comment]
> Visualization of the results is one aspect, but lots of the roachtests would ideally also want to programmatically assert something about the metrics collected from a workload. 

I'm considering this a separate chunk of work. I definitely do not want tests to scrape a webpage in order to make assertions. I very much want to explore utilizing the existing time series metrics for these test assertions. This issue is about something else: performance visualization.

**Comment by petermattis** [comment]
An initial cut of the perf dashboard is up. Remaining items before I consider this issue closed are to complete the end-to-end automation of collection of the perf data from nightly roachtests and processing of this data and to add more than just the `kv{0,95}` tests (e.g. `ycsb` and some `tpcc` configuration).

**Comment by nvanbenschoten** [comment]
8 months later and roachperf is hooked up end-to-end. There's still more we can improve there, but those improvements are tracked in https://github.com/cockroachlabs/roachperf/.
