### ISSUE TITLE
scripts: the introduction of bors broke the release notes script

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24418]
The release note scripts was assuming a specific commit message format for merge commits. bors-driven merges use a different formats, which confuses the script.

The script needs to be upgraded accordingly.

cc @jseldess @benesch @couchand

**Comment by couchand** [comment]
@knz I can look into it this afternoon.

**Comment by knz** [comment]
Cool thanks! Let me know if you need help. I know the code is probably hard to read.

**Comment by couchand** [comment]
Proposed solution:

Issue one: tracking release notes by PR from the git history.  Bors-generated merge commits are octopus merges, and they don't associate individual PRs with the merge parents.
Solution: use the GitHub-generated ref/pull to identify which PR each parent branch belongs to.

Issue two: Bors merges are authored by `craig[bot]`, not by the person who "clicked the green button" (or rather, in the case of Bors, issued the `r+` or `r=`).  This makes the section of "PRs merged by contributor" is ill-defined (according to @knz).
Solution: reorganize the section by group of contributors to each branch, rather than the individual who merged.

**Comment by couchand** [comment]
Issue one is high priority, needs to be addressed by Monday.   Issue two is lower priority, since it's not used in the official release notes.
