### ISSUE TITLE
ui: non intuitive time window selector: v2.0-rc.1	

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#24466]
![image](https://user-images.githubusercontent.com/894257/38305834-35439ecc-37c3-11e8-8eaf-e3ea27a49d09.png)

The time window selector appears to be primarily driven by how long a cluster has been running, not by a users filter habits. The web ui for new clusters starts with 10 min window by default. I came back to the ui after keeping a cluster up for a while and when I refreshed the window changed itself to `last 1 hour`, which wasn't what I wanted. I manually changed the time back to 10 minutes, but on refresh, it reverted to `last 1 hour`. This morning I was planning to analyze my cluster performance again and now the window keeps resetting to `6 hours`, which makes it very hard to answer the questions I need without a bunch of extra clicks.

There are two things here:
1. My filters should be sticky across refreshes
2. What is the sensible default for time window? It seems like it shouldn't vary by cluster uptime since I'm assuming the questions people want to ask are skewed towards more recent events by default. That decision is worth a second look.

**Comment by piyush-singh** [comment]
Since we've already started some discussion about reasonable defaults here, let's use this issue to sort out the best default values when viewing for the first time (and whether that should be user configurable). I've created  #24484 to track stickiness of selections across refreshes in a single session. We can knock that out quickly and continue discussion about ideal default behavior here.

**Comment by piyush-singh** [comment]
@couchand pointed out that the refresh issue should be solved by an older ticket #7778 that we will pick up over the next week and a half. Going to close my dupe in the meantime.
