### ISSUE TITLE
storage: should set BlockReads in GCRequest's ReplicatedEvalResult

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24538]
From #24209.

@nvanbenschoten wrote:

> If GCRequest is declared at clock.Now(), is it ignored by historical reads in the commandQueue? In that case, how does the synchronization work when we check that the requestCanProceed? Is it possible that a historical read passes this check but still finds that the keys it is trying to read have been GCed?

I wrote:

> I think you *might* be right and we should fix it but morally this won't happen. Note that we bump the thresholds in the first command that doesn't actually GC any keys. This means that in practice it's visible to all reads by the time we actually remove data. I think there's a scenario in which a read slips by the GC bump but gets stalled before opening a RocksDB snapshot, so that when it finally does we have actually already removed keys? Setting `ReplicatedEvalResult.BlockReads = true` should fix that problem.

**Comment by bdarnell** [comment]
`BlockReads` is a blunt instrument. There's no reason to stall all reads while the GC is being applied, we just need to do a better job of synchronizing the GC threshold check with the acquisition of a snapshot. 

I think we can actually move the GC threshold check to the end of the request instead of the beginning. If a read races with a GC, just let it proceed but replace its results with an error before returning to the client.

**Comment by tschottdorf** [comment]
How does this work post https://github.com/cockroachdb/cockroach/pull/28813?

I think what we can do is move the gcThreshold check to after the read has evaluated. My only concern is that this might tickle some bugs in the MVCC code that now gets to see unusual histories (but if memory serves correctly, GC produces valid histories).

**Comment by bdarnell** [comment]
I'd go with @nvanbenschoten's suggestion to check the threshold both before and after the read.
