### ISSUE TITLE
build: Abend compiling cockroachDB v2.0.0 on armhf (32bit)

### ISSUE THREAD

**Issue by giminni** [cockroachdb/cockroach#24544]
1. Please supply the header 
N.A.

2. Please describe the issue you observed:
Compilation ended with error (see below)

- What did you do?
Compile cockroachDB on armhf (32bit) with:
1. cd $GOPATH
2. go get -d github.com/cockroachdb/cockroach
3. cd $GOPATH/src/github.com/cockroachdb/cockroach
4. make build TAGS='stdmalloc'

- What did you expect to see?
Compiled binary bin/cockroach

- What did you see instead?

`go run pkg/cmd/docgen/{main,funcs}.go functions docs/generated/sql --quiet
# github.com/cockroachdb/cockroach/pkg/util/timeofday
pkg/util/timeofday/time_of_day.go:114:42: constant 3600000000 overflows int
# github.com/cockroachdb/cockroach/pkg/util
pkg/util/union_find.go:92:7: constant 4294967295 overflows int
Makefile:1219: recipe for target 'bin/.docgen_functions' failed
make: *** [bin/.docgen_functions] Error 2`

$ uname -a
Linux xu4svrp01 4.14.7+ #1 SMP PREEMPT Wed Dec 20 03:06:36 CST 2017 armv7l armv7l armv7l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

$ make --version
GNU Make 4.1
Built for arm-unknown-linux-gnueabihf

$ gcc --version
gcc (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519

$ go version
go version go1.10 linux/arm

$ bash --version
GNU bash, version 4.3.48(1)-release (arm-unknown-linux-gnueabihf)

$ cmake --version
cmake version 3.5.1

$ autoconf --version
autoconf (GNU Autoconf) 2.69

**Comment by nvanbenschoten** [comment]
Hi @giminni, thanks for the interest in CockroachDB! At the moment we don't have any plans to get the database working on 32-bit systems. In the past, compilation has succeeded somewhat by accident, but we don't have any confidence that there aren't 32-bit-specific bugs creeping in our codebase due to assumptions about word size. For example, we've never been strict about the distinction between Go's `int` and `int64` data types. On a 64-bit system, they're synonymous. However, on a 32-bit system, casting an `int64` to an `int` could result in data loss and very subtle bugs. For this reason and others, I don't think Cockroach will be officially supported on 32-bit systems any time soon, although there is an issue tracking its progress here: https://github.com/cockroachdb/cockroach/issues/8179.

That all said, we have recently made a small push to create unofficial arm64 release builds and improve the toolchain around 64-bit arm builds. If you're interested, you can follow our recent progress in [this thread](https://github.com/cockroachdb/cockroach/issues/20433).
