### ISSUE TITLE
backupccl: Backup command should support specifying a table-name pattern

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#24550]
Tracking issue for user interest.  This has been requested by one enterprise customer.

**Comment by dianasaur323** [comment]
Thanks for filing, @bobvawter. Let's decide how we want to approach this after we follow-up with the enterprise customers using backup / restore to figure out how mission critical this is. Filing in as 2.1 milestone for now so that it doesn't slip before we get a chance to decide how to approach this.

**Comment by bobvawter** [comment]
Linking for posterity: https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1523023390000299

**Comment by mwang1026** [comment]
Hasn't been mentioned since so closing. If interest, please reopen.
