### ISSUE TITLE
distsqlrun: make fast path for aggregator with fully ordered grouping columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24575]
We plan queries that use aggregates without a `GROUP BY` clause using the same aggregator code path as those that have a `GROUP BY` clause.

Unfortunately, the aggregator doesn't do anything special when it has 0 grouping columns, which means that for every row, the aggregator looks up the empty string in a hashmap and writes to its value. This is only a small inefficiency, but it shows up at up to 10% in a `pprof` profile. Let's fix it.

**Comment by abhimadan** [comment]
Since there are zero grouping columns in this case, it is vacuously true that all grouping columns are ordered. I think this will be included nicely as part of future work to make a fast path for fully ordered grouping columns which doesn't use a map (#24113 doesn't include this fast path, but a future PR will).

**Comment by jordanlewis** [comment]
Ah, right. Changed the title of this issue to reflect the work for fully ordered grouping columns.

**Comment by abhimadan** [comment]
Closed by #24933.
