### ISSUE TITLE
build: cmake 3.11.0 does not work with our makefile

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#24611]
This is on OSX 10.13.3 using brew.

Brew now installs and updates cmake to 3.11.0 and this is not compatible with out Makefile.

`make` will build librocksdb correctly, but then stop with the following (without an error):
```bash
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_impl_debug.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_bench_tool.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(rocks_lua_compaction_filter.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_impl_debug.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_bench_tool.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(rocks_lua_compaction_filter.cc.o) has no symbols
```

If you run `make` again:
```bash
GOPATH set to /Users/bram/go
Running make with -j8
go run pkg/cmd/docgen/{main,funcs}.go functions docs/generated/sql --quiet
make[1]: /usr/local/Cellar/cmake/3.10.3/bin/cmake: No such file or directory
make[1]: *** [cmake_check_build_system] Error 1
make: *** [libroachccl] Error 2
make: *** Waiting for unfinished jobs....
touch bin/.docgen_functions
```

To downgrade back to cmake 3.10.3, run the following commands:
1. `brew unlink cmake`
1. `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a169609a5dcd5bf0cb83c2d8ffc7da934b3d81fe/Formula/cmake.rb`
1. `brew pin cmake`

Once this is fixed, you should be able to run `brew unpin cmake` and allow it to upgrade like normal.

**Comment by benesch** [comment]
Ah, unsafe clean isn't properly cleaning up libroachccl. Oops.

**Comment by benesch** [comment]
For posterity:

  * You may need to run `make unsafe-clean` whenever you upgrade macOS, GCC, CMake, or any other tool used in the build that is not vendored.
  * There was a bug in `make unsafe-clean` that was preventing libroach from being cleaned up. I've opened a PR to fix that: https://github.com/cockroachdb/cockroach/pull/create?base=cockroachdb%3Amaster&head=benesch%3Aclean-libroach

P.S. Make does print error messages, but they're often not the last thing printed because of the way jobs run in parallel. Look for "waiting for unfinished jobs" to find the actual error message.
