### ISSUE TITLE
testing: run tests with metadata-test-off flag in nightlies

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#24702]
With the new metadata testing infrastructure, some of our tests are run with new processors which are added between the processors in the plan. This has led to some bugs being hidden. For example, the final post processing spec for some processors will not be "rendered" since they are not the final processor and some test cases will be missed.

The tests should be run with the `metadata-test-off` flag at least in the nightlies to ensure that these code paths are being executed.

**Comment by abhimadan** [comment]
This also happened in #24704, so it might even be worthwhile to run this in every CI run.

**Comment by pbardea** [comment]
That would be ideal if it doesn’t take too much of a toll on the CI completion time. 

Alternatively, we could run the meta tests tests in the nightlies and make the default the no meta tests. Since it seems to happen pretty frequently. I think Jordan also ran into similar issues.

**Comment by andreimatei** [comment]
Could the `metadata-test` thing be controlled by a logictest "config" (like we have for distsql on/off)?
Also can you elaborate a bit on what code exactly is disabled when we inject the metadata magic? What's the "final post processing" exactly? How come tests don't fail without it?

**Comment by abhimadan** [comment]
> Could the `metadata-test` thing be controlled by a logictest "config" (like we have for distsql on/off)?

I think it could. We could structure it as a subtest under the existing distsql tests, so there would be a metadata on/off mode underneath those.

> Also can you elaborate a bit on what code exactly is disabled when we inject the metadata magic?

The test essentially plans additional processors corresponding to each level in a `planNode` tree. This was mainly done because it was simple to do and the metadata processors should be allowed to be planned anywhere. However, it messes up `renderNode`s because the render is applied to the metadata processor, not the intended processor, which results in the `PostProcessSpec` of some processors differing in tests from outside of tests. This shouldn't affect the correctness of the tests, but it can hide other subtle bugs, as @pbardea has seen.

**Comment by abhimadan** [comment]
Assigning to myself for now. I'll look into adding the metadata tests as distsql subtests instead of being gated by a flag.

**Comment by abhimadan** [comment]
I think that's possible, but I think it would be fairly messy, and adding special-case logic for tests at that level of granularity seems unappealing. I also think there could be other possible disparities between metadata tests being enabled and disabled that we haven't encountered, and adding special case logic for those as well also seems unfortunate. I'd still prefer to have subtests for now, since it's a bit more future-proof.
