### ISSUE TITLE
sql: support window functions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2475]
http://www.postgresql.org/docs/9.4/static/tutorial-window.html

**Comment by nvanbenschoten** [comment]
Window functions are used by the Postgres JDBC driver in it's `getColumns` reflection method. Specifically, the method issues a query that looks like:

```
SELECT * 
FROM 
  (SELECT
    n.nspname,
    c.relname,
    a.attname,
    a.atttypid,
    a.attnotnull OR (t.typtype = 'd' AND t.typnotnull) AS attnotnull,
    a.atttypmod,
    a.attlen,
    row_number() OVER (PARTITION BY a.attrelid ORDER BY a.attnum) AS attnum,
    pg_catalog.pg_get_expr(def.adbin, def.adrelid) AS adsrc,dsc.description,
    t.typbasetype,t.typtype  
  FROM pg_catalog.pg_namespace n  
  JOIN pg_catalog.pg_class c ON (c.relnamespace = n.oid) 
  JOIN pg_catalog.pg_attribute a ON (a.attrelid=c.oid)
  JOIN pg_catalog.pg_type t ON (a.atttypid = t.oid)
  LEFT JOIN pg_catalog.pg_attrdef def ON (a.attrelid=def.adrelid AND a.attnum = def.adnum)
  LEFT JOIN pg_catalog.pg_description dsc ON (c.oid=dsc.objoid AND a.attnum = dsc.objsubid)
  LEFT JOIN pg_catalog.pg_class dc ON (dc.oid=dsc.classoid AND dc.relname='pg_class')
  LEFT JOIN pg_catalog.pg_namespace dn ON (dc.relnamespace=dn.oid AND dn.nspname='pg_catalog')
    WHERE c.relkind in ('r','v','f','m') and a.attnum > 0
      AND NOT a.attisdropped
      AND n.nspname LIKE E'company' 
      AND c.relname LIKE E'customers') c
    WHERE true  AND attname LIKE E'id' ORDER BY nspname,c.relname,attnum
```

where the `row_number() OVER (PARTITION BY a.attrelid ORDER BY a.attnum) AS attnum` part is the window function.

Because this JDBD method is probably used by all JVM ORMs, we're going to need to support window functions before we can support ORMs like Hibernate.

**Comment by petermattis** [comment]
Care to try and translate that query to english?

**Comment by nvanbenschoten** [comment]
It looks like the query is fetching all columns from `pg_catalog.pg_attribute` that are in the desired DB (`n.nspname LIKE E'company'`) and table (`c.relname LIKE E'customers'`). The key here is that they're running the `row_number()` window function, partitioned on the tableID and ordered by the column number. 

I'm actually not sure why this is required, because it seems like it's impossible for the query to need partitioning over multiple tables if the db name and table name are restricted, and a single table already has an attnum field anyway. The only reason I can come up with is: `"pg_attribute.attnum: The number of the column. Ordinary columns are numbered from 1 up. **System columns, such as oid, have (arbitrary) negative numbers**"`. Perhaps they want to have all column numbers be from 1 up, even for system columns. Another reason might be that `attnum` could have gaps in it from deleted columns, which they may be trying to avoid by using the window function.

I'm working on adding window function support right now, so hopefully we'll be able to support this in the near future.
