### ISSUE TITLE
ui: node list on narrow screen overflows without scroll

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#24844]
On a narrow enough screen (less than about 1100px in my inital test) the node list overflows its container on the overview page.  Unfortunately, the page is not horizontally scrollable, so the overflowing part of the table is just lost forever.

<img width="822" alt="screen shot 2018-04-16 at 4 58 44 pm" src="https://user-images.githubusercontent.com/793969/38834788-755c45da-4197-11e8-9df3-96d35c5ee19b.png">

File this under UI responsiveness.

**Comment by vilterp** [comment]
Note from IRL convo with @couchand: we may want to enable horizontal scrolling here, but that'd be weird, since horizontal would be internal scrolling (within the div containing the table) and horizontal would be whole-page scrolling.

In general, we should choose one or the other: either scroll the whole page horizontally and vertically, or scroll an internal div horizontally and vertically, but have the whole-page layout be fixed. The latter is what e.g. AWS's consoles do, and it works pretty well there.

**Comment by josueeee** [comment]
+1 on "scroll an internal div horizontally and vertically, but have the whole-page layout be fixed"

**Comment by couchand** [comment]
Just on this one page?
