### ISSUE TITLE
sql: weird behaviour with age date functions

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#24872]
I am playing with the date's age functions and something weird is happening.
The doc states the following:

<img width="751" alt="crdb_age" src="https://user-images.githubusercontent.com/3340262/38879600-52a1676e-4296-11e8-9774-1d5e2977b782.png">

So I would expect those 2 statements to be equivalent:
1) `select age(now() - interval '1 month', now());`
2) `select age(now() - interval '1 month');`

Yet they yield opposite values:
1)`-744h`
2)`744h`

**Comment by nvanbenschoten** [comment]
@tlvenn reading over this issue, it looked to me like we had a bug. However, I just confirmed that this is the correct behavior and that `age(timestamp1, timestamp2)` is meant to subtract the second timestamp from the first. See https://www.postgresql.org/docs/10/static/functions-datetime.html.

I think the confusion may be due to poorly named arguments. cc. @knz

**Comment by knz** [comment]
@tlvenn I just checked and postgres has the same behavior. The problem is the documentation for this function.

**Comment by tlvenn** [comment]
Thanks for the confirmation @knz, I suspected as much.
So the doc should probably say:
`Calculates the interval between the current time and val`.
