### ISSUE TITLE
build: cockroach fails to build on other archs, only build on x86-64

### ISSUE THREAD

**Issue by itamarjp** [cockroachdb/cockroach#24878]
please take a look in the builds.log

https://copr.fedorainfracloud.org/coprs/itamarjp/cockroach/build/742148/

same build in fedora koji, 

https://koji.fedoraproject.org/koji/taskinfo?taskID=26426138

I think should be interesting for cockroach to setup a github webhook to automatically lanch builds on copr.

**Comment by danhhz** [comment]
Hi, thanks for the suggestion! Unfortunately, we don't offer official support for other architectures at this time. We do have a best-effort ARM build that one of our engineers maintains; if you'd like to do something like that, we're always accepting PRs!

**Comment by itamarjp** [comment]
I think you should consider adding support for other arch's, in a short future you will start seeing alot of arm and risc-v servers, and fedora / rhel and centos will support all of them.

**Comment by itamarjp** [comment]
if you're interested in the github webhook to fedora copr, just tell me and I will provide you a spec file.

**Comment by benesch** [comment]
I'm going to close this out because I don't think there's anything specific to do here. We already support arm64, and issues #8179 and #6091 are tracking x86 and arm32 (though neither of them are likely to be supported soon). If you feel there is another specific architecture that we should support, please open an issue about that specific architecture.

We may look into triggering COPR builds once we provide an official RPM (#11783), but for now I don't think it makes sense.

Thanks for your interest in CockroachDB, though, @itamarjp!
