### ISSUE TITLE
sql: warn users when they use a special keyword function

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24921]
From https://forum.cockroachlabs.com/t/column-quoting-problem-leads-to-silent-select-failure/1551

CockroachDB supports several auto-conversions of keywords to function calls, for compatibility with PostgreSQL.

For example the keyword `USER` is replaced by `current_user()`.

This is unfortunate because it makes it super-easy to create invalid queries that do not fail with an error and instead return bogus results. For example:

```sql
CREATE TABLE foo("user" string);
SELECT * FROM foo WHERE user = 'bar';
```

Because the "user" keyword is not quoted in the SELECT query, the WHERE clause is really `WHERE current_user() = 'bar'`, which is unlikely to be what the client wanted.

Several avenues for improvement here:

- [ ] prevent any statement containing the bare user keyword in an expression if some "let's be sane" session variable is set (e.g. `sql_safe_updates`? a new one?)
- [ ] support a "new dev" mode which disables these keywords-are-functions and makes the dialect more regular
- [ ] highlight this pitfall in the docs

**Comment by bdarnell** [comment]
I suggest that we disallow the `user` keyword if any table (or view) referenced by the query contains a column named `user` (if they really mean the `user` keyword, they can use the less-ambiguous `current_user` name). I don't think we can silently reinterpret `user` as referring to the column instead of the function (that's more of a break from postgres compatibility than I'm comfortable with, even though I think it was dumb for postgres to give `user` this behavior), but I'd be OK with making this an error to alert the user to the need to quote references to a column named `"user"`. As long as it's restricted to queries involving tables with columns named `user` I think we could turn it on by default and not worry about a safe-mode flag.

**Comment by knz** [comment]
Ben with all due respect your suggestion does not make sense (to me).

The decision whether to allow the keyword named "user" is made during parsing. At that time, we don't have a syntax tree yet, much less any semantic information about which table(s) is being accessed, and therefore we cannot yet answer the question "does this involve tables with columns named `user`".

After parsing the keyword USER has been desugared to a function call, and we do not keep this information around (that a keyword has been desugared).

Introducing plumbing from parsing all the way through semantic analysis to the point of name resolution, just for the sake of deciding whether `user` should be accepted, seems unreasonable (to me).

**Comment by bdarnell** [comment]
Yeah, the plumbing and layering violations make this tricky. But we do preserve a lot of detail about the original input in other cases so that we can reconstruct something very close to the input, so there's some precedent for not just discarding the fact that it was desugared. 

My concern with any sort of safe mode that disables the `user` keyword entirely is that this sort of mode is rarely turned on when you need it. It needs to happen by default to make a difference, but then that hurts postgres compatibility. I was trying to find a change that is narrow enough that I'd be willing to break compatibility.

**Comment by knz** [comment]
Assuming we only care about USER specifically, my best suggestion would be to desugar USER to `current_user_with_warning()` and then detect that name during semantic analysis with a string comparison on the function name. That would be this propagation we're talking about.

And regarding your other comment, I see us having _more_ desugaring over time, not less.
