### ISSUE TITLE
redundant  raft heartbeat

### ISSUE THREAD

**Issue by wuweiweiky** [cockroachdb/cockroach#2493]
In multiraft state.start  when got ticker.Chan(),  s.multiNode.Tick() and s.coalescedHeartbeat() are called,   because s.multiNode.Tick()  will send hearteat,  so  s.coalescedHeartbeat() is redundant .

-----------------------------------------multiraft code-------------------------------------

case <-s.Ticker.Chan():
				if log.V(8) {
					log.Infof("node %v: got tick", s.nodeID)
				}
				s.multiNode.Tick()
				ticks++
				if ticks >= s.HeartbeatIntervalTicks {
					ticks = 0
					s.coalescedHeartbeat()
				}

**Comment by bdarnell** [comment]
`multiNode.Tick()` will send many heartbeats (one for every group this node is the leader of). We only want to send one coalesced heartbeat per interval, so we call `coalescedHeartbeat()` here and drop all the outgoing `MsgHeartbeat` messages in `handleWriteResponse`. 

This is important when `HeartbeatIntervalTicks > 1`. Since each group's tick count may not be aligned, `multiNode.Tick()` may try to send heartbeats on every tick. By discarding those ticks and maintaining our own count, we ensure that we only send coalesced heartbeats on the correct interval.
