### ISSUE TITLE
Are there any plan to support mysql protocal and grammar?

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#2494]
since mysql is very popular.

**Comment by vivekmenezes** [comment]
Frank,

 We are implementing a grammar close to Postgres with some improvements on
some fronts for our Beta release. As folks start using cockroach we'll
reassess on an ongoing basis
what additions we need to add to the language. We are not working on wire
compatibility for the Beta release, but we do understand the need for that
in the future and it will eventually get put on our road map.

We'd like to hear about features that you've found valuable that should be
considered for Cockroach.

Thanks

Vivek

**Comment by petermattis** [comment]
There are no plans to support the MySQL grammar and we've chosen to support the postgres wire protocol.

**Comment by kaeverens** [comment]
out of interest, is there a reason why you chose the PostGres variant?

**Comment by bdarnell** [comment]
The postgres grammar file was in a more easily reusable form, the protocol was better documented, and the postgres license terms are better for our purposes.

**Comment by ivanjaros** [comment]
Any changes with this? I'm asking because CDB provides all I am looking for in a DB but the simple fact that I need multiple queries to create table+index, to give a simple example, makes is too impractical for real use since it requires too much code alteration and tying my whole codebase to single db like this makes no sense. So I just wanted to see if there is maybe mysql-compatible protocol in the works before i move to tidb?
