### ISSUE TITLE
Where condition on pg_namespace is broken in 2.0.0

### ISSUE THREAD

**Issue by smarkwell** [cockroachdb/cockroach#25018]
Is this a question, feature request, or bug report?
Bug

**BUG REPORT**

Env
 - Windows 10 Pro 1709
 - Server version: CockroachDB CCL v2.0.0 (x86_64-w64-mingw32, built 2018/04/03 21:03:23, go1.10) (same version as client)

```
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.0.0 (x86_64-w64-mingw32, built 2018/04/03 21:03:23, go1.10) (same version as client)
# Cluster ID: c28c0534-9f7d-42f7-9639-4d018fbfa1a8
#
# Enter \? for a brief introduction.
#
warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
root@localhost:26257/> set database=test;
SET

Time: 1.129ms

root@localhost:26257/test> SELECT * FROM pg_namespace WHERE nspname="public";
pq: column name "public" not found
root@localhost:26257/test> select * from pg_namespace;
+------------+--------------------+----------+--------+
|    oid     |      nspname       | nspowner | nspacl |
+------------+--------------------+----------+--------+
|  330228340 | crdb_internal      | NULL     | NULL   |
| 1181682001 | information_schema | NULL     | NULL   |
| 1928221446 | pg_catalog         | NULL     | NULL   |
| 1548079034 | public             | NULL     | NULL   |
+------------+--------------------+----------+--------+
(4 rows)

Time: 6.7466ms

root@localhost:26257/test> create table test ( field1 INT, field2 INT );
CREATE TABLE

Time: 11.3851ms

root@localhost:26257/test> select * from test where field1 = 1;
+--------+--------+
| field1 | field2 |
+--------+--------+
+--------+--------+
(0 rows)

Time: 11.9261ms
```

2. Please describe the issue you observed:

- What did you do?

Attempting to filter a query on pg_namespace

- What did you expect to see?

A successful result set

- What did you see instead?

The filter condition is somehow treating the value as the column name

`pq: column name "public" not found`

**Comment by a-robinson** [comment]
Hi @smarkwell, I think you're hitting something that often confuses users who haven't used postgres before. In postgres (and consequently in cockroach because we strive for postgres compatibility), quotation marks (`"`) are used to refer to identifiers like table or column names. To quote values such as string literals, you have to use apostrophes (`'`), meaning you want to run `SELECT * FROM pg_namespace WHERE nspname='public';`.

For reference:
https://stackoverflow.com/questions/41396195/what-is-the-difference-between-single-quotes-and-double-quotes-in-postgresql
https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL

**Comment by bw-smarkwell** [comment]
Thank you, my apologies for the distraction, there is an upstream system that exposed this issue.
