### ISSUE TITLE
sql: figure out better way of triggering system config gossip

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2502]
Right now, we use the CommitTrigger on EndTransaction requests.
This is being set when the system tables are being poked in sql operations, on a op-by-op basis.
This is rather fragile. For example, delete/update don't set the trigger.

We should find a better way of doing this.

**Comment by spencerkimball** [comment]
Code was removed previously which checked for keys within the config prefixes section of the keyspace on write commands and re-gossiping as necessary. Perhaps we could create a method which accepts a slice of key ranges being modified which would trigger re-gossip. That method would be called from `executeCmd` on non-txnal write commands (with just key range for that command) and from the commit trigger on txnal write commands (supplying all intent keys modified by the txn).

The method would go through the slice of key ranges, and if any modified the system config, would re-gossip.

**Comment by mberhault** [comment]
I went with a trigger specifically to avoid having to examine all intents in the EndTransaction.
I'd rather avoid putting it back in, instead improving the sql-side logic that determines when to set the trigger.

**Comment by spencerkimball** [comment]
@mberhault, is this really fragile? How many issues have we had with it so far? Please close this unless you feel like there's still a reasonable expectation that work will / should be done here.

**Comment by bdarnell** [comment]
It matters for the new settings table - the changes we currently make to system tables are limited. If we're going to allow direct writes to the settings table then we'd need some way to make them trigger the gossip update. Or we make all settings changes go through `SET` so the table itself can remain read-only.

**Comment by bdarnell** [comment]
And separately the node liveness intent problem was because the only way we could trigger gossip was by wrapping the CPut in a transaction.

**Comment by dt** [comment]
sql writes are supposed to go through `row{Updater,Inserter,Deleter}` to calculate any row keys to write -- we could probably note in those when we're hitting a gossiped key?

**Comment by dt** [comment]
Er, actually, it looks like we already do this: delete/update/insert all call it via `startEditNode`: https://github.com/cockroachdb/cockroach/blob/c2026d86dbfbf5524b047c2574071907efb12084/pkg/sql/update.go#L95

**Comment by mberhault** [comment]
@a-robinson: I believe you're doing some system config work?

**Comment by a-robinson** [comment]
Nothing that will help with this, no. Just giving them their own zone configs.

**Comment by petermattis** [comment]
The most recent bit of fragility that was fixed was ensuring that txns which modify the system-config range are anchored on the system-config range (see `client.Txn.SetSystemConfigTrigger`). Closing as this seems stale and there are no additional concrete suggestions for improvements.

**Comment by bdarnell** [comment]
The node liveness GC issue was an indirect consequence of this: the liveness heartbeats should not logically be MVCC values, but we made them so because that was the only way to attach the gossip commit trigger to them. This in turn means that we're doing extra GC work here. 

The original motivation of this issue was that getting the transaction anchor correct was fragile, and I don't have a concrete suggestion there. But for the liveness issue, we could avoid forcing non-transactional updates into transactions by allowing some way to attach a gossip trigger to non-transactional updates (at least ConditionalPut, but ideally any update). It would be tricky to make this change to the liveness span now, but we should consider this next time we're changing anything here or introducing new gossiped spans.
