### ISSUE TITLE
storage: Don't require splits to complete before running replicate queue

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#25047]
Currently, the replicate queue requires that all splits complete before doing its thing (https://github.com/cockroachdb/cockroach/blob/5d39b641c4e2fffe354b35cc63daad0ddde7c86f/pkg/storage/replicate_queue.go#L117, https://github.com/cockroachdb/cockroach/blob/5d39b641c4e2fffe354b35cc63daad0ddde7c86f/pkg/storage/replicate_queue.go#L152).

This makes sense, because it's cheaper/less risky to send snapshots for smaller ranges than for ones that are bigger than the configured limit. However, this leaves the cluster susceptible to data unavailability/loss if a range fails to ever split for some reason. If we had a perfect track record of splits never getting stuck, this wouldn't be a big deal, but we have had some problems with ranges failing to split (e.g., https://github.com/cockroachdb/cockroach/issues/24966, https://github.com/cockroachdb/cockroach/issues/25036, https://github.com/cockroachdb/cockroach/pull/24896, https://github.com/cockroachdb/cockroach/pull/23310, https://github.com/cockroachdb/cockroach/issues/21357).

I suspect we'd be better off allowing replication even if size-based splitting was needed. Do you have opinions, @nvanbenschoten or @tschottdorf?

**Comment by tschottdorf** [comment]
Snapshots are currently pulled into memory on the receiving side, which I think is one of the original motivations for this restriction. With @nvanbenschoten [upcoming change](https://github.com/cockroachdb/cockroach/issues/16954) and possible elimination of other memory-blowup inducing code, we may be able to drop this coupling again, and I absolutely think we should do so once it becomes safe.

**Comment by nvanbenschoten** [comment]
I don't know the exact reason for introducing this restriction, but I suspect there were two main factors:
- ranges had no upper bound on size, so if they needed a split then that means they could have been arbitrarily large.
- large snapshots are expensive and potentially deadly because they buffer the entire range in memory.

The first factor is similar to the reason why we used to [prevent](https://github.com/cockroachdb/cockroach/pull/7788) snapshots when the range size was larger than 2x the `max_range_size`. We removed this restriction after we introduced backpressure that attempted to bound the size of ranges. The second factor is still valid, but will be addressed in #16954. Since we do a better job bounding range size and will soon remove the effective snapshot size limit, I think we can make this change shortly.

Whether we should make the change is another question. I personally would love to see it because it reduces the number of components that have dependencies on each other. As we saw in https://github.com/cockroachdb/cockroach/pull/20589, these dependencies can easily turn into cycles which create deadlocks, so it's almost always best to avoid them.

**Comment by a-robinson** [comment]
> I don't know the exact reason for introducing this restriction, but I suspect there were two main factors:

Those are definitely the factors -- there's a comment in the code I linked to that explicitly lays that out. Sorry for not including the full range of relevant lines in the original post:

https://github.com/cockroachdb/cockroach/blob/5d39b641c4e2fffe354b35cc63daad0ddde7c86f/pkg/storage/replicate_queue.go#L153-L157

> Whether we should make the change is another question.

That question is easy. Once the large snapshot problem is addressed, we should certainly remove the `repl.needsSplitBySize()` check. As is, splits not working can lead to under-replication/unavailability/data loss because we won't ever up-replicate the range even if nodes are lost.

**Comment by nvanbenschoten** [comment]
@andreimatei you just addressed this, right?

**Comment by andreimatei** [comment]
yup
