### ISSUE TITLE
ui: react rendering errors get swallowed

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#25102]
Errors thrown during render get mysteriously swallowed.  This has bitten us all at various times, but we haven't prioritized figuring it out.  Let's figure it out and make sure we fix it.

**Comment by vilterp** [comment]
Some of them end up here: https://github.com/cockroachdb/cockroach/blob/8a7030f00e653ddd35c5298ff496d3aa112f6abc/pkg/ui/src/redux/cachedDataReducer.ts#L111

Because in this promise chain: https://github.com/cockroachdb/cockroach/blob/8a7030f00e653ddd35c5298ff496d3aa112f6abc/pkg/ui/src/redux/cachedDataReducer.ts#L180-L188

…the `.dispatch` causes a React re-render, and any errors as part of that get caught by the `.catch` and stuffed into the cached data reducer state as if they were data loading errors.

**Comment by vilterp** [comment]
On a related note, some errors aren't silently swallowed, they just blank out the whole page (e.g. https://github.com/cockroachdb/cockroach/issues/31260)

Would be nice to catch these and display some kind of error.
