### ISSUE TITLE
qa: EXPORT CSV

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#25223]
This issue tracks the qa for Export CSV available in the next alpha release.

https://github.com/cockroachdb/cockroach/pull/25075

**Comment by vivekmenezes** [comment]
@a-robinson I assigned you randomly to be the qa-buddy.

**Comment by a-robinson** [comment]
Sorry for the delay on this. It wasn’t clear to me until I recently re-read it that this QA was meant to be done before the early-June alpha rather than before the full 2.1 release.

My rough manual test plan:

* Just play around with it - mess around with the syntax, different invalid options, using it within a transaction, etc
* Try the different storage options
* Try different types of queries - empty result set, one result, large result set, complicated joins/aggregation, non-deterministic SQL functions
* Invalid authentication
* Local directory that doesn’t exist
* Local directory with insufficient permissions
* Local directory with I/O error (e.g. forcefully unmount tmpfs)
* Inject timeout/error into cloud endpoints (e.g. by running from laptop and turning off wifi)
* Use weird unicode character as delimiter
* Make sure IMPORT works on the output of each successful EXPORT

**Comment by vivekmenezes** [comment]
@dt to comment on the plan

**Comment by dt** [comment]
It leans on distSQL so I might try multi-node and also inject some node failures or networking issues, disk space or otherwise mess with temp space, etc but that likely isn’t that different than just QAing distSQL’s ability to run the underlying query.

Potentially interesting are `show trace` and error conditions since our non-standard distsql processors have to reimplement some of that plumbing.

**Comment by dt** [comment]
> * Syntax guidance provided by `\h EXPORT` is incorrect - missing the required FROM keyword
>   * Fixed by https://github.com/cockroachdb/cockroach/pull/25677

#25677

> * The "unsupported EXPORT query -- as an alternative try `cockroach sql --format=csv`" error message isn’t incredibly clear. It leaves open the question of why is the query unsupported?
>   * Also, is it that the EXPORT itself is unsupported or that the query I provided to EXPORT is unsupported? Wording could be better even if we don’t squeeze in additional explanation.
> * Some errors (e.g. the “unsupported EXPORT query” error) take priority over the enterprise license check. If you don’t have the license, it’d be nice if that failed first so you don’t spend a bunch of time fixing your query just to realize you can’t use the feature

This was fixed when @jordanlewis merged the execuction engines and made distsql able to run any query. He removed this error.

> * Why does running EXPORT not create an entry in the jobs table / UI page given that running IMPORT does?

Known issue. Noted in https://github.com/cockroachdb/docs/issues/3563.

> * `IMPORT` always reports that 0 rows and bytes were imported, which clearly isn't true.
>   * Looks like this is already covered by https://github.com/cockroachdb/cockroach/issues/25293

#28469

> * Problems with providing nodelocal paths with different (possibly invalid?) numbers of slashes (confusing trying to map to/from the template of `[scheme]://[host]/[path]?[parameters]` in the  docs -- if everything goes into the external I/O dir, why is the starting slash even needed?):
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:' FROM SELECT * from startrek.quotes;
> pq: Local storage requested but path not provided
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:/tmp/csv1' FROM SELECT * from startrek.quotes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n1.0.csv |  200 | 20918 |
> +----------+------+-------+
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal://tmp/csv1' FROM SELECT * from startrek.quotes;
> pq: nodelocal does not support hosts: nodelocal://tmp/csv1
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1' FROM SELECT * from startrek.quotes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n1.0.csv |  200 | 20918 |
> +----------+------+-------+
> ```
> * For nodelocal mode, it’s really unintuitive where the file goes.
>   * I think the docs need to more strongly call out what’s needed for NFS/nodelocal to make sense. Using it without setting the `--external-io-dir` flag is basically nonsensical even if all the nodes are on the same machine, since the resulting file location(s) can't be known in advance.
>   * I got pretty confused at first trying to find the output file, not realizing it was written into the leaseholder’s store directory (not the absolute filesystem path, or on gateway node, or on the sql shell’s node).
> * Parameters that aren’t recognized should be an error. Instead, they’re silently ignored
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1?AWS_ACCESS_KEY_ID=foo' FROM SELECT * from startrek.episodes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n3.0.csv |   79 |  3021 |
> +----------+------+-------+
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1?foo=bar' FROM SELECT * from startrek.episodes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n3.0.csv |   79 |  3021 |
> +----------+------+-------+
> ```

`nodelocal` has and continues to be confusing. https://github.com/cockroachdb/docs/issues/3563

> * Why is AWS_REGION listed as a valid parameter for “S3-compatible services” but not S3 itself?

This was only required for knock-off APIs since the SDK did region detection when using the official one.
Matt has since eliminated it as part of testing/polish on minio.

> * The `nullas` docs have a typo and read as if they’re still talking about IMPORT

https://github.com/cockroachdb/docs/issues/3563

> * Not a bug, but unicode emoji aren’t valid delimiters and that makes me sad :(

:( we can doc that they have to be ascii https://github.com/cockroachdb/docs/issues/3563

> * The documentation of the GCS parameters doesn’t make sense, and appears incorrect.
>   * It equates not specifying AUTH with setting AUTH=default, which isn’t true in practice:
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: write to google cloud: googleapi: Error 403: 21965078311-compute@developer.gserviceaccount.com does not have storage.objects.create access to cockroach-alex/csv/n1.0.csv., forbidden
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv?AUTH=default' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: expected settings value for cloudstorage.gs.default.key
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv?AUTH=implicit' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: write to google cloud: googleapi: Error 403: 21965078311-compute@developer.gserviceaccount.com does not have storage.objects.create access to cockroach-alex/csv/n1.0.csv., forbidden
> ```

https://github.com/cockroachdb/docs/issues/3563

> * EXPORT’s `nullas` default isn’t compatible with IMPORT’s `nullif` default
>   * I can’t export the startrek.quotes table and directly import the result. It only works if I add `nullif = ''`
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://tmp829410720848561/csv2?AUTH=implicit' FROM SELECT * from startrek.quotes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n1.0.csv |  200 | 20918 |
> +----------+------+-------+
> (1 row)
> 
> Time: 168.310424ms
> 
> root@:26257/defaultdb> IMPORT TABLE t2 (quote STRING NULL, characters STRING NULL, stardate DECIMAL NULL, episode INT NULL) CSV DATA ('gs://tmp829410720848561/csv2/n1.0.csv');
> pq: "gs://tmp829410720848561/csv2/n1.0.csv": row 1: parse "stardate" as DECIMAL: could not parse "" as type decimal:
> root@:26257/defaultdb> IMPORT TABLE t2 (quote STRING NULL, characters STRING NULL, stardate DECIMAL NULL, episode INT NULL) CSV DATA ('gs://tmp829410720848561/csv2/n1.0.csv') WITH nullif = '';
> +--------------------+-----------+--------------------+------+---------------+----------------+-------+
> |       job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes |
> +--------------------+-----------+--------------------+------+---------------+----------------+-------+
> | 351315896311414786 | succeeded |                  1 |    0 |             0 |              0 |     0 |
> +--------------------+-----------+--------------------+------+---------------+----------------+-------+
> (1 row)
> root@:26257/defaultdb> select count(*) from t2;
> +-------+
> | count |
> +-------+
> |   200 |
> +-------+
> (1 row)
> ```

I'm not sure what we can do about this:
  - the default is that there is _no_ `nullif` value in IMPORT -- no value in the imported data is automatically re-mapped to null by default.
  - when exporting values though, if we hit a null, we have to print it as _something_, so we can't have a default of no `nullas` value, we have to print something (empty string, "null", etc).

I don't think we want to default `nullif` to `NULL` or something like that since we'd then risk messing with users who have that string in their data.

Some CSV readers/writers allow printing empty strings as `,,` or as `,"",` to allow distinguishing these, which could be useful here.

but then we're back to saying you need to read and use the docs.. I donno... @mjibson / @rolandcrosby  ?

> * Shouldn’t the `cloudstorage.gs.default.key` setting be write only? Including it in the output of `SHOW ALL CLUSTER SETTINGS` seems really bad

Root can read all the system tables, where the setting is stored, so hiding it from root in SHOW SETTING doesn't seem to win us much. 
https://github.com/cockroachdb/cockroach/pull/17619#issuecomment-322209519

> * Maybe this isn’t EXPORT’s fault, but if I set `nullas` to a number that appears in one of the latter columns, the actual occurrences of that number end up marked as null if I import the resulting CSV file. It seems like escaping of some sort should avoid that? You can repro with:
> ```
> EXPORT INTO CSV 'gs://tmp829410720848561/csv4?AUTH=default' WITH nullas='26' FROM SELECT * from startrek.quotes;
> IMPORT TABLE t4 (quote STRING NULL, characters STRING NULL, stardate DECIMAL NULL, episode INT NULL) CSV DATA ('gs://tmp829410720848561/csv4/n2.0.csv') WITH nullif='26';
> ```

That seems like it is expected -- if you say "read X as null", then yes, X will be changed to null. We should doc that you need to ensure X isn't something that appears in your actual data.
https://github.com/cockroachdb/docs/issues/3563

> * SHOW TRACE FOR (which you recommended trying out) doesn’t work with EXPORT at all. Is that actually a problem, though?
> ```
> root@:26257/defaultdb> show trace for EXPORT INTO CSV 'gs://tmp829410720848561/csv5?AUTH=default' FROM SELECT * from startrek.quotes ORDER BY stardate DESC LIMIT 11;
> invalid syntax: statement ignored: syntax error at or near "export"
> DETAIL: source SQL:
> show trace for EXPORT INTO CSV 'gs://tmp829410720848561/csv5?AUTH=default' FROM SELECT * from startrek.quotes ORDER BY stardate DESC LIMIT 11;
>                ^
> HINT: try \h SHOW TRACE
> ```

This syntax is gone now I think, but `SET TRACING = on; EXPORT ...; SHOW TRACE FOR SESSION;` looks like it works as expected.

> * Shutting off WiFi during export caused memory panic
>   * Opened https://github.com/cockroachdb/cockroach/issues/26112 with details

Matt closed #26112, looks like something has fixed it.

**Comment by vivekmenezes** [comment]
@dt anything else need to be done here?
