### ISSUE TITLE
qa: timetz

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#25224]
this issue tracks the qa for the timetz type available in the next alpha

https://github.com/cockroachdb/cockroach/issues/20944

@andreimatei you have been picked randomly to qa this feature

**Comment by vivekmenezes** [comment]
@andreimatei this is visible in the next alpha. A reminder to spend a short bit of time playing around with it.

**Comment by andreimatei** [comment]
Will play with it tomorrow.

**Comment by andreimatei** [comment]
cc @windchan7 

I want to prefix everything by saying that I don't really understand much and everything below might be wrong.

Well so I've played around with this thing. I had a hard time wrapping my head around what this is, because the datatype is fairly non-sensical (as Postgres admits in its documentation).

What I can say, however, is that our implementation does not seem to match Postgres' (and I guess matching Postgres is the only reason to implement such a thing).

Our behavior seems to diverge from Postgres in both of the important aspects about timezone handling - what data is recorded in the database (i.e. the offset from UTC computed from the input) and how data is presented to the user.

Experiments have been recorded here: https://docs.google.com/spreadsheets/d/1YPcYLFEz74Y1MWbOdCpSFKQGo7RiX1udaiTSbJDH0SU/edit?usp=sharing

The first major problem is that we fail to parse dates in something like: `select '2018-05-18 13:00:00 Europe/London'::timetz;`. Postgres accepts the data part - in fact it is recommended to put it when talking about timezones with dst. Without the date part, the offset from UTC to be computed is ambiguous. 

The the 2nd problem is that, when the session's timezone is set to a timezone that observes DST, and a date and an offset is not specified, Postgres takes the current date into consideration when computing the offset. Cockroach does not. This leads to different interpretations of timetz values. For example, in crdb, timetz inputed today without specifying a date or an offset seem to be treated as EST, whereas Postgres interprets it as EDT. Being May, EDT is in affect for the eastern time zone.

The third problem is that the way we display timetzs is different from Postgres. We a) take the current session's tz into consideration, which Postgres doesn't, and b) prepend a non-sensical date of 0000-01-01 to it.

It would seem that more work is needed here :)

**Comment by windchan7** [comment]
@andreimatei 
Thank you for QA this feature. Here's my response to the problems your encountered:

1. This is expected as said in the PR: `this commit does not attempt to support any new time formats beyond what we already support in the time portion of TIMESTAMP`. So we won't be able to parse the fancy time zone information or the date part, as `TIME` type doesn't support it.

2. Please see my explanation about what `time zone` means in CockroachDB's `timetz` below.

3. This is actually due to pq's weird display of both `TIME` and `TIMETZ` data type. This behavior is documented in the beginning of `TIMETZ`'s logic test.

I think the major misunderstanding is that the `time zone` in CockroachDB `TIMETZ` is the time zone we use to display the result back to the user. It's for display purpose only, as far as I understand.

Our implementation cannot match Postgres exactly because we do not store time zone information. Which means all the time zone displayed are rendered based on user's session time zone. Therefore, it's impossible for our implementation to match Postgres's. This is documented in the doc page.

**Comment by windchan7** [comment]
I know this is really confusing. That's also the reason that we should not recommend using TIMETZ data type to the users.

**Comment by andreimatei** [comment]
I've discussed some with Victor offline. Pasting some conclusions and further discussion items:

I think we're in agreement that there is a problem with the interpretation of timetz's when the session's timezone is one with dst rules. This is funky:
```
```root@127.0.0.1:58071/demo> show timezone;
| America/New_York |

root@127.0.0.1:58071/demo> select '13:00:00'::timetz;
| 0000-01-01 13:00:00-05:00      |
```

In postgres, this is `13:00:00-04:00`.

I think we're also in agreement that there is a problem with the *display* of timetz's when the session's timezone has dst rules. The following is bizarre:
```
root@127.0.0.1:58071/demo> select now();
|               now                |
| 2018-05-18 16:37:50.578807-04:00 |
+----------------------------------+
(1 row)

root@127.0.0.1:58071/demo> select now()::timetz;
| 0000-01-01 15:37:52.018859-05:00 |
```

Further, these are my distilled complaints:
1) we don't accept some timezone formats (`select '16:00:00 America/New_York'::timestamptz;`). You say timestamptz also doesn't accept them. Fair enough.
2) we don't accept dates in the input  (`select '2018-01-01 16:00:00'::timestamptz;`). timestamptz accepts this. What's your answer? (I concede that accepting this is less important given 1), however, the date is still important when the session's timezone is dst)
3) We display things differently from Postgres.
 a) we preprend a nonsensical date. You say that's the crdb cli client's fault, and you're right.
 b) we take the session's offset into consideration (but incorrectly cause no DST) and display the time accordingly, Postgres remembers how the time was input (with what offset) and displays it with the specified offset. What do you say here? "Known difference, nothing to see"

**Comment by windchan7** [comment]
@dt 
David, can you confirm that Cockroach doesn't want to store `time zone` or `location offset` information in its value? Because I remember that's what you meant during our first few conversations. 

If that's the case, we won't be able to match Postgres behavior because I'm pretty sure Postgres stores `time zone offset` in its `timetz` value. It's documented here: `The appropriate time zone offset is recorded in the time with time zone value.`, in https://www.postgresql.org/docs/9.5/static/datatype-datetime.html.

**Comment by dt** [comment]
So while I'm getting up to speed here, some general tips I picked up from going though slightly similar testing with timestamptz a while back:
- First off, I'd avoid any client rendering differences by using `psql` to query both DBs  -- if the DB is acting the same, we can think about the clients later.
- For testing the actual DB behavior, I'd suggest making a combination of `time`, `timetz`, `timestamp` and `timestamptz` columns and then writing to them with and without offsets specified, with and without a session offset, then read them with and without a session offset, in both Cockroach and Postgres. 
- Finally there's casts and function overloads, but the same strategy applies there -- make a table of selects of all the casts, then run it with/without, etc against both DBs.

Examples:
```
root=# select version();
                                                    version
----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.2 on x86_64-apple-darwin16.4.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit
(1 row)
root=# set timezone = 0;
SET
root=# create table foo (name varchar, t time, tz timetz, ts timestamp, tsz timestamptz);
CREATE TABLE
root=# insert into foo values ('no-offsets-no-session', '11:00:00', '11:00:00', '2018-04-30 23:00:00', '2018-04-29 23:00:00');
INSERT 0 1
root=# insert into foo values ('offsets-no-session', '11:00:00 -0500', '11:00:00 -0500', '2018-04-30 23:00:00 -0500', '2018-04-29 23:00:00 -0500');
INSERT 0 1
root=# set timezone = -3;
SET
root=# insert into foo values ('no-offsets-session-3', '11:00:00', '11:00:00', '2018-04-30 23:00:00', '2018-04-29 23:00:00');
INSERT 0 1
root=# insert into foo values ('offsets-session-3', '11:00:00 -0500', '11:00:00 -0500', '2018-04-30 23:00:00 -0500', '2018-04-29 23:00:00 -0500');
INSERT 0 1
root=# set timezone = 0;
SET
root=# select * from foo;
         name          |    t     |     tz      |         ts          |          tsz
-----------------------+----------+-------------+---------------------+------------------------
 no-offsets-no-session | 11:00:00 | 11:00:00+00 | 2018-04-30 23:00:00 | 2018-04-29 23:00:00+00
 offsets-no-session    | 11:00:00 | 11:00:00-05 | 2018-04-30 23:00:00 | 2018-04-30 04:00:00+00
 no-offsets-session-3  | 11:00:00 | 11:00:00-03 | 2018-04-30 23:00:00 | 2018-04-30 02:00:00+00
 offsets-session-3     | 11:00:00 | 11:00:00-05 | 2018-04-30 23:00:00 | 2018-04-30 04:00:00+00
(4 rows)

root=# set timezone = -2;
SET
root=# select * from foo;
         name          |    t     |     tz      |         ts          |          tsz
-----------------------+----------+-------------+---------------------+------------------------
 no-offsets-no-session | 11:00:00 | 11:00:00+00 | 2018-04-30 23:00:00 | 2018-04-29 21:00:00-02
 offsets-no-session    | 11:00:00 | 11:00:00-05 | 2018-04-30 23:00:00 | 2018-04-30 02:00:00-02
 no-offsets-session-3  | 11:00:00 | 11:00:00-03 | 2018-04-30 23:00:00 | 2018-04-30 00:00:00-02
 offsets-session-3     | 11:00:00 | 11:00:00-05 | 2018-04-30 23:00:00 | 2018-04-30 02:00:00-02
(4 rows)
```

And in cockroach:
```
root=# select version();
                                                         version
-------------------------------------------------------------------------------------------------------------------------
 CockroachDB CCL v2.1-alpha.20180507-379-ge88994b6f-dirty (x86_64-apple-darwin17.5.0, built 2018/05/17 18:39:27, go1.10)
(1 row)
root=# set timezone = 0;
SET
root=# create table foo (name varchar, t time, tz timetz, ts timestamp, tsz timestamptz);
CREATE TABLE
root=# insert into foo values ('no-offsets-no-session', '11:00:00', '11:00:00', '2018-04-30 23:00:00', '2018-04-29 23:00:00');
INSERT 0 1
root=# insert into foo values ('offsets-no-session', '11:00:00 -0500', '11:00:00 -0500', '2018-04-30 23:00:00 -0500', '2018-04-29 23:00:00 -0500');
INSERT 0 1
root=# set timezone = -3;
SET
root=# insert into foo values ('no-offsets-session-3', '11:00:00', '11:00:00', '2018-04-30 23:00:00', '2018-04-29 23:00:00');
INSERT 0 1
root=# insert into foo values ('offsets-session-3', '11:00:00 -0500', '11:00:00 -0500', '2018-04-30 23:00:00 -0500', '2018-04-29 23:00:00 -0500');
INSERT 0 1
root=# set timezone = 0;
SET
root=# select * from foo;
         name          |    t     |       tz       |         ts          |            tsz
-----------------------+----------+----------------+---------------------+---------------------------
 no-offsets-no-session | 11:00:00 | 11:00:00+00:00 | 2018-04-30 23:00:00 | 2018-04-29 23:00:00+00:00
 offsets-no-session    | 11:00:00 | 16:00:00+00:00 | 2018-05-01 04:00:00 | 2018-04-30 04:00:00+00:00
 no-offsets-session-3  | 11:00:00 | 14:00:00+00:00 | 2018-04-30 23:00:00 | 2018-04-30 02:00:00+00:00
 offsets-session-3     | 11:00:00 | 16:00:00+00:00 | 2018-05-01 04:00:00 | 2018-04-30 04:00:00+00:00
(4 rows)

root=# set timezone = -2;
SET
root=# select * from foo;
         name          |    t     |       tz       |         ts          |            tsz
-----------------------+----------+----------------+---------------------+---------------------------
 no-offsets-no-session | 11:00:00 | 09:00:00-02:00 | 2018-04-30 23:00:00 | 2018-04-29 21:00:00-02:00
 offsets-no-session    | 11:00:00 | 14:00:00-02:00 | 2018-05-01 04:00:00 | 2018-04-30 02:00:00-02:00
 no-offsets-session-3  | 11:00:00 | 12:00:00-02:00 | 2018-04-30 23:00:00 | 2018-04-30 00:00:00-02:00
 offsets-session-3     | 11:00:00 | 14:00:00-02:00 | 2018-05-01 04:00:00 | 2018-04-30 02:00:00-02:00
(4 rows)
```

Looking at that postgres behavior, yes, it looks like it is indeed storing the offset. Thats not how timestamptz vs timestamp works, so it's a bit surprising. If you look at something like Vertica, [they don't store it as far as i can tell](https://my.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/SQLReferenceManual/DataTypes/Date-Time/TIME.htm).

I don't think we want to store it, but obviously we won't match postgres' behavior if we don't. I'm not sure what we actually need for ORM compat.

**Comment by windchan7** [comment]
But `TIME WITH TIME ZONE` and `TIMETZ` are alias in Postgres. If we make a distinction between the two in Cockroach, it would be confusing to users. Jordan talked about doing some ORM checks probably we should wait to see how it goes. @jordanlewis

**Comment by bdarnell** [comment]
> I don't mind that we have more features but this new feature, as is, is different and thus should have a different type name.

The only reason we're implementing this type is for compatibility. It wouldn't make sense to introduce something incompatible (but similar) with a different name. I think we need to rework the implementation to store the offset (even though this is surprising and different from TIMESTAMPTZ).

**Comment by knz** [comment]
> so I wonder how important it really is to compatibility.

From #20944:

> Used in Hibernate/Java criteriaBuilder.

@justinj do you recall how it is used?

**Comment by bdarnell** [comment]
> Used in Hibernate/Java criteriaBuilder.

I suspect this means "supported by hibernate". Hibernate contains support for using TIMETZ if you want to put it in your database, and we may see failures when running hibernate's test suite because we don't have it, but I doubt that it's necessary in any practical sense for compatibility with hibernate.

**Comment by knz** [comment]
Thanks @justinj, bingo: https://www.postgresql.org/docs/10/static/functions-datetime.html

indeed `current_time()` (which is of common use) returns `timetz` because of historical reasons.

I wonder how much mileage we could get by having that function return something else, but it makes me a bit uncomfortable to attempt to go that route.

**Comment by dt** [comment]
it is also possible we just need the datum, as produced by `current_time`, but would be fine with only a `time` column type (neatly side-stepping the offset storage question).

**Comment by knz** [comment]
Discussed with @jordanlewis: Jordan will look at this ( #26097) in the next milestone.

I recommend we keep this QA open until  #26097 is resolved.

**Comment by andreimatei** [comment]
Should we revert `timetz` in the meantime?
If what @dt says about just supporting `current_time` without actually supporting this data type more broadly is possible, that would sound great to me.

**Comment by bdarnell** [comment]
Yes, I think we should revert it (or at least unlink it from the grammar) until we can reimplement it with the stored offset.

**Comment by jordanlewis** [comment]
Unlinking it sounds good to me. But what's the hurry?

I'm planning on getting to the stored offset version in the next week.

**Comment by knz** [comment]
Andrei, Justin, Ben, hold your horses. As indicated in the meeting notes last week, there was a 2-week slack period for Jordan to look into this. There's no rush.

**Comment by vivekmenezes** [comment]
I'm closing this issue because we decided to take this feature out.
