### ISSUE TITLE
sql: string to decimal conversion improperly truncates large negative values

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25258]
Consider the following (valid, unsurprising) behavior:

```
> select decimal '9223372036854775807.000000001';
+---------------------------------+
|             DECIMAL             |
| '9223372036854775807.000000001' |
+---------------------------------+
|   9223372036854775807.000000001 |
+---------------------------------+

> select 9223372036854775807.000000001::decimal;
+----------------------------------------+
| 9223372036854775807.000000001::DECIMAL |
+----------------------------------------+
|          9223372036854775807.000000001 |
+----------------------------------------+
```

Now compare this:

```
> select decimal '-9223372036854775807.000000001';
+----------------------------------+
|             DECIMAL              |
| '-9223372036854775807.000000001' |
+----------------------------------+
|   -9223372036854775807.000000001 |
+----------------------------------+
```

Still happy! And now:

```
> select (-9223372036854775807.000000001)::decimal;
+-------------------------------------------+
| (-9223372036854775807.000000001)::DECIMAL |
+-------------------------------------------+
|                    -9223372036854775807.0 |
+-------------------------------------------+
```

woops, the fractional part was truncated.

cc @nvanbenschoten @mjibson

**Comment by nvanbenschoten** [comment]
I did some digging and it looks like this is all fully explained by the call to `DecimalCtx.Quo` when converting arbitrary precision rational numbers. This function uses the `DecimalCtx`, which is bound to a precision of `20`. We'll want to increase the operation's precision for this division, because it's still at a stage where we expect no arithmetic loss.

https://github.com/cockroachdb/cockroach/blob/cdd09093131a290b0d1f46618b8b18a4dec69be8/pkg/sql/sem/tree/constant.go#L275

The reason we don't hit this in the positive case is because we never lose our `expr.OrigString`, which is used earlier in `NumVal.ResolveAsType`.

Another thing I suspected for a while was that we were messing up the call to `LimitDecimalWidth` in `tree.PerformCast`:

https://github.com/cockroachdb/cockroach/blob/cdd09093131a290b0d1f46618b8b18a4dec69be8/pkg/sql/sem/tree/eval.go#L2988-L2989

This makes sense for more casts, but I'm not sure if we want this when performing the `DECIMAL->DECIMAL` identity cast. cc. @mjibson

**Comment by nvanbenschoten** [comment]
The following diff fixes the specific issue here:
```
--- a/pkg/sql/sem/tree/constant.go
+++ b/pkg/sql/sem/tree/constant.go
@@ -272,7 +272,7 @@ func (expr *NumVal) ResolveAsType(ctx *SemaContext, typ types.T) (Datum, error)
                                return nil, errors.Wrapf(err, "could not evaluate denominator %v as Datum type DDecimal "+
                                        "from string %q", expr, den)
                        }
-                       if cond, err := DecimalCtx.Quo(&dd.Decimal, &dd.Decimal, &denDec.Decimal); err != nil {
+                       if cond, err := HighPrecisionCtx.Quo(&dd.Decimal, &dd.Decimal, &denDec.Decimal); err != nil {
                                if cond.DivisionByZero() {
                                        return nil, ErrDivByZero
                                }
```

I think it's the right change, but technically it is still lossy. @knz do you think we need a mode in `cockroachdb/apd` that returns an error if the operation ever results in information loss due to insufficient precision?

**Comment by knz** [comment]
> do you think we need a mode in cockroachdb/apd that returns an error if the operation ever results in information loss due to insufficient precision?

I think that silent information loss for a data type that aims to be information-preserving is indeed difficult to justify.

**Comment by nvanbenschoten** [comment]
I just looked closer at `cockroachdb/apd` and it has an `Inexact` trap specifically for this purpose. Thanks for designing this so well @mjibson!

**Comment by mjibson** [comment]
I'm confused why we are doing a division here at all. Can you explain why that's happening?

**Comment by nvanbenschoten** [comment]
`go/constant` provides infinite precision using rational numbers. We need to divide to turn this into an arbitrary precision decimal.

**Comment by nvanbenschoten** [comment]
Re-opening because of the discussion in #25755. Specifically, see https://github.com/cockroachdb/cockroach/pull/25755#issuecomment-390750409.

@louishust would you be interested in working on this?

**Comment by jordanlewis** [comment]
It doesn't repro anymore.

```
demo@127.0.0.1:57528/defaultdb> select (-9223372036854775807.000000001)::decimal;
             numeric
----------------------------------
  -9223372036854775807.000000001
(1 row)

```
