### ISSUE TITLE
roachtest: add --count flag

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25284]
This makes it easier to "stress" test a roachtest, something we should do habitually before merging one (and eventually automate).

- this should work with the `-c` flag (reuse cluster).
- this could interact with the `--parallelism` flag by running multiple copies of the test in parallel (only when `-c` is not specified)

@petermattis, assigning you as the resident roachtest expert.

**Comment by andreimatei** [comment]
Reopening this because the `--count` flag does not interact well with `--parallelism`, as OP asked for.
This code neuters the `--parallelism` regardless of `--count`, making it so that one can't run multiple copies of a test in parallel.
https://github.com/cockroachdb/cockroach/blob/c3fd89bfd3ee90983fb0bd35fda1a56b4a3011d4/pkg/cmd/roachtest/test.go#L263

**Comment by andreimatei** [comment]
`--parallelism` and `--count` worked well together for a while now
