### ISSUE TITLE
join query - bad performance

### ISSUE THREAD

**Issue by benoit-ponsero** [cockroachdb/cockroach#25312]
Hello,

I'm testing cockroach and i notice bad performances on join queries. 
exemple: 

t1: market(id, active, contract_id)  ~ 4000 rows
t2: market_country (market_id, countries_id) ~ 900 000 rows
t3: country (id, code) ~ 239 rows

i want to select all active market that have country = 'FR' and contract = 3718:

```
SELECT
    *
    FROM
          market m
    JOIN market_country mc ON mc.MARKET_ID = m.ID
    JOIN country c ON c.ID = mc.COUNTRIES_ID
    WHERE
        c.CODE = 'FR'
        AND m.ACTIVE = true
        AND m.CONTRACT_ID = 3718;
```

in local env : 
mysql: 5ms
cockroach: **1.7 sec**

Why the difference is so big ?

here is the ddl:

```
CREATE TABLE market (
	id BIGINT NOT NULL,
	"name" STRING(64) NOT NULL,
	contract_id BIGINT NULL,
	active BOOL NULL DEFAULT false,

	INDEX market_contract_id_idx (contract_id ASC),
	INDEX market_id_idx (id ASC),
	FAMILY "primary" (id, "name", contract_id, active, rowid)
)

CREATE TABLE country (
	id BIGINT NOT NULL,
	code STRING(2) NOT NULL DEFAULT '':::STRING,
	INDEX country_code_idx (code ASC),
	INDEX country_id_idx (id ASC),
	FAMILY "primary" (id, code, rowid)
)

CREATE TABLE market_country (
	market_id BIGINT NOT NULL,
	countries_id BIGINT NOT NULL,
	INDEX market_country_countries_id_idx (countries_id ASC),
	INDEX market_country_market_id_countries_id_idx (market_id ASC, countries_id ASC),
	INDEX market_country_market_id_idx (market_id ASC),
	FAMILY "primary" (market_id, countries_id, rowid)
)

```

$ cockroach version
Build Tag:    v2.0.1
Build Time:   2018/04/23 19:18:28
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.5.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
Build SHA-1:  c92bc6e912880c28c0784d3208583fb27f482f76
Build Type:   development

**Comment by knz** [comment]
Note that you can perhaps use our temporary setting `experimental_force_lookup_joins` to accelerate this particular query.

**Comment by rytaft** [comment]
In order to have `experimental_force_lookup_join` work for this query, you will need to change your schema so that `market_id` is the first column in the primary key of `market_country`. Since it's not possible to change the primary key after the table is created, you would need to reload these tables. But I've verified that the lookup join will work, assuming you `set session experimental_force_lookup_join=true;` and alter the schema to have a composite primary key with `market_id` as the first column. 

Hope this helps! Let us know if you run into any issues with this approach.

**Comment by benoit-ponsero** [comment]
Hi,

Thanks so much for your help. it's about **3ms** now.

I have drop the table and re-created with market_id as the first column of primary key and after setting session variable `experimental_force_lookup_join = true`, the SELECT statement took now 3ms. 

Do you know if there is a global setting for this variable ?

**Comment by rytaft** [comment]
Great! Glad to hear it worked. 

`experimental_force_lookup_join` is a session variable, so you'll need to set it for each new client session. It's not a global variable because there are some queries where it is the wrong choice and performs much worse than a hash join or merge join.  It's also an experimental feature, so will probably not be supported in our v2.1 release. (That's because in v2.1 the query optimizer will choose the correct join algorithm, but for now it must be done manually.)
