### ISSUE TITLE
3 nodes, replicas going only to one node

### ISSUE THREAD

**Issue by thstart** [cockroachdb/cockroach#25316]
Is this a question, feature request, or bug report?

**QUESTION**
I have 3 nodes. Importing large database through node 3. All replicas going only to node 1.

Have you checked our documentation at https://cockroachlabs.com/docs/stable/? If you could not find an answer there, please consider asking your question in our community forum at https://forum.cockroachlabs.com/, as it would benefit other members of our community.

Prefer live chat? Message our engineers on our Gitter channel at https://gitter.im/cockroachdb/cockroach.

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

==========================
commands:
==========================
n1:
/usr/local/bin/cockroach
start
--insecure
--store=/TC.CockRoachDB.store
--host=my ip address 1
--http-port=9000
--cache=25%
--max-sql-memory=25%

n2:
/usr/local/bin/cockroach
start
--insecure
/TC.CockRoachDB.store
--host=my ip address 2
--http-port=9000
--cache=25%
--max-sql-memory=25%
--join=my ip address 1:26257

n3:
/usr/local/bin/cockroach
start
--insecure
/TC.CockRoachDB.store
--host=my ip address 3
--http-port=9000
--cache=25%
--max-sql-memory=25%
--join=my ip address 1:26257

==========================
web console:
==========================
ID	n1	
ADDRESS	my ip address 1
UPTIME	16 hours
BYTES	2.7 GiB
REPLICAS	270
MEM USAGE	5.9 GiB
VERSION	v2.0.1

ID	n2
ADDRESS	my ip address 2
UPTIME	16 hours
BYTES	70.9 MiB
REPLICAS	8
MEM USAGE	320.7 MiB
VERSION	v2.0.1

ID	n3
ADDRESS	my ip address 3
UPTIME	15 hours
BYTES	5.9 MiB
REPLICAS	0
MEM USAGE	463.5 MiB
VERSION	v2.0.1

       
2. Please describe the issue you observed:

- What did you do?

installed v.2.01 from scratch. on node n3 began importing data using:
UPSERT INTO

- What did you expect to see?
same amount of replicas on all nodes.

- What did you see instead?
importing via n3 there is no data on this node. there is no data on n2.
the only data I see is on node n1.
<img width="1002" alt="cockroachdb01" src="https://user-images.githubusercontent.com/357530/39638642-bd6a9a2e-4f7b-11e8-8abb-a506ed8576c0.png">

**Comment by tschottdorf** [comment]
Thanks for your report, @thstart. This looks unexpected, could you send me a screenshot of the page at `/#/reports/range/21` (from any node, but preferably n1)? I'm particularly interested in the "simulated allocator output".

**Comment by 474420502** [comment]
I also have the same problem :cry:

**Comment by tschottdorf** [comment]
@474420502 could you send the screenshot I asked for above from your cluster that has this problem?

**Comment by 474420502** [comment]
@tschottdorf  http://14.17.96.14:5050

**Comment by tschottdorf** [comment]
@474420502 could you `set cluster setting server.remote_debugging.mode = 'any';` so that I can access the debug pages? Please note that you don't want to do this if there's sensitive data in that cluster, as enabling debugging can in principle expose some of it.

**Comment by 474420502** [comment]
@tschottdorf  ok, now  server.remote_debugging.mode = 'any'.

**Comment by tschottdorf** [comment]
Thanks! What strikes me as the most obvious problem here is a lack of network connectivity:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/5076964/39673738-8ff8eb78-510f-11e8-9dde-f4bf3b292e1b.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/5076964/39673743-ad6fd536-510f-11e8-9b53-758ed5ebc095.png">

In the logs, I see these pretty much right away:

> grpc: addrConn.createTransport failed to connect to {cockroach02:8802 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup cockroach02 on 114.114.114.114:53: no such host". Reconnecting...

This suggests that you need to set a proper `--advertise-host` flag on each node so that they can connect to each other. Or you make the hostnames `cockroachXX` resolvable. Can you try either option and report back? Thanks!
 
some more ramblings from earlier investigation below, but there's nothing actionable there.

----

This is even though gossip is healthy. Note that the first graph is asymmetric. For example, `n2` can talk to `n1` but `n1` cannot talk to `n2`. Only `n3` can go both ways, and in fact `n3` managed to get four replicas at some point, which may be related to that.

Looking at the node addresses, something is odd:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/5076964/39673781-b97f5936-5110-11e8-95f9-f5b8c75090a5.png">

This looks like you're running node 1 and node 3 on the same machine, and similarly node 2 and node 4. Or, you have set up nodes that have identical host names. I was able to pull the startup command line for those two from the logs:

1: [config] arguments: [cockroach start --insecure --http-port=5050 --port=8800 --store=data --host=cockroach01]
3: [config] arguments: [cockroach start --insecure --http-port=5051 --join=cockroach01:8800 --port=8803 --store=data --host=cockroach01]

**Comment by 474420502** [comment]
@tschottdorf  Thanks! The Problem is solved!  :+1:  http://14.17.96.14:5050

**Comment by 474420502** [comment]
ERROR [replicate,n1,s1,r73/1:/Table/51/5/2018-05-06T12:2…] avoid up-replicating to fragile quorum: 1 matching stores are currently throttled 
There are a lot of similar error logs!

**Comment by tschottdorf** [comment]
Thanks! We need to do a better job exposing this problem to the operators.

**Comment by tschottdorf** [comment]
@thstart -- hopefully you are running into the same problem, just let us know!

**Comment by thstart** [comment]
I investigated and discovered the following. I was importing using n3. Checked everything until found out n3 was behind a firewall not accepting incoming connections. Still only n1 got replicas. n1 and n2 were fine regarding firewall allowing incoming connections but only n1 got the replicas. Because of time constraints I tore down the cluster and started from scratch and now it is working fine.

**Comment by tschottdorf** [comment]
Thanks @thstart! I'll leave this open until I've filed/found follow-up issues to surface these kinds of problems better.

**Comment by tschottdorf** [comment]
This is now tracked as part of https://github.com/cockroachdb/cockroach/issues/18850.

**Comment by dimovnike** [comment]
hello, what is the recommended way to properly detect this situation? I tried /_status/vars but that also says liveness_livenodes=3 while only 2 nodes are replicating and 1 node is not due to a firewall issue. How to detect non-working nodes?

**Comment by tschottdorf** [comment]
@dimovnike this is unfortunately a blind spot today. One way to see it would be under `/debug/` in the admin UI; there's a network connectivity page. But ideally this would give you a yellow cluster status.

PS this problem is now tracked as part of #18850. I'll refer to your comment there, but please post further comments over there as well to save me the work :) Thanks.
