### ISSUE TITLE
acceptance: TestDockerCLI/test_log_config_msg.tcl failed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25334]
Seen in https://teamcity.cockroachdb.com/viewLog.html?buildId=641386&buildTypeId=Cockroach_UnitTests

TestDockerCLI/test_log_config_msg.tcl 

[artifacts.log.zip](https://github.com/cockroachdb/cockroach/files/1976610/artifacts.log.zip)

```
.180504 11:14:10.925984999 EXPECT TEST: START TEST: Check that the cluster ID is reported at the start of new log files.
child process exited abnormally
    while executing
"system "grep '\\\[config\\\] clusterID:' logs/db/logs/cockroach.log""
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_log_config_msg.tcl" line 17)
non-zero exit code: 1
    	cli_test.go:92: non-zero exit code: 1

```

**Comment by tschottdorf** [comment]
Also seen in https://github.com/cockroachdb/cockroach/issues/25788

**Comment by tschottdorf** [comment]
And another one, https://github.com/cockroachdb/cockroach/issues/25630.

**Comment by tschottdorf** [comment]
@knz could you triage?

**Comment by petermattis** [comment]
Saw this again: https://teamcity.cockroachdb.com/viewLog.html?buildId=672752&buildTypeId=Cockroach_UnitTests_Acceptance

I poked around at the logs, but it isn't clear at all what happened. It seems like the test just hung looking for `clusterID` in the logs.

**Comment by petermattis** [comment]
This has happened to me 3 times today. @knz Let's spend some time getting to the bottom of it tomorrow.

**Comment by petermattis** [comment]
I spent a bit of time trying to repro the failure just now and failed. It's not clear to me why testing that the `clusterID` is present in every log rotation needs to be an acceptance test. Seems like this could be part of a unit test in `util/log`.

**Comment by knz** [comment]
A test in `util/log` will not verify that the cluster id is properly populated upon node start-up.

**Comment by knz** [comment]
Ok I think I found the bug. It's pretty straightforward. 

The test is waiting for `[config] clusterID:` to be written to the last log file created, `cockroach.log`. It ensures that there is at least one rotation by making the rotation threshold tiny to ensure we have a rotation on nearly every log message.

The problem is that the log file header is buffered. 

It won't actually be written to the log file until 

a) a flush event occurs,  or
b) the server process terminates.

The flush event may only come a second later (`flushInterval`). But the grep is issued immediately after the server is started. There's a possibility for a race.

There are two fixes possible, either wait in the test before grepping for `clusterID` that the new log file becomes non-empty (i.e. wait for the first flush), or issue a Flush upon writing the log header.

I'll do the latter.

**Comment by knz** [comment]
Wait my analysis is flawed because I see the header is written via `sb.file.Write()` so that is unbuffered and should be visible immediately.

So it's probably just a race with the rotation process (i.e. the grep is catching the server in the middle of a rotation, when the file was just created). I still know how to fix this.
