### ISSUE TITLE
storage: automatically pick timestamp for AOST

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25405]
User @erichocean on gitter was interested in using AOST in a way that avoids having to pick a timestamp manually. Concretely, the AOST read would try to read the latest data, but skips open transactions, with the requirements that AOST never a) block and b) interfere with writes.

In CockroachDB, commit timestamps are chosen when the transaction starts. To get these semantics, AOST queries would have to a) lower their timestamps and restart every time they run into an intent, which is inefficient. The alternative b) is running at a fixed offset in the past and running at high priority, but this forces the writes to refresh (their outcome doesn't change, so the refresh should just work). 

In Spanner, by comparison, commit timestamps are chosen only when the writes are written out, and read locks are taken before that. This means that AOST queries will block writes to the same keys, so they technically also violate the constraint above. They don't force the writes to restart, but neither does CockroachDB (a refresh is cheaper; it's just another round of reads). So arguably option b) is closest here, but it requires manual choice of a timestamp.

It's not clear that one is better than the other, but users intuitively expect the commit timestamp to be chosen at commit time.

A related idea by @erichocean was to let each node keep track of the lowest timestamp for their open transactions, and gossip this. When running AOST, use the lowest known gossiped timestamp at high priority.

This wasn't particularly high priority.

**Comment by erichocean** [comment]
One option I proposed was to be able to query the gossip'd value, something like:

    select system_timestamp();

This could either (a) query all of the nodes for their greatest "safe" timestamp, or (b) just immediately return the value of the node being queried.

A user would then use this value in a sequence of subsequent queries:

   select * from foo as of system time <result>;

I do agree that there is value in knowing exactly which timestamp you got, and being able to record that somewhere (e.g. for reporting).

The primary advantage of asking for the system time that will work is that you can then run regular priority queries which are guaranteed non-blocking and guaranteed not to bounce concurrent writes. Adding a `system_timestamp()` function doesn't introduce any new syntax, and would cover my use case adequately.

**Comment by a-robinson** [comment]
Isn't this just debating the UX for follower reads (https://github.com/cockroachdb/cockroach/pull/21056)?

**Comment by bdarnell** [comment]
Yeah, it's probably best to look at this as an aspect of follower reads, since we're already building that for 2.1. Follower reads will impose a bound on how long transactions can run without refreshing their timestamp, so follower reads by definition can't disrupt running transactions.

**Comment by erichocean** [comment]
How can I do `as of system time` with a high priority transaction? You can't use that construct between a `begin/commit` pair, so the priority needs to be set as part of the `as of system time` statement, right? https://www.cockroachlabs.com/docs/stable/select-clause.html doesn't show a way to set the priority…

**Comment by tschottdorf** [comment]
@erichocean sorry, we should have pointed out that you can't actually AOST inside of a transaction right now. There's an issue open for it: #20266. This is actually fairly unfortunate

@bdarnell follower reads does not resolve intents below the close timestamp, so you can still run into conflicts with an AOST read: txn writes intent at t=50, t=50 gets closed out on that range, but txn remains pending on another range with a lagging closed timestamp. Client tries to read at t=50 and finds pending transaction, waits. Txn finally commits and unblocks client.

Once the provisional txn commit timestamp got closed out we could theoretically let pushes through, but this wasn't discussed right now. Something to keep in mind to keep follower reads from ever blocking on an intent which should be the goal. Perhaps AOST-induced pushes would just always succeed in aborting (or at least upgraded to high prio).

**Comment by bdarnell** [comment]
> follower reads does not resolve intents below the close timestamp, so you can still run into conflicts with an AOST read

Ah, right. But I still think it makes sense to consider the two features together. Essentially, the user says "I am willing to accept results up to X seconds old, and I'd rather have my results as quickly as possible than wait for fresher results". Ideally you'd use the minimum of the closed timestamp and the oldest open transaction. I think anyone who wants follower reads would *also* want to be free of running into pending intents.

I'm still not convinced that it's worthwhile to try and precisely define the latest timestamp that can be read without blocking (versus simply picking the oldest *tolerable* age and using that unconditionally), but I think if we do it we wouldn't want separate options for follower reads and avoiding pending txns.

**Comment by erichocean** [comment]
> I'm still not convinced that it's worthwhile to try and precisely define the latest timestamp that can be read without blocking (versus simply picking the oldest tolerable age and using that unconditionally), but I think if we do it we wouldn't want separate options for follower reads and avoiding pending txns.

I'll give you my actual use case. I have two tables, `target_amazon_listings_m1` and `actual_amazon_listings_m1`. I have a bunch of compute process that run independently in a loop over about 5 million SKUs. Each time a SKU is processed (roughly once per hour), 1-3 rows in `target_amazon_listings_m1` can be inserted, updated, or deleted.

Separately, on about a 10 minute cadence, I have a separate process that does a read-only loop over  `target_amazon_listings_m1` and `actual_amazon_listings_m1`, and generates a series of XML updates to submit to Amazon to "reconcile" the two, i.e. to make our catalog on Amazon match our desired ("target") listings, prices, stocks, etc. Later, the success of those updates is examined and `actual_amazon_listings_m1` is updated with the results. Rinse and repeat, indefinitely.

These two tables have millions of items, and I make many queries to both during this loop. It is also _essential_ that the reads to both are consistent **and** that I don't block any updates to `target_amazon_listings_m1` during this process—remember, I have about 5 million SKUs constantly updating this table.

So, `as of system time` is nearly perfect for me, except that I have to pick a fairly old timestamp in order to avoid blocking on a competing write. If `select system_timestamp()` was available, even if pessimistic (node-local), that would allow me to get a reasonably tight read-bound.

**Comment by erichocean** [comment]
*How long does a writing transaction typically take?

5 seconds, but it's happening continuously—we aim to have 50,000 txns in progress at any given time.

What is the maximum staleness you can tolerate from these scans?

10 minutes.

What is the downside of always running at that maximum staleness instead of fitting the query as tightly as possible to the current transactions (or choosing a timestamp around the typical writing transaction time and accepting that some slower-than-average writes may get blocked)?

People buy an item on marketplace A that we've sold on marketplace B, resulting in a cancellation and negative feedback. The tighter our numbers are, the less frequently this happens. If we have too many cancellations, our seller accounts can be suspended or penalized (worse search results, extra fees, etc.). So I try to keep our marketplace catalogs as up-to-date as possible.

**Comment by bdarnell** [comment]
> So I try to keep our marketplace catalogs as up-to-date as possible.

In that case, is "reads should never interfere with writes" really the best policy for you? If you did AOST at 5s in the past, the reads would only interfere with the relatively rare writes that were already taking longer than usual. If a write transaction was running for 5 minutes instead of 5 seconds, are you really prepared to accept much staler data in your reads just to avoid interfering with it?

**Comment by erichocean** [comment]
Right, but what I think happens in practice is this:

1. Start read-only txn at -5s.
2. Block on read of key A.
3. Unblock on read of key A, block on read of key B.
4. Repeat 3 and 4, over and over, because each time you block, someone else starts writing _another_ key you want to read.

So in practice, just going back -5s actually ends up taking a very long time.

**Comment by tschottdorf** [comment]
If you want a workaround that looks dirty but (hopefully) works today, try the following:

```BEGIN TRANSACTION PRIORITY HIGH; SELECT transaction_timestamp(); SELECT pg_sleep(5); SELECT ... AS OF SYSTEM TIME ...; COMMIT```

This query will waste five seconds sitting around at first, but then it should be able to move any stragglers out of the way.

**Comment by knz** [comment]
@tschottdorf were you intending to have `transaction_timestamp()` pin the kv txn timestamp and prevent the automatic push that spencer introduced? IIRC the `transaction_timestamp()` function doesn't pin the ts, you'd need `cluster_logical_timestamp()` to pin it.

**Comment by tschottdorf** [comment]
@knz I just want to make sure that the transaction is populated (it's probably done eagerly anyway). You're right that `cluster_logical_timestamp()` would be more efficient in avoiding internal retries, but that *shouldn't* be necessary here. This is a read-only txn at high priority, so it shouldn't be pushed by anything except uncertainty restarts, and waiting 5s eliminates those.

**Comment by bdarnell** [comment]
> Start read-only txn at -5s.
> Block on read of key A.
> 3 seconds later, unblock on read of key A, block on read of key B. 3 seconds later, unblock on read of key B, block on read of key C…
> Repeat 3 and 4, over and over, because each time you block, someone else starts writing another key you want to read and then you wait for that.

The reason to start at time `t-5s` is that you should no longer see *new* writes at that timestamp. New writes should go to time `t` or later. The only time your `t-5s` transaction should encounter new writes is if there is a transaction that has been running for more than 5s and is still going.

**Comment by erichocean** [comment]
So, I've trying to pick a decent time and that's just not working for me: I can't pick one reliably, and the txn *blocks* if I screw up.

As a recent example, I had 50 machines populating a table which in the end, had ~20,000 rows. Took about 10 minutes overall. Went to `cockroach sql` after the process we're supposedly "done" and did a simple `select count(*) from mytable;`. 5 minutes later, tried the AOST version.

In the end , I had to go back *30 minutes* to get a query that would return a result in something measured in milliseconds. Of course, the value was wrong (~300). In the end, I ran a script to bounce all 50 machines so their connections would reset. Once I had done so, the normal `select count(*) from mytable;` returned in about 200ms.

I simply cannot guarantee there aren't long-running txns stuck somewhere in the system for whatever reason. I can't even find them at this point, and I know of know `cockroach` command to kill any such txns if I could find them.

Absent that ability (and really, even with it), I need *some* way to get a txn on a table that will not block on reads seemingly indefinitely. The alternative of having some universal oracle that knows the correct AOST time, or even just the correct `pg_sleep()` time is proving to be pretty impractical.

I apologize for being emphatic on this issue. I know we all have the same goal of making CockroachDB as usable as possible in real-world scenarios. I'm *really* not trying to make life difficult. :)

**Comment by erichocean** [comment]
Thinking more about this, I think the current policy of making a connection wait for writes is inappropriate for "auto-commit" `SELECT`s. Instead of waiting for all in-progress writes, these queries should (at most) wait for the uncertainty period, but otherwise return whatever was committed when the query was made, i.e. as of whatever `statement_timestamp()` says.

It's extremely non-intuitive that one long-running txn can bring the cluster to a standstill on even the simplest of queries. I get the desire to use `SERIALIZED` for everything, but universal blocking on auto-commit selects isn't practical.

**Comment by knz** [comment]
Interesting idea. Having auto-commit (standalone) statements automatically produce an AS OF SYSTEM TIME clause suitable for not blocking other stuff is ... semantically correct! A client would not see the difference. The only drawback is that it could increase the latency of such a query significantly.

Suppose this behavior could be implemented, would you see this as an opt-in feature?

**Comment by tschottdorf** [comment]
@erichocean what you're describing sounds like there is a yet undiscovered problem at work. If your inserts all finished, there shouldn't be anything blocking reads even at the current timestamp. Perhaps your workload is tickling a bug.

@knz can we run `select * from [ show sessions ] where kv_txn IS NOT NULL;` and find the stuck transaction that way? Or actually, `SHOW QUERIES` should be more straightforward. You can even pin the query to the node, by running `set application_name = 'node 123'` on each connection before doing work.

**Comment by erichocean** [comment]
Okay, just ran `show queries` and I've got at least 10 txns that are over 45 minutes old:

    root@c1.vultr.zuberglobal.com:26257/zuber> select * from [show queries] order by start asc limit 10;
    +----------------------------------+---------+----------+----------------------------------+--------------------------------------------------------------------------+-----------------------+------------------+-------------+-----------+
    |             query_id             | node_id | username |              start               |                                  query                                   |    client_address     | application_name | distributed |   phase   |
    +----------------------------------+---------+----------+----------------------------------+--------------------------------------------------------------------------+-----------------------+------------------+-------------+-----------+
    | NULL                             |      15 | NULL     | NULL                             | NULL                                                                     | NULL                  | NULL             |    NULL     | NULL      |
    | 1531b37ad6c4f18e000000000000000a |      10 | compute  | 2018-05-24 21:58:08.497695+00:00 | SELECT * FROM skus WHERE id = $1                                         | 8.6.8.55:39976        |                  |    false    | executing |
    | 1531b37ad6a88fbd000000000000000a |      10 | compute  | 2018-05-24 21:58:08.527796+00:00 | SELECT * FROM skus WHERE id = $1                                         | 207.246.101.226:46758 |                  |    false    | executing |
    | 1531b37b143a7b990000000000000004 |       4 | compute  | 2018-05-24 21:58:08.944319+00:00 | SELECT * FROM products_m1 WHERE asin = $1                          | 140.82.22.90:51488    |                  |    false    | executing |
    | 1531b37b2d4e61720000000000000003 |       3 | compute  | 2018-05-24 21:58:09.494994+00:00 | SELECT * FROM products_m1 WHERE asin = $1                          | 8.6.8.135:53642       |                  |    false    | executing |
    | 1531b37b2e9285750000000000000008 |       8 | compute  | 2018-05-24 21:58:10.298909+00:00 | SELECT * FROM skus WHERE id = $1                                         | 8.6.8.250:36042       |                  |    false    | executing |
    | 1531b37b75ae1919000000000000000a |      10 | compute  | 2018-05-24 21:58:10.366784+00:00 | INSERT INTO missing_sellers_m1(id) VALUES ($1) ON CONFLICT (id) DO       | 207.246.101.226:46744 |                  |    false    | executing |
    |                                  |         |          |                                  | NOTHING                                                                  |                       |                  |             |           |
    | 1531b37b3b4fcca30000000000000008 |       8 | compute  | 2018-05-24 21:58:10.512607+00:00 | SELECT * FROM skus WHERE id = $1                                         | 8.6.8.250:35952       |                  |    false    | executing |
    | 1531b37b47eda0f0000000000000000a |      10 | compute  | 2018-05-24 21:58:10.724272+00:00 | SELECT * FROM skus WHERE id = $1                                         | 8.6.8.55:40052        |                  |    false    | executing |
    | 1531b37b4826f8520000000000000005 |       5 | compute  | 2018-05-24 21:58:10.728081+00:00 | SELECT * FROM products_m1 WHERE asin = $1                          | 207.246.106.27:55324  |                  |    false    | executing |
    +----------------------------------+---------+----------+----------------------------------+--------------------------------------------------------------------------+-----------------------+------------------+-------------+-----------+
    (10 rows)
    
    Time: 10.022141177s
    
    root@c1.vultr.zuberglobal.com:26257/zuber> select statement_timestamp();
    +----------------------------------+
    |       statement_timestamp        |
    +----------------------------------+
    | 2018-05-24 22:45:25.176999+00:00 |
    +----------------------------------+
    (1 row)
    
    Time: 10.859973ms

**Comment by erichocean** [comment]
Yes, all nodes were restarted.
