### ISSUE TITLE
sql: allow user priority to be set via SQL

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2555]
Cockroach internally allows a user priority to be set on all operations. This is particularly relevant to the operation of transactions, where the user priority is used to generate a random priority for the transaction as a whole. Transactions which conflict use the priorities to determine which can be pushed or aborted as necessary.

* Do some research into the SQL 92 ANSI standard and see if there's any equivalent or near-equivalent mechanism for supporting priorities.
* Make determination whether to use existing prioritization scheme or to introduce our own (probably something similar to the way we currently set the database syntax via `SET SYNTAX = modern`).
* Thread the user priority through to the underlying KV commands.

**Comment by petermattis** [comment]
SQL 92 has no mention of priorities as far as I can tell. It would be straightforward to add something like `SET TRANSACTION PRIORITY <num>` similar to the existing `SET TRANSACTION ISOLATION LEVEL`.

**Comment by vivekmenezes** [comment]
It will be more valuable to set the priority for the session rather than for every transaction. I don't see anyone changing their priority for every command they send to the server.

**Comment by bdarnell** [comment]
I think session scoping is rarely appropriate; connection pools mean that a "session" will often encompass very different operations. I think that the minority of applications that will bother with priorities at all will often want to set them on a per-transaction basis. 

Another place where setting priorities might make sense is at the user level: if the users table assigned every user a priority admins could use that to set priorities (which would have the convenience of session-scoped priorities without requiring all clients to be redeployed to change)

**Comment by vivekmenezes** [comment]
I see at least two levels of priority (latency-sensitive, and batch-processing) that users are interested in that may not map to the priorities we've implemented. These can be configured for the entire application (online application, versus analysis job). I think it will be wise to not expose the actual priority number we use internally because we do change it automatically during a retry and such.

**Comment by tamird** [comment]
SQL transactions do not retry in the kv sense, though.

**Comment by bdarnell** [comment]
@vivekmenezes We already distinguish between "user priority" and real priority. The user priority is constant across retries and is used to generate the real priority.

**Comment by jusongchen** [comment]
MS SQL server use  SET DEADLOCK_PRIORITY (at session scope) to help which
transaction to be aborted when a deadlock situation is arised


Excerpt from MS SQL doc:

Which session is chosen as the deadlock victim depends on each session's
deadlock priority:

   -

   If both sessions have the same deadlock priority, the instance of SQL
   Server chooses the session that is less expensive to roll back as the
   deadlock victim. For example, if both sessions have set their deadlock
   priority to HIGH, the instance will choose as a victim the session it
   estimates is less costly to roll back.
   -

   If the sessions have different deadlock priorities, the session with the
   lowest deadlock priority is chosen as the deadlock victim.

more infor at
https://msdn.microsoft.com/en-us/library/ms186736(v=sql.105).aspx

Regards,

Jusong Chen


On Fri, Sep 18, 2015 at 11:17 AM, Ben Darnell <notifications@github.com>
wrote:

> @vivekmenezes <https://github.com/vivekmenezes> We already distinguish
> between "user priority" and real priority. The user priority is constant
> across retries and is used to generate the real priority.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2555#issuecomment-141524244>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by spencerkimball** [comment]
Thanks Jusong--that does actually seem pretty close to what the user priority provides in our system. I wouldn't want to call it deadlock priority though.

Also these user priorities are not just for transactions, as some comments in this issue are suggesting. They're equally applicable to non-txnal commands.

**Comment by petermattis** [comment]
@spencerkimball FYI, all SQL statements are executed in a transaction context. If there is not an explicit user transaction active, then an implicit transaction is created for each statement and committed when the statement completes.

**Comment by tschottdorf** [comment]
This will be valuable for writing tests for issues such as #2861 #2859 (which would otherwise have to rely on random 10 second timeouts). So if someone wants to pick this up - it's a useful contribution.

**Comment by vivekmenezes** [comment]
It will be nice if we can explore what a user really wants here. Setting a priority is something easy to specify and implement, but that doesn't translate to an SLA that a user really wants, like 99.9% latency < 100ms. This is a very powerful feature lets explore it a bit more and make it amazing!

**Comment by yaojingguo** [comment]
I would like to have a look.

**Comment by yaojingguo** [comment]
Here is the my initial design of user priority feature. Please give your
feedbacks.

## SQL Command Syntax

Make `BEGIN TRANSACTION` to support the following new usages:

```
BEGIN TRANSACTION USER PRIORITY 100
BEGIN TRANSACTION USER PRIORITY 100 ISOLATION LEVEL SNAPSHOT
BEGIN TRANSACTION ISOLATION LEVEL SNAPSHOT USER PRIORITY 100
```

Make `SET TRANSACTION` to support the following new usages:

```
SET TRANSACTION USER PRIORITY 100
SET TRANSACTION USER PRIORITY 100 ISOLATION LEVEL SNAPSHOT
SET TRANSACTION ISOLATION LEVEL SNAPSHOT USER PRIORITY 100
```

Add the following new SQL command to show user priority:

```
SHOW TRANSACTION USER PRIORITY
```

## Value Range of User Priority

The type of user priority is int32 now. The comment for `MakePriority` in [data.go]
and the comment for `user_priority` in [api.proto] say that the range of user
priority is [1, 2^31-1). But `MakePriority` converts a user priority from
[-2^31, 2^31-1] to [1, 2^31] before generating the random priority. So the
actual value range of user priority should be [1, 2^31-1] instead of [1,
2^31-1). A negative user priority may be supplied by `InternalSetPriority`
in [txn.go].

Here are my initial thoughts on this:

- SQL commands for setting user priority only accepts a value in a new range [0,
  2^31-1]. And user priority's default value is `0`.
- `MakePriority` only accepts a value from the new range and convert `0` to `1`.
- `InternalSetPriority` should be renamed to `SetPriority` and accept a value in
  the new range.

## Scope of USER PRIORITY

ISOLATION LEVEL has already been implement as local scoped. So I suggest to
implement USER PRIORITY in the same way.

[data.go]: https://github.com/cockroachdb/cockroach/blob/master/roachpb/data.go
[api.proto]: https://github.com/cockroachdb/cockroach/blob/master/roachpb/api.proto
[txn.go]: https://github.com/cockroachdb/cockroach/blob/master/client/txn.go

**Comment by petermattis** [comment]
Do you see a need for such a larger priority range? The link to the Transact-SQL docs above show only 21 priority levels. Perhaps it would be better to not use a numeric priority at all but to have a few symbolic priority levels: `LOW`, `NORMAL`, `HIGH`.

**Comment by yaojingguo** [comment]
@petermattis, you are right. We don't need such a larger priority range. I have updated my design in my original comment. Please have a look.

**Comment by petermattis** [comment]
@yaojingguo Can you update this in light of @spencerkimball's changes to `MakePriority`?

**Comment by spencerkimball** [comment]
That PR is here: https://github.com/cockroachdb/cockroach/pull/3659

Hopefully will check in today.

**Comment by yaojingguo** [comment]
@petermattis I have updated my design in the light of @petermattis's changes. PTAL.

**Comment by petermattis** [comment]
LGTM. 

One small thought: perhaps we should drop the `USER` from the SQL syntax. For example, instead of:

```
BEGIN TRANSACTION USER PRIORITY priority_value
```

We would have:

```
BEGIN TRANSACTION PRIORITY priority_value
```

**Comment by yaojingguo** [comment]
@petermattis, I have dropped `USER`. I will start coding now.

**Comment by yaojingguo** [comment]
@petermattis. I have a PR for this issue. Could you please take a look?

And I have one question about the syntax. My original design does not allow a comma `,` between ISOLATION LEVEL and PRIORITY. But PostgreSQL supports it. And both [1] and [2] say:

> The SQL standard requires commas between successive transaction_modes, but for historical reasons PostgreSQL allows the commas to be omitted.

Which of the following choices should we pick?

1. Only support a space.
2. Only support a comma `,`
3. Support both a space and a comma `,`
 
[1]: http://www.postgresql.org/docs/9.4/static/sql-set-transaction.html
[2]: http://www.postgresql.org/docs/9.4/static/sql-start-transaction.html

**Comment by petermattis** [comment]
Let's start with a required comma. Making the comma optional won't be difficult and we're already differing from PostgreSQL syntax here.

**Comment by yaojingguo** [comment]
@petermattis I have updated the design according to your suggestion.

**Comment by yaojingguo** [comment]
@petermattis A new commit for the updated design: https://github.com/cockroachdb/cockroach/pull/3912

**Comment by petermattis** [comment]
LGTM
