### ISSUE TITLE
storage: Push timestamps more aggressively

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#25579]
In CockroachDB 1.x, pushing a serializable transaction's timestamp was tantamount to aborting it, so we were very conservative about when we did it. The RefreshSpans mechanism introduced in 2.0 makes pushing a transaction's timestamp much cheaper, so we should consider doing it more often.

Specifically, there are two opportunities where it might make sense to push the timestamp:
- PushTxn: We currently only push the timestamp if the pushee is snapshot, but extending this to serializable transactions as well would unblock the pusher at the expense of requiring a refresh in the pushee
- Command queue: Reads in the command queue block writes at lower timestamps, but not higher timestamps. Pushing a write's timestamp may allow it to proceed without blocking.

As a motivating example for pushing timestamps from the command queue, consider a workload consisting mainly of point writes with perioidic full-table reads (from https://github.com/cockroachdb/cockroach/issues/25405#issuecomment-388673471). Currently, the read acts as a barrier and forces writes to stall: the read can't proceed while any writes are in flight, and concurrent writes are blocked until the read completes. `AS OF SYSTEM TIME` queries are recommended as a workaround, but this raises the question of what timestamp should be used. If reads in the command queue didn't block writes but instead pushed their timestamps (as is already the case for past reads in the timestamp cache), the point writes would be able to continue uninterrupted while the read is in progress.

Jira issue: CRDB-5705

**Comment by andreimatei** [comment]
I think this issue deserves to continue to exist.

@nvanbenschoten @sumeerbhola I wonder what you think of the second situation Ben discusses - pushing when running into read latches. It seems to me that we should discriminate between latches held by limited scans (where the latch is likely overly-broad) and latches held by scans with known bounds. In the latter case it seems like a good idea for the write to change its timestamp; after all, it's almost certain that it will end up doing that anyway after the latches are released.
Pushing writers that encounter read latches could be a temporary thing until we get scans to not hold latches while they evaluate - discussed around https://github.com/cockroachdb/cockroach/issues/41720#issuecomment-812601948

**Comment by sumeerbhola** [comment]
Do we have a workload where this is likely to help? I am trying to understand whether there is a good reason to doing this intermediate solution now, versus waiting until we can do latchless scans.

**Comment by andreimatei** [comment]
There's [the discussion](https://github.com/cockroachdb/cockroach/issues/25405#issuecomment-388673471) Ben linked to, for example. Anything with large scans during writes...

**Comment by nvanbenschoten** [comment]
It sounds like what you're proposing is to push a writer when it runs into a read latch at a higher timestamp, so writers block less on concurrent readers. What I thought this issue was proposing (but now see that it's not) was to push a writer when _a reader runs into its latches_, so that readers block less on concurrent writers. The first proposal seems possible, though it's not clear to me how much benefit it would provide (given the observed performance of https://github.com/cockroachdb/cockroach/pull/33373) and it risks introducing false contention for limited scans, as you mentioned. The latter does not seem easily possible to me, though the benefit would be a lot larger if it was.

I think I agree with Sumeer that we should continue to pursue latchless limited scans for the time being. But I also think we should keep this issue open.

**Comment by nvanbenschoten** [comment]
> The first proposal seems possible, though it's not clear to me how much benefit it would provide (given the observed performance of #33373) and it risks introducing false contention for limited scans, as you mentioned.

I'm coming more and more around to this idea after observing how things behave in multi-region YCSB. In that workload, each row is split into 10 column families. Writes target a single column family and reads scan across all 10. What we see is that because latching currently allows reads to block on writes and writes to block on reads, these large scans allow disjoint writes to transitively block on each other. This leads to unpredictable performance when writes have a high replication latency, as it's easy for this latency to compound even across write sets that are otherwise disjoint.

So for non-limited scans, bumping the write above the read eagerly instead of waiting first seems strictly better, as it avoids blocking on a known outcome. For limited scans, this may result in false contention, as noted. However, as of https://github.com/cockroachdb/cockroach/pull/33373, limited scans won't immediately wait on conflicting writes, so there may be something we can do to avoid this waiting on these reads leading to false write-write contention.

Any change here will want to be sure to avoid introducing read-within-uncertainty-interval restarts in cases where a write gets bumped above a read and slips ahead of it.

**Comment by sumeerbhola** [comment]
> However, as of #33373, limited scans won't immediately wait on conflicting writes, so there may be something we can do to avoid this waiting on these reads leading to false write-write contention.

Since I am planning to revive that PR: limited scans will optimistically evaluate, by not waiting on their latches, but they will have added their latches, so the writes will observe them (as is already discussed earlier in this thread). We could mark these latches as special in some way, so that writers don't push their timestamp when encountering them.

> Any change here will want to be sure to avoid introducing read-within-uncertainty-interval restarts in cases where a write gets bumped above a read and slips ahead of it.

Won't the local uncertainty limit be sufficient for this? Or is the issue here that there is literally a local race between the read and write, and the read does not have an observed timestamp yet (though the initialization of the observed timestamp happens in `Store.Send` so seems to be before one would compute the localUncertaintyLimit for the read).

**Comment by nvanbenschoten** [comment]
> We could mark these latches as special in some way, so that writers don't push their timestamp when encountering them.

I was thinking along these lines as well. During optimistic evaluation, reads will not be waiting on writes, so it would be safe for writes to wait on reads without risking transitive, false write-write conflicts. It's only once the optimistic evaluation fails that we'll want writes to push their timestamp above the reads. Or we may decide that blocking of limited scans is worth it even after this point, to avoid pushing the timestamp of writes that wouldn't otherwise get bumped if we waited to see how far the scan read.

> Won't the local uncertainty limit be sufficient for this?

I don't think this will be sufficient unless we ensure that the writes get pushed to `max(read_timestamp, local HLC clock) + 1`. Otherwise, we would only bump the write timestamp to `read_timestamp + 1`, which would still often be within the read's uncertainty interval.

> Or is the issue here that there is literally a local race between the read and write, and the read does not have an observed timestamp yet (though the initialization of the observed timestamp happens in Store.Send so seems to be before one would compute the localUncertaintyLimit for the read).

Right, the read will have already gathered its observed timestamp, so this isn't a local race. So instead of pushing the write to `max(read_timestamp, local HLC clock) + 1`, we could push it to `max(read_timestamp, read_local_observed_timestamp) + 1`.
