### ISSUE TITLE
pgwire: replace deadline and connection polling with separate goroutine

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25585]
From https://github.com/cockroachdb/cockroach/pull/25328#issuecomment-386760916:

>Rather than setting a deadline on the read and periodically polling whether the session is cancelled, we could fire up another goroutine which blocks on ctx.Done() and then closes the connection. I recall there was some reason this approach wasn't taken when this code was written, but taking another look it isn't clear to me why it wouldn't work. This would be a bit more involved of a change, so I'm fine with the current PR as a stop-gap solution.

The reason we use a deadline approach in the first place is because:
>even when the context is canceled, you still might need to use the connection to send back an error (e.g. sending an AdminShutdownError when draining).

However, this can be worked around by half closing the connection. That is, we can close the connection for reading but still write to it. See [TCPConn.CloseRead](https://golang.org/pkg/net/#TCPConn.CloseRead).

Jira issue: CRDB-5704

**Comment by knz** [comment]
I think this was done @andreimatei right?

**Comment by nvanbenschoten** [comment]
No this was not. We still poll.

**Comment by Zyqsempai** [comment]
Is this one still actual?
If yes, i will be glad to take care of it, but i need some more information(since it's my first issue) about where to start?

**Comment by asubiotto** [comment]
@Zyqsempai thanks for your interest! Yes, this issue is still available. The current landscape is that we create a `readTimeoutConn` here:
https://github.com/cockroachdb/cockroach/blob/1c7351ef238a3bf25ed35ab25bc8336333ddaf80/pkg/sql/pgwire/conn.go#L237
in order to have connections listen for context cancellation when the server is about to shut down (canceled in this method): https://github.com/cockroachdb/cockroach/blob/1c7351ef238a3bf25ed35ab25bc8336333ddaf80/pkg/sql/pgwire/server.go#L332. Since `Read`s block, we periodically wake the connection up and have it check its context, which results in higher than necessary CPU usage. The proposal is to call `CloseRead` on this connection (as a tcp connection) in `drainImpl` so that this causes the `Read` to unblock when necessary. The reason a full `Close` cannot work, is that the server must still send a message to the client as to why the connection was closed (see `AdminShutdownErr`). Note that `CloseRead` only exists on the `TCPConn` implementation of `net.Conn` so we'll have to cast `net.Conn`s as `TCPConn`s (they can also sometimes be `tls.Conn`s, so we'll have to get the underlying `conn` in that case), I think doing this without introducing new error cases will probably be the hardest part.

**Comment by Zyqsempai** [comment]
@asubiotto Hi, thanks for explanation.
But i have few questions.
What is the best place to make `CloseRead`?
https://github.com/cockroachdb/cockroach/blob/1c7351ef238a3bf25ed35ab25bc8336333ddaf80/pkg/sql/pgwire/conn.go#L1879
we have that `Read` function, which check the exit conditions, does it make sense to rename the type and change the behavior of that function?

**Comment by asubiotto** [comment]
The `CloseRead` should be done by the server in `drainImpl` on the connections where we're currently canceling them (nothing should necessarily change in `drainImpl`, but the `context.CancelFunc` will probably now be a custom function that does this (and probably also send `DrainRequest` over the `stmtBuf`. The `readTimeoutConn` exists only for the purposes of checking exit conditions. Since we would now preempt connections, there is no need for the `readTimeoutConn` wrapper any more so we can probably just remove it.
I'm realizing that this issue is a bit more involved than it first seems, so I'm removing the "good-first-issue" label since it's probably not the best way to start contributing to cockroach, but please don't let this deter you from working on this!

**Comment by Zyqsempai** [comment]
@asubiotto Thanks for pointing me, I have strong willing to start contributing to cockroach, so no worries;)

**Comment by rafiss** [comment]
Right now, the early exit condition is:
```
	rtc.checkExitConds = func() error {
		// If the context was canceled, it's time to stop reading. Either a
		// higher-level server or the command processor have canceled us.
		if err := ctx.Err(); err != nil {
			return err
		}
		// If the server is draining, we'll let the processor know by pushing a
		// DrainRequest. This will make the processor quit whenever it finds a good
		// time.
		if !sentDrainSignal && s.IsDraining() {
			_ /* err */ = c.stmtBuf.Push(ctx, sql.DrainRequest{})
			sentDrainSignal = true
		}
		return nil
	}
```

That means if we switch to using a separate goroutine, then we need to check `ctx.Done()` as well as check if the server is draining. I think we need to create another channel inside of `pgwire.Server` that can be used for that.

**Comment by rafiss** [comment]
This issue is pretty old, so I believe there are a few out of date comments from the initial thread.

> even when the context is canceled, you still might need to use the connection to send back an error (e.g. sending an AdminShutdownError when draining).

I don't think this is the case anymore. The only time AdminShutdownError is sent is when draining starts. If the context is cancelled, the current code will just give up on reading and start returning errors: https://github.com/cockroachdb/cockroach/blob/db5d44dbc96456c8bb555320152b91d42524f6bb/pkg/sql/pgwire/server.go#L865-L870

Even so, I guess using CloseRead won't hurt.

> The proposal is to call CloseRead on this connection (as a tcp connection) in drainImpl so that this causes the Read to unblock when necessary.

I don't think it will be possible to do this in drainImpl, since that function doesn't have a reference to the connection. (Nor should it IMO, since that would mean it needs to hold a reference to _all_ the connections.) So instead, we should do this in a separate goroutine right before calling `(pgwire.Server).serveImpl`.
