### ISSUE TITLE
Remove Tuple as a result type from the parser

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2567]
postgres supports returning a tuple as a result type:

create table xyz (x int primary key, y int, z int);

select DISTINCT (y,(y,z)), y from xyz;
     row     | y 
-------------+---
 (2,"(2,3)") | 2
 (2,"(2,)")  | 2
(2 rows)

We should decide to either fully support it, or remove it from our parser. I can't see a need for this. Thoughts?

**Comment by vivekmenezes** [comment]
We don't support: Count(x, y)
but support: Count((x,y)), because (x,y) is a single value of type Tuple.

**Comment by petermattis** [comment]
We don't support `count(x, y)` because that function does not exist. For that matter, it doesn't exist in postgres or mysql either. The argument to count needs to be a single expression, while `x, y` is two expressions. FYI, `count((x, y))` is shorthand for `count(row(x,y))`.

We could fairly easily return a tuple for `select (1, 2)`, though we'd hit an impedance mismatch with the Go SQL driver interface. 

We definitely need to support certain tuple operations, though (e.g. `select * from t where (x, y) = (1, 2)`). I'm not quite clear on what you're proposing to remove from the parser.

**Comment by fire** [comment]
The concept of ranges is somewhat related as it involves data types that can be decomposed. http://www.postgresql.org/docs/9.4/static/rangetypes.html 

Sorry if this doesn't fit here.

**Comment by vivekmenezes** [comment]
@fire thanks for pointing out the range types in postgres.

@petermattis I brought this up because I was surprised to find us supporting SELECT Count((x,y)), and not SELECT (x,y). The error message you get when you run SELECT (x,y) is also weird. Now I see some value in supporting Count((x,y)), and we should keep it.

I am proposing removing Tuple as a RESULT type in the parser unless we are committed to supporting it. The lack of support in the Go driver perhaps is evidence that it isn't valuable to users.

**Comment by petermattis** [comment]
@vivekmenezes Would you want to remove support for `SELECT * FROM t WHERE (a, b) IN (SELECT x, y FROM z)`? In this case, the subquery SELECT is returning a list of tuples which are then being used by the IN expression. I think the current error message for when a top-level statement does `SELECT (1, 2)` is bad, but I don't think we should remove support for `SELECT` returning tuple values.

@fire We're unlikely to support range types any time soon. Indexing of range types relies on the postgres Gist indexing method which is not something we can support given our current storage backends.

**Comment by vivekmenezes** [comment]
@petermattis we should keep it. Closing this issue.
