### ISSUE TITLE
roachtest: use roachtest from branch instead of master

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25740]
Now that 2.1 and 2.0 are diverging, it is becoming more irksome to be running the `roachtest` from master against the release-2.0 branch. For example, https://github.com/cockroachdb/cockroach/issues/25738 is a failure of that test caused by usage of a cluster setting that doesn't exist on the 2.0 branch. Using the `roachtest` from master made sense when the 2.0 branch was initially created and most PRs on master were being back-ported. We're no longer in that world.

Changing this is relatively straightforward, though we'll likely want to back-port a number of `roachtest` PRs (i.e. the filing of issues) to the release-2.0 branch.

**Comment by jordanlewis** [comment]
We also need to backport the `build/teamcity-local-roachtest.sh` script to all branches. Currently, we try to trigger that script and fail if it doesn't exist (like in the old release branches).

**Comment by danhhz** [comment]
If we didn't want to backport it, the every-pr roachtest build could also be made to pass if the script doesn't exist.

**Comment by jordanlewis** [comment]
That's what's done today, using a TeamCity custom script. But nobody likes those.

**Comment by danhhz** [comment]
Separately, I also would like to register my preference that instead of keeping roachtests backported to the release branches, we should instead be passing the major version into the roachtest invocation, and it can be used to skip as necessary. It will be considerably less maintenance and our public interface should be stable enough that including a minimum major version in the roachtest config is not significant overhead

**Comment by petermattis** [comment]
@danhhz The branch we're building against is already available via the `TC_BUILD_BRANCH` environment variable. We could make that more obvious. Are you imaging that each test would be configured with the minimum version it is run against? Do we run into problems with tests like `hotspotsplits` where a metric used by the test is only available on a newer version?

**Comment by tschottdorf** [comment]
>  our  public interface should be stable enough that including a minimum major  version in the roachtest config is not significant overhead

We're not limiting ourselves at all to our public interface, and this is bound to become worse over time. In the last few weeks alone there have been a number of crdb_internal tables. Plus, roachtests can in principle hit various grpc endpoints and this too is something I'll likely have to end up doing for some low-level (yet at-scale) tests I need to write.

Not saying this suggests going the other direction, but it seemed a lot more natural to me to run the tests from the branch against the branch. Perhaps past experience here has taught some otherwise.

**Comment by danhhz** [comment]
Who knows, maybe my assumptions are off. What would you imagine would happen in one of these tests that use grpc endpoints directly? Would it exist in both branches with different behavior? Or would it only exist on branches new enough to have it (or have its most recent behavior)?

**Comment by tschottdorf** [comment]
Yeah, similar to how when you introduce a new unit test, it would only run against future branches that have that commit. This requires the occasional backport, but *hopefully* roachtests fall broadly into two categories:

1. they exercise something that's new to cockroach (i.e. something that was fixed), so they get backported iff the new thing gets backported and
2. they test something general that's always been there, then you can always backport the roachtest.

I think there's enough flux in the roachtest/workload sphere to justify doing what you're suggesting, though, so I'm open to that. It will be easy enough to skip problematic tests.

**Comment by danhhz** [comment]
That's a great framing. I feel like my instincts here are that we should make (2) as low-friction as possible (aka no explicit backport, it happens automatically) to encourage people to write more roachtests. Once we have a more robust set of roachtests and we think most new ones would be for new features, then I think my opinion would swing to snapshotting them in branches.

**Comment by petermattis** [comment]
Ok, I'll add a facility for roachtests to specify the minimum version they require to run. Should be relatively straightforward to do this and we can iterate and extend it as necessary.

**Comment by nvanbenschoten** [comment]
Whichever approach we decide on, I think we should consider that over time the distribution of new roachtests will begin to trend toward category one. We're still in somewhat of a catch-up phase with these roachtests, which is why most of them have fallen into the second category. I also suspect that as the testing becomes more complex, the "tests for something general that's always been there" will actually require small behavioral changes that may not necessarily be backported, so even they will technically fall into category one. This would lead me to believe that we should run only the roachtests on a branch against that branch.

That said, I think there's a third category which is missing: _changes to existing roachtests to adjust assertions and fix flakes_. Depending on how many of these we see in practice, they might make the cost of maintaining multiple versions of the same roachtest through backports prohibitive.

**Comment by petermattis** [comment]
> This would lead me to believe that we should run only the roachtests on a branch against that branch.

Well, we're not locking ourself into any approach at this point. I've implemented a mechanism that allows tests to specify a min-version they require in order to run. If it becomes onerous to specify this we can revisit.
