### ISSUE TITLE
Truncating and inserting inside a commit fails

### ISSUE THREAD

**Issue by elliott-davis** [cockroachdb/cockroach#25794]
Version 2.0.1

2. Please describe the issue you observed:

- What did you do?

```
BEGIN TRANSACTION;
TRUNCATE schema_migrations;
INSERT INTO schema_migrations (version, dirty) VALUES (1, true);
COMMIT;
```

- What did you expect to see?

Success with new rows inserted into the `schema_migrations` table

- What did you see instead?

```
error: pq: relation "schema_migrations" does not exist in line 0: INSERT INTO "schema_migrations" (version, dirty) VALUES ($1, $2)
```

**Comment by vivekmenezes** [comment]
@elliott-davis TRUNCATE is not transactional in cockroachdb because it assumes the table can be very large and we also support AS OF SYSTEM TIME queries on old data making large deletions of data prohibitively expensive.  We could consider making it transactional for "small" tables. Is this something that could interest you?

**Comment by elliott-davis** [comment]
I think that could be useful - at least to not surprise users coming from postgres

**Comment by vivekmenezes** [comment]
@elliott-davis I have a fix referenced here that will work but will not work for tables with a FK reference. I have another issue https://github.com/cockroachdb/cockroach/issues/26166 tracking it for FK tables.
