### ISSUE TITLE
qa: point in time restore

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#25820]
You can publish your QA plan before starting.

**Comment by vivekmenezes** [comment]
@couchand any chance you can QA this this week?

**Comment by couchand** [comment]
Test Plan: Point-in-Time Restore
================================

This document describes the initial plan for testing the new point-in-time
restore feature.  We provide a general description of the expected
functionality, enumerate the major dimensions which will come into play, and
then analyze which combinations of options will need to be studied to provide
the best coverage of the major use cases.  Finally, we sketch out the general
flow that tests will take and list the specific checks to be made at each step.

- Background
- Significant Dimensions
- Documented Limitations
- General Flow of Tests
- Representative Test Cases

Background
----------

CockroachDB is designed with fault-tolerance in mind, so in the course of normal
operation there should be no need to deal with backups.  However, to support
recovery from large-scale disaster scenarios, we have developed a distributed
backup and restore feature that allows an organization to have high confidence
that their data is secure from major loss, even in the event that the cluster
becomes fundamentally broken.

In version 2.0 of CockroachDB, a point-in-time version of the existing
enterprise restore functionality was introduced as a beta feature.  This builds
on the same architectural foundations as the `AS OF SYSTEM TIME` query phrase.
Cockroach uses multi-version concurrency control to provide transactional access
to the stored data.   On a periodic basis, the system cleans up old versions
of data, but until that time, the old versions are still accessible.  We have
supported querying that data for a while with `AS OF SYSTEM TIME`, but the new
feature adds support to export those old versions as part of an enterprise
`BACKUP` command by adding `WITH revision_history`.  Then future `RESTORE`
statements can utilize these old versions by restoring to a particular point
in history rather than latest by adding `AS OF SYSTEM TIME` to the command.

Since the point-in-time restore feature is intimately tied to backup with
revision history, and both are specific flavors of the general `BACKUP` and
`RESTORE` commands, many of the important testing dimensions will be generally
applicable to all testing of backup/restore.  This testing plan describes user
flows, starting with run-of-the-mill SQL data definition and manipulation
statements, followed by one or more invocations of `BACKUP`, and finally the
use of a `RESTORE` statement followed by verification of the results.


Significant Dimensions
----------------------

First we will document, for completeness, dimensions that apply equally to
general backup/restore.  Afterwards, we'll examine the dimensions particular
to point-in-time restore.

### General Backup/Restore Dimensions

- What to back up: whole database, single table, multiple tables.
- What to restore: whole database, single table, multiple tables.
- How to back up: full, full + incremental, full + several incremental.
- Schema details: various column types and configurations.
- Schema dependencies: foreign keys, sequencies, views, interleaved tables.
- Skipping dependencies on restore: foreign keys and sequences.
- Target database: original or using `into_db` to go elsewhere.
- Job control: pausing, resuming, and canceling backup and restore jobs.

Some of these dimensions have obvious interactions with the revision history
backup and point-in-time restore and will require more complete testing, others
might only be examined on a more cursory basis.

### Specific Point-in-Time Restore Dimensions

- Which backups have revision history: All, or some subset of them.
- Time to restore as of: too early, during backup, too late.
- Garbage collection window: the specific value of this setting should not
  make a difference, only the relationship of this window with the as of times
  used for the backup and restore commands.

The bulk of the specific point-in-time restore testing will be developing
specific timelines that exercise different scenarios relevant to the feature.

Documented Limitations
----------------------

There are a number of documented limitations to backup/restore generally, and
revision history backup and point-in-time restore specifically.  For the most
part, testing of these will be just checking that the limitation is applied
sensibly and that error messages are more or less clear.

- Both backup and restore require root.
- When restoring, the target database must exist, but the tables must not.
- Privilege grants on the tables are not included in the backup.
- Default grants on the target database are applied to restored tables.
- Incremental backups must be taken within the GC window.
- When restoring, incremental backups must be specified in order.
- Neither backup nor restore is allowed inside a transaction.
- An entire database may only be restored if the whole database was backed up.
- Incremental backups cannot be taken after a `CREATE`, `DROP`, or `TRUNCATE`.
- Point-in-time restore can only be made from a backup with revision history.

General Flow of Tests
---------------------

Always:

- Create database.
- Create table(s).
- Insert, update, or delete some data.
- (Timestamp A)
- Create, drop, truncate, or alter tables, and/or:
- Insert, update, or delete some data.
- (Timestamp B)
- Create, drop, truncate, or alter tables, and/or:
- Insert, update, or delete some data.
- (Timestamp C)
- Full backup of database or table(s) as of B.

Zero or more times:

- Alter tables, and/or:
- Insert, update, or delete some data.
- (Timestamp D)
- Alter tables, and/or:
- Insert, update, or delete some data.
- (Timestamp E)
- Incremental backup of database or table(s) as of D.

Always:

- Restore from full or incremental backup(s) as of some timestamp.
- Verify expected data exists, other data does not.


Representative Test Cases
-------------------------

The above general script can be followed for most of the tests that will be
performed, altering and filling in details for each of the important cases.
In particular, we will be sure to cover:

- Full backup with revision history, restoring from a time in that history.
- Full & incremental backups with revision history, restoring from a time in:
  - the first (full) backup,
  - the most recent incremental backup, and
  - an intermediate incremental backup.
- Full & incremental backups, only one of which has revision history, restoring:
  - the first (full) backup,
  - the most recent incremental backup, and
  - an intermediate incremental backup.

This last group of scenarios should each cover at least one case each where the
restore as of timestamp is before and after the range of the backup that was
taken with revision history.

Crossing each of these general scenarios should be the most important general
backup dimensions, specifically column types, schema dependencies, target
database, and job control.
