### ISSUE TITLE
qa: sql bytea_output

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25840]
Issue #20782.
PR #25835

**Comment by vivekmenezes** [comment]
@arjunravinarayan reminder to QA this item soon

**Comment by arjunravinarayan** [comment]
Apologies for the delay. The set of dependencies (namely: pgadmin4)
required that I upgrade my linux distribution. This did not seem like
a justifiable way to spend a workday, so I waited for a weekend to
perform the upgrade.


First, I began by trying to understand the feature. It seems
`BYTEA_OUTPUT` was added to enable PGADMIN4 support. So that seemed
like a good place to start. Googling around revealed that PGADMIN4
will not even connect to the database without `BYTEA_OUTPUT` support
(this is a problem for postgres < 9.6). Thus, one simple test would be
to simply try and connect to a cockroach cluster with PGADMIN4. If it
works, then the motivating issue is solved.

I then read the `BYTEA_OUTPUT` docs for Postgres. It says there are two
possible values for this setting: HEX and ESCAPE. I don't know what
this means. However, I can empirically test this.

I created a table in Postgres (connected via psql).

`CREATE TABLE FOO (bar BYTEA)`

And then I ran

`INSERT INTO FOO VALUES ('a')`

Followed by

```
root=> set bytea_output = hex;
SET
root=> select * from foo;
  a
------
 \x61
(1 row)

root=> set bytea_output = escape;
SET
root=> select * from foo;
 a
---
 a
(1 row)
```

I then connected to a cockroach cluster (running
`v2.1.0-alpha.20180702-1943-ga4a744dc44`) and observed the exact same
results in PSQL.

However, when running the same commands via the Cockroach Client, the
output was `a` in both ESCAPE mode and HEX mode. This could just be
incorrect client behavior, and not incorrect wire behavior, since PSQL
renders the right thing.

I then connected to a v2.0 cluster, and then ran re-ran the commands
via PSQL. I saw the following output:


```
root=> set bytea_output = escape;
ERROR:  unknown variable: "bytea_output"
```

However, PSQL rendered the `\x61` format output regardless, so the
bytea output must be in HEX mode by default.


I saw the same results with the cockroach client.

I then attempted to connect to the cluster via PGADMIN4. On v2.0 I
received the following error upon opening a connection:

`ERROR: unknown variable: "bytea_output"`, which is the same error
that is received when trying to use the `SET` command.



This also matches the errors reported for Postgres pre-9.6
incompatibility with PGADMIN4. I then attempted to connect to the
cluster with the 2.1 alpha. I did not receive this error, and
connected successfully.

However, I must note that PGADMIN4 is not really usable with
cockroach. It was unable to introspect the existing databases, and was
unable to create a database (since the default SQL it outputs is
`CREATE DATABASE foo WITH OWNER = root`, and CockroachDB does not
support `WITH OWNER`). However, we do know it's getting past the
BYTEA_OUTPUT barrier, since I was able to inspect users (but not
create them).

Therefore I conclude that `SET BYTEA_OUTPUT` is working correctly,
although the Cockroach client rendering is not respecting the setting
as psql does. It is unclear if this is intended or not. If we wish to support PGADMIN4, we will need to do some concerted
testing, and perhaps add stub syntax that doesn't do anything for
things like `CREATE DATABASE ... WITH OWNER` that don't seem
changeable within PGADMIN.

**Comment by justinj** [comment]
(the problem you're describing with the client was #20525, I think, which appears to have been closed)

**Comment by knz** [comment]
The problem you encountered is that `lib/pq` is too clever for its own good. `psql` does not interpret the bytes received from the server so you can observe the encoding that the server used. `lib/pq` (the driver used by `cockroach sql`) attempts to "guess" the encoding and decode the bytes always so you cannot observe the difference.

Your experimental step to use `psql` to validate the feature was the correct one. The steps you used and the conclusions you drew are also correct. I'd say, this was a nice piece of QA. Thank you.

**Comment by arjunravinarayan** [comment]
In general I was not too bothered by the lack of defined success criteria. It made me look around and make up my own testing requirements, without being constrained by your (the implementing engineer's) preconceptions. The uncertainty conveyed in my QA report was thus intentional. It allows the review of the QA to discard information that end up being out-of-scope, without inhibiting exploration during the QA. In general I was quite happy to be forced to think about it from first principles.

**Comment by knz** [comment]
Thanks, that's really a helpful comment.

**Comment by arjunravinarayan** [comment]
You're welcome! Thanks for the feedback. I'll close the issue since we both feel like the QA validated everything and there are no actionables left.
