### ISSUE TITLE
storage: use of finalized trace in TestStoreRangeRebalance in multi-cpu

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2593]
This occurred on a six-node cluster which was under constant insertion load; splits were occuring and ranges were being rebalanced. At some point the node which was receiving the insertion load crashed with this error; I was able to restart it.

Unfortunately I do not currently have a test which reproduces this; working on that.

Stack trace:
```
W0919 00:47:53.450129 9746 kv/dist_sender.go:569 failed to invoke *proto.MergeRequest ["\x00tsdcr.store.keycount.2\x00\x01\n\x01\f\x06\x1d\\",""): range 1 was not found
panic: use of finalized Trace:
Name Origin Ts Dur Desc File
c638073448831290.11 localhost:8082 00:47:53.449029 920.404µs node server/node.go:483
c638073448831290.11 localhost:8082 00:47:53.449049 884.354µs ·executing Batch storage/store.go:1198
c638073448831290.11 localhost:8082 00:47:53.449055 876.869µs ··read-write path storage/replica.go:584
c638073448831290.11 localhost:8082 00:47:53.449060 7.317µs ···command queue storage/replica.go:816
c638073448831290.11 localhost:8082 00:47:53.449072 859.503µs ···raft storage/replica.go:875
c638073448831290.11 localhost:8082 00:47:53.449940 0 ·error: *proto.RangeNotFoundError server/node.go:490


goroutine 85 [running]:
github.com/cockroachdb/cockroach/util/tracer.(*Trace).epoch(0xc82230e140, 0x4dac6d0, 0xe, 0x0)
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/tracer/tracer.go:106 +0xda
github.com/cockroachdb/cockroach/util/tracer.(*Trace).Epoch(0xc82230e140, 0x4dac6d0, 0xe, 0x10)
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/tracer/tracer.go:101 +0x4d
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc8203ea000, 0xc8209338c0, 0x10, 0x2499, 0x1, 0x200000002, 0x140547af3362b531, 0x0, 0x140547af335f193a, 0x6569eff0d6f26a13, ...)
/Users/matt/go/src/github.com/cockroachdb/cockroach/storage/replica.go:941 +0x256
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
/Users/matt/go/src/github.com/cockroachdb/cockroach/storage/store.go:1498 +0xa39
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820072d80, 0xc82024ca30)
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x62
```

**Comment by tschottdorf** [comment]
what's on this line here? /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/replica.go:941 +0x256

This error can occur if you have a panic (since the `Finalize` call is usually in `defer()`). It can also happen if the trace isn't properly duplicated when the `ctx` crosses goroutine boundaries (which of course is a bit unexpected, but it's been quite effective at making sure the trace doesn't do that (it should not)).

**Comment by tschottdorf** [comment]
ok, I took another look. It looks like the request is aborted with a `multiraft.ErrGroupDeleted` which turns into a `RangeNotFoundError`, but a little later the request still pops up in `processRaftCommand`. This can happen if the group is deleted while the request is pending, in which case it's cancelled explicitly by MultiRaft, but may already have been picked up by the leader.

I also noticed that we're leaking pending commands: `r.pendingCmds` is written to when the command is being proposed, but it's deleted only in `processRaftCommand` (but we don't necessarily ever get there).

I think the latter problem can be solved by some refactoring which deals with `pendingCmds` and `errChan` simultaneously (i.e. delete from the former after reading from the latter). That change would also greatly reduce the chances of seeing the trace issue again, though only because we'd be "virtually certain" that the cleanup of the pending cmd would precede the eventual processing of the command, which would then run with a "dummy" context and not use the trace. But there isn't any guarantee and I don't see a straightforward solution.

**Comment by tschottdorf** [comment]
**should** be fixed with #2977. If it reoccurs, we'll investigate anew.

**Comment by tschottdorf** [comment]
Alas. Investigating anew.

**Comment by tschottdorf** [comment]
@mrtracy you got this one, right?

**Comment by mrtracy** [comment]
Yes, working on it
