### ISSUE TITLE
kubernetes: DaemonSet secure config

### ISSUE THREAD

**Issue by lwsanty** [cockroachdb/cockroach#26038]
in `cloud/kubernetes/performance/cockroachdb-daemonset-insecure.yaml` it is said that
```
# If you're interested in using a DaemonSet in secure mode, please reach
# out to us via a Github issue or our public Gitter channel.
```
So I'm asking about examples or legit ways to build daemonset config file to force cockroach work in secure way

**Comment by a-robinson** [comment]
Thanks for following up on that. I don't have a working example that I can point you at today, and it's unlikely I'll create one in the immediate future unless more people are interested in it, but you can try it yourself if you're feeling a little adventurous:

Take the [`cockroach-k8s-request-cert` init container from our normal secure `StatefulSet` config file](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset-secure.yaml#L155) and stick it into the `DaemonSet` config in the same way it's used in the `StatefulSet` config. I think you'll either have to modify the `cockroach-k8s-request-cert` invocation to add its IP address to the `-addresses` flag or you'll have to pass `--advertise-host=$(hostname -f)` to the main cockroach process and use the machines' hostnames rather than IP addresses in the `--join` flag.

If you do that, you'll have to approve each of the certificates as they're created when you first spin the cluster up, but everything should work fine as long as you don't change which machines cockroach runs on. If you add new machines, you'll have to approve new certs correspondingly as the machines are added. You could automate this as well with some code that watches for certificate-signing requests and auto-approves them, but we don't have such a tool today.

**Comment by lwsanty** [comment]
got it!
however, could you please describe a bit how to `modify the cockroach-k8s-request-cert invocation to add its IP address to the -addresses` ?

**Comment by a-robinson** [comment]
@lwsanty, I've added a config file and instructions in https://github.com/cockroachdb/cockroach/pull/26816. If you're still interested, give it a try and let me know how it goes for you.

**Comment by lwsanty** [comment]
@a-robinson it works, thanks a bunch!
