### ISSUE TITLE
sql: make TIMETZ more pg-compatible

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26097]
Following up to #25224.

Currently TIMETZ does not store the time zone.
The code could be adapted to do this and make the data type more compatible with postgres.

**Comment by bobvawter** [comment]
Is there a similar need for `TIMESTAMPTZ`, too?

**Comment by jordanlewis** [comment]
Luckily, no. TIMESTAMPTZ behaves like we thought TIMETZ did - no timezone stored, interpreted according to session timestamp at time of read.

**Comment by knz** [comment]
@jordanlewis what do you think will be the timeline on this?

Unless you propose to come up with something soon-ish, I suggest we create an intermediate step where the feature is disabled. I already filed https://github.com/cockroachdb/docs/issues/3254 to remove it from docs.

**Comment by jordanlewis** [comment]
I'll be working on this within the next 2 weeks.

**Comment by otan** [comment]
Done some digging and will start implementation on this shortly.

In postgres, TimeTZADT is stored as {timeofday, zone_offset}. However, zone_offset is not quite what you expect naturally - it is the negative of the offset given by `t.Zone()`. For example, ET is `-05:00` but the offset is stored as 18000.

For comparisons, it compares timeofday, and then zone_offset. For an illustration:
```
 otan=# select '19:00+03'::timetz < '16:00+00'::timetz;
 ?column?
----------
 t
(1 row)

otan=# select '19:00+03'::timetz = '16:00+00'::timetz;
 ?column?
----------
 f
(1 row)

otan=# select '19:00+03'::timetz < '13:00-03'::timetz;
 ?column?
----------
 t
(1 row)

otan=# select '19:00+03'::timetz < '16:00'::time;
 ?column?
----------
 t
(1 row)
```

My plan is to bring back https://github.com/cockroachdb/cockroach/pull/28095/files over parts, but largely adapting the encoding used by https://github.com/cockroachdb/cockroach/pull/27605 because it would've been correct (minus some test failures which I will look at addressing).
