### ISSUE TITLE
sql: support `create sequence OWNED BY option`

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#26382]
See https://www.postgresql.org/docs/10/static/sql-createsequence.html

`CREATE SEQUENCE OWNED BY  <table>.<column>` attaches a sequence to a particular column so that dropping that column (or table) also drops the sequence.

There can be multiple sequences attached to the same table/column.

**Comment by awoods187** [comment]
CC @vilterp @knz

**Comment by vilterp** [comment]
@knz I was surprised to see that this is not an option for tables in postgres: [the docs](https://www.postgresql.org/docs/current/static/sql-createtable.html) just say "The table will be owned by the user issuing the command".

Currently, sequences in CRDB follow the behavior for tables, so "owned by user issuing command" should be the behavior. How is ownership of a schema object represented by our SQL system? Don't see anything in `structured.proto`, so I'm not sure where this change would be made.

**Comment by knz** [comment]
@vilterp there must be a misunderstanding. The syntax is `CREATE SEQUENCE ... OWNED BY <table>.<column>` or `OWNED BY NONE`. When a sequence is attached to a column in this way, dropping the column (or the table) also drops the sequence. 

It would make little sense (to me) to attach a table or view to another table's column in this way.

**Comment by vilterp** [comment]
Ah yes, sorry, I read the docs too hurriedly and thought it was `OWNED BY <user>` instead of `OWNED BY <table>.<column>`.

While we don't yet have the `OWNED BY` syntax, the "ownership" relation between a table column and a sequence already exists in Cockroach — it's stored in `dependedOnBy` field on the sequence's table descriptor and the `usesSequenceIDs` field on the column descriptor, and is added implicitly when the user specifies a `DEFAULT` expression for a column which uses `nextval('some_sequence_name')`. The `DROP SEQUENCE` statement consults these fields so that it doesn't drop a sequence if it's being used by a column.

So, we would implement `CREATE SEQUENCE … OWNED BY` and `ALTER SEQUENCE … OWNED BY` by updating those fields on the protos. Seems fairly small.

Related note: another small difference between PG and CRDB: In PG, when you create a column using the `serial` type, it implicitly creates a sequence that's `OWNED BY` that column. With us, you have to create the sequence explicitly, but the ownership is set when you create the column, so you still don't have to use `OWNED BY` in that circumstance. Curious how people are running into this — probably SQL generated by ORMs uses it.

**Comment by knz** [comment]
Note: if/when this becomes supported, the ownership must be reflected properly in information_schema/pg_catalog. This is verified by ORMs, eg TypeORM, see https://github.com/cockroachdb/cockroach/issues/22298#issuecomment-427961316 for an example.

**Comment by awoods187** [comment]
Needed for https://github.com/cockroachlabs/support/issues/267

**Comment by arulajmani** [comment]
After digging into this a bit, I think the PG ownership concept is different from the relationship established by having a table column in the  `dependedOnBy` list in CRDB. 
1. PG only allows one column to be an owner, where as a sequence could be depended on by multiple columns theoretically. 
2. A sequence that is owned by a table can be dropped without the table being dropped -- if we were to add the sequence to `dependedOnBy` when ownership is added, CRDB would not mirror that behavior. 

To create an ownership relationship as close as PG, I think it will require a new field in the proto.
