### ISSUE TITLE
sql: normalization is O(n^2) in the depth of a scalar expr?

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26417]
@jordanlewis @nvanbenschoten can you check whether my reading is correct:

```go
// VisitPost implements the Visitor interface.
func (v *NormalizeVisitor) VisitPost(expr Expr) Expr {
   [...]
  // Evaluate all constant expressions.
  if v.isConst(expr) {
      [...]
       value, err := expr.(TypedExpr).Eval(v.ctx)
  }
  [...]
}
```

This will call `isConst()` on every node of a scalar expression on the return path, right?
And isConst() itself is also performing a full recursion of that node?

So for every node at depth N we have N*(N-1) traversals?

**Comment by nvanbenschoten** [comment]
@knz I think you're missing two key details that make the expected complexity O(N) instead of O(N^2):
- `isConst()` will short circuit without a full traversal of a tree if any part of it is not const.
- if `isConst()` returns true then the next part of `NormalizeVisitor. VisitPost` evaluates it, which collapses the subtree. 

Together, these two factors combine such that as we're walking up the tree, we expect every call to `isConst` to take constant time.

**Comment by knz** [comment]
woah, mind blown. Thanks for explaining!

**Comment by justinj** [comment]
Hm, there are still cases where we can get some quadratic behaviour though, right? Specifically cases where there's only something non-constant at a leaf node? For instance wouldn't something like
```
(1 + (1 + (1 + (1 + ... (1 + a)))))
```
have the quadratic behaviour Raphael is describing?

**Comment by nvanbenschoten** [comment]
Yeah, you're probably right. We do try to normalize away from trees like those https://github.com/cockroachdb/cockroach/blob/5ab56f2cc605a0dcd87ca45b45388be115e37be4/pkg/sql/sem/tree/normalize.go#L233-L249

so that we can normalize constant expressions more aggresively, but we are probably missing cases.
