### ISSUE TITLE
ui: embed DistSQL plan visualizer in the admin UI

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#26523]
@asubiotto's work (https://github.com/cockroachdb/cockroach/issues/19476#issuecomment-379843588) adds an `EXPLAIN ANALYZE …` command which returns a DistSQL plan annotated with runtime stats. Currently this can be viewed on the plan decoder / visualizer site, but we'd like to integrate it into the web UI. It should be integrated somehow with the upcoming queries screen (tracking issue: #26519).

One proposal (sampled `EXPLAIN ANALYZE`-ing):
- Every 1000 or so queries for a given fingerprint, turn on tracing and store the resultant annotated plan so it can be shown later in the UI.

Another proposal (user-triggered `EXPLAIN ANALYZE`-ing):
- Store a representative query (constants still there, not scrubbed) on a sample interval (we'll already be storing representative physical and DistSQL plans)
- On the query detail page for a given fingerprint (which will show the SQL, physical, and DistSQL plans), add an "explain analyze" button which actually runs the query, and replaces the bare DistSQL plan with the annotated plan

Jira issue: CRDB-5002

**Comment by jordanlewis** [comment]
> Every 1000 or so queries for a given fingerprint, turn on tracing and store the resultant annotated plan so it can be shown later in the UI.

I think this is the right idea, if the interval is made configurable via a setting, but we can't enable this until we can make sure that tracing doesn't tank the performance of queries, which it currently does. We've had some ideas about how to improve things on that front, but no concrete movement yet.

**Comment by piyush-singh** [comment]
This request has resurfaced now that we have @RaduBerinde's on demand explain feature embedded into the UI (essentially the second option Pete outlined above). We demoed this for the SE team today, and they pointed out that for some of our customers' clusters will be air-gapped which prevents them from calling out to github in order to render DistSQL plans.

We can either embed the tool itself into the UI, or as Bram suggested, generate a PNG file for the DistSQL plan and add that to the bundle file instead. Renaming the issue to capture current state.

cc @dhartunian and @awoods187 

PS - it is so nice to finally see this after dreaming about it for 2 years.
