### ISSUE TITLE
sql: something is leaking traces (maybe InternalExecutor?)

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#26531]
Start up a cockroach node and run `set cluster setting trace.debug.enable=true;` then navigate to http://localhost:8080/debug/requests. In an unloaded system the "active" traces should be 0 (or maybe 1 for "server shutdown"). There currently appears to be a bunch of them created during the migrations that are hanging around afterward. If you then open up a browser tab to http://localhost:8080/#/jobs and let it sit, this number of active traces seems to grow without bound.

They all vaguely look like the following: 
```
2018/06/07 13:53:01.649919 | 4.121454 | sql txn
-- | -- | --
13:53:01.649961 | .    43 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] [Open pos:0] executing ExecStmt: SELECT id, status, created, payload, progress FROM system.jobs
13:53:01.649970 | .     9 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] executing: SELECT id, status, created, payload, progress FROM system.jobs in state: Open
13:53:01.650013 | .    43 | ... txnID:cbfc8588-379a-47b4-8058-1ea5b7b1dbb4
13:53:01.650867 | .   855 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] creating DistSQL plan
13:53:01.650887 | .    20 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] querying next range at /Table/15/1
13:53:01.650910 | .    23 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] running DistSQL plan
13:53:01.651218 | .   308 | ... [n1,intExec=admin-jobs,intExec=crdb-internal-jobs-table] [Open pos:1] executing Sync
```

**Comment by andreimatei** [comment]
The reason why I'm seeing some of these open traces even when `trace.debug.enable` is not set is because @tschottdorf added some magic for a server to start with tracing on and have it set to false later.
The reason why these traces are not finished is indeed as I suspected - when an `InternalExecutor` is used inside a higher-level txn, we init its transactional state in a custom way. What got lost in the process is delegating the responsibility of finishing up the root span it creates. Will send some sort of a fix.

Thanks for the report, Dan.
