### ISSUE TITLE
sql/stats: memory accounting for sampled rows

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#26547]
Currently the Sampler and SampleAggregator processors use `SampleReservoir` which stores rows directly. We need to hook this up to memory accounting.

**Comment by RaduBerinde** [comment]
@rytaft I believe this is fixed?

**Comment by rytaft** [comment]
We're not actually doing memory accounting... the memory bug I fixed earlier wouldn't have been prevented by memory accounting since it was due to residual references to large kv batches that prevented garbage collection. 

I don't think it's urgent to add memory accounting, but it might still be useful for ensuring that the 10,000 sampled rows for tables with many really wide columns don't take up too much memory. I don't think we need to do this for the current release since I've turned off histogram creation for automatic stats.

**Comment by RaduBerinde** [comment]
Wanted to write something down about why this is not an issue for 19.1: auto stats don't calculate histograms, and so we don't sample any rows. The memory accounting is only relevant for the sampled rows (the cardinality sketches are fixed in size).

**Comment by rytaft** [comment]
This was completed by #39144 and #39738
