### ISSUE TITLE
sql: tuple types do not match Postgres

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#26733]
Postgres allows the following:
```
SELECT (3, 50) IN ((1, 2), (select (3, 50)), (5, 100));
```
but we fail:
```
> SELECT (3, 50) IN ((1, 2), (select (3, 50)), (5, 100));
pq: unsupported comparison operator: (3, 50) IN ((1, 2), (SELECT (3, 50)), (5, 100)): expected (SELECT (3, 50)) to be of type tuple, found type tuple{int, int}
```
unclear if anything depends on this, though it would be useful for constructing various testing queries.

I seem to remember there was a reason for this divide, but I don't remember what it was.

Jira issue: CRDB-4987

**Comment by jordanlewis** [comment]
Smaller test case:

```
root@127.0.0.1:50594/defaultdb> SELECT (3, 50) IN ((select (3, 50)), (5, 100));
pq: unsupported comparison operator: (3, 50) IN ((SELECT (3, 50)), (5, 100)): expected (SELECT (3, 50)) to be of type tuple, found type tuple{int, int}
```

**Comment by jordanlewis** [comment]
The problem is that the type checker naively assumes that cases like this require all expressions on the right to be concrete `Tuple` expressions. However, as this case demonstrates, subqueries are valid in this context as well.

The error here is thrown from `checkAllExprsAreTuples` in `type_check.go`.

**Comment by jordanlewis** [comment]
Interestingly, putting a subquery tuple on the left of the comparison works just fine, suggesting that we might be able to remove a tuple special case and have things still work.

**Comment by jordanlewis** [comment]
Removing the special case for tuples doesn't work, because there's a legitimate reason for having a special case for tuples. `TypeCheckSameTypedExprs` on a bunch of tuples won't be able to figure out the first tuple type that has no nulls in it properly - like in the case of `(1, null), (null, 1)` it needs to figure out that the type should be `(int, int)` - that's why the tuple special case exists.

The trouble currently is that the tuple special case works by running `TypeCheckSameTypedExprs` pointwise on all of the tuple elements. In the case of subqueries, you can't do that, since subqueries aren't evaluable at typechecking time. So there would need to be special case logic in `typeCheckSameTypedTupleExprs` to deal with subqueries.

**Comment by knz** [comment]
still current

**Comment by jordanlewis** [comment]
No longer repros.
