### ISSUE TITLE
metrics: add ranges are "Under-diversified" metric (different from under-replicated)

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#26757]
**FEATURE REQUEST**

Per https://forum.cockroachlabs.com/t/playing-with-dc-ha-outages/1743, it's possible to get into a state where ranges have the correct number of replicas across a cluster, but replicas are not sufficiently spread across localities.

This is dangerous, since you could think in the case of a rolling upgrade that you're safe to bring down a DC or locality, and accidentally make data unavailable. It would be helpful to have a metric that would indicate whether replicas are sufficiently distributed across localities to tolerate another fault.

**Comment by tim-o** [comment]
Zendesk ticket #[2492](https://cockroachdb.zendesk.com/agent/tickets/2492) has been linked to this issue.

**Comment by tbg** [comment]
As a workaround for now, if this becomes a problem during manual failover tests, the recommended approach is to observe the replication queue to wait until it settles down (this isn't satisfactory, but should be good enough for manual testing)

**Comment by tbg** [comment]
Here are some pointers to look into (caveat emptor: I'm not an expert in this code).

The code that computes the constraints is here:

https://github.com/cockroachdb/cockroach/blob/55afcbb11b143254d5869503d5f1a1b84e0b2f84/pkg/storage/allocator_scorer.go#L902-L939

This doesn't cover "localities" though. For that, there's separate code: 

https://github.com/cockroachdb/cockroach/blob/55afcbb11b143254d5869503d5f1a1b84e0b2f84/pkg/storage/allocator_scorer.go#L1088-L1110

A range is "diversified" (for lack of a better term - we should find a better word for this) if the current replica config satisfies all constraints and meets some diversity target. It's unfortunately unclear how the diversity needs to be thresholded. For example, constraints could force a range into a non-diverse configuration, in which case we'd need to handle the diversity score appropriately.

All this suggests that this might be hairier than it seems. There's also the issue that to keep a metric, right now we need to compute this for each leader replica every 10s, so it will need to be cheap. This doesn't look cheap so far.

**Comment by darinpp** [comment]
I was thinking yesterday about this. Here is one suggestion. Have all nodes compute a metric for their ranges for which they are leaders (or leasholders?) that shows the smallest number of nodes lost that could cause the range to loose quorum. The same thing can be computed for any other location level attributes available across all nodes (country, region, rack etc). It can done even for attributes - like cloud provider for example. This data can be aggregated across all nodes and provide some table like this (assuming 4000 ranges):


 Loss Count\Type of   Loss | Node | Region | DataCenter
 -- | -- | -- | --
 1 | 0 | 0 | 0
 2 | 0 | 0 | 4000
 3+ | 4000 | 4000 | 4000

What this data shows is that you can survive loss of at least two nodes (two is guaranteed, loss of more nodes may also not result in quorum lost but that would depend on which nodes failed), or loss of two regions, or loss of one whole data center.

If a let's say two nodes fail the table may change like this:

 Loss Count\Type of   Loss | Node | Region | DataCenter
 -- | -- | -- | --
 1 | 30 | 4000 | 4000
 2 | 400 | 4000 | 4000
 3+ | 3570 | 4000 | 4000

and the show the progress from this state to the fully diversified state in the first table.

If the table like this is too complicated, then perhaps a simple metric that shows the minimum number of nodes that when taken down could make at least one range to lose quorum. This metric can be called resilience and could be a simple `Resilence - Node:2, Region:2, DataCenter:1`

**Comment by tbg** [comment]
I was thinking about this more in terms of constraints:

https://github.com/cockroachdb/cockroach/blob/b81f313f6866b47afccbceb773cdabf377f4705b/pkg/sql/opt/xform/testdata/coster/zone#L234

Locality diversity isn't strictly a constraint since we'll chose to violate it in order to fulfill actual constraints, but it's close enough to one. Whether a given cluster is "safe" depends on the constraints being satisfied, and I don't think that can be read off from the table in general. I realize that this issue is only about under-diversification, but I think that is just one facet of the general problem and that we need to solve more than just that.

For example, in re-partitioning we create (I think) a bunch of zone configs and then we want to wait until the cluster tells us that everything conforms to that zone config now, which it doesn't really know how to do today. (Or, we reboot nodes with locality tags and want to wait until everything is diversified. Or, we just added a new constraint and want to wait until that has been satisfied).

It seems "straightforward" to iterate through all of the leaseholders for all ranges and to check whether there are any for which the allocator would have to do something, but it seems expensive to do (just guessing), which precludes having this mechanism "always-on". This isn't a stated design goal, but I think it would be good from an alerting and metrics point of view.

As far as exposing whatever we do to the client goes, the baseline that we'll have to satisfy is that of a single indicator that can be polled. This indicator might be the metric itself, or it might be a "more interesting" endpoint (but we'll definitely want to keep a metric, too, if we can). On top of that we'll need introspection to indicate progress and, absent progress, explains where the problems are, at least to some extent (for example listing some ranges that aren't properly aligned with their constraints).

The table still looks useful. You could imagine having a sort of "outage simulator" where you get to specify a failure scenario (i.e. n1 and AZ3 go down) and get a table back that shows you what to expect.

PS https://github.com/cockroachdb/cockroach/issues/19644 is related, though I don't know if we're going to solve it here.

**Comment by andreimatei** [comment]
I think I'm intuitively thinking about this similarly to Tobi. What we want to express to users, primarily, is what constraints are satisfied and what constraints are not. So I'd take a constraint-centric approach to presenting this information.
Which is not to say that the sort of risk table that you, @darinpp, propose, would not be useful. That's a different view of sort of the same thing, but not quite. 

So what I think it'd like to see is a list of constraints with information about how satisfied each one is. Something like:
1. table foo constraint "2 replicas in dc=east, 1 replica in dc=west": 30/1000 ranges (1GB/30GB of data) are in violation  (not enough replicas in dc=east)
2. table bar under-diversified: 10/1000 ranges (300MB/30GB) have 2 replicas in dc=west and no replicas in dc=central; 20/1000 ranges have 2 replicas in dc=east and no replicas in dc=central
3. table baz partition "north_america" constraint "region=us": 20/1000 ranges are in violation
4. table qux replication factor 3 violation: 1/1000 ranges have only 2 replicas, 2/1000 ranges have 4 replicas (out of these 2, 1/2 ranges are also under-diversified having 2 replicas in dc=west) (*)
5. table quux lease holder preference violation: ...

*) The 2nd half of this represents #12768 - the lack of atomic rebalances and the risk that it puts you under

It seems to me that this is the first way to present the data. It's more raw than the risk table, and also slightly more actionable: I get some more info about what's wrong. On the other hand, if my goal is only to get a high-level view of the risk my system is either, this view admittedly seems worse.

In any case, the trickiest thing to me seems to be how to gather the data. Currently all the range metrics that we have (including an under-diversified metric) are collected by nodes every 10s by iterating over all the ranges. I guess we should hook into that, and maintain per-constraint counters of violations.

cc @bdarnell

**Comment by tbg** [comment]
Here's an issue that reflects the general problem better than this one:

https://github.com/cockroachdb/cockroach/issues/31597 (links to https://github.com/cockroachdb/cockroach/issues/31551)

**Comment by andreimatei** [comment]
> Here's an issue that reflects the general problem better than this one:

Yeah, but this one already has more discussion, so I think we should stay here.

One thing that @darinpp mentioned and that's also been on my mind is whether we can maintain whatever data/metrics we end up maintaining here purely in an event-driven way, without a particular need for periodic recomputation. Like, increment and decrement metrics when a replica is added/removed, and separately react to zone configs changing or node liveness changing or node locality changing.
I'm not sure what the answer is, but I am inclined to think that we've been pretty lazy in putting everything behind a periodic scanner.
