### ISSUE TITLE
server: version upgrade predicate is wrong

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26852]
in `server_update.go` the following code:

```go
func (s *Server) upgradeStatus(ctx context.Context) (bool, error) {
  // ...
  statusMap := s.nodeLiveness.GetLivenessStatusMap(false /*includeRemovedNodes*/)
  var newVersion string
  for _, row := range datums {
    id := roachpb.NodeID(int32(tree.MustBeDInt(row[0])))
    version := string(tree.MustBeDString(row[1]))

    // problem -- this incorrectly skips temporarily dead nodes
    if statusMap[id] == storage.NodeLivenessStatus_LIVE {
      if newVersion == "" {
        newVersion = version
      } else if version != newVersion {
        return false, errors.New("not all nodes are running the latest version yet")
      }
    }
  }
```

cc @tschottdorf

**Comment by knz** [comment]
The code should also not use `crdb_internal.gossip_nodes` and instead issue a request to KV to retrieve the node list.

**Comment by benesch** [comment]
The end of that function verifies that there are no dead nodes:

```go
	// Check if all non-decommissioned nodes are alive.
	for id, status := range statusMap {
		if status != storage.NodeLivenessStatus_DECOMMISSIONED && status != storage.NodeLivenessStatus_LIVE {
			return false, errors.Errorf("node %d is not decommissioned but not alive, node status: %s.",
				id, storage.NodeLivenessStatus_name[int32(status)])
		}
	}
```

**Comment by knz** [comment]
The end of that function is not reached if the code before that gets the (wrong) impression that the cluster version upgrade is already complete.

**Comment by windchan7** [comment]
@knz If the final check is not reached because it thought the cluster version upgrade is already complete, this means that all `live nodes` are having the same version as current cluster version, say `X`. This also means that all the nodes in the cluster, regardless of living or dead, also has it version to be at least `X`. In this case, the finalization SQL statement won't be executed because the auto upgrade will simply quit.

In the case where a dead but non-decommissioned node is running a lower version, say `Y`, but all the other living nodes are running at version `Z`, say `Y` < `Z`, then the current cluster version cannot exceed `Z`. So the upgrade logic will continue and the final check for dead and non-decommissioned nodes in `upgradeStatus` will find that there are dead and non-decommissioned nodes. So the auto upgrade will not happen. I don't think it will skip temporarily dead nodes.

In addition, the dead and non decommissioned node case is also tested by the `upgrade` roachtest. Hope this helps!

**Comment by knz** [comment]
Also besides that correctness problem due to `statusMap` I must say I am not convinced by your argument at all: I am not seeing any code anywhere which prevents the cluster setting to be updated if a node goes temporarily down after `upgradeStatus()` completes but before `startAttemptUpgrade()` proceeds to write to the cluster setting.

**Comment by windchan7** [comment]
Got it. Thanks for the clarification!
