### ISSUE TITLE
kv: improve tracing from canceled DistSQL reads

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#26882]
When a query gets stuck because it's sending to an unavailable range, one method today for trying to determine which range it's trying to talk to is to trace and cancel the hanging SQL statement. But the resulting trace doesn't seem too useful because it doesn't contain the rangeID it's stuck on (the logs end at DistSender).

We should log the replica we're trying to send to before we do.

**Comment by tschottdorf** [comment]
In the issue that prompted this, the final problem was actually not that the range was down, but that it had to scan through many empty ranges first. Somehow, even though the query was canceled somewhere after having already read multiple ranges, this did not show in the trace.

@andreimatei what's expected here from the current code? I think this was a table reader going through all of the empty ranges, and it didn't seem to trace anything. It would be good if it returned some trace points even if it got canceled, which I suspect is not happening.

**Comment by andreimatei** [comment]
Well canceling a query is a brutal operation - it cancels some context on the gateway, which then closes all the inbound streams on the gateway. Then errors propagate to the other nodes.
So, yeah, it's expected that you don't get any trace.

There are two things that we could do - have a "gentle" query cancelation option that doesn't brutally close streams, only sends a draining signal (we already have such signals). Or have a tracing mode where the trace is continuously sent, instead of just at the end of a query. The first one is probably simpler, but they both require a bit of work I think.

**Comment by andreimatei** [comment]
Upon further thought, I think what we want here is not to use canceling at all, but a different SQL statement that generates a specific trace signal that causes the trace to be collected. And that ideally would work across DistSQL and DistSender, except it's much easier with DistSQL cause the inter-node communication is done through streaming connections on which these signals can be sent, whereas with regular RPCs we'd need to invent another mechanism.
