### ISSUE TITLE
tests: design for a network simulator debugging tool

### ISSUE THREAD

**Issue by andybons** [cockroachdb/cockroach#27]
Megastore has a pseudo-random test framework capable of exploring the space of all possible orderings and delays of communications between simulated nodes or threads, and deterministically reproduces the same behavior given the same seed.

This would be unbelievably useful.

/cc @toddlipcon since he’s had experience designing something like this for HDFS HA.

**Comment by xiang90** [comment]
@andybons @spencerkimball We just started to a pseudo-random test framework inside raft. 

The first step is to randomly probing the possible testing space with a seed, so that we can reproduce the found problem.
The second step is to actually recording the probed testing space and find a way to end the testing, when we are sure that we have searched all possible sequences for the internal state machine.

https://github.com/coreos/etcd/pull/2203

**Comment by andybons** [comment]
@xiang90 :+1:

**Comment by bdarnell** [comment]
Making a note of this for later: https://github.com/ahorn/linearizability-checker is another tool for analyzing Jepsen logs. It's similar to but more efficient than Aphyr's Knossos tool.

**Comment by knz** [comment]
Ok this is really a superset of what I was looking at with #4036. Let me study these options and then I'll see what I can propose.

**Comment by AkihiroSuda** [comment]
We have also a similar tool which increases the non-deternimism of thread scheduling (and so on).
This tool can be easily used with the existing unit tests and Jepsen tests.

http://osrg.github.io/earthquake/post/fosdem2016/

**Comment by knz** [comment]
I'm not sure this is happening in this way any more. Not planning to work on this soon.

**Comment by knz** [comment]
cc @knz for later

**Comment by bdarnell** [comment]
We've been using jepsen for a long time now and have no specific plans to build anything else in this area, so there's no point in keeping this issue open.
