### ISSUE TITLE
sql: CREATE INDEX fails to see a column that was recently added

### ISSUE THREAD

**Issue by brentahughes** [cockroachdb/cockroach#27033]
**BUG REPORT**

Version: 2.0.2

When adding a column to an existing active table and immediately adding an index to that new column it will sometimes error with `(details: pq: index "table_name" contains unknown column "column_name")`. This is mostly seen when running a migration on an production system. Rerunning the migration will often times work on the 2nd attempt.

**How To Reproduce**
This is not a 100% guarantee to reproduce the issue but will at times work.

1. Create the table
```
CREATE TABLE test ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    name STRING NOT NULL
);
```

2. Produce a load on the table
```
while true; do cockroach sql --insecure -d db_name -e "INSERT INTO test (name) VALUES ('some_$(date)')"; done
```

3. Add column with index
```
ALTER TABLE test ADD COLUMN description STRING NOT NULL DEFAULT 'something';
CREATE INDEX ON test (description);
```

**Expected Error** 
`(details: pq: index "test_description" contains unknown column "description")`

**Comment by knz** [comment]
cc @vivekmenezes maybe CREATE INDEX does not scan the list of column mutations properly

**Comment by vivekmenezes** [comment]
The correct way to resolve this issue is to keep track of tables that were created during a transaction, we can keep track of schema elements such as columns/indexes that were created during a transaction. That way when applying a schema change to a schema element when we know it is created during a transaction, we know if it is visible to the cluster. if it is still invisible to the cluster, the schema change can move forward safely knowing that there are no extant versions of the schema element out there.

**Comment by jordanlewis** [comment]
This has been fixed!
