### ISSUE TITLE
docs: capacity metrics, upscale/downscale considerations

### ISSUE THREAD

**Issue by rendaw** [cockroachdb/cockroach#27049]
Sorry for the vague title, and this may be a collection of related questions/notes.  This was discussed in [gitter first (log here](https://gist.github.com/rendaw/4b73e33b5802ef240946452d29c60216)).

I'd like to avoid repeating things since I'll likely leave out important details from the conversation, but the main points were:

1. On decommissioning a node, what and why to check for in "Check the node before decommissioning"
2. How do the `Examples` on the page relate to the metrics available on the dashboard?  The screenshots (ex: in point 1) show replicas per store of 70, which is much higher than the 3 replicas discussed in other places.
3. Specifically, how can an admin check to see if there's enough disk capacity to scale in without stalling (or a lack of disk space requiring a scale out) while maintaining the desired number of replicas?  Cluster disk usage vs capacity might work, but if there's significant rebalancing going on that value might not be safe.  Maybe something like average replicas?

I'm fairly certain the above summary is not adequate, so please read the discussion if you have time.  In fact the more I read it the more I think what I left out was important.  If someone would like to rewrite this summary by all means do so.

**Comment by tim-o** [comment]
Attn @couchand @vilterp since we were talking about this at lunch.

@rendaw, we'll create docs requests for the first two. 

Re #3, I think the user story for this would be something like "As an administrator, you want to be able to know whether you can tolerate a failure of a node or locality without running out of disk space, or otherwise negatively impacting performance." Is that right?

**Comment by vilterp** [comment]
Yes, I think that is a good user story for the product to support. cc @piyush-singh to get it into Airtable.

**Comment by rendaw** [comment]
For 3 that sounds right.  Specifically, it would be nice to know how close we are to the danger zone as well, not just whether we're in a safe spot or not.  Also, knowing about performance would be nice but my main interest is data volume (assuming that having both would take more effort than just the one).

**Comment by tim-o** [comment]
Yeah, @piyush-singh and I were discussing that as well - ideally we'd be able to monitor and alert based on thresholds.

**Comment by couchand** [comment]
I'll reiterate here something I said in meatspace earlier: I predict it will be difficult for us to define this metric so that it's both cheap to measure/calculate and also meaningfully accurate.

The response to the cluster to any particular event is going to be based on the complex interactions of everything going on.  For simple clusters with default settings and a straightforward architecture, it's easy enough to provide heuristics here.  However, for any nontrivial data architecture, I think it would very quickly become difficult for us to provide a single data point for this summary.

In our lunchtime conversation this very quickly turned to running simulations on particular failure scenarios.  This idea sounds interesting to me but also seems to open a few different cans of worms.

Definitely open to hearing ideas that address these concerns.
