### ISSUE TITLE
Support for "Grave Accent" - `

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#27130]
This query is valid in mysql (and postgres ?) but invalid in 

```sql
ALTER TABLE `users` ADD `id` BINARY(16) FIRST;
```

related to https://github.com/cockroachdb/cockroach/issues/25468, the query is from laravel ORM (eloquent)

**Comment by benesch** [comment]
Hi @kocoten1992! Thanks for filing. That query is actually only valid in MySQL, which, as far as I know, is the only database that uses the backtick character to quote identifiers instead of the standard double-quote character.

CockroachDB, by contrast, implements a more standard dialect of SQL that closely mirror's Postgres's dialect. Accordingly, you'll want to tell your Laravel application to use the Postgres driver. I believe you'll want to adjust your database config, in config/database.php, to look something like this:

```php
'mydatabaseconfig' => [
    'driver' => 'pgsql',
    // ...
];
```

If that doesn't work, please do follow up. We're available on Gitter if you prefer real-time chat. I'm going to close this issue for now, though, since there's nothing for us to do on our end.
