### ISSUE TITLE
ui: interleaved tables should be shown as child tables

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27218]
Not sure if there is an issue open for this yet, but I couldn't find one.

So here I have 4 child tables that are interleaved in the parent table sessions.
<img width="1355" alt="screen shot 2018-07-05 at 20 58 06" src="https://user-images.githubusercontent.com/1614265/42354682-77b7a48a-8096-11e8-8d46-d7a3ea4ccead.png">

I know it's a known issue that we don't have stats for the size of child tables and they all get rolled into the parent table, but why can't we at least show that relationship?

Indent the child table under the parent table and don't show any stats for now.

**Comment by couchand** [comment]
fwiw the size issue is here: #9433

**Comment by bdarnell** [comment]
On a related note: when viewing the table page for a child table, you can see in the CREATE TABLE statement that it is interleaved. But the table page for the parent has no indication that it has any children (except for the fact that the stats shown are confusing because they include the child data as well).  There should be some indication of the relationship on both tables' pages.

**Comment by jordanlewis** [comment]
Closing as won't fix
