### ISSUE TITLE
Storing data in memory

### ISSUE THREAD

**Issue by dax0** [cockroachdb/cockroach#2727]
Is there a better way to do this than tmpfs and is it even worth doing this or are there better solutions when I don't care about the data being durable?

I see this: https://github.com/cockroachdb/cockroach/blob/master/storage/engine/in_mem.go

**Comment by dax0** [comment]
Found it here:
https://github.com/cockroachdb/cockroach/blob/016136e8a913fb8155bd0aa2c1d1aac5d3161981/cli/flags.go#L130

**Comment by dax0** [comment]
Unfortunately could not get it to work, any guidance would be appreciated

**Comment by tschottdorf** [comment]
I'm assuming your node just sat there with a message like

> connected to gossip but missing sentinel. Has the cluster been initialized? Use "cockroach init" to initialize.

We do support in-memory engines (as you noticed) but have been using them mostly for our unit tests. The problem in practice is that while you can **start** such a node, you can't **bootstrap** one (that would mean running `cockroach init` for that engine, but the engine gets destroyed when that process ends, so the subsequent `start` wouldn't behave any differently).

One way to get around it is bootstrapping with an on-disk store which can be removed once you have an otherwise in-mem cluster running, but honest support for this likely entails changes to how the initialization process is exposed through the command line tool.

So, short answer - what you're asking for is going to work at some point, but not yet. You can have a single-node in-mem instance for playing around with though; see the `--dev` flag.

**Comment by dax0** [comment]
Thanks for that response, that's exactly the same conclusion that I arrived that.

**Comment by knz** [comment]
This is now possible thanks to #4027.
You can start a new node ready for replication with a memory-only data store using this command:
```
   cockroach start --stores=mem=12312312 
```

(or possibly with `--join` if joining an existing cluster) and this will not store the data persistently.
