### ISSUE TITLE
perf: Cockroachdb can a 100 billion data query be supported?

### ISSUE THREAD

**Issue by 444728248** [cockroachdb/cockroach#27354]
Cockroachdb can a 100 billion data query be supported?

**Comment by ZOXEXIVO** [comment]
no, you catch timeout on 10 million

**Comment by knz** [comment]
The correct answer is "it depends". 

If you run the query `select generate_series(1,100000000000);`  with e.g. `cockroach sql --format=tsv -e 'select generate_series(1,100000000000)'` chances are you'll get your 100 billion rows of output.

A write query will stop at somewhere between 10.000 and 100.000 rows updated because there is a maximum size on mutation transactions. Also there is a timeout of 10 minutes.

Other read queries to tables may fail due to various timeouts but these can be tuned.

Again it all depends on the use case.

**Comment by tschottdorf** [comment]
Closing as not actionable.

**Comment by 444728248** [comment]
ok tks！
