### ISSUE TITLE
server: `start --background` returning too early

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#27957]
```
Build Tag:    v2.0.4-853-gc74ac3dfd
Build Time:   2018/07/26 15:18:38
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.6.0)
Go Version:   go1.10
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
Build SHA-1:  c74ac3dfdebf7c004b3a03f29b91b2716d375802
Build Type:   development
```

**BUG REPORT**

`cockroach start --insecure --background && cockroach quit --insecure`

- What did you expect to see?

`start --background` block until startup finishes, then `quit` successfully exits.

- What did you see instead?
```
[15:20:17] ~/Desktop $ cockroach start --insecure --background && cockroach quit --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
W180726 15:20:20.300389 39 cli/start.go:1035  unexpected error from no-op Drain request: rpc error: code = Unavailable desc = node waiting for init; /cockroach.server.serverpb.Admin/Drain not available
ok

[15:20:20] ~/Desktop $ CockroachDB node starting at 2018-07-26 15:20:20.393859102 +0000 UTC (took 0.7s)
build:               CCL v2.0.4-853-gc74ac3dfd @ 2018/07/26 15:18:38 (go1.10)
admin:               http://null-2.local:8080
sql:                 postgresql://root@null-2.local:26257?sslmode=disable
logs:                /Users/david/Desktop/cockroach-data/logs
temp dir:            /Users/david/Desktop/cockroach-data/cockroach-temp045902319
external I/O path:   /Users/david/Desktop/cockroach-data/extern
store[0]:            path=/Users/david/Desktop/cockroach-data
status:              restarted pre-existing node
clusterID:           349ee01b-72e4-42e9-a325-2cb6f461384b
nodeID:              1


[15:20:26] ~/Desktop $ ps aux | grep cockroach
david            89378   0.0  0.0  4267768    900 s002  S+    3:20PM   0:00.00 grep cockroach
david            89362   0.0  0.5 558621872  82656 s002  S     3:20PM   0:00.61 cockroach start --insecure
```

`start` apparently returned before the server was ready to handle the `quit` request, which then failed and left the process running.

**Comment by knz** [comment]
I think this is going to be difficult to achieve (@bdarnell correct me if I am wrong): the parent process currently exits as soon as systemd has accepted the background launch. To fix the issue filed above, one would need to invent a synchronization protocol between the bg and fg processes. 

Such a sync protocol is quite uncommon in unix server software. Also it would be a lot of work.

All in all I would suggest closing this issue, especially because...

@dt there is already a protocol to synchronize: 

1. `mkfifo pid_file`
2. `cockroach start --background --pid-file=pid_file`

When you can read from `pid_file`, the server is ready. That is guaranteed to work, and is also thoroughly tested (precisely in that way).



This is btw a standard protocol for unix servers.

**Comment by dt** [comment]
huh, my understanding was that the SD_NOTIFY protocol was meant to do exactly this: allow the background process to let the foreground process know when it was ready to serve traffic, which seems corroborated by the comment in sdnotify.go: `Servers can use sdnotify.Ready() to signal that they are ready to receive traffic`. Are we just saying we're ready before we actually are?

**Comment by bdarnell** [comment]
> the parent process currently exits as soon as systemd has accepted the background launch

There's no systemd here, we're just using the systemd notification protocol between the parent and child process. This is exactly what it's for, to ensure that the server is ready for client commands by the time the parent process returns. 

In this case, the notification appears to be correctly waiting for the socket to be opened, but it's not waiting for the store to be bootstrapped. (Maybe because draining/quitting uses GRPC instead of pgwire?)  This might be related to #27956.

**Comment by knz** [comment]
fix incoming
