### ISSUE TITLE
kv: inconsistent Sender.Send definition

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#27976]
The `Sender.Send()` interface says:
```
If the returned *roachpb.Error is not nil, no response should be returned.
```

`DistSender.Send()`, on the other hand, says:
```
// Note that on error, this method will return any batch responses for
// successfully processed batch requests. This allows the caller to
// deal with potential retry situations where a batch is split so that
// EndTransaction is processed alone, after earlier requests in the
// batch succeeded. Where possible, the caller may be able to update
// spans encountered in the transaction and retry just the
// EndTransaction request to avoid client-side serializable txn retries.
```
This is a relatively recent change by @spencerkimball, I believe, from when we introduced the span refresh mechanism

And indeed I saw both a response and an error from the `DistSender`:
```
err: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=32aae940 key=/Table/54/1/4/3/0 rw=true pri=0.03392128 iso=SERIALIZABLE stat=PENDING epo=0 ts=1532632946.588500624,1 orig=1532632946.580634087,0 max=1532632946.580634087,0 wto=false rop=false seq=75.
resp: (err: <nil>), *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, ... 3 skipped ..., *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse, *roachpb.QueryIntentResponse
```

Should the `Sender.Send()` comment be updated?

I'd also like to understand the relationship between[ `BatchResponse.Header.Error`](https://github.com/cockroachdb/cockroach/blob/617c2262b511f9ade6bce077bca754d9cc0cef10/pkg/roachpb/api.proto#L1492) (documented to be the first error in any of the individual responses) and the error returned besides the `BatchResponse`, if anybody knows. This eludes me at the moment.

cc @bdarnell @tschottdorf @nvanbenschoten

**Comment by tschottdorf** [comment]
When the refresh mechanism was introduced, it hacked around the interfaces a bit, which is what you're seeing. I think I left a TODO about this somewhere in the code as well.
The client.Sender interface really hasn't served us well and we'd set it up differently today. However, since we're stuck with it for now, I think it's reasonable to update the comment.

As for the `(*BatchRequest, *Error)` response, this is the difference between, say, a `ConditionFailedError` and an RPC error. The former says: this is the error that was the result of executing the batch, the latter says "I couldn't even get that batch where it needed to go". In the absence of bugs in CockroachDB, these are retryable (because they could only be rpc errors, context cancellations, etc). In reality, they've been different kinds of errors such as "truncation resulted in empty batch" (DistSender bug), etc.

**Comment by bdarnell** [comment]
> I'd also like to understand the relationship between BatchResponse.Header.Error (documented to be the first error in any of the individual responses) and the error returned besides the BatchResponse, if anybody knows. This eludes me at the moment.

The original idea (I'm not sure if this is still true) was that BatchResponse.Header.Error would be nil on the server side until the very last minute (at which point we'd fill it in to send on the wire), and we'd use the separate pErr return (and we could use `returncheck` to ensure that this return value is used, which is not feasible for a deeply-embedded Error field). We have/had assertions at various points in the stack that BatchResponse.Header.Error is nil.
