### ISSUE TITLE
ui: Enable CORS / Expose API in order to consume CockroachDB metrics

### ISSUE THREAD

**Issue by cmnstmntmn** [cockroachdb/cockroach#28013]
**FEATURE REQUEST**

Enable CORS in order to reuse all sort of metrics that are now available and are powering the admin interface; you can see a list of them here `http://localhost:8080/#/debug`

Some use cases:

- add database metrics to current admin dashboards, in order to give a wider picture of the system;
- trigger alerts based on metrics.

in general would be nice to expose the API and make use of it anywhere you like it.

**Comment by couchand** [comment]
We've always exported the raw data in Prometheus format at `/_status/vars`, and thanks to #25227 we now also support pushing the data to a Graphite instance.  We can probably do a better job of documenting how to set these up (cc @jseldess).

Are these sufficient for your usage @cmnstmntmn?  We definitely want to support the use-case of running an external dashboard with CRDB metrics, but we're moving in the direction of further locking down the API itself, since we're adding more and more administration and maintenance functionality that can be quite sensitive.

**Comment by cmnstmntmn** [comment]
@couchand the problem is with CORS; if they're not enabled on the admin ui http server, then they can't be used elsewhere;

so far, i manage to consume them via a proxy as @benesch suggested me on gitter

**Comment by cmnstmntmn** [comment]
@couchand you are probably right;

well, the architecture looks like this:

**a web server** serving
- an API / json
- app/html (Mithril JS)

an i was looking to bring some metrics from crdb directly into the app/interface;
