### ISSUE TITLE
importccl: IMPORT executed successfully but didn't insert any rows into table

### ISSUE THREAD

**Issue by floatliang** [cockroachdb/cockroach#28036]
**BUG REPORT**

I use mysqldump export a table with 400k rows to .sql file,and use IMPORT MYSQLDUMP DATA to import the .sql file. The result in terminal shows job executed successfully but the number of rows in the table is zero.

Firstly I use a PROCEDURE to create a 400k rows table in mysql:

```
DELIMITER $$
USE `test`$$
DROP PROCEDURE IF EXISTS test.`pro_test_data`$$
CREATE PROCEDURE test.`pro_test_data`( pos_begin INT,pos_end INT)
BEGIN
         DECLARE i INT;
         SET i=pos_begin;
         WHILE  i>=pos_begin && i<= pos_end DO

                   INSERT INTO test.`UC_USER` (`ID`, `USER_NAME`, `USER_PWD`, `BIRTHDAY`, `NAME`, `USER_ICON`, `SEX`, `NICKNAME`, `STAT`, `USER_MALL`, `LAST_LOGIN_DATE`, `LAST_LOGIN_IP`, `SRC_OPEN_USER_ID`, `EMAIL`, `MOBILE`, `IS_DEL`, `IS_EMAIL_CONFIRMED`, `IS_PHONE_CONFIRMED`, `CREATER`, `CREATE_DATE`, `UPDATE_DATE`, `PWD_INTENSITY`, `MOBILE_TGC`, `MAC`, `SOURCE`, `ACTIVATE`, `ACTIVATE_TYPE`, `IS_LIFE`) VALUES(i,'admin','1ba613b3676a4a06d6204b407856f374',NOW(),'sb','group1/M00/03/BC/wKi0d1QkFaWAHhEwAAAoJ58qOcg271.jpg','1','admin2014','01','1',NOW(),'192.168.121.103',NULL,'','10099990001','0','1','0',NULL,NULL,NULL,'1','E5F10CAA4EBB44C4B23726CBBD3AC413','1-3','0','2','2','1');     
                  SET i=i + 1;
         END WHILE;
END$$
DELIMITER ;
```
`call test.pro_test_data(0,400000);`

And this is the schema of table:

```
CREATE TABLE `UC_USER` (
         `ID` BIGINT (20),
         `USER_NAME` VARCHAR (400),
         `USER_PWD` VARCHAR (800),
         `BIRTHDAY` DATETIME ,
         `NAME` VARCHAR (800),
         `USER_ICON` VARCHAR (2000),
         `SEX` CHAR (4),
         `NICKNAME` VARCHAR (800),
         `STAT` VARCHAR (40),
         `USER_MALL` BIGINT (20),
         `LAST_LOGIN_DATE` DATETIME ,
         `LAST_LOGIN_IP` VARCHAR (400),
         `SRC_OPEN_USER_ID` BIGINT (20),
         `EMAIL` VARCHAR (800),
         `MOBILE` VARCHAR (200),
         `IS_DEL` CHAR (4),
         `IS_EMAIL_CONFIRMED` VARCHAR (4),
         `IS_PHONE_CONFIRMED` VARCHAR (4),
         `CREATER` BIGINT (20),
         `CREATE_DATE` DATETIME ,
         `UPDATE_DATE` DATETIME ,
         `PWD_INTENSITY` VARCHAR (4),
         `MOBILE_TGC` VARCHAR (256),
         `MAC` VARCHAR (256),
         `SOURCE` VARCHAR (4),
         `ACTIVATE` VARCHAR (4),
         `ACTIVATE_TYPE` VARCHAR (4),
         `IS_LIFE` VARCHAR (4)
) ENGINE=INNODB;
```
Then i use mysqldump to generate .sql file:

`mysqldump -uroot -p test UC_USER > /home/test/crdb/backup/user.sql`

Then i use IMPORT to import .sql file ,and use caddy as file server:

```
IMPORT TABLE UC_USER (
ID INTEGER,
USER_NAME STRING,
USER_PWD STRING,
BIRTHDAY TIMESTAMP ,
NAME STRING,
USER_ICON STRING,
SEX STRING,
NICKNAME STRING,
STAT STRING,
USER_MALL INTEGER,
LAST_LOGIN_DATE TIMESTAMP ,
LAST_LOGIN_IP STRING,
SRC_OPEN_USER_ID INTEGER,
EMAIL STRING,
MOBILE STRING,
IS_DEL STRING,
IS_EMAIL_CONFIRMED STRING,
IS_PHONE_CONFIRMED STRING,
CREATER INT,
CREATE_DATE TIMESTAMP,
UPDATE_DATE TIMESTAMP,
PWD_INTENSITY STRING,
MOBILE_TGC STRING,
MAC STRING,
SOURCE STRING,
ACTIVATE STRING,
ACTIVATE_TYPE STRING,
IS_LIFE STRING 
)  
MYSQLDUMP DATA ('http://localhost:2015/user.sql');
```

Then i got:

+--------------------+-----------+--------------------+------+---------------+----------------+-------+
|       job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes |
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
| 369926299881209857 | succeeded |                  1 |    0 |             0 |              0 |     0 |
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
(1 row)

Time: 15.198180204s

But when i select the rows of this table:

root@:26257/defaultdb> select count(*) from uc_user;
+-------+
| count |
+-------+
|     0 |
+-------+
(1 row)

Time: 81.586194ms

I test it in Ubuntu 16.04 ,crdb version is v2.1.0-alpha.20180702,mysql version is 5.7.22.

**Comment by knz** [comment]
cc @dt for triage

**Comment by dt** [comment]
Looks like it has to do with the case of the table name -- the unquoted name in the in the query gets normalized to lower-case `uc_user` -- which is then the name of the table imported. Then the file reader looking for rows sees the INSERTs for `UC_USER` and thinks they don't match so it ignores them, this ending up with 0 rows.

If you wrap the upper-case table name in the `IMPORT` statement with quotes (e.g. `TABLE "UC_USER" (...`), it should prevent it being lower-cased in normalization, so the created table will be named `UC_USER`, and then the rows matched correctly and imported.

Also in the latest alphas, you don't need explicitly inline the syntax, and can let IMPORT figure it out from the mysqldump, e.g. `import mysqldump ('path://to/uc_user.sql');`. In that case it keeps the upper-case name (since it is in ticks in the dump) and the rows match it too.

**Comment by dt** [comment]
@knz You've thought a lot about table name normalization and case handling, curious if you have any input on what the "right" behavior is here. For context, the `IMPORT` statement supports a taking essentially a `CREATE TABLE`  statement to define the schema of the table it should import, and then reads rows for that table from another file -- which can be in CSV or SQL format.

In this case the `IMPORT` statement contained an unquoted, upper-case table name. The SQL data file referred to the table name in quotes (AFAIK, mysqldump always quotes table names, so we don't do any normalization in the dump reader).

**Comment by knz** [comment]
Here the problem and the solution are rather simple:

- mysql has case-insensitive identifiers. The quoting in MySQL exists only to disambiguate identifiers from keywords, not to determine casing
- meanwhile, the quoting is not mandatory. For example SQL queries in apps made for the mysql server may contain both `SELECT * FROM uc_user`, `SELECT * FROM \`UC_USER\`' or `SELECT * FROM UC_USER` and these are all equivalent for the mysql server
- in order to smooth out the migration of the client apps, it is important that the result of the import in crdb makes both `UC_USER` and `uc_user` valid, i.e. that it normalizes to the pg lowercase syntax.
- therefore, the right thing to do is, during the import, 
     1) normalize the mysql identifers using `lex.NormalizeName`
     2) double-quote the result of that normalization to create the crdb/pg-compatible SQL needed for the CREATE TABLE / IMPORT (to cover the rare but possible case where the identifier is actually a keyword)

**Comment by knz** [comment]
(the result will be identifiers that an app can be used unquoted -- except for the rare case where the identifiers are keywords, but that's exactly how it should be)

**Comment by dt** [comment]
Thanks @knz! I’ll implement that today.
