### ISSUE TITLE
Change Date representation to an int64 Time in seconds representation

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2803]
Currently Date is represented as a time.Time. While this is okay, we've run into a number of problems converting Date into Time, or vice versa, mostly as a result of the fallout of having a time zone offset in time.Time. It will be safer and better to just represent date as an int64 UTC Unix time in seconds.

**Comment by tamird** [comment]
I don't think we want a single integer. We should use a triplet of integers
for day, month, and year.

**Comment by petermattis** [comment]
Is the thought that we'd use the triplet for storage/transport and convert to a `time.Time` to perform calculations? We certainly don't want to implement date calculations ourselves (e.g. dealing with leap years, etc).

**Comment by vivekmenezes** [comment]
If we use the int64 some operations like comparisons can be done without converting to a time.TIme. @tamird is there a strong reason for you to want a triplet (int64, byte, byte)?

**Comment by bdarnell** [comment]
The reason we're having trouble representing dates as `time.Time` is that they encode hour values that can only be interpreted in the context of a time zone. If we're going to change the encoding, it should be to something that doesn't even contain any sub-day values. I'd probably go with days since epoch (i.e. unix timestamp / 86400) instead of a triplet, but it doesn't really matter as long as the methods to convert between dates and timestamps are on the EvalContext and use the session timezone.
