### ISSUE TITLE
ui: network and disk response time 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28051]
**FEATURE REQUEST**

A good network and disk latencies are are required for good performance and stability.  For example, a 1 ms network round trip, 2ms disk response times can at the most deliver 3ms response.  The resulting system can deliver theoretical 1,000 / 3 = 333 TPS assuming no other contention and delays.  

As the TPS increases, these response times do fluctuate leading to variance in txn response time.  Capturing network and disk response times over time aid in understanding the behavior of the system.

**Comment by vilterp** [comment]
Note: maybe we can derive disk latency as `disk time / disk op count`?

Network response time seems like a separate issue. Need to define that more specifically. I think we measure latency to other cockroach nodes by pinging them; otherwise would need to decide what else to ping to get a measure of latency.
