### ISSUE TITLE
sql: bulk i/o access keys show up in SHOW QUERIES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#28187]
This is true for `EXPORT` statements. It's worth testing if keys show up in `SHOW JOBS` for `IMPORT`, `BACKUP`, and `RESTORE` as well.

```
~/export-movr$ cockroach sql --insecure --database=movr -e "show queries;"
+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+-------------+-----------+
|             query_id             | node_id | username |              start               |                                                                              query                                                                               | client_address  | application_name | distributed |   phase   |
+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+-------------+-----------+
| 1546ddd001912de10000000000000001 |       1 | root     | 2018-08-01 20:50:08.615397+00:00 | EXPORT INTO CSV                                                                                                                                                  | 127.0.0.1:50617 | cockroach sql    |    false    | executing |
|                                  |         |          |                                  | 's3://cockroachdb-movr/datasets/perf-tuning/us-east/rides?AWS_ACCESS_KEY_ID=xxx&AWS_SECRET_ACCESS_KEY=xxx' |                 |                  |             |           |
|                                  |         |          |                                  | FROM TABLE movr.public.rides                                                                                                                                     |                 |                  |             |           |
| 1546de2fe796a8bb0000000000000001 |       1 | root     | 2018-08-01 20:57:00.496288+00:00 | SHOW CLUSTER QUERIES                                                                                                                                             | 127.0.0.1:50759 | cockroach sql    |    NULL     | preparing |
+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+-------------+-----------+
(2 rows)
```

**Comment by knz** [comment]
- I have verified that the string is scrubbed away from uploaded stats (pfew!)
- however we keep the string in the statement key in stmt stats. so that statements with different parameter get bucketed separately for stats

@mjibson @dt can you advise here? We really have three choices:

1. handle this the same as CREATE USER WITH PASSWORD, where the password is scrubbed upfront. However if we do this then SHOW QUERIES / the administrator won't be able to distinguish the ongoing EXPORT queries.
2. do not handle this like CREATE USER WITH PASSWORD, but then as Jesse found out we *may* be leaking credentials
3. change the syntax of EXPORT to split the target URL from the authentication information. In that case we could keep the URL but hide the authentication information.

A mitigating factor which may make choice (2) (i.e. the status quo) acceptable is that SHOW QUERIES only shows all queries for the `root` user: non-`root` users can only see their own queries. But then again even then CREATE USER WITH PASSWORD always scrubs the password, with the general idea "secrets should only go one way into the server, never come out".

What do you think?

**Comment by dt** [comment]
I’d originally have said that root should be able to see the precise query/job being run, including the parameters used to connect to external services (eg being able to inspect the params could help in debugging why a job was failing to write or something), but that is not the position we took with jobs:  We have a sanitizer for the job descriptions that nukes the query parameters from the URIs and we’ve been careful to only put “secrets” in those parameters (or in cluster settings). Given the precedent there, I think we should do the same to the `show queries`.

**Comment by knz** [comment]
Where is that logic implemented?

**Comment by dt** [comment]
`storageccl.SanitizeExportStorageURI` does the actual de-parameterizing of a URI.

It's called in the various ccl hooks when they compose their job descriptions, using job-specific helpers. We don't have a generalized AST scrubber or anything.

**Comment by BramGruneir** [comment]
Why is this assigned to @knz and in our current milestone?  This seems like a clear bulk i/o item to me.

**Comment by knz** [comment]
Ok so this is not so easy as it looks. The various statements that accept a URL do so via an arbitrary scalar expression (i.e. not a constant literal string). So we can have things like `export into sv 's3:' || '//' || '....'`

With arbitrary expressions we do not have any handle to "hide" anything sensitive.

While investigating this, I also realized that the same problem applies to any sensitive information present in an INSERT statement, consider an app that does `INSERT INTO passwords (user, pw) VALUES ('toto', 'secret123123')`. 

Do we care this shows up in SHOW QUERIES? Probably. Can we do something about it? Not technically, no.

The only sane alternative is to shorten/reduce the output of SHOW QUERIES to include just the statement tag, and strip everything else of the statement syntax (for display). But this would seriously undermine the ability of users to analyze/troubleshoot what is currently running.

This is a case where we need to think about security from a UX and documentation perspective. This is not a technology problem.

@bdarnell can you chime in and state an opinion about my analysis above?

As to the next course of action here: not sure.

**Comment by dt** [comment]
The job record itself has the raw URI details in its binary proto, so as long as root can read system tables, root can get the that to that parameter, whether it is in `show queries` or not.

For the specific case of BACKUP/RESTORE/IMPORT/etc, where we _know_ we're taking a parameter that includes cloud credentials, we could use a different AST node that we know how to hide when rendering in `show queries`, but as long as `SHOW QUERIES` is root-only, this hasn't really changed anything given the above.

**Comment by dt** [comment]
Hiding the parameters that contain "secrets" in the `jobs` and `queries` output potentially gives the appearance that they're irrecoverable even by root, when in fact that is not true, so arguably we shouldn't even try to hide them from root and just make it obvious that you need to use keys -- i.e. purpose-generated ones -- that you're comfortable with everyone who has root on your cluster knowing.

**Comment by bdarnell** [comment]
> While investigating this, I also realized that the same problem applies to any sensitive information present in an INSERT statement, consider an app that does INSERT INTO passwords (user, pw) VALUES ('toto', 'secret123123').

> Do we care this shows up in SHOW QUERIES? Probably. Can we do something about it? Not technically, no.

This doesn't seem like a problem to me. Anyone who could see this data in SHOW QUERIES could also just SELECT it back out of the database (barring a few very uncommon permission configs that only grant write access). It's important that queries only be visible to the executing user and superusers. I don't think it's important to hide users' queries from themselves, at least for things that are fully under the user's control (they could hash or encrypt the passwords, for example)

For backup/restore credentials, the user can't avoid passing the raw credential, so it would be nice to strip it out, but it's not worth losing the general SHOW QUERIES functionality and stripping it down to just the statement tag. I think in the long term it would be nice to move the credentials to separate syntax (`BACKUP TO ... WITH CREDENTIALS ...`) so it's easier to find and parse it out the secrets instead of stuffing sensitive and non-sensitive data into one string. But remember that admin users likely have other means of finding the credentials being used (via traces and other debug interfaces, etc), so I wouldn't consider it crucial to do this masking for SHOW QUERIES.

**Comment by knz** [comment]
> But remember that admin users likely have other means of finding the credentials being used (via traces and other debug interfaces, etc), so I wouldn't consider it crucial to do this masking for SHOW QUERIES.

yes this seems like the strongest argument to me. There are so many ways that the SQL entered by one client can show up on an admin's screen that it doesn't make sense to me to just focus on SHOw QUERIES.

We could theoretically extend the scope to "limit visibility of sensitive data" but that would be a much larger project that must also encompass log filtering, etc.

@jseldess are you ok with limiting the work to a doc update for BACKUP/EXPORT that will highlight that the URL details may show up in places?

**Comment by jseldess** [comment]
Yep, makes sense to me. I created https://github.com/cockroachdb/docs/issues/4108. Thanks for hashing through this. Feel free to close this.
