### ISSUE TITLE
Make SQL layer as standalone library

### ISSUE THREAD

**Issue by ivanjaros** [cockroachdb/cockroach#28271]
I have read one of your old blogs: https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/

and since you are using kv storage for the data, it would be great if you would make your sql layer into standalone library so people could use it with badger, for example.

Is there any plan for this?

**Comment by arjunravinarayan** [comment]
Hi @ivanjaros, there is currently no plan for this, and there will not be. The biggest reason is that we do a lot of internal refactoring of the interfaces between the various layers, and leaving SQL as the only publicly exposed layer gives us the flexibility to move fast. We do not intend to have multiple intermediate layers also be publicly exposed, giving us a larger maintenance surface area.

There are many subtleties that require fairly nuanced couplings between layers. For instance, since you mentioned badger, consider that we rely on our storage engine (RocksDB) to provide:

* Block-based tables
* Indexed batches
* Level-based compaction
* Custom Merge operator
* Prefix bloom filters
* Range deletion tombstones
* Reverse iteration
* Direct SSTable ingestion
* Table-level bloom filters

Many of which badger does not provide. Refactoring CockroachDB to be agnostic to some of these features existing, and having fallback paths is not a maintenance burden we wish to take on.

I hope this helps explain why this is not part of our roadmap.
