### ISSUE TITLE
storage: should reads enforce seq nums?

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28289]
I believe seq nums are currently ignored for reads, but should they be? If a replayed read encounters an intent from the same txn with a higher seq num, shouldn't that write be invisible to it?

cc @tschottdorf

**Comment by tschottdorf** [comment]
Technically yes, but we just haven't needed that behavior so far. It would become important if we needed to replay a pipeline, but then we'd be screwed anyway because we don't keep historic versions of intents of the same txn around, and that would be needed to satisfy these reads.

**Comment by nvanbenschoten** [comment]
Right, we don't currently rely on sequence numbers to provide idempotency from a clients perspective, just to prevent repeated side effects if a request is replayed. Since a read doesn't have any side effects (other than the tscache, but we can ignore that here), whether we enforce seq nums or not during reads shouldn't make a difference.

**Comment by andreimatei** [comment]
Yeah, I had a bit of a brain fart when writing this, not realizing that the client must not be waiting for the read any more if the read got reordered with an overlapping write.
Linking to a broader replay discussion in https://github.com/cockroachdb/cockroach/issues/26915
