### ISSUE TITLE
sql: Add support for triggers in CockroachDB

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#28296]
Feature request to add support for triggers in CockroachDB

Epic CRDB-347

Jira issue: CRDB-4914

**Comment by Ranguna** [comment]
+1 for this.
Triggers and functions are one of the few things blocking us from migrating aurora to cockroach. Can't wait to see this. 

One question, is there any reason this issue is under a project that appears to be "deprecated"?

**Comment by ajwerner** [comment]
> One question, is there any reason this issue is under a project that appears to be "deprecated"?

Only because of internal organizational change since this was filed.

Triggers very much depends on some form of https://github.com/cockroachdb/cockroach/issues/17511. I think we've increasingly got an idea of what goes in to a basic form of it. That's not a small project by any stretch. After that, integrating triggers into the query planning layer is also not a small project. I do think there's some enthusiasm around doing this but I wouldn't expect it to happen for at least another couple of releases (which would mean at least a year from now). Even that would be pretty ambitious.

**Comment by Ranguna** [comment]
Thank you for all the information, it's good to know this hasn't been forgotten!

Please take as much time as needed to do this correctly, I'll be patiently waiting.

Keep up the awesome work 👌

**Comment by AraHaan** [comment]
Any ETA on this? This is preventing me from migrating from sql server stored on my laptop to cockroachDB. Of which I would love to use cockroachDB in the future to try it out with my Discord Bot.

**Comment by Ranguna** [comment]
> I care more about triggers than stored procedures atm

@AraHaan you need part of the work that will be done/is done in stored procedures to unblock work on triggers.

So for now, we'll have to wait on both.

**Comment by pillzu** [comment]
Heyo
Any updates on this? It's been nearly 4-5 years since the issue came into light and I am unable to find anything on trigger support for cdb yet. Would really appreciate any updates on this since I've been using it in my current project and the complexity kinda requires triggers to achieve the intended outcome (I can do it on the server end but I'd rather use triggers if possible for less load on the server machine).

**Comment by ajwerner** [comment]
We've been hard at work on implementing UDFs, which are a pre-requisite for triggers. In the previous release we previewed support for basic UDFs. We have been continuing down that path. We don't yet support performing writes from UDFs. This issue has not been ignored, but is large.

**Comment by pillzu** [comment]
I see! Thanks a lot @ajwerner! Really appreciate the quick response. 
Will be waiting for the release. 

Good luck

**Comment by ajwerner** [comment]
Just to be more concrete, I don't expect triggers to be implemented for at least another year.

**Comment by saolof** [comment]
Did this also include event triggers for DDL statements?

**Comment by oponcea-dn** [comment]
Any news about this?

**Comment by DrewKimball** [comment]
I'm going to close this issue in favor of #121513. You can follow progress there - I've included a checklist that I'll try and keep up-to-date with progress.
