### ISSUE TITLE
roachpb.Value initialized inconsistently

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2839]
We currently use a mix of direct field access to [`(roachpb.Value).Bytes`](https://gist.github.com/tamird/dcdb09f4b92b55e4d2fa) and [getters and setters](https://gist.github.com/tamird/bcc0609775cb30e8d1cd), which results in some error spew (of the form "... value type is not ...") in [tests](https://circle-artifacts.com/gh/cockroachdb/cockroach/8446/artifacts/0/tmp/circle-artifacts.mFXPMZz/test.log).

We should standardize on the use of accessor methods or change `roachpb.Value` to contain a oneof (why isn't it a oneof already?).

**Comment by petermattis** [comment]
Making `roachpb.Value` a oneof complicates checksum computation for little additional gain. We should standardize on using the getters and setters. They are relatively new which is why they are not used consistently.

**Comment by thschroeter** [comment]
Happy to fix this.

**Comment by tamird** [comment]
Great! When you've done the work of changing all the callers, consider applying this patch to prevent regressions:
```diff
diff --git a/build/protobuf.mk b/build/protobuf.mk
index ea6ea0e..1d585d2 100644
--- a/build/protobuf.mk
+++ b/build/protobuf.mk
@@ -65,6 +65,8 @@ $(GO_SOURCES): $(PROTOC) $(GO_PROTOS) $(GOGOPROTO_PROTO) $(PROTOC_PLUGIN)
 	  sed -i.bak -E 's!$(REPO_NAME)/(etcd)!coreos/\1!g' $$dir/*.pb.go; \
 	  rm -f $$dir/*.bak; \
 	  gofmt -s -w $$dir/*.pb.go; \
+	  gorename -from \"github.com/cockroachdb/cockroach/roachpb\".Value.Bytes -to bytes; \
+	  gorename -from \"github.com/cockroachdb/cockroach/roachpb\".Value.Tag -to tag; \
 	done
 
 $(CPP_HEADERS) $(CPP_SOURCES): $(PROTOC) $(CPP_PROTOS) $(GOGOPROTO_PROTO)
```

**Comment by bdarnell** [comment]
Gorename can be quite slow when operating on exported identifiers because it has to scan your whole GOPATH for imports (and may spew a lot of errors if you have other projects in the same GOPATH that are in a messy state). I don't think we want to add this in the normal flow of generation. Can we give these an unexported custom name in gogoproto? (or just one that's unlikely to be used accidentally)

**Comment by tamird** [comment]
Good point. Custom names are the way to go.

**Comment by thschroeter** [comment]
Will push my changes later today for review.

I've done the mechanical changes replacing direct access to the `Bytes` field outside the `roachpb` package with access using getters and setters.

Will try to give the `Bytes` and `Tag` fields unexported names using gogoproto. Otherwise I probably just rename `Bytes` to `BytesUnchecked` this will at least allow to rename the [GetBytesChecked](https://github.com/cockroachdb/cockroach/blob/68590a9c004ddf5fd40dfb35df7d45470154192e/roachpb/data.go#L365) function to `GetBytes`.
