### ISSUE TITLE
security: customizable/required fields in certificate

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#28408]
With support for more varied certificate setups, we would like to add a few features (some or all):

* required fields in certificates. eg: a unique cluster identifier to allow the same CA between multiple clusters, but to restrict client certificates to a single cluster
* custom field to hold the client name (currently hard-coded to `CommonName`)
* custom value for the `node`/`root` users

**Comment by mberhault** [comment]
@rolandcrosby to keep track.

**Comment by petermattis** [comment]
The motivation for this feature is that some certificate management services will not generate a certificate with "node" or "root" as a `CommonName`. For example, AWS ACM refuses to do this. And we've heard similar from customers who use other certificate management services.

**Comment by petermattis** [comment]
Most CAs require `CommonName` to be a valid DNS name. From @knz: could we populate the `SubjectAlternateName` field? AWS ACM allows this, but will this run into problems elsewhere in the stack (e.g. does Go TLS use that field)?

**Comment by petermattis** [comment]
Strawman proposal: use subdomains of a domain owned by the user to store the `node` and `<sqluser>`. For example, if user owns `movr.com`, the node cert would specify `CommonName = "node.movr.com"` and client certs would specify `CommonName = "<sqluser>.movr.com"`. It is possible that we'd want to use `SubjectAlternateName` instead of `CommonName` here, but that shouldn't be a problem. The CRDB cluster using these certs would need to be configured via a flag to strip off the `.movr.com` suffix. Something like `--cert-name-suffix=.movr.com`. Or this could be inverted to use a regex to extract the portion we want: `--cert-name-pattern=([^.]+)\.movr\.com`.

**Comment by knz** [comment]
> `--cert-name-pattern=([^.]+)\.movr\.com.`

nah that won't do, `.` is allowed in usernames now. But ther'es nothing wrong with `(.*)\.movr\.com`

**Comment by knz** [comment]
maybe the suffix idea is better, less chance for the user to get the escaping wrong

**Comment by petermattis** [comment]
@knz, @aaron-crl how does this `--cert-name-pattern`/`--cert-name-suffix` idea look with the light of a few days shining on it?

**Comment by knz** [comment]
It looks good, and now I have a mild preference for `--cert-name-pattern` again -- it's going to be hard to get it wrong, because the server uses it immediately upon startup.

The tricky thing is certificate rotation though. Do we want to be able to change the pattern while a node is up and have it rotate?

**Comment by petermattis** [comment]
> It looks good, and now I have a mild preference for --cert-name-pattern again -- it's going to be hard to get it wrong, because the server uses it immediately upon startup.

Heh, flip-flopping? I do that sometimes.

Do you have time to code this up in 20.1? I realize that is an aggressive timeline, yet this would remove a significant pain point for users, and the implementation seems super straightforward (unless I'm missing some complexity). Worst case is that we're missing something about how it doesn't actually solve the problem. I probably also have time to take a crack at this. Let me see if I can get a prototype done this weekend.

> The tricky thing is certificate rotation though. Do we want to be able to change the pattern while a node is up and have it rotate?

I think changing the flag on a running server could be v2 functionality. Perhaps something similar to `crdb_internal.set_vmodule`. `crdb_internal.set_cert_name_pattern`? I imagine in most cases the cert-name-pattern will not need to change with cert rotation, and if it does need to change, we could ask for a restart.
