### ISSUE TITLE
storage: concurrent non-1PC CPuts see ReadWithinUncertaintyIntervalError

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#28461]
The lack of a `ConditionFailedError` is causing an `INSERT ... ON CONFLICT DO NOTHING` statement to fail spuriously. Should be easy to reproduce this scenario in a smaller test case, verify that it is still happening and fix it. 

Forked from https://github.com/cockroachdb/cockroach/issues/17108#issuecomment-318761706:

> > Yes, it would require the first (but slower) txn to read something the second one wrote.
I would have to check what a CPut would do, but it's possible that it would treat this as a ReadWithinUncertaintyIntervalError. Even though that would be somewhat silly: it could still look at the future value and if it doesn't match the assumption of the CPut, it may as well return a ConditionFailedError right there (I think).
>
> I think this may be what is happening. The errors are all occurring on INSERTS for which there appears to be an existing row. These are INSERT ... ON CONFLICT DO NOTHING. But the lack of ConditionFailedError is causing the insert to fail on conflict.

**Comment by andreimatei** [comment]
I'm confused about what this issue is asking for but, just in case, a reminder that a txn cannot continue to be used after it encountered any non-retryable error - so one can't simply swallow a `ConditionFailedError` (if that's what this was suggesting).

**Comment by petermattis** [comment]
Eh? Doesn't `ON CONFLICT DO NOTHING` swallow `ConditionFailedError`?

**Comment by andreimatei** [comment]
It'd better not... Will look when I can.

**Comment by andreimatei** [comment]
@petermattis to answer your concern - to the best of my tracing abilities, I don't see any indication of anybody swallowing a `ConditionFailedError`, and instead I see indications of PKs being checked with scans (for better or worse):
https://github.com/cockroachdb/cockroach/blob/bec26d2e6859ed808b2835f00cbfa99ce9c5c093/pkg/sql/tablewriter_upsert.go#L812

I maintain that continuing after an error in one of our txns is not a thing; I remain confused about what this issue is asking for and I'm even more confused about why it was assigned to me :P.
Passing back.

**Comment by petermattis** [comment]
The original issue was that we were seeing unexpected `ReadWithinUncertaintyError` issues on a local cluster (where the clocks are perfectly synchronized). There was a suspicion this had something to do with conditional puts, but you're claiming that can't be the case. The query in question is concurrent (conflicting) statements of the form `INSERT INTO nodes(hash) ... ON CONFLICT (hash) DO NOTHING`. 

A lot has changed since this issue was filed. I'll see about coming up with a new reproduction.
