### ISSUE TITLE
cli: cockroach quit should warn users that there are under replicated ranges when killing a node  

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#28506]
Not sure which area this would go under, so starting with CLI.

**FEATURE REQUEST**

Users occasionally run into issues and accidentally make data unavailable by being too aggressive in node decommissioning ex: http://forum.cockroachlabs.com/t/1830, others that can't be published publicly. 

It'd be valuable to broadcast a message along the lines of "Under-replicated ranges detected: further decommissioning may result in data unavailability or data loss!"

**Comment by tim-o** [comment]
Zendesk ticket #[2719](https://cockroachdb.zendesk.com/agent/tickets/2719) has been linked to this issue.

**Comment by knz** [comment]
@tschottdorf does this fall in core?

**Comment by tschottdorf** [comment]
I think I fixed this in https://github.com/cockroachdb/cockroach/pull/28707 by making it OK to decommission whichever nodes you like (it may not complete, but nothing should break).

It's more involved to do more because to figure out whether decommissioning can proceed you need to make informed statements about where replicas can and cannot go, which is logic owned by the allocator, and that is far away and would be quite low on the core list of priorities to fix.

@tim-o, WDYT?

**Comment by tim-o** [comment]
@tschottdorf , I just want to make sure I understand: the PR would solve this need by preventing the decommission statement from completing unless there are enough nodes to pick up the replicas? And until there are enough, the node will stay active? If so, yeah, that'd avoid the need for this ticket.

**Comment by tschottdorf** [comment]
Yes, that's the change I made. Ok, closing!
