### ISSUE TITLE
kv: prevent uncertainty restart after pushing intent into own future

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2861]
Similar to #2859, there is some surprising behavior for read-only transactions and snapshot isolation. In one shell do:

```
create database d1;
set database = d1;
create table t1 (col1 int primary key);
insert into t1 values (1);
begin transaction isolation level snapshot;
insert into t1 values (2);
```

Note, leave the transaction uncommitted. In a second shell do:

```
begin transaction isolation level snapshot;
select * from d1.t1;
query error: read at time 1445276533.949613094,0 encountered previous write with future timestamp 1445276533.951177120,0 within uncertainty interval
```

Why isn't the read-only transaction seeing a snapshot of the database at the time it started? I imagine this is an artifact of our implementation and yet it is surprising.

**Comment by tschottdorf** [comment]
that you're getting the error is surprising if you're doing the second thing strictly after the first. Did you begin the second transaction before the first by any chance?
In any case, the error is a retryable error that would instruct the KV client to simply retry the command at a higher timestamp (due to clock uncertainty). Since only single-roundtrip transactions can be managed completely by the kv client, you get the error back.

**Comment by petermattis** [comment]
The second transaction was started several seconds after the first.

**Comment by tschottdorf** [comment]
yep, same here. Let me take a closer look.

**Comment by petermattis** [comment]
Might be unrelated, but perhaps we should auto-restart SQL transactions if the first statement was the one which encountered an error.

**Comment by tschottdorf** [comment]
oh, I think what the read is doing is pushing the first transaction into the future, but then it's going back for the read and now has this transaction... in the future. Which leads to the uncertainty error. It should have marked the node as "certain", so I'm assuming that's what got lost there.

**Comment by tschottdorf** [comment]
The only way a NodeID is currently added to the Txn is currently through a `ReadWithinUncertaintyIntervalError`. We should really be doing this with every successful response as well.

**Comment by tschottdorf** [comment]
working on this.

**Comment by tschottdorf** [comment]
It's unfortunately a little complicated. The way `txn.CertainNodes` works is that it's populated on a `ReadWithinUncertaintyIntervalError`. We should always update `CertainNodes` if a successful transactional reply is sent; that isn't the issue.
The issue here is that we run into the `ReadWithinUncertaintyIntervalError` after the txn has just pushed an offending write out of the way (i.e. into its immediate future). When the `Store` retries the batch, we still have to worry about uncertain reads, just not for that one value (because we know we just pushed it into our future, and  we know we're omitting it). So we need a way to attach the information "don't perform uncertainty restarts for only a subset of the requests in the batch".
On top of that, we're currently just setting `txn.Timestamp = txn.MaxTimestamp` when we know there aren't uncertain reads. That's also not quite clean since that transaction may be returned in the reply, and we shouldn't risk messing with the `MaxTimestamp` of the reference transaction (I don't think it would be polluted since `txn.Update(.)` does the right thing, but still).

I'm thinking adding a field `[]CertainIndexes int` to the batch request header which could transport this information (`CertainIndexes = [-1]` would signify a certain read).

**Comment by tschottdorf** [comment]
I'm going to reopen this since the fix that closed this was only a stop-gap for single-node deploys. It seems worthwhile to work towards an actual fix, as described above.

**Comment by tschottdorf** [comment]
The book-keeping complexity here is most easily demonstrated using a Scan operation (single-point ops are easier).

Imagine that on a `Scan("a","c")` and on a node that's not in `CertainNodes`, we run into an intent on key `a` which we manage to push (the other writer is snapshot). Upon retrying the read, we'll run into a `ReadWithinUncertaintyIntervalError` on `a`. But that's an artifact of "forgetting" that we actually pushed this key.
We can't just set the whole `Scan` to certain because we don't really know much about any of the other keys we're going to read.
For example, we can still catch an "honest" `ReadWithinUncertaintyIntervalError` if we continue the scan to key `b`, depending on what's there.

So when resolving the intent, we need to attach information to our request that we can pass all the way down to the internal MVCC machinery (iterators) to read without uncertainty only on single keys.

**Comment by tschottdorf** [comment]
To repro this, it's enough to run change `ba.Txn.CertainNodes.Contains(...)` to always return false, and to run `make test PKG=./sql TESTS=Logic TESTFLAGS=-v -d testdata/*2861`.
