### ISSUE TITLE
changefeedccl: support (or workaround) schema changes with backfills

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28635]
Consider the following sequence of events:

- t1: `CREATE TABLE foo (a INT PRIMARY KEY)`
- t2: `INSERT INTO foo VALUES (1), (3)`. this writes v1 of the table desc
- t3: `CREATE CHANGEFEED FOR foo WITH updated`
- t4: `ALTER TABLE foo ADD COLUMN b STRING DEFAULT 'bar'`. this writes version 2 of the table desc (with the new col mutation in DELETE_ONLY) and allows leasing v1 or v2
- t5: no more v1 leases, the schema changer writes v3 of the table desc (with the new col mutation in DELETE_AND_WRITE_ONLY) and allows leasing v2 or v3
- t6: schema change backfills kv `(1)` to be `(1, 'bar')`
- t7: `INSERT INTO foo VALUES (2)`
- t8: schema change backfills kv `(3)` to be `(3, 'bar')`
- somewhere between t5 and t9: no more v2 leases
- t9: schema change backfiller finishes and updates table desc. this writes v4 of the table desc (with the col public in the table desc) and allows leasing v3 or v4
- t10: no more v3 leases

The question is what to emit for the insert at t7. The schema change could fail or otherwise be rolled back, so until t9, we can't say for certain whether it should be `(2)` or `(2, 'bar')`.

Option 1: If we emit `(2)@7` and no more changes ever come to `a=2`, then reading the value with `SELECT` at t11 will give a different answer than the last thing we emitted, which seems counterintuitive (and would break things like the ElasticSearchConnector).

Option 2: If we emit `(2, 'bar')@7` at t7 and the schema change is rolled back, then we've emitted bad data. This option is a no-go.

Option 3: We could wait until t9 to emit the insert of `(2, 'bar')@7`, at which point the schema change was successful, but this means that running any schema change that needs a backfill will essentially hang the changefeed until it finishes. Also, running a SELECT at t7 will give a different result (it would pick up the old version of the table desc with the new column still in mutations, so it would be `(2)`). This is also a no-go.

Option 4 (danhhz's preference): We could emit `(2)@7` at t7 and then also emit `(1, 'bar')@t9`, `(2, 'bar')@9`, `(3, 'bar')@9` at t9. This addresses the ux and latency issues, but it's costly to emit every row in the table every time a schema change with backfill runs. So, we could add an option to turn off the t9 emits (behaving exactly like option 1). Making it a configurable option is unfortunate, but this seems to be the best of all worlds.

The current behavior is the changefeed watching foo will throw an error about not supporting backfills at some time before emitting anything for t7. This means we've avoided any correctness issues, but there's currently no way for the operator to manually recover the changefeed. For 2.1, we either need close the loop on the manual workaround or implement option 4. It's not yet clear to me (danhhz) which will be easier.

**Comment by danhhz** [comment]
Oh, an awful (but workable) workaround is to make a totally new changefeed with a new initial scan at a time after t9 and start everything from scratch.

**Comment by mrtracy** [comment]
I've been looking into this for a little while now, here's an update on our progress:

+ Support for schema backfills will be behind an option, tentatively `allow_schema_backfill`. Without this option specified, the current behavior of cancelling a changefeed when a backfill schema change occurs will continue.
+ For changefeeds with backfill support, during a backfill we will be emitting several "duplicate" rows during the backfill process. This is because the backfill process occurs over several transactions, in which rows are written with the new (still write-only) columns filled in.  From the perspective of the changefeed poller, we have not figured out a way to distinguish these writes from normal user updates without some considerable modifications. Therefore, we will simply emit these changes normally on the feed; the non-public column data will *not* be emitted on these writes.
+ Finally, after the schema change is finalized, the changefeed will again output all rows in the table as of the moment the added column(s) become public.

**Comment by danhhz** [comment]
SGTM

**Comment by mrtracy** [comment]
Resolved by #30902.
