### ISSUE TITLE
sql:  TestTraceFromErrorReplica:  no redirect message from n1 found

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#28694]
https://teamcity.cockroachdb.com/viewLog.html?buildId=841286&buildTypeId=Cockroach_UnitTests

**Comment by jordanlewis** [comment]
```
trace_test.go:605: no redirect message from n1 found
```

**Comment by andreimatei** [comment]
@petermattis you volunteered to debug some failures. Here's one that might jive with similar stuff I think you've debugged recently; if you don't want it, pass it back.
A query is expected to use the wrong replica and get redirected through a `NotLeaseHolderError`, and yet sometimes apparently it goes to the right replica from the get-go.
Perhaps this is due to some smarts I think @tschottdorf has added recently for updating leaseholder caches more aggressively than before - I think now we update on successful RPCs whereas before we didn't or something like that (although I don't know if this Aug 16th is before or after said change).

**Comment by tschottdorf** [comment]
Aug 16 is definitely before.

**Comment by petermattis** [comment]
`432950 runs so far, 0 failures, over 1h26m27s` <- roachprod-stress on master. Let me see if I can reproduce this failure on an older SHA.

**Comment by andreimatei** [comment]
sgtm

**Comment by petermattis** [comment]
No failures after 23m with `roachprod-stressrace` on current master.
