### ISSUE TITLE
storage: loading many problem range pages at once OOM-kills the node

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#28854]
- Which version of CockroachDB are you using?
v2.1.0-alpha.20180702-779-gaa52d31

- What did you do?
On cluster adriatic, 5/6 nodeos were live, but there were 11 problem ranges. On adriatic-05, I went to the problem ranges page (/reports/problemranges), and saw 11 ranges listed as Unavailable.
I opened each page in a new tab.

- What did you expect to see?
11 reports on the unavailable ranges.

- What did you see instead?
The node crashed, via OOM kill.

- What was the impact?
Now I have 248 unavailable ranges.

I was able to replicate this with node 6 as well.

@benesch is following up with a memory profile, after bringing node 6 back up and replicating the crash. Assigned to @tschottdorf for triage and further assignment.

**Comment by arjunravinarayan** [comment]
The pages are definitely unresponsive for long periods of time (10+ minutes), bringing down the Admin UI. This effect is reliably reproducible, even if crashing the nodes is not.

**Comment by benesch** [comment]
Upping the memprof interval yielded this damning profile:

https://cdn.rawgit.com/benesch/fdb9621b442fb88349a06ed3a1854843/raw/b7dded3f618637595105ae06ccec42c4b5bbd35c/pprof.svg

/cc @nvanbenschoten this seems like something you're qualified to investigate :)

**Comment by nvanbenschoten** [comment]
I fairly confident this memory blowup should be avoided by https://github.com/cockroachdb/cockroach/pull/27117 and it looks like adriatic is running `aa52d3187a49f29a54d85340fba890cc6e45e461`, which doesn't include that change. I'm tempted to say this is resolved since I don't think there's going to be a great way to test this out past deploying a new build to adriatic and watching to see if we ever find this again. What do you think @arjunravinarayan?

**Comment by arjunravinarayan** [comment]
Yup, that sounds good to me. Thank you for the triage!
