### ISSUE TITLE
storage: TestAmbiguousResultErrorOnRetry is fooling itself

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28985]
At least the `1PC-txn` subtest is not testing anything. It's supposed to test, among others, that re-evaluations of 1PC batches get ambiguous errors. Except it's not actually verifying that and, moreover, the batch it re-evaluates does *not* get an ambiguous error. That's really scary, but I suspect it's just an artifact of the test setup which is funky.

The first problem is that the test passes just fine if the expected ambiguous error is not generate. The following line returns a `nil` err if `detail` is `nil`:
https://github.com/cockroachdb/cockroach/blob/9af0fc159e4f60636659b169860b6a85fbab2506/pkg/storage/replica_test.go#L8471

The second problem is that, the vast majority of time, the expected error is not generated at all (I've seen it generated once though, so there's a race at play here too). The test hackily forces a re-evaluation by intercepting the proposal, bumping the `LeaseAppliedIndex` and calling `refreshProposalsLocked()` (pretending that a snapshot arrived), and then still proposing the "original" request. It then would like to expect that the re-evaluation receives an ambiguous error because the "original" succeed. The test claims that holding the replica mutex while submitting the original proposal is supposed to ensure that that proposal will be applied before the retry.
For some reason, when the batch is evaluated a second time, the respective `mvccPut` doesn't find the key that it's writing (if it would have found it, somehow a `WriteTooOld` would have been generated I think, which would have been turned into an ambiguous error).

I don't know what's going on. I hope that what the test is doing is not kosher, but don't know what to blame exactly. I think maybe the reason why the second evaluation doesn't see the first is because the two requests end up being in the command queue at the same time and so they operate on bad RocksDB snapshots (I think maybe calling `refreshProposalsLocked()` takes the original out of the queue prematurely, given that we manually call `defaultSubmitProposalLocked()` for it later. But I don't know for sure...

cc @tschottdorf and @nvanbenschoten in case they have any words

**Comment by andreimatei** [comment]
Note to self - maybe there's two problems with this test:
1) `refreshProposalsLocked()` provides a proposal response to the first proposal, which takes it out of the command queue, and then the re-evaluation happens before the first application (and so it uses a non-copacetic rocksdb iterator)
2) the first application does actually go through because we've already bumped the `LeaseAppliedIndex` and so when it is checked (downstream of raft), the check will fail. And yet I think once I've seen the ambiguous error being produced - so how can that be?

**Comment by andreimatei** [comment]
cc @bdarnell

**Comment by bdarnell** [comment]
> The following line returns a nil err if detail is nil:

I spent a few minutes going down the wrong path here, so for the record this is also true of the preceding check at line 8467 (which is actually the one that applies when the command does not generate an error at all).

It looks to me like the test has always been broken and the incorrect use of `errors.Wrapf` on a possibly-nil value covered up this fact. So let's start from scratch:

The test wants to verify that one-shot writes (both non-transactional ones and 1pc txns) produce ambiguous errors if they are re-evaluated and then fail (re-evaluations now only happen when snapshots are applied, which reduces the scope of the test). I think the way I'd test this is:

1. Use a `multiTestContext`, and stop all but one node during the test so that commands can be proposed but won't apply.
1. Use a `submitProposalFn` hook only to determine when the command has reached the proposal stage
1. Once the submitProposalFn has been tripped, call `refreshProposalLocked` (probably with all the same hackery the test is currently doing).
1. Verify with the `submitProposalFn` that the reevaluation is also getting proposed
1. Bring the downed nodes back up to let everything finish
1. Verify the AmbiguousResultError (in the same way that this test is currently trying to do).

On the other hand, this situation is really strange. We only have outstanding proposals while we're the leaseholder, and the leaseholder shouldn't get so far behind that it would need a snapshot from the (non-colocated) leader. The attempted retry here is just an effort to avoid ambiguity (if the retry succeeds, we can return success instead of an ambiguous error). I think the snapshot-with-pending-proposal case is too rare to worry about and we should just return an ambiguous error to the client without retrying (as we do for `proposalErrorReproposing`). Then I don't think we even really need this test (or at least it can be dramatically simplified).

**Comment by tbg** [comment]
@petermattis could you take a look?

**Comment by tbg** [comment]
(my preference would be to do what Ben suggested: return an ambiguous error)

**Comment by petermattis** [comment]
@spencerkimball You volunteered to help with some of these failures. Can you take a look at this one?

**Comment by andreimatei** [comment]
hold up - the conclusion here is that we want to remove a type of reproposal and delete this test, not make any fixes

**Comment by andreimatei** [comment]
Fixed in #33381

**Comment by tbg** [comment]
So satisfying to see a wart removed. Thanks for making it happen @andreimatei.
