### ISSUE TITLE
cli: crash caused by running SQL commands from external file

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#29040]
I was doing QA for #28158, and I managed to get the database into a bad state so that every command was really slow. The command I ran was: `> \| cat cockroach-data/extern/employees.sql`. This file contained all the output from running a pg_dump on an employees database with about 3 million rows.

Basically, since I was testing `IMPORT PGDUMP`, I was trying to see how long it would take to run all the inserts directly instead of using IMPORT. At some point the CLI crashed and restarted:
```
root@:26257/employees> \| cat cockroach-data/extern/employees.sql
invalid syntax: statement ignored: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
```
Soon after that, every CLI command was super slow, even when I restarted the database. Commands like `show tables` would take ~5 seconds to run. I'm not sure the two things are connected, but the crash should probably be investigated. The server did not crash, only the client.

Github won't let me attach the file here (it's too large), but happy to send it some other way if it would be helpful.

**Comment by knz** [comment]
The problem you found is that `\|` sent the entire pgdump file to the server as a giant SQL batch. There was no "crash" -- the server at some point bailed out with a memory budget in pgwire. However it was not before it had already accumulated thousands of statements to execute in the SQL session, and because we do not (yet) detect dropped client connections, it happily went through to execute the statement already batched.

I suppose the batched statements contained plenty of CREATE and INSERT. this would explain why everything was slow from then on.

Really the way forward is to revisit `\|`. Currently this command is not working as intended.

**Comment by knz** [comment]
Dup  #15645.
