### ISSUE TITLE
cli: `cockroach quit` produces transient errors again

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#29180]
This resurrects the problem previously known as  #25870

`cockroach quit` complains:

```
W180828 13:53:50.800930 1 cli/start.go:1251  graceful shutdown failed: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding; proceeding with hard shutdown
```

Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=866453&buildTypeId=Cockroach_UnitTests

This should have been fixed in  #26158 but may have been resurrected inadvertently in #29146.

cc @a-robinson

**Comment by a-robinson** [comment]
I'm really not seeing what #29146 could have done to let such an error sneak through, since all it changed was add a couple cases where we'd return early if the error was an init error. This transient error is happening specifically because `doShutdown` isn't returning early.

Agreed that it's annoying, though.

**Comment by knz** [comment]
ok I'll look into it
