### ISSUE TITLE
schema changes: cannot update progress on failed job error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#29200]
On the same cluster (running 2.0.2) as #29190 and #29192, I see this periodically:
```
W180827 10:32:49.623242 522 sql/schema_changer.go:785  [n6] failed to log progress on job 367367629159563268 after completing state machine: cannot update progress on failed job (id 367367629159563268)
```

I think this may mean that two nodes are running the same job/schema change at a time. And indeed, I see at least `n2` and `n6` complaining about it around `180827 10:32`. In fact more nodes have messages about this job across days.
Something here is fishy, but I don't know what to blame exactly.

**Comment by vivekmenezes** [comment]
This is certainly a problem that could be seen before https://github.com/cockroachdb/cockroach/pull/28014.
The PR fixed a problem where a job could be marked failed even when the schema change could not have rolled back.

I'm going to close this because I don't see any particular action we need to take.
