### ISSUE TITLE
Kubernetes, Service Mesh, TLS & CDB

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#29224]
Let's face it, managing TLS manually (init & rotation) in k8 is not really fun and can be an ops nightmare. It's no wonder that service meshes are trying to (successfully) manage this aspect. For example, both Istio and Consul Connect are managing TLS of behalf of services.

In this setup, I dont want CDB to deal with TLS at all. I am currently forced to use the `--insecure` flag which feels weird as discussed previously with @bdarnell in the [past](https://github.com/cockroachdb/cockroach/issues/10780) because it ends up communicating a false reality that the cluster is not secured.

Recently, I have noticed that now, some features (Create user with password) are being gated behind CDB running a secure cluster by itself. I understand the principle behind this, nobody wants to send sensitive materials over a non secure connection but we are back to the same root problem of CDB making the assumption that if it is not handling TLS by itself, it necessary means it's insecure.

When we look at it, the reality is:

1) Insecure cluster
2) Secure cluster with managed TLS
3) Secure cluster with provided TLS

Using `--insecure` flag is not imho the proper way to tackle 3), we should be able to give a `--with-provided-tls` flag to hint CDB that the cluster is secured even though it is not managed by itself.

**Comment by a-robinson** [comment]
cc @bdarnell @mberhault

As discussed previously, though, allowing things like passwords for users is essentially just security theater unless there are also passwords required for nodes to join each other. If you allow nodes to join each other without passwords, then any user could just pose as a cockroach node to get root access to all data in the cluster. And if you do require some sort of password for nodes to join the cluster, then you'll end up needing similar infrastructure to manage the node password as to manage a wildcard cert for the nodes.

There are other potential workarounds, but none that appear very user friendly.

**Comment by tlvenn** [comment]
Hi @a-robinson,

In a service mesh, as you are aware, there are rules which enable one service to connect to another, otherwise a given service cannot connect to another service, period.

To push this even further, for traceability and forensic purpose, leveraging dynamic passwords is the next step. In this scenario, each services that want to connect to CDB will get assigned a dedicated user/password in CDB. This is something entirely managed by Vault for example (Once #28045 is addressed).

But presently, because my cluster has to run with the `--insecure` flag, Vault cant even create users with password for services anymore.

**Comment by knz** [comment]
@piyush-singh @kannanlakshmi I think you may want to chime into this discussion

**Comment by bdarnell** [comment]
If you're relying on the service mesh for security, what are the passwords for? Why not just use passwordless users and rely on the service mesh for client security too?

The answer is probably that the service mesh provides a weaker level of security than what is truly desired: It protects against eavesdropping and MITM, but doesn't really provide finer-grained authentication than "allowed" or "disallowed". You still need *something* (passwords or certs) to distinguish one user from another (and from `root`). 

This is basically a duplicate of #16188: it's desirable to have some form of authentication in insecure mode. The difficulty is that there are two protocols to support: the client/server postgres protocol (which supports both password and cert auth) and the peer-to-peer inter-node protocol, which currently only supports certificates or nothing. 

We're not (just) being stubborn here and saying that certificates are the only valid way to do auth. Designing and building a password-equivalent authentication system for this layer is a significant amount of work. So far we haven't undertaken that project because it seemed that this mode would always be a second-class citizen next to the full TLS mode (and so we'd be better off spending our time on improving the TLS experience via integration with Vault, etc). But maybe service meshes provide an environment where such a configuration would make sense and not just be a discouraged alternative. We'll take that into consideration; thanks for pointing it out.

**Comment by tlvenn** [comment]
> If you're relying on the service mesh for security, what are the passwords for? Why not just use passwordless users and rely on the service mesh for client security too?

To guarantee the identity of the service pod connecting to the DB as a given user.

> The answer is probably that the service mesh provides a weaker level of security than what is truly desired: It protects against eavesdropping and MITM, but doesn't really provide finer-grained authentication than "allowed" or "disallowed"

Not really, the issue is not to distinguish between 2 users who would have different credentials but to distinguish between 2 instances of the same service. If one pod / server is compromised, it will connect to the DB with an unique user and will leave that fingerprint on the DB. When something suspicious is happening on the DB, by looking at the user who made the query, we can pinpoint the pod / server and take action to remove that rogue instance from the cluster for example.

To quote Hashicorp on the need of dynamic secrets:
>The second challenge after centralization is that services are often sharing the same credentials. This has been a standard practice for applications, but most security organizations would have a panic attack if it was proposed that all human users share the same login credentials. If those credentials leak it is very challenging to identify the source of the compromise or leak. Updating or rotating credentials creates a coordination problem, as there are many users of the credential. Revoking the credential has a large blast radius, potentially taking down multiple service tiers at once.

Source: https://www.hashicorp.com/blog/why-we-need-dynamic-secrets

**Comment by knz** [comment]
We've made progress in multiple areas around this:

- TLS for client connections can now be disabled
- TLS cert setup for inter-node connections can now be automated (`cockroach connect`)
- we're tracking multiple issues to add more configurability

I think this particular issue has outlived its usefulness; if you have further specific requests, please let us know.
