### ISSUE TITLE
cloud: k8s config needs updating for --http-host in 2.1

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#29240]
The k8s config specifies `--http-host` but that has been removed from the CLI. It should now be `--http-addr`.

**Comment by a-robinson** [comment]
We should still update the config to avoid using the deprecated flags, but removing the `--http-host` flag was actually unintended. I fixed it earlier in https://github.com/cockroachdb/cockroach/pull/29213 / https://github.com/cockroachdb/cockroach/pull/29220.

**Comment by mjibson** [comment]
Ah. I was running the most recent beta and hit this, and was confused that the release notes said only deprecated.

**Comment by tlvenn** [comment]
Just ran into this myself and leveraging the CDB helm chart to deploy in K8.

**Comment by a-robinson** [comment]
Sorry about that, @tlvenn. We can't switch to using `--http-addr` in the config until v2.1 is the default version, since v2.0 doesn't include that flag. All future v2.1 beta releases will still support the `--http-host` flag thanks to #29220, though, so hopefully you're the last person to run into this.

**Comment by tlvenn** [comment]
No worry @a-robinson, I will wait for the next beta to upgrade my staging cluster.
