### ISSUE TITLE
ui: Login times out when a cluster isn't in a healthy state

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#29270]
Attempted to log in on Omega, running version v2.1.0-beta.20180827-141-gf9c0948 with Auth enabled by default. When the cluster is in a bad state, logging in times out after 30 seconds. 

This isn't ideal in a scenario when you are trying to debug the cluster's state, however @couchand pointed out that debug.zip might be the only path to investigate in that scenario. Filing this issue to investigate how best to handle login for misbehaving clusters.

Jira issue: CRDB-4875

**Comment by vilterp** [comment]
The main problem is that login as implemented requires sessions to be read/written from the `system.sessions` table, persisted in the KV layer. Persisting sessions allows you to stay logged in while hitting multiple nodes behind a load balancer, but can lock you out when KV reads/writes to that range aren't working. It seems we want an option which lets you log in without requiring KV reads/writes, and which maintains security.

Strawman proposal @dt and I came up with:
- Add a CLI command, e.g. `cockroach enable-temp-login --certs-dir=certs --temp-user=<username> --temp-password=<password>`, which makes a gRPC call to the cluster to set up a temporary login
- Implement the endpoint hit by this tool. Store the temporary login in memory s.t. logging in with this username and password skips the normal path, and instead creates a session which is stored only in memory.
- Update the authentication mux to check for these special memory-only sessions instead of always consulting the KV layer.
- (Probably) implement a TTL on these temporary logins and their sessions.

This seems to give users a way of securely debugging clusters where KV is not working, without compromising security, at the cost of some code complexity, although I don't fully understand @couchand's concerns about security here.

Also, the idea of allowing users to take a `debug zip` and browse it in the Web UI (RFC: #18845) seems to be another possible solution.

**Comment by couchand** [comment]
My only security concern here is that I want our authx code to be as simple and obvious as possible to make auditing easy.

My main concern is that we'd be spending a significant amount of effort solving this problem in the wrong way: I don't think the web UI should be the primary tool for debugging clusters that are significantly broken, since more than just login will fail in that case.  We should be focusing our efforts on healthy and moderately problematic clusters, and providing data exports and external tooling to help debugging more fundamentally broken clusters.

So, given a fixed amount of bandwidth to spend on the debugging broken clusters problem, I'd rather spend it on making `debug zip` or similar tooling better and more usable than trying writing some new mechanism to get login working, only to enable the user to see a UI that has trouble getting any useful data anyway.

**Comment by vilterp** [comment]
@bdarnell do you have any thoughts on this? Login being dependent on KV for user credentials and settings does seem to be a problem, since it prevents you from using the admin UI to debug your KV issues… This has been a problem on both Cyan and Reg.

**Comment by bdarnell** [comment]
>  I don't think the web UI should be the primary tool for debugging clusters that are significantly broken, since more than just login will fail in that case. We should be focusing our efforts on healthy and moderately problematic clusters, and providing data exports and external tooling to help debugging more fundamentally broken clusters.

I agree with @couchand. Making login work while the cluster is down would be non-trivial and then you're just going to be logging into a mostly-broken UI. Debugging a broken cluster fundamentally requires tools external to the cluster.

**Comment by a-robinson** [comment]
At a fundamental level I completely agree, but we've really built up the debug pages (and admin/status server endpoints) as our primary debugging tools over the last couple years. Giving them up is going to be painful for a while.

**Comment by andreimatei** [comment]
Can we give up the need tp *write* if we give up support for accessing the UI through a load balancer?

**Comment by bdarnell** [comment]
We could still access through a load balancer without writes if we issued signed bearer tokens instead of server-side sessions. What we'd lose is the ability to enumerate and revoke those tokens.

**Comment by vilterp** [comment]
Seems like we can't get around reading from the users table for username/password-based authentication, but can we gossip sessions instead of writing them to KV?

Also, I'm not sure whether our login attempts on borked clusters (Cyan and Reg) have stalled on the reads from the users table, the write to the sessions table, or something else; we just see the request time out after 30s. Not sure where best to look for something like this (most ideas I have are debug pages anyway).

**Comment by bdarnell** [comment]
Gossiping sessions (and failing closed if it's not in gossip) would probably work in place of writes.

In a sufficiently borked cluster, we can't read from the users table, because in order to read, you need to be able to write liveness records, leases, etc. Currently on register I can log in with a SQL shell and cert (although I can't do much once connected), which I think implies that the KV reads are working enough for us to be able to log in this way.

**Comment by couchand** [comment]
@mrtracy did you consider gossiping web sessions or was the plan always just a system table?  It doesn't look like the RFC mentions the question.

**Comment by dt** [comment]
+1 to signed bearer tokens, just since it relies on fewer of the moving parts pieces being moving correctly to get to the debug tools -- I could easily see debug pages being useful for investigating a gossip issue.

**Comment by couchand** [comment]
Our session ids are bearer tokens, we don't sign them because signing a hash of random bytes is pointless.  But from context I gather that what's meant here is stateless sessions with something like JWT.  Due to the inability to revoke sessions, this seems like a non-starter.

It seems like gossiping sessions is a good way to address the specific concerns raised in this issue.  It would be good to minimize the surface changes, for instance the SQL system table access is currently the only way to revoke sessions.  If we could implement the change by exposing the same system table but have it backed by memory storage and gossip for communication, that seems pretty workable.

What's the level of effort to do something like this?  Is it feasible and safe to try to make this change before the release?

**Comment by dt** [comment]
> Due to the inability to revoke sessions, this seems like a non-starter.

Is that impossible? Could we sign the login-generated stateless session cookies with cluster.secret, so that they could be invalidated by rotating cluster.secret?

**Comment by couchand** [comment]
See the leftmost column of this flowchart:

![image](https://user-images.githubusercontent.com/793969/45762639-ce2cdf00-bbfc-11e8-80f3-80b92d9990d8.png)

from: http://cryto.net/~joepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/

**Comment by dt** [comment]
I mean, we're talking about an internal admin UI here, so `EVERY SINGLE USER` isn't exactly millions of customer sessions -- I'd be fine with a couple DBAs logging back in if you need to revoke a session?

**Comment by bdarnell** [comment]
Is the inability to revoke a session really a dealbreaker? We don't (yet) support cert revocation for cert auth, for example. Issuing a short-lived signed token when we can't write to the session table seems reasonable to me. However, I don't think it's reasonable to add support for that model at this point in the 2.1 cycle.

Using gossip also weakens our revocation support - there's no guarantee that information will propagate through gossip in any particular time, so a revoked token could continue to be used for the gossip propagation delay. Again, maybe that's OK, but I don't think revocation support is a good reason to argue for gossiping session state instead of signed tokens. 

It's also not clear how much more highly available gossip is than kv reads in practice - a lot of our recent issues that have rendered clusters unavailable have also broken gossip.

**Comment by dt** [comment]
If we didn't aim to have roaming sessions / load balancer, and just had local sessions on each node, how would revocation work? would we need to revoke any session for that user each node?

**Comment by andreimatei** [comment]
@dhartunian @kscurtis I wanna make sure this guy is on your radars. I think we were hit by it again, and it's pretty terrible - when the cluster is in different states of brokedness and you need the UI most, you can't access it for bad reasons (IMO). Requiring the UI to be able to *write* to the database in order to log you in is really bad, I think. Even requiring it to read anything is quite bad (at least when I'm trying to auth as root). Let's please do something about it soon, it's a major problem.
To be fair, it seems like @bdarnell was dissenting a bit about the need to improve things in favor of having some "other tools", but it looks like that he's come around some afterwards maybe.
