### ISSUE TITLE
storage: understand and fix lack of space reclamation

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#29290]
We've known for a while that space reclamation still isn't working properly, both after dropping and rebalancing (see for example #26147).

In the context of recent RocksDB investigations, the idea came up of removing the CockroachDB-userland compaction queue and to rely more on RocksDB to carry out the required compactions. Instead, we'd inject suitable table collector facilities

https://github.com/cockroachdb/cockroach/blob/c13227c9da61482086ef1a40ba2ec3f152c55cd2/c-deps/libroach/options.cc#L153

that would take into (point and range) deletion tombstones.

We should run larger experiments (with bigger datasets than #26147) and rebalancing, point and clearrange deletions, that verify the expected space reclamation and fix them while understanding the reason they don't happen today.

cc @benesch @dt

**Comment by petermattis** [comment]
FYI, I experimented using @benesch's delete-range property collector to mark an sstable for compaction if it contained any range tombstones. I hoped this would remove the need for the compaction queue, but the `clearrange` roachtest showed that not all of the disk space was reclaimed. I think this is pretty much the experiment you're describing. I didn't have a chance to investigate what wasn't working.

See https://github.com/cockroachdb/cockroach/compare/master...petermattis:pmattis/delete-range-prop-collector?expand=1

**Comment by tschottdorf** [comment]
Note: I'm skipping the space reclamation portion of the drop test in https://github.com/cockroachdb/cockroach/pull/29511. That test should be restored when this issue is fixed.

**Comment by petermattis** [comment]
Talking about this with some folks today, the problem with my experimental branch above might be not flushing the memtable on some sort of periodic basis. The `clearrange` roachtest has no traffic other than the `DeleteRange` traffic, so it seems possible that a large number of range tombstones are still in the memtable. That would be easy enough to fix. If I find time I'll give it a whirl.

Cc @benesch in case you want to try this experiment first.

**Comment by petermattis** [comment]
I've fixed my experimental branch. The problem was the lack of flushing. Here are some graphs showing a run of `clearrange` with the compaction queue "disabled". (By disabled I mean that it doesn't suggestion compactions, but instead periodically flushes the memtable based on suggested compactions).

<img width="968" alt="screen shot 2018-09-20 at 12 00 50 pm" src="https://user-images.githubusercontent.com/6201335/45837441-5a163800-bcdd-11e8-87d9-2fb908b40812.png">

The decrease in available space is because the test sets up a zfs snapshot (i.e. it is nothing to be concerned about).

<img width="967" alt="screen shot 2018-09-20 at 12 00 59 pm" src="https://user-images.githubusercontent.com/6201335/45837444-5d112880-bcdd-11e8-8baf-764586e52f52.png">

The compactions are all being driven by RocksDB. Note that there are relatively few flushes. 

<img width="964" alt="screen shot 2018-09-20 at 12 01 13 pm" src="https://user-images.githubusercontent.com/6201335/45837451-5f738280-bcdd-11e8-8a53-9cdabf704a53.png">

Look ma! No compaction queue activity.

**Comment by petermattis** [comment]
Since this issue was filed, we have switched to using Pebble which incorporates range tombstones in its compaction heuristics and also has the concept of a deletion-only compaction that is a metadata only operation which is particularly effective in reclaiming disk space quickly.
