### ISSUE TITLE
ui: timeseries: Add failed query count to Queries chart

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#29346]
We have added a new time series for failed query counts, however it is currently not exposed and only accessible through custom charts in debug pages. We should expose this time series on the Overview dashboard in the Queries chart.

cc @vilterp @couchand @danhhz

**Comment by couchand** [comment]
I don't think it's appropriate to add this as an additional series to that chart.  Currently, each of the series on that chart are types of SQL statements, but the count of failures is an aggregate across a subset of each of the types.  Thus, the metrics are incomparable.

It would be much stronger to allow comparison of the failures to the total number of statements or the number of successful executions, neither of which is represented on that chart, even by manually summing each of the other series, since those series are not a complete representation of the subtypes.

**Comment by danhhz** [comment]
From a practicality standpoint, it's a bit incomparable, but the benefit of having it somewhere obvious outweighs the con. If we make it a new graph of successes and failures and then decide to bury that graph because it's not important enough to have on the front page, we've lost the point of this.

**Comment by vilterp** [comment]
Updated the PR to add failures as a separate chart on the SQL dashboard. Fourth from the top; hopefully not too buried :P
