### ISSUE TITLE
gossip: Log spam in one node cluster with join flags

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#29438]
If you start a single cockroach process with a few join addresses, then init the single node, log messages about attempting to gossip connections will be emitted over and over every second until the end of time.

One such repro:
1. Start a Kubernetes cluster: `minikube start`
2. Install helm: `helm init`
3. Install the cockroach helm chart with just 1 replica: `helm install stable/cockroachdb --name my-release --set Replicas=1`
4. Check its logs: `kubectl logs my-release-cockroachdb-0`

In this particular case, only the node's own address is resolvable via DNS, so it just repeats these two messages every second:

```
I180831 19:35:50.026783 5192 gossip/client.go:129  [n1] started gossip client to my-release-cockroachdb-0.my-release-cockroachdb:26257
I180831 19:35:50.027890 5192 gossip/client.go:134  [n1] closing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257): stopping outgoing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257); loopback connection
```

**Comment by petermattis** [comment]
Here's an easier repro:

```
~ cockroach start --insecure --join localhost:26257 --logtostderr
...
~ cockroach init --insecure
```

The problem spam is being generated by `Gossip.bootstrap`. In a single-node cluster, `haveClients` will always be `false` so gossip will continually try to "bootstrap". If there is a valid resolver (which there is because a join address was specified), we'll try to open a client, discover that the connection is a loopback to ourselves which will cause `Gossip.maybeSignalStatusChangeLocked` to be called. That method determines that gossip is "stalled" because there are no incoming or outgoing connections. And because there is a resolver, it will poke the stalled chan causing bootstrap to loop again. 

@spencerkimball Is this what you expect to be happening in a single node cluster? Detecting loopback connections is irritating because the resolver address could be some sort of DNS round-robin or load balancer and thus not always create loopbacks. And there is a related scenario where the join flag specifies a remote node that has not yet been started. Perhaps a node with a valid sentinel key should not consider itself stalled.
