### ISSUE TITLE
Space is not reclaimed

### ISSUE THREAD

**Issue by isoos** [cockroachdb/cockroach#29441]
CRDB Version: `v2.1.0-beta.20180827` (recently upgraded from `v2.1.0-alpha.20180730`)

I've got a table with ~5M records, and it seemed normal that it took up GBs of space. Right now it has only ~12000 rows, and the admin console reports 1.3 GiB size (and 486 ranges). The schema is simple, and the `JSON` column has a content typically less than 200 bytes.

````
CREATE TABLE table_x (
	c1 STRING NOT NULL,
	c2 STRING NOT NULL,
	c3 STRING NOT NULL,
	c4 JSON NULL,
	c5 TIMESTAMP NULL,
	c6 INT NULL,
	c7 STRING NULL,
	c8 TIMESTAMP NULL,
	CONSTRAINT "primary" PRIMARY KEY (c1 ASC, c2 ASC, c3 ASC),
	FAMILY "primary" (c1, c2, c3, c4, c5, c6, c7, c8)
)
````

The space is about the same in the past two days, and we are way past the 25h data retention period. The table has some load (records are created and deleted), but it is not in the magnitude of GBs.

How can we debug why the space is not reclaimed?

I have a much larger table in the TB range, where I've deleted ~10% of the records and it didn't reclaim the space either.

**Comment by andreimatei** [comment]
Peter do you know the right questions to ask here?

**Comment by tschottdorf** [comment]
Not a response, but we're tracking this kind of issue here: https://github.com/cockroachdb/cockroach/issues/29290

**Comment by andreimatei** [comment]
@isoos poking around it seems that we have quite poor control over the space reclamation process, because of the imperfect control we have over our on-disk storage library - RocksDB. This is something we really need to improve soon.
To see if indeed RocksDB is not compacting your data sufficiently, you can try to take down nodes one at a time and run `cockroach debug compact <store dir>` on each one. Seeing if that gives you space back will give us some info.

**Comment by isoos** [comment]
@andreimatei: The first part refers to the capacity usage reported on the landing page of the dashboard.  I've done compaction with two nodes, and by the time the second node synchronized, the third already reported lower space consumption. The `debug compact ...` command had very little output, and the change reported there was very small (less than 1%), but the overall space used did decrease.

However, the space used by the table didn't change too much, it is still much higher than I'd expect.

**Comment by tschottdorf** [comment]
@isoos could you post the output of `https://xxx:8080/_admin/v1/databases/yourdbname/tables/yourtablename/stats`? That will show me additional statistics about the table useful for tracking this down.

**Comment by isoos** [comment]
The table currently has ~23k rows. In the past few weeks the size decreased a lot, but I think it should take less space.

```
{
  "rangeCount": "486",
  "replicaCount": "1458",
  "nodeCount": "3",
  "stats": {
    "containsEstimates": false,
    "lastUpdateNanos": "1537286252123481797",
    "intentAge": "0",
    "gcBytesAge": "62031341756682",
    "liveBytes": "18572802",
    "liveCount": "69980",
    "keyBytes": "88586512",
    "keyCount": "634497",
    "valBytes": "373141176",
    "valCount": "3610419",
    "intentBytes": "0",
    "intentCount": "0",
    "sysBytes": "3088398",
    "sysCount": "14661"
  },
  "approximateDiskBytes": "464774728",
  "missingNodes": [
  ]
}
```

**Comment by tschottdorf** [comment]
Thanks @isoos and apologies for the delay getting back to you. This has the approximate disk usage for this table at 464mb. Logically, the information stored on disk is 88mb for keys (keyBytes) and 373mb for values (valBytes). There's often a discrepancy between the logical and actual on-disk information (due to write amplification, compression, etc), but here it seems to match up pretty well.

It also claims that there are 634k keys (keyCount) and a total of 3.5 million versions (including historical versions, valCount). On average, this would indicate that each key has ~5 versions.

You're using a single column family, so that each unique row in the table should correspond to a count of one in `keyCount`. Yet I assume a `COUNT(*)` gives you the ~23k and not ~634k. This raises the question of what churn you're seeing on this table. This could happen if during each ~24h window, you write and remove ~600k rows (I think that boils down to 7qps). Does that sound reasonable at all?

**Comment by isoos** [comment]
I'd say that ~600k rows turnaround over a week is realistic, but not over a day.

**Comment by tschottdorf** [comment]
Oh, in my math I forgot to take into account the replication factor, which I assume is three. This means we're talking about ~634k/3 ~ 210k SQL insert/update/delete ops churned through in 24h, ie more like 2-3 qps. I assume this puts us in the realm of what could be possible, especially taking into account that old versions aren't *immediately* purged when they become purgable (there's a background process taking care of it).

Also, the approximateDiskBytes indicates that your disk space is 464mb total, i.e. a third of that per node. (We're only talking about that one table).

Does that seem to check out?

**Comment by tschottdorf** [comment]
Folding this into #29290 but please let me know what you think of the above comment, @isoos!
