### ISSUE TITLE
ui: intent count stays above zero

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2952]
(seeing this in the UI, but since that doesn't do any counting itself, it's probably miscounted in general).

single node, splits are the only txns.

<img width="630" alt="screen shot 2015-10-29 at 4 23 10 pm" src="https://cloud.githubusercontent.com/assets/5076964/10831050/98e0af90-7e59-11e5-82b1-7d3689049443.png">

**Comment by tschottdorf** [comment]
(slight chance that there are actually intents which are never resolved. likely need to dig into this one a litte more).

**Comment by petermattis** [comment]
I just started a cluster (`cockroach start --dev`) with no load on it and the intent count starts at 21 and stays there. Is this a data collection issue or actual intents that are never resolved? If the latter, reassign to @tschottdorf.

**Comment by mrtracy** [comment]
This appears to be a collection issue on the bootstrap store: the intent count goes to zero if bootstrapping store is restarted.  Still investigating.

**Comment by mrtracy** [comment]
Incorrect analysis: This was actually an issue with splits.  If an EndTransactionRequest has a SplitTrigger, the normal incremental MVCC stats for the command are zeroed out, because the splitTrigger() method recomputes MVCC stats for both ranges.  However, the small difference between the original and recomputed stats was not being applied to the store metrics.

PR incoming for this.
