### ISSUE TITLE
sql: allow non-admin users to run import when they have database privileges

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#29605]
Import currently requires admin privileges.
It would be nice to allow users with appropriate privileges on the database to run import to populate tables within said database.

There are a few issues to think of:
- local storage use (security might be ok, but we don't have a way to restrict usage right now)
- cloud credentials use (eg: default credentials/cluster setting for GCS)
- actual privileges needed for the operation of import
- restriction to just one database and all privilege checks

CC: @kannanlakshmi, @nstewart for product categorization.
CC: @mjibson, @dt for additional details

**Comment by mjibson** [comment]
Other concerns:

- resource usage. IMPORT can take a lot of CPU for a long time.
- job management. we'll have to allow users who created a job to modify it.

**Comment by kannanlakshmi** [comment]
cc @rolandcrosby

**Comment by rolandcrosby** [comment]
I'll put this in our product backlog - it's definitely something we'll need to support - but at first glance it looks like there's a lot more underlying work that would have to happen in order for us to safely support this.

**Comment by rolandcrosby** [comment]
I recently discussed with @dt, @mjibson, and @kannanlakshmi whether it would make sense to require CREATE permission on a database in order to IMPORT a table into that database. The line of reasoning here is that a user who can create an empty table ought to be able to populate the table with data. Some of the non-obvious implications of this are listed above (ability to use default cluster permissions, ability to read anything specified under --external-io-dir). Other non-obvious things you're able to do if you can IMPORT include:

  - Any user with the ability to import data can cause the cluster to make HTTP requests against arbitrary URLs and store the results. (I've verified that you can basically get the full text of a page if you import as CSV and set a delimiter that doesn't exist in the input file -- try something like `import table foo (line text) csv data ('http://example.com') with delimiter = '£';`)
  - Any user with the ability to import data can negatively affect cluster performance in ways that we typically safeguard against for SQL statements.

To me these operations seem distinct from what you'd usually expect when granting someone permission to create a table; I'd be inclined to set up a new permission specific to importing data. What are your thoughts? Any suggestions on what we can do to enable this?

**Comment by mberhault** [comment]
We don't really safeguard much of anything when it comes to SQL statement execution. We try to limit memory, but that's about it. The bigger concern is non-SQL-statement impact of IMPORT.

I'm less concerned about resource utilization (local disk, ram, network, etc..) and more about access to restricted resources. The GCP credentials is definitely an issue, we would want to allow credentials separate from the cluster-wide ones.

**Comment by mwang1026** [comment]
Closing since we did this recently
