### ISSUE TITLE
ui: statements: Not clear how many execution attempts for a fingerprint failed

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#29676]
When viewing the statements page, it is impossible to tell if any of the execution attempts for a fingerprint resulted in failures. Further, when looking at the statement details page, it is still not possible to tell how many executions failed.

Executing `select 5/0` multiple times and `select 3/5` once yields the following:

![image](https://user-images.githubusercontent.com/21692034/45184295-8b2e3d00-b1f4-11e8-8950-0b6aeba6809e.png)

The statements page correctly shows the aggregated stats for the fingerprint, but there is no mention that 5 of the 6 attempts failed.

![image](https://user-images.githubusercontent.com/21692034/45184303-941f0e80-b1f4-11e8-9aff-6a30ac686e8a.png)

The statement details page similarly does not explicitly state the count of failures anywhere. The only indication is the "Failed?" field in the right rail, but the field only indicates that there are a non-0 number of failures and successes. Ideally, we would be able to see an exact count of the failures, separated out from the "First Attempts" count.

The "Failed?" field could also use a more descriptive message than what we show for mixed successful and failed statements:

![image](https://user-images.githubusercontent.com/21692034/45185659-fa0d9500-b1f8-11e8-9814-49cf2d5f1a94.png)

cc @Amruta-Ranade @couchand @josueeee 

Jira issue: CRDB-4852

**Comment by couchand** [comment]
From the point of view of the data we collect, all the data in the right-hand rail is on the same level (including `failed`).  They are various pieces of a multi-column key that, in addition to the fingerprint itself, form the most granular level at which we collect the `StatementStatistics`.  For the initial implementation we added special handling for `app`, since there was a clear known need to pivot on that value.  It makes sense that you'd also want to be able to pivot on `failed`.  I would propose that it also makes sense to pivot on `distSQL` and `opt` (for different purposes).

In the general case, it would be really nice to be able to filter the results on both the list and the details pages by all three of those key parts, in the way that you currently can with App.  But maybe the particular UI mechanisms will differ between them?

For the short term, I can see just updating the message in that right-hand rail.  "No" and "Yes" seem to be fine if there's consensus.  Maybe if both are represented we want to show the proportion that apply?  At first glance it seems like it might make sense to sum the `first_attempt_count` of all records for the denominator, and sum that metric for only records matching the specific sub-key for the numerator... for your example @piyush-singh that would show up as "Failed? 5/6".

It's all a little awkward since they are each potentially dimensions that are useful to know about.  Do only the distributed queries fail?  Do only the optimized queries fail?  Do only queries from particular apps fail?  Much more attention needs to be paid to the user stories we're trying to solve to design a more useful interface.  The current version is very much "here's the data, kaboom splat!"

**Comment by piyush-singh** [comment]
@couchand's update makes this much more clear on the statement details page, which suffices for 2.1. To Andrew's point we will revisit this in 2.2 as we evaluate use cases for the statements page more critically.
