### ISSUE TITLE
storage: "unable to find value for" error before crash

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#29826]
Adriatic nodes 5 and 6 crashed without stack traces, and also without dmesg saying anything about them being OOM killed. The only strange thing in the logs is this, a few seconds before the cockroach processes died:

```W180906 15:37:40.715628 243422132 storage/engine/mvcc.go:2223  [n6,s6,r13601/3:/Table/102/2/9/{5/10/…-6/10/…}] unable to find value for /Table/102/2/9/6/3/974014/0 @ 1536248258.158758783,1 (txn:<id:<f4811041-77ff-4206-9b3c-236dc5100d89> key:"\356\211\221\211\205\361#\243\210" epoch:3 timestamp:<wall_time:1536248256731354175 logical:2 > priority:907658 sequence:39 > timestamp:<wall_time:1536248256510673218 logical:1 > deleted:false key_bytes:12 val_bytes:5  vs {ID:9ce0833b-6950-4e08-b844-4ce920c6beaa Isolation:SERIALIZABLE Key:[238 137 145 137 133 241 35 199 136] Epoch:3 Timestamp:1536248258.158758783,1 Priority:832351 Sequence:193 DeprecatedBatchIndex:0})
W180906 15:37:40.716924 243422133 storage/engine/mvcc.go:2223  [n6,s6,r9183/6:/Table/102/2/9/{8/9/1…-9/8/6…}] unable to find value for /Table/102/2/9/9/3/973769/0 @ 1536248258.158758783,1 (txn:<id:<f4811041-77ff-4206-9b3c-236dc5100d89> key:"\356\211\221\211\205\361#\243\210" epoch:3 timestamp:<wall_time:1536248256731354175 logical:2 > priority:907658 sequence:48 > timestamp:<wall_time:1536248256510673218 logical:1 > deleted:false key_bytes:12 val_bytes:5  vs {ID:9ce0833b-6950-4e08-b844-4ce920c6beaa Isolation:SERIALIZABLE Key:[238 137 145 137 133 241 35 199 136] Epoch:3 Timestamp:1536248258.158758783,1 Priority:832351 Sequence:193 DeprecatedBatchIndex:0})
```

They were running the [`v2.1.0-beta.20180910` candidate](https://github.com/cockroachdb/cockroach/issues/29507#event-1825118126), b21f281ff6401c1517bbac328b3ae7e9e3bc803c.

The line that logged it is here: https://github.com/cockroachdb/cockroach/blob/b21f281ff6401c1517bbac328b3ae7e9e3bc803c/pkg/storage/engine/mvcc.go#L2222-L2224

More postmortem details here: https://docs.google.com/document/d/1mQma3IKXaCP_vXTLklDiDGW948rbOnaXH8OxYS8EUio/edit#

**Comment by tschottdorf** [comment]
Let's look at that message:

```
unable to find value for [...] @ 1536248258.158758783,1:

txn: f4811041-77ff-4206-9b3c-236dc5100d89>
timestamp:<wall_time:1536248256731354175 logical:2 > priority:907658 sequence:48 > timestamp:<wall_time:1536248256510673218 logical:1 > deleted:false key_bytes:12 val_bytes:5  vs {ID:9ce0833b-6950-4e08-b844-4ce920c6beaa Isolation:SERIALIZABLE Key:[238 137 145 137 133 241 35 199 136] Epoch:3 Timestamp:1536248258.158758783,1 Priority:832351 Sequence:193 DeprecatedBatchIndex:0})
```

Dissecting the first part, we see two timestamps:

- `1536248256.731354175.2`, the meta txn timestamp (name this T_Intent)
- `1536248256.510673218.1`, the meta record's timestamp (name this T_Meta)

The second one is smaller than the first, `T_Meta < T_Intent`. This can happen because a txn has an `OrigTimestamp` and a `Timestamp` and the latter can get pushed. Since txns always write at their `OrigTimestamp`, the `T_Meta` (which is essentially the `OrigTimestamp`) can trail `T_Intent` (which is `Timestamp`).

Now for the intent resolution, which comes from a different txn at timestamp `1536248258.158758783,1` (name this `T_Commit`, equal to the first timestamp in the "unable to find value for" message). Surprisingly, we have `T_Commit > T_Intent`.

So at first glance, this looks problematic: we try to commit an intent, but instead find some other transaction's intent at a lower timestamp. If we only tried to resolve intents at keys that are guaranteed to hold a committable intent, that'd be proof that things had gone awry.

But I think we're actually pretty liberal about sending these intent resolutions. For example,

- txn1 writes a, b, c (epoch 0)
- txn1 has to restart
- txn1 writes b, c (epoch 1); note it doesn't update a this time
- txn1 commits

will (I think) send intent resolutions to a, b, c. The difference is that on b, c they will result in a committed value, but at a it will actually remove the intent (since the epoch mismatches).

So this warning can be triggered when someone else removes the intent early. It still looks a bit concering that the other intent is at a lower timestamp, though, because you'd think that "writing under" a removed intent is something that would catch an error somewhere.

But I don't think it does: we don't populate the timestamp cache for blind writes (because we don't have to) or for intent resolutions (because we don't have to).

My TL;DR is that this seems kosher. And it's likely unrelated to the crashes, which may have been a rapid out-of-memory that wasn't even flushed to the logs (though I thought that the Go runtime wrapped things up properly when it fails to allocate, though I don't know that).

**Comment by vilterp** [comment]
Thanks for the investigation Tobi. As I wrote in the postmortem doc, there aren't any OOMs noted in the `dmesg` logs the day of the crash, although I'm not 100% sure one would be there. So yeah, if this is kosher, the mystery of why/how those nodes crashed seems to still be open `¯\_(ツ)_/¯`

**Comment by andreimatei** [comment]
At the very least the comment ` // This should never happen as ok is true above. ` has to be updated. And also that log message can be more informative.

**Comment by vilterp** [comment]
Ah interesting, thanks. Indeed strange that we didn't see a stack trace in the log like in the go-ethereum issue.

**Comment by tschottdorf** [comment]
This is odd indeed, but I'm pretty sure the warning is unrelated to the crash, so closing this.
