### ISSUE TITLE
doc: outdated Permissions information in design doc

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#2983]
In section [Permissions](https://github.com/cockroachdb/cockroach/blob/master/docs/design.md#permissions) of the design doc, `PermConfig` is mentioned. But  `PermConfig` doesn't exist in [config/config.proto](https://github.com/cockroachdb/cockroach/blob/master/config/config.proto).

**Comment by JackKrupansky** [comment]
Is Permissions being permanently removed, just temporarily, or is it morphed to something else?

I presume this was due to the existing design being purely at the KV level and not based on SQL.

Is there a separate design for SQL-level authorization at the row and column level? (I don't recall seeing it.)

Is there a design doc for SQL auth at the table level?

Thanks.

**Comment by knz** [comment]
Permissions are now handled at the SQL level. There are RFCs about this in docs/RFCS.

**Comment by yaojingguo** [comment]
@knz, are you taking about RFC [SQL privileges](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_privileges.md)?

**Comment by knz** [comment]
@yaojingguo yes that's what I'm talking about.
