### ISSUE TITLE
qa: Load-based rebalancing of leases and replicas

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30007]
Original issues:
https://github.com/cockroachdb/cockroach/issues/17979 for replicas
https://github.com/cockroachdb/cockroach/issues/21419 for leases

PRs:
https://github.com/cockroachdb/cockroach/pull/28340
https://github.com/cockroachdb/cockroach/pull/28852

Docs issue:
https://github.com/cockroachdb/docs/issues/2051

**Comment by vivekmenezes** [comment]
@vilterp you've been randomly assigned this issue. The goal here is to take this feature for a spin and find problems.

**Comment by vilterp** [comment]
Hey @a-robinson, looking at it today. It's taken me a bit to wrap my head around how this is different than the old stats-based rebalancing approach (seems the docs aren't written yet) but I'm getting a handle on it.

**Comment by a-robinson** [comment]
Thanks! Let me know if you want to chat at all about it.

**Comment by vilterp** [comment]
At this point I've just done the basics — ran the roachtests for this and observed various metrics while they were running, as well as looking at the unit test to understand how the allocator is making this decision.

I think we should chat about it though, since I still don't fully grok how this interacts with "follow the workload" (is that different than the prior "stats-based rebalancing")? I.e. if there are a lot of QPS coming from nodes in a certain locality, we want to move leases there, but we also want to balance leaseholders. These goals seem like they could be competing in some scenarios; a more thorough QA should probably explore that.

**Comment by vivekmenezes** [comment]
Is there any followup work remaining on this issue?

**Comment by vilterp** [comment]
I took it for a spin and things seemed to work as promised. Wasn't able to find the time to construct more complicated scenarios that would cause failure modes like thrashing, conflict between different rebalancing methods, etc. Would be good to do that testing to shake out any issues, but not sure who has the bandwidth.

**Comment by a-robinson** [comment]
Yeah, from my perspective this never really got the adversarial testing I was hoping for. Including it in the QA rotation would be ideal, although I understand if other QA issues come first.
