### ISSUE TITLE
remove custom RocksDB compaction filters

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3005]
Currently, we seem to be on track for using a custom RocksDB compactor for the removal of expired response cache and transaction table entries. Since these are part of the raft-replicated data, and since the compaction is not synchronized through a Raft command, we should make sure that these are only accessed through a mechanism that errors out well before the actual garbage collection might've taken place. Alternatively, we could reconsider our strategy, completely abandon the RocksDB compaction operator, and send the relevant keys to be gc'ed through raft-replicated `GCRequest`s (which already handle cleanup of user-space keys).

**Comment by bdarnell** [comment]
I prefer moving the GC from a compaction operator to a raft command because it's easier to ensure correctness that way and it's not clear that the performance benefits of using a compaction operator will matter that much. 

A couple of notes if we continue to use the compaction operator:
* Even if the actual GC doesn't happen in the raft command, the expiration timestamp should be updated with a raft command so it is synchronized across replicas.
* The consistency checker proposed in #837 will have to be aware of this; we'll probably also want to exclude GCable response cache entries from raft snapshots.

**Comment by spencerkimball** [comment]
If we go with your proposed txn-only response cache implementation, there will be almost no pressure on the GC from these entries. Given that, I think it's safe to abandon the custom compaction operator and rely on the normal range GC, which solves these identical replica state issues. It further eliminates a tricky dependence on RocksDB functionality which would be problematic if we want to swap in a different storage technology.

**Comment by tschottdorf** [comment]
Even better, the response cache GC can happen when the transaction entry is
GC'ed. So the only one left is Txn GC.

**Comment by petermattis** [comment]
What was the verdict here? The RocksDB compaction filter currently isn't being used. I'm happy to strip out the code.

**Comment by tschottdorf** [comment]
I think ripping it out is still the way to go.
