### ISSUE TITLE
ui: Decomissioning nodes listed as suspect while still running

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30095]
Repro steps: I created a large cluster, then decommissioned a handful of nodes.

While waiting for all replicas to be rebalanced off the decommissioning nodes, all the decommissioning nodes are marked as "Suspect" in the admin UI even though they're still running and capable of handling requests. After all replicas were rebalanced off of them, they were still just considered suspect until the cockroach processes had been shut off for 5 minutes.

It seems fine that the nodes are considered suspect after being shut off but before the 5 minute "time until store dead" setting, but it's weird that they're considered suspect by the UI while they're still running in a decommission(ing/ed) state.

<img width="1206" alt="screen shot 2018-09-11 at 2 42 53 pm" src="https://user-images.githubusercontent.com/7085343/45385238-dd48d700-b5d5-11e8-8139-f8ccdf5feadf.png">

**Comment by couchand** [comment]
Note that this determination dates to #22237, before which decommissioning nodes were simply counted as decommissioned as soon as decommissioning started.

Note that if you hover over the status icon for the node it is explicit that it's yellow due to decommissioning.

It makes sense to me that they're yellow rather than green, since they're no longer running in normal operation.  Even though they can still handle requests, they can't contribute to replication anymore, which I think is the main purpose of the high-level status in the overview.

cc @piyush-singh

**Comment by a-robinson** [comment]
I suppose it makes sense when thinking about the rationale now, but at the time I was confused by it.

> Even though they can still handle requests, they can't contribute to replication anymore, which I think is the main purpose of the high-level status in the overview.

They're in an intermediate state between live and suspect, in my opinion. When I see suspect nodes, my mind immediately worries that them being suspect means that ranges are underreplicated/unavailable as a result. Whereas decommissioning nodes don't accept new replicas but are perfectly well-functioning members of their existing ranges' quorums.
