### ISSUE TITLE
storage: snapshots transport require very high demands on the network

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#3013]
Now default range size is 64MB. If there is a snapshot transporting, it will occupy rpc channel for some time. Rpc and raft heartbeat will be blocked. 
Default raft heartbeat interval is 3s. This means that it must transfer 64MB or more snapshot data in the 3s, which the network requirements are very high. Otherwise raft will re-election. 
Especially for remote nodes, heartbeat timeout situation should be easy to happen.

**Comment by bdarnell** [comment]
Yeah, we're going to need to do something about this. We have several options. 

* The `etcd` team is looking at allowing snapshots to be spread across multiple `raftpb.Messages`. 
* Or we could do it at our own transport layer (`server/raft_transport.go`): detect `MsgSnap` and send it over multiple RPCs. A custom solution might be justified since we will likely want to implement preemptive snapshots, sending the snapshot before the configuration change starts instead of after it has been applied. 
* An even simpler transport-layer fix would be to make the key of `server.rpcTransport.queues` the pair (StoreID, IsSnapshot), so that snapshots don't compete with other traffic in the same queues. I think this will create multiple connections although I'm not sure that this works in our current RPC setup. If we move to GRPC the multiplexing would be better.

**Comment by tamird** [comment]
FWIW, I'm pretty sure our current RPC setup never creates multiple identical connections.

**Comment by YuleiXiao** [comment]
@bdarnell @tamird 
There is another problem. Not only network, apply snapshot and generate snapshot will block multiraft goroutine for a long time if range size is bigger. In my computer, it cost 11s to generate a 800M snapshot, this make followers re-election, too.

**Comment by bdarnell** [comment]
Preemptive snapshots would help with that too, since we could move snapshot generation off the main multiraft thread. Snapshots should also only be around 64M instead of 800M once we fix some issues with the response cache.

**Comment by tschottdorf** [comment]
cc @spencerkimball

**Comment by spencerkimball** [comment]
@tamird @bdarnell now that we have grpc in place, what's the plan here?

I'm seeing big latency spikes (5s!) and lots of copies of the data (protobuf and grpc seem to both make copies) when doing snapshots. This feels like a beta must-fix given the latency variance.

Is the plan to stream these in smallish bits directly from an iterator so we avoid any memory blowup?

**Comment by bdarnell** [comment]
The immediate plan is to move snapshots onto a separate grpc stream so we can take advantage of grpc's native multiplexing. That will get rid of the blocking on the network layer, and this part is definitely critical for beta. If problems persist the next step would be to move snapshot generation off the critical path as etcd has done. Actually streaming the snapshot without building the whole thing up in one blob is going to be tricky given the etcd/raft interfaces, although it would be possible.
