### ISSUE TITLE
sql/parser: put sqlSymType on a diet

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3018]
`sqlSymType` currently weighs in at 800 bytes. It is a union of all of the possible return values from various parser states. The size of this structure is problematic. The pointers add burden to the GC. The size itself contributes to slower allocations due to needing to clear the memory.

In C-based yaccs, the symtype structure is implemented via a `union` making it much smaller. We could do something similar in Go by replacing all of the fields in the struct with an interface with methods to retrieve the type specific data. This would be a mostly mechanical set of changes, but somewhat speculative as to whether it actually helps performance.

**Comment by nvanbenschoten** [comment]
I started hacking on this last night, and was pleasantly surprised by the results. As shown below from some preliminary benchmarking, reducing the size of `sqlSymType` from **800 bytes** down to **72 bytes** (which could get even smaller) by using a `union` (in a similar way to Go Protobuf unions) makes a substantial difference in parsing performance for any benchmark exhibiting a decently complex query. I'm currently in the process of putting together a PR to be reviewed, and should have a better idea of the performance implications soon. This change will admittedly make sql.y a little messier with the new layer of indirection for the `union`, but if these benchmarks are representative, the added code complexity is worth it for the performance improvement.

```
name                   old time/op  new time/op  delta
Bank_Cockroach-4        297µs ± 8%   235µs ± 4%  -21.07%   (p=0.000 n=10+9)
Select1_Cockroach-4    61.1µs ± 7%  58.4µs ± 4%   -4.51%  (p=0.019 n=10+10)
Insert1_Cockroach-4     534µs ± 1%   544µs ± 0%   +1.90%   (p=0.000 n=10+9)
Insert10_Cockroach-4    935µs ± 1%   946µs ± 1%   +1.18%   (p=0.000 n=9+10)
Insert100_Cockroach-4  4.83ms ± 2%  4.89ms ± 2%   +1.19%   (p=0.028 n=10+9)
Scan1_Cockroach-4       306µs ± 2%   307µs ± 2%     ~     (p=0.529 n=10+10)
Scan10_Cockroach-4      366µs ± 1%   367µs ± 1%     ~      (p=0.720 n=10+9)
Scan100_Cockroach-4    1.02ms ±56%  0.86ms ± 1%     ~      (p=0.400 n=10+9)
```

**Comment by petermattis** [comment]
Mind sending out a pointer to the branch you're working on? I'd be curious to take a look at the approach you've taken and the effect on `sql.y`. I'm not sure if those benchmarks are adequately representative. More focused parsing benchmarks would be useful to isolate the performance improvement. I'm very surprised with the level of improvement to the `Bank` benchmark.

**Comment by nvanbenschoten** [comment]
The current commit is [here](https://github.com/nvanbenschoten/cockroach/commit/9845b53f019c7eaf76ba906c0198a33a64470d8c). I wrote up a script to aid in automating the migration process of `sql.y`, so any changes we want should be pretty quick to make. For instance, I was able to play around with adding and subtracting fields from the union type, and found that the current configuration performs the best so far.

On that note, I ran the changes against the SQL parsing benchmark (which I intend to build out soon), and got some pretty nice results.

```
name     old time/op  new time/op  delta
Parse-4  47.6µs ± 8%  24.5µs ± 2%  -48.51%  (p=0.000 n=10+9)
```

**Comment by nvanbenschoten** [comment]
I was just able to improve the results further by adding the `IntVal` ival to the union type. This reduced the size of `sqlSymType ` down from **80 bytes** to **56 bytes** and gave another ~3% improvement. See [the latest commit](https://github.com/nvanbenschoten/cockroach/commit/dad1c7208de6cf375fc62797ae2a2449772ee011). At this point, I don't believe it makes sense to put anything else in the union interface, as all other fields are used at least partially for metadata.

```
name     old time/op  new time/op  delta
Parse-4  47.6µs ± 8%  22.9µs ± 3%  -51.99%  (p=0.000 n=10+10)
```

**Comment by nvanbenschoten** [comment]
And here's memory. It makes sense that the benchmarks are allocating a greater number of times while parsing because of the new layers of indirection in the parse tree, but that they are showing memory footprints around a third to a quarter of their previous size because of the reduced amount of wasted space in `sqlSymType`.

```
name              old time/op    new time/op    delta
Bank_Cockroach-4     291µs ± 5%     224µs ± 5%  -22.95%  (p=0.000 n=10+10)
Parse-4             44.0µs ± 1%    22.9µs ± 2%  -48.03%   (p=0.000 n=9+10)

name              old alloc/op   new alloc/op   delta
Bank_Cockroach-4    81.7kB ± 1%    32.6kB ± 1%  -60.14%  (p=0.000 n=10+10)
Parse-4             20.5kB ± 0%     5.3kB ± 0%  -74.05%  (p=0.000 n=10+10)

name              old allocs/op  new allocs/op  delta
Bank_Cockroach-4       676 ± 1%       737 ± 1%   +9.04%  (p=0.000 n=10+10)
Parse-4               79.0 ± 0%     135.0 ± 0%  +70.89%  (p=0.000 n=10+10)
```

**Comment by petermattis** [comment]
Nice. Usually reducing allocations improves performance, but that's only part of the story. GC overhead is also proportional to the amount of data that needs to be scanned and `sqlSymType` was previously very large and contained a lot of pointers. Let me take a look at how ugly this made `sql.y`.

**Comment by nvanbenschoten** [comment]
If we do determine that this change has made `sql.y` too ugly to justify, alternatives might be to add a preprocessing step from non-unionized `sql.y` to unionized `sql.y` (basically the script I already wrote, which is far from reliable), add support for unions directly into our fork of the yacc compiler, or add a post-processing step from non-unionized `sql.go` to unionized `sql.go` (I also already wrote this one when prototyping the change to get the initial benchmark results). From experience playing around with this so far, I can say that if we wanted to do one of the source code rewriting approaches (1 or 3), rewriting the `.go` file is much simpler than rewriting the `.y` file as it doesn't require understanding the global state of %token and %type declarations at all times, but instead can work only at the local level during variable assignment. The post-processing would also have the added benefit of not risking touching invalid input files. We could make any of these work off of a `` `union` `` struct tag in the sql.y's union structure to allow for configuration. None of these alternatives are great though, because they all end up reducing the transparency of the grammar to parser compilation.

**Comment by petermattis** [comment]
`sql.go` is already opaque and unreadable in comparison to `sql.y`. If you can hide all of the union stuff within automatic edits to `sql.go` then that sounds good. How much work is that going to be? I'm mildly worried about introducing magic, though. Can you can bundle up your change so far into a PR so we can all see what the `sql.y` changes look like?

I believe our fork of the yacc compiler can go away in go1.6 as all of our local changes have been pushed upstream.

**Comment by nvanbenschoten** [comment]
Ok, I just opened a [PR](https://github.com/cockroachdb/cockroach/pull/4216), so you can check out what the `sql.y` changes look like. 

In terms of the automated editing tool, I currently have a version from `sql.go` -> unionized `sql.go` that is less than 200 lines of Go code. However, I don't think it currently makes all necessary changes, so it might take a few hours to clean it up and make it work without the need for any manual changes.
