### ISSUE TITLE
storage: uncertainty error with same physical component of the timestamp - can it be avoided?

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#30234]
A client ran into this:
```
pq: restart transaction: HandledRetryableTxnError: ReadWithinUncertaintyIntervalError: read at time 1536930304.161793970,0 encountered previous write with future timestamp 1536930304.161793970,1 within uncertainty interval `t <= 1536930304.164421489,0`; observed timestamps: [{1 1536930304.161793970,0} {2 1536930304.164421489,0}]
```

Note that only the logical component of the timestamp differs. I think this suggests a dance where first txn2 ran into txn1's read and restarted at a bumped timestamp, then managed to commit, then txn1 that’s still running runs into txn2's write. 

I think maybe there is something that we could do to avoid a restart here (because I think we can deduce the fat that txn1 can be ordered before txn2)?

cc @tschottdorf @bdarnell @nvanbenschoten

**Comment by nvanbenschoten** [comment]
That's an interesting question and your interpretation of what's going on all adds up. I think maybe if we used something closer to a vector clock we could encode these dependencies directly inside of timestamps. Outside of that, I don't see a great way of doing so.

Perhaps we should be pushing transactions by a minimum of `MaxOffset` instead of by one logical tick when they restart. That would also avoid this issue. It's probably not worth doing though, as it would have other consequences.

**Comment by nvanbenschoten** [comment]
Actually, a transaction's `ObservedTimestamps` are similar to what I was meaning with the vector clock. I think if we wrote values with their corresponding `ObservedTimestamps` we could avoid uncertainty restarts like this.

**Comment by andreimatei** [comment]
Yeah, that's the sort of thing I had in mind, but I need to think through this some more.

> Perhaps we should be pushing transactions by a minimum of MaxOffset instead of by one logical tick when they restart. That would also avoid this issue. It's probably not worth doing though, as it would have other consequences.

Well we can't simply push by that amount and allow the txn to restart immediately (cause that would be "injecting" a bogus timestamp). If we push by `MaxOffset`, then the pushed txn has to wait a bit before it restarts. In practice, when restarting, a txn takes the max of the pushed ts and the current ts on the gateway (and the latter should generally be higher, except when the gateway's clock is behind I guess).

**Comment by tschottdorf** [comment]
We already push transactions to `clock.Now()` regardless of the pushee's timestamp (unless that has changed when I didn't look). I don't think anything about ObservedTimestamps can avoid them (that timestamp is just the wall clock of the node when the txn first touched it, but isn't even connected to the txn timestamp except for the guarantee that it was larger during the first epoch). To avoid uncertainty restarts, you need to prove that the offending write isn't committed. You can go check the txn record, and if that comes back as PENDING, you know that the error can be elided. (I'm operating under the assumption that the uncertainty interval error is really only there to get us linearizability on a single key, i.e. read-what-you-wrote).

Another way to get that would be to plumb a client ID all the way through. Then you don't emit errors when the client IDs mismatch. But that kind of plumbing is invasive and there's no canonical SQL client ID.

**Comment by andreimatei** [comment]
Tobi, I'm trying but I'm having a hard time parsing the points in your last comment. I think there might be some misunderstanding too, as you seem to be talking about intents whereas I was just talking about committed txns.

> We already push transactions to clock.Now() regardless of the pushee's timestamp

By "pushee's timestamp" you mean the timestamp from the ts cache?
Btw, I don't know if this contradicts what you're saying here, but I just found out (and it came as a surprise to me) that, upon txn restart, we do *not*  push a txn's timestamp to `clock.Now()` (for neither clock - not the one where the ts cache bump happens, nor the gateway). I though we always did that, but turns out that we only do it for `TransactionAbortedError`, not for other restart.
https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/data.go#L1130

***
Anyway, I'd like to restart the conversation with a simpler and perhaps more convincing scenario that I was just discussing with @nvanbenschoten :

- gateway A creates two transactions, in succession: txnSlow (ts:5) and then txnFast (ts:10).
- txnFast writes a value on node B (and possibly also commits; we'll discuss the commit vs not committed cases separately)
- txnSlow goes to node B to read that value. The value (either a committed value or an intent) appears to be in the uncertainty interval (txnSlow has no `observedTimestamp` for node B at this point) and causes txnSlow to restart (after first waiting for txnSlow to commit if the value was an intent)

This scenario is accurate, right? And it also seems silly - txnSlow should clearly be ordered before txnFast as they came from the same gateway, so there shouldn't have been any uncertainty.

So what can be done about it? To avoid the uncertainty, the intent/value in question would need to carry some information allowing txnSlow to deduce that it has been written by a "future" txn. A natural example of such information would be a list (say, `pastTimestamps`) of <NodeID, timestamp> representing timestamps known to be in the writer's past. This would be more or less the opposite of a txn's `ObservedTimestamps` collection (which has information about timestamp known to be in our future). The definition of a value/intent `v` having a `pastTimestamp <n, ts>` would be that timestamps less than `ts` taken from `n`'s clock are known to be in the value's past. In other words, if a txn comes along with a `timestamp <= ts` and that timestamp came from `n`'s clock, the value/intent can safely be ignored (it would not be uncertain).

I'm not sure about all the information that could be included in `pastTimestamps`, but one item that can definitely be in there can represent a txn's <gateway id, `OrigTimestamp`>. So, in our scenario above, the intent/value could carry `pastTimestamps: <A, 10>` and `txnSlow` could carry the information that it's `OrigTimestamp` 5 was taken from `A`'s clock, and that would allow us to eliminate the uncertainty.
When a txn restarts, we'd have to keep track of what node's clock the restart timestamp came from. I'm not sure yet about when this information is trackable (e.g. if a txn is bumped by a ts cache, in which info some information can be tracked there).
Does all this sound sane?

**Comment by tschottdorf** [comment]
> Tobi, I'm trying but I'm having a hard time parsing the points in your last comment.

Oh, you're right. What I was trying to say is: when a txn pushes another txn, it pushes it to the clocks current timestamp (not "just above itself"). But when you restart because of the timestamp cache, it's a different story. Moving all the way to a current timestamp could be a good idea (since the txn is writing). For read-only txns, it can pay off to stay where you were so that you populate the timestamp cache less aggressively.

> This scenario is accurate, right? And it also seems silly 

Yes, in this case what I wrote above ("you need to prove that the offending write isn't committed") becomes much easier because we can assume that the gateway assigns incremental timestamps to back-to-back transactions. So if from an intent or value you can deduce the gateway node, you can reason about the required ordering (with a bit of care applied to txns which had their timestamp pushed, etc).
Also, some of this would be "free" when running into an intent if we assigned txn ids that encode the coordinator ID (as once suggested in the context of parallel commits).

I suspect embedding anything into values (or perhaps even intents) is a non-starter because it's a pessimization for the case in which there isn't contention. On the other hands, the uncertainty restarts are a bit of a wart. Are they ever useful except when single-register linearizability would otherwise be violated? A concept of client state (i.e. some automatic linearizability token) would solve this problem for us, but with load balancers etc in the mix, we can never quite fingerprint the clients.

**Comment by tschottdorf** [comment]
> As you say just above, using a static txn id for this only works "with a bit of care applied to txns which had their timestamp pushed", but I don't see how we'd deliver this "bit of care".

It's all a bit messy. The thing (well, one thing) you want to avoid is starting txnSlow which then gets pushed and commits, and then you (=the client) start txnHigh which ends up having a timestamp below the previous commit timestamp but gets to not see the previous writes due to the magic (which relies on the pre-push timestamp). If the gateway made sure to update the HLC with the provisional commit timestamp before the commit is carried out, that couldn't happen. And I think what you want is ObservedTimestamps? That's the lowest timestamp we ever observed from each node. For example, txnSlow in your example observes 5, txnFast observes 10. If you stored that, txnSlow sees the 10 of txnFast's write and knows that txnFast visited the node first at 10, whereas you did at 5, and since you're still running, the other one isn't something you ran earlier.

> Well, I'd argue that even holding on to timestamps is a pessimization in the case when there's no contention. So what's a few more bits for a node id?

Not sure what you mean. Holding on to timestamps is one thing, writing them to stable storage (multiple times) is another. Single-node databases do this sort of analysis because they can view everyone's read/write sets and can make computations based on that. I think trying to jam stuff through disk to replace that is something we should avoid.

> I also think that the point of these restarts is single-register linearizability. What you call "read-what-you-wrote", I call "no stale reads". I tend to like it... Bob in accounting should be able to yell to Lisa in compliance "I've inserted the TPS reports" at which point Lisa should be able to go read them, without a token. Plus, holding my head high and saying "no stale reads" lets me end many discussions with clients over our isolation model without having to go deeper (cause if you go deeper, it gets really confusing).

You're not going to get an argument from me that we should be dropping this guarantee. I was asking this question because I want to make sure that this isn't important for anything else.

There's also another way out, which is really to implement causality tokens and let them disable the whole uncertainty thing. For example, if we had a custom CRDB client driver (or code that does this manually), it could run transactions like this:

```
BEGIN TRANSACTION TOKEN 124125125.1123
```

or perhaps (to make it easier to do this via ORMs)
```
BEGIN;
CAUSALITY TOKEN 124124124124.124124
```

where that timestamp is the last successful commit timestamp by the client. We could then initialize the MaxTimestamp using this timestamp which mostly means that there's no uncertainty (unless nodes are actually offset and transactions are short).

Btw, the (most?) general problem to solve here is that in which contending clients (doing a read of everything except their own key and then a write of their own key in a loop) are heavily load balanced, that is, each transaction hits a different coordinator (and they're offset). In that scenario, you never *have* to see uncertainty restarts (no client reads their writes back, so you never catch a stale read), but in reality you'll see many of them. At that point, without tracking the key ranges, there's little hope.

Practically, we expect clients to hit the same (or a small number of) gateways repeatedly, and so an optimization that avoids these errors most of the time in that case does make sense to me.

The question is then, is what you're suggesting worth the complexity and overhead compared to the simple (but manual) solution that pushes the problem into the clients? That's not something there's a simple answer for, but what I like about the client-side solution is that a) it's basically free and b) it also allows clients to specify a token that just disables uncertainty retries (similar to AS OF SYSTEM TIME, but you get to run a writing transaction, too). The downside, of course, is that clients have to "do stuff" to get the benefit. That's a large downside.
