### ISSUE TITLE
sql: explicit index added by ORM after FK creates redundant index with the FK's _auto_ index

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#30402]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

In a single transaction I create some tables with foreign keys and primary keys between them. When I `show indexes` I find that redundant `_auto_` indexes were created.

- Which version of CockroachDB are you using?

v2.0.5

- What did you do?

```
$ docker run -d --net=host -ti cockroachdb/cockroach:v2.0.5 start --insecure
$ cat schema.sql 
BEGIN;
CREATE TABLE users (
	id SERIAL NOT NULL,
	uid VARCHAR,
	passwordhash VARCHAR,
	description VARCHAR,
	is_remote BOOLEAN,
	PRIMARY KEY (id),
	UNIQUE (uid)
);
CREATE TABLE groups (
	id SERIAL NOT NULL,
	gid VARCHAR,
	description VARCHAR,
	PRIMARY KEY (id),
	UNIQUE (gid)
);
CREATE TABLE user_groups (
	user_id INTEGER NOT NULL,
	group_id INTEGER NOT NULL,
	PRIMARY KEY (user_id, group_id),
	UNIQUE (user_id, group_id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	FOREIGN KEY(group_id) REFERENCES groups (id)
);
CREATE INDEX user_groups_user_id_asc ON user_groups (user_id ASC);
CREATE INDEX user_groups_group_id_asc ON user_groups (group_id ASC);
COMMIT;
$ docker run --net=host -ti cockroachdb/cockroach:v2.0.5 sql --insecure -e 'create database if not exists test;'
$ docker run -ti --net=host -ti cockroachdb/cockroach:v2.0.5 sql --insecure --database=test -e "$(cat schema.sql)"
COMMIT
$ docker run --net=host -ti cockroachdb/cockroach:v2.0.5 sql --insecure --database=test -e 'show indexes from user_groups'
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
|    Table    |                     Name                      | Unique | Seq |  Column  | Direction | Storing | Implicit |
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
| user_groups | primary                                       |  true  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | primary                                       |  true  |   2 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_group_id_key              |  true  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_group_id_key              |  true  |   2 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_auto_index_fk_group_id_ref_groups | false  |   1 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_auto_index_fk_group_id_ref_groups | false  |   2 | user_id  | ASC       |  false  |   true   |
| user_groups | user_groups_user_id_asc                       | false  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_asc                       | false  |   2 | group_id | ASC       |  false  |   true   |
| user_groups | user_groups_group_id_asc                      | false  |   1 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_group_id_asc                      | false  |   2 | user_id  | ASC       |  false  |   true   |
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
(10 rows)
```

- What did you expect to see?

As the `_auto_` indexes are covered by indexes that are explicitly created in the same transaction I expect to see only indexes for the primary keys and my explicitly created indexes:
```
$ docker run --net=host -ti cockroachdb/cockroach:v2.0.5 sql --insecure --database=test -e 'show indexes from user_groups'
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
|    Table    |                     Name                      | Unique | Seq |  Column  | Direction | Storing | Implicit |
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
| user_groups | primary                                       |  true  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | primary                                       |  true  |   2 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_group_id_key              |  true  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_group_id_key              |  true  |   2 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_asc                       | false  |   1 | user_id  | ASC       |  false  |  false   |
| user_groups | user_groups_user_id_asc                       | false  |   2 | group_id | ASC       |  false  |   true   |
| user_groups | user_groups_group_id_asc                      | false  |   1 | group_id | ASC       |  false  |  false   |
| user_groups | user_groups_group_id_asc                      | false  |   2 | user_id  | ASC       |  false  |   true   |
+-------------+-----------------------------------------------+--------+-----+----------+-----------+---------+----------+
(8 rows)
```

- What was the impact?

When I use python's alembic package to generate migrations from my schema it gets confused because it reflects the existing indexes from the database, finds indexes it does not expect, and tries to remove them.

In case it is of some interest, here is the sqlalchemy schema I used to generate the schema.sql:
```
user_groups = sa.Table(
    'user_groups',
    DeclarativeBase.metadata,
    sa.Column('user_id', sa.ForeignKey('users.id'), primary_key=True),
    sa.Column('group_id', sa.ForeignKey('groups.id'), primary_key=True),
    UniqueConstraint(sa.Column('user_id'), sa.Column('group_id')),
    Index(
        'user_groups_group_id_asc',
        sa.Column(name='group_id').asc(),
        ),
    Index(
        'user_groups_user_id_asc',
        sa.Column(name='user_id').asc(),
        ),
    )

class User(DeclarativeBase):
    __tablename__ = 'users'

    id = sa.Column(sa.Integer, primary_key=True)
    uid = sa.Column(sa.Unicode, unique=True)
    passwordhash = sa.Column(sa.Unicode)
    description = sa.Column(sa.Unicode)
    is_remote = sa.Column(sa.Boolean)
    groups = relationship(
        'Group',
        secondary=user_groups,
        back_populates='users',
        collection_class=set)

class Group(DeclarativeBase):
    __tablename__ = 'groups'

    id = sa.Column(sa.Integer, primary_key=True)
    gid = sa.Column(sa.Unicode, unique=True)
    description = sa.Column(sa.Unicode)
    users = relationship(
        'User',
        secondary=user_groups,
        back_populates='groups',
        collection_class=set
        )
```

This looks related to 
https://github.com/cockroachdb/cockroach/pull/25362
https://github.com/cockroachdb/cockroach/issues/25663
https://github.com/cockroachdb/cockroach/pull/25786

Jira issue: CRDB-4833

**Comment by dt** [comment]
Huh, interesting.

So there are sort of two separate problems here:
  1) the ORM doesn't like indexes it didn't make
  2) the ORM makes the index we need after we needed its we made our own first.

I'll get back to 1) in a second.

The `CREATE TABLE user_groups` statement has be evaluated with the schema definitions it has to decide what table it is going to create so that subsequent statements can then use that table.
The FKs in the `CREATE TABLE` definition require an index and since there isn't one (at the time we evaluate the `CREATE TABLE`), it adds one. Being in a txn doesn't really change that, since we still need to make a table for later statements to use.

The explicit addition of a duplicate index later (in the same txn or not) doesn't really change what the  `CREATE TABLE` does. I'm actually slightly surprised it doesn't fail since it is duplicative.

Ideally the explicit `INDEX` would just be included in the `CREATE TABLE` rather than being sent afterwards -- then the FK would just find and use it. Alternatively, the FK could be added after the explicit index, where again it'd be able to find and use it. Both of these however would seem to require ORM changes.

_Maybe_ we could just ignore the ORM's explicit `CREATE INDEX`, transforming it to a rename of our matching existing, automatically generated index, so that it would appear to have just worked? I dunno, I'm usually not a fan of spooky magic things like a `CREATE INDEX` silently becoming a `RENAME INDEX`  but these are the kinds of things we do in the name of existing ORM combat.

That, however, only works when the ORM actually did try to create a matching index -- if the user-defined schema *didn'*t include a supporting index, we'd still need to make an automatic one and we'd still have issue 1) -- the fact that the ORM doesn't like seeing indexes it didn't make.

**Comment by dt** [comment]
@gpaul as a workaround, is there any way you can convince the ORM to include your index in the CREATE TABLE instead of sending it later? if not, can you convince it to add the FK after it adds the index you want it to use for the FK?

**Comment by gpaul** [comment]
I believe so - I'll report back after I try a couple of things.

**Comment by gpaul** [comment]
I tried the following, which looked promising but also fails:


```
$ cat schema-2.sql
BEGIN;
CREATE TABLE users (
	id SERIAL NOT NULL,
	uid VARCHAR,
	passwordhash VARCHAR,
	description VARCHAR,
	is_remote BOOLEAN,
	PRIMARY KEY (id),
	UNIQUE (uid)
);
CREATE TABLE groups (
	id SERIAL NOT NULL,
	gid VARCHAR,
	description VARCHAR,
	PRIMARY KEY (id),
	UNIQUE (gid)
);
CREATE TABLE user_groups (
	user_id INTEGER NOT NULL,
	group_id INTEGER NOT NULL,
	PRIMARY KEY (user_id, group_id),
	UNIQUE (user_id, group_id)
);
CREATE INDEX user_groups_user_id_asc ON user_groups (user_id ASC);
CREATE INDEX user_groups_group_id_asc ON user_groups (group_id ASC);
ALTER TABLE user_groups ADD FOREIGN KEY(user_id) REFERENCES users (id);
ALTER TABLE user_groups ADD FOREIGN KEY(group_id) REFERENCES groups (id);
COMMIT;
$ docker run -ti --net=host -ti cockroachdb/cockroach:v2.0.5 sql --insecure --database=test -e "$(cat schema-2.sql)"
Error: pq: foreign key requires an existing index on columns ("group_id")
```

**Comment by knz** [comment]
The new issue you encounter is because the CREATE INDEX is deferred to the end of the transaction, so by the time ALTER TABLE ADD FK runs it doesn't "see" the new index (which hasn't really been created yet).

The fact that schema changes are "coarsely" asynchronous in that way is a known serious limitation which we are working hard to lift ASAP, but you'll have  to work around it in 2.0. 

There are two ways to do this:

1) either run these statements outside of a BEGIN...COMMIT block, or

2) make the INDEX clauses part of the CREATE TABLE statement as suggested by david above. In that way the indexes are available immediately for the FK definition to pick up.

To answer David's earlier comments/concerns

> The explicit addition of a duplicate index later (in the same txn or not) doesn't really change what the CREATE TABLE does. I'm actually slightly surprised it doesn't fail since it is duplicative.

CockroachDB supports multiple redundant index definitions. We have discussed this before and concluded there's not much we can do because postgres accepts this too.

> the ORM doesn't like indexes it didn't make

The introspection facilities in 2.0 were broken. It's possible that SQLAlchemy is equipped to do something adequate but fails to find the information it needs (e.g. the proper index definitions) in pg_catalog.  We've largely fixed that in 2.1.

Also, @gpaul please make sure you're using the latest SQLAlchemy code we have published last month, it contains several bug fixes and cross-compatibility with crdb 2.1.

> Maybe we could just ignore the ORM's explicit CREATE INDEX, transforming it to a rename of our matching existing, automatically generated index, so that it would appear to have just worked? I dunno, I'm usually not a fan of spooky magic things like a CREATE INDEX silently becoming a RENAME INDEX but these are the kinds of things we do in the name of existing ORM compat.

I'm not a fan of this either, mainly because of the other point:

> That, however, only works when the ORM actually did try to create a matching index -- if the user-defined schema *didn'*t include a supporting index, we'd still need to make an automatic one and we'd still have issue 1) -- the fact that the ORM doesn't like seeing indexes it didn't make.

this, and also this may be an introspection issue (see my point above). If introspection fixes in 2.1 are sufficient to solve this issue, I'd rather not add more "automagic" behavior elsewhere.

**Comment by knz** [comment]
@jordanlewis @mjibson I think we may have resolved this in Q4 2018 by fixing a couple of introspection tables. A good "next step" would be to re-try the use case to see if the problem persists.

**Comment by lucy-zhang** [comment]
I think any problems related to auto-creating indexes should no longer be applicable once we stop auto-creating indexes for FKs in 20.2. There's also some problem with the ORM and the introspection tables, which I think is an issue for Features, so I'm reassigning it.
