### ISSUE TITLE
lease acquisition uses non-idempotent txn closure, probably breaking OSC

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3050]
apply this diff:

```diff
diff --git a/server/testserver.go b/server/testserver.go
index 2fad316..5e7f5ea 100644
--- a/server/testserver.go
+++ b/server/testserver.go
@@ -18,6 +18,8 @@
 package server

 import (
+       "time"
+
        "github.com/cockroachdb/cockroach/client"
        "github.com/cockroachdb/cockroach/config"
        "github.com/cockroachdb/cockroach/gossip"
@@ -62,7 +64,7 @@ func NewTestContext() *Context {
        // MaxOffset is the maximum offset for clocks in the cluster.
        // This is mostly irrelevant except when testing reads within
        // uncertainty intervals.
-       ctx.MaxOffset = 0
+       ctx.MaxOffset = 50 * time.Millisecond

        // Load test certs. In addition, the tests requiring certs
        // need to call security.SetReadFileFn(securitytest.Asset)
```

It leads to some transaction restarts (which would also happen in production).
Then,

```
--- FAIL: TestLeaseManager (0.03s)
        lease_test.go:90: expected /1/1, but found
--- FAIL: TestLeaseManagerReacquire (0.02s)
        lease_test.go:253: expected refcount of 2, but found 3
```

The issue is that `(*LeaseManager).Acquire` takes a transaction, but changes its internal state according to operations carried out within that transaction without ascertaining that the transaction actually commits (which, of course, it may not).

The resulting state looks quite inconsistent, with refcount overcounting being on the harmless side. In the first test failure, it appears that the node thinks it has a lease while nothing's been persisted to the lease table, breaking online schema changes.

**Comment by petermattis** [comment]
Ugh. Yeah, that's broken. We need to use the client's transaction to read the table descriptor during lease acquisition in order to avoid problems with insert into a table occurring in the same transaction as table creation. But it seems like [insertion into the lease table](https://github.com/cockroachdb/cockroach/blob/master/sql/lease.go#L122-L132) should happen outside of the client's transaction. Does that sound kosher? If the client's transaction aborts, the lease will still be present but the table creation would be rolled-back, but that doesn't seem problematic as the lease will never be used.
