### ISSUE TITLE
roachtest: Duplicate issue posts

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#30541]
I've noticed a few duplicate issues created by roachtest recently. They're correctly posted as comments on the original issue, but the same test name and build id are getting posted multiple times (for example, build 919791 is posted three times in #30525)

**Comment by petermattis** [comment]
I recently changed the parent test to fail if any of the subtests failed. Seems like that is possibly related because we have 3 levels in the jepsen tests (`jepsen/<N>`, `<group>` and `<nemesis>`).

Cc @tschottdorf and @benesch in case you have other thoughts as you've both played around with the issue posting code that roachtest uses.

**Comment by tschottdorf** [comment]
I think you're right that the first failure is the subsubtest, the next failure is the subtest (but it posts only a comment that doesn't make this obvious, and the search for the issue title is not exact so it doesn't create its own new one), and one more layer of that.

**Comment by petermattis** [comment]
Should be easy to not post an issue failure from a test which has subtests. `roachtest` provides a strict separation there which makes this more feasible than `go test`.
