### ISSUE TITLE
Track PCF usage

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#30837]
We don't have a way to track if anyone is using PCF to connect to a CockroachDB cluster. We should track this by setting up some sort of env channel var for PCF.

**Comment by a-robinson** [comment]
Note that this differs quite a bit from anything we've done before because we don't have a configuration for cockroach to run in PCF but merely for clients in PCF to connect to cockroach running elsewhere. We have a channel env var for where cockroach is running, but not for where clients are connecting from.

**Comment by kannanlakshmi** [comment]
Yes, understood and that makes sense. Its not a priority at the moment, just adding it to the backlog, so we don't forget about it.

**Comment by kannanlakshmi** [comment]
Closing this as I can track downloads of our PCF tile from the Pivotal Marketplace settings tab. That should suffice for now.
