### ISSUE TITLE
sql: Timestamp math is inconsistent with PostgreSQL

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#30976]
Here it fails to work with days:

```sql
select i::date from generate_series('2012-06-29'::timestamp, '2012-07-03'::timestamp, '1 day'::interval) i;
pq: step cannot be 0
```

Here's it working with seconds:

```sql
select i::date from generate_series('2012-06-29'::timestamp, '2012-07-03'::timestamp, '86400 seconds'::interval) i;
              i
+---------------------------+
  2012-06-29 00:00:00+00:00
  2012-06-30 00:00:00+00:00
  2012-07-01 00:00:00+00:00
  2012-07-02 00:00:00+00:00
  2012-07-03 00:00:00+00:00
(5 rows)

Time: 485µs
```

There are also no tests for this flavour of generate_series that I was able to find.

**Comment by bobvawter** [comment]
The problem here is that `makeTSSeriesGenerator()` only ever looks at the nanosecond component of the step duration: https://github.com/cockroachdb/cockroach/blob/f4e4789ed4bdd77ab6c30149a66deccefd83b25e/pkg/sql/sem/builtins/generator_builtins.go#L345

In order to meaningfully support the months part of the step duration, we need to perform calendrical math.

I've done some investigation of how PostgreSQL handles `generate_series()` when it comes to corner-cases and how this differs from go's `time.Time.AddDate()` and its normalization strategy.  Postgres advances by the largest time unit and in cases where it would select a date that extends beyond the end of the month, the last day of the month is chosen.  This truncated day is then used as the basis for producing the next element in the series `next = truncate(next + largest_step_unit)`.  Then the next-smallest unit of time in the step is evaluated until done.

Here's some output from pgsql:

```
bob=# SELECT * FROM generate_series('2015-01-29 22:00:00'::TIMESTAMP, '2017-05-31 00:00:00'::TIMESTAMP, '1 year 1 month 1 day ');
   generate_series   
---------------------
 2015-01-29 22:00:00
 2016-03-01 22:00:00
 2017-04-02 22:00:00
(3 rows)

bob=# SELECT * FROM generate_series('2015-01-29 22:00:00'::TIMESTAMP, '2017-05-31 00:00:00'::TIMESTAMP, '2 year 2 month 2 day ');
   generate_series   
---------------------
 2015-01-29 22:00:00
 2017-03-31 22:00:00
(2 rows)

bob=# SELECT * FROM generate_series('2014-01-29 23:00:00'::TIMESTAMP, '2017-05-31 00:00:00'::TIMESTAMP, '1 year 1 hour');
   generate_series   
---------------------
 2014-01-29 23:00:00
 2015-01-30 00:00:00
 2016-01-30 01:00:00
 2017-01-30 02:00:00
(4 rows)
```

My plan is to rework `seriesTSNext()` in `generator_builtins.go` to do our own calendar math so that we can maximize compatibility with PostgreSQL and add a bunch of logictests to cross-check against observed pgsql output.

**Comment by bobvawter** [comment]
Per offline conversation with @knz, it looks like all of our date math is a bit off.  Consider the following:

PG
```
bob=# select '1996-02-29 22:00:00'::TIMESTAMP + '1 year';
      ?column?       
---------------------
 1997-02-28 22:00:00
```

CRDB
```
root@127.0.0.1:55065/defaultdb> select '1996-02-29 22:00:00'::TIMESTAMP + '1 year';
          ?column?           
+---------------------------+
  1997-03-01 22:00:00+00:00
```

Will look into aligning the behavior of operators with pgsql.

**Comment by chessman** [comment]
@knz Hello. I still can reproduce it with cockroach 2.1.4. Has it been ported to 2.1?
```
SELECT * FROM generate_series('2017-11-11 03:00:00'::TIMESTAMP, '2017-11-15 00:00:00'::TIMESTAMP, '1 day');
pq: step cannot be 0
```
