### ISSUE TITLE
sql: review all known hibernate failures

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#30975]
Based on what we saw in #30877, it is now worthwhile to spend the time to investigate all of the known Hibernate test failures and categorize them.

There are only 311 current failures, so this work can be broken up amongst the SQL semantics team members.  I think there is a strong case here that we will find some actual bugs and having an exhaustive list of the known failures will be instrumental for future Hibernate work.

The current list of failures can be see here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/hibernate_blacklist.go

**Comment by knz** [comment]
This work has completed. Inventory:


Occurrences | Github Issue | Description | In 2.2? | Notes
-- | -- | -- | -- | --
99 | #6583 | Locking unsupported | No | Fundamental divergence
93 | #5807 | temp tables unsupported | (maybe for testing) | Feature planned for later
33 | #26725 | lo_creat is unsupported | No | (BLOBs) Feature planned for later
11 | #24062 | Hibernate expecting a 32-bit serial type, but gets 64 | Yes |  
9 | #12123 | can't drop a table within a transaction and create a new one of the same name | Maybe | Team: Schema changes
9 | #26738 | this tests expects and exception, but due to the last of fk constraint this fails | Maybe | Team: Schema changes
7 | #17511 | stored procedures unsupported | No | Feature planned for later
4 | #16769 | pg_catalog.pg_attribute shows column physical types (int8), needs to send visible types instead (int4). | Yes |  
4 | #26443 | user defined schemas are not supported | Yes |  
3 | #26732 | unsupported binary operator: <int> / <float> . Existing, wont-fix issue. | No | Fundamental divergence
3 | #31670 | correlated DELETE | Yes | Team: SQL Planning
2 | #3781 | to_char() is not supported, but we do have support for strftime | No | Feature is low-impact, high-cost
2 | #10028 | views do not currently support * expressions | No |  
2 | #31673 | Physical planning error "conflicting ColumnTypes" | Yes | NEW ISSUE; Team: SQL Execution
2 | #31708 | current_time not supported | No | Needs TIMETZ
1 | #9682 | computed indexes unsupported | No | Feature planned for later
1 | #24897 | CREATE OR REPLACE VIEW is unsupported | No |  
1 | #27274 | retyable transaction is not retried | No | Test needs to be adapted
1 | #31589 | "family" cannot be used as an unquoted table name | Yes | NEW ISSUE
1 | #31671 | DROP never completes | Maybe | NEW ISSUE; Team: Schema changes
1 | #31721 | correlated INSERT | Yes | Team: SQL Planning
