### ISSUE TITLE
storage: Add metrics for txnwait queue

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#31106]
Prior to 2.0, the Distributed/"KV transaction restarts" chart was a good indicator of the amount of contention in a cluster. Now that contended transactions tend to spend time in the txnwait queue instead of being restarted, that's a less reliable indicator. We should add metrics for the number of transactions in the queue, average wait time, etc.

**Comment by tbg** [comment]
To add the metrics, follow the example of `tsCache.Metrics`: https://github.com/cockroachdb/cockroach/blob/3f7ca5b3ce60bfed5e73bed5c31d016e43375d23/pkg/storage/store.go#L809

That is, store the metrics on `txnwait.Queue` itself, and register them as given in the snippet above.

I think we'll want the following (all prefixed something like `txnwaitqueue`)

1. `num_pushees`: Gauge: number of txns in the queue: `len(q.mu.txns)`
1. `num_pushers`: Gauge: number of goroutines in MaybeWaitForPush
1. `oldest_pushee`: Gauge: age of the oldest txn in the queue (need to add creation time to entries in `q.mu.txns`)
1. `pusher_wait`: Count: time spent in `MaybeWaitForPush` (added when returning from that method)
1. all of the above for MaybeWaitForQuery (`q.mu.queries`); possible not all make sense
1. `num_deadlock`: Count: incremented every time ErrDeadlock is returned

@bdarnell @nvanbenschoten does that sound reasonable? I also think we want to be able to introspect the contention queue, but that seems out of scope here.

**Comment by tbg** [comment]
@andy-kimball I would suggest this one as a starter project as well (my favorite of the ones I've heard so far). Ideally we'll get this in before 2019.1.

**Comment by nvanbenschoten** [comment]
That all looks good, although I'm not sure how useful the `MaybeWaitForQuery` metrics will be. The number of actors waiting in `MaybeWaitForQuery` should correspond to the number of pushers in `MaybeWaitForPush`, right?

**Comment by tbg** [comment]
Honestly I'm not so sure, why would they be equal? Some pushers monitor their own proto via queries, but those queries may be at a different node. I agree that we probably don't pay attention to the queries numbers as much as the pushers, though.

The number of goroutines in `MaybeWaitForQuery` should equal the sum of the refcounts here:

https://github.com/cockroachdb/cockroach/blob/b595efd6433c4bb1dcc6a261b98a86cc57c850fd/pkg/storage/txnwait/txnqueue.go#L635-L638

The number of goroutines in `MaybeWaitForPush` is here:

```
	pending.waitingPushes = append(pending.waitingPushes, push)
```

so they're both straightforward to compute.

**Comment by bdarnell** [comment]
> 4\. `pusher_wait`: Count: time spent in `MaybeWaitForPush` (added when returning from that method)

This might want to be a histogram instead of a count. We also want a counter of the number of txns that have gone into the txnwait queue at all.

**Comment by tbg** [comment]
Updating with a bit more intent. Two main goals here:

1. get a good view of contention -> histogram of pusher_wait as Ben suggested, and counter of txn entering the queue in the first place. Less interesting but still useful: number of deadlocks, gauge-counter of pushees in the queue (see below).
2. detect queue stall (i.e. txn goes in, txn never gets to leave) -> gauge-counter of txns presently in the queue. "gauge-counter" refers to the fact that we want a gauge but this is tricky because the Store will pass a Metrics object into many queues, so a single Gauge doesn't work. We use a counter that is displayed as an absolute number.

Spelling that back out as metrics (the names probably need to be rearranged to match existing conventions)


`pushers_num_entered` (count)
`pushers_num_active` (gauge-count)
`pushers_duration` (histogram)
`pushers_num_deadlock` (count)
`pushees_num` (gauge-count)

@bdarnell do we also want to track how many requests do *not* enter the queue? Otherwise, our numbers are skewed and it'll be hard to tell how much contention there really is.

By the way, Darin, I just looked at the code again and I'd have to really dig in to understand `MaybeWaitForQuery`. No comment in that file in very useful, please take time to expand/rework the comments as much as you can so that the next person will have an easier time than you must've had.

**Comment by bdarnell** [comment]
> @bdarnell do we also want to track how many requests do not enter the queue? Otherwise, our numbers are skewed and it'll be hard to tell how much contention there really is.

Maybe? Where exactly would we capture it? We already capture overall request counts. I suppose we could count something like "pushes that don't enter the contention queue", but I'm not sure how I'd interpret that number. 

I'd also like a counter for total transaction-seconds spent in the contention queue (if that doesn't come for free with the histogram. I see I contradict my own previous comment. I am large, I contain multitudes.

**Comment by tbg** [comment]
> Maybe? Where exactly would we capture it? We already capture overall request counts. I suppose we could count something like "pushes that don't enter the contention queue", but I'm not sure how I'd interpret that number.

You're right, total request counts should do it. I think @darinpp is opening the PR today and it should have the histogram and count of pushers entering, which gives a general idea of total pusher seconds spent waiting.
