### ISSUE TITLE
performance: how to prevent latency spikes?

### ISSUE THREAD

**Issue by isoos** [cockroachdb/cockroach#31345]
My overall cluster's query throughput is okay, but I'm unhappy with random and unpredictable latency spikes:
- The same primary-key filtered read or the same update can be under 100ms, and can last longer than 20 seconds.
- Sometimes a `SELECT COUNT(*) FROM table;` is done in a few seconds, sometimes is takes longer than 30 seconds. Arguably, the table was busy with updates.

My application uses about 100 connections. The storage is NVMe SSDs.

**Comment by isoos** [comment]
Is there a fair scheduling when the queries are trying to get a leaseholder to do their parts, or is it possible to have starvation? Because the later would explain the spikes I see.

**Comment by nvanbenschoten** [comment]
HI @isoos, thanks for the question. You mention that query latency varies significantly. To confirm, you are performing modifications on the table at the same time that you're scanning it, right?

What's likely happening is that your writing transactions are acquiring timestamped locks on the table that your read transactions end up waiting on. If a read on a key occurs at a timestamp higher than a provisional write to that same key, the reader needs to either abort the write or wait for it to complete. We favor the latter approach.

One way around this is to perform your large reads a little bit in the past so that they never need to wait on active writing transactions. This is possible through the use of [time travel queries](https://www.cockroachlabs.com/docs/dev/as-of-system-time.html). For instance, you could change your queries to look like `SELECT COUNT(*) FROM table AS OF SYSTEM TIME '-5s';` and avoid any contention between foreground write traffic and these large scans. Of course, this is only possible if your use case allows for reads a few seconds in the past.

**Comment by isoos** [comment]
> To confirm, you are performing modifications on the table at the same time that you're scanning it, right?

Correct.

> What's likely happening is that your writing transactions are acquiring timestamped locks on the table that your read transactions end up waiting on.

Are these locks resolved in the order of the timestamps?

> This is possible through the use of time travel queries.

I've tried a few experiments with these and I don't see any time improvement, but maybe the current load was not that bad.

**Comment by nvanbenschoten** [comment]
> Are these locks resolved in the order of the timestamps?

No, the locks are resolved whenever the transaction that is holding them commits. Reads at timestamps equal to or larger than the timestamped locks will wait on them to unlock. This is why time travel queries can be beneficial in these cases.

**Comment by isoos** [comment]
>> Are these locks resolved in the order of the timestamps?

> No, the locks are resolved whenever the transaction that is holding them commits.

Right, I'm sorry, I was meaning the beginning of the process: when a transaction wants to acquire a lock, and the resource comes available, and multiple connections are waiting on it, what is the order that decides who will acquire it? Is there a chance for starvation there, or is it e.g. timestamp-ordered?

**Comment by isoos** [comment]
Related to the UPDATE/DELETE operations:

It seems to me that the concurrent operations have a great effect on how often the latency spikes occur.  When I cut the load in half (4 parallel processing instead of 8), the latency spikes seem to be much less frequent (e.g. hours of operations without them vs. 15-30-minutes), and they never occur on a single-threaded processing.

As the usual latency is <100ms for them, and the spike is >20 seconds, and there is less than 10 parallel UPDATE/DELETE on that table at any given time, I don't see any sequence of events that would explain it the spikes, unless it is starvation.

Would you be able to give pointers to the related code?

**Comment by isoos** [comment]
One important thing that I've just realized: the spikes happen on transaction commits, where the deletes affect multiple tables and ranges, but multiple, concurrent, similar transactions happen, very likely affecting the same ranges.

**Comment by nvanbenschoten** [comment]
> Right, I'm sorry, I was meaning the beginning of the process: when a transaction wants to acquire a lock, and the resource comes available, and multiple connections are waiting on it, what is the order that decides who will acquire it?

That depends on which version of Cockroach you're running. In 2.0, the acquisition is random. In 2.1, the connections queue on the lock and the first one there will acquire it.

> As the usual latency is <100ms for them, and the spike is >20 seconds, and there is less than 10 parallel UPDATE/DELETE on that table at any given time, I don't see any sequence of events that would explain the spikes, unless it is starvation.

Spikes of more than 20 seconds sounds like a serious bug. I'm curious if you'd be able to correlate these spikes with range splits, which can see in the admin UI in the Replication->Range Operations graph. The reason I bring this up is because we recently found a bug (see https://github.com/cockroachdb/cockroach/issues/31330) that would stall operations on the right-hand side of a range split for a similar amount of time, but this would only show up in traffic if the range was under a lot of load.

How much write traffic are you putting on the cluster when you see these stalls? How large are the operations themselves? How many rows are they touching? I'd like to get a better idea of what these UPDATE/DELETE ops look like.

**Comment by nvanbenschoten** [comment]
> That issue may be related, although can it happen on range merge too? (do range marges happen on deletes?)

Yes, I think that's possible. Remember though that delete operations actually write data (tombstones), so your ranges will grow while writing and only shrink after old MVCC versions of keys are cleaned up.

If most of your transactions are taking 9 seconds then I think we should focus on why they're so slow, because things are only going to get worse if they ever contend and block one another. Is the entire loop in a transaction? From your explanation, it doesn't look like it, but I'd like to confirm.

Is it possible that your page by page scans are contending with your deletes? If they're ever operating on the same set of rows then that could be the case. It looks like the scans are already non-transactional, so it may be beneficial to run the page by page scans using `AS OF SYSTEM TIME` a few seconds in the past to prevent them from serializing with the deletes.

**Comment by nvanbenschoten** [comment]
@isoos do you have an update on this issue?

**Comment by isoos** [comment]
@nvanbenschoten I have wrapped the code with timers and if one transaction goes above a certain threshold, I decrease the concurrency. Not much of a solution, but at least I don't have too much timeouts...

**Comment by nvanbenschoten** [comment]
We've made a lot of progress in this area over the past few releases. Notably, we've improved queuing efficiency and fairness through a combination of a new lock-table data structure, per-lock wait-queues, and unreplicated locks.

This is reflected in the improvements to YCSB that we see, which may be a decent proxy for the workload we're discussing here, given the contended nature. So I'm going to close this, as I don't see anything more that's actionable. But please re-open if you feel there's more to discuss.
