### ISSUE TITLE
exec: implement columnarized N:1 inner hash join

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#31375]
See http://oai.cwi.nl/oai/asset/14075/14075B.pdf, section 5.3 for more details.

**Comment by changangela** [comment]
For this vectorized hash join operator, the build table's equality columns must only contain distinct values. An inner join is then performed.

Before the build phase, all equality and output columns from the build table are collected and stored.
In the vectorized implementation of the build phase, the following tasks are performed in vectorized fashion:
1. The bucket number (hash value) of each key tuple is computed and stored into the buckets array.
2. The values in the buckets array is normalized to fit within the hash table bucketSize.
3. The bucket-chaining hash table organization is prepared with the computed buckets.

In the vectorized implementation of the probe phrase, the following tasks are performed:
1. Compute the bucket number for each probe rows key tuple and store the results into the `buckets` array.
2. In order to find the position of these key tuples in the hash table:
    - First find the first element in the bucket's linked list for each key tuple and store it in the `groupID` array. Initialize the `toCheck` array with the full sequence of input indices (0...batchSize - 1).
    - While toCheck is not empty, each element in toCheck represents a position of the key tuples for which the key has not yet been found in the hash table. Perform a multi-column equality check to see if the key columns match that of the build table's key columns at groupID.
    - Update the differs array to store whether or not the probe's key tuple matched the corresponding build's key tuple.
    - Select the indices that differed and store them into `toCheck` since they need to be further processed.
    - For the differing tuples, find the next ID in that bucket of the hash table and put it into the `groupID` array.
3. Now, `groupID` for every probe's key tuple contains the index of the matching build's key tuple in the hash table. Use it to project output columns from the has table to build the resulting batch.
