### ISSUE TITLE
bulkio: enable EC2 instance-based temporary credentials for S3 access

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#31611]
In much the same way that GCE instances can be given implicit credentials for access to Google cloud storage, AWS EC2 instances can be associated with an IAM role; in this case, applications on the EC2 instance can retrieve and use temporary credentials associated with the role. The AWS documentation for this functionality is [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html); in the Go SDK, I believe this is in the `ec2rolecreds` package.

We should implement this implicit authentication method, and ensure that the user interface for it matches what we do for implict GCE instance auth (see #31602).

**Comment by mberhault** [comment]
There are two things here:
1. implicitly using the instance role (can be done by simply calling `session.NewSession()`)
1. allowing temporary credentials that may be coming from an instance role (through they can come from other methods such as MFA). Those require a session token (can be specified along with access key ID and secret in the [static credentials](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#NewStaticCredentials))

The two ways of accessing this are completely different. The first would be credentials configured on the cockroach VM itself. The second could be the VM credentials of the client running `BACKUP`, manual calls, Vault-generated credentials, etc... This is probably much more useful. Also pretty simply to implement, we just need to support an additional parameters: `SESSION_TOKEN` and pass it instead of the empty string in `Credentials: credentials.NewStaticCredentials(b.AccessKey, b.Secret, ""),`

**Comment by mberhault** [comment]
Created a separate issue  just for the session token: #32276.

We can leave this issue as supporting a role to assume (where cockroach itself would call STS AssumeRole, resulting in the temporary credentials mentioned in the other issue).

**Comment by rolandcrosby** [comment]
After discussing with a customer and investigating, I believe this may be even more trivial than I thought: the AWS SDK will [automatically use instance-based credentials](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials) if you don't specify credentials. So all we need to do is stop requiring an AWS access key ID and secret for S3 URLs, and initialize the client without providing any credential arguments in that case.

**Comment by rolandcrosby** [comment]
@dt has pointed out that on GCP [we use an `auth=implicit` URL parameter](https://www.cockroachlabs.com/docs/v19.1/backup.html#considerations) when using instance-based credentials. We should add this parameter for S3 URLs, and not require a user to pass the AWS key/secret when `auth` is set to `implicit`. (Otherwise, `auth` should default to `specified`, which should retain the current behavior of requiring an S3 access key and secret.)

**Comment by lucy-zhang** [comment]
Is `auth=specified` supported for S3? I thought it was just for GCE.
