### ISSUE TITLE
Server node cache the CmdID to reject the same request

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#3162]
Suggestion:
In #2962 we know the retry in "DistSender" will send a new request to the first range node again. It will give the first range node more unnecessary pressure.
Can we just cache each "CmdID" in "RequestHeader" ? Range node check the cache first and reject the request which already exists.
And range node also need to delete the "CmdID" from the cache when return the resp to the gateway node.

**Comment by tschottdorf** [comment]
since the reworking of the sequence cache (and the subsequent removal of `CmdID`) this is roughly what should happen (at least in a transaction): after the timeout, the next request sent by `DistSender` will have the same sequence number, and the transaction will restart. Of course, a request which can never complete within the time `DistSender` is prepared to wait, will never be able to commit.
I'm closing this, but feel free to discuss further.
