### ISSUE TITLE
ui: node map doesnt work at all when there are large #s of nodes

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#31699]
Here's a 42 node cluster if you drill down to the leaf of the locality trees. 

![image](https://user-images.githubusercontent.com/894257/47305631-12ded800-d5f8-11e8-9227-5c9be6834a90.png) with nodes running v2.1.0-beta.20181015

We need to fix this UX.

**Comment by piyush-singh** [comment]
Related to #22874, @couchand any idea what the previous max we tested with was when closing out that other issue? From the PR, it looks like the previous fix was targeting common use cases which means 42 nodes is probably well outside what we tested with. 

On another note, since we do want to support other teams working on scaling # of nodes for 2.2, does it make sense to create a new A label for the web UI around scaling? Would be useful for some of the issues Alex filed during TPC-C 50k testing along with Robert's requests to support ~1000s of tables on the databases page.

**Comment by vilterp** [comment]
Yeah, I don't think we should try to show the circle layout when there are this many things. A tree-table UI shows the same info and scales better. From @josueeee's designs:

![image](https://user-images.githubusercontent.com/7341/47387779-5449b300-d6de-11e8-9847-7a5e6af227fe.png) ([source](https://www.figma.com/file/WzhvMEGkuDi8Wd7va0vgHHiG/Hardware-Metrics?node-id=0%3A1))

Not sure the best way to integrate the TreeTable and the map — show them together? switch between them? etc…

**Comment by couchand** [comment]
@josueeee also had an early design for the node list as a panel coming up from the bottom over top the node map.

@piyush-singh don't remember the previous max but i think it was something like twelve.  👍 for a new label, just made it.
