### ISSUE TITLE
pgwire: array of unknown should become array of text

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31912]
While comparing output from postgres and cockroach I found the OIDs in arrays in the binary format differed. For example:

`select array[null]`

postgres returns 
```
0 0 0 1 0 0 0 1 0 0 0 25 0 0 0 1 0 0 0 1 255 255 255 255
```
and cockroach 
```
0 0 0 1 0 0 0 1 0 0 2 193 0 0 0 1 0 0 0 1 255 255 255 255
```

The `25` in the postgres return is the OID of the type, `text` in this case. The `2 193` in cockroach is `2*256+193 = 705` which is `unknown`.

Similarly for `select array[B'101']` postgres returns OID 1560 (bit) and cockroach returns 1562 (varbit).

It's not clear to me if we can just change the OIDs to match postgres without breaking something else so I'm just documenting this here.

@jordanlewis any insight into this?

Jira issue: CRDB-4772

**Comment by jordanlewis** [comment]
You can also check with `pg_typeof()`, for the record, which agrees with what you are finding.

I think for the first one, returning `unknown[]` isn't super crazy - Postgres just defaults to `text` for `null` maybe? Seems like an odd choice. I think we're fine here.

For the second one, I think there are some differences in the way we and Postgres handles `b''`. I think @knz recently added varbit (?), maybe he knows more.

**Comment by knz** [comment]
Guys we're having like three or four discussions in here, there is a lot to unpack.

1) the behavior of a *literal* `null` (i.e. not a stored null, not a null in a placeholder) in postgres is **weird**. Postgres will try to auto-promote it to a bunch of different types depending on contexts. It's actually somewhat difficult to get the type "unknown" derived in pg.

**I do not think we need/want to emulate that in cockroachdb. literal nulls are rare anyway.**

2) in pg it's impossible to build arrays of unknowns (`unknown[]` is not a type in pg). Conversely, pg auto-promotes an array of unknown element type (eg because it's full of untyped nulls, but can also be because it's full of placeholders without hints) to `text[]`. The values (e.g. the placeholders) are then inferred to be `text` accordingly.

**we could do something similar in crdb. Arrays of unknowns are nonsensical anyway.**

3)  postgres derives the type `bit` (not `varbit`) for bit array literals (e.g. `B'101'`). crdb currently derives the type `varbit`. This may have been a plain error in my initial implementation. To be investigated. Also this is not specific to arrays. 

4) Matt I think we should be careful to prioritize effort adequately. I am all in finding good ways forward for cases that actually happen in apps, but really complex expression containing *literal* `null`s (again, literal, not stored or passed via placeholders) are *rare* and I do not want to spend much time thinking about them unless they can teach us about other things.

**Comment by mjibson** [comment]
I'm happy to leave the NULL case. The BIT one is a bit weirder, but I don't care too much either way. I definitely agree that I don't want to spend much or any effort in the OID pit mines. I mostly wanted to document my findings and get some words from ya'll. Mission accomplished.

**Comment by mjibson** [comment]
Second thought: we shouldn't do anything about this until someone complains, and maybe not even then unless it's a big, convincing deal.

**Comment by knz** [comment]
can you file one separate issue for "bit literals should have type bit, not type varbit", with your examples.

Then you can rename this issue to "array of unknown should become array of text" 

we can follow up on them.

**Comment by mjibson** [comment]
done

**Comment by jordanlewis** [comment]
This is solved:

```

demo@127.0.0.1:26257/defaultdb> select pg_typeof(array[null]);
  pg_typeof
-------------
  text[]
(1 row)
```
