### ISSUE TITLE
kv: maybe leaderCache should have expired time

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#3196]
Currently, `leaderCache` only updated when `NotLeaderError`. Why don't we update it when successfully receive resp from a range node? Because it make update too frequently? We can skip `replicas.MoveToFront(i)` to update it when after a short period(expired time). 
And I think if we don't have expired time for `leaderCache` , it will be solidify a range leader for a gateway node. The random operation in `SortByCommonAttributePrefix` will be useless.
I also encounter a case like this: one of the three node disconnect from the network(named node C), other two node still work for a long time, then the "node C" recovered. "node C" has plenty of raft log entries to catch up, so "node C" is very busy at that time. But "node C" still in many gateway node's `leaderCache`(cached before node C disconnect from the network), they send lots of requests to "node C" at once when "node C" recovered. "node C" can't reply them in time because of the plenty of raft work. If we have expired time for `leaderCache`, the gateway node can give pressure to "node C" little by little when "node C" recovered.

**Comment by tschottdorf** [comment]
I'm not sure I understand what you're saying, but basically if there is a leader then for the duration of that lease we **have** to send to that leader. We can't just expire a cache and then send to someone else (that someone else will simply point us back at the leader). If a leader goes down and remains down for a reasonable amount of time, there will be a new leader (after the old leadership expires), I can't quite see the circumstances under which the problem you're describing would occur. Am I missing your point?

**Comment by bdarnell** [comment]
We shouldn't expire the leader cache while the old lease is valid; I assume the suggestion is to give the cache an expiration time equal to the lease duration (currently the leader cache is valid until we explicitly update it in response to a NotLeaderError). The problem is that in normal operation, the old leader will renew its lease so it is wasteful to expire the cache and try a random node at least once every time the lease is renewed.

However, there is definitely room for improvement in our handling of the leader cache. Consider the case where C was leader and died, and A is the new leader. A client with C in its leader cache will first try C, then randomly A or B. If it chooses A, it gets a response but doesn't update its leader cache so the next request will have to go through this cycle again. C is only removed from the leader cache when we hit B and get a NotLeaderError. We should also update the cache on successful responses since we know we've found the new leader.

Additionally, we may be able to make use of the lease expiration in other ways in DistSender: use a higher SendNextTimeout when we know the node we're attempting to reach has a valid lease, and a shorter one if it may have expired.

**Comment by changrui82** [comment]
To bdarnell: Yes, I agree with you in some ways.
We need to update `leaderCache` when C is died. To change `leaderCache` to A or B.
But I think we also need to change some ranges' `leaderCache` back to C when C recover, for load balance.
So, I mentioned "expire the leader cache", in order to make C has opportunity to become `leaderCache` for some ranges again.
About you last paragraph, I'm not sure we can distinguish the node whether has a valid lease.
Thanks for your reply!

**Comment by bdarnell** [comment]
> But I think we also need to change some ranges' leaderCache back to C when C recover, for load balance.
So, I mentioned "expire the leader cache", in order to make C has opportunity to become leaderCache for some ranges again.

Ah, that's different. The leader cache must always reflect the true leader of the range, so what's needed here is not a change to the cache, but a change to the way leaders are chosen. There is a trade-off here since moving a leader can cause disruption (as all clients will need to be informed of the new leader on their next request), so we don't want to change leaders too often, but allowing one node to stay the leader for many ranges indefinitely is not ideal either. This will correct itself (very slowly) through the rebalancing system, but we will probably need to consider load in leadership decisions at some point.

> About you last paragraph, I'm not sure we can distinguish the node whether has a valid lease.

The lease has an expiration time. We could return that time in the `NotLeaderError` (and maybe add it to the `ResponseHeader` for all successful responses), and then we could know when the lease is valid.

**Comment by petermattis** [comment]
@tschottdorf Is this necessary/worthwhile for Beta?

**Comment by tschottdorf** [comment]
Sorry, never saw this.
It's not client-facing, so we don't have to rush it in before the first "serious" deployments, but the improvements discussed in this thread make a lot of sense. I would leave this in 1.0 but we should revisit this soon after Beta.

**Comment by petermattis** [comment]
I don't think there is anything left to do here. When a node recovers, we will rebalance leases onto it. And we take load into consideration when making rebalancing decisions, though there is more work to be done in that area.
