### ISSUE TITLE
storage: TestStoreMetrics got stuck in range lookup on shutdown

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#32056]
Gist here:
https://gist.github.com/tschottdorf/21fbb3f9bde217cf16511dda34310cec

I stared at this a bit, but couldn't make sense of it. We have two goroutines that are in the `singleflight.(*Group).doChan`. I think the first probably triggered the second since the goroutine IDs are adjacent.

So goroutine 51432 is presumably some regular key lookup and calls `performRangeLookup` which eventually ends up in `lookupRangeDescriptorInternal` again (to find the replica that has the meta2 key?). `lookupRangeDescriptorInternal` is then presumably what spawns the second singleflight. That second singleflight also ends up in `lookupRangeDescriptorInternal` but it doesn't spawn another singleflight, implying that it's joining onto the first singleflight. This is odd because that shouldn't happen unless they're looking at the same key. But there's additional detail in that the range lookups have to scan forward, so it's not 100% clear that they wouldn't somehow overlap.

I'm going to put this on the back burner (ran into this on CI in https://github.com/cockroachdb/cockroach/pull/31728 and don't want to get completely sidetracked), but perhaps @nvanbenschoten has some ideas about what this might be.

**Comment by nvanbenschoten** [comment]
This is interesting. goroutine 51431 is a node liveness attempt, so it's presumably touching a key in the liveness range that's not in the range descriptor cache. It launches a range lookup for `meta(livenessKey)`, which is presumably goroutine 51432. This in turn launches another range lookup for `meta(meta(livenessKey))`, which is goroutine 51433. This should be a meta1 key so the two lookups shouldn't be coalesced together.

It's possible that we're doing something funky in `makeLookupRequestKey` that's causing the `requestKey`s to be equal and creating the deadlock. I'll try to reproduce.

**Comment by nvanbenschoten** [comment]
I was able to reproduce this with about 20 minutes of `roachprod stress`.

**Comment by nvanbenschoten** [comment]
We're never using an `evictionToken` in the failure, so `makeLookupRequestKey` should always return the key without trying to coalesce lookups. In fact, none of the range lookups in the test are coalesced.

**Comment by nvanbenschoten** [comment]
The chain of events goes like this:
1. goroutine 1204 looks calls `LookupRangeDescriptor` with the key `/System/NodeLiveness/2`
2. it launches goroutine 1205, which calls `LookupRangeDescriptor` with the key `/Meta2/System/NodeLiveness/2/NULL`
3. which launches goroutine 1206, which calls `LookupRangeDescriptor` with the key `/Meta1/System/NodeLiveness/2/NULL/NULL`

So far so good. So why is goroutine 1206 stuck? I don't see its corresponding `singleflight.(*Group).doCall`. I need more logs.

**Comment by nvanbenschoten** [comment]
Aha! I was banging my head against this for a while because I could see `RangeDescriptorDB.FirstRange` being called but couldn't see it return. The stack was unwinding with empty return values but I wasn't able to `recorver` in defered functions. I could see that we had a `mtcRangeDescriptorDB` as our `RangeDescriptorDB`, but was looking at `mtcRangeDescriptorDB.RangeLookup` instead of `multiTestContext.FirstRange`.

I turns out that this is the same issue as https://github.com/cockroachdb/cockroach/issues/30600, but 847bc80 changes the panic to a `log.Fatal` and for some reason the Fatal is being swallowed by the `singleflight.Group`.

**Comment by nvanbenschoten** [comment]
Ok I see what's going on. `multiTestContext.FirstRange` is being called concurrently through a liveness update while all stores are being stopped in [`verifyStats`](https://github.com/cockroachdb/cockroach/blob/acd1250b15b7ed3c8938dfd53b8bc53bb53c578c/pkg/storage/client_metrics_test.go#L81-L86). It looks like the first store is stopped first, so it is nil in `m.senders` by the time a different store gets to `multiTestContext.FirstRange`. Unfortuanately, store 1 is the only store that has the first range because we never actually replicate it to other nodes in `TestStoreMetrics`. We need the first range descriptor to complete the liveness update for a different node and the liveness update is blocking that node from draining.

Replicating the first range to all nodes seems like the right solution, but doing so causes other stalls and messes with the test logic itself. I'm trying to figure out a way to avoid these issues.

We may just want to handle this situation in `multiTestContext.FirstRange` better and return an error instead of fataling. Even if we do fix `TestStoreMetrics`, I don't trust other tests to not run into the same issue.

**Comment by nvanbenschoten** [comment]
> We may just want to handle this situation in multiTestContext.FirstRange better and return an error instead of fataling. Even if we do fix TestStoreMetrics, I don't trust other tests to not run into the same issue.

I went with that approach.
