### ISSUE TITLE
SET default_transaction_isolation returns SET but does nothing

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#32115]
**Is your feature request related to a problem? Please describe.**
`SET default_transaction_isolation...` and `SET transaction_isolation...` both return` SET` indicating they've taken effect, though they cannot be meaningfully set to any value besides `serializable`.

**Describe the solution you'd like**
I think any kind of change to behavior would be an improvement:
- Remove `default_transaction_isolation` and `transaction_isolation` as settings available to the `SET` statement.
- Return an error indicating the setting is read-only.

**Describe alternatives you've considered**

**Additional context**
It's challenging to document the relationship between `SET` and `SHOW` for settings that are essentially read-only.

**Comment by knz** [comment]
Sean I think it's a bit more complicated than that. IIRC the reasoning for the current behavior is that we want to support apps that desire to set a lower isolation level, but silently promote them to serializable which is "backward compatible". If we were to return an error instead, these apps would not work any more.

@bdarnell do you confirm this was the reasoning?

**Comment by bdarnell** [comment]
Isolation level settings establish a minimum: when the application says "set isolation level read committed", it means "I can tolerate unrepeatable and phantom reads, but can't tolerate dirty reads". We can satisfy this request, since we'll never give them dirty reads. We won't give them unrepeatable or phantom reads either, but they never said they *require* those things, only that they can tolerate them (with an implied "whenever it makes things faster"). 

It's important for compatibility that these commands be supported, since it's extremely common for applications to issue these commands as a way of declaring their transactional requirements. This may or may not change the database's behavior, and this is fine as long as the database can provide an isolation level that's at least as strong as the requested one.

**Comment by sploiselle** [comment]
Makes sense. Thanks, folks.
