### ISSUE TITLE
old version grpc used

### ISSUE THREAD

**Issue by nicolasStevenin** [cockroachdb/cockroach#32172]
Hi,

**Describe the problem**

When I compile your project, in the **pkg/util/grpcutil/grpc_util.go** you are using an old version of https://github.com/grpc/grpc-go : "google.golang.org/grpc/transport"
And this repository doesn't exist since version 1.5.2 (currently 1.16.0)

**Environment:**
 - CockroachDB version 2.1.0
 - Server OS: CentOS 7
- Go 1.11

**Additional context**
What was the impact?
There are a lot of conflicts between your version used of grpc and other projects which use a recent version of grpc but also your project cockcroach.

**Comment by knz** [comment]
@nicolasStevenin this is why we are using the `vendor` tree where we keep a copy of all packages CockroachDB depends on.

CockroachDB cannot simply / blindly upgrade to the later version of everything because more often than not the "latest version" has bad bugs. 

In general I agree we should strive to follow updates to grpc, but in your case you should simply tell your build system to use the `vendor` tree shipped with the CockroachDB sources.

@benesch @petermattis feel free to comment further.
