### ISSUE TITLE
distsql: Incorrect results when executing VALUES statement with OID values

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#32422]
Use logic test to repro:
```
# LogicTest: fakedist

query OO
VALUES ('pg_constraint'::REGCLASS, 'pg_catalog.pg_constraint'::REGCLASS)
----
pg_constraint  pg_constraint
```

EXPECTED: The test should pass.
ACTUAL: The test fails:
```
testdata/logic_test/__test:3: VALUES ('pg_constraint'::REGCLASS, 'pg_catalog.pg_constraint'::REGCLASS)
expected:
    pg_constraint  pg_constraint

but found (query options: "") :
    139623798  139623798
```

**Comment by andy-kimball** [comment]
NOTE: I uncovered this after adding an optimization that collapses:
```
SELECT 'pg_constraint'::REGCLASS, 'pg_catalog.pg_constraint'::REGCLASS
```
to:
```
VALUES ('pg_constraint'::REGCLASS, 'pg_catalog.pg_constraint'::REGCLASS)
```

**Comment by andy-kimball** [comment]
As part of fixing this, fix up the test cases that I modified to work around this issue:

`pgoidtype`
`builtin_function`

Search for comments like this to find instances that need to be fixed up:
`TODO(SQL execution team)`

**Comment by jordanlewis** [comment]
The issue with this is that Values is planned in a special way - all expressions within the values clause are fully evaluated before physical planning.

So, the special form we added to avoid this problem for `::REGFOO` casts isn't activated. Normally, in an expression like `SELECT 'pg_constraint'::REGCLASS FROM t`, when serializing the `Expr` for distribution, we go through the `DOid.Format` path which has a special serialization form that preserves the encoding we're discussing here.

Values nodes are serialized in a different way, however - instead of serializing the expressions, we serialize the underlying datums, using the `VALUE` encoding method. There's no way to preserve the special OID semantics with `VALUE` encoding, so we end up in this mess.

One solution would be to teach the `VALUE` encoder to preserve the "correct" form of the OID - whether that's text or integer. I'll explore this.

**Comment by jordanlewis** [comment]
I spoke too soon - that solution doesn't really work. We can't change the value encoding for these datums. We seem to be painted into a corner.

Ah, I think we can avoid the issue in a separate way, by forcing the planner to never distribute (and therefore require serialization for) values plans that contain these special snowflake datatypes.

**Comment by jordanlewis** [comment]
Heh, now that I think about it, it's messed up that valuesNodes don't check for expression support before trying to serialize themselves in the first place. Broken, in fact. I found another issue:

```
root@127.0.0.1:50196/defaultdb> explain(distsql) values((select 1), 3);
pq: internal error: subquery 1 ("(SELECT 1)") not started prior to evaluation
DETAIL: subquery.go:54,eval.go:3839,values.go:175,distsql_physical_planner.go:2609,distsql_physical_planner.go:2380,explain_distsql.go:121,plan.go:644,walk.go:134,walk.go:139,walk.go:101,walk.go:65,plan.go:649,plan_node_to_row_source.go:139,processors.go:767,flow.go:625,distsql_running.go:261,distsql_running.go:792,conn_executor_exec.go:998,conn_executor_exec.go:840,conn_executor_exec.go:416,conn_executor_exec.go:99,conn_executor.go:1113,conn_executor.go:390,conn.go:309
HINT: You have encountered an unexpected error inside CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this problem is already tracked. If you cannot find it there,
please report the error with details at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.

root@127.0.0.1:50196/defaultdb>
```

**Comment by jordanlewis** [comment]
I take it back, `valueNode` was already properly checking for expression support. The missing piece was that, during the actual plan setup phase, we need to make sure to `wrapPlan` the `valueNode` if we're not distributing. Simple fix after all! PR incoming.

**Comment by jordanlewis** [comment]
Another irritating issue I'm trying to work around is that, due to the special handling of the way `valuesNode` expects all of its subexpressions to be fully evaluatable in DistSQL, `EXPLAIN` doesn't quite work in a uniform way. We don't want `EXPLAIN` to force subquery evaluation - it should be an instant action with no side effects. But then we can't "look into" the values node to get the concrete datums out.

**Comment by jordanlewis** [comment]
Turns out we already had a flag to deal with this problem. PR updated and ready to go now.
