### ISSUE TITLE
changefeedccl: Correct ordering from rangefeed catch-up scans

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#32488]
Currently when a rangefeed performs a "catch-up" scan before beginning to output directly from raft events, there is no guarantee on the ordering of the output. This would break some of our guarantees for CHANGEFEED outputs; therefore, we must somehow put the output of catch-up scans into the correct order before outputting events to the CHANGEFEED sink.

**Comment by mrtracy** [comment]
Note that it is currently not possible to correctly re-order this output above the level of the rangefeed; the output from a RangeFeedRequest is actually an aggregate of several "single" rangefeeds from each range for the targeted span; importantly, the new underlying rangefeeds may be started due to range relocation events such as splits, meaning that we cannot currently track which events are the result of "catch-up" scans.

So, any solution to this implemented at the Changefeed level (a buffer-and-sort solution) would still need new information from the distsender RangeFeedRequest.  Therefore, I am currently leaning towards a solution at the singleRangeFeed level, and that is my current avenue of investigation.

**Comment by danhhz** [comment]
cc @nvanbenschoten in case you have thoughts

**Comment by mrtracy** [comment]
My guess is that the best way to do this is to add an option to make the catch-up operation a reverse scan, as mentioned here: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170613_change_feeds_storage_primitive.md#mvcc-level

As mentioned this might incur a performance hit, but I wonder if that performance hit would still be less than buffering-and-sorting the scanned rows.

**Comment by nvanbenschoten** [comment]
Scanning-in-reverse or scanning-and-buffering are the two options I can think of. I don't have a good handle on which one is a better approach and would defer to benchmarks on that. Scanning in reverse will slow down iteration and will prevent us from using a `SimpleIterator` but scanning and buffering will impose memory overhead. I believe both will require extra key comparisons, just at very different levels. @petermattis any intuition here?

I do agree that this should be pushed into the rangefeed itself (`rangefeed.catchUpScan.iterateAndSend`) so that higher levels can avoid thinking about the complexity.

**Comment by petermattis** [comment]
I don't have any intuition which will be faster or easier. Scanning in reverse is quite a bit slower than forward scanning. But scanning-and-buffering could be problematic too.

**Comment by mrtracy** [comment]
After coming to an understanding of the rangefeed code, I no longer think this can be easily solved with a reverse iterator, because the rangefeed is outputting both the catch up scan *and* active raft commands until the catchup is complete.  A buffer will be needed somewhere.

However, I think this buffer could have one of two behaviors:
1.) A store-and-sort buffer on the output of all events to the processor to a particular registered feed. This buffer would be maintained until the catch-up scan is complete, at which points its contents will be sorted and output and then no longer be necessary.  It may be possible to do this above the singleRangeFeed level, although it would be difficult to do above the distSender level (as we lose information about when new single feeds are re-dialed.
2.) The buffer could be use to buffer "live" events from raft for a specific feed until its catch-up scan is complete. After the catch-up scan is complete, the buffer could be dumped into that feed followed by live events. This would be combined with the reverse iterator approach.

I'm currently liking approach #2, and I will say this is for more than one reason: i think this approach could be used to avoid putting backpressure on raft.  I would do this by having feeds which fall behind a certain buffer limit go back to the "catch up scan" phase; I can flesh out my idea for that in more detail, but it makes me want to prototype option #2 first.

**Comment by danhhz** [comment]
I'd vote for a variation on (2) with two buffers inside the RangeFeed impl.

One buffer is used to buffer all "live" events while the catch up scan is finished.

For the catch up scan, instead of using a reverse iterator, we could use a normal forward iterator and a very small buffer. The invariant we need to maintain coming out of RangeFeed is only that each key is output in ascending timestamp order. This can be accomplished by iterating though a key and buffering all versions of that key, then outputting them in reverse, then moving on to the next key and reusing the buffer. I'd expect that the number of versions that need to be buffered of any individual key should remain pretty small.

After this catchup scan finishes, the "live" buffer can be output in order.

**Comment by nvanbenschoten** [comment]
I like the approach @danhhz laid out in https://github.com/cockroachdb/cockroach/issues/32488#issuecomment-441457762 as well. However, we should still play around with a reverse iterator. It's difficult to gauge whether the additional key comparison required on every key will be cheaper than iterating in reverse at a lower level (which conceptually does something similar).

One additional optimization we can add in is that we only need to buffer live traffic for keys that we haven't yet reached in our catch-up scan. Effectively, this means that we could flush the live buffer as we scan, instead of waiting until the very end to flush it all. This should keep the live buffer small because the range of keys that it covers will shrink as more time goes on and more keys are fed into the RangeFeed. This might be more trouble than it's worth.

**Comment by danhhz** [comment]
Closed by #33705
