### ISSUE TITLE
storage: 4.5 seconds after a cluster creation is a bad time to run your transactions

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32495]
A transaction running around 4.5s after cluster creation (think tests) can easily catch a `TransactionAbortedError`. This is because all ranges start up as having expiration-based leases (as a likely path dependency / accident - they all come from the first range, and splits maintain the original epoch-based lease on both sides). 4.5s later, these leases become eligible for a refresh. The new leases are generally epoch-based, and so it is not `Equivalent()` to the old one (and so it gets a new `Sequence`, which fact in turn causes the new lease acquisition to trigger [this code](https://github.com/cockroachdb/cockroach/blob/5add5b33aa920ed9514efa2f7a80530670cd10bb/pkg/storage/replica_proposal.go#L206) which resets the timestamp cache.

After that ts cache wipe, a concurrent `BeginTxn` can fail its tscache check resulting in `TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY)`.
I believe we've seen this be a cause of flakiness for multiple tests.

Discussing with @bdarnell, it seems that we have a couple of options:
1) if the rhs of a split wants epoch-based leases, have it not inherit the expiration-based lease from the lhs. Exactly how to do that is yet unclear. Can a range not have a lease at all? Perhaps we can give the rhs an expired lease.
2) make `Lease.Equivalent()` understand this transition from exp to epo, and have it consider the two equivalent.

cc @tbg @benesch

**Comment by tbg** [comment]
I don't remember the details, but I think there was a reason to have the RHS of the split start out as leaseholder. I think at some point prior we didn't do that and it could lead to anomalies where another replica would get the first lease but didn't populate the tscache low water mark.

**Comment by petermattis** [comment]
If the primary concern is test flakiness, could we make the initial expiration lease on range 1 shorter and have the cluster initialization wait until the other ranges have converted to epoch-based leases?

**Comment by andreimatei** [comment]
@tbg are you perhaps thinking of the problems with node restarts addressed here?
https://github.com/cockroachdb/cockroach/commit/9497a1185e4e9ec147a979195bd8c2bbd796d36a

@petermattis how short would we make it? I'd like to not give up on a fix yet... A split should not trigger a tscache wipe.

**Comment by petermattis** [comment]
I was thinking of 1s.

**Comment by bdarnell** [comment]
@tbg Yeah, a completely uninitialized range would allow the new leaseholder to start without initializing the tscache. An expired lease or an invalid lease with a correct expiration time would work. 

I think simply shortening the lease (giving the RHS a copy of the LHS lease with the expiration changed to now()) is a bit risky since the LHS has been allowed to serve reads at times between now() and the expiration. Copying the lease over with a correct timestamp but invalidating it somehow is not ideal because it forces a stall of that duration.

Maybe the right way to look at it is as a kind of lease transfer: as soon as we recognize that our lease is not the type we want, we "transfer" the lease to ourselves. That should ensure that all the timestamp boundary conditions are handled correctly.

**Comment by andreimatei** [comment]
> Maybe the right way to look at it is as a kind of lease transfer: as soon as we recognize that our lease is not the type we want, we "transfer" the lease to ourselves. That should ensure that all the timestamp boundary conditions are handled correctly.

How do you envision a "kind of lease transfer" helping with the `prevLease.Sequence != newLease.Sequence` check in `leasePostApply`, which is what's causing the unnecessary tscache wipe?

**Comment by andreimatei** [comment]
How about if the RHS would simply start with a epoch-based lease, initialized by hand (so no `leasePostApply()` runs)?

**Comment by benesch** [comment]
> I think simply shortening the lease (giving the RHS a copy of the LHS lease with the expiration changed to now()) is a bit risky since the LHS has been allowed to serve reads at times between now() and the expiration.

But this is all happening one node node where we can prove that the LHS has not served reads between now() and the expiration, no? Or are you worried about the case where the leaseholder crashes immediately after committing the split txn?

> How about if the RHS would simply start with a epoch-based lease, initialized by hand (so no leasePostApply() runs)?

This seems like a good option.

**Comment by nvanbenschoten** [comment]
> We could prove this today, but if we do something about #14992 (which @nvanbenschoten was recently looking at) it would become possible for the LHS to serve reads between now() and the expiration concurrent with the split.

Which is an option I strongly think we should keep open. I think we're all in agreement that splits should be as minimally disruptive as possible to foreground traffic.

**Comment by andreimatei** [comment]
I dug through the code a bit. It looks to me like the the original node epoch (epoch 1) is written (async) by the liveness heartbeater, triggered by `Server.Start()`, and separately all the splits, including the ones for system ranges, are done by the split queue.
So, how about we blocked the split queue until a node manages to write its original epoch, and we make the `splitTrigger` initialize the RHS with an epoch-based lease using the current node's epoch (which would now be guaranteed to exist)?

Btw, this all got me thinking about what happens if a node tries to acquire an epoch-based lease before it ever wrote a liveness record. I think the answer is that it would just return an error without sending a `LeaseRequest` because of this code.
https://github.com/cockroachdb/cockroach/blob/ee4361551d20a675ba465b8999e66889b69cd1b4/pkg/storage/replica_range_lease.go#L188 
So this makes me think that it'd be sane for a node (newly added to the cluster or restarted) to not start serving until it manages to write its liveness record. I guess we'd lose in some cases where a node could currently serve remote data even though it can't reach the liveness range or serve any local data, but that doesn't seem like a big deal to me.
What do y'all think.

**Comment by bdarnell** [comment]
> So, how about we blocked the split queue until a node manages to write its original epoch, and we make the splitTrigger initialize the RHS with an epoch-based lease using the current node's epoch (which would now be guaranteed to exist)?

Not all splits come from the split queue. Some splits could come from an ALTER TABLE SPLIT command running on a different gateway. 

> So this makes me think that it'd be sane for a node (newly added to the cluster or restarted) to not start serving until it manages to write its liveness record.

The only problem with this is bootstrapping: a node may have to process KV ops for liveness records to be written. The situation is similar to the issues around node ID assignment (which blocks SQL traffic on a brand new node); I think we could rearrange things so that we write an initial liveness record in the same part of the bootstrapping process as we obtain a a node ID.

**Comment by bdarnell** [comment]
Another idea: We currently create the first range in Store.BootstrapRange and then leave all the splits to be performed by the split queue. There are no leases yet. If instead of writing a first range that spans the entire keyspace, we wrote two ranges (one covering the span that wants expiration-based leases and one covering the span for epoch-based leases), this problem shouldn't occur. The first real leases would be created as the correct type.

Extending this logic to create *all* ~22 initial ranges at bootstrapping time would also help make tests more deterministic and faster, although doing so might involve duplicating more logic from the split-finder.

**Comment by andreimatei** [comment]
I like this idea; I'll continue looking into it.

**Comment by benesch** [comment]
I like that idea too. You shouldn’t need to duplicate really any logic from
the split finder. The list of static splits is exposed as a global in
package config IIRC.

**Comment by andreimatei** [comment]
I'm trying to make the bootstrap process create all the system ranges statically, but I hit a snag. The code around [here](https://github.com/cockroachdb/cockroach/blob/3c6fb83cd8d6ad8c70b7c7301f89479170058f84/pkg/server/node.go#L224) runs after the engine has been initialized with the static ranges, and it creates a hacked up `client.DB` using a "local sender" which sends everything to range 1 (in particular, the requests for allocating a node id and a store id). Since now the sequences for those ids are no longer on range 1, the allocations fail.
I think we have two options; would like comments from people who know about this code (if any such people exist / if any such comments exist). One thing to keep in mind is that the node / store ids that we want allocated are already known (in fact, we assert that we've allocated what we expected).
1. We could write the value expected for the respective sequences at a lower level, without using a `client.DB` for it.
2. We could use a better sender in this bootstrapping code.
    1. We could teach the "local sender" to resolve the static ranges
    2. If I'm not mistaken, there already is a `DistSender` (created in `NewServer()`) by this point. Perhaps we can start using it. Of course, the `DistSender` is probably in a bit of a funky state since there are no other nodes it can talk to, but I think that theoretically it should be able to resolve local ranges. What would it need in order to do so? It would need the first range descriptor to be "in gossip" for meta1, which I guess we could do since we've recently written said descriptor to the engine. With that, I think the DistSender should be able to use the `Node` object (which also already exists in some state) to route to the local `stores` object just like the the `localSender` already does.

**Comment by bdarnell** [comment]
I would love to get rid of this local sender. I think that the simplest approach (which is also compatible with the other changes you're making to this code, moving towards special casing bootstrap instead of using the full production code paths) is to write the correct sequence values directly to the engine instead of going through a client.DB. 

`2.ii` (using a full DistSender) is also acceptable, but I expect that is going to unearth more complexity than it's worth. I don't think `2.i` (teaching the local sender to do range resolution separately from DistSender) is a good idea.

**Comment by andreimatei** [comment]
Agreed; let's hardcode the hell out of the initial state of the engine.
I got the beast booting up, but sure enough it was a matter of time until more routing pain: the `testContext's` sender which sends everything to range 1:
https://github.com/cockroachdb/cockroach/blob/26d16bbafc70d60aadd8d0ce8d28ea9a4a82c3a0/pkg/storage/replica_test.go#L279

I guess I'll have to teach this sucker about all the system ranges.

**Comment by andreimatei** [comment]
Nevermind the last comment, I had forgotten that the `testContext` is about testing a single range. But it still uses `store.BootstrapRange()`, at least sometimes. I guess I'll have to teach it to not do the splits.

**Comment by danhhz** [comment]
@andreimatei any update on this?

we're trying to move cdc over to RangeFeed but a bunch of tests have to be skipped because closed timestamps (and thus RangeFeed) depends on the user tables having all epoch based leases. i think i have a workaround that waits for everything to switch to an epoch lease, but that means the test takes forever

**Comment by andreimatei** [comment]
Working on it. It's a bit of a one test at time story at the moment since the change makes a bunch of 2014 tests unhappy.
But shouldn't be long.
