### ISSUE TITLE
Recovery cockroachdb to specific transaction

### ISSUE THREAD

**Issue by victorggsimida** [cockroachdb/cockroach#32573]
**What is your situation?**

I know: cockroach db can use cockroach dump or select outfile  to dump data with a specific timestamp by using 'as of'.

But can I dump the data with specific transaction? and recovery the data to specific transaction state.

In mysql, we use mysqldump to dump data with binlog position and recovery to the binlog position.

Is there the same solution to cockroachdb

**Comment by knz** [comment]
@tim-o @rolandcrosby can you pick this up? we must figure out what the need is exactly

**Comment by tim-o** [comment]
@victorggsimida, it'd be helpful if you could tell us more about the specific behavior you'd like cockroach to perform.

We do have [audit logging](https://www.cockroachlabs.com/docs/stable/experimental-audit.html), which will create a file containing every change made to a specified table. As you noted, we also allow users to [backup AS OF SYSTEM TIME, and with revision history](https://www.cockroachlabs.com/docs/stable/backup.html#backup-with-revision-history). We also allow users to use [change data capture](https://www.cockroachlabs.com/docs/v2.1/change-data-capture.html#main-content) to stream changes to Kafka, where you could do whatever you pleased with it.

If you were to backup using revision history, you can also [RESTORE from a specific point in time](https://www.cockroachlabs.com/docs/stable/restore.html#point-in-time-restore). 

It sounds like backing up with revision history and restoring from a point in time would suit your need, but if not please let us know what would be missing. Thanks!

**Comment by rolandcrosby** [comment]
@victorggsimida, if I'm reading your question correctly, it sounds like you're trying to take a backup of the state of your database at a specific point in linear history, in the same way that you'd specify an offset in a MySQL binlog or Postgres WAL. Because CockroachDB is a distributed database that runs on multiple nodes, and because it can tolerate some amount of clock discrepancies between nodes, there is no total ordering of all writes to a CockroachDB database the way there is in a single-node database with a single WAL. However, the [hybrid logical clock timestamps](https://www.cockroachlabs.com/docs/stable/architecture/transaction-layer.html#time-and-hybrid-logical-clocks) used in CockroachDB for `AS OF SYSTEM TIME` queries (and for `cockroach dump --as-of`) *do* provide a cluster-wide checkpoint that you can rely on to ensure you've seen all the transactions that have committed as of that logical timestamp. For a higher-level overview of how this system works, I recommend reading our [Living Without Atomic Clocks](https://www.cockroachlabs.com/blog/living-without-atomic-clocks/) blog post.

**Comment by victorggsimida** [comment]
@tim-o 
hi, appreciate your answer.
as i know
1. audit log  : is for specific table. if i want to make audit log for all tables? i need to run many alter table command?

2. audit log is stored in each node?  I need to collect the log to restore data?

3. audit log fields : i did not see the unique serial number ( such logical clock timestamps)?
if i use the dump as of system time '2018-11-11 11:11:11'

and in the audit log: at the above timestamp,  there are many audit log? how to determine which audit to redo?

at all:  maybe i need a unique sn where dump and in audit log?


4. cdc to kafka is a good idea. but cdc is for enterprise user only? not for free

**Comment by victorggsimida** [comment]
@rolandcrosby  
haha. thank u for your answer.

oh,  AS SYSTEM OF TIME  can use  a cluster-wide checkpoint (hybrid logical clock timestamps )
. 
forgive my not enough understanding of AS SYSTEM OF TIME.

but I still has some question

1. how to get a list of    cluster-wide checkpoint? I can use?

and yes I can get backup with specific timestamp (or specific transaction ) with AS OF SYSTEM TIME

2. but how do I recover the data to specific timestamp?   maybe I need some log with cluster-wide checkpoint to redo the log.

**Comment by knz** [comment]
@victorggsimida thank you for your extra questions.

1. there is no such list as "list of cluster-wide checkpoints". CockroachDB does not keep a full transaction log. You should think about this as points on a continuous (not discrete) line of time. 

2. to recover the data at a specific timestamp you can either:

   - run `cockroach dump` with the option to get data "at a given system time", then load the dump in a new database
   - use RESTORE (CCL feature) with a given system time

I hope this answers your question.

Note however that you are asking questions here about "How to use CockroachDB". These are good discussion points, but Github is not exactly the best place to have these conversations. We would like to invite you to discuss these points on the forum instead: https://forum.cockroachlabs.com/ - there you will have better quality answers.

Since your questions do not yield a clear actionable change in CockroachDB or its documentation, I will now close this issue. Feel free to follow up with more discussion points (on the forum) or suggestions for changes in CockroachDB (new issues on Github).

Thank you again for your interest!
