### ISSUE TITLE
Allow web login for insecure clusters

### ISSUE THREAD

**Issue by lnogol** [cockroachdb/cockroach#32659]
**Is your feature request related to a problem? Please describe.**
Apparently web login can't be enabled for insecure clusters. It might make sense in some cases.

**Describe the solution you'd like**
A way to allow web login for insecure clusters. Environment variable?

**Describe alternatives you've considered**

**Additional context**
We have this in Kubernetes:
* CRDB as a `StatefulSet` with `hostNetwork: false` - not directly exposed
* `Weave Net` as CNI plugin which [encrypts traffic](https://www.weave.works/docs/net/latest/tasks/manage/security-untrusted-networks/) within the cluster
* our backend running alongside CRDB that talks to the database
* TLS Ingress through which we access the admin UI

Assuming both DB-to-DB and backend-to-DB traffic is encrypted on a lower layer, it should be quite secure.

There may be something I don't see though.

**Comment by knz** [comment]
cc @piyush-singh @couchand  for triage

**Comment by couchand** [comment]
It's not currently supported to set passwords for users on an insecure cluster.  If that were possible, this would naturally shake out.  So I would consider this a duplicate of #16188.

Let me take this opportunity to opine about why I think it would be a bad idea to implement #16188.  The configuration you've described does indeed provide transit encryption for the cluster's traffic.  However, encryption is not the only necessary security feature, we absolutely need authentication as well.  By running a cluster in insecure mode, not only are the nodes communicating in clear text, but they also are not validating their peers' and clients' certificates, since there are no certificates to be had.  This means there is no assurance that any given request is from a legitimate source.

I'm also not convinced by any promises that external transit encryption provides - too often we've seen vulnerabilities from premature SSL termination.  It seems that end-to-end encryption within process is the safest way to go, and there needs to be a very strong justification for disabling that.  Since there's nothing stopping a person today from setting up and using a secure cluster in Kubernetes, I don't believe that bar has been reached.
