### ISSUE TITLE
sql: comparison of float and int

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#3266]
The following sqllogictest fails with the error:

```
unsupported comparison operator: <float> < <int>
```

https://github.com/cockroachdb/sqllogictest/blob/a88396b84bb1fe62edf2e072e585d68c0b2ecdca/test/select1.test#L94

Which makes sense because `c` is an `INTEGER`, and the call to `avg` returns a `float`. This test is currently disabled for other reasons, but when enabled will fail here. We could decide to either

1. Disable this test. This would involve coming up with a way to selectively disable portions of sqllogic tests, instead of just disabling entire files. It would also mean we are choosing to be more strict than other SQL implementations.
2. Implement float and int comparisons.

**Comment by petermattis** [comment]
We explicitly disallow float vs int comparisons right now. I think we might have to relax this behavior as it is going to be an irritating difference from other SQL implementations.

**Comment by bdarnell** [comment]
We have explicitly decided to be more strict than other SQL implementations, but it may make sense to relax that strictness in the case of comparisons. The main reason to disallow mixed-type arithmetic is because we have to choose what type the result should be. For comparison operators that return a bool that doesn't apply, so allowing mixed comparisons seems less of a concern than other operations.

**Comment by petermattis** [comment]
That sounds like a reasonable and safe first step in relaxing the type comparison rules. @mjibson Care to take this on? Should be relatively straightforward.
