### ISSUE TITLE
sql:  support correlated subqueries in UPDATE SET RHS expressions

### ISSUE THREAD

**Issue by netice** [cockroachdb/cockroach#32786]
I hava test a tabe
```
create table test (id UUID, parent_id UUID, parent_path text);
```
when i run
```
UPDATE test as node 
SET parent_path=concat((SELECT parent.parent_path 
                                          FROM test parent
                                          WHERE parent.id=node.parent_id), 
                                          node.id::varchar, '/');
```
I got  the error :  ```ERROR:  no data source matches prefix: node```

This issues  is that sub select can not reference the update table using table alias,
this work in postgres.
If i remove the ```node``` it works
```
UPDATE test as node 
SET parent_path=concat((SELECT parent.parent_path 
                                          FROM test parent
                                          WHERE parent.id=parent_id), 
                                          node.id::varchar, '/');
```

cockroachdb v2.1.1
gentoo linux

**Comment by knz** [comment]
@netice CockroachDB does not currently support correlated subqueries in combination with mutation statements (INSERT/UPSERT etc).

This is planned to be introduced in CockroachDB 2.2.

**Comment by knz** [comment]
cc @andy-kimball can you consider adding this to the CBO test suite for UPDATE, so that when the PR lands that adds the planning for UPDATE we can close this issue.

**Comment by andy-kimball** [comment]
I'm adding it to our test suites. However, there are a few caveats:

- Until we have support for general-purpose Apply (which is planned for 2.2), we cannot execute this case, since we can't statically prove that the subquery returns <= 1 row. To fix that requires making the `id` column a `PRIMARY KEY`, or introducing `LIMIT 1` to the subquery.

- The `UPDATE` correlated subquery support should be part of the next alpha (due out in a week or two), but it will not be enabled by default, requiring the `experimental_optimizer_updates` session flag to be set to true.
