### ISSUE TITLE
ui: Incorrect range count on overview page

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#32948]
When reproducing the problem from https://github.com/cockroachlabs/support/issues/240, I ended up in a state where the cluster overview page is showing an incorrect range count that contradicts all the other (correct) range counts I can find on other pages.

<img width="1440" alt="screen shot 2018-12-07 at 4 38 21 pm" src="https://user-images.githubusercontent.com/7085343/49679856-5922b600-fa43-11e8-8675-c7871db380f1.png">

<img width="942" alt="screen shot 2018-12-07 at 4 37 39 pm" src="https://user-images.githubusercontent.com/7085343/49679858-5e800080-fa43-11e8-8b38-c7359008f979.png">

There were really only 20 ranges in the cluster at the time, but 4 ranges were being counted from the 4 downed nodes.  For context, I had started a 12 node cluster, replicated all ranges to all 12 nodes, then taken down 4 nodes. All ranges remain available, but underreplicated.

I tracked it down to this conditional in the redux code:

https://github.com/cockroachdb/cockroach/blob/81ed730f073675fe5d634274658e1ff5e291157d/pkg/ui/src/redux/nodes.ts#L193

It's causing us to count the last saved metrics from nodes that haven't been running for minutes (tens of minutes in my case, since I increased the `server.time_until_store_dead` setting to allow more time to debug), even though the ranges that those nodes had been accounting for are now also accounted for by other nodes. 

I added some debug logging to confirm, and nodes 9-12 were all in the node liveness state `UNAVAILABLE`, but were all having their ranges counted by the loop below. Between the 4 of them, they had 4 ranges on them.

I'd just change it myself, but I don't know if there's some history behind this logic.

**Comment by couchand** [comment]
Thanks for digging into this @a-robinson!  Looking at that code, I'm not really surprised it can get confused.  It seems reasonable enough for the metrics that each node definitely reports for itself, but for shared counts of ranges, it's not sound.  It mostly works because it relies on only the leaseholder reporting the range, but as you've found there are times when that assumption doesn't hold.  Also, it's a little awkward architecturally to be getting the same data in at least three different ways depending on where you're looking at it.

**Comment by couchand** [comment]
To give my best effort at some historical context: I think this is how it was written because it was seen as a lighter-weight way of getting the information, since it wouldn't require enumerating each range.  But I don't think it's worth it if the numbers can be wrong.
