### ISSUE TITLE
roachpb: Attach a transaction to any error by refactoring roachpb.Error

### ISSUE THREAD

**Issue by kkaneda** [cockroachdb/cockroach#3303]
@tschottdorf  wrote:

Possibly we can do the following:

* have *roachpb.Error implement error, but in turn remove the implementation from all the errors in ErrorDetail (and along them, auxiliary interface implementations such as IndexedError or - TransactionRestartError)
* add a *roachpb.Transaction to roachpb.Error and move the auxiliary implementations to it
* have all (former) errors in ErrorDetail implement a marker interface (for example type StructuredError interface{})
* type switches that pull information out of the ErrorDetail can match on pErr.GetDetail()

This isn't fully fleshed out, but if you're interested in taking a look I'd be happy to suss it out with you. There isn't an issue for it yet, but #2809 is somewhat related.

**Comment by kkaneda** [comment]
Still looking into, but making`*roachpb.Error` implement `error` might be a bit confusing. Currently some functions return `error` while some other functions return `roachpb.Error`. Mixing these two types of functions can cause unintended behavior like a failing test below:

```
func Test(t *testing.T) {
	err := func() error {
		return nil
	}()
	err = func() *roachpb.Error {
		return nil
	}()
	if err != nil {
		t.Error("err must be null")
	}
}
```

**Comment by tschottdorf** [comment]
yes, that's one standard caveats about using interfaces and we need to be careful about that. It's possible to have **neither** be an error (so neither `err := *ReadWithinUncertaintyError` nor `roachpb.NewError(err)` would implement `error`). Seems unidiomatic Go (plus we lose some of the tooling support) but may be the right thing to do.

Otherwise, there's no reason why some functions would return `*roachpb.Error` and others `error` - if `*roachpb.Error` is an `error`, we can return it that way directly (avoiding the issue above). Everything that wasn't a `*roachpb.Error` but an `error` will be re-wrapped at some point, i.e. there will be some code like

```go
if _, ok := err.(*roachpb.Error); !ok && err != nil {
  err = roachpb.NewError(err)
}
```

plus conversion before sending over the wire. Any "error" which carries structure (basically anything in `ErrorDetail`) shouldn't be an error any more, but is returned directly via a `*roachpb.Error` encoding that information (and possibly more). There will be a bunch of interface conversions. What I'm talking about happens mostly in `Replica` - maybe the coordinator will deal with `*roachpb.Error` exclusively.

Definitely still not fleshed out. Let me know what you think.

**Comment by tschottdorf** [comment]
Since we'll also want to get rid of `IndexedError`, we're going to have to start passing `*roachpb.Error` from `(*Replica).executeBatch` up (but since all of the other `ErrorDetail` members won't be `error` any more, it's going to be from `replica_command.go` up already anyway). Internally, we should probably just drop the `error` interface. At the client boundary (`client.Txn` and so on) we might still want it for ease of use (and to avoid massive test refactors), but that can be done separately.

**Comment by kkaneda** [comment]
I see. Thanks, Tobias! Will look into more with the direction.

**Comment by kkaneda** [comment]
@tschottdorf , @andreimatei , I'll close this old issue, but please let me know if there is still some work left. Thanks!
