### ISSUE TITLE
build fail cannot find package "github.com/cockroachdb/cockroach/pkg/sql/exec/types" 

### ISSUE THREAD

**Issue by netice** [cockroachdb/cockroach#33043]
build cockroachdb from git source
gentoo linux
```
Running make with -j4
GOPATH set to /var/tmp/portage/dev-db/cockroach-9999/work/cockroach-9999
go install -v execgen
bin/prereqs ./pkg/sql/exec/execgen/cmd/execgen > bin/execgen.d.tmp
bin/prereqs: cannot find package "github.com/cockroachdb/cockroach/pkg/sql/exec/types" in any of:
	/usr/lib/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/types (from $GOROOT)
	/var/tmp/portage/dev-db/cockroach-9999/work/cockroach-9999/src/github.com/cockroachdb/cockroach/pkg/sql/exec/types (from $GOPATH)
make: *** [Makefile:1465: bin/execgen] Error 1
```

**Comment by knz** [comment]
@netice thank you for your interest in CockroachDB!

The error you see is because the CockroachDB source tree is not in a good location relative go $GOPATH.

For now, it is important that the source tree is in the right location relative to $GOPATH, otherwise the build will not be successful. You do this like this:

```sh
$ go get -d github.com/cockroachdb/cockroach
$ cd $GOPATH/github.com/cockroachdb/cockroach
$ make
```


Does this help? Let us know if we can help you further.

**Comment by netice** [comment]
@knz thanks. This works! I think this shoud be added to the documents.
