### ISSUE TITLE
perf: a transaction performance test result, may be helpful

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#3304]
![sshot-2](https://cloud.githubusercontent.com/assets/7114592/11548921/535918e6-999c-11e5-986c-f9cccdb21636.png)

Deployment
3 nodes
100 range/node
1replica/range

Test Case
100 thread per node send txn concurrently
serval put operations per txn
keys/txn  on different ranges

some suggestions for improving the performance of txn:
1、decrease IO operation，so：
     a、add cache on top of rocksdb in order to apply raft log in memory and asyn batch to rocksdb. It is similar to mysql/pg
    b、use batch to decrease the number of raft message and IO operation to rocksdb. but if range is too small, there will be less chance to batch the txn operation. so I suggest that we need increase the size of range, 64M is  too small and improve the capability of txn concurrency of range. read cache and raft is bottleneck.

2、increase the rocksdb/raft IOPS.

**Comment by petermattis** [comment]
Interesting. I'm not sure about the range size being too small, but its easy enough to test larger values. See `ZoneConfig.RangeMaxBytes`.

**Comment by bdarnell** [comment]
Increasing the range size will probably help benchmarks like this, but it has other consequences that are more difficult to measure (e.g. rebalancing is more expensive and recovery is slower). I think that once we have async snapshots (#3241), the best value for `RangeMaxBytes` will likely be larger than 64MB, but it's not clear how we can determine the optimal value.

[`multiraft/storage.go`](https://github.com/cockroachdb/cockroach/blob/e046632c5685dc22b9882d58e37062489d0d5253/multiraft/storage.go#L242) currently makes a separate `Append` call for each range's log. Applying these in a single batch may help (so would appending to the log and writing the HardState in the same batch). We also process each command as a separate rocksdb batch. Combining these would improve performance, although we have to be careful: a failed command abandons its batch, but we still need to commit any successful ones. 

It's somewhat risky to buffer log entries and HardState in memory without writing to disk (since simultaneous power failure could result in data loss/inconsistency), but applying commands to the replica doesn't need to be fsync'd immediately.

**Comment by Frank-Jin** [comment]
@bdarnell yes, if the size of range becomes bigger, the async snapshots is necessary. For my opinion, we don't need reshard frequently. Actually, Range split and migration will make system performance down obviously. Maybe It's a option that we use big range and manually launch resharding.

**Comment by Frank-Jin** [comment]
We had tested cockroachdb by our e-business application，we found a problem of txn performance.
Many of our appliction's txn need write several table, for example, one of them is creating order, it needs insert records at eight tables and every records has about 4 indexes, this means a cockroach txn need insert 32 k-v,and these k-v writing operation may be distributed at different store and range.

The result is the low performance. Consider this conditon maybe very common, Do we have a good solution?

**Comment by Frank-Jin** [comment]
@petermattis 
@bdarnell

**Comment by petermattis** [comment]
@Frank-Jin Is it possible for you to provide the schema for your application and an example of the types of operations you perform on it? Failing that, could you provide an example schema and operations that show similar workloads. I can certainly come up with something matching your description, but having your precise schema and operations would make sure we're talking about the same thing.

**Comment by Frank-Jin** [comment]
@petermattis The schema for our application is a bit complex, I can give an example.
Our applicatin is user's order management system for our e-commerce site, Creating order is the most important transanction, when a user need purchase some goods, he will create an order for it.
 
The operations of this txn is as below:
begin
  insert table-user-order (four indexes)
  insert table-order-log
  insert table-prudct-info
  insert table-gift              (x indexes)
  .....
commit

The logic is very simple,but a txn need insert record to 8 table and some tables have several indexes.

**Comment by Frank-Jin** [comment]
Maybe we can place  related ranges at the same store，the problem is that even ranges is at the same store, but the txn is still distributed.  There are still a lot of random write.

I wonder if we can find solution to batch writes from different ranges at the same store.

**Comment by petermattis** [comment]
Thanks for the detail, @Frank-Jin. One optimization avenue that we're exploring is that the inserts could be performed in parallel. Currently, every statement in a transaction is performed serially, but since these inserts are all touching different tables there is no need for that. Further, because these are inserts they are not reading anything before performing the writes so we could gather up all of the writes generated by the inserts into a single batch.The scattering of the writes across ranges won't be so bad if we can get the SQL executor and KV dist-sender to make sure the writes are performed concurrently.

The tables are actually guaranteed to be in different ranges because we split ranges at table boundaries. The indexes, however, may be on the same range as the primary table data, depending on the size of the table. Support for "[interleaved](https://github.com/cockroachdb/cockroach/issues/2972)" indexes/tables is on our roadmap precisely so that we can give the developer a tool to control data locality. Interleaved tables/indexes do require the sharing of the primary key for the table, so they may not help your scenario.

**Comment by spencerkimball** [comment]
Many fixes have gone in for this problem in the past year. Notably:

#7985, #9197, #14188

I'm closing this issue. Let's reopen as necessary.
