### ISSUE TITLE
Supporting SQL queries from the browser

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3321]
@tamird mentioned that making SQL queries via protobuf/json won't be supported for much longer. Since it will take some work to re-enable SQL queries from the browser, I'm curious how important people feel it is that we support such queries. 

My understanding, though incomplete, is that since the browser doesn't support TCP, we'd need a translation layer that can send/receive HTTP or possibly use WebSockets. Currently that layer exists and lives below the Postgres wire protocol, but once that middle layer is removed, we'd need to reimplement it on top of the Postgres wire protocol separately instead (and specifically so that the browser could communicate with it directly.)

Personally I feel it's important - it's a easy way to store information and make it accessible to the frontend, not to mention an easy way to interact with Cockroach. However, @tamird and @tschottdorf suggested I create an issue to discuss the issue, since it would require some extra work to implement and we weren't entirely sure how difficult it would be.

**Comment by petermattis** [comment]
Supporting SQL queries over HTTP isn't particularly difficult, especially if we were to remove support for transactions. We could likely also remove support for multiple-statements.

**Comment by maxlang** [comment]
I suppose that's a good intermediate step, and was mentioned by @tschottdorf and @tamird as well. I'd definitely like to push for full support in the future, to allow users to run queries from the UI, even as a beta feature if it's feasible, but it could definitely be punted to the bottom of the list.

**Comment by petermattis** [comment]
Running transactions from the UI is a bad idea (note: transactions != SQL operations). Heck, running transactions from our SQL shell is problematic and doing it from the UI is only more difficult. Let's drop that idea from consideration for the beta and perhaps permanently. If someone wants to run arbitrary SQL they can fire up the SQL shell (`cockroach sql`).

**Comment by tschottdorf** [comment]
I see the value in supporting SQL queries in the UI mostly from the standpoint of necessity: we'll have a bunch of data in SQL tables that we want to render in the ui, and instead of cooking up a multitude of endpoints it makes more sense to have one "thing" that executes SQL and returns the results as JSON.
Exposing a textbox to the client, sure, why not. Looks good in a demo and maybe sometimes I want to check something quickly without figuring out my login details for the actual client.
But as @petermattis pointed out, hand-run transactions are just a bad idea if they're not in a single round-trip. Even if we did that, it would only make sense in a world that has a very rich client built into the ui, which is also something that I strongly oppose given that I doubt its utility.

I think I'm generally in favor of having a HTTP endpoint that takes a statement (or list of statements, depending on whether `sql.DB` can handle that) which would operate under the same type of security as the UI access for that user (we might need some exceptions for accessing internal tables) and which talks JSON. That should hopefully not be too much work: adding an endpoint is easy, executing the SQL against the internal server is easy, marshalling the result to JSON should have been done before. If we want to allow multiple statements in one string (perhaps with some transactions inside of them) we could still support that by reaching out to the parser and chopping up the string into multiple statements we then individually pass to `driver.Conn`, but we should save that for when it actually becomes relevant.

It avoids all of the complexity on the javascript side but still allows a lot of advanced UI features, should we want them in the future. Plus, the security story doesn't get more complicated.

**Comment by petermattis** [comment]
Right, we definitely need the UI to internally be able to send SQL queries. It would be silly to create HTTP endpoints for accessing the list of users/databases/tables/permissions/etc.

My proposal is that we take the current `sql/driver.{Request,Response}` protos and strip out support for transactions and multiple statements per request. We leave in support for placeholders (no SQL injection vulnerabilities in our javascript, right?). For the time being, @maxlang can continue using the current HTTP interface, just being careful to not use the functionality (transactions and multiple statements) that will be removed shortly.

**Comment by maxlang** [comment]
I spoke to @tschottdorf and have a much better understanding of the reasoning and limitations. This sounds good to me, I currently just depend on sending one line of SQL and receiving rows which should be easy to support.

**Comment by petermattis** [comment]
Current plan is to strip out the raw SQL query execution from the browser and instead perform JSON requests. See #4298.
