### ISSUE TITLE
sql: CHECK constraint not run properly on the result of  UPSERT INTO ... SELECT

### ISSUE THREAD

**Issue by netice** [cockroachdb/cockroach#33258]
To reproduce:

```
create table t(x int, y int, unique (x,y), constraint y_not_null check (y is not null));
create table t2(x int, y int, unique (x,y), constraint y_not_null check (y is not null));
insert into t (x,y) values (1,2);
insert into t2 (x,y) values (1,2);
upsert into t (x) select t2.x from t,t2 where t.x=t2.x;

then we got error:
ERROR:  failed to satisfy CHECK constraint (y IS NOT NULL)
```

We use this for a use case that need ```UPDATE ... FROM```which cockroachdb not support .
We follow the document [https://forum.cockroachlabs.com/t/how-to-update-one-table-from-another/2217](https://forum.cockroachlabs.com/t/how-to-update-one-table-from-another/2217) to get our use case work;

**Comment by knz** [comment]
@netice Thank you for your report. However in this case the behavior is correct / well-defined.

The UPSERT statement is different from the INSERT ON CONFLICT because it will always overwrite the existing rows with the new values. So if we take the example you give:

```
upsert into t (x) select t2.x from t,t2 where t.x=t2.x;
```

The `select` query will compute a result that is equivalent to `values (1)`

Then `UPSERT INTO t(x) VALUES (1)` will be executed,

which is equivalent to `UPSERT INTO t(x, y) VALUES (1, DEFAULT)`

Now the DEFAULT value for `y` is NULL. So the CHECK constraint fails.

To solve this problem you need to either:

- change the DEFAULT value for `y`, or
- use a `SELECT` query that computes a value for `y`, for example `UPSERT INTO t(x,y) SELECT t2.x, ... FROM t,t2 where t.x=t2.x`

Does this help?

**Comment by netice** [comment]
@knz thank you. Is that  UPSERT update all columns and if we do not offer an value for some columns is will use default value to update these columns?

**Comment by knz** [comment]
> @knz thank you. Is that UPSERT update all columns and if we do not offer an value for some columns it will use default value to update these columns?

yes
