### ISSUE TITLE
some import/restore tests generate IllegalLeaseIndex errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#33453]
A bunch of restore and import tests seem to generate lease index errors. I think it's surprising... Is it?

The error is generated here, for the application of a command past its lease index:
https://github.com/cockroachdb/cockroach/blob/c52610a6c2a69ee621942b062056c24a7c97bf69/pkg/storage/replica.go#L5248

A factoid is that `replica.refreshProposalsLocked()` does not seem to be called (that's another place where a similar errror be generated) in one of the tests that I've played with.

The tests exhibiting this seem to be:
```
TestBackupRestoreSystemJobsProgress 
TestImportPgDump
TestImportPgDump/read_data_only 
TestImportPgDump/single_table_dump
```
They can be triggered by putting a panic where the error is generated. The tests otherwise pass.

@tbg Are you surprised / do you reckon this is this worth investigating? Feel free to pass it back too.

**Comment by tbg** [comment]
I looked into this in TestBackupRestoreSystemJobsProgress. There, it *is* due to a reproposal from https://github.com/cockroachdb/cockroach/blob/8d1ffc2a4fba1c08d30ef9d635007f9545a8b6b2/pkg/storage/replica.go#L4279-L4286.

Basically the range splits, the right hand side immediately receives a proposal at the new leader, but then the first thing that pops out of Raft is the empty entry which prompts a reproposal of the command, which then triggers the behavior you're seeing. This is a little silly, since we also know that more commands are likely to pop out immediately after the empty command and the reproposal may not make sense, but it's difficult to tell (well, you could tell something if you're colocated with the leader, as you often are).

Could you double check that you saw this behavior without the reproposal?

**Comment by andreimatei** [comment]
> Could you double check that you saw this behavior without the reproposal?

You're right, there are reproposals. Closing this in favor of #33466
