### ISSUE TITLE
sql/sem/tree: TestPrettyData takes 18s

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#33649]
TestPrettyData takes 18 seconds. Is there any way we could trim down this test?

**Comment by RaduBerinde** [comment]
Still wasting a bunch of time because of this..

**Comment by jordanlewis** [comment]
Just out of pure curiosity I pprofed this test, all of the time is spent retrieving and setting values in the `memoiDoc` hashmap.

The problem with this algorithm is that it's essentially redoing a ton of work, because of how Go hashmaps are done. Each time you insert an `iDoc` into the map, the entire `iDoc` tree must be re-hashed. There is no memoization of any component of the `iDoc` tree, so the algorithm is something like `O(n^2)` at the best - each new parent of a tree requires redoing the entire child tree's hashing work.

After writing this, I realized that there must be something else going on because hashmaps use regular equality for their hash keys in Go, and equality doesn't follow pointers. Looking at one of the interfaces in `iDoc`, I noticed that many of its implementations have struct, not pointer receivers. So that's the problem - I'll send a PR and I think this will go away completely.

**Comment by jordanlewis** [comment]
Before: 29.236s
After: 17.613s

**Comment by jordanlewis** [comment]
Oh... the real problem with this test is that it runs `n+10` workers per test, where `n` is equal to the number of characters in the string... that's a little excessive haha, I guess you're probably right about the nightly, unless @mjibson @knz think we can make that a little less exhaustive.
