### ISSUE TITLE
ui: move all frontend timezone logic to the server

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3365]
The server is better able to handle timezones vs the frontend which would require frequent updates.

**Comment by maxlang** [comment]
Specifically, remove moment-timezone

**Comment by mrtracy** [comment]
Closing, I don't think this is relevant; the UI is display-only, and all times on the server should be stored (and likely returned to the client) in UTC, and converted only to a local time zone when displayed to the user (and right now, the Admin UI is designed to display all times in UTC with no local time zones).  I'm honestly not sure what this issue was referring to, closing.

**Comment by bdarnell** [comment]
This issue was referring to the use of moment-timezone, which embeds a copy of the zoneinfo database and therefore requires regular updates. Moving timezone-related logic to the server would let us use the server's copy of the zoneinfo database (which can be updated without replacing the cockroach binary). But it looks like we're no longer using moment-timezone, so this is moot. (and even if we change back to using local time instead of UTC, it seems like we should be able to use browser functionality to get the local time instead of embedding zoneinfo)
