### ISSUE TITLE
storage: TestWedgedReplicaDetection takes 10s

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#33654]
I'm about to skip it on test short.
I don't know why it takes so long; I haven't investigated. It does not appear to be a new thing (i.e. not caused by the recent cluster bootstrap changes - also the test is configured to run with a single range).
Perhaps it's expected to take so long...

@petermattis are you interested in taking a look?

**Comment by petermattis** [comment]
The reason this test takes 10s is because that is the value of the `MaxQuotaReplicaLivenessDuration` constant. Change that constant to 5s and the test takes 5s. Perhaps that constant should be changed into a field in `base.RaftConfig`. I won't have time to do this any time soon, but the work should be straightforward. Sending this back your way @andreimatei.
