### ISSUE TITLE
server: TestServerStartClock is flaky

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#33719]
```
> make stress PKG='./pkg/server' TESTS=TestServerStartClock

--- FAIL: TestServerStartClock (0.19s)
    server_test.go:161: time: server 1547494457.648957000,1 vs actual 1547494457648957000

ERROR: exit status 1

88 runs completed, 1 failures, over 4s
context canceled
FAIL
```

**Comment by tbg** [comment]
Repro'ed.. how is it that this fails so quickly but never under nightly stress?!

**Comment by tbg** [comment]
This test is weird. I assumed it would use a manual clock because that would make sense, but it doesn't (and running a whole server with a manual clock is basically a bad idea).

The test starts a server, runs a command, gets the wall clock and makes sure that the hlc isn't ahead of the wall clock. Under stress, sometimes our call to `hlc.Now()` sees the same walltime as before and so there's a logical tick, and the test barfs. But that's perfectly fine, in fact this test would fail 100% of the time if the clock were manual.

Going to send a PR.
