### ISSUE TITLE
build: roachprod-stress{,race} is broken

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#34083]
The roachprod-stress{,race} target essentially tries to run this:

```
$ make test PKG=./pkg/storage/ GOFLAGS='-v -c -o foo.test'
Running make with -j8
GOPATH set to /Users/tschottdorf/go
Detected change in build system. Rebooting Make.
unable to detect go version: go: parsing $GOFLAGS: non-flag "foo.test"
```

Manually this works:

```
go test -c -o .test ./pkg/util/stop/
```

(I'm not sure if `.test` is intentional, I think that's a buglet in `$(notdir $(PKG)).test"`)

But this does not:

```
GOFLAGS='-c -o .test' go test ./pkg/util/stop/
go: parsing $GOFLAGS: non-flag ".test"
```

But this one does:

```
GOFLAGS='-c -o=.test' go test ./pkg/util/stop/
```

So I think adding a `=` is all we need.

**Comment by tbg** [comment]
I sent #34084 to make it "work" again but the two other issues remain: why is it using GOFLAGS from the env and what about `$(notdir $(PKG)).test`.

**Comment by petermattis** [comment]
> (I'm not sure if .test is intentional, I think that's a buglet in $(notdir $(PKG)).test")

It is a buglet that I haven't bothered to fix (and seems relatively harmless). The problem is that you specified `./pkg/storage/` with a trailing slash. If you specified `./pkg/storage` then the `notdir` expression would have produced `storage.test`. I'll fix at some point. I just have to peruse the make functions to find the right one. Or perhaps we should always name the binary `roachprod-stress.test`.

**Comment by tbg** [comment]
🙇 thanks @petermattis for the fix
