### ISSUE TITLE
Serial type start default value is not 1?

### ISSUE THREAD

**Issue by lunny** [cockroachdb/cockroach#34177]
**Describe the problem**

I'm testing cockroachdb v2.1.4 work with [xorm](https://github.com/go-xorm/xorm) which tests PASS with postgres. I found some tests failed because the returned serial id should be 1 but not.

**To Reproduce**

`docker run -d -p 26257:26257 -p 18080:8080 cockroachdb/cockroach:v2.1.4 start --insecure`
 
And check out the PR https://github.com/go-xorm/xorm/pull/896 and run `./test_cockroach.sh`

**Expected behavior**

The returned serial should be 1.

**Additional data / screenshots**

--- FAIL: TestInt16Id (0.20s)
Here is some failed logs
```Go
    session_pk_test.go:196: converting driver.Value type int64 ("419936459461492737") to a int16: value out of range
panic: converting driver.Value type int64 ("419936459461492737") to a int16: value out of range [recovered]
	panic: converting driver.Value type int64 ("419936459461492737") to a int16: value out of range
```

**Environment:**
 - CockroachDB version [2.1.4]
 - Server OS: [Mac/Linux]
 - Client app [`xorm`, github.com/lib/pq]

**Comment by knz** [comment]
@lunny thank you for your report. For performance reasons, CockroachDb does not use SQL sequences by default when you use the type SERIAL.

This is actually a pretty wide topic of conversation and since you're focused on that particular test suite I recommend that you add the following parameter to your connection URL: `&experimental_serial_normalization=sql_sequence`

this will enable the use of sequences and make this particular test pass.
