### ISSUE TITLE
storage: more discriminate write backpressure on large ranges

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34210]
@nvanbenschoten I'd like to discuss a couple of thinks around `backpressurableReqMethods`:
https://github.com/cockroachdb/cockroach/blob/5c1ffd19e0dc7e99c1d4425949899d0fab88af19/pkg/storage/replica_backpressure.go#L50

1) Should `QueryIntent` be in that list?
2) Should we exempt rollbacks?
3) Should we exempt commits?

**Comment by andreimatei** [comment]
> QueryIntent doesn't write, so why would it be on the list?

Well because it's bundled up with EndTransaction, isn't it? So putting ET on the list without it I think doesn't make sense, since the batch is not backpressured if some requests don't match the list.

**Comment by nvanbenschoten** [comment]
> Should QueryIntent be in that list?

No, I don't think it should be.

> Should we exempt rollbacks?

We could, yes. 

> Should we exempt commits?

Again, we could. I guess removing `EndTransaction` entirely from `backpressurableReqMethods` would be fine. I'll do that, along with `BeginTransaction` since it's not used anymore anyway.

> What I don't understand is why ClearRange is on the list. ClearRange strictly removes data, so.. isn't that helping?

Good point, `DeleteRange` writes data first, but `ClearRange` doesn't. I'll remove that.
