### ISSUE TITLE
distsqlrun: eliminate queuing in flowScheduler and tune max_running_flows

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#34229]
**Describe the problem**

In the face of a large number of flows today's distsqlrun.flowSchedule begins queuing requests for processing. This queueing leads to delays in processing incoming flow requests. At a certain point these requests will be delayed long enough that the upstream node expecting a connection will time out (default 10s) which results in the client receiving an inscrutable `no inboud stream connection` error. See #27746. While some amount of queuing might be acceptable, today there is no limit on queuing or on how long requests might be delayed. Rather than work through exactly what the queuing behavior ought to be, this issue suggests we should reject incoming requests which today might be queued. This will lead to faster failure with a more reasonable error.

**To Reproduce**

Run a workload which creates a large number of distsql flows. 

**Expected behavior**
The client should receive an error related to resource exhaustion.

**Additional context**
Wrapped up in this issue is the question of what is the right number of max_running_flows before rejection occurs. Coming up with a more sophisticated acceptance control mechanism is out of scope for this issue but it is important that this change not break existing workloads. 

Jira issue: CRDB-4659

**Comment by sumeerbhola** [comment]
@lunevalex 
What is the thinking behind closing this -- is the current value of 500 for `sql.distsql.max_running_flows` high enough for this not to be a practical problem? And if that limit is never hit, is there a reason it even exists -- is it because we do see some short amount of queueing that protects the system?

**Comment by lunevalex** [comment]
@sumeerbhola we trying to clean up the KV Backlog to make it useful for planning. To help with that we declared a limited bankruptcy on issues that have not ben touched by anyone in over two years. All issues that this happened to are marked with X-stale and can be found here https://github.com/cockroachdb/cockroach/issues?q=+is%3Aissue+project%3Acockroachdb%2Fcockroach%2F22+label%3AX-stale+. I'll re-open this back as it looks like we may be looking into this as part of the admission control work.

**Comment by yuzefovich** [comment]
I think the time is ripe for removing this queueing in the flowScheduler altogether.

(Note that the whole discussion about the flowScheduler is only relevant to the _remote_ DistSQL flows - all flows that are scheduled on the gateway of distributed plans as well as all non-distributed plans don't go through the flow scheduler.)

My reasoning is that we now have an actual admission control in place, so this queueing - which served as a form of admission control previously - is no longer needed. I've reviewed most of the issues linked to this one, and I believe [this comment](https://github.com/cockroachdb/cockroach/issues/27746#issuecomment-455288555) from Peter has the succinct explanation for why we had this queueing:
> We're limiting network and CPU use as well, though RAM is probably the most important (network and CPU will get slower, RAM will hit a wall and cause the node to die).

The actual admission control now directly (mostly) takes care of
- the network usage through `SQLSQLResponseWork` queue
- the CPU usage through `SQLKVResponseWork` queueing (mostly, I think).

Sumeer also [pointed out](https://github.com/cockroachdb/cockroach/issues/34229#issuecomment-952184839) some deficiencies in admission control in relation to this issue:

> - The basic framework includes SQLStatementLeafStartWork which I think would map to starting of these remote DistSQL flows, but the integration code does not exist. This is tracked in https://github.com/cockroachdb/cockroach/issues/65948

It doesn't seem like a blocker to me for removing this flow scheduler queueing since already implemented admission control queues do kick in.

> - There is no dynamic adjustment of the tokens for SQLStatementLeafStartWork. My current understanding is that the only reason to limit the start is to control memory usage (CPU and IO usage is already controlled in a more fine-grained manner via the kv, sql-kv-response, sql-sql-response requests). btw, what originally motivated `max_running_flows`? My current thinking is that we should use the `rootSQLMemoryMonitor` to inform admission of such flows -- it could either take the form of dynamically computing a token limit, or keep starting new flows until say 80% of the limit and then fallback to consulting the dynamic token limit.

Neither the admission control nor the queueing in the flow scheduler prevent the nodes from OOMing, however, over the years we have become much better with the memory accounting which serves as the pushback on the RAM usage when exceeding `--max-sql-memory` budget. It seems independent of either.

In 22.1 (as well as in a backport to 21.2) we already increased the default value of `max_running_flows` from `500` to `128 * N(cpus)`, and I believe we haven't seen any fallout from that. Removing the queueing altogether to me seems like a less scary change than bumping up that default value was.

----

In order to see how CRDB would behave when overloaded with remote DistSQL flows I ran `kv100` workload with concurrency 16384 on a 3 node roachprod cluster with 4 cpus each (meaning `max_running_flows=512`). `kv` table had 2.5m of rows that were split into 16 ranges evenly distributed across the nodes. I also set `sql.defaults.distsql=on` so that each point read would be distributed.

Here is what I got with the flow scheduler's queueing in place:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  300.1s        0        2726963         9086.3   1799.2    939.5   6174.0   8589.9  27917.3  
```
and with that queueing eliminated:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  300.1s        0        3163805        10543.5   1506.8    570.4   5368.7  10737.4 103079.2  
```

As we can see the overall throughput increased at the expense of increase in the tail latencies while reducing the average latency. I've done similar experiments with concurrencies of 4096 and 8192 and obtained similar results. Here are some of the relevant metrics of the runs with 16384 concurrency:
![Screen Shot 2022-07-22 at 12 46 22 PM](https://user-images.githubusercontent.com/5135385/180516510-50b61622-ca42-4ee8-94c9-29ca3f04eb82.png)
![Screen Shot 2022-07-22 at 12 46 50 PM](https://user-images.githubusercontent.com/5135385/180516570-0e92b4be-00a8-46d9-8cb8-e6bc30c18b18.png)
![Screen Shot 2022-07-22 at 12 47 24 PM](https://user-images.githubusercontent.com/5135385/180516638-94d2e02d-8e60-4eed-bbd3-6aad1c7d0004.png)
![Screen Shot 2022-07-22 at 12 47 49 PM](https://user-images.githubusercontent.com/5135385/180516707-93908418-b8bb-483b-823b-d9d117c344b3.png)

To me the numbers and the graphs show that the admission control does its job well enough for us to remove the queueing in the flow scheduler, but I'm curious to hear from others. Thoughts? cc @sumeerbhola @ajwerner @irfansharif cc @cockroachdb/sql-queries

**Comment by sumeerbhola** [comment]
Looks fine to me. It is interesting that the latter half of the run where there is no `max_running_flows` has a runnable goroutines per CPU of ~100, which is higher than the limit admission control is trying to achieve (`admission.kv_slot_adjuster.overload_threshold` is 32). I suspect this is because this workload consumes significant CPU in the SQL layer, and we are seeing the effects of what we were discussing in https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1657286381660829

**Comment by yuzefovich** [comment]
We decided to take a conservative approach with removing this queueing behavior. In 22.2 we will introduce a cluster setting that controls whether the queueing is enabled or not (disabled by default) so that we have an escape hatch in case we missed some cases in this discussion, and then in 23.1 we'll remove the queueing altogether.

Also, #84932 has already added a small memory reservation whenever a new remote DistSQL flow is being scheduled which improves our stance on the RAM usage stability.
