### ISSUE TITLE
intentresolver: split up work done on behalf of GC queue by transaction

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#34227]
**Describe the problem**
@andreimatei  discovered in his analysis of https://github.com/cockroachdb/cockroach/issues/34082#issuecomment-457025248 determined that the GC queue is not making progress which is problematic. The proximate cause of the lack of progress is a timeout while attempting to push transactions associated with intents which need to be resolved. The current behavior is that all of the transactions needing to be resolved are put into a single, potentially quite large batch. 

**To Reproduce**

We do not currently have a reproduction. A proposed strategy is to create a transaction with a large number of intents due to a large number of transactions and see how big we can go. Ideas on how to test a potential solution would be appreciated.

**Expected behavior**

We make progress on the GC queue.

**Potential solutions**

Put a limit on the number of transactions we attempt to push in a batch request. This may be sufficient to alleviate the timeout and likely is an adequate solution but in the case of any failure of pushing any of the transactions none of the intents will be resolved. 

A further change to address this problem might be to instead group the intents by transaction and split the work of pushing and intent resolution based on a chunk of transactions. This way even if one of those chunks fails to push its transactions, the other chunks which succeed will proceed to resolving their intents. A cost to this approach is that intent resolution will have worse batching properties. Given that GC queue work is asynchronous and should rarely encounter intents anyway, that performance consideration is not likely important.

**Comment by tbg** [comment]
I had some unmerged work that would expose a service with which you could write raw k/v keyspace. Back in the day I used this to create ranges that were chock full of whatever garbage I desired.

I think that instead of this, you could tap into @andreimatei's new knowledge about cluster bootstrap and add a hook (env var?) that can bootstrap the cluster with various profiles. One of them could be "give me a range that has 200k intents each written by a different transaction anchored on some other range". Taken to the extreme, we could make a cockroach debug command that spits out a corresponding data directory which we could then use for manual and acceptance testing.
