### ISSUE TITLE
Use the WebUI to identify the correct node name and ip address of a troubled node

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34246]
**Describe the problem**

The webui shows the ip address from aws and labels nodes such as node 1, node 2, node 3 etc. Unfortunately, but these node names and ip address don't actually correspond to the underlying nodes. This is a problem when a node crashes and you need to learn more about it--you can't identify the correct node to pull logs or stderror from using the webui. 

**The current workaround is:**
![image](https://user-images.githubusercontent.com/22278911/51755037-ba522780-208b-11e9-94c2-afe09f869e75.png)
Then you can use that IP to find the right IP:
*Generic*
`roachprod list -d -m | grep <ip from web>`
*Specific:*
`roachprod list -d -m | grep 172-31-41-232`
`andy-nomerge-0003 ip-172-31-41-232.us-east-2.compute.internal 172.31.41.232 18.191.36.171`

Then use the right IP to get the stderr 
*Generic:*
`roachprod get $CLUSTER:<node> logs/cockroach.stderr <name of file on your machine>`
*Specific:*
`roachprod get $CLUSTER:3 logs/cockroach.stderr 124deadnode`

Then open the file and drag and drop to github.

**Comment by ajwerner** [comment]
A problem here is that the node currently does not know about its external IP, this routing is handled entirely above the node. The fact that it has an external IP is a property of the other infrastructure that cockroachdb knows nothing about.

It's not as straightforward as just displaying some value that the node knows. We'd need some way to inform the nodes of their external IPs in order to use it in the web UI.

**Comment by petermattis** [comment]
The `roachprod start --sequential` flag can be used to ensure that roachprod node indexes match cockroach node IDs. That can reduce confusion here as it allows you to see `n1` in the web UI and know that corresponds to `<cluster>:1` on the command line.
