### ISSUE TITLE
storage: large raft log not truncating for unknown reason

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34269]
I look at a cluster of 6 nodes, with two of them being down. One range was under-replicated. The replication queue would like to upreplicate it but it's not because the Raft log is considered too large (the log is 50MB and the cutoff is 16MB I think). There's tens of thousands of log entries.
The Raft log is not being truncated because the Raft log queue does not consider it should queue it. Why no is the million dollar question. The queue is aware of the size of the log and correctly uses it to assign a high score. We unfortunately don't have the `truncateDecision` because we're never logging it if it's negative (I'm fixing that). I can only assume that the truncation decision is circularly related to the under-replicated status, but I don't have a smoking gun.
The only information I could get about the opinion of the raft log queue is the following:

![image 1](https://user-images.githubusercontent.com/377201/51778994-b4cc0000-20d2-11e9-9cc4-b6b02b7c605e.png)

Here's the admin UI report for that range.
[r28024-PM.pdf](https://github.com/cockroachdb/cockroach/files/2798269/r28024-PM.pdf)

Here's the range info from a debug.zip.
[28024.txt](https://github.com/cockroachdb/cockroach/files/2798275/28024.txt)

Here's a debug.zip (internal only)
https://drive.google.com/open?id=1T_cGn_8NlztXvHHOgTroLl870kuI2iTD

Another interesting thing going on in that cluster is that some stores seem to be periodically throttled in the `storePool` of the node with the large Raft log (`n2`), because they seem to be refusing snapshots (and I'm not talking about the nodes that are dead). This can be seen in the following trace taken from the Manuel Enqueue page asking the replication queue.
https://gist.github.com/andreimatei/eeacd0a79eec809e2494961fb9f19be3

However, I have no reason to believe that the throttling has anything to do with the refusal to truncate. The throttling might have independently been a problem for the up-replication.

Tobi, I believe you know the truncation decision code the best...

cc @petermattis

**Comment by tbg** [comment]
I have to verify this in code but in theory I think something like this happens:

Say a preemptive snap is generated at index 1000 and the Raft log is long, say index 10 is still there. The snapshot will have to include the Raft log from 10..1000 today. I don't think there's a particular reason for this, but our TruncatedState moves in a replicated fashion (technically each replica could truncate its own log to whatever seems reasonable to it).

This means that unless the log gets truncated, the snapshots will fail (due to including the long log).
Now the Raft log queue wants to avoid running a truncation that cuts off an in-flight snapshot. All of the existing replicas are up-to-date, so the truncation index it seeks out is basically the last index (which is that of the inflight snapshot). By truncating that index, the snapshot would be cut off from the log (this doesn't seem true exactly, it seems that it would line up perfectly fine and thus be OK, but let's assume there's a one-off somewhere in my thinking). So the Raft log queue decides not to truncate there, and in fact I think it decides not to truncate at all, though realistically it could truncate any index below the index of the snapshot.

Going to take a look at the code now.

**Comment by petermattis** [comment]
On v2.1.3, we compute the target size for truncation as:

```
	// A "cooperative" truncation (i.e. one that does not cut off followers from
	// the log) takes place whenever there are more than
	// RaftLogQueueStaleThreshold entries or the log's estimated size is above
	// RaftLogQueueStaleSize bytes. This is fairly aggressive, so under normal
	// conditions, the log is very small.
	//
	// If followers start falling behind, at some point the logs still need to
	// be truncated. We do this either when the size of the log exceeds
	// RaftLogTruncationThreshold (or, in eccentric configurations, the zone's
	// RangeMaxBytes). This captures the heuristic that at some point, it's more
	// efficient to catch up via a snapshot than via applying a long tail of log
	// entries.
	targetSize := r.mu.state.Stats.Total()
	if targetSize > r.mu.maxBytes {
		targetSize = r.mu.maxBytes
	}
```

On master, this code is now:

```
	// A "cooperative" truncation (i.e. one that does not cut off followers from
	// the log) takes place whenever there are more than
	// RaftLogQueueStaleThreshold entries or the log's estimated size is above
	// RaftLogQueueStaleSize bytes. This is fairly aggressive, so under normal
	// conditions, the log is very small.
	//
	// If followers start falling behind, at some point the logs still need to
	// be truncated. We do this either when the size of the log exceeds
	// RaftLogTruncationThreshold (or, in eccentric configurations, the zone's
	// RangeMaxBytes). This captures the heuristic that at some point, it's more
	// efficient to catch up via a snapshot than via applying a long tail of log
	// entries.
	targetSize := r.store.cfg.RaftLogTruncationThreshold
	if targetSize > *r.mu.zone.RangeMaxBytes {
		targetSize = *r.mu.zone.RangeMaxBytes
	}
```

The `v2.1.3` code looks problematic. In the customer's issue, the total size of the range is 56.6 MiB while the Raft log size is 53.3 MiB. The Raft log is not considered "too large". This feeds into the truncate decision code:

```
		probing := (progress.RecentActive && progress.State == raft.ProgressStateProbe)
		if probing && decision.NewFirstIndex > decision.Input.FirstIndex {
			decision.NewFirstIndex = decision.Input.FirstIndex
			decision.ChosenVia = truncatableIndexChosenViaProbingFollower
		} else if !input.LogTooLarge() && decision.NewFirstIndex > progress.Match {
			decision.NewFirstIndex = progress.Match
			decision.ChosenVia = truncatableIndexChosenViaFollowers
		}
```

The down replica is in `ProgressStateProbe`, but not recently active. So we fall into the second branch and limit the truncation to 82277. Unfortunately, that doesn't explain why we haven't truncated to 82277. 

I think @tbg's theory about a pending snapshot preventing truncation is more likely. Something I'm confused about looking at that code is that we seem to prevent truncation before the Raft applied index. In this case, that index is 84509.

**Comment by tbg** [comment]
> The v2.1.3 code looks problematic. In the customer's issue, the total size of the range is 56.6 MiB while the Raft log size is 53.3 MiB. The Raft log is not considered "too large". This feeds into the truncate decision code:

Yikes, take a look at the backport ffeb645b4fda666406a1fcaaa0ca3b1af3348a92 and compare to the original https://github.com/cockroachdb/cockroach/pull/32437/files -- I messed up the cherry-pick. PRs are out. This isn't the root cause, though.

**Comment by tbg** [comment]
Here's the annotated progress:

```
"progress": {
  "1": { // leader, n2
    "match": 82346,
    "next": 82347,
    "state": "ProgressStateProbe"
  },
  "2": { // follower, n5
    "match": 82346,
    "next": 82347,
    "state": "ProgressStateReplicate"
  },
  "3": { // dead node, n3
    "next": 82277,
    "state": "ProgressStateProbe",
    "paused": true
  }
}
```

What sticks out here is that the leader is in ProgressStateProbe. It's also recently active (duh) so the following code makes this truncation out to the first index:

https://github.com/cockroachdb/cockroach/blob/335194315341b6727da86eb282dda0374c9ab0cf/pkg/storage/raft_log_queue.go#L341-L344

In effect, not truncating at all.

So, the root cause is that the leader is stuck in ProgressStateProbe instead of ProgressStateReplicate. Luckily I've seen and fixed this bug before:

https://github.com/etcd-io/etcd/commit/5c209d66d2ab8a5de7a33a61a1f90c4a4caefd7c

Our Raft version on 2.1.3 is lacking more fixes than that. It also hasn't picked up https://github.com/etcd-io/etcd/commit/dac8c6fcc05ba42a8032d5b720f6c1704965c269, which essentially wedges the Raft group if triggered. We remedied this in v2.1.4, which picks up everything (and is basically equal to `master` upstream).

For the user, restarting the leader node (n2) should do the trick. Ideally, of course, the cluster would be upgraded to v2.1.4 which shouldn't exhibit this problem in the first place.

**Comment by tbg** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/34287 to discuss not sending the past Raft log in snapshots and how to get there.

**Comment by tbg** [comment]
@andreimatei, could you check my reasoning and communicate the solution to the user?

**Comment by andreimatei** [comment]
done. So we're done here, right? Closing.

**Comment by tbg** [comment]
Yep, thanks for looking into this.

**Comment by RaduBerinde** [comment]
Looks like we have the same problem with 2.1.4 (a node was taken down, and a bunch of ranges didn't upreplicate because the raft log was to large).

2.1.4 does not include #34284. @tbg do you think we should try again with a one-off build that contains that?

**Comment by tbg** [comment]
Do you have a Raft status of an affected range? #34284 is a good change but without it the log should still truncate if it is large enough to block snapshots. I'd wanna take a look at the available data first before making a suggestion. Perhaps there's a new bug.

**Comment by tbg** [comment]
Looking at the associated new debug zip, I can see from the problem ranges report that range 36078 is underreplicated. Looking at the range status, I see a Raft log size of 53929414bytes ~ 54mb, which would be below the threshold in #34284. In that sense, that PR would apply. Interestingly the Raft log size limit during snapshot receipt is 16777239 ~ 16mb which is much more aggressive than I thought (but now remember is the right one - it's 4 times the size at which the log queue would ordinarily start truncating aggressively, which it doesn't now due to the bug).

Looking further though, the descriptor of that range does have three members, but only two of them claim (if the debug zip is to be trusted) that they have a replica. We have n6/replicaID=1 n1/replicaID=5 n4/replicaID=3 and only n4 and n6 have the range (n4 is leader). In fact the debug zip doesn't have anything for `n1` at all, so either the node is down or there is a problem relating to Gossip:

> rpc error: code = Unknown desc = unable to look up descriptor for n1

It'll be helpful to clarify the status of n1, but I assume from your post @RaduBerinde that n1 is down in this scenario.

n4 shows the RaftStatus as follows, indicating essentially that nothing is known about n1. This alone would also prevent a log truncation if n1 is regularly contacting the leader n4. It isn't supposed to be doing that (it's down) but perhaps the code is being silly in this case.Normally my suggestion would be to send r36078 through the raft log queue manually (admin ui) but there's a bug that doesn't log the decision if it is a negative one. It is likely still worth doing to see whether that truncates the log (it probably won't or it would've happened already -- there are way too many entries to not truncate).

```
    "progress": {
      "1": {
        "match": 3191656,
        "next": 3191657,
        "state": "ProgressStateReplicate"
      },
      "3": {
        "match": 3191656,
        "next": 3191657,
        "state": "ProgressStateReplicate"
      },
      "5": {
        "next": 3191656,
        "state": "ProgressStateProbe",
        "paused": true
      }
    }
```

Even with the size bug, I still don't understand why it's not truncating. It really should be, since the follower on n1 isn't live.

**Comment by tbg** [comment]
Ok, I think I have it. We're looking at the status for replicaID=5. Notice how `Match == 0` (which makes sense; we don't know about this follower because it's not responding).

Enter this code:

https://github.com/cockroachdb/cockroach/blob/335194315341b6727da86eb282dda0374c9ab0cf/pkg/storage/raft_log_queue.go#L341-L348

`probing` will be false since the follower isn't active. Also, `input.LogTooLarge()` is `false`. Obviously also `decision.NewFirstIndex > 0`. So we go ahead and set out prospective truncation index to zero, which turns this truncation into a noop.

Silly bug. I introduced this 6d4bf7a3f79f79b85ced5b07647a7867f21689be and will fix it tomorrow if nobody beats me to it.

Also, it turns out that the upgrade from 2.1.3 to 2.1.4 didn't do anything; I think it was this bug all along. This is because of this code:

https://github.com/cockroachdb/cockroach/blob/335194315341b6727da86eb282dda0374c9ab0cf/pkg/storage/raft_log_queue.go#L150-L155

which works around the bug and is in 2.1.3. So the previous problem was likely the same one as this one, except I didn't realize.

If a hotfix is in order, #34284  should fix it because it prevents taking the branch that prevents the truncation.

**Comment by rkruze** [comment]
In the recent debug zip n1 is down.
