### ISSUE TITLE
jobs: garbage collect old CreateStats jobs

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#34377]
Once PR #34279 merges, enabling the cluster setting `sql.stats.experimental_automatic_collection.enabled` has the potential to create **many** CreateStats jobs. This has a couple of implications:

1. The `system.jobs` table may grow very large over time, possibly affecting the performance of new jobs. This can be addressed by simply deleting all jobs (or all `CreateStats` jobs) over a certain age.

2. The Jobs view on the AdminUI may become cluttered. This is somewhat mitigated by the fact that there is a "TYPE" dropdown, but if a user wants to see their own manual runs of `CREATE STATISTICS`, they are likely to be drowned out by all the automated runs. The question is: should the Jobs view even show the automated `CreateStats` jobs? Or perhaps there should be two types: `AutoCreateStats` and `CreateStats`?

Any thoughts from members of the AdminUI team or people who are familiar with the jobs infrastructure would be appreciated!

cc @danhhz, @couchand, @piyush-singh

**Comment by piyush-singh** [comment]
cc @celiala we should discuss the best way to handle this in the admin UI. Might need to consult with @vilterp since he touched this page most recently, I believe.

@rytaft we should probably consider the UX impact for the SQL shell as well (via `SHOW JOBS`): this could rapidly become unwieldy in the constrained space of a terminal. cc @awoods187 for that consideration. Whichever route we decide to opt for, we should be consistent across interfaces - `SHOW JOBS` and the admin UI should display the same values to users.

**Comment by rytaft** [comment]
Sounds good -- let me know how I can help. Thanks!

**Comment by piyush-singh** [comment]
cc @rolandcrosby based on conversation in person

**Comment by dt** [comment]
See also #34725
