### ISSUE TITLE
SQL: Reconsider Reserved ID Ranges for Table Descriptors

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#3444]
In our current system, special semantics on metadata tables (e.g. SystemDB) are enforced using "Reserved "descriptor ID ranges at the beginning of the ID space; for example, "system" tables are identified by having an ID <= MaxSystemDescriptorID.

The difficulty comes when we need to divide the reserved space into subsections; for example, we are dividing the currently reserved space into two sections - the first will house SystemDB and its tables (the contents of which are gossiped), while the second section will contain other internal tables which are not gossiped, but do have special semantics (e.g. cannot be dropped).  Using reserved-range subdivision will not work in the future when the schema is locked down.

We should consider a different system for assigning special properties to these tables if possible.

**Comment by petermattis** [comment]
I'm pretty sure we're gossiping more than necessary right now. The lease
table does not need to be gossiped. The descriptor table only needs the
version for each descriptor gossiped, not the entire descriptor. Would be
good to trim down our gossip traffic while figuring out this issue.

**Comment by bdarnell** [comment]
Transferring my comments from #3425: The gossiped tables are loaded in bulk, so it is helpful to give them a reserved descriptor range so they are contiguous at the KV level. The need for a reserved descriptor range is less clear for non-gossiped tables, but one thing it gives us is the ability to control all system tables with a single zone config. It's unclear how useful this is, though, since the reserved tables include both metadata tables (which are small and may want a higher replication factor for availability) and log/timeseries tables (which are large and don't need as much replication).

**Comment by petermattis** [comment]
#3778 reworked the reserved ID range and moved the lease table out of the `SystemConfig` range. It is useful for the non-gossiped system tables to have statically allocated IDs because various tests assert the ID values for tables that are visible at startup. While those tests could be fixed, it doesn't feel worth it at this time.

I think the current setup is fine for now.
