### ISSUE TITLE
Disallow splits within SQL rows

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3461]
Distributed SQL processing will likely benefit from having all data for a given row in the same range. This is a bit speculative, but since range merges are a long way off (probably further than distributed SQL), it would be a good idea to avoid making splits that we will later regret. When choosing split keys, we should look into the key structure and ensure that we do not split between columns (or column groups with #3435) of the same row.

**Comment by petermattis** [comment]
I think this would be worthwhile as well. It would also ensure that single row operations only affect a single range and are thus candidates for the 1PC optimization.

**Comment by BramGruneir** [comment]
Is it not possible for a single row to be significantly larger than our 64 MiB limit?

**Comment by petermattis** [comment]
What scenario are you imagining for a large row that wouldn't also apply to a single large column?

**Comment by BramGruneir** [comment]
What our max size for a varchar, text or xml type?  Do we have a way of splitting up a single element if it gets too big?

**Comment by tschottdorf** [comment]
I think it's understood (at least at this point) that CockroachDB isn't going to be a good fit for storing blobs, and that a column should occupy much less data than a Range can hold.
Also think we should avoid such splits.

**Comment by BramGruneir** [comment]
That's fine.  But we should outline our max sizes then.
Also, I can envision some very bad schemas that make each row huge.  I think splitting might be unavoidable in some of these cases.

**Comment by petermattis** [comment]
We currently don't have a limit for varchar or text types. We don't support an xml type. And we currently don't have a way of splitting up a single element if it gets too big. I can imagine various means of accomplishing that, just hasn't been a priority yet.

**Comment by petermattis** [comment]
Bigtable (and presumably Spanner) requires a row to be entirely contained within a single tablet (i.e. range).

**Comment by petermattis** [comment]
Any thoughts on how to prevent splits in the middle of a row? We can certainly examine the key structure, but I think it is a non-starter to actually look up the associated table in order to determine how many column values need to be decoded. That is, I think we want to only look at the key, in isolation, to determine if it is a valid split point.

SQL encoded keys come in two variations: table keys and index keys. Table keys are structured as `/<tableID>/<primaryIndexID>/<primaryIndexCols>[/<columnID]`. Index keys are structured as `/<tableID>/<indexID>/<indexCols>`. My thought is to append an additional byte to both table and index keys containing the number of bytes for the `columnID`. For keys which do not contain a `columnID` (i.e. sentinel row keys and index keys) this byte would contain `0`. The find-split-key code would just have to determine if the provided key was a table key and had a `0` suffix. Storing the number of bytes the `columnID` encoded into would allow stripping of the `columnID`. Not sure if that is necessary. Alternately we could just append a `0` for keys which are valid to split on and `1` for other keys.

**Comment by bdarnell** [comment]
Yes, we need to find a valid split point from the keys alone. Ideally we'd want something a bit stronger than "is this key a valid split point": we want to be able to find the closest split point to a given key. Appending the length of the column portion of the key gives us this; a 1/0 suffix does not.
