### ISSUE TITLE
Potential race condition in Gossip SystemConfig updates

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#3466]
I was working on #2978 for a little while, and couldn't get around leaking goroutines occasionally in leaktests. Whose responsibility should it be for cleaning up goroutines (with a `stopper`) that are used for listening to callback channels? The side who registered the callback channels (stop listening?), or the side who is sending updates on the channels (close the channel?).

More importantly though, I was wondering if Gossip's current implementation of [executing callbacks](https://github.com/cockroachdb/cockroach/blob/master/gossip/gossip.go#L404) could be a race condition. Is there any guarantee that if two SystemConfig updates are close, that the second update wont run it's callback before the first one? In that case, the first update would call `go cb(cfg)` first, but I don't believe Go's memory model, guarantees that this goroutine will execute first without any synchronization. See [here](https://play.golang.org/p/dcX5gQ5RQL) for a demo.

**Comment by bdarnell** [comment]
Yeah, the current implementation is racy. If we don't move to a channel as proposed in #2978, we'll need to either run the callbacks synchronously or remove the `SystemConfig` argument and have the callback query for the current state (so a delayed callback would cause the application to see the same current SystemConfig twice instead of replaying an old value).

I think it's would be simpler if the `Gossip` side invokes the callback via a `Stopper`, but this won't work with `multiTestContext` which currently has multiple stores sharing a single `Gossip` object. In that case we need to run the callbacks synchronously on the `Gossip` side and have the registered callback use `RunAsyncTask` if it's too expensive to remain synchronous.
