### ISSUE TITLE
backupccl: canceled job didn't stop Export retry loop

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34714]
In #34650 a user hit the time-bound iterator bug and some exports got stuck in the ExportRequest retry loop. The job was canceled, but the retries kept going. Context cancelation should have prevented this; it's worth looking into why, and whether there's anything we could do to harden this.

Jira issue: CRDB-4632

**Comment by mjibson** [comment]
The retries kept going makes sense because we don't check the job status until a call to Progress the job. What is odd is (the user reported) that even after rebooting all nodes in the cluster the job was still running after cancelling it. I'm not entirely convinced the reported list of actions happened in the reported order (for example maybe it was reboot nodes, then cancel job).

But it does seem nice if...say...the thing that Resumes/Starts jobs also started its own go routine to check for job cancellation/pause and canceled the context it passes to the Resume func. This could halt jobs faster and should prevent these kind of runaway bugs in the future.
