### ISSUE TITLE
Postgres compatibility for AWS DMS

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#34766]
Trying to use AWS Replication/Migration services and Cockroach as a target.  The initial error I get is:  

```

Endpoint identifier | Replication instance | Status | Failure message
-- | -- | -- | --
crdb | replication-server | failed | Test Endpoint failed: Application-Status: 1020912, Application-Message: postgres_set_encoding(...) faild in creating statement 'select character_set_name from information_schema.character_sets' ODBC general error., Application-Detailed-Message: RetCode: SQL_ERROR SqlState: 0A000 NativeError: 1 Message: ERROR: virtual schema table not implemented: information_schema.character_sets; No query has been executed with that handle ODBC general error.
```

Issue #8675 is aware of the missing character_set table, but once/if this error is resolved who knows how many more will come down the line.  So this is a general request to make cockroach compatible with Amazon DMS (and ideally other competing services).
Thanks!

Epic CRDB-14124
Jira issue: CRDB-4627

**Comment by knz** [comment]
@rolandcrosby @awoods187 I think you want this on your radar.

**Comment by knz** [comment]
@bladefist thanks for your initial report!

**Comment by bladefist** [comment]
@knz Your welcome. I think this could be very beneficial to you guys as well, it's a great way for companies to migrate or replicate to Cockroach.  The Amazon DMS tools are really high quality and allow for streaming replication, which can support a rolling migration. 

Cockroach could also be the source database and replicate to a huge list of various databases, which might be a little bit easier than using changefeeds.  

Just a thought.

**Comment by knz** [comment]
cc @vy-ton - can you retriage this?

**Comment by ajstorm** [comment]
@otan Any chance you could have a look at this when you've got a minute.  It's interesting that they're using a cursor just to check the backend version.

**Comment by otan** [comment]
Not sure what exactly to look at here - DECLARE might just be the default way they interact with the DB - we can't support it for a while.

**Comment by ajstorm** [comment]
Could we no-op the DECLARE syntax on a private build and point the tool at that cluster to see what's hiding behind this initial error?

**Comment by otan** [comment]
we'd have to fudge all expect DECLARE syntax, which is quite a bit of fudging. i fully expect it to require DECLARE to iterate through all the tables (as iterating on a table without inferring the PK is difficult, and DECLARE takes it all away)

**Comment by bladefist** [comment]
Might be easier to work w/ AWS on creating a specific driver for Cockroach? The product is much more mainstream than it was when I originally made this ticket.

**Comment by ajstorm** [comment]
For the last couple of days I've been tinkering with AWS DMS.  What I've found is that it does work for _very_ simple setups.  

The setup I'm able to get working is the case where the source tables all start empty.  In this mode, once I start the AWS DMS service I can see data replicated from an Aurora PG source to a CRDB (Serverless) target.  Of course, this isn't that interesting of a case, as for _migration_ you'd want to also perform the initial load of existing data.  

The problem however, is that when the source tables start out populated, the initial load fails (with: `Command failed to load data with exit error code 0. Please check target database logs for more information. [1020403]`).  My theory, is that it's failing because we're missing some aspects of the PG `COPY` command which AWS DMS employs ([see this article])(https://www.linkedin.com/pulse/aws-database-migration-service-best-practices-pavan-pusuluri/).  

My plan is to do some more digging into the `COPY` command usage in the coming weeks, but it's good to know that we're getting closer on this one.

**Comment by ajstorm** [comment]
This is now resolved with https://github.com/cockroachdb/cockroach/pull/78303.

Note that until https://github.com/cockroachdb/cockroach/issues/44923 is addressed, you must run your migrations tasks in a mode where they do not drop tables on the target.  We're currently working on a solution for #44923 to remove this restriction and allow migration tasks to run in "drop on target" mode.
