### ISSUE TITLE
sql: infrastructure to get visibility into the sql memory budget

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#35097]
The sql memory budgeting mechanism doesn't give us much visibility into what is going on in a running cluster. There is nothing we can monitor in the UI (at least not by default) to see if we're running close to the limit, and when we start erroring out there's not much information about what was going on.

We should design infrastructure that allows figuring out what the budget used for at a given time. This will have some overhead, so it should be something that is only enabled temporarily, for short periods of time. It could be triggered by a debug endpoint, or it could be turned on periodically whenever we reach e.g. 80% of the budget. Perhaps it could even be triggered on already-running operations when an out-of-budget error occurs.

This is something that should be on our radar for the next release to try and avoid expending engineering time on debugging out-of-budget errors after they happen. I would like to help out with the design/planning and perhaps even the implementation.

CC @jordanlewis @knz 

Jira issue: CRDB-4608

**Comment by knz** [comment]
I'm sorry I don't have ideas on how to do this with our current codebase and a standard Go runtime.

My opinion on this has always been that we need a custom go runtime to track consumption per "request" (eg SQL connection/query). I don't know how to make things work otherwise.

**Comment by petermattis** [comment]
Can we use a [custom profile](https://rakyll.org/custom-profiles/) here?

**Comment by jordanlewis** [comment]
Custom profiles are very limited. What we could do is write out arbitrary
data into pprof format, which isn't as hard as it sounds. @tbg did an
experiment with that on a recent Friday, maybe he can share.

**Comment by tbg** [comment]
I started writing some infra for this on a whim a while back, found [here](https://github.com/tbg/uprof).
This came out of convos with @jordanlewis and his PR https://github.com/cockroachdb/cockroach/pull/30930.

The hope is that we could do stuff like

```
go tool pprof http://localhost:8888/debug/pprof/sql.budgetalloc
go tool pprof http://localhost:8888/debug/pprof/sql.tablereader.bytesread
go tool pprof http://localhost:8888/debug/pprof/kv.num_keys_iterated
...
```

and get something like a heap profile, perhaps even with labels (per anonymized statement, or at least statement tag), and that we could also profile individual operations (`EXPLAIN (PROFILE) SELECT ....`), though it'll be a bit challenging to get that working cross-node and it definitely verges into the territory of tracing and would need to be suitably integrated with it. Either of these options also intersects with metrics collection (i.e. any metric should also have an associated profile that can be turned on, which allows showing the contributing call stacks to the metric).

For high CPU usage though, I think just extending #30930 so that it contains the anonymized statement and can be turned on on demand and for short periods of time (I was thinking `SET CLUSTER SETTING server.pprof.label_until = NOW() + INTERVAL '30 seconds';` or integrated into the debug page ui profile link) would do a good job in practice.

There's no such counterpart for the heap profile, though that would be fantastic. The way heap profiles are collected is extremely different though (done during GC), and doesn't lend itself well to labeling at allocation time. Or maybe it's possible, not sure. But it doesn't seem to exist today.

**Comment by jordanlewis** [comment]
We added the sessions page which shows the amount of allocated bytes per active sessions, and a UI graph that shows the total number of allocated bytes.

**Comment by yuzefovich** [comment]
#97657 added a virtual table that exposes the state of the memory monitor tree on a single node, so it seems like this has been fixed. @RaduBerinde did you envision something more / automatic?

**Comment by yuzefovich** [comment]
I'm going to close this issue as a result of two changes:
- #97657 exposed the state of the memory accounting system on a single node via a virtual table
- #114275 introduced a new "memmonitoring profiler" which periodically will dump the state of that virtual table to a textual file.

**Comment by jordanlewis** [comment]
Woohoo, always hoped to see this one get done!
