### ISSUE TITLE
opt: support re-planning with the results of a subquery

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35158]
Today this query requires a full-table scan:

```
SELECT * FROM x WHERE a = (SELECT a FROM x LIMIT 1)
```
even if `a` is indexed. We should support some kind of feedback to re-plan after we have the results of a subquery that might allow a much better plan.

This might be within the realm of doable thanks to some of @jordanlewis's recent efforts on apply join.

**Comment by jordanlewis** [comment]
This shouldn't be too difficult. Subqueries are already executed in a distinct phase, before the rest of the query. The missing piece would be a re-planning phase.

This has come up several times recently that we really need to come up with some concept of a placeholder span. You don't really want to re-optimize the whole query, probably - likely you just want to change the filter conditions into spans when possible, since that's a lot cheaper than re-optimization.

**Comment by justinj** [comment]
This is a dup of #35110
