### ISSUE TITLE
sql: unexpectedly high KV traffic on Namespace span resolving table name

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#35293]
Running a KV0 benchmark on a 128 node cluster leads to unexpectedly high QPS on a single range. 
![screenshot_2019-02-28 replication dashboard cockroach console 1](https://user-images.githubusercontent.com/1839234/53611482-c7879800-3b9c-11e9-9260-977f1adaedcb.png)

An unfortunate thing about this traffic is it seems to sometimes have high correlation with increased raft log commit latency.

![screenshot_2019-02-28 custom chart debug cockroach console 2](https://user-images.githubusercontent.com/1839234/53611505-d706e100-3b9c-11e9-864a-ec515d7cdd1b.png)

This range happens to be the SystemConfigSpan. When digging further with logspy we can see that all of the traffic to this range comes from the following query:

```
I190301 01:37:51.027024 3841768 storage/replica_evaluate.go:413  [n21,s21,r6/3:/Table/{SystemCon…-11}] evaluated Get command header:<key:"\212\211\274\022kv\000\001\213\211" > : header:<> value:<raw_bytes:"\264\354\223\312\001j" timestamp:<wall_time:1551403675956970817 > > , err=<nil>
```

This query seems to be the namespace resolution for the kv table. 
```
root@localhost:26257/defaultdb> SELECT crdb_internal.pretty_key('\212\211\274\022kv\000\001\213\211', 0);
  crdb_internal.pretty_key
+--------------------------+
  /2/1/52/"kv"/3/1
```
Where `2` is the [NamespaceTableID](https://github.com/cockroachdb/cockroach/blob/master/pkg/keys/constants.go#L297) `1` is its primary index, 52 is the database ID and `kv` is the table name. My best guess is that this is happening from this call https://github.com/cockroachdb/cockroach/blob/4cfbb6ecf7de234708cb855a9c95f85cea99e3ef/pkg/sql/database.go#L209.

Given nothing this database schema is not changing, why isn't the cache being hit more frequently? 

For reproduction, the above data was procured from a 128-node c5.xlarge AWS cluster running KV0 with 8192 split and 4 workload binaries running with concurrency 2048.

Jira issue: CRDB-4594

**Comment by RaduBerinde** [comment]
A CPU profile should help identify the code path that is calling `GetDatabaseDesc` so often.

**Comment by ajwerner** [comment]
I'll give it a shot. While it is a large amount of traffic from the perspective of the server, it's a small number of calls from the perspective of the client. There are a lot of nodes here. Given that range was seeing ~2k QPS and there are 128 nodes, we're talking about ~20 calls per second per node. When I captured it in a jaeger trace the reads were taking hundreds of microseconds. Either way I'll track it down.

**Comment by RaduBerinde** [comment]
In pprof, I think you can use `focus=GetDatabaseDesc` and it will show you those parts of the profile even if the CPU usage is relatively small.

**Comment by ajwerner** [comment]
![screenshot_2019-03-04 cockroach cpu](https://user-images.githubusercontent.com/1839234/53765708-c60ce700-3e9e-11e9-949c-4b035267d735.png)

It took running a 180s profile to show up.

**Comment by RaduBerinde** [comment]
I don't see anything off in that diagram - it's expected for the top code path to run on every query. It doesn't look like resolving objects results in frequent `Get`s or we would see it in there.

**Comment by ajwerner** [comment]
I think it's all a question of what is too frequent. I'm surprised that each node seems to have to do the transaction to do the lookup ~20 times per second. Is there code that invalidates the cache based on number of uses rather than on time?

**Comment by RaduBerinde** [comment]
No, looking at the table lease code it should be on the order of once every 5 minutes. I was suggesting that it might be some other codepath that's responsible (perhaps not involving `GetDatabaseDesc`, not sure..).

I wonder if there's an easy way to add a profiler metric to count how many `Get`s we execute instead of CPU time. @tbg might know the answer. A poor-man's version would be to use `debug.PrintStack` and aggregate in a map.

**Comment by knz** [comment]
This may help: #35555

**Comment by ajwerner** [comment]
Unfortunately this is still going on after #35555. I'm doing some more digging.

**Comment by postamar** [comment]
I see that `system.rangelog` is still in our deny-list for system descriptor leasing so I guess this is still open. It feels dumb that we can't at least cache these descriptors because of bootstrapping, assuming that that's the only reason. Couldn't we allow this by forbidding any schema changes on these tables? This way we get to use in-memory descriptors in the collection just like we already do for the system database descriptor.

This implies that instead of ALTERing these tables in a migration we'd have to re-create them, but this is probably what we'd want to do anyway just out of safety. The tables in question are `lease`, `descriptor`, `namespace` and `rangelog`.

**Comment by ajwerner** [comment]
I concur with your assessment. We should just serve in-memory versions of these always and disallow schema changes. It's not a hard change and would be very valuable for cluster scalability.

**Comment by rafiss** [comment]
Would that latest idea help with CRDB-18341 ?
