### ISSUE TITLE
cockroach UI continues to show staggered version though nodes are running with same versions

### ISSUE THREAD

**Issue by kswathihs** [cockroachdb/cockroach#35486]
**We are seeing staggered version warning in the UI though nodes are running with the same versions**

**To Reproduce**
we have the Cockroach cluster in GCP. we upgraded the cluster to 2.1.4 (from 2.1.0). Nodes are showing the right versions in the dashboard, but we still the warning. Is cockroach considering old decommissioned/dead nodes?

**Expected behavior**
warning should not be shown

**Additional data / screenshots**
<img width="1185" alt="screen shot 2019-03-07 at 11 52 13 am" src="https://user-images.githubusercontent.com/44799888/53936481-e374c780-40cf-11e9-9f64-e8060db23466.png">
<img width="1180" alt="screen shot 2019-03-07 at 11 58 55 am" src="https://user-images.githubusercontent.com/44799888/53936611-6bf36800-40d0-11e9-9331-3afc211442ab.png">

**Comment by awoods187** [comment]
CRDB counts the dead nodes as a part of the cluster because CockroachDB doesn't expect for you to have dead nodes for a long period of time. You should decommission those nodes via https://www.cockroachlabs.com/docs/v2.1/remove-nodes.html#main-content

Note, you should only decommission one node at a time and make sure it's fully decommissioned before decommissioning the next node. 

Let me know if you have any questions.

**Comment by kswathihs** [comment]
Thanks @awoods187 warning is not displayed after decommissioning dead nodes.

**Comment by a-robinson** [comment]
I get that this isn't a particularly important issue and there's a way for users to fix it, but it's still pretty silly for nodes which have been dead for weeks to justify the "Staggered Version" warning.
