### ISSUE TITLE
webui: show completed queries within a time interval 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35629]
I want to be able to see the last queries my cluster run. It'd be great if we could extend `show queries` to show queries from a past time interval.

`Show queries from <time interval>`

Other DBs offer this through monitoring or tracing. 

Jira issue: CRDB-4568

**Comment by piyush-singh** [comment]
This was a planned feature once we decoupled statement stats from telemetry. The plan was to store individual executions of statements so that we could explore everything that executed in the cluster over the past few hours (Spanner stores this for up to 24 hours). We'll be revisiting this once we have time to put more effort into improving statement statistics.
