### ISSUE TITLE
storage: quiescent ranges

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#357]
(Capturing a discussion between @spencerkimball  @tschottdorf and I)

It is likely that in a large deployment of cockroach, only a small fraction of ranges will be active at any time. If we allow inactive ranges to become quiescent and stop sending raft heartbeats, we can reduce the number of active consensus groups, perhaps to the point where coalesced heartbeats become unnecessary.

In detail, when a leader finds that
* X ticks have elapsed since the last command was proposed
* No read leases are currently needed
* All followers have acknowledged the latest log entry

The leader may become quiescent by allowing its lease to expire, broadcasting a message to all followers that it is becoming quiescent, and stepping down. Followers in a quiescent group would not start an election unless they had a new command to propose (or needed a read lease).

It is important that the group be fully replicated before becoming quiescent because otherwise the under-replicated tail of the log is at risk of data loss. The leader informs the followers of the groups' quiescent state, but this message does not need to be acknowledged or retried - any followers who do not receive this message will simply start a new election and the group will stay active a while longer.

Advantages:
* Quiescent ranges do not contribute to heartbeat traffic. If enough of the cluster's data is quiescent, we can forego the complexity of coalesced heartbeats (intuitively, the motivation for coalesced heartbeats is that heartbeat traffic grows proportionally to both storage and traffic. If inactive ranges are quiescent, the storage factor is removed and heartbeat traffic is closer to a constant multiple of command traffic)
* Quiescent ranges also do not contribute to non-coalesceable traffic such as the elections that would be necessary to recover from a cluster-wide power outage.
* By calling elections on-demand, we increase the likelihood that nodes closer to the user of a particular piece of data will be chosen as that range's leader.
* If we get rid of coalesced heartbeats, we avoid complications like those discussed in #315 and can attach additional information to heartbeats as discussed in coreos/etcd#2368.

Disadvantages:
* The request that wakes up a quiescent range has significantly increased latency (1 RTT minimum, probably 2 if we add the pre-vote RPC). Without randomized election timers, the chance of a contended election is also increased. (Note that we don't need to go through a full election cycle for reads; we could serve a read as soon as the pre-vote RPC indicates that no other node has won a quorum)
* Heartbeat traffic becomes more variable. A scan across the entire keyspace could wake up many ranges, leading to greatly increased heartbeat related load until those ranges go back to sleep. (This could be mitigated by continuing to coalesce heartbeats even if that is less helpful in the average case)
* This will have an impact on schema designs; scattering reads across many nodes with hash-based keys will be less effective. This is especially harmful to scatter-based designs because it increases latency variance instead of average latency.

Open questions:
* Should the leader step down when it becomes quiescent (advancing to a new term that does not yet have a leader) or should it remain the leader of its term so that it might be able to resume its job with less than a full election cycle?
* In practice, will enough ranges be quiescent that we can get rid of coalesced heartbeats? Can we go even further and replace multiraft and multinode with a collection of regular raft.Nodes? (at the cost of one goroutine per active group)

**Comment by spencerkimball** [comment]
Nice writeup.

**Comment by cockroach-team** [comment]
Curious about the assertion that a substantial portion of ranges could be
quiesced. For most online applications, you'd probably want a key which
evenly distributes random accesses across the key space (eg the hash-based
design you mentioned) in which case, even as storage increases, all ranges
would continue to be equally warm. To end up with quiescable ranges, you
are basically mandating that the key design exhibit skew, which is usually
an anti-pattern for scalable storage.

It seems the only way that skew (and thus quiescability) is acceptable is
if the partitioning is very fine grained. For example, in a gmail-like
application, if each user has his or her own range. Then, of course, only
some fraction of users are active at any point in time, but because you've
made partitioning so fine grained, the number of active ranges is still
quite high (tens of millions, I'd wager, for gmail)

**Comment by bdarnell** [comment]
Yeah, the more I think about it the more doubts I have about it. For gmail it was true (large absolute numbers to be sure, but what matters here is the ratio of active ranges to nodes); for Google Reader it was mostly untrue. 

I think that cockroach will ultimately favor locality more than systems like bigtable (due to the advantages of single-range transactions), so it's possible that the right answer is to design for more schema locality, but I think if I designed a system the way I would for bigtable it would not work as well with quiesced ranges.

**Comment by spencerkimball** [comment]
Not sure who that last comment was from...

With an interleaved schema (which we surely expect to be the rule, not the exception), most things begin to look like a gmail-like application. You expect your "entity groups" to be hash based and all data hierarchically related to the entity group's root key to be co-located on a single range, or group of consecutive ranges.

Regardless, my experience with scale out data storage is that you end up with massive amounts of data which is written once and then left cold. Time series data comes to mind.

All of that said, I agree that you could easily still end up with a larger fraction of ranges not quiesced. That might mean we don't ditch multinode. But overall, it doesn't change the utility of looking at this in a different way.

We're really trying to avoid senseless heartbeat traffic and leader election storms on cold startup. If you're writing, you're doing quorum traffic anyway; no way to avoid it. If a range is active for reading, we'll eat the heartbeat traffic, but it's still likely only a small or at worst, proportional, fraction of the read traffic directed at the leader.

**Comment by bdarnell** [comment]
But you're assuming that any given operation only touches a small number of "entity groups"; not all applications are amenable to such a schema (Reader wasn't).

Time series data is actually an example of what I'm talking about. If the name of the series is the "primary key", then you end up with cold data at the bottom of every range; can't make a range quiescent until you've completely filled it up and moved on to the next one (which will eventually come to dominate if it's not GC'd, but 64MB of time-series data points can take a long time to fill up).

I agree that no matter what we can take advantage of this insight to avoid the election storms by deferring creation of the raft group at startup, and instead do it lazily as needed. If we can't ditch multiraft and coalesced heartbeats, I'm not sure the explicit quiescence protocol is worth the trouble at this point.

**Comment by toddlipcon** [comment]
Sorry, I was the anonymous commenter above, not sure why my reply-by-email didnt show up with my name.

My point wasn't so much that there aren't use cases that could quiesce ranges, but more that there are many many use cases where you can't get any meaningful benefit. Given that, you still have all the problems, as Ben mentions above. But, I agree it's a nice principled way of lazily re-starting raft, and doing that partial implementation is likely simpler than also the automatic step-down when idle.

**Comment by tschottdorf** [comment]
I'm strongly in favour of quiescing ranges regardless of the fate of coalesced heartbeats.

To my mind, quiescing ranges is a transparent, simple way to avoid unecessary traffic that can be turned on and off on the fly and deals with election storms nicely.

We may decide not to implement it now, but we should at least keep it in mind for everything else that we add in Raft. They and coalesced heartbeats could coexist quite nicely (it's easy for multinode to intercept the message that quiesces a Raft group, so the bookkeeping is easy) and so for me these two are orthogonal problems.

In most scenarios where coalesced heartbeats are not required, it would be great to get rid of them completely. They are not strictly heartbeats in the sense of pure Raft (you may end up getting heartbeat by a group that you think is the leader but really isn't any more and knows it) and thus an abstraction that has to be considered very carefully for anything in Raft involving heartbeats. Plus, the very second etcd/raft decides to send just a little bit more information with their heartbeats (as they should), heartbeats are going to be truly per-group and once that is used in Raft, coalesced heartbeats in their current form will not work any more. I have some ideas on how they should change, see below.

On the other hand, coalesced heartbeats are a scalable way of figuring out which (physical) nodes can talk to each other, quickly. And that's really all they should do for us, once groups may go quiescent. That reduces what we want from coalesced heartbeats should we need to keep them (see below).

The main counter-argument against getting rid of coalesced heartbeats seems to be that without them, we would run into trouble if a lot of Raft groups were active at the same time due to the large number of heartbeats.

But that's not necessarily true. Heartbeats don't need to be sent when there is regular traffic on the group (this isn't currently implemented in Raft, but by Raft design, a heartbeat should equal an empty append request). So as long as the group is active (i.e. has things pass through consensus every now and then) no heartbeats need to be sent. That's a very basic Raft optimization that is sure to find its way into upstream Raft one way or the other.

That means you strictly only **need** coalesced heartbeats when you have large numbers of groups which are only active by means of reading from them without going through consensus (i.e. via a lease). Those groups would be without regular Raft traffic, so naively they would need heartbeating.

But at that point, you've reduced to a fairly special case and you've still got all the options in the world, and that includes a variation of coalesced heartbeats:

- What you really need to know is that certain nodes' messages reach you (and vice versa).
- That's perfect for coalescing, as no per-group information is needed.
- Multinode could simply pass those signs of life back and forth between those groups on the respective nodes, and feed them into the groups (but as a special kind of heartbeat that isn't interpreted by Raft outside of their scope).
- So there would not be any coalesced heartbeats, but coalesced "which physical nodes can message us". Which is probably enough once you add serial id to those messages.

The clean exposition would be a little more involved, but basically my proposition for coalesced heartbeats would be to alter them into something that doesn't pretend that it's transporting heartbeats at the cost of significant complexity and potential for incorrect behaviour in Raft, but rather per-host signs of life (multiplexed into per-group signs of life through MultiNode).

Once we get around to implementing read leases (for instance doing something like [Timeless leader leases](https://github.com/cockroachdb/cockroach/issues/230#issuecomment-75925594)) you'll be relying on heartbeats for correctness in the face of some network failures and then it becomes crucial that they work as they should. But you really only need the sign-of-life information above.

As for MultiNode, there's probably some value in having it. Unless performance improves significantly when switching to individual goroutines, it can't hurt to have a simple point through which all Raft traffic  and bookkeeping can be accessed. I would opt for keeping it (at the very least for now), making sure that it doesn't accrue cruft.

But quiescent ranges would be advisable no matter what.

**Comment by bdarnell** [comment]
> The main counter-argument against getting rid of coalesced heartbeats seems to be that without them, we would run into trouble if a lot of Raft groups were active at the same time due to the large number of heartbeats.

> But that's not necessarily true. Heartbeats don't need to be sent when there is regular traffic on the group (this isn't currently implemented in Raft, but by Raft design, a heartbeat should equal an empty append request). So as long as the group is active (i.e. has things pass through consensus every now and then) no heartbeats need to be sent. That's a very basic Raft optimization that is sure to find its way into upstream Raft one way or the other.

Another way to look at this is that relying on regular traffic as an alternative to heartbeats requires either a high sustained level of traffic or infrequent heartbeats (making us less responsive to failures). Coalescing heartbeats lets us decrease the HeartbeatInterval at lower cost.

**Comment by tschottdorf** [comment]
@bdarnell That's true. I think at the heart of it I'm mostly unhappy with the correctness implications of coalesced heartbeats and with the fact that they have to be upgraded with nearly every new feature that Raft groups learn (where heartbeats likely acquire new semantics).

I've attempted to address some of the shortcomings of coalesced heartbeats in #315, I think with those modifications we could do quiescent ranges (=no election storms) as well as  leader/follower leases if we wanted (ideally timeless ones, because that's low on traffic) without running into too much complexity and/or sacrificing failure recovery.

What do you think about the fate of quiescent ranges? I currently consider them valuable for dealing with election storms, but in my mind they're in tandem with coalesced heartbeats and MultiRaft, not standalone.

**Comment by bdarnell** [comment]
I think we definitely want to make range initialization lazy, to avoid election storms on a cold start. Returning previously-active ranges to the quiescent state is helpful, although my feeling is that it's low-priority since it won't help us eliminate coalesced heartbeats.

**Comment by dt** [comment]
Bumping this issue per offline discussion with @paperstreet and @tschottdorf: forcing ranges to quiesce (and stay quiet) may be useful for bull import/restore, if it allows applying a snapshot with an index in the future

**Comment by petermattis** [comment]
This is done as of #9315 and #9407.
