### ISSUE TITLE
sql: lookup joins should use batch limit

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#35950]
See https://github.com/cockroachdb/cockroach/issues/35947#issuecomment-474442227

Lookup joins should use a batch limit because we don't know how many rows we might get - unless we know the input forms a key (in which case we know we'll get at most one per input row).

**Comment by jordanlewis** [comment]
I investigated this. Currently, lookup joins can't use batch limits because we restrict batch scan requests to have ordered spans. I think the reason for this is the ResumeSpan semantics, but I'm not sure...

@RaduBerinde you added this restriction way back in 2016 - do you understand why it exists?

**Comment by RaduBerinde** [comment]
I don't remember the details, but yes I believe it had to do with the resume span semantics. Those semantics might have evolved over time though so we may not have the same restrictions today.
