### ISSUE TITLE
backupccl: fixtures import (and thus CSV imports?) are too sensitive to node liveness errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#36058]
A `fixtures import` invocation failed:
```
workload fixtures import tpcc --warehouses=10000
...
Error: importing fixture: importing table order: pq: job 436450579945160705: node liveness error: restarting in background
```
The job continued in the background, but the `workload` invocation exited with an error code.

The node that was performing the import did encounter very high latencies in heartbeating its liveness record around that time, for some reason, and its epoch was bumped by others.
Still, it seems to me that this all should have hardly caused the `workload` invocation to return an error.
I think we want to move a bunch of roachtests over to `fixtures import` for loading their data, and so I think it'd be really good for that to be as resilient as possible. Or is there an argument for not caring what `workload` reports and watching some job instead somehow?

Btw, in other cases, I've seen the import fail with what I think is a DistSQL communication error:
```
ccl/workloadccl/fixture.go:516  imported stock (1h30m16s, 1000000000 rows, 1000000000 index entries, 314 GiB)
 61 Error: importing fixture: importing table order_line: pq: communication error: rpc error: code = Canceled desc = context canceled
```

@mjibson are you the right victim here?

cc @tbg

Epic CRDB-8816

Jira issue: CRDB-4533

**Comment by tbg** [comment]
Hmm, it does seem like the better UX that the synchronous client thread
would fall back to a mode in which it polls the job record and reports the
eventual status of that.

**Comment by mjibson** [comment]
This is an existing feature request: #35048. Should most likely be sent to the bulk-io team for prioritization.

**Comment by andreimatei** [comment]
I'll pass it to... @dt ?
For me imports of 10000 warehouses fail about 30% of the time, mostly because of network connections dropping (or overload causing networking problems maybe). I think importing really needs to be more resilient.

**Comment by dt** [comment]
Architectural reasons made it hard to make IMPORT resilient in the past -- every node produced data and pushed it into a giant distributed buffer and sort, so if any node failed, you had no idea what was missing from you giant buffered sort, so you essentially had to throw it all away and start over (mod some ability to checkpoint certain phases).

In 19.2 we're replacing that with a simpler 1-pass import that should be a little easier to ruggedize

**Comment by miretskiy** [comment]
I think we should poll jobs system to determine when import completes.

To that end, there is work happening to make bulk-y operations runnable in "detached" mode:
"import table t csv data (...) DETACHED" (UI aspects still in the air).  In that mode, the statement
returns the job id.

We can then poll jobs framework for the job completion, instead of relying on connecting staying up.

One quirk is that we doin't get the same information from polly system.jobs as we get
when we wait for the statement to complete running (you just see opaque payload proto buff).
We might be able to work around that somehow (perhaps having a special resumer implementation which waits for the job to succeed, or fail, and returns appropriate data).
