### ISSUE TITLE
opt: inject stats during backup/restore

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36099]
Currently, clusters automatically create statistics after restore finishes. This can cause a hit to performance as statistics build during active load. By automatically building statistics during backup/restore, clusters will be ready to handle the load with peak performance when an restore completes. This will help with POC performance (a common pattern is to bulk insert followed by an immediate performance test) as well as speed up time to a usable cluster.

**Comment by danhhz** [comment]
Can we split this issue into one for IMPORT and one for BACKUP/RESTORE? The latest thinking is the former should (likely) accept a flag that causes it to compute the stats as it goes and inject them afterward, but the latter should probably save the stats in the BACKUP and put them back as part of RESTORE. Since the work for the two is very different, it'd be nice to track and prioritize them separately.

**Comment by awoods187** [comment]
Added a new issue for just import (https://github.com/cockroachdb/cockroach/issues/36273) and paired this down to backup/restore.

**Comment by dt** [comment]
@RaduBerinde filed the backup/restore one separately in #38264 but as it already has some discussion on it about implementation, I'm closing this one as the dupe
