### ISSUE TITLE
sql: txn already encountered an error; cannot be used anymore

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36236]
> ERR (220): pq: txn already encountered an error; cannot be used anymore (previous err: unexpected value: raw_bytes:"<\372\035\314\n" timestamp:<wall_time:1553712901023502804 > )

I got this error when running sqlsmith in single thread mode, which just runs db.Exec with no BEGIN or transactions. I assume this is one of those "shouldn't be able to happen" things. I don't have the repro SQL, but am just logging it here for searchability.

**Comment by andreimatei** [comment]
This error means that an operation performed by a txn encountered an error (in particular, it looks like a CPut error based on the "unexpected value"), and then somebody tried to do something else with the txn (which is generally not allowed). This can happen with the parallel execution queue, but we have some code that's trying to score errors received by concurrent operations in that case and it's supposed to return the original error to the client.
Or this can happen if someone (SQL) just ignores an error.
Or who knows, it could be also be a bug in the client package somehow.

I'm gonna unassign myself since I'm not working on it and also cause investigation I think should start at the higher levels.

Btw, I've noticed that the error is ignored by SQLSmith. Not sure about the philosophy, but it's probably a legitimate problem that it's finding.

(please include SHAs in these reports. In particular, the parallel execution queue is about to go away momentarily and that kind of ordering is relevant)

**Comment by mjibson** [comment]
This was observed from fcc2630a9ce94384763adecd9dc6260eb0afb51c.

**Comment by mjibson** [comment]
Closing until we have repro SQL.
