### ISSUE TITLE
memory usage spike with range delete

### ISSUE THREAD

**Issue by garvitjuniwal** [cockroachdb/cockroach#36588]
**Describe the problem**

When I do `DELETE FROM db.foo` on a large table, I see memory usage of cockroach spike.

**To Reproduce**

8 node cluster. Table db.foo has 1 million keys (each key is an int), total disk usage 26 GiB. 
When I tried `DELETE FROM db.foo`, memory usage on the gateway node went up by 2 GB.

Is that command loading all keys in memory before issuing deletes? The command was fast enough that I believe that it does not put an individual tombstone on each row, but the memory usage is unexpected.

TRUNCATE does not seem to exhibit this problem. I could be using TRUNCATE here, but TRUNCATE is treated like a schema change for privilege purposes which is giving us some trouble given the way we setup privileges in our services.

**Environment:**
Cockroach version 2.1.3
Server Linux
Client `cockroach sql`

**Comment by andreimatei** [comment]
I looked at the code in the `deleteNode` and it didn't look like we're supposed to accumulate anything. There's also a `rangeDeleteNode` which I think may be taken here. That one I don't really know about, but I'm guessing it also is not supposed to accumulate anything.
@jordanlewis ?

**Comment by garvitjuniwal** [comment]
We also encountered this on Cockroach 2.0.5 + custom patches, and got a chance to collect a heap profile. The top entries look like this

```
     flat  flat%   sum%        cum   cum%
    7.08GB 82.53% 82.53%     7.08GB 82.53%  github.com/cockroachdb/cockroach/pkg/roachpb.(*DeleteRangeResponse).Unmarshal
    0.46GB  5.31% 87.84%     0.46GB  5.31%  github.com/cockroachdb/cockroach/pkg/storage/engine.copyFromSliceVector
    0.21GB  2.47% 90.31%     0.43GB  4.96%  github.com/cockroachdb/cockroach/vendor/github.com/scaledata/etcd/rafthttp.startPeer
```

The complete heap profile is here 
[memprof.double_since_last_profile.000000031989297152_2018-12-24T06_10_12.91.prof.txt](https://github.com/cockroachdb/cockroach/files/3050936/memprof.double_since_last_profile.000000031989297152_2018-12-24T06_10_12.91.prof.txt) and the binary from which this is generated is 
[cockroach.tar.gz](https://github.com/cockroachdb/cockroach/files/3050939/cockroach.tar.gz)

**Comment by jordanlewis** [comment]
Thanks, @garvitjuniwal. Did you see the memory spike on all nodes or just the one executing the delete?

Here's a more complete picture of the stack that caused the allocations:

![image](https://user-images.githubusercontent.com/43821/55849973-93e74880-5b20-11e9-8de6-2812a5da7f34.png)

Reading the [`deleteRange` code](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/delete_range.go#L172), it would appear that we send all of the `deleteRange` requests for a SQL-issued deletion request in a single KV batch, no matter how big the span is. This can be problematic, because the `deleteRange` API currently returns all of the keys deleted in a giant, non-streamed buffer.

This means that if you have 8 gigabytes of keys to delete, your response will have 8 gigabytes of data to look through.

This is clearly unideal. There also isn't too much the SQL side of things can do about it. There's no reasonable way to create a "good-sized" span to delete, because we don't know how many keys a given span has within it. I think there's 2 possible resolutions to this issue:

1. the DeleteRange kv request learns to return the number of deleted SQL rows, not all of the deleted keys. This is hard because kv requests don't know how to decode SQL data currently.
2. the DeleteRange kv request learns to return at most `n` bytes of key data, plus a resume span, like other requests. This would permit SQL to "stream" a deletion.

I think option 1 is much better.

@andreimatei I'm kicking this back to the core side, unless you have an objection.

**Comment by jordanlewis** [comment]
Also, tagging @knz as another one of those "core-but-sql" issues.

**Comment by andreimatei** [comment]
Isn't what you want to put a limit on the respective batch (limit in the
number of keys, which is not particularly good)? Or do these requests not
understand limits?

**Comment by jordanlewis** [comment]
A batch limit might work, but the requests don't seem to have a limit field.

**Comment by andreimatei** [comment]
I believe the limit is on the batch. Or maybe for scans it's on both? I
remember it being pretty confusing.

**Comment by jordanlewis** [comment]
Right you are, and nobody sets that in this deleteRange node. Will send a patch.
