### ISSUE TITLE
sql: after killing a node and restarting it it doesn't seem to serve traffic

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36785]
**Describe the problem**

@lucy-zhang and I were testing schema changes while killing a node https://github.com/cockroachdb/cockroach/issues/36723#issuecomment-482327992.

We want to try the test again on the cluster so we attempted to return it to a healthy state (dropped the index, restarted the node). Unfortunately, even after stopping and restarting the workload, node 3 (the node we killed) doesn't seem to be serving traffic.

![image](https://user-images.githubusercontent.com/22278911/55995972-03c21400-5c84-11e9-9c4b-2bd91dd8fb83.png)
![image](https://user-images.githubusercontent.com/22278911/55995977-07559b00-5c84-11e9-9313-d6b745df9c87.png)

**Version**
 v19.1.0-rc.2-35-g134478e

**Comment by awoods187** [comment]
debug.zip https://drive.google.com/open?id=10PIqRvDc62Mq0n8qk9DnECVm3DUFfzk8

**Comment by petermattis** [comment]
I’d bet this is due to the load generator, not CockroachDB. Try restarting
your workload. This would be nice to fix, but it needs fixing at the
application/load-balancer.

**Comment by awoods187** [comment]
I did try restarting the workload generator and it didn't change anything.

**Comment by petermattis** [comment]
Ah, I see you mentioned in the original message that the workload was restarted. (I was reading this issue on mobile and missed that). That makes no sense. Does the restated node have any SQL connections?

**Comment by tbg** [comment]
Friendly reminder that not every issue is automatically a Core issue. In this case, you restarted a node and you're saying that n3 isn't serving traffic. I don't see a screenshot of the graph corresponding to n3, but I assume you are seeing zero SQL queries on it and that's why you were filing this. The work to do here is to find out whether there are SQL connections to the node, and if so, what these connections are up to. `SHOW SESSIONS` and `SHOW QUERIES` on `n3` should be helpful there. Either way, this isn't a core issue (at least not yet).

**Comment by tbg** [comment]
Ah, I see now that your first graph is from `xxx-0003` (the old confusion between nodeID and node name strikes again). Yep, doesn't seem to be serving traffic and

> SHOW SESSIONS and SHOW QUERIES on n3 should be helpful there.

(or whatever sql folks think is the right thing to look at).

**Comment by awoods187** [comment]
I can no longer reproduce (after going through the entire schema change repro steps from the linked issue). As a result, I will close this issue since we seem to have addressed the underlying issue.
