### ISSUE TITLE
jobs: allow jobs to pause themselves on "failure" instead of terminal failure

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36887]
A failed job is terminal and a new job has to be created, but a paused job can be resumed. In many cases, something that is transient fails the job and it's unnecessary hassle to start from the beginning. During cluster instability or choas, for example, all sorts of errors can be returned, but once the cluster recovers, it'd be nice if an operator could resume the backup or restore or changefeed.

There are a few UX issues to work out before doing this. First is how the error will be surfaced to the user. Second is whether it should eventually time out and fail. This latter is important to IMPORT/RESTORE, for example, which clean up the partial data when they fail.

**Comment by pbardea** [comment]
also adding this to the bulk io backlog. Similarly, something like this would be even more useful on the stream ingestion job since we may have already ingested days worth of data and don't want to wipe it all for what could be a transient failure.

**Comment by ajwerner** [comment]
This seems extremely similar though slightly different from https://github.com/cockroachdb/cockroach/issues/59542

**Comment by adityamaru** [comment]
I'm going to reopen this since we only added a `DEBUG_PAUSE_ON` option for restore. I think there is still an argument to be made that pause on failure should be the default for all jobs that opt-in. We have seen customers face issues where a `503:Service Unavailable` error from GCS, 90% into the backup causes the job to fail and throw away all of its work.

While jobs should have their own retry logic for specific classes of errors, it is hard to get complete coverage of transient errors.
