### ISSUE TITLE
webui: nodes shown as green during asymmetric network partition

### ISSUE THREAD

**Issue by kellabyte** [cockroachdb/cockroach#36890]
**Describe the problem**
I setup a 3 node cluster. 2 of the nodes joined the first node successfully and showed up green. I had an issue with port forwarding that prevented the ability for any of the GRPC or SQL protocols to work on those 2 nodes. They still remained to show up green although there were lots of errors in their logs about not being able to connect to each other.

The cluster showed under replicated ranges. It wasn't easily visible to understand why because all nodes looked healthy. As a new person this wasn't intuitive.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

I spun up a 3 node cluster using docker and forgot to forward the ports on 2 of the 3 nodes.

**Expected behavior**
I expect nodes that are unhealthy and that cannot receive replicas to show up as unhealthy in some way in the cluster status page.

**Environment:**
```
CockroachDB CCL v2.1.6 (x86_64-unknown-linux-gnu, built 2019/03/04 23:21:07, go1.10.7)
```

Jira issue: CRDB-4473

**Comment by tbg** [comment]
Hi Kelly,

our troubleshooting story for this problem unfortunately isn't great (yet). There is a networking debug page that would've shown you this problem right away ("Network latencies" under `/debug`, you would've seen that A can connect to B but not vice versa), but what is really needed here is some prompt from the main UI to go take a look at that if it looks fishy.

cc @andreimatei / @piyush-singh can you boulder this one out? It's sort of a long-standing papercut that has tinted more than one first experience.

Nominally a duplicate of

**Comment by andreimatei** [comment]
Well, do you have a clear fix in mind?
It seems to me that this is a general problem - what's needed here is a general way to surface alerts, plus a list of things we want to alert on, plus... an implementation for alerts...

**Comment by tbg** [comment]
No, there's no clear fix. This would be relatively straightforward to build on top of gossip_alerts (periodically check whether a connection is established to all gossiped nodes which is cheap, if not emit the alert, then expose the alerts in the health endpoint which the UI already pings every couple of seconds). It's worth considering alternatives, though.

**Comment by bdarnell** [comment]
Some brainstorming of different solutions:

AIUI, the root cause here is the discrepancy between the join hosts and the advertise hosts. The join hosts are more visible so you tend to get them right, but if the advertise hosts are wrong you can get into this state. Nodes can join the gossip network (using the join hosts, and relying on gossip's full-duplex communication over a single connection), but ranges can't be replicated to them because that needs the advertise hosts to be correct (everything else needs connections pointing in both directions). 

We could give a warning/error at startup if the advertise host looks likely to be broken. I think we already do this if the node can't resolve its own advertise host; we could build that into the gossip handshake so that the gossip connection won't establish if it looks like we can't communicate in both directions. We might also be able to warn if you're using raw IPs for the join hosts but the advertise host is getting the domain name by default (the use of raw IPs suggests that you don't have working inter-node DNS. However, in the gitter chat that preceded this issue filing, IPs were being used for both join and advertise, and the fault lay elsewhere in the network). 

We could make gossip more consistent with our other protocols by only using the join address for an initial handshake, then dropping that connection and starting over with the advertise address. I'm not sure whether that would make it easier or harder to diagnose the problem, though.

in the UI, we could take a couple of different approaches. The "green" color of the nodes is too generous and based only on a single factor; we should incorporate more signals into this (although it's hard to incorporate network problems into the node count. If there's a 50/50 partition, how many nodes are green and how many are red? Maybe network faults are their own category). We should probably do the pairwise connectivity checks of the network report page more often and include them (at least as a pass/fail status) in the main UI instead of a debug page (or incorporate it via gossip_alerts). 

The UI was correctly reporting underreplicated ranges, but didn't provide any guidance. Ideally we'd catch the failures trying to upreplicate and make them accessible by clicking on the underreplicated range count or something like that. This seems challenging from a plumbing perspective, though. 

My favorite ideas out of this are adding a check to create a reciprocal connection when a new gossip connection is established, and incorporating the network report page into the main UI.

**Comment by sebastianblunt** [comment]
Note that this is not just a web UI issue, if you have a load balancer in front of your nodes that checks the readiness endpoint it will cause the load balancer to send traffic to nodes that are not actually functional, causing a percentage of requests to randomly time out and fail.

**Comment by sebastianblunt** [comment]
Not stale.
