### ISSUE TITLE
distsql: Investigating using []*types.T rather than []types.T

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#36909]
This issue came out of discussion on #36710.

There are many distsql-related methods and protobuf structs that construct and pass around `[]types.T`. The `types.T` struct is 128+ bytes, so constantly copying them by value into slices is a potential perf and memory usage concern.

The alternative is using `[]*types.T`. Much of the time, types are singleton instances that are stored once globally (e.g. `types.String`, `types.Int`), so this would reduce memory usage and copying to 8 byte pointer values.

One concern with switching to `[]*types.T` is that the default protobuf `Unmarshal` code would allocate a new object for each `types.T` in a slice, vs. embedding them by value in a single slice. This could be a problem when these slices are passed from machine to machine by distsql.

The only way to know for sure if something should be done here is doing some additional investigation that includes some testing/benchmarking.

**Comment by yuzefovich** [comment]
For some context on why I want to address this issue: I ran into a subtle bug due to the fact that we're operating on "slices of values" (`[]types.T`) and "single pointers" (`*types.T`). I had a piece of code like this that was misbehaving:
```
	for i, t := range types {
		b.b[i] = NewMemColumn(&t, size)
	}
```
And compare it to
```
	for i := range types {
		b.b[i] = NewMemColumn(&typs[i], size)
	}
```
The problem with the first snippet is - IIUC - that we allocate a single `types.T` struct for the iteration, then we copy over each type we iterate over into that struct and then pass in the pointer to `t` into the method. That method stores the pointer internally inside of a `MemColumn`, and on consequent iterations the captured type is overwritten.

I later ran into the same problem in a couple of other places, so I started thinking that we should somehow prevent such bugs from occurring with some "fundamental" change, and I recalled seeing this issue.

---

One idea that @jordanlewis suggested was to add `util.NoCopy` into `types.T` struct to set up the linter to prevent us from writing loops like the first snippet. While it would work for that purpose, it would introduce another limitation - we would not be allowed to access pre-populated singleton types (e.g. `t := *types.Int` would be prohibited), so I don't think that option is a good one.

So I started thinking about changing our usage of `[]types.T` to `[]*types.T`. My first intention was to make all execution infrastructure operate on `[]*types.T` from the time all DistSQL infrastructure is set up: we would keep `[]types.T` in `InputSyncSpec` and introduce `InputSyncSpecWrapper` that would be the translator. But in many places we're using other specs (like `ProcessorSpec`) that still would have access to "unwraped" input spec. I would probably need to introduce another couple of wrappers to hide the original "unwrapped" input sync, and this doesn't seem nice.

Now I'm thinking that maybe we should switch to `[]*types.T` and `*types.T` everywhere (including in the protobuf structs)? I see that there are some concerns that this would increase the number of allocations during proto unmarshaling and could have a performance hit. I wanted to measure that performance hit, but couldn't figure out how to make protobuf spec so that `[]*types.T` gets generated. Any ideas?

Also, @RaduBerinde said that "the `*types.XX` everywhere are kind of annoying". Could you expand on that?

Are there other concerns about switching to `[]*types.T` everywhere that I'm missing? cc @andy-kimball @asubiotto

**Comment by andy-kimball** [comment]
Maybe there's a more natural way, but one way to get the equivalent of `[]*types.T` is by defining:
```
type TRef = *T
```
in types.go, so that you can use:
```
repeated bytes types = 1 [(gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/sql/types.TRef"];
```

**Comment by yuzefovich** [comment]
Thanks for the suggestions here and on slack.

First I built the binaries without the UI and ran TPCC benchmark on 6 node cluster.

- 5 min ramp and 10 min load:

*before*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    12236.8  95.2%     15.7     15.2     18.9     23.1     32.5    226.5
```
*after*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    12237.4  95.2%     16.5     15.2     19.9     26.2     50.3    218.1
```
- 15 min ramp and 60 min load

*before*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 3600.0s    12524.1  97.4%     16.6     15.2     18.9     23.1     33.6   2281.7
```
*after*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 3600.0s    12522.5  97.4%     16.1     15.2     18.9     24.1     41.9    226.5
```

---
I then rebuilt the binaries (to confirm that I didn't mess things up and to include UI) and did the same benchmarks.

- 5 min ramp and 10 min load:

*before*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    12223.3  95.0%     15.6     15.2     17.8     22.0     31.5    226.5
```
*after*
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    12254.9  95.3%     15.9     15.2     18.9     23.1     39.8    226.5
```
- 15 min ramp and 60 min load

*before*
```
to be filled
```
*after*
```
to be filled
```

I also looked different metrics in the UI and didn't see any noticeable differences. So unless I'm missing something it sounds like a good idea to me to replace `[]types.T` with `[]*types.T` throughout the code base.
