### ISSUE TITLE
exec: decimal encoding support for Arrow representation

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#37044]
Decimal serialization is currently not supported for distributed vectorized flow execution. We just need to figure out a way to quickly encode `apd.Decimal`s, which we can then send as a serialized arrow byte slice.

Jira issue: CRDB-4453

**Comment by asubiotto** [comment]
cc @mjibson any thoughts on what the best way to encode `apd.Decimal`s would be?

**Comment by mjibson** [comment]
apd just got [Compose and Decompose](https://godoc.org/github.com/cockroachdb/apd#Decimal.Compose) support which will be used in an upcoming Go release for database/sql serialization of decimals. You could use that for now.

It's not the fastest possibility (because it does some endian swapping), but it is already written and works with primitive types. For highest speed work I'd recommend copying those functions but removing the byte swapping.

**Comment by arctica** [comment]
We have a big table with a lot of DECIMAL columns for timeseries purposes. Support for DECIMAL in vectorized execution could be very interesting.

Additionally we also have a TIMESTAMP column which prevents vectorized execution. Should I open an issue requesting support for this data type?

**Comment by asubiotto** [comment]
Hi @arctica,

Thanks for your interest in vectorized execution! Supporting `DECIMAL` is a priority for us although we're working on adding external storage to support spilling to disk for large queries first. We'll update this issue once we start working on `DECIMAL` support.

With respect to `TIMESTAMP`, we added support for it in https://github.com/cockroachdb/cockroach/pull/42416, which should be in the 19.2.1 release (to be released in the next few weeks).

**Comment by jordanlewis** [comment]
Did we solve this with flat decimal? @yuzefovich

**Comment by yuzefovich** [comment]
We do support encoding decimals since #43311, but the speed of serialization of decimals is much to be desired (e.g. [here](https://gist.githubusercontent.com/yuzefovich/97c514b772e5bf1bc63f584203e6deaf/raw/9ee33b11f3834bc3eee799df07a39f547213fb3c/colserde%25206%2520commits) are up-to-date numbers). I think we can close this issue and #44195 tracks the improvement to the speed of serialization.
