### ISSUE TITLE
importccl: import never completes, but doesn't fail. 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#37142]
**Describe the problem**
User is importing  json blobs under a UUID key (trying to migrate an HBase workload) and the import never completes, just hangs. 

**To Reproduce**
User is able to reproduce each time the import, they have provided their DDL, as well as goroutines from when the import stalls, it can all be found [here](https://drive.google.com/drive/u/0/folders/1YdwtdbWVnsRaSIAZOa-u05izRJE3qnO0).

User is deploying us on GKE, using n1-standard-4 machines, total of 12 nodes. 

If possible, provide steps to reproduce the behavior:

**Expected behavior**
Import should finish even if it takes a while, but should just hang indefinitely without any progress. 

**Environment:**
 - CockroachDB version v19.1.0-rc.2
 

Epic CRDB-8816

Jira issue: CRDB-4447

**Comment by plaflamme** [comment]
FYI: the latest time I tried was with `v19.1.0-rc.3`; same behaviour was observed.

**Comment by dt** [comment]
I looked though the debug.zip and it said node 9 was running the job. The logs for node 9 have a couple hundred of these: `jobs/registry.go:327  error while adopting jobs: unable to acquire lease: job-update: split failed while applying backpressure: could not find valid split key`.

That usually means we have a an overfull range that can't split because it's all revisions of the same row and we can't split mid-row. This used to happen with jobs records when we a) re-wrote metadata to update progress and b) wrote progress information too often: we'd hit 64mb of revisions for a single job row very quickly, since each frequent (due to progress) revision rewrote a large amount of (static, unchaining) metadata. We tried to fix that by writing the big metadata in one part of the row and then the often updated progress in a different part (i.e. separate column families), so updating the progress didn't need to re-write all the metadata and though we'd seen the last of this issue. Apparently not.

So I think that means either we have a _giant_ amount of fixed metadata (unlikely, but I think I figured out a way it'd be possible with large keys as samples) or we have too much progress info being updated too often. We asked @plaflamme to check the raw sizes of the details and progress fields of the job, and the details field was 2.9mb while the progress was 70kb. That rules out the _giant_ static metadata, and suggests progress is to blame. 

Progress consists of `numNodes*3` floats and a list of resume spans. 12 nodes means 144 bytes of floats so to get to 70kb that has to be the resume spans. We update the write progress every time we finish flushing a "span" assigned to the the sst writer process. Each of those assigned spans is picked via sampling the produced data before importing it. The default sampling targets 5*32 = 160mb of import data per span. This 230gb import, at 160mb per span, would thus expect 1430ish spans. 1430 updates to a 70kb progress record will easily break out 64mb row limit. 

Aggressively lowering the gc ttl could help _as long as we we're flushing and updating progress slow enough that the gc can keep up_. That said, we could in theory have lots of processors flushing quickly (I mean that'd otherwise be a *good* thing since it'd mean IMPORT was nice and fast) but if that made 64mb of revisions before the gc got to it, we could be back in trouble.

I think we might want to try to make fewer spans and thus fewer progress updates (with more time between them) for an import this big.  For legacy reasons, the knob that controls the target amount of data in each span is called `sstsize` (it no longer affects sst sizes though). It is passed in the job as an option, e.g. `IMPORT ... WITH sstsize='4gb';` 

Thus, I think the best bet might be to reconfigure the zone for the jobs table with a 30s gc.ttlseconds, cancel the old import, then try running the IMPORT job with `WITH sstsize = '4gb'` and see how that goes.

Incidentally, for the next release we plan on switching implementations of IMPORT to one which doesn't sample spans at all. As it stands it still allows individual processors to update the job progress directly, but this is making me realize they should stream their progress back to the coordinator and it should merge those to then do a bounded number of progress updates at fixed intervals rather than having it depend on cluster size.

**Comment by plaflamme** [comment]
@dt thanks for the hints. With the following:

* `gc.ttlseconds=30`
* `WITH sstsize = '4gb'`
* a fresh cluster with 16 nodes and 700GB SSD drive each

I was able to import the table. The reported duration was 8:19:32 for a total of 2.7TB in ~150K ranges.

Note that even though the cluster had enough space for the resulting table, I had to increase its size because the import was failing due to some nodes running out of space (12 nodes with 325GB drives).

As for the next release feature that doesn't sample, is this the one behind the `experimental_direct_ingestion` flag? If so, I tried this originally and it resulted in a very large range distribution skew: some nodes had ~35K ranges and others had ~4K.

**Comment by dt** [comment]
@plaflamme Hooray, I'm glad it finally worked! As one of the ones who wrote a lot of `IMPORT`, I'm also sorry to have left so many rough edges in there for you to his, but thank you for your patience working though them and being so helpful in debugging them with us!

Existing `IMPORT`'s architecture requires multiple passes to read/sample/partition the data and significant headroom (at least 2-3x) to buffer, sort and then ingest it. These issues with larger (>20gb) imports have been on our TODO list to address, but fixing them will require a pretty significant re-architecture of how IMPORT worked which we hadn't yet gotten a chance to do.

The good news is that we're now starting on that, and `IMPORT` should work _much_ better for larger datasets when 19.2 is released later this year. The prototype of that work is the `experimental_direct_ingestion` flag you found, but, as you noticed, it is still in the prototype stage. Among the prototype's major outstanding issues is that it doesn't actively balance the work it does around the cluster, which I think you observed. Hopefully we'll have a much smoother experience for larger bulk IMPORTs ready to use in a few months though.

**Comment by plaflamme** [comment]
@dt Sounds great! Thanks for your work on `IMPORT`; it's a pretty fundamental component for any "migration" use case. We'd like to see the time to migrate large-ish tables like this one down substantially. As we continue working on our POC, we may be able to help test some of these new features or fixes.

**Comment by tim-o** [comment]
Zendesk ticket #[3259](https://cockroachdb.zendesk.com/agent/tickets/3259) has been linked to this issue.

**Comment by andrewbaptist** [comment]
I'm looking through issues related to "split failed while applying backpressure" - this seems pretty stale as the import is fundamentally different than it was 4 years ago. Should we close this issue out?

**Comment by andrewbaptist** [comment]
I'm looking through issues related to "split failed while applying backpressure" - this seems pretty stale as the import is fundamentally different than it was 4 years ago. Should we close this issue out?

**Comment by stevendanna** [comment]
Closing this issue. CockroachLabs is certainly happy dig into IMPORT performance issues that still exist in recent versions.
