### ISSUE TITLE
ui: capture cluster events

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3725]
We should be capture significant cluster events and expose them via an API and in the UI. I've started a list of event types and I'd appreciate feedback on events that should/shouldn't be created.

*\* = near term

Cluster events
- **Cluster initialized
- Cluster enters warning state
- Cluster enters unhealthy state

Node events
- **Node found and added
- Node found, unable to add
- **Node lost (unable to communicate with node)
- Node rediscovered (after a node was first lost)
- *\* Node removed (node removed from cluster)
- Node restarting
- Node shutting down
- Node unhealthy
- Node returned to healthy state (recovered)
- Node experienced a crash

Store events
- **Store low on capacity
- Store full
- Store error

Range events (these will quickly become too frequent to be useful, but illustrate the system working early on)
- **Range split
- Range merge
- Range beginning election
- Range elected new leader
- **Range rebalancing

User Events (all have an associated user)
- New user created
- User deleted
- User's permissions changed

Database Events (all have an associated user)
- **New database created
- Database permissions changed
- **Database deleted

Table Events  (all have an associated user)
- **New table created
- Table schema change started (include whether columns/indices changed)
- Table schema change completed
- Table permissions changed
- **Table deleted

Other Alerts
- CPU high on node
- Memory usage high on node

**Comment by petermattis** [comment]
Nice list.

How can a node be "found" and not added? How can a node be "lost"? I think it will be cognitively simpler to records events like "Node added" and "Node removed".

**Comment by maxlang** [comment]
> How can a node be "found" and not added

I don't know if this can happen currently, but this has happened with other systems I worked on where a machine is able to communicate but isn't able to join. Could be something as simple as very stale data or a version mismatch. If stuff like this can't happen currently then we don't need an event for it.

> How can a node be "lost"

I wanted to make a distinction between purposeful (node deliberately removed from the cluster because we don't need that machine) and accidental (we're not sure what happened but we haven't been able to reach that node.) After a node has a been lost for a time, I suppose it would be removed. I'll add this as a separate event.

**Comment by petermattis** [comment]
On Sun, Jan 10, 2016 at 2:13 PM, Max Lang <notifications@github.com> wrote:

> How can a node be "found" and not added
>
> I don't know if this can happen currently, but this has happened with
> other systems I worked on where a machine is able to communicate but isn't
> able to join. Could be something as simple as very stale data or a version
> mismatch. If stuff like this can't happen currently then we don't need an
> event for it.
>
This currently can't happen, but at some point when it does I would model
it as the node being added but being immediately unhealthy with the reason
being version mismatch. This would have symmetry with an existing node
being restarted and coming back up with a mismatching version.

> How can a node be "lost"
>
> I wanted to make a distinction between purposeful (node deliberately
> removed from the cluster because we don't need that machine) and accidental
> (we're not sure what happened but we haven't been able to reach that node.)
> After a node has a been lost for a time, I suppose it would be removed.
> I'll add this as a separate event.
>
Yes, there should be a distinction. "Node removed" would refer to a node
been purposefully removed. "Node dead" would indicate a node that is
nominally still part of the cluster but hasn't been heard from in a while.
I'm not terribly fond of the term "lost" because it connotes a bit of
"removed" and "dead" without indicating which.

**Comment by maxlang** [comment]
Sounds good, I've updated the list to reflect this.

**Comment by mrtracy** [comment]
I've been working towards this issue quite a bit: there are now two tables, `system.rangelog` and `system.eventlog`, which record a small number of the events previously outlined.  From this point on, logging additional event should be relatively simple in most cases; that said, for many of our remaining target events it is difficult to determine exactly when the event has happened (e.g. a node goes down).

I am converting the original list in this issue into a checklist below, _excluding events which are not relevant to the beta of CockroachDB_; I am also dividing up the events into a few sections:

+ **Auditable state changes** occur when the cluster is modified as a direct result of a user action.  These changes have a permanent effect on the preferred state of the cluster.
+ **Dynamic state changes** occur when the cluster's state is modified as a result of a non-user event, such as an automatic process or a natural event (i.e. machine down).  These changes have an effect on the state of the cluster, but are expected to be temporary.
+ **Anomalies** occur when an undesirable or otherwise interesting occurs, but the event did not modify the state of the cluster in any permanent way.

### Auditable Changes
##### Cluster Events
+ [ ] Cluster initialized
+ [ ] Node joins cluster
+ [ ] Node clean shutdown
+ [ ] Node restarted after clean shutdown

##### DDL Events
+ [x] Database Created
+ [x] Database Dropped
+ [ ] Database Altered
+ [x] Table Created
+ [x] Table Dropped
+ [ ] Table Alteration (phased process, events for both begin and end)
+ [ ] Index Creation (phased process)
+ [ ] Index Alter (phased process)
+ [ ] Index Drop (phased process)
+ [ ] GRANT on any database object
+ [ ] REVOKE on any database object

### Dynamic Changes
##### Cluster Health Events
+ [ ] Node marked down
+ [ ] Node marked dead
+ [ ] Node recovering after marked down or dead
+ [ ] Node marked up
+ [ ] Node quarantined

##### Balancing Events
+ [x] Range Split
+ [x] Replica change for range
+ [ ] Quorum loss detected for range
+ [ ] Quorum restored for range


### Anomalies
+ [ ] Store capacity full
+ [ ] Logged Error
+ [ ] High CPU usage
+ [ ] High memory usage

**Comment by JackKrupansky** [comment]
Does "(phased process)" for DDL events encompass the notion of backfilling
that has a start, end, and status? I wouldn't expect the event table to
give the status of backfill, but at least the DDL even itself could
indicate what degree of backfilling might be required.

-- Jack Krupansky

**Comment by petermattis** [comment]
I think we should leave out the Anomalies from the event log, at least in the short term. While we definitely want to highlight those anomalies in the UI, there are some irritating heuristics to develop to determine how and when to log about them. 

We also have to be careful about the "quorum {loss,restored}" events. We don't want to get into a situation where a partial cluster outage causes an event log storm.

**Comment by maxlang** [comment]
@mrtracy maybe we should create a new issue for the events we wish to capture for beta. Regardless, reassign this to me once you have the events you want to capture and I'll add them to the UI.

**Comment by cuongdo** [comment]
I haven't looked closely, but here's Hashicorp's gossip-based membership and failure detection library:

https://github.com/hashicorp/memberlist

**Comment by vivekmenezes** [comment]
@mrtracy should we close this issue?

**Comment by mrtracy** [comment]
Yes, this is not informing our planning process and is likely to rot even further.

**Comment by mrtracy** [comment]
I've created a new issue for the DDL events: #13492. I think that those events are non-controversial and should definitely be in the log. 

Most of the other incomplete events are things that we don't want to log as events anymore - they represent the detection of an abstract occurrence and the logging of a concrete event in reaction to that. In contrast, all existing events (and the remaining DDL events) result from a distinct action on the part of the user or an automated process.
