### ISSUE TITLE
workload: add flag to remove FKs and Indexes from tpc-c

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37265]
**Describe the problem**

We want to test FK performance by using TPC-C with and without FKs. It requires a manual process to remove FKs (and their indexes) that can be error-prone and time-consuming. I'd like to add a flag to workload to load TPC-C without these FKs and indexes for easier testing. 

Here is what needs to be removed:

FKs
- [x] ALTER TABLE customer DROP CONSTRAINT fk_c_w_id_ref_district;
- [x] ALTER TABLE DISTRICT DROP CONSTRAINT fk_d_w_id_ref_warehouse;
- [x] ALTER TABLE history DROP CONSTRAINT fk_h_c_w_id_ref_customer;
- [x] ALTER TABLE history DROP CONSTRAINT fk_h_w_id_ref_district;
- [x] ALTER TABLE tpcc.order DROP CONSTRAINT fk_o_w_id_ref_customer;
- [x] ALTER TABLE order_line DROP CONSTRAINT fk_ol_supply_w_id_ref_stock;
- [x] ALTER TABLE order_line DROP CONSTRAINT fk_ol_w_id_ref_order;
- [x] ALTER TABLE stock DROP CONSTRAINT fk_s_i_id_ref_item;
- [x] ALTER TABLE stock DROP CONSTRAINT fk_s_w_id_ref_warehouse;

Indexes:
- [ ] drop index order_idx cascade;
- [x] drop index history_h_w_id_h_d_id_idx;
- [x] drop index history_h_c_w_id_h_c_d_id_h_c_id_idx;
- [x] drop index order_o_w_id_o_d_id_o_c_id_idx;
- [x] drop index order_line_fk;
- [x] drop index stock_s_i_id_idx;

**Comment by yuzefovich** [comment]
Nathan made many modifications to TPCC workload in #36854, and one of those changes resolves this issue.

In order to import the data without the foreign keys, you simply specify `--fks=false` on the import command as follows:
`roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=1 --db=tpcc --fks=false"`.

I've just confirmed that the data is imported without the FKs and indexes. One exception is index `order_idx` which is present. I'm guessing that it exists for performance reasons, but an ability to drop it on demand by a flag is desired, I could add a minor modification to the workload.

**Comment by yuzefovich** [comment]
@awoods187 please let me know whether any extra work is needed here (like an option to drop `order_idx` via a flag or something else).

**Comment by awoods187** [comment]
I think my needs are met by @nvanbenschoten's change. Thanks all!
