### ISSUE TITLE
kv: optimize hlc.Clock interaction in DistSender.sendSingleRange()

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#37279]
As a part of the effort to reduce contention on the hlc.Clock mutex we notice that one of the largest sources of writes the call to `hlc.Clock.Update()` in `kv.DistSender.sendSingleRange()` [here](https://github.com/cockroachdb/cockroach/blob/38d473e5b07010a96a02278f540010479d5bba9c/pkg/kv/dist_sender.go#L504). This call throws away the return value and thus could be optimized to have a fast path that only acquires the an exclusive lock after determining that the clock's current value is behind the value being written.

Part of #37276.

**Comment by xuhui-lu** [comment]
hey, I am interested in this ticket, may I pick it up?

**Comment by xuhui-lu** [comment]
@ajwerner any updates?

**Comment by erikgrinaker** [comment]
Had a quick look at this. Some related optimizations were already made in 38a4cbe92e343f5b8e9d8cbda2d279fff3561c8f, which may alleviate this somewhat.

A naïve approach would be for `Clock.Update()` to return immediately without locking if `rt.WallTime < c.getPhysicalClockAndCheck()`. I believe this is safe in principle, since `Clock.Now()` will never return a time less than the physical clock. However, since it's possible for the physical clock to jump backwards I believe we would have to update `c.mu.timestamp.WallTime` for this to be safe, which would require taking out the lock after all.

An alternative might be to use a `RWMutex` and take out a read-lock first to check against `c.mu.timestamp.WallTime`, and then recheck with a write-lock if necessary. Is there a reason why we don't already use `RWMutex` here? Also, do we have a benchmark suite which would be appropriate for testing this?

**Comment by erikgrinaker** [comment]
Occurred to me that we can use atomic updates for `Timestamp.WallTime` even though updates and other fields must be protected by the mutex. Submitted #56708 for this, which shows an order of magnitude improvement under high concurrency on a (probably unrealistic) micro-benchmark.
