### ISSUE TITLE
disable or remove range tree code

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3739]
The range tree code isn't being used and there are no plans to use it for beta or 1.0. We should either find a use for it, disable it or remove it.

**Comment by tschottdorf** [comment]
It's got use cases in the design document, though I'm not convinced that it's going to live up to the premise (I have certain doubts about the maintainability of the data structure as it is, but haven't looked at it much). Disabling it just means it's going to rot, so maybe what we ought to be doing is figuring out whether we're eventually going to want it and if so, leave it in/exercise it in some other way, and otherwise stripping it out.

**Comment by JackKrupansky** [comment]
What benefit will be lost by not using a range tree?

The Range Metadata section of the design document gives the impression that distributed range metadata is a virtual necessity for very large databases, so is that the only real short-term benefit loss, that databases would be limited to a much more moderate size? Where in the 16T to 1P range would be the practical upper limit for a Beta/1.0 database?

Is the replacement idea to just use the metadata from Gossip? IOW, the full cluster range is determined virally as nodes connect rather than recorded in the Range Metadata in the local key store?

Would there still be range metadata in the key store, but just a single level for the local keys rather than a multi-level (tree)?

**Comment by petermattis** [comment]
Range Metadata != Range Tree. The Range Tree does not affect how large databases can be. The Range Tree was imagined as a way to distributed data for map-reduce operations, but we currently haven't had a need for it.

I'm not at all convinced that the Range Tree will be the right tool for distributing SQL queries. It feels a bit like a hammer in search of a nail. If we encounter a problem that needs a hammer we can always resurrect it.

**Comment by tschottdorf** [comment]
I'm ok with that. @spencerkimball what do you think?

**Comment by spencerkimball** [comment]
It'll surely rot if we toss it. I'd prefer to keep it because I'm
envisioning a 20% time project to do a simple map reduce implementation
using it. Is it causing any issues right now?

**Comment by tschottdorf** [comment]
Haven't seen it trouble anyone for a long while (basically since response
cache overhaul)

**Comment by petermattis** [comment]
A simple map-reduce implementation doesn't require the range spanning tree. Yes, a map-reduce implementation could use such a tree, but it could also look at the normal range metadata. IMO, there is more speculation in the range spanning tree than warrants its continued existence at this time.

Is the range tree code causing issues? There are tests that need to be updated when making various changes. And the performance impact has never been evaluated.

**Comment by spencerkimball** [comment]
Performance impact is likely minimal, though I agree it hasn't been tested
– range splits already will require a distributed transaction on any sort
of non-trivial sized database.

If you feel this strongly, go ahead and remove it. We're not going to be
trying to use it anytime soon.

**Comment by tschottdorf** [comment]
if we keep it, let's add its contribution to the trace. Just so that if it does add (on a larger cluster, if it needs to rotate all the way up to the root, that's a lot of RPCs), we see it.

**Comment by BramGruneir** [comment]
The implementation is that of of a pure red black tree, not a left leaning one.  So it should minimize the number of rotations required.  But I agree, we should add it to trace.

For insertions (splits in our case) It should have a max of 2 rotations.
For deletions (merges in our case) it should have at most 3 rotations.  

However, there is the possibility of having to recolour all the nodes leading up to the root in the very worst case.  So O(log(n)) is the worst case number of operations, but is exceedingly rare.

**Comment by petermattis** [comment]
Sounds like we're keeping the range tree code for now. As we do larger scale benchmarking involving splits we should keep in mind testing with the range tree code disabled to see what it's performance impact is.
