### ISSUE TITLE
sql: enhance setting of locality 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37429]
Opening a separate issue from https://github.com/cockroachdb/cockroach/issues/37310

@andy-kimball points out:

> The more I work with constraints and localities, the more I think we've missed the boat on making them intuitive to use. Each person who's tried using the new locality-sensitive optimizer feature (Andy W, Rich, Roko, Nate) has been confused by some aspect of how to set it up. One of the reasons is due to the strange syntax:
>
>CONFIGURE ZONE USING lease_preferences='[[+cloud=aws,-region=us_east], [+cloud=gce,+region=us_west]]'
> instead of something that feels more natural with SQL, such as:
> 
> CONFIGURE ZONE USING LEASE PREFERENCES ON cloud='aws' AND region<>'us_east', FALLBACK TO cloud='gce' AND region='us_west'
> I'd expect to use strongly-typed localities, so that I get an error if cloud is not a valid locality field. I'd expect that ZONEs and LOCALITYs are first-class schema objects that are versioned just like any other schema objects (with changes rolled out across cluster in same way).
> 
> I know I'm pulling in a bunch of extra stuff into what seems like a simple issue. But it's context to help others understand why I think we should at least consider more strongly-typed handling of LOCALITY. If we really want geo-distributed use-cases to be a centerpiece of our strategy, I think we need to recognize that we've made some usability mistakes so far, and consider rectifying them (in a future release) with better syntax and stronger typing.

I tend to agree and think we should consider this work for 19.2.

**Comment by petermattis** [comment]
A related issue, but likely a separate work item: we should allow changing the locality tags for a server without restarting. Currently the locality is set via a flag which requires a server restart. Fixing this is almost trivially easy and I just recently became aware that it is a headache to require a server restart to change the locality tags for a server.

**Comment by knz** [comment]
>  we should allow changing the locality tags for a server without restarting. 

Funny you should say that, I remember one of our customer asking for this before. Filed #37787.

**Comment by jseldess** [comment]
As the person who documented zone configs initially, and found it hard, I love the general direction of this request. One question I have is: If replication zones are defined directly in schemas, how would we handle the cluster-wide replication zone (`.default`) and system range replication zones like `.liveness`?

**Comment by andy-kimball** [comment]
Say I run this:
```
ALTER TABLE t CONFIGURE ZONE USING constraints='[+region=us-east1]';
```
and then this:
```
SHOW CREATE TABLE t
```
I'd expect the output of the table to include the configured zone, but it doesn't today. I'd also expect to be able to use `CONFIGURE ZONE` directly within a `CREATE TABLE` statement, but can't do that today.

Furthermore, when a new zone is created, it becomes part of the gossiped system config information rather than being part of SQL schema. This causes various anomalies, like not being able to rely on versioned schema when compiling queries, and not working consistently with `AS OF TIME`.

**Comment by jordanlewis** [comment]
> Furthermore, when a new zone is created, it becomes part of the gossiped system config information rather than being part of SQL schema. This causes various anomalies, like not being able to rely on versioned schema when compiling queries, and not working consistently with AS OF TIME.

@andy-kimball can you say more about this? I think it would be a significant lift to move the zones into schema definitions. I'd like to make sure there's a good enough reason to make that kind of sweeping change.

Ideally, I'd like to see an example. I don't understand how you'd expect zones to work properly with `AS OF SYSTEM TIME` even if they were available in the schema, since zones apply immediately, outside of what MVCC guarantees.

**Comment by andy-kimball** [comment]
From an architectural view, I think Zones should just be another part of the schema. Pretty much all the ZoneConfig related code I worked with during the last release was messy, fragile and unintuitive. I attribute that to it being "off to the side" and added early on using different design principles than we used with Schema. They're tacked on with a partial SQL syntax that was originally intended to be used for testing, and the API's to go from Table/Index/Partition schema to Zone config/constraints are surprising and unintuitive.

A good example is the code in `zone_config.go` and `zone.go` - both Radu and I really spun our wheels trying to understand and modify it to make the optimizer zone-config-sensitive. The code tries to "optimize" storage of index/partition/table configs in order to minimize the size of these zone configs (using inheritance and subconfigs), since they are passed as part of the SystemConfig gossip record. This makes the zone configs really tricky and error prone, and caused multiple bugs in my implementation (e.g. see https://github.com/cockroachdb/cockroach/pull/36689).

Also, rollout of ZoneConfig changes is done through gossip rather than through the usual schema rollout mechanism. This means we can't look at jobs to track progress, we have no idea when the rollout is done, etc. It also is really awkward to detect when changes to ZoneConfigs occur - I can't just look to see if the version has been incremented, as with schema.

Overall, I had a very negative experience with Zones/Constraints/Configs as part of my optimizer work. It took me much longer than it should have to land the locality-sensitive optimizer changes. I got confused and surprised repeatedly by how they worked.

All that said, I'm advocating for a particular high-level ideal architecture. I'm not arguing that there's an urgent need to do anything right now. But if/when we decide we want to make substantial changes to the Zone-related code, I think that's the time to consider adopting a more integrated architecture.

Finally, regarding `AS OF SYSTEM TIME`, you could be right that it doesn't make sense with zones. I haven't thought that fully through...

**Comment by ajwerner** [comment]
@awoods187  should we close this?

**Comment by awoods187** [comment]
Yeah it seems out of date at this point.
