### ISSUE TITLE
Column names in to_json does not match PostgreSQL

### ISSUE THREAD

**Issue by simjesp** [cockroachdb/cockroach#37478]
**Describe the problem**

When using JSON built-ins (e.g. TO_JSON, JSON_AGG), it seems that column names are discarded as property names and replaced with "f1"..."fn" instead, which doesn't match PostgreSQL behavior.  

**To Reproduce**
For the following schema

```
CREATE TABLE public.test(
	column1 varchar,
  	column2 varchar
);

INSERT INTO test VALUES ('Hello', 'World');
```
Running the following query yields different results in CockroachDB (v19.1.0) and PostgreSQL v10.0 (example in this [DB Fiddle](https://www.db-fiddle.com/f/6WY8CdG1h8hrpXxEf3jMcY/0)) 
```
SELECT TO_JSON(x.*) FROM (SELECT column1, column2 FROM test) x`
```
PostgreSQL will output
```{"column1":"Hello","column2":"World"}```

While CockroachDB will output
```{"f1": "Hello", "f2": "World"}```

The same behaviour can be observed using JSON_AGG

**Additional details**
A quick glance at the source would indicate that this line 			```builder.Add(fmt.Sprintf("f%d", i+1), j)``` in pkg/sql/sem/tree/datum.go is the culprit, but i don't quite have the insight into the source to gather where the column name would be available from. 

**Expected behavior**
Expected behavior is that the JSON output would match that from the same query in PostgreSQL.

**Comment by jordanlewis** [comment]
Thanks for filing.

Tuple labels are stored in the tuple type struct. Unfortunately, builtin functions don't currently have access to the fully-realized type of their input, since overload resolution takes care of finding the right builtin for a function signature. That means that builtins currently can't know the tuple labels of their input, which is why the to_json function can't see those column types.

A fix for this requires devising a way to let builtin functions see the full type of their input arguments.
