### ISSUE TITLE
Regarding the use of certificates between nodes, I have a few questions I would like to ask?

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#37502]
Regarding the use of certificates between nodes, I have a few questions I would like to ask?
1. If the production environment is used, what is the problem with the --insecure mode?
2. When I developed another project, I encountered a cluster A raft package sent to another cluster B, which led to the inexplicable raft package often received in cluster B, and the raft package will also flow to the leader election and Change leader's fsm, the reason is that the node of the same IP is removed from cluster A, and then added to cluster B after initialization. The problem of raft packet is caused. Is the certificate of communication between nodes below to solve this problem?

**Comment by tim-o** [comment]
@yangxuanjia 

1. If you are using an insecure cluster, anyone could connect directly to the cluster without providing any authentication, whether a password or certificate. This is very risky since an attacker would only need access to the network to start messing around with your production data. Production deployments should be secure.
2. I can't really comment on what you encountered on another project - in our case, if you wanted to cycle a node from one cluster to another, you would need to wipe the node's store first, or create a new store. Otherwise you'll get an error when the node recognizes that the cluster it thinks it belongs to doesn't match the ID of the new cluster.

Hope that helps!

**Comment by mberhault** [comment]
1. `--insecure` means a few things:
  - all communication (node-node and client-node) is unencrypted
  - peers are not authenticated
  - there are no passwords, and anyone can connect as `root`
  This means that `--insecure` is absolutely inappropriate for production use, it should be for testing and local development only.
2. When running securely, nodes verify each other's certificates when a connection is established. As long as the CA is unique to the cluster (no one outside the Cockroach nodes and clients have certificates signed by this CA), only nodes with certificates signed by the same CA can talk to each other.

Please feel free to re-open if you need more details. However, these kinds of questions are best asked on the [forum](https://forum.cockroachlabs.com/).
