### ISSUE TITLE
sql: include anonymized query with internal error reports

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#37514]
This PR tracks making sure that the anonymized query shows up in Sentry reports that are filed when an `AssertionFailed` error is caught. See discussion here:

https://github.com/cockroachdb/cockroach/issues/37444#issuecomment-491320677

**Comment by RaduBerinde** [comment]
Pasting @knz's comment below:

---

It's because it's an error, not a panic.

The statement is (currently) added only upon panics in `(*connExecutor).closeWrapper()`, which is called under `recover()` in `(*Server).ServeConn` (`conn_executor.go`)

The proper way forward is to extract the logic which string-ifies the currently executing statement to a separate function, then:

- have that function called from `closeWrapper` to do the same as it does today
- add a call to that function at the end of `(*connExecutor).execCmd()` in the error path, next to the call to `ex.sessionEventf(ctx, "execution error: %s", pe.errorCause())`, and decorate the error with `Wrapf(... log.Safe())`

**Comment by RaduBerinde** [comment]
I tried inducing an internal error in the optimizer with no other changes, and I triggered it exactly once. I noticed that we get two events in sentry. One has the statement and one doesn't:
https://sentry.io/organizations/cockroach-labs/issues/1033682764/events/

Any idea what's going on? And why we don't get the same in the report in #37444 (based on the times we do get them in pairs, but neither has the statement)? I put the error in the same place where we hit the error in that issue. Maybe something changed here between 19.1 and master?

**Comment by RaduBerinde** [comment]
I ran the same test on 19.1 and I do see two reports but neither contains the statement.

The two reports come from these two lines (CC @andreimatei):
https://github.com/cockroachdb/cockroach/blob/c8bda1de440cfe90cf23a433119d77795cfa0047/pkg/sql/conn_executor.go#L1344:

(`recordError` and `Close->bufferErr->writeErr->RecordError`).

On master, the first report includes the statement. Not sure what exactly changed in that code path (so we can backport it).

**Comment by knz** [comment]
Yes there is a change between 19.1 and master that causes this - Ben included a forced error report in pgwire which is extraneous when SQL already does the right thing.

Compare the error handling in pgwire between 19.1 and master and see what I mean. If you can identify the commit that fixed that, perhaps you can backport. Otherwise I can look later this week.

**Comment by RaduBerinde** [comment]
AFAICT the report from pgwire doesn't include the statement (in either 19.1 or master). Something changed w.r.t. the first call (to recordError).

**Comment by knz** [comment]
I dug into the code and I found the culprit:  #23278 enhances sentry reports with the tags available in the context,
then Andrei's PR #35805 adds the statement as a tag.

@andreimatei  I do not approve of how #35805 influences Sentry reports really. It's too much magic -- too much reliance on having the proper context object available during error reporting.
IMHO the correct solution would be to use an error wrapper that carries the statement with `log.Safe()`, in the manner advertised by #36987.

**Comment by knz** [comment]
Also, FYI the Sentry "tags" field is not meant to carry long strings. When I was last looking at them they were truncated at some point. Better use the "extra" fields in the sentry packet instead.

**Comment by RaduBerinde** [comment]
Andrei, putting this on your plate.

**Comment by RaduBerinde** [comment]
BTW this is the patch I was using to return an internal error from the optimizer:
```
@@ -222,6 +222,21 @@ func (o *Optimizer) Optimize() (_ opt.Expr, err error) {
 		)
 	}
 
+	// haha
+	//
+	{
+		lol := false
+		rootProps.ColSet().ForEach(func(col int) {
+			if o.mem.Metadata().ColumnMeta(opt.ColumnID(col)).Alias == "lolomg" {
+				lol = true
+			}
+		})
+
+		if lol {
+			return nil, pgerror.AssertionFailedf("radu's test error 5. situation normal")
+		}
+	}
+
 	return root, nil
 }
```

Then run query `SELECT 1 AS lolomg`

**Comment by andreimatei** [comment]
Wait, what did I do?

> @andreimatei I do not approve of how #35805 influences Sentry reports really.

I didn't intend for #35805 to have anything to do with Sentry reports... But how does it influence it? I don't see the statement being added as a tag to any context... Where does that happen?

I only see this code which we've had for a while, which adds the statement as a random value in the context:
https://github.com/cockroachdb/cockroach/blob/5fa1a4de3daf6d1696a5ad373a2b9faa742275a4/pkg/sql/conn_executor.go#L1200

But anyway now that we're talking, the wip code I'm passing around with @spencerkimball for the tracing stuff does start to use more tags cause they have a big role in the UI, including a tag for the statement. I didn't know these are supposed to be private. Perhaps we can introduce a naming convention to have some of them not be included in Sentry?

Anyway, I don't really want this on my plate :). I don't quite understand what the problem is and what needs to be done :)

**Comment by knz** [comment]
The problem is that the context annotation added by `withStatement` is included in the Sentry report thanks to Solon's work in #23278.

I do not know who should do the work, but I'd like to point out that:

- Andrei your change in #35805 is somewhat responsible for including that statement in Sentry reports, because prior to this change, `withStatement` was not on the path to error reporting.

- Solon's PR #23278 abuses the "tags" field in the Sentry report to populate the statement in the error report. That is unfortunate because Sentry tags are not meant to be used like that. The proper way to do this is to use "extra" fields.

At the end of the day, the current situation is not good because of the combination of the two things. I do not know who "owns" the situation but I recommend that something be done about it.

cc @jordanlewis

**Comment by justinj** [comment]
This came up again in #38052—anything I can do to help get this working again?

**Comment by awoods187** [comment]
this seems super useful--glad we are working on it

**Comment by RaduBerinde** [comment]
We don't seem to be getting anywhere here, and this is a big problem on 19.1. I'd like to separate two things:
 - the minimal fix we can backport to 19.1 so that at least one of the two filed reports contains the statement.
 - the right thing to do on master going forward (a single report with the statement, better use of Sentry tags/extra fields, etc).

Let's focus on the first one for now. I don't have an idea for what we need to do. Probably someone needs to spend some more time and understand this better. Maybe @jordanlewis can designate a person - will someone from your team be maintaining the executor going forward?

**Comment by knz** [comment]
Ok try this:

1. in `dispatchToExecutionEngine`, there is a `defer` near the beginning:

```go
  defer func() {
    planner.maybeLogStatement(ctx, "exec", ex.extraTxnState.autoRetryCounter, res.RowsAffected(), res.Err())
  }()
```

Add this inside the defer, after the `maybeLogStatement`:

```go
  if err := res.Err(); err != nil {
     res.SetError(errors.Wrapf(err, "context: %s", log.GetContextString(ctx)))
  }
```

2. in `pkg/util/log/crash_reporting.go` make a new function `GetContextString(ctx context.Context) string` which works as follows:

```go
func ... {
  var buf bytes.Buffer
    for _, f := range tagFns {
    v := f.value(ctx)
    if v != "" {
      fmt.Fprintf(&buf, "%s: %s", f.key, v)
    }
  }
  return buf.String()
 }
```

This will piggy back on the stmt registration already performed by Solon.

Alternatively for step 1 you can try to add this in the defer instead:

```go
  // TODO(knz): replace by use of the error library.
  if err := res.Err(); err != nil {
     pqErr, ok := pgerror.GetPGCause(err)
     if !ok {
        pqErr := pgerror.New(..., "%v", err)
     }
     pqErr.SafeDetail = append(pqErr.SafeDetail, &pgerror.Error_SafeDetail{SafeMessage: log.GetContextString(ctx)})

     res.SetError(pqErr)
  }
```

I don't know which of the two methods provides the better quality reports, you'd have to try.

**Comment by RaduBerinde** [comment]
I tried it but I don't see the context in Sentry: https://sentry.io/organizations/cockroach-labs/issues/1085547442/?project=164528&query=radu&statsPeriod=14d

 It also makes the error look pretty awful:
```
Error: pq: context: statement: SELECT _ AS _
: internal error: radu's test error 6. situation normal
Failed running "demo"
```

**Comment by knz** [comment]
ok sorry my advice above was wrong.

For step 2 you can either:

- use my first snippet but use `pgerror.Wrapf(...)` with `log.Safe(log.GetContextString(ctx))`  (not `errors.Wrapf`)

- or the second snippet, the one that appends manually to `SafeDetail`.

Have you tried this second one btw?

(I can have a look later this week if you can't make it work)

**Comment by RaduBerinde** [comment]
I tried the second one and it reports to sentry, but we lose the return code in some cases (I think there's code in `pgerror` which recognizes certain errors). I'll try the other version when I can.

**Comment by RaduBerinde** [comment]
First one seems to work great, I'll send out a PR. Thanks!

**Comment by RaduBerinde** [comment]
I spoke too soon.. This fails quite a few SQL tests because the error message is prepended with the new stuff. I could fix those, but I'm not entirely sure we want all errors to change in this way, e.g.:
```
root@127.153.131.195:38393/defaultdb> select * from t.a;
pq: statement: SELECT * FROM _._: relation "t.a" does not exist
```

**Comment by RaduBerinde** [comment]
What if we only do this extra wrapping for internal errors? We could even do it inside `sqltelemetry.RecordError` so we don't change errors in other paths.

**Comment by knz** [comment]
That could work too
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
Tried to do it in `RecordError`, it doesn't look that the statement is in the `ctx` passed to that. I will post a PR for a variation on your initial proposal where we only add to the details of InternalErrors.

**Comment by RaduBerinde** [comment]
This problem is now fixed. I filed #38516 to keep track of the other issues we found.
