### ISSUE TITLE
Testing for value not in array column doesn't work as expected

### ISSUE THREAD

**Issue by zrsmith92** [cockroachdb/cockroach#37620]
**Describe the problem**

Testing whether an element appears in an array column using `'foo' = ANY array_column` works, but testing for the opposite with `'foo' != ANY array_column` does not. See reproduction below:

**To Reproduce**

```sql
CREATE TABLE a (b STRING[]);
INSERT INTO a VALUES (ARRAY['foo', 'bar']);
INSERT INTO a VALUES (ARRAY['baz', 'boo']);
```

Testing for an element in an array works:
```sql
SELECT * FROM a WHERE 'baz' = ANY b;
      b
+-----------+
  {baz,boo}
(1 row)
```

But the opposite does not:
```sql
SELECT * FROM a WHERE 'baz' != ANY b;
      b
+-----------+
  {foo,bar}
  {baz,boo}
```

**Expected behavior**
I would expect the last query to return only the `{foo, bar}` row, not both.

**Environment:**
 - CockroachDB version: 19.1.0
 - Server OS: MacOS 10.14.4
 - Client app: `cockroach sql`

**Additional context**

I can't find this syntax documented in the cockroach documentation, so maybe it isn't supported. It just seemed strange to me that equality works but inequality doesn't.

**Comment by solongordon** [comment]
I can see why this might be unintuitive but it is working as expected. Per our [scalar expressions documentation](https://www.cockroachlabs.com/docs/v19.1/scalar-expressions.html#multi-valued-comparisons),

> The result of the comparison is true if and only if the comparison of the left value is true for any element on the right.

`'baz' != ANY b` returns both arrays because they both contain an element which is not equal to `'baz'`. If you would like rows which do not contain `'baz'`, please specify `WHERE 'baz' != ALL b` or `WHERE NOT 'baz' = ANY b`.

Note also that this is consistent with PostgreSQL's behavior.
