### ISSUE TITLE
sql: Support syntax for TRUNCATE TABLE IF EXISTS

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#37798]
**Is your feature request related to a problem? Please describe.**

User is asking for support for `TRUNCATE TABLE IF EXISTS` since we already have support for `DROP TABLE IF EXISTS`.

**Comment by tim-o** [comment]
Zendesk ticket #[3363](https://cockroachdb.zendesk.com/agent/tickets/3363) has been linked to this issue.

**Comment by bdarnell** [comment]
This does seem straightforward, but note that it doesn't look like any other databases support "truncate table if exists" (see [this thread](https://grokbase.com/t/postgresql/pgsql-hackers/12a9q1thvk/truncate-if-exists) on the postgres mailing list where it was considered and rejected). TRUNCATE is more like DELETE than it is like DROP TABLE since it doesn't change the schema. 

The alternatives (either DROP TABLE IF EXISTS followed by CREATE TABLE, or CREATE TABLE IF EXISTS followed by TRUNCATE) are straightforward and portable, and have the advantage of leaving the schema in a definite state (the table will definitely exist) instead of continuing the uncertainty about whether the table exists or not.

**Comment by knz** [comment]
this is not supported by pg
