### ISSUE TITLE
*: audit and migrate uses of roachpb.ReplicaDescriptors.Unwrap

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#37916]
Each of these needs to be migrated to `All`, `Voters`, `Learners` (or one of the more specific methods on `ReplicaDescriptors`).

- [x] Should learners be allowed to serve follower reads? No for now. A learner is a temporary state on the way to a full voting replica. One can certainly imagine the benefits to a replica that can be read from in the past but doesn't affect quorum, but this is considered out of scope for the current project, which is to get rid of the technical debt of preemptive snapshots. This means learners also don't need closed timestamps.

- [x] Should learners be included in replica metrics? Definitely not counted as a live replica. Probably shouldn't be included in calcBehindCount. These are about the health of the voters.
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_metrics.go#L204

- [ ] Should we add metrics specifically for learners?

- [x] Quota pool? Doesn't delay until it has the snapshot, then it does. https://github.com/cockroachdb/cockroach/pull/35787#issuecomment-490004991
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_proposal_quota.go#L132
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_raft_quiesce.go#L83

- [x] Log truncation? Treat as a normal follower https://github.com/cockroachdb/cockroach/pull/35787#issuecomment-490005442

- [X] Should learners block quiescence? Yes

- [x] Allocator. Definitely we want to include learners when deciding when to add a replica, otherwise we could race and add too many. Probably should consider them for removal as well. Rebalance? I think yes for consistency with the other two.

- [x] Store QPS balancing: We don't want to use learners as candidates, since they can't be leaseholders. Do we use them when figuring out per-store qps/diversity? Probably also no

- [x] Should learners be included in consistency check? Doesn't seem particularly interesting to include them but I also don't see the harm
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_consistency.go#L307

- [x] Do learner replicas block decommissioning? On one hand, it seems like we should be waiting for every replica to be removed before the node can be turned down, but on the other hand, it can't be affecting quorum, so how disruptive is it to shut off a node with only learners left?
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/server/admin.go#L1426

- [x] How should we treat learner replicas in the admin ui (node fullness, num replicas etc)?
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/server/admin.go#L1426

- [x] Should learner replicas get passed to queues? Initial guess is it depends on the queue and this should be an option in `queueConfig` like `needsLease`.

- [x] The merge queue needs all replicas for the two ranges to be co-located. Should we just drop learners from both sides?

- [x] What happens if a range with a learner splits?

- [x] `(Replica).changeReplicas` and `(Store).AdminRelocateRange` both are dealing with a specific set of recomputed replicas and so want all replicas.

- [x] `(Replica).adminScatter` has a RandomizeLeases option, which only wants voters since learners can't be leaseholders
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_command.go#L1425

- [x] We implemented the `(ReplicaDescriptors).QuorumSize` to use voters, which is correct but looking more closely at the places where we use quorum size, it seems like we might want to include learners in some of them. Otherwise, we're basically making a decision on information that is very shortly going to be outdata. Maybe this is okay? Worth thinking about more closely

  Example: In `processOneChange`, not making changes while we don't have quorum https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replicate_queue.go#L296-L306

- [ ] `(Store).Capacity` and `updateReplicationGauges` update a set of counts. What downstream uses these counts? What if they have different preferences for whether it includes learners?

- [x] How should learner snapshots behave? There are a bunch of places preemptive snapshots get special cased (they can be rejected etc), are learner snaps the same?

- [x] A couple of tests also rely on the "snapshot intersects existing range" error to detect when we can't upreplicate over some old replica that needs to be gc'd but hasn't yet. I guess learner snapshots need the same behavior? My initial impression of this is that it seems a little bit of an abstraction breakage for a snapshot to be the detection mechanism for this, but you do need knowledge of the actual state of things on some remote node and it's not clear that anything else is better

**Comment by danhhz** [comment]
There's supposed to be a list there, but I think it's too big for github. Hmmm

**Comment by danhhz** [comment]
Additional things to audit:

- [ ] Uses of `(Store).mu.replicas`
- [ ] Uses of `newStoreReplicaVisitor`
- [ ] Uses of `(Store).VisitReplicas`

**Comment by tbg** [comment]
> Do learner replicas block decommissioning?

I think they should, to minimize log traffic when the node does get shut down. This isn't a particularly strong argument, though. Maybe a stronger one (depending on how you look at it) is that by enforcing this we'll catch cases in which they'll linger.

**Comment by danhhz** [comment]
@tbg curious for your thoughts on the two snapshot related bullets I just added. Basically, 1) at a high level, how should a learner snapshot be different from a raft snapshot and 2) at a low level, what should be responsible for error-ing when trying to upreplicate some range on to a store that still has an old, intersecting replica lying around. Context for (2) is the TestReplicateAfterRemoveAndSplit and TestStoreRangeMergeReadoptedBothFollowers tests

**Comment by tbg** [comment]
> (Store).Capacity and updateReplicationGauges update a set of counts. What downstream uses these counts? What if they have different preferences for whether it includes learners?

I think the allocator uses the Capacity and balances on it (plus goes into panic mode if a node is very full, I believe 95%). The gauges are used for metrics only, so the question is what's desired there.

> How should learner snapshots behave? There are a bunch of places preemptive snapshots get special cased (they can be rejected etc), are learner snaps the same?

They should behave like Raft snapshots in that regard, which unfortunately still means that they can get rejected https://github.com/cockroachdb/cockroach/blob/f8ca8b76b7a57f820fe41463493ffc161c08cacf/pkg/storage/store_snapshot.go#L552-L554 The whole replicaGC story is pretty bad. We have a way to make it much better though: https://github.com/cockroachdb/cockroach/pull/36654 should allow us to eagerly clean out overlapping replicas so that we don't do this awkward thing we do right now, which is just not accept the clearly better snapshot until the gcqueue has checked with the meta ranges. Something worth trying out in the short term could be just running a synchronous gcqueue run for the overlapping range before going ahead. We were historically scared of doing things like that (because it touches meta2), but if you're trying to send a snapshot, you've already touched meta2 and you're on a queue, and also the snapshot is very likely reasonable. I think that change could actually benefit import/restore/scatter quite a bit, too.

At the end of all this, though, it's still possible to see a snapshot legitimately rejected. This would happen if the range changed out from under us and the snapshot we were sending was legitimately stale. But that case we can just treat as a replicate queue processing error and throw our hands up. With today's code, errors will unfortunately be frequent, so we'll have to be prepared to retry at least a few times on "intersects existing range" errors. BTW, these errors are currently string matched throughout, which is pretty bad, so if you can change that I'd plause that.

Oh, and that's the remaining bullet point you had above (which I only looked at now).
