### ISSUE TITLE
opt: use partition values to use/constrain indexes

### ISSUE THREAD

**Issue by ridwanmsharif** [cockroachdb/cockroach#38031]
As @andy-kimball suggested in https://github.com/cockroachdb/cockroach/issues/37312#issuecomment-494671824, when `PARTITION BY LIST (col)` is used, the partition values are enumerated as part of `PARTITION ... VALUES IN` clauses. We could use those to build the index skip scan described in https://github.com/cockroachdb/cockroach/issues/37312#issuecomment-489354659. That way, even if the user does not define a check constraint, they'd still get the same benefits of https://github.com/cockroachdb/cockroach/issues/37312 where previously un-usable indexes are used and constrained based on check constraints and filters. This wouldn't need histograms to make it work (i.e. could be done today).

**Comment by awoods187** [comment]
@jordanlewis could you expand here on your reason why you thought this might not meet all of our users needs? I believe it was about the cost of re-partitioning

**Comment by jordanlewis** [comment]
Yeah, the problem here is that nothing verifies that all rows are part of the given partitions (not to mention that this approach wouldn't work for `BY RANGE` partitions at all) - in other words, there's always a default "catch all" partition available that will foil the optimizer's ability to create tight spans for all of the partitions.

**Comment by andy-kimball** [comment]
But then it's just a question of performance. Most of the time, all rows are part of the given partitions, in which case we get a huge speedup. If there are rows not part of the given partitions, then we end up scanning them. But that should be no worse than doing what we do today, which is a table scan.

See Radu's [comment here](https://github.com/cockroachdb/cockroach/issues/37312#issuecomment-489354659). Histograms have the same problem - they may not specify all possible values, or even specify extra values. That's OK, given the way Radu's spans work. My observation is simply that we can apply his method to `BY LIST` partitions. I also agree that it'd be good to have some kind of `BY LIST` partition keyword that forbids use of a "catch all" partition. We might generate an automatic check constraint to enforce that (which would then automatically be used by the optimizer).

**Comment by jordanlewis** [comment]
> But then it's just a question of performance. Most of the time, all rows are part of the given partitions, in which case we get a huge speedup. If there are rows not part of the given partitions, then we end up scanning them. But that should be no worse than doing what we do today, which is a table scan.

That's very true. I like this point. In the normal case, where nobody puts non-partitioned data, the penalty is merely a few extra (empty) parallel scans.

> We might generate an automatic check constraint to enforce that (which would then automatically be used by the optimizer

We were talking about this as well. The downside is that repartitioning that removes partitions becomes more annoying, because you have to carry out some kind of schema change esque re-check scan. The scan itself can be cheap, because it boils down to a `limit 1` scan on each of the partitions you're removing, but it seems like it would be easy to do incorrect bookkeeping behind the scenes, since check constraints can be as complex as our expression language. And, you'd have to make sure to perform this check atomically enough that there's never a point in time where the schema doesn't have a check constraint at all, since that would kill performance on queries that expected the check constraint to be there.

All in all I think we do want to make partitions without default buckets either behave like check constraints or add explicit ones, but I wanted to call out the engineering difficulties I perceive here.
