### ISSUE TITLE
java: More threads --> Worse throughput? golang: similar symptoms? Sequential IDs.

### ISSUE THREAD

**Issue by Samusername** [cockroachdb/cockroach#38160]
Performance of inserts.
Language: java, jdbc

With e.g. four threads, performance is ok: more than 20 000 rows per second.
When amount of threads is increased, e.g. to more than 10, 
performance is smaller: e.g. slightly more than 10 000 rows pers second.
One data generator.

Has someone noticed similar symptoms?

Some set up information:

Version: v19.1.1
CockroachDB nodes: 3 or more, e.g. 9. 
Replication factor of user data, default: 3.

Table:
ID     (PK), 
JSONB  (Small json data entries),  
(and e.g. two small other columns).

Following is used in connection string: reWriteBatchedInserts=true
batch inserts. 
batch size: e.g. 4096 or 8192.

I think same test data generator has worked ok in some other tests (with some other DBMSs).
Of course there may still be some problems there also. 
(I cannot send source codes of that version, but other generator would need to be written and shared.)

With an other data generator, which was written in golang, such decrease in performance was not noticed. It worked ok with more than 20 threads. (Difference to java: golang generator used random IDs.)

One k8s node for each cockroachdb node.
8 CPUs per node.
Enough RAM per node. E.g. 10 GB.

Q: Could there be some problem with performance with JDBC, with CockroachDB?
Or is problem somewhere else.

**Comment by Samusername** [comment]
Can multi row batch inserts make performance better. Currently only normal batch inserts are in use.
Multi row: [link](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html).

**Comment by Samusername** [comment]
Actually, I think following happens. 
Also with golang.

golang: multi row inserts (batch). Batch size, e.g. 4096. 
( Tested also with smaller multi row size, but then performance got worse. When using sequential IDs.) 

golang: One multi row insert per db.Exec.

golang, earlier: random IDs were in use. 
Performance was better with random IDs in comparison to sequential IDs. Threads: 20.

golang: use sequential IDs. 
Threads 4 --> Performance improves / stays better than when using 20 threads.

Similar seems to happen with java: 
Performance stays better when 4 threads are used instead of more than 10 threads. Sequential IDs in use.

This is a little bit complex, so I may have done / written up something incorrectly.

**Comment by Samusername** [comment]
> use sequential IDs.
> Threads 4 --> Performance improves / stays better than when using 20 or 12 threads.

Does this happen because of some design topic in CockroachDB? / How CockroachDB is designed.

**Comment by ricardocrdb** [comment]
Hey @Samusername 

I hope we can clarify these differences you are seeing in performing your tests. A few things to note come to mind. One, when sequential IDs are used, this may impact performance due to capping the throughput on a single node. This is due to the keys being sorted on ranges as the data is entered, described [here](https://www.cockroachlabs.com/docs/v19.1/architecture/sql-layer.html#encoding).

Secondly, in our SQL performance best practices, we recommend using `UUID`s, in order to help distribute the ranges to multiple nodes, as described [here](https://www.cockroachlabs.com/docs/v19.1/performance-best-practices-overview.html#use-uuid-to-generate-unique-ids). This will help the performance by spreading the workload across multiple nodes so that the processing can be done in parallel.

One other thing to keep in mind is that adding more concurrent writers/threads will not necessarily always increase performance. As described in this [article](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing), having more connections does not necessarily help the latency of their example site. The same logic can be applied with concurrent writers and throughput. Due to different configurations and hardware settings, there is no magic number, and only through various experimentations can a happy medium be found where you can get optimal performance on your current setup. 

One way of determining this is to try testing with the same number of concurrent writers while changing the write/block sizes. Once you find peak performance there, try increasing the number of concurrent writers while maintaining that ideal block size. At some point,  you will see a peak in performance and the performance starts to take a dip as more concurrent writers are added. At that point, the peak would be your optimal performance.

I hope this clarified any questions or concerns you had. Let me know if there are any other questions.

Cheers,
Ricardo

**Comment by Samusername** [comment]
Thank you for comments!

Topic: Sequential IDs

If we **split** one huge DB table to smaller DB tables, e.g. to 4-6 DB tables, then total performance is excellent. --> Much better than when using random IDs.

4-6 threads per data generator. One data generator per DB table.

So, the performance is worse, if there is **one huge** DB table and e.g. 12 or 20 threads.
So, best total performance could be achieved by using smaller DB tables, and sequential IDs. 
(This is my understanding correctly from tests.)

**Comment by ricardocrdb** [comment]
Hello @Samusername 

This is most likely due to a new range being created when a new table is created. As newer tables are created, newer ranges are added to the cluster, and the likelihood of using the same ranges compared to using one massive table is much smaller, so you are able to utilize more nodes processing different ranges.

Let me know if you have any other questions, or if we can go ahead and close this issue.

Cheers,
Ricardo

**Comment by Samusername** [comment]
That feels like a possible reason / theory what could happen. (You are the experts.)
Thank you!
This ticket can be closed.

**Comment by ricardocrdb** [comment]
Hey @Samusername 

Thanks for the confirmation, I will go ahead and close this issue.

Cheers,
Ricardo
