### ISSUE TITLE
stats: better integration with backup / restore

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#38264]
Currently restoring a backup does not restore any table stats. Instead, it triggers a refresh of the stats. This could take a long time during which query performance might be degraded (and it would probably come at a particularly bad time given that we had to restore a backup).

Ideally the stats would be backed up and restored along with the tables.

**Comment by RaduBerinde** [comment]
CC @rytaft and @awoods187

**Comment by awoods187** [comment]
I think this is a great idea--thought @dt and @rolandcrosby

**Comment by dt** [comment]
that should be pretty straight forward I'd think. I'm assuming there's some proto encoded representation of stats we could just retrieve and stick in the backup desc along side the table desc?

for incremental backups, I'm guessing we'd just grab the whole stats, and then in restore we just use the stats from the last backup?

**Comment by dt** [comment]
Point-in-time restore isn't as obvious to me... we could include revision history of the stats when we ask for revision history of the table? or we could just restore the latest stats before the requested time and then trigger a refresh?

**Comment by RaduBerinde** [comment]
They're currently stored in a system table. We do have code to convert to/from a JSON representation. No reason we can't add a proto as well if necessary.

For point in time, I think it's definitely reasonable to return the latest stats and trigger a refresh. In principle we could retrieve old stats from the system table (but it might have a different zone config than the table itself).

**Comment by rolandcrosby** [comment]
For simplicity and to avoid edge cases where GC times are different on the system and data tables, I like the approach of just grabbing the latest stats and storing them alongside the backup descriptor. I imagine this would work for incremental as well as full backups.

Backup AOST could also run into the issue of stats not being available due to GC differences. I think it'd make sense to try to grab the stats AOST, and if that fails, just don't include stats in the backup (and, in RESTORE, always fall back to generating new stats before the RESTORE job completes if there aren't any stats in the backup).

**Comment by rolandcrosby** [comment]
Closed by #39644.

**Comment by awoods187** [comment]
awesome!
