### ISSUE TITLE
Create index failed:could not find valid split key

### ISSUE THREAD

**Issue by luzongyi** [cockroachdb/cockroach#38370]
The create index sql like this:create index idx_countyid_isdelete on tb_name(county_id,is_delete);

When I tried to create an index.It failed.And it have two situations:

1:pq: job-insert: split failed while applying backpressure: could not find valid split key
2:pq: duplicate: index "idx_countyid_isdelete" in the middle of being added, not yet public

The situation 1.I don't even know what's that mean.

The situation 2.I used 'show indexes' to look what indexes it have.But the idx_countyid_isdelete did not exists.So I still don't know why.

**Comment by luzongyi** [comment]
Is this issues confirm ? 
Look at this link: https://github.com/cockroachdb/cockroach/issues/37772

**Comment by ricardocrdb** [comment]
Hey @luzongyi 

PR [37781#}(https://github.com/cockroachdb/cockroach/pull/37781) is the Pull Request involving the backpressure issue which has been merged at this point, as you can see at the link. There are also a couple of workarounds, discussed in [#25770](https://github.com/cockroachdb/cockroach/issues/25770#issuecomment-390730820) and [#35842](https://github.com/cockroachdb/cockroach/issues/35842#issuecomment-479148691).

In regards to the index issue, let me know how it appears once you have updated to a later version, or performed one of the workarounds for the split range issue.

Cheers,
Ricardo

**Comment by luzongyi** [comment]
Hey, @ricardocrdb 

Thanks for your reply.

My mistake.The actual situation is worse than what I said before.Except it cann't create index.It also cann't create table ,cann't create database.And cann't set the cluster config setting like this:

SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0;

This situation has been going on for two days.And my version is not v19. It's v2.1.0.In this moment.How can I alleviate this situation?

**Comment by luzongyi** [comment]
About this issues.It looks like not easy to fix it.After discussing with my team.We would solve it on another way.

Because in the whole project, the role of this cluster is only for query.That means it can be stop a few days.So dump the all data and rebuild a new cluster.Then import the data back.It maybe work.

The dump job has been completed.The sql file is 240GB.And it's importing now.

And the version changed from v2.1.0 to v2.1.6

**Comment by ricardocrdb** [comment]
Hey @luzongyi 

At this point, it sounds like the cluster has run into the event where the backpressure issue occurred on a system range, and the cluster is basically unable to recover. A `dump...import` of the database(s) would be needed in order to get the cluster back up and running, at which point the workarounds can be used. If this was done, I would suggest getting the latest 2.1.x copy, which backported the fix for this issue, as per [#37782](https://github.com/cockroachdb/cockroach/pull/37782).

Sounds like you already have a dump of the data, and are working on re-creating the cluster, so at this point upgrading to the latest 2.1.x version should be done in order to help alleviate these issues from occurring in the future.

Let me know how it works out, and if there are any other questions.

Cheers,
Ricardo

**Comment by luzongyi** [comment]
Hey @ricardocrdb 

Now the recovery job is on a single node for test.If it works out.I will re-create a new cluster to do it.And I also will use the latest 2.1.x version.When it done.I will let you know.

Thanks.

**Comment by luzongyi** [comment]
Hey @ricardocrdb 

Thanks for your help yesterday.

About the thing:create index.There is a good news.The dump data has not been completely imported into the new cluster yet.Then the old cluster is back to healthy again.Now I can create or drop database,create or drop table and create or drop index.

I think that's weird.I will observe it a few days.If it still good.I will close this issue on monday.

**Comment by luzongyi** [comment]
Now except can't create index on the table of 400 million rows .Every thing else is good.
