### ISSUE TITLE
exec: finalize vectorize setting name and behavior

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#38620]
Currently, the `experimental_vectorize` flag has 3 values: off, on and always. Off means never run with vectorize, and is the default. On means run everything that vectorized supports with vectorized. Always means run everything with vectorized, even the things that vectorized doesn't support.

This issue tracks changing this setting to what it will look like in 19.2.

We need to change the name of the setting to remove the `experimental_` prefix, since anything that's going to be enabled by default shouldn't have `experimental` in its name.
Then, we need to add a new setting (maybe called on? auto? streaming?) that encodes the behavior of planning vectorized only if all operators are streaming operators.

**Comment by yuzefovich** [comment]
There is a lot flakiness with "streaming" on by default on "fakedist" configurations. (Note that I override "vectorize" to off on all fakedist configs.) For example, when I run `make testlogic FILES=aggregate` three times this is what I get:
```
            --- FAIL: TestLogic/fakedist-metadata/aggregate/other (0.02s)
                logic.go:2379: 
                    
                    testdata/logic_test/aggregate:173: SELECT json_agg(1) FROM kv
                    expected success, but found
                    (XXUUU) unordered spans (/Table/53/1/{5-8} /Table/53/1/{3-5})
                    kv_batch_fetcher.go:180: in makeKVBatchFetcherWithSendFunc()
```
```
        --- PASS: TestLogic/fakedist-metadata/aggregate (1.52s)
            --- PASS: TestLogic/fakedist-metadata/aggregate/other (1.14s)
            --- PASS: TestLogic/fakedist-metadata/aggregate/string_agg (0.19s)
```
```
           --- FAIL: TestLogic/fakedist-metadata/aggregate/other (0.05s)
                logic.go:2363: 
                     
                    testdata/logic_test/aggregate:315: SELECT count(*) FROM kv GROUP BY 1+2
                    expected:
                        6
                        
                    but found (query options: "") :
                        9                  
```
I've seen similar failures on "fakedist" and "fakedist-disk".

My only guess is that there are other "internal" queries that need to be executed in order to run the queries from the logic test files, and those "internal" ones are performed with default vectorize "streaming" setting and are probably accessing some systems tables, and that is broken somehow. Any ideas about that?

There is a bunch of other tests failing at the moment as well, but I have nothing to share about those (maybe it is the same underlying problem).
