### ISSUE TITLE
exec: support projections of LIKE and NOT LIKE

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#38657]
We currently support selections of LIKE and NOT LIKE, but not projections. This means you can't do something like `SELECT x LIKE 'foo%' FROM t`.

This will require extending the like ops generator to produce a projection as well as a selection operator, and teaching col_exec_setup to plan these correctly.

As part of this work, I think we should consider reunifying LIKE and NOT LIKE with the rest of the comparison operators, so that you can get a LIKE operation by calling `GetSelectionConstOperator` or `GetProjectionRConstOperator`, rather than special constructors just for LIKE.

This is required for TPCH query 14, which is also blocked by lack of CASE support for the moment.

@solongordon is there any obstacle that you can see to trying that unification out?

**Comment by solongordon** [comment]
The unification is worth a look though I'm wondering what the goal is you have in mind. If it's to reduce the number of special cases in `column_exec_setup`, it should be pretty easy to add a new function which delegates to either `GetSelectionConstOperator` or `GetLikeOperator` depending on the inputs. I'm wary of cramming all that logic into one function during templating because the two are pretty different. `GetLikeOperator` chooses between several different operators depending on the like pattern.

**Comment by solongordon** [comment]
Also while we're here we should resolve this TODO: https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/sql/exec/like_ops.go#L43-L45
