### ISSUE TITLE
Listening URL file is written after process is backgrounded

### ISSUE THREAD

**Issue by akshayjshah** [cockroachdb/cockroach#38758]
**Describe the problem**
When running CockroachDB with the `--background` and `--listening-url-file` flags, the listening URL file isn't written until *after* control is returned to the shell. This makes it awkward to actually read the URL from the file, which makes `--background` less useful (especially in tests, where I'm starting databases on ephemeral ports).

It's easy to work around this by retrying until the file appears, but that's a bit distasteful.

**To Reproduce**
This bash script fails reliably on my machine:
```bash
#!/usr/bin/env bash
set -euo pipefail

rm -f connfile
cockroach start --background --insecure --listening-url-file connfile >/dev/null 1>&2
cat connfile > /dev/null
```

**Expected behavior**
I expected the listening URL file to be written out before control is returned to the shell. If that's not possible, it'd be nice to clarify the `cockroach start --help` output.

**Additional data / screenshots**
None.

**Environment:**
 - CockroachDB version: 19.1.1
```sh
$ cockroach version
Build Tag:    v19.1.1
Build Time:   2019/05/15 20:21:46
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin14)
Go Version:   go1.11.6
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  c8bda1de440cfe90cf23a433119d77795cfa0047
Build Type:   release
```
 - Server OS: MacOS
 - Client app: `cockroach` CLI

**Additional context**
This doesn't have any production impact, but it forces me to choose between flaky tests or an ugly workaround.

**Comment by nvanbenschoten** [comment]
@akshayjshah thanks for the report! This does seem to be a usability hurdle.

@knz I tracked this down to the following comment, which makes this behavior look intentional:

https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/cli/start.go#L705-L718

Your comment on https://github.com/cockroachdb/cockroach/commit/f7c175e4b0b594e33c55fc96e2fa28a56f311c00 also discusses the difference between how `--pid-file` and `--listening-url-file` are treated. There, you state that:
> In contrast, the listening URL is still only written after the server
has done bootstrapping and is able to serve SQL sessions. This remains
the reliable way to wait until a server is ready to accept clients.

Do you mind taking a look at this issue? It may be the case that we simply need to update the help text for these two flags to make it clearer what can be expected from them when combined with the `--background` flag

**Comment by akshayjshah** [comment]
Thanks for the digging, Nathan!

If `--background` returns control to the shell before the server is ready to accept clients, what's its intended use case? The docs say "control is not returned to the shell until the server is ready to accept requests," which made it sound (to me) like the server is fully bootstrapped and ready to serve queries.

**Comment by knz** [comment]
@akshayjshah two things

1) regarding your particular use case. It's 100% legitimate and the correct way forward for you is this:

```sh
rm -f connfile
mkfifo connfile
cockroach start --background --insecure --listening-url-file connfile >/dev/null 1>&2
cat connfile > /dev/null
```

Notice the `mkfifo`. this is guaranteed to work and do what you want - the `cat` will only produce the URL when the server is ready to accept requests.

2) FYI the behavior is indeed intentional. Your confusion is perhaps about your understanding of what "accepting requests" mean. We need to clarify this in docs and the command line help:

- a newly created node that is not yet initialized can accept `init` and `--join` *requests* from other nodes, but not accept SQL clients
- a node only accepts SQL clients when it's fully initialized.

So the behavior is intentional as follows:
- `--background` puts the proces in the background when it's able to accept requests from other nodes
- `--listening-url-file` writes the URL when it's able to accept SQL client connections
- there can be an arbitrary amount of time between the two things, for example if `init` or `--join` is delayed.

It would be incorrect/inconvenient/unusable to produce the SQL URL before the node is initialized, because then SQL clients would try to connect and get an error, and not know what to do about it.

**Comment by tbg** [comment]
I filed a (sparse) issue about this a while ago - https://github.com/cockroachdb/cockroach/issues/35070

I'm not sure that the current behavior is 100% intentional as is. I think we never quite sat down and figured out what `--background` is supposed to be there for nowadays. There's an argument that it should return when the server is ready for an init if it needs bootstrap, but that generally it should wait until the server is ready to serve SQL requests.

**Comment by knz** [comment]
@tbg excuse me, I actually sat down and spent quite some time figuring out the alternatives, to settle on the current one. 

I was not aware of the linked issue #35070, but I think the text you wrote in there does not weigh well against the rationale detailed in the 2nd commit from #29107.

> There's an argument that it should return when the server is ready for an init if it needs bootstrap, but that generally it should wait until the server is ready to serve SQL requests.

These two requirements are contradictory.

**Comment by tbg** [comment]
They are not if you assume that bootstrapping a cluster and restarting nodes in an existing cluster are different operations, which could be justified. We could even have `--background` only return when the node serves SQL connections, which means that it'll hang if it needs an init (until it's gotten the init).

At the end of the day, the question is what we want to provide to the end user via this flag. I'm relatively sure it was "node serves SQL" originally, and has then morphed into something unspecified as we changed the bootstrap sequence.

**Comment by knz** [comment]
> We could even have --background only return when the node serves SQL connections, which means that it'll hang if it needs an init (until it's gotten the init).

Yes it would be nice if we had started with that originally, but it would break existing scripts that do something like this:

```
cockroach start --port=123 --background &
cockroach start --port=124 --background &
cockroach start --port=125 --background &
cockroach init --port=123
```

Also it might make the integration story with service managers more difficult: deployments won't be able to assume any more that `--background` will yield back to a service/job manager "fast" any more -- they'd need to think about whether it's initialized already or not.

I think it would be good here if @bdarnell could share some opinion too.

**Comment by tbg** [comment]
I wasn't aware of https://github.com/cockroachdb/cockroach/pull/29107, thanks for the link.

@bdarnell had some sort of opinion in https://github.com/cockroachdb/cockroach/issues/34897#issuecomment-465222698, but not much detail.

I agree that ultimately what matters is give users the best bang for their buck out of the flag, which depends on how they use it (or want to use it).

The current behavior has surprised folks regularly, which provides some indication that ergonomics aren't ideal. OTOH we wouldn't hear from those who are using the current semantics and are happy with them.

**Comment by bdarnell** [comment]
> Also it might make the integration story with service managers more difficult

Service managers should not be running with `--background`. This flag is for ad-hoc at-the-terminal use cases and scripted tests, so we should optimize for those cases and not production use with a process manager.

The tricky part is the two meanings of "ready": there's ready to accept an `init` command and ready to accept sql connections. This gets more important when a follow-up to #28495 makes `init` mandatory. If `--background` doesn't return until we're ready to accept sql connections, it's hard to script the `init` dance correctly.

Fortunately, there's been another relevant change. Since #21682, we can accept SQL connections even before `init` (they'll just be blocked in a queue until the `init` has been run). I think it makes sense to write the listening file at the same time.

**Comment by akshayjshah** [comment]
> Since #21682, we can accept SQL connections even before init (they'll just be blocked in a queue until the init has been run). I think it makes sense to write the listening file at the same time.

This sounds great.

**Comment by akshayjshah** [comment]
@knz @tbg Thanks again for fixing this, guys - I just updated our dev and CI environments to 19.2.1, and this lets us remove some heavily-commented code from our Makefile. Appreciate it! ❤️
