### ISSUE TITLE
sql: incorrect handling of negatives

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#38780]
`select -1/1` incorrectly returns `1`. It is believed to have been introduced by f4658b4. It is present in 2.1 and 19.1.

**Comment by jordanlewis** [comment]
I think the linked commit did indeed introduce the problem. The commit added a new `Negative` field to `NumVal`, which is commented as:

```
	// Negative is the sign bit to add to any interpretation of the
	// Value or OrigString fields.
```

This comment isn't being obeyed everywhere, which is the root cause of this problem. A resolution to this needs to audit all uses of `NumVal.Value` and ensure that the `Negative` field is getting correctly propagated to the downstream uses of the `Value`.

As an example of bad behavior, check out `constant.go` (I think this is the main file that has the problem that causes this issue):

```
	case *BinaryExpr:
		switch l := t.Left.(type) {
		case *NumVal:
			if r, ok := t.Right.(*NumVal); ok {
				if token, ok := binaryOpToToken[t.Operator]; ok {
					return &NumVal{Value: constant.BinaryOp(l.Value, token, r.Value)}
				}
				if token, ok := binaryOpToTokenIntOnly[t.Operator]; ok {
					if lInt, ok := l.asConstantInt(); ok {
						if rInt, ok := r.asConstantInt(); ok {
							return &NumVal{Value: constant.BinaryOp(lInt, token, rInt)}
						}
					}
				}
```

Note that we don't modify `l.Value` or `r.Value` with the value of `Negative` before passing them into `constant.BinaryOp`.

@knz do you have any insight into the proper thing to do here? I'm thinking that we might want to make `NumVal.Value` only accessible by a method, and have that method automatically run `UnaryOp(MINUS, Value)` and return the result, the way we do with `asConstantInt`?

**Comment by mjibson** [comment]
If we misused something in multiple places we should make that impossible or difficult to happen in the future. I concur with having a method and unexporting the members.

**Comment by mjibson** [comment]
Another:

`select 1 - 2.` => `1`

**Comment by mjibson** [comment]
Whatever PR fixes this should also remove the ignoreSQL stuff from #38784.

**Comment by knz** [comment]
> do you have any insight into the proper thing to do here? I'm thinking that we might want to make NumVal.Value only accessible by a method, and have that method automatically run UnaryOp(MINUS, Value) and return the result, the way we do with asConstantInt?

that's not the right way to do this IMHO, because if you do this you will get the incorrect result for `sqrt((1*-0)::float)`. (Should be `-0`, but with your proposal the value `-0` would evaporate inside the constant evaluation)

The right way to do this is to propagate the sign to the result using the regular algebraic rules, to "lift" the negative sign in the result NumVal:

```
 a + b   -> a + b
 a + -b  -> a - b
-a + b   -> b - a
-a + -b  -> -(a + b)

 a - b   -> a - b
 a - -b  -> a + b
-a - b   -> -(a + b)
-a - -b  -> -(a - b)

 a * b   -> a * b
 a * -b  -> -(a * b)
-a * b   -> -(a * b)
-a * -b  -> a * b

 a / b   -> a / b
 a / -b  -> -(a / b)
-a / b   -> -(a / b)
-a / -b  -> a / b

 -a      -> -a
- -a     -> a

(not sure about the following four)
 a % b   -> a % b
 a % -b  -> -(a % b)
-a % b   -> -(a % b)
-a % -b  -> a % b
```

**Comment by rafiss** [comment]
@knz I'm not sure if I followed your initial example, but in postgres the behavior is:

```
postgres> select sqrt((1*-0)::float);
+--------+
| sqrt   |
|--------|
| 0.0    |
+--------+
```

To me, it seems like it is correct to always evaluate a the `-` unary operator with a `UnaryOp` right away when evaluating an expression. This would also agree with the [order of precedence defined by Postgres](https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE). (As an aside, it seems like that order of precedence is different than what mathematicians use traditionally -- in the math field I think normally `-3 ^ 2` would evaluate as `-1 * 3 ^ 2` -> `-1 * 9` -> `-9`. But in Postgres, this evaluates to `9`.)

**Comment by mjibson** [comment]
We've been aware of the `-` precedence difference for a while: https://www.cockroachlabs.com/docs/v19.1/porting-postgres.html#precedence-of-unary

I think this happens because postgres implements operators on types, and all type operators are at the same level of precedence (about the middle), and as a result many operators have a preference that differs from what we expect.

**Comment by rafiss** [comment]
Thanks for that link -- it seems to describe the `~` (bitwise NOT) operator, and not the `-` (arithmetic negation) operator. But I will definitely make sure that both `~` and `-` are handled as they should be, and will implement all the precedence rules according to [our own docs](https://www.cockroachlabs.com/docs/v19.1/porting-postgres.html#precedence-of-unary), and to [Postgres precedence rules](https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE) where our docs don't specify any difference.
