### ISSUE TITLE
how can i know row locate in which node?

### ISSUE THREAD

**Issue by leafji** [cockroachdb/cockroach#38861]
Hello @jordanlewis :

I would like to ask some question about partition feature with zone config， which is how can i know that which node some specific data locate in.

For example:

create table t1(a int primary key) ;

ALTER TABLE t1 PARTITION BY LIST (a) (
    PARTITION p1 VALUES IN (3),
    PARTITION p2 VALUES IN (6),
    PARTITION p3 VALUES IN (9)
  );

ALTER PARTITION p1 OF TABLE t1
    CONFIGURE ZONE USING constraints='[+region=sp0]';

ALTER PARTITION p2 OF TABLE t1
    CONFIGURE ZONE USING constraints='[+region=sp1]';

ALTER PARTITION p3 OF TABLE t1
    CONFIGURE ZONE USING constraints='[+region=sp2]';

so, if how can i get the information about which row store in which node ?
like below value 3 locate in sp0,
values6 locate in sp1
values9 locate in sp2

**Comment by mattcrdb** [comment]
Hi @leafji,

Currently, CockroachDB does not support such a command to determine which nodes a particular row lives on.

However, I went ahead and replicated your example in a geo partitioned deployment and was able to determine the information you are looking for using the following:

`SHOW EXPERIMENTAL_RANGES FROM TABLE t1;`
This will return us the information about the ranges that make up t1's table data.

Since our partition is related to our primary key we can do this:
`SELECT * FROM [SHOW EXPERIMENTAL_RANGES FROM TABLE t1] WHERE "start_key" = '/3'`

Note that '/3' is the key used in partition p1, you can change this to 6 or 9 to see the other results. 

Assuming your region "sp0" contains nodes 1,2 and 3.

The result will look like this: 
```sql
  start_key | end_key | range_id | replicas | lease_holder  
+-----------+---------+----------+----------+--------------+
  /3        | /4      |       31 | {1,2,3}  |            2  
```
Note that the `replicas` column result is referring to the nodes where that data is stored.

Let me know if you have any other questions!

Thanks,
Matt

**Comment by mattcrdb** [comment]
Hey @leafji ,

Just wanted to check in to see if this information was useful.

Let us know.

Thanks,
Matt

**Comment by leafji** [comment]
Hey @mattcrdb ,

Thanks your suggestion, I will try my best to seach another direct methods, and will close this issue then.

Thanks.
