### ISSUE TITLE
exec: probably a bug with ordinality

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38995]
```
root@127.0.0.1:54010/defaultdb> CREATE TABLE t (a INT PRIMARY KEY);
CREATE TABLE

Time: 2.685ms

root@127.0.0.1:54010/defaultdb> INSERT INTO t VALUES (1), (2);
INSERT 2

Time: 2.99ms

root@127.0.0.1:54010/defaultdb> SELECT a, ordinality*2 FROM t WITH ORDINALITY AS ord;
  a | ?column?  
+---+----------+
  1 |        2  
  2 |        4  
(2 rows)

Time: 732µs

root@127.0.0.1:54010/defaultdb> SET experimental_vectorize=on;
SET

Time: 269µs

root@127.0.0.1:54010/defaultdb> SELECT a, ordinality*2 FROM t WITH ORDINALITY AS ord;
E190719 16:39:41.591449 882 sql/sqltelemetry/report.go:56  [n1,client=127.0.0.1:54012,user=root] encountered internal error:
assertion failure
```
Also, not sure if it's related, by I expected that the column name in the output would be "ord" and not "?column?".

**Comment by rafiss** [comment]
I believe we already don't support renaming with the `WITH ORDINALITY AS ord` syntax. Also, I think even if we did it wouldn't get that name because of the multiplication.

I'll look into the failure.

**Comment by rafiss** [comment]
From a cursory investigation, it seems like the issue is with the interactions between ordinality and projection. Both of these operators add a column to the result batch, but the projection operator is not aware that the ordinality operator has added the column. I'm looking for more details, but just wanted to note that down before the weekend starts.

**Comment by yuzefovich** [comment]
I looked into this a bit more, and I believe the underlying problem is #39042.

**Comment by yuzefovich** [comment]
Never mind, my hypothesis was wrong, disregard last comment.
