### ISSUE TITLE
why backup function has not backup sequence, it make restore looks like funny

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#39345]

**Comment by mattcrdb** [comment]
Hey @yangxuanjia ,

Could you provide some more information?

Thanks,
Matt

**Comment by yangxuanjia** [comment]
the backup enterprise function can backup table or database,  but has not backup sequence, like create table t1(id int primary key default nextval("t1_id_seq"), name string);,  restore must set miss_sequence then the table can restore,  why not backup sequence when backup database?

**Comment by mattcrdb** [comment]
Thank you for bringing this up!

I was able to reproduce this issue.

I will look into it and reply to you once I know what's going on.

**Comment by mattcrdb** [comment]
If the sequence is in that database that you are backing up, then restoring the database will succeed with the sequence.

If you are backing up a table that is dependant on a sequence, you must restore the table and the sequence that it is dependant on. This is because the sequence is a dependency and the table is its own entity when doing a backup table on its own.

the syntax would be `RESTORE table_name, seq_name FROM ...`

Let me know if you have further questions.

Thanks,
Matt

**Comment by yangxuanjia** [comment]
the backup document say "It is not possible to create an incremental backup if one or more tables were created, dropped, or truncated after the full backup. In this case, you must create a new full backup.",  but i try to do these ops, it's no problem.  Are these problems fixed?

**Comment by mattcrdb** [comment]
Can you provide me with steps to reproduce?

I will investigate, thank you.
