### ISSUE TITLE
pgwire cannot bind to IPV4 "all-addresses"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3962]
Without any arguments, pgwire listens only on [::]:15432 (ipv6 all-addresses). 

With `--pgaddr 0.0.0.0:15432` (ipv4 all-ddresses), the configuration is ignored and it starts listening on [::]:15432 as well.

Only with an explicit ipv4 address (eg. `--pgaddr x.y.z.w:15432`) does the desired behavior appear.

I think this is rather new as I did not have this problem last week.

There are two bugs in here:

1. `--pgaddr 0.0.0.0:15432` should really listen on ipv4
2. by default (no argument) pgwire should probably listen on both ipv4 and ipv6 or the current behavior should be clearly outlined in the doc.

**Comment by tamird** [comment]
cc @mberhault

**Comment by knz** [comment]
#3757

**Comment by knz** [comment]
(Via @tamird) might be related to #3757

**Comment by knz** [comment]
Ok after some more investigation this issue is not reallyn related to the argument `--pgaddr` but more to the general behavior of `net.Listen` when provided these values as input. What is the general way in Go to specify the "any" binding for ipv4?

**Comment by knz** [comment]
Found while investigating #4036

**Comment by mjibson** [comment]
https://groups.google.com/forum/#!msg/golang-nuts/F5HE7Eqb6iM/q_um2VqT5vAJ has some good info on this.

**Comment by mjibson** [comment]
@knz can you replicate this on a Mac? I dived in a bit and it seems like Go thinks it's a ipv4 address. Linux may be doing some auto ipv6 magic.

**Comment by bdarnell** [comment]
I'm not sure exactly how the system calls are exposed via go, but I've run into this in the [past](https://github.com/tornadoweb/tornado/blob/b22da52c781d4d03e57f3674afa0d1473f06a33b/tornado/netutil.py#L175). In short, linux likes to bind to both ipv4 and ipv6 together whenever it can, while BSD and OSX require them to be bound separately. To handle things in a sane and cross-platform way you have to pass extra socket options on linux to make it act more like BSD. This seems like something Go should handle for us instead of something we do at our level.

**Comment by knz** [comment]
The issue was found and was affecting a Linux system. 
The issue has went away after upgrading to 4fc0779c204eb893bb733b87ee1b59edc3917f55.
Closing this issue for now, if found again on BSD/OSX another issue could be opened too.

**Comment by tamird** [comment]
This was (unintentionally) fixes in #4161.
