### ISSUE TITLE
split failed while applying backpressure to ...: could not find valid split key

### ISSUE THREAD

**Issue by dacrypt** [cockroachdb/cockroach#39665]
This happens after several update operations to the record. After a while, it fails and trying to update the record in any way, returns the following error:

```update profiles set picture='' where id = '3d33c7f0-6794-4662-800a-5b5961647d33';```

```pq: split failed while applying backpressure to [txn: 17da559f], Put [/Table/79/1/"=3\xc7\xf0g\x94Fb\x80\n[Yad}3"/0,/Min), EndTransaction(commit:true) [/Table/79/1/"=3\xc7\xf0g\x94Fb\x80\n[Yad}3"/0] on range r83:/Table/79/1/"{=3\xc7\xf0g\x94Fb\x80\n[Yad}3"-h\xe6v.4tD\xb7\xb2z\xe3C\x81_i\x91"} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=1]: could not find valid split key```

This is a small database with a table to store user's profiles (only 20 profiles). 
In the profile's table we store the picture of the user.

The picture field (type `string`) has a value with 259366 bytes. 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAIAAAC6s0uzAAAgAElEQVR4nMx92ZLsKKyghOv+9jxOxPxzGc2DQAgtgJ1Zp6+i43SWzSKzaRf4//7v/wEAAEBERAQBrABA/a+`...

```show columns from profiles;
       column_name       |  data_type   | is_nullable | column_default | generation_expression |                                      indices                                      | is_hidden
+------------------------+--------------+-------------+----------------+-----------------------+-----------------------------------------------------------------------------------+-----------+
  id                     | UUID         |    false    | NULL           |                       | {primary,idx_profiles_deleted_at,idx_idtype_idnumber,idx_profiles_company_tax_id} |   false
  created_at             | TIMESTAMPTZ  |    true     | NULL           |                       | {}                                                                                |   false
  updated_at             | TIMESTAMPTZ  |    true     | NULL           |                       | {}                                                                                |   false
  deleted_at             | TIMESTAMPTZ  |    true     | NULL           |                       | {idx_profiles_deleted_at}                                                         |   false
  status                 | BOOL         |    true     | NULL           |                       | {}                                                                                |   false
  email                  | VARCHAR(110) |    false    | NULL           |                       | {}                                                                                |   false
  picture                | STRING       |    true     | NULL           |                       | {}                                                                                |   false
```

The problem gets fixed after dumping and recreating the database from the dump.

**Environment:**
 - CockroachDB CCL v19.1.4 (x86_64-unknown-linux-gnu, built 2019/08/06 15:34:13, go1.11.6)
 - Server OS: ubuntu
 - Client app: cockroach sql

**Comment by lunevalex** [comment]
@dacrypt apologies for a really late response, this issue typically happens when you have rows with large data in them. Every time a row is updated we store a new version of the row in our MVCC data structure, so so i's possible to create more data then can fit in a single range (64MB at the time this ticket was created, the range size was updated to 512MB in 20.1). A row must reside within a single range, it is an invariant in the system. When the MVCC data reaches max size CRDB will refuse further writes to that row until that data is garbage collected (every 25 hours). The best solution in this case is to move the large columns (i.e. the picture) to its own column family so it's not updated with every user profile update. You can find more about column families here https://www.cockroachlabs.com/docs/stable/column-families.html.

**Comment by dacrypt** [comment]
Thanks for the update. To be fair, we shouldn’t have been using it to store pictures in the first place anyway.
