### ISSUE TITLE
ccl/cryptoccl: implement encryption-at-rest for pebble/vfs.FS 

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#39673]
The existing encryption-at-rest code is implemented in C++ in `c-deps/libroach/ccl`. The general approach is that we provide a custom `rocksdb::Env` which intercepts all file operations. We have to reimplement that code for use by Pebble (which is written in Go). Luckily, all of the crypto operations are supported by the Go standard library. The equivalent of `rocksdb::Env` in Pebble is the `pebble/vfs.FS` interface.

**Comment by petermattis** [comment]
As part of this work, we need to implement `Pebble.GetEnvStats`. Despite the name, `EnvStats` are mostly about encryption at rest:

```
// EnvStats is a set of RocksDB env stats, including encryption status.
type EnvStats struct {
	// TotalFiles is the total number of files reported by rocksdb.
	TotalFiles uint64
	// TotalBytes is the total size of files reported by rocksdb.
	TotalBytes uint64
	// ActiveKeyFiles is the number of files using the active data key.
	ActiveKeyFiles uint64
	// ActiveKeyBytes is the size of files using the active data key.
	ActiveKeyBytes uint64
	// EncryptionType is an enum describing the active encryption algorithm.
	// See: ccl/storageccl/engineccl/enginepbccl/key_registry.proto
	EncryptionType int32
	// EncryptionStatus is a serialized enginepbccl/stats.proto::EncryptionStatus protobuf.
	EncryptionStatus []byte
}
```

**Comment by petermattis** [comment]
@sumeerbhola Is there anything left to do on this issue?

**Comment by sumeerbhola** [comment]
#42943 added the stats but they are incomplete. The code has the following TODO:
```
	// TODO(sumeer): make the stats complete. There are no bytes stats. The TotalFiles is missing
	// files that are not in the registry (from before encryption was enabled).
```

**Comment by petermattis** [comment]
Thanks for jogging my memory. Do we need to implement these metrics in 20.1? I'm not sure what they are used for.

**Comment by jbowens** [comment]
> Do we need to implement these metrics in 20.1? I'm not sure what they are used for.

The already-populated `EncryptionType` field gets turned into the `rocksdb.encryption.algorithm` timeseries metric. The others look like they're surfaced through the `Stores` rpc (`_status/stores/`) and are consumed in the admin UI: `#/reports/stores/local`.

AFAICT, everything we need for populating `TotalFiles` already exists in `pebble.Metrics`. Almost everything is there for `TotalBytes` except the size of the obsolete log files. I'm not sure if we care about including them, because the size of log files is already a bit muddled in active log files w/ the distinction between live data and the on-disk file's allocated size. If we do want to count allocated file size for obsolete log files, we probably also want to surface the live log file's allocated file size for consistency.

Do you have any suggestions for the `ActiveKeyBytes` metric? Pebble's `*fileMetadata` would have the file size in-memory, at least for sstables, but not sure how we could expose that cleanly through pebble's interface. I could add a `(*pebble.DB).Files` method that returns a snapshot of all the files currently managed by pebble?

**Comment by petermattis** [comment]
> AFAICT, everything we need for populating TotalFiles already exists in pebble.Metrics. Almost everything is there for TotalBytes except the size of the obsolete log files. I'm not sure if we care about including them, because the size of log files is already a bit muddled in active log files w/ the distinction between live data and the on-disk file's allocated size. If we do want to count allocated file size for obsolete log files, we probably also want to surface the live log file's allocated file size for consistency.

Include the size of obsolete files in `pebble.Metrics` seems straightforward. I'm not sure how important this is, though. I'll leave this up to your judgement. Good point about "live bytes" vs "total bytes" muddling the `TotalBytes` metric already. WAL size is usually pretty small, so my concern about this is correspondingly small.

> Do you have any suggestions for the ActiveKeyBytes metric? Pebble's *fileMetadata would have the file size in-memory, at least for sstables, but not sure how we could expose that cleanly through pebble's interface. I could add a (*pebble.DB).Files method that returns a snapshot of all the files currently managed by pebble?

`pebble.DB.SSTables` returns a `[][]TableInfo`. `TableInfo` is the exported version of `fileMetadata`. So I think everything is already present for `ActiveKeyBytes`.

**Comment by petermattis** [comment]
@jbowens I think this should be closed, right? I believe the "Completes #..." line didn't trigger Github to do so. I usually use "Fixes #...".

**Comment by jbowens** [comment]
Ah yeah, thanks
