### ISSUE TITLE
exec: calling defer f.Wait() could block indefinitely when panicking

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#39779]
We call `defer f.Wait` in `Flow.Run` when running a flow. If a materializer experiences a non-vectorized panic, it will panic itself without performing any cleanup (i.e. canceling the flow context to notify components they should exit). This defer will then get executed, causing us to wait indefinitely for components to exit. We should decide to either perform some kind of cleanup on a panic or never call `defer f.Wait` (which we might also then want to write a linter for). Another option would be to `recover()` in the `defer`.

**Comment by yuzefovich** [comment]
A minor clarification is that this case occurs when the panic is not caught by `CatchRuntimeVectorizedError` because it is not "related" to the vectorized engine where "related" is defined as originating in the code that "lives" in one of these prefixes:
```
	execPackagePrefix  = "github.com/cockroachdb/cockroach/pkg/sql/exec"
	colBatchScanPrefix = "github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*colBatchScan)"
	cFetcherPrefix     = "github.com/cockroachdb/cockroach/pkg/sql/row.(*CFetcher)"
	columnarizerPrefix = "github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnarizer)"
```
I think I like your suggestion about using `recover()` since it aligns with what we're doing in the vectorized engine. One concern that I have (which might be ungrounded) is about the case when a goroutine other than the one `defer`ring `f.Wait()` panics. What will happen in such a case?

**Comment by asubiotto** [comment]
> One concern that I have (which might be ungrounded) is about the case when a goroutine other than the one deferring f.Wait() panics. What will happen in such a case?

Only the panicking goroutine's stack is unwound (confirmed with a playground experiment) which will just exit the program so we won't get a hang.
