### ISSUE TITLE
exec: support for OR expressions

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#39776]

**Comment by solongordon** [comment]
The naive way to do this would be to project the results of the left and right expressions and then have an Or operator which takes two boolean columns as input.

However, this is not quite correct because the Or evaluation should short-circuit if the left side is true. Example:
```
root@127.0.0.1:54317/defaultdb> create table t (x int);
CREATE TABLE

root@127.0.0.1:54317/defaultdb> insert into t values (0);
INSERT 1

root@127.0.0.1:54317/defaultdb> select * from t where 1/x = 1;
pq: division by zero

root@127.0.0.1:54317/defaultdb> select * from t where x = 0 or 1/x = 1;
  x
+---+
  0
(1 row)
```
This is a bit of a pain. I think we might need to do some clever selection vector manipulation to get the short-circuiting behavior. For instance if our OR expression is `x > 0 OR y > 0` we could do the following:
- Save the initial state of the selection vector.
- Apply the selection operator for `NOT x > 0`.
- Apply the selection operator for `NOT y > 0`.
- Set the selection vector to whatever indices appear in the original selection vector but not the final one.

**Comment by jordanlewis** [comment]
We do something very similar in the `CASE` operator.

**Comment by solongordon** [comment]
Good to know, I'll have a look and see if we can share logic between the two.

**Comment by solongordon** [comment]
Come to think of it maybe you can represent an OR expression as a CASE operation. `x > 0 OR y > 0` should be the same as `CASE WHEN x > 0 THEN true WHEN y > 0 THEN true ELSE false`.

**Comment by jordanlewis** [comment]
Yeah that seems accurate.
