### ISSUE TITLE
sql: propagate the number of rows updated / inserted to the command-line client 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3993]
The client should report the number of rows altered with insert/update. This applies both to the interactive client and "-e".

**Comment by knz** [comment]
Useful to report success/failure of CAS operations in #4036

**Comment by knz** [comment]
So I was looking into this and again the DB interface is not helping.
The problem is that even with multiple result sets the interface is still either rows[][] or nothing. For reporting the row count for update and delete, we need a different kind of interface, where the number of rows is a separate return value from the rows themselves; i.e.

```
type ResultSet struct {
   OK bool
   size  int
   rows *[][]string
}
query(...)  (results []ResultSet, err error)
```

But this requires rather pervasive changes in the Go driver and db interface.

What is wise to do here? 
- Roll out our own extended interface in our fork of lib/pq? 
- Have update/delete return a single row containing the number of updates? (that would be very untypical SQL behavior)

**Comment by andreimatei** [comment]
I thought returning the number of rows as the result is what @dt was working on? And I thought that's standard behavior? What does postgres return for INSERT and UPDATE?

**Comment by bdarnell** [comment]
The trouble is that the go sql interface has a strict separation between Query (which returns rows) and Exec (which returns a count of rows affected). We need to either use a lower-level interface (i.e. use lib/pq directly without going through database/sql) that does not force us into this distinction or parse the statements on the client side so that we can send statements with results via Query and statements without results via Exec.

**Comment by petermattis** [comment]
Tomorrow (or early next week) I'm going to take a look at what going directly through `lib/pq` (or `cockroach/pq`) can buy us.

**Comment by knz** [comment]
( While looking at #4036 )
