### ISSUE TITLE
demo: add enterprise license that automatically applies to cockroach demo

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#40222]
Users shouldn't have to actually have a license to be able to use the enterprise features in `cockroach demo`.

**Comment by knz** [comment]
> We have to make sure that users can't apply this license to other clusters -- its easy to see the current cluster license using

This is security by obfuscation. It's trivial to modify the cockroach program to print out the license anyway.

**Comment by knz** [comment]
@jordanlewis thank you for having a separate conversation, given that I am also having a separate conversation of my own about this with @dt 	.

It would help all the parties involved to ensure their separate conversations are put in writing and recorded for review in the issue description. (I will do my own part of this homework shortly).

**Comment by knz** [comment]
Here's my separate conversation:

1. @rolandcrosby 	and @dt are brainstorming license self-serves in 20.1, based on an opt-in interactive choice. This new feature would be:
  - **opt-in**
  - accompanied by a **clear text to advise the user** that their data would be sent online
  - accompanied by the **required legal links to GDPR data usage policy**

2. until the 20.1 work moves forward, @jordanlewis 	and @dt and @rohany 	have been tasked with *enabling enterprise features in the `demo` shell*

3. emphasis on "enabling enterprise features" and not "enabling telemetry" (as I had initially mis-understood)

4. as to the technical ways to do this here the spectrum of known solutions:

   1. a special boolean for `demo` that would create an alternate license validation path
   2. a pre-defined constant license string
   3. a locally auto-generated license string
   4. pinging a server online

5. pros and cons:

   @dt does not like solution 1 because "it makes the code harder to reason about" (I agree).

   @dt has no objection to the other 3 solutions.

   I (@knz) do not like any solution which makes `cockroach demo` mis-behave or incomplete if used behind a firewall or offline (eg in a plane)

   Any solution that requires a roundtrip to our server needs to serve the user with a **clear message that informs them this is taking place** and, if we store this data, **legal links to data retention policies**

   Any solution that requires an internet roundtrip needs a clear way to opt out, documented upfront in the UI presented by the tool -- in the `demo` case, that would be the terminal UI: flag `--help` + a warning/info string printed to the terminal when starting the program.

**Comment by knz** [comment]
> I do think we want telemetry from Cockroach Demo--I think it will be invaluable information

We can do so by enabling telemetry the regular way (and this does not require an enterprise license, so it's a separate license). We can easily recognize telemetry from a `demo` session once enabled because the app name `cockroach demo` does not get scrubbed.

**Comment by knz** [comment]
I'm sensitive to the "a license is a contract so it's important CRL remains party to contracts established by a tool automatically" so I don't have _fundamental_ objections to the idea to use a lic server.

However the opt-out and clear documentation about data retention is still a pre.

**Comment by knz** [comment]
There's an alternative as well: a license is a contract but the license key is not the only way to establish a contract.

We _can_ establish this contract upfront (eg via the web site) with a special-purpoose license saying "enterprise features are also granted implicitly to every user of the `cockroach demo` tool as long as clusters created in this way are not used for production purposes or made persistent"

**Comment by knz** [comment]
> Telemetry reporting is already on-by-default and disabled, if desired, via an env var

Are you sure? IIRC `cockroach demo` uses `TestServer` internally and that disables telemetry. I haven't looked at the code recently so I don't recall if there's an override.

**Comment by knz** [comment]
Let me check quickly

**Comment by knz** [comment]
Ok so I was right (and you're right it's an oversight), the update and reg loop is enabled in `cli/start.go` upon `cockroach start[-single-node]` only:

```go
      // Start up the update check loop.
      // We don't do this in (*server.Server).Start() because we don't want it
      // in tests.
      if !envutil.EnvOrDefaultBool("COCKROACH_SKIP_UPDATE_CHECK", false) {
        s.PeriodicallyCheckForUpdates(ctx)
      }
```

I gladly propose including this code in `cockroach demo` as well.

**Comment by knz** [comment]
I agree that _assuming we choose a license server_ the right thing to do will be to place that activation behind the same logic as the telemetry.

I'm still a bit annoyed at the idea to make `cockroach demo` ineffective when used offline, given that alternatives choices exist (see above).

**Comment by knz** [comment]
>  if you acquire a license though some other channel, i.e. go to the website and ask for one yourself for your air-gapped cluster -- you can still install it yourself just the same via SET.

oh I had not envisioned this alternative. That's actually pretty clever. Maybe it could be possible to include this idea into the warning messaage printed out if the HTTP conn to the lic server fails?

**Comment by knz** [comment]
(I would even suggest printing this message even when the check succeeds, to inform the user "they can make their enterprise feature also available offline by requesting a trial key")

**Comment by knz** [comment]
Responding to @awoods187 	

> I think we want cockroach demo to be usable offline with enterprise license

As suggested by David this is possible by requesting a trial license separately and installing it manually in the demo cluster using the `SET CLUSTER SETTING` statement.

> the whole point is to make this easy for developers to see and try features out?  What is easy about these proposed solutions?

The proposed design (license server) would make enterprise features available automatically for users who use the command online, and available manually for offline users by requesting a trial license separately.

I think it may be worth prototyping this design and then evaluating its UX with some users (and some PM acceptance testing) to verify that it "works" and is easy enough.

**Comment by knz** [comment]
No more comment on rationale from me.

Just a request that the more salient arguments here (and the things deliberately left out of scope) be mentioned on the eventual commit message.
