### ISSUE TITLE
backup: consider using distsql for work distribution

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#40239]
While watching `backup2tb`, which runs on 10 nodes,  I noticed that during the BACKUP phase at various times some of the nodes are completely idle while others are busy, even though the leaseholders per store graph is pretty even. 

This isn't terribly surprising: the way the backup coordinator sends out work isn’t really aware of who it is sending it to and just has a global limit on the max number of outstanding requests, so if more of those go to a single node, others my have no work sent to them at times. The 10 node cluster just seems to highlight this more than our 3 node clusters did.

There's a long-standing TODO around that limiter about this issue, but it also highlights another thing: BACKUP and RETORE both have lots of work to do that they want to distribute among nodes, pushing the computation out to the data. They do this by sending KV commands (ExportRequest and ImportRequest) however since they were originally built, distsql has been built as a general purpose way to distribute work, and push computation close to data, and has since had years of polish.

Switching to to use distsql as the work-distribution layer of BACKUP and RESTORE could utilize its more sophisticated tools for routing work to the appropriate ranges as well as steaming metadata between longer-running workers and coordinators.

For backup, instead of one coordinator sending raw export requests individually, we’d just let distsql’s existing partition-span-by-nodes assign table spans to Export_Processors_, with one processor on each node, and then have those processors send the ExportRequests (likely to themselves). We’d could do more granular request pacing/limiting in the processor since we can assume its work is all for one node, and potentially could get better sequential access patterns as well (since we could coalesce spans, since they’re now grouped by node for us)

For restore, we’d could eliminate ImportRequest and do the download/rekey in a processor that then sends AddSTTable requests (essentially doing the same thing, just not in a KV command). 
I mentioned how ImportRequest currently works (e.g. sending itself requests) to our core buddy a few weeks ago and they were pretty dubious that it belonged in the kv API, given that it doesn’t interact with the replica, i.e.  doesn’t declare keys / acquire latches / update ts cache / etc or read/write to it at all -- It is essentially a pure function of its input (files + rekey) sends its output via another KV command (an AddSSTable request that we expect will go to itself). This pure computation could just as easily happen in a distsql processor, and not tie up a replica/`store.Send` for something that doesn't actually involve Store.

Again, we built these this way before we had any alternative general purpose distributed computation infra, but it might be worth revisiting that design now that distsql has not only been built but also has years of polish too.

**Comment by dt** [comment]
This would be potentially useful for #44480

**Comment by pbardea** [comment]
A summary of an offline discussion with @dt, with respect to distsql restore:

### Background
Today, restore processes the import entries by following a pipeline as follows:
- Partition the import entries into chunks
- Split and scatter the chunks across the cluster
- Create workers and split and scatter the individual entries in each chunk. We chunk so that these workers can work on their own span which has shown to have performance improvements.
- As soon as an span has been scattered, an ImportRequest is sent for that range.

Note that scattering the ranges takes a non-trivial amount of time and benefits from being done concurrently with ImportRequests.

It's also important to note that restore also limits the number of in-flight requests in order to prevent over-congesting DistSender and causing other badness. This prevents us from sending all of the requests in parallel and waiting for them to be processed.

### Proposed DistSQL Version
The leading distsql implementation of this flow is to create 2 processors: one which splits and scatters, and another that performs in the ImportRequest. The first would stream it's completed entries to the second. In particular, the SplitAndScatter processor would stream the entries to import to the processor that is colocated with the leaseholder of that range. This is beneficial because ImportRequests will usually go to the same node they were dispatched on. Otherwise, there may be a situation where all nodes attempt to send an ImportRequest to the same node and now the entire cluster is blocked from making progress until the ImportRequests are handled.

Note, that this solution requires a new router type where data can be explicitly sent to a particular node in a DistSQL flow.

### Alternatives
1. SplitAndScatter in the processor that performs the import request.
This may provide a bit of benefit, but fundamentally still face the same issue where requests that all go to one node would start jamming all nodes and force nodes waiting on these requests to be idle.

2. SplitAndScatter, than schedule data import processors.
This solution would perform the SplitAndScattering serially, then after everything was scattered, plan out which processors are responsible for which spans. However, we have previously seen 

3. If the zone configs are restored at the start of the restore, we could pre-split and scatter based on those partitions and then we could assign the spans to nodes according to the locality restraints. However, there is likely insufficient information there to identify the leaseholder of a specific span, and the mechanism for notifying the processor that the span is ready to import isn't clear either.

**Comment by pbardea** [comment]
#50637 tracks the work related to creating the router that will connect the split and scatter processor to the restore data processor.

**Comment by pbardea** [comment]
After chatting with the DistSQL folks, the preferred approach is to use a `RangeRouter`, which is implemented today but does not have any uses. The RangeRouter can map spans to output streams. The idea is that each split and scatter processor will update its range router's mapping for the span it just exported, then the router will send it to the correct restore data processor.

**Comment by pbardea** [comment]
Closed by #51959.
