### ISSUE TITLE
Arithmetic on bigint does not compute correct results

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4025]
Just tested:

```
root@:15432> select 1754345309233639313::bigint * 10;
+--------------------------------+
| CAST(1754345309233639313 AS BIGINT) * 10 |
+--------------------------------+
| -903290981373158486            |
+--------------------------------+
```

Strangely if the value fits in an int the result is correct:

```
root@:15432> select 175434530923363931::bigint * 10;
+--------------------------------+
| CAST(175434530923363931 AS BIGINT) * 10 |
+--------------------------------+
|            1754345309233639310 |
+--------------------------------+
```

**Comment by petermattis** [comment]
`BIGINT` is an alias for `INT64`. It has no relation to `math/big.Int`. If you want arbitrary sized integers you need to use `DECIMAL`.

**Comment by knz** [comment]
Oops thanks !

**Comment by JackKrupansky** [comment]
Help me out... sql.y turns an ICONST token into an IntVal and scan.go generates an ICONST for a very large number larger than an int64 can hold (with a cast to Int64 in ScanNumber in scan.go). Sure, the raw token string is also in the ICONST/IntVal, but... how exactly does that IntVal in sql.y get turned into a DECIMAL Bit.Int (Ddecimal)? Where is the magic? Even if an explicit cast is used, how does that ICONST/IntVal finally get treated as a long string of decimal digits rather than DInt?

**Comment by petermattis** [comment]
There are still bugs in the DECIMAL implementation. A DECIMAL constant can currently never exceed the size of an int64.
