### ISSUE TITLE
sql: BIGINT parsing doesn't work

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4026]
```
Andreis-MacBook-Pro-2.local:26257> select 45395843954895834905843958439085904859034850934;
query error: strconv.ParseUint: parsing "45395843954895834905843958439085904859034850934": value out of range
select 45395843954895834905843958439085904859034850934;
```

**Comment by petermattis** [comment]
See my comment about #4025. You need to cast to `DECIMAL`:

```
root@:15432> select 45395843954895834905843958439085904859034850934::decimal;
+---------------------------------------------------+
| CAST(45395843954895834905843958439085904859034850934 AS DECIMAL) |
+---------------------------------------------------+
| "45395843954895834000000000000000000000000000000" |
+---------------------------------------------------+
```

PS Why is that ascii table being misformatted?

**Comment by nvanbenschoten** [comment]
The reason for the loss of precision is because we currently parse all floating point numbers or integers that would [overflow](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/scan.go#L549) a uint64 as `NumVals`, which [evaluate](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/eval.go#L1339) to a FLOAT, before being cast to a DECIMAL.

**Comment by nvanbenschoten** [comment]
As the `NumVal.Eval` comment states, type coercion needs to be improved before it is practical to default `NumVal`s to DECIMALS. Untyped literals could play a big role in this.

**Comment by andreimatei** [comment]
Right, I just filed this as a tracking bug.

**Comment by petermattis** [comment]
Do we need the new typing system to fix this? Or is there a shorter term fix available?

**Comment by nvanbenschoten** [comment]
I made a change a while ago to parse all `IntVal`s as `NumVal`s when the value is out of range. This made the issue's initial example look like:

```
root@:15432> select 45395843954895834905843958439085904859034850934;
+--------------------------------+
| 45395843954895834905843958439085904859034850934 |
+--------------------------------+
| 4.5395843954895834e+46         |
+--------------------------------+
```

This is better than an error, but it's still unfortunate that there is a loss of precision due to the `NumVal` float parsing. We could avoid this issue by evaluating all `NumVal`s as DECIMALS, but without the new type system, this would make working with constant FLOATS surprisingly difficult (in a similar way to the difficulty we currently face working with constant DECIMALS). When I tested changing the default `NumVal` type before, it broke a number of tests (which can be fixed), and wrecked havoc on sqllogictest. That said, I could see an argument made for no loss of precision being more important than ease of use. What do you think @andreimatei?

**Comment by andreimatei** [comment]
As long as we don't crash, I think we're good for the immediate term. I'll remove the "beta" label.

**Comment by nvanbenschoten** [comment]
I'm not sure why I didn't think of this before, but earlier this week @jseldess brought up the way that he's been writing casts for the docs, and it makes much more sense just to cast STRINGS to DECIMALS if we don't want any loss of precision. This will actually be more efficient than casting from a FLOAT to a DECIMAL anyway.

```
root@:26257> SELECT DECIMAL '12345678.7654323456788767887768767811';
+---------------------------------------+
| CAST('12345678.7654323456788767887768767811' AS DECIMAL) |
+---------------------------------------+
| 12345678.7654323456788767887768767811 |
+---------------------------------------+
```

**Comment by nvanbenschoten** [comment]
```
root@:26257> select 45395843954895834905843958439085904859034850934;
+--------------------------------+
| 45395843954895834905843958439085904859034850934 |
+--------------------------------+
| 4.5395843954895834e+46         |
+--------------------------------+
```

Parsing now works with the new typing system. The loss of precision is due to a FLOAT being determined as the numeric constant's type. Closing in favor of #6369.
