### ISSUE TITLE
save the offending data import is rejecting

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#40374]
**Is your feature request related to a problem? Please describe.**

the import command stops immediately when the data does not match import specifications.

`pq: nodelocal:///quotetestdata.csv: row 4: expected 3 fields, got 2`

it takes extra steps to look at the row and find the offending lines and find each and every line.  This becomes iterative process if there are many errors, especially if the offending data is at the end of the large data files that takes hours to process.

**Describe the solution you'd like**

save the offending data to another destination so that the file can be re-processed without having to reprocess the entire file again only to find one error at a time.

**Describe alternatives you've considered**

**Additional context**

**Comment by rolandcrosby** [comment]
To support this, we can add additional IMPORT syntax to allow the user to pass an additional cloud storage URI, to which we will write any malformed input lines. The code to parse cloud storage URIs and write to cloud storage is in [export_storage.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/storageccl/export_storage.go). Statements that use this functionality include BACKUP, EXPORT, and CREATE CHANGEFEED.

As this is being added rather late in the release, I'd hesitate to implement this via a SQL grammar change at this point. Instead, we could implement this via an experimental `WITH` option to start, and consider reifying it in the grammar in 20.1 after getting additional feedback from the SQL team.

I'm thinking the syntax could be something like:

`import table foo (a int primary key, b string, c string) delimited data ('s3://path/to/infile.csv') with experimental_malformed_input_uri='s3://place/to/store/malformed/input'`

We should try to implement this for the delimited and csv import formats to start. I think it should be possible to make this work for the mysqldump and pg_dump formats in the future as well, but there are other open UX questions we'll need to answer if we want to do that.

Open question: Should the cloud storage URI be a file name or directory name? Since IMPORT runs in parallel across multiple nodes, if we want to write all the malformed lines to a single file, we'll need to buffer all the malformed lines on a single coordinator node and have that node write the malformed lines to a file all at once. Alternatively, if we allow the path to be a directory, we could allow each node to accumulate the malformed lines separately and then write the data as they wish.

**Comment by robert-s-lee** [comment]
@rolandcrosby we can ask if single or multiple files are preferred with AWM.

**Comment by miretskiy** [comment]
@spaskob  can you describe what else do you see happing on this issue?

**Comment by spaskob** [comment]
Nothing in particular - feel free to close it after your PR merges.
It makes sense for you to own it since I am no longer actively working on IMPORT.
