### ISSUE TITLE
sql: failure to update job state can cause jobs to remain forever

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#40563]
When we fail to update the job state (to indicate success) at the end of a job, we log an error and move on, due to #38617. This can cause jobs to remain in a non-success state in the jobs table forever, even if all the other work for the job is completed.

**Comment by lucy-zhang** [comment]
cc @spaskob who has been designing job improvements

**Comment by dt** [comment]
I think we also have lots and lots of orphaned CREATE INDEX jobs in customer clusters running 19.1 from indexes that were created inside txns and thus didn't run async at all, plus the reported "hanging" drop jobs where the schema change lost track of its job record. Between these, it seems like there may be a lot of existing orphaned jobs in customer clusters.

I think for 19.2 we should consider adding an extra clean-up-orphaned-schema-change-jobs step to the job GC loop. E.g. fetch up to 10 schema change jobs that are over 10min old. For each, checks if the table descriptor it references is a) non-existent or b) public state and has empty mutations slice. If so, delete the job record.

(In 20.1 I think @spaskob's work on jobs will hopefully mean the job _is_ the schema change and we don't have this orphaning issue)

**Comment by spaskob** [comment]
What is the exact definition of orphaned? In particular, should I expect their status to always be running?
Any examples of customers' system.jobs table rows will be very useful for unit testing.

**Comment by spaskob** [comment]
Blocked by #40890

**Comment by dt** [comment]
#40890 seems like it probably affected the cleanup of _finished_ jobs by the cleanup loop, but what I was worried about here is jobs that are _not_ finished... and _never will be_. Specifically jobs that were created by schema changes that are no longer running, and are thus not going to come along and update the job they made, currently will sit around forever, and since they're not finished, show up in the UI in various places where users keep mistaking them for something running / stuck. 
One case of these, fixed in #39819, yields harmless but confusing CREATE INDEX jobs that were never used by the creation of the actual index since it happened in the txn, but we've had users report these as stuck (understandably).  I think #38617 could also mean real jobs that were being updated by a schema change may also have become orphaned: the schema change that was going to mark them as finished is done, but somehow the job is not marked as done, and thus it will linger forever.

I was thinking that for these, we want an extra case in our GC loop, that no only cleans up old finished jobs, but also cleans up old _unfinished_ jobs if we think they've become orphaned, so they stop confusing users.

**Comment by spaskob** [comment]
@dt any recommendations on how to confirm that the last PR has fixed this issue?
