### ISSUE TITLE
Support "bytea" as alias for "bytes" in the syntax for pg compatibiity, perhaps other types too?

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4069]
It is desirable for tutorials / doc etc to be able to provide examples that can be copy and pasted both in CockroachDB and PostgreSQL. For example:

```
select length('a'::string) + length('b'::bytes)
```

works in CockroachDB but not with pg, because pg knows neither `string` nor `bytes`. However pg knows `text` and `bytea`. Cockroach knows `text` as an alias for `string`, but does not know `bytea`. This issue suggests to add "bytea" as a syntactic alias for `bytes`.

**Comment by knz** [comment]
Also perhaps it would be smart to give more examples in our doc using "text" instead of "string", again so they can be pasted onto pg for comparison.

**Comment by JackKrupansky** [comment]
Maybe somebody from the original team could shed some light on the choice of STRING and BYTES, and whether they have some particular value other they being simple and obvious terms.

Me, I'd dump them in favor of TEXT and BLOB, with BYTEA for PG-compat.

BINARY LARGE OBJECT and BLOB are standard SQL.

CHARACTER LARGE OBJECT and CLOB are standard SQL as well - unlike VARCHAR, the maximum length is optional. PG allows the VARCHAR length limit to be optional as well.

MySQL supports TEXT and BLOB.

MySQL also supports BINARY and VARBINARY.

So:

TEXT, CHARACTER LARGE OBJECT, CLOB, VARCHAR.

BINARY LARGE OBJECT, BLOB, BYTEA, BINARY, VARBINARY.

If STRING and BYTES are to remain, fine, but the preference should be for standard SQL or PG-compat.

**Comment by petermattis** [comment]
Compatibility with the Postgres SQL dialect has never been a goal. I think we need to be very careful about adding functionality for the sole purpose of increasing PG-compatibility at this point. If we have users clamoring for it I would feel differently, but right now this is speculation. It's also possible I'm wrong about not making PG-compatibility a goal. I'm willing to hear arguments why we should. I think it is worthwhile to open this discussion and resolve it one way or the other rather than revisiting it feature by feature. 

My primary arguments against targeting PG-compatibility are that it is too hard, not necessary for adoption and at odds with some of the fundamental design decisions in CockroachDB. For example, the optimistic concurrency control in CockroachDB is at odds with the pessimistic locking necessary for `FOR LOCKING` clauses. Right now we're reworking how type inference works. Making this type inference 100% PG-compatible seems unnecessarily restrictive.

`STRING` and `BYTES` are aliases for `TEXT` and `BLOB`. Unfortunately, the rationale for these aliases is still non-public. Hopefully that will change soon. The large number of similar types (`TEXT`, `VARCHAR`, `CLOB`, etc) in other SQL systems seems like historical baggage to me. We can certainly make aliases for them (doing so is very easy), though I'd prefer to hold off until we hear that not having those aliases is a burden.

**Comment by bdarnell** [comment]
I think that increasing postgres-compatibility should be a goal, within limits. 100% compatibility is not achievable but that doesn't mean we shouldn't take low-cost steps like adding aliases to get closer. (Compatibility with the union of all SQL dialects is not a goal: I think it's a good idea to add `bytea` but that doesn't mean we should also add `VARBINARY` for compatibility with mysql).

My motivation for this is an extension of the logic that led us to implement the postgres wire protocol. Implementing the protocol allows us to work out of the box with preexisting low-level drivers in every major language, but it doesn't go far enough. Since people typically use some sort of framework (rails/activerecord, django, sqlalchemy, etc, etc) to abstract the database, we need to support the subset of SQL that these frameworks generate (for *some* existing dialect) or else we're back to requiring per-language/framework changes to support cockroachdb. I think this is achievable -- these frameworks tend to generate very simple statements -- but it does require a common vocabulary. 

Where the cost is low (adding new aliases for keywords we already have), I think we should go ahead and do it. Where the cost is prohibitive (`FOR LOCKING`), we won't, and I doubt that will make any difference for any of the major data frameworks. In between there will be a lot of edge cases that we'll have to decide one at a time (e.g. how close our type inferencing should come to postgresql's behavior), and we'll probably want to decide those in part based on how common the construct in question is.

**Comment by petermattis** [comment]
Supporting the subset of SQL used by common SQL frameworks seems like a reasonable rule to apply. I'd be curious to know what that subset is and where we're currently falling short.

**Comment by bdarnell** [comment]
Good question. A while back I ran SQLAlchemy's test suite against postgres and captured all the queries it ran (with `tshark`). The full log is at https://drive.google.com/file/d/0ByQnrkOiRT_LUHhhb3BRc29KQkE/view?usp=sharing

It's hard to tell what's actually required in there, though. The tests demonstrate the use of a lot of postgres extensions that we won't support, but it's hard to tell which are part of the "critical path" of using sqlalchemy at all versus something that you can opt in to. I did some preliminary work in [this branch](https://github.com/bdarnell/cockroach-python/tree/sqlalchemy) a while ago to try and build a cockroach dialect for sqlalchemy. All of this needs more investigation.

**Comment by JackKrupansky** [comment]
I took a quick look at the first few dozen CREATE TABLEs in that SQLAlchemy log and saw these non-CockroachDB features:

SERIAL
TIME WITHOUT TIME ZONE
TIMESTAMP WITHOUT TIME ZONE
CREATE SEQUENCE, nextval
CREATE TYPE
CREATE DOMAIN

And some things I was not sure about:

FOREIGN KEY
No PRIMARY KEY
CONSTRAINT

**Comment by knz** [comment]
I checked the SQLAlchemy log and bytea is the only remaining overlap, short of implementing pg's integer ranges, serial and hstore types.

**Comment by jseldess** [comment]
Bytes type covered in docs here: https://www.cockroachlabs.com/docs/bytes.html
