### ISSUE TITLE
sql: waiting to update leases: xxx is not a table logspam

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#40779]
Many tests have been logging the following a lot:

```
W190914 23:52:21.639523 178 sql/schema_changer.go:949  [n1,scExec] waiting to update leases: error with attached stack trace:
    github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.WaitForOneVersion
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:314
    github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).waitToUpdateLeases
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1201
    github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec.func1
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:948
    github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:964
    github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1.1
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1968
    github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1
    	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:2233
    github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1337
  - error with embedded safe details: ID %d is not a table
    -- arg 1: <sqlbase.ID>
  - ID 6889 is not a table
```

I'm not sure if this is a bug, but if it's not, it definitely shouldn't be spewing a stack trace.

It looks like @knz edited this code last, so I'm guessing it's just an issue of printing the error wrong. @knz could you please change this to be the previous behavior (not logging a giant stack trace?)

@lucy-zhang, could you figure out whether these logs are exposing an actual problem or are benign? If the latter, should they be getting logged at all?

**Comment by knz** [comment]
The error reporting is, IMHO, working exactly as intended:

- this code path is hiding the error object by replacing it with a new one. Prior to my change, the hidden error was forgotten entirely and we would completely lose track of it.
- this error object is not further captured (it is replaced by another one) so there is no other place than the log file to dump its details
- the details are needed to understand where that error object is coming from
- given the actual message ("ID ... is not a table") it certainly sounds to me like an error that needs to be investigated, instead of hidden by a more concise warning message. We should not be managing leases on descriptors that are not tables.

**Comment by lucy-zhang** [comment]
I will investigate this more, but for now, I believe this error can happen if the table ID is for a table that no longer exists in `system.descriptor` (as opposed to actually being a database or something). Maybe this node thinks it has leases for a table that doesn't exist, which could be bad.

**Comment by jordanlewis** [comment]
@lucy-zhang did you manage to make headway on this by any chance?

**Comment by lucy-zhang** [comment]
Not really. As expected, I was able to reproduce it reliably by dropping a table and waiting until it's deleted from `system.descriptor`, so I think the problem is that the lease manager (and maybe `system.leases`?) doesn't become aware of dropped tables and doesn't stop attempting to refresh their leases. But I'm not sure how serious of a problem this is.

I'm planning to get back to investigating this at some point, after getting through the release blockers.

**Comment by lucy-zhang** [comment]
@pbardea and I looked at this a little more today. I spoke too soon in my earlier comment, and it seems like the problem is more straightforward: We create a schema changer to GC the table, and the schema changer deletes the row for that table from `system.descriptor` and *then* tries to look it up. Paul is working on a fix.

**Comment by pbardea** [comment]
Also, it seems like it loops because we swallow the error in the case that the table descriptor is not found and thus never remove it from the map of schema changers to run on GC.

**Comment by knz** [comment]
Wait does it mean that in 19.1 and previous versions, if a user drops a table the following happens:
- the descriptor is never removed from system.descriptors (merely from system.namespace)
- there is a schema changer created, that will run forever attempting to look up a descriptor and not finding it?

? If so that bug will need a backport, and we may discover performance improvments in several places.

**Comment by pbardea** [comment]
After further investigation it looks like I was wrong. Because we swallow the error we eventually go down the "successfully completed schema change" code path and do remove the schema change.

It does seem like we should not log the the table is not an object when in fact it was a table and deleted.
