### ISSUE TITLE
storage: WaitForFullReplication hangs and causes test flakes

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#40805]
`TestParallel/subquery_retry_multinode` timed out and caused a build to fail, and the stack traces show that it seemed to have gotten stuck on `TestCluster.WaitForFullReplication()`. There were about 10 seconds of `testutils/testcluster/testcluster.go:718  [n1,s1] has 1 underreplicated ranges` in the logs.

#38565 is potentially related.

Test logs (internal): https://drive.google.com/file/d/1kQeirJNVxZlUUtgT_SpRYjlfw7U1tw-m/view?usp=sharing

**Comment by ajwerner** [comment]
@irfansharif any chance you could take a look at this? I've also seen

```
 make roachprod-stress CLUSTER=ajwerner-stress PKG=./pkg/ccl/partitionccl TESTS=TestRepartitioning
```
fail where it seems like we just don't move a replica we need to move (the SucceedsSoon times out). That may or may not be related. That test is currently pretty flaky with fatal errors today due to things fixed in #40751 but it eventually fails and it looks like we're just not doing anything. I verified that the replica which needs to move does indeed get the right zone config.

**Comment by ajwerner** [comment]
See this commit for an apparent repro:

https://github.com/ajwerner/cockroach/commit/be54787aab13cb42834f7d54daf192aa53af1413

**Comment by ajwerner** [comment]
Turns out my above comment is totally unrelated, see #40823.

**Comment by irfansharif** [comment]
Taking a look at this now.

**Comment by irfansharif** [comment]
```
panic: test timed out after 12m0s

goroutine 5157537 [running]:
testing.(*M).startAlarm.func1()
  /usr/local/go/src/testing/testing.go:1334 +0xdf
  created by time.goFunc
```

Just a timeout. We seem to have bumped this up in #40572.
