### ISSUE TITLE
sql: SELECT difference with column families

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#41007]
Same tables, different column families, different results. 

```
CREATE TABLE ef (e INT8, f INT8, INDEX (f));

INSERT INTO ef VALUES (NULL, 1), (1, 1);

SELECT e FROM ef WHERE f > 0 AND f < 2 ORDER BY f;

DROP TABLE ef;

CREATE TABLE ef (e INT8, f INT8, INDEX (f), FAMILY (f), FAMILY (e));

INSERT INTO ef VALUES (NULL, 1), (1, 1);

SELECT e FROM ef WHERE f > 0 AND f < 2 ORDER BY f;
```

First select:

```
   e    
+------+
  NULL  
     1  
(2 rows)
```

Second:

```
  e  
+---+
  1  
(1 row)
```

**Comment by jordanlewis** [comment]
Looks like trouble with `cfetcher`, since this doesn't repro with vectorize=off.

**Comment by jordanlewis** [comment]
Wait, nevermind, I had something mixed up. It does in fact repro with vectorize=off.

**Comment by jordanlewis** [comment]
Ah... perhaps the problem is that the index joiner is ignorant of the fact that multi-cf tables might have missing entries, which would indicate a NULL for that entry.

In this example, the primary index looks something like this:

```
/Table/ef/primary/rowid1/0 -> 1
/Table/ef/primary/rowid2/0 -> 1
/Table/ef/primary/rowid2/1 -> 1
```

And the secondary index:
```
/Table/ef/secondary/1 -> rowid1
/Table/ef/secondary/1 -> rowid2
```

The index joiner sees the 2 rows from the index, and creates 2 spans into the primary. Since it's smart and tries to do single-CF lookups, it creates the following spans:

```
/Table/ef/primary/rowid1/{1-2}
/Table/ef/primary/rowid2/{1-2}
```

The first span is empty, since there was a NULL for the column in the second column family. The index joiner doesn't do anything special when it doesn't see a match (which it presumes impossible) so we don't return anything at all.

**Comment by jordanlewis** [comment]
To solve this I think we'd need to teach the index joiner to be a little bit smarter about the data it receives, like the lookup joiner is - I think it might need to keep a map of things it has or hasn't seen. Alternatively perhaps it could always ask for column family 0?

@solongordon what do you think?

**Comment by solongordon** [comment]
I bet the lookup joiner is also susceptible to this bug, for instance if it's doing an inner join against a primary index. If that's the case, I think we would need to always request column family 0 as you suggest, since otherwise we can't distinguish between NULL and the absence of a row. I'll investigate.

On the index joiner side we could do something a bit fancier since we know the row exists, but perhaps for 19.2 we should stick with the column family 0 since it seems safer.

**Comment by solongordon** [comment]
I confirmed this is broken for lookup joins too.
```
root@127.0.0.1:54494/defaultdb> create table t (x int primary key);
CREATE TABLE

root@127.0.0.1:54494/defaultdb> create table t2 (x int primary key, y int, family (x), family (y));
CREATE TABLE

root@127.0.0.1:54494/defaultdb> insert into t values (1);
INSERT 1

root@127.0.0.1:54494/defaultdb> insert into t2 values (1, null);
INSERT 1

root@127.0.0.1:54494/defaultdb> select t2.y from t inner lookup join t2 on t.x = t2.x;
  y
+---+
(0 rows)
```
