### ISSUE TITLE
Incorrect count of total replicas for AllocatorAdd

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#41328]
**Describe the problem**

https://github.com/cockroachdb/cockroach/commit/dd5053e introduces a bug where the count of the total replicas after adding a new one is incorrect as it only takes into account the live replicas. This is different than 19.1 where all the replicas are counted. The bug leads to a situation where we would decide to add a new replica to a range with 1 dead and 2 live replicas and end up with 4 total replicas.
In 19.1 `willHave := len(desc.Replicas().Unwrap()) + 1`
In 19.2 `willHave := len(existingReplicas) + 1` however `existingReplicas := liveVoterReplicas`
There is a comment there that says `only include live replicas, since dead replicas should soon be removed` but this isn't generally true as a range may be under-replicated and there may not be enough live nodes to rebalance.

**To Reproduce**
1. Start a three node cluster
2. Kill one node and add a new node
3. Wait until the node killed in #2 is declared dead and all the ranges are rebalanced
4. Kill one node and add a new node

At that point all ranges (that are with replication number of 5) will add an extra replica to the node added in #4 and will end up with 4 replicas total - 3 on the live nodes and one on the dead node. 

Shutting down any of the live nodes at that point will lead to loss of quorum and the ranges will become unavailable.

**Expected behavior**
A common sense dictates that we should have 3 replicas on the 3 live nodes. However - this isn't also working in 19.1 so just fixing the bug in 19.2 won't get us to the common sense case. 19.1 is also badly behaving as it will get stuck and keep the ranges with 2 live and one dead replica.

**Comment by darinpp** [comment]
A customer reported the behavior here https://github.com/cockroachdb/cockroach/issues/41239

**Comment by andy-kimball** [comment]
Dan, can you comment on this? Was it your intention to modify this behavior in https://github.com/cockroachdb/cockroach/commit/dd5053e?

**Comment by danhhz** [comment]
I doubt I meant to change any behavior here, I'll take a look. cc @tbg

**Comment by danhhz** [comment]
This definitely seems to be an error in my refactor, I intended no behavior change here.

I looked up when the "only include live replicas, since dead replicas should soon be removed" comment was introduced and it was in #28875. This PR fixed #25392, which was a situation where one replica went dead, then another went dead, then the first dead replica came back.

**Comment by danhhz** [comment]
Is the right fix here simply to restore the old behavior? I'm not sure.

I agree that in Darin's scenario we want 3 replicas on the 3 live nodes. As I understand it, at master, we'll end up with 4 replicas, 3 on the live nodes and 1 on the dead node? If we buy the justification in #28875 that when we have a dead node we should upreplicate first before removing the dead node's replica, then it sounds like this line is working as intended. My question then is why does the dead node's replica stick around?

**Comment by darinpp** [comment]
A sensible thing to do when `num_replicas = 5` and you don't have 5 live nodes is to transition to 3 replica configuration. With replication factor of 3, you would relocate a replica on a dead node to a live node. But I haven't seen that logic anywhere in the code so I'll assume that we never did this.

**Comment by danhhz** [comment]
This seems related https://github.com/cockroachdb/cockroach/blob/04f2f3f69b4fe12b02499637be6b33435f45386d/pkg/storage/replicate_queue.go#L484-L517

**Comment by danhhz** [comment]
I'm still confused about why we don't remove that replica on the dead node

**Comment by darinpp** [comment]
> I'm still confused about why we don't remove that replica on the dead node

Because we haven't wrote the code in a way to handle that. The logic currently sees 5 nodes (3 live and 2 dead). One replica is placed on a dead node and 2 on the live nodes. The replication factor is 5 so the range is under-replicated. We currently check to see if we have a live node to add one more replica and that's - yes. But then we check if we have one more live node to get to the final configuration of 5 replicas and that's - no. So not being able to get to 5 replicas - we don't do anything.

**Comment by tbg** [comment]
Thanks for the sleuthing, @darinpp. The root cause as I see it is that we're even attempting to upreplicate in this situation, i.e. this path:

https://github.com/cockroachdb/cockroach/blob/91bb5880bc26a1447ed8a2ed6d6ddd900a863048/pkg/storage/allocator.go#L368-L384

basically makes the decision to upreplicate. Later, when we actually act on this decision, we used to not follow through because of the lack of live targets, but now we added an extra bug that does do it.

> With replication factor of 3, you would relocate a replica on a dead node to a live node. But I haven't seen that logic anywhere in the code so I'll assume that we never did this. We do transition up from 3 to 5 but never down.

There's something here but it's janky at best:

https://github.com/cockroachdb/cockroach/blob/91bb5880bc26a1447ed8a2ed6d6ddd900a863048/pkg/storage/allocator.go#L370-L371

If you have a range that wants to be 5x replicated but the cluster only has three (possibly dead, but not decommissioning or decommissioned) nodes, the effective replication factor will be set to three. This doesn't bite here since no nodes are being decommissioned, so after the kill+add the cluster will consider the effective replication factor three (four live nodes, but preferring the next best odd number).

For 19.2, we need to reestablish the 19.1 behavior. Fixing the underlying problem is too likely to introduce another problem.

**Comment by danhhz** [comment]
That's a good point. I think we could do something better in the future, but the only thing we could safely land right now for 19.2 would be the previous behavior. Are we calling this a 19.2 release blocker?

@darinpp wanna pick this off? I introduced this bug in my refactor and could blindly plumb down the old behavior, but you probably have this loaded up better at the moment.
