### ISSUE TITLE
sql: support  SQL declare (cursor)

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#41412]
**Is your feature request related to a problem? Please describe.**
A customer tried to use [tableau](https://www.tableau.com/en-us/) to connect to cockroachDB, using [this](https://help.tableau.com/current/pro/desktop/en-us/examples_postgresql.htm) guide.

Tableau uses `declare` for its queries, CockroachDB does not currently support compatibility with SQL level declare.

Tableau can not be used.

**Describe the solution you'd like**
Support for the declare keyword.

[postgres docs on declare](https://www.postgresql.org/docs/9.1/sql-declare.html).

Epic: CRDB-11397

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3853](https://cockroachdb.zendesk.com/agent/tickets/3853) has been linked to this issue.

**Comment by tfoldi** [comment]
I can easily fix this by adding Cockroach as a supported database driver to Tableau. Only thing you have to do is to set `params["UseDeclareFetch"] = "0";` in connectionBuilder.js in the Tableau TACO file. 

If you're interested I can show how to do build a proper driver customization for Tableau...

**Comment by tfoldi** [comment]
OK, I tested it and works like a charm. Code is here: https://github.com/tfoldi/tableau_cockroachdb_connector

![](https://raw.githubusercontent.com/tfoldi/tableau_cockroachdb_connector/master/connection_dialog.png)

**Comment by mattcrdb** [comment]
cc @jordanlewis

**Comment by otan** [comment]
this is needed for QGIS support for PostGIS.

**Comment by jordanlewis** [comment]
@otan, could you say more? Including links to sample queries or use cases would be very helpful.

**Comment by otan** [comment]
QGIS uses `DECLARE BINARY CURSORS` cursors: https://github.com/qgis/QGIS/blob/b4c21fa44e25c23c9ee542f56f031b3de1a94fea/src/providers/postgres/qgspostgresconn.cpp#L1353

and then FETCH: https://github.com/qgis/QGIS/blob/b4c21fa44e25c23c9ee542f56f031b3de1a94fea/src/providers/postgres/qgspostgresconn.cpp#L1698

... all for the sake of deducing endianness :3 

this is a startup sequence; i'm unable to open the tool without it, unfortunately.

**Comment by jordanlewis** [comment]
@otan @rafiss would we be able to send a PR to qgis to use a simpler method of deducing endianness?

**Comment by otan** [comment]
Maybe, but I found something perhaps even more useful -- the [`ogr2ogr` tool](https://gdal.org/programs/ogr2ogr.html) requires DECLARE CURSOR to work so we can export from CRDB into other exotic data formats.

**Comment by jordanlewis** [comment]
Note that there is more support required than just `DECLARE CURSOR` here.

`FETCH` is also required. `FETCH` has a few variants, including relative, absolute, and forward and backward fetches. The linked code significantly needs both forward relative and absolute fetches. Implementing absolute fetches is significant because it requires buffering all of the results of the cursor on the gateway, presumably in memory and then spilling to disk. Just wanted to say it is likely just the tip of the iceberg and we have to get a realistic estimate of the work required before we dive into this.

@otan would it be possible for you to run some of these tools against Postgres and collect a log of the statements produced? I would like to make sure we are not missing any other features. Significantly, if you can figure out whether "multiple active result sets" are used (aka - are there other SQL statements intereleaved in between the cursor FETCH statements on the same connection?) that would be very helpful for effort estimation.

**Comment by jordanlewis** [comment]
I would also be curious to see the comprehensive list of tools we need to support for spatial, and of that list, which tools require cursor support. I continue to find it surprising that geospatial tools all need DECLARE CURSOR. Why would that be exactly? Is this a case of 2 tools (ogr2ogr and qgis) needing the feature making it seem like they all do? Do they actually all need cursors? And in the latter case, why is that exactly? Is it because they're old?

Sorry for all of the questions. I feel we need an improved understanding of the situation here to appropriately understand and prioritize this work.

**Comment by otan** [comment]
See also: https://drive.google.com/drive/folders/1IQ8Y3VvsrcbEAaQku3d3vXJuPVcWHu5W?usp=sharing

**Comment by otan** [comment]
> I would also be curious to see the comprehensive list of tools we need to support for spatial, and of that list, which tools require cursor support. I continue to find it surprising that geospatial tools all need DECLARE CURSOR. Why would that be exactly? Is this a case of 2 tools (ogr2ogr and qgis) needing the feature making it seem like they all do? Do they actually all need cursors? And in the latter case, why is that exactly? Is it because they're old?

I'm not sure exactly why -- my guess is that it's easy to say "fetch me all data in a paginated manner" without having to read the schema and figure out exactly how it works.

**Comment by otan** [comment]
I will also note ArcGIS also required DECLARE CURSOR -- I will forward those notes to you.

**Comment by otan** [comment]
> I would also be curious to see the comprehensive list of tools we need to support for spatial, and of that list, which tools require cursor support. I continue to find it surprising that geospatial tools all need DECLARE CURSOR. Why would that be exactly? Is this a case of 2 tools (ogr2ogr and qgis) needing the feature making it seem like they all do? Do they actually all need cursors? And in the latter case, why is that exactly? Is it because they're old?

I don't think we've got a comprehensive list anywhere (@awoods187 do you?) -- these are ones that came up that seem popular in either import/export of data (ogr2ogr is *the* tool) or visualisations (ArcGIS and QGIS, which are both AFAICT *the* tool).

**Comment by dilip2048** [comment]
> OK, I tested it and works like a charm. Code is here: https://github.com/tfoldi/tableau_cockroachdb_connector
> 
> ![](https://raw.githubusercontent.com/tfoldi/tableau_cockroachdb_connector/master/connection_dialog.png)

How do I install it to my tableau?

Just starting using tableau. I want to connect my cockraochDB to tableau and visualize the data on it.

**Comment by tfoldi** [comment]
> Just starting using tableau. I want to connect my cockraochDB to tableau and visualize the data on it.

The process is documented here: https://tableau.github.io/connector-plugin-sdk/docs/share

**Comment by xvaara** [comment]
Do you have plans to implement cursor support?

**Comment by otan** [comment]
not yet @xvaara -- do you have a use case to share with us? this helps with prioritisation!

**Comment by FranckErnewein** [comment]
Hi @otan,
We use tools ( stitchdata.com ) to synchronise our Postgres databases to our datawarehouse (aws redshift).
We started to migrate services on cockroach but we can not use stitchdata anymore because it scans source database using `CURSOR` to copy new/updated lines to Redshift.

**Comment by xvaara** [comment]
I have many triggers, functions etc. so I can't use crdb. But I'd like to use it via postgres_fdw to sync instances and save versioning data. But I'd need to access that directly from postgresql. I'm thinking I'll try to use dblink if this still isn't on the roadmap. I asked about it somewhere few years ago.

**Comment by yob** [comment]
I also ran into this while experimenting with accessing cockroachdb via the postgres_fdw extension.

I was curious to see if it's possible to use FDW as part of the solution to incrementally migrating from postgres to cockroachdb. Possibly by creating a view that sits on top of the same table in postgres and cockroach, making them look like a single table to users of the database.

I followed the [postgres_fdw] setup docs](https://www.postgresql.org/docs/12/postgres-fdw.html) and importing the cockroachdb table into postgres appeared to work, however querying it fails. Here's how it looks from the postgres side:

```sql
experiment=# \dE
             List of relations
 Schema | Name  |     Type      |  Owner   
--------+-------+---------------+----------
 public | users | foreign table | postgres

experiment=# \d+ users
                                                Foreign table "public.users"
 Column |       Type        | Collation | Nullable | Default |      FDW options      | Storage  | Stats target | Description 
--------+-------------------+-----------+----------+---------+-----------------------+----------+--------------+-------------
 id     | bigint            |           | not null |         | (column_name 'id')    | plain    |              | 
 uuid   | uuid              |           |          |         | (column_name 'uuid')  | plain    |              | 
 email  | character varying |           |          |         | (column_name 'email') | extended |              | 
 name   | character varying |           |          |         | (column_name 'name')  | extended |              | 
Server: cockroachdb
FDW options: (schema_name 'public', table_name 'users')

experiment=# select * from users limit 1;
ERROR:  at or near "declare": syntax error: unimplemented: this syntax
DETAIL:  source SQL:
DECLARE c1 CURSOR FOR
^
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/41412/v20.2
CONTEXT:  remote SQL command: SELECT id, uuid, email, name FROM public.users LIMIT 1::bigint
```

**Comment by rafiss** [comment]
I'm closing this since initial DECLARE support will be in v22.1. I've files issues for additional work on cursors:

https://github.com/cockroachdb/cockroach/issues/77099
https://github.com/cockroachdb/cockroach/issues/77100
https://github.com/cockroachdb/cockroach/issues/77101
https://github.com/cockroachdb/cockroach/issues/77102
https://github.com/cockroachdb/cockroach/issues/77103
https://github.com/cockroachdb/cockroach/issues/77104
