### ISSUE TITLE
ui: search for graph names in the webui

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41638]
[Adding search to the statements page](https://github.com/cockroachdb/cockroach/issues/41537#issuecomment-542342431) got me thinking about broader search in the webui. The webui has so many great features like the network page or the CPU graph or the Ranges graph. But it can be hard to find these metrics. I know we've discussed promoting certain graphs to the front page that we know are valuable, or promoting graphs as a method of alerting if they show problematic results, but what if we also allowed for searching by title.

For example, say I'm a developer and I want to check for CPU. Instead of clicking different parts of the webui to find the relevant graph, I could type `CPU` in a search bar and then we would show relevant CPU results available that I could click and have it take me directly to the relevant graphs. Many people don't have the breadcrumb pattern of navigating the webui memorized (or don't know that different sections exist). With search, developers can more easily find all the value of the webui.

![image](https://user-images.githubusercontent.com/22278911/66924590-dd957c00-eff8-11e9-9f67-88a459a68528.png)

Jira issue: CRDB-5424

**Comment by awoods187** [comment]
@piyush-singh wonder if you think this is a good idea?

**Comment by piyush-singh** [comment]
Realized I didn't follow up here after our conversation in person. In short, I do think this is useful, but we may be able to get some of this value via better organization and flows in the UI. We will probably end up doing some sort of search/filter in the future though, so keeping this issue for now. Thanks for filing Andy!

**Comment by rmloveland** [comment]
I also want this.  I am the type of user who basically can not discover things by clicking around, but if I type "range" I would love to have autocomplete for: all charts that have 'range' in the title, all queries that have 'RANGE' in the SQL text, all debug page options that have "range", etc.

E.g. if I have a box at the top of the landing page and can type 'Replica' I can get to the 'Replica Quiescence' chart in ~1s (assuming autocomplete).

If I want to view 'Replica Quiescence' under the current regime I have to know it's in *Metrics* tab.  Then I further have to know it's in *Replication* dashboard. Then I further have to know I need to scroll down because the *Replica Quiescence* chart is not visible until you scroll down the page.

If finding 'replica quiescence' were an "ad" and I had to "convert" on it, I would probably drop out of the conversion funnel well before getting through the multiple steps above

but if I type "replica" and it pops up? boom

**Comment by awoods187** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/61511

**Comment by awoods187** [comment]
This seems like a good win in usability cc @thtruo

**Comment by thtruo** [comment]
Thanks for sharing Andy - the theme around improving searching / finding things of interest is an important one for people who use DB Console. cc @Annebirzin for awareness. I think there's still low-hanging fruit for us to consider to make things easier to find. As we consider those sets of improvements, it could ladder up into a bigger search improvement.

**Comment by Annebirzin** [comment]
I agree this falls with the theme of finding relevant information in db-console and could be a good usability win. A global search could be a good shortcut for users who may know what they are looking for. Another approach would be to surface metrics/modules on the overview page that guide users to relevant parts of the db-console (a bit more hand-holding). I think a combination of both would be useful.

**Comment by awoods187** [comment]
I agree both would be valuable but I would vote for search first since everyone is familiar with search and it doesn't require the same education/mapping intuitively to how people look for problems. How complex a project would it be to add a global search, say just for chart or endpoint names?
