### ISSUE TITLE
importccl: BenchmarkImportWorkload fails Pebble assertion

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#41932]
I believe we have a TC build that's running all the benchmarks to catch decay like this. May I ask you gentlemen to see why it hasn't caught this?
I'm also curious how come this uses Pebble.

```
make bench PKG=./pkg/ccl/importccl/ BENCHES=BenchmarkImportWorkload

--- FAIL: BenchmarkImportWorkload
    require.go:794:
        	Error Trace:	bench_test.go:59
        	Error:      	Received unexpected error:
        	            	pebble: keys must be added in order: /Table/53/2/0/1/"BARBARBAR"/"9cdLXe0Yhg"/1/0/1572030210.872746000,0#0,1, /Table/53/1/0/1/2/0/1572030210.872746000,0#0,1
        	Test:       	BenchmarkImportWorkload
```

**Comment by petermattis** [comment]
I'm not sure why our CI `bench` smoketest didn't catch this. We switched to using Pebble for sstable generation recently (even if you're not using Pebble for the storage engine). This is fairly safe as the sstable writing is not nearly as risky as the full kit-and-kaboodle of the storage engine. The assertion here looks valid. I think the benchmark needs fixing. I'll take a look next week.

**Comment by petermattis** [comment]
The problem is happening in or around `ccl/workloadccl/format.ToSSTable`. Some instrumentation shows the keys being added to the sstable:

```
batch: 1
  /Table/51/1/0/0
batch: 10
  /Table/52/1/0/1/0
  /Table/52/1/0/2/0
  /Table/52/1/0/3/0
  /Table/52/1/0/4/0
  /Table/52/1/0/5/0
  /Table/52/1/0/6/0
  /Table/52/1/0/7/0
  /Table/52/1/0/8/0
  /Table/52/1/0/9/0
  /Table/52/1/0/10/0
batch: 5000
  /Table/53/1/0/1/1/0
  /Table/53/2/0/1/"BARBARBAR"/"9cdLXe0Yhg"/1/0
  /Table/53/1/0/1/2/0
```

As far as I can tell, `format.ToSSTable` is only used by benchmarks. @danhhz has this just always been broken and we never noticed because RocksDB sstable building wasn't checking the keys were in order?

**Comment by danhhz** [comment]
It definitely worked when I wrote it, but it looks like it was accidentally working. `ToSSTable` is assuming the kvs coming out of WorkloadKVConverter are sorted, but I don't think this is guaranteed. The old sstable builder did check sortedness, so my guess would be something around the recent import changes rather than anything about the switch to pebble. Feel free to skip it and I'll deal with it later.

> I'm not sure why our CI bench smoketest didn't catch this.

Looks like that build uses `make benchshort` and this benchmark is skipped under short.

**Comment by petermattis** [comment]
> The old sstable builder did check sortedness, so my guess would be something around the recent import changes rather than anything about the switch to pebble. 

Really? The RocksDB sstable builder didn't check sortedness in Release builds until a recent change we made. Possible there is some other check on the `rocksdb::SstFileWriter` code path that I missed, but I just looked again and didn't see it.

I'll send out a PR to skip this benchmark.

**Comment by danhhz** [comment]
Did it check sortedness in non-release builds? That could be what I'm remembering. I definitely saw some out of order key errors way back when

**Comment by petermattis** [comment]
> Did it check sortedness in non-release builds?

Yes, though Debug builds were disabled, though it seems possible you stumbled across one somehow.
