### ISSUE TITLE
blog typos -> confusion

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#4194]
http://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/

> To address this case, CockroachDB always writes a sentinel key for each row that is the primary key without a column ID suffix. For our example row of <3, 4.5, "hello”>, the sentinel key would be: /test/3. Huzzah!

I think that's a typo, and should be <10, 4.5, "hello">. 

I'm not sure if the sentinel key would be /test/10 then;  I'm not sure how this example row relates at all to the case under discussion, which is when a column has a null value. Please revise for clarity.

**Comment by tamird** [comment]
@glycerine you're right, that should be `10`, not `3`. This doesn't relate to the specific case of that row, since the non-primary-key columns are not NULL, but the intention is to demonstrate that the sentinel key is always written, and thus would be present in case the non-primary-key columns _are_ NULL.

**Comment by tamird** [comment]
I'm going to close this issue; thanks for reporting the typo. Let me know if you have any lingering confusion.

**Comment by glycerine** [comment]
@tamird Thanks for clearing that up.
