### ISSUE TITLE
sql: uncancellable query

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#42035]
```
SELECT
	tab_192082.col_331528 AS col_331529,
	tab_192080.col_331526 AS col_331530,
	'?':::STRING AS col_331531,
	e'\x05#He<':::STRING AS col_331532,
	tab_192079.col_331524 AS col_331533
FROM
	(
		VALUES
			(e'k\x15\'':::STRING, '9':::STRING),
			(e'\x7fzJ\x1ai\b/':::STRING, e'j,1\x03':::STRING),
			('':::STRING, '[2':::STRING)
	)
		AS tab_192079 (col_331524, col_331525)
	JOIN (VALUES (e'H\x04FqaK\\':::STRING), (NULL), (e'R\t\x15\x1el<\x10':::STRING)) AS tab_192080 (col_331526)
		JOIN (VALUES ('b':::STRING)) AS tab_192081 (col_331527) ON tab_192080.col_331526 = tab_192081.col_331527 ON
			tab_192079.col_331524 = tab_192081.col_331527 AND tab_192079.col_331525 = tab_192081.col_331527
	JOIN (
			VALUES
				(e'L*76\x15':::STRING),
				('I,4<trA':::STRING),
				(e'A\x02\x0b3!z':::STRING),
				('':::STRING),
				(e'\x04\x0bl*':::STRING)
		)
			AS tab_192082 (col_331528) ON tab_192081.col_331527 = tab_192082.col_331528
WHERE
	true
LIMIT
	57:::INT8;
```

If you run this and then try to cancel it with `cancel query 'blah'` nothing happens. Using `set statement_timeout = '5s';` also does nothing.

**Comment by asubiotto** [comment]
This query seems to be stuck in an infinite loop at plan time here:
https://github.com/cockroachdb/cockroach/blob/1960dbdcf99672b13ee43a938ae821195c30d4b5/pkg/sql/opt/xform/optimizer.go#L423

**Comment by RaduBerinde** [comment]
CC @justinj @andy-kimball 

There are a bunch of rules that keep firing (including AssociateJoin) that I don't think are adding anything to the memo (which should be ok). I wonder if there is a flaw in the explorer logic where in certain cases rules that fire but don't do anything prevent us from declaring things as "fully explored".

**Comment by RaduBerinde** [comment]
Ah, no, the `AssociateJoin` rule is actually creating more and more inner join expressions. Haven't figured out how yet, it's pretty hard to debug. Simplified repro:
```
SELECT * FROM
      (VALUES ('x', 'x'), ('y', 'y')) AS vab (a, b)
    JOIN
        (VALUES ('z'), ('u')) AS vc (c)
      JOIN
        (VALUES ('v')) AS vd (d)
      ON c = d
    ON a = d AND b = d
  JOIN
    (VALUES ('w'), ('w')) AS ve (e)
  ON d = e
```

**Comment by RaduBerinde** [comment]
Finally, I found something. We are creating redundant filters under `range`:
```
filters
 ├── range [type=bool, outer=(1), constraints=(/1: [/'v' - /'v']; tight), fd=()-->(1)]
 │    └── and [type=bool]
 │         ├── and [type=bool]
 │         │    ├── and [type=bool]
 │         │    │    ├── and [type=bool]
 │         │    │    │    ├── and [type=bool]
 │         │    │    │    │    ├── and [type=bool]
 │         │    │    │    │    │    ├── and [type=bool]
 │         │    │    │    │    │    │    ├── and [type=bool]
 │         │    │    │    │    │    │    │    ├── and [type=bool]
 │         │    │    │    │    │    │    │    │    ├── and [type=bool]
...
 │         │    │    │    │    │         └── const: 'v' [type=string]
 │         │    │    │    │    └── eq [type=bool]
 │         │    │    │    │         ├── variable: column1 [type=string]
 │         │    │    │    │         └── const: 'v' [type=string]
 │         │    │    │    └── eq [type=bool]
 │         │    │    │         ├── variable: column1 [type=string]
 │         │    │    │         └── const: 'v' [type=string]
 │         │    │    └── eq [type=bool]
 │         │    │         ├── variable: column1 [type=string]
 │         │    │         └── const: 'v' [type=string]
 │         │    └── eq [type=bool]
 │         │         ├── variable: column1 [type=string]
 │         │         └── const: 'v' [type=string
 │         └── eq [type=bool]
 │              ├── variable: column1 [type=string]
 │              └── const: 'v' [type=string]
 └── eq [type=bool, outer=(1,2), constraints=(/1: (/NULL - ]; /2: (/NULL - ]), fd=(1)==(2), (2)==(1)]
      ├── variable: column1 [type=string]
      └── variable: column2 [type=string]
```

CC @rytaft (not sure if this is related to your recent improvement to this rule).

**Comment by RaduBerinde** [comment]
I think there are in general a few problems with `Range`. For example, `ConsolidateFilters` should sort the AND clauses inside each `Range`, because `SortFilters` cannot do that. It also feels we are missing some things in general around duplicate filter elimination.

I believe we added the `Range` operator solely for the benefit of constraints calculation, right? I wonder if things evolved and we can consider alternate approaches. For example, instead of storing Constraints on each `FiltersItem`, could we just store one on `FiltersExpr` (and group filters by columns when calculating that)?

**Comment by rytaft** [comment]
`FiltersExpr` is just a slice of `FiltersItem`s, so we'd need to change that definition to store scalar properties. I think @andy-kimball made the decision to not allow storing scalar properties on lists like `FiltersExpr` for performance reasons, although I don't remember the details.

I'll look into fixing the `Range` operator and adding duplicate filter elimination like you suggested, since I think that's probably easier than changing `FiltersExpr` to store a constraint. (If we change `FiltersExpr` to store a constraint, that also breaks some of the assumptions in the stats code, so we'd need to do a fair amount of work there too)
