### ISSUE TITLE
cli: avoid initializing a server context when running cli-only commands.

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4203]
Found by @bdarnell via #4201.

This needs to make cli.Context inherit from base.Context and server.Context from cli.Context.

**Comment by knz** [comment]
@bdarnell agreed on the approach? base -> cli -> server?

**Comment by bdarnell** [comment]
If by "make server.Context inherit from cli.Context` you mean embedding a cli.Context in server.Context, that won't work due to import cycles.

I'm not sure if a cli.Context type even makes sense. We need some place to parse command-line flags into, and maybe a Context struct would be useful for grouping those, but I think plain top-level variables (as currently used in `cli/flags.go` for some fields) are OK too. Once we know which command we're running, then the cli package should construct a server.Context (or rpc.Context, etc) based on those flag variables.

**Comment by tamird** [comment]
This also currently causes:
```
$ /cockroach sql --dev

****
**
** This node is being run in DEVELOPMENT mode.
**
** All data is ephemeral, and there is no security.
**
****

# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
```

**Comment by knz** [comment]
Needed to address #4217.
