### ISSUE TITLE
2000 High contention transactions over the same records take 30+ seconds

### ISSUE THREAD

**Issue by fracasula** [cockroachdb/cockroach#42062]
**What is your situation?**

I built a script to stress test CockroachDB which we are considering using for some of our production projects here at [Netdata](https://github.com/netdata/netdata), an open source project with 40k+ stars on GitHub.

I published the entire test [here](https://github.com/fracasula/cockroachdb-test).

I'm using Docker compose to bring up a cluster of 3 CockroachDB nodes with a Load Balancer in front of them (HAProxy). Once the cluster is up and running I start a Golang application that fires 2000 transactions against the cluster. Please have a look at the repository which explains in detail the test and how to run it.

For the sake of completeness I copied and pasted the explanation that is in my repository below.

**CockroachDB test - EXPLANATION**

This test consists in bringing up a cluster of 3 nodes with a HAProxy Load Balancer in front of them.

Once the cluster is up and running a Golang application will fire 2000 transactions over 10 connections that all try
to write over the same records thus over the same Range.

Every transaction consists of two `INSERT`s, one `UPDATE` and one `SELECT`.

The concept is very simple, an account is created in the `accounts` table with a balance of 1,000.00€ then 2000
goroutines are created. Each one of them tries a Database transaction. 

Each Database transaction tries to add two monetary transactions to the `transactions` table for the exact same account, 
one of 500.00€ and one of 495.00€.  

After writing the two monetary transactions the Database transaction tries to update the account balance. 
It then `SELECT`s the balance to check whether it is below zero. 
If it is below zero it rollbacks the transaction, if it is not below zero it commits the Database transaction.

We expect only one Database transaction to succeed out of the 2000, which means that the remaining balance at the end of
the program should be 5.00€.

**Note:** On my computer it's taking an average of 30 seconds to complete. If I run the same test with SQLite (not SQLite in memory) it takes less than 3 seconds for the same outcome (100% consistency).

**Requested resolution**

I would like to understand if the poor performance I'm experiencing with CockroachDB could improve to something similar to what I'm getting with other Databases (i.e. SQLite) by configuring CockroachDB properly. Any advice/clarification would be very appreciated.

Select all that applies:

- I mostly seek information: data, general advice, clarification.
- I seek guidance as to how to tune my application or CockroachDB deployment.

**Comment by mattcrdb** [comment]
Hi there,

I modified your DDL to have UUID's instead of integers for accounts.id and transactions.account.

I suspect you were running into a hot range and that is why the script was taking long.

Under the hood, CockroachDB stores everything lexicographically and therefore everything was hitting the same range.

With UUID's, I am seeing the script perform in ~2.3 seconds.

Please let me know if the modification worked on your end.

Best,
Matt

**Comment by mattcrdb** [comment]
These may be helpful to you as well.

https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#understanding-and-avoiding-transaction-contention

and 

https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#unique-id-best-practices

**Comment by fracasula** [comment]
Hi @mattcrdb thanks for getting back to me.

I see your point but  I don't see how that should affect the performance though since there was no AUTO INCREMENT on the IDs, I'm supplying the same ID (i.e. `1`) for all the 2000 transactions so the nodes shouldn't have to communicate to agree on the next ID since there's no sequence at all. There's also no `SELECT` roundtrip either (e.g. `INSERT INTO tbl (id, …) VALUES ((SELECT max(id)+1 FROM tbl), …)`).

In fact I just changed the example and I'm now using `UUID`s instead of `INT`s but I'm still getting the same kind of performance (i.e. `Script took 26.323504876s`).

Here's the new schema:

```sql
CREATE TABLE accounts (
    id UUID NOT NULL,
    balance_cents INT8 NOT NULL,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    FAMILY "primary" (id, balance_cents)
);

CREATE TABLE transactions (
    account UUID NOT NULL,
    id UUID NOT NULL,
    amount_cents INT8 NOT NULL,
    description STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (account ASC, id ASC),
    CONSTRAINT fk_account FOREIGN KEY (account) REFERENCES accounts (id),
    FAMILY "primary" (account, id, amount_cents, description)
) INTERLEAVE IN PARENT accounts (account);
```

And [here](https://github.com/fracasula/cockroachdb-test/blob/98b225ba57332a2ca75273300116d2e052ae083a/bootstrap.sql) is the old one (as you can see there's no sequence/auto_increment there).

> Under the hood, CockroachDB stores everything lexicographically and therefore everything was hitting the same range.

Of course the queries are hitting the same range regardless of the auto increment because I'm supplying the account ID that the transactions should run against [here](https://github.com/fracasula/cockroachdb-test/blob/master/goapp/main.go#L13). That was the whole point of my test, I verified that by running a `SHOW RANGES` too. We're talking about a script that runs 2k transactions over the same 3 records over and over (1 row into the accounts table and 2 rows into the transactions table).

Is there anything that can be done to improve performance in this scenario? Also, where did you run the test? Bare metal or you used the `docker-compose` I provided? I don't see how it could take ~2.3 seconds in your case unless you didn't run my go app and used something else to hit the DB.

Thanks!

**Comment by mattcrdb** [comment]
You can try limiting the performance to one node. I suspect that the time is being spent on raft consensus between each transaction and that is accumulating. You can try running this test on a one node cluster. I was running it using the docker-compose you provided but i misunderstood the premise so UUID's won't change anything so long as you are hitting the same row every time.

**Comment by fracasula** [comment]
I already tried that as I told your colleague [Carolyn Parrish](https://www.linkedin.com/in/parrishcarolyn) via email, I forgot to mention it it here though. Please find it below for reference:

> Initially I thought it was because of the consensus algorithm, meaning that it takes longer than a traditional SQL database because multiple nodes have to agree on a write before it is committed.
But then I tried the same code on a single node (no consensus there) and, even though the execution time went down from 30 seconds to 18 seconds, I realized it may not be the main culprit.
Consider that SQLite behind an HTTP server (so take HTTP overhead into account as well) takes less than 3 seconds against the 18 of the single CRDB.

**Comment by mattcrdb** [comment]
Is SQLite running in serializable mode?

**Comment by fracasula** [comment]
> Is SQLite running in serializable mode?

I think so, here's an excerpt from the [SQLite documentation](https://www.sqlite.org/isolation.html):

> Except in the case of shared cache database connections with PRAGMA read_uncommitted turned on, all transactions in SQLite show "serializable" isolation. SQLite implements serializable transactions by actually serializing the writes.

To make sure I'm getting a `serializable` isolation level I'm using a single connection only with the shared cache turned off plus I'm doing a `BEGIN EXCLUSIVE TRANSACTION` [for all transactions](https://github.com/fracasula/cockroachdb-test/blob/master/goapp/transactions/transactions_sqlite.go#L18). And here's [how I create the SQLite connection](https://github.com/fracasula/cockroachdb-test/blob/master/goapp/main.go#L33):

```go
db, err = sqlite.New("sqlite.db?cache=private&_foreign_keys=1&_txlock=exclusive&_journal=DELETE")
```

Does it make sense? If you think my SQLite set up is wrong please let me know.

I've updated my [repo](https://github.com/fracasula/cockroachdb-test) anyway so that you can run the SQLite code as well if you want. As usual just do `make run` first and then `make test` for running the CRDB test or `make test-sqlite` for running the SQLite one.

On my computer it takes ~320 **milliseconds** with SQLite versus the ~16 **seconds** of CRDB. It was taking 3 seconds before because it was adapted in another project and it was running behind a REST API so the 3 seconds were due to the HTTP overhead. If I call the SQLite DB directly like in the new code I pushed for you it takes only 320ms.

**Comment by nvanbenschoten** [comment]
Hi @fracasula, thanks for opening this issue and providing fantastic reproduction steps. That makes all of this significantly easier to iterate on.

Using your repo, I tried to get a better understanding for both why things are running slower in Cockroach than in SQLite and to see whether there's anything we could do about it.

### Differences between CRDB and SQLite:

To start, let's discuss the differences between the two configs, as this will help us determine where to optimize and whether there are any obvious wins.

- The first obvious difference between the two deployments is that CRDB is running with a cluster of 3 machines while SQLite is running with just a single instance. This means that Cockroach is performing a lot more work than SQLite for each write. While Cockroach is performing a round of distributed consensus between all three processes (including an fsync in each process) at least once per txn, it's not even clear that SQLite needs to perform a single fsync if a transaction is rolled back, which they all are here. Given that it's taking 160us per txn (320ms / 2000 txns), I would guess not.

When I drop down to a single node Cockroach cluster, I see a similar improvement to you, with the runtime dropping to about 16s. Cockroach still doesn't avoid the fsync on rolled back txns, but at least it no longer needs to coordinate across processes. Of course, this coordination is part of the sell of Cockroach, but it's helpful to understand its cost.

- The next difference is that CRDB is using Docker networking and HAProxy while (I think) the idea is that SQLite is avoiding these extra layers, either by talking to a SQLite process or by talking to a HTTP server that's talking directly to SQLite. I wasn't expect this to have much of an impact, but I was surprised when I found that while working on an improvement to some of the SQL for Cockroach, the app still took **7 seconds** to run with a syntax error in the first SQL statement. That indicates that there's some serious overhead somewhere in the network stack here. See below for further exploration.

### Improvements to SQL:

While getting familiar with the code, I noticed two easy wins to make the SQL work better with CRDB.

- The first is to merge the [`UPDATE accounts`](https://github.com/fracasula/cockroachdb-test/blob/fdc6b32c3b755a39f6906228be01da161b472377/goapp/transactions/transactions.go#L37) statement with the [`SELECT accounts`](https://github.com/fracasula/cockroachdb-test/blob/fdc6b32c3b755a39f6906228be01da161b472377/goapp/transactions/transactions.go#L45) statement using a `RETURNING` clause. You can do this with a statement like `UPDATE accounts SET balance_cents = balance_cents - $1 WHERE id = $2 RETURNING balance_cents`. This reduces the number of statements issued and the number of times the accounts table is read. With this change, performance improved by about **23%**.

- The second is to batch the [`INSERT INTO transactions`](https://github.com/fracasula/cockroachdb-test/blob/fdc6b32c3b755a39f6906228be01da161b472377/goapp/transactions/transactions.go#L24) statements together into a single [multi-row statement](https://www.cockroachlabs.com/docs/stable/insert.html#insert-multiple-rows-into-an-existing-table). This is generally [good practice](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#use-multi-row-dml-instead-of-multiple-single-row-dmls) with CRDB when possible because it reduces the number of SQL statements issued and allows for more batching across the network and to disk inside Cockroach. With this change, performance improved by about another **20%**.

Both of these are good improvements to make with CRDB no matter what, but I think they're particularly beneficial because of the networking performance we see with docker compose.

### Removing Docker

These improvements were helpful, but I still couldn't explain the ~7ms transaction latencies in CockroachDB. At some point, I spun up a single-node Cockroach cluster on my laptop, outside of Docker compose. I ran the same test against it (with the SQL improvements) and saw the test finish in **4.7s**! This corresponds to a transaction latency of **2.3ms**. That's much closer to what I was expecting and is on the order of the latency of a single fsync.

So I think there's something funky going on with docker or haproxy in this test, which I can't really explain. We can dig more into it, but I think the remaining internal difference between the two databases is that CRDB still performs an fsync on a rolled back transaction while sqlite is able to avoid it when transactions are rolled back.
