### ISSUE TITLE
ui: exclude backups from the "Service Latency: SQL, 99th percentile" graph

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#42174]
**Is your feature request related to a problem? Please describe.**
Currently, in the service latency graph, we include backups. This can be confusing to users who expect this only to include queries from the application. The information window from the service latency graph states: “Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.” Here is a graph of a cluster performing 15 incremental backups every hour, they take a few seconds to run, so they spike the graph: 
![image (4)](https://user-images.githubusercontent.com/351857/68176585-44dc8700-ff3a-11e9-8541-d0e28400ac7e.png)

**Describe the solution you'd like**
I would like to see backups removed from this graph, they could be included elsewhere, but I believe on this graph, they should be removed to help users focus on their queries and not admin tasks.

**Comment by piyush-singh** [comment]
@mwang1026 ran into this again this week. cc @jordanlewis and @awoods187 as you start to think about statement telemetry. FWIW other customers have run into this too - simple sql shell commands that can take some time to return (e.g. `SHOW RANGES`) will impact p99 latency which will sometimes panic our users.

**Comment by tim-o** [comment]
Our friend @jasobrown also ran into this - @jordanlewis @awoods187 thoughts?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5110](https://cockroachdb.zendesk.com/agent/tickets/5110) has been linked to this issue.

**Comment by jasobrown** [comment]
bump - any comments here?

**Comment by bdarnell** [comment]
Backups are a particularly common example of this, but the root cause is that percentiles are not particularly useful metrics for heterogenous data. Another case where this comes up is benchmarks, since they often have exact ratios of reads to writes or other operations. A benchmark that runs 99% reads and 1% writes will show unstable p99 latencies depending on exactly how the data broke down during the sampling interval. You can adjust this to avoid being right on the edge (we normally use 95/5 instead of 99/1 for our "read-heavy" benchmarks for this reason), but then you may be measuring something slightly different (if we assume that reads are consistently faster than writes, then p99 of a 95/5 benchmark is actually the p80 write latency). 

This is a difficult problem to solve in the general case; I've never seen a satisfactory monitoring solution that looked primarily at the database instead of the application. (In fact, one of my more heterodox SRE positions is that means are a better starting point than percentiles or medians - you have to put in more work to categorize your operations before percentiles are meaningful). We have some steps in this direction (filtering by app name in the statements page), but even that's not fine-grained enough. 

That said, I think it still makes sense to remove backups (and other bulk-io operations) from this chart as a special case because they're very common and so dramatically different in performance from regular statements.

**Comment by Azhng** [comment]
Hi @rkruze, do you know if the backup operations that caused these latency spikes were executed using `BACKUP` statement or `CREATE SCHEDULE FOR BACKUP` ?

**Comment by piyush-singh** [comment]
Roko has left the company since this was filed. This was from a regular backup statement as this issue predates the `CREATE SCHEDULE FOR BACKUP` feature

**Comment by mwang1026** [comment]
All `CREATE SCHEDULE` does is create the schedule. Under the hood it's just running `BACKUP` commands, although those backups run with the `detached` option which actually makes it non-blocking. Regardless, you will still have these issues iwth long running imports, exports, restore, backup, etc. that are run blocking

**Comment by Azhng** [comment]
I see. I wanted to confirm this because we account service latency of `CREATE SCHEDULE FOR BACKUP` statement using `internal_metrics`, which should not be visible in this graph, instead of using the regular `metrics`. 

I will send in the PR to exclude Bulk IO operations from being accounted.
