### ISSUE TITLE
sql: fill in pg_index.indoption

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#42175]
`pg_index.indoption` is supposed to be "an array of indnatts values that store per-column flag bits. The meaning of the bits is defined by the index's access method".

In practice, it appears that it's a bitfield with 2 used bits - a descending bit, and a "nulls-first" bit. See https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_index.h#L70-L76:

```
/*
 * Index AMs that support ordered scans must support these two indoption
 * bits.  Otherwise, the content of the per-column indoption fields is
 * open for future definition.
 */
#define INDOPTION_DESC			0x0001	/* values are in reverse order */
#define INDOPTION_NULLS_FIRST	0x0002	/* NULLs are first instead of last */
```

We should fill this in properly, as at least one ORM (Django) expects to be able to retrieve accurate results from this query - it's currently always set to 0 for all columns.

**Comment by rafiss** [comment]
Just to spell this out explicitly to affirm my understanding:

Because CockroachDB sorts NULL values first with ASC and last with DESC, this means that the only two valid values of this bitfield are `0b10` and `0b01`. In other words, if the index is ASCENDING, then the nulls will appear first. And if the index is DESCENDING, the nulls will appear last.
