### ISSUE TITLE
sql: add test with insert behavior on timestamps before and after update

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42309]
This issue tracks adding a test (perhaps roachtest) with the script in #42283, potentially extended to other types that allow a precision parameter.

Jira issue: CRDB-5372

**Comment by lucy-zhang** [comment]
I wonder if this could be generalized. Could we have a test that creates columns of every type (not restricted to timestamps), generates random values of each type, and ensures that all the values survive a round-trip during and after a cluster upgrade?

There are also other potential sources of upgrade-related error besides this bug, since all the values and table descriptor protos have to be both forward- and backward-compatible during a rolling upgrade. It would be nice to have a test that exercises all the possibilities.
