### ISSUE TITLE
ALTER INDEX IF EXISTS does not seem to work

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#42399]
**Describe the problem**

The syntax `ALTER INDEX IF EXISTS` does not seem to work. It seems its implementation was forgotten in https://github.com/cockroachdb/cockroach/issues/2034

**To Reproduce**

Run this statement:

```sql
alter index if exists i1 rename to i2;
```

I'm expecting it to be ignored, but I'm getting:

```
SQL Error [42704]: ERROR: index "i1" does not exist
```

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.2.0-rc.4 (x86_64-unknown-linux-gnu, built 2019/11/05 20:40:29, go1.12.12)
 - Server OS: Linux in DOcker
 - Client app: JDBC

**Comment by awoods187** [comment]
This does appear to be missing. Contrast it with:
```SQL
alter table if exists i1 rename to i2;
RENAME TABLE

```

**Comment by jordanlewis** [comment]
@rafiss could you or @apantel take this?

**Comment by rafiss** [comment]
The support for this syntax was added in #2126 

In #5838 the syntax was changed a bit so that it requires the `@` syntax for specifying an index in an `ALTER INDEX` statement. Still, I would agree that this error message isn't good -- it should either tell you to use the `@` syntax, or else just get ignored.
