### ISSUE TITLE
sql: unexpected FK validation problem with MATCH FULL

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#42498]
```
CREATE TABLE table1 (
	col1 REGPROC NOT NULL,
	col2 DATE NOT NULL
);

CREATE TABLE table2 (
	col3 REGPROC NOT NULL,
	col4 DATE NOT NULL,
	UNIQUE (col4, col3)
);

ALTER TABLE table1
	ADD FOREIGN KEY (col2, col1) REFERENCES table2 (col4, col3) MATCH FULL;
```

Produces an error:

```
pq: validate foreign key constraint: incompatible COALESCE expressions: expected col1 to be of type date, found type regproc
```

The two tables are identical except table2 has a unique index. If you take out the `MATCH FULL` it works. Something's fishy.

**Comment by lucy-zhang** [comment]
FWIW, the internal executor query for validating `MATCH FULL` FK constraints that's producing this error is generated here: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/check.go#L63-L120

**Comment by lucy-zhang** [comment]
I took a quick look, since I wrote that query a while ago. This seems like an obvious bug: we're probably trying to do `COALESCE(col2, col1)`, but `COALESCE` can't take arguments of differing types, and our logic tests never caught this because we only used int columns.

I think this should be easily fixable. We can just replace `COALESCE(c_1, ..., c_n) IS NULL` with `c_1 IS NULL AND ... AND c_n IS NULL`.
