### ISSUE TITLE
opt: allow correlated non-mutating CTEs

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#42540]
We should support queries of the form:
```
SELECT
    *
FROM
    (VALUES (1), (2)) AS v (x),
    LATERAL (SELECT * FROM (WITH foo AS (SELECT 1 + x) SELECT * FROM foo))
```

**Comment by jseldess** [comment]
@RaduBerinde, can you help me draft up a description of this limitation?

**Comment by RaduBerinde** [comment]
@rytaft could you help @jseldess with this?

**Comment by rytaft** [comment]
Sure -- I'd say something like:
"Common Table Expressions (CTEs), which are expressions of the form `WITH cte_name AS <query>`, may not contain references to a higher scope. In other words, if a CTE is contained in a subquery, the CTE may not reference columns defined outside of the subquery. For example, `SELECT (WITH foo AS (SELECT 1 + x) SELECT * FROM foo) FROM (VALUES (1), (2)) AS v (x);` returns the error "ERROR: CTEs may not be correlated" because `x` is used in the CTE but defined outside of the subquery."
