### ISSUE TITLE
profiling: surface C++ profiles

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#42585]
During the [backup memory leak](https://github.com/cockroachdb/cockroach/issues/42527) investigation, C++ profiles were needed.
The current method of enabling jemalloc profiling involves:
- enable jemalloc profiling: `MALLOC_CONF=prof:true`
- enable periodic profile dumps: `COCKROACH_MEMPROF_INTERVAL=60s`
- restart process and look for profiles in `<data-dir>/logs/jeprof*`

By comparison, Go heap profiles are also available:
- as automatic profiles when allocated memory high-watermark is exceeded (see [heap profiler](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/heapprofiler/heapprofiler.go)
- in the debug section of the admin UI

We should make C++ profiles more easily accessible. It is possible to [enable profiling but leave it inactive](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling), although this is only useful for memory growth (better than nothing).
The cost of profiling within jemalloc should be weighed against the usefulness of regular C++ profiles.

@petermattis for triage.

**Comment by petermattis** [comment]
The big question in my mind is whether this is worthwhile. We've had exactly one memory leak in C++ code in recent memory, no plans to extend the amount of C++ code we use in the near term, and plans to deprecate most of the existing C++ code. 

Is it possible to enable jemalloc profiling without setting the `MALLOC_CONF` environment variable?

Cc @miretskiy who was looking at what we could have done to automatically catch this memory leak.

**Comment by miretskiy** [comment]
I was able to compile libroach w/ address sanitizer.  No issues were found
when running tests... BUT, I'm can't say "we're in the clear" because
there could be other leaks & issues in the other c-deps: Basically, any of
the sanitizer options (-fsanitize=address, etc) *must* be applied to
everything consistently
(both compile and link step).  In addition, when using fsanitize=*, you
shouldn't use jemalloc.
These types of transformation/changes are hard to get right, particularly
by somebody (me) who is entirely unfamiliar with the mish-mash of various
build systems
used by c-deps subprojects.

Another issue is that some sanitizers (e.g. leaks) can only be found if
there is a test that exercised the code in question.  A spot check for this
particular leak seem
to indicate that we didn't have c++ tests that touch that code -- so, we
would not have been able to find those leaks anyway.

My attempts to try to use sanitizers all the way up through CGO layer were
not very successful either (my hope was that if this worked, then our go
tests would
have been able to trigger the leak).  It's possible to pass sanitizer flags
to "go test" (e.g. CGO_CFLAGS="-fsanitize=address"
CGO_LDFLAGS="-fsanitize=address" go test...).
Alas, that didn't work at all -- basically, for the sanitizers to work
*everything* must be using those sanitizers.  I was getting false positives
because some parts
of the dependencies (e.g. rocksdb) were not compiled w/ sanitizers and some
were.  In addition, it's not clear at all if this would actually work (Go
does have -msan mode for a reason:
there is a hookup to memory sanitizer there).

Going back to @Peter Mattis <peter@cockroachlabs.com>  point: it all boils
down to how much effort we want to expand on this:
   * Even on c++ side, the effort is not trivial: All build systems/make
files/cmake etc, for all of the c-deps must be wired to support sanitizers.
   * Sanitizers are only as good as your test coverage
   * Does not seem easy (or even possible w/ current version of Go) to use
those sanitizers across cgo boundary.

One of the ideas builk io team discussed is running a long term cluster --
a "customer cluster" that will not be restarted, but instead some workloads
will run against it
periodically.  If jemalloc information is exported, then at the very least
a spot comparison prior to releases could have revealed egregious memory
leak.

It is not clear (to me) if jemalloc profiling (and graphs) could have
revealed "minor" memory leaks.  If we slowly leaks few MB here and there,
release managers looking at those graphs
simply would not see a sharp increase and just assume things are fine.  In
reality, leaking anything in a long running cluster is not fine...

**Comment by mberhault** [comment]
I think there are two aspects here:
- running a sanitizer to detect memory issues during tests
- exposing jemalloc profiles more easily

Both are fairly complex and may not be worth it if pebble replaces RocksDB soon (eg: by the next major release).

I raised this issue mostly because obtaining jemalloc profiles is a bit arcane. I remembered they were doable mostly because I hooked up jemalloc to dump periodic profiles. The only other information is either in the logs when [periodic Go profiles start](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L168), or deep inside our wiki. Anyone else looking to profile CGO memory usage will need to dig around for a while. This would be made much simpler if CGO memory profiles were available alongside Go memory profiles (high-watermark profiler and Admin UI debug pages).

**Comment by petermattis** [comment]
To answer my own question: it looks like the [`opt.prof_active`](http://jemalloc.net/jemalloc.3.html#opt.prof_active) option for `mallctl` can be used to enable or disable profiling programmatically. This is an alternative to using the `MALLOC_CONF` env variable.  We should see what the perf impact is of always enabling jemalloc profiling and capturing "heap growth" profiles like we do for Go. Plumbing this through to the admin UI feels like a step too far for our anticipated usage, but simply gathering heap growth profiles feels like a good compromise between difficulty and benefit.

**Comment by petermattis** [comment]
@miretskiy Can I toss this your way? Re-reading the jemalloc docs again, I'm not sure if we can programmatically enable profiling, but docs can lie or be confusing. I think the only way to know for sure is to try. My thinking is to either extend `server/heapprofiler` to automatically grab jemalloc profiles as well, or to add a parallel `cgoheapprofiler`. See also `cli/start_jemalloc.go` which has code to write a jemalloc profile. Might be worthwhile to move that code into a utility library (`util/jemalloc`?). I believe `server/heapprofiler` looks for Go heap growth. The jemalloc version should look for cgo heap growth. See `server/status/runtime_jemalloc.go:getJemallocStats()`.

**Comment by miretskiy** [comment]
+1

**Comment by bdarnell** [comment]
> Re-reading the jemalloc docs again, I'm not sure if we can programmatically enable profiling, but docs can lie or be confusing.

From memories of a past life: you want to set a static `const char *malloc_conf = "prof:true"` (and then fight with linker order to make sure this is the one that jemalloc actually sees). This is cheap enough to be hard-coded to on (because it only samples a small fraction of allocations).

**Comment by miretskiy** [comment]
I doubt it makes sense to spend any time on this.
