### ISSUE TITLE
workload: deprecation warning for --init flag suggests cleanup necessary

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#42713]
Various roachtests (e.g. `kv*` and `ycsb*`) run `workload` in a fashion which emits a deprecation warning:

```
I191123 01:18:15.173627 1 workload/cli/run.go:326  DEPRECATION: the --init flag on "workload run" will no longer be supported after 19.2
```

Tossing this to you @danhhz in the hopes you either know how to fix it, or know who would know how to fix it.

Jira issue: CRDB-5331

**Comment by danhhz** [comment]
Yeah, having two ways to init a cluster (`workload init` and `workload run --init`) was confusing to new users of workload (both CRDB users and new engineers). The fix is to replace uses of `workload run --init` with a predecessor `workload init` call. A quick grep finds 12 cases, I'll send you a PR
