### ISSUE TITLE
cla-assistant: look into alternative to CLA assistant

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42795]
The CLA assistant glitch is supper annoying. Going to their website and clicking "Recheck PRs" doesn't seem to help. I have to push another commit, which is especially annoying for backports.

It would be great if we looked into an alternative to this thing.

Epic DEVINF-226

Jira issue: CRDB-5322

**Comment by kenliu** [comment]
We could run our own instance of this so that we have more control over it when it has issues (as per @bobvawter )

**Comment by kenliu-crl** [comment]
noting that https://github.com/cockroachdb/dev-inf/issues/52

**Comment by kenliu-crl** [comment]
cla-bot (https://colineberhardt.github.io/cla-bot/) looks like an alternative worth investigating. It's widely used by many OSS projects, doesn't require any separate login or database, and seems to be actively maintained.

**Comment by rail** [comment]
I was looking at another cla related issue today and found this cla checker as a [github action](https://github.com/cla-assistant/github-action).

It uses GitHub actions to check if the PR owner signed the CLA against a JSON file that lives in the main repo.

When you sign the CLA, it creates a commit.

I have mixed feelings about this approach:

*  the file is public
* CLA commits will trigger TeamCity builds (can we configure TC to ignore them?)
* It requires escalated permissions in order to commit the changes.

**Comment by rail** [comment]
https://github.com/cla-assistant/blockchain-services is another approach.
