### ISSUE TITLE
BACKUP/RESTORE should be extended to include users and permissions

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#42825]
Currently, backup/restore does not currently cover users/grants/permissions/etc, just the DDL and data in the table.  An extension of backup (similar to BACKUP CATALOG in other databases) to allow an administrator to restore users and permissions to a database or object after a restore would enable more seamless enterprise adoption and enable new disaster recovery scenarios.

Epic: CRDB-10881

Jira issue: CRDB-5318

**Comment by mwang1026** [comment]
This issue slipped through the cracks a bit--sorry. If you want to make sure we see it, best thing to do is file it under the Bulk I/O Backlog project. We do weekly triage.

We made some improvements here for 20.1 https://github.com/cockroachdb/cockroach/issues/44814

As far as auto-applying those on the restore, there's a bit of nuance there. For example, if you restore a database to 10 hours ago, and a user who had permissions at that time no longer has permissions, should you restore those grants? Or is that not too much of a concern because it's a big edge case-y?
