### ISSUE TITLE
1PC CPuts suffering from lost updates

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#42849]
When running as a 1PC, a CPut can erroneously miss to consider the last value on its key. This is because we mistakenly ignore a write too old condition in some cases. The ignoring happens here:
https://github.com/cockroachdb/cockroach/blob/c276b70cdff27b1bf4111f4b27b1459122804d70/pkg/storage/replica_evaluate.go#L344

An example of a bad scenario is the following:
- txnA starts at ts 10
- a Put of key a happens at ts 15
- txnA does a CPut that writes the key if there's nothing there, in the same batch as an EndTransaction
- the CPut evaluates at the "read timestamp" (so no key is seen) and so it erroneously succeeds, overwriting the first Put. A WriteTooOldError is returned from the CPut evaluation, which is turned into a WriteTooOld flag by `evaluateBatch()`
- the EndTransaction is the evaluated and succeeds, despite the WriteTooOld flag

The conditions under which this happens are:
- no reads before the EndTransaction batch. If there would be any reads, the EndTransaction would refuse to commit when the `WriteTooOld` flag is set on the txn at the end, insisting that the client refresh.
- no pipelined writes that are unresolved by the time of the EndTransaction. If there's any such writes, the EndTransaction moves the txn record to STAGING (instead of COMMITTED), and the erroneous ignoring of the wto condition doesn't kick in (by a happy accident)?

So in 19.2 this leaves mostly 1PC txns vulnerable. But in 19.1 I think the second condition above doesn't stand, so maybe the problem was even worse?

It would appear the bug was introduced in #38668, which was backported to 19.1.5.

Here's a test exemplifying the problem.

```go
func TestXXX(t *testing.T) {
	defer leaktest.AfterTest(t)()
	ctx := context.Background()

	s, _, db := serverutils.StartServer(t, base.TestServerArgs{})
	defer s.Stopper().Stop(ctx)
	keyA := "a"
	txn := client.NewTxn(ctx, db, 1 /* gatewayNodeID */, client.RootTxn)
	log.Infof(ctx, "!!! test starting txn: %s", txn.ID())

	if err := db.Put(ctx, keyA, "a"); err != nil {
		t.Fatal(err)
	}

	b := txn.NewBatch()
	b.CPut(keyA, "b", nil /* exp */)
	if err := txn.CommitInBatch(ctx, b); err != nil {
		t.Fatal(err)
	}

	val, err := db.Get(ctx, keyA)
	if err != nil {
		t.Fatal(err)
	}
	v, err := val.Value.GetBytes()
	require.NoError(t, err)
	log.Infof(ctx, "!!! val: %s", string(v)) // This will be "b".
```

**Comment by nvanbenschoten** [comment]
Discussed this with @andreimatei. The other thing that seems to be at play here is that `DistSender.splitBatchAndCheckForRefreshSpans` is not recognizing the `ConditionalPutRequest` and setting `EndTransactionRequest.NoRefreshSpans = false`, which would prevent this issue. This is expected, because `ConditionalPutRequest` doesn't require refreshing:
https://github.com/cockroachdb/cockroach/blob/45d709f1bb65c26573a7b42de13df15510c1a5ce/pkg/roachpb/api.go#L998-L1000

So one of these two things needs to give. Either we need to require a refresh on CPut/InitPut/Increment (maybe with an optimization to omit them when possible) or we need to re-introduce logic back into `evaluateBatch` to never swallow a WriteTooOld error when these requests hit one.
