### ISSUE TITLE
cli/dump: COMMENT ON missing

### ISSUE THREAD

**Issue by namibj** [cockroachdb/cockroach#42875]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
If a column has a comment (via `COMMENT ON`), the comment will be missing in the `cockroach dumo --dump-mode schema` output.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Create a schema with a comment ([the example in the docs](https://www.cockroachlabs.com/docs/v19.2/comment-on.html) will do)
2. Issue `cockroach dump --dump-mode schema <database>` | grep COMMENT
4. Observe the lack of output, which implies no comment was dumped with the schema.

**Expected behavior**
The schema is dumped with all comments.

**Environment:**
 - CockroachDB version v19.2.0
 - Server OS: Linux/archlinux
 - Client app cockroach dump

**Additional context**
What was the impact?

It silently swallowed my comments, which specified preliminary enum mappings for int2 columns. Thankfully it wasn't much.

**Comment by jordanlewis** [comment]
Thanks for the report!

@hueypark could I send this one your way, if you have some time?

cc @dt - dump counts as BulkIO, right?

**Comment by hueypark** [comment]
@jordanlewis Of course. It's likely that I will be able to create the first PR on December 15th. It seems appropriate to be implemented this on `crdb_internal.create_statements` in `crdb_internal.go`. Is that correct?

**Comment by namibj** [comment]
@hueypark It certainly looks like it.

**Comment by dt** [comment]
This reminds me that this is not the first time we've discovered a new SQL feature that was never added to SHOW CREATE TABLE when it was introduced, and the current setup is prone to such mistakes since we can only catch what we're written tests for. We should really have a test that can catch these when the new feature is introduced, e.g. something that verifies random schemas round-trip though `ShowCreateTable`. Maybe something along the lines of a) sqlsmith generate a random create statement from the grammar (maybe with a little help for be semantically correct w.r.t FKs), b) create a copy of that table using `SHOW CREATE TABLE` and then c) verify that the table descriptor for the original matches the copy (after blanking ID and timestamps).

**Comment by namibj** [comment]
@dt this sounds almost like fuzzing. If you can decouple it enough from the transactional layers, you might be able to fuzz directly for round-trip idempotence. Thnaks for adressing this.
