### ISSUE TITLE
sql: invalid string when converted to bytea

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#42881]
**Describe the problem**

:::BYTEA instead of ::BYTEA.

The former means "this is the type of value" the latter means "convert to this type" but when converting the value is first interpreted as a string and then converted to a bytea, and in this case, that string was invalid for some reason.

Seeing the following errors: 

```
client_test.go:84: pq: error in argument for $3: invalid UTF-8 sequence
client_test.go:87: key not found
client_test.go:90: value changed
```

**To Reproduce**

```
CREATE TABLE t1 (
bucket BYTES NOT NULL,
fullpath BYTES NOT NULL,
metadata BYTES NOT NULL,
CONSTRAINT "primary" PRIMARY KEY (bucket ASC, fullpath ASC),
FAMILY "primary" (bucket, fullpath, metadata),
CONSTRAINT check_fullpath CHECK (fullpath != '')
)```

The golang code and SQL that I've reproduced the error with looks like this.

```go
func TestUTF8(t *testing.T) {
pgConn, err := sql.Open("postgres", "postgres://root@localhost:26257/defaultdb?sslmode=disable")
if err != nil {
t.Error(err)
}

bucket := []byte{}
key := []byte("full/path/2")
oldValue := []byte{0, 255, 255, 1}
newValue := []byte{0, 255, 255, 4}

insertResult, err := pgConn.Exec("INSERT INTO t1 (bucket, fullpath, metadata) VALUES ($1::BYTEA, $2::BYTEA, $3::BYTEA);", bucket, key, oldValue)
if err != nil {
t.Error(err)
}
rowsAffected, err := insertResult.RowsAffected()
if err != nil {
t.Error(err)
}
fmt.Printf("ROWS AFFECTED: %d\n", rowsAffected)

q := `
WITH matching_key AS (
SELECT * FROM t1 WHERE bucket = $1::BYTEA AND fullpath = $2::BYTEA
), updated AS (
UPDATE t1
SET metadata = $4::BYTEA
FROM matching_key mk
WHERE t1.metadata = $3::BYTEA
AND t1.bucket = mk.bucket
AND t1.fullpath = mk.fullpath
RETURNING 1
)
SELECT EXISTS(SELECT 1 FROM matching_key) AS key_present, EXISTS(SELECT 1 FROM updated) AS value_updated;
`

row := pgConn.QueryRow(q, bucket, key, oldValue, newValue)

var keyPresent, valueUpdated bool
err = row.Scan(&keyPresent, &valueUpdated)
if err != nil {
t.Error(err)
}
if !keyPresent {
t.Error(errors.New("key not found"))
}
if !valueUpdated {
t.Error(errors.New("value changed"))
}
}
```

**Expected behavior**
Should work without having to change `::BYTEA` to `:::BYTEA`

**Environment:**
 - CockroachDB version 19.1

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4183](https://cockroachdb.zendesk.com/agent/tickets/4183) has been linked to this issue.

**Comment by rytaft** [comment]
I walked through this example with a debugger, and it looks like the placeholder is getting type string on this line in the type check code: https://github.com/cockroachdb/cockroach/blob/27b79e47c64f8a7745616d7e61818c19a5a95080/pkg/sql/sem/tree/type_check.go#L458.

The reason it gets set there is because `isUnresolvedPlaceholder` returns true. And the reason that function returns true is because there is no placeholder hint set in `ProcessPlaceholderAnnotations`. After [this line](https://github.com/cockroachdb/cockroach/blob/27b79e47c64f8a7745616d7e61818c19a5a95080/pkg/sql/sem/tree/type_check.go#L2298), the only placeholders that have a type hint are the ones outside the subquery. This makes sense, because `walkStmt` does not traverse into subqueries within a FROM clause.

Assigning this back to you, @rohany since it seems like this issue is in the type check code, not within the optimizer.

**Comment by rohany** [comment]
Ah i see. I couldn't figure out why a placeholder hint wasn't being set. I'll take another look at it, thanks for your help!

**Comment by rafiss** [comment]
I think this is fixed by https://github.com/cockroachdb/cockroach/pull/60949/
