### ISSUE TITLE
storage: prevent misuse of lease_preferences that don't match replica constraints

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#42902]
**Describe the problem**

It's currently possible to set `lease_preferences` in zone configurations that are not guaranteed to be satisfied because replication constraints are not sufficiently configured to ensure that at least one replica will end up in the preferred lease locality. This has come up a few times and is surprising to users (and to crdb devs) whenever it does. Lease placement is incredibly important for reliable performance, so we avoid making it easy to get this wrong. 

**To Reproduce**

```bash
# Create cluster.
export CLUSTER=local
roachprod create ${CLUSTER} --nodes=10
roachprod stage  ${CLUSTER} cockroach

# Start cluster.
roachprod start ${CLUSTER}:1 --args='--locality=continent=us,region=us-west'
roachprod start ${CLUSTER}:2-3 --args='--locality=continent=us,region=us-central'
roachprod start ${CLUSTER}:4-6 --args='--locality=continent=us,region=us-east'
roachprod start ${CLUSTER}:7-9 --args='--locality=continent=eu,region=eu-west'

# Set up ranges with zone configs
roachprod run ${CLUSTER}:10 -- './cockroach workload init kv --splits=1000 {pgurl:1}'

# Run SQL
> ALTER DATABASE kv 
  CONFIGURE ZONE USING num_replicas=3, constraints = '{+continent=us: 2}', lease_preferences = '[[+region=us-west]]'

# ...
# Not all leaseholders in us-west...

# Run SQL
> ALTER DATABASE kv
  CONFIGURE ZONE USING num_replicas=3, constraints = '{+continent=us: 1, +region=us-west: 1}', lease_preferences = '[[+region=us-west]]'

# ...
# All leaseholders in us-west!
```

**Expected behavior**

One of three things should be happening here:
1. lease_preferences should be taken into consideration for replica constraints. This would mean that `lease_preferences = '[[+region=us-west]]` implies an implicit `constraints = '{+region=us-west: 1}'`.
2. We should throw an error if lease_preferences are used without guaranteeing that a replica is in the locality that the lease is desired in.
3. We document this significantly louder than we do today. This is my least favorite solution but it's still better than the status quo.

I'd be interested to hear from @bdarnell, @tbg, and @darinpp about their preferences here. Remember to constrain the options to ensure that your preference is respected, or there's no telling which one we'll pick.

**Comment by tbg** [comment]
My initial reaction is that 2) is the most sensible option since it's relatively easy to implement. As we re-design the API (something we're thinking about, right? Nobody loves this use of yaml here) we should consider removing this pitfall. For example, if the lease preference were "annotated" in the constraints, syntax would prevent one from even falling into that trap. Bad strawman (that doesn't even cover the case of more than one replica in a region): `constraints = '{+region=us-west: LEADER}'`
1) looks like it'd catch weird semantics, too. if you have `{left: 1, right: 1}` and set a preference to `middle`, I guess we'd want that to actually update the config to contain `middle:1` but then which one do we take away? To maintain the rep factor, we'll need to remove one constraint. I don't think we'd do that, so it's an error already. Looks like something similar would always be a problem in the real world, so we should really just tell the operator that they need a constraint that allows for the lease to be placed where they want it.
