### ISSUE TITLE
sql: ROLLBACK both returns an error and executes

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4295]
```
root@:15432> select * from t;
query error: pq: retry txn "sql/executor.go:401 sql" id=adef9c17 key=/Table/53/1/114634185768599553/0 rw=true pri=0.00436543 iso=SERIALIZABLE stat=PENDING epo=1 ts=1455053984.406002621,1 orig=1455053984.406002621,1 max=1455053977.447547284,0
root@:15432> rollback;  
query error: pq: kv/txn_coord_sender.go:380: transaction is already committed or aborted
root@:15432> rollback;
query error: pq: there is no transaction in progress
```

The first `rollback` statement executes just fine. It shouldn't return that error.

**Comment by tschottdorf** [comment]
as discussed, the error in this concrete case is since the transaction times out at the coordinator between the select and the rollback (which translates into a kv-level abort).

I think that a SQL rollback should always just abandon the transaction instead of propagating the error to the client; it's not clear to the client what to do with it, and its state will indeed have aborted the SQL transaction. The swallowed error could be logged on the command line instead.

**Comment by tamird** [comment]
isn't this another case that would be prevented by #3108?

**Comment by andreimatei** [comment]
@tamird we need to swallow other KV error too, I think

**Comment by tamird** [comment]
Maybe.

**Comment by dt** [comment]
looks like this works on master now -- rollback has been refactored several times since this was filed, and has some test coverage too now.

```
root@:26257> update deletes set a = 5 where k = 399;
pq: retry txn "sql/executor.go:602 sql implicit: false" id=d119f0bc key=/Table/270/1/399/2/1 rw=true pri=0.01322776 iso=SERIALIZABLE stat=PENDING epo=1 ts=1457633424.432822193,1 orig=1457633424.432822193,1 max=1457633415.176377279,0
root@:26257> rollback;
ROLLBACK
root@:26257>
```
