### ISSUE TITLE
Introduce IMPORT TABLE IF NOT EXISTS syntax to gracefully handle existing table situation

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#43000]
**Is your feature request related to a problem? Please describe.**
Just as handling situations in creating a table that exists, it would be nice to also handle situations when an import job tries to run an import on an existing table instead of throwing a message `pq: relation "orders3f658466178611ea9f2facde48001122" already exists`

**Describe the solution you'd like**
Solution is to introduce `IF NOT EXISTS` option for `IMPORT TABLE` to silently handle the situation. 

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-5304

**Comment by C0rWin** [comment]
If no objections, I would like to pick this issue for my next contribution.

**Comment by markrofail** [comment]
If this issue is still up for grabs, I would like to work on it.

**Comment by jyz0309** [comment]
Hi,@dt @markrofail  I'm new to the community and Cockroach and would like to pick this up.Can I pick this issue? And if I can, can I get some help from you?

**Comment by markrofail** [comment]
@jyz0309 I am in the same boat as you. I was trying to pick this up in Hackroberfest and wasn't able to. Sorry to disappoint.

**Comment by dt** [comment]
Hey folks,

Sorry I haven't been as responsive as usual on this ticket. My bad.

We've been debating our long-term high-level plan for `IMPORT` and one theme there is that we want to reduce the overlap between what `IMPORT` and `CREATE TABLE` does: right now `IMPORT` can be instructed to create a table with a given schema, and then import data into it, but "create a table with a given schema" is what `CREATE TABLE` is for, and having to maintain two features that do the same thing isn't doing us any favors. That motivation means we may be moving to a world where we instead suggest users perform regular `CREATE TABLE` to make tables, followed by `IMPORT INTO` to load data into them instead of the single IMPORT command. If we did that, the IMPORT command is left to focus just its core purpose --- data loading, not schema manipulation.

In that context, this feature is actually a little tricky: it makes the data loading conditional _on the schema manipulation_ but those are exactly the two things we're trying to separate above. 

Perhaps the answer is to instead add an `IMPORT INTO ... IF EMPTY` option, so you could use the existing `CREATE TABLE IF NOT EXISTS...` feature and then run `IMPORT INTO... IF EMPTY` for idempotent data loading?

**Comment by jyz0309** [comment]
> Perhaps the answer is to instead add an `IMPORT INTO ... IF EMPTY` option, so you could use the existing `CREATE TABLE IF NOT EXISTS...` feature and then run `IMPORT INTO... IF EMPTY` for idempotent data loading?

Sorry that response too late...it means that I need to cancel the `IMPORT` schema manipulation, and just keep the data loading, and make the IMPORT become `CREATE TABLE IF NOT EXIST... + IMPORT INTO...`?

**Comment by bisakhmondal** [comment]
Hii all, I'd like to work on it.
Hey, @dt your comment totally makes sense. So the issue finally boiled down to work on this - 
> Perhaps the answer is to instead add an IMPORT INTO ... IF EMPTY option

, right?
Thanks
