### ISSUE TITLE
storage: BenchmarkMVCCReverseScan_Pebble fails on master

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#43122]
Git SHA: 44f7ccd

```
$ make bench PKG=./pkg/storage/engine BENCHES=BenchmarkMVCCReverseScan_Pebble
pkg: github.com/cockroachdb/cockroach/pkg/storage/engine
--- FAIL: BenchmarkMVCCReverseScan_Pebble/rows=10/versions=2/valueSize=512-8
    bench_test.go:250: failed to scan: 9 != 10
--- FAIL: BenchmarkMVCCReverseScan_Pebble/rows=10/versions=2
--- FAIL: BenchmarkMVCCReverseScan_Pebble/rows=10
...
```

**Comment by itsbilal** [comment]
The regression occurred with the changes to `skipEmptyFileBackward` in https://github.com/cockroachdb/pebble/pull/413/commits/8e84b1ff40b4616ff1fb27fa49ddd3184afe9d04

**Comment by petermattis** [comment]
@itsbilal Huh? Interesting. Are you on top of tracking this down?

**Comment by itsbilal** [comment]
Looking into it today. It's the if statement that sets the synthetic boundary in `levelIter.skipEmptyFileBackward`; removing the synthetic boundary code there fixes this.

**Comment by petermattis** [comment]
> Looking into it today. It's the if statement that sets the synthetic boundary in levelIter.skipEmptyFileBackward; removing the synthetic boundary code there fixes this.

I think we need to distinguish between a synthetic boundary at the beginning of the file and one at the end of the file. We're not currently doing so, and that seems very problematic. Should be easy to reproduce this badness in `testdata/level_iter_seek` test cases. Specifically, what happens if we create a synthetic boundary at the lower bound and then call `Next`? What happens if we create a synthetic boundary at the upper bound and then call `Prev`?
