### ISSUE TITLE
perf: investigate block_writer hiccups during splits

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4322]
After #4196 is fixed, performance is generally stable except that there is a 1-2/sec dip every time a split occurs. This is easily visible in the output of the `block_writer` and the log messages from the cockroach server. We should investigate if there is any low-hanging fruit to trim the duration of those hiccups.

**Comment by tschottdorf** [comment]
Reminder to myself: all system transactions should definitely be traced and
sampled once we have that stuff in place. It's currently a bit harder to
debug that since I don't have the `net/trace` endpoint hooked up right now
and we don't have the full machinery yet.

**Comment by mrtracy** [comment]
Note that this performance dip has alway been present in the block writer example; unlike #4196, it was not a problem that was introduced later.

**Comment by nvanbenschoten** [comment]
With the `net/tracing` stuff back in, I've been able to confirm that this latency is coming from the `splitTrigger` itself, which I've seen take up to **1.5 seconds**. Specifically, [copying](https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L1419) the original range's  sequence cache to the new range's sequence cache accounts for about 2/3 of this latency. The other third is coming from the statistic computations on the [original](https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L1409) and [new](https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L1434) ranges. 

I've discussed the first issue with @tschottdorf, which resulted in #4413. We should be able to drastically improve this cache copying time by keeping up with cache eviction whenever txns are resolved, instead of relying on the slow GC path from the `gcQueue`.

I'm not sure if speeding up the statistics computation is also a possibility. I was informed that @petermattis already ported this code to C++ to speed it up, so he might be able to shed more light on the issue.

**Comment by tschottdorf** [comment]
Should also double-check whether the stats computation reads the sequence
cache.

**Comment by petermattis** [comment]
The stats computation was moved from `MVCCComputeStats` to `RocksDB.ComputeStats` a few months ago which was a significant performance improvement. I'm not aware of any low-hanging fruit within the stats computation itself, though there is an additional optimization that could be done during split. Currently, we compute the stats on each of the new ranges. But we know ahead of time what the stat on the original range was. We should be able to compute the stats on only one of the new ranges and then derive the stats for the other range using some arithmetic. See `Replica.splitTrigger`.
