### ISSUE TITLE
storage/engine: experiment with enabling memtable bloom filters

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4323]
RocksDB has support for a dynamic bloom filter that can be used with the MemTable. See [memtable_prefix_bloom_{bits,probes}](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L708-L717). Enabling this option may provide a performance boost when checking to see if a key is present in the MemTable. I'm not sure if there are any side-effects or downsides to enabling, or what good values for those configuration options are.

**Comment by dt** [comment]
I tried with just adding memtable of 8mb or 16mb, then adding probe limits of 4, 6, and 8 to an 8mb memtable, then finally adding `bloom_locality`.

All the benchstats:
https://gist.github.com/dt/736ef6a7dbaf1c2becb6

Nothing looks like it made Bank or pgbench any faster (except the 8 probe claims a 10% gain on parallel pgbench), and most suggest a 5% slowdown on bank. Almost all see significant speedup on insert, with the up to 8% on 1k row inserts. Memtable alone sees slowdown on deletes, though adding probes = 8 seems to flip those to speedup as well. 

I'm not too encouraged, since Bank and pgbench don't see gains, but maybe those bulk-insert speedups are appealing.

**Comment by petermattis** [comment]
The parallel pgbench numbers look suspicious. Lots of variation between runs there. 

I agree that I'm not seeing any compelling speedup here. Let's put this on hold for now and we can revisit after the beta is out.

**Comment by petermattis** [comment]
I experimented with this as well and didn't see any compelling speedup. Closing for now.
