### ISSUE TITLE
sql: support unlogged table

### ISSUE THREAD

**Issue by apantel** [cockroachdb/cockroach#43352]
`CREATE UNLOGGED TABLE` is not supported by CockroachDB.

**Comment by jordanlewis** [comment]
We're never going to implement this, as CockroachDB's philosophy isn't compatible with tables that can lose data.

cc @awoods187 @vy-ton

**Comment by rafiss** [comment]
For the sake of compatibility with tools/drivers, it seems like we could support the `UNLOGGED` keyword but just ignore it. The docs about it indicate that it just means the table _might_ lose data on a crash. So it seems like it would be fine for our "unlogged" tables to just be normal tables.

> If specified, the table is created as an unlogged table. Data written to unlogged tables is not written to the write-ahead log (see Chapter 29), which makes them considerably faster than ordinary tables. However, they are not crash-safe: an unlogged table is automatically truncated after a crash or unclean shutdown. The contents of an unlogged table are also not replicated to standby servers. Any indexes created on an unlogged table are automatically unlogged as well; however, unlogged GiST indexes are currently not supported and cannot be created on an unlogged table.

**Comment by jordanlewis** [comment]
I think supporting modifiers like this is sometimes fine, but I think we should only really do it if we know of a tool that creates these automatically that doesn't have another workaround. If it's a matter of mimicking `UNLOGGED` just in case someone uses it, I'm less inclined to like the idea. Thoughts?

**Comment by rafiss** [comment]
That sounds fine with me. I've only seen this feature in tests so far.

**Comment by otan** [comment]
this is used by the osm2pgsql tool https://wiki.openstreetmap.org/wiki/Osm2pgsql, which is billed as "OSM data is perhaps the most popular GIS data that's used by organizations all over the world."

https://github.com/openstreetmap/osm2pgsql/blob/master/src/table.cpp#L89

**Comment by awoods187** [comment]
I think we need to reopen this based on geospatial

**Comment by ajwerner** [comment]
Part of the reason this is difficult in cockroach is that we’re a distributed database and all nodes will need to access the data. Where will the data go if we don’t replicate it using our normal replication protocols? If we want to expose access but don’t want to use the existing replication protocols, we’d need to invent new ones that can lose data. That’s quite a lift.

**Comment by andrewbaptist** [comment]
I think the ask here is a little different than what you mentioned. Specifically, this table would still be replicated, but it would never be written to disk. The whole transaction and raft machinery would still be there, but the raft log would be an in-memory log, and the pebble mem-table for this table would never go to the LSM. This requires a bound on the total size of the table (and probably in aggregate as well, since it is kept in RAM). 

There would be some complexity on "shutdown of the whole cluster" - but it would be reasonable to reset this table any time this is done.

I could see this being useful for "small memory tables" that are used for things like statistics
