### ISSUE TITLE
opt: incorrect index chosen with constant-folded ORDER BY expression

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43360]
**Describe the problem**
The user has two similar queries, one query completes in about 2.3s,  user was able to reduce this to 1s appears that the wrong index is being chosen, the other query if quick takes milliseconds. 

Here are both queries: 

This does NOT choose the correct INDEX,
AND IS very slow even WHEN the correct INDEX IS hinted:

```
SELECT id,
CURSOR
FROM
  (SELECT id AS id,
          created AS
   CURSOR
   FROM nodes
   WHERE ((created < '2019-12-11T22:30:17Z')
          OR ((created = '2019-12-11T22:30:17Z')
              AND (id < '')))
     AND organization = '62bcde19-d467-44b6-b693-c76e42a24421'
   ORDER BY CASE
                WHEN FALSE THEN created
            END ASC, CASE
                         WHEN NOT FALSE THEN created
                     END DESC LIMIT 21)
ORDER BY
CURSOR DESC;
```

 This chooses the correct INDEX
AND IS fast:

```
SELECT id,
CURSOR
FROM
  (SELECT id AS id,
          created AS
   CURSOR
   FROM nodes
   WHERE ((created < '2019-12-11T22:30:17Z')
          OR ((created = '2019-12-11T22:30:17Z')
              AND (id < '')))
     AND organization = '62bcde19-d467-44b6-b693-c76e42a24421'
   ORDER BY CASE
                WHEN FALSE THEN 'created ASC'
                ELSE 'created DESC'
            END LIMIT 21)
ORDER BY
CURSOR DESC;
```
Please describe the issue you observed, and any steps we can take to reproduce it:

You can find all the statistics and explains [here](https://docs.google.com/document/d/1O9cix4iOvMXKGhV4phB1KRFA7BKew1G2PW6FmBf9CFc/edit?usp=sharing)

**Expected behavior**

The users application UI uses this query to list all variety of info, so built into it is the ability to page forwards or backwards through the various tables, which accounts for the complexity of the case statement. It's used every time someone logs on, and at unpredictable intervals thereafter. It is critical for the application.  At the moment they have a workaround, however it would be nice to know why the original query was taking so long. 

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2

**Additional context**
Critical query for the users application.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4274](https://cockroachdb.zendesk.com/agent/tickets/4274) has been linked to this issue.

**Comment by RaduBerinde** [comment]
The second variant makes no sense. `'created ASC'` is just a string, it could just as well be `'foobarbaz'`. The inner ORDER BY expression is thus constant and it does nothing, and the query can just return any 21 rows. The right index gets chosen because of the outer `ORDER BY CURSOR DESC` (where `CURSOR` is an alias for `created`).

Looking at the [plan](https://cockroachdb.github.io/text/decode.html#eJzUm91ym0gWx6_NU5zyjaECmIYWX4m3VpbIjmZlKSvh7GRcLhUWxGEjgwvQZLxbWzXlZ_DlPl2eZAskFNAHgpaFNLpI7O7TB_p3PvqPCn90gtD1PR1a_vhr4FvjL-1LaLW68BvSeJEXgP5dlUcy5qbeV8__5nET15v-zt17Uxbupu4kAlFA2jlC50gEoaEjSRcwC_c-4pHII5GhqNbAaJoGmM3LrgGebzsh0NSJa8PH5qD1U3NAywIDvb4Jvetul6VOrIfH6dS14fq6007H_ODe8tx_W5Hre_l1s_lx4FiRY4PZuTKGZvPqg_lrMgVt433zumuC53-jGV3XMwYsdWK7oXU3cWy47Pe7i3tYLPpsTUKHpU4mVhiFjuNVde-HMDQHnd7fctsLxl_WDU8jP7LuQ_h52O9dpqOtfm9oDpqdngmnj4H7YAVPp_Bh0LlqDj7B341PQLs2NIcthqVOrnudf1wb0Om1jV9mnEdzlKOvzhPQKde5edYuizddBHQOenPYYqHAxTwCIysc59wBncYm8bDsc5Mb29nop22UcZTGbMnJIpQb7-Z986rT_ZTBTbv2Yuf5JSzM74mFNJNYSK_Agh-yEEebhTS4DMW8pahm1zQG83rwgzs3sib84_Ru4o75WXl0ej8bLROGZtPsDM1OawhnNxQAwH-Sf-PP6difTB-88FSHm8VgMuHap4uBWzazIA1QdKrDaVy1HEKcqIAo6YKsSwovyBgj7Y0g6IJwmllpu2HkeuNoNPanXrxakTRRyhh8ccPIH439ySh6enRi97P8zjrxrIdkZjSKYYxGubnpZLJwLmQmAv9b5qIKVpKp_7KlYczDtnciImrIhUDiZkaEQ0ENTXxNJPNd7z9JsKQIhUwyzfLwmZKt672zaTT-FNWTNrW980CFOA4PIu3p-wehaHJx0Rwehh_uvz6OHEF8qu8dQvEJe3gIFY9VFeItYx3JvCyrotIogUBFSBDrbpWqoAm4DqFBQkREDXVPQkNVsPKaSEiEBlmSYLW4VvYlNIiwEAsNEjb1Cw0iJkRCg4RHjUKDCASR0CABgWVBq_GUJauUakKDqD6OHEFloUECoUahUS8ESeUlJIvakaktFQmyWqfAqMJhnwJDQ-g1kewiMKogUZG85Rzdm8AgwbKzwKjC5gACg4RJDYWjIlEu_g7wWGDsJDKqIMGyrClH3lcJRUalGjlyBDup7yog6lTftXWJhi7IvKSJooJLdQlJKv6Cby9dAqEaBUc1InsVHPJmwUGAhFxwVE0SBR3oGw0SLDsKjmpsDiE4CJjs0FOr8ai1pxKA2EFsVAOBZbWhHTkMIrFRsT6OHAHhw3w1CLU-zBNAIDpWZR1LvKhoSEXlvhUXDyE0FLk-oVGNyB6FhiYg7TWRkAuNqkmiKPhQQqM6lh2FRjU2BxEa1ZnsIDSq8ahXaFQHsYPQqJgYgiAXF83hYRAJjYoYjhwBodCoBqFeoZFCoG7P3lKU8cuHbrPTA7r_wWTB6H1k4aMxuOwPDQaGRtdomeDaLIynQegH8H7QvwJ6MQ7N4Wx28XJuznD2Huo_fzIGBtCLN2_fwdmMlsghZIqiLgk6Un49Y6A_yJhdbDRr9trJG8vv4OyMYea_517CvYAzWbwb2w7SOBvLCofxnczdyZrEjRXZwaIlYiyi5JJtYwCXn6DVHBrxrfZm72uDGf-Y3ovRa89e9f1h1eubmyzbxrAF3c5VxwQRZS4xRxNPv6U4juOo0A8iCr6__O_7yx_fX_6AeRrq4No6mtvrOGdhBbbrWRM3etLhRgAORHSbNQgjKwp1uAn8b-HF0tzYDyMdEFJFmcdKQ8rOfXWedKARkx37bCdDHPcXGucm_MB2Ate714HL3d1jMPWceA07s39ZjPv_csbRPCU37nfGUMerdut3vWS1uvWVy6X7x7woCI0Vgx8QliaWSCzN5rc9n0z3PnEf3CjbVLZufz6OkI7Q-oWuFzmBZ024TCA22RaxKwdwI0WJ19QFxWKURTxZoHHyI9pknuzXibvm_SL3Qh1obuOKWWVlZ553ZP9cwEqRRMQrWMTq7ZaL_kCnyMvonssQfCYCubSqIG2WLDOpzW7zuilKbxAD9BvMAM3h9R7W94mszUoOzqOXCdf6JlLgpEIIVy4fx1FTNIWXVE3Utq8oCCaQRxSqBgteJ2LLIJ1JYdQKSy97cOtSmfiVq8Tkr2kSnUUjJjceC6V4TMiYSMwFms9I-Rm8ZjFmLoSCNHn-8V8i5-4D6yF2CyDAymfmvJSz3Ocdx3ElZU6FyCR5LTcEXsMYl4_B9vRe17eSzJbiJF86WrevL85cKUlf9o3EJr9z6Y_lc2pseTP5-tfiP0wrF7dXz_0Vr14YBZbrRTqc43PpHOlAnyd_W8jBeUZHw1xHy7yWfGYPJ2fn5fLoFm7WOVOqedlwSxW9lCu_TW1CE5DGNxqNhpxvE9nxTW1C5aXZZ2O_WPFSvl-sFmNDFnhFUtWCQ2b9-tI1uXQIZw4giS1Rkot17iRygnCLPeRvcv1T4XJOFD0artrmnw_hxp9GTnCRqHM2UyrhBX2Oq9XJlgLYktm3zLYcgDxRomfaxX6lld1Kenz_5Yu0XCG-hci9_xIxLHy2L9KeXrDTJbHn-t7GnFla8ZsVuNbdxNEXj9vpXvHyBV-ynVEHEVH_DwAA__9y2hbj) for the first variant, it looks like the problem is that even though we are constant-folding the expression, it remains a "synthesized" projection column, and it has no FD (equality) relationship with the original one.

**Comment by RaduBerinde** [comment]
This particular case is solved by adding the FD equality between the synthesized column and the input column. However, it doesn't solve similar cases where the input column is not projected; for that we need to make `CanProvideOrdering/BuildChildReqOrdering` code for Project a bit smarter.

**Comment by awoods187** [comment]
Nice work fixing this so fast!
