### ISSUE TITLE
ui: negative stats and incorrect range counts

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4347]
- Killing a cluster and restarting often changes stats and graph stats negative
- The number of ranges in the cluster does not update correctly, despite definitive splits

**Comment by petermattis** [comment]
@mrtracy Is this fixed now?

**Comment by mrtracy** [comment]
#4625 falls under this blanket, and probably accounts for the range count error; as for negative stats, i'll see if I can get a better reproduction.

**Comment by mrtracy** [comment]
Alright, here's the deal with negative values: I simply forgot how time series works.

For counters, every time series datapoint records the `cumulative` value of the counter at a certain time. When we want to convert that into a rate, the time series system computes the derivative as part of the query, something like `datapoint(t+1) - datapoint(t)`.

However, the counter value is kept in memory, and when the server restarts all counters are set back to zero. In this special case, the counter value actually _decreases_ from the perspective of the time series query.

This is encountered in all other time series systems, and they solve it by returning a _non-negative derivative_ instead of a regular derivative.  There is still some information loss during a server reset, but it will no longer result in an impossible negative rate. 

We can add this support on either the server or the client, but for the time being I think it will be faster to add on the client side.

**Comment by spencerkimball** [comment]
@mrtracy I haven't see this for a while. Has it been fixed?

**Comment by mrtracy** [comment]
It's still very much present, we need to be able to query a non-negative derivative for a time series (this is a feature present in most time series systems for exactly this purpose).

I used my free friday to do a refactor of the time series query system, which will solve this problem and a few others.  PR coming up for that.
