### ISSUE TITLE
sql: crash on bad descriptor keys

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#43616]
I've randomly gotten into a crash which seems to be caused by some database descriptor keys not looking like the code expects - it wants an int and apparently it found a tuple.

I ran into this when starting crdb for a first time on a different machine than my usual one, and so I think the data dir was from an older version. Indeed, the log has this line:
```
I191229 03:08:54.666339 614 sql/event_log.go:132  [n1,intExec=set-version] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:19.2-6 User:root}
```

This is the panic:
```
E191229 03:10:12.578038 2298 sql/conn_executor.go:729  [n1,client=127.0.0.1:49832,user=root] a SQL panic has occurred while executing "SELECT t.oid, CASE WHEN nsp.nspname IN ('pg_catalog', 'public') THEN t.typname ELSE (nsp.nspname || '.') || t.typname END FROM pg_type AS t LEFT JOIN pg_type AS base_type ON t.typelem = base_type.oid LEFT JOIN pg_class AS base_cls ON base_type.typrelid = base_cls.oid LEFT JOIN pg_namespace AS nsp ON t.typnamespace = nsp.oid WHERE ((t.typtype IN ('b', 'p', 'r', 'e')) AND ((base_type.oid IS NULL) OR (base_type.typtype IN ('b', 'p', 'r'))))": value type is not INT: TUPLE
E191229 03:10:12.578438 2298 util/log/crash_reporting.go:207  [n1,client=127.0.0.1:49832,user=root] a panic has occurred!
panic: value type is not INT: TUPLE [recovered]
	panic: panic while executing 1 statements: SELECT _._, CASE WHEN _._ IN (_, _) THEN _._ ELSE (_._ || _) || _._ END FROM _ AS _ LEFT JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE ((_._ IN (_, _, __more2__)) AND ((_._ IS _) OR (_._ IN (_, _, __more1__)))); caused by value type is not INT: TUPLE
```

I'm thinking this has something to do with the migration to the new namespace table? Although the migrations appear to have finished before the crash, as indicated by this line:
```
I191229 03:08:54.651290 41 server/server.go:1635  [n1] done ensuring all necessary migrations have run
```

Full log: https://gist.github.com/andreimatei/8c8805021faeece8e387be21cb2c4b5b

What I've done is `cockroach workload init kv` and then `cockroach workload run kv`. The latter crashed. Perhaps the newly created database from the `init` have something to do with it.

Doesn't repro when restarting the server - but then again the data has been migrated and the databases have been created. Haven't tried harder.

Any idea what's going on? Perhaps it's obvious to @arulajmani?

**Comment by andreimatei** [comment]
Actually, this happens every time I do `workload run kv`.
My data: https://drive.google.com/open?id=1RT81yc-N1IXzm0m7EnCDD8DhIYsRky0h

**Comment by solongordon** [comment]
I'm looking into this. Repro steps:
1. Start a v19.2.1 node to create a fresh data directory.
2. Restart the node with a bleeding edge binary.
3. Run `SELECT * FROM pg_type`.

**Comment by solongordon** [comment]
Confirmed that this issue appears as of #43203.

**Comment by solongordon** [comment]
OK, I think I see what's going on now. The new namespace table mimics the original one by having the `id` column in its own column family. This triggers the [legacy single-column encoding behavior](https://github.com/cockroachdb/cockroach/blob/master/docs/tech-notes/encoding.md#single-column-column-families) where we encode a single value rather than a single element TUPLE.

Normally we write to the namespace table using direct KV PUTs, which just write a single KV pair for the `id` column family. However, since the migration goes through the SQL layer, it also writes a "sentinel" KV pair for column family 0. When `GetAllDatabaseDescriptorIDs` encounters one of these sentinels, it chokes.

It should be easy enough to update `GetAllDatabaseDescriptorIDs` to ignore the sentinels. However, I don't think there's any good reason that the new table uses column families in the first place. (The old namespace table only had them for backward compatibility with format version 1 as far as I can tell.) I'm tempted to change the namespace TableDescriptor to use a single column family in order to avoid such complications in the future. This would break backward compatibility with HEAD but not with any alphas we have released.

**Comment by solongordon** [comment]
I've mostly talked myself out of messing with the namespace TableDescriptor, since it's a bit more complicated than I expected and has the backward compatibility problems mentioned above. I'll get a PR up for the quick fix shortly.

**Comment by danhhz** [comment]
Hey @solongordon mind pinging https://github.com/cockroachdb/cockroach/issues/43754 when this is closed?
