### ISSUE TITLE
util/log: stdlib log bridge always outputs to stderr

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4374]
This causes packages which have to use stdlib logging (e.g. `util/stop`, due to import cycles) to always output logs to stderr. See https://github.com/cockroachdb/cockroach/blob/master/util/log/clog.go#L1096. I don't see a particular reason for this behavior. The stdlib logging bridge should use the same log output as everything else.

**Comment by knz** [comment]
I am running into a conceptual problem. Currently errors logged via the bridge (e.g. generated by the Go library) are logged as INFO. However INFO does not show up on stderr by default, so a default startup would hide "interesting" error messages from the console.
I can see two ways forward:
- detect whether the message logged through the bridge contains the words "error" or "warning" and change the severity accordingly.
- pass all messages logged through the bridge with severity ERROR.

What do you think?

**Comment by petermattis** [comment]
Passing all messages logged through the bridge with severity ERROR would eliminate much of the benefit of not logging those messages to stderr. My thought is that we should leave the log bridge messages at severity INFO, but to revisit some of our `log.Warning` messages and elevate them to `log.Error`. In particular, the log message from `rpc/client.go` in #4466 seems like an ERROR, not a WARNING. 

The idea to detect messages with "error" and "warning" and change the severity accordingly is interesting, but also a bit magical. I'd prefer to avoid that approach if we can.

**Comment by knz** [comment]
OK but how do you suggest to deal with the TLS messages generated by Go's http library? I think we definitely want those to appear.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petermattis** [comment]
Update: `http.Server` has an `ErrorLog` field. We could set that field and direct the log messages to `log.Error`.

**Comment by knz** [comment]
Hmm I tried that and it's going to be difficult to implement without major reshuffling of `util`. 
The problem is that http.Server's `ErrorLog` must be a `log.Logger` which has its own set of formatter functions (Info, Warn, ...) on top of an `io.Writer`. To override this we must either

- implement our own `log.Logger` shim that redirects everything to our own `log` module; or
- implement an `io.Writer` shim that does the same.

However both are difficult to implement because they would depend on `util/log`, and then once we have them we must inject them into the `http.Server` in `util.ListenAndServe`, which because of dependency cycles cannot depend on `util/log`.

The "proper" thing would be probably to split our logger (clog?) in a back-end (with either an io.Writer or log.Logger interface) and front-end, and allow the back-end to be used anywhere including `util`.  
Does that sound about right?

**Comment by bdarnell** [comment]
Can we break the dependency cycle by moving `util.ListenAndServe` and related code to `util/netutil`? Now that the util/net.go is getting more complicated it would be good to put it in a place where it can use the same logging as the rest of our code.

**Comment by petermattis** [comment]
`util/clog` is using `util/encoding` unnecessarily. The dependency is easy to break and then `util.ListenAndServe` can use `util/clog`. I'll make that change. Might be worthwhile to create a `util/netutil` as well, but I'll leave that for someone else or for the issue to be forced for some other reason.

**Comment by petermattis** [comment]
Good grief, removing the dependency on `util/encoding` isn't enough. `util/log` also depends on `roachpb` for the `roachpb.{Node,Store,Range}ID` types. See #4449 for my opinion on this.

**Comment by petermattis** [comment]
The `roachpb` dependency doesn't need to exist either. It is needed for `util/log.AddStructured` which is so far unused in our code base. My opinion is we should remove it.

**Comment by tschottdorf** [comment]
Sgtm

**Comment by tamird** [comment]
Another alternative is to break roachpb's dependency on util. A cursory
glance suggests it's not so difficult.

On Thu, Feb 18, 2016 at 9:12 PM, Tobias Schottdorf <notifications@github.com
> wrote:

> Sgtm
>
