### ISSUE TITLE
A node can be overwhelmed with new learner replica requests

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#43750]
With the introduction of learner replicas, it seems that there is no way for a node to reject learner replicas that other nodes may want to put on it. Previously, with the snapshots, a node was able to reject snapshots and to limit the number of incoming replicas. In some cases we see rebalancing from a number of nodes to a single node (which happens to be the most underutilized at a given moment) which is immediately followed with a rebalanced from that node to some other nodes (as it becomes over-utilized). The fix may just be to give the destination node a way to reject requests for placing new replicas when multiple nodes do this at once.

**To Reproduce**

To reproduce, there has to be some sort of trigger that would case multiple nodes to initiate rebalance at once. #43749 is an example of one such trigger. If the trigger is present - the issue can then be observed. 

**Expected behavior**
In presence of a rebalance trigger, state after the rebalancing shouldn't lead to a need of a new rebalance. 

**Environment:**
 - CockroachDB version [20.1]
 - Server OS: [n/a]
 - Client app [n/a]

**Additional context**
What was the impact?

Unnecessary load and traffic in the cluster.

**Comment by tbg** [comment]
Can you confirm my rendition how this was avoided in the past? Say I have a 100 node cluster and I'm adding a node. Potentially all 100 nodes will see the empty node join and they'll all initiate a snapshot. Prior to learners, these snapshots were serialized at the recipient, even more so, since they were preemptive snapshots, any attempt to send a snapshot would be denied (and the sender would back off for, I think, a second). This would slow things down to the point where the senders' view of the recipients stats would be mostly accurate, avoiding the stampede.

With learners, there's no such direct throttling. All of the nodes may add one learner to the new node, giving it extra replicas. The snapshot will be a Raft snapshot, so they will all queue up at the recipient, none of them will get canceled. So the recipient will receive all 100 snapshots, one by one. At least by the time this first cycle is through, the senders should know that the recipient now has 100 replicas, so the size of the stampede is bounded by the number of nodes, but it's not great. But note that the stampede is "fine" if there are many more than size_of_cluster replicas that are supposed to be on that node ultimately. (As you pointed out).

The dirty fix is rejecting Raft snapshots directed to learners when another snapshot is inflight. The learner will be rolled back, roughly establishing the old order.
I don't particularly like this because it'll throw sand in the gears in more day-to-day situations. We've long had issues with slow or unpredictable rebalancing, and the rejection of preemptive snapshots was a misdesign playing a large role in that, and it's unfortunately that we've relied on its helpful side-effect in this one situation. It's quite reasonable for multiple nodes to send replicas to a new node in general. That this become a much smoother process with learners.

What really "should" happen is that once a node has decided that it should put a replica elsewhere, it goes to that node and requests a reservation. The result of the reservation returns the actual stats of the node (relevant to the operation) including all reservations. The sender can then confirm that it still wants to proceed with the replica addition. It's going to be really hard to make that happen in a way that doesn't further obfuscate that area of the code. Allocation decisions really should be made more centrally to address this class of issues.

Unfortunately lots of words but no good answer. I do really want to avoid regressing to the rejection of incoming replicas based on a semaphore. Making the rejection conditional on the fullness of the recipient seems like an answer, but it's going to be difficult to compute again (and to make reliable - possibly the sender *needed* to put the replica there, even though it violates some mean replica count).

Could you motivate the severity of this issues and the urgency to provide a fix? It's not clear to me if this is a smoldering fire affecting customers or if it's mostly a thicker papercut that we have time to address holistically.

**Comment by darinpp** [comment]
Mitigated by https://github.com/cockroachdb/cockroach/pull/44247 so closing for now.
