### ISSUE TITLE
backupccl, engine: re-enable Time-Bound Iterator in ExportToSST

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#43799]
TBI looks like it could be a big deal in getting to low-RPO via frequent incremental backups and indeed, is potentially even required to get there. On paper it sounds like the perfect solution, so what do we need to do to regain enough confidence in it and re-enable its use in BACKUP?

Context refresher: Within the current BACKUP/RESTORE feature offering, the way to reduce RPO is to backup more often. For this to work for more frequent durations, the cost of backing up what changed would scale with the size what changed as opposed to the total data size. This is exactly what the time-bound iterator optimization is supposed to deliver -- by recording the span of timestamps that appear in any given SSTable and then installing a filter to only open sstables that contain relevant times, we can ignore irrelevant data very cheaply.

However over 2017 and 2018, we encountered a few tricky correctness issues in the interaction of the time-bound iterator and our MVCC logic and handling intents, and generally lost confidence in this code, ultimately disabling its use in the scans used by BACKUP (though, as far as i know, we don't currently actually know of any remaining bugs in it, right?)
At the time, we did some tests that indicated that on a freshly made and populated cluster, backing up a day's worth of changes, it didn't have a particularly large impact, and was thus not enough to outweigh our general acquired distrust of it even thouhg we'd fixed all the known bugs.
However more recently we've heard from customers interested in RPO on the scale of a minute rather than a day, running in clusters that contain terabytes of data. Without TBI, generating incremental such backups looks very expensive -- potentially prohibitively so.

**Comment by petermattis** [comment]
I'm not aware of any remaining bugs, but the semantics of time-bound iterators are tricky due to the lack of a timestamp in deletion tombstones for the MVCC metadata key. The commentary around `IterOptions.{Min,Max}TimestampHint` doesn't capture the subtly that I vaguely remember.

@dt Do you recall if and where we documented the subtleties with time-bound iterators? If not, one of us will have to reconstruct that knowledge.

**Comment by dt** [comment]
I believe we currently handle not seeing the deletion tombstone for an intent resolution by using a non-time-bound “sanity iterator” that can seek directly to a key found via the time-bound one here: https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/incremental_iterator.cc#L55 and there is also a comment where it is called below that. I don’t recall/know of any other docs on it though.

**Comment by pbardea** [comment]
I don't have much context around the issues around TBIs but in trying to learn more about them I noticed this comment on this test: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/batcheval/cmd_refresh_range_test.go#L45 which mentions some trickiness around the intent resolutions not contributing to the SST's timestamp bounds.

**Comment by sumeerbhola** [comment]
Savepoints may have broken the invariant required to make `MVCCIncrementalIterator` work.
Say an ongoing txn wrote at ts=8, then at ts=10 and then rolled back the savepoint corresponding to ts=10. AFAIK, this rollback is know to the transaction but not immediately persisted. The intent timestamp (MVCCMetadata.timestamp) collected by the TimeBoundPropCollector is 10, and the provisional value is also at ts=10 (the value at ts=8 is only in the history inside MVCCMetadata).
An incremental iterator for the interval (..., 8] will miss this provisional value and the incremental backup at 8 will succeed when it should have returned a `WriteIntentError`.
@itsbilal to check if my understanding is correct.

This will again be viable with the segregated lock table #41720 since I think one can afford to scan the entire lock table, and if there is anything in the MVCCMetadata history that overlaps with the incremental iterator interval return a `WriteIntentError`.

**Comment by itsbilal** [comment]
@sumeerbhola your understanding is correct and thanks for coming up with the scenario, but the question is, should the backup return a `WriteIntentError` though? The transaction has been pushed forward, and will commit the value at ts 10. A rollback doesn't change the MVCC timestamp at which the key is written, just the sequence number. The MVCC timestamp for a provisional value can only be seen to move forward.

**Comment by sumeerbhola** [comment]
Sounds like we are good since `MVCCMetadata.Timestamp` continues to be a lower bound on the transaction commit time regardless of whether the provisional value is the correct one or not.

**Comment by dt** [comment]
So where does this leave us? Are we still pretty sure it is correct today? If so, what do we need to do to have enough confidence to turn it back on for incremental backup?

**Comment by petermattis** [comment]
@sumeerbhola You've been thinking more deeply about this than I have recently. Can you give a final verdict here?

**Comment by sumeerbhola** [comment]
I read the various issue threads and reread some of the code, and tried to construct a proof of correctness. Say `(t_s, t_e]` is the interval for `MVCCIncrementalIterator`.

- If one sees a key version `k@t` where `t` is in `(t_s, t_e]`, I think it is possible that the latest committed modification to `k` in this interval is `< t` (or no modification) and we incorrectly think that `k@t` is committed: the scenario involves `k@t` being previously a provisional value, then the range was deleted from this node and then at a different node `k@t` was delete because the transaction was aborted. Then this range is added again to this node with a range tombstone to delete all old data. The range tombstone may have deleted the intent but not yet deleted `k@t`. The incremental iterator is not going to see the range tombstone, so will see `k@t`.

- I am not sure that the fix made for https://github.com/cockroachdb/cockroach/issues/34819#issuecomment-472181236 is adequate. The sanityIter can be at `t1` where `t1 < t_s` and the normal iter observed `t2` where `t2 in `(t_s, t_e]`. So we would incorrectly ignore the intent at `t2` by using the sanityIter since it was constructed before the iter.

**Comment by sumeerbhola** [comment]
- The second example above is fine. The read latch on `t2` prevents a concurrent operation that writes to `t1 < t2` while the incremental iterator is being constructed.
- The only fix I have for the first example is to use the RocksDB/Pebble seqnum n from the latest tombstone when the range was added and tell the iterator to ignore all seqnums < n. This uses the fact that we use tombstones in a limited manner.
- I think there is another bad case which has nothing to do with range tombstones, and is due to the optimization that the intent is deserialized and included in the sst bounds only if it is the last entry in the sst: When a new value is proposed at timestamp t, the intent is at k@0 and the new value is k@t. The intent can be compacted down independent of k@t since it is a different key from the perspective of the storage engine. This loss of pairing means we can have intents within ssts that are not accompanied by their provisional value so could be missed. The segregated lock table would address this issue since we won't need to do such an optimization.

**Comment by petermattis** [comment]
What about the idea to perform table filtering as a two-step process:
1. Find an initial set of candidate sstables using the timebounds.
2. Expand the candidate set with any sstable at a higher-level than a candidate that contains the desired key range. 

I think this would be fix the range tombstone problem, though I haven't thought through what the implementation complexity would be. For 20.1, we'd need an implementation in RocksDB and I don't think RocksDB exposes enough information to do this currently.

@dt Something I'm not clear on is why incremental iteration needs to filter on the max timestamp. Can we restrict it to only filtering tables older than the min timestamp and then do the max timestamp filtering on a per-record basis? 

> The only fix I have for the first example is to use the RocksDB/Pebble seqnum n from the latest tombstone when the range was added and tell the iterator to ignore all seqnums < n. This uses the fact that we use tombstones in a limited manner.

This would be an interesting primitive. Could it replace time-bound iterator entirely? Imagine if `ExportToSst` returned the RocksDB/Pebble sequence number which is the max seqnum exported. We store this in a range-local key. The next `ExportToSst` for the range uses this sequence number to filter out sstables containing only older sequence numbers. The optimization would go away on leaseholder transfer, but if incremental backups are performed frequently enough, perhaps that doesn't matter. Lots of hand-waving here. This would be quite difficult to do as well, and not a candidate for 20.1.

**Comment by dt** [comment]
Does removing the upper-timebound dodge the above example issues? I think we'd be pretty okay with filtering key-by-key for the upper-bound given that a) that is usually going to be very close to no bound and b) there's a limit o how far behind that bound can possibly be (gcttl), whereas the lower-bound is the one that applies to potentially infinite cold old data.

**Comment by dt** [comment]
Could we use the same approach as a our current "sanity iterator" except use the non-filtered iterator to re-read _every_ key we (think we) read from the filtered iterator?

Essentially we'd `Seek(a)` on the table-filtered iterator, see that it lands on `k@t` so we then `Seek(k)` the non-filtered iterator? That way every key we emit is guaranteed to be one that a  normal, non-filtered iterator would see (since it did), but we potentially can still skip over lots of irrelevent keys with the seek? I guess the question is could this skip over a key that it shouldn't?

If we a) remove the upper time-bound and b) always include tables that don't have populated non-zero time props, would this be sound?

**Comment by sumeerbhola** [comment]
I think that will work.
The invariant that we have when using `(t_s, t_e]` in the current incremental iterator is that any version (committed or provisional) `k@t` where `t` is in that interval, that we should see with the non-incremental iterator, will have its sstable included in the incremental iterator.
Then the question is whether anything in the iterator after the choosing of the sstables will prevent it from being seen. There may be multiple sequence numbers associated with `k@t` but the latest sequence number will be seen (unless deleted by a range tombstone, which is a contradiction to the assumption that `k@t` is visible in the non-incremental iterator). So doing another read of `k`, starting from the intent (which we may have missed), using the sanity iterator should be correct.

**Comment by dt** [comment]
Recap from offline discussion today:
We think that this approach (using the normal "sanity" iterator for every key we emit, and only using the TBI key to find the keys to which to seek it) will work (leaving the max_timestamp in as-is), and identified three concrete tasks to get there:
1) update the c++ code to use the "sanity" iter to re-read every key and turn TBI on by default
2) optimization to use `Next` before `Seek` when iterating in tight lockstep
3) test(s) which manually constructs various combinations of SSTs with the various interesting cases to increase our confidence here.

The first one should happen ASAP for inclusion in 20.1 so it gets as much time to bake in stabilization period as possible. (2) ideally also wants to merge ASAP for similar reasons. 3) is a bit less time-sensitive and just needs to happen before release.

@petermattis do you have any preference on who (bulk-io vs storage) does 1) and 2) ?

**Comment by petermattis** [comment]
Will seeking the "sanity" iterator for every key be performant? An sstable iterator seek is about 30x more expensive than calling `Next`. So we'd have to be skipping a lot of data to make this worthwhile.

**Comment by dt** [comment]
Yep, that is what item (2) in that list is meant to address: if sanityIter and TBI were on the same key, after we `NextKey()` the TBI, we want to `NextKey()` the sanityIter once first, to see if it lands on the same key again, and only when it doesn't will we then switch to using `Seek` to catch it back up to the TBI, so in tight-loop lockstep case it should just be 2 calls to NextKey per key.

that said, even without that optimization, even if it is 30x slower to read a one key, the e.g. 10000000x reduction in the number of keys we need to read should more than make up for that, or at least that's the hope.
