### ISSUE TITLE
storage: filtering of "unremovable" replicas causes trouble for rebalancing

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#43835]
Let me describe a situation I've encountered, and ask better people what the problem is, if any (I suspect there is one).

A range with 3 replicas. The lease just transferred to, say, n1. The Raft leadership transfers too after the lease. Very soon after this lease transfer, n1's allocator wants to rebalance the range (say, to conform to some constraints). The rebalancing logic looks at what replicas are behind, and if enough of them are, then it refuses to rebalance. The determination of who's behind is based on the `raft.Status` that n1 has for the range. Since the Raft leadership has recently moved, a bunch of nodes are being probed and thus are in `StateProbe` in the `raft.Status`. This causes n1 to consider all these nodes as being behind, which in turn causes it to not rebalance.
The code that decides that we shouldn't rebalance when replicas are behind is here:
https://github.com/cockroachdb/cockroach/blob/4475b297079f93dc75fa08fbaa7ba3a93d539d44/pkg/storage/allocator.go#L710

I don't understand the reason for this replica filtering code, generally. What does replicas being behind have to do with rebalancing? I think it's trying to avoid some fragile configurations that I don't understand; perhaps someone does and can spell it out for me.
More narrowly, it seems unfortunate that a Raft leadership transfer causes this blip in rebalancing. However, there's a note in the code about the case where we're the lease holder but not the raft leader claiming that "it's better to simulate the removal with the info that we do have than to assume that the rebalance is ok"... I don't know what to make of that.

cc @darinpp @ajwerner @tbg @nvanbenschoten 

Jira issue: CRDB-5270

**Comment by petermattis** [comment]
Raft will prevent the removal of a replica that is a necessary part of quorum from completing until the replica is no longer a necessary part of quorum, which means that the removal will block other rebalancing operations. The necessary part of quorum part could be because there are only 2 replicas out of 3 or, as you discovered, because the leader hasn't determined how far behind its followers are. Why do we care how far behind the followers are? Because if we remove one of the up-to-date replicas we'll have a) left the quorum in a fragile state, and b) transferring Raft leadership to one of the behind replicas will take a while as we wait for the replica to catch up.

Some of this code was written before @tbg's Raft log fixing odyssey. It is possible it is no longer so important as behind replicas catch up quickly. Though I'm not certain of that. A behind replica might require a snapshot which could take 10s of seconds to send over a wide area network (or because we've increased the range size).

**Comment by andreimatei** [comment]
> The necessary part of quorum part could be because there are only 2 replicas out of 3

This part makes sense

> Why do we care how far behind the followers are? Because if we remove one of the up-to-date replicas we'll have a) left the quorum in a fragile state, 

What does "fragile" mean?

> and b) transferring Raft leadership to one of the behind replicas will take a while as we wait for the replica to catch up.

But why would we transfer leadership to a behind replica? If there's a quorum, then there's always *another* up-to-date replica. It seems to me that the relevant layers could make sure that the leadership ends up there.

**Comment by petermattis** [comment]
> What does "fragile" mean?

My memory on this is a bit dodgy and out-of-date and that might not have been the correct term. I think you can start with a fully caught up set of 3 replicas, and then replace one of the replicas. Now you have 2 up-to-date replicas, and 1 behind replica. If you transfer Raft leadership, the new leader doesn't know the state of the followers. You don't want to try and remove the up-to-date follower because doing so will have to wait until the behind replica is caught up. 

> But why would we transfer leadership to a behind replica? If there's a quorum, then there's always another up-to-date replica. It seems to me that the relevant layers could make sure that the leadership ends up there.

Which relevant layers? AFAIK, this is the relevant layer for making these sorts of decisions.

**Comment by nvanbenschoten** [comment]
>> What does "fragile" mean?

> You don't want to try and remove the up-to-date follower because doing so will have to wait until the behind replica is caught up.

Right, as long as a quorum of replicas are able to vote and Raft's config change rules are adhered to (e.g. never remove the leader), the range will eventually be able to make progress, but having to wait seconds to be able to perform writes is just as bad a temporary unavailability. So we want to do our best to ensure that there's always a quotum of up-to-date followers in the Range. If we don't have enough information to determine that on a new leader, then we'd rather not make any change.

**Comment by darinpp** [comment]
Like Andrei, I don't see why this is needed. Configuration changes require confirmation from the old and new quorums and can't commit unless there are enough up to date replicas. So if you have 2 up to date replicas and 1 behind, trying to remove one of the up to date replicas can only be committed if the replica that is behind catches up to the leader.

**Comment by petermattis** [comment]
This isn't a correctness issue, but one of rebalancing performance. If you have 2 up-to-date replicas and 1 behind and try to remove one of the up-to-date replicas, Raft will merrily accept the command, but it won't be committed until the behind replica catches up. This will block the `replicateQueue` from doing any other work during that time.

**Comment by nvanbenschoten** [comment]
> This will block the replicateQueue from doing any other work during that time.

It will also block foreground traffic to the range during that time.

**Comment by ajwerner** [comment]
The question at hand isn't necessarily how behind replicas combined with other failure scenarios might cause temporary unavailability, requiring snapshots. The question is how does the logic that exists make any sense. In what scenario is it helpful?

We know it is problematic in the scenario where there has recently been a raft leadership change. In that case we also know that there was a quorum of up-to-date followers as of the last committed log entry, by merit of the raft protocol. It is the case that upon a new leadership election that no quorum of up-to-date replicas exists. Namely consider the case where you have 5 replicas with 3 up-to-date and then 2 of the up-to-date replicas crash, including the leader. At that point an election will be held and the other up-to-date replica will be elected. At this point the new leader needs to catch up the remaining followers before commands can be appended. This seems to be the scenario of concern. That being said, the unavailability this would create is independent of configuration change.

> So we want to do our best to ensure that there's always a quotum of up-to-date followers in the Range. If we don't have enough information to determine that on a new leader, then we'd rather not make any change.

I hear your point but I'm not sure I understand the scenario which would lead to this temporary unavailability as it pertains to changing replicas. Can you help spell out a scenario that highlights your concern?

>This isn't a correctness issue, but one of rebalancing performance. If you have 2 up-to-date replicas and 1 behind and try to remove one of the up-to-date replicas, Raft will merrily accept the command, but it won't be committed until the behind replica catches up. 

While this seems sound, we never just remove a replica. In the old times, we would first add a new replica after sending it a snapshot and then remove a replica. In that case we had an even-numbered quorum. I'll buy that there are some edge cases that are somewhat hazardous w.r.t. temporary unavailability in the case of failure of another up-to-date node. In the new world, we're never going to remove a replica directly. We're upgrading a learner, which we ensure has received a snapshot just prior to the upgrade, and we're downgrading a voter to VOTER_OUTGOING. It is the case that for that config change to commit it need to be acknowledged on both the incoming and outgoing quorum but because the new incoming learner is likely up-to-date we shouldn't have a problem.
