### ISSUE TITLE
sql: empty SHOW CREATE TABLE output for temp tables

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#43852]
@awoods187 noticed that SHOW CREATE TABLE produces empty results for temporary tables.

```
root@127.0.0.1:54991/defaultdb> set experimental_enable_temp_tables=true;
SET

Time: 407µs

root@127.0.0.1:54991/defaultdb> create temp table t (x int);
CREATE TABLE

Time: 3.57ms

root@127.0.0.1:54991/defaultdb> show create table t;
  table_name | create_statement
-------------+-------------------
(0 rows)
```

**Comment by otan** [comment]
ok, similar to https://github.com/cockroachdb/cockroach/issues/43853

we seem to be trying to find a table in `pg_temp_<blah>` because the `ResolveDataSource` function thinks it belongs in there, but the information_schema is reporting it as `public`. how are we storing temp tables in terms of parents to the schema?
