### ISSUE TITLE
bulkio, sql: mutations with job IDs are persisted in backups and cause problems after restoring

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#44019]
When taking backups, we currently preserve the contents of `mutationJobs` and `gc_mutations` on the table descriptors, which contain job IDs for the schema change. This causes problems when restoring the backup on a different cluster, where jobs with those IDs don't exist.

For a simple reproduction (with `gc_mutations`), create a table with an index and drop the index, which leaves a job in the "waiting for GC TTL" state, and then take a backup of the table:
```
root@:26257/defaultdb> create table t (a int, index (a));
CREATE TABLE

Time: 10.054ms

root@:26257/defaultdb> insert into t values (1), (2), (3);
INSERT 3

Time: 3.78ms

root@:26257/defaultdb> drop index t@t_a_idx;
DROP INDEX

Time: 112.24ms

root@:26257/defaultdb> show jobs;
        job_id       |   job_type    |              description              | statement | user_name | status  |   running_status   |             created              |             started              | finished |             modified             | fraction_completed | error | coordinator_id
+--------------------+---------------+---------------------------------------+-----------+-----------+---------+--------------------+----------------------------------+----------------------------------+----------+----------------------------------+--------------------+-------+----------------+
  521128172017778689 | SCHEMA CHANGE | DROP INDEX defaultdb.public.t@t_a_idx |           | root      | running | waiting for GC TTL | 2020-01-15 16:34:57.023391+00:00 | 2020-01-15 16:34:57.048795+00:00 | NULL     | 2020-01-15 16:34:57.095392+00:00 |                  0 |       |           NULL
(1 row)

Time: 6.022ms

root@:26257/defaultdb> backup t to 'nodelocal:///backup';
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  521128953384796161 | succeeded |                  1 |    3 |             0 |              0 |    57
(1 row)

Time: 50.286ms
```
Inspecting the backup with `protoc --decode_raw` shows that field 33, which is `gc_mutations`, is preserved:
```
    33 {
      1: 2
      2: 1579106097092344000
      3: 521128172017778689
    }
```

 Then start a fresh cluster and restore the table, and do something to trigger the async schema changer on that table, like updating the zone config to change `gc.ttlseconds`:
```
root@:26257/defaultdb> restore table t from 'nodelocal:///backup';
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  521133970934759425 | succeeded |                  1 |    3 |             0 |              0 |    57
(1 row)

Time: 63.545ms

root@:26257/defaultdb> alter table t configure zone using gc.ttlseconds='10';
CONFIGURE ZONE 1

Time: 7.229ms
```
Eventually log statements like this will appearing several times per second (I tested this with a local 3-node cluster and a 1-node cluster):
```
I200115 17:39:13.936893 159 sql/sqlbase/structured.go:1516  [n1,scExec] publish: descID=52 (t) version=7 mtime=1970-01-01 00:00:00 +0000 UTC
W200115 17:39:13.938967 159 sql/schema_changer.go:1991  [n1] Error executing schema change: job with ID 521128172017778689 does not exist
I200115 17:39:13.943209 159 sql/sqlbase/structured.go:1516  [n1,scExec] publish: descID=52 (t) version=7 mtime=1970-01-01 00:00:00 +0000 UTC
W200115 17:39:13.945117 159 sql/schema_changer.go:1991  [n1] Error executing schema change: job with ID 521128172017778689 does not exist
```
I believe this is happening because `SchemaChanger.maybeGCMutations()` is getting called in a loop (from `SchemaChanger.exec()`), and it calls `Publish()` but never succeeds because the callback to update the job status on success can't find the job: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schema_changer.go#L789

I'm not sure why the attempt occurs multiple times per second, or how much of this is caused by retries inside `Publish()`/`PublishMultiple()` and how much of it is caused by retries in the `SchemaChangeManager`. The retries seem to happen more frequently on a 3-node cluster.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4358](https://cockroachdb.zendesk.com/agent/tickets/4358) has been linked to this issue.

**Comment by lucy-zhang** [comment]
So, the main problem is that we shouldn't be trying to back up table descriptors with job IDs (except in a full-cluster backup, where we'd also restore the jobs). We could stop backing up the mutations entirely, but we'd also have to handle in-progress schema changes correctly. I don't know how we would back up a table in the middle of a column backfill, for instance. cc @dt

The other problem is that we shouldn't be retrying in a tight loop (or maybe even retrying at all) if the schema changer can't find the corresponding job. I would have expected us to retry once a minute, in accordance with the usual schema change retry delay. Even if we get rid of the `SchemaChangeManager` and its retry mechanism in later releases, we will likely still have to backport a fix to handle existing cases where a schema change job doesn't exist.

**Comment by dt** [comment]
Yeah, I think this used to work -- in the sense that the schema change just picked up and continued to completion after a RESTORE -- when the table descriptors were their own jobs, before the schema change process integrated with jobs at all, but is broken and becoming more so as we move more to jobs.

I see a couple options:
a) refuse to backup a table with a pending schema change (outside of full-cluster backup). This seems like the easiest approach and the one where i'd have the highest degree of confidence in correctness but might not fly with users: backups run every X minutes automatically and failing because someone else ran a schema change could irritate operators. Maybe it is OK if/when full-cluster is the default, and doing something like backing up a single table is the exception that is okay to say "nope, that table is doing something else right now."?
b) nuke the mutation during restore, hope the rest works out? this seem like a quick fix but i'm guessing it sweeps some other problems under the rug.
c) follow the lead of whole-cluster backup/restore and collect relevant jobs during backup of specific tables and then restore those jobs along with the tables, to approximate the old behavior of picking up where we left off. This seems like the "right" answer but sounds like the most complex? at the very least, we'd need to rewrite any table ids in the job and ensure that that doesn't rot over time.

cc @pbardea

**Comment by pbardea** [comment]
With regards to option (b), I think this would be fine for index additions/deletions but am fairly concerned about the state of the cluster with a half-added column.

I'd agree that option (a) would be the easiest to implement, but I also think, as mentioned, that this would disrupt the ability to perform a backup quite a bit (especially if this fix is to be backported to 19.2 where there isn't even the concept of a full cluster backup).

A few other options may be:
(d) If the table is undergoing any column additions/deletions: disallow the backup. If the table is undergoing any index additions/deletions: remove these mutations from the descriptor and don't include the spans of the indexes being added/removed in the backup.
However, this still fundamentally faces the same challenges as option (a) as backups may not be allowed is someone is performing a specific schema change on a table.

(e) Same as (d) but instead of disallowing the backup when a column is added, attempt to remove halfway written column during RESTORE.

**Comment by lucy-zhang** [comment]
Per offline discussions, the immediate priority is to make backups with in-progress schema changes restorable again. The plan is to have RESTORE ignore any in-progress schema changes, by clearing the `mutations`, `gc_mutations`, and `mutationJobs` fields and omitting constraints in the `Validating` or `Dropping` states when restoring.

For tables with in-progress column backfills (due to either adding or dropping a column), this will result in KVs with columns that don't correspond to any column on the table descriptor. We're going to keep restoring these KVs as-is, and we'll need to rely on the row fetcher being able to handle those columns correctly, which is possible in principle. @pbardea is investigating and working on tests for this (possibly involving adding randomization to the logic tests).

This is basically option (b) described above, except that we ensure that KVs with values for abandoned columns are handled correctly. Once RESTORE is patched to handle these backups, we could decide to pursue option (c) at some later time.

@dt points out that once we fix RESTORE, thus fixing our correctness problem, we _could_ continue taking backups the way we do now (with mutations, job IDs, etc.), so that we have a complete snapshot of the table descs and KVs exactly as they are, and can decide to handle them differently in future implementations of RESTORE if desired.

**Comment by pbardea** [comment]
Update with regards to adding/dropping columns. Updating the fetcher to support extra columns does not seem like a superficial change after a bit of investigation. 

### The problem

This led me to further investigate the behaviour that we see when we BACKUP a table that was mid-way through a column mutation. In summary, after the RESTORE reads and writes to the table perform as normal since the mutations were also RESTORED. However, the mutations will not finish executing.

On 19.2 clusters, the corresponding schema change job (found in MutatiohnJobs) will not be found and the async schema change will fail to run this schema change silently. This becomes an issue when another mutation is applied to this table, as the abandoned mutation is first in line but can never execute. In practice, this means that all further schema changes will block on this table descriptor.

On 20.1 clusters, we run into a similar problem. Instead of the async schema change manager picking up the mutation and failing to find the job, there will simply be no job and the mutation on the table descriptor will be left there blocking other migrations from making progress.

### Solutions
1. The first solution was the one that was previously explored: updating the fetcher to support these columns and wiping the mutations upon RESTORE. The attempt for these PRs are #44710 and #44569. If after further consideration, the fetcher can be extended to support this, then those PRs may be re-opened and that should fix this issue. It would be nice if we could support this at the fetcher level as it would also make CRDB resilient in general to bad state caused by schema change issues (e.g.  failure during reverting).

2. The second solution would be to create the schema change jobs based on the mutation during the RESTORE. This would look something like the proof of concept I put up at #47588. From initial manual testing it looks like it works, and it should theoretically also work on 19.2, but I've not tried this yet.

Theoretically both these solutions should solve the problem on both 19.2 and 20.1.

**Comment by pbardea** [comment]
There has also been discussion where similar issues are encountered when attempting to roll back a DROP COLUMN. #47712 has part of that discussion.

**Comment by pbardea** [comment]
The conclusion from offline discussion is that RESTORE will synthesize these jobs. I am going to continue with #47588, and backporting this change should resolve this issue on previous cluster versions.
