### ISSUE TITLE
sql: drop table cascade on interleaved parents has strange behavior

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#44068]
When a table is an interleaved parent to another table or index, dropping the parent with cascade doesn't actually drop the child table or index. It instead just deletes all data in the table or index and leaves it accessible.

**Comment by lucy-zhang** [comment]
This is even worse for for secondary indexes interleaved into primary indexes of other tables not in the interleave hierarchy. The index gets "truncated" but the primary index does not:

```
demo@127.0.0.1:53495/defaultdb> create table t1(a int primary key); insert into t1 values (1);
INSERT 1
demo@127.0.0.1:53495/defaultdb> create table t2(b int primary key, a int); insert into t2 values (1, 1);
INSERT 1
demo@127.0.0.1:53495/defaultdb> create index idx on t2(a) interleave in parent t1(a);
CREATE INDEX
demo@127.0.0.1:53495/defaultdb> drop table t1 cascade;
DROP TABLE
demo@127.0.0.1:53495/defaultdb> select * from t2;
  b | a
----+----
  1 | 1
(1 row)
demo@127.0.0.1:53495/defaultdb> select a from t2@idx;
  a
-----
(0 rows)
```

I think we should prioritize fixing this. @rafiss thoughts? I made the mistake of not realizing how serious this bug is and had neglected Rohan's PR (#44080) earlier, but I think it's definitely worth rebasing and cleaning up.

@pbardea is working on something to just fix the references in #55466 (which I think is meant for backporting to 21.1), but now I'm wondering if we should just backport the fix to drop the tables/indexes entirely. It would be a behavior change, but since we already clear all the data, maybe it's fine if we also just remove the tables/indexes as well.

**Comment by rafiss** [comment]
@lucy-zhang I don't think Rohan's PR can easily be rebased anymore. Do you still think it's important to get to this issue?

**Comment by lucy-zhang** [comment]
I doubt we're going to get to it in 21.1, and past that point there are diminishing returns since we're deprecating interleaved tables. Closing because we're not going to take action.
