### ISSUE TITLE
sql: excessive memory usage in SHOW JOBS

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#44166]
When running `SHOW JOBS`, we see high memory utilization in the cluster. Specifically a backup job's payload may be ~5MB. Consider a backup that is run every hour and `jobs.retention_time` is set to the default 336h, this may lead to 5MB * 336 hours * 1 backup / hour = ~1.7GB of memory utilization when `SHOW JOBS` is run. There are 2 factors at play:

1. The internal executor has a lack of memory accounting for memory in the rows it return after the query is executed.
2. The backup job payload may need to be re-evaluated. Previously, the entire backup descriptor was thought to be a good description of the job that's running but as we add more information it may make sense to trim the job payload to include only a subset of the backup descriptor's fields.

A short term remediation would be to set the `jobs.retention_time` cluster setting to something closer to 48h.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4423](https://cockroachdb.zendesk.com/agent/tickets/4423) has been linked to this issue.

**Comment by tbg** [comment]
For context, the code in which the above happens is

https://github.com/cockroachdb/cockroach/blob/26a612ad46e693b308e7237d6442b1e61e45018e/pkg/sql/crdb_internal.go#L456-L466

We see that there's no pagination and no memory accounting (above the InternalExecutor). Additionally, all of the rows that are to be returned are buffered in-memory:

https://github.com/cockroachdb/cockroach/blob/6cd0e025a1f71de84d894c58bdb282b5c53fa2d4/pkg/sql/virtual_schema.go#L270-L288

`debug zip` is also affected by this (since it slurps all of the crdb_internal tables).

It seems that `InternalExecutor` should take a bytes monitor (right now it just uses https://github.com/cockroachdb/cockroach/blob/90f5b694a62cbda84badc9e87849cdf927ed4930/pkg/sql/internal.go#L61-L63) but until consumers paginate/stream properly this will lead to errors (instead of excessive memory usage).

**Comment by jordanlewis** [comment]
It would be great to consider removing the "slurp" API from the internal executor and force users to paginate. Otherwise, this will probably happen again and again in different contexts.

**Comment by pbardea** [comment]
+1 to Jordan's comment above, just going to note that #44180 helped resolve the issue we were seeing in the long term, but I'm going to keep this issue open to track the need to update the internal executor for a more robust solution.

**Comment by spaskob** [comment]
I want to try to add a fix for this for 20.1. What will be practical approach that would take a up to a week to implement? I am not looking to solve this long-term for now.

**Comment by tbg** [comment]
@jordanlewis is it prohibitively complex to change `addRow` to stream out changes to the consumer? I know we start streaming rows back for regular larger SELECTs, wondering how much gets in the way of doing the same for virtual tables. If we have that, pagination is all we need here. Short of that, I don't have a good idea here other than just doing pagination and stopping it once X mb of data have been buffered... or perhaps we can give the `virtualDefEntry` a row container that can spill to disk?

**Comment by jordanlewis** [comment]
It shouldn't be too hard. I talked about it offline with Spas and forgot to record the results here. We can add another implementation of a results interface that sends rows over a channel, which in the case of internal queries shouldn't be too performance limiting.

In the case of the jobs table, I thought we didn't need to worry about adding pagination to the virtual table because it's a real table, but maybe we're reading from some view that gets fully slurped into memory first. Either way we have infrastructure to deal with that now - there's just a different iterating vtable interface to implement. (vagaries due to typing on phone at the moment)

**Comment by spaskob** [comment]
@jordanlewis Thanks, do you mind adding the code links that you showed me back when we discussed offline.

**Comment by spaskob** [comment]
I am going to punt on this for 20.1. It is harder than just adding a steaming API to `internal_executor`. I have a PR in progress that I will merge once in 20.2.
I have discussed this with Jordan and David and we think short term the problem was resolved by Paul's fix to not save `BACKUP` stats in the job row and we should fix this long term but it is not important for 20.1.

**Comment by ajwerner** [comment]
> The internal executor has a lack of memory accounting for memory in the rows it return after the query is executed.

The internal executor has a lack of memory accounting also while it's executing. We should fix that too.

**Comment by joshimhoff** [comment]
See https://github.com/cockroachlabs/support/issues/370 for another instance of this hitting a prod CC customer. Will add more details there soon.
