### ISSUE TITLE
Incorrect result for query with IS NULL condition on UNIQUE column and VECTORIZE=experimental_on

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44207]
Consider the following statements:

```sql
SET SESSION VECTORIZE=experimental_on;
CREATE TABLE t1(c0 INT);
CREATE TABLE t0(c0 INT UNIQUE);
INSERT INTO t1(c0) VALUES (0);
INSERT INTO t0(c0) VALUES (NULL), (NULL);
SELECT * FROM t0, t1 WHERE t0.c0 IS NULL; -- expected: two rows are fetched, actual: one row is fetched
```

The query fetches one row, although it is expected to fetch two. When removing the `UNIQUE` from `t0.c0`, the query works correctly. It also works correctly when `VECTORIZE` is not set to `experimental_on`. The following query demonstrates that the predicate evaluates to `TRUE` for two rows:

```sql
SELECT t0.c0 IS NULL FROM t0, t1; -- {TRUE, TRUE}
```

I found this issue based on commit `c76ad970e73e606bc55a372d93f9d2d6acb32c9c`.

**Comment by asubiotto** [comment]
Looks like this is the plan:
```
root@127.0.0.1:52729/movr> EXPLAIN (VEC, VERBOSE) SELECT * FROM t0,t1 WHERE t0.C0 IS NULL;
                text
-------------------------------------
  │
  └ Node 1
    └ *colexec.Materializer
      └ *colexec.hashJoinEqOp
        ├ *colexec.simpleProjectOp
        │ └ *colexec.CancelChecker
        │   └ *colexec.colBatchScan
        └ *colexec.simpleProjectOp
          └ *colexec.CancelChecker
            └ *colexec.colBatchScan
```
And the root cause lies in the `hashJoinEqOp`. The equality columns are empty and for some reason only one result is returned (maybe because we don't follow the next chain). The inputs to the hash joiner are correct (right/build side is nulls). My hunch is that empty equality columns are probably not handled well by the vectorized hash joiner. I'm not very familiar with this code. @yuzefovich, since I think you are, would you mind taking a look?
