### ISSUE TITLE
sql,ui: enable users to see "their" jobs in crdb_internal.jobs and admin UI

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44335]
This issue is related to #40991.

Today `crdb_internal.jobs` and the Jobs Details page in the Admin UI are both restricted to use by only admin users. The rationale is that the job details contain privileged information over arbitrary tables and we don't want non-admin users to peek into things they don't have privilege over.

However conceptually it's reasonable for a user to want to see "their" jobs, operating on tables they do have privilege over.

We can actually choose two levels of visibility:

1. visibility over their *personal* jobs, i.e. for which the `Username` field in the job payload is exactly that of the querying user.

2. visibility over the targets of the job, i.e. verify that they have privilege over _every_ descriptor listed in the `DescriptorIDs` field.

It seems to me that the bare minimum is (1), and that (2) would be convenient but would incur a potentially expensive join with the descriptors table.

**Comment by knz** [comment]
cc @spaskob for consideration

**Comment by spaskob** [comment]
This makes a lot of sense. I will take this into account when redesigning jobs. What is the expected timeline for this feature?

**Comment by dt** [comment]
I don’t think we should do (2) — I think showing a non-admin another user’s jobs is a bit weird and we should behave like `show queries` — non-admins only see their own stuff.

**Comment by knz** [comment]
I think (1) will be necessary for 20.1 because of a customer ask.
This is related to #40991. Please ping @solongordon and @BramGruneir who will confirm and provide details.

**Comment by knz** [comment]
sorry I meant ping Solon and @dbist

**Comment by awoods187** [comment]
I'm a big fan of providing this visibility.

**Comment by knz** [comment]
I'm going to give a shot at just (1).

**Comment by knz** [comment]
Here's a reason why (2) is important: roles: If a set of users Alice, Marie, Joe are part of the same role "users who can access tables in database MyApp".

Then arguably they should be able to view each other's jobs, at least those concerning schema changes, without being cluster-wide admins.

**Comment by dt** [comment]
Sure, but I think the key part of that is "arguably" - while I think it is probably OK to see a pending index being added to a table you can see since you'll be able to see it when it is done anyway, I don't see why you should see another user's BACKUP, or, even more so, consider an EXPORT job (turning it into a job is a backlog item). Plus, if the tentative 20.2 work happens to make more schema changes fully transactional (hidden outside their SQL txn), showing even just schema changes to a different user no longer even seems so cut and dried.

I think we should really be looking at the model of `SHOW QUERIES`: Just since we both have permissions on the same table does _not_ mean you suddenly get to see my running queries. Doing something similar but subtly different in `SHOW JOBS` seems ripe for confusion and accidental leaks.

**Comment by knz** [comment]
Good points, let's just make sure these arguments are properly captured and documented when users eventually reach to support to ask these questions.

**Comment by knz** [comment]
Feature (1) is done in #44345 and will be there in 20.1

I'm going to close this issue with the understanding that (2) is undesirable as per the conversation above.

@jseldess the doc work for #44345 should include a proactive explanation of why we don't allow more flexibility, so that users don't come to us with that question.
