### ISSUE TITLE
sql: missing KV when primary key column not in column family 0

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#44450]
Create a table where the primary key is not in the first column family:
```
CREATE TABLE t (a INT PRIMARY KEY, b INT, FAMILY (b), FAMILY (a));
INSERT INTO t VALUES (100, 200);
```
Now examine the corresponding KVs:
```
$ cockroach debug rocksdb scan --value_hex --db=cockroach-data | grep '^/Table/52'
/Table/52/1/100/0/1580226164.547421000,0 : 0x68B150E90A239003
```
We expect a KV for each column family, but there is only one for column family 0.

I'm not sure if this breaks any existing behavior, but it causes issues if we make our "needed column family" logic smart enough to not always include column family 0.

**Comment by solongordon** [comment]
It turns out this is "working as intended" to a degree. Since `a` is encoded into the key, it can be decoded from column family 0 (or any column family), so we skip writing an empty KV entry for the second column family.

This makes sense but I also find it hard to reason about. It used to be you could assume a column family had a KV entry if any of its columns was not null. Now there are more caveats: it has an entry if any of its columns is not null AND value-encoded. And when is a column value-encoded? If it's either not indexed OR composite. Oh, except for secondary indexes, where composite values are always stored in column family 0.

It's also confusing that the table definition above specifies two column families but one of them will never have KV entries, so it's functionally equivalent as not specifying any families at all. This seems to undermine what the user was originally trying to express. I also wonder if it limits our ability to reduce contention by scanning the two column families separately.

@nvanbenschoten do you have any opinions here? Is it worth the extra complexity here to avoid writing unnecessary KV entries?

**Comment by nvanbenschoten** [comment]
Does the second column family make it into the TableDescriptor? I thought we had some validation that columns in the primary key need to be in the first column family.

**Comment by rohany** [comment]
We relaxed that restriction in order to allow primary key changes on tables with multiple column families, because the primary key change could result in the new primary key not being in family 0.

**Comment by nvanbenschoten** [comment]
Got it. So then I'm confused why we don't write this extra key. If the first column family contained only the primary key (e.g. `CREATE TABLE t (a INT PRIMARY KEY, b INT, FAMILY (a), FAMILY (b));`) then wouldn't we write an empty sentinel column family? Why is this case any different?

**Comment by rohany** [comment]
That was just how the code was written originally -- if a family's value is empty and the family is not the sentinel family, then no k/v is written as a space optimization.  This can be changed if that doesn't make sense though.

**Comment by nvanbenschoten** [comment]
How does the "sentinel family" relate to the column family containing the primary key? I don't think there is a relationship anymore. In fact, it looks to me like the PK can now even be split over multiple families.

So it seems like we have two options:
1. we always write both the sentinel column family and every column family that contains a key-only-encoded column.
2. we recognize that key-only-encoded columns that are NOT NULL do not imply the existence of a key-value on their own, if that key-value is not the sentinel family.

I'd lean towards option number 2 because it is a big deal to write superfluous KVs for a variety of reasons including write amplification and the potential for doing so to create synthetic contention. I'd also lean towards option number 2 because I think that logic, while complex, can be more locally centralized and tested in isolation. You two know the code better than I do though, so I'll defer to your judgment.

**Comment by nvanbenschoten** [comment]
> It's also confusing that the table definition above specifies two column families but one of them will never have KV entries, so it's functionally equivalent as not specifying any families at all. This seems to undermine what the user was originally trying to express.

This stumped me too, but I think it can still make sense if the column families are considered properties of a table instead of properties of a specific index*. In that case, the key-only-encoded column may end up as a value-encoded column in a different secondary index.

\* I'm not sure what the current state of this change is.

**Comment by rohany** [comment]
We had originally thought about making column families index level properties, but got a lot of pushback due to the complexity. Since they are table level properties, what you said can and will happen.

**Comment by solongordon** [comment]
Helpful to know that the cost of superfluous KVs can be high. And good point that the column families can have an effect on secondary indexes even if not on the primary one. I'll go ahead with handling the thornier logic in `NeededColumnFamilyIDs` for now. Thanks Nathan.

**Comment by solongordon** [comment]
Considering this "working as intended" for now.
