### ISSUE TITLE
util/log: remove proto-encoded logs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4449]
Use normal textual logs instead. We're not displaying debug logs in the admin UI anymore, nor do I think we want to in the future. The proto-encoded logs add a hurdle to debugging since they must be viewed with `cockroach log`.

@spencerkimball I imagine you have an opinion about this.

**Comment by BramGruneir** [comment]
We still do display the logs in the admin UI.  @maxlang ?
But I agree that requiring `cockroach log` is an unneeded setp

**Comment by petermattis** [comment]
Eh? I was looking for the logs in the admin UI and unable to find them. Where are they now?

**Comment by BramGruneir** [comment]
http://localhost:26257/#/logs/1?level=INFO
Still works, but you have to have the logging to disk turned on.

No links to it right now.  Not sure what the plan is.

**Comment by spencerkimball** [comment]
I made that the default because for a little while there was a push to encode the semantic details of request contexts in the logs. That might still be a good idea and you'll be just tossing out a decent amount of work. Why fix what isn't broken?

How about adding human readable debugging string at the top of the log file indicating that you should run the log file through `cockroach log $filename`?

**Comment by petermattis** [comment]
I wasn't proposing to toss out the work, just to make the log files textual by default. I don't think we should be exposing our debug logs in the admin UI which is one motivator for the proto-encoding. And we're not currently using the structured logging so the normal use case of trying to view the logs is being obstructed for no benefit.

**Comment by petermattis** [comment]
Discussed with Spencer offline and he agreed it is fine to output text logs by default. So I'll be moving forward with this.
