### ISSUE TITLE
docs: how to add cert for a second node?

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#4450]
Given that the basic cert establishment directions are these three commands

~~~
cockroach cert create-ca
cockroach cert create-node 127.0.0.1 [::1] localhost  123.123.0.54
cockroach cert create-client root
~~~
how does one add the certs for a second node?  The above makes a cert for 54.  I tried to make one for 55 and get:
~~~
$ ./cockroach cert create-node 127.0.0.1 [::1] localhost    123.123.0.55
Error: failed to generate node certificate: security/certs.go:90: error creating certificate: open certs/node.server.crt: file exists
Failed running "cert"
$
~~~

Are we supposed to reuse the one cert for all nodes?  If I'm running in cloud I won't know the IP addresses before the machines are spun up.

latest version of cockroach / amd64 /linux / go1.5.3
33d0fa2238fcd02afacb66f4e27d1e0a40ed5fe2

**Comment by mberhault** [comment]
You should definitely generate one set of certs per node. With the current code that uses fixed file names by user, this means that you should copy the node certs (and ca.crt) to a node, then delete the node certs from your machine before generating the next ones.

This will soon change to have more explicit arguments for the key and crt files (eg: `--crt-file` and `--key-file`, more in line with other tools out there), so this will become less of an issue.

As for IP addresses, I'm not sure what the issue is. There would be little point in generating the cert before spinning up the machine as you'll need to copy them over anyway, so might as well do it once the machine is up and reachable, at which point you should know its IP address.

Ultimately, cert deployment is rather annoying because basic security practices say that:
* the ca key should be on a very secure machine (the one generating certs) and nowhere else
* node keys should only be on the nodes (and even password protected, although we don't support that right now)

**Comment by mberhault** [comment]
Almost forgot the most salient point: the initial version of the docs is being finalized and will include detailed steps (eg: shell commands) for a secure multi-node cluster. The basic requirement will be ssh access to each node (meaning they must already have been created).

**Comment by jseldess** [comment]
@glycerine: Docs should cover this now. See:
- [Start a Local Node](https://www.cockroachlabs.com/docs/start-a-local-cluster.html)
- [Manual Deployment](https://www.cockroachlabs.com/docs/manual-deployment.html)
- [Start a Node](https://www.cockroachlabs.com/docs/start-a-node.html) (docs for `cockroach start`)
- [Create Security Certificates](https://www.cockroachlabs.com/docs/create-security-certificates.html) (docs for `cockroach cert`)

Feedback welcome in the [docs repo](https://github.com/cockroachdb/docs/issues)!
