### ISSUE TITLE
jobs: perform exponential backoff to reduce impact of jobs that cause panics

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#44594]
**Is your feature request related to a problem? Please describe.**
This bug leads to panics when users run the IMPORT INTO job on 19.2.2: https://github.com/cockroachdb/cockroach/issues/44252.

The impact can be very high. See this graph of the SQL prober error rate:

![image](https://user-images.githubusercontent.com/1443719/73546451-415a7e00-440b-11ea-8027-88d2d8e917e6.png)

50-100% error rate for 1hr!

The nodes crash at a fast enough rate that (a) the cluster is more or less entirely unavailable to the customer for the duration of the incident and (b) it is hard for an operator to get a SQL connection that lives long enough to cancel the problematic jobs (this is why it takes around 1hr to mitigate).

How can we reduce impact / make it easier to mitigate this issue?

1. If a job fails, the job system could do an exponential backoff.
2. If a job fails repeatedly and the job system detects that the failures are caused by dying CRDB nodes, the job system could mark the job as a "job of death" and not retry it.
3. If an SRE passes a command line flag to CRDB, the job system could not pick up any jobs.

This bug tracks 1 only.

I'm suggesting concrete solutions but I am more interested in improving the problem of very high impact than anything else! I'm suggesting concrete solutions to get a conversation started.

**Describe the solution you'd like**
If a job fails, the job system could do an exponential backoff. This would reduce the impact of a job that causes panics. The amount of time between panics would increase over time. This would also make it easier for an operator to cancel the job.

I don't know that the job system is not ALREADY doing this. If so, my bad! I do see the cluster setting `jobs.registry.leniency`. The description for this cluster setting reads "the amount of time to defer any attempts to reschedule a job". Doesn't sound like an exponential backoff.

On the CC side, we should set this cluster setting so as to reduce impact of jobs that cause panics, IMHO.

**Describe alternatives you've considered**
See 1, 2, and 3 from the above list.

@ajwerner @pbardea @spaskob @carloruiz @DuskEagle @chrisseto @vilterp @vladdy 

Epic: CRDB-7912

**Comment by ajwerner** [comment]
We have solved 3. with https://github.com/cockroachdb/cockroach/pull/44786

**Comment by sajjadrizvi** [comment]
I am currently implementing job retries with exponential backoff. I plan to implement it in the following way:

- Add two new columns in system.jobs: (1) `num_runs` that counts the number of times the job has run, and (2) `last_run` timestamp.
- We add a new index in the jobs table on `claim_session_id`, `created`, and `status` columns, storing `last_run`, `num_runs`, and `claim_instance_id`. The index optimizes claiming the jobs that have their next execution time before the current time.
- When the registry of a node runs its next adoption loop, it claims only those jobs whose calculated next execution time is before the current time. The next execution time can be calculated as `((last_run::int + base*(2^num_runs))::timestamp)`. Base is a configurable number in seconds, e.g., 10 seconds.
- When a claimed job is processed, we increment `job_runs` and update `last_run` to now().
- When a job fails, the job moves to its reverting state if it is not retriable. Otherwise, the job remains in the running state and it is retried in the next job-adoption phase.

**Comment by ajwerner** [comment]
This looked good. Let's not touch the last bullet in the first commit.

**Comment by sajjadrizvi** [comment]
The last bullet is just mentioning the current behavior. We are not modifying anything in the system.

**Comment by ajwerner** [comment]
Notes from @dt:

Observability matters here. We should indicate in crdb_internal.jobs that we're in back off, why we're in backoff (either with an error from the last run or a note that the last coordinator probably died), information about the last run. 

We want to make sure that errors we will retry do get logged. 

We want to make sure pause/resume will clear the retry state.
