### ISSUE TITLE
colexec: implement clean up of disk spilling infrastructure in all cases

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#44652]
Currently, external sort and (soon to be merged) external hash joiner clean up the disk spilling infrastructure only in the happy case - when the operator goes all the way. However, it is possible that query gets cancelled or some other event will cause the vectorized flow to shutdown some time "in the middle." We need to have a way to clean up everything in such scenario.

**Comment by asubiotto** [comment]
We could add a slice of `Closers` to the flow, similar to when we clean up the memory monitoring infrastructure. This allows us to register any components that need to be closed with the flow to be able to close them on Cleanup, rather than hoping that they will be closed by downstream components, which has been proven brittle and doesn't work in the case when a limit is hit.
