### ISSUE TITLE
rpc: investigate dying on fatal crypto errors

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4486]
In `rpc.Client`, failure to connect to a remote host (i.e. another cockroach node) may be due to a crypto configuration error. We could detect errors such as `x509.HostnameError` and kill the process instead of trying forever to make progress unsuccessfully. 

Given that `rpc.Client` is going away, we should figure out what can be done with gRPC.

**Comment by bdarnell** [comment]
Killing the local process because a remote node is misconfigured seems harsh; it seems easy for one node to wipe out a whole cluster this way. We want to make sure that these errors become visible somehow, but we shouldn't kill the node unless we can determine that it's our configuration that's wrong.

**Comment by petermattis** [comment]
I agree on the need to be careful, yet we should make an effort to detect crypto misconfigurations. I'm going to change the milestone to 1.0 as I don't think this needs to be addressed for beta.

**Comment by jseldess** [comment]
I have a candidate working through the startup instructions in Docker on Windows and reporting a crypto error as well, though it's probably very different than what's in focus here:

```
$ docker run --rm cockroachdb/cockroach:beta-20170126 version
time="2017-02-02T21:46:21-05:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Build Tag:    beta-20170126
Build Time:   2017/01/26 16:00:11
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.7.4
C Compiler:   gcc 4.9.2
```

```
$ docker exec -it roach1 ./cockroach sql
time="2017-02-03T17:55:45-05:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Error response from daemon: Container f928e1c3f1334d63f1fb35c98c621d7f59b29af334c05a12a21aee32fceb5f76 is not running
```

**Comment by bdarnell** [comment]
The "system certificate pool" warning is coming from docker, not us (and it doesn't appear to be preventing things from running). I think the real problem here is just our other known issues with docker on windows (#12593)

**Comment by a-robinson** [comment]
To add to what @bdarnell said, the last line ("Container ... is not running") is the real problem. It indicates that container the user is trying to exec into isn't running -- either because they didn't start it properly or because it crashed it for some reason. They should use the `docker logs` command on it to see why.

**Comment by jseldess** [comment]
OK, thanks @bdarnell and @a-robinson. I've asked the candidate to show me the full sequence of commands and responses. If that doesn't help, I'll ask for the logs.

**Comment by mberhault** [comment]
Connection and certificate debugging is now tracked in #24630
