### ISSUE TITLE
Allow a sub-select for a CDC cursor value

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#44970]
**Is your feature request related to a problem? Please describe.**
When creating a changefeed to start from a particular timestamp, there is usually a two step process to get the timestamp and then include that timestamp in the creation of a changefeed.  An example is below...

```
-- ## 1 ## Get Current Timestamp
select cluster_logical_timestamp();

-- ## 2 ## Get the High Water Mark from the Changefeed
SELECT high_water_timestamp FROM crdb_internal.jobs WHERE job_id = 63782674821

-- ## 3 ## Create a new Changefeed that starts from the current timestamp #44300 or the last high water mark #2
create changefeed for table sample into 'experimental-s3://chrisc-test/changefeed?AUTH=implicit' with cursor = <High Water Mark or Current Timestamp>
```

**Describe the solution you'd like**
A simple improvement would be to have this called as one statement, with the timestamp retrieval being a subselect in the cursor clause.  Examples are below:

```
create changefeed for table sample into 'experimental-s3://chrisc-test/changefeed?AUTH=implicit' with cursor = cluster_logical_timestamp();

create changefeed for table sample into 'experimental-s3://chrisc-test/changefeed?AUTH=implicit' with cursor = (SELECT high_water_timestamp FROM crdb_internal.jobs WHERE job_id = 63782674821)
```

**Describe alternatives you've considered**
The alternative today is to script out the timestamp to a variable and then rewrite / echo the create changefeed statement.  

**Additional context**

**Comment by ajwerner** [comment]
I want to break this into two distinct issues. The first has a clear solution and will also fix https://github.com/cockroachdb/cockroach/issues/41006. For the second I'd like to better understand the use case.

The first issue case is that you'd like to create a changefeed from now without a full table backfill.

To address this, I'd suggest that we add a `with backfill=false` option. That option will default to true if the cursor is empty and false otherwise to match the existing. 

The other ask is to be able to select a timestamp from an actual subquery. This is actually quite hard. I'd like to better understand why it is that you're trying to do this. 

cc @mwang1026

**Comment by chriscasano** [comment]
Correct, the first would be starting a changefeed without a backfill.  So backfill=false would be a good option with cursor= now().  The use case here would be importing all data into a table and then starting the changefeed directly after the import.  This is typically done when you're doing parrallel testing between an existing database (oracle, db2, etc) and trying to test the migration to cockroach db.  

For the sub query, this is pretty common.  If a changefeed fails or gets cancelled and you want to pick it up from the last high water mark, you typically have to query the jobs table to find the high water mark from the job and then put it into a new changefeed.  it's a two step process, see here: https://www.cockroachlabs.com/docs/v19.2/create-changefeed.html#start-a-new-changefeed-where-another-ended

**Comment by mwang1026** [comment]
I feel like a syntax with `backfill=false, cursor=now()` is redundant since you're trying to achieve the same thing (and having a cursor value implies no backfill). It could also be confusing if `backfill=true, cursor=<some_timestamp>`--throw an error? My preference would be some value that when passed to the `cursor` option would denote a "special case" where you set the cursor to whatever the system time was of the `create changefeed` command.

wrt the subquery it's possible to work around that today but like you said it's an extra step. If the most common use case is that they just want to start from the high water mark from a previous changefeed, I feel like that's a special case--unclear if it's technically any easier.

**Comment by ajwerner** [comment]
I think we're close to being on the same page but I'm going to re-iterate my position on this issue more explicitly.

> It could also be confusing if backfill=true, cursor=<some_timestamp>--throw an error

I think this is a valuable feature. See #41006.

> My preference would be some value that when passed to the cursor option would denote a "special case" where you set the cursor to whatever the system time was of the create changefeed command.

This "special case" is just not specifying a cursor.

---

My proposal again is the following:

Add a `backfill` boolean option to `create changefeed`. The `backfill` option will default to `true` if no cursor is specified and `false` if a cursor is specified.

If we do this it will solve both this issue for the `now()` use case as no cursor implies `now()` and it will solve #41006.

@mwang1026 does this proposal bother you?

---

> wrt the subquery it's possible to work around that today but like you said it's an extra step. If the most common use case is that they just want to start from the high water mark from a previous changefeed, I feel like that's a special case--unclear if it's technically any easier.

I think we should punt on this for now and say you need to do the extra step.

**Comment by mwang1026** [comment]
Doesn't bother me
