### ISSUE TITLE
Statements sections is returning an Internal Server Error after upgrading to v19.2.4

### ISSUE THREAD

**Issue by kresic87** [cockroachdb/cockroach#45073]
After upgrading from v19.2.3 to v19.2.4, the Statements section in the admin console stopped working. We are running on CentOS 7. This happens on both our dev and production DB.

The browser console shows repeated errors:
GET ***.com/_status/statements 500 (Internal Server Error).

![Screenshot 2020-02-13 at 11 03 11](https://user-images.githubusercontent.com/2317711/74423846-36630d00-4e51-11ea-8df2-37d269bb7421.png).

Is anybody else experiencing the issue?

**Comment by mattcrdb** [comment]
Hi @kresic87,

can you collect a debug.zip using `cockroach debug zip`?

Thanks,
Matt

**Comment by mattcrdb** [comment]
Hi again,

Nevermind about my previous request, this page now requires the admin role to access.

You can read about this [here](https://www.cockroachlabs.com/docs/releases/v19.2.4.html#security-updates).

As a workaround, for the time being, you can obtain an evaluation license from our website and grant the admin role to the sql user you are authenticating to the web-ui with. 

Let me know if you have any questions.

Matt

**Comment by kresic87** [comment]
Hi Matthew,

thanks for that. My bad was not to check al changes, but a 401 or 403 and a
more informative message would have been helpful.
This just felt like an internal issue. Thanks a bunch for replying, I'll
fix it accordingly.


Cheers

**Comment by mattcrdb** [comment]
I understand!

We're working on improving the error message.

see https://github.com/cockroachdb/cockroach/issues/44600

**Comment by punycode** [comment]
Today I ran into this problem too, after planning an upgrade. The implications of the original change introduced in #44349 are more far reaching for users of CockroachDB Core. Since RBAC is a feature for CockroachDB Enterprise, access to the `_status/statements` endpoint via UI is broken for Core users.

Core users cannot grant the `admin` role to a password based user.

Would it be an option, to allow `GRANT/REVOKE admin TO …` for CockroachDB Core users too, without allowing the corresponding `CREATE/DROP ROLE` statements? This way the advanced RBAC features would still be Enterprise-only while allowing Core to use the pre-existing `admin` role.

**Comment by mattcrdb** [comment]
Hi @punycode,

Yes, we are currently working on granting the admin role for core users in the traditional GRANT method.

For the time being you can use the following workaround:

`insert into system.role_members (role, member, "isAdmin") VALUES ('admin', 'sql_user', true);`

**Comment by punycode** [comment]
Thanks! This will work for the time being.

**Comment by marcboeker** [comment]
@mattcrdb Thanks for providing a way to add the admin role to a given user. But unfortunately I can't get it working. My `system.role_members` looks like this:

```
  role  |    member     | isAdmin
+-------+---------------+---------+
  admin | db_user       |  true
  admin | root          |  true
```

And if I'm using `db_user` to log into the CockroachDB dashboard I'm still getting an internal server error for statements/jobs. What am I doing wrong? Thanks!

**Comment by mattcrdb** [comment]
Hey Marc!

Can you restart the nodes in your cluster? That should help.

Let me know,
Matt

**Comment by marcboeker** [comment]
@mattcrdb Awesome thanks, that did the trick!

**Comment by SpokeyWheeler** [comment]
Guys, can I just say that this is an ill-judged implementation? It means that we have to give developers admin access just to look at these pages. Can you not create a different role that allows access to these pages / endpoints, rather than requiring full admin? The current approach actually makes the platform **less** secure.
