### ISSUE TITLE
sql: prevent schema changes during upgrades

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#45092]
In our docs for [upgrading Cockroach versions](https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html), we include this warning:

> ... refrain from starting schema changes during the upgrade process. Schema changes are complex operations that involve coordination across nodes and can increase the potential for unexpected behavior during an upgrade. 

This advice seems to apply to both major and point releases of CockroachDB. This is a problem today, as we do not have any method to prevent schema changes from starting during an upgrade. This is necessary in cases where the administrator of the database does not control the queries that are run by users of the database.

**Comment by awoods187** [comment]
@lucy-zhang and I were just talking about this. I think this should be done automatically.

**Comment by awoods187** [comment]
I'm closing this in favor of the various other issues @lucy-zhang has made and is tracking on.

**Comment by lucy-zhang** [comment]
Those issues/PRs are all extremely specific to 20.1, since we're basically forced to ban schema changes for this particular upgrade. They're going to go away for 20.2 by default unless we decide otherwise.

I think we may want a more general policy for the future, and keep this issue open to discuss that.
