### ISSUE TITLE
Remove "experimental" from Follower Reads convenience function (experimental_follower_read_timestamp())

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#45243]
**Describe the problem**
When using the convenience function for follower reads with AS OF SYSTEM TIME, it contains the word "experimental." For users, this miscommunicates that it's beyond the experimental stage. This is a big deal because we've improved follower reads in 20.1 and customers can get a lot of value out of it.

**To Reproduce**
Looking at our follower reads docs (https://www.cockroachlabs.com/docs/stable/follower-reads.html), it shows the convenience function (experimental_follower_read_timestamp()), and I used that to enable follower reads.

**Expected behavior**
I expect to be able to use follower reads convenience function without the word "experimental" in it.

**Additional data / screenshots**
<img width="1540" alt="Screen Shot 2020-02-20 at 8 50 40 AM" src="https://user-images.githubusercontent.com/1663752/74939576-25208000-53be-11ea-9580-5b30c678c185.png">

**Comment by ajwerner** [comment]
I don't think it makes sense to remove this label until we do further due diligence. Other than shortening the default closed timestamp target interval (#43147) since the feature was introduced. We've uncovered #44053 which can lead to follower reads not occurring and users seeing even higher latency which should be fixed. 

This interface was introduced as a pragmatic path to provide access to follower reads to users without making the client explicitly choose a timestamp. It is worth noting that this interface has proven to be difficult to understand and to user. Clients with this function are expressing a desire for fast reads but have to use roundabout math to reason about the staleness (which indeed has improved). Under certain scenarios follower reads can fail. When they fail, it is often confusing for users. At the very least I'd like to improve the story around observability of follower reads before removing the experimental label. 

I suspect clients generally would prefer to indicate their largest amount of tolerated staleness and then have the system provide the most up-to-date view which can be provided with a local read. This functionality is a Spanner feature is key for unlocking both correctness and low-latency for [Zanzibar](https://research.google/pubs/pub48190/). This interface would likely prove both more valuable to end users and more possible to implement with reasonable guarantees.

This function is useful but I suspect this feature deserves another round or so of iteration before we relabel it under the auspices of being a newly complete feature.

**Comment by bdarnell** [comment]
> I suspect clients generally would prefer to indicate their largest amount of tolerated staleness and then have the system provide the most up-to-date view which can be provided with a local read. 

Clients want everything to happen at the speed of light to the local replica, with the latest data, and without having to think about anything. We can't give them all three. 

`experimental_follower_read_timestamp()` optimizes for "don't think about anything", but it doesn't guarantee that the read will be fast, no does it give you the latest data that can be read locally. This is part of why it's experimental - we could tweak the formula one way to make it more reliably fast but return more stale data, or we could tweak it the other way to get fresher data but a higher chance that it has to fall back to a remote read. But those two goals are in tension, and anything that looks/works like `experimental_follower_read_timestamp` can't satisfy both at once.

Users who think about their freshness requirements can specify this instead of using the convenience function (like in spanner's "exact staleness" mode), and then we can tailor the speed/freshness tradeoffs to their specifications, although this is still not ideal since there's no way for users to get both fast and fresh data reliably, even if they are willing to quantify their expectations.

I think the ideal solution looks more like spanner's "bounded staleness" mode, which includes some sort of negotiation phase to figure out the freshest timestamp that can be served locally. This wouldn't work at all like an AOST query does today, and it may not be practical to do without some limitations on how queries are run (so that we can discover the ranges involved in the query early in the process).

**Comment by ajwerner** [comment]
> experimental_follower_read_timestamp() optimizes for "don't think about anything", but it doesn't guarantee that the read will be fast, no does it give you the latest data that can be read locally. This is part of why it's experimental - we could tweak the formula one way to make it more reliably fast but return more stale data, or we could tweak it the other way to get fresher data but a higher chance that it has to fall back to a remote read. But those two goals are in tension, and anything that looks/works like experimental_follower_read_timestamp can't satisfy both at once.

Agreed. Even if everything worked perfectly, this approach is built upon best-effort abstractions. Today we know of cases under normal operation where follower reads will fail to go to follower reads continuously. We also know of plenty of cases where follower reads will go to leaseholders transiently. Is that ever going to lead us to removing the `experimental` label while follower reads are implemented as they are today? If we had clearer understandings of when the mechanism will fail and how to quantify that failure as some function of cluster state would we be more comfortable removing the label?

>This wouldn't work at all like an AOST query does today, and it may not be practical to do without some limitations on how queries are run (so that we can discover the ranges involved in the query early in the process).

It might be possible for nodes to track a global closed timestamp property and thus avoid coordination when attempting to pick a read that can be served locally if the bound permits a timestamp preceding that global closed timestamp. It feels like such a timestamp could be propagated around the cluster in something like 2x the RTT between the furthest nodes plus the closed timestamp interval. For clients who want a staleness somewhere between the present and the global closed timestamp, a negotiation seems critical.
