### ISSUE TITLE
jobs: 19.2 binaries may not properly deal with 20.1 jobs

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#45367]
This is a placeholder issue to discuss the issue of 19.2 nodes misbehaving after 20.1 nodes update a job, especially during a cluster rollback scenario.

We need to reason about how a 19.2 node will react to the new job states. What will their adoption code do when it sees them?

We'll want to ensure we also confirm this with some experiments and tests that exercise the new jobs stats in mixed version clusters.

Additionally, there may be some cases outside of adoption code that calls jobs-related functions that inspect or assert the states, e.g. schema changes in < 20.1 run on their own, outside of jobs, but as part of running, they sometimes manually load a job directly and call SetDetails or update progress, and do so regardless of what state the job itself thinks it is in, so we may run into assertions in those methods that thought they'd only be called in certain states.

**Comment by spaskob** [comment]
Thanks for filing this!

On first thought just by looking at the code this should be fine for jobs and in worst case we may need a simple 19.x patch (See 2b below).

Essentially 20.1 has a slightly different job state machine (SM) and a superset of the job states in 19.x. So we need to think about these scenarios:

1. When a 20.1 node adopts a 19.x job will it handle it correctly?
2. Vice versa.

For case 1) we will be fine for all terminal states as the terminal states are the same in both releases.
Similarly, `StatusPending` and `StatusRunning` are handled in the same way. That leaves us with `StatusPaused`. This one is interesting, as in 20.1 we defined a new `jobspb.Payload` field that stores the last seen error if `Resume` failed. That means that 19.x jobs will be always resumed in `StatusRunning` which also is fine because 19.x jobs can only be paused while in `StatusRunning`. This may be more problematic in the opposite direction which is case 2b.

In case 2) we have several things to worry about

2a. How 19.x will deal with the new states `Status{CancelRequested, PauseRequested, Reverting}`?
2b. What about pausing a job in 20.1 and resuming in 19.x?

2a. The 19.x scheduler looks to adopt jobs only in states `Status{Pending,Running,Paused}` so it will not try to pick up the new states from 20.x so this should be fine.

2b. If a reverting job in 20.1 is paused and resumed in 19.x then it will resumed as `StatusRunning` which may be problematic. The patch to deal with this should not be too hard. We can patch the new `jobspb.Payload` proto and make 19.x schedulers not resume any jobs that have field `FinalResumeError` set.

**Comment by jordanlewis** [comment]
Unfortunately, we cannot necessarily rely on a 19.2.x patch unless we choose to make that 19.2.x patch a required upgrade between 19.2 and 20.1, which is an out-of-the-ordinary move. It would be preferable if at all possible to avoid introducing a required 19.2.x patch release.

Normally, the way that situations like this are handled is that the code that writes things that are not understandable by 19.2 is gated behind the "upgrade finalized flag", so that the new binary does not write the new states until the upgrade has been finalized and all nodes are therefore running the new binary permanently.

Is that a possibility in this situation?

**Comment by spaskob** [comment]
That would be close to impossible since the new states are critical for the
new jobs operations semantics. An option is to gate behind a pausing jobs
in state reverting which is the only problematic case. This should be quite
easy.

**Comment by spaskob** [comment]
Any tips on how to test the above scenarios manually?

**Comment by jordanlewis** [comment]
Are you saying that the only way that 20.1 could write state that is unreadable by 19.2 is if a user pauses a job in state "reverting"?

If that's the case, then I agree with your idea. If a user tries to pause a job that is currently reverting, and the upgrade is not yet finalized (checkable with a boolean predicate), the database should return an error.

**Comment by jordanlewis** [comment]
To test this scenario manually, you should:

1. start a cluster with 19.2 binary
2. upgrade all nodes to a 20.1 binary
3. do not "finalize the upgrade"
4. get a job into a state that 19.2 can't recognize
5. downgrade all nodes to 19.2 binaries

**Comment by spaskob** [comment]
Manual Testing Part 1:
Successfully tested that 19.2 jobs are successfully resumed and finished on 20.1 cluster. Follow up investigation may be needed on why progress went to 0 soon after the job was resumed on 20.1 but the data was correctly imported (testing with an import job).

**Comment by spaskob** [comment]
Part 2:
Successfully tested 20.1 jobs resumed on 19.2 and succeeding although similar abnormality was observed: the progress will fall down to 0 after the job is adopted on 19.2.
This was tested both by pausing the jobs via `PAUSE JOB id` and `RESUME JOB id` and by simply killing the cluster and upgrade/downgrade.

**Comment by spaskob** [comment]
Part 3: 
Test the new state `Reverting` in 20.1. There is no corresponding state in 19.2. When a job in state `Reverting` is paused and resumed in 19.2 the state becomes `Running` which is dangerous because the job already has a error field set and additionally some rolling back of the work may have been done in `OnFailOrCancel`.

**Comment by spaskob** [comment]
Summary of manual testing:
The above experiments have confirmed the original hypothesis that:
If a `Reverting job` in 20.1 is paused and resumed in 19.2 it will resumed as `Running` which is be problematic.
Additionally there was some unexpected behavior: `Progress` of a job restarts from 0 when it is resumed on a different version node but the job still succeeded so I am less worried about that.

How to mitigate the problem with 20.1 `Reverting` jobs being resumed as `Running` on 19.2 clusters?

1. We can disable pausing of 20.1 jobs in state reverting  through a cluster setting. That way a `Reverting` job can never be paused via a 20.1 gateway unfortunately I tested that 19.2 will grant any pause job request as long it is in a non-terminal state. So it's possible to still pause the job if the request hits a 19.2 gateway and if it is resumed by a 19.2 gateway it will be resumed as 'Running` which is not what we want. So it looks like we need to ask clients to not run `PAUSE JOB` commands at all during the migration but it is impossible to enforce it in all cases.

**Comment by jordanlewis** [comment]
So you're saying that a 19.2 node can pause a 20.1-initiated job, which is what causes the problem in this case?

**Comment by spaskob** [comment]
Yes, but only if the 20.1 job is in state  `Reverting` the pausing and
subsequent resuming will actually cause a problem.

**Comment by jordanlewis** [comment]
Okay, so the full situation is that if you have a job running in a mixed-version state that you revert via a 20.1 gateway and then pause+resume via a 19.2 gateway, the job will have unpredictable/broken behavior, right?

Can we hone in on examples of this unpredictable behavior? How bad is it? Should we just move forward with the risk that it's possible to get into this state, or ban `revert` from 20.1 until all nodes are upgraded?

Would it be possible for us to recover a user's cluster that got into the bad state?

**Comment by spaskob** [comment]
To recap the discussion from our meeting on the issue. It turns out the issue already exists in 19.2 and this just makes it more likely to occur although still low probability. I have filed a 19.2 issue that needs to documented by docs: https://github.com/cockroachdb/cockroach/issues/45809.

**Comment by spaskob** [comment]
Can someone advise what is the best way to communicate this to docs?

**Comment by spaskob** [comment]
To add some more color, it is also possible for `PAUSE` JOB id` to cause the job to fail.

1. Start a `19.x` job with id x.
2. From `20.1` node execute `PAUSE JOB x`.
3. The job will try to update its progress and see an unknown state `PauseRequested` and will fail.

This seems ok, since the job can be restarted later and also we showed before that it is not a good idea to `PAUSE/CANCEL` jobs in a mixed cluster so this scenario does not increase the attack surface during upgrades.

**Comment by spaskob** [comment]
A variation of the above problem is:

1. Start a `20.1` job.
2. Pause it from a `20.1` node.
3. Before the state of the job is flipped from `pause-requested` to `paused` from any `20.1` node downgrade the cluster to `19.x`.
4. Now the job is stuck in state `pause-requested`.

This is also low probability and the fix would be to pause the job again which will overwrite its state.
