### ISSUE TITLE
colexec: issue with buffering of decimals

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#45481]
While debugging the failure of `distsql_agg` logic test on #45318, I noticed the following:
- the query `SELECT b, c, sum(a) FROM data GROUP BY b, c ORDER BY b, c;` returns the correct output
- whereas the query `SELECT b, c::decimal, sum(a) FROM data GROUP BY b, c::decimal ORDER BY b, c::decimal;` returns incorrect output.

So it seems like we have a problem with `Decimal`s. My theory is that we do only a shallow copy in the `Columnarizer` (and we have `Materializer -> rowexec.orderedAggregator -> Columnarizer` in the plan), and whenever we return more than a single batch from the columnarizer, the decimals somehow get corrupted. cc @jordanlewis maybe you will have some insight here.

I'm not sure exactly which operator is to blame, but I tried the following fix
```
--- a/pkg/sql/colexec/columnarizer.go
+++ b/pkg/sql/colexec/columnarizer.go
@@ -20,7 +20,9 @@ import (
        "github.com/cockroachdb/cockroach/pkg/sql/colexec/typeconv"
        "github.com/cockroachdb/cockroach/pkg/sql/execinfra"
        "github.com/cockroachdb/cockroach/pkg/sql/execinfrapb"
+       "github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
        "github.com/cockroachdb/cockroach/pkg/sql/sqlbase"
+       "github.com/cockroachdb/cockroach/pkg/sql/types"
 )
 // Columnarizer turns an execinfra.RowSource input into an Operator output, by
@@ -111,6 +113,21 @@ func (c *Columnarizer) Next(context.Context) coldata.Batch {
                // TODO(jordan): evaluate whether it's more efficient to skip the buffer
                // phase.
                copy(c.buffered[nRows], row)
+               for colIdx, columnType := range columnTypes {
+                       bufferedRow := c.buffered[nRows]
+                       if columnType.Family() == types.DecimalFamily {
+                               if bufferedRow[colIdx].Datum == nil {
+                                       if err := bufferedRow[colIdx].EnsureDecoded(&columnType, &c.da); err != nil {
+                                               execerror.VectorizedInternalPanic(err)
+                                       }
+                               }
+                               if bufferedRow[colIdx].Datum != tree.DNull {
+                                       decCopy := &tree.DDecimal{}
+                                       decCopy.Set(&bufferedRow[colIdx].Datum.(*tree.DDecimal).Decimal)
+                                       bufferedRow[colIdx] = sqlbase.EncDatum{Datum: decCopy}
+                               }
+                       }
+               }
        }
```
and it almost worked. So maybe another place is the culprit.

In order to reproduce, simply modify `distsql_agg` test:
```
diff --git a/pkg/sql/logictest/testdata/logic_test/distsql_agg b/pkg/sql/logictest/testdata/logic_test/distsql_agg
index 8a15ef8a76..8ebfa6960d 100644
--- a/pkg/sql/logictest/testdata/logic_test/distsql_agg
+++ b/pkg/sql/logictest/testdata/logic_test/distsql_agg
@@ -1,4 +1,7 @@
-# LogicTest: 5node-dist 5node-dist-metadata 5node-dist-disk
+# LogicTest: 5node-dist
+
+statement ok
+SET vectorize=experimental_on
```

If debugging manually on a 2 node local cluster, follow this:
```
# LogicTest: 5node-dist-disk

statement ok
SET vectorize=experimental_on

statement ok
CREATE TABLE data (a INT, b INT, c FLOAT, d DECIMAL, PRIMARY KEY (a, b, c, d))

# Split into seven parts.
statement ok
ALTER TABLE data SPLIT AT SELECT i FROM generate_series(1, 6) AS g(i)

# Relocate the seven parts to the two nodes.
statement ok
ALTER TABLE data EXPERIMENTAL_RELOCATE
  SELECT ARRAY[i%2+1], i FROM generate_series(0, 6) AS g(i)

# Generate all combinations of values 1 to 7.
statement ok
INSERT INTO data SELECT a, b, c::FLOAT, d::DECIMAL FROM
   generate_series(1, 7) AS a(a),
   generate_series(1, 7) AS b(b),
   generate_series(1, 7) AS c(c),
   generate_series(1, 7) AS d(d)

query IRR
SELECT b, d, sum(a) FROM data GROUP BY b, d ORDER BY b, d
----
1  1  196
1  2  196
1  3  196
1  4  196
1  5  196
1  6  196
1  7  196
2  1  196
2  2  196
2  3  196
2  4  196
2  5  196
2  6  196
2  7  196
3  1  196
3  2  196
3  3  196
3  4  196
3  5  196
3  6  196
3  7  196
4  1  196
4  2  196
4  3  196
4  4  196
4  5  196
4  6  196
4  7  196
5  1  196
5  2  196
5  3  196
5  4  196
5  5  196
5  6  196
5  7  196
6  1  196
6  2  196
6  3  196
6  4  196
6  5  196
6  6  196
6  7  196
7  1  196
7  2  196
7  3  196
7  4  196
7  5  196
7  6  196
7  7  196
```
(this diff needs to be added to master branch until #45318 is merged):
```
diff --git a/pkg/sql/colexec/simple_project.go b/pkg/sql/colexec/simple_project.go
index e16182cd38..8fcc4ca8c9 100644
--- a/pkg/sql/colexec/simple_project.go
+++ b/pkg/sql/colexec/simple_project.go
@@ -14,7 +14,6 @@ import (
        "context"
 
        "github.com/cockroachdb/cockroach/pkg/col/coldata"
-       "github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror"
 )
 
 // simpleProjectOp is an operator that implements "simple projection" - removal of
@@ -35,6 +34,9 @@ type projectingBatch struct {
        coldata.Batch
 
        projection []uint32
+       // colVecs is a lazily populated slice of coldata.Vecs to support returning
+       // these in ColVecs().
+       colVecs []coldata.Vec
 }
 
 func newProjectionBatch(projection []uint32) *projectingBatch {
@@ -48,9 +50,16 @@ func (b *projectingBatch) ColVec(i int) coldata.Vec {
 }
 
 func (b *projectingBatch) ColVecs() []coldata.Vec {
-       execerror.VectorizedInternalPanic("projectingBatch doesn't support ColVecs()")
-       // This code is unreachable, but the compiler cannot infer that.
-       return nil
+       if b.Batch == coldata.ZeroBatch {
+               return nil
+       }
+       if b.colVecs == nil {
+               b.colVecs = make([]coldata.Vec, len(b.projection))
+       }
+       for i := range b.colVecs {
+               b.colVecs[i] = b.Batch.ColVec(int(b.projection[i]))
+       }
+       return b.colVecs
 }
```

**Comment by asubiotto** [comment]
Note: this issue reproduces on a single node cluster for easier debuggability.

**Comment by asubiotto** [comment]
Reproducing this with the pasted `logictest` reproduction. The plan is (removed some operators for simplicity):
```
query T
EXPLAIN (VEC, VERBOSE) SELECT b, d, sum(a) FROM data GROUP BY b, d ORDER BY b, d;
----
│
└ Node 1
  └ *colexec.Materializer
    └ *colexec.Columnarizer
      └ *rowexec.orderedAggregator
        └ *colexec.Materializer
          └ *colexec.diskSpillerBase
            ├ *colexec.sortOp
            │       └ *colexec.colBatchScan
```
There are two problems:
# Problem 1
The `rowexec.orderedAggregator` buffers grouping columns using `rowAlloc.CopyRow`. This copy is just a `copy([]EncDatum)`, which will copy the `EncDatum` structs as-is to the buffered row. The `Datum` inside the `EncDatum` is an interface pointer to a `DDecimal`. The input `Materializer` does perform an allocation of a new `DDecimal` but sets the underlying `apd.Decimal` (which is a struct, not a pointer) to the `apd.Decimal` held in the `coldata.Batch` it's materializing. This `apd.Decimal` holds a reference to a `big.Int` (`abs` field), which is a `Word` slice, so even though a new object is allocated, the slice reference is copied as is. Therefore, the ordered aggregator's grouping column `EncDatum` and `Datum` are actually safe, but the `Datum` has a reference to a slice that is present in the batch. When getting a new batch, the upstream sorter performs a `Copy`, which ends up performing a copy of a new value into the `abs` field memory pointed to by the original `Decimal` in the batch. At this moment, the row aggregator's grouping column is overwritten and the query will return incorrect results.
## Who should be doing what?
1) The sorter is correct in overwriting its internal batch, this is according to the `coldata.Batch` interface. However, the assumption is that modifying the output batch shouldn't affect its internal results. With the current way of copying, this is not true, since if the aggregator decided to copy.
2) The materializer is technically allowed to create a new `Datum`, but doesn't have to, since it is only required to return unsafe rows.
3) The aggregator (and unfortunately a big part of row execution) has good intentions when calling `rowAlloc.CopyRow`, but this copy is only a shallow copy. This needs to change.
# Problem 2
The Columnarizer is also behaving in a funky manner. Adding logging to it, the rows to output are buffered in the correct order, but when the first overwrite happens in the sorter, the order gets slightly jumbled up:
```
I200228 00:50:42.513272 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 7 196]
I200228 00:50:42.513277 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 1 196]
I200228 00:50:42.513281 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 2 196]
I200228 00:50:42.513286 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 3 196]
I200228 00:50:42.513290 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 4 196]
I200228 00:50:42.513294 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 5 196]
I200228 00:50:42.513299 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [1 6 196]
I200228 00:50:42.513303 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 7 196]
I200228 00:50:42.513308 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 1 196]
I200228 00:50:42.513312 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 2 196]
I200228 00:50:42.513317 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 3 196]
I200228 00:50:42.513321 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 4 196]
I200228 00:50:42.513325 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 5 196]
I200228 00:50:42.513330 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [2 6 196]
I200228 00:50:42.513334 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 7 196]
I200228 00:50:42.513339 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 1 196]
I200228 00:50:42.513343 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 2 196]
I200228 00:50:42.513347 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 3 196]
I200228 00:50:42.513351 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 4 196]
I200228 00:50:42.513356 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 5 196]
I200228 00:50:42.513360 1223 sql/colexec/columnarizer.go:121  [n1,client=127.0.0.1:65433,user=root] buffered row [3 6 167]
```
Printing out the indices where the decimal of the grouping row was in the batch, shows that it is overwritten by the same number displayed in the columnarizer. This is another instance of the lack of deep copying since the `Columnarizer` only does a `copy([]EncDatum)`.

# Solution
## Urgent Action items
1. Deep copy `EncDatumRows` in `rowAlloc.CopyRow` and ensure that it is used everywhere instead of just `copy`. Possible solutions:
    - [**QUICK FIX**] In `CopyRow`, ensure that the `EncDatum` is encoded and `copy` the byte slice to the new `EncDatum`. This will probably not be the best performance wise, but should not affect row execution since `Datum`s are lazily decoded. It will have a performance impact on mixed flows.
    - Implement a `Copy` method for all `Datum`s that performs a deep copy. `EncDatum` will also have a `Copy` method that additionally copies the `encoded` field.
2. Audit the `Copy` in vectorized execution, since it currently does not perform deep copies either. We see here that it is currently broken for decimals, since an `UNSAFEGET` + a `SET` is not enough. I think that this should be the only type it's broken for but we should double check.
## Less urgent action items.
1. The materializer shouldn't try to return safe rows.
2. The last stage of the flow above is `Materializer -> Columnarizer`, we should never have that in flows. We check when wrapping processors but not sure we do at the end of the flow.

**Comment by asubiotto** [comment]
I'm going to get started on implementing `Copy` for all `Datum`s

**Comment by yuzefovich** [comment]
Nice investigation!

> The last stage of the flow above is Materializer -> Columnarizer, we should never have that in flows. We check when wrapping processors but not sure we do at the end of the flow.

We definitely do not check at the end of the flows, but also we cannot omit the materializer - our draining infra relies on having a materializer at the end of the flow, so without (probably significant) refactor we won't be able to remove the pair of columnarizer + materializer in such cases.

**Comment by jordanlewis** [comment]
Yes, nice investigation! I'm a little concerned about the conclusion though - we don't want to force the row execution engine to deep copy all rows just because we need to, I think, right? Wouldn't it be better to give `Materializer` a deep copy mode, or introduce a deep copying operator that just does that one job?

**Comment by asubiotto** [comment]
Well the problem is that the row execution `Next` interface doesn't allow for keeping rows around. We could also change the `Next` interface to say that the `[]EncDatum` is not safe for reuse, but the `EncDatum` elements are, which would mean a `copy` is sufficient. The current row execution engine seems to already implement this behavior. I haven't dug deep into why, but I assume it's because we safely decode rows and when "overwriting" internal memory to return, we overwrite references to `EncDatum`s e.g. row[0], rather than what the sorter does in this example which is equivalent to something like`row[0].WriteUnderlyingMemory(newElement)`.

This would mean that we'd just change the `Next` guarantees and have the materializer properly implement that (by doing an explicit deep copy). I kind of like this.

**Comment by jordanlewis** [comment]
Yes, I think the contract of `Next` is already what you say - people expect that the underlying datums are safe to keep around without worrying that anyone will mutate them. The reason is that all input data to the system gets freshly allocated - nobody reuses `Datum` containers.

I like the idea of having `materializer` change to do the explicit deep copy (except for in the case where we're finally writing out to the wire - maybe we don't need to do the copy there - but i guess we can optimize later, and for now shoot just for correctness).
