### ISSUE TITLE
sql/pgwire: responses to commands should be coalesced

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4549]
Noticed while comparing pg and cockroach network traces, e.g. in https://github.com/cockroachdb/cockroach/issues/4538#issuecomment-186655930 

The responses to a combined command packet are sent as separate/individual packets by cockroach, whereas pg keeps the responses combined. The extra packets mean more network traffic / overhead.

Responses should be coalesced for performance.

**Comment by petermattis** [comment]
Strange. Looks to me like we only flush the write buffer immediately before trying to read another command from the client.

**Comment by petermattis** [comment]
Ah, it looks like postgres is trying to read the next command from the client before flushing the response to the previous command. We could certainly do that as well, though it is mildly irritating to do from Go because the I/O is blocking. What we could do is check to see if the read buffer has another command buffered before flushing the response to the previous command.

**Comment by bdarnell** [comment]
This is what Nagle's algorithm is for. Go's `net` package turns `TCP_NODELAY` on by default; maybe we should turn it off? Although it would be good to be able to flush the outgoing buffer before we go into a blocking read.

**Comment by knz** [comment]
( While looking at #4036  )
