### ISSUE TITLE
sql: allow inconsistent reads through

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4558]
We should be allowing inconsistent reads (from any replica) from SQL.

**Comment by petermattis** [comment]
Does the KV layer allow inconsistent reads? If so, how do you specify that? How would you want to indicate that inconsistent reads are ok in an SQL statement?

**Comment by tschottdorf** [comment]
`kv` allows this through the `ReadConsistency = INCONSISTENT` setting. But you can't have inconsistent reads in a transaction, so SQL needs more machinery. Also, I think read-write transactions based on inconsistent reads may be a bad idea. Plus, SQL will have to be much more accepting to "weird" data as it's carrying out its KV operations since "anything can happen".

I don't know if inconsistent reads are really that useful, given that we have read-only transactions with very little overhead, and reading a bit in the past should put you on safe grounds.

**Comment by bdarnell** [comment]
As I said in #6150, I'm not sure how useful this would be. Even basic functionality (index joins) requires consistency across ranges, so I think we should focus on (recent-past) time travel instead of a completely inconsistent mode.

**Comment by knz** [comment]
Is still relevant now time travel queries have been implemented? (#8188)

**Comment by tschottdorf** [comment]
I'm very comfortable closing this until there is a concrete future need to reopen this again.

**Comment by spencerkimball** [comment]
Closing pending future need. In particular as @bdarnell notes, we probably need a "safe" timestamp mechanism.
