### ISSUE TITLE
ui: add slow query log to the webui

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45618]
Now that we have a slow query log, it might be useful to show this in the UI similar to the way we show a snippet of the most recent cockroach log lines. I'm not sure what the performance of this would look like and if it is wise to load all of the statistics or just a recent snippet if the file is open and being written to.

**Comment by taroface** [comment]
Noting that the slow query log is accessible from http://<admin-ui>/_status/logfiles/local/<slow-query-log>.log as a JSON

**Comment by awoods187** [comment]
I tested out the slow query log today and discussed the findings in the [context of tpc-c](https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1592233411109600). It became clear during the conversation that the slow query log, while an important tool, does not contain distribution information. @jordanlewis points out that workloads contain queries that can be distributed differently. The slow query log has no indication of the distribution of queries, and only shows the ones that pass the threshold. For example:

Let’s say you were doing 1000 queries per second, and got 1 query per second that was slower than your threshold. (.1% of the queries slower than threshold)

Another scenario would be that you’re doing 10 queries per second, and 1 query per second was slower than your threshold (10% of the queries slower than threshold)

If you only examine the slow query log, those 2 scenarios are indistinguishable. Bringing this back to TPCC, seeing a few slow queries in the log doesn’t tell you too much unless you contextualize it by thinking about the distribution of the query latency in your workload.

As such, I don't think it makes sense to add the slow query log to the webui. Instead, we should add filters to the webui statement stats page that let you look at a subset of queries (say execution time similarly to the slow query log). The slow query log is still important because it creates a log file which is well understood by operators and because it can be fed into third-party tools if you prefer them over our webui.

**Comment by piyush-singh** [comment]
>As such, I don't think it makes sense to add the slow query log to the webui. Instead, we should add filters to the webui statement stats page that let you look at a subset of queries (say execution time similarly to the slow query log). The slow query log is still important because it creates a log file which is well understood by operators and because it can be fed into third-party tools if you prefer them over our webui.

Hmmm not sure I am following exactly. I think the original intent of this issue is met by the endpoint Ryan mentioned above - there is a simple way to grab the entire slow query log via HTTP endpoint which is useful in situations where grabbing access to the log files is complex (e.g. in a k8s orchestrated cluster). Exposing a simple interface over HTTP helps with ease of access. 

I do think there is value in exposing summarized slow query log stats in the statements page. We could, for example, add controls to enabled or disable slow query logging and then show actual statement executions that match specific fingerprints on the statement details page. Is this that similar to what you were thinking Andy? Depending on what you mean, I might close this issue and open a different one since I think the need here has been met already.

**Comment by awoods187** [comment]
>We could, for example, add controls to enabled or disable slow query logging and then show actual statement executions that match specific fingerprints on the statement details page.

Yes, I was thinking we add filters to statement stats that let you do things like filter out all queries that take longer than x, or all non-full table scans. We could also have a page the prepopulates some of this filters but i think just having them available on the statement stats page will be a win. The problem with just taking the endpoint and putting style around the logs is that the logs by themselves are often not enough to solve the problem because they miss the distribution informaiton.

**Comment by piyush-singh** [comment]
Awesome, we're on the same page. I'll open a new issue and close this one out.
