### ISSUE TITLE
server: separate node-node and client-node RPC traffic on different ports

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45907]
This follows a discussion with @Amruta-Ranade and a recommendation from @aaron-crl 

In v19.1, we created the option to separate the SQL and the RPC ports. 
This was based off the idea that sites would want to restrict node-node traffic on a separate network.

However that design did not properly consider that the RPC port is used for both node-node traffic and node-CLI traffic. For example, `cockroach node`, `cockroach quit`, `cockroach init`, `cockroach debug` all use APIs over RPC.

To properly answer the security story, we need to create the ability to isolate all node-node traffic on separate port, with its separate/distinct TLS story. 

Epic CRDB-6673

Jira issue: CRDB-5118

**Comment by knz** [comment]
cc @ajstorm for tracking. We'll need this to for multitenant architecture unification

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-5118](https://cockroachlabs.atlassian.net/browse/CRDB-5118) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-45907`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
