### ISSUE TITLE
ui: custom time range with "now" as the start time is nonsensical

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#45939]
![Screen Shot 2020-03-10 at 9 10 26 AM](https://user-images.githubusercontent.com/6201335/76315442-0f142a00-62af-11ea-8b0e-9de897f29213.png)

What is "now" supposed to do for the start time of a custom time range? Perhaps I'm lacking imagination.

**Comment by koorosh** [comment]
@piyush-singh , I think the main issue here tied to incorrect behavior of both "Today" (for date picker) and "Now" (for time picker) options, but "Now" option is still can be useful, I suppose.
Currently, "Today" button changes both date and time to current time, and the "Now" button does the same - it changes the date field as well (not only time). 
I would expect that "Now" option (for time picker) doesn't change the date and it is possible to select some custom date in the past and then select "now" time to get the date range starting with the same hour/minute as now but in past.
Do you think it makes any sense?

**Comment by piyush-singh** [comment]
Hmm I think that would ultimately just be confusing. As an end user, I would indeed expect the "now" button to update both the date and time field, and I don't think I would set a date first before attempting to click on it. We can get similar behavior by selecting a 24hr window and then modifying the date afterwards, so I think just removing the "now" option is probably best.

**Comment by petermattis** [comment]
@piyush-singh Have you tried using this UI to select a specific start or end time? Beyond just this "now" issue, it seems pretty broken. This isn't a recent problem, but something I've failed to file in the past. See the animation below. Selecting an hour doesn't change to the selected hour but one that is completely different. Typing into the text field doesn't seem to do anything at all. This is super reproducible for me.

![time selector](https://user-images.githubusercontent.com/6201335/86535422-4043e600-beae-11ea-9c22-75635a18e94b.gif)

**Comment by koorosh** [comment]
- Indeed, time selection doesn't work as expected due to an issue with proper conversion of time with timezones to UTC. The selection is shifted by timezone offset.
- Also, it appears quite confusing, when the date range is selected within local timezone and then charts show data on a timeline with UTC.

**Comment by piyush-singh** [comment]
@petermattis I think this is the result of two issues - we seem to not be using UTC in the picker (whereas we use UTC everywhere else in the UI). We also do input validation to make sure that the selected start time is not after the selected end time. I usually anchor the end time to now by clicking "Today" and then set the start time. Going the other way is definitely confusing due to the two issues above, and we may want to rethink the UX here - it may be better to just allow the user to enter any time they wish and display an error if the selection isn't valid. cc @Annebirzin for any thoughts on the best UX for the invalid input state.
