### ISSUE TITLE
cli: support `debug zip --anonymize`

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46031]
We should provide this switch so that diagnosing of issues is not hindered by manual scrubbing by the user -- which could be prone to mistakes as well.

Few examples:
-  The table/key names (XXXX) in log lines:
```
I200311 07:21:32.053215 826880069 storage/replica_command.go:797 [n8,replicate,s8,r16277/42:/Table/131{-/1/"XXXX…}] change replicas (REMOVE_REPLICA (n5,s5):37): read existing descriptor r16277:/Table/131{-/1/"XXXX^51b23f4c1607fe220acebc023621568f"} [(n4,s4):40, (n8,s8):42, (n5,s5):37, (n11,s11):43, next=44, gen=8]
```
- The same as above in range reports, rangelog.json
- User names used to log into the admin UI

**Comment by onno-vos-dev** [comment]
@irfansharif Just want to +1 this issue. I've been asked to provide a debug zip a few times now but due to restrictions have to make sure I scrub all PII from the dump. Currently I got some crazy `sed` commands to deal with this but having an `anonymize` flag as proposed here would me sleep a little bit better :smile: 

I see there's already a PR ongoing for it, if you'd like I'm happy to pitch in :+1:

**Comment by irfansharif** [comment]
I empathize with your pain! Hopefully there's not much of that before long. There's a bit of design work ongoing by @knz over at #48076, that you may be interested in.
