### ISSUE TITLE
Reorganize SQL commands

### ISSUE THREAD

**Issue by Lewiscowles1986** [cockroachdb/cockroach#46112]
## Background

Watching https://www.twitch.tv/videos/566559036 it seems that even your internal team gets some issues from the size of the >5.5k line `pkg/sql/sem/builtins/builtins.go`

## Question

Would you be Open to a PR, or series of PR's, which basically puts each command into an external go file?

## Reasoning

Other than avoiding merge conflicts for subtle revisions to implementations (sadly not bindings)...

The binding and the implementation would live separately, which I think should make this file shorter, more glanceable (in the way C++ headers are glanceable, you could still make a mess) and easier to re-factor and contribute to later.

**Comment by jordanlewis** [comment]
Hi @Lewiscowles1986, thanks for filing the issue! I'm the one who did the Twitch stream, and although normally I don't have that problem since I'm sitting in an IDE, I'm the first to admit that `builtins.go` is a completely insane file and deserves to be broken up.

We're definitely open to PRs of this nature. As a warning, though, we are near our next release, so we probably won't merge the PR until we cut our release branch which will probably happen in the next week or two.

Thank you for your interest in contributing! Feel free to tag me, @rohany and @otan on the PR.

**Comment by Lewiscowles1986** [comment]
Cool, I'm suggesting the following categories

- string.go
- uuid.go
- json.go
- math.go
- datetime.go

By keeping everything in the same package I'm hoping to avoid too much headache. I may prefix with `impl_`. It is my hope this might make testing simpler too, so it might not just be about organisation. I'll try to keep commits small and I hear you RE: a few weeks. This might take me a few weeks or I might hit a roadblock.

**Comment by otan** [comment]
i'd probably suggest splitting into https://sourcegraph.com/github.com/cockroachdb/cockroach@d8bdc938177ea4b5226b95ee6cc51af0951054fc/-/blob/pkg/sql/sem/builtins/builtins.go#L82

**Comment by jordanlewis** [comment]
Happy to accept contributions for this but going to close it for now.

**Comment by Lewiscowles1986** [comment]
I think I started, then read and thought on

> We're definitely open to PRs of this nature. As a warning, though, we are near our next release, so we probably won't merge the PR until we cut our release branch which will probably happen in the next week or two.

And wanted to make sure we were not going to get into rebase hell.
