### ISSUE TITLE
Incorrect result for MAX, INTERLEAVE IN PARENT, and vectorize=experimental_on

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46140]
Consider the following test case:

```sql
SET vectorize=experimental_on;
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 BOOL) INTERLEAVE IN PARENT t0(rowid);
INSERT INTO t0(c0) VALUES (0);
INSERT INTO t1(rowid, c0) VALUES(0, TRUE);
SELECT MAX(t1.rowid) FROM t1 WHERE t1.c0; -- { NULL }
```
It is unexpected that the query fetches `NULL`. When disabling vectorization, the query returns the expected result:

```sql
SET vectorize=off;
SELECT MAX(t1.rowid) FROM t1 WHERE t1.c0; -- { 0 }
```

I found this bug based on commit `3d8b9d56f36ddce5c71827e89ecb2e5d5e046495`.

**Comment by asubiotto** [comment]
Thanks for the submission. Just a note that this doesn't seem to reproduce with `vectorize=auto` on a06be622747fa0b70376005f88aec30a8b45af7e.

**Comment by mrigger** [comment]
I assume the following triggers the same underlying bug?

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT) INTERLEAVE IN PARENT t0(rowid);
UPSERT INTO t1(rowid) VALUES (0);
UPSERT INTO t0(rowid) VALUES (-1);
SET vectorize=on;
SELECT MIN(rowid) FROM t0; -- -1
SELECT MIN(rowid) FROM t0 @{FORCE_INDEX=primary,DESC};  -- NULL
```
I found this test case based on commit 322f83364bc0807c3147af0631cb7317c584ce43.

**Comment by yuzefovich** [comment]
Yes, I believe the underlying root cause is the same in both reproductions.

It looks to me that the issue is in `cfetcher` that incorrectly handles interleaved tables. In both reproductions, `cfetcher` incorrectly returns zero-length batch while it should be returning a batch with a single tuple. I'm very unfamiliar with that code, so I'm wondering whether @rohany or @jordanlewis could take a look at this issue.

**Comment by rohany** [comment]
I can take a look
