### ISSUE TITLE
UUIDs implementation useless/not production-ready

### ISSUE THREAD

**Issue by desmap** [cockroachdb/cockroach#46141]
I can use UUID and store them as binary to save space but I can't query them?? You write  in your docs *This approach has the disadvantage of creating a primary key that may not be useful in a query directly, which can require a join with another table or a secondary index.*

But then your UUID feature is completely useless. CRDB is a distributed DB => UUIDs are a must => binary UUIDs are a must because of space => so you need also to provide a function to convert them back to let us query with them, eg. for FKs = PKs. Maybe I got something wrong but binary and query-able UUIDs are the core and must-feature of any distributed DB...  :/

**Comment by ajwerner** [comment]
> But then your UUID feature is completely useless

I think you may be confused about what the documentation is saying. Can you help me understand your problem better? Have you run into any issues?

You can query using binary uuids. You can use them in fks. I think the docs are trying to say that UUIDs are generally random and thus may be less human meaningful that some multi-column primary key. I’m going to close this because it doesn’t seem like a real issue. If you find a problem with our UUID offering please open another issue which explains the problem.

**Comment by ajwerner** [comment]
> This approach has the disadvantage of creating a primary key that may not be useful in a query directly, which can require a join with another table or a secondary index.

If indeed it's just this line you're taking issue with, it's not in any way talking about the capabilities of the UUID data type, just that it's not human meaningful.
