### ISSUE TITLE
ui: admin UI hangs when 2 nodes down in a 3 node cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#4617]
When you start up a 3 node cluster and then take 2 of the nodes down, the sql client hangs and the admin ui goes blank.

1. Start first node: `./cockroach start --insecure`
2. Start second node: `./cockroach start --insecure --stores=cockroach-data2 --port=26258 --join=localhost:26257`
3. Start third node: `./cockroach start --insecure --stores=cockroach-data3 --port=26259 --join=localhost:26257`
4. Start sql client: `./cockroach sql --insecure'.
5. Run `show databases;`. **Response is fine.**
6. Open admin UI. **Looks fine.**
7. Stop second and third nodes.
8. In sql client, run `show databases;`. **No response.**
9. Refresh admin UI. **Blank page.** 
10. Restart node 2. **sql client and admin UI fine again.**

@tamird reproduced this as well.

**Comment by tamird** [comment]
To clarify, the SQL client part of this is the expected
raft-doesn't-have-quorum stall. The bug is that the admin UI is down when
you need it most.

**Comment by cuongdo** [comment]
I'm not clear on how to resolve this. The admin UI renders but with no graph data, because it can't query the time-series data. The time-series query times out for the same reason the SQL shell hangs: no Raft quorum. 

The current node may not even have the required ranges to serve the latest time-series data. Is there a way to always replicate recent time-series data to all nodes?

**Comment by tschottdorf** [comment]
There's technically no reason to query timeseries data consistently. Timeseries don't go through SQL, right? If not, it should be relatively easy to use INCONSISTENT isolation by default. When done so, any replica can service the reads.

**Comment by tamird** [comment]
Any replica with the requisite ranges.

On Mon, Mar 14, 2016 at 4:08 PM, Tobias Schottdorf <notifications@github.com

**Comment by cuongdo** [comment]
Exactly. There’s no guarantee that the single node that’s up has any of the requisite ranges.

On March 14, 2016 at 4:13:18 PM, Tamir Duberstein (notifications@github.com) wrote:
Any replica with the requisite ranges.

On Mon, Mar 14, 2016 at 4:08 PM, Tobias Schottdorf <notifications@github.com

**Comment by bdarnell** [comment]
This is why IMHO any serious deployment will want to export their monitoring data to some external monitoring system. In addition to being a suboptimal timeseries database in terms of efficiency, it's difficult to make the timeseries component of cockroachdb significantly more reliable than the rest of the DB. (it's doable, yes, but getting there means moving away from "let's build a basic monitoring system *using* cockroachdb" towards "let's build an entirely separate monitoring system that happens to be embedded in cockroachdb")

Inconsistent reads could hit a very out-of-date replica, maybe even a replica that has been removed from the range but doesn't know it yet (this could happen even if nothing's wrong with the cluster). It may be better to do a consistent read at an older timestamp (are we smart enough to serve those from replicas yet?)

We should handle this more gracefully than a blank page, but the UI is necessarily going to be severely degraded when this happens.

**Comment by tschottdorf** [comment]
> Exactly. There’s no guarantee that the single node that’s up has any of the requisite ranges.

If you have one out of three up, it's guaranteed to have it (unless the cluster crashed really early).

> Inconsistent reads could hit a very out-of-date replica, maybe even a replica that has been removed from the range but doesn't know it yet (this could happen even if nothing's wrong with the cluster).

That's a fair point.

> It may be better to do a consistent read at an older timestamp (are we smart enough to serve those from replicas yet?)

No, not smart enough yet. It would require `DistSender` to know about timestamp cache internals. Sounds kind of complicated.

We're obviously a little limited by design, but if a cluster goes 2/3rd down, it'd be great to at least keep the existing part of the graph. Can that be achieved from within the UI perhaps?

**Comment by mrtracy** [comment]
Inconsistent reads at older timestamps wouldn't work: time series are not stored in the MVCC system, and thus can't be read in the past.

In any case, a cluster would not even need to be 2/3 down in anything larger than a three-node cluster; you could lose two machines and temporarily be unable to access a good chunk of time series data.

I'm not sure if there is a clear fix to this; we're talking about a scenario where a huge part of the cluster is unavailable for some reason, and we want information on the portion that is down.  Even if we made a radical change, such as moving time series to be locally stored on the nodes that generated them, that wouldn't help us in this case. As Ben said, fixing this would basically involve creating a separate database product embedded into Cockroach (with CA properties).

Some ideas i've brainstormed:

I. We already have an eventually consistent database available in cockroach: gossip. Could we gossip status summaries, perhaps storing the last ten minutes of status for each node on _every_ node?

II. Perhaps we could provide some sort of "emergency mode" in the UI, triggered when time series queries are failing, which attempts to contact nodes directly and get some basic information from them.  This still wouldn't get us any information about the nodes that are down, but it could at least identify _which_ nodes are down and highlight the situation for the user.

III. Solution II still doesn't help us diagnose what went wrong on the down nodes, other than pointing them out to the user. Perhaps we could have nodes publish recent fatal errors into gossip when they restart? Or is there a way we could provide log access to these failed machines through cockroach?  Otherwise, they're going to need to ssh into the down machines and get logs themselves.

**Comment by petermattis** [comment]
You've mixed up two concepts with "inconsistent reads at an older timestamp". We can do inconsistent reads (any replica can respond to the request) and, for MVCC data, we can read at an older timestamp. Since the timeseries data is not MVCC encoded, the second option is out. But we can still do an inconsistent read. The caveat @bdarnell mentioned is present, but that seems better than trying to change up the timeseries system at this point. And while the timeseries data retrieved by an inconsistent read might be significantly out of date, it does contain timestamps which would allow the UI to visually indicate when the last update to the data was received.

**Comment by cuongdo** [comment]
Yes, I believe that an inconsistent read is the best strategy here. Some UI
work will also be needed to smooth out the visual glitches accompanying
server timeouts (e.g. "No data available" showing for graphs.
