### ISSUE TITLE
ui: statement diagnostics history download button only shows up on hover

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#46340]
In the statements diagnostics history page, the Download button only shows up on hover. There is not much indication on the page that this is what you have to do. In contrast, the diagnostics page for a statement just shows the Download for each row, which I think is better. In any case, they should be consistent.

**Comment by awoods187** [comment]
<img width="1558" alt="Screen Shot 2020-04-06 at 11 08 20 AM" src="https://user-images.githubusercontent.com/22278911/78574640-46b3ba80-77f8-11ea-9c42-d1eb55a2cb61.png">
<img width="1321" alt="Screen Shot 2020-04-06 at 11 04 59 AM" src="https://user-images.githubusercontent.com/22278911/78574644-474c5100-77f8-11ea-91ab-cfd137ea161c.png">

We should make this always visible rather than reactive to hovering. It's already within the advanced debug pages--I don't think we run the risk of it being run frequently (which we would be worried about given its expense).

**Comment by RaduBerinde** [comment]
A relevant comment here: https://github.com/cockroachdb/cockroach/pull/46790#issuecomment-607986117
