### ISSUE TITLE
backfill: half of backfills aren't memory accounted, and they don't use predictable amount of memory

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#46346]
The backfill code has a few flaws.

1. It's not memory accounted when generating the SQL keys. Index keys can be large, and there can be many of them - both the `entries` list and the keys themselves in `backfill/backfill.go` should be accounted for.
2. The backfill code generates chunks of index entries by asking for 1000 rows at a time, and building entries for all 1000 rows. This is troublesome - what if the rows are really big? This will be mitigated in 20.1, since kv now takes a bytes limit. But, for inverted indexes, a single row can generate a ton of entries as well. The backfill code should act as an iterator - instead of generating all keys for all rows, it should generate keys for its batch of rows until the keys have hit a fixed-size buffer limit, write that out, then continue.

**Comment by joshimhoff** [comment]
CC @dt 

Interesting!
It sounds like backporting a fix for 2 isn't controversial (unlike 1)?

**Comment by dt** [comment]
Yeah, I don't think I'd object to that change in a backport on principal since it isn't a user-visible change (though from practical point of view it may actually be the more difficult change to backport).

I have an idea for how to make adding account to stable releases less of a user-visible change which I might try to play with next week that could let us add accounting even in backports, but i'll make a separate issue for that.

**Comment by joshimhoff** [comment]
> I have an idea for how to make adding account to stable releases less of a user-visible change which I might try to play with next week that could let us add accounting even in backports, but i'll make a separate issue for that.

Awesome!

**Comment by dt** [comment]
I wrote that up over on https://github.com/cockroachdb/cockroach/issues/46367#issuecomment-601724935

**Comment by dt** [comment]
re-opening until the backport lands
