### ISSUE TITLE
sql: DROP DATABASE issue with TEMP tables

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46393]
Consider the following statements:

```sql
CREATE DATABASE db11;
USE db11;
SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t0(c0 INT);
```
When the temporary table is **not** dropped, and the session is restarted, it seems that the database can no longer be removed:

```sql
DROP DATABASE db11 CASCADE; -- cannot access temporary tables of other sessions
```
Using `SET experimental_enable_temp_tables = 'on'` before the `DROP DATABASE` does not seem to make a difference. The `TEMP TABLE` also cannot be dropped after ending the session:

```sql
USE db11;
DROP TABLE t0; -- relation "t0" does not exist
```

A workaround is to create a new temporary table with the same name and drop it before ending the session:

```sql
USE db11;
SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t0(c0 INT);
DROP TABLE t0;
```
Strangely, this seems to affect only databases with specific names. This might suggest that some internal logic confuses databases/database names.

**Comment by knz** [comment]
This is a temp table / DDL edge case which we forgot to cover.
cc @ajwerner @jordanlewis for triage.

**Comment by otan** [comment]
i've got an idea for the main idea of the issue - create database does not have privs to read/write to temp schemas (repro: temp schema in one db on one session, deleting the database on another session)

But:

> Strangely, this seems to affect only databases with specific names. 

I *think* this is because you may have some corrupted database state (as I could only reproduce this when I have a database with invalid table metadata from a previous database session) around - and given your stress tests and bug finding that may be the case! But I'm not sure. If there are temporary tables still around, there should be a "background task" that cleans them up periodically which errors if there is an issue trying to drop stuff for whatever reason which ends up here: https://github.com/cockroachdb/cockroach/blob/322f83364bc0807c3147af0631cb7317c584ce43/pkg/sql/opt/exec/execbuilder/relational.go#L156.

Do you see issues that look like a background job in your logs failing to cleanup temporary tables that looks like `schema change statement cannot follow a statement that has written in the same transaction`? If so, do you mind copying those logs over?

**Comment by mrigger** [comment]
@otan I just looked into the log file and when closing the session after executing the statements, an error is indeed logged:
```
I200323 17:19:00.079934 1825450 sql/event_log.go:132  [n1,client=127.0.0.1:55192,hostnossl,user=root] Event: "create_database", target: 478, info: {DatabaseName:db11 Statement:CREATE DATABASE db11 User:root}
I200323 17:19:00.115558 1825450 sql/event_log.go:132  [n1,client=127.0.0.1:55192,hostnossl,user=root] Event: "create_table", target: 480, info: {TableName:db11.public.t0 Statement:CREATE TEMPORARY TABLE t0 (c0 INT8) User:root}
I200323 17:19:00.117077 1826894 kv/kvserver/replica_command.go:397  [n1,split,s1,r545/1:/{Table/476-Max}] initiating a split of this range at key /Table/480 [r547] (zone config)
E200323 17:19:04.597693 1825450 sql/conn_executor.go:856  [n1,client=127.0.0.1:55192,hostnossl,user=root] error deleting temporary objects at session close, the temp tables deletion job will retry periodically: delete-temp-TABLE: unimplemented: schema change statement cannot follow a statement that has written in the same transaction
I200323 17:19:05.702017 61 server/status/runtime.go:498  [n1] runtime stats: 785 MiB RSS, 406 goroutines, 104 MiB/177 MiB/319 MiB GO alloc/idle/total, 85 MiB/114 MiB CGO alloc/total, 583.0 CGO/sec, 6.3/0.3 %(u/s)time, 0.0 %gc (1x), 20 KiB/30 KiB (r/w)net
```

**Comment by otan** [comment]
Thanks for confirming!

The fix I just submitted should work in this case, but I want to get to the bottom of the background job not cleaning up which I may file separately.
