### ISSUE TITLE
sql: output of show create table differs from the syntax of the table created 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46554]
The output of show create table is different than the the original create table statement. 
```SQL
root@127.0.0.1:60098/movr> CREATE TEMP TABLE mytemp(c INT);
CREATE TABLE

Time: 16.767ms

show create table mytemp;
  table_name |        create_statement
-------------+----------------------------------
  mytemp     | CREATE TEMP TABLE mytemp (
             |     c INT8 NULL,
             |     FAMILY "primary" (c, rowid)
             | )
(1 row)

Time: 186.186ms
```
I know that these can be considered aliases but this may be confusing to users who didn't specify things like INT8 or apply a column family.

Build Tag: v20.1.0-beta.2-1072-g6c3c5d4a9a
Build Time: 2020/03/25 12:43:24
Distribution: CCL
Platform: darwin amd64 (x86_64-apple-darwin19.3.0)
Go Version: go1.13.4
C Compiler: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Build SHA-1: 6c3c5d4
Build Type: development

Jira issue: CRDB-5082

**Comment by otan** [comment]
i think this would require a significant lift as it involves then storing the original CREATE TABLE string. this is now also made harder by stuff like ALTER TABLE which can change the structure.

it is worth MySQL will have the same behaviour of renaming it to a system appropriate standard that makes recreation of the table "as close to the system definition as possible", which is what we do here: http://sqlfiddle.com/#!9/d3689/26 (postgres does not support show create table)

unassigning for now as I don't feel like this is a quick and easy decision, would like to see if others agree.

**Comment by bdarnell** [comment]
> i think this would require a significant lift as it involves then storing the original CREATE TABLE string

More than that, it requires splitting the original string up and storing information about the original spelling of things in each column type (etc) so we can reconstruct it later. I think we should just set expectations appropriately that `SHOW CREATE TABLE` is *semantically equivalent* to the original statement, but may not match it exactly. 

In the case of `INTEGER` and `INT` normalizing to `INT8` or `INT4`, this change could even be helpful since it means that applying the CREATE statement will produce the same results even if the `default_int_size` setting has been changed. 

FWIW, I would support hiding the `FAMILY` line from `SHOW CREATE TABLE` if it's equivalent to the default. I'd maybe even support using `BIGINT` instead of `INT8` because it's in the SQL standard (and likewise for other standardized types). But I wouldn't support an effort of the depth required to match the original spellings.

**Comment by awoods187** [comment]
My thinking has evolved since I originally posted this issue. I do think we should keep it as is but I like the ideas ben offers on how to improve the display by removing `FAMILY` and using `BIGINT`.
