### ISSUE TITLE
sql: support foreign key references from computed columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#46672]
Currently, you can't have a foreign key reference to or from a computed column. This issue tracks lifting that restriction.

```
root@127.0.0.1:59162/defaultdb> show create table a;
  table_name |               create_statement
-------------+------------------------------------------------
  a          | CREATE TABLE a (
             |     a INT8 NOT NULL,
             |     b INT8 NULL AS (a) STORED,
             |     CONSTRAINT "primary" PRIMARY KEY (a ASC),
             |     FAMILY "primary" (a, b)
             | )
(1 row)

Time: 76.875ms

root@127.0.0.1:59162/defaultdb> alter table a add foreign key (b) references a.a;
ERROR: computed column "b" cannot be a foreign key reference
SQLSTATE: 42P16
root@127.0.0.1:59162/defaultdb> alter table a add foreign key (a) references a.b;
ERROR: relation "a.b" does not exist
SQLSTATE: 42P01
```

We should allow this, but don't allow the foreign key to cascade UPDATE operations. (if CASCADE UPDATE is present, then return an error as we do now.)

More context: https://cockroachlabs.slack.com/archives/C4ERHM60Z/p1715610700697119

Jira issue: CRDB-5070

Epic CRDB-37763

**Comment by jordanlewis** [comment]
cc @RaduBerinde - we should keep an eye on this as we move FKs out of the HP entirely.

**Comment by awoods187** [comment]
A concrete example of this is the journey of moving from a single-region to multi-region application like in MovR.

We'd like to adjust the schema to the following:
rides.city, rides.vehicle_id --- fk ---> vehicles.city, vehicles.id
rides.city, rides.rider_id --- fk ---> users.city, users.id
this is currently impossible because you can’t use a column (rides.city) in more than one outgoing foreign key. That will be addressed in this issue.

Unfortunately, adding a duplicate column is a workaround, but we don’t actually have support for having a fully schema-side “duplicate column” without computed columns. Computed columns would work, but they don’t support outgoing fks.

**Comment by RaduBerinde** [comment]
Actually, it looks like references *to* computed columns work (at least on master, but probably in 20.2 as well). Note that the statement `alter table a add foreign key (a) references a.b;` is incorrect, it should be `references a(b)`. That works (well, if you add a `UNIQUE` to the column).

**Comment by msirek** [comment]
I think this restriction can be lifted.  I tried some test cases and they are all working.
It looks like the restriction was originally put in place 5 years ago due to incorrect behavior documented here:
#22428

But changes since then seem to be causing FK support to work properly now.

We'd just need to lift the CREATE and ALTER TABLE restrictions [here](https://github.com/cockroachdb/cockroach/blob/dc2eb667ce0ba305ca13e09e5f76e41c9b384c60/pkg/sql/catalog/descpb/column.go#L50-L61) and [here](https://github.com/cockroachdb/cockroach/blob/c8c499501cff2fa9dc88ab7b3890062011ad1b78/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L798-L810) and then add a bunch of tests.

Target 23.2?

**Comment by Cidan** [comment]
any updates on this? hit this snag today.

**Comment by dikshant** [comment]
This seems like a quick win and we have a customer that ran into this. Let's try to pick this up in the next few weeks.
