### ISSUE TITLE
kvserver: quiescing ranges with no proposal quota leads to impossibility to un-quiesce

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#46699]
We believe we've seen the following situation: a leaseholder was unable to propose anything because it was stuck trying to acquire quota. The range has a bunch of quota outstanding (so very little quota left), and it was also quiesced. The outstanding quota pertained to command that hadn't been acked by a particular replica, which replica has been on a node that was dead for days.

Generally we don't quiesce when commands are outstanding like that, but the theory is that the respective replica died and was considered dead by the code that's deciding whether the range can be quiesced, but before it was considered dead by the code that release quota held up by these replicas.
Quiescing code:
https://github.com/cockroachdb/cockroach/blob/1f9586007a242bd783dfcd0ae62da13cf62f6bed/pkg/kv/kvserver/replica_raft_quiesce.go#L262 

Releasing quota for dead nodes:
https://github.com/cockroachdb/cockroach/blob/bc52ebfb756d718816888aaf34985fca09162bfd/pkg/kv/kvserver/replica_proposal_quota.go#L149

One observation is that the two code paths use different notions of node liveness. But I guess the real problem is that we're generally incoherent in the treatment of quota and quiescing.
The way things are supposed to work when quiescing is not in play is that eventually, when processing a "raft ready", we're supposed to notice the dead replica and release the respective quota.  But since we're successfully quiescing, there's no more raft ready.

Nathan and Andrew suggested not quiescing when there's outstanding quota. That sounds good to me. I want to see if there's other thoughts on the pickle. I'm interesting in doing something here personally, cause I want to get into this code.

cc @nvanbenschoten @ajwerner @tbg @bdarnell

**Comment by ajwerner** [comment]
> Nathan and Andrew suggested not quiescing when there's outstanding quota. That sounds good to me. I want to see if there's other thoughts on the pickle. I'm interesting in doing something here personally, cause I want to get into this code.


The other related alternative is to clear the outstanding quota when quiescing. The problem is, for the most part, the mismatch between the liveness criteria for a follower. To do the former is to say that the we like the condition in use by the proposal quota better while the latter is to say that we like the condition in use by the quiescing code better. Both are driven by pretty arbitrary constants, 10 and 7 seconds respectively, attached to different bookkeeping mechanisms, raft message activity vs lifeness record updating. 

I like the proposal of extending the queiescing logic to consider the same condition as we consider in the proposal quota indirectly by looking to see if there is outstanding proposal quota. That condition should also ensure that there's no race condition where a command sneaks in after we first determine that we should quiesce and takes all of the quota.

**Comment by tbg** [comment]
Interesting find. I agree that having the quiesce code path check whether there is outstanding quota (atomically with quiescing) makes sense (and in turn we atomically check quiescence when acquiring quota, or so it seems we have to). That the liveness conditions differ is annoying, and I'm open to sychronizing them, but that doesn't seem like the real fix here (the race could still happen if they used the same one, I think)

**Comment by ajwerner** [comment]
> that doesn't seem like the real fix here (the race could still happen if they used the same one, I think)

Agreed.

**Comment by nvanbenschoten** [comment]
I prefer the check that `len(r.mu.quotaReleaseQueue) == 0` in `shouldReplicaQuiesce` as well. It shouldn't require any new synchronization and it doesn't introduce a new code path that can be responsible for releasing quota.
