### ISSUE TITLE
importccl: re-enable CANCEL/PAUSE tests for IMPORT

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#46729]
Tests which test the behavior of PAUSE'ing and CANCELing an IMPORT job have been skipped. I've briefly attempted to unskip these tests, but it requires a non-trivial amount of work. This issue is to be used as a tracking issue to track this work.

Epic CRDB-7776

Jira issue: CRDB-5063

**Comment by adityamaru** [comment]
Resurrecting this issue because I need to write some CONTROL job tests for #52004

In the current state of the CANCEL test (with some updating), we setup an IMPORT with 10 CSV targets on a single node. We have a filter on the AddSSTable store response and enforce a flush on every batch. `RunJob("CANCEL")` ensures the IMPORT job is started before issuing a `JOB CANCEL` and then closes the channel, thereby unblocking all the store responses. Here is what I have observed so far:

- The job status is immediately changed to `cancel-requested` after `CANCEL JOB` is issued.
- Closing the response channel allows the IMPORT job to complete and attempt to mark itself as succeeded. This fails deterministically as the job status is `cancel-requested`.
- After the IMPORT job completes (errors out), the `OnFailOrCancel` hook may or may not run before we attempt the second IMPORT which we expect to succeed.

1. If `OnFailOrCancel` runs the drop logic, it reads the tableDesc from `job.Details` with a status "offline", but the IMPORT job has managed to publish the tables (write a desc to KV with status "public"). So the ConditionalGet fails before the CPUT of the dropped table desc.

2. if `OnFailOrCancel` does not run, we encounter a "table already exists" error because the second IMPORT job attempts to create a table that is still there.

I am not certain what we want this test to look like yet, but I still have a couple of questions:

-  From what I can tell, the `OnFailOrCancel` method for IMPORT can never succeed after the tables have been published, because the tableDesc in `jobs.Details` is never cleared of its "offline" status during publishing.  So does this need to be fixed?

- What triggers the `OnFailOrCancel` hook for an IMPORT job? If we fix the above, ideally we want to trigger the hook before running the second IMPORT so that we don't see an existing table with the same name. Do we have any knobs to this effect?

**Comment by pbardea** [comment]
> After the IMPORT job completes (errors out), the OnFailOrCancel hook may or may not run before we attempt the second IMPORT which we expect to succeed.
I'm not aware of any knobs to control when `OnFailOrCancel` is called, but does it make sense for the test to wait for the first job to reach a terminal state (e.g. failed in this case) to ensure that it has cleaned up after itself before running the second IMPORT?

> From what I can tell, the OnFailOrCancel method for IMPORT can never succeed after the tables have been published, because the tableDesc in jobs.Details is never cleared of its "offline" status during publishing. So does this need to be fixed?

Yep, it sounds like this needs to be fixed. After publishing the tables, the job details should be updated with the new descriptors (the PUBLIC ones), so that they can be cleaned up properly in case of a failure. This is what restore does.
