### ISSUE TITLE
restoreccl: Restoring a full cluster then a specific table from a prior timestamp errors out

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#46740]
**Describe the problem**
A bit of an edge case, but could present problems if people rely on this. Scenario is you have a table that, at the timestamp you're doing the full cluster restore, was dropped. You restore the full cluster, then afterward attempt to restore the dropped table into the new cluster, it'll error with `ERROR: license for cluster(s) 601c3d5f-46ca-4e2d-af25-92dd4b91d068 is not valid for cluster 588dc95e-1e79-41d0-8e03-cab12cea76f1 SQLSTATE: XXC02`.

If you just try to restore that table in a fresh cluster at the earlier timestamp, restores fine.

**To Reproduce**
1. Take a full cluster backup to `LocationA` at timestamp 1
2. Create a table TableA
3. Take an incremental backup to `LocationA` at timestamp 2
4. Drop TableA
5. Take an incremental backup to `LocationA` at timestamp 3
6. Create a new cluster
7. Restore full cluster backup from `LocationA` at timestamp 3
8. Try to restore TableA from backup at timestamp 2 (it will throw an error)

**Expected behavior**
I would expect if the Full Cluster restore works, for the table restore to work as well

**Additional Context**
I'm a bit surprised that it's a license error. How often are licenses changed? How often are customers using the same license across all clusters? How are licenses provisioned for CC?

FULL CLUSTER BACKUP from demo
RESTORE into roachprod local

**Comment by pbardea** [comment]
I dug into this and the reason that we're seeing the license error is that the full cluster restore restores the license that was backed up (by design), and since the backup was done on a demo cluster the license used on that cluster isn't valid on the roachprod cluster.

Everything here is working as expected. One would only run into this when backing up from a demo cluster and restoring on a non-demo cluster (which shouldn't be done).
