### ISSUE TITLE
sql: multiple schema DROP tests fail in jobs_verification.go

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#46835]
In the CI for #46832 (unrelated to schema changes) I observe this: 

![image](https://user-images.githubusercontent.com/642886/78116342-6caa1b00-7404-11ea-9e9f-9f358aebbc05.png)

https://teamcity.cockroachdb.com/viewLog.html?buildId=1842946&buildTypeId=Cockroach_UnitTests

All the failures have the same symptom:

```
    jobs_verification.go:139: error scanning '&{<nil> 0xc0017aff00}': sql: no rows in result set
```

@lucy-zhang @spaskob is this expected?

**Comment by knz** [comment]
oh I think that's what Andrew is fixing in #46829, nvm

**Comment by knz** [comment]
oh wait no that may not be the case. @lucy-zhang can you still have a look and see what's up here?

**Comment by lucy-zhang** [comment]
Oh, yeah, this is because at some point I changed all the tests to assume that there would be 4 schema change jobs (from the migration), since the tests work by checking a specific row in the output of the jobs table, and I didn't want to try to change the interface for that.

The way to fix this is to just subtract 4 from all the places where we call `VerifySystemJob`/`VerifyRunningSystemJob` with an offset for all the failing tests. I left myself a TODO (`// TODO (lucy): The offset of +4 accounts for unrelated startup migrations`) in most of these places. If you want, I can just add a commit on top of your PR to do this.

**Comment by knz** [comment]
I'll do it and add you as a co-author :)
thanks for the pointer.
