### ISSUE TITLE
Document manual steps to produce debug.zip

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#46895]
Provide steps to manually retrieve the information contained in debug.zip in case `cockroach debug zip` doesn't produce it for whatever reason, e.g. if the command hangs.

The collected information would include retrieval of nodes' log files, goroutines, problem ranges endpoints, etc.

**Comment by andreimatei** [comment]
There's tons and tons of things in the debug.zip, and it's always changing. Many of them can't exactly be done by hand. When getting the zip fails, I think you really need to start asking specific questions; nobody's gonna collect everything.
We could document perhaps how to retrieve a couple of very common things... But I'm not sure what I'd put there apart from all the logs. Collecting anything that is per-node is very laborious. We could perhaps talk about what to collect from a given node, once you know what node you care about.

I'm personally much more interested in debugging every instance where collecting the zip hangs. We've done progress in the area, and it's really important that it doesn't hang.

Btw, generally I think you should assign a person or a project to an issue, otherwise it's very likely that nobody will see it.

**Comment by petermattis** [comment]
There seems to have been some miscommunication here. Fully and persistently documenting `debug zip` is not what is being asked for. The intention is to provide some details of the steps and endpoints that `debug zip` collects for internal (i.e. support) use for exactly those situations where `debug zip` is hanging. @knz and I discussed this the other day and I believe he has a sense of what to produce. The result will not be a code or docs PR, though. So I think we can close this issue.

**Comment by knz** [comment]
I asked Alex to file the issue so that I can track it.
There was no ambiguity from my perspective (Peter already explained to me what was needed before we filed the issue).

**Comment by knz** [comment]
The explanation is now published for use by all our users, in the public wiki:

https://wiki.crdb.io/wiki/spaces/CRDB/pages/433291265/Collecting+a+debug+zip+manually
