### ISSUE TITLE
sql: investigate slow stressrace on schema change migration tests

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#46941]
When running the schema change migration tests under stressrace, they take more than 7m30s to complete. The timeout was increased for these tests, but we should investigate as to why these tests are taking a long time to run and hopefully reduce the test timeout interval to what it was before.

**Comment by lucy-zhang** [comment]
This was originally prompted by #46504. I don't think we're realistically going to pursue this. That test involved a lot of job registry operations and had a lot of subtests, so it was just slow, and right now the stressrace timeout per package is min(20 minutes, minutes * number of tests) which doesn't seem outrageously high; it seems that the worst that happens is that we take longer to detect timeouts due to hung tests. I'm closing this.
