### ISSUE TITLE
Comparison with (-9223372036854775808)::TIMESTAMP results in an unexpected error

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46973]
Consider the following statements:

```sql
CREATE TABLE t0(c0 TIMESTAMP UNIQUE);
SELECT * FROM t0 WHERE (-9223372036854775808)::TIMESTAMP!=t0.c0; -- ERROR: unordered spans (/Table/1208/2/{!NULL-292277026596-12-04T15:30:07.999999001Z} /Table/1208/{2/292277026596-12-04T15:30:08.000001Z-3})
```
Unexpectedly, the `SELECT` results in an error `ERROR: unordered spans (/Table/1210/2/{!NULL-292277026596-12-04T15:30:07.999999001Z} /Table/1210/{2/292277026596-12-04T15:30:08.000001Z-3})`. When using the `=` operator rather than `!=`, the query does not result in an error and fetches no rows.

I found this bug based on commit 0c1b121315e246e3e51fc6f7aa613f77de6b6527.

**Comment by otan** [comment]
@knz / @RaduBerinde might need your help with this one as it's gnarly.

The optimizer finds spans for != by using Next and Prev to determine the range and exclude teh current key. We key timestamps by storing the unix offset and the microsecond offset.

Note we store TIMESTAMP/TIMESTAMPTZ in indexes as `<time.Unix()><MicrosecondOffset>` - ill omit the microsecond offset for the purposes of explaining the rest.

However, the min int64 for the unix offset represents 292277026596-12-04 15:30:08+00:00, and the max int64 for the unix offset represents 292277026596-12-04 15:30:07.999999. Note here: `minInt64::time > maxInt64::time`. However, spans don't work nicely that way. I understand this is due to the "offset" effect of Golang time being represented as time since 0, wheres the Unix() functions are time since 1970-01-01 so some overflow/underflow will cause the above to happen.

So this means that the max Golang representable time is int64(-9223372028715321601), which is "219250726-11-09T07:00:15Z".

So we have a problem here that the span "scan" for `!=` TIMESTAMP/TIMESTAMPTZ operations. This means we should technically be scanning `[-9223372028715321600...current)`, `(current, int64max]` *and*` (int64min ... -9223372028715321601]` for the != operator. For the case of this ticket, it should scan `[-9223372028715321600... 9223372036854775807]` and `(-9223372036854775808 , -9223372028715321601]`. Seems like a hassle (and not simply a change in the Min/Max/Prev/Next operators). Other operators related to time might also be also affected.

The other alternative is to not allow the parsing of dates after a certain threshold (i.e. something like `time.Unix(-9223372028715321601, 999999999)`). This is certainly outside the range of dates postgres supports (postgres only does one uint64 which represents microseconds since 2001-01-01). The only problem is if someone decides to store an arbitrarily far enough date in their past versions that we now may not return correct results for those rows if they use timestamp in the index.

(if we were to do this again, I'd just make it store the uint64 offset since 2000-01-01 as postgres does, so we have the same bounds)

**Comment by RaduBerinde** [comment]
This is not just a problem with spans. The span issue just reflects the sad reality that the encoding is incorrect -  values in an index are not actually ordered:
```
root@127.0.0.1:43811/movr> select * from t order by t;
                  t
-------------------------------------
  292277026596-12-04 15:30:08+00:00
  1970-01-01 00:00:01+00:00
```

I would not add special code to the spans just to fix this case, there will be other problems. I agree that we should cap the timestamps to be in a range where this does not happen (and DTimestamp.Min/Max/IsMin/etc should reflect that).

I doubt this kind of extreme values are used in practice (short of bugs).

**Comment by otan** [comment]
sounds good, i'll look to cap some timestamps around the place.
