### ISSUE TITLE
ui: Allow the release notes signup banner to be disabled by an environment variable

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#46998]
@petermattis pointed out that having an env var to disable this banner would be nice for nightly test clusters and other internal testing here at CRL.

**Comment by irfansharif** [comment]
It'd be nice if the env var is set through roachprod by default, or something to the effect.

**Comment by piyush-singh** [comment]
Would be great to pick this up during the stability period for this release. We have seen a few customers request a way to remove this as well.

**Comment by irfansharif** [comment]
Have we had too many signups through that CTA? I'm actually a bit surprised to find it there. Presumably if you've gotten as far as running a full fledged binary and are clicking around in the Admin UI, you're already pretty invested. My unsolicited 2c: I don't think I was asking for it to be hidden just because of the visual noise, it feels pretty "spammy"/"pop-up"-ey and especially so given it's in the very first view of our product, so sour taste and all that.

**Comment by Annebirzin** [comment]
@piyush-singh @dhartunian related to this issue I created designs for an [admin ui settings page](https://www.figma.com/file/OzoUuhNk05nFuaZB6UNVBx/obsrv_admin-ui-node-list) (original issue #52197)

![Screen Shot 2020-09-01 at 10 37 42 AM](https://user-images.githubusercontent.com/51920721/91865274-3684f780-ec3f-11ea-9dca-fc285eea5ab9.png)
