### ISSUE TITLE
storage: Move SetLastVerificationTimestamp to a replicated Raft command

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4710]
Currently a Range's LastVerificationTimestamp is broken as it is only set on the node that was the leader when a GC or verification is performed. Because of this we should temporarily move the `RangeLastVerificationTimestampKey` to the unreplicated range-local group. 

To allow this key to rejoin the replicated range-local meta key group, we will want to move the SetLastVerificationTimestamp functionality into a raft command (either adding it to GC() or creating a new one) so that a new leader can pick up the previous leader's verification timestamp.

**Comment by spencerkimball** [comment]
I actually don't think is is a problem. The last verification timestamp is relevant only to an individual replica. Every replica must be verified periodically on its own. The purpose of the verify queue is to prevent bits from rotting on disk. Making this replicated would prevent replicas from individually scheduling timely verifications.

The reason that the last verification timestamp is set after GC is that the GC implicitly does the verification, so we update the verification timestamp to prevent unnecessary work by the verify queue.

I will send out a PR to remove the TODOs in the code and add a timestamp for something else I'm working on, the `LastReplicaGCTimestamp`.

**Comment by bdarnell** [comment]
OK, makes sense. I just saw the use of this timestamp in the gc queue and assumed it was GC related, instead of being primarily for the verification queue.

It feels like a premature optimization to set the verification timestamp from the GC queue; it's relying on the fact that the GC queue covers everything that the verification queue would, but that's just an implementation detail. An optimization I'm about to suggest in #4960 would break this equivalence so it would no longer be appropriate to set the verification timestamp there.
