### ISSUE TITLE
ORDER BY unexpectedly causes a value to be represented in E notation when VECTORIZE=on

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#47115]
Consider the following test case:

```sql
SET SESSION VECTORIZE=on;
CREATE TABLE t0 (c0 DECIMAL PRIMARY KEY, c1 INT UNIQUE);
INSERT INTO t0(c0) VALUES (1819487610);
SELECT t0.c0 FROM t0 ORDER by t0.c1; -- expected: {1819487610}, actual: {1.81948761E+9}
```
Unexpectedly, `t0.c0` is represented in E notation. When dropping the `ORDER BY`, the value is represented as `1819487610`:
```sql
SELECT t0.c0 FROM t0; -- {1819487610}
```
The result is also as expected when dropping one of the constraints, or when the vectorizer is turned off. Interestingly, when `1819487609` or `1819487611` are inserted, rather than `1819487610`, this issue does not occur.

**Comment by yuzefovich** [comment]
Hm, the issue here seems to be that in `colencoding/key_encoding.go` we always use only "key" encoding for decimals which encodes `1819487610` as `181948761` with `E=1`, but in the row engine somehow the same value is encoded using "value" encoding which keeps the "full" mantissa with zero exponent. It seems like having a secondary index here plays a role as well.

@rohany I wonder if you could take a look at this, but it doesn't seem too urgent to me.
