### ISSUE TITLE
sql: system.namespace is unreadable from 19.2 nodes in mixed version state

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#47167]
19.2 nodes in a mixed-version state with 20.1 can't read `system.descriptor` from SQL. This has cascading problems, because `crdb_internal.zones` explicitly reads `system.descriptor`, and a few things explicitly read `crdb_internal.zones`, including debug zips, admin ui, and so on.

The cause of this is that #44006 edits the `system.namespace` descriptor (which is descriptor ID 2, which is called `namespace_deprecated` in 20.1) to changes its name to `namespace_deprecated` for the purpose of making Backup not fail due to seeing descriptors with duplicate names. But the 19.2 (and prior) code expects the original `namespace` table to be named `namespace`, and does not resolve it otherwise.

**Comment by dt** [comment]
Looking at this, the issue that #44006 was fixing was that the original migration added a second desc with the same name (`namespace`) and the same parent (system) which violated a contract that BACKUP and RESTORE was assuming -- that names were unique within a DB. This is because BACKUP loads all descs and then builds a map from name to ID from the descriptors (reusing the same resolution as RESTORE, where we need to run that logic on the descriptors from the backup). If we introduce a duplicate name (adding a desc at ID 30 with the name `namespace` while the desc at ID 2 also has that name), all backups in that cluster, at least on 19.2 nodes, will start to fail (backup loads all descs to build that map, so even unrelated backups of any table will see the dupe and error out).

The way #44006 fixed it was to change the name _in_ the old namespace desc (at ID2) when it created the new desc at 30 with that name. However as we see here, 19.2 nodes will still resolve that ID 2 descriptor as the descriptor for `system.namespace`, and then be confused.

We know we can't have duplicates, and we know we can't change the name in ID 2, so I think what we need to do is change the name in ID30, creating it with a new name like `namespace_with_parent` or something.

_Then_, when the cluster version ticks up (in the new thing sql-schema folks added to do the jobs migration post upgrade finalize), then we can do the swap -- rename the ID 2 table to _deprecated (or just drop it?) and rename `namespace_with_parent` to `namespace`?

I guess last question there though would be what does 20.1 resolve for `system.namespace` until then ? If it is 30, it is also going to dislike the name mis-match?

**Comment by rohany** [comment]
> I guess last question there though would be what does 20.1 resolve for system.namespace until then ? If it is 30, it is also going to dislike the name mis-match?

As long as the descriptor on disk's name != the name we lookup the descriptor with we're going to error out (unless we add a special case)

**Comment by dt** [comment]
Yeah, I think we might need a special case for that part, but at least that is a 20.1 special case and I think can be pretty narrowly scoped.
