### ISSUE TITLE
bulk, *: latency impact of background jobs on foreground traffic

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#47215]
#45888
#34744
#36925
#36091

Jira issue: CRDB-5026

Epic CRDB-14568

**Comment by pbardea** [comment]
The main finding from my investigation here with respect to index creation is 

- Playing around with various cluster settings related to index backfills, controlling the batch was able to fairly accurately control the impact that an index backfill had on the foreground TPCC traffic.

P99 latency sat around 40ms before the initial index backfill, which ran form 22:50 - 22:53. The second index backfill started at around 22:53 and ran from 22:53 - 23:12. The batch size of the initial index backfill was the default 50k, and only 10 for the second. This is a rather extreme example, but shows that the batch size can reduce the impact of backfills on foreground traffic at the expense of taking longer to complete.
<img width="1048" alt="Screen Shot 2020-08-16 at 11 52 01 PM" src="https://user-images.githubusercontent.com/507390/90556674-4bee2200-e167-11ea-9730-7b59013a6b88.png">

- Index backfills on non-live traffic did not have a noticeable impact on live-traffic.

Follow-up work:
- Is the contention here related to the reads on the existing index, or traffic interacting with the backfill on the new index. This information can inform how useful it would be to change the backfill process to backfill an index in `DELETE_ONLY` mode and then incrementally catch up any missed deletes and writes after an initial backfill.

<This is still a WIP. Going to download some Jaeger traces and also upload them for comparison. Most of the differences in query times were due to waiting for the KV concurrency manager to acquire latches.>
