### ISSUE TITLE
*: datadriven approach to mixed cluster tests

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#47229]
In the wake of recent release blockers related to mixed version clusters breaking things such as #47167 and #47110, we have found that there is a large amount of "big brain thinking" needed to ensure clusters work on mixed versions. Cases are easily missed or super strange edge cases may exist.

One of the ways to move forwards to exercise edge cases is to start "randomized testing", but before that it seems we're missing a framework of dealing with mixed-cluster testing first.

At the moment, one can do mixed-cluster testing by using logic tests such by using `local-mixed-19.2-20.1`, which works on a fixed mixed cluster layout. Alternatively, one could download a roachtest that downloads an old binary and having a lot of boiler plate to set up the desired scenario.

It seems like it would be extremely nice if we instead had a datadriven approach to mixed-cluster testing. It would be super easy and accessible for everyone to test random edge cases and regressions if we could do something along the lines of the strawman below:

```
start 19.2.5 node1
start 19.2.5 node2
start 19.2.5 node3 # hey you could even shut down this node

# execute some crazy import
execute node1 table_name
IMPORT <data> INTO x

# make sure descriptors are ok, or something of the ILK
select_descriptor node1 table_name
----
<result>
<result>

# upgrade a node to master
upgrade node2 latest_on_master

# run query that may be backwards compatible on all three clusters, check they are sane.
run_query node1 <query>
----

run_query node2 <query>
----

run_query node3 <query>
----

# downgrade and test
downgrade node2 19.2.5

# run query that may be backwards compatible on all three clusters, check they are sane.
run_query node1 <query>
----

run_query node2 <query>
----

run_query node3 <query>
----

```

Jira issue: CRDB-5024

**Comment by otan** [comment]
cc @irfansharif out of curiosity, what testing plans do you have for https://github.com/cockroachdb/cockroach/issues/39182. would this be something that could be tackled?

**Comment by tbg** [comment]
@otan let's chat. Poorly copy-pasted slack DM with Jordan below

----

@jordanlewis:
what do you think about https://github.com/cockroachdb/cockroach/issues/47229?
We had a brainstorm in the sql features meeting about what we could have done to catch the problem with the namespace table, and Oliver came up with this idea
is this compatible with your work with Spas? orthogonal? just curious

@tbg:
It sounds like Oliver might have missed that version-upgrade exists
The approach to reduce friction to doing such testing is the right instinct.
I think using datadriven here is a good idea. I’m less sold (if that’s even being proposed) to do this in unit testing, as we need to download binaries, spawn processes, etc
I guess I would encourage Oliver to look at the result of my recent work on acceptance/mixed-version
there’s a harness that we can use to put datadriven mixed version SQL tests into roachtest

@jordanlewis:
personally, I always avoid doing roachtests if I can because they’re slow and hard to get started with for me. maybe that’s a personal problem. but i think if it’s not local and near instant, we have a problem

@tbg:
But these would be local and near-instant

@jordanlewis:
ok, would you mind writing up a quick comment to that effect on the issue? “I guess I would encourage Oliver to look at the result of my recent work on acceptance/mixed-version”

@tbg:
You’re really just rebuilding roachtest --local if you try to do this in unit tests

@jordanlewis:
i see, ok

@tbg:
Excited that people are raving about that mixed version stuff now

**Comment by otan** [comment]
Ah, we're looking at https://github.com/cockroachdb/cockroach/blob/bc2d311f68209972ae3ca417331aa02a170a5adc/pkg/cmd/roachtest/versionupgrade.go#L92 right?

I was hearing roachtest was too slow so thought that was an issue, but will give it an investigation sometime soon. Seems like it should be easy to form into a datadriven approach.

**Comment by tbg** [comment]
I hear the "roachtest is too slow" argument, but see the salient line here:

>  You’re really just rebuilding roachtest --local if you try to do this in unit tests

There's no reason a roachtest run with `--local` needs to be slowed than a cobbled together in-process version of the same. You will need to download, spawn, kill external binaries and do all of the things roachtest does to get the old versions. As a bonus, you *can* also run this against real clusters, which can't hurt.

I'm still touching this version-upgrade test, but I'll cc you on all future PRs. I might also preemptively add a refactor or two that you would certainly need, like being able to stream the steps into the framework as opposed to hardcoding them at the top.

**Comment by jordanlewis** [comment]
I think the "roachtest too slow" thing came from me, and I wasn't considering `roachtest local`. Sorry for the negative propaganda!

**Comment by tbg** [comment]
While I have bright SQL-savvy minds thinking about this, what would be one wonderful application of all this is to run the logic test suite against clusters that are rolling back and forth between HEAD and the predecessor version without finalizing. The tricky thing to figure out is how to handle the parts of the logic tests that fail in such a setup for the right reasons (using features from HEAD that are unavailable in the mixed setup). This is more of a bookkeeping/ergonomics issue than a technical problem, but if we solve it it will pay off. Coincidentally, a similar story will appear with multi-tenancy, where we will also default to running all logic tests in a setup in which they run in the context of a constrained tenant.

**Comment by otan** [comment]
took a brief look at doing this today - the main challenge is getting the mixed binaries in. i think if we want mixed version tests that are local we can:
* put a copy of all older version binary in the repo (1x osx, linux binary for all previous repos)
* for all bazel defined versions, use the shadowing build rules (e.g. https://docs.bazel.build/versions/1.2.0/external.html#shadowing-dependencies) so we can initialize a server/binary depending on version. potentially opens us up to using `testserver` for mixed versions rather than using cli commands to start up servers. only allows testing of bazel'd versions of CRDB though.
* i'm trying to find a way of defining a bazel rule which selects a binary to download from a HTTP link, so the binary doesn't have to live in the repo. will update if i find a way, probably the cleanest way, but tests can only be run on bazel.

**Comment by tbg** [comment]
The holy grail would be to have the actual code for both versions debuggable. You could imagine having the previous CRDB version as a submodule, ie on master today you would have

```
./cockroach-21.2 (tracking release-21.2 with the occasional bump)
```

and our `testcluster` tooling could optionally instantiate the `TestServer` defined by the cockroach-21.2 code tree. I think if we keep the necessary interfaces stable.

I think there's a fair amount of yak shaving to get there and it is likely easier to use the autodownload approach you describe. We could even do this inside of our test infra, if we teach `TestCluster` to "just" call `binfetcher.Download` with an appropriate cache location. But then we need to make bigger changes too, to interop TestCluster with standalone binaries. So maybe the "submodule repo" approach is even lighter on the required coding work while yielding more powerful results. A lot of care has tone into TestCluster (certs, etc) that I'd hate to have to replicate once more.

**Comment by irfansharif** [comment]
Getting an importable v22.1 TestCluster would be a giant boon and a lot more flexible+faster+reliable than having to write mixed version tests running actual CRDB binaries. It's a good yak to shave.

> only allows testing of bazel'd versions of CRDB though.

CRDB v22.1 is bazel'd, our release binaries are built using it.

**Comment by tbg** [comment]
Played around with it a tiny bit. Not trivial imo, but hopefully someone here can learn from my problems and maybe address them? I tried to get to a place where in a `master` test, I can import a 22.1 `server.TestServer` and get that to compile. By "compile", I mean `go test` compile. While we can probably get a bazel build to compile, that isn't enough. If we can't use Goland to work with the resulting mixed-version tests, it's only an academic exercise. Helpfully I also don't know the next thing about bazel so that was another reason for me to not worry about bazel much.

```
git submodule add -b release-22.1 -- git@github.com:cockroachdb/cockroach ./crdb-22.1
echo "
build --config nolintonbuild
build --config=dev
" >> ./crdb-22.1/.bazelrc.user
./dev doctor
You are ready to build :)
./dev gen protobuf
```

Nice! The `Makefile` has never been able to do that, which has been blocking folks from using multiple checkouts (worktrees) for release branches. So apparently that works now, with https://github.com/cockroachdb/cockroach/pull/79455 having been the last block.

```diff
diff --git a/crdb-22.1 b/crdb-22.1
deleted file mode 160000
index 0509bc6c07..0000000000
--- a/crdb-22.1
+++ /dev/null
@@ -1 +0,0 @@
-Subproject commit 0509bc6c07ceed6d77d8cd088cb79d4a0e8f38ed
diff --git a/pkg/server/admin_cluster_test.go b/pkg/server/admin_cluster_test.go
index dea4cd2add..a8ad980d6b 100644
--- a/pkg/server/admin_cluster_test.go
+++ b/pkg/server/admin_cluster_test.go
@@ -15,6 +15,7 @@ import (
 	"testing"
 	"time"
 
+	"github.com/cockroachdb/cockroach/crdb-22.1/pkg/server"
 	"github.com/cockroachdb/cockroach/pkg/base"
 	"github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/livenesspb"
 	"github.com/cockroachdb/cockroach/pkg/roachpb"
@@ -243,3 +244,8 @@ func TestLivenessAPI(t *testing.T) {
 		return nil
 	})
 }
+
+func TestBar(t *testing.T) {
+	v212Server := server.TestServer{}
+	_ = v212Server
+}

```

So far so good but here are the first roadblocks:

```
$ go test ./pkg/server/ -run TestFoo
# github.com/cockroachdb/cockroach/pkg/server
pkg/server/admin_cluster_test.go:18:2: cannot find package "github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cockroach/crdb-22.1/pkg/server" in:
	/Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cockroach/crdb-22.1/pkg/server
FAIL	github.com/cockroachdb/cockroach/pkg/server [setup failed]
FAIL
```

I figured out that it's looking into `vendor` because `crdb-22.1` is a standalone module. Ok, easy enough to "fix":

```
mv crdb-22.1/{go,nope}.mod
```

```
# github.com/cockroachdb/cockroach/crdb-22.1/pkg/server
crdb-22.1/pkg/server/testserver.go:311:41: cannot use &TestServer{} (value of type *TestServer) as type serverutils.TestServerInterface in variable declaration:
	*TestServer does not implement serverutils.TestServerInterface (missing GetAdminHTTPClient method)
crdb-22.1/pkg/server/testserver.go:529:41: cannot use &TestTenant{} (value of type *TestTenant) as type serverutils.TestTenantInterface in variable declaration:
	*TestTenant does not implement serverutils.TestTenantInterface (missing GetAdminHTTPClient method)
crdb-22.1/pkg/server/testserver.go:764:9: cannot use &TestTenant{…} (value of type *TestTenant) as type serverutils.TestTenantInterface in return statement:
	*TestTenant does not implement serverutils.TestTenantInterface (missing GetAdminHTTPClient method)
crdb-22.1/pkg/server/server_sql.go:582:3: not enough arguments in call to descs.NewCollectionFactory
	have (*cluster.Settings, *lease.Manager, *"github.com/cockroachdb/cockroach/pkg/sql".VirtualSchemaHolder, *hydratedtables.Cache, spanconfig.Splitter, spanconfig.Limiter)
	want (context.Context, *cluster.Settings, *lease.Manager, "github.com/cockroachdb/cockroach/pkg/sql/catalog".VirtualSchemas, *hydratedtables.Cache, spanconfig.Splitter, spanconfig.Limiter)
```

These also make sense. The import paths inside of crdb-22.1 are all incorrect (refer to the "outside" master code).

That got me thinking, should we just vendor ourselves at the older version? To try this out quickly:

```
mv crdb-22.1/ vendor/github.com/cockroachdb/cockroach
```

but not a chance, since that makes the import path `github.com/cockroachdb/cockroach` ambiguous:

```
$ go test ./pkg/server/ -run TestFoo
ambiguous import: found package github.com/cockroachdb/cockroach/pkg/server in multiple directories:
	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/server
	/Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cockroach/pkg/server
```

At this point I was a bit out of my depth with how modules even work. I figure there should be a way to have crdb-22.1 in the vendor directory with a `go.mod` that refers to it as `cockroachdb/cockroach` (so that the "old code" just works without accidentally referencing the outside import paths) but with an actual import path not matching that... not sure.

This is probably easier to snuff out in a toy repo.

**Comment by otan** [comment]
> I figure there should be a way to have [crdb-22](https://cockroachlabs.atlassian.net/browse/CRDB-22).1 in the vendor directory with a go.mod that refers to it as cockroachdb/cockroach (so that the "old code" just works without accidentally referencing the outside import paths) but with an actual import path not matching that... not sure.

i think the way to do this is to actually publish release versions of go modules, like how pgx is `github.com/jackc/pgx/v4` for v4 and `github.com/jackc/pgx` for v3.  You can import both. In other words, change the go.mod to:
`module github.com/cockroachdb/cockroach v21` and the like for the others. then maybe you'd be able to do this:
```
import (
  crdb221 "github.com/cockroachdb/cockroach/v221"
  crdb211 "github.com/cockroachdb/cockroach/v211"
)
```

unfortunately, we can't, because we don't check in generated files to our modules. bazel has a chance because it knows how to fetch and rebuild older versions, but it's unclear to me about goland.

i think the debuggability aspect of this is a bit of a pipe dream, but maybe i should have a never-say-never attitude.

**Comment by tbg** [comment]
> unfortunately, we can't, because we don't check in generated files to our modules. bazel has a chance because it knows how to fetch and rebuild older versions, but it's unclear to me about goland.

That's not a problem, I think it is fine to expect a `./dev gen` before being able to use the IDE/`go test`. That's already necessary today. I was able to run `./dev gen` just fine in the submodule.

> i think the way to do this is to actually publish release versions of go modules, like how pgx is github.com/jackc/pgx/v4 for v4 and github.com/jackc/pgx for v3. You can import both. In other words, change the go.mod to:

But this means that we have to provide a version of the (say) 22.1 codebase that uses an import path `github.com/cockroachdb/cockroach/v2201` and in particular needs a search-replace across ~everything, no? What we would want to achieve is to keep the `cockroachdb/cockroach` import path, i.e. avoid transformations like these:

https://github.com/jackc/pgx/commit/72cc95e4dd18576691da38c46c7e6a101869c10a

Probably the answer is "can't be done with go modules". We could, once we cut a release branch, also give it a separate import path and avoid the problem that way, i.e. we'd do the rename on (say) `release-22.1` when it is first cut, and then cry all of the time because all backports will require a manual stitch-up. It will also be weird because then master will be v0 and the release branch will be a "later" go version. So maybe we'd make master `v0.22.2` and release-22.2 is `0.22.1` or the like.

Maybe we can automate the search-replace for the import path.

Anyway, the yak shaving that I alluded to is definitely there.

**Comment by rickystewart** [comment]
Reading through these comments, I'm a little perplexed why we're trying to get multiple versions of `cockroach` all linked into the same executable. Does this yield some advantage as opposed to just using a precompiled executable for each and using the normal facilities for putting the mixed-version cluster together (i.e. getting N versions of `cockroach`, one for each version under test, then running `cockroach start` for all the versions)?

Given that the various CRDB versions are going to have different third-party libraries vendored I find it pretty dubious you're going to be able to get 22.1 and 22.2 (for example) linked into the same executable w/ everything working as expected. My suspicion is that even if you get a build "working", you'll probably have made some compromises to get that far and by that point the `cockroach` you're "testing" doesn't actually have the same behavior as any released `cockroach` because you're intermingling stuff from different versions together. This aspect reminds me in a way of #67473 and I do want to make some tweaks to how our dependencies are referenced in the Bazel build such that we can have two different versions of an open-source library in the same build context, but of course this stuff would work for Bazel and not GoLand or anything like that.

Of course if `pkg/server` were not so large and monolithic then I might not have the same concerns, but I don't see that changing any time soon either.

**Comment by otan** [comment]
> Does this yield some advantage

people want to use the Goland debugger :) which i still am of the belief

> i think the debuggability aspect of this is a bit of a pipe dream,

I think it's possibly possible, but as you say, pretty difficult and I imagine the standalone binary world would (a) get us to a place where something works and we can start testing *something* (b) be a lot easier to reason about and maintain.

**Comment by tbg** [comment]
> I think it's possibly possible, but as you say, pretty difficult and I imagine the standalone binary world would (a) get us to a place where something works and we can start testing something (b) be a lot easier to reason about and maintain.

That is probably right. The main goal needs to be making it easy for devs to write mixed-cluster tests while staying in their IDE most of the time. If we introduce yet another completely separate framework for it (like some special test harness), this is going to be difficult, and won't be adopted at the rate we would like to see. So ideally whatever we do, to a dev, looks like "I use TestCluster but can tell it easily that some of the nodes should be running the previous version and this just works at least for most vanilla things one can do". I think that can be done with a `TestServer` that's backed by a running process (and which `t.Fatals` on anything that isn't really possible with a binary). If we someday find out that the "linking things together" approach works too, then we can still replace the approach, but I suspect we never will.
