### ISSUE TITLE
sql: backfill TableDescriptor_CheckConstraint.ColumnIDs slices from pre-2.0 releases

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#47265]
This is a bug introduced with #22322 

If a CHECK constraint is created in v1.x (pre-2.0) and then brought into a cluster in v2+, either via an upgrade or a RESTORE, then `pg_catalog.pg_constraints` will not be populated properly.

This is because the vtable constructor accesses the `.CheckConstraint.ColumnIDs` field directly, instead of using the `.CheckConstraint.ColumnsUsed()` accessor which is able to re-construct the data when it's missing.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
Good catch, we should be using `TableDescriptor_CheckConstraint.ColumnsUsed()` here:
https://github.com/cockroachdb/cockroach/blob/bc2d311f68209972ae3ca417331aa02a170a5adc/pkg/sql/pg_catalog.go#L967

How did you find this?

**Comment by knz** [comment]
This morning I reviewed `git log --patch` on `structured.proto` to find out all the things that didn't have a natural "what if this field was not populated" behavior.

**Comment by nvanbenschoten** [comment]
By the way, this bug was introduced in https://github.com/cockroachdb/cockroach/pull/22323, not #22322.

**Comment by knz** [comment]
I think it's the combination of the two actually

**Comment by nvanbenschoten** [comment]
It's strange though. I wrote https://github.com/cockroachdb/cockroach/pull/22322 specifically to enable https://github.com/cockroachdb/cockroach/pull/22323/commits/19980b5495f22f4ef137131f97909057166ea989, and then... promptly forgot about the accessor that had just been added.

Anyway, I can write a patch for this if you want. Just let me know if you're not already working on this.

**Comment by knz** [comment]
I cc'ed you on this because you wrote the original PR. However, both this issue and its two friends #47267 and #47263 are nominally on the SQL schema team's shoulders.

I'd recommend @jordanlewis advises how he recommends to handle this.

**Comment by nvanbenschoten** [comment]
It's a one-line fix. I'll send a patch to @jordanlewis.

**Comment by nvanbenschoten** [comment]
I just tried to reproduce this by walking through CRDB versions in Docker to see whether the fix works, and it turns out that there's not a bug here to begin with. The line in question isn't touching the table descriptor directly. Instead, it's touching a `ConstraintDetail` that was returned from `GetConstraintInfoWithLookup`. The thing we missed in that commit was that it also added https://github.com/cockroachdb/cockroach/pull/22322/commits/8d37935253186473e7022d66d023f5d2639781bf#diff-25f86d65061dc37b0bb41d0d098eca73R2359. That calls into `CheckConstraint.ColumnsUsed()` and handles the migration. The post-migrated struct is accessed in `pg_constraints`.

So I think the remaining task is to actually address this TODO so that we don't need to worry about this state anymore:
https://github.com/cockroachdb/cockroach/blob/3967538f10b8382359d6f12063f9dda6c22f9bb0/pkg/sql/sqlbase/structured.go#L3616-L3618

**Comment by nvanbenschoten** [comment]
I've reworked this issue a little to reflect that. I'll hand the rest off to Jordan to prioritize.

**Comment by lucy-zhang** [comment]
We're not planning to do anything further on this.
