### ISSUE TITLE
kv/kvserver: better throttling/pacing of the consistency queue for bigger disks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#47290]
The consistency checker queue periodically loops over all of the replicas on a node, and for each replica that the node holds the lease for, it initiates a consistency check operation. The consistency check operation involves computing a SHA 512 checksum for the data in the range at a particular point in time on all replicas. This is somewhat expensive in terms of both CPU and IO, but has been immensely valuable in tracking down bugs.

Right now there is a single knob to control the consistency checker pacing: `server.consistency_check.interval`. This setting defaults to `24h`. So every `24h` we expect to scan over all of the data in a cluster. With 1 TB of data on a node, we expect this scanning to produce a steady hum of 12 MB/sec of disk read traffic. That is already high, but perhaps tolerable. With 10 TB of data on a node, this scanning would produce a roar of 120 MB/sec of disk read traffic.

![Screen Shot 2020-04-09 at 2 19 11 PM](https://user-images.githubusercontent.com/6201335/78927745-66074d80-7a6d-11ea-80d6-6ec8acd45f30.png)

Note the drop-off in disk read traffic when the consistency check interval was turned much higher (`10000h`) at 18:03.

The graph above was from a cluster doing a large import and each node had ~1.7 TB of data. The read traffic is higher than expected. I believe, but haven't proven, that is due to another deficiency of the consistency queue: it tends to queue and process new ranges immediately when they are created during splits, rather than spreading out their checking over the check interval.

In order to handle 10 TB of data per node, we need to significantly reduce the background read traffic of consistency checks. I suspect we'd be better served by a knob which throttles the rate rather than one that controls the frequency.

**Comment by tbg** [comment]
We can introduce a `rate.NewLimiter()` backed by a cluster setting (`server.consistency_check.max_rate`?) here

https://github.com/cockroachdb/cockroach/blob/73b22520154f9bb0ef4b7b6df25fea66c1942682/pkg/kv/kvserver/replica_proposal.go#L238

Impl hints:

The cluster setting would be set up similar to [`kv.snapshot_rebalance.max_rate`](https://github.com/cockroachdb/cockroach/blob/0ced104f8e9fdd0ba8483a8b50cb02879083959b/pkg/kv/kvserver/store_snapshot.go#L828) except without an env var, and would live at the top of `replica_consistency.go`.

Additionally, [`collectChecksumTimeout`](https://github.com/cockroachdb/cockroach/blob/f0f6aa3a72fabd794c226b61fa8f6f13ca4fffbe/pkg/kv/kvserver/replica_consistency.go#L65) can't be static any more. I'm tempted to just remove it since the queue (the primary caller of this) already has a timeout (in the context).

Once that's done, we need to make sure the default consistency queue timeout of one minute is adaptable as well, namely we need to define a `processTimeoutFunc` here:

https://github.com/cockroachdb/cockroach/blob/0ced104f8e9fdd0ba8483a8b50cb02879083959b/pkg/kv/kvserver/consistency_queue.go#L52-L61

I think it should be a static component (like `15s`) plus something that depends on the approximate size of the range times the rate limit (with a large enough fudge factor).

[See here](https://github.com/cockroachdb/cockroach/blob/0ced104f8e9fdd0ba8483a8b50cb02879083959b/pkg/kv/kvserver/raft_snapshot_queue.go#L54) for an example of what one looks like.

On a related note, for large ranges we also need to make the consistency checker diffs streaming: https://github.com/cockroachdb/cockroach/issues/21128 (a larger change - out of scope here).

**Comment by nvanbenschoten** [comment]
> I suspect we'd be better served by a knob which throttles the rate rather than one that controls the frequency.

It seems like there are two concerns here. The first is that we are worried that the consistency checker is run non-stop on nodes with a sufficiently large amount of data. The second is that we are worried about the impact on foreground traffic that iterating over a range without throttling can have. Unless I'm missing something, these are orthogonal concerns. For instance, we will still occasionally see problems from the latter concern even with small data sizes, just less frequently.

If we are only concerned about the first issue - reading constantly when the duration to scan over all ranges on a node exceeds 24h - there might be an easier solution. We could place a minimum value on the [`consistencyQueue.timer` delay](https://github.com/cockroachdb/cockroach/blob/bb20495b3a9762a43bec426b36b64f4dea03d024/pkg/kv/kvserver/consistency_queue.go#L147) so that there's always some delay between processing two sequential ranges. We do the same thing elsewhere. This may be less effective now that the range size has grown to 512 MB.

If we are also concerned about the impact of reading an entire range as fast as possible when performing a consistency check then we'll need rate limiting down around `Replica.sha512`, like @tbg said.

I'm realizing that I don't have a good mental model for how rate-limiting the use of an LSM iterator impacts foreground traffic. If we are worried about exhausting CPU resources then I guess staying out of hot loops helps because it avoids pinning a thread for some amount of time. However, I would expect it to actually place a larger amount of total compute load on the system because the task would hang around longer and would perform more context switches in and out of its work. If we're worried about exhausting I/O resources then the impact of throttling depends on specifics in the storage engine. If an iterator accesses an SST, will the entire file be read without throttling even if my use of the iterator itself is throttled? Does I/O prefetching come into play here? I guess I'm wondering if throttling at the iterator level is sufficient or whether we need to push a throttling/priority policy deeper into the storage engine for this to have the desired effect of not being disruptive to foreground traffic. Maybe @petermattis has thoughts here.

**Comment by petermattis** [comment]
Good point about needing to pace within `Replica.sha512`, especially with larger range sizes. Do we need to be concerned about the consistency checker running non-stop if we sufficiently pace `sha512`?

> I'm realizing that I don't have a good mental model for how rate-limiting the use of an LSM iterator impacts foreground traffic. If we are worried about exhausting CPU resources then I guess staying out of hot loops helps because it avoids pinning a thread for some amount of time. However, I would expect it to actually place a larger amount of total compute load on the system because the task would hang around longer and would perform more context switches in and out of its work. If we're worried about exhausting I/O resources then the impact of throttling depends on specifics in the storage engine. If an iterator accesses an SST, will the entire file be read without throttling even if my use of the iterator itself is throttled? Does I/O prefetching come into play here? I guess I'm wondering if throttling at the iterator level is sufficient or whether we need to push a throttling/priority policy deeper into the storage engine for this to have the desired effect of not being disruptive to foreground traffic. Maybe @petermattis has thoughts here.

Neither Pebble nor RocksDB do prefetching no normal iteration An iterator reads an sstable a block at a time. An iterator pins in memory the metadata for the sstables it is currently pointing at, and the data block within the sstable. 

I'm pretty sure that rate limiting above the iterator would be sufficient. Put another way, I'm not sure what additional goodness we'd implement by pushing the rate limiting into the iterator itself.

**Comment by tbg** [comment]
> It seems like there are two concerns here. The first is that we are worried that the consistency checker is run non-stop on nodes with a sufficiently large amount of data. The second is that we are worried about the impact on foreground traffic that iterating over a range without throttling can have. Unless I'm missing something, these are orthogonal concerns. For instance, we will still occasionally see problems from the latter concern even with small data sizes, just less frequently.

I had implicitly made the assumption that the only concern is really the second about throttling `sha512`. Is anyone seeing a benefit to additionally enforcing "pauses" between consistency checks in addition to enforcing a minimum interval between checks for the same range (which is what we have today)?

**Comment by tbg** [comment]
Oh, I see now that it looked as if I was suggesting pacing calls to `sha512`. Yeah, we don't want that. It should be inside `sha512`.

**Comment by petermattis** [comment]
> I had implicitly made the assumption that the only concern is really the second about throttling sha512. Is anyone seeing a benefit to additionally enforcing "pauses" between consistency checks in addition to enforcing a minimum interval between checks for the same range (which is what we have today)?

Pacing the `sha512` computation itself seems sufficient to me. As I mentioned before, I'm pretty sure this pacing can be done in that method and doesn't need to be pushed into Pebble/RocksDB.
