### ISSUE TITLE
pg_catalog related problems

### ISSUE THREAD

**Issue by nawafHinai** [cockroachdb/cockroach#47376]
when using nodejs 12
**TypeORM version:0.2.24
pg driver version: 8.0.2

when You connect to cockroach db for the first time every thing goes smooth without any errors,
but when you restart the application or start another instance,
you will face "pg_catalog" related problems caused by -as I think- the PrimaryColumns,

when the PrimaryGeneratedColumn() set to rowid the Error will be:
![rowid_error](https://user-images.githubusercontent.com/43580372/79048693-f097aa80-7c2f-11ea-855d-0cb84bc874f7.JPG)

when the PrimaryGeneratedColumn() set to uuid the Error will be:
type 'pg_catalog"."uuid' does not exist
![uuid_error](https://user-images.githubusercontent.com/43580372/79048691-eecde700-7c2f-11ea-9732-94d0837093ea.JPG)

uuid_error

please report this issue

**Comment by nawafHinai** [comment]
Update:
same error happens when you try to generate migrations.
I think this caused by some thing when typeorm load the current schema of the database.

anybody have Ideas?

**Comment by otan** [comment]
@rafiss / @apantel ?

**Comment by rafiss** [comment]
Sorry, I missed this in in my inbox.

It might relate to this issue: https://github.com/cockroachdb/cockroach/issues/43177

@nawafHinai could you share some code that reproduces this problem? Also, which version of CockroachDB are you using?

**Comment by nawafHinai** [comment]
I am using typeorm and the nodejs pg connector.
the code is clear and its working smoothly with postgres.

but with cockroach db it will work for the first connection but in the second time it will fail and it will give me the above error.

It always  says type 'pg_catalog"."uuid' does not exist' or type 'pg_catalog"."int8' does not exist, what ever type I put as primaryColumn it give me this error.

**Comment by nawafHinai** [comment]
CockroachDB  v19.2.5

**Comment by rafiss** [comment]
Thank you for the additional details. I agree with you that it seems like there is a bug in CockroachDB. There is still more information that I would need in order to debug this issue. The ideal way to provide that information is for you to share a code sample that reproduces the problem. Would it be possible for you to do that, without sharing any sensitive data?

For example, I'd like to know which user you are using to connect to the database. What permissions does this user have?

One data point: I was able to follow the [TypeORM tutorial](https://github.com/typeorm/typeorm#quick-start) (which uses PrimaryGeneratedColumn), and I did not encounter this error.

**Comment by nawafHinai** [comment]
I have tested this code and the same error happend.

[https://github.com/nawafHinai/cockroach-typeorm-error]

and it always happen when typeorm try to get the current database schema, because does not happen on the first time connection to the database.

**Comment by nawafHinai** [comment]
the code in this [repo](https://github.com/nawafHinai/cockroach-typeorm-error)

**Comment by rafiss** [comment]
Thank you for providing the reproduction example. The cause of your issue is this line in `ormconfig.json`:
```
    "type": "postgres",
```

You should change that so it says `"type": "cockroachdb",`

If you have a problem after doing that, please re-open this issue or file a new one.
