### ISSUE TITLE
Prevent sending batches to decommissioned nodes

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#47459]
**Describe the problem**

It is currently possible to send a batch to a node that is decommissioned, based on an outdated cached range descriptor (https://github.com/cockroachdb/cockroach/blob/82fec00c83d4bfe35b906264ccb568568cec15b7/pkg/kv/kvclient/kvcoord/dist_sender.go#L500). In case when the descriptor shows a replica on a node that completed the decommissionning - we can either skip that replica or reload the range descriptor.
 
**To Reproduce**

- access a range on n1 from n2
- decommission n1 (making sure that the range won't rebalance to n2)
- try to access the range again from n2

**Expected behavior**
The replicas on the decommissioned nodes should be skipped (https://github.com/cockroachdb/cockroach/blob/82fec00c83d4bfe35b906264ccb568568cec15b7/pkg/kv/kvclient/kvcoord/dist_sender.go#L511)

The impact of this bug is that we will incur a round trip latency the first time that we do something on a range with a stale descriptor if we choose a replica that doesn't exist anymore. This by itself isn't a big deal but can surface another issue - as in #47460

**Comment by andreimatei** [comment]
I'm pretty confused about this issue, now that I re-read it. Do we understand why the stale descriptor wasn't evicted from the cache once the real leaseholder is found? I think that's what's supposed to happen here. I assume it probably has something to do with the error being ambiguous (#47460), but why was the error ambiguous if the node was long dead? Something's missing here for me.

**Comment by erikgrinaker** [comment]
@aliher1911 Maybe we should have a look at this since we've been making changes in this area anyway (#66199). I'm not really too worried about the extra latency of hitting a decommissioned node once due to a stale descriptor (it's not really that different from a stale lease or range descriptor), as long as caches are evicted and the request retried. If checking the decom state and skipping the replica is trivial then maybe we can add a check for that (which also needs to evict from caches), but otherwise I think we can close this as long as we handle the error gracefully.

**Comment by aliher1911** [comment]
I tried to repro that in a testcluster in following cases:
- put data in scratch range
- decommission leaseholder for that range
- try to read or write data to that range using node without replicas or non non leaseholder replica from that range
I don't see any ambiguous errors or attempts to talk to talk to decommissioned node, only heartbeat rejections that are retried immediately. The code is very different with 19.x where it was reported I assume.

**Comment by erikgrinaker** [comment]
Great, I think we can consider this fixed by #66199 then, so closing this.
