### ISSUE TITLE
kv: TestStoreRangeMergeRHSLeaseExpiration timeout under testrace

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#47503]
Something got stuck for 45 minutes.

The log only has periodic `StorePool missing descriptor for local store`.

https://teamcity.cockroachdb.com/viewLog.html?buildId=1876754&buildTypeId=Cockroach_MergeToMaster

Attaching the logs
[TestStoreRangeMergeRHSLeaseExpiration.txt](https://github.com/cockroachdb/cockroach/files/4479067/TestStoreRangeMergeRHSLeaseExpiration.txt)

@tbg any chance you can look at this one?

**Comment by tbg** [comment]
Repros in $TESTTIMEOUT via

make stress PKG=./pkg/kv/kvserver/ TESTS=TestStoreRangeMergeRHSLeaseExpiration TESTTIMEOUT=5m 2>&1 | tee log

(5m is too high, probably can set 1m and see it faster)

**Comment by tbg** [comment]
The test starts a merge, invalidates the RHS lease, and sends 10 gets to a magic key. The main goroutine of the test waits for all 10 latches to be acquired, but this isn't happening. I can see that all 10 gets return NotLeaseholderError. I think this might just be the case in which the RHS loses the lease before the gets arrive, in which case they never acquire any latches but just bounce off the leaseholder check. The main goroutine is then deadlocked reading from a channel that will never get written to. Going to confirm and send out a fix.

**Comment by tbg** [comment]
Ah, close but I got it wrong. The test wants all of the requests to go to the newly minted leaseholder n1 (the lease on n2 was just expired as part of the test), so that they get stuck in a latch trap there. But sometimes some of the requests arrive at n1 before it has the lease, so it bounces early without acking the trap channel, and the test deadlocks. I suppose I can find a way to fix that.
