### ISSUE TITLE
server: consider changing the resolution order in --join list

### ISSUE THREAD

**Issue by vladdy** [cockroachdb/cockroach#47550]
I recently introduced the support of SRV record resolution for nodes from the `--join` list in #45815. It was found by @darinpp to cause an issue when SRV lookup failed with ambiguous error like below in some environment: 

```
ERROR: failed to initialize node: failed to lookup SRV record for "REDACTED_NODE": lookup REDACTED_NAME on REDACTED_ADDRESS_PORT: server misbehaving
```

Since currently only `no such host` errors are ignored for SRV lookups, the problem led to inability to start nodes as there was no way to override the resolution order. 

During the investigation, I found that the above error message can happen both in temporary and permanent cases, but it was confirmed to be the temporary case of unknown DNS response: https://github.com/golang/go/blob/7bb33179cadf072403b2f1d8f8210c5ae414d135/src/net/dnsclient_unix.go#L203-L210

It would be a good time now after we got the feedback to review the implementation in order to make the resolution more robust and prevent related startup failures. At least three options can be considered:

1. Just handle the error like above and use this logic to swallow errors from `LookupSRV()`: `DNSError && IsNotFound || (IsTemporary && message="server misbehaving")`. The drawback here is that should any other error which we do not expect occurs, it will be a permanent failure preventing node startup.

2. Make the host lookup first and try to resolve SRV record as the last resort. This would require those who migrate to SRV records to create records different from existing hostnames. On the other hand, this allows the user to use `/etc/hosts` override in case they need to configure an override locally.

3. Introduce a way to designate SRV records (i.e. with `srv:` prefix) in the list which increases the complexity.

cc @knz, @bdarnell for opinion

By the way, I noticed that I overlooked the fact that `net.DNSErr` comes with useful error types which I'm going to switch us to instead of error message comparison.

**Comment by vladdy** [comment]
Just forgot to mention that personally I would prefer the option 2

**Comment by bdarnell** [comment]
It may be the case in k8s that SRV records are used on names that don't also have A records, but in my past experience with SRV records (at google) it's common to use SRV records on a name that also resolves normally. If both SRV and A records exist, SRV is expected to take precedence (this is specified in https://tools.ietf.org/html/rfc2782). So I don't like option two.

I'd vote for option 1 but take it even further: *all* errors resolving SRV records should be non-fatal and allow us to continue to regular resolution. We want to make sure to log the error if it occurs (unless it's a known clean error like "no such host"), but it should never block the rest of the process. (RFC 2782 also recommends continuing after all errors from the SRV lookup).

In the long term I think allowing more resolution types as in option 3 is a good idea. We had that before but ripped it out because regular hostnames were the only resolver in use and the rest were rotting. I think I'd rather wait to reintroduce more structure to the `--join` flag until we have more examples of how it'd be used (for example, I think instead of just a `srv:` prefix, we may want a sort of key-value model like we have for the `--store` flag).

**Comment by knz** [comment]
@vladdy did you plan to implement this improvement?

**Comment by vladdy** [comment]
Yep, I'll start working on this asap, just wanted to get some consensus on how to proceed.
