### ISSUE TITLE
storage: make cmdQ and tsCache concurrent

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#4768]
I saw nvanbenschoten make some improvement in `cmdQ` and `tsCache`.
It's a very good progress. But I have some other opinions.
When we use cmdQ or tsCache, we have a big locker like:

```
        r.mu.Lock()
        var wg sync.WaitGroup
        var spans []roachpb.Span
        readOnly := ba.IsReadOnly()
        for _, union := range ba.Requests {
            h := union.GetInner().Header()
            spans = append(spans, roachpb.Span{Key: h.Key, EndKey: h.EndKey})
        }
        r.mu.cmdQ.GetWait(readOnly, &wg, spans...)
        cmdKeys = append(cmdKeys, r.mu.cmdQ.Add(readOnly, spans...)...)
        r.mu.Unlock()
```

It will block the system performance heavily when there are concurrent request. 
Especially when each request(batch) has lots of cmds(will do more work in locker area, make other go routine wait more time)
I fact, when there are rare conflict, nvanbenschoten's solution will enlarge the locker area(because need more time to analysis) and decrease the system tps.
And my opinion is: "Because each item in tsCache will removed after 10 second, and each item in cmdQ will removed after several millisecond, So it's not worth to do much work for each item. the life of them are too short"
I saw currently we use red-black tree as base for them. red-black tree is hard for concurrence.
I'm doing some research on it, use skiplist to replace red-black tree and make them concurrent.
And here is preliminary benchmark result:
![read32](https://cloud.githubusercontent.com/assets/15647248/13453927/d197eca8-e08e-11e5-8ff1-d08b52981511.PNG)
I the test, I make a client to query value for rand key, and each batch has 32 queries(reads). 
The client can run with n threads. When I increase client threads number, you can see the system tps can't increase in current solution, But can increase obviously in my new solution.

Do you agree this improvement direction? I will try to complete it ASAP.

**Comment by petermattis** [comment]
Concurrent skip-lists are neat data structures and the improvement in the graph is certainly nice. I'd be curious to see what you've done as it isn't obvious to me how to adapt the existing CommandQueue and TimestampCache to a lockless approach.

**Comment by petermattis** [comment]
@changrui82 Did anything become of your work here? I'm taking a look at timestamp cache performance right now and it is significant even in the absence of contention.

**Comment by changrui82** [comment]
I have some trouble to submit my code yet.
I can give a summary for my solution:
first, we have two kinds of command, single key command and interval command.
then, we can use concurrent skiplist to save single key command in tsCache, and use concurrent interval tree to save interval command in tsCache. When write command need to do check in tsCache, it should check both skiplist and interval tree.
We can just don't do rotate to make interval tree can concurrent, although it may make the interval tree unbalance. In fact, only interval command will save into interval tree, unbalance is not a big problem. As for delete, because tsCache has lowWater, we can create a new interval tree(and a new skiplist) every 10 seconds, and drop the whole old interval tree(and the skiplist) after 10 seconds.

cmdQueue is a little more complex then tsCache. We also use skiplist plus interval tree to save each command in cmdQueue. But we need to give each batch a index serially, then we can insert them to interval tree(and skiplist) concurrently.
We need to add a batch into cmdQueue first, then try to do `getWait`, in order to make each command can be seen by newer command.

Hope this can make some help.

**Comment by petermattis** [comment]
Thanks for the write-up @changrui82. The recent `TimestampCache` and `CommandQueue` changes have significantly reduced the burden on the interval tree. For the `TimestampCache` we avoid the interval tree completely in common cases. That said, I imagine there are workloads where improvement is still possible. Having separate structures for single-key requests and interval requests is an idea worth keeping in mind.

**Comment by nvanbenschoten** [comment]
I revisted this after the discussion on #31904 and I think there is something that could be improved here with the `CommandQueue`. The lock we put around `getPrereqs` and `add` is serving two purposes, and with the right data structure, one of those roles goes away. The first role of the lock is to sequence commands that need to be ordered. The second role is to provide exclusive access to llrb-backed interval tree because the structure is not thread-safe. Only this first role is strictly necessary. Taking that logic a bit further reveals that we're very pessimistic with our sequencing, as non-interfering commands (non-overlapping commands or multiple reads) don't need to be strictly sequenced at all.

To make this more concrete, here is the current order of operations that we perform:
```
lock
getPrereqs (and pull into a slice, with tricks to reduce the size of this slice)
add new command
unlock
...
iterate over slice and wait for prereqs
...
lock
signal dependents
remove command
unlock
``` 

With a concurrent data structure, we could turn this into:
```
lock
pick seq num
add new command with seq num
unlock
...
iterate over data structure itself for prereqs, ignore higher seq nums, wait as we iterate
...
signal dependents
remove command
```

We see that we no longer need to collect the prereqs under the first lock, which is the most expensive operation that the CommandQueue performs. We also don't need to synchronize between insertion and removal, which https://github.com/cockroachdb/cockroach/issues/22340#issuecomment-415861574 revealed to be an issue. 

Furthermore, the first lock here doesn't even need to provide full mutual exclusion. It could be some kind of lock-free queue that only enforces an order between overlapping requests (an optimistic mini-command queue with reduced granularity?). This would permit full concurrent access to the CommandQueue by any non-overlapping requests.

There are still a lot of unknowns here, but it's worth thinking about this. I suspect that a structural improvement like this would allow us to speed thing up while removing a lot of the optimizations that have built-up over time and provide a cleaner abstraction, all at the same time.

**Comment by nvanbenschoten** [comment]
Addressed by https://github.com/cockroachdb/cockroach/pull/32251.
