### ISSUE TITLE
go1.14: unsafe pointer conversion failure

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#47684]
I was trying to write a test for #47440 and query cancellation, and ran into this error: 
```
fatal error: checkptr: unsafe pointer conversion

goroutine 346 [running]:
runtime.throw(0x8f6aef3, 0x23)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72 fp=0xc001294080 sp=0xc001294050 pc=0x40374a2
runtime.checkptrAlignment(0xc000a5e480, 0x8b64c40, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/checkptr.go:18 +0xb7 fp=0xc0012940b0 sp=0xc001294080 pc=0x4008cd7
github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.leafToNode(...)
	/Users/rohany/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/latch_interval_btree.go:113
github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.newLeafNode(0xc00059e6d0)
	/Users/rohany/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/latch_interval_btree.go:133 +0x78 fp=0xc0012940e0 sp=0xc0012940b0 pc=0x774c5a8
github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.(*btree).Set(0xc00059e6d0, 0xc000126040)
	/Users/rohany/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/latch_interval_btree.go:712 +0x3a7 fp=0xc001294170 sp=0xc0012940e0 pc=0x77512d7
```

To repro, add this test to a test in the `sql` package:
```
func TestCancelVirtualTableGenerator(t *testing.T) {
	defer leaktest.AfterTest(t)()
	const queryToCancel = "SELECT * FROM pg_catalog.pg_type"
	cancelQuery := fmt.Sprintf("CANCEL QUERIES SELECT query_id FROM [SHOW CLUSTER QUERIES] WHERE query = '%s'", queryToCancel)

	// conn1 is used for the query above. conn2 is solely for the CANCEL statement.
	var conn1 *gosql.DB
	var conn2 *gosql.DB

	tc := serverutils.StartTestCluster(t, 2 /* numNodes */, base.TestClusterArgs{})
	defer tc.Stopper().Stop(context.TODO())

	conn1 = tc.ServerConn(0)
	conn2 = tc.ServerConn(1)

	errChan := make(chan error)
	go func() {
		_, err := conn1.Exec(queryToCancel)
		errChan <- err
	}()
	_, err := conn2.Exec(cancelQuery)
	if err != nil && !testutils.IsError(err, "query ID") {
		t.Fatal(err)
	}

	err = <-errChan
	if err == nil {
		// A successful cancellation does not imply that the query was canceled.
		return
	}
	if !isClientsideQueryCanceledErr(err) {
		t.Fatalf("expected error with specific error code, got: %s", err)
	}
}
```
and then run `make stressrace PKG=./pkg/sql/ TESTS=TestCancelVirtualTableGenerator`. There is a test doing something similar to this (`TestCancelDistSQLQuery`) but something seems to go wrong accessing a virtual table. It doesn't seem to matter what virtual table is queried. I don't know how serious of an issue this actual is because it seems to work under `make stress`. I can reproduce this on commit ba19aa446d99afa159ee5bd915e31de46940ef90.

**Comment by nvanbenschoten** [comment]
Thanks for filing @rohany. This warning is firing because you're running go1.14. In the latest version of Go, the race builds default to enabling `-d=checkptr` instrumentation: see https://github.com/golang/go/issues/34964 and https://go-review.googlesource.com/c/go/+/162237. 

> This CL adds -d=checkptr as a compile-time option for adding
instrumentation to check that Go code is following unsafe.Pointer
safety rules dynamically. In particular, it currently checks two
things:
> 1. When converting unsafe.Pointer to *T, make sure the resulting
pointer is aligned appropriately for T.
> 2. When performing pointer arithmetic, if the result points to a Go
heap object, make sure we can find an unsafe.Pointer-typed operand
that pointed into the same object.

The dynamic check is complaining about a very real thing. In that btree implementation, we deliberately violate type safety in order to avoid the runtime cost associated with polymorphism. The check complains when we cast a pointer of a smaller struct to that of a larger struct, as it should:
https://github.com/cockroachdb/cockroach/blob/666a0ac62832b6884bc6b039b4c944dbb42924aa/pkg/kv/kvserver/spanlatch/latch_interval_btree.go#L112-L114

This would generally be pretty bad because, if we weren't careful, the pointer to the larger struct now gives us access to the memory owned by other heap objects or unallocated memory. In this case, though, we are being careful. Any `node` struct in the btree impl is careful to avoid accessing its `children` array if its `leaf` field indicates that it is actually a `leafNode` struct. [Here's](https://github.com/cockroachdb/cockroach/blob/666a0ac62832b6884bc6b039b4c944dbb42924aa/pkg/kv/kvserver/spanlatch/latch_interval_btree.go#L431) an example of that behavior at play.

So this check is firing for a completely valid reason, but it's not telling us anything we weren't already aware of. We're going to need to address this before upgrading to go1.14. So far, I've been simply disabling the check in race builds using `-d=checkptr=0` with the idea that we'll eventually want to do more when we move to go1.14. The actual patch we might consider looks something like:
```
diff --git a/Makefile b/Makefile
index 79f7d28170..ba272c94b3 100644
--- a/Makefile
+++ b/Makefile
@@ -988,7 +988,7 @@ testbuild:
 testshort: override TESTFLAGS += -short

 testrace: ## Run tests with the Go race detector enabled.
-testrace stressrace roachprod-stressrace: override GOFLAGS += -race
+testrace stressrace roachprod-stressrace: override GOFLAGS += -race -gcflags=-d=checkptr=0
 testrace stressrace roachprod-stressrace: export GORACE := halt_on_error=1
 testrace stressrace roachprod-stressrace: TESTTIMEOUT := $(RACETIMEOUT)

@@ -1056,7 +1056,7 @@ testbaselogic testccllogic testoptlogic: TESTFLAGS := -test.v $(if $(FILES),-sho
 testbaselogic testccllogic testoptlogic:
        cd $($(<F)-package) && $(<F) -test.run "$(TESTS)" -test.timeout $(TESTTIMEOUT) $(TESTFLAGS)

-testraceslow: override GOFLAGS += -race
+testraceslow: override GOFLAGS += -race -gcflags=-d=checkptr=0
 testraceslow: TESTTIMEOUT := $(RACETIMEOUT)

 .PHONY: testslow testraceslow
``` 

However, reading back over the original [CL](https://go-review.googlesource.com/c/go/+/162237) that introduced the check, I'm noticing that they also added a new `//go:nocheckptr` annotation. I'll play around with that to see if we can disable this check at a more granular level.

**Comment by rohany** [comment]
Wow, thanks for the detailed explanation! Do you remember what sort of performance difference removing extra pointer derefs caused by pushing `leafNode` and `node` to an interface gave?

**Comment by nvanbenschoten** [comment]
No, unfortunately, I don't have any numbers for that off the top of my head. If I had to make a guess based on my memory of the magnitude of some of the other optimizations that went into it though, I'd estimate it would add somewhere around 200ns per lookup and insertion, which would be about a 20-30% perf hit. The cost would mostly be due to the need for dynamic dispatch to access fields in these node structs. That's a complete guess, though.
