### ISSUE TITLE
sql: investigate performance impact of kvBatchSize settings

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#4772]
PR #4759 introduces fetching of key values in batches of `kvBatchSize` (set to 10,000).

Single-node experiments showed that batch size of 1000+ was enough to not cause performance degradation. We should also perform multi-node experiments to get an idea of what the impact of changing this value is.

**Comment by spencerkimball** [comment]
@RaduBerinde, has anything been done here? I'm removing the 1.0 milestone as this is not required for 1.0. Could you add a comment describing any work that has been done here in the past year?

**Comment by RaduBerinde** [comment]
There were single-node experiments done as part of the original change. I don't think any multi-node experiments were run comparing batch sizes. While there may be some potential performance gains here, I think we should first explore improving the interface (#13193).

Note that with DistSQL most KV batches would be local, so it likely wouldn't benefit from larger batch sizes.

**Comment by spencerkimball** [comment]
@RaduBerinde based on your comment, I'm in favor of closing this issue. It doesn't sound like there's a reasonable expectation of doing work on this issue unless we run into it in performance testing. Please re-open if you disagree.

**Comment by a-robinson** [comment]
Re-opening in the spirit of not keeping performance experiments that we want to run bottled up in our heads, since I've been wanting to play with this ever since seeing us do 20-30 separate scans  per range in https://github.com/cockroachdb/cockroach/issues/18159. As @RaduBerinde mentioned this isn't a huge deal when distsql is being used for a query, but distsql isn't used for all queries (as we were seeing in #18159) and presumably won't be for a while.

And cc @andreimatei given his interest in scan performance.
