### ISSUE TITLE
cli: implement cockroach quit with --cert-principal-map

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#47754]
**Describe the problem**
`cockroach quit` command doesn't work with a cluster started with the following pattern **`cockroach start-single-node --certs-dir=certs --cert-principal-map=node.example.com:node,artem:root --background`

**To Reproduce**
Follow the [openssl](https://www.cockroachlabs.com/docs/dev/create-security-certificates-openssl.html) guide and start cluster with `--cert-principal-map`. Then issue `cockroach quit --url 'postgres://'`. The end result is
```
cockroach quit --url='postgres://node.example.com:26257?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.artem.crt&sslkey=certs/client.artem.key&sslmode=verify-full'
Usage:
  cockroach quit [flags]

Flags:
      --certs-dir string
                                                                                    Path to the directory containing SSL certificates and keys.
                                                                                    Environment variable: COCKROACH_CERTS_DIR
                                                                                    (default "${HOME}/.cockroach-certs")
  -h, --help                                                                help for quit
      --host <addr/host>[:<port>]
                                                                                    CockroachDB node to connect to. This can be specified either as an
                                                                                    address/hostname, or together with a port number as in -s myhost:26257.
                                                                                    If the port number is left unspecified, it defaults to 26257. An IPv6
                                                                                    address can also be specified with the notation [...], for example
                                                                                    [::1]:26257 or [fe80::f6f2:::]:26257.
                                                                                    Environment variable: COCKROACH_HOST
                                                                                    (default :26257)
      --insecure
                                                                                    Connect to an insecure cluster. This is strongly discouraged for
                                                                                    production usage.
                                                                                    Environment variable: COCKROACH_INSECURE

      --url postgresql://[user[:passwd]@]host[:port]/[db][?parameters...]
                                                                                    Connection URL, e.g. "postgresql://myuser@localhost:26257/mydb". If
                                                                                    left empty, the connection flags are used (host, port, user, database,
                                                                                    insecure, certs-dir).
                                                                                    Environment variable: COCKROACH_URL

Global Flags:
      --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
      --no-color                         disable standard error log colorization
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)

ERROR: invalid argument "postgres://node.example.com:26257?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.artem.crt&sslkey=certs/client.artem.key&sslmode=verify-full" for "--url" flag: invalid file name for "sslcert": expected "client.root.crt", got "client.artem.crt"
Failed running "quit"
```

**Expected behavior**
cluster should shut down gracefully

**Environment:**
 - CockroachDB version 20.1.rc1
 - Server OS: OSX 10.15.4
 - Client app: cockroach cli

**Comment by dbist** [comment]
@petermattis FYI

**Comment by dbist** [comment]
passing the following `--url` makes no difference 
```
cockroach quit --url='postgres://node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.artem.crt&sslkey=certs/client.artem.key&sslmode=verify-full'
warning: --url specifies database "", but command "quit" does not accept a database name - database name ignored
Usage:
  cockroach quit [flags]

Flags:
      --certs-dir string
                                                                                    Path to the directory containing SSL certificates and keys.
                                                                                    Environment variable: COCKROACH_CERTS_DIR
                                                                                    (default "${HOME}/.cockroach-certs")
  -h, --help                                                                help for quit
      --host <addr/host>[:<port>]
                                                                                    CockroachDB node to connect to. This can be specified either as an
                                                                                    address/hostname, or together with a port number as in -s myhost:26257.
                                                                                    If the port number is left unspecified, it defaults to 26257. An IPv6
                                                                                    address can also be specified with the notation [...], for example
                                                                                    [::1]:26257 or [fe80::f6f2:::]:26257.
                                                                                    Environment variable: COCKROACH_HOST
                                                                                    (default :26257)
      --insecure
                                                                                    Connect to an insecure cluster. This is strongly discouraged for
                                                                                    production usage.
                                                                                    Environment variable: COCKROACH_INSECURE

      --url postgresql://[user[:passwd]@]host[:port]/[db][?parameters...]
                                                                                    Connection URL, e.g. "postgresql://myuser@localhost:26257/mydb". If
                                                                                    left empty, the connection flags are used (host, port, user, database,
                                                                                    insecure, certs-dir).
                                                                                    Environment variable: COCKROACH_URL

Global Flags:
      --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
      --no-color                         disable standard error log colorization
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)

ERROR: invalid argument "postgres://node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.artem.crt&sslkey=certs/client.artem.key&sslmode=verify-full" for "--url" flag: invalid file name for "sslcert": expected "client.root.crt", got "client.artem.crt"
Failed running "quit"
```

**Comment by petermattis** [comment]
@knz The error here is coming out of code you wrote: `pkg/cli/client_url.go`. Can you provide some guidance on how to fix? The code seems to be enforcing that the username specified in the URL matches up with the filename specified in the URL. Should we just relax that restriction. If the user wants to name the cert filename "foo.bar", shouldn't we allow that?

**Comment by knz** [comment]
The code in `client_url.go` exists for the following purpose: **we have made it possible to use --url also for CLI commands that don't use SQL** including e.g `cockroach init`.

The non-SQL commands are restricted by the logic around `--certs-dir` - they don't accept cert files named arbitrarily, they have to follow a particular pattern. This is why the URL parser is stricter than it needs to be for a SQL command.

In very particular, the check that the username matches the cert name is because we can't simply ignore the username: the username is the primary anchor for the human user to declare their *intent* to work with a particular account (e.g. `root` vs some non-root member of the `admin` group). If a user mistakenly pastes a URL for some random user, we want to *tell* them (via an error message) they made a mistake instead of silently accepting the username that was in the cert. 

There are two ways forward I think:

- pass an argument to the check to indicate which client is "consuming" the URL and only do the stricter checking for non-SQL commands
- apply the principal map before the username is checked to match the cert name

**Comment by petermattis** [comment]
Thanks for the background, @knz.

> The non-SQL commands are restricted by the logic around --certs-dir - they don't accept cert files named arbitrarily, they have to follow a particular pattern. This is why the URL parser is stricter than it needs to be for a SQL command.

I'm not quite understanding this statement. `--certs-dir` requires the certs and keys to follow a particular naming pattern, but if the certs and keys are specified in `--url`, how is `--certs-dir` involved (other than the existing check which seems unnecessary). I think I'm missing something here.

> In very particular, the check that the username matches the cert name is because we can't simply ignore the username: the username is the primary anchor for the human user to declare their intent to work with a particular account (e.g. root vs some non-root member of the admin group). If a user mistakenly pastes a URL for some random user, we want to tell them (via an error message) they made a mistake instead of silently accepting the username that was in the cert.

Are we looking at the principal in the cert on the client side? I don't think we are? My understanding is that we're validating that the cert/key filenames following the pattern `client.<user>.{crt,key}`. Update: I tested this and we are looking at the principal inside the cert. My original complaint was that we were only looking at the filename, but the checks are more extensive than that. 

> There are two ways forward I think:
> * pass an argument to the check to indicate which client is "consuming" the URL and only do the stricter checking for non-SQL commands
> * apply the principal map before the username is checked to match the cert name

The problem is happening for non-SQL commands, so I don't think the first option is feasible. For example:

```
~ ./cockroach quit --url="postgresql://root@localhost:26257?sslcert=certs/client.root.crt&sslkey=certs/client.root.key&sslmode=verify-full&sslrootcert=certs/ca.crt"
warning: --url specifies user/password, but command "quit" does not accept user/password details - details ignored
W200423 12:37:22.829478 1 security/certificate_loader.go:327  could not parse certificate for /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/certs/client.root.crt: failed to validate certificate 0 in file client.root.crt: client certificate has principals ["foo.crdb.io"], expected "root"
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.
```

`client.root.crt` contains `CN=foo.crdb.io` and the server was started with `--cert-principal-map=foo.crdb.io:root`. Doing these pattern and cert checks client sides seem excessive. Again, I think I'm missing something about the implementation that is making them desirable. So please provide gentle explanation.

Note that the behavior for the `quit` command differs from `sql` which succeeds for this URL:

```
./cockroach sql --url="postgresql://root@localhost:26257?sslcert=certs/client.root.crt&sslkey=certs/client.root.key&sslmode=verify-full&sslrootcert=certs/ca.crt" -e "select current_user()"
  current_user
----------------
  root
(1 row)
```

**Comment by knz** [comment]
So the starting point to understand this is that the non-SQL commands do not use a URL to connect via the SQL driver (obv.)

What they use instead is a struct that gives them

1) a username
2) whether to use TLS or not (the "insecure" bit)
3) a **cert directory** (i.e. not individual files) -- because the client code uses the same cert loader that the server uses and that works off a directory, not individual cert paths.

When a non-SQL command is passed a URL to work with, the URL parsing code will derive:

- the username from the username part of the URL
- whether to use TLS or not, based on whether `&sslmode=disable` is present in the query args or not
- the cert directory, by finding the common path prefix between the `&sslcert=` and `&sslkey=` parameters.

Because the cert loader code **determines the cert file name by concatenating the cert dir path with the username**, we want to avoid the following situation:

- the user passes some weird cert path with the *intention* to use the weird cert (their intention is spelled out in the URL)
- our code takes the path prefix of that, then derives an *unrelated* path name based off the path and the username and ends up using an unrelated cert.

So the URL checker will not only check that there's a common path prefix (to populate the cert dir field) -- it also verifies that the provided cert path is identical to the one that is derived, later+independently, by our cert loader code.

Does this clarify?

(All this situation becomes simpler/moot if we get rid of the server-side cert loader code for the client-side commands and let the client code work with the discrete file names specified in the URL.)

**Comment by petermattis** [comment]
> Does this clarify?
> 
> (All this situation becomes simpler/moot if we get rid of the server-side cert loader code for the client-side commands and let the client code work with the discrete file names specified in the URL.)

Yes, this clarifies. I've been piecing this together by looking at the code, but this explanation ties it all together. Using the server-side cert loader for the client-side commands seems to be the original sin. I wonder how difficult that will be to untangle.

**Comment by petermattis** [comment]
> Using the server-side cert loader for the client-side commands seems to be the original sin. I wonder how difficult that will be to untangle.

Here is the stack trace from `runQuit` through to usage of the `CertificateManager`:

```
github.com/cockroachdb/cockroach/pkg/base.(*Config).GetCertificateManager(0xc0006a8160, 0xe0aa4c8, 0xe0a3590, 0x203000)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/base/config.go:350 +0x93
github.com/cockroachdb/cockroach/pkg/base.(*Config).GetClientTLSConfig(0xc0006a8160, 0xe0aa4c8, 0xc000c10c08, 0x400e826)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/base/config.go:397 +0x38
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialOptions(0xc0008036c0, 0xc000242c30, 0xf, 0xc00068cb01, 0x30, 0x30, 0x7a11740, 0x60, 0x77dda20)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:667 +0x953
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialRaw(0xc0008036c0, 0xc000242c30, 0xf, 0x100000000, 0x4010aee, 0x758d0c0, 0xc00086be18, 0xc000c10ee8)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:893 +0x69
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:995 +0x7a
sync.(*Once).doSlow(0xc0002780dc, 0xc000c10fb0)
	/Users/pmattis/Development/go1.13/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/Users/pmattis/Development/go1.13/src/sync/once.go:57
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal(0xc0008036c0, 0xc000242c30, 0xf, 0x100000000, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:991 +0x1f2
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCUnvalidatedDial(...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:940
github.com/cockroachdb/cockroach/pkg/cli.getClientGRPCConn(0x840a6a0, 0xc000367840, 0xc0006a8160, 0xc000587500, 0xbebc200, 0xf, 0x4008000000000000, 0x400000, 0x100000, 0x200000, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:1309 +0x1bb
github.com/cockroachdb/cockroach/pkg/cli.getAdminClient(0x840a6a0, 0xc000367840, 0xc0006a8160, 0xc000587500, 0xbebc200, 0xf, 0x4008000000000000, 0x400000, 0x100000, 0x200000, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/quit.go:267 +0x65
github.com/cockroachdb/cockroach/pkg/cli.runQuit(0xaa2aa00, 0xc000383a00, 0x0, 0x1, 0x0, 0x0)
```

It's starting to make sense how we ended up in the current situation. I'm not seeing how to tease this apart yet.

**Comment by petermattis** [comment]
Tonight's idea: make `base.Config.certificateManager` an interface and populate it with a different `CertificateManager` implementation in client command contexts. More specifically, I'd make `base.lazyCertificateManager.cm` an interface.
