### ISSUE TITLE
rowexec: disk spilling hash joiner doesn't use `(EncDatum).Fingerprint

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#48130]
Repro:

Run the following logictest:
```
# LogicTest: fakedist-disk

statement ok
CREATE TABLE t1 (x INT[]);
CREATE TABLE t2 (x INT[]);
INSERT INTO t1 VALUES (ARRAY[1, 2, NULL, 3]);
INSERT INTO t2 VALUES (ARRAY[1, 2, NULL, 3]);

query T
SELECT * FROM t1 INNER HASH JOIN t2 ON t1.x = t2.x
----
{1,2,NULL,3}
```

It will fail with an error that it is trying to encode the array as a table key. This is because the `DiskRowContainer` uses `Encode` to create a key for the rows it contains. It doesn't look like the solution is just to use `Fingerprint` however -- it assumes it can decode the hashed key back into the row that was placed in the container. For some types of fingerprint (JSON (and soon not to be arrays)) this is not true.

Jira issue: CRDB-4354

**Comment by asubiotto** [comment]
From slack:

We only care about this for joins, right? One reason we use keys is because they provide a desired ordering. If we don't want that (I'm assuming fingerprinting doesn't provide ordering), I think using the same strategy as composite columns (storing the value to decode in the value) is the way to go. We probably will want to abstract out the encoding/decoding in some sort of strategy and use the current key encoding for containers that need ordering with the fingerprint strategy for those that don't.

**Comment by asubiotto** [comment]
Following up on my previous comment: I think that the specialized strategy is not necessary since the only type that should return an error will be JSON after your changes, and we currently don't support ordering by JSON.

What will need to be done after the array PR is to just use `Fingerprint` for a JSON key with that datum encoded as a value in the value similar to composite keys in order to support disk spilling when joining JSON. @rohany are you planning on doing this or just calling this limitation out?

**Comment by rohany** [comment]
I don't have the bandwidth for this right now, but I could take it at some point in the future.

**Comment by yuzefovich** [comment]
This no longer reproduces on master.
