### ISSUE TITLE
kv: error in consistency checker is silently ignored

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48171]
Found by @irfansharif while investigating https://github.com/cockroachlabs/support/issues/425

```
E200321 10:35:29.278249 832598208 storage/consistency_queue.go:128  [n4,consistencyChecker,s4,r4/14:/System/{NodeLive…-tsd}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E200321 10:35:29.278274 832598208 storage/queue.go:845  [n4,consistencyChecker,s4,r4/14:/System/{NodeLive…-tsd}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E200321 11:38:01.584825 835109410 storage/queue.go:845  [n4,raftlog,s4,r4/14:/System/{NodeLive…-tsd}] requested entry at index is unavailable
```

The consistency checker detects an invalid replica but does not stop the process to request further investigation.

I think this should be converted to log.Fatal. @tbg do you agree?

**Comment by tbg** [comment]
Where are you seeing an "invalid replica"? The contexts cancel, meaning the checksum computation did not finish in time. The way this works is that the checker puts a raft command through the range that triggers an async population of the checksum. The checker then sends a long-poll for the result, with a (I believe) 5s timeout. If the checksum is not available within 5s, for example because the range is unavailable or the node overloaded, you see this error. Definitely not a good idea to fatal in that circumstance.

**Comment by knz** [comment]
shouldn't the lack of result from the checker be a reason to suspend further operations on the range?

**Comment by tbg** [comment]
No. We should suspend further operations when the range is inconsistent. If we fail to establish that in the time limit we set ourselves for this operation, it usually means a lot of things but not that the range data has gone inconsistent.
