### ISSUE TITLE
sql,sqlbase: add leasing information to all descriptors

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#48250]
This issue deals with internal structure of where the relevant descriptor metadata used for leasing is stored. Today the only leased descriptor is the `*TableDescriptor`. The fields used for leasing are stored in that encoded protobuf. 

In order for a SQL query to execute, it needs to refer to the structure of the relevant schema artifacts. These artifacts are used for name resolution, permissions checking, planning, and execution. It is critical that during the execution of a query, that the schema in use remains valid. Today we achieve this generally though the use of leases on the table descriptor. This doesn't work perfectly w.r.t. resolving database names to IDs or the permissions on a database because we don't lease database information but it mostly works most of the time. It does work for our other needs because all of the rest of the relevant information for execution is stored on the `*TableDescriptor`. 

Table descriptor leases are handled very carefully to ensure that the validity of a lease is not violated by the commit of a transaction. 

Today we have just one leased piece of schema information, tables. Tables utilize the two-version leasing semantics which enable online schema changes (see [table descriptor leases RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20151009_table_descriptor_lease.md) and more broadly [online schema changes RFC]( https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20151014_online_schema_change.md))

**Describe the solution you'd like**

What's clear is that we want to lift the concepts which are critical for leases up out of the table descriptor. What's less clear is how best to do that. The fields in question are `version`, `modification_time`, `name`, and `id`. Perhaps `create_as_of_system_time` could live here but I'm not sure I see any reason for that. 

The proposal is that we create a new message `sqlbase.DescriptorMetadata` that lives in the `sqlbase.Descriptor` protocol buffer. During the migration, some of the fields will be duplicated in the children descriptors but we should remove those over time. The other slight awkwardness of this proposal is that we pass the explicit children of the protocol buffers around (i.e. `*sqlbase.DatabaseDescriptor` and `*sqlbase.TableDescriptor`) after unwrapping them from the `oneOf`. After this proposal, we'll need to pass around the `*sqlbase.Descriptor`. That seems fine to me. In practice we should be passing around structs which include these protos anyway.

**Describe alternatives you've considered**

Other alternatives which we've discussed have been to:

1) Store the metadata in a different column family in the `system.descriptor` table.

I'm not actively in favor of this because of the pain of migrating code which manually encodes and decodes descriptors.

2) Storing the metadata in a different table altogether.

This too feels like complexity for no benefit.

**Additional context**

Relates to #47070 

We'll need to make sure to migrate all existing descriptors. This can be a sqlmigration. The newer versions will need to look at both the new and old location for this information.

**Comment by ajwerner** [comment]
cc @lucy-zhang and @rohany 

I'm not sure why in the past we haven't discussed just augmenting the `sqlbase.Descriptor` proto. I'm suggesting we do this now.

**Comment by jordanlewis** [comment]
Oh yeah. I forgot about that too. Interesting...

**Comment by rohany** [comment]
Hmm, that seems like the most reasonable thing -- it already is providing us with the "common descriptor fields" that we've been talking about adding columns for.

**Comment by lucy-zhang** [comment]
+1 to putting the metadata in `sqlbase.Descriptor`.
> After this proposal, we'll need to pass around the `*sqlbase.Descriptor`. That seems fine to me. In practice we should be passing around structs which include these protos anyway.

I don't think we'd actually want to pass around `*Descriptor`s unless absolutely necessary. Hopefully we could delineate the relatively small parts of schema change execution that actually need to touch leasing-related metadata, and for everything else, we could keep using the unwrapped inner descriptor with its specific type. (Though I think we'd want to keep `name` and `id` around since they're used so much for logging, etc.)

I don't have a great sense of how this should work with our existing `MutableTableDescriptor`s and `ImmutableTableDescriptor`s. I guess to update a table descriptor, we would read the `Descriptor` from KV, unwrap it and generate a `MutableTableDescriptor` from it as usual, do whatever we needed to with just the `MutableTableDescriptor`, and then re-wrap the updated `TableDescriptor` in a `Descriptor` with the version incremented, etc. (Do we need to do the same for the other leasable objects at this point?) I guess we could have the entire `Descriptor` come in a `Mutable` flavor, including the leasing metadata, but it seems better to have the leasing metadata separate and inaccessible from most of the schema change execution implementation.

Also, I want to pull the draining names list out of the table descriptor, since it would be bad to have to reimplement the namespace table interactions for databases, schemas, and enums when they're identical. This'll take some refactoring, but hopefully it would get the drop table/sequence/view/etc. implementations into a better place overall.

**Comment by ajwerner** [comment]
Relates to #47149

**Comment by ajwerner** [comment]
Will be closed by https://github.com/cockroachdb/cockroach/pull/49960.

**Comment by ajwerner** [comment]
Closed by #49960.
