### ISSUE TITLE
opt: account for interleaved tables when costing scans

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#48280]
We had a example that came up recently where we had a foreign key relationship, the parent table only had 32 rows and we were inserting 128 rows in the child. The optimizer very reasonably chose a hash join, but we were not aware that the parent table was part of an interleaving and scanning the 32 rows actually meant scanning a massive hierarchy.

We should find a way for the optimizer to adjust scan costs for interleaved tables. An idea would be to look up stats for all tables in the interleaving and compute how many interleaved rows we would scan "in-between" two consecutive rows in our table. CC @rytaft for more ideas

Jira issue: CRDB-4339

**Comment by rytaft** [comment]
Agree that we need to improve costing for interleaved tables in general, since right now the optimizer is not even aware that such a concept exists.

We should probably add some attribute to each index in the optimizer to indicate whether it is interleaved, which would allow us to adjust the cost for scans like you suggest. This would be similar to the "rows processed" concept that we already use for joins, which can be different than the number of output rows. I'm not very familiar with how interleaving works, but I imagine that an "interleaving" attribute should contain a set of indexes that are all part of the interleaving.

We also need a way to access the interleaving information when costing joins, since joining two interleaved tables should be cheaper than joining separate tables.

**Comment by jordanlewis** [comment]
Interleaved tables have been removed.
