### ISSUE TITLE
kv: multi-node shutdown impossible because drain does not change raft group membership

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48339]
As investigated from #47384 - the new `quit-all-nodes` roachtest is failing. 

The roachtest is asserting that in a 5-node cluster, shutting down 3 nodes gracefully is possible. The failure occurs when shutting down the 3rd node: there is exactly 1 range  (r4, `/System/tsd`) which remains unable to transfer away, and blocks the graceful shutdown.

I can see this in the log for n3:

```
I200504 09:04:23.412726 26233 kv/kvserver/store.go:1101  [drain,n3,s3,r4/3:/System{/tsd-tse}] trying to move replica out: lease transfer = true, raft transfer = true

E200504 09:04:23.413652 26233 kv/kvserver/store.go:1116  [drain,n3,s3,r4/3:/System{/tsd-tse}] did not transfer lease repl=(n3,s3):3 seq=10 start=1588583052.648048181,0 epo=1 pro=1588583052.648050409,0 for replica r4:/System{/tsd-tse} [(n5,s5):5, (n4,s4):4, (n3,s3):3, next=6, gen=12] when draining: <nil>

W200504 09:04:23.414026 26237 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {10.128.0.211:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.128.0.211:26257: connect: connection refused". Reconnecting...
```

The store is reporting that the raft group for r4 is [n5, n4, n3]. Then subsequently fails to do anything because n5 and n4 are down. 

This raises the fundamental question: why did shutting down n5/n4 not transfer the raft group membership for r4 to other nodes?

Looking at the logs for n5 we see something of interest:

```
I200504 09:04:15.860769 5612 kv/kvserver/store.go:1094  [drain,n5,s5,r4/5:/System{/tsd-tse}] not moving out
```

"not moving out" indicates that `if !needsLeaseTransfer && !needsRaftTransfer` was encountered. The bit of interest is `needsRaftTransfer` here (n5 was not leaseholder). `needsRaftTransfer` is only true if the replica was a raft leader. It does not become true if the replica was a mere follower of the group.

I think this summarizes what's happening: because the nodes that are shutting down leave replicas as members of their replication groups, it's not possible to shut down a quorum of _any_ replication group in the cluster. So a progressive cluster shutdown as done in the `quit-all-nodes` test is not possible.

As a first next step, I will disable the test.

Then are two ways forward here:

- either document that shutting down >1 node (or, more generally, a quorum of nodes taking into account the relevant replication factors)  gracefully at a time with `quit` / `node drain` is not possible unless nodes are *decommissioned* first; or

- create some intelligence in the drain code that detects when some other replicas in a group are already draining/unavailable and handle a shutdown by requesting upreplication first.

**Comment by knz** [comment]
@tbg @irfansharif can you check my analysis above and see if you have better alternatives as a way forward?

**Comment by bdarnell** [comment]
> This raises the fundamental question: why did shutting down n5/n4 not transfer the raft group membership for r4 to other nodes?

Because that would make draining far more expensive, just like decommissioning. It would be a bad idea to do this just to be able to parallelize your graceful restarts more aggressively (you'll finish the process much more quickly by draining and restarting one node at a time than by decommissioning and restarting N nodes in parallel).

Additionally, if the operator has set the replication factor to 5 or more, they did this to increase their failure budget. They're unlikely to want to consume the *entire* failure budget for graceful restarts. 

> either document that shutting down >1 node (or, more generally, a quorum of nodes taking into account the relevant replication factors) gracefully at a time with quit / node drain is not possible unless nodes are decommissioned first; or

Yes (and I wouldn't even discuss decommissioning here; I don't think we want to conflate draining and decommissioning because they have very different use cases).

As a special case it is sometimes possible to drain multiple nodes at once: if locality diversity or explicit zone constraints ensure that a set of nodes will not have overlapping replicas, you can drain them all at once. So you could drain a whole AZ's worth of nodes at once, for example (as long as you have 5+ AZs to ensure that system ranges don't get pigeonholed into the same AZ). I'm not sure this is useful enough to document, though. Operations like this would generally be proceeded by draining traffic at the LB/DNS level, at which point you could drain things gracelessly.

**Comment by knz** [comment]
Thanks Ben for your comments. 

This tells me perhaps there is not much to do here in terms of product changes.
I wonder though how much we can do to explain this to users. Some notes in docs in special places (how to shut down more than one node at a time) could be added, but maybe a high-level tech note or blog post could complement this? I think it would be good to have some kind of overview for tech support to explain this every time users ask.

@jseldess what would you recommend we do for education here?

**Comment by irfansharif** [comment]
> I don't think we want to conflate draining and decommissioning because they have very different use cases

I don't see much mention of draining in our docs (`cockroach node drain` is not a thing @knz , I assume you just meant `cockroach quit`). I also haven't used `cockroach quit` very often, and would second that users could do with more guidance around the differences between the two. Given that I can `cockroach node decommission` multiple nodes safely, but I can't say the same for `cockroach quit`, is (I think) surprising UX.

**Comment by knz** [comment]
`cockroach node drain` is a thing now (just not documented yet).

> would second that users could do with more guidance around the differences between the two

ok now we have three hands in favor, none against, so it's going to become a thing.

**Comment by irfansharif** [comment]
The takeaway here was to not introduce any product level changes, but to perhaps have added documentation (cockroachdb/docs#6951).
