### ISSUE TITLE
sql/kv: how does multi-tenancy interact with zone configurations?

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48375]
Up until now, we've been pretty handwavy around the interaction between mutli-tenancy and zone configurations. Our proposed split of the SQL keyspace would leave each tenant with its own `Zone` table, so it would be natural for each tenant to have their own set of zone configurations.

However, for this to work properly, the consumer of the zone configs needs to be made aware of SQL tenants and the distributed storage of their individual zone configurations. A KV range will need to know which Zone table to search in when determining the zone configs that apply to it. There would likely be a large amount of disruption that would fall out of this. For instance, `config.ZoneConfigHook` (and all of its uses) would need to become tenant-aware.

**Comment by tbg** [comment]
I thought we were heavily leaning towards not giving tenants any say over zone configs, at least not in the foreseeable future (see [here](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#bookmark=id.w9hy8mqf5xz7) based not only on technical obstacles, but  also because we may not want to hand this kind of control to users for some time.

We will want some way for the system tenant to manipulate zones for the tenant, but this is a much smaller undertaking without any low level work - we "only" need to add SQL syntax that generates zones for the right key spans (and the usual introspection machinery).

**Comment by nvanbenschoten** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/49445.
