### ISSUE TITLE
replicaoracle: avoid gossip and node descriptor

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#48432]
package `replicaoracle` uses gossip to resolve the NodeIDs for leaseholders. This is silly, since the leaseholder cache could easily cache `(node,store)` pairs instead of just `store`, obviating this use of gossip. As far as I can tell, the only remaining uses are similary spurious (for example looking up the own nodeID).

The dependency on Gossip is undesired since the replica oracle is used for SQL physical planning. Something similar goes for the node descriptor, which is fed into the span resolver here: https://github.com/cockroachdb/cockroach/blob/fcc55537439a078b53c9124ebb9d120ffdee85f4/pkg/sql/distsql_physical_planner.go#L185-L191

Labelling as a blocker, though there's a chance it isn't - will need a closer look. cc @ajwerner are there other uses of Gossip here that I missed (and that may be harder to replace)?

**Comment by tbg** [comment]
Hmm, I was too optimistic here. The tricky bit is the nodeID -> node address lookup which we use gossip for. We basically want an eventually consistent cache of that on every tenant.

**Comment by ajwerner** [comment]
It seems like there's good news here. The oracle is only used to plan distsql flows IIUC. I suspect we can get by by adding a new oracle implementation that side-steps the dependency. Thanks for digging this up, I'll look at it a little later in the milestone unless you have more pressing concerns.

**Comment by tbg** [comment]
Oh, that makes sense - great. No need for you to drop what you're doing. I might go in and refactor things so that the span resolver can more obviously be "optional".

**Comment by tbg** [comment]
Oops, accidentally keyworded this.

**Comment by andreimatei** [comment]
It looks to me like the node addresses don't actually end up being used for much. I might try to clean some stuff up, cause I'm unraveling some stuff around the uses of the leaseholder cache and I got here by misfortune.

**Comment by andreimatei** [comment]
My gift to y'all is #49675 which removes the use node addresses in DistSQL planning. I'll likely have another gift soon when I get rid of the limitation Tobi mentioned above - the fact that the leaseholder cache only maintains StoreIDs, and so the oracles need gossip to translate store ids to node ids - that will get rid of `GetNodeIDForStoreID()` from `DeprecatedOracleGossip`.

Unfortunately, even with node addresses not being used any more, the `GetNodeDescriptor()` method on `DeprecatedOracleGossip` is still used [here](https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/sql/physicalplan/replicaoracle/oracle.go#L277) in order to sort the replicas by locality and latency for follower reads and such. Figuring out the story there I'll leave to you.

**Comment by tbg** [comment]
Will be handled by DistSender refactor
