### ISSUE TITLE
sql: portal restarts execution after exhausting rows

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48448]
See https://github.com/sfackler/rust-postgres/issues/552#issuecomment-623801356 and [this test](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/tests/test/main.rs#L644-L685).

There appears to be something going wrong with a portal that is queried after exhausting all rows. Instead of returning zero rows once exhausted, the portal seems to restart. I haven't dug into this enough to determine where the bug is coming from, but this is a clear deviation from Postgres' behavior.

The easiest reproduction I have is with [this test](https://github.com/sfackler/rust-postgres/blob/f9ba58967ba2bbbbb6ff9c84a07adae246a8e316/postgres/src/test.rs#L320) in the `rust-postgres` driver. The test passes as-is, but it breaks with the following patch. Postgres continues to pass with it.
```rust
diff --git a/postgres/src/test.rs b/postgres/src/test.rs
index 6750118..d6e0490 100644
--- a/postgres/src/test.rs
+++ b/postgres/src/test.rs
@@ -318,11 +318,12 @@ fn binary_copy_out() {

 #[test]
 fn portal() {
-    let mut client = Client::connect("host=localhost port=5433 user=postgres", NoTls).unwrap();
+    let mut client = Client::connect("host=localhost port=26257 user=root", NoTls).unwrap();

     client
         .simple_query(
-            "CREATE TEMPORARY TABLE foo (id INT);
+            "SET experimental_enable_temp_tables = 'on';
+             CREATE TEMPORARY TABLE foo (id INT4);
              INSERT INTO foo (id) VALUES (1), (2), (3);",
         )
         .unwrap();
@@ -341,6 +342,9 @@ fn portal() {
     let rows = transaction.query_portal(&portal, 2).unwrap();
     assert_eq!(rows.len(), 1);
     assert_eq!(rows[0].get::<_, i32>(0), 3);
+
+    let rows = transaction.query_portal(&portal, 2).unwrap();
+    assert_eq!(rows.len(), 0);
 }

 #[test]
```

_to run:_
```sh
$ cargo test portal
thread 'test::portal' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', postgres/src/test.rs:347:5
```

@mjibson do you have any insight into this?

More generally, I think it would be valuable to try to get that driver's test suite running against Cockroach. It's one of the best test suites I've seen for stressing Postgres wire compatibility. cc. @rafiss.

**Comment by mjibson** [comment]
I can confirm and reproduce this bug. Cockroach handles portals by using a [special function](https://github.com/cockroachdb/cockroach/blob/b6dae149c67a08db7c1e8ab0ac6a85e183f939a4/pkg/sql/pgwire/command_result.go#L405) that takes over the pgwire state machine and does some things. However I think that function is only called when there are actually more rows to call, since it is called from the `AddRow` func:

https://github.com/cockroachdb/cockroach/blob/b6dae149c67a08db7c1e8ab0ac6a85e183f939a4/pkg/sql/pgwire/command_result.go#L394

Thus, I suspect that since the query finished, we exited up to the normal state machine, which then saw the exec and decided to just run it anew. It seems like we don't correctly track portals that have been opened, emptied, but not closed. We could fix this by correctly tracking empty, unclosed portals and return whatever empty thing we need.

Below is a test that demonstrates this.

`pkg/sql/pgwire/testdata/pgtest/portals`:
```
# Regression for #48448
send
Query {"String": "CREATE TABLE foo (id INT8); INSERT INTO foo (id) VALUES (1), (2), (3)"}
Query {"String": "BEGIN"}
Parse {"Query": "SELECT * FROM foo ORDER BY id"}
Bind {}
Execute {"MaxRows": 2}
Sync
----

until
ReadyForQuery
ReadyForQuery
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"CREATE TABLE"}
{"Type":"CommandComplete","CommandTag":"INSERT 0 3"}
{"Type":"ReadyForQuery","TxStatus":"I"}
{"Type":"CommandComplete","CommandTag":"BEGIN"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"ParseComplete"}
{"Type":"BindComplete"}
{"Type":"DataRow","Values":[{"text":"1"}]}
{"Type":"DataRow","Values":[{"text":"2"}]}
{"Type":"PortalSuspended"}
{"Type":"ReadyForQuery","TxStatus":"T"}

send
Execute {"MaxRows": 2}
Sync
----

until
ReadyForQuery
----
{"Type":"DataRow","Values":[{"text":"3"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 1"}
{"Type":"ReadyForQuery","TxStatus":"T"}

send
Execute {"MaxRows": 2}
Sync
----

until
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"SELECT 0"}
{"Type":"ReadyForQuery","TxStatus":"T"}
```

**Comment by mjibson** [comment]
I don't plan on doing this work unless we think I'm the best person to do it. @jordanlewis can you triage or decide who should decide if this should get done, and by whom?

**Comment by jordanlewis** [comment]
The execution team will take this one.
