### ISSUE TITLE
ui: (bug) job state not reflected correctly

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#48489]
**Describe the problem**

There's a potential UI feedback bug (20.1.rc2) where job state is not reflected correctly. Jobs were indeed running and also finished, but the jobs page didnt show any progress. There's also a question on the difference between running_status and status column in SHOW JOBS.

**Reproduction Steps**
- Run import job of csv from nodelocal storage
- Check Jobs page in Admin UI while running the job (shows 0% even though progress is being made)

**Notes**
- `running_status = NULL` in output of `SHOW JOBS;`
- import single CSV hangs for a long time

**Comment by onno-vos-dev** [comment]
I reported this as well earlier today at: https://github.com/cockroachdb/cockroach/issues/48475 so there's a little bit of information there as well.

**Comment by onno-vos-dev** [comment]
@dhartunian This turned out to be not a UI issue but an issue with configuration. Setting: `kv.snapshot_rebalance.max_rate` and `kv.snapshot_recovery.max_rate` from `8 MiB` to `128 MiB` resolved the situation for us. 

(Closed the issue I created: https://github.com/cockroachdb/cockroach/issues/48475 myself)

**Comment by dhartunian** [comment]
Thanks for the update @onno-vos-dev. Much appreciated.
