### ISSUE TITLE
sql: Implement a SQL driver that uses sql.Executor directly

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#4869]
This would allow our in-process SQL queries to use the same tools one would use externally to deal with SQL databases such as ORMs and other goodies.

Seems like a no brainer and should be easy to implement.

**Comment by knz** [comment]
So I have started to look at this. Basically there are two levels at which one can provide a go.sql driver:

1. at the same level that our pgwire driver uses internally. This uses the `Executor` and `Session` objects and uses the entire transaction state machinery.

2. at the same level that our other internal processes currently use internally. This does not use the `Executor` and `Session` objects and thus can only launch single statements with implicit transactions. However it is very lightweight (basically amounts to `s.db.Txn(ctx, func (...) { runQuery(...) })`.

Going route 1 brings us a feature-rich interface but I see only a limited advantage compared to using `lib/pq` and connecting locally. In particular there are a lot of initializations needed which basically amounts to overhead.

Going route 2 is comparatively lightweight prevents us from implementing the `sql.Tx` (transaction) interface. 

If the goal is simply to clean up our existing code then route 2 is sufficient. 

However if the goal is to use an ORM it is likely that `sql.Tx` will be required in which case we should go to route 1. 

However if we go route 1 then we would be adding some complexity/overhead to our existing internal clients (mainly the lease manager and schema changer).

Of course there is also the option to build two separate internal `sql` drivers, one at each level.  It's a bit more work but keeps options open.

Any advice / preference?

**Comment by tamird** [comment]
I would be more than happy to go with the simple route for now and revisit
as needed.

The iterative approach has worked out best for us in the past.

**Comment by andreimatei** [comment]
I may say something stupid, but why can't we internally open a pgwire connection to ourselves, instead of writing a sql driver?

**Comment by tamird** [comment]
For one, we'd be serializing and deserializing things needlessly.

**Comment by andreimatei** [comment]
I'm going to close this because I think a sql driver is unlikely to happen. I'm cleaning up the various "internal executors" that we have so that they run common code with a regular network client. Since this issue was filed, we've refactored our connection handling code so that the networking code is isolated from the rest of query processing.
One thing that would probably preclude using a driver everywhere where we need internal SQL execution is that often the code that needs to execute SQL needs to execute it in a higher-level txn that was created using the KV interface. It'd probably be hard to support this through a driver.
