### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [cockroachdb/cockroach#48707]
**Describe the problem**

I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running cockroachdb on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for cockroachdb if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/cockroachdb/cockroach/blob/d3aa53d44b528d4f0d120654c709c000222c0a71/pkg/util/humanizeutil/humanize.go#L106
https://github.com/cockroachdb/cockroach/blob/d3aa53d44b528d4f0d120654c709c000222c0a71/pkg/kv/kvserver/closedts/minprop/tracker_test.go#L163
**To Reproduce**

What did you do? Describe in your own words.

--

**Expected behavior**

--

**Additional data / screenshots**

--

**Environment:**
master branch,
commit: d3aa53d44b528d4f0d120654c709c000222c0a71

**Additional context**

--

**Comment by nvanbenschoten** [comment]
Hi @BurtonQin, thanks for the report! This is an interesting issue, especially the part about gRPC moving away from 64-bit atomic accesses. I think that makes a lot of sense for them because, as a library, they're looking to support as many potential users as possible.

For CockroachDB, we're less concerned about supporting 32-bit CPU architectures. This is both because we don't see much demand for them from our users (even Raspberry Pis has 64-bit processors these days!) and because we don't want to take on the burden that comes with claiming support for systems that we aren't actively testing on.

So I don't think this is a concern for CockroachDB, but I appreciate you filing the issue to have the discussion!
