### ISSUE TITLE
Why the backup keys need intents does not exist in this time period?

### ISSUE THREAD

**Issue by halleyshx** [cockroachdb/cockroach#49246]
When I test the backup feature to backup a cluster，I find the backup occasionally slow(It used to take a minute to finish. It took 20 hours)，open log file, I found some of the same keys in the export retry, After some positioning, so I add some log,like this(pkg/ccl/storageccl/engineccl/mvcc.go:211):
`if i.meta.Txn != nil {
			if i.startTime.Less(metaTimestamp) && !i.endTime.Less(metaTimestamp) {
.....
i.valid = false
log.Errorf(context.Background(), "%v",i.err)
return
}
}`
There is some same logic in mvcc_incremental_iterator.go of v20.1.0. My version is v19.1.
The new content of the log:
`pkg/ccl/storageccl/engineccl/mvcc.go:211   conflicting intents on /Table/1293/8/"13984"/"uѧl\u007fsL\xbc\x95\x1aV]\xac6 \""/0`

From some code of intent, I noticed that the intent is asynchronous clear.

why backup find intent write key directly retry, but the transaction of intent write key had commit. Why the backup logic not to find the transaction's commit state to judge the intent write key which we can backup.

so Why not judge the commited state of keys to backup?
After the record of key is successfully written(commited over), it can be backed up successfully, don't care the intent of timestamp.Is that OK?
Why not？

Thanks.

**Comment by dt** [comment]
Hi @halleyshx !

I'd love to hear more about what you're observing when your minute-long backup takes 20h. Is it possible there are any open, unresolved transactions in the tables being backed up?

`ExportRequest` is the basis of BACKUP and it does indeed not handle seeing an intent -- it does not know if that intent is related to a pending or completed / aborted transaction without out potentially needing to contact that transaction's coordinator, so it simply errors out when it sees an intent and lets the next layer up, called DistSender, handle getting that intent cleaned up and then trying the export again. This _usually_ works fine since backups take awhile and, by the time we get to exporting any given range, all the intents for the ongoing transactions there that started before the backup have been cleaned up (and those that started after are ignored). The exception to this is when there are large numbers of intents left around (e.g. if something was crashing and leaving intents for aborted transactions instead of cleaning them up) or, what we usually see recently, if there is actually a transaction still open in the span being backed up, in which case we don't know _what_ to do about the intent.

**Comment by halleyshx** [comment]
Hi @dt !
Thank you for your answer！

The table id 1293, name is pool in the datapool database,size is 45.0 GiB.There are no operations other than occasional bulk inserts into the table.
According to my observation，there are not any open, unresolved transactions in the tables being backed up.
From SQL Queries of metrics and Transactions of metrics, there are no anomalies in these two graphs.

Now it is still very slow and the remaining 13s are not moving, although 4h is less than 20 hours (this time is not fixed).
![image](https://user-images.githubusercontent.com/24284940/82399808-87098800-9a88-11ea-9ea9-9e9c699d6710.png)
`BACKUP DATABASE datapool TO 'nodelocal:///full-backup-database-beforetime_-300s-is-2020-05-20_070355' AS OF SYSTEM TIME '2020-05-20 07:03:55'`

The same full backup operation took 3min16s two days ago
![image](https://user-images.githubusercontent.com/24284940/82400656-79ed9880-9a8a-11ea-9b28-54ce1fda6d7d.png)
`BACKUP DATABASE datapool TO 'nodelocal:///full-backup-database-beforetime_-300s-is-2020-05-18_134235' AS OF SYSTEM TIME '2020-05-18 13:42:35'`

I still don't understand why the backup needs to look at whether the intent clear rather than whether the transactions commited?

Now that intents existed have increased backup times, Whether it is better to make a backup operation by deciding whether transactions are committed or not?

Thanks!

**Comment by dt** [comment]
We can't always tell from just an intent if it is resolved or not -- we need to actually look up the owning transaction and/or contact its coordinator to discover its status, which is what we do during normal OLTP traffic, but is considered too expensive to do in bulk when exporting and entire table in backup, so instead we expect to run far enough in the past that we hope to not see any intents (since, once the backup has been running for, say, a minute, then it's read time is a minute in the past and we'd expect any intents from them to have been resolved.)

What would be interesting to try when you see one of these hanging backups is to issue a scan of the table in question, e.g. `select count(*) from datapool.pool` -- the scan will try to read every row but will actually attempt to find/resolve intents as it goes. If it succeeds, i'd expect to then see your hanging backup complete immediately, which imply that we has some unresolved _orphaned_ intents hanging around that _should_ have been cleaned up. On the other hand, if the `select` _also_ hangs, then that would suggest that both it and the backup are running into a actual open transaction's intent and are blocking as expected.

If we see the first case -- that the `select` runs quickly and then the backup completes -- then we might have a bug somewhere in intent cleanup or, like you suggest, we might benefit from adding more logic to `ExportRequest` to try to handle resolved but not cleaned up intents better. If it is the second case, then we're actually doing what's expected and we should instead be looking for what transaction is holding on to these open intents. Does that make sense?

**Comment by halleyshx** [comment]
Ok, I got it. I feel it's good.I will do the test as you said.
When I noticed again that there was a slow backup, I will execute the `select` operation. Then the results will be shared with you.

In addition, here are some of today's backup tests. Time is not fixed. And the last one is the full backup operation we talked about earlier.
![image](https://user-images.githubusercontent.com/24284940/82467192-f9638200-9af3-11ea-83b1-ab48035fa3ee.png)

It‘s time to sleep, I will try to do the test tomorrow.
Thanks!

**Comment by halleyshx** [comment]
Hi @dt 
Today this slow backup occurs again,like this:
![image](https://user-images.githubusercontent.com/24284940/82563878-689bad80-9baa-11ea-8d81-63a01e6305fd.png)

So I execute the statement like this:
`mysql> use datapool
mysql> select count(*) from pool;
+----------+
| count(*) |
+----------+
| 13852860 |
+----------+
1 row in set (6.58 sec)`

Soon the statement is executed, but the backup percentage remains unchanged.
![image](https://user-images.githubusercontent.com/24284940/82564987-42770d00-9bac-11ea-9bbc-5ba095294150.png)

I feel like this is the third case.

What should I do next?
Thanks!

**Comment by halleyshx** [comment]
My version is v19.1.

**Comment by dt** [comment]
Hey @halleyshx,

Thanks for the info! This looks like a tricky issue and I think to make more progress on it we'll need some more info about the keys and ranges and logs. Since backup is an enterprise feature, and since BACKUP is an enterprise feature, this is something we'd do via the enterprise support channel at http://support.cockroachlabs.com.

Thanks again!
