### ISSUE TITLE
Client interface design

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#493]
For discussion before I dive into the code: [`client.KV`](https://godoc.org/github.com/cockroachdb/cockroach/client#KV) currently has the generic methods `Call` and `Prepare`/`Flush`, as well as a handful of specializations: `GetI`, `GetProto`, `PreparePutProto`, `PutI`, `PutProto`. The specialized methods draw attention away from the more flexible Call and the potentially-faster Prepare (unless we introduce additional variations like `PreparePutProto`). I'd like to unify these as follows:

* `KV.Call` and `KV.Prepare` take a single object instead of a method/args/reply triple. This object replaces `client.Call`; for the purposes of this writeup I'm going to call it an `Op` to avoid ambiguity around the different uses of `Call` (and because it differs substantially from the current `Call` struct)
* All of the specialized methods become factories for `Op`, probably as static functions instead of methods: `db.Call(client.PutProto(...))` or `db.Prepare(client.PutProto)`. We'd add functions for all the major user-facing requests; most applications wouldn't need to pass method names explicitly.
* To avoid the need for an awkward `(Op, error)` return signature, Ops may contain an error. `Call` and `Prepare` will return this error if it exists (or maybe in the case of Prepare the return is deferred to Flush)
* Dealing with return values is the trickiest part. `Op` is an interface so some operations can have specialized implementations. This allows for both type-safe access to the reply proto (which would otherwise have been converted into a generic `proto.Response`) and hooks after the request has completed (to unmarshal response bytes into a user-supplied protobuf object.

While I'm at it, I'd like to propose a few more changes:
* Make `KV.Call` take a variable number of Ops. Eliminate `KV.Flush`; use `KV.Call()` with no arguments instead. (`Prepare()` is also pretty trivial at this point; many callers would be able to replace it with varargs `Call()`)
* Remove the gob-based `GetI` and `PutI` methods. I don't think we should encourage language-specific encodings; if we want to be able to Get and Put generic `interface{}` we should probably use JSON.
* I'm on the fence about `GetProto` and `PutProto`. I'm more comfortable giving protobufs special treatment than gob, but it still doesn't feel quite right (and the use of gogoproto instead of standard protobuf might be problematic in some cases). On the other hand, code for storing protobufs in cockroach will have to live somewhere and we can put it here without introducing any new dependencies or other headaches. I suppose we could introduce some sort of marshaller interface but that might be overkill.

**Comment by petermattis** [comment]
I just noticed `GetI` and `PutI` earlier today. I agree they should go away. Gob is intended for network encoding, not disk storage.

I find the explicit use of method name strings (e.g. `proto.Put`, `proto.Get`) awkward. I like that this proposal would get rid of them. I think I would hold off on making `KV.Call` take a variable number of Ops.

**Comment by tnachen** [comment]
A language agnostic network encoding is preferred for a client with a different language can easily integrate

**Comment by bdarnell** [comment]
All client communication is already language-agnostic (protobufs or json over HTTP); we only use go-isms for things that are internal to cockroach (net/rpc for inter-node communication, gob for gossiped data).

**Comment by cloudmode** [comment]
I just spent a few days porting a foundationdb model over to cockroachdb, and I can give you a little perspective coming from that space:
1. cockroachdb should be agnostic to value encoding, i.e. that should be the job of the model layer. Offering explicit support for one encoding or another could lead to features that assume the encoding. We use msgpack as our wire protocol AND for our value protocol, because it's JSON compatible AND it is easily supported in dynamic languages like obj-c).
2. It would be nice to have a range operator that returns only the keys, without values. Perhaps I missed this one, but it would be great to get just the keys, without needing to load up the memory with potentially unused values. It also let's me control how much stuff has to get read off of disk, and transmitted to my client. 
3. I can then use the single value get using whatever key(s) I select. 

I can provide detailed use cases if you'd like.

Great work by you guys. I'm really impressed. And it looks like cockroachdb is going to save my butt now that FoundationDB is gone. (see https://github.com/cloudmode/roachclip-fs for our first cut)

**Comment by petermattis** [comment]
Nice to hear that Cockroach is helping you out.

As Ben said, for the key/value API, Cockroach is agnostic to the value encoding. The value is stored as raw bytes and Cockroach only ever treats it as such. It is up to the user to know if those bytes are a proto, json, msg-pack or something else. The `PutProto` and `PutI` interfaces that currently exist are just client side niceness on top of `Put`. 

A scan operation that only returned keys is a possibility. It would lessen network traffic, but due to the way data is stored on disk, it wouldn't reduce disk reads. An alternative to changing scan would be to add an index to your data:

```
  /data/<key> -> <large value>
  /exists/<key> -> <>
```

When you use insert `<key>` you would do puts to both `/data/<key>` and `/exists/<key>`. When you need to scan without values you use `/exists/<key>`. And when you want to retrieve a value you retrieve `/data/<key>`. Distributed transactions make this approach much easier.

**Comment by cloudmode** [comment]
Thanks Peter,

That is pretty much what I did, by adding an additional 'meta' key that identified the range of keys that were stored in the primary key-value storage. I was then able to query that key, prior to retrieving specific values (a chunked blob store). I like the exists idea too. 

re: reducing disk reads, not necessarily the number of reads, but the size of the data that is actually read. Is that a network only issue?

**Comment by petermattis** [comment]
Keys and values are stored next to each other on disk. While scanning through contiguous keys the values will necessarily be read. Avoiding the network traffic might be a win, though it would be good to have real use cases that show benefit.

**Comment by spencerkimball** [comment]
I'm fine with these changes

**Comment by spencerkimball** [comment]
#818

**Comment by spencerkimball** [comment]
#830

**Comment by spencerkimball** [comment]
@petermattis should we consider this closed?

**Comment by petermattis** [comment]
Yeah, for now I think this is good.
