### ISSUE TITLE
pg_namespace not visible to regular users

### ISSUE THREAD

**Issue by roji** [cockroachdb/cockroach#49313]
Similar to #48726, the contents pg_namespace aren't visible to regular users. It may be worth going over all system catalog tables and making sure visibility is correct.

/cc @rafiss

edit: we should address #56020 first, probably.

Jira issue: CRDB-4239

gz#12320

**Comment by rafiss** [comment]
Thanks @roji. For some reason when I was changing the other table, I looked at this one and intentionally decided to keep it admin-only... but now I'm not sure why I decided that.

The good news is that this is the last pg_catalog table that is hiding behind this privilege check. (Of course, there could be other privilege checks that are hiding other tables, but I think those are as they should be, as far as I know.)

**Comment by rafiss** [comment]
@otan i don't think a fix got merged for this. is it closed for a different reason?

**Comment by otan** [comment]
oh sorry, thought it did in #51213 but it wasn't merged. don't mind me....

**Comment by dcecile** [comment]
For others who run into this, the [rust-postgres](https://github.com/sfackler/rust-postgre) driver queries the `pg_namespace` table to get info about custom types (e.g. enums):

https://github.com/sfackler/rust-postgres/blob/tokio-postgres-v0.7.5/tokio-postgres/src/prepare.rs#L19-L25

 Without permission, no rows are returned, resulting in this nondescript error:
 
 > `Error: Error { kind: UnexpectedMessage, cause: None }`
 > https://github.com/sfackler/rust-postgres/blob/tokio-postgres-v0.7.5/tokio-postgres/src/prepare.rs#L145

To grant permissions, upgrade to CockroachDB 21.1.0 or higher, and grant `CONNECT` on your database, e.g. `GRANT CONNECT ON DATABASE defaultdb TO api_read`. (This feature was added in https://github.com/cockroachdb/cockroach/commit/69dfda17aab1e9e0740bf0d996007b7270fbca3a via #59676, #60455, and #60457.)

**Comment by rafiss** [comment]
Thanks for leaving those instructions @dcecile! 

Also, we decided that in v22.1 (coming out in 2022), CockroachDB will grant CONNECT privilege by default (https://github.com/cockroachdb/cockroach/pull/72595)

**Comment by rafiss** [comment]
Closing this since this should not be an issue in v22.1

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4239](https://cockroachlabs.atlassian.net/browse/CRDB-4239) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-49313`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rafiss** [comment]
This is resolved, as per https://github.com/cockroachdb/cockroach/issues/49313#issuecomment-974982619
