### ISSUE TITLE
server: add more stats to TableDetails admin API

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#4931]
From @petermattis:

We should also return stats here [in `TableDetailsResponse`] such as number of ranges and number of bytes.

**Comment by spencerkimball** [comment]
@cuongdo are we aggregating MVCC stats for tables yet? Shouldn't be too hard to do.

**Comment by cuongdo** [comment]
I don't believe so. We should though.

**Comment by cuongdo** [comment]
Just talked to @tschottdorf. Getting aggregated `MVCCStats` for tables is going to be a substantial change, because `MVCCStats` are updated for each put, abort, etc. When each of these updates is performed, we'd need to parse the `roachpb.Key` to attribute the stats changes to a specific table. All of this key parsing could incur a substantial performance penalty and would take a fair amount of testing to verify.

A better approach for beta seems to be modifying `DistSender` so that it can return the number of `RangeDescriptor`s for a given table. Then, we can provide an approximate size in bytes for the table in the UI.

This would satisfy the general requirement that a user should be able to see the relative sizes of tables, to aid in optimization and debugging.

Thoughts?

**Comment by petermattis** [comment]
I'm fine with counting the number of ranges in the short term. Medium term we can add a new RPC that aggregates the `MVCCStats` across a set of ranges.

**Comment by mrtracy** [comment]
I agree with the on-demand solution: when a query comes in for table stats, count the number of RangeDescriptors in its key range. To get more detailed stats, send an RPC on each range to return the current MVCC stats.

Aggregating per-table stats _incrementally_ is going to be more difficult. When answering a query for table stats, we require some sort of de-duplication to make sure that we're counting the MVCCStats once for each range (instead of for each _replica_).  This is conceptually easier to do using the RPC than doing it in a distributed "push" fashion like our other stats.
