### ISSUE TITLE
colexec: add support for LShift binary operator

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#49467]
Add support for `LShift` binary operator. For more details, see #49463.

**Comment by tancredosouza** [comment]
Good morning! Can I try this one? :)

**Comment by yuzefovich** [comment]
@tancredosouza of course! I'll assign the issue to you to indicate that it is currently being worked on.

**Comment by tancredosouza** [comment]
Hi there! I believe to be almost done with both LShift and RShift implementations.

The only thing missing, I believe, is the translation of the following statement:
`telemetry.Inc(sqltelemetry.LargeLShiftArgumentCounter)`

Since these are the only operations which send telemetry information, I wasn't able to figure out how to translate that to `getBinOpAssignFunc`.

I could also leave it as a "TODO" item in my code. 

What do you think?

Kind regards,
Tancredo.

**Comment by yuzefovich** [comment]
> I wasn't able to figure out how to translate that to `getBinOpAssignFunc`.

I assume that something like this should just work, no?
```
if {{.Right}} < 0 || {{.Right}} >= 64 {
  telemetry.Inc(sqltelemetry.LargeLShiftArgumentCounter)
  colexecerror.ExpectedError(pgerror.Newf(pgcode.InvalidParameterValue, "shift argument out of range"))
}
```

Is there something I'm missing?

**Comment by tancredosouza** [comment]
That did it. I tried that before but must have misspelt something, which caused it to not work.

Thanks!

**Comment by derekkenney** [comment]
Hi there. Is this still an open issue? I'm looking for a good first issue to contribute to. Thanks.

**Comment by yuzefovich** [comment]
@derekkenney it's still "open" in a sense that it hasn't been "closed" yet, but @tancredosouza is actively working on it and already has a PR out, so please take a look at some other good first issue that doesn't have an "assignee" yet.
