### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by Nayana-ibm** [cockroachdb/cockroach#49528]
I am building Cockroachdb from source. Found build steps at two places. One with source archive and other with git clone.

Source archive: https://www.cockroachlabs.com/docs/v19.2/install-cockroachdb-linux.html#build-from-source
Git clone:  https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting+and+building+from+source

Also observed difference in :  
- Dependency package versions (go, cmake etc.)
- Two test failures observed when build with source archive (`Error: Failed to get version tag from git. Are you running in the cockroach repo directory? err=exit status 128, out=fatal: not a git repository` )
- Output of cockroach version:
```
Build Tag:    v19.2.5 ( with source archive)
Build Tag:    v19.2.5-dirty ( with git clone)
```
Which document will you prefer to use? Which one is the latest updated?
Please let me know.

**Comment by Nayana-ibm** [comment]
@nvanbenschoten Do you have any idea on this

**Comment by nvanbenschoten** [comment]
Hi @Nayana-ibm! Thanks for the question. Both approaches you mentioned are valid ways to build CockroachDB from source. Using the source archive is the minimal way to build from source and is typically used by administrators who plan to deploy the resulting binary directly. Using a git clone is a little more heavyweight and typically used by contributors who plan to make and upstream changes. So there's not a preferred approach - both should work. Does that help?

**Comment by Nayana-ibm** [comment]
Thanks @nvanbenschoten for quick response. 
Yes, I could build using both the ways.  Actually we are building for s390x platform hence thought of asking which is a preferred approach. 
Also one thing I noticed is when built using git clone,, version it prints as `Build Tag:    v19.2.5-dirty`

**Comment by nvanbenschoten** [comment]
The build tag is based on the git sha that you have checked out. If you want to build at a specific version, you can checkout the corresponding git tag. For instance, to build `v19.2.5` you can `git checkout v19.2.5`. If it continues to include a dirty portion, that likely means that you have uncommitted changes in your working directory.

> Actually we are building for s390x platform hence thought of asking which is a preferred approach.

I don't think we have any experience building for s390x, but Go supports it, so it might work. Feel free to post back here about your experience.

I'm going to close this because it doesn't sound like there's anything more here to discuss, but please re-open if necessary.
