### ISSUE TITLE
distsql: transition distsql physical planner to use SQLInstanceIDs instead of NodeIDs

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#49596]
The distsql physical planner currently uses `roachpb.NodeID`s to identify nodes. With multitenancy work, use of `roachpb.NodeID` is slowly being phased out in favor of a `SQLInstanceID` (https://github.com/cockroachdb/cockroach/issues/48009). The distsql physical planner should be changed to use `SQLInstanceID`s.

This work is not urgent since for phase 2, tenants will only be executing single-node queries and `SQLInstanceID`s can be cast to `NodeID`s for the time being, but it is cleanup that should be done after that phase.

**Comment by tbg** [comment]
For the record, in https://github.com/cockroachdb/cockroach/pull/48795 I'm adding code that makes sure that we never try to SetupFlow. I added that because in the same PR, one of my changes let to a flow being scheduled (since we used -1 for the NodeID in the NodeDescriptor, which I've now rectified to use the same fakeNodeID as the rest of the tenant).
