### ISSUE TITLE
ui: std deviation not visible on statements list page 

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#49706]
While @nstewart was exploring slow statements in a cluster, he noted that overall p99 latencies were high, but it was difficult to spot the offending queries on the statements list page. After digging into the statement details, he was able to find a query with very high variance:

![image](https://user-images.githubusercontent.com/21692034/83285455-3d1d5200-a1ac-11ea-9242-7f706b7db434.png)

However this isn't visible on the statement list unless the you hover over the statement in question:
![image](https://user-images.githubusercontent.com/21692034/83285506-4f978b80-a1ac-11ea-83fb-f5d13331d470.png)

We should explore how we can make this easier to spot without requiring hovering over each statement. This may be a bug/regression on this page from the design update.

cc @Annebirzin and @awoods187 

Jira issue: CRDB-4206

**Comment by dhartunian** [comment]
The scaling here is based on other items in the list so there's likely a separate item that has a really high mean.

Would be cool to explore adding a ratio of stdev/mean (https://en.wikipedia.org/wiki/Coefficient_of_variation) which would allow comparison but I wonder if this would cause more confusion since it's not a measure that folks are as familiar with.

Another option could be to have a ratio past which we should a yellow ⚠️ or something by the statement to highlight to the customer.

**Comment by nstewart** [comment]
Any reason we can't explicitly show the std dev as a column? Def don't want to suggest a specific design, but if we can't find one that is clear - that approach might be helpful. It looks like we talk about pairs of means and std dev throughout the UI

**Comment by nstewart** [comment]
@ajwerner 's point of view on arbitrary latencies: https://github.com/cockroachdb/cockroach/issues/49658#issuecomment-636115794
