### ISSUE TITLE
server: feature request: enable use standard https port 443 for AdminUI

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#49811]
**Is your feature request related to a problem? Please describe.**
From CockroachCloud user:
> We usually use non-standard ports like 8080 for internal communications. From the client side (browser) to the Loadbalancer, the connection is usually protected by TLS on 443. I'm not sure of the advantages of using port 8080 for publicly available secure URLs. My knowledge on the networking layer is limited and I hope there are reasons behind the decision.

> My point is - if you tell me that a URL would work on the internet, it should work on the internet in all cases. It is strange that I have to relax my router's security settings to access a secure cockroach DB on the internet.

**Describe the solution you'd like**
Use standard https port 443 for AdminUI.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/58752716/83559791-2a27bc00-a4e3-11ea-8a69-a8760cb6d649.png)

**Comment by florence-crl** [comment]
Hi @piyush-singh, please add an appropriate label to this issue if needed.

**Comment by knz** [comment]
So we are not planning to support this inside CockroachDB, and not for a complex technical reason.

In fact, CockroachDB is already perfectly able to serve on port 443, for example with `--http-addr=:443`.

However, on unix system all the port numbers between 0 and 1024 (including 443) are reserved for processes running with `root` privileges. We are completely against running CockroachDB as `root` because we can't guarantee that bugs inside CockroachDB could not yield privilege escalation and resource abuse on the host system. 

The proper deployment if you want to use port 443 is to deploy a HTTP (or even TCP) proxy alongside the CockroachDB process, for example using nginx.

Or even better, use a HTTP load balancer listening on port 443, and distributing connections to CockroachDB nodes listening on a different port.

So this is not a technical issue, it's an education issue.

@bdarnell feel free to extend/enhance my response if you have any additional thoughts.

**Comment by knz** [comment]
cc @aaron-crl if you also have additional thoughts.

**Comment by florence-crl** [comment]
@knz Thanks for the additional information.  I created this issue not for CockroachDB in general, but mores specifically for the CockroachCloud implementation of the AdminUI. Sorry for not making that clear earlier.

**Comment by knz** [comment]
oh I see
cc @joshimhoff @DuskEagle for further triage

**Comment by aaron-crl** [comment]
Exposing an internet service on 443 vs 8080 makes little external threat difference. We might want to make sure we add relevant no-crawl and caching decorators around any infrastructure we wouldn't want a webcralwer to cache but I see no security reason this can't be aligned on the standard HTTPS port.

**Comment by bdarnell** [comment]
I think it's a good practice to expose the admin UI on port 443 instead of 8080 or elsewhere. We can't do that by default because of unix port permissions (and the likelihood that at least in test/dev environments there may be something else on the machine using that port), but whenever it's convenient it's nice to put it on the standard port. (Note that I would not recommend running `cockroach` as root in order to bind to this port, but configuring your load balancer to do this port remapping). 

We should do this in the load balancers used for the web UI in CockroachCloud.

**Comment by knz** [comment]
I think this issue is not filed in the right repo. Unfortunately I cannot transfer it to the managed service repo.

I'll let @DuskEagle process this further for CC as the SRE teams sees it fit. Perhaps it needs to be processed by some PM as well. In any case, there's not more to be done by CRDB engineering in this repo.

**Comment by DuskEagle** [comment]
We are tracking this within the Cockroach Cloud repo.
