### ISSUE TITLE
bulkio: Encrypted Backups should use keys

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#49845]
Ideally, from a KMS.
And ideally the KMS of the cloud provider.

Passphrases were a great stop gap, but they are not sufficient 

In aws that would be https://aws.amazon.com/kms/
In gce that would be https://cloud.google.com/kms
In azure that would be https://azure.microsoft.com/en-us/services/key-vault/
You get the idea.

**Comment by BramGruneir** [comment]
@dt and @thtruo for triage.

**Comment by mwang1026** [comment]
Some more context:

Due to security reasons, certain companies don't allow explicit passphrases exposed anywhere in their commands. Instead, they prefer to use certs with rotating keys or implicit, key management service services (KMS) where they pass a "key" which auths them to the KMS which passes the passphrase to CRDB without it being explicitly logged anywhere.

There are implications of this--each time we retry we have to hit the KMS each time to get the passphrase again--but due to security restrictions some companies have no choice.

There is also the consideration of server side encryption, but some companies require server side AND client side encryption, on top of encrypted transmission (e.g. TLS)

**Comment by shermanCRL** [comment]
We’ve implemented AWS KMS last year, and have plans for more. Closing this issue (any objection @bram?), future work is tracked here:

- https://github.com/cockroachdb/cockroach/issues/72571
