### ISSUE TITLE
sql: add {SHOW/SET} ZONE sql command in shell to display zone config protobufs

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#5000]
Will need to be able to show zone for cluster, databases, & tables.

Also, need `SET ZONE` for same cluster, databases, & tables.

The input and output formats would be yaml.

**Comment by knz** [comment]
1) I'm not really comfortable with yaml for doing this; could you suggest why not using something more straightforward like JSON or at least something that does not make newlines mandatory?

2) how urgent is this? I'm rather far from this area of the product for now. @petermattis suggested to de-assign since I'm not planning to work on this in the next two weeks.

**Comment by petermattis** [comment]
The `cockroach zone` command already allows you to view the zone config for the cluster, databases and tables. We even have [docs](https://www.cockroachlabs.com/docs/configure-replication-zones.html). I don't think there is anything left to do here.
