### ISSUE TITLE
storage: investigate whether facebook/rocksdb#6973 should be backported

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#50182]
https://github.com/facebook/rocksdb/pull/6973

> Fix a bug that causes iterator to return wrong result in a rare data race
>
> The bug fixed in #1816 is applicable to iterator too. If a put and DB flush happens just between iterator to get latest sequence number and getting super version, empty result for the key or an older value can be returned, which is wrong.

**Comment by jbowens** [comment]
It looks like a very unlikely race but worthwhile to backport. I think the crux of the race is that if you grab a sequence number _before_ grabbing the superversion/readState, some keys visible at the sequence number you grabbed may have already been overwritten with more recent sequence numbers, causing you to think they didn't exist at all at your sequence number.
 
* Thread A writes Set(k, v1), updating the memtable. Thread A tries to read the value it just wrote and grabs a sequence number x to read from, but gets descheduled before it can acquire a reference to the super version.
* Thread B does a Set(k, v2) at sequence number x+1 and flushes the memtable.
* Thread A wakes up, grabs the new superversion. When it looks for the key k, it only finds k with sequence number x+1, so it returns that the key doesn’t exist.

Pebble doesn’t have the same problem for `Get` or `NewIter`, because we grab the read state before we pick a sequence number to read from. I think there’s a related (very unlikely) race with `NewSnapshot` though, because we grab the snapshot’s sequence number before we lock `d.mu` in order to append to the snapshot list.  If `d.mu` is contended and we get really unlikely, it seems like it would be possible for new keys to be flushed and eventually overwrite the snapshot's keys if the flush/compaction grabbed the snapshot list before NewSnapshot can append its sequence number.

**Comment by petermattis** [comment]
> I think there’s a related (very unlikely) race with NewSnapshot though, because we grab the snapshot’s sequence number before we lock d.mu in order to append to the snapshot list. If d.mu is contended and we get really unlikely, it seems like it would be possible for new keys to be flushed and eventually overwrite the snapshot's keys if the flush/compaction grabbed the snapshot list before NewSnapshot can append its sequence number.

Yeah, I think there is a problem here. I think we need to grab the sequence number atomically with adding the snapshot, which means grabbing the sequence number while holding `DB.mu`. Seems feasible to write a test which would demonstrate this badness.

**Comment by jbowens** [comment]
@petermattis How far back do you think we should backport the RocksDB bug?

**Comment by petermattis** [comment]
Responded verbally already. Responding here for posterity: 19.1, 19.2, and 20.1.
