### ISSUE TITLE
sql: support IMPORT PGDUMP into table with partial indexes

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#50225]
### Description

CockroachDB does not currently support `IMPORT`ing into a table with partial indexes.

### Workaround for IMPORTing into a table with partial indexes

1.  Drop any partial indexes defined on the table.
2. Perform the `IMPORT`.
3. Recreate the partial indexes.

### Workaround for IMPORTing a PGDUMP with partial indexes

1. Drop the partial indexes on the Postgres server.
2. Recreate the PGDUMP.
3. IMPORT the PGDUMP.
4. Add partial indexes on the CockroachDB server.

### Notes

In order to support this, the `DatumRowConverter` will need to evaluate partial index predicate expressions with the variables replaced with each row's values. I've left a [TODO here](https://github.com/cockroachdb/cockroach/blob/c1d0b4ac64711ab4fed3f13878e1ff3c523c8d74/pkg/sql/row/row_converter.go#L378-L379).

Jira issue: CRDB-4140
Epic CRDB-8353

**Comment by mgartner** [comment]
Currently, there is no paradigm for evaluating expressions, like partial index predicates, during an `IMPORT`. `IMPORT` [doesn't currently support computed columns](https://github.com/cockroachdb/cockroach/blob/4eac05a8e5b8d3caa1ea3bb654d6e074d7c84f7a/pkg/sql/row/row_converter.go#L504). It also doesn't validate the rows satisfy `CHECK` constraints:

```
root@localhost:26257/defaultdb> create table t (a int, b int, check (a > 2));
CREATE TABLE

root@localhost:26257/defaultdb> show create table t;
  table_name |              create_statement
+------------+---------------------------------------------+
  t          | CREATE TABLE t (
             |     a INT8 NULL,
             |     b INT8 NULL,
             |     FAMILY "primary" (a, b, rowid),
             |     CONSTRAINT check_a CHECK (a > 2:::INT8)
             | )
(1 row)

root@localhost:26257/defaultdb> import into t (a, b) csv data ('nodelocal://1/test.c
sv');
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
+--------------------+-----------+--------------------+------+---------------+-------+
  574429359494791169 | succeeded |                  1 |    5 |             0 |   105
(1 row)

root@localhost:26257/defaultdb> select * from t;
  a  | b
+----+----+
   1 |  1
   2 |  2
   3 |  3
  11 | 11
  40 | 40
(5 rows)
```

Therefore, I think a suitable first step for partial indexes is to err when trying to `IMPORT` into a table with partial indexes. The work around would be to drop the partial index, issue the `IMPORT`, then re-add the partial index.

**Comment by vy-ton** [comment]
fyi @rafiss another SQL incompatibility mentioned for IMPORT

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4140](https://cockroachlabs.atlassian.net/browse/CRDB-4140) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-50225`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by ecwall** [comment]
> Workaround for IMPORTing into a table with partial indexes
This has been tested and merged in #85244, but PGDUMP has not yet been tested.

**Comment by ajwerner** [comment]
@ecwall or @rafiss is it worth making a new issue to test pgdump and close this one?

**Comment by rafiss** [comment]
we won't schedule this work, as per https://github.com/cockroachdb/cockroach/issues/93660
