### ISSUE TITLE
twitchplays: ALTER TABLE gives 'i/o timeout'

### ISSUE THREAD

**Issue by riking** [cockroachdb/cockroach#50422]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. `create table fillup_keyed ( data float8 null, id1 uuid null default gen_random_uuid(),  id2 uuid null default gen_random_uuid(),  id3 uuid null default gen_random_uuid(),  id4 uuid null default gen_random_uuid(),  id5 uuid null default gen_random_uuid(), id6 uuid null default gen_random_uuid(), PRIMARY KEY (id1, id2, id3, id4, id5, id6) )`
2. `insert into fillup_keyed (data) select random() from generate_series(1, 100000)`; repeat a few times
3. `alter table fillup_keyed add column id1hash string as (sha256(id1::string)) stored`
4. Error: `read tcp 10.150.0.4:60597->35.190.189.85:26257: i/o timeout`

**Expected behavior**
Coherent statement timeout errors instead of TCP timeouts. As seen below, sometimes this returned actual timeouts instead of TCP errors.

**Additional data / screenshots**

https://clips.twitch.tv/AmusedDaintyDugongBCouch

**Environment:**

https://www.twitch.tv/twitchrunscockroachdb

**Additional context**
What was the impact?

Jira issue: CRDB-4122

**Comment by riking** [comment]
This may be an issue specific to the playground - when testing with CREATE INDEX + SHOW JOBS later, the commands that succeeded gave i/o timeouts, and the ones that failed gave timeout errors.

**Comment by jordanlewis** [comment]
Thanks for filing and checking out the playground! I'm pretty sure this is an issue with the program that sits in between the stream and the database, but maybe it points to a bug with the cancellation protocol. The error comes from the Go driver, not the database, and I'm guessing it's caused by the very aggressive statement timeout that's set on the client.

I think what's happening is that the statement timeout stops the SQL command from running on the server, but we avoid sending the right message back to the client, which is left hanging... something like that.
