### ISSUE TITLE
bulkio/import: IMPORT is not resilient to node failures

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50732]
I've hit this a few times over the past month and it really hurts. It appears that a single node failure, even if it's not the node running the IMPORT statement, can cause an IMPORT to fail. For instance, if any node in the cluster hits a `clock offset exceeded` error, the IMPORT will fail with that error. This can be a real bummer after getting 90% of the way through a 10TB IMPORT and hitting this on the 36th hour.

This may be part of a tracking issue about DistSQL resilience as a whole. If so, feel free to close.

Jira issue: CRDB-4096

**Comment by dt** [comment]
Yeah, ironically, we _are_ resilient to the failure of the coordinator node since the job will just resume from its persisted progress information, but any other node failing pops out of distsql as an error and we treat that the same as any other terminal error. BACKUP and RESTORE are similar.

**Comment by miretskiy** [comment]
I assume that you were running some sort of a heavy workload (tpcc)?  If that's the case, then I would argue that hitting
an error while the cluster is under heavy load is not much different from the interrupted http/GC cloud read error.
We used to propagate those and fail the import; now we don't.

So, I'd say that, ultimately, it's a question of determining if an error is retryable or not.  And that's not that simple, unfortunately.

Now, we could consider just blindly retrying the job up to X number of times if each retry makes progress.

**Comment by nvanbenschoten** [comment]
No, this wasn't under any load other than the IMPORT itself. A single node in a large cluster crashed because its clocks got out of sync and that killed the rest of the IMPORT.

> Now, we could consider just blindly retrying the job up to X number of times if each retry makes progress.

Ideally, we wouldn't even need to retry the entire job. Without knowing very much about what I'm talking about, it seems like we should be or already are checkpointing the progress of IMPORTs, so we should be able to pick up where we left off.

**Comment by dt** [comment]
Retrying the job would pick up from the persisted progress, just like if the coordinator had died. 

It isn't quite as simple as you might hope since you can't e.g. just seek to byte 5432 of an arbitrary input and start reading if e.g. it is a SQL or avro or whatever format where the parse has state, but instead we track i'th "row" of the input and then fast-discard rows until we get there on resume. In theory you could do something a bit smarter, but so much of the cost in ingest and not reading the input it hasn't made sense to invest there. Checkpointing is also a bit complicated since you have a reader at some position and then a lot of buffering and sorting and such downstream, so the i'th row read isn't always the i'th row ingested, but we handle all that too with some callbacks and hooks to keep track of what's been flushed all the way though. So, long-story short, we do have ability to pick up where we left off, it's just a matter of not marking the job as _failed_ when we see some kinds of errors. We don't currently have a good way to do that, but it shouldn't be hard.

**Comment by joshimhoff** [comment]
I ran three ~6 GB RESTOREs on a cloud cluster concurrently. I hit some OOMs! (A contributing cause there is that the CC cluster was on c5s, not m5s; we will eventually fix this.) It appears that 2 / 3 RESTOREs failed as a result of the crashes, as per this issue. Why do I think that? Well, one bc/ this issue is open. And two, the time correlation is very strong. The error was `communication error: rpc error: code = Canceled desc = context canceled`. I have a debug zip, if that is needed.

This is going to cause a lot of pain in our cloud environment, as crashes happen! I think we should consider fixing this in as part of 21.2.

**Comment by yuzefovich** [comment]
I think that this issue can be closed as a result of #60947 - @dt do you think otherwise?
