### ISSUE TITLE
sql/opt: could not produce plan conforming to LOOKUP JOIN hints on single column source table

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50841]
I've found a case where a pair of LOOKUP JOIN hints are being rejected iff the source table is constant and contains a single row.
```sql
-- setup schema
CREATE TABLE kv  (k  INT8 PRIMARY KEY, v  INT8);
CREATE TABLE kv2 (k2 INT8 PRIMARY KEY, v2 INT8);
INSERT INTO  kv  VALUES (1, 1), (2, 2);
INSERT INTO  kv2 VALUES (1, 3), (2, 4);

-- works
SELECT v, v2
  FROM (SELECT unnest('{1, 2}'::INT8[]) AS lookup_k)
       INNER LOOKUP JOIN (SELECT k, v FROM kv) ON k = lookup_k
       INNER LOOKUP JOIN (SELECT k2, v2 FROM kv2) ON k2 = lookup_k;

  v | v2
----+-----
  1 |  3
  2 |  4

--- works
SELECT v
  FROM (SELECT unnest('{1, 2}'::INT8[]) AS lookup_k)
       INNER LOOKUP JOIN (SELECT k, v FROM kv) ON k = lookup_k;

  v
-----
  1
  2

--- works
SELECT v
  FROM (SELECT unnest('{1}'::INT8[]) AS lookup_k)
       INNER LOOKUP JOIN (SELECT k, v FROM kv) ON k = lookup_k;

  v
-----
  1

-- does not work
SELECT v, v2
  FROM (SELECT unnest('{1}'::INT8[]) AS lookup_k)
       INNER LOOKUP JOIN (SELECT k, v FROM kv) ON k = lookup_k
       INNER LOOKUP JOIN (SELECT k2, v2 FROM kv2) ON k2 = lookup_k;

ERROR: could not produce a query plan conforming to the LOOKUP JOIN hint
```

This seems to be a recent regression, as it works on `v20.1.0-beta.4-817-gba19aa4` but does not work on `v20.2.0-alpha.1-606-g5286181aad`.

**Comment by RaduBerinde** [comment]
Isn't the first SELECT identical to the last one?

**Comment by nvanbenschoten** [comment]
Yes, sorry. Updated. It was supposed to be `unnest('{1}'::INT8[])`.

**Comment by RaduBerinde** [comment]
We inline the one value for `lookup_k` (making the condition `k=1`) and the lookup join is no longer generated. I guess we should disable `InlineJoinConstantsLeft` if the join has a hint.

**Comment by nvanbenschoten** [comment]
Either that or just don't return an error when this generates a HashJoin between the other two scans because the LookupJoin which was being hinted at was optimized away. I'll defer to you on how literally these hints need to be taken

Also, for context on why I'm using join hints in the first place, I've found that without it, planning takes about 15ms for this query (which actually contains 3 lookup joins). So the join hints cut a 45ms query down to 30ms, which has a noticeable impact on workload throughput.

**Comment by RaduBerinde** [comment]
It's a little hard to detect - the join still exists, it's just a hash join (with the constraint k=1 now pushed below).

**Comment by DrewKimball** [comment]
@nvanbenschoten what is the original query that took 15ms to plan? That sounds like a suspiciously long time.

**Comment by nvanbenschoten** [comment]
The query that took 15ms to plan was:
```sql
SELECT sum(s_num_out * dm_close)::FLOAT8 AS old_mkt_cap,
       sum(s_num_out * lt_price)::FLOAT8 AS new_mkt_cap
  FROM (SELECT unnest($1:::STRING[]) AS symb)
  JOIN (SELECT dm_s_symb, dm_close FROM daily_market WHERE dm_date = $2) ON dm_s_symb = symb
  JOIN (SELECT lt_s_symb, lt_price FROM last_trade)                      ON lt_s_symb = symb
  JOIN (SELECT s_symb, s_num_out   FROM security)                        ON s_symb    = symb;
```

Adding lookup join hints drops down the planning time significantly. However, we can't currently add one to the first JOIN because we hit this error if `$1` is a single element.

**Comment by andy-kimball** [comment]
It seems fragile to track down every rule that might cause a join pushdown rewrite and disable them, just b/c there are join hints. I think this shows a weakness in our current definition of how join hints work. Perhaps a join hint should be defined as "use this join type if it's possible, otherwise fall back to some other join type" rather than "use this join hint if it's possible, else raise an error". This will be endless whack-a-mole if we're trying to disable every rule that might lead to the inability to honor a join hint, or even worse, transitive rules that together lead to that outcome.

+@awoods187 for thoughts on whether we should modify the semantics of join hints like I outline above.

**Comment by andy-kimball** [comment]
Perhaps a compromise would be to raise an error only when we can prove that we can _never_ apply a hint. I suspect we can do this in most common cases after normalization but before placeholder assignment (e.g. can't use a merge or lookup join if there's no join filter). Just like today, this means that when migrating to a new release, the user can start seeing errors where before there were no errors (because we added a new rule that made the hint impossible to follow), but that's still much better than only seeing errors in production.

+@RaduBerinde
