### ISSUE TITLE
sql: coldata.Batch-aware distsql receiver and pgwire.conn

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50857]
The `Materializer` is expensive because it has to turn all of our nicely packed native data back into expensive boxed `tree.Datum`s. At the very end of the pipe, the `DistSQLReceiver`’s job is to push a row of `tree.Datum` into pgwire, by type-switching on the `tree.Datum` and converting into bytes.

If we have a pipeline of vectorized-only execution, there’s no need to convert to `Datum` at all. Theoretically, we could push an entire `coldata.Batch` to the receiver, and have the pgwire adapter churn through that batch itself, converting our physical datatypes directly to pgwire bytes, no wasted allocations.

I expect this would be a nice win, and bring us much closer to the dream of 0 pointless allocations in the query path.

A very cursory investigation shows that the main interface that would have to change is the `pgwire.conn`, which currently has a `bufferRow` method that takes `tree.Datums`. If we added a new method that took `coldata.Batch`, and propagated that change all the way up into the `DistSQLReceiver`, then the stage would be set for the vectorized planner to not plan that final `Materializer` in flows and instead push its batches right to the receiver.

**Comment by yuzefovich** [comment]
I have a prototype for this which - although incomplete - is able to run TPCH queries on a single node, but the initial performance numbers are not that promising - basically I see no performance difference. I think this is due to the fact that this root materializer sits at the very end of the flow, and only a handful of rows reach it, so still vast majority of work (and time spent) is  in the internals of the vectorized flow. For queries 11 and 16 that return 1k and 18k rows still no visible difference.

What's puzzling to me at the moment is that when I run `sql -e "select * from lineitem" > /dev/null`, on master (e.g. for [floats](https://gist.github.com/yuzefovich/b97690fd55b7861bacf5dd1cdb2e6c57)) it spends noticeably less time writing the data according to pgwire encoding than with the [prototype](https://gist.github.com/yuzefovich/87f7aba0e2ec4585deef18b7d15c18d0). I don't think there are any allocations occurring, and I'm thinking that it's likely due to the sampling nature of the profiler, but I'm not sure. I expected for such a query to actually see a difference.

Still, I believe it is very useful to address this issue because it will allow us to clean `vectorizedFlow` object: rather than us having to set the root materializer as the single processor in `FlowBase`, we will be able to handle both kinds of flow separately which is nice. Additionally, we'll be able to move out the logic that is responsible for shutting down the vectorized flow out of materializer which is also nice from the abstraction standpoint.

**Comment by yuzefovich** [comment]
I pushed my prototype in #51026. Note that it is in a very "raw" state (meaning that it contains a lot of copy-pasted code, no comments, poor naming, etc).

**Comment by yuzefovich** [comment]
#64697 introduces a flow coordinator and cleans up the materializer as I was mentioning above. I think that PR takes us one step closer to addressing this issue, and I believe it would be a nice to have to 21.2 to implement it, so I'm going to put in our 21.2 release column.

**Comment by yuzefovich** [comment]
I'll pick this up for today.
