### ISSUE TITLE
CockroachDb support for .net core framework.

### ISSUE THREAD

**Issue by rajeevsoni** [cockroachdb/cockroach#50896]
Support for .net core via EFCore ORM or some other way for seamless usage for developers.

**Comment by vy-ton** [comment]
@rajeevsoni We're working on full support for the Entity framework. You can see known issues on https://github.com/cockroachdb/cockroach/issues/48050 

The Microsoft team has merged scaffolding for EF Core, see [PR](https://github.com/npgsql/efcore.pg/pull/1379). Since this merged, EFCore will automatically detect if CockroachDB is being used. Please try it out and report any issues you encounter.

**Comment by rajeevsoni** [comment]
@vy-ton  thanks for sharing this. Will surely be trying this. If I found anything will share as well.

**Comment by rajeevsoni** [comment]
EFCore support is there, as mentioned in the above comments.
