### ISSUE TITLE
security: CockroachDB provides misleading message when using pkcs8 certs without a password

### ISSUE THREAD

**Issue by pip25** [cockroachdb/cockroach#51059]
I am trying to connect with the root user to a secure cluster with proper certificates only (the password is set to null). When using the JDBC driver version 42.2.8 or lower, it connects normally, but on higher versions, it fails with the following error message: "_Caused by: org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided._". 

Insecure mode continues to work. I haven't tried with users which DO have a password.

This was tested with CockroachDB versions v19.1.4 and the latest at the time of writing, v20.1.3. Connection fails with both. 

Checking the changelogs for the JDBC driver (https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.9), the new "pkcs12 key functionality" that was introduced looks suspicious, but I am not familiar enough with the internal workings of the driver to say this with any certainty.

This is not a blocking issue for now, since I can simply revert to an earlier version, but do note that the latest Spring Boot starter projects which many Java applications use as basis now pull in v42.2.12 (or higher) by default, so if anyone tries a new project with CockroachDB, they might find that secure mode simply refuses to work properly.

**Comment by rafiss** [comment]
@pip25 Thanks for filing this issue!

I think you are right -- the new pkcs12 support in PGJDBC is likely the reason for this behavior.

The docs here have some more information about connecting with a cert file, and they imply that a password is required: https://jdbc.postgresql.org/documentation/head/ssl-client.html

It says that the default password is `changeit`. Does it work if you use that?

I'm guessing that PGJDBC is requiring this because the implementation of pkcs12 requires a password. Check out the resources [here](https://stackoverflow.com/questions/20904657/using-a-p12-file-without-a-password-in-java), [here](https://stackoverflow.com/questions/1814048/sun-java-keymanagerfactory-and-null-passwords), and [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6415637).


Out of curiosity, if you are able to test with a Postgres backend, do you see any different behavior? Based on all this information, it seems like the same thing would happen, so I don't think there's any CockroachDB change that could fix this.

**Comment by pip25** [comment]
Thanks for the reply. It seems the root of the problem really is the driver, I was able to reproduce the issue with a PostgreSQL server (and the exact same certificates). I submitted a bug report there as well:
https://github.com/pgjdbc/pgjdbc/issues/1819

Do note, however, that CockroachDB appears to provide an inappropriate error message, since PostgreSQL responds to connection attempts with a *FATAL: connection requires a valid client certificate* error, while the message from CockroachDB gives the impression that there is nothing wrong with the certificates, only the password is missing.

**Comment by rafiss** [comment]
I've renamed the issue to describe the information about the error message.

cc @thtruo

**Comment by pip25** [comment]
@rafiss I've adjusted the title. My certificates were using a pkcs8 key instead of a pkcs12 one.

**Comment by knz** [comment]
> PostgreSQL responds to connection attempts with a FATAL: connection requires a valid client certificate error, while the message from CockroachDB gives the impression that there is nothing wrong with the certificates, only the password is missing.

CockroachDB's default authentication method is **Certs OR password**, ie. fall back to password if cert authn fails. This explains the behavior.

It's possible to configure crdb to only accept certs, in which case the error would be the same.

Does this clarify? Do we need more work on this issue?

**Comment by pip25** [comment]
It does explain why this is happening, thank you. Honestly, I'm not convinced such a "silent" fallback behavior is desirable, though I guess that's not up to me to decide.

**Comment by knz** [comment]
It's configurable. The current setting is what it is for backward-compatibility with previous crdb version. A user can override this for their cluster using the HBA configuration system.

**Comment by knz** [comment]
see https://dr-knz.net/authentication-in-postgresql-and-cockroachdb.html
for details.

I'm going to close this issue. If you have further questions or comments, please let us know.
