### ISSUE TITLE
ui: graphs don't always load

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5114]
Build sha:  0ed1dcea959db2c68e027cce85e1938631e7a128
This is after https://github.com/cockroachdb/cockroach/pull/5050, but before https://github.com/cockroachdb/cockroach/pull/5057, so it may no longer be relevant.

On a secure cluster, the overview graphs often load properly on page load, but sometimes break on automatic refresh. Sometimes, they don't load at all on page load and stay broken.

see: https://beta.cockroachdb.com:8080/#/cluster

**Comment by mberhault** [comment]
this is still iffy: https://beta.cockroachdb.com:8080/#/cluster
graphs kind of come and go.
current build sha: 7246138f9cc7ca7ac72952edf858e8fa532232b8

**Comment by mrtracy** [comment]
I cannot reproduce this locally; I'm wondering if this is an expression of #4617.  Let me know if you see this again, the beta link you provided is currently working as expected (although I did check it last Friday, and it was indeed broken as you claim).

**Comment by mrtracy** [comment]
Okay, found the repro on the beta cluster: it's a timeout issue.  We are setting a timeout of 2 seconds, the queries are simply running long (likely due to the long load time).

@maxlang was there any specific reason you added this timeout?

And a general question: should we just remove the timeout entirely, or keep it (while extending it a little) and message it better in the UI?

**Comment by maxlang** [comment]
Yeah I came to the same conclusion - I think I changed the timeout to 10s locally at one point and saw it resolved.

The issue was that if you don't set a timeout, the queries never... timed out. So if, for example, the server went down, the health check would break because once 6 other queries had gone out for various things metrics, events, and none had finished, the health check would get queued behind them and never return (even if just the health check had a timeout).

Changing the timeouts to 10s instead of 2s will fix this issue for now, but I don't feel these requests shouldn't take more than 2s to complete, so I feel like we should look into this more.

**Comment by tschottdorf** [comment]
If you were looking at this just now, the cluster was doing pretty badly.
On a timeout, maybe we can just keep the old graphs instead of flicking N/A
right away? Or maybe fade everything a little bit so you know from looking
at it it's not completely fresh.
