### ISSUE TITLE
Submitting your first PR

### ISSUE THREAD

**Issue by SpokeyWheeler** [cockroachdb/cockroach#51205]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Open https://github.com/cockroachdb/cockroach/blob/master/docs/first-pr.md
Click the link

Something went wrong
Try refreshing the page. Refresh
If the problem persists, contact Atlassian Support or your space admin with the following details so they can locate and troubleshoot the issue:

This code: 984f13
The URL of this page

Reload this page

Reloading doesn't help.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

See above

**Expected behavior**

I expected to see a wiki

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by irfansharif** [comment]
Hi @SpokeyWheeler, sorry that you ran into this. I just clicked through and it seems to have worked for me. Judging from that and the error code, I'm guessing it had something to do with Atlassian servers acting up. I'm going to optimistically close this out assuming it works for you now, but do re-open if it doesn't. Perhaps the contributing guide should simply sit in the repo itself instead of elsewhere.
