### ISSUE TITLE
The import job still runs after it has been cancelled

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#51455]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
I try to import 1TB csv files to CRDB, when I cancel the JOB, I find the JOB is still running, but the JOB status is CANCEL.
![image](https://user-images.githubusercontent.com/11207613/87541870-97c72a80-c6d4-11ea-8fd1-e6157c8eca3a.png)
![image](https://user-images.githubusercontent.com/11207613/87541883-9e55a200-c6d4-11ea-889b-99dfd1180df7.png)

I restart the cluster, the job continue running，I see massive disk and network traffic, and I find many split event from cluster log, the prefix of split key is data from CSV files,  so I remove all csv files, the job stop, I see no data write to the store.
but another bug is that: there is 800GB data in the cluster, but no way to GC.
![image](https://user-images.githubusercontent.com/11207613/87542007-ce04aa00-c6d4-11ea-87be-d1f8cad363ce.png)

My colleagues told me that if you cancel a restore job, the residual data cannot be cleaned up, I think it is the same bug.
**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
   V 19.2
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by adityamaru** [comment]
Hey @heidawei, thanks for reporting this!

In CRDB v19.2 when a job cancellation is triggered, its status is immediately changed to `CANCEL` but the job only **stops** running when it goes to update its progress the next time after the cancellation. The progress update will fail (as the status == `CANCEL`) and the job failure hook will attempt to clean up after the canceled job. This asynchronous nature of job cancellation is why you are observing it running for a little longer.

As for the behavior you observe on node restart, I believe it is the KV layer reacting to the imported data, the IMPORT job will not be adopted by any node on cluster restart because it is in the `CANCEL` state. 

Unfortunately, in CRDB v19.2 and less, the job cancellation/cleanup semantics were not very reliable/durable, and so the cluster could be in a state where the IMPORT job was canceled, the cleanup hook failed to run before cluster restart and now the cancel/cleanup will never be resumed after cluster restart. There has been a lot of work done in v20.1+ to make cancellation and cleanup resumable, reliable, and durable.

I would recommend dropping the imported tables to reduce the used capacity and upgrading to v20.1+ for more robust job cancellation semantics.

**Comment by heidawei** [comment]
thanks，I will upgrading to v20.1+  and try again.

**Comment by adityamaru** [comment]
Feel free to reopen/comment if you run into any other issues 🙂
