### ISSUE TITLE
import: rolling back failed IMPORT INTO into empty table is slow

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#51512]
When IMPORT INTO fails, it needs to undo whatever it did before it can return your table to you. In the general case it may have added any number of rows anywhere in your table, so we need to do a somewhat expensive `RevertRange` operation to find rows with timestamps that indicate they were written by the IMPORT and delete them one-by-one.

However in the special case where an IMPORT INTO is into an initially empty table, we could do much better than this -- if we knew that _every_ row in the table was created by the IMPORT and needed to be deleted, we could simply blindly ClearRange the whole thing, or even allocate a new table and schedule the failed IMPORT for async cleanup ala `TRUNCATE`. 

This would be a pretty simple check -- after schema-changing the table to OFFLINE state, we could just run a `SELECT COUNT(*) ... LIMIT 1`. As soon as we find even one row, we'd bail out. If we find zero, we can set a bit in the IMPORT job. If, during rollback we see that bit, we can simply truncate the table instead of reverting it.

**Comment by dt** [comment]
note: if the table is interleaved, clearrange would be bad but if we re-use TRUNCATE it should already handle that.

**Comment by pbardea** [comment]
From an offline discussion with @dt: Alternatively rather than performing a `SELECT` we could do a KV request for the table's range and see if there's any data there. That should tell us if it's safe to perform a ClearRange request. (Note that we wouldn't do this check if the table were interleaved since we wouldn't be able to safely perform a ClearRange in that case anyway.)

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/pull/52754
