### ISSUE TITLE
roachtest: jepsen tests must learn how to pass `--join` and `init`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#51739]
Our jepsen tests are currently all failing e.g:

```
E200722 08:19:46.369501 1 cli/error.go:394  ERROR: no --join flags provided to 'cockroach start'
```

**Comment by irfansharif** [comment]
Welp, I'm a bit amazed I'm learning about all of these failures through auto-filed issues after the fact instead of CI, forcing me to fixed these tests before merging. I don't know what I should've done differently, any hints?

How do I run these jepsen tests? The fix here is probably dead-simple (just having n1 point to itself), but I don't know where to look. I'll wrap it up in the morning.

**Comment by knz** [comment]
There's not much you would have learned during CI. It's on us (the team) to have failed to remember that Jepsen also initializes clusters, using logic separate from roachtest/roachprod.

The repository is here: https://github.com/cockroachdb/jepsen

The file you need to edit is this: https://github.com/cockroachdb/jepsen/blob/master/cockroachdb/src/jepsen/cockroach/auto.clj

Specifically this function: https://github.com/cockroachdb/jepsen/blob/master/cockroachdb/src/jepsen/cockroach/auto.clj#L177

Feel free to ask the team for help with the Clojure syntax. I find it rather intuitive but YMMV.

**Comment by knz** [comment]
> How do I run these jepsen tests?

My best bet would be a `roachtest` invocation.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/jepsen/pull/24, fun exercise.
