### ISSUE TITLE
ui: Admin UI login is not case-insensitive like SQL shell

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#51781]
The SQL shell lower cases all characters in usernames upon creation, however the admin UI does not do something similar which can lead to confusion. From @florence-crl:

root@:26257/movr> CREATE USER Admin1 WITH PASSWORD 'cockroach' ;
CREATE ROLE

root@:26257/movr> GRANT admin to Admin1;
GRANT

root@:26257/movr> SHOW USERS;
  username |  options   | member_of
-----------+------------+------------
  admin    | CREATEROLE | {}
  admin1   |            | {admin}
  root     | CREATEROLE | {admin}
In Admin UI,
(A) If you sign in with all lower case username admin1, privileges work correctly.
(B) If you sign in with all mixed case username Admin1, privileges will NOT work correctly; most noticeably on the Databases and Statements pages

**Comment by knz** [comment]
@piyush-singh  I think the code has a bug, but not the one you think!

### The misconception

Let's start with the end result. 
What if the SQL username did actually include mixed case? For example I could run this:

```sql
CREATE USER "Admin1" WITH PASSWORD 'cockroach';
```

Now this user is actually called `Admin1` in SQL, not `admin1`. How would this user log into the admin UI, if we were to case-fold the input in the login form to lowercase?

(You could try and tell me "the user should use double quotes in the form" - but that would not work either: first of all it's very confusing, and second it's also possible for the username to contain additional punctuation too.)


Now as to what is really going on.

The issue here stems from confusion about what is happening. The statement "The SQL shell is case-insensitive" is actually false. What is happening is that our SQL dialect automatically normalizes unquoted identifiers to lowercase, and otherwise preserves the case of quoted identifiers.

You can think of this as a *transformation* (and not "case-insensitiveness"):

- `SELECT AbC` is auto-transformed to `SELECT abc`
- `SELECT "AbC"` is not auto-transformed and the column remains called `AbC`.

The same applies for table names, usernames, settings, session vars, etc.

As a result, in your example above **the user is actually called admin1 (lowercase), not Admin1**. This is why that is what we want the user to enter in the form.

### The bug

If there is only a user named `admin1` in the database **we should refuse to let a user named Admin1 log in with its credentials**.

I am surprised this is possible today? (Taking your report at face value, it seems to be). If it is indeed possible, this may even be a security bug.

cc @dhartunian

**Comment by knz** [comment]
ok scratch everything I wrote above - the usernames in CockroachDB SQL are indeed case-independent, like in PostgreSQL. I did not fully understand this before.
I will send  a PR.

**Comment by knz** [comment]
Ah, dang it. In PostgreSQL usernames are case-sensitive, and they're not in CockroachDB.

This is ... confusing and unexpected.

@solongordon I'm going to fix the proximate issue that Piyush filed here, but we need to consider whether there are more surprises looming down the line due to case-insensivity in usernames / role names during session login.
