### ISSUE TITLE
util/encoding: consider changing float encoding

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5192]
https://github.com/google/orderedcode/blob/master/orderedcode.go#L246-L257 shows that we can encode the float64 bits reinterpreted as an int64. I think we'll have to do some additional handling of NaN, positive and negative infinity, but that shouldn't be a problem.

**Comment by jgraettinger** [comment]
Hi! This perhaps deserves it's own issue, but I also just noted that encoding.DecodeFloatAscending() produces invalid decodings if a non-nil `tmp` buffer is passed in. It happens because `decodeLargeNumber` & friends return `m`, which references into `tmp`, but `makeFloatFromMandE` then over-writes when working with `b`.

**Comment by nvanbenschoten** [comment]
Hi Johnny, thanks for the catch! A quick change to the tests shows that you're right. I am pretty surprised that we never exercised that path in either tests or real code. I'm going to open another issue and look at fixing this. After that, we can look towards actually providing the decode routines with a scratch space, as it should give a nice bump to float decoding performance.

**Comment by nvanbenschoten** [comment]
A rough implementation of this approach shows that it will lead to keys averaging about twice the size of the previous approach, but will also improve encoding and decoding speed by around 10x each!

Also, as discussed in person, since we are no longer sharing an encoding between decimal and float, we can optimize the decimal encoding in isolation (probably by using [`big.Int.Bytes()`](https://golang.org/pkg/math/big/#Int.Bytes)). I'll look into this after speeding up the float encoding. All of this needs to stabilize by the end of next week.

**Comment by petermattis** [comment]
The encoded values will be twice the size? That sounds fine if we're talking about moving from ~5 bytes to 9 bytes.

**Comment by nvanbenschoten** [comment]
It looks like we're going from a variable sized key that's anywhere from 3 to 12 bytes ([examples](https://github.com/cockroachdb/cockroach/blob/9160b7af808893a60544d2f0991755b43c965183/util/encoding/float_test.go#L79)) depending on the size of the mantissa, to an almost always fixed 10 bytes.

**Comment by petermattis** [comment]
Ah, yes. That seems correct. We might be able to shave a byte by using `EncodeUint64`, but we'd have to make sure we handle negatives correctly which would be slightly different than the orderedcode implementation. I think.

**Comment by nvanbenschoten** [comment]
Yep, that's exactly the effect that has. It also speeds up encoding and decoding by about 30% more.
