### ISSUE TITLE
Add flag to hide welcome text in interactive sql shell

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#52059]
We are starting to experiment with in-browser interactive tutorials. In cases where we want to immediately load up a sql shell for the tutorial, it would be nice to have a flag that lets you hide all of the welcome text and just show the prompt. In such cases, the welcome text is distracting and could even lead users to try things that aren't the focus of the tutorial. 

In addition to a flag for hiding welcome text, perhaps it'd be nice to have a shell option to reveal that information. This would even be helpful in cases where the welcome text is displayed.

**Comment by jseldess** [comment]
@knz, would this be easy to add? It would make the UX so much nicer for in-browser tutorials.

**Comment by knz** [comment]
Hi Jesse,
is this `cockroach sql` or `cockroach demo`?

Here's the list of all the welcome messages and what they are used for. Can you select/check those that need to be skipped?

- [ ] `sql` *"Welcome to the CockroachDB SQL shell ... to exit type \q"*
- [ ] `demo` *"Welcome to the CockroachDB demo database!"*
- [ ] `sql` *"Client version", "Server version"*
  used to detect when there is a client/server mismatch. If we don't print this, what do you suggest to detect misconfigurations in the deployment?
- [ ] `sql` *"Cluster ID: ..."*
  used to detect when the cluster was reset "under" the SQL client, or if the server has changed addresses and the client mis-connected to a different cluster.
- [ ] `sql` *"Organization: ..."*
  used to report on the current license, if any
- [ ] `demo` *"--geo-partitioned replicas operates on a 9 node cluster; the cluster size has been changed accordingly"*
- [ ] `demo` *"Partitioning the demo database, please wait..."*
  reported prior to partitioning, so that the user is informed why the prompt is taking a little while to appear
- [ ] `demo` *"Telemetry and license acquisition disabled by configuration"*
  printed if the corresponding env var was set
- [ ] `demo` *"Enterprise features disabled for OSS build"*
  printed if using an OSS-only executable
- [ ] `demo` *"This demo session will attempt to enable enterprise features ..."*
  printed prior to acquiring a license. If the license server breaks (which happens at least once per quarter), this hints as to why the shell seems to hang)
- [ ] `demo` *"Beginning initialization of the ... dataset"*
  reported so that the user is informed why the prompt is taking a little while to appear
- [ ] `demo` *"The cluster has been preloaded with the ... dataset"*
  printed when `--empty` was not specified or a dataset sub-command was used
- [ ] `demo` *"Reminder: your changes to data stored in the demo session will not be saved!"*
- [ ] `demo` *"Connection parameters: ..."*
  (also available via `\demo ls`)
- [ ] `demo` *"The user ... with password .. has been created. Use it to access the web UI"*
- [ ] `sql`, `demo` *"Enter \? for a brief introduction."*

**Comment by jseldess** [comment]
Sorry for the delay and lack of specificity. I'm specifically thinking about `demo`. Honestly, it might be best to have an option to hide all of the `demo` welcome messages, but the connection parameters are particularly misleading; when we embed demo in our docs, it's not possible to connect another client from outside that environment. Also, the DB Console won't be reachable at the address printed in the message. But for the DB Console, a more fundamental challenge is that it is not reachable at all when running demo in-browser because, to make a UI reachable, Katacoda requires the service to listen on all IPs, and I'm pretty sure `demo` listens only on `localhost`, without the option to change that.

**Comment by knz** [comment]
Ok I understand the use case now. Let's have the details about the addresses not visible.

**Comment by jseldess** [comment]
Thanks for resolving this, @knz! Did we ever open a separate issue about allowing `demo` to listen all all IPs rather than just `localhost`?

**Comment by knz** [comment]
>  allowing demo to listen all all IPs rather than just localhost?

I was not aware of this ask. Yes can you please file this issue and elaborate on it what's the user story exactly.
