### ISSUE TITLE
sql: COPY seemingly spends a lot of time in the optimizer

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#52071]
Trying out the osm2pgsql tool, which utilizes copies. Thus far I have found it spends most of its time in the optimizer trying to copy over ~10M rows (~4 of these in parallel). Here is a CPU profile over 10s during the COPY period:

![image](https://user-images.githubusercontent.com/3646147/88837791-744cb700-d18d-11ea-930f-5270942b1302.png)

Repro steps:
* Checkout https://github.com/openstreetmap/osm2pgsql/compare/master...otan-cockroach:crdb_branch, build using `cd build && cmake .. && make && cd ..`
* Run cockroach single node built with #52068 included.
* Download the dataset: https://download.geofabrik.de/europe/iceland-latest.osm.pbf
* Run the tool `./build/osm2pgsql -U root -d defaultdb -H localhost -P 26257 --number-processes 1 -C 20480 ~/iceland-latest.osm.pbf`
* Profile during this step:

```
Processing: Node(6965k 6965.0k/s) Way(356k 14.24k/s) Relation(5290 661.2/s)
```

PostgreSQL is able to do this in ~7s, we take ~49s. (maybe fodder for https://accidentallyquadratic.tumblr.com/)

Jira issue: CRDB-3984

Epic CRDB-14477
Epic CRDB-14916

**Comment by RaduBerinde** [comment]
COPY uses a batch size of 100 and compiles and runs an Insert statement each time. We could definitely increase the batch size. But that wouldn't fix the problem - a lot of the time is spent in `buildValuesClause`, which is proportional to how many rows we are inserting.

**Comment by RaduBerinde** [comment]
Full SVG here: https://gist.github.com/f37117d916906f98c756e5323668c138

**Comment by RaduBerinde** [comment]
Some interesting things:
 - the dataset has a lot of NULLs, and we spend a lot of time in `ConstructNull` (which is expensive because of hashing the type). We can fix this by caching one Null per VALUES column. Though we really should improve `HashType` to not allocate a string.
 - building the scalar properties is expensive, lots of small things add up. For example, simply returning a `ScalarListExpr` child as an `opt.Expr` is an interface-to-interface conversion which takes almost 3% of the time.

**Comment by RaduBerinde** [comment]
I looked around and I think we should rework COPY entirely. We would create a dummy tree.Statement type and register an "opaque" operator that gets built as a `scanBufferNode` that emits the rows buffered so far (and use that as the input to the INSERT rather than a VALUES clause). This will avoid a lot of overhead around getting the values through the optimizer and will also allow simple reuse of the opt plan.

**Comment by otan** [comment]
thanks for poking
cc @mjibson who said he's working on COPY on Fridays :)

**Comment by RaduBerinde** [comment]
I was just thinking it would be a decent Friday project. @mjibson if you're interested we can discuss my proposal in more detail (not sure how much it overlaps with your other work on COPY).

**Comment by awoods187** [comment]
Nice investigation!

**Comment by cucaroach** [comment]
I wonder if there's any cross over between https://github.com/cockroachdb/cockroach/issues/60651 and this.   Seems like an optimized bulk insert mechanism could cover both use cases?

**Comment by rafiss** [comment]
@cucaroach since https://github.com/cockroachdb/cockroach/issues/81731 was done, is this one closed also, or is there still more work for it?

**Comment by cucaroach** [comment]
No its done, thanks!
