### ISSUE TITLE
cli/demo: allow cockroach demo to specify a fixed port

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#52082]
**Is your feature request related to a problem? Please describe.**

Currently, `cockroach demo` uses a random port that changes every time you start a new demo cluster. This makes it difficult for users writing applications/scripts that they want to test against a demo cluster. They have to change their connection string every time a demo cluster is shut down/started back up.

**Describe the solution you'd like**

We should add a `--port` flag to the `cockroach demo` command that allows users to specify a fixed port at which the demo cluster listens for client requests.

**Additional context**

See [Set Up a Virtual Environment for Developing Multi-Region Applications](https://www.cockroachlabs.com/docs/stable/multi-region-setup.html) for an example context.

FYI
@jseldess

**Comment by bdarnell** [comment]
The use case of `demo` has drifted quite a bit from when it was first introduced. Originally it picked a random port because you were never intended to connect to it directly - it would just wire up an internal connection between the server and the `cockroach sql` shell.

Now that people are using it in very different ways, I think it might make sense to make it work more like a real server and use port 26257. Make the less common case of running both `demo` and another server at the same time be the case that needs an extra command-line flag.

(This gets a little trickier for the http port, though - 26257 is going to be available unless someone is running another cockroachdb server. But port 8080 is very likely to have conflicts on development machines)
