### ISSUE TITLE
sql: collect contention metrics

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52093]
I recently watched a customer try to debug a problematic transaction that content a slow query. When the query is run manually, it performs well. When it is run in the load, it performs poorly. We suspect that contention may be a cause but have no way to debug this problem with the customer. We can investigate long-running transactions but can't really see contention directly, at least not easily in this session. 

We should identify metrics of contention to expose to the WebUI and EXPLAIN ANALYZE(DEBUG) so that we can determine if contention is the reason for poor query performance.

**Comment by kocoten1992** [comment]
thank you, was very tempted create this kind issue, I wish to have this kind of metrics to know query conflicting and redesign application better.

**Comment by awoods187** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/52073

**Comment by bobvawter** [comment]
I'd love to be able to have a graph which shows the number of transactions that are blocked, pushed, or otherwise affected by concurrent transactions. The goal is to be able to drive that down to zero though code and schema changes.

The move to a serializable transaction model requires work on the part of our users and we should give them a signal showing that they're doing it correctly.

**Comment by jordanlewis** [comment]
cc @johnrk this is the kind of thing we were talking about in our meeting.

**Comment by ajwerner** [comment]
One thing I think this gets at that #52073 really does not is that this is about getting information back to the gateway about contention that a transaction experiences. That issue is more about getting a server-side perspective of contention. We still may utilize that server-side view of contention on the statements page by looking at the stats of the ranges underneath the statement plan.

**Comment by awoods187** [comment]
@asubiotto I think we can close this issue now with your various prs. 

Remaining open are https://github.com/cockroachdb/cockroach/issues/61478 https://github.com/cockroachdb/cockroach/issues/60156
