### ISSUE TITLE
stress: failed test in cockroach/util/retry/retry.test: TestRetryExceedsMaxBackoff

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5209]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b1125fa08614aa770703b67a18dfb9856e2cd4ad

Stress build found a failed test:

```
=== RUN   TestRetryExceedsMaxBackoff
--- FAIL: TestRetryExceedsMaxBackoff (1.00s)
	retry_test.go:44: expected retry loop to run for 20ms, actually ran for 1.00013201s
```

Run Details:

```
6485 runs so far, 0 failures, over 5s
12793 runs so far, 0 failures, over 10s
18870 runs so far, 0 failures, over 15s
24458 runs so far, 0 failures, over 20s
29262 runs so far, 0 failures, over 25s
34010 runs so far, 0 failures, over 30s
38666 runs so far, 0 failures, over 35s
43233 runs so far, 0 failures, over 40s
47710 runs so far, 0 failures, over 45s
52148 runs so far, 0 failures, over 50s
56451 runs so far, 0 failures, over 55s
60675 runs so far, 0 failures, over 1m0s
64817 runs so far, 0 failures, over 1m5s
68960 runs so far, 0 failures, over 1m10s
72934 runs so far, 0 failures, over 1m15s
76099 runs so far, 0 failures, over 1m20s
79977 runs so far, 0 failures, over 1m25s
83575 runs so far, 0 failures, over 1m31s
83576 runs completed, 1 failures, over 1m31s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
Truly bizarre that this test has failed. And not just once, but multiple times. That all the failures occur with an actual run time of ~1s is suspicious. Anyone have any thoughts about that?

I'm going to change the test to not actually do any sleeps. The test is verifying the max-backoff logic, but we can do that using the internal `retry.retryIn` method without ever calling `time.After`.

**Comment by bdarnell** [comment]
Regarding the 1s value: that's around what you'd expect to see if `MaxBackoff` were simply being ignored (the test uses a multiplier of 1e5 and an initial backoff of 10 microseconds, so if you ignore the limit then the next backoff is 1s). However, the test was not actually doing anything, and would pass if `MaxBackoff` were ignored, because it specifies a `MaxRetries` that is too low for the backoff cap to be triggered. So this test was only sleeping for 10 microseconds (plus or minus 15% for the randomization factor), and waking up after a second. Bizarre.
