### ISSUE TITLE
Makefile: need better bootstrap regen detection

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#52477]
The recent addition of protoc-gen-doc (#51803) caused people to have problems building:

```./bin/protoc-gen-doc: program not found or is not executable```

Running `rm bin/.bootstrap` fixes this. We need some better detection to regenerate .bootstrap when there are new programs added.

Epic CRDB-10447

Jira issue: CRDB-3944

**Comment by knz** [comment]
The problem here is twofold:

- the various utilities in `bin/` do not depend on the `.bootstrap` target
- the various uses of the utilities in `bin/` do not depend on the executable in `bin/` and thus not on `.bootstrap`. 

So if we introduce a new utility and just change the *action* for `.bootstrap`, "nothing happen" and the uses of the new utility fail until the user explicitly refreshes `.bootstrap`.

IMHO it would be time-consuming and error-prone to establish all these dependencies at a fine grain. I have a better suggestion:

- extract the rule that builds `.bootstrap` into a separate makefile `bootstrap.mk`
- make the `.bootstrap` depend on `boostrap.mk`
- make the various uses of utilities depend on `.bootstrap`

This way if we ever modify `bootstrap.mk` to add a new `go install` line, that will force a refresh of `.bootstrap` upon first use of a utility.

**Comment by jordanlewis** [comment]
No longer relevant given bazel.
