### ISSUE TITLE
kvserver: fatal assertion during range being subsumed

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#52517]
Saw this happen [here](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2159211&_focus=205443), which happened running TestParallel/create_stats under test race I think.

```
I200807 06:08:21.161099 9680 kv/kvserver/replica_command.go:414  [n1,split,s1,r36/1:/System/tsd/cr.node.s{ec…-ql…}] initiating a split of this range at key /System/tsd/cr.node.sql.distsql.exec.latency-p99.9... [r69] (34 KiB above threshold size 32 KiB)
F200807 06:08:21.512884 9862 kv/kvserver/replica_write.go:160  [n1,s1,r53/1:/System/tsd/cr.node.txn.…] lease applied index bumped while the range was subsumed
```

Looks like we were in this area recently as of #50265.

**Comment by nvanbenschoten** [comment]
That's not good. We should start logging the batch summary in this fatal message and then stress `TestParallel/create_stats`.

**Comment by aayushshah15** [comment]
I played around with this. The assertion fires because of the change I made to `checkExecutionCanProceed` in #51594. After the change, `checkExecutionCanProceed` will only block a request due to an ongoing merge if we have a `VALID` `LeaseStatus`. However, before sending a `TransferLeaseRequest`, the `AdminTransferLease` logic [explicitly invalidates the current lease](https://github.com/cockroachdb/cockroach/blob/4ed88b93c7ce25f98832eb9abfa1f7801e99af50/pkg/kv/kvserver/replica_range_lease.go#L701) on the (soon-to-be old) leaseholder. This means that `TransferLeaseRequest`s have to have the `skipLeaseCheck` flag & they're evaluated with a `LeaseStatus` object in the `ERROR` state, and thus these requests don't check for a pending merge. 

I'm sending a PR out with a fix.

**Comment by nvanbenschoten** [comment]
What is the proposed fix? It seems like `TransferLeaseRequest`s should not be allowed during a merge's critical section because they bump the lease applied index on the range. Only `RequestLeaseRequest`s should be allowed because they do not:
https://github.com/cockroachdb/cockroach/blob/829451573eff2d568e64259ac6daf648b78a4b25/pkg/kv/kvserver/replica_proposal_buf.go#L189-L193
