### ISSUE TITLE
backupccl: write checkpoint in resume, not planning

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#52922]
`VerifyUsableExportTarget` currently runs during backup planning, including for `DETACHED` backups.
However it _writes_ to the BACKUP-CHECKPOINT file, which has the side-effect of preventing any BACKUP from starting in that destination, but doing so during planning of a DETACHED BACKUP could mean that the backup itself is rolled back, leaving the CHECKPOINT file behind. 

We should separate this: a) attempt to write some other file to verify write access and then clean it up (but ensure that it has no side-effects if left behind) b) write the checkpoint file as soon as the backup actually begins executing, if it doesn't exist, for mutual exclusion.

**Comment by pbardea** [comment]
In addition, I think that we also need to add some type of job specific information to the backup manifest that we save in the checkpoint file if we want to still use the checkpoint for mutual exclusion.

Otherwise, when Resuming and the backup finds that there already exists a backup file, it will not be able to differentiate the case that the same job has already created the checkpoint file on a previous attempt or if another concurrent backup got to the destination first.

**Comment by dt** [comment]
I was thinking _writing_ it in Resume is fine as it’s then exclude _planning_ a new backup there since we’d leave the read of it in Verify during planning?

**Comment by pbardea** [comment]
Ah, I was thinking that we could have a race between reading and writing it - but we already have that race today (and would also have it if we both read and wrote in Resume since `storageccl` doesn't have a "WriteIfNotExists").
