### ISSUE TITLE
document known geospatial limitations

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#52970]
some known issues (when compared to PostGIS)
* `@` operator cannot work in CRDB. instead, switch anything that looks like `a @ b` to `b ~ a`. (#56124)
* cannot insert into spatial_ref_sys yet. working to use SRID 0. also blocks `ogr2ogr -f PostgreSQL`.... (#55903) 
* cannot import data from `ogr2ogr` to other formats, as we do not yet support `DECLARE CURSOR`. requires exporting cockroachdb as CSV or GeoJSON. (#41412) 
  * external tooling from "External TOoling" column in https://github.com/orgs/cockroachdb/projects/6

**Comment by rmloveland** [comment]
> switch anything that looks like a @ b to b ~ a

bummer about the reversal of operands, otherwise might be easy to regex. is this `~` new syntax from us? or does something else use the `~` also? 

(really what I'm asking is: is it fundamental to re-order the operands from `@`?)

**Comment by otan** [comment]
> (really what I'm asking is: is it fundamental to re-order the operands from @?)

yeah, it doesn't work with our current parser definitions :(. introducing the syntax makes other syntax such as `SELECT @1 FROM x` not work, which is fundamental in getting other parts of the codebase (e.g.sql execution) to work.

**Comment by awoods187** [comment]
Could you explain this further? Why do we differ from PG here?

**Comment by otan** [comment]
We've reserved the `@` operator for things like column definitions (`select @1, @2 from tbl`) or index specifications (e.g. `select * from tbl@idx`, which conflicts with @ being allowed as an operator (e.g. `SELECT a @ b`). Being able to solve this ambiguity with the parser due to custom syntax already in place is hard.

**Comment by rmloveland** [comment]
> is it fundamental to re-order the operands from @?

Thanks Oliver!  I may have misunderstood your response but what I was trying to get at is: even though we cannot use `@` for this operator and will use `~` instead, would it be possible to keep the ordering of the operands the same, e.g.

`a @ b`

becomes 

`a ~ b`

This will make a lot of things easier because as you know `a` and `b` can be pretty huge expressions, and reordering them in one's code etc. could be kinda painful vs. (in my dream world) having the option to do something fairly naive like `s/ @ / ~ /g` on a SQL file.

Sorry if you already answered this above, guess I did not understand.

**Comment by otan** [comment]
Ah sorry, no. a ~ b means a contains b, and a @ b means a is within b, which are opposites.
the exact nature is `a ~ b` = `b @ a `.
