### ISSUE TITLE
dealing with clock offset monitoring alerts

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#531]
The code in `rpc/clock_offset.go` periodically tries to measure the maximum clock offset present in the cluster. Currently, when the offset cannot be measured, the node is shut down harshly via `log.Fatalf`.

It may generally not be a good idea to take such action when considering time zone changes as it may instantly kill the whole cluster. What we really want is to make sure that someone is going to fix the problem very soon, i.e. that it ends up prominently in whatever is going to be monitored by administrators.

**Comment by bdarnell** [comment]
Time zone/daylight-savings changes don't affect the unix timestamp so that shouldn't be an issue, although we could still have mass deaths when the local NTP server changes its mind about what time it is. I think that's OK though. Killing the server when the offset can't be measured seems harsh, but if there's a significant clock difference we do need to kill the server - otherwise we can have replicas diverge due to differing response cache expiration.

**Comment by spencerkimball** [comment]
Agreed. I think we want to commit suicide until we have a more elaborate solution. Let's fix this when we encounter it.
