### ISSUE TITLE
Structured log format

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#532]
Currently logs output by Cockroach follow the glog format, but the actual log message is mostly free text.
That seems ok for the debug-free output, but once you turn up verbosity just a little bit, it becomes really hard to make sense of what's going on by manual inspection. Whenever troubleshooting a particular request I wind up trying just that, and I would imagine that the same thing would happen in production setups when individual requests are traced and debugged.

For log outputs which are associated to an operation (for example `Scan), to a `client.Call` or a transaction (i.e. whenever a `TxnID` or `ClientCmdID` is available), those lines should be output in a way that can be parsed automatically. Log output such as
```
I0401 11:37:19.112100   14300 retry.go:93] routing Scan rpc failed; retrying immediately
```

isn't valuable without stating that additional information, for example in the form
```
I0401 11:37:19.112100   14300 retry.go:93] user=root cmd=Scan cmd_id=12412,12 msg=rpc failed; retrying immediately
```

The same goes for

```
W0401 11:37:19.112022   14300 dist_sender.go:413] failed to invoke Scan: key range "a"-"z" could not be located within a range on store
```
which could take the form
```
W0401 11:37:19.112022   14300 dist_sender.go:413] user=root cmd=Scan cmd_id=... err=key range "a"-"z" could not be located within a range on store
```

and many others from that context.

I'm not sure if that's the best approach and how to specify the format, but I think it's worth thinking about.

**Comment by petermattis** [comment]
I'm not sure if I would describe this as structured logging (the output could be difficult to parse if `err=` could contain anything), but I'm a fan of having a common format and location in the log message for known data such as user, cmd and cmd_id.

**Comment by bdarnell** [comment]
We should probably start using https://godoc.org/golang.org/x/net/context to pass around this contextual information. 

As for the output format, there's a new standard for JSON text sequences: http://www.rfc-editor.org/rfc/rfc7464.txt. This might be an option to have logs that are basically human-readable (albeit quite verbose) but can have machine-readable structure. Or we could define a protobuf-based log format to use instead of or in addition to the free-text logs (e.g. saving the exact arguments passed to Infof() so we can reconstruct the textual message but also examine individual fields without parsing strings).

**Comment by tschottdorf** [comment]
A `context.Context` is not ideal for this sort of thing because while it allows storing key-value pairs, it doesn't allow listing the stored key-value pairs. But morally we want something like a context that can do that (and probably at some point we'll want to use things like deadlines and cancellations anyways).

I took a look at the [log15](https://github.com/inconshreveable/log15) package, and it generally seems to capture what we want fairly well. It's opinionated towards machine-parsable logging (so a log event is basically a short descriptor of the type of event and then key-value pairs) and looks pretty configurable.

If that sounds like a good starting point I'll start by doing some exploratory work for store/range, passing through context from `store.executeCmd`.

**Comment by bdarnell** [comment]
The point of `context.Context` is that it can be shared across packages without conflicts; it's good that it doesn't allow enumeration of its contents because I don't think we'd want to write *everything* that gets written to the context into the logs (for example, etcd/raft also uses `context.Context`; we don't want to blindly write anything they put there into our logs). Our logger should either have a set of well-known keys that it looks for for our logging context or we could put a map in there for arbitrary keys and values.

**Comment by tschottdorf** [comment]
ok, I'll start by putting a Context in Store and passing it around.

**Comment by tschottdorf** [comment]
Current plan:

- [x] add switch to `glog` that omits the header (so it prints only your log message)
- [ ] add functions `log.Infoc(ctx context.Context, msg)` which will wrap around `clog.Print(f?)`
- [ ] glog custom header formatter so that we can get the file, lineno, ... into structured data
- [ ] clean up the other formatted loggers. We shouldn't be logging much unstructured data at all, so it may be a good idea to remove all log functions `log\.\w+f`. 
- [ ] switch away from flag handling, or at least switch to pflags.

**Comment by tamird** [comment]
What's the state of this?

**Comment by tschottdorf** [comment]
I think this issue has accrued so much dust that whatever is left of it can just go into a new issue when we get around to brushing up the logging once more. If nothing else, the items above have all been dealt with.
