### ISSUE TITLE
bulkio: on_execution_failure=reschedule doesn't work as expected

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53227]
`on_execution_failure=reschedule` seems to have the same behavior as `on_execution_failure=retry` where it retries the BACKUP command a minute after the last failure.

To reproduce:
- Create a schedule -- first backup starts running
- Invalidate credentials mid-way through -- backup fails
- Watch for retries every one minute

**Comment by miretskiy** [comment]
I'm pretty sure as to the root cause for this.  First, the 1 minute retry was not the retry that was due to `on_execution_failure=retry` policy; it was merely the frequency we check for schedules to execute.

The problem is that during schedule execution phase, we execute each schedule under a savepoint.
If the execution fails, we rollback.  So, if backup planning failed (for example because of the keys that no
longer valid; remember the backup used to read/write some files while planning), then we would just rollback
to savepoint, mark the schedule status as failed execution and just go back to sleep for 1 minute until
the next time to scan.

We have to treat those planning errors the same way as the failures during job execution: that is
we have to invoke NotifyJobTermination on the schedule executor.
