### ISSUE TITLE
IMPORT that can overwrite duplicates rather than fail

### ISSUE THREAD

**Issue by dankinder** [cockroachdb/cockroach#53363]
**Is your feature request related to a problem? Please describe.**
This came up [on the forum](https://forum.cockroachlabs.com/t/how-to-ignore-error-rows-during-import/3930/4) and @ajwerner suggested filing an issue.

I would have expected `experimental_save_rejected` to work not just for rows with parsing errors but also for rows that violate constraints, but this doesn't produce any output file:
```
CREATE TABLE mytable (stuff STRING PRIMARY KEY);
IMPORT INTO mytable (stuff) CSV DATA ('nodelocal://1/stuff-0.csv') WITH experimental_save_rejected;
ERROR:  duplicate key in primary index: duplicate key: blah
```

Where `stuff-0.csv` is something like:
```
blah
blah
somethingelse
```

**Describe the solution you'd like**
Granted, this is an experimental feature as it is, but it's useful.

The simplest solution would be to correctly identify which rows are violating the constraint.

A much nicer solution would be a flag for how to behave when constraints are violated, e..g `WITH overwrite_duplicates` which would cause the values being imported to overwrite whatever was already in the table.

My use case is a migration from one system to CRDB where I want to minimize downtime. It's a large amount of data, and I would like to be able to run a bulk import while the original system is online, then have a short downtime where I select on the data that has changed and import that. Without such a feature I have to use normal UPSERTS for the 2nd import which is much slower than CSV import.

**Describe alternatives you've considered**
As already described, using the normal write path is the only alternative and it's much slower.

Epic CRDB-7909

Jira issue: CRDB-3872

**Comment by dt** [comment]
Thanks for filing this!

Unfortunately it is pretty difficult to support for tables with any indexes, so it is unlikely we'd implement it in IMPORT, but for use-cases which need uniqueness violation handling other than rejection, batched SQL `INSERT.. ON CONFLICT`/`UPSRET` should be able to do what you want. 

While that's the short version, if you or anyone else coming along to consider working on this issue want the nitty-gritty details of why this is hard, here's the long one: 
Say you have this table: `CREATE TABLE (i PRIMARY KEY, x STRING UNIQUE)` and your input data is `(1, a), (2, b), (1, c)`. 

If we ingest the row and index entry for (1, a)` we'll produce two entries: one, in the primary index, for "1" and one, in the secondary index on `x` for "c". Now we ingest `(2, b)` and do the same. Now we get to `(1, c)`. This will produce two entries again, one for "1" in the primary index and one for "c" in the secondary index, but critically the first is a duplicate of the existing entry we ingested for the first row. If we allow their addition, the one for "1" in the primary key will _replace_ the prior one, effectively replacing the row (as suggested in this issue), but that row's already ingested entry for "a" in the index on "x" is a problem, since the entry from this row, for "c", will _not_ replace that entry for "a".

If this were a full-fledged SQL `INSERT` statement executing, the insert of the new row 1 would look up the previous value for that row and determine that it will b effectively removed to make way for the new one, and then derive any index entries that correspond to it and remove them as well, i.e. in this case "a" in the index on x. But part of what sets IMPORT apart from writing via normal SQL is it just writes, more or less blind, and in bulk. It doesn't go row by row checking if it already exists and optionally running conflict resolution code that maintains correctness of all the indexes.

While the index on x here is unique, it doesn't need to be -- it'd still have too many entries here if it were a non-unique index as it'd have the orphaned entry for "a" either way. If in the future IMPORT switches to just ingest rows (the PK) on the first pass and then trigger after-the-fact index builds, then we could see a replace-on-duplicate approach working, but for now it'd be unable to ensure correctness for tables that have indexes.

**Comment by dankinder** [comment]
Hi David, thanks for the thorough explanation.

In my case it would be sufficient to have this feature even if the only index is the primary key index. I also imagine it would be faster to do this bulk insert and then build the indexes rather than use SQL `INSERT`.

But granted, this is less useful given that it won't work if there are any non-primary indexes.
