### ISSUE TITLE
bulkio: Telemetry for Scheduled Backups

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53427]
We want to be able to see how people use scheduled backups, and how often they run into issues. At a high level, our goals are to understand:
1. What types of usage are occurring
2. What problems people have with the feature

Suggested things to measure:
- Schedules created successfully, schedule creation failed (can we know why failed? worth it?); Options included (FULL BACKUP option? first_run? on_execution_failed?)
- If backup was from schedule or explicit, and whether it failed or succeeded
- Dropped schedule

Others to consider:
- Schedule skip / failure / retry and reason (could get spammy but could be valuable)

**Comment by pbardea** [comment]
It sounds like there's a 2 categories here:

**Schedule Creation/Editing**
- The metrics that I'm thinking of including here:
   - Schedule Control
      - [ ] Dropped schedule
      - [ ] Paused schedule
      - [ ] Resume schedule
   - [ ] Schedule creation success and failure
   - [ ] If the user is enterprise
   - [ ] If the backup schedule also had an incremental backup schedule
   - [ ] If the backup schedule automatically determined the full backup frequency
   - [ ] If the scheduled has a recurrence at all (one-off)
   - Usage of options:
        - [ ] Specified first_run
        - [ ] Error policy
        - [ ] Pause wait behavior policy

**Backup Execution**
When we execute a backup today, we have some telemetry to understand telemetry features. It sounds like it would be useful to augment the current telemetry to point out which of these backups are scheduled and which are not. I'm not sure which schema would work better to label these features as originating from scheduled backups.

Question: Can we query telemetry features by prefix?

If so, I think it makes sense to add a suffix of `.scheduled` to the metrics that we currently emit for backup (let's call this option A). If not, then I think we could emit both the counter that we do today, as well as the suffixed feature (let's call this option B).

So option A would emit `backup.span.incremental` for non-scheduled incremental backups and `backup.span.incremental.scheduled` for scheduled incremental backups. Option B would emit only the former for non-scheduled backups and both for scheduled backups.

**Schedule Specific Execution**
I'm not sure what the best way is to collect information about schedules skipping/waiting since I'm not sure if there's a way to differentiate between 10 clusters that each had a scheduled that skipped once or 1 cluster that had a scheduled that skipped execution 10 times. I'm open to ideas here and still brainstorming -- maybe it would be interesting to report how long a schedule has been delayed?

**Failure Reason**
I think we can include this if we have specific failure modes we're looking for, but generally telemetry metrics should be a constant feature name. Perhaps it would be useful to differentiate between failures during planning and the actual execution of the backup. Although, I think that we could generalize that to all backups.
