### ISSUE TITLE
bulkio: More Backup telemetry

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53430]
We've added some new features and functionality so we should track its usage, if we can.

Suggested metrics:
- Used KMS for encryption of backups
- Usage of into, to vs. explicit incremental

For discussion:
- Should we see how many times we run at "high priority" because of waiting on an intent too long?

**Comment by pbardea** [comment]
I'm thinking that in addition to the logs that we log today, we also include:
- [ ] Encryption mode (passphrase vs KMS)
- [ ] If the backup was nested
- [ ] If the backup was INTO LATEST

And maintain:
- [ ]  If the backup was incremental (regardless of nestedness, or auto-append)
- [ ] If the backup was using an auto-append directory (regardless of nestedness)

I'm weary of including "high priority" since this is managed on a per-node basis, and may be reported multiple times in a backup (also if the backup is retries). We could emit some metric every time a node first has to resort to high-priority, but this metric might be a bit messy since it won't be a 1:1 correspondence with a backup job.

**Comment by pbardea** [comment]
Done in #54546 and backported in https://github.com/cockroachdb/cockroach/pull/54864.
