### ISSUE TITLE
bulkio: can't tell whether the full file was loaded or not when using userfile

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53513]
When using userfile, I forced a "failure" by turning off my wifi. Eventually my shell closed the connection. I expected there to be some notation of a failed upload but instead everything "looked" like a success and a partial file was uploaded.

The ideal experience is some way for the user to easily validate whether the file was uploaded successfully as expected, and to have a way to delete the partial file, the partial file to not show up there, etc.

The key user problem to solve here is having the *confidence* that my upload completed, with the file's data being complete, so open to any solution that addresses that (and doesn't necessarily need to cover my above suggestions)

**Comment by adityamaru** [comment]
cc: @dt 

@miretskiy and I spoke extensively in the morning trying to reach a consensus on what the txn semantics for userfile should look like. The main concern we settled on was whether we really do want userfile to perform all of its create/write operations within a single txn. This makes sense when talking about it from the copy machine POV because we can plumb the copyTxn and do all the creation/writing in that - but in the case of BACKUP to userfile it was not so clear. Which txn do we use, how many operations will be within that txn, will the size of the operations in a single txn have significant performance impacts?

One solution which gives us the "transactional semantics" for userfile upload but leaves BACKUP/IMPORT usage untouched is to write to temp tables when coming from the copy machine. Then when the copy machine is ready to commit, we `SELECT * FROM` copy the temp tables to persistent tables. Granted this is rewriting all the data again, but it also gives us the cleanup semantics we desire in case the copy txn is rolled back. A failed BACKUP would however still leave behind partially written files but as far as I know we don't cleanup after ourselves if we fail to write to any external storage?

There is also the option which was briefly touched upon of only populating the metadata filename column on userfile COMMIT, thereby indicating to the user that the whole operation has succeeded. This would mean switching to file UUIDs while the Write() is going on, and would also involve changes to the other operations which rely on filename to identify chunks. Would we implement any cleanup semantics in this case if we rollback the copyTxn?

**Comment by mwang1026** [comment]
While this is a bad user experience, we also should consider a "do nothing" option here. While a bad experience, if there is a proxy for the user to know it completed successfully, either looking at the "file size" and comparing to what they expect, etc. then we could live with this for now -- but we should pin down time to improve it.

It's also helpful to know how other file transfer from client protocols / work to see if we have comparison points.

I don't have a sense of the complexity of the above options -- if they're v easy I think no brainer, but if it's complicated I think we should consider the "do nothing" option.

**Comment by adityamaru** [comment]
another quicker, less intrusive bandaid solution would be to plumb the expected size of the file being uploaded to the FileTableStorage layer, and just before closing the writer, checking that against the bytes written to the userfile tables. This "verification" step could then error out causing the txn we write in, to rollback its inserts. This way we can keep the txn semantics as they are right now - allow userfile storage to spawn a new one on every call to WriteFile, but also prevent the user from seeing partially written payloads.

I still need to prototype this, but just floating the idea.

**Comment by dt** [comment]
I'm somewhat inclined to switch to UUID-based file chunk PKs _anyway_ to make cheap renames, and then the client can do the same thing any other file upload client would do and upload to a tmp name and rename after. I think we want O(1) renames _anyway_ so this seems worth doing, and if we do it now we don't need to worry about migrations unlike if we wait?

**Comment by adityamaru** [comment]
@mwang1026 closing this because we have switched to writing tmp suffixed files now.
