### ISSUE TITLE
sql: Hibernate query to load type metadata started failing 

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#53854]
Hibernate makes the following query to load type metadata:

```
 SELECT t.typname, t.oid FROM pg_catalog.pg_type AS t JOIN pg_catalog.pg_namespace AS n ON (t.typnamespace = n.oid) WHERE (n.nspname != 'pg_toast') AND ((t.typrelid = 0) OR (SELECT c.relkind = 'c' FROM pg_catalog.pg_class AS c WHERE c.oid = t.typrelid));
```

Sometime in the past 3 days it started failing with `ERROR: use of crdb_internal_vtable_pk column not allowed.`

Expected result:

```
     typname    |  oid
----------------+--------
  jsonb         |  3802
  _name         |  1003
  regproc       |    24
  geography     | 90002
  _bit          |  1561
  _time         |  1183
  _oid          |  1028
  _char         |  1002
  bit           |  1560
  int2vector    |    22
  varchar       |  1043
  _varbit       |  1563
  _regclass     |  2210
  _record       |  2287
  anyelement    |  2283
  bytea         |    17
  _int2vector   |  1006
  timestamp     |  1114
  _timetz       |  1270
  _float4       |  1021
  bool          |    16
  name          |    19
  _geography    | 90003
  _interval     |  1187
  int2          |    21
  record        |  2249
  _jsonb        |  3807
  _date         |  1182
  int8          |    20
  timetz        |  1266
  varbit        |  1562
  text          |    25
  _text         |  1009
  _oidvector    |  1013
  float4        |   700
  interval      |  1186
  regprocedure  |  2202
  regtype       |  2206
  timestamptz   |  1184
  uuid          |  2950
  _timestamptz  |  1185
  _int2         |  1005
  float8        |   701
  int4          |    23
  inet          |   869
  _geometry     | 90001
  _bpchar       |  1014
  bpchar        |  1042
  _bool         |  1000
  _numeric      |  1231
  _float8       |  1022
  _bytea        |  1001
  _inet         |  1041
  char          |    18
  oid           |    26
  _varchar      |  1015
  _regnamespace |  4090
  _int8         |  1016
  _timestamp    |  1115
  _regprocedure |  2207
  regnamespace  |  4089
  time          |  1083
  _regtype      |  2211
  geometry      | 90000
  _int4         |  1007
  _regproc      |  1008
  regclass      |  2205
  unknown       |   705
  _uuid         |  2951
  anyarray      |  2277
  date          |  1082
  numeric       |  1700
  oidvector     |    30
(73 rows)
```

**Comment by RaduBerinde** [comment]
I think the problem is related to [EnsureKey](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/norm/decorrelate_funcs.go#L350)

This code has some logic to avoid adding `crdb_internal_vtable_pk` to a scan, but we would still use it if it was already part of the scan. Note that it's not enough to tweak this function, we'd also need to somehow make sure that the ordinality column and not `crdb_internal_vtable_pk` would be chosen as the key.

We could mess with the logical properties and never expose `crdb_internal_vtable_pk` as a key but I'm not sure if other stuff can break that way. The alternative would be to make the virtual table scan actually return a unique int value for `crdb_internal_vtable_pk` - @jordanlewis how hard would that be?

**Comment by RaduBerinde** [comment]
> We could mess with the logical properties and never expose crdb_internal_vtable_pk as a key

Hmm, actually, it looks like we already do that. I'll investigate some more. It's hard because we can't use optsteps (these tables aren't available in the test catalog).

**Comment by RaduBerinde** [comment]
It looks like we expose `(crdb_internal_vtable_pk, oid)` as a key, probably coming from a secondary index. That should be easy to fix.
