### ISSUE TITLE
ui: Cumulative statistics on noden overview page don't seem correct

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5398]
The Node's page lists each node in the cluster, giving an overview of their bytes, ranges, etc. In the first row in the table, it lists cumulative totals for each of these (see below). I'm not sure these totals make complete sense because of a cluster's replication factor. For instance, in a three-way replicated three-node system, each node will have a replica for all ranges, so adding them together to get the total range count doesn't make sense. For instance, below the cluster as a whole has only 15 ranges, not 45. The bytes total is a little less obvious because it could be argued that the cluster does store the combined amount. Still, I think it would make more sense to set this value to the total unique bytes in the cluster (in this case 293.9 MiB).

![screen shot 2016-03-19 at 1 04 20 am](https://cloud.githubusercontent.com/assets/5438456/13896763/e80145ec-ed6e-11e5-880f-ed52dca48358.png)

**Comment by mrtracy** [comment]
#4626 addressed this somewhat by changing "Ranges" to "Replicas".  

The problem here is that it is much easier to count the total number of objects (number of replicas, total bytes) than it is to count the number of _unique_ objects (number of ranges, unique bytes).  For total copies, each store can trivially report its own counts and they can be aggregated (and that's what you see in these graphs).  

For _unique_ objects, a de-duplication of distributed objects would be required.  It's unclear to me that such a query can be done correctly in an incremental, distributed fashion (which is how all statistics are currently computed).

The closest thing we have is the "ranges.leader" calculation, in which each store reports the number of replicas it contains which are currently range leaders.  I suppose we could extend that system to also count the _bytes_ of current leader ranges, in order to approximate the number of unique bytes.  However, this system has a flaw: each store still reports independently, and it is possible that multiple replicas of the same range will report as the "leader" on different stores during a single stat calculation period. Its also possible for _zero_ replicas will report as leader for a range. In either case, the range leader stat (and any hypothetical unique bytes statistic) would be subject to significant reporting anomalies.

It would be possible to get a reliable count of statistics with a distributed query across all nodes.

**Comment by bdarnell** [comment]
Instead of fully deduplicating, could we fake it by joining the replica count with the zone config, so that a replica in a 3-replica zone counts as 1/3 of a range (and 1/3 of its bytes are counted towards total bytes, etc)? 

For beta, I'm fine with only showing the total post-replication stats.

**Comment by cuongdo** [comment]
<img width="851" alt="screenshot 2016-03-28 11 57 20" src="https://cloud.githubusercontent.com/assets/1564582/14082121/4cee00f2-f4dc-11e5-8b3b-41e129a90fe6.png">

After @mrtracy's change, this is what the node stats table looks like now. Note the "replicas" terminology rather than "ranges". Is this sufficient for beta, or do we still want to dedupe (or fake-dedupe)?

**Comment by maxlang** [comment]
@nvanbenschoten Do you still feel we should dedupe the bytes? I feel it's a bit confusing to only include unique bytes in the rollup and probably a bit complicated to pull off. I'd be down to create a "Leader Bytes" or similar measure that measured how many primary bytes were on a specific node. It feels like both numbers are useful - total bytes for checking how much overall space I need, and total unreplicated bytes for getting a sense of how much data I have.

**Comment by nvanbenschoten** [comment]
@maxlang Yeah I agree that both would be useful stats to have in the UI and understand that deduping the bytes would be pretty tricky to do correctly. It sounds like the "Leader Bytes" approach would be a good way to approach the problem, but I wonder if even doing something like what @bdarnell suggested would get the point across. Either way, I think it would be really valuable to logically separate the amount of information stored in a cluster from the cluster's replication factor.

**Comment by maxlang** [comment]
I don't feel dividing by replication factor would be a good idea, because you don't actually know to what degree everything is replicated. I think our replicated % is binary, so it doesn't count ranges that have fewer than the full number of replicas, so that wouldn't be useful either.

@nvanbenschoten are there any other values besides storage amount where you think this is an issue?

**Comment by mrtracy** [comment]
We have decided to begin keeping per-table statistics in Q3, which will record the unique (de-duplicated) size counts.  For store-level numbers, the replicated numbers should be adequate.

That work is now tracked in #7682
