### ISSUE TITLE
ui: Node overview page doesn't update leader range count for unreachable nodes

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5415]
When a node that is the leader of a set of ranges goes down, that leadership is transferred to another node. The ui will correctly show that the new leader has in increased number of leader ranges, but it wont show that the old range (which is now down) has a reduced number of leader ranges until that new node is brought back up.

**Comment by jseldess** [comment]
In a new "Fault Tolerance" docs demo, we use the admin ui to show how, when one node dies, replicas are eventually moved to another node. Since it's potentially confusing that the replica count for the dead node doesn't go down, we're pointing users to this issue to follow the fix. 

Docs PR: https://github.com/cockroachdb/docs/pull/834
