### ISSUE TITLE
storage/pebble: panic pebble: flush-to key

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#54284]
**Describe the problem**

I was running a cluster trying to debug an issue in the allocator when I saw that a node had died with the following panic:
```
panic: pebble: flush-to key (/Table/61/1/992/"\u007f\x05\x9bJs\xc1H\x00\x80\x00\x00\x00\x01\xc6D\x06"/0/1599852788.409022053,0) < flushed key (/Table/61/1/1821/"\xe9\"\x18\x11'(H\x00\x80\x00\x00\x00\x03A\xbf\xcd"/0,0)

goroutine 268922 [running]:
panic(0x492b400, 0xc0371efa80)
        /usr/local/go/src/runtime/panic.go:722 +0x2c2 fp=0xc002bc50d8 sp=0xc002bc5048 pc=0x7b15c2
github.com/cockroachdb/pebble/internal/rangedel.(*Fragmenter).FlushTo(0xc010f08570, 0xc047b94a80, 0x27, 0x30)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/rangedel/fragmenter.go:286 +0x828 fp=0xc002bc5220 sp=0xc002bc50d8 pc=0x16b4188
github.com/cockroachdb/pebble.(*compactionIter).Tombstones(0xc001c5c780, 0xc047b94a80, 0x27, 0x30, 0x0, 0xc047b94a80, 0x0, 0x30)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction_iter.go:603 +0xff fp=0xc002bc5270 sp=0xc002bc5220 pc=0x16fb7af
github.com/cockroachdb/pebble.(*DB).runCompaction.func4(0xc05cbee3f0, 0x27, 0x30, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1898 +0x11c fp=0xc002bc5480 sp=0xc002bc5270 pc=0x173e8cc
github.com/cockroachdb/pebble.(*DB).runCompaction(0xc0008d6a80, 0x19a2, 0xc010f08480, 0x60c5200, 0x94b38e0, 0xc03c2aca00, 0xc016200c80, 0x6, 0x8, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2233 +0x15ee fp=0xc002bc5bc8 sp=0xc002bc5480 pc=0x16f6dae
github.com/cockroachdb/pebble.(*DB).compact1(0xc0008d6a80, 0xc010f08480, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1669 +0x167 fp=0xc002bc5e50 sp=0xc002bc5bc8 pc=0x16f5007
github.com/cockroachdb/pebble.(*DB).compact.func1(0x6164bc0, 0xc0119cc990)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1630 +0xbe fp=0xc002bc5ee0 sp=0xc002bc5e50 pc=0x173db4e
runtime/pprof.Do(0x6164bc0, 0xc0119cc990, 0xc000384ce0, 0x1, 0x1, 0xc001f24798)
        /usr/local/go/src/runtime/pprof/runtime.go:37 +0xf8 fp=0xc002bc5f68 sp=0xc002bc5ee0 pc=0x1019738
github.com/cockroachdb/pebble.(*DB).compact(0xc0008d6a80, 0xc010f08480, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1627 +0xa2 fp=0xc002bc5fc8 sp=0xc002bc5f68 pc=0x16f4e82
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc002bc5fd0 sp=0xc002bc5fc8 pc=0x7e1d91
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1424 +0x3f4

```

**Environment:**
 - v20.2.0-alpha.1-3327-g8412b1efe5 (x86_64-unknown-linux-gnu, built 2020/09/11 19:12:57, go1.13.14)
 - 9 node, gce cluster with n1-standard-4 nodes

**Comment by petermattis** [comment]
@itsbilal Please take a look. The SHA includes your `compactionOutputSplitter` refactor.

**Comment by itsbilal** [comment]
Yep, already investigated. Details are on slack, but the core issue is a bad interaction between `nonZeroSeqNumSplitter` withholding a compaction split suggestion, and the end of the compaction. I'll fix this on Monday.

**Comment by petermattis** [comment]
> Details are on slack

For posterity, it is useful to copy those details to this issue.

**Comment by itsbilal** [comment]
Sure. Here's the relevant compaction input:

L4 input:
```
/Table/58/1/1999/...#0,SET
/Table/61/1/1180/.../0,0-/Table/61/1/1202/"...#13211169,RANGEDEL
/Table/61/1/1999/...#91952,SET
```

L3 input:
```
/Table/58/1/1333/...-/Table/58/1/1407/...#13759205,RANGEDEL
/Table/61/1/1821/...-/Table/61/1/1895/...#13504457,RANGEDEL
```

Compaction output into L4:
```
/Table/58/1/1999/...#0,SET 
/Table/61/1/1999/...#91952,SET
```

And then the compaction should finish, as the range del fragmenter is empty and no more keys remain.
The issue is that `limit = /Table/61/1/992/`, a grandparent limit that’s right before the last key in the compaction input, but we can’t truncate the compaction right before it (`/Table/61/1/1999/...#91952,SET`) because, from the splitter’s view, the fragmenter isn’t empty (`/Table/61/1/1821/...-/Table/61/1/1895/...#13504457,RANGEDEL` is sitting around in it), the last point seqnum was 0 (`/Table/58/1/1999/...#0,SET`).

So we “hold off” the split suggestion, but turns out that was the last key in the compaction, so we never get around to calling `shouldSplitBefore` again and resetting limit. We end up calling `finishOutput(limit)`, with the now-out-of-date limit that’s earlier than both the latest range tombstone and the panic is triggered.

Possible solutions:
1) Detect all end-of-compaction cases and set `limit = nil`
2) Instead of just checking for `c.rangeDelFrag.Empty()`, have a `c.rangeDelFrag.End()` method and if that ends before the current key, treat the rangeDelFrag as empty as far as the nonzero sequence number checking is concerned.
