### ISSUE TITLE
ui: node marked "red" even though it's healthy

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5434]
build sha: 6388648af9741b287bf39a2caca5e2d3001ffc44

On a newly-started cluster (even after a few minute), the 4th node (special only because it does not yet hold any ranges) is still marked red:
![red-node](https://cloud.githubusercontent.com/assets/5901480/13920205/3994b90e-ef48-11e5-997e-8cbb720cc12d.png)

Two things here:
* it probably shouldn't be red. the node is reachable both through the UI port and the cockroach port
* there's no legend or floating help for the color coded

**Comment by mberhault** [comment]
now it's green. perhaps because it finally got some ranges rebalanced to it?

**Comment by mrtracy** [comment]
You are correct. The current code is computing that color from the "recentness" of the node's "lastUpdatedTimestamp". With no ranges, this timestamp is zero.

This is almost certainly the wrong criteria to use when determining the "alert" color; it works under the assumption that ever node is going to see at least one update every ten seconds. This works on small clusters where every node is probably receiving time series data, but otherwise it would be possible for perfectly active nodes to go yellow or red simply because they have no traffic.

**Comment by mrtracy** [comment]
Note that I have partially addressed this in #5412: the health color is now based on the "updated_at" time for the status itself (rather than the lastUpdatedTime value taken from store stats). This means that a node will only be colored as unhealthy if it has not self-reported its own status within a certain period of time.

This may be enough by itself to address this issue.

**Comment by maxlang** [comment]
Can I assign this to you @mrtracy ?

**Comment by mrtracy** [comment]
I think it's already fixed by #5412; i'm going to go ahead and close it.
