### ISSUE TITLE
ui: increase freshness of table size in ranges metric

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5435]
Quoting @bdarnell, from a code review discussion from #5361:

> kv/dist_sender.go, line 356 [r1](raw file):
> Note that this uses prefetching in the event of a cache miss, so even in the worst case it won't go one at a time (it currently fetches 8 at a time).
> 
> This will tend to under-count the number of ranges for tables that are currently growing: the cache is not updated after a split until we try to send an rpc to the range and get an error. We have to decide whether we want a fast answer that may be stale by an unknown amount of time, or one that is slower (at compared to a cache hit) but gives a more accurate answer. I suspect that the unbounded staleness of the cache will severely reduce the usefulness of this data (a growing table is exactly when this value is interesting), so it's probably better to opt for accuracy (if you're OK with the stale data anyway, then this LGTM)
> 
> The best way to get an accurate count is probably to add support for an EndKey to RangeLookup and then issue a consistent RangeLookup RPC with a high MaxRanges value (you could also use a Scan of the appropriate Meta2 range). Ideally this would be plumbed through the DistSender so that it can populate the cache (since you're doing the work anyway), but that's not necessary for now.

**Comment by mrtracy** [comment]
Since this bug was logged, we have divided the Admin API table-specific stats into two methods: the original `TableDetails` and a newer `TableStats.  TableDetails is meant to return metadata about the table - schema information, zone configuration, etc.  TableStats is meant to return statistics about the table, such as its current size; the division was created because the information in TableStats is more expensive to compute.

Right now, both of these methods return a `range_count1 field; however, they are computed differently.  The estimated range count on `TableDetails` is computed using the cache-friendly, but possibly stale method which is the crux of this issue.  The range count provided by `TableStats` is taken from a direct count of Meta2 keys, which is correct and does not suffer from this issue (although it is not plumbed through DistSender, so the cache population is gone.)

The remaining issue here is - should both of these methods return a `range_count` field? Right now, the UI is always calling both of these methods on each table, so it's fairly useless to return `range_count` from `TableDetails`.  However, this may not be the case in the future, and it may prove useful to get the fast estimate provided by TableDetails.

Thus, this is likely an issue of documentation and confusion, rather than actual functionality.  I will create a pull request to add a "TODO" to the protobuffer service definition which outlines this confusion, and close this issue. We can come back to it if we later decide to refactor our Admin API for common consumption by third parties.
