### ISSUE TITLE
ui: the available space on a node is not necessarily the sum of its stores

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#5454]
<img width="1357" alt="screen shot 2016-03-21 at 4 08 24 pm" src="https://cloud.githubusercontent.com/assets/3691886/13937025/45b1eb30-ef7f-11e5-8c12-38be0fc7b9f4.png">

Both stores are on the same disk, so the available and total space on disk should be equal to that of each store.

**Comment by mrtracy** [comment]
This is a tough one, and it is not a UI issue; it's a configuration issue.  Not only can this happen on the same node, it could even happen across nodes: it's possible to start two cockroach nodes on the same machine which use the same disk for their store.

That said, it's also possible to start two stores on the same disk, _providing each with a size limit_. In that case, the available capacity is still a proper sum.

In terms of the anomalous situation, I simply do not know a good way to determine when this is happening.  The situation is:
1. Two stores are using the same physical disk; they may not even be on the same node.
2. The stores are not using reserved space limits.

Would it be better to simply disallow that situation?  To warn users not to run in that configuration? Or can we somehow detect it and account for it on the UI (which seems to be the most difficult option by far).

**Comment by maxlang** [comment]
Yeah, detecting it seems challenging. I'd probably leave it as is but just add a warning tooltip and a callout in the docs where it explains stores. Eventually, though, we should try to handle this in a more sophisticated manner.

**Comment by maxlang** [comment]
cc @jseldess

**Comment by bdarnell** [comment]
Unless the user explicitly specifies a space limit, our available capacity will always be based on the unverifiable assumption that the entire disk is available to us (and won't be used by other processes on the machine, whether other cockroach stores or something completely different). I'm not sure if there's anything more clever we'll ever be able to do here, besides deemphasizing "available capacity" in the UI or just documenting this limitation.

**Comment by cuongdo** [comment]
I think we should document the limitation but keep available capacity in
the UI. It's my suspicion that most users will have a store per physical
disk, especially since that's slightly less work to configure (and the
default config has a single store). We can make the single store per disk
scenario more likely by documenting that we recommend one store per disk.

**Comment by JackKrupansky** [comment]
To me, it feels like Beta would be fine with a documented limitation/recommendation/best practice of one CockroachDB store per device and one CockroachDB node per hardware node.

Personally, that feels like a reasonable permanent restriction, or at least reasonable for even 1.0.

If there is an explicit check/error fine, but even the absence of such a check and the display anomaly described above would be a trivial limitation for Beta, in my not-so-relevant opinion. I mean, if a real user does complain about this specific scenario, I think the proper response would be to inquire why they are doing this in in the first place [just testing multi-store on my single-style laptop?!] and strongly advice against going into production with such a configuration.

There is the case of fully virtualized servers, where CockroachDB would only "see" the fraction of the resources that have been externally allocated to it. There the only issue is whether it is advisable or beneficial to have multiple CockroachDB nodes on a given fat node or whether CockroachDB itself would better manages the full hardware resources of the machine - most software does a poor job of exploiting the parallelism of a high-cpu machine. Maybe somebody mightbe running into the described anomaly because they are trying to do a poor-man's virtualization by hand rather than a truly virtualization hardware node.

**Comment by jseldess** [comment]
As discussed in the front-end meeting, we'll keep this out of the tooltip, since it's not a likely setup for a production cluster. But once we have docs for our Admin UI, I'll be sure to call it out.

**Comment by spencerkimball** [comment]
I'm going to set this to `known-limitation`. We should document this, but when that's done, let's close this. I don't believe there is any engineering work that's worthwhile to do here. @jseldess, because there aren't docs for the frontends, I'm removing the 1.0 milestone. Please move it back to 1.0 if you're planning to get this documented by 1.0 release.

**Comment by jseldess** [comment]
@spencerkimball, I think it's important to get admin ui docs in for 1.0, but I'll wait until we do q2 okrs before claiming it'll happen for sure.

**Comment by dianasaur323** [comment]
@jseldess @Amruta-Ranade could we add this into the admin UI documentation and close out when done?

**Comment by dianasaur323** [comment]
thanks @Amruta-Ranade

**Comment by Amruta-Ranade** [comment]
Closed via #1849
