### ISSUE TITLE
sql: Allow non-admin users to change their own password

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#54660]
Users currently require roles CREATELOGIN or CREATEROLE to be able to change their password, however, such privileges permits any user to change any users's password. 

We need a feature that allows to change the user's own password only. For security purpose, we should request the current users's password before allowing to proceed. 
It would be nice to be able to turn this feature off by a cluster settings or by creating a new "CHANGE-YOUR-OWN-PASSWORD" role.

In Postgresql, users can change their own password (but the feature cannot be removed) - see [the postgres docs](https://www.postgresql.org/docs/13/sql-alterrole.html) as well as: https://dba.stackexchange.com/questions/176205/is-there-any-way-to-prevent-a-postgresql-user-to-change-his-her-own-password

Assigning to @knz and @aaron-crl for triage.

Please also add the ability to toggle this feature on/off. For example in the scenario of kerberos auth, the admin would like 1 setting to stop users updating their crdb password. 

gz#6235

gz#5920

Epic CRDB-11567

Jira issue: CRDB-3730

**Comment by aaron-crl** [comment]
@thtruo for Product intake.

**Comment by fabiog1901** [comment]
To add some extra context/justification, below are the general security rules enterprises must follow:

1. DBAs should **not** have users access/security admin privileges.
2. Security admins should not have DBA admin abilities, **only** users access/security privileges.
3. Neither DBAs nor Security admins should know the users passwords.

It is therefore required for users to be able to (re)set their own password without having DBAs/Security Admins resetting it on their behalf, as that would break rule #3.

**Comment by BramGruneir** [comment]
Here is the customer request: https://cockroachdb.zendesk.com/agent/tickets/6235 for context.

**Comment by lancel66** [comment]
Large customer has indicated this will become a blocker in the near future due to security requirements in their organization. Here are the associated support ticket and JIRA issue links:

https://cockroachdb.zendesk.com/agent/tickets/5920
https://cockroachlabs.atlassian.net/browse/CRDB-1734

**Comment by thtruo** [comment]
cc @mwang1026 for awareness on behalf of Piyush

**Comment by knz** [comment]
The best practice to satisfy the security requirements is to use an external authentication database where the IT policies can be enforced. Why are they not doing this?

**Comment by GlennFawcett-doordash** [comment]
Most performance-oriented applications are not okay with tightly coupling database logins with a 3rd party authentication service.

**Comment by glennfawcett** [comment]
Most performance-oriented applications are not okay with tightly coupling database logins with a 3rd party authentication service.

**Comment by knz** [comment]
Performance-oriented applications do not open and close SQL sessions on the performance hot path. Regardless of the auth mechanism, setting up a SQL session can take anywhere from 200ms to 1.5s and so clients use connection pools etc to mitigate that delay. Within that context, it makes sense to have authentication validated by an authentication broker service separate from the database.

Again, I'd like to hear more about the use case. It seems to me that if an entity is restricted by regulation or compliance requirements to be careful about password policies, that entity would not be at liberty to entrust their credentials to the database that also stores the application data (due to the risk of spillage from one security domain to another).
