### ISSUE TITLE
cli: negative execution timing on PREPARE

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#54888]
I got negative execution timing when `PREPARE`ing a statement:
```
# Server version: CockroachDB CCL v20.2.0-alpha.1-3658-gdb9c393482 (x86_64-apple-darwin19.6.0, built , go1.13.15) (same version as client)
# Cluster ID: a3b07996-a996-431e-aab0-eed58e2612f5
#
# Enter \? for a brief introduction.
#
demo@127.0.0.1:53922/defaultdb> create table t (a int, updated_at timestamptz);
CREATE TABLE

Time: 4ms total (execution 4ms / network 1ms)

demo@127.0.0.1:53922/defaultdb> prepare stmt (timestamptz) as insert into t values (1, $1);
PREPARE

Time: 3ms total (execution -85636855ms / network 85636858ms)
```
I don't think that's intentional.

**Comment by knz** [comment]
@arulajmani is that a dup of your other issue

**Comment by arulajmani** [comment]
Yeah, I think this is quite similar to #54750, but not the same. I finally tracked that one down, and the reason we see negative values is because currently we don't record the correct service latency for anything except for normal statements. Service latency is defined as: https://github.com/cockroachdb/cockroach/blob/77dd8405eed5b7effbf6898ffbb0651f498237dd/pkg/sql/executor_statement_metrics.go#L69
The culprit here is `plannerEndExecStmt`, which isn't set for anything other than statements dispatched to the execution engine. This means that observer statements, prepared statements etc. will have a negative service latency, which leads to these whacky numbers. The other issue was caused because of the `SHOW SYNTAX` observer statement. 

As a remedy, I propose introducing a new `sessionQueryServiced` addition to the current phase times we gather. This should be set independent of whether we used the execution engine or not, by all queries going through the conn_executor. Then, we can use this for service latency calculations and this will solve both the issues.

**Comment by knz** [comment]
Is your proposed solution analogous to introducing a new phase?

(If so that would incur some code churn since we have a few places that make assumptions about how the phases sum up to service lat. Instead I would suggest to reset the phase timings all to current time at the beginning of all executions, so that the latency of unused phases drop to zero)

**Comment by knz** [comment]
On second thought, why don't you show us what you were thinking about in a diff? Maybe it's just good already
