### ISSUE TITLE
Evaluate and possibly implement options via self-referential functions

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#550]
via @petermattis:
http://commandcenter.blogspot.de/2014/01/self-referential-functions-and-design.html

`client.Context` could be a good candidate to test this with immediate value to end-users.

**Comment by bdarnell** [comment]
The self-referential aspect of this is to support temporary mutations to global state, which doesn't really make sense here (we don't want to support changes to the client.Context after the client is created). We might be able to simplify the interface a bit by using builder-style methods instead of requiring callers to construct struct literals, but I think it probably makes the most sense to leave this a dumb struct instead of adopting fancier configuration patterns.

**Comment by tschottdorf** [comment]
Ok, agreed.
