### ISSUE TITLE
server: status redirects hit rpc port instead of http port

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5530]
For example:
requesting `https://beta.cockroachdb.com:8080/_status/metrics/2`
if the node we're hitting is not node 2, it will attempt to fetch the corresponding url on node 2, but it uses the node address from gossip.
This results in a request to: `https://ip-172-31-58-173:26257/_status/metrics/2`
Which is the wrong port. Instead, the redirect should use `:8080`

**Comment by tamird** [comment]
Shit. Using :8080 is also not resilient because that node may be running
its admin UI on a different port.

Shit.

**Comment by mberhault** [comment]
yup.
If the plan is still to collapse ports together again, then I think it's ok to say "some admin UI functionality may break if nodes use different admin ports"

**Comment by tamird** [comment]
Yeah, that's the plan. Sadly we're waiting for performance improvements
from upstream to enable this.

**Comment by mrtracy** [comment]
So is this still a beta issue? The resolution to this is either gossiping the other port, or punting until its one port again.  If this needs work before the beta period, I am out of time.  Reassigning.

**Comment by BramGruneir** [comment]
We'll need to gossip the admin ports, I can take this on if it is still a beta issue.  
But I think we're fine leaving it as is.  We can just add a comment into the docs and cli flags help.

**Comment by mberhault** [comment]
We need to at least change the redirect to use the original node's admin port. Sure, things will be a bit broken when nodes use different admin ports, but other scenarios will work.

**Comment by d4l3k** [comment]
This is partially blocking #6657. 

For the short term, would it be reasonable for me to add the HTTP port to the node status key?

**Comment by bdarnell** [comment]
I've been thinking about addressing this in a slightly different way, by exposing all the status HTTP endpoints over RPC. This would mean that commands like `cockroach node ls` would no longer need to take a separate `--http-port` argument; they could use the same pgwire/rpc port as the other commands. This could be done in a generic way by defining a GRPC `HTTPRequest`, although we'd need to be careful that this doesn't result in privilege escalation (this needs to either be limited to status endpoints that don't require authentication or the node needs to preserve information about who made the request instead of upgrading it to the node's own permissions).

I'm not sure if this is worthwhile, though, since we intend to eventually move back to one port (there are some uses for an HTTP-over-RPC transport to allow everything to be routed the same way, but I doubt we'd want to build such a thing if we don't have the problem of two separate ports). So it's probably more expedient to just add the HTTP address to the node descriptor.

A third option would be to go in the other direction and define all the status endpoints as RPCs, and use grpc-gateway to expose them over HTTP. This the direction we're heading with new work (server/admin.proto), so maybe we should just port all the existing JSON status endpoints to this system.

**Comment by d4l3k** [comment]
I'm happy to work on either of the last two. I'm already halfway done with the second.

**Comment by petermattis** [comment]
Adding gRPC methods for all of the status endpoints and then exposing them via grpc-gateway sounds like the way to go to me.

**Comment by tamird** [comment]
Possibly related https://github.com/cockroachdb/cockroach/issues/5163

**Comment by d4l3k** [comment]
Okay, I'll port status over.

**Comment by d4l3k** [comment]
I've gotten about half of the status endpoints switched to GRPC.

The remaining ones can't be directly converted since they don't use protocol buffers or are unstructured like `/_status/stacks/:node_id`.

I'm not sure if I should serialize them to bytes and wrap them in a simple protocol buffer message or just leave them as only HTTP endpoints.

**Comment by tamird** [comment]
Is there any reason they can't be converted to protocol buffers?

**Comment by d4l3k** [comment]
Not really, except it might break compatibility with other things using
those endpoints. Though we could just make the HTTP endpoints not just
display the raw protocol buffers and go though some conversion step.

**Comment by tamird** [comment]
Give it a try - I'm pretty sure these endpoints are not covered by any
compatibility guarantees.

**Comment by petermattis** [comment]
Are they used from the ui? Or perhaps manually from a browser?

**Comment by tamird** [comment]
Some are used from the UI.

**Comment by d4l3k** [comment]
From the ui and manually I think. I'm also not sure how to convert text
goroutine stack traces into a meaningful protobufs.

**Comment by bdarnell** [comment]
For the stacks I think it's fine to leave them as HTTP-only. In addition to the UI, some of them are used from the CLI (e.g. `cockroach node ls`). As long as we update the CLI and UI to match, I think it's fine to make backwards-incompatible changes here.
