### ISSUE TITLE
opt: generate inverted index scans for JSON fetch value and containment operators

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#55318]
CRDB previously generated inverted index scans for queries with filters like `j->'a' @> '{"b": "c"}'`. In order to generate these scans, it relied on normalization rules that converted the filters into JSON containment expressions, with the `@>` operator.

These normalization rules had to be removed in #55316 because they were found to produce inequivalent expressions. While #55316 re-added some support for index acceleration of filters with the `->` operator, it did not cover this particular type of filter.

**Comment by rytaft** [comment]
cc @ianjevans I added the "docs-known-limitation" tag to document that we cannot generate inverted index scans for queries with filters that have JSON fetch value and containment operators (e.g., `j->'a' @> '{"b": "c"}'`) on 20.2 or 21.1. This was possible in 20.1 and before, but it caused other issues (see above for details). The full issue will be fixed on 21.2, but we do not plan to backport the fix to 20.2 or 21.1, since it is too risky. On 20.2 and 21.1, various other workarounds are available. For example, the filter `j @> '{"a": {"b": "c"}}'` produces the same results as `j->'a' @> '{"b": "c"}'`, and it can be index-accelerated.

**Comment by mgartner** [comment]
This has been fixed on master by #63048. See @rytaft's comment above for details. Closing.
