### ISSUE TITLE
sql: v20.2 - information_schema.tables index on table_name only includes tables in the current search_path

### ISSUE THREAD

**Issue by alex-berger** [cockroachdb/cockroach#55437]
**Describe the problem**

This bug affects CockroachDB version v20.2.0-beta.*.

When querying `information_schema.tables` for a specific table which resides in a custom schema (not in `public`) the 
string equality operator (`=`) does not work as expected on the `table_name` column. As a workaround one can use the
`like` operator with a wildcard (`%...%`) pattern which seems to work as expected.

**To Reproduce**

Spin up a CockroachDB cluster e.g. using `docker run --rm -it -p 26257:26257 cockroachdb/cockroach:latest-v20.2 start-single-node --insecure` and apply the following SQL statements.

```SQL
create schema nx;

create table nx.yy(a int);

select * from information_schema.tables where table_schema = 'nx' and table_name = 'yy'; 
--> unexpected empty result !!!

select * from information_schema.tables where table_name = 'yy'; 
--> unexpected empty result !!!

select * from information_schema.tables where table_schema = 'nx' and table_name like '%yy%' and length(table_name) = length('yy'); 
--> expected result with one row
```

**Environment:**
 - CockroachDB version `v20.2.0-beta.*`

**Comment by rafiss** [comment]
Thanks for finding and reporting the bug! I tracked down some further details: The `information_schema.tables` table has an index on `column_name`. It's a virtual index which is [materialized on the fly](https://github.com/cockroachdb/cockroach/blob/03e8d3262a9a50d8ee12f822e4fbfb64bdf79cbf/pkg/sql/information_schema.go#L1505). The issue is that the code that it uses to [look up a table by name](https://github.com/cockroachdb/cockroach/blob/03e8d3262a9a50d8ee12f822e4fbfb64bdf79cbf/pkg/sql/catalog/resolver/resolver.go#L153) only includes tables in the current database and search_path.

I think we'd want to keep the lookup limited to the current database, but it should include tables from all schemas in the current database.

**Comment by alex-berger** [comment]
I don't know whether this is related, but tables in custom schemas do also not appear in `crdb_internal.tables`.

**Comment by rafiss** [comment]
@alex-berger you're right -- we fixed and backported that one separately: https://github.com/cockroachdb/cockroach/issues/54976
