### ISSUE TITLE
server: DecommissionRequest proto field was reassigned past ID

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#55435]
In v20.1, the Decommission field in DecommissionRequest had ID 2

In v20.2 the field was removed and a new field was added also with ID 2

This causes a misbehavior in mixed 20.1-20.2 clusters

**Comment by knz** [comment]
@tbg @bdarnell does this sound like a release blocker?

**Comment by irfansharif** [comment]
That was intentional. Despite the type change, the boolean values from earlier get auto-encoded/type cast to the appropriate enum type in the 20.2 type. Looking at the spec developers.google.com/protocol-buffers/docs/proto#updating:

> enum is compatible with int32, uint32, int64, and uint64 in terms of wire format […] int32, uint32, int64, uint64, and bool are all compatible

We're actually relying on this wire format compatibility to have decomm/recomm work properly in mixed version clusters. There's a (thorough) test for mixed version settings here cause of the same concern: https://github.com/cockroachdb/cockroach/blob/fbaaaa6c177451d7a853d0a1fcae2ba5caefff06/pkg/cmd/roachtest/mixed_version_decommission.go#L25 

We also tried explaining some of it in the commit message introducing this diff, check out [`57033b4` (#50329)](https://github.com/cockroachdb/cockroach/pull/50329/commits/57033b4bccd693e7b30a3359b256e0aa6375a14b).
