### ISSUE TITLE
Excessive CPU utilization during restore

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#55652]
#47290 introduced rate limiter during the computation of sha512 checksums.

I believe this rate limiter, due to fairly inefficient underlying limiter implementation, results in excessive CPU usage during
cluster RESTORE.

CPU Utilization during restore on an empty cluster (restore is the only process running):
<img width="697" alt="Screen Shot 2020-10-16 at 7 59 21 PM" src="https://user-images.githubusercontent.com/54641364/96323315-9d415300-0fea-11eb-94d6-fd304bcaa1b0.png">

5 second profile: checksum computation around 40%.
<img width="814" alt="Screen Shot 2020-10-16 at 7 56 39 PM" src="https://user-images.githubusercontent.com/54641364/96323355-c6fa7a00-0fea-11eb-8af9-4e742cba114f.png">

Zooming in, majority of time spent because of new timer creation.
<img width="1210" alt="Screen Shot 2020-10-16 at 7 58 54 PM" src="https://user-images.githubusercontent.com/54641364/96323373-dda0d100-0fea-11eb-835d-f482c0b7af82.png">

During restore we expect many new ranges to be created rapidly.  Setting 
```
 set cluster setting server.consistency_check.max_rate='1TB';
```
Results in the following CPU utilization picture on the cluster (setting changed at 00)
<img width="696" alt="Screen Shot 2020-10-16 at 8 06 26 PM" src="https://user-images.githubusercontent.com/54641364/96323438-1e98e580-0feb-11eb-97b3-d3075bdbb438.png">

CPU utilization drops; though we still need to burn cycles computing checksum, at least, we're not spending this time
in the limiter code:
<img width="1273" alt="Screen Shot 2020-10-16 at 8 07 54 PM" src="https://user-images.githubusercontent.com/54641364/96323518-6b7cbc00-0feb-11eb-9bf6-ce60b1e699cb.png">

**Comment by lunevalex** [comment]
@miretskiy it's an interesting issue, if restore is consistently hitting the newTimer codepath that means that the checksum computations are being throttled by the limiter. Looking at the rate.Limiter code it looks like the go authors chose to use a Timer instead of Sleep to allow for the wait to terminate early if the context is cancelled or expired. 

It seems that an interesting avenue to explore would be to see if we can disable or otherwise reduce the consistency_queue checker, since all of those sha512 calculations are also creating a lot of pressure on the CPU. Looking at the code the checker is going to run as soon as it can for a range and then every 24 hours. A potential change would be to introduce an offset to the scheduler, so rather than scheduling a consistency check immediately for a range it can do so at a random offset between 0 and the checker interval (i.e. 24 hours by default). 

cc: @tbg wdyt?

**Comment by ajwerner** [comment]
Consider adopting https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/quotapool#RateLimiter for the rate limiter. It should be much more efficient.

**Comment by tbg** [comment]
Re: better scheduling of these checks, the consistency queue "generally" spaces them out over the interval.

Here's the code that "sleeps" between consistency checks:

https://github.com/cockroachdb/cockroach/blob/59306ed424ed537fdf9502b1461f8980a6369ce7/pkg/kv/kvserver/consistency_queue.go#L187-L199

used from here:

https://github.com/cockroachdb/cockroach/blob/1ba2821900b7cb0b24f333b471b8858730b28a5d/pkg/kv/kvserver/queue.go#L861-L871

However, the profile probably shows the CPU utilization of a single consistency check running. These checks have to run *sometime*, so this seems mostly "fine" and the task at hand is making the check cheaper.

We should follow Andrew's suggestion. Additionally, it may be worth looking into a much weaker checksum - sha512 seems like overkill. I'd bet that (the sane comparable alternative to) CRC32 would do just fine here, assuming it shaves significant chunks of CPU off.

**Comment by petermattis** [comment]
> Zooming in, majority of time spent because of new timer creation.

I encountered the excessive timer creation problem in Pebble. It was fixed by forking the `rate` package and extending the API to support a `DelayN` operation which allowed the caller to implement the waiting as it sees fit (in pebble this is a `time.Sleep`). See https://github.com/cockroachdb/pebble/commit/62af71ee9887ae8a46822deccdb929d5b3dfc35d.

**Comment by ajwerner** [comment]
One thing that might be simpler than any of this is just to reserve bigger chunks of bytes. We know that the stats computation is single threaded. Just reserve a minimum of 32k at a time or something and I suspect this problem will disappear.

**Comment by ajwerner** [comment]
something like:

```go
 
+       const rateLimitMinAcquisition = 32 << 10 // 32 KiB
+       var rateLimitBudget int                  // already acquired bytes
        visitor := func(unsafeKey storage.MVCCKey, unsafeValue []byte) error {
                // Rate Limit the scan through the range
-               if err := limiter.WaitN(ctx, len(unsafeKey.Key)+len(unsafeValue)); err != nil {
-                       return err
+               byteLen := len(unsafeKey.Key) + len(unsafeValue)
+               if delta := rateLimitBudget - byteLen; delta < 0 {
+                       toAcquire := -delta
+                       if toAcquire < rateLimitMinAcquisition {
+                               toAcquire = rateLimitMinAcquisition
+                       }
+                       if err := limiter.WaitN(ctx, toAcquire); err != nil {
+                               return err
+                       }
+                       rateLimitBudget += toAcquire
                }
+               rateLimitBudget -= byteLen
 
                if snapshot != nil {
```

**Comment by lunevalex** [comment]
@tbg you are correct there is some spacing code, but the the spacing function is based off the time it took to process a consistency check, rather than the consistency check interval. Under a heavy load of range creation and with relatively fast checksum computations, this code would not prevent a steady stream of checks. My suggestion was to delay the first check for range and space it out over the first 24 hours, since checking it right after creation does not sounds particularly useful. 

It seems switching the rate limiters is a good simple fix, it will also allow us to get rid of the custom monstrosity that we built to deal with the bursts in the first place. I will try out the https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/quotapool#RateLimiter and see how it goes. Separate question should we pull this rate limiter into a separate repo so it could be used in Pebble and Cockroach? It would seem like standardizing here would make sense.

**Comment by lunevalex** [comment]
@miretskiy if all goes well I should be able to give this a shot on my flex friday, since thats the only time I would have to write some code.

**Comment by ajwerner** [comment]
> Separate question should we pull this rate limiter into a separate repo so it could be used in Pebble and Cockroach? It would seem like standardizing here would make sense.

I'm strongly in favor of that. It's got some dependencies on `util/timeutil` and `util/syncutil` and one tiny one on `util/log` which should be easy to shrug off. I'm happy to do the extraction. I'll make a repo on `cockroach/quotapool` with an Apache license on Friday if there's no objections.

**Comment by miretskiy** [comment]
@lunevalex Thanks for taking a look at this.  Spacing out sha computation seems like a reasonable idea.  Using a better timer implementation should also help.
