### ISSUE TITLE
No credentials provider in chain

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#55665]
Error observed while uploading range to s3.
https://github.com/cockroachlabs/support/issues/628

**Comment by dt** [comment]
no immediate plans to try to work on this

**Comment by dt** [comment]
We've since learned more about this error. 

We typically see this error when using ?AUTH=implicit where the SDK decides what keys to use e.g. when it is reading credentials from the default profile like ~/.aws/credentials, and it indicates the credentials are not valid.

Now, if someone just had invalid credentials and got an error, that is more or less working as intended, but what we've seen often where it can be unexpected is in deployments that have more frequent key rotations and expiration policies in place, specifically if a an operation like BACKUP is running when the keys expire.  Errors due to expired keys seem to make it through the SDK's internal retries because the SDK's on-disk credential provider does not expose expiration information, so the SDK doesn't refresh and try again according to analysis by @miretskiy.

For now, to minimize the time that we're using keys after reading them, we open a new instance of the SDK's client -- which re-reads the file -- for each file we write/read to/from S3 during a backup/restore. However within any individual operation -- writing a file, listing backups, etc -- if the keys expire out from under us, this error seems likely to be returned.

For now, the best mitigation is probably to avoid key expirations during bulk operations if possible and/or make sure key rotation pushes new keys well in advance of expiration to give any operations that started with old keys ample time to complete.

In the future, it is possible implementing our own credential provider that did smarter refreshes could make the SDK's build-in retries hide this for us.
