### ISSUE TITLE
A few questions: Strange SQL syntax, and inserting without giving primary keys

### ISSUE THREAD

**Issue by tchoulihan** [cockroachdb/cockroach#5575]
I tried inserting a row (from the example) without giving the primary key(as is typical in SQL), as follows:

```
root@:26257> CREATE TABLE accounts (id INT PRIMARY KEY, balance DECIMAL);
CREATE TABLE

root@26257> INSERT INTO accounts (balance) VALUES (DECIMAL '10000.50');
....fails
```

Also, what's with the strange syntax for table creation and datatype inserts? If cockroach uses postgressql for a translation layer, then why isn't the syntax the same as postgres? Will my postgres sql connector even work, considering the syntax looks different?

**Comment by tamird** [comment]
In "typical SQL", you're probably using auto incrementing primary keys, which is not supported in CockroachDB (though we have some alternatives such as `unique_rowid()`). Either way, you need to give your primary key an explicit default e.g. `CREATE TABLE foo (id INT PRIMARY KEY DEFAULT unique_rowid())`.

The SQL syntax supported by cockroach is not exactly the same as postgres, but the wire protocol is the same - this means that your PG connector will work, but you may need to rewrite some of your SQL.

**Comment by tchoulihan** [comment]
How do people currently handle the issue of inserting data with non-conflicting keys? Several clients may need to insert data, but would have no idea what primary key to provide in order to be non-conflicting. Their data might be rejected simply because they didn't know that the primary key was taken.

Does this mean that the PG connector has to use custom SQL statements? I was planning on using activeJDBC as an ORM, (it works with PG), but I take it that this wouldn't work, since only the communication protocol works, but actual SQL statements must be completely rewritten.

**Comment by tamird** [comment]
> How do people currently handle the issue of inserting data with non-conflicting keys? Several clients may need to insert data, but would have no idea what primary key to provide in order to be non-conflicting. Their data might be rejected simply because they didn't know that the primary key was taken.

As mentioned in my previous comment, this is mitigated by setting the primary key's default to `unique_rowid()` or `experimental_uuid_v4()`. Also, if you don't care about the primary key, you can create a table without one - this is supported in both postgres and cockroachdb.

> Does this mean that the PG connector has to use custom SQL statements? I was planning on using activeJDBC as an ORM, (it works with PG), but I take it that this wouldn't work, since only the communication protocol works, but actual SQL statements must be completely rewritten.

Yes, that's correct. It is likely that a custom cockroachDB ORM layer will be necessary.

**Comment by andreimatei** [comment]
@tchoulihan what issues are you running into with activeJDBC, other than autoincrement missing?

**Comment by tchoulihan** [comment]
Thanks @tamird . The `unique_row()` solution makes sense. 

That is what I kinda figured. I'm sure there are good reasons to not use standard SQL schema, but just note that a lot of ORM frameworks that simplify things aren't going to be usable, unless the SQL statements are pretty much compliant with an already existing framework like postgres or mysql  or sqlite. 

@andreimatei , I haven't actually tested it out, but its clear that pretty much every ORM framework would need to have a cockroach DB layer considering the SQL statements aren't standard.

**Comment by andreimatei** [comment]
@tchoulihan we do support the standard statements, although not completely (for some we actually support a super-set of Postgres syntax :) ). We haven't tested it with all the ORMs yet and it's indeed likely that some will not work completely / at all yet, but we're definitely interested in hearing specific syntax that each one needs to have supported. So please let us know if something specific doesn't work for you (other than the autoincrement columns).

In the first message you said "strange syntax for table creation", but I'm not sure what you meant.

**Comment by tchoulihan** [comment]
Usually the primary key is given after, both in mysql and postresql like this:
```sql
CREATE TABLE table_name(
   column1 datatype,
   column2 datatype,
   column3 datatype,
   .....
   columnN datatype,
   PRIMARY KEY( one or more columns )
);
```
Whereas in cockroachdb, it uses this: `id INT PRIMARY KEY`

Also, the `INSERT` statement looks like it requires a datatype, whereas this isn't necessary in either mysql or postresql.

**Comment by petermattis** [comment]
@tchoulihan You can specify the primary key in CockroachDB exactly as you've done in the `CREATE TABLE` statement there. The `id INT PRIMARY KEY` form is short hand when the primary key is only a single column. Note that both Postgres and MySQL support that syntax as well.

The need to specify the data type during insert (i.e. `DECIMAL '10000.50'`) is caused by the type inference (or lack thereof) in CockroachDB. We're working on fixing this.

**Comment by tchoulihan** [comment]
@petermattis Ah, thanks, had never seen it that way before. 

Is there an issue open for type inference, I couldn't find any and I'd like to keep an eye on it; I'm pretty sure my ORM doesn't support insert statements like this.

**Comment by nvanbenschoten** [comment]
@tchoulihan With regards to type inference, it should be noted that the need to specify the data type during insert is only present when our parser would incorrectly infer the provided value's type. This is currently only an issue for a few of our data types, which unfortunately includes DECIMAL. If you had been inserting into a FLOAT column, `INSERT INTO accounts (balance) VALUES (10000.50);` would have worked as expected. The issue exists because `10000.50` will be interpreted as a FLOAT, and at this point our typing system is not contextually aware of the type expected, so it will not implicitly change to interpreting the constant values as a DECIMAL. This will be fixed when our [SQL typing RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/typing.md) is implemented, which should be shortly after we reach our Beta milestone.
