### ISSUE TITLE
SERIAL4 is showing up as INT8 after creating table.

### ISSUE THREAD

**Issue by wontruefree** [cockroachdb/cockroach#55864]
**Describe the problem**

I am trying to create a 32bit integer serial and I am getting a 64 bit.

**To Reproduce**

1. Set up CockroachDB cluster
2. create table
```sql
root@:26257/yolo> CREATE TABLE  test ( id SERIAL4 PRIMARY KEY);
```
3. describe table
```sql
root@:26257/yolo> SHOW COLUMNS FROM test;
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  id          | INT8      |    false    | unique_rowid() |                       | {primary} |   false
(1 row)
```

**Expected behavior**
the column type should be an `INT4`

**Environment:**
Build Tag:    v20.1.8
Build Time:   2020/10/21 15:46:38
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  ffd029f51aa134f2bce4a39ef1f3ad095c3856ad
Build Type:   release

MacOS
Docker

**Additional context**
Trying to port an application from postgres to cockrochdb

**Comment by rafiss** [comment]
thanks for the issue @wontruefree.

I believe the issue here is that when the setting `serial_normalization` is set to `rowid` or `virtual_sequence` (`rowid` is the default), then any SERIAL column will be backed by `unique_rowid()`, which always returns INT8. The motivation here is that `unique_rowid()`  is far quicker than using a real sequence, though that behavior can be forced by setting `serial_normalization=sql_sequence`. 

I don't know if it's do-able for us to make different `unique_rowid()` functions for different SERIAL sizes -- I'm not sure if we could still guarantee uniqueness with the smaller number of bits. But if we can, then that would be a fix.

Otherwise, we may address this issue by returning a warning (or possibly an error) if a SERIAL4 or SERIAL2 column is created and `serial_normalization=sql_sequence` is not being used.

**Comment by wontruefree** [comment]
So no matter which serial you use (SERIAL4, SERIAL8) you will only get an INT8?  I am reading the [documentation](https://www.cockroachlabs.com/docs/stable/serial.html) and I dont see the difference in data_types.  
Let me know if you can do SERIAL4 with sql_sequence.  I would like to integrate with a project that is postgres only right now.

**Comment by rafiss** [comment]
@wontruefree Yes, if you use `SERIAL4` and have `serial_normalization=sql_sequence`, then the column type will be an `INT4`. Just be aware that `sql_sequence` has an additional performance cost: https://www.cockroachlabs.com/docs/stable/serial.html#generated-values-for-mode-sql_sequence

If possible, I would recommend that you try using `SERIAL8` with `serial_normalization=rowid`.
