### ISSUE TITLE
sql: separate metrics pages by APP and Database

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#55861]
Currently, you can separate the Transactions and Statements by App but not by database (#33316). 

Customers are also interested in being able to separate the metrics pages by App and by Database. This is an issue to track that request. 

gz#5514

Jira issue: CRDB-3622

**Comment by jordanlewis** [comment]
We don't have an easy path to making this happen today. We'd need to add "dynamic" time series metrics that are scoped by app. We would probably not want to make this automatically happen for all apps and databases, because time series data doesn't like to have "dynamic dimensions" the way this is.

We could conceivably have a cluster setting that includes the desired set of apps and databases to record timeseries for, but I'm concerned about performance implications here.

I would urge users to solve this problem themselves, by adding their own latency and throughput metrics per app in the application. This is standard practice for observability for microservice architectures, and I'm not sure what customers can't get using this standard practice.

Andy, could you please determine which metrics the customer needs bucketed by app and database, and why the standard practice I suggested is insufficient?

**Comment by maryliag** [comment]
No longer a priority
