### ISSUE TITLE
opt: normalize !st_disjoint -> st_intersects

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#55976]
This means we are able to utilise the index!
(unfortunately we cannot do st_disjoint -> !st_intersects yet)

**Comment by otan** [comment]
cc @rytaft does this sound like a `good first issue` / valid operation?

**Comment by rytaft** [comment]
Hey @otan  -- this does seem like a good first issue, but it's not going to be useful until we also support using an index with !st_intersects. We don't yet support using an index with !st_intersects because it requires scanning the set complement of the spans required for st_intersects. I'm not even sure if the set complement would be correct without modifications, because there might be some false negatives.  cc @sumeerbhola if you have thoughts about this.

If we do decide to add support for using an index with !st_intersects, then to add this normalization rule to convert st_disjoint -> !st_intersects, people can look at one of our existing normalization rules here: https://github.com/cockroachdb/cockroach/blob/753ab8b53c6832dfc457059fc1c3e8f5c8d66dd0/pkg/sql/opt/norm/rules/comp.opt#L241, with custom code here: https://github.com/cockroachdb/cockroach/blob/753ab8b53c6832dfc457059fc1c3e8f5c8d66dd0/pkg/sql/opt/norm/comp_funcs.go#L119.

**Comment by rytaft** [comment]
Although we could certainly use the index if the original predicate was !st_disjoint, in which the new predicate would be st_intersects. So this is probably still worthwhile.

**Comment by sumeerbhola** [comment]
> I'm not even sure if the set complement would be correct without modifications, because there might be some false negatives.

I agree this is a problem whenever the inverted index generates a false positive (which is always the case for geospatial). But even if that were not the case, doing the (primary key) set complement after the set expression evaluation is not something we can actually compute.

If one could compute the shape complement of one of the parameters to `st_disjoint`, then this could be made to work. It doesn't seem like a general solution though. If there are actual use cases involving large polygons that could benefit from this, it may be worth considering.
