### ISSUE TITLE
cdc: backfill consistently on schema change

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#56098]
Changefeed behavior during schema changes is surprising and non-ideal for many users. Namely: they receive both the original rows and the updated rows during certain schema change events. We have the option of not including the updated rows, but we should also have the option or expand the existing option to not emit the original rows as this behavior can be undesirable on large tables. Related to https://github.com/cockroachdb/cockroach/issues/35738 

gz#4938

Jira issue: CRDB-3579

Epic CRDB-19158

**Comment by BramGruneir** [comment]
@amruss Any update on the status of this issue?

**Comment by amruss** [comment]
@BramGruneir - there is #58518 that is being worked on but besides that no major updates here

**Comment by ajwerner** [comment]
We added an option for adding a `NULL` column in 20.2 I think. Modifying the default value of a column doesn't change any data so that shouldn't trigger a backfill. 

> Make the behavior consistent across all schema changes.

I'm not clear on what this means.

**Comment by ajwerner** [comment]
@amruss I'm not sure that this issue is concrete enough to be actionable. I also feel like the use of backfill here is confusing. I feel like upon reading this again there's some reference to "logical" backfill as though there was some other kind. I worry that this issue is using language to refer to the writes due to #35738 as something that are ever desirable. They aren't. That issue is tracked there.

**Comment by amruss** [comment]
@ajwerner acked - I updated it to be scoped to what we emit with the no backfill option

**Comment by amruss** [comment]
@vy-ton throwing this on your plate to close out when needed

**Comment by miretskiy** [comment]
@amruss is there anything we expect to happen on cdc side for this issue?
If not, let's close this?

**Comment by amruss** [comment]
Closing for the CDC Tream
