### ISSUE TITLE
Bug caused by delete operations within a transaction

### ISSUE THREAD

**Issue by Cynthia-Lee97** [cockroachdb/cockroach#56111]
**Describe the problem**
 I start two transactions.
One of the transaction SELECT operations can get the data, but the DELETE row returns DELETE 0

**To Reproduce**
What did you do? Describe in your own words.
1. Set up CockroachDB node
2.
![image](https://user-images.githubusercontent.com/56955504/97552298-0e333280-1a0f-11eb-84d8-8c72d853acec.png)
3.The reading and writing data of T2 are inconsistent

**Expected behavior**
An error should be reported while performing the DELETE operation.

**Additional data / screenshots**
create table t(a int primary key); insert into t values(1),(2),(3); 
T1:BEGIN;select * from t where a=1;delete from t where a=1;
T2:BEGIN;select * from t where a=1;delete from t where a=1;select * from t where a=1;

**Environment:**
 - CockroachDB version 20.2
 - Server OS: Linux
 - Client app cockroach sql

**Comment by gzq1991** [comment]
This is for your reference only
![image](https://user-images.githubusercontent.com/56956386/97648249-395d6680-1a8f-11eb-9ec0-7a028fef44ea.png)

**Comment by jordanlewis** [comment]
Thank you for the report. Apologies from the slow response. I can repro this, and I would agree that it's at least odd behavior.

![image](https://user-images.githubusercontent.com/43821/98489795-82cf5380-21fd-11eb-999d-254fa6cade12.png)

@knz, I think you would be most easily able to route whether this is a SQL or KV issue given recent work - any thoughts?

**Comment by nvanbenschoten** [comment]
I just tested this out and found that when the second transaction goes to commit, it receives a transaction retry error. So it won't be able to commit, as expected. But the report here is correct that the transaction retry error is being deferred too far, which is allowing a non-serializable state to be leaked to the client through the `DELETE` return value.

I think the reason for this is because `DeleteRangeRequest` is considered to be a blind write, so [any `WriteTooOld` error it hits is being deferred](https://github.com/cockroachdb/cockroach/blob/be84ae4a59e6a5e50694c1756e05b0ba7c3a54d8/pkg/kv/kvserver/replica_evaluate.go#L314). This is correct for standard `DeleteRangeRequest`s, but not for those with the `ReturnKeys` flag set. In those cases, a `WriteTooOld` should be propagated immediately. I thought the fix for this would be as simple as:
```
diff --git a/pkg/roachpb/api.go b/pkg/roachpb/api.go
index aa796141ab..f1ae0664be 100644
--- a/pkg/roachpb/api.go
+++ b/pkg/roachpb/api.go
@@ -1194,6 +1194,10 @@ func (*DeleteRequest) flags() int {
 }

 func (drr *DeleteRangeRequest) flags() int {
+       maybeRead := 0
+       if drr.ReturnKeys {
+               maybeRead = isRead
+       }
        // DeleteRangeRequest has different properties if the "inline" flag is set.
        // This flag indicates that the request is deleting inline MVCC values,
        // which cannot be deleted transactionally - inline DeleteRange will thus
@@ -1209,14 +1213,14 @@ func (drr *DeleteRangeRequest) flags() int {
        // This workaround does not preclude us from creating a separate
        // "DeleteInlineRange" command at a later date.
        if drr.Inline {
-               return isWrite | isRange | isAlone
+               return isWrite | maybeRead | isRange | isAlone
        }
        // DeleteRange updates the timestamp cache as it doesn't leave intents or
        // tombstones for keys which don't yet exist, but still wants to prevent
        // anybody from writing under it. Note that, even if we didn't update the ts
        // cache, deletes of keys that exist would not be lost (since the DeleteRange
        // leaves intents on those keys), but deletes of "empty space" would.
-       return isWrite | isTxn | isLocking | isIntentWrite | isRange | consultsTSCache | updatesTSCache | needsRefresh | canBackpressure
+       return isWrite | maybeRead | isTxn | isLocking | isIntentWrite | isRange | consultsTSCache | updatesTSCache | needsRefresh | canBackpressure
 }

 // Note that ClearRange commands cannot be part of a transaction as
```
But that didn't seem to fix the issue, so there might be a little more going on here as well. I'm actually seeing `RETRY_SERIALIZABLE` errors instead of `RETRY_WRITE_TO_OLD` errors, which indicates that things aren't interacting quite as expected and that the timestamp cache might somehow be related.

I'll continue taking a look tomorrow. Thanks for filing this @Cynthia-Lee97!

**Comment by nvanbenschoten** [comment]
The other issue here is that `MVCCDeleteRange` is failing to return a `WriteTooOld` error when it observes a tombstone at a higher timestamp than the deleting transaction's read timestamp. The proximal fix for this is to include tombstones in the operation's initial scan:
```
diff --git a/pkg/storage/mvcc.go b/pkg/storage/mvcc.go
index 4e714ab536..d8e39b1713 100644
--- a/pkg/storage/mvcc.go
+++ b/pkg/storage/mvcc.go
@@ -2414,7 +2414,9 @@ func MVCCDeleteRange(
                scanTxn = prevSeqTxn
        }
        res, err := MVCCScan(
-               ctx, rw, key, endKey, scanTs, MVCCScanOptions{Txn: scanTxn, MaxKeys: max})
+               ctx, rw, key, endKey, scanTs, MVCCScanOptions{
+                       Txn: scanTxn, MaxKeys: max, Tombstones: true,
+               })
        if err != nil {
                return nil, nil, 0, err
        }
```

This ensures that the following call to `mvccPutInternal` returns a `WriteTooOld` error on any of these tombstones above the txn's read timestamp. With that change, we correctly restart the transaction immediately after the conflicting DELETE.

This fix is a little strange though, as I don't think we want to re-tombstone existing tombstones which exist below the transaction's read timestamp. So we'll have to be careful here to ignore those. I'm wondering if this is enough of a reason to rewrite this function and get rid of the call to `MVCCScan` in favor of an iterator. The use of `MVCCScan` was added in https://github.com/cockroachdb/cockroach/commit/ee80e3d8ebe815106a98063ad9f90b9345f6b575 as a performance optimization, back when `MVCCIterate` required a cgo call per key. Now that everything is in Go, I don't see a reason not to change it going forward, though it would also be nice to fix this in a manner that could be backported.

**Comment by nvanbenschoten** [comment]
I think this might have been fallout from https://github.com/cockroachdb/cockroach/pull/43008. Now that we're no longer detecting the WTO error from the write timestamp cache, it's up to `MVCCDeleteRange` itself to detect it. That's more consistent with how everything else works, so that's mostly ok, but then `MVCCDeleteRange` needs to uphold its half of the bargin.
