### ISSUE TITLE
sql: CHAR(n) not enforced on insert/update

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5624]
When inserting a value into a `CHAR(n)` column, the length limit is not enforced. We do enforce the length limit when casting a string to a `CHAR(n)` type:

```
root@:26257> select 'hello world'::char(5);
+--------------------------------+
| CAST('hello world' AS CHAR(5)) |
+--------------------------------+
| hello                          |
+--------------------------------+
```

**Comment by JackKrupansky** [comment]
(Should we guess whether shorter values are not space-extended to the limit as well?)

**Comment by knz** [comment]
Actually none of the constraints on column types are honored by insert or update. 

For casts only the cast to string honours the width. On int, float and decimal the precision and width are not honored either.

`marshalColumnValues` where the compatibility check is made with column types is not the right place to implement this constraint because its results are not used by index updates.
