### ISSUE TITLE
Dropping a table with more than one `nextval` calls (to the same sequence) in the DEFAULT expr crashes

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#56387]
**Describe the problem**
```
CREATE SEQUENCE bar;
CREATE TABLE foo (id INT, a INT DEFAULT nextval('bar') + nextval('bar'));
INSERT INTO foo VALUES (1);
DROP TABLE foo;
```

crashes with the following stack trace:
```
couldn't find reference from sequence to this column
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).removeSequenceDependencies
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/sequence.go:609
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).dropTableImpl
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/drop_table.go:307
  | github.com/cockroachdb/cockroach/pkg/sql.(*dropTableNode).startExec
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/drop_table.go:118
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:515
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:296
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  |     /Users/adityamaru/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:120
```
 - CockroachDB version master

Some high level debugging led me to conclude the following:
`removeSequenceDependencies` iterates over`UsesSequenceIds` from the column descriptor when removing dependencies. This slice is populated in `maybeAddSequenceDependencies` which walks the expression using the sequence, which in this is two invocations of `nextval`. Thus, the same sequence ID gets added twice to this slice.

When removing the dependency in `removeSequenceDependencies`, the first iteration finds the dep correctly and mutates the state to "remove" the dep. The second iteration (on the same seqID) is now unable to find the dependency to remove and fails with the above assertion error. One solution would be to ensure that the same sequence ID is not added to `UsesSequenceIds` more than once, but I do not fully understand how other parts of the system use this slice.

**Comment by arulajmani** [comment]
Looked into this a bit, and seems like adding the same sequence ID in a table descriptors `UsesSequenceIDs` is deliberate. This accounts for cases like when two columns of a table use the same sequence -- dropping one of those columns shouldn't remove the dependency, which is why it's important to track the number of times a sequence is used in addition to if the sequence is used! 

The problem appears to be this backrefs thing over here: https://github.com/cockroachdb/cockroach/blob/40806e4c8e41e95764613ff780c9211a00882ab3/pkg/sql/sequence.go#L508
This is supposed to track all descriptors modified in the current transaction and we use this "cached" version instead of the one returned by the desc collection. Currently, the caller of this function is responsible for adding stuff to the map. In the example above, as the sequence descriptor is being used twice for a single column, we're reading a stale version from the desc collection the second time around. The easiest solution here is to add to this map within the function instead of having the caller do it. 

I'm not quite sold on this though. In particular, I don't like this second level of cache above the descriptor collection that's being passed around between functions. I vaguely remember talking about this at a high level with you @lucy-zhang, could you recommend what we should do here? I haven't interacted with the desc collection in its new incarnation

**Comment by rafiss** [comment]
The example in the initial issue description no longer crashes. Closing this out, but please comment and reopen if you feel like there is still something missing. (I didn't read through all the background on what's been going on here.)
