### ISSUE TITLE
ui: unexpected undefined execution stats in the admin UI

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#56432]
This issue does not seem to occur when running a simple query.

To reproduce:
```
cd go/src/github.com/cockroachdb/cockroach
roachprod create local
roachprod put local cockroach 
roachprod put local ./bin/workload
roachprod start local
http://localhost:26264/#/overview/list
roachprod run local:4 -- "./cockroach workload fixtures import tpcc --warehouses=10 --db=tpcc"
roachprod run local:4 "./workload run tpcc --wait false --tolerate-errors --warehouses=10 --active-warehouses=10 --duration=15m --split --scatter {pgurl:1-3}"
```

Navigate to any statement's `Execution stats` page and the `Other execution stats` section will be empty:
![](https://user-images.githubusercontent.com/10560359/98552751-21f85780-229f-11eb-9bc4-45a5dabdff7d.png)

This is because in `statementDetails.tsx`, `r.value` is undefined here and therefore omitted:
https://github.com/cockroachdb/cockroach/blob/be84ae4a59e6a5e50694c1756e05b0ba7c3a54d8/pkg/ui/src/views/statements/statementDetails.tsx#L512

**Comment by asubiotto** [comment]
Note that #56431 fixes accessing an undefined `r.value` in the case of a specific stat, but it remains a mystery why `r.value` is undefined in the first place, for other execution statistics that should always be returned (such as `rows read`). cc @dhartunian where would be a good place to look?

**Comment by dhartunian** [comment]
@asubiotto this is due to the aggregation that happens on the client-side that collects all fingerprint stats across nodes to present in a unified summary.

the aggregation is a function from a list of protos to a single new instance and because the fields are nullable in the TypeScript definition, we can omit new fields in the aggregation function without causing a type error.

I will put up a quick PR.

My guess is that in a single-node scenario, this problem didn't come up because we didn't touch the proto.
