### ISSUE TITLE
bulkio: backups with temporary tables leave descriptors in weird state

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#56512]
When performing a database/cluster restore with temporary tables, a database's descriptors may reach an unexpected state.

In 20.1, this can be achieved with a database restore. In 20.2, this can only be achieved with a cluster restore (of a cluster with temporary tables).

After restoring a backup that contains temp tables, performing a `SHOW TABLES` in the cluster leads to:
```
root@localhost:26257/defaultdb> show tables;
ERROR: internal error: schema id 52 not found
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1940: forEachTableDescWithTableLookupInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1812: forEachTableDescAllWithTableLookup()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1788: forEachTableDescAll()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:404: func53()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:492: 1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:115: func2()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()
```

ID 52 refrences the pg_temp schema:
```
> select * from system.namespace;
  parentID | parentSchemaID |              name               | id
-----------+----------------+---------------------------------+-----
[...]
        50 |              0 | public                          | 29
        50 |             52 | a_temp_table                    | 53
        51 |              0 | public                          | 29
        54 |             29 | t                               | 55
```

One solution here could be to not restore any temporary tables back during cluster restore. However, in this case we need to consider possible jobs that could be referencing these descriptors. When a session ends, the temporary tables are dropped and we create a job (including a GC job, which references this descriptor). If cluster restore chooses not to restore temporary tables, then it should also choose to not restore jobs associated with their tables.

**Comment by pbardea** [comment]
Adding some thoughts based on a conversation with @adityamaru. 

One approach worth investigating is having cluster restore not restore any temporary tables as well as any jobs which reference temporary tables. We know have a mechanism for relatively easily injecting a function that can selectively filter job rows via a `systemBackupConfiguration` (https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/system_schema.go#L36). (This would need to be backported or we would make one-off filtering methods for backport fixes.) The filtering there could then check if the job references any dropped temporary tables. I'm unsure if there are cases where a job could indirectly reference a temporary object (dropping a database that contains the descriptor seems to be safe?).

Another thread that was discussed was whether the temp object cleanup could save us here. Specifically, if there was a path where we could restore into some good state before the cleanup job kicked in. Based on @adityamaru's research it looks like this isn't so simple and avoiding to restore the jobs might be the simplest way forward.

**Comment by adityamaru** [comment]
So we played around with the above-specified approach of filtering out specific rows in the system.jobs/comments/zone configs table when restoring and removing any entries which referred to temp object descriptor IDs. There were concerns about RESTORE getting too much into the weeds with this approach, and in general we want to try and avoid playing catchup with new SQL features. Following is a new approach which @pbardea and I discussed:

- BACKUP all table descs including temp objects (tables and sequences)
- During RESTORE planning,  create a "fake" pg_temp schema in `defaultdb` with the name `pg_temp_0_0` or something of the sort. This would involve creating a schema key and writing it to system.namespace similar to `createTempSchema`. I think we would not want to update the session data mutator because we want this pg_temp schema to remain hidden to the rest of the cluster.
- Remap the parent schema ID of all the temp object descriptors to point to this newly created pg_temp schema.
- Rely on the reconciliation logic to pickup this schema and clean up all the temp objects associated with it.
- If the RESTORE job fails, the fake schema will still be cleaned up as part of the reconciliation.

The pros of this approach are that it does not introduce too much logic to restore in terms of special-casing system tables. It also relies on the existing temp reconciliation logic and will be easier to backport to 20.1.

The cons are that it relies on the naming convention of the pg_temp schema to be picked up as an "inactive session" during cleanup.

Wanted to get your thoughts on this @arulajmani @dt

**Comment by dt** [comment]
I think I like this approach -- synthesizing a temp session and letting the existing clean up handle it -- more than teaching RESTORE to do the filtering.
