### ISSUE TITLE
Scheduled backups to S3 fail when using implicit auth with frequently rotated tokens

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#56536]
**Describe the problem**

Scheduled backup to S3 using implicit auth fails on cluster.  Customer is rotating host auth tokens every hour.  failure occurs on hourly backups.  The working assumption is that the token expires, but the database is holding onto the old token and not re-authenticating with the new token on the host.  

Customer suspects that the issue can be found and fixed here: 

1) Delete the s3 object from type s3Storage: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/cloudimpl/s3_storage.go#L39
pkg/storage/cloudimpl/s3_storage.go:39

2) Fix breakage by instantiated a new s3 client every time you need to talk to the cloud during a Put or Get call

3) Optional: figure out the client max age and cache the s3 object for 50% of the token age
pkg/storage/cloudimpl/s3_storage.go:39
https://github.com/cockroachdb/cockroach|cockroachdb/cockroach>cockroachdb/cockroach 

Epic CRDB-71

Jira issue: CRDB-2931

**Comment by miretskiy** [comment]
Disclaimer: I'm not an expert on the all things authentication...
After reading some docs, I think we have few issues at hand.

1. This problem is not specific to backup; it effects any access to external storage (backup, restore, import, CDC)
    since tokens can expire at any time.
2. Even if we could detect/query token expiration, we will not be able to generate new tokens.
    
I maybe wrong here, but I think the use of temporary tokens on any of the above operations
may not be something we can support.  In general, the generation of the token need not occur
on the same instance or even for the same user.    The node running backup/restore/etc may 
not have access to the IAM identity that has permissions to generate  temporary tokens. 
And if that identity has permission to generate tokens, then... why use those tokens if you could
use identity?

**Comment by mikeczabator** [comment]
disclaimer : I also not an expert on auth.  

My understanding is that each individual host is authenticated.  The db uses the host's authentication via AUTH=implicit.  The host always has access to S3, via the rotated token.  The problem seems to be the database is not refreshing the session via a new token when running the hourly backup jobs.  It will work for the first hourly backup, and fail via the second.  When manually running the SAME command via SQL, it works.  The problem seems to lie within the scheduled jobs.

**Comment by miretskiy** [comment]
Makes sense. The AUTH=impolicit is the key here.  We do have issues around explicit authentication w/ temp tokens.
Created separate issue for that.

**Comment by mikeczabator** [comment]
Thanks.  Can you share that new issue please so I can track?

**Comment by miretskiy** [comment]
I linked  explicit auth issue to this issue.

Also: aws sdk does not reload config files when they change: https://github.com/aws/aws-sdk-go/issues/1993

**Comment by miretskiy** [comment]
I think we now fully understand the scope of the issue and what it will take to address it.

The underlying problem, turns out, has to do with how AWS SDK treats and refreshes
various credential providers.  Basically, when creating s3 client, a chain of authentication providers
is constructed; by default consisting of: environment provider (those AWS_ACCESS_KEY, etc env variables),
user configuration, shared configuration (the ~/.aws/credentials file).  However, while it is possible
to specify session tokens via any of the above mechanisms, it is not possibly to specify when such
token expires (and thus, making job of refreshing credentials on our side that much harder).

It also appears, that contrary to the code comments in the SDK, the above providers are initialized once, and are
never reloaded/reinitialized because, after all, those credentials do not have expiration (or, to be more exact:
SDK does not provide a mechanism to specify such expiration).
There is a feature request issue open against AWS SDK requesting for a mechanism on refreshing
local config(s): aws/aws-sdk-go#1993

My read is that AWS will likely not address the above issue.  But they do point a way to address
this problem right now.  To be clear, this is not a hack, or a workaround, but rather, using the 
builtin SDK credentials providers, and using the fact that we already configure AWS SDK to retry,
up to 10 times, transient errors -- such as credential errors.

The immediate way forward (and that should work on any release cockroach binary) is to
switch from using a regular credentials file (shared credentials with keys/tokens/etc set) to using
credentials returned from either an HTTP end point or a special credential process mechanism.

Both of these mechanism must return a json object with the required credentials.  Alas,
the format of the JSON object is slightly different -- I suspect due to an oversight/bug on AWS's side.
I'm assuming that we will use the output of the `aws2 sts get-session-token` command and use
that output to construct required JSON for the provider endpoints.
The above command returns JSON object that looks like this:
```
{
    "Credentials": {
        "AccessKeyId": "MY_KEY",
        "SecretAccessKey": "MY_SECRET",
        "SessionToken": "MY_TOKEN",
        "Expiration": "2020-11-13T01:50:59+00:00"
    }
}
```

The easier mechanism is to use credential provider mechanism.
1. Create a default AWS credential configuration (~/.aws/credentials) file with the following sections:
```
[default]
credential_process=/path/to/creds.sh
```
2. creds.sh is a simple script which uses `jq` command to transform JSON into the format
    expected by the "crendential_process" provider:
```
#!/bin/sh

jq '.Credentials + {Version: 1}' /Users/ubuntu/.aws/creds.json
```
  In a nutshel, read a file `creds.json`, extract crential section and add required "Version" field.

And external process can update creds.json file, and the credtial provider program (creds.sh) will be invoked
automatically by AWS SDK to reload expired credentials.

The second mechanism is similar, only the data should be served from an HTTP endpoint.
1. Configure AWS with *empty* default profile
2. Start cockroach with the  AWS_CONTAINER_CREDENTIALS_FULL_URI variable pointing to 
    a localhost address that will serve JSON credentials; e.g. 
   ` AWS_PROFILE=none AWS_CONTAINER_CREDENTIALS_FULL_URI=http://127.0.0.1:8000/creds.json ./cockroach ...`

Again, external mechanism populates creds.json file server on http endpoint.
The only goatcha is that, instead of SessionToken, the file must contain "Token" key.
This can be done with jq program that renames SessionToken -> Token:
`jq '.Credentials | .["Token"] = .SessionToken | del(.SessionToken)' creds.json`

In the long run, we will also make changes in our code:
  1. Reduce the scope of the lifetime of the s3 object (as suggested by the comment above).
  2. Scope reduction will make the issue less prominent, and also harder to debug if/when it happens.
      Since credentials can expire at any time, we can't guarantee that we won't return credential
      errors.  We think there is a way to ensure that we retry operations Get/put/delete/list if such credential errors occur.
  3. We will determine if any of the above fixes are backportable (probably).
