### ISSUE TITLE
backupccl: TestRestoreMidSchemaChange is very slow under race and got much slower at the end of October

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#56584]
Filing this on behalf of the test infra community service team.

TestRestoreMidSchemaChange currently takes about 8 minutes under race: https://teamcity.cockroachdb.com/viewLog.html?buildId=2434684&buildTypeId=Cockroach_UnitTests_Testrace&tab=testsInfo

I noticed that it also got much slower at the end of October, before which it was very steady. Is that concerning? Feel free to close this if you don't care.

I do think we should probably skip this test under race if we're fine with it being so slow, though.

![image](https://user-images.githubusercontent.com/43821/98848278-7a566300-241f-11eb-9dee-6804fc63c2dc.png)

**Comment by pbardea** [comment]
Thanks for filing!

The timing lines up with when this test was expanded to include more test cases, as well as test cases to include cluster restore.

I don't think there's much value in running these under race since the purpose of these tests is just to check that we can restore a particular backup file.
