### ISSUE TITLE
ui: SAVEPOINT metrics

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5681]
Right now, we don't have any metrics for SAVEPOINTs. Maybe we should?

cc @andreimatei

**Comment by andreimatei** [comment]
meh, I don't see that being too useful.
One thing we might consider is if the commit metric should be incremented on RELEASE instead of the subsequent COMMIT. One thing that's currently wrong is that if you do `RELEASE` (succeeds) then `ROLLBACK`, we'll count the rollback as a rollback, although the transaction has committed at the RELEASE point.

**Comment by cuongdo** [comment]
doesn't seem useful
