### ISSUE TITLE
kvcoord: EvictionToken accidentally allocates too much

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#56917]
In `DistSender.sendToReplicas`, we accidentally produce objects when invoking `routing.Desc()` and `routing.Leaseholder()`:

```
	desc := routing.Desc()
	ba.RangeID = desc.RangeID
	leaseholder := routing.Leaseholder()
```

I think this is because `routing` is a pass-by-value `EvictionToken`, but those methods return pointers to fields within the `EvictionToken`.

This seems fixable by either passing `EvictionToken` by pointer or by storing the `Desc` and `Leaseholder` as pointers in the token.

All told, these allocations add up to about 1% of the total allocations in a `kv 100` workload.

**Comment by nvanbenschoten** [comment]
> I think this is because routing is a pass-by-value EvictionToken, but those methods return pointers to fields within the EvictionToken.
>
> This seems fixable by either passing EvictionToken by pointer or by storing the Desc and Leaseholder as pointers in the token.

These two suggestions seem spot on.

@andreimatei this looks like fallout from the recent work in this area. In general, this new structure is a little difficult to work with because of the interfaces in `pkg/kv/kvbase`. The `RangeCacheEntry` interface forces an allocation for all callers of `RangeDescriptorCache.Lookup` no matter what. It also restricts our ability to use pointer receivers for `EvictionToken`'s methods. How strongly are we tied to `RangeCacheEntry`? Was there a reason we didn't move `EvictionToken` to `pkg/kv/kvbase` instead?

If we want to keep the interface then I suggest we have `*EvictionToken` implement the interface instead of `EvictionToken`. This will at least allow us to avoid heap allocations in `DistSender` itself, even if other uses of the `RangeDescriptorCache` interface will remain sub-optimal.

After that, we should fix the assertion in `NewReplicaSlice` so that the method no longer causes its arguments to escape.

**Comment by jordanlewis** [comment]
This also shows up in `getRoutingInfo`, when we call `returnToken.Desc()`.

**Comment by andreimatei** [comment]
> in general, this new structure is a little difficult to work with because of the interfaces in pkg/kv/kvbase. The RangeCacheEntry interface forces an allocation for all callers

Yes, the `RangeCacheEntry` interface is unfortunate. Let me revive #53361 which was trying to get rid of it.
