### ISSUE TITLE
sql: regression test MovR

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#56922]
MovR is an important sample workload that we ship in our workload package for demos, use in education (e.g., documentation, training), and encourage SE use for customer demos. However, we don't regularly run tests against MovR to ensure that workload doesn't regress with changes to CockroachDB. We need to invest the same rigor of performance tests as we do with other benchmarks like TPC-C and TPC-H to ensure that MovR always works well for our end customers.

Examples of issues include [this](https://github.com/cockroachdb/cockroach/issues/56821#issuecomment-730548242) or this [slack conversation](https://cockroachlabs.slack.com/archives/CB5KE3RFU/p1605639486003700).

Jira issue: CRDB-2892

**Comment by awoods187** [comment]
cc @jordanlewis @vy-ton @nstewart

**Comment by nstewart** [comment]
Also this example from 20.1 - https://github.com/cockroachdb/cockroach/issues/49658

**Comment by rafiss** [comment]
We can add a nightly test that executes the steps of the Movr demo. The demo script is here https://github.com/cockroachlabs/scripted-demos/blob/master/geo-partitioned-replicas-demo.sh

We won't be able to commit to fixing all the issues that come up with this test, since there's such a broad range of features in the demo, but hopefully this is a good starting point for catching regressions and routing them to the correct team.

**Comment by vy-ton** [comment]
@rafiss @solongordon Can we add this for 21.1 stability or a quality initiative for 21.2?
