### ISSUE TITLE
do i need a hash index ?

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#57057]
I have a table, as follow：
CREATE TABLE logs (
    fid UUID NOT NULL DEFAULT gen_random_uuid(),
    username STRING NULL,
    createtime TIMESTAMPTZ NULL,
    content STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (fid ASC),
    INDEX time_idx (createtime ASC,username ASC) USING HASH WITH BUCKET_COUNT = 8,
    FAMILY "primary" (fid, username, createtime)
    );

there are tens of thousands of usernames, but each user generates logs not so frequently(1 log every 10 seconds for a user), 
if i just index on (username, createime), is there a single node hotspot when inserting ?
thanks a lot.

**Comment by jordanlewis** [comment]
Hi @carr123, do you need to query all recent logs across all users? If not, a `(username, time)` index will be fine and will likely not be hotspotted since it's got the username prefix.

If you do need to query all recent logs across all users, then you probably do want to put `time` first, and you probably do want to use a hash-sharded index.

For questions like this, it's better to ask in the Forum or Community Slack (links above) than GitHub, typically. Thanks!

**Comment by jordanlewis** [comment]
(Forum https://forum.cockroachlabs.com)

**Comment by carr123** [comment]
thanks very much
