### ISSUE TITLE
limitSize bug or defect

### ISSUE THREAD

**Issue by benlatern** [cockroachdb/cockroach#57215]
**Describe the problem**
vendor/go.etcd.io/etcd/3/raft/util.go line 212
`func limitSize(ents []pb.Entry, maxSize uint64) []pb.Entry {
	if len(ents) == 0 {
		return ents
	}
	size := ents[0].Size()
	var limit int
	for limit = 1; limit < len(ents); limit++ {
		size += ents[limit].Size()
		if uint64(size) > maxSize {
			break
		}
	}
	return ents[:limit]
}`

whether the ents[0] > maxSize or not,the ents[0] will return，This is contrary to the method function

**Comment by nvanbenschoten** [comment]
Hi @benlatern, thanks for the report. I believe this behavior is intentional. If we look at the `raft.Storage` interface, we see that the [`Entries`](https://github.com/etcd-io/etcd/blob/28d1af294e4394df1ed967a4ac4fbaf437be3463/raft/storage.go#L51-L54) method is also passed a `maxSize` value whose semantics are meant to mirror those in this `limitSize` utility. There, the comment says:
> MaxSize limits the total size of the log entries returned, but Entries returns at least one entry if any.

This seems critical to ensure that the Raft state machine never gets stuck due to a log entry that's too large to handle. What makes you think this is a bug or defect? A reading of the code?

I'm going to close this issue for now, but please re-open if I missed something.
