### ISSUE TITLE
opt: avoid re-constructing entire memo on Placeholder injection?

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#57223]
The `AssignPlaceholders` method is one of the most expensive in optimization for workloads that re-use prepared statements with placeholders over and over. I think it has to (partially?) re-Construct all operators in the entire memo, right? It looks like some memory is shared but not all (the `Private` fields are shared by reference I think, and not fully copied), which implies (maybe?) that it's safe to alias some of the memory in operators.

Would it be possible to avoid re-Construction of all operators in the memo by copying the relevant operators into new objects? For example, it's very expensive to rebuild the various table statistics objects - but presumably those are immutable and can be shared from a cache, no? I guess there are some things you need to re-optimize, like turning the placeholders into spans, but is there some that you can avoid?

The {{CoypAndReplaceDefault}} path is ~10% on workloads like YCSB/KV, where planning is a high fraction of the time spent per query. Here is a screenshot of a CPU profile on one of the YCSB workloads where we spend a lot of time doing reconstruction.

![image](https://user-images.githubusercontent.com/43821/100620081-fe4b8e80-32eb-11eb-8482-ea5e16fec92e.png)

**Comment by RaduBerinde** [comment]
In practice, assigning values changes most operators in the tree so it's not easy to know what is safe to reuse and what isn't.

A while back, @andy-kimball and I discussed a way to speed up YSCB-style queries with a special scan operator which turns a placeholder into a span. That way we wouldn't need to do anything, just reuse (execbuild from) the cached memo.

**Comment by andy-kimball** [comment]
Yes, I think a special `PlaceholderScan` operator is probably the next thing that could/should be done in order to cut down our planning times.

**Comment by sumeerbhola** [comment]
For kv95, we were discussing the cpu profile from https://github.com/cockroachdb/cockroach/issues/62078#issuecomment-809853915 that shows ~19% cpu in `makeOptimizerPlan`.

**Comment by nvanbenschoten** [comment]
@RaduBerinde the fast-path introduced in https://github.com/cockroachdb/cockroach/pull/63807 appears to have been very successful. Did you consider adding a similar fast-path for trivial mutations? Does the fast-path make sense for mutations? If so, it seems like it would be worthwhile, because I suspect that compared to scans, an even larger fraction of mutations in user workloads would be considered "trivial".

In workloads like kv0, we run trivial mutations like `UPSERT INTO kv VALUES ($1, $2)`. Even with the added cost of Raft consensus and disk write I/O, these workloads are often CPU bound, and `AssignPlaceholders` and the rest of `makeOptimizerPlan` is still prominent in CPU profiles.

<img width="1573" alt="Screen Shot 2021-12-30 at 5 24 07 PM" src="https://user-images.githubusercontent.com/5438456/147792068-b9a14c50-7b87-4d3f-9cb3-17b37384000d.png">

**Comment by RaduBerinde** [comment]
It should be possible, just some elbow grease involved. Feel free to file an issue against SQL Queries.

**Comment by nvanbenschoten** [comment]
Done in https://github.com/cockroachdb/cockroach/issues/77128.
