### ISSUE TITLE
kvserver: remove below-raft throttling

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#57247]
We currently throttle when adding sstables to the LSM due to background bulk operations. This throttling happens in two places, in `Store.Send`, prior to the proposal, and in `addSSTablePreApply`, when applying to the state machine at each replica. The latter is problematic in that it (a) delays applying later things in the raft log at the replica, and (b) blocks a worker on the raft scheduler, which can impact other ranges.

The `Store.Send` throttling only looks at the store health on the leaseholder, and we have seen occurrences where one node (or a few nodes) in a cluster has an unhealthy LSM store. If we maintained soft state in a node about the health of other stores in the system (this state would be slow changing), we could use it in `Store.Send` and remove the apply-time throttling.

This store health information can also be useful for throttling in the GC queue.

Jira issue: CRDB-2847

Epic CRDB-15069

**Comment by erikgrinaker** [comment]
@cockroachdb/repl discussed this a bit last week. We definitely need to avoid below-Raft throttling while holding the Raft mutex. Posting some preliminary thoughts below, nothing concrete yet.

We think that the store-level throttling likely happens a bit early -- it seems like the ideal throttling point would be right as the request is about to acquires latches in the concurrency manager. Requests can be hanging around for a long time between traversing the store and being evaluated, e.g. because they're waiting for latches. And throttling later than that basically means that we'll have to choose between head-of-line blocking (because we acquired latches), reordering problems (because we've already evaluated the request), or request reevaluation (to handle reordering).

We also felt like a distributed throttling scheme to take into account the health of follower stores would likely be too complex (and possibly more in the purview of the allocator, which should move replicas off of hot nodes). On followers, we can often defer command application as long as commands get committed to the log, which would allow us to do some level of local Raft throttling. But we would have to do this throttling without holding onto a scheduler goroutine, by returning early and backing off.

We'll also need to keep other throttling mechanisms in mind here, e.g. admission control and the proposal quota pool.

**Comment by erikgrinaker** [comment]
Note to self: if we were to do store-level throttling based on the state of other replica stores, we should consider using the existing store gossip mechanism:

https://github.com/cockroachdb/cockroach/blob/44223233bd1cdb59abaafd4e43d2f2404559026f/pkg/kv/kvserver/store.go#L2388-L2389

https://github.com/cockroachdb/cockroach/blob/e1f30c66effd61371c37a01d4b5ce025aef77142/pkg/roachpb/metadata.proto#L392-L401

Remote store info is maintained in `StorePool` (primarily for use by the allocator/rebalancer) by subscribing to gossip updates:

https://github.com/cockroachdb/cockroach/blob/24e3c4a8e0c53c0d16eb49caf4d68fced3b3d44e/pkg/kv/kvserver/store_pool.go#L397-L398

**Comment by erikgrinaker** [comment]
#74254 is related.

**Comment by erikgrinaker** [comment]
Store read amp is gossiped as of #77040.

**Comment by tbg** [comment]
Updating this issue to link it properly into the https://github.com/cockroachdb/cockroach/issues/79215.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/75066#issuecomment-1143065417 is also concerned with removing below-raft throttling, so closing this one.
