### ISSUE TITLE
20.2 Performance issues when using Postico

### ISSUE THREAD

**Issue by rsadres** [cockroachdb/cockroach#57302]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
When using [Postico](https://eggerapps.at/postico/) and 20.2 all tasks are slow. 
What takes 1 second with 20.1.X, takes 7 + 7 seconds with 20.2. Accessing the individual tables, which is normally instant takes 1-2 seconds.

**To Reproduce**

- Download Postico
- Run any query on a 20.2 cluster via Postico
- Run the same query on a 20.1.X cluster via Postico
- compare speeds

**Expected behavior**
I expected 20.2 to be the same speed if not faster. 

**Additional data / screenshots**
Speed issue:
<img width="1280" alt="Postico Fetching Schema 02" src="https://user-images.githubusercontent.com/10146234/100763957-d3cd0480-33c3-11eb-9607-754a2e344dd8.png">
<img width="1280" alt="Postico Fetching Schema 01b" src="https://user-images.githubusercontent.com/10146234/100763970-d596c800-33c3-11eb-8730-53b53bee5254.png">
<img width="1280" alt="Postico Fetching Schema 01a" src="https://user-images.githubusercontent.com/10146234/100763973-d62f5e80-33c3-11eb-9e8b-db32ea8ae6c4.png">

Additional issue: Screenshots of the Postico “settings/connection" window. One for connecting to the cloud, the other locally.
I have not changed anything my end, but in the latest update to 20.2 Cockroach added “public.” to all our tables in the schema. Not sure why?

<img width="653" alt="Postico - Cockroach Local" src="https://user-images.githubusercontent.com/10146234/100763977-d6c7f500-33c3-11eb-88f5-d16dbadf6486.png">
<img width="651" alt="Postico - Cockroach Cloud" src="https://user-images.githubusercontent.com/10146234/100763981-d7608b80-33c3-11eb-858b-00612154c2ad.png">

**Environment:**

**Additional context**
20.2 is not usable for this client in their normal workflow (with Postico)

**Comment by z0mb1ek** [comment]
I think it is related to https://github.com/cockroachdb/cockroach/issues/57249

**Comment by rafiss** [comment]
Thanks for the report!

The “public.” prefix is expected. That is the default [schema name](https://www.cockroachlabs.com/docs/v20.2/sql-name-resolution#naming-hierarchy), and in 20.2 we started including schema names in the output because we released the user-defined schema feature.

A couple questions @rsadres 
- Does the issue still exist if you use v20.2.2?
- How many tables are in this database?
- Can you share the exact query that you ran that was slow? (with sensitive/confidential identifiers removed)
- Can you also share the output of running `EXPLAIN <query>` (for both 20.1 and the slow 20.2 cluster)?

**Comment by rafiss** [comment]
We've heard back from the customer that v20.2.2 fixes their slowness. Likely because it includes https://github.com/cockroachdb/cockroach/pull/56349
