### ISSUE TITLE
sql/dbconsole: gauge that represents all actively running queries on the cluster

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57378]
A customer recently inquired on how to tell if their cluster was overloaded.

While we have executed SQL queries:
![image](https://user-images.githubusercontent.com/22278911/100893804-c2e6c680-3489-11eb-93d0-ce9ecc5b7132.png)
this is not the same as current concurrency as it really counts commits i.e. QPS

We do have `sql.distsql.queries.active` (also a graph "Active Distributed SQL Queries").
@a-entin has requested a similar metric for all SQL statements, i.e. across all selects/updates/inserts/deletes/imports/, regardless distributed or not.

Instead of looking at concurrency, you can measure cluster overload by looking at the hardware page. We do have the following relevant information on the hardware page:

- CPU
- Memory
- Disk Read Bytes
- Disk Write Bytes
- Disk Read Ops
- Disk Write Ops
- Disk IOPS in progress
- Available Disk Capacity
- Network Bytes Received
- Network Bytes Sent

If the cluster is overloaded with too much concurrency, one of the primary resources on this page would be overloaded.

We also measure goroutines:
![image](https://user-images.githubusercontent.com/22278911/100896126-4c979380-348c-11eb-8ee6-20df03b677da.png)
This isn't perfect either because there are non-SQL statement goroutines but is a reasonable proxy like the hardware pages. 

We could make an increment counter for every goroutine that corresponds to SQL statements to add a global concurrency metric if the hardware pages and goroutines are insufficient.

**Comment by a-entin** [comment]
CRL sizing /capacity planning guidance is based on workload concurrency. We need to surface this exact metric to enable customer compliance. Secondary attributes suggesting and "overloaded" condition is open to interpretation. Customers appreciate and willing to honor the sizing guidance, however must have an unambiguous metric to quantify and track *historically* the actual workload concurrency *at the database level*. Figuring out the actual workload concurrency from the application environment is particularly challenging in certain app architectures, like lambdas and micro-services. Added complication is because these arch types are often deployed with auto-scaling.
This "asked" metric would make it actionable - observe the metric, perform trivial arithmetic calculations based on the metric and voila - the recommended new cluster size. 

Re "global"... the metric needs to be across all sql statement types a user can execute, so it is "global" in that sense. However the metric needs be collectable and viewable by cluster and by individual node. It would have limited utility if only available "globally" at the cluster level. MVP is by node. One customer is specifically interested in table level utilization metric, yet this is driven by a different requirement, not capacity planning / sizing.

I don't know how to quantity an excessive cluster load via hardware tab in the UUI. Secondary signs of "overload" are:
- not actionable, i.e. don't provide quantification required to adjust the cluster size; and
- not even conclusive

Re non-conclusive observations...
CPU: Say we see 99% CPU utilization. Is this a good thing (good cluster utilization) or a bad thing (overload)? Note that we only chart user CPU, not surfacing system CPU. Even if we did show system, how do you account for perhaps other actors on the server chewing on CPU? Further, say by some insight, an operator is convinced the cluster is in overload. How does one decide by how much to increase the size?

RAM: Since CRL says no-swap, watching RAM doesn't help. It's either enough for the moment or OOM. Binary. No helpful for quantitative sizing decisions.

Storage: It is certainly possible to conclude from the UI page if storage is falling behind (have to consider caveats #48462 and #48465). Yet how would a user conclude if the storage is overloaded because of the user workload and not because say shared storage is experiencing some connectivity issues (e.g. AWS EBS volume has a noisy neighbor, there are no errors an indicators available to a user)? Anywho, not obvious how a user would act on these observations from the cluster size adjustments standpoint.

**Comment by jordanlewis** [comment]
Alex, I still can't actually figure out what you are asking for.

What does "workload concurrency" mean to you? You keep saying "workload concurrency" as if it's a well-defined term, and maybe it is, but I don't really understand what you are going for with this. Sorry if I'm being totally dense.

Is it the number of sessions that are currently actively executing a SQL query, across the cluster? (We have this one already...)

Is it the number of OS threads that are actually running on all servers? (Also available)

Is it the number of goroutines that are currently scheduled to be executed? (Also available)

Is it the sum of the currently active goroutines for all queries across the server? (Not available)

Something else?

What is the thing that the customer actually needs to be able to see here? Because if it's just "is my cluster overloaded", I'm sorry to say that we don't have a straightforward way of understanding whether CockroachDB is overloaded right now, as I'm sure you are well aware. This is obviously a problem, but it lacks a solution today.

**Comment by a-entin** [comment]
The original title represented the ask. The changed title does not.  The ask precisely - add metric for the number of actively executing statements. By node and aggregated to cluster level. Because it's an essential metric for workload governance. Seeing this metric would enable users to reconcile workload with the cluster size (total # of vcpus) and thus avoid cluster overload. The discussion in this thread also touches the points why other "methods" don't really help that goal.

By "workload concurrency" I'm referring to the number of actively executing statements. It is the same as the number of open transactions. When we discussed a simple limiter (admission control), we talked about exactly that metric. This ask is to expose that metric and have the ability to graph it over time in web ui.

Another way to say... there is a `sql.distsql.queries.active` for distributed active queries. Can we have the same thing but for *all* "queries", not just dist (presuming a query is any sql statement).

**Comment by jordanlewis** [comment]
Apologies. I have amended the title again.

This metric exists. It is called `sql.distsql.queries.active`. The metric is poorly named, and I apologize for any miscommunication about the meaning of this metric in the past.

This is the metric that is known currently in the db console as "Active Distributed SQL Queries":

![image](https://user-images.githubusercontent.com/43821/101064061-90100180-3561-11eb-8cbe-c91e2f59536e.png)

This metric is a Gauge that is incremented when any executable SQL statement begins, and decremented when it finishes. Note that, for the purposes of this `Gauge`, a `Subquery` and "Postquery" (foreign key checks and cascades) count as an active query.

This metric does not include things like `BEGIN` or `COMMIT`, only actual SQL statements.

I will close this for now. I do think we should clean this up, but I don't want to just clean it up ad hoc because it may break people's previously existing monitoring.

I will also create a new issue to add a Gauge for currently active *transactions*, which is a separate useful metric.

**Comment by awoods187** [comment]
https://github.com/cockroachdb/cockroach/issues/57475
