### ISSUE TITLE
streaming: add support for stream producer to create new stream generations

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57427]
Throughout the lifetime of a stream, it is desirable to be able to resume a stream or otherwise logically separate streams in time. These separations are referred to as "generations" in the cluster to cluster streaming RFC.

Generations enable a stream to be re-planned (and therefore have a new topology with different partitions). We might want to re-plan a stream if the topology of the cluster changes (the user would then need to kick off a new producer stream). 

Alternatively, consider streaming to a file-based system. In order to enable buckets to be eventually deleted, the producing stream should periodically create a new generation so that old generations can eventually be deleted when they are no longer needed.

Jira issue: CRDB-3541

**Comment by adityamaru** [comment]
Posting some notes from a discussion with @pbardea and @annezhu98 about adding generation support for cluster to cluster streaming.

**Refresher on the current state of things:**
1. Currently, a `stream address` refers to the PGURL of the node we will connect to, to stream data from.
2. The topology returns this stream address as the only partition address in the topology, so in the current implementation, stream address == partition address.
3. This means that there will only be one ingestion node running the ingestion processor, and that node will set up a partition on the source node that tracks changes on the entire tenant keyspace.

**Multi Partition setup:**
In the future, C2C will be configured in a way that every node in the source cluster will be responsible for one or more partitions that will stream events to outboxes. Nodes in the ingestion cluster will dial-up these outboxes, depending on the partition they are asked to ingest, and which outbox contains the changefeed events for that partition.

**Why generation support is important**

**Sinkless:**

In a sinkless stream, we have a single node emitting changefeed events. This node is also the coordinator node running the changefeed job. If this node were to die, the changefeed job would get adopted by another node in the cluster, but the stream client would lose connection with the dead node, and the stream would no longer see any events even if the job were resumed. Currently, there is no way for the stream client to discover what other nodes are in the cluster, so we will first have to build out the grammar to support listing all nodes in a cluster. On losing connection with the coordinator, the client should round-robin all the nodes we supplied via the query, and check which one is the new coordinator of the job so that we can start streaming events again. On the consumer side, we will have to tear down our ingestion flow, and replan it based on the new streaming address.

**Multi partition**

In a multi-partition configuration, the fundamental difference is that we do not have the ingestion job/client triggering the changefeed. Instead, the producer is kicked off separately and emits events to outboxes. Therefore, the incidence of who generates the new generation event on topology change, shifts to the producer. 
There are possibly two situations in which we emit a generation event:
- If an emitter node goes down, then the coordinator of the changefeed will realize this, and emit a new generation event.
- If the coordinator goes down, the job will be readopted by another node, and on resumption will emit a new generation event.

The above two situations are not mutually exclusive i.e the emitter could be the coordinator.

We cannot use the eventCh for each partition to inform the client/consumer of a generation event since some of these partitions might be on the now-dead nodes. Thus, we might need to persist the generation event and new topology somewhere where the consumer can poll it, and then react to a generation change. The details here should be ironed out once we have multi-partition support. Note, nodes being added to the source cluster 

Conclusion:
- For sinkless C2C we will have the client do all the work related to generating a new generation event, and locating the new stream address. 
- The client will convey this to a consumer via an API that will trigger a teardown of the existing ingestion flow, and a replan with the new stream address. This API should be usable by multi-partition C2C as well.
- More scoping needs to be done for multi-partition C2C generation support. This will be covered in other issues.
