### ISSUE TITLE
sql: TestCommitWaitState takes nearly 3 seconds

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#5743]
Something stinks here.

**Comment by andreimatei** [comment]
Looked a bit but I think the problem is somewhere in the shutdown. @tamird mind if I assign this to you in the hope of finding someone more suitable?
Or feel free to assign back if you give me a hint about about how to debug who's trying to open that grpc connection.

The stall doesn't happen all the time. When it happens, the log ends with some grpc failures to connect, which are not there when the shutdown proceeds quickly. The tasks to drain are there in both cases.

`make test PKG=./sql TESTS=TestCommitWaitState  TESTFLAGS="-v"`
```
I160418 19:03:23.311307 sql/txn_restart_test.go:511  !!! test done
I160418 19:03:23.311432 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:331
1      server/node.go:741
I160418 19:03:23.311736 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:331
W160418 19:03:23.311777 storage/intent_resolver.go:308  [node=1,store=1,range=5] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:742: node 1 stopped
I160418 19:03:24.312544 /Users/andrei/work/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:60633: getsockopt: connection refused"; Reconnecting to "127.0.0.1:60633"
I160418 19:03:25.813506 /Users/andrei/work/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:60633: getsockopt: connection refused"; Reconnecting to "127.0.0.1:60633"
I160418 19:03:25.814010 /Users/andrei/work/src/google.golang.org/grpc/clientconn.go:317  Failed to dial 127.0.0.1:60633: grpc: timed out trying to connect; please retry.
--- PASS: TestCommitWaitState (2.57s)
```

**Comment by dt** [comment]
I think this is the same thing in #5742 - I threw a bunch of timing in there and that one was also the deferred `TestServer.Close()` call and also only intermittently slow.

**Comment by tamird** [comment]
2400 runs with a 2-second timeout and no failures. I guess the gremlins fixed this one.
