### ISSUE TITLE
jobs: generate IDs from the client

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#57492]
Today job IDs are created by the `DEFAULT` expression on the primary key column. The problem with this is that the job IDs are often referenced inside of other objects. Given we don't know the job ID until we write the job record, constructing other things which reference a job in a transaction is awkward. Worse, we have some code that ends up leaking jobs because we create a new ID upon transaction retries, making the whole thing hard to make idempotent.

**Comment by lucy-zhang** [comment]
We actually don't get the job ID from the default expression upon writing the record, but from calling this method on the registry which itself calls `builtins.GenerateUniqueInt()`:

https://github.com/cockroachdb/cockroach/blob/3ae0f0638a7a8e2b5911ef57f88aa8494f2ac06c/pkg/jobs/registry.go#L442-L461

I think all these points still stand, though. Fixing it should be straightforward, since we can just export `makeJobID()` and call it outside the transaction closure when applicable (and when possible).
