### ISSUE TITLE
backupccl: no event log entries for restore and import

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57575]
The bulk I/O operations should be reported in the event log. They are not currently.

cc @aaron-crl @piyush-singh

**Comment by dt** [comment]
Not including BACKUPs in event log is intentional -- BACKUPs are scheduled to run e.g. every 5min and should be non-events, just the steady, background state of your cluster. Filling eventlog with them seems likely to be spammy.

Similarly, EXPORT isn't an event any more than `--format=csv -e "SELECT * ..." > myfile` (it isn't even a job, since it isn't resumable -- it is literally just a SELECT query that writes to a file instead of a terminal).

IMPORT and RESTORE though both seem like they should log events, since they create objects which would usually also be events if run on their own.

**Comment by knz** [comment]
ok that works for me

**Comment by knz** [comment]
Discussed with @aaron-crl : lower priority for the immediate CC free tier security goals, but we absolutely need this in v21.1 so that the Serverless release can use it.

**Comment by mwang1026** [comment]
We spoke about this wrt 21.1 and agreed that a single entry in event log specifying that RESTORE and IMPORT were run, and some reference to the directory / files that were imported/restored is sufficient.
