### ISSUE TITLE
catalogkv: GetAllDescriptors does not return temporary schema descriptors

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#57619]
Consider this:
```
demo@127.0.0.1:26257/defaultdb> set experimental_enable_temp_tables = true;
SET

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> create temp table t (a int);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select parent_schema_id, schema_name from crdb_internal.tables where name = 't';
  parent_schema_id | schema_name
-------------------+--------------
                52 | [52]
(1 row)

Time: 3ms total (execution 3ms / network 0ms)
```

The schema_name is `[52]`, which suggests it is not populated

https://github.com/cockroachdb/cockroach/blob/dd170893579a45b423df56d51a2039e703571bd1/pkg/sql/crdb_internal.go#L367-L371

I've looked into this, and it should get populated here by the GetAllDescriptors call

https://github.com/cockroachdb/cockroach/blob/dd170893579a45b423df56d51a2039e703571bd1/pkg/sql/crdb_internal.go#L293-L308

which suggests the temporary schema isn't even being returned by `p.Descriptors().GetAllDescriptors`.

Haven't had the chance to dig further, but smells fishy and not intended behaviour. User defined schemas work fine:

```
demo@127.0.0.1:26257/defaultdb> create schema u;
CREATE SCHEMA

Time: 32ms total (execution 9ms / network 23ms)

demo@127.0.0.1:26257/defaultdb> create table u.u();
found schema 54
found schema 54
CREATE TABLE

Time: 5ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select parent_schema_id, schema_name from crdb_internal.tables where name = 'u';
found schema 54
  parent_schema_id | schema_name
-------------------+--------------
                54 | u
(1 row)

Time: 5ms total (execution 5ms / network 0ms)
```

I've also found that the temporary schema gets returned correctly in `GetSchemasForDatabase`, but found no special case code there.

My short dig suggests that it never reaches

https://github.com/cockroachdb/cockroach/blob/dd170893579a45b423df56d51a2039e703571bd1/pkg/sql/catalog/catalogkv/catalogkv.go#L325-L326

Jira issue: CRDB-3511

**Comment by lucy-zhang** [comment]
I think there's a simple but unpleasant explanation for this, which is that `GetAllDescriptors` only scans `system.descriptor` and temp schemas don't have descriptors. `GetSchemasForDatabase` works correctly because it uses the the namespace table.

It's not going to be entirely straightforward to fix this by just scanning all the namespace entries, because we have both callers of `GetAllDescriptors` that expect descriptorless schemas and those that do not (e.g., in restore planning), so we probably just need a new concept of getting all the catalog elements. When getting all the catalog elements, we presumably also need some interface that encompasses both `catalog.Descriptor` and everything currently stored in `catalog.ResolvedSchema` (which is for name metadata for descriptorless schemas). I had opened #57538 as a proposal for dealing with this, but there should also be simpler ways to solve this immediate problem.

**Comment by postamar** [comment]
Considering that we're discouraging `catalogkv` usage outside of `descs.Collection` I'm going to close this.

**Comment by postamar** [comment]
Fixing the above issue will address this one, closing.
