### ISSUE TITLE
sql: tie timestamp/date functions to local clock instead of hlc clock

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5767]
From https://github.com/cockroachlabs/registration/issues/17#issuecomment-203936108

> I think the HLC is doing the right thing for the way we use it internally, but I'm not sure that exposing it (or rather, its wall-time component) as the sql-level timestamp is the right thing. Guaranteeing a non-decreasing clock at the expense of a much higher rate of duplicate values doesn't feel like a very good tradeoff. Maybe we should revisit cockroachdb/cockroach#5037 and instead of changing the basic timestamp functions, we introduce a new function that returns a strictly increasing HLC timestamp.

The concrete proposal is to revert the various time functions (`now()`, `current_timestamp()`, `current_date(), `age(), `transaction_timestamp()`, `statement_timestamp()`, etc) to use the node's local clock and introduce a new function (e.g. `cluster_timestamp()`) which is taken from the hlc clock.

@knz, @bdarnell Thoughts?

**Comment by tschottdorf** [comment]
Yeah, seems closer to the principle of least surprise. We're going to have
to explain distributed time anyway, so we might as well go for the one
that's most readily explained (and retains some entropy compared to the
current one).

Good luck with the migration though.

**Comment by petermattis** [comment]
What migration problem are you worried about here? The functions will still exist, they will just started returning slightly different timestamps.

**Comment by bdarnell** [comment]
This shouldn't have the migration problems because timestamps are computed at the sql gateway level, and there is only one gateway for a transaction. 

SGTM, but @knz should weigh in since he was the driving force behind the current model.

**Comment by knz** [comment]
I think having two sets of functions is fine. I don't think it matters too much which one is doing what as long as:

- `now`, `current_timestamp` and `current_date` are based on the same
- `now` is monotonic for a single client connection
- there exists at least 1 function that is monotonic in the same order as txn commits (currently that's `now`, but we could introduce another for that).

I haven't seen scenarios where applications rely on `now` being monotonic between clients in a distributed settings, however the existence of a monotonic function (`now` or otherwise) is essential for testing and debugging issues in transaction orders.

**Comment by bdarnell** [comment]
If we do this we may want to revert cockroachdb/cockroach-go#3. No need to muck with the max offset if HLC timestamps aren't easily observable.

**Comment by knz** [comment]
I would like to come back to the initial problem and request a clarification:

The current implementation already provides `statement_timestamp()` and `clock_timestamp()` to access the node-local time. Is it not possible for the test application(s) to use this instead of `now()` or `current_timestamp()` to avoid ts collisions?

(The question is motivated by simplicity: (re-)introducing a sql-level transactional timestamp would incur some unpleasant bookkeeping, since the sql txn ts must be preserved across retries and statement batches. I'd rather avoid that if possible.)

**Comment by petermattis** [comment]
Yes, test applications can use other timestamp functions than `now()`, but I think `now()` is the one most frequently reached for. I'm not clear on why re-introducing a sql-level transactional timestamp would be difficult. We have a natural place to store it in `txnState`.

**Comment by knz** [comment]
Then in terms of API. It is the case that Postgres aliases `current_timestamp()` to `transaction_timestamp()`, but what about CockroachDB splitting them and using `transaction_timestamp()` for the hlc clock and `current_timestamp()` for the local clock?

**Comment by petermattis** [comment]
Seems more confusing for our timestamp functions to have different semantics than Postgres. Better to introduce a new one.

**Comment by JackKrupansky** [comment]
Postgres has three levels of time: time at start of transaction, time at start of current statement, and time at the moment the function is executed. See:
http://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT

I'm presuming you probably intend to maintain the semantics of those three levels of time capture, but that the actual issue is which measure of time, node wall clock vs. cluster transaction time.

Is there a proper term for HLC minus its logical (L) part, since timestamp values would not have a logical part? Is there an easy way of getting this same HLC minus L value as each subsequent SQL statement and each invocation of now occurs? Node-local wall clock time certainly sounds easier.

I guess the odd thing would be if now() could be behind the start of transaction time if HLC minus L was earlier than simple node-local wall clock time.

But if the raw column values are used to create the replicas on nodes other than the leader node, then using the node-local time of the leader node if that's where now() would be calculated. OOPS... the transaction timestamp is caputured at the gateway node, not the range leader node. Interesting.

I checked the new proposed transaction docs and saw no mention of time or HLC. It would probably be good to incorporate some of this semantic discussion there, especially what exactly the transaction timestamp is.

**Comment by knz** [comment]
@JackKrupansky we already support 4 different time sources in our SQL dialect. The discussion here is which name to give to which. See my PR #5805 for the new proposal.

**Comment by knz** [comment]
Fixed via  #5805.
