### ISSUE TITLE
sql: REGIONAL BY ROW with computed region

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#57682]
Originally proposed [here](https://docs.google.com/document/d/1j4XxQtLJIYIsxmj6m3DkMlUsC1XyVHXN_d32YWSKydM/edit?disco=AAAAK32FfdQ).

By default (see https://github.com/cockroachdb/cockroach/issues/57670), REGIONAL BY ROW tables will create a hidden `crdb_internal` column with a type of `crdb_internal_region` and a default value of `gateway_region()`. This provides complete freedom to how this column is configured per row and is appropriate for when a schema contains no locality information.

However, there are cases where a schema does contain some locality information and this degree of freedom is not needed. In fact, in cases where there is a direct mapping between existing columns and the desired value of the region column, the degree of freedom can be detrimental. This is because the optimizer cannot depend on the mapping and so it still needs to fan out in various cases (point lookups, uniqueness checks, etc.).

To support this, we should support an alternative form of REGIONAL BY ROW tables with a computed region value. A strawman for how this might look is
```
CREATE TABLE warehouse (...) REGIONAL BY ROW AS (CASE WHEN w_id < 5 THEN 'us-east1' ELSE 'us-west2' END)
```
The computed REGIONAL BY ROW tables would behave almost exactly the same as standard `REGIONAL BY ROW` tables. The only difference is that the `crdb_internal` column would be a computed column. So instead of:
`crdb_internal crdb_internal_region NOT NULL DEFAULT gateway_region()`
the column would be expressed as:
`crdb_internal crdb_internal_region NOT NULL AS (CASE ...) STORED`

**Comment by rytaft** [comment]
After this is implemented, we'll need to ensure that the optimizer is choosing good plans for queries accessing `REGIONAL BY ROW` tables with a computed region.

Specifically, we'll need to make sure that the optimizer avoids adding uniqueness checks on the primary key for inserts and updates. This can be ensured by either (1) eliminating the `UNIQUE WITHOUT INDEX` constraint on the primary key for these tables altogether, or (2) adding logic in the optimizer to avoid adding uniqueness checks if the region column is functionally dependent on the rest of the key. I have a slight preference for option (2) since it seems more generally applicable.

Additionally, we might need to add some additional logic in the optimizer to ensure scans are local. This is probably just a matter of ensuring that we are adding a constraint on the computed column if the columns it depends on are constrained.

**Comment by rytaft** [comment]
I've created #57720 and #57722 to cover the optimizer work, so this issue can be closed once the SQL syntax and semantics changes outlined at the top of this issue are complete.

**Comment by ajstorm** [comment]
@otan can you confirm that we've covered everything in here, and if so, close this issue?

**Comment by otan** [comment]
bye bye
