### ISSUE TITLE
server: expose a Prometheus metrics handler

### ISSUE THREAD

**Issue by mdlayher** [cockroachdb/cockroach#5768]
Hey all,

Did some playing around with CockroachDB last night, and I noticed that it can export a wide variety of metrics about itself, but it seems that these may be in a custom format.

Have the team thought about adding [Prometheus](https://prometheus.io) metrics to CockroachDB?  It seems that many of the existing metrics would directly map to Prometheus metrics, and Prometheus is already being used by a variety of large projects, such as etcd and Kubernetes.

If this has been considered and decided against, I will continue my plans to create a CockroachDB Prometheus exporter using metrics parsed from `http://localhost:8080/_status/metrics/local`.

Thanks for your time!

**Comment by andreimatei** [comment]
@mrtracy might have some opinion on this, he's one of the people that did work on our metrics

**Comment by mberhault** [comment]
we have actually, I took a look a little while back, but put it on the back burner.
We'll actually be visiting SoundCloud next week, and I'm certain this will come up. Adding relevant parties: @tschottdorf, @beorn7

**Comment by mdlayher** [comment]
Excellent!  Very happy to hear this.  I may even be able to pitch in and contribute native Prometheus support in the near future.

**Comment by BramGruneir** [comment]
It looks like Prometheus expects time series which is perfect for our stats.  I see no reason not to support this directly.  And our UI can either consume these, or use the current ones if that's not an easy switch to make.
@mdlayher we would appreciate the help!

**Comment by SuperQ** [comment]
Well, to be more precise, Prometheus expects counters and gauge metrics.  It scrapes and creates time-series from that data.

We have a reasonably good metrics library for Go[0]

[0]: https://github.com/prometheus/client_golang

**Comment by beorn7** [comment]
Happy to chat about this, and to provide assistance where needed.

**Comment by mrtracy** [comment]
This is certainly something that has been on our informal road map. Our internally maintained time series database is aimed primarily at small or prototype deployments, to provide useful metrics immediately without requiring any additional software. This will be inadequate for larger deployments which want to use an external, specialized time series system; we need to begin supporting that scenario in the near future.

Under the covers, metrics for each machine are locally maintained using familiar data structures: counters, gauges, EWMA rates, histograms. While each machine periodically records the values of these metric structures into our internal time series database, these values could be recorded into _any_ time series system.

As I see it, there are two different problems in flight here:

##### 1. Using prometheus metrics data structures 
While our current library of counters/gauges/etc. is custom, but the only real benefit of that is its minimalism; I would be fine with converting to a third-party metrics library (such as that provided by Prometheus), as long as those structures have low overhead and provide the metrics that we need. 

However, we will want to support a variety of time series systems, not just Prometheus - I don't want to end up in a situation where we need to maintain separate counter-like structures to support different time series databases.

If the prometheus-provided metrics library can be easily swapped in, while still being agnostic to the actual time series database being utilized, then that might be a good course of action. This was actually considered by @mberhault and myself briefly a few months ago, before being tabled due to schedule constraints.

##### 2. Providing a handler for Prometheus
If we decide to use Prometheus's metrics library, then this is likely provided nearly for free. However, if we decide to continue using our custom metrics library, then we still must provide a handler for prometheus.

As I understand it, this will involve formatting our metrics data to be consumable by prometheus, and providing that from some endpoint.  This sounds relatively straightforward, but my big concern would be integration testing (making sure the format we provide is actually compliant with Prometheus). If anyone in this thread has guidance on that, it would be helpful.

**Comment by beorn7** [comment]
In short:

Ad 1.: There are two ways of being TSDB-agnostic. First, you could consider the Prometheus exchange format per se TSDB-agnostic. (It's understood by Influxdata's Telegraf, and anybody could quickly write a reader for it based on its protobuf definition.) Second you could wait for the client library refactor/rewrite (which I should work on instead of writing this comment). There you can at least tap into the stream of metric protobuf messages in your own code (via the then public registry interface) and add an adaptor to other formats. (This will anyway happen for Graphite as already done in the Python and Java client.)

Ad 2: Should you go for that approach, you don't need to generate the Prometheus format yourself (although some do that, again pretty straight forward if using protobuf). The client library has means of mirroring existing metric values (via the so-called const metrics). The expvar collector is an example for that.

**Comment by mberhault** [comment]
#6080 is a WIP. I took the approach of having our registry implement `prometheus.Collector` and our individual metrics objects implement `prometheus.Metric`.

While this is functional, we need to sort out our registry organization, mapping between metrics, labelling, and naming.
