### ISSUE TITLE
kvserver: serve follower reads before checking lease

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#57992]
Extension of #57397.

Once closed timestamps are separated away from lease state, it becomes possible to serve follower reads on ranges that have no active leaseholder. To do so, we'd want to check whether a read can be served by a replica based on the replica's closed timestamp _before_ checking whether the replica has or knows about the current Range lease.

An important property that this should give us is that once a replica begins serving follower reads at a timestamp, it will always continue to serve follower reads at that timestamp. This means that even if the replica becomes completely partitioned away from the rest of its range, it will continue to stale available for (increasingly) stale reads.

Epic: CRDB-2559

**Comment by andreimatei** [comment]
I tried switching around the conditions for serving as a leaseholder and serving as a follower below, and hit a snag: https://github.com/cockroachdb/cockroach/blob/679ee6e3e3bd6a8a36bf8ee22bf0665c59afa114/pkg/kv/kvserver/replica.go#L1312-L1317

As things stand, if I just invert the conditions and have the leaseholder evaluate a request under an empty lease status, that request just spins in case it runs into a lock. This is because, when hitting the lock and trying to handle it via `handleWriteIntentError()`, this obscure code path is hit:
https://github.com/cockroachdb/cockroach/blob/368e589e57e39c48048ae4c80d8cc33f5fb77b53/pkg/kv/kvserver/concurrency/lock_table.go#L2335
To the lock table, the situation looks as if a request evaluating under an old lease hit an intent and the expectation of the highlighted code is that the request will be re-evaluated under a newer lease and thus take a different code path (I think). However, without further changes, the request continues to evaluate as a follower read again and again.

I'm wondering what the moral is here. It seems to me that there are benefits from evaluating under a lease when there is a lease: the encountered locks can be added to the lock table. I guess the alternative is to arrange things such that a request evaluating on the leaseholder as a "follower read" handles locks the same way that a true follower would - I believe on follower the lock table is disabled and thus not involved in waiting for locks, and so the reader pushes directly. But, I assume there are benefits to going through the lock table (which I'd be curious to hear spelled out). I see notes, though, suggesting that maybe we actually want to go more in the other direction - enabling the lock table on followers.
https://github.com/cockroachdb/cockroach/blob/9157c7bfd0e9ebadcb06a7ce65a8c7765fb2780c/pkg/kv/kvserver/concurrency/concurrency_control.go#L765-L773
The note says that this might happen with the migration of replicated locks in to the lock table, so maybe it's close?

I want take the opportunity to discuss this issue more conceptually, to have it click more for me. The issue is motivated as:
> An important property that this should give us is that once a replica begins serving follower reads at a timestamp, it will always continue to serve follower reads at that timestamp. This means that even if the replica becomes completely partitioned away from the rest of its range, it will continue to stale available for (increasingly) stale reads.

I believe what this passage refers to is the fact that, currently, a replica doesn't activate the follower reads code path when the lease it knows about is invalid. This is because of the following code:
https://github.com/cockroachdb/cockroach/blob/e0244451438cf7426a11acd0c5ef8afd8b665c18/pkg/kv/kvserver/replica_follower_read.go#L68-L70
This code doesn't handle the `InvalidLeaseError` (produced [here](https://github.com/cockroachdb/cockroach/blob/1ac67a16817238f601f0b49bd7a67ad3c1531505/pkg/kv/kvserver/replica_range_lease.go#L987)) and, even for the `NotLeaseholderError`, it nitpicks the error's fields. This code is crap, as far as I can tell. The only reason the code has to care about the specifics of the lease error has to do with the following line:
```
r.store.cfg.ClosedTimestamp.Clients.Request(lErr.LeaseHolder.NodeID, r.RangeID)
```
This is about the "old closed timestamp code", and is going away momentarily. So, I can simply remove the error checks inside `canServeFollowerReads()` and thus get the property that the current status of the lease (or rather the replica's view of the lease status) will have no bearing on serving follower reads. Which is what we want, right? The reordering of the checks that this issue is ostensibly asking for doesn't really seem necessary. Does this sound right?
