### ISSUE TITLE
opt: add support for using the insert fast path with uniqueness checks

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#58047]
It is currently not possible to use the insert fast path if any uniqueness check postqueries are required. Since some `REGIONAL BY ROW` tables will require uniqueness checks on every insert, it would be unfortunate if we cannot ever use the insert fast path for those tables. This issue covers the work to investigate whether it may be possible to support uniqueness checks with the insert fast path, and if so, implement the necessary changes.

Epic CRDB-26290

Jira issue: CRDB-3441

**Comment by rytaft** [comment]
This has come up again as something that would be important for a customer using RBR tables. It would allow us to cut the number of round-trips required for an insert from 3 down to 1 or 2, which impacts latency a lot. Let's investigate how hard it would be to support this.

**Comment by rytaft** [comment]
In addition to an explicit fast path, a simpler option may be to simply parallelize checks with the mutation, as described in https://github.com/cockroachdb/cockroach/issues/58942:

> It may also be possible to run the uniqueness checks in parallel with the mutation itself. If the mutation only affects a single row, the uniqueness check can be trivially parallelized with the mutation (particularly if the mutation is an INSERT with VALUES input).

**Comment by msirek** [comment]
@rytaft To clarify, is this issue open for just making insert fast-path uniqueness checks for REGIONAL BY ROW tables faster, or all uniqueness checks in general (including non-RBR tables)?  The former may be easier to do. We could just build GET requests for all the possible regions besides the region being inserted to, and make them part of the batched KV requests (including PUTs) sent by the `insertFastPathNode` (which should execute in parallel, I believe, since they target different ranges). If any of the GETs return a row, error out.  

For general uniqueness checks, we probably can't make any assumptions about the form of the uniqueness checks and would have to keep them in their current form (a separate `exec.Node` tree which is run separately). Though [here](https://github.com/cockroachdb/cockroach/issues/58942#issuecomment-1476814893) it sounds like it may not be possible to run these simultaneously with the mutation.
