### ISSUE TITLE
Disallow even number of replicas in a zone configuration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5809]
Currently, you can specify an even number of replicas in a zone configuration. For example:

```
$ ./cockroach zone set .default  'replicas:
- attrs: [us-east-1a]
- attrs: [us-east-1b]
- attrs: [us-west-1a]
- attrs: [us-west-1b]'
```

@petermattis mentioned that this can lead to situations where both sides of a network partition can form a quorum. 

We should therefore require that zones always list an odd number of replicas.

**Comment by bdarnell** [comment]
> both sides of a network partition can form a quorum.

That's not true. A majority is always required: 2/2, 2/3, 3/4, 3/5, etc. We should strongly discourage even-numbered configurations because they are relatively brittle (especially two-node clusters which are strictly less reliable than a single-node cluster), but we don't need to strictly disallow them.

**Comment by jseldess** [comment]
@petermattis, based on @bdarnell's comment, should I just put a strong discouragement in the docs?

**Comment by petermattis** [comment]
@bdarnell Good point about a majority being needed. While we don't need to strictly disallow even node clusters, do you see any good reason for allowing them?

**Comment by bdarnell** [comment]
We should definitely disallow 2, since it's dangerous and an attractive starting point. Other even numbers don't make sense for now, but they could when we have better support for reading from followers (so you could use the fourth replica for geographic distribution and not just fault tolerance). Until then they're not very useful, but they're not so obviously harmful that they need to be banned IMHO.

Note that this ban will have to be enforced at the zone configs and not at the deeper layers, since internally we pass through a 2-replica configuration on the way from 1 to 3.

**Comment by JackKrupansky** [comment]
Jesse, et al, my glossary has entries for quorum, network partition, split-brain, replication count, etc. that you guys are welcome to use that detail a lot of this stuff. The RF entry in particular discusses the 2 and odd issues mentioned here. Let me know if there are any relevant terms that aren't in my glossary.

**Comment by petermattis** [comment]
I was thinking we would ban invalid configurations in `ZoneConfig.Validate`.

**Comment by jseldess** [comment]
@JackKrupansky, definitely plan on leveraging that glossary. It just hasn't been a priority, compared to other fundamentals for getting a user up and running. Hopefully for v1.
