### ISSUE TITLE
kv: TestResetQuorum is timing out (acceptance test)

### ISSUE THREAD

**Issue by TheSamHuang** [cockroachdb/cockroach#58165]
Updated `TestResetQuorum` test is timing out.

**Comment by rafiss** [comment]
The acceptance test is still skipped, so reopening. See https://github.com/cockroachdb/cockroach/blob/faaa7322a352c5d4d1852256910af09a01e5d0fd/pkg/cmd/roachtest/tests/reset_quorum.go#L28

**Comment by irfansharif** [comment]
This roachtest tests a small subset of what TestResetQuorum does, except this roachtest was skipped since 2020 when it was first authored. It also makes use of the deprecated crdb_internal.ranges_no_leases view, pre-coalesced ranges (the unit-test equivalent does not suffer from this issue). Removing in https://github.com/cockroachdb/cockroach/pull/105631.
