### ISSUE TITLE
sql: schema change probably doesn't work in practice

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#5817]
Discussed with @vivekmenezes today: since we use CPut when backfilling schema changes, we are likely to encounter an already-written-and-correct key and fail to write to it. The solution is to filter out already-present keys, yet we currently do not do this. All the code is in sql/backfill.go.

**Comment by vivekmenezes** [comment]
I had forgetten why we needed to use CPut for indexes. We do it to ensure uniqueness of the index when the index is marked UNIQUE.

**Comment by tamird** [comment]
That's not the only reason; we must also do it to ensure we don't overwrite
an existing value as there may be write skew between the backfill and
another UPDATE.

**Comment by petermattis** [comment]
I thought backfill transactionally read rows from the table and created the corresponding index rows. There shouldn't be any skew possible. If something else is writing to the table, either that transaction will succeed or the backfill one will.

**Comment by tamird** [comment]
In the case of a mutation adding both a column and an index on that column,
I believe write skew is possible.

**Comment by petermattis** [comment]
Can you elaborate on the specific problem scenario?

**Comment by seiflotfy** [comment]
Is it ok if i work on this, I am already busy with backfill.go

**Comment by seiflotfy** [comment]
Can someone provide an SQL statement that would trigger that issue?

**Comment by vivekmenezes** [comment]
This has to be triggered by adding a test to schema_change_test.go.

What you could do is create a table, add some data to it. Then add a new index mutation to the table descriptor and make sure it's in the WRITE_ONLY state. Insert some more data to the table, which will result in some new index entries being written. Now run the backfill, and the cputs to the new index will fail because some entries are not null.

I'm happy for you to add this test, see that it fails and then disable it and check it in. You can then work on the fix with the test enabled in a separate PR.

Thanks for taking on these challenging changes!

**Comment by vivekmenezes** [comment]
the test should be in sql/schema_changer_test.go

Thanks

**Comment by tamird** [comment]
@petermattis one case that could cause this is adding a unique column to an existing table - the new index and column descriptors will be in the WRITE_ONLY state when the backfill commences; suppose there is a no-op update at the end of the table - this update will write only the new column and index, leaving existing values untouched. When the backfill process arrives here, its CPuts will fail.

**Comment by seiflotfy** [comment]
When you guys are talking backfill, after adding a new index, should I add a new column?

**Comment by vivekmenezes** [comment]
The test you are adding should be added for both 1. a new index, and 2. a
new column with a default value. They're two separate tests for this bug.
I'm happy to see them as separate PRs if you'd like. Thanks!

**Comment by seiflotfy** [comment]
Can't the tests be done via normal TestLogic (SQL statments) ?

**Comment by vivekmenezes** [comment]
No, because it's a race condition you're trying to simulate here. You need
to add a mutation, then before the backfill runs you need to insert a few
entries, then run the backfill. The order of the operations is important.

**Comment by vivekmenezes** [comment]
@seiflotfy I'm planning on working on this as part of 

https://github.com/cockroachdb/cockroach/issues/3274

I hope you've not started working on it. Thanks

**Comment by seiflotfy** [comment]
Go ahead, I was waiting for my PR to land in case i need to touch that part
again

**Comment by vivekmenezes** [comment]
There is plenty of stuff to get your hands dirty with 👍

**Comment by tschottdorf** [comment]
Why not Put instead of CPut?

On Wed, Apr 6, 2016, 19:17 vivekmenezes <notifications@github.com> wrote:

> There is plenty of stuff to get your hands dirty with 👍
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5817#issuecomment-206471343>
>
-- 

-- Tobias

**Comment by vivekmenezes** [comment]
when we have a unique index we depend on the CPut to tell us that the index
for the current row is the same as the index for another row.

**Comment by tschottdorf** [comment]
Ah, didn't think of unique indexes. Ok, but then still another solution is going (locally) into the direction that (I think we all assume) KV is going to go anyway - make it a bit more flexible/savvy. For now, this would mean extending `CPut` so that it's not only possible to accept one existing value, but two (`nil` and whatever the unique index for the current source row dictates). Wouldn't that work? Having to filter through the existing entries sounds like a lot of work best avoided.

Something like (ignoring the need for a migration, which probably just means adding a hacky new field for the repeated value until we know how to handle this stuff).

```go
message ConditionalPutRequest {
  optional Span header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
  // The value to put.
  optional Value value = 2 [(gogoproto.nullable) = false];
  // Set exp_value.bytes empty to test for non-existence. Specify as nil
  // to indicate there should be no existing entry. This is different
  // from the expectation that the value exists but is empty.
  repeated Value exp_values = 3 [some options here];
}
```

**Comment by vivekmenezes** [comment]
I do like the idea of pushing this down to the KV layer. Anyone opposed to this change?

**Comment by petermattis** [comment]
If we're going to muck with the KV layer, perhaps we should add the ability to write at a historical timestamp so that the backfilling could be non-transactional. We discussed the details of this somewhere.

**Comment by tschottdorf** [comment]
Agreed that we should revisit it to see if we can bring those two things together (or at least have an idea about tying them in with each other). Without making perfect the enemy of good, obviously.

**Comment by petermattis** [comment]
#2860 is the existing issue for adding the necessary KV functionality to support transaction-less backfill. Enhancing `ConditionalPut` is likely much easier.

**Comment by vivekmenezes** [comment]
I'm going to go ahead and extend CPut. I think it's a clean way to do this.

**Comment by vivekmenezes** [comment]
This change is going to look like this:

```
message ConditionalPutRequest {
  optional Span header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
  // The value to put.
  optional Value value = 2 [(gogoproto.nullable) = false];
  // Set exp_value.bytes empty to test for non-existence. Specify as nil
  // to indicate there should be no existing entry. This is different
  // from the expectation that the value exists but is empty.
  optional Value exp_value = 3
  repeated Value other_exp_values = 4;
}
```

to allow us to disambiguate between the lack of existence of a key:value (nil) from a key:Null value (value with an empty []byte). There is no way to represent a nil value in a protobuf slice. It cannot be marshaled

So when specifying expected values, one value is placed in exp_value and the others in other_exp_values.  When a nil value is present among them it must go in exp_value.

Another option is to use a boolean to represent the nil exp_value. I'm not in favor of that, besides for backwards compatibility the first option is better.

**Comment by petermattis** [comment]
I'm having mixed feelings about this. See my new comment on #2860. Adding an `OlderThan` field to `DeleteRequest`, `PutRequest` and `ConditionalPutRequest` is where we want to eventually end up so that backfills can be performed non-transactionally. @tschottdorf, @bdarnell What kind of complexities do you see with doing this?

**Comment by bdarnell** [comment]
So the plan is that the new `value` and one of the `other_exp_values` would be the same, right? And when it matches the `CPut` is effectively a noop; you're just doing this to get a nil back instead of a `ConditionFailedError`? It feels dirty to me to make `CPut` take multiple expected values. I'd rather address this by changing the way we handle condition failures: add a boolean `error_on_mismatch` field to `ConditionalPutRequest` and an `actual_value` field to the response. When the flag is set, we don't return an error (so it doesn't short-circuit the batch), but we return the value we saw. The schema changer can then inspect the response and see if the mismatch represents the expected value or not.

Put-if-older-than seems like a safe addition if it solves the problem, although I'm not sure I see the big picture here and it seems like there might be races depending on how we select the timestamp.

Ultimately, though, I think we need put-at-timestamp. That's a scary change and I haven't fully thought it through yet, but I think we need to preserve the timestamp equivalence between data rows and corresponding index rows if we're going to support time travel queries.

**Comment by petermattis** [comment]
The context for put-if-older-than or put-at-timestamp is for backfill to be able to write index or column data  while user transactions are concurrently writing (though not reading) that data. I was imagining we'd use the timestamp at which the schema change was initiated, but you're correct that time-travel queries throw a wrench into that plan. We do know the timestamps of the table data since we scan the table in order to perform the backfill. Seems feasible to use those timestamps with a put-at-timestamp operation in order to preserve the timestamp equivalence with index data.

I'm curious why put-at-timestamp is so much scarier than put-if-older-than.

**Comment by bdarnell** [comment]
Maybe we're not talking about the same thing for put-if-older-than. I'm interpreting it to be a kind of conditional put, that writes a value with the current timestamp or not, based on the timestamp of the existing entry.

**Comment by petermattis** [comment]
Yes, that is what I was imagining for put-if-older-than. Clearly that is safe and I think it would work if we ignored time-travel queries.

Is there a specific concern about put-at-timestamp? I can see that violating the existing properties were data is always written at the newest version is scary, yet I'm failing to imagine what issues it could cause. Most likely that's because it is Friday afternoon and my brain is tired.

**Comment by bdarnell** [comment]
The scariest thing about put-at-timestamp is that it will require that all of our safety checks to ensure that time only marches forward (some of which can be complex and subtle) have new exceptions to allow these writes to occur in the past. There are a lot of opportunities to introduce bugs there, and lots of interactions to consider (e.g. how does it interact with the timestamp cache, or the gc queue, etc).

**Comment by petermattis** [comment]
Might be worthwhile to have a brainstorming session next week. If put-at-timestamp is too scary, perhaps we should see if time-travel queries can be made to work with put-if-older-than. My thinking here is that schema changes such as the addition of an index could have a timestamp in the associated `IndexDescriptor` and a query at an earlier time would ignore the index.

**Comment by bdarnell** [comment]
Yeah, I don't know whether we need time travel queries to support indexes that were added after the target time or not. But whether we need that as a feature or not, using different timestamps could come back to bite us in surprising ways.

**Comment by tschottdorf** [comment]
What exactly is a "time travel query"? Is that just a query at a past timestamp? I agree that it seems fishy to have different timestamps for index entries and their source row, and that we must make sure that the index isn't used for queries which have a timestamp lower than the maximum timestamp used in a backfill operation's chunk. That doesn't seem terribly difficult though as it could be made a property of the last mutation which switches the index in read-write mode.

I'm also not a fan of put-at-timestamp. Seems brittle and not worth it - it'd make sense if we retroactively wanted to pretend the index had always been there, but what's the point.

Happy to discuss this next week. Unrelatedly, I think the batching being transactional could be fine and not worth optimizing away if it's set up to rarely ever span ranges (`DistSender` can figure that out for us effortlessly).

**Comment by bdarnell** [comment]
Yes, time travel queries are queries at a past (user-specified) timestamp.

**Comment by vivekmenezes** [comment]
One option is for us to create a new Init() command that guarantees that
the value is initialized to a particular value. It would return an error
when encountering a conflict. It would be used specifically for the
backfill use case or loading new data into the db.

**Comment by tschottdorf** [comment]
I think the most straightforward way is still

* use an augmented `ConditionalPut` (as per @bdarnell's suggestion, though the responses could get a little fat - maybe we can trim it down)
* check responses for unexpected existing values (i.e. not `nil` or the value we tried to write)
* collect the maximum response timestamp used during backfill and attach it to the index before switching it to read-write mode
* use an index only if operating at a timestamp `>=` index' post-backfill timestamp
* can avoid the transactional overhead almost entirely by making the batching respect range boundaries (so that 1PC transactions are all we ever do) as outlined above.

**Comment by vivekmenezes** [comment]
Another option:

We use Put() and run another stage at the end called IsConsistent(). This new stage checks if the index is consistent before making it live. I say this because we have another consistency verification use case where we periodically want to verify the consistency of our indexes (just like we verify replication consistency today)

**Comment by spencerkimball** [comment]
I completely agree with @tschottdorf and @bdarnell that augmenting `CPut`, `Put` and `Delete` would be fraught. The amount of special casing we'd need to do would be fragile. Only way to go on something like this is a new op, IMO.

I've been thinking this past weekend about how to support a generalized bulk insert operation. My thought was we have a new `BulkPut` KV command which takes a key range. `BulkPut` is a ranged command with a repeated set of (key, value, timestamp). The first thing it does is scan the specified range. For many bulk load style use cases, this scan will be completely empty. On index backfill, it will be progressively more full of values as `BulkPut` calls are made to the same range.

The iterator on existing data, assuming it's not empty, is used to determine whether there are any existing values at earlier timestamps than the start of the bulk insert (i.e. the timestamp being used as the read timestamp for the backfill). This would be an error for `BulkPut` and would support the unique index constraint issue affecting backfill.

**Comment by vivekmenezes** [comment]
We've already discovered that we don't need CPut for the backfill column case. I think for the index case it makes most sense to use a BulkPut mechanism that just dumps a new index, and then later verifying whether the index is consistent before making it live for SELECT. In this particular case you need to only check if the index is the same size as the primary index (number of rows) in the table.

I agree that we should be sharing the same Bulk ingestion mechanism between bulk ingestion and backfilling when it's ready.

**Comment by bdarnell** [comment]
Limiting the ability to write at a past timestamp to a new command doesn't really allay my concerns. The safety checks that I'm worried about disabling are throughout the `Store`/`Replica` stack and not just in the specific commands. 

I think we need to separate the bulk-loading use case which operates like a more efficient version of the standard `Put` from the index backfill which may need to insert at a past timestamp and as a result has other constraints.

**Comment by vivekmenezes** [comment]
The index verification process that checks the size of the index at a particular timestamp can take a lot of time because it involves running a Scan() and counting the number of keys delivered. Is there a way to run Count(start, end Key) effectively?

I think the answer is no.

http://stackoverflow.com/questions/25538750/getting-total-number-of-key-value-pairs-in-rocksdb

Regarding fixing this issue, I don't like changing the API to sending back a conflicting value to the user. I'd prefer an API change that runs the users intention fully. This can involve:
1. modifying CPut to take more than one expected value.
2. Modifying Put to take an initialize/unique flag that puts the value at the key and barfs when it find a value different from the initialized value.
3. Add a new Init() method, same as above with a different name.

FWIW I'm not keen on 3 because we've only found one use case, but at the same time perhaps we're going to change that mechanism completely once we've figured out the bulk input use case and can easily delete this one call to it.

1 has the advantage that it's a more natural extension to the API (optional -> repeated), and there could be other use cases for it.

**Comment by tschottdorf** [comment]
re: @bdarnell's comment above:

> So the plan is that the new value and one of the other_exp_values would be the same, right? And when it matches the CPut is effectively a noop; you're just doing this to get a nil back instead of a ConditionFailedError? It feels dirty to me to make CPut take multiple expected values.

It doesn't feel dirty to me - our current `CPut` is "write this if that other thing is already there" and now the one that we want is "complain if something else has been written there already". We could add a boolean "Coalesce" to the proto that switches on the second behavior. Maybe that feels less dirty? In any case, option one is my favorite - 2 turns `Put` into some hybrid of `CPut` (which can only be worse than adding semantics to "real" `CPut`), and I agree with @vivekmenezes on 3.
I don't see why this solution can't carry us a long way even past 1.0 (with the intelligent batching repeatedly mentioned above), at which point we'll be better equipped to introduce more complicated solutions.

**Comment by vivekmenezes** [comment]
We've agreed that we're going to make this work with the current API. Given that this is one specific use case it's probably the right decision.

The current plan is to replace CPut with Put for populating the index. Additionally, every key written is going to be read and the value is verified to be either nil or equal to the one being written

**Comment by tamird** [comment]
Why replace cput? If you're filtering, you can be assured that you're only
writing values which are not present.

**Comment by vivekmenezes** [comment]
Good point. I'll leave CPut and use it for values where the expectation is nil.

**Comment by tschottdorf** [comment]
I can still only scratch my head. Why is adding a boolean to `CPut` such a big deal? The upshot is huge. The change is simple. It's very efficient (in the absence of specialized backfill commands which will most likely be at least as unintuitive as the new `CPut`). We'll almost certainly dramatically change the KV API at some point in the future and can back this out for something more powerful.
What am I missing here?

**Comment by vivekmenezes** [comment]
The main argument against is that this is a specific use case and it might be solved efficiently in kv using a solution that is more generic, but we don't know what that general solution is so it's best to use existing mechanisms and push the application of the policy to a higher level at the cost of latency.

For the distributed SQL case are we planning to add a complex conditional expression that we push down into the k:v store? That could be useful here.

**Comment by petermattis** [comment]
@vivekmenezes The current plan for distributed SQL is to not add anything to the KV layer. Processing will be distributed to the same node containing the data and we'll then take advantage of the local-call optimization to perform regular KV operations.

**Comment by tschottdorf** [comment]
We don't need to know what the "general" solution is until we know what the general problem is. We have a fairly concrete problem and we own the KV API and keep it internal precisely to have some flexibility. We can migrate this out at will later. The current argument is "let's do something bad instead of something good because the problem isn't general enough to do something about it". I don't know where all the discussion on that happened, but certainly not here.
Anyway, I've said what I wanted to say, and will hope that we won't find that the favored proposition is as bad as I think it's going to be in the most relevant prod scenario (backfilling a table under write pressure, where your backfill will have to restart pretty much continuously because it's two-phase and really gets in the way of everything, for each chunk written).

**Comment by vivekmenezes** [comment]
The plan is to also split up the backfill into chunks (perhaps 100 rows at a time), where each chunk is in a separate transaction. This will reduce the contention between the backfill and online r/w operations.

If we stick with the current API, some CPut writes of chunks will fail, resulting in those chunks being separately read and filtering applied to a subsequent CPut write to allow it to succeed. So the stuff that is happening outside the API is essentially applying this filtering every once in a while whenever an index entry is seen. I suppose even given the above, collisions are likely to happen often enough that we're going to end up doing a lot of filtering, which suggests pushing the policy into the API better approach.

Is there anyone against adding a boolean to CPut for this? I'll whip up a small PR with the options for the API change and add it to this issue for comment.

**Comment by vivekmenezes** [comment]
```
// option 1
func (db *DB) CPut(key, value, expValue interface{}, alsoUseValueAsExpValue bool) *roachpb.Error {
}

// option 2. Initialize key:value with initValue. Report an error if the key:value has already
// been created and the value is different from initValue
func (db *DB) InitKey(key, initValue interface{}) *roachpb.Error {
}
```

**Comment by bdarnell** [comment]
Adding a boolean to `CPut` that causes it to return without error if the new value is already present SGTM; I like that better than opening it up to specifying multiple arbitrary expected values (I missed the point in the conversation when that idea was introduced, so the earlier comments about adding a boolean to Cput confused me).

**Comment by vivekmenezes** [comment]
Fine. Ill implement the boolean addition to cput tonight
