### ISSUE TITLE
stability: node losing connection after 5-6 hours

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5826]
Build sha: 636e1b9
Scenario: beta cluster with moderate load (photos going slowly).

Approximately 5 to 6 hours after restart (not a fresh cluster, just node restart), two nodes lost connection to the cluster.
However, the connection seems fine, and I'm not seeing any relevant log entries other than:

```
W160402 23:33:29.271885 gossip/gossip.go:891  not connected to cluster; use --join to specify a connected node
```

Restarted `ec2-52-91-234-29.compute-1.amazonaws.com`, and no problems rejoining cluster.
I've left `ec2-54-208-199-194.compute-1.amazonaws.com` alone if someone wants to take a look.

**Comment by mberhault** [comment]
forgot the logs (for that run only, I dropped the parts of the logs before restart)
`ec2-52-91-234-29.compute-1.amazonaws.com`:
[node2.stderr.txt](https://github.com/cockroachdb/cockroach/files/201356/node2.stderr.txt)
`ec2-52-91-234-29.compute-1.amazonaws.com`:
[node4.stderr.txt](https://github.com/cockroachdb/cockroach/files/201357/node4.stderr.txt)

**Comment by bdarnell** [comment]
The message is clearly wrong, since `--join` is in use. I'm not sure whether this is just a bug in the logging or if it points to a bug in the way we're handling bootstrap addresses.

Just before the first of these messages, we see this:
```
I160403 00:13:17.923191 storage/replica_command.go:1374  range 31: new leader lease replica {3 3 11} 2016-04-03 00:13:17.430035493 +0000 UTC 1.490040542s
I160403 00:13:17.926671 storage/split_queue.go:116  splitting range=31 [/System/"update-cluster"-/Table/11) size=47703508 max=8388608
E160403 00:13:17.927329 storage/queue.go:446  [split] range=31 [/System/"update-cluster"-/Table/11): error: storage/replica_command.go:1656: unable to determine split key: storage/engine/mvcc.go:1958: the range cannot be split; considered range "/System/\"update-cluster\""-"/Table/11" has no valid splits
I160403 00:13:17.928817 storage/split_queue.go:116  splitting range=31 [/System/"update-cluster"-/Table/11) size=47703508 max=8388608
E160403 00:13:17.929256 storage/queue.go:446  [split] range=31 [/System/"update-cluster"-/Table/11): error: storage/replica_command.go:1656: unable to determine split key: storage/engine/mvcc.go:1958: the range cannot be split; considered range "/System/\"update-cluster\""-"/Table/11" has no valid splits
I160403 00:13:21.009870 server/status/runtime.go:160  runtime stats: 1.6 GiB RSS, 234 goroutines, 23 MiB active, 36978.08cgo/sec, 0.86/0.05 %(u/s)time, 0.00 %gc (23x)
I160403 00:13:31.008320 server/status/runtime.go:160  runtime stats: 1.6 GiB RSS, 235 goroutines, 45 MiB active, 27904.69cgo/sec, 0.76/0.04 %(u/s)time, 0.00 %gc (29x)
I160403 00:13:38.951116 storage/replica_command.go:1374  range 64: new leader lease replica {3 3 5} 2016-04-03 00:13:38.337582466 +0000 UTC 1.61185133s
W160403 00:13:40.901169 gossip/gossip.go:891  not connected to cluster; use --join to specify a connected node
```

I think the presence of "update-cluster" there is a boundary condition in the split logic (it's the last key before the system config span); what's really going on here is that the system config span (tables 0-10) has gotten pretty big: 47MB (and this cluster has had its split size reduced to 8MB). The system config span is not allowed to be split because it is gossiped. We may need a separate zone config for this span so that we don't keep fruitlessly trying to split it, although I think that's unlikely to be the real problem here.

If we were actually gossiping 47MB, that would probably be a problem that might cause nodes to have trouble connecting or staying connected. However, it looks like whatever that 47MB is is not actually getting gossiped: the total gossip payload (as reported by `/_status/gossip/local` on one of the healthy nodes) is only 9KB, including the encoded system db. Is there that much garbage (raft logs, intents, etc) in the system span that doesn't get gossiped, or is the update-cluster key somehow huge? (the udpate-cluster goroutine doesn't appear to be running amok; a stack trace reports its been asleep for 1148 minutes)

Is the node even broken? I can connect to it with `cockroach sql` and poke around, and it's able to reacquire leader leases and keep retrying that failing split. And it does have some information in gossip, although it appears to be missing the sentinel. Maybe there's some bookkeeping problem around `Gossip.incoming` and `Gossip.outgoing` that is causing it to get confused about which connections it has so it can't recover from gossip partitions?

**Comment by bdarnell** [comment]
I think it's significant that this started happening after the cluster size increased to 5. `gossip.minPeers` is 3, so in a 4-node cluster we expect every pair of nodes to be directly connected. 5 nodes is the smallest cluster in which multiple hops may be required for gossip.

**Comment by tschottdorf** [comment]
Try the acceptance tests with 5 hosts.

**Comment by bdarnell** [comment]
The acceptance tests with `--nodes=5` work for me. What am I supposed to be seeing?

**Comment by tschottdorf** [comment]
Nothing, that was just an easy thing to check.

**Comment by knz** [comment]
Do we still run into this issue?

**Comment by bdarnell** [comment]
I don't think we've seen any sign of it in months, so let's close the issue.
