### ISSUE TITLE
server: `cockroach mt start-sql` does not load / populate cluster ID from KV

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#58310]
I was trying to add the cluster ID in the logging output for SQL pods, and I found it missing.

The proximate issue is that there should be a call to `log.SetNodeIDs()` in the initialization routine, the way that `cli/start.go` does it.

However, in my attempt to add that, I did not find an initialized value for the cluster ID to feed into that call. Where should it be?

(Perhaps it is not actually loaded from KV during initialization?)

**Comment by knz** [comment]
cc @ajwerner @tbg

**Comment by andy-kimball** [comment]
What would `nodeID` be set to for SQL pods in `SetNodeIDs`? Zero?

**Comment by ajwerner** [comment]
I'd think `SQLInstanceID`:

https://github.com/cockroachdb/cockroach/blob/e53b17af66f158e5ba6412b6913b9b67616f633b/pkg/base/node_id.go#L78-L91

**Comment by knz** [comment]
I didn't grow an intuition for that. FWIW, the logging package only includes non-zero/empty values. So a node ID set to zero would cause the logging events to omit the node ID field.

Likewise, I already made the log package include the tenant ID and/or sql instance ID if present.

I am aware the node ID is made equivalent to the SQL instance ID for SQL planning purposes. However I think it doesn't make sense for telemetry and logging. In fact, it would create confusion if we aggregate telemetry/logging payloads from KV and SQL pods together. Unless we can distinguish these streams somehow? Maybe the simple presence of a tenant ID in the payload would be sufficient to interpret the "node ID" field as a sql instance ID.

**Comment by andy-kimball** [comment]
I notice there's a separate `func SetTenantIDs(tenantID string, sqlInstanceID int32)` method. So it'd be a bit strange to set `nodeID` to `sqlInstanceID` and also have it here.

I do like the idea of re-interpreting `nodeID` as `sqlInstanceID` based on context, but only if that works in all the places.

**Comment by knz** [comment]
> So it'd be a bit strange to set nodeID to sqlInstanceID and also have it here.

I would agree it makes sense to pass a zero value to the node ID in `log.SetNodeIDs` for this reason.

**Comment by andy-kimball** [comment]
What if SQL tenant pods queried KV to get a guaranteed unique nodeID? Would we be worried about nodeID exhaustion given that tenant pods will go up and down?

**Comment by knz** [comment]
yes I suppose we would. node IDs are a 31-bit entity  and practically we're uncomfortable using more than 16 of those bits due to how the default `rowid` column is populated in new tables.

**Comment by knz** [comment]
OTOH, perhaps the SQL pods could receive the node ID of their "main" peer KV pod.

**Comment by andy-kimball** [comment]
But then multiple SQL pods could have the same `nodeID`, which doesn't seem useful. This is probably impractical, but what if NodeID looked like this:
```
type NodeID struct {
	Kind NodeKind
	ID int32
}
```
Where Kind can currently either be `SQL` or `KV`. We'd thread that through all our code. In the (presumably) few places where we must use at most 32 bits (such as when generating rowids), we'd assert that we're in a non-ambiguous context, where the Kind is guaranteed to be one value.

**Comment by knz** [comment]
I'm not opposed to that.

**Comment by knz** [comment]
That being said - I'm just realized that with a fully random SQL instance ID as numeric node ID in SQL, we're getting broken behavior in the `unique_rowid()` function. That may be worth investigating separately.

**Comment by andy-kimball** [comment]
I'm not sure I understand what's broken. The `unique_rowid` function just relies on a guarantee that `SQLInstanceID` is unique for all currently running SQL pods, which should be true today.

**Comment by knz** [comment]
The `unique_rowid` has pseudo-monotonic  behavior, because it mixes the node ID in the low order bits with a timestamp in the high order bits.

Our users often mistakenly understand/assume it is actually time-monotonic. because the timestamp takes precedence for values of node IDs smaller than 16 bits. However,t he moment a value becomes larger than that, it interferes with the timestamp and breaks the pseudo-monotonicity. That's a likely correctness pitfall for users who have come to rely on the behavior.

The problem I am pointing to here is that we don't want to "exhaust" the pool of 16 bits values until we have a better handle on how users exploit `unique_rowid`.  This could be a problem if SQL instance ID is auto-generated from a process PID or a network address, for example, or is fully random (as I recall Tobias explaining me)

**Comment by andy-kimball** [comment]
Hm, I see what you mean, and am definitely surprised we'd flip timestamp bits. Isn't that actually buggy for node IDs greater than 16 bits, meaning we might have unique ID collisions?

**Comment by knz** [comment]
Yes it is and that is why I pushed hard against the idea of "repaving" nodes (which would force generating node IDs).

**Comment by andy-kimball** [comment]
I think we want a different concept to solve this problem, maybe called `TransientNodeID`. Unlike `NodeID`, this would be guaranteed unique only _at any given time_ rather than unique across time, similar to a Unix process ID. We'd build an algorithm that would reuse IDs in order to guarantee that `TransientNodeID` is always a small-ish integer < 16 bits.

However, now that I read the doc comment for `SQLInstanceID`, I see that this is what that's already envisioned to be. So I think once we do the work to make that work as described above (for `TransientNodeID`), it should fix the long-standing problems with `unique_rowid`. This also suggests we should keep `NodeID` and `SQLInstanceID` separate, as their semantics are different in important ways.

**Comment by bdarnell** [comment]
> Isn't that actually buggy for node IDs greater than 16 bits, meaning we might have unique ID collisions?

Yeah, we only *guarantee* uniqueness as long as no node IDs exceed 16 bits; beyond that it's probabilistic. It takes a pretty high rate of `unique_rowid` generation to produce a collision but it's possible.

I've been advocating against the use of `unique_rowid` since before it had that name (#4183) but people really like their more-or-less ordered 64-bit identifiers. And in theory you can just retry your transaction if you hit a collision on insert (but you have to be specifically prepared for this case; a unique constraint violation isn't normally retryable).

**Comment by andy-kimball** [comment]
@bdarnell, I think the concept of `SQLInstanceID` would solve these issues once and for all. `SQLInstanceID` is already part of the codebase since @tbg added it for multi-tenancy. So what remains is to implement the algorithm that guarantees that all live nodes in a logical cluster have a unique `SQLInstanceID`.

**Comment by knz** [comment]
This has been addressed by  #58317 and #58862
