### ISSUE TITLE
sql: bad query puts connection in invalid state

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5833]
`master` at time of writing, with standard `(id, balance)` bank table.

```
root@:26257> set database = bank;
SET
root@:26257> select * from (select balance from accounts where id = 3 union values(0)) as f;
+---------+
| balance |
+---------+
|       0 |
+---------+
root@:26257> select from (select balance from accounts where id = 3 union values(0)) as f;
pq: unexpected DataRow in simple query execution
root@:26257> select * from (select balance from accounts where id = 3 union values(0)) as f;
driver: bad connection
root@:26257>
```

I just checked and `select from accounts` already causes the same behavior. Continuing after `bad connection` works again, but the connection loses its database setting.

**Comment by petermattis** [comment]
The connection is reopened after it becomes bad, which is why the database setting is lost.

**Comment by RaduBerinde** [comment]
I'll take a look. I think `SELECT` with no targets should be a syntax error. We probably need to check for that earlier and/or make the grammar more restrictive.

**Comment by bdarnell** [comment]
This is one reason why we should discourage use of `SET DATABASE =` in favor of specifying the database on the URL or CLI (or using fully-qualified names). Our examples for `cockroach sql` should generally include the `--database`/`-d` flag. (note that in `psql` and `mysql` the `--database` flag is optional: a database may be given by the first positional parameter because this is so common)
