### ISSUE TITLE
kvserver: purging outdated replicas during migrations run into nil pointers

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58378]
**Describe the problem**

On this [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2551606) I see the following crash:

```
I201230 17:15:54.784810 1 util/stop/stopper.go:566 â‹® quiescing
W201230 17:15:54.784885 377 sql/sqlliveness/slinstance/slinstance.go:183 â‹® [n2] exiting heartbeat loop
F201230 17:15:54.770224 110793 kv/kvserver/replica_proposal.go:783 â‹® [n2,s2,r85/1:â€¹/Table/52/1/{49-50}â€º] not using applied state key in v21.1
goroutine 110793 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7fdd001, 0xe9a5d6, 0x203000, 0x452890)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000913000, 0x16558dfbdede14da, 0x4, 0x1b0c9, 0x72e7526, 0x1f, 0x30f, 0x0, 0xc001019040, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:270 +0xc52
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x54d7220, 0xc0038f7000, 0x1, 0x4, 0x48433ac, 0x24, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x1c5
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:804
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal(0xc002994800, 0x54d7220, 0xc0038f7000, 0xc003412830, 0x8, 0xc003b350e0, 0xc002476840, 0x0, 0xc003412800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:783 +0x690
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal(0xc002994800, 0x54d7220, 0xc0038f7000, 0xc003412830, 0x8, 0xc003b350e0, 0xc002476840, 0x484, 0x84818)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:816 +0x8e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose(0xc002994800, 0x54d7220, 0xc0038f7000, 0xc003b350e0, 0xc003fcc3f0, 0xc001b8d528, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:74 +0xf1
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc002994800, 0x54d7220, 0xc0038f7000, 0xc003b350e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:136 +0x73d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc002994800, 0x54d7220, 0xc0038f7000, 0xc003b350e0, 0x4e95740, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:352 +0x491
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithRangeID(0xc002994800, 0x54d7220, 0xc0038f7000, 0x55, 0xc003b350e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:97 +0x53d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:36
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2(0x54d7220, 0xc0038f7000)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_range_lease.go:402 +0x632
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000ec4240, 0x54d7220, 0xc0038f7000, 0xc0038eaa00, 0x35, 0xc000e8f500, 0xc002281b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xdd
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x11d
```

This code was introduced in https://github.com/cockroachdb/cockroach/pull/58088. I suppose it's possible that my PR caused this issue, but I doubt it. Another thing to note is that I don't think this cluster was upgraded or anything like that so I have to assume that there's some initialization invariant that code is not expecting.

**Comment by irfansharif** [comment]
```
I201230 17:15:54.760385 110364 kv/kvserver/replica_raftstorage.go:820 â‹® [n2,s2,r85/1:{-}] applying snapshot of type VIA_SNAPSHOT_QUEUE [id=â€¹1ca210deâ€º index=19]
I201230 17:15:54.770168 110793 1@kv/kvserver/replica_proposal.go:783 â‹® [n2,s2,r85/1:â€¹/Table/52/1/{49-50}â€º] the server is terminating due to a fatal error (see the DEV channel for details)
I201230 17:15:54.784698 110364 kv/kvserver/replica_raftstorage.go:841 â‹® [n2,s2,r85/1:â€¹/Table/52/1/{49-50}â€º] applied snapshot of type VIA_SNAPSHOT_QUEUE 
```

I think this assertion is a bit racey. I'm a bit surprised by the synchronization we're seeing here, but it's evidently possible for a replica to be evaluating proposal while concurrently applying a snapshot? In the failure above, r85 is being freshly created by the snapshot, which is still being applied. Part of that application process entails setting the right replica state from the incoming snapshot, which happens here:

https://github.com/cockroachdb/cockroach/blob/bdd0b93a9ae961b9fd6ef3b5dcb968ca82ca33c6/pkg/kv/kvserver/replica_raftstorage.go#L1001-L1005

Given this test starts of at master, `state.UsingAppliedStateKey` from the snapshot will always be true, which is supposed to make it's way to the replica's in-memory ReplicaState, and what the assertion below is checking for:

https://github.com/cockroachdb/cockroach/blob/bdd0b93a9ae961b9fd6ef3b5dcb968ca82ca33c6/pkg/kv/kvserver/replica_proposal.go#L772-L774

But because the evaluation seems to be happening concurrently with the snapshot application, it's possible for us to read from an uninitialized ReplicaState, which would then trip up this assertion.

**Comment by irfansharif** [comment]
I'm not sure if I'm missing some obvious synchronization that would disallow command evaluation from happening concurrently with the replica being instantiated by means of a snapshot. I think we might have to drop the assertion here.

**Comment by tbg** [comment]
Wow, that's... weird, right? First of all (and I'm sure you're aware, just writing this out anyway) there is nothing mixed-version going on. Everyone here ought to be using the applied state right off the bat. And it pretty much looks as though what you're seeing is true: we are evaluating a lease request on a replica that was just created in response to a snapshot, and the snapshot has not applied yet, meaning that the lease will evaluate against a completely blank disk state, while the in-memory state already has the descriptor (see the log tags on the fatal error).

But looking into this further, I'm not sure how this would work. We are setting the replica state here:

https://github.com/cockroachdb/cockroach/blob/ce4b23d2a19f32dda34a896e95be50deb197237b/pkg/kv/kvserver/replica_raftstorage.go#L987-L1010

but note that ingesting the actual data happens *before*. This would mean that there shouldn't be any way for a lease to make it to evaluation (wouldn't it bounce on the key check since it addresses to the [start key](https://github.com/cockroachdb/cockroach/blob/e1f9e34e8743b5c2b86f9cbda74bc537f2960c7e/pkg/kv/kvserver/replica_range_lease.go#L201-L203)?!) unless it can also observe the on-disk state.

So I'm still not sure what's going on here - the synchronization of req eval and snapshots seems lacking, but I can't use that to explain this *particular* problem. Can you? I don't think we'd ever send out a snapshot that has `!UsingAppliedStateKey`, right?

**Comment by ajwerner** [comment]
We set the entry in the store before we set the raft state:

https://github.com/cockroachdb/cockroach/blob/ce4b23d2a19f32dda34a896e95be50deb197237b/pkg/kv/kvserver/replica_raftstorage.go#L972

I believe that circumvents the key check. We should move some of this logic around so that requests can't find the replica until after it has been initialized.

**Comment by tbg** [comment]
Oh - good call. I'll take a look.

**Comment by tbg** [comment]
Let's say we fix this - are we still on thin ice? I believe fixing this is good enough to address the case of the very first snapshot, as an uninitialized replica (probably) won't ever try to evaluate anything. When a snapshot arrives on an existing replica, and that replica is evaluating some requests at the time (probably follower reads then), it does so under a timestamp that is covered by the lease including the uncertainty interval and has the MVCC history as observable by the commands immutable, so it won't matter whether the commands apply against the old or new state per se. But can there still be weird interleavings regarding the in-memory state? A command may read something from `r.mu.state` and sees the new state instead of the old. I wonder whether there are any instances of this, but even if not, it makes me somewhat uncomfortable that we don't have better boundaries there. Morally speaking, shouldn't the snapshot application grab an "everything latch"?

**Comment by tbg** [comment]
I poked at this for a while and it's not super easy to untangle. We'd really want to update the in-memory state of the replica before switching out the placeholder at the store at least for the first snapshot, but in general we do want to update the descriptor atomically with updating the store's key lookup index. Nothing that can't be fixed here, but it will take a little bit of elbow grease and since it's very tedious with 5pm brain, I will look at it again tomorrow.

**Comment by nvanbenschoten** [comment]
> Morally speaking, shouldn't the snapshot application grab an "everything latch"?

I think latching is a little too high-level for this kind of synchronization. Snapshots can block writes that are holding latches, so without some form of re-entrance, we'd run into all kinds of deadlocks if we tried to use them. This sounds more like the kind of issue that the `readOnlyCmdMu` is meant to solve - though in practice it does a pretty haphazard job: https://github.com/cockroachdb/cockroach/issues/46329.

The interactions between below Raft state changes and above Raft state observations are pretty subtle. In part, that's because we aren't explicit about when we're observing state above Raft (see https://github.com/cockroachdb/cockroach/issues/55461) so we end up needing to be very defensive about how we change things below Raft. For instance, snapshot ingestion goes through all kinds of hoops to make sure that the entire snapshot is ingested atomically to disk, even if that means that 4 of the 5 SSTs are tiny. If we had a cleaner policy about snapshotting an entire range's state during evaluation then we could add in some fine-grained synchronization around this snapshot and things would be a lot easier to think through.

Regarding this specific issue, it is surprising how late we set `r.mu.state` in `Replica.applySnapshot`. https://github.com/cockroachdb/cockroach/issues/58378#issuecomment-754069294 is thinking along the right lines.

**Comment by irfansharif** [comment]
Going to re-open this issue as a placeholder given we needed to revert the stop-gap in  #60429.

**Comment by tbg** [comment]
Starting to look at this now.

**Comment by tbg** [comment]
I ran the `kvserver` tests with this patch:

```diff
diff --git a/pkg/server/testserver.go b/pkg/server/testserver.go
index 082bf10558..b679fda253 100644
--- a/pkg/server/testserver.go
+++ b/pkg/server/testserver.go
@@ -456,7 +456,28 @@ func (ts *TestServer) NodeDialer() *nodedialer.Dialer {
 // completes.
 func (ts *TestServer) Start() error {
        ctx := context.Background()
-       return ts.Server.Start(ctx)
+       err := ts.Server.Start(ctx)
+       if err != nil {
+               return err
+       }
+       return ts.stopper.RunAsyncTask(ctx, "foo", func(ctx context.Context) {
+               for {
+                       select {
+                       case <-ts.stopper.ShouldQuiesce():
+                               return
+                       default:
+                       }
+                       if err := ts.Server.node.stores.VisitStores(func(s *kvserver.Store) error {
+                               s.VisitReplicas(func(repl *kvserver.Replica) (more bool) {
+                                       _ = repl.Version()
+                                       return true
+                               })
+                               return nil
+                       }); err != nil {
+                               panic(err)
+                       }
+               }
+       })
 }
 
 type dummyProtectedTSProvider struct {
```

To my dismay, it doesn't seem that easy to reproduce this bug.
