### ISSUE TITLE
ERROR: mysql parse error: syntax error at position 2 when importing

### ISSUE THREAD

**Issue by carbotaniuman** [cockroachdb/cockroach#59096]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

```
root@:26257/defaultdb> IMPORT MYSQLDUMP ('http://localhost:3000/a.sql');
ERROR: mysql parse error: syntax error at position 2
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Setup a local single-node instance
2. Download `https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/mysqldump/employees-full.sql.gz` and extract the file as `a.sql
3. Start a python server hosting that file with `python -m http.server 3000`
4. Run `IMPORT MYSQLDUMP ('http://localhost:3000/a.sql');` in cockroach SQL

**Expected behavior**
The SQL dump is imported.

**Environment:**
 - CockroachDB version: CCL v20.2.3 @ 2020/12/14 18:43:04 (go1.13.14)
 - Server OS: Windows
 - Client app: cockroach sql

**Comment by jc1203** [comment]
Hi guys, I'm new for the community and is trying to learn and help contribute.

Was curious about this issue, and did some digging.

This issue seems to be **Windows-only**. Please see my findings below.

Is it ok that I take on this issue? It is also fine if you guys prefer me taking on the "good first issue". I don't mind at all, and I'm just trying to find something to learn.

===============================================

Please see my findings here:

This seems to be a **Windows-only** issue.

- Tried the exact step using Ubuntu inside WSL2, and the import statement **succeeded**.
  - Built and ran linux version of cockroach server, sql client, as well as running python3 inside WSL2
- Tried the exact step inside Windows, and is **able to reproduce** the issue.
  - Built and ran **Windows** version of cockroach server, sql client, as well as running python3 inside **Windows**

Moreover, some findings when reproducing this issue on **Windows**:
- The python server showed
```
::1 - - [18/Jan/2021 16:33:11] "GET /%5Cb.sql HTTP/1.1" 301 -
::1 - - [18/Jan/2021 16:33:11] "GET /%5Cb.sql/ HTTP/1.1" 200 -
```
after I ran `IMPORT MYSQLDUMP ('http://localhost:3000/a.sql');`
- The input in `readMysqlCreateTable` function contained HTML instead of SQL.

It seems that Cockroach SQL client is adding extraneous backward slash for IMPORT statement on Windows platform?

**Comment by jc1203** [comment]
http_storage.go:339
`dest.Path = filepath.Join(dest.Path, file)` changed the forward slash in URL ('/a.sql') to backward slash ('\a.sql'), as this is running in Windows.

**Comment by shermanCRL** [comment]
Thanks for the report and troubleshooting! Indeed, it appears we should be using `path.Join` instead: https://stackoverflow.com/questions/34668012/combine-url-paths-with-path-join

We’d be happy to have your contribution, if interested: https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR

**Comment by jc1203** [comment]
Thanks @shermanCRL 

I will read through the document and prepare my PR.

**Comment by Muhammedismail** [comment]
Hi i do have the similar issue while importing a mysql dump file (one full database file :maria db) on cockroach  
USE db_prod; IMPORT MYSQLDUMP 'https://cloud.net/gn/pki/-/blob/branch-1.2/db_sa_integration_1.sql'

And the error is 
Error: mysql parse error: syntax error at position 2 

any body suggest me what leads to this error? or how to fix it
