### ISSUE TITLE
ts: truncate old time series data

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#5910]
Time series data will currently grow unbounded for the lifetime of the cluster - we need system in place to periodically truncate time series data older than a specified limit.

Previously, there were some ambitions to maintain time series "rollups" of historical data in our time series systems, but given that we are planning to add integration with external time series databases before 1.0, I believe it is acceptable to simply drop old data.

**Comment by seiflotfy** [comment]
what about partitioning a table into intervals, and have each interval have a TTL. Once that expires drop that partition. I am talking partitioning because deleting single entries might be more expensive also not sure about the vaccuum. Does this make sense?

**Comment by tschottdorf** [comment]
It would be nice to embed this into the standard framework of the GC queue and zone configs, but time series being inline values (i.e. not MVCC) means we can't look at one and know their age, at least not without decoding the key (a whacky-ish idea would be to encode the time slot as the MVCC timestamp, but then we might have too many versions of single keys which we can't split).

If we want to use the GC queue (and I intuitively would prefer that over building another special-cased system), we could add a (n optional) `TimeseriesTTL` value to `config.GCPolicy` which would govern the lifetime of timeseries keys (the GC queue then would special-case keys which start with `keys.TimeseriesPrefix` and apply this timeout).
The upshot is that we could give different lifetimes to different time series easily via zones, and that there wouldn't be any new queues/infrastructure.

This won't be the most performant way to dispose of time series data right off the bat, but it can be made pretty performant if it should ever matter (for example, instead of naively packing all of the gc'able time series keys into a GCRequest individually, we could extend GCRequest to also take a key range of inline keys to GC which would then be hit with a `DeleteRange` when the `GCRequest` executes).

**Comment by bdarnell** [comment]
Truncating old timeseries data (at least as a one-off migration at upgrade, although we might as well solve the more general problem at the same time) will be a prerequisite for turning the consistency checker on by default. Any clusters that ever ran a version predating the partial merge fix will have inconsistent data in their history.

**Comment by tschottdorf** [comment]
We can run such a truncation through the GC queue in offline mode as well.

On Fri, Apr 8, 2016, 00:35 Ben Darnell <notifications@github.com> wrote:

> Truncating old timeseries data (at least as a one-off migration at
> upgrade, although we might as well solve the more general problem at the
> same time) will be a prerequisite for turning the consistency checker on by
> default. Any clusters that ever ran a version predating the partial merge
> fix will have inconsistent data in their history.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5910#issuecomment-207121589>
>
-- 

-- Tobias
