### ISSUE TITLE
sql: repair functions should be more locked down than just admin

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#59153]
The new functions `crdb_internal.unsafe_upsert_descriptor` and its friends have power to unleash real havoc on a database. Admin is granted for a variety of reasons. In the initial revision of that work, the access was locked down to just the `root` user. This special principle was deemed unacceptable. We should add some other role or or something to not have to expose access to these disruptive operations to all admin users.

cc @knz

**Comment by knz** [comment]
Something that @dt and I were considering:

Suppose for an instant that we were living in a world where every cluster was running multi-tenant; where every cockroachdb node was exposing the tenant-level SQL server to client apps.

In that world, would it make sense to make the `unsafe_...` functions accessible from the system tenant only, and have them operate on tenants given as argument? This way the  non-system tenants would have no way whatsoever to shoot themselves in the foot, even when a SQL user has `admin` privileges.

**Comment by ajwerner** [comment]
I don't hate that idea. I do, on some level, think that I can imagine cases where I want to experiment with mucking around with descriptors in a tenant. Tenant are no less exposed to corruption bugs. Getting a handle to sql shell inside a tenant seems likely to be much easier than getting one to the system tenant empowered to muck with that tenant, at least in the short term. On some level, I feel a heck of a lot better about users mucking around with descriptors inside of tenant than in the system tenant. I think these two ideas are complementary but distinct in their value.

**Comment by knz** [comment]
Ok sure we can distinguish

however my comment was in reaction to the subtext of your original description:

> We should add some other role or or something to not have to expose access to these disruptive operations to all admin users.

The `admin` role *is* our superuser role and is, throughout the entire code base, the condition for disabling authorization checks. `root` is merely a member to this role.

 There's never been a good reason to insert an intermediate level of authorization between `admin` and superuser, and even if we had such a reason it would be quite an annoying amount of work.

So I'd generally want to avoid thinking in that direction.

The next possible practical approach/proposal would be to create a new non-`admin` role in every new cluster (and every CC cluster) and state that every new user gets assigned that role; so that accessing the `admin` role becomes properly difficult.

The technical changes inside CockroachDB to achieve that are more tractable than your proposal, however then it becomes a huge docs project, because we've thoroughly capitalized on the `admin` role throughout all our guides, tutorials and reference docs.

So really neither approach strikes me as particularly agreeable, at a high level.

Hence my desire to take this sideways, and either:

- play the multi-tenancy card, where we have a new degree of movement which isn't constrained by docs and previous usage yet; or
- make the problematic feature (the `unsafe_` functions here) disabled by default, with no way to enable them from "within SQL"; for example only make them available when an env var is set.

**Comment by ajwerner** [comment]
Thanks for the details. I better understand now.

I think this proposal needs to fit into a broader vision for how tenants fit into dedicated clusters. 

If we can get all user data scoped to a tenant key space and only provide tenant access while retaining distsql and dedicated access to the nodes of the system tenant then this becomes a wonderful answer.

**Comment by dt** [comment]
I'm 👎 on "no way to enable from within SQL" -- we reach for these tools when things are going wrong, and that's a bad time to force a node restart to pass an env var or cli param. 

Maybe a feature flag cluster setting (features.unsafe_admin_tools.enabled or something)? Then you have a record that unsafe features were enabled in the event log at least. I'm also very 👍 on the "everybody runs as a tenant, just sometimes as the sole tenant of their own cluster" approach where really scary, major config changes are done in the system tenant, by establishing a separate "admin" SQL session on the admin port with the admin cert, etc -- none of which you'd use in day to day DDLs, user mgmt, etc, i.e. clearly a "break glass in emergencies" only situation.

**Comment by knz** [comment]
Yes we can envision a cluster setting as an intermediate step.

**Comment by ajwerner** [comment]
Closing this with a feeling that we need to support the user story to lock down admin more than today it tends to be locked down.
