### ISSUE TITLE
kv/intentresolver: txn record GC allows unbounded concurrency

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#59246]
See https://github.com/cockroachdb/cockroach/issues/58298#issuecomment-755905931. In that comment, we noticed that `(*IntentResolver).gcTxnRecord` allows for unbounded concurrency through the `gcBatcher` object. We shouldn't allow this, as this has the potential to cause an unavailable range to balloon into an OOM.

The tricky part here is that we want to delay txn record GC for such a long time, so it's difficult to do something semi-synchronous like we do in other places. One approach towards fixing this is to re-work the requestbatcher API to support a callback interface, so that we don't need to maintain goroutine stacks and hold a semaphore during this 1s (`defaultGCBatchWait`) wait. This is what the following prototype did, to moderate success: https://github.com/nvanbenschoten/cockroach/commit/2f788e3f9abd4ea18f2d121864b703d4978c7c5e.

Jira issue: CRDB-3311

**Comment by lunevalex** [comment]
Discussed this with @nvanbenschoten offline, and wanted to capture the outcome here for future reference. 

The unbounded concurrency comes from txn record clean up, then intent cleanup has an upper concurrency limit, so we don't need to worry about it here. We always want to clean up intents aggressively, because as other transactions bump into old intents, it slows down processing. There is no way to get to orphaned txn records, so the main downside is if they dont get cleaned up, we have extra garbage lying around until the gc_queue cleans them up. This means we can take a more lax approach to this clean up. We propose to make the following two changes add a concurrency limit to GCBatcher for txn record clean up, if the limit is exceeded just drop the cleanup requests on the floor. If a cleanup cannot be performed because the range goes unavailable or for any other reason, timeout and drop the request on the floor.
