### ISSUE TITLE
sql: support "time-travel" queries

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5963]
The desire to perform queries on historical versions of a table has come up in discussions several times recently. We could either allow a transaction-wide timestamp to be set or add syntax for querying a table at a timestamp. The latter approach would be more flexible as we could query one table at a timestamp and join with another table at the current time. For syntax, I propose we extend the existing index-hints syntax. This might look something like:

```
SELECT * FROM t@{TIMESTAMP=<timestamp>}
```

The KV scan operation would need to be enhanced to take a timestamp that differs from the transaction timestamp. I'm not sure what the ramifications of this are. Presumably this wouldn't affect the timestamp cache. Are there other concerns

Time-travel queries would also have to be aware of schema changes. The current proposal for backfilling schema changes (#5817) would cause index data to have a different timestamp than the associated row data. So time-travel queries would need to be careful to disable usage of index depending on when it was created.

We would also likely want to enhance the zone config GC policies. Currently the only policy is time based (default 1 day). This could cause surprises because an overwritten key would have the old version deleted after a day causing the time-travel query to not accurately represent the table at the specified time.

**Comment by tschottdorf** [comment]
> We would also likely want to enhance the zone config GC policies. Currently the only policy is time based (default 1 day). This could cause surprises because an overwritten key would have the old version deleted after a day causing the time-travel query to not accurately represent the table at the specified time.

Additionally, the Replica should return an error when the timestamp can't be served any more according to the last GC cycle.

> The KV scan operation would need to be enhanced to take a timestamp that differs from the transaction timestamp. I'm not sure what the ramifications of this are. Presumably this wouldn't affect the timestamp cache. Are there other concerns

Not on the replica level, but since everything in SQL is inside of a KV transaction (and thus pinned to a timestamp), we have to figure out the way to get that behavior. One way is to have `sql` run historical queries inside of their own transaction at a past timestamp (i.e. a join of a table with a SELECT from the past would have to run two individual transactions - more state to manage, but since we only need one-shot transactions, it could be manageable). The other way is somehow having this fall out of inconsistent SQL (so even more involved)

The more straightforward thing is certainly to not allow this mix-and-match behavior and instead have

```
BEGIN TRANSACTION READONLY(123125125125.125125); -- not great syntax
-- read stuff
COMMIT
```

which would map onto what we have with relative ease. Maybe that's enough?

The `SELECT t@{...}` syntax could also create confusion when used from inside of a transaction.

**Comment by bdarnell** [comment]
Yeah, I'd rather start with a single transaction timestamp unless there's clear demand for mixing different timestamps in one transaction. That just seems like a lot more plumbing work and will complicate distributed sql. 

As a precedent for syntax, mysql supports `SET TIMESTAMP=1460392519` (this is used in the replication protocol so that secondaries use a timestamp that was given to them by the primary instead of their local clock).

**Comment by tschottdorf** [comment]
We should be dealing in cluster_timestamp, correct?

Also, on a slight tangent, for causality tokens we might need a similar
syntax:

BEGIN TRANSACTION;
-- do stuff
SELECT CLUSTER_TIMESTAMP() -- our causality token for this op
COMMIT;

BEGIN TRANSACTION;
SET CAUSALITY_TOKEN <from above> -- used as min-timestamp for next
operation (ened some protection against injection of high timestamps though)
...
COMMIT;

On Mon, Apr 11, 2016 at 12:39 PM Ben Darnell <notifications@github.com>
wrote:

> Yeah, I'd rather start with a single transaction timestamp unless there's
> clear demand for mixing different timestamps in one transaction. That just
> seems like a lot more plumbing work and will complicate distributed sql.
>
> As a precedent for syntax, mysql supports SET TIMESTAMP=1460392519 (this
> is used in the replication protocol so that secondaries use a timestamp
> that was given to them by the primary instead of their local clock).
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5963#issuecomment-208439246>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
Hmm, good point about using the HLC instead of a wall time. But how would a user get an HLC value? My understanding of the use cases for this feature are for coarse-grained wall timestamps; people want to ask for the data as it existed at noon yesterday, not a precise sub-second instant. (although maybe we could make this useful if there were a way to query for the list of HLC timestamps at which a given row was modified, so the user could select a timestamp from that)

**Comment by petermattis** [comment]
@spencerkimball Care to weigh in on the alternatives? You have the most context about the use cases for this feature.

**Comment by spencerkimball** [comment]
There is already concrete demand for mixing timestamps per table in a joined SQL query. The session-only timestamp works for running repeatable queries at historical timestamps. But the mixed timestamps is necessary for testing historical scenarios with different foundational assumptions. Both of these use cases have been requested.

@bdarnell we're definitely going to need HLC or else you won't be able to precisely identify data as it existed after a specific commit. Seems like we're going to need to be able to return the HLC commit timestamp (this is just the causality token, which we need for ordering consecutive, causally-related transactions in any case). That could be stored and reused for historical queries. Further, I think we will need a way to access all of the historical values for a specific row / column with associated HLC timestamps.

**Comment by spencerkimball** [comment]
Also, @petermattis I've said this before; I think we should allow a bulk-insert mode at the KV layer which allows the backfiller to rewrite indexes at appropriate historical timestamp(s) and which can back fill underneath any new entries being written at current timestamps while the index is still in write-only mode. That would help ameliorate the problems of time travel with older indexes.

**Comment by petermattis** [comment]
@spencerkimball Both @bdarnell and @tschottdorf feel put-at-timestamp (needed to write/rewrite an index at appropriate historical timestamps) is difficult. See the discussion on #5817.

**Comment by tschottdorf** [comment]
I'm not opposed to the idea in general (see #5981), but it needs to be
properly developed and I feel that rushing it in now (and blocking stuff)
because there's something that looks somewhat like a possible use case for
it is ultimately counter-productive. My suggestion would be to hash out the
actual semantics which are needed for bulk loading while keeping the
backfill use case (which is a little more involved due to the need to
accept some existing values) in mind. If we develop a proper operation, it
won't be hard to migrate the backfilling over to benefit from it. This new
operation is something that would merit a short draft (not necessarily an
RFC) to make sure it covers all the bases.

On Mon, Apr 11, 2016 at 4:57 PM Peter Mattis <notifications@github.com>
wrote:

> @spencerkimball <https://github.com/spencerkimball> Both @bdarnell
> <https://github.com/bdarnell> and @tschottdorf
> <https://github.com/tschottdorf> feel put-at-timestamp (needed to
> write/rewrite an index at appropriate historical timestamps) is difficult.
> See the discussion on #5817
> <https://github.com/cockroachdb/cockroach/issues/5817>.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5963#issuecomment-208557761>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Hope I didn't give the impression that this feature is being rushed in. I specifically made this an issue and not an RFC because it isn't well developed. We've heard feedback that such a feature would be useful, but the actual use cases need fleshing out.

**Comment by tschottdorf** [comment]
No worries, the "rushing in" referred to the at one time proposed
introduction of a specialized bulk put operation in the context of the
index backfill issue (an operation which we will need, but which hasn't
been discussed properly).

On Thu, Apr 14, 2016 at 10:30 AM Peter Mattis <notifications@github.com>
wrote:

> Hope I didn't give the impression that this feature is being rushed in. I
> specifically made this an issue and not an RFC because it isn't well
> developed. We've heard feedback that such a feature would be useful, but
> the actual use cases need fleshing out.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5963#issuecomment-209970796>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
We need to make a decision about whether we're going to support time travel queries in the near future. It has implications for other features including dump/restore (#6058) and table alterations (#5817). It is more complicated to implement these features in a way that will be compatible with the future introduction of MVCC-based time travel. We need to decide whether we're going to start paying the price for this feature or allow other development to proceed unhindered (which will make it more expensive to introduce time travel later, when and if we do).

I vote against implementing time travel for the foreseeable future. We have our hands full implementing the features we're already committed to. Furthermore, I have my doubts that the MVCC system is even a good way to implement time travel. We cannot support more than 64MB (i.e. the range split size) of values of a single key without changes to the way splits work, and storing more mvcc history makes the live data more sparse and increases the number of ranges that non-time-travel scans will have to touch. I think that introducing hidden columns to time-travel-enabled tables (which can still use transaction HLC timestamps for sequencing) will be a better solution and does not require us to build timestamp-preservation into all other parts of the system (beyond what is already needed as an implementation detail of the transaction system).

**Comment by petermattis** [comment]
@bdarnell Can you expand on the "introducing hidden columns to time-travel-enabled table"idea? Seems like you would need the timestamp appended to the primary key, otherwise new values would overwrite old values for a row. On reads you'd need to filter out the non-latest rows which I don't see how to do using standard SQL expressions (perhaps window functions could help). If I squint, this seems a lot like the MVCC timestamps. 

I'm also concerned about supporting time-travel queries due to the interaction with other features, yet we've heard demand for time-travel queries on a number of occasions. I'm undecided on whether we should implement it.

**Comment by tschottdorf** [comment]
I agree with @bdarnell that using MVCC for these old versions is the wrong
approach for all the reasons he mentioned. Unfortunately, time travel
queries become much more involved once historical data is kept separately
from MVCC. I have no clear idea of what a good solution would look like,
and even though it's come up repeatedly, I haven't seen evidence that it's
something we must support.
There may be other requirements as well (having different replication/zone
settings for these archived data).

On Sat, Apr 16, 2016 at 10:41 AM Peter Mattis <notifications@github.com>
wrote:

> @bdarnell <https://github.com/bdarnell> Can you expand on the
> "introducing hidden columns to time-travel-enabled table"idea? Seems like
> you would need the timestamp appended to the primary key, otherwise new
> values would overwrite old values for a row. On reads you'd need to filter
> out the non-latest rows which I don't see how to do using standard SQL
> expressions (perhaps window functions could help). If I squint, this seems
> a lot like the MVCC timestamps.
>
> I'm also concerned about supporting time-travel queries due to the
> interaction with other features, yet we've heard demand for time-travel
> queries on a number of occasions. I'm undecided on whether we should
> implement it.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5963#issuecomment-210830919>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
@petermattis Yes, the timestamp field would need to be appended to the primary key and all unique indexes (maybe the non-unique ones too for symmetry). This is still pretty hand-wavy but here's what I'm thinking in a little more detail:

* Rewrite any time-travel-enabled `CREATE TABLE` statements to create two tables: one as written, and one with the timestamp field added to the table and all indexes.
  * Optionally, the table as written could be omitted and the timestamp-enabled table used for all queries. This would speed up writes at the expense of non-time-travel reads
* All writes are rewritten to update both tables
* Reads without time travel run against the regular table
* Reads with time travel in the very recent past (less than the maximum lifetime of a write transaction) use MVCC on the regular table
* Reads with time travel in the more distant past are rewritten to refer to the history table.

The read rewrites are the trickiest part: Lookups for a single row by primary key are straightforward; you just add "AND timestamp <= $1 LIMIT 1" to the where clause. Multiple rows are trickier; you need a `GROUP BY real_pk` and some logic to select the one with the highest timestamp (which now that I think about it is pretty difficult to express in SQL). Index joins will need to make sure that the primary row that is selected is the current one at the selected time.

So this does seem complicated and there are a lot of unresolved questions. But the ones involved in using MVCC for time travel seem even more insurmountable. 

We need to do some research on how other systems handle this: if it's possible by rewriting queries, then surely there must be ORMs or other frameworks to do it in a database-independent way. (and if no such framework exists then that may be a clue that it's not actually feasible to retrofit at the SQL level).

* [Temporal features](https://en.wikipedia.org/wiki/Temporal_database) were added to the SQL standard in SQL 11
* MS SQL Server 2016 has temporal features with some [interesting limitations](https://devjef.wordpress.com/2015/07/13/time-traveling-with-sql-server-2016-temporal-tables/): you cannot change the schema of a versioned table without turning off versioning and losing history
* Postgres had time-travel features in the past but [removed them](http://www.postgresql.org/docs/6.3/static/c0503.htm). There's a [newer extension](https://github.com/arkhipov/temporal_tables) using range types for the timestamp column.

**Comment by mjibson** [comment]
The time-travel-enabled `CREATE TABLE` idea also isn't helpful to the backup/restore case, since that needs to work with all tables.

Is there some other solution that could work for recent time travel only? I can't think of one that doesn't have all of the same implications as a general time travel solution, though. A long-running backup of a large database would eventually be time traveling out of the "recent" definition anyway.

**Comment by bdarnell** [comment]
I'm fine with MVCC-based time travel for the duration that would be necessary to complete a backup; I just wouldn't want to tell users that you keep MVCC data for years and expect it to be preserved across backups/restores, etc.

**Comment by mjibson** [comment]
Ok. Can we solidify around a proposal to add just that feature as a first pass? I'm in favor of the `BEGIN TRANSACTION READONLY(timestamp)` syntax. Or `BEGIN TRANSACTION AT timestamp` maybe.

**Comment by bdarnell** [comment]
I think modifying the `BEGIN` statement is going to be difficult to use in practice. For example, the Go `pq` driver always sends a hard-coded ["BEGIN"](https://github.com/lib/pq/blob/3cd0097429be7d611bb644ef85b42bfb102ceea4/conn.go#L513). I think it's probably better to make it a `SET` statement like priority or isolation. Or we we could implement the SQL 2011 syntax, which is apparently `AS OF SYSTEM TIME $1` placed after the table name in the `FROM` clause.

**Comment by tschottdorf** [comment]
From an implementation point of view, it's be desirable to know any user-supplied timestamp before starting a transaction (at least for now) since that avoids changing the transaction timestamp of operations that may already have issues commands. Of course we'll have to break with this as required, but perhaps for now the `SQL2011` syntax @bdarnell points out above is a good starting point, where we allow it only outside of transactions (since such a query does not benefit from a transaction anyway, and support for it inside of one can be retrofitted when the machinery gets more complex).
That is, the suggested starting point is supporting

`SELECT ... AS OF SYSTEM TIME $1` limited to implicit SQL transactions.

That's "easy" to implement, useful, (apparently) standard SQL, and has potential to generalize in a meaningful way.

**Comment by bdarnell** [comment]
Can this be closed now? @mjibson
