### ISSUE TITLE
cli: Don't log to stderr by default

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#5964]
When we discussed showing log files in the web UI, everyone in the room recoiled from the idea of showing our raw (or lightly-filtered) logs that prominently. And yet that's exactly what we do when you start a node in the terminal. This gives a bad first impression (most notably with the "no replication targets available" message, although I'm sure there are others). 

Stderr is a part of the app's UI and we should treat it as such. Instead of routing our internal log messages there, the messages that show up on stderr by default should be those from the admin UI's events tab, which are designed for human consumption.

More radically, if stderr is a tty and not just a pipe or file, we could do something more useful than just a log of messages. We could start the SQL shell, or maybe have a curses-based display of some information from the web UI.

**Comment by petermattis** [comment]
I'm in full agreement that stderr is part of the app's UI. The few messages that we do display on stderr are insufficient to debug anything. I sometimes run with `--logtostderr` to get the full details. I'd be fine with turning off logging to stderr by default.

I think opening a SQL shell if stderr is a tty could be dangerous. What happens if you exit the shell? Or ctrl-c? Similarly for a curses-based display. Such a display might be useful, but I'd keep it separate from the `start` command.
