### ISSUE TITLE
sql: extend crdb_internal.cluster_settings to indicate whether a setting was explicitly customized

### ISSUE THREAD

**Issue by nickelnickel** [cockroachdb/cockroach#59673]
Digging around I found that system.settings shows cluster settings that have been modified and not explicitly set back to default with "SET CLUSTER SETTING <foo>=DEFAULT;". It would be great to have this in the debug.zip so we can know which settings in a cluster have been changed, and when, so that they can be considered for any cluster issues.

Note: If a setting is changed to the same value as the default, but not with "=DEFAULT", it will show in this table. If there is a way to just output the non-default values, that would be even better, but the above is more than sufficient and uses existing bits.

**Comment by knz** [comment]
This data is already available in debug zips under `crdb_internal.cluster_settings.txt`. What else is needed?

**Comment by RoachietheSupportRoach** [comment]
That table gives a view of what is non-default / what has been set explicitly. I wasn't able to figure out a clean way to query this otherwise. crdb_internal.cluster_settings.txt shows all of the cluster settings but doesn't note if they're set to the default or not.

**Comment by nickelnickel** [comment]
That table gives a view of what is non-default / what has been set explicitly. I wasn't able to figure out a clean way to query this otherwise. `crdb_internal.cluster_settings.txt` shows all of the cluster settings but doesn't note if they're set to the default or not.

**Comment by knz** [comment]
We don't have a mechanism inside cockroachdb to determine via SQL whether a setting was changed, so there's no information about that that `debug zip` could pick up.

I will relabel the issue accordingly.

**Comment by knz** [comment]
@dt see the new title of this issue for context. 

What is the internal API that the SQL code can use to determine whether a setting has a stored value, i.e. is not reporting defaults?

**Comment by knz** [comment]
cc @rafiss @vy-ton  for visibility

**Comment by dt** [comment]
`crdb_internal.cluster_settings` iterates the in-memory cached values -- same as code that checks the setting -- which does not distinguish between a default vs overridden setting. We'd need to add a new `[MaxSettings]int64` array of slots for atomic bools to track that if we wanted the fully local, in-memory setting to be able to reflect if it was overridden or not.

In SQL, you can easily look at just the set of overridden settings by doing `select * from system.settings` -- indeed, that table might more accurately be named `system.explicitly_set_settings` or `system.overridden_settings`. If we really wanted `crdb_internal.cluster_settings` to include an annotation for if it is explicitly set or is just default, we could rename `crdb_internal.cluster_settings` to `crdb_internal.cluster_setting_values` or something and then add a new view named `crdb_internal.cluster_settings` that does a left outer join on it plus and the real `system.settings` to see if the latter is is non-null.

Alternatively, if we're okay with settings that are _explicitly set to their default value_ showing up as default=true rather than false/overridden, we could pretty easily just ask the in-memory setting if its current value (which may or may not be from reading override) is _equal to_ its default value. That could be done purely from the in-memory values, just like the current table, without needing to go to kv to read the override table.

P.S. in addition to `SET CLUSTER SETTING ... = DEFAULT` and `SET ... TO DEFAULT`, there's also `RESET CLUSTER SETT...`. As you might have guessed from the above pedantry about the name of `system.settings`, all of these are just shorthand for `DELETE FROM system.settings` .

**Comment by dt** [comment]
@knz Actually, reading back to the original motivation here, I think debug.zip should probably just be dumping `system.settings` _instead of_ `crdb_internal.cluster_settings`. For debugging, we only need to know the overridden settings -- everything else is already known from the code, and is just bloating the debug zip (like all the help text).

**Comment by knz** [comment]
This is a SQL observability issue.

cc @maryliag for re-triage.

**Comment by bobvawter** [comment]
Yes, please.  I have been scratching my head over a cluster that turned out to have automatic stats disabled; it would be great if the `env.sql` in a statement diagnostic were to also only show non-default settings.

**Comment by kevin-v-ngo** [comment]
Hi @thtruo and @knz, from SQL Obs triage we were wondering if this would be best owned by the Obs team as it is providing  general observability into cluster settings (whether through SQL or some other interface). Thoughts?

**Comment by dt** [comment]
I'm pretty sure this is just a couple character diff, replacing `crdb_internal.cluster_settings` with `system.settings` on this line:
https://github.com/cockroachdb/cockroach/blob/dfc6a8643ed1dbe8a38b224e60ea370ba0238cb5/pkg/cli/zip_cluster_wide.go#L79

**Comment by ajwerner** [comment]
Let's just grab both? `system.settings` will be smaller.

**Comment by dt** [comment]
sure, I guess. IMO crdb_internal.cluster_settings with its included defaults is just noise, but collect-eveything-first, ignore-noise-later seems easy enough too so either way.

**Comment by thtruo** [comment]
cc @nkodali @dhartunian in response to Kevin's question, what are your thoughts on Observability Infrastructure taking point on this change?

**Comment by knz** [comment]
there's an ongoing convo about the ownership of cluster settigns. Not clear that obs infra is supposed to own this?

@mwang1026 might have an opinion

**Comment by ajwerner** [comment]
Put up https://github.com/cockroachdb/cockroach/pull/70498 because it seemed about as easy as all the discussion about which team should put this on their roadmap.
