### ISSUE TITLE
storage: support debug tools on encrypted stores

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#59771]
If a store is using ccl encryption-at-rest, the `debug pebble` commands cannot be used to inspect the store's files because they do not run on the encrypted FS.

I think we just need to initialize and propagate the appropriate `vfs.FS`. We will need to update pebble tools package to accept a `vfs.FS`.

**Comment by petermattis** [comment]
The Pebble tools already know how to use a `vfs.FS`, but we don't currently expose this configuration. See `pebble/tool.T.setFS` (this is used by the tool tests). Rather than exposing `setFS`, I think we should add a `pebble/tool.FS` option that can be passed to `pebble/tool.New` similar to the other options.

**Comment by jbowens** [comment]
Peter added the option to Pebble in cockroachdb/pebble#1105.

Eyeing finishing this up as a storage starter project.
