### ISSUE TITLE
ui: display warning when running fewer than 3 nodes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5978]
A 1 or 2 node cluster cannot survive node failure. We should display a prominent warning in the admin UI next to the node count when running a cluster with too few nodes.

**Comment by tschottdorf** [comment]
Are you sure we want to put big warnings on a ui of someone who
intentionally wants to run single-node? Why not prominently warn if there
are under-replicated ranges? That's the case by default unless you run
three nodes.

On Mon, Apr 11, 2016 at 10:33 AM Peter Mattis <notifications@github.com>
wrote:

> A 1 or 2 node cluster cannot survive node failure. We should display a
> prominent warning in the admin UI next to the node count when running a
> cluster with too few nodes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5978>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
True, we should be slightly more intelligent than always putting the warning up. For example, we could make the warning a small indicator until a second node is added to the cluster.

**Comment by JackKrupansky** [comment]
How about more of a "prominent information display" than a warning per se. Same thing, but allows for the prospect that the user has intentions that may not be inconsistent with full HA, but sufficient for specific application needs. For example, they may have a cluster for write-once, read-only data, where they will simply regenerate the full cluster if a rare node failure does occur, or queue and batch write if nodes have failed. Or they may not require HA and simply want replication to handle greater load rather than fault-tolerance per se. Or... whatever crazy requirements they have.

So, how about an "Availability" indicator with a level ala password strength: Low, Medium, High. High being full HA (RF >= 3), Medium being data is replicated but cannot achieve quorum on single-node failure, and Low meaning no replication. Or, maybe just Weak and Strong (binary.) You probably can't say None, since the cluster is indeed fully available when all nodes are available. Also, in truth, it  is ranges that have availability per se, node nodes, or even the cluster per se. You could have an indicator of what percentage of the cluster ranges have HA, or have a None, Mixed, Strong indicator based on the fraction of ranges that have fully met their quota for replication.

I'm continually amazed over in Cassandra land by how many people are running production clusters with one or two nodes. We always immediately remind them that they won't have HA with RF < 3, but they always have some excuse. Commonly, they are manually managing the cluster, so on a failure they will explicitly decide whether to restore a backup or decide whether they have split brain and manually create a new node and repair from the other node. Or something, other than have the cluster itself intelligently do the right thing, feeling that they are more in control and feel more comfortable with a smaller hardware budget. Go figure.
