### ISSUE TITLE
backupccl: multi-region cluster restore can result in unachievable zone configurations

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59984]
The new multi-region abstractions rely on cluster regions. If a user attempts to restore a multi-region cluster with the new abstractions to a different cluster with different cluster regions, it will succeed, but the user will not be able to tell that zone constraints are in violation and it will offer unpredictable latency based on replica placement (replicas first attempt to respect zone configurations and if they cannot then they are placed on the cluster based on diversity heuristics. 

Epic CRDB-10350

Jira issue: CRDB-3208

**Comment by adityamaru** [comment]
Fleshing this out a little more:

A cluster restore is a destructive operation that replaces the zone configs in the restoring cluster with those that are part of the backup. As a result of this, if a restore was to be performed into a cluster with a node topology, or locality tags etc. that made the backed up zone configs unachievable, this would cause problems. More concretely, the allocator would be unable to correctly up-replicate or rebalance the clusters ranges resulting in degraded performance.

To begin with there are two options that could be explored:

1. Fail the RESTORE after performing some zone config validation checks.

We might be able to reuse some of the validation that we perform on `ALTER...CONFIGURE ZONE` to sanity check what we are restoring from the backup. If these validations fail, we can fail the restore. This however makes that backup unusable and prevents a user from getting access to their data.

2. Add an option to RESTORE to exclude restoring zone configs.

Following from 1), if we want to enable a user to restore their cluster independent of the node topology, we could add an option to not exclude restoring the zone config system table. This comes with its own downsides. To name a few:

- Restored global tables will no longer remain global tables.
- Regional By Row tables will be restored with partitions that do not have any effect, since we did not restore the corresponding zcfg from the backup.

A user would thus have to perform several post restore operations to once again take advantage of the MR capabilities.

Cluster restore has historically tried to remain true to its job description of bringing back your cluster to the same state as it was in when it was backed up. In this case, inserting invalid zone configs could brick the cluster and be worse than not restoring zone configs at all.

**Comment by awoods187** [comment]
I like the idea of failing early if zone configurations can't be met to alert and warn customer to take action to adjust the cluster to meet the zone configurations (can the error include the zone configs that can't be met?). I also like the idea of providing an override via not restoring zone configs (would it be possible to restore the ones that can be achieved and reject the ones that cannot?) in the event that a customer needs an urgent restore even with a suboptimal secondary environment.
