### ISSUE TITLE
sql: poor error message for failed schema changes

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#60491]
When adding a unique index that fails because of a duplicate key, usually we get a nice error like this:
```
ERROR: failed to ingest index entries during backfill: duplicate key value violates unique constraint "idx"
SQLSTATE: 23505
DETAIL: Key (a)=(1) already exists.
CONSTRAINT: idx
```

But sometimes we get a very poor error: `4 entries, expected 5 violates unique constraint ..`. The "X entries, expected Y" part means nothing to everyone who is not intimately familiar with the implementation of the schema changes; we should remove it from the message.

**Comment by jordanlewis** [comment]
@lucy-zhang suspects the bad message is caused by backfills where duplicate keys end up in different SSTs. This bad message comes from the post-ingest validation, which just counts the keys in the table vs the resultant index, whereas the good message comes from an in-memory de-duplication pass when forming the SSTs.

We could improve the message pretty easily - we could make the error message the same as in the good case, without printing out the duplicate key. Printing out the duplicate key is harder, right now we'd have to do a big join query which could be prohibitively expensive.

**Comment by jordanlewis** [comment]
@dt, were you looking at something related to this and an SSTable ingestion flag? DisallowShadowing?

**Comment by jordanlewis** [comment]
For now, let's just make the error message the same as in the good case - but without the detail of the duplicate key.

**Comment by dt** [comment]
yeah, `DisallowShadowing` would yield an error earlier, when we go to ingest the sst which would contain a duplicate key (and thus not increase the number of entries as expected, leading to the later mismatched count during validation). On its own that might be nice in that it'd fail faster, but the error itself isn't _much_ better than the bad error today, since it currently doesn't return the offending key in any sort of structured or user-readable way:
```
	err := &Error{msg: existingIter.Key().Key.String()}
	return enginepb.MVCCStats{}, errors.Wrap(err, "ingested key collides with an existing one")
```

That said, setting `DisallowShadowing` also makes SST ingestion more expensive, particularly ingestion of data where the keys in the new SST interleave with existing keys which causes the iteration of the existing keys to not skip over the span but rather step though it slowly. This means setting `DisallowShadowing` for ingesting new, in-order PK data is usually cheap, but setting it for writing out-of-order data like we see during an index backfill would result in iterating over the whole index many more times, in aggregate, than if we just wait to do it once at the end. Is the join _that_ bad? like, sure, it's expensive, but if we just *wrote* O(table) keys how bad could reading O(table) keys really be?
