### ISSUE TITLE
backupccl: cluster backup has bad interaction with IMPORT INTO

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#60500]
Cluster backups do not interact well with running IMPORT INTO jobs.

When taken without revision_history, backup takes a snapshot of the data at a given time. If an IMPORT INTO job is running, the data in that table is not accessible to the user. So, a cluster backup includes the spans that are being imported into the OFFLINE tables. However, at restore time this causes an issue: We only restore a snapshot of the data, and not its MVCC history. This makes it impossible for IMPORT INTO to properly revert in the case of a failure (and so the revert will fail).

**Note: The data is restored at the timestamps as they were in the backed up cluster.**

Possible solutions:

Short term:
- Error out backups that include OFFLINE tables

Long term:
- Backup these OFFLINE spans as they appeared at the start time of the job. We'll also need to clear out the progress of the running IMPORT INTO jobs.

Epic CRDB-8816

Jira issue: CRDB-3183

**Comment by dt** [comment]
So @pbardea has a very astute observation here which is that `IMPORT INTO` never overwrites a key. This means the IMPORT keys are the only ones above the offline time -- they're not shadowing prior revisions at earlier times. Thus, even if we don't have a protected timestamp, or even if we _restored_ partial IMPORT data and don't have any revision history at all, we can safely RevertRange to the offline time. Typically RevertRange would fail here since the GCThreshold says "nope, don't have that history to revert to" but here we know that we _do_ -- the latest version of every key at that time is still the latest version since we didn't overwrite them and any keys with more recent times can be outright deleted since there wasn't an older revision we'd need to unearth. 

So, if (and only if) we're reverting an `IMPORT INTO`, we could set a flag on our RevertRange requests to skip requiring the GCThreshold to be lower than the StartTime, meaning we could revert after TTL or even on RESTORE'd data. This is promising, but I'm sure we'll want to be careful with such a flag since it is relying pretty strongly on the caller's promise that it knows the range was offline at SQL level.
