### ISSUE TITLE
sql: prevent sql transactions from committing after the descriptor leases they've used have expired

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6050]
The method `client.Txn.CommitBy` was added in #3028 to address #2820, which said that this functionality was needed to support table leases. However, this method was never used outside of tests; we still need to actually use this functionality when committing sql transactions to ensure that the transactions stay within the bounds of their table lease. Or if this is no longer necessary for correctness at the sql level, we could consider deprecating and removing the functionality.

**Comment by petermattis** [comment]
We definitely still need this functionality for correctness.

**Comment by vivekmenezes** [comment]
Wow I was just looking for this deadline code to see if it was implemented :-)

Yes, definitely need it.

**Comment by vivekmenezes** [comment]
#14198 includes an update to the table lease RFC suggesting that the transaction deadline enforcement needs to change. Reopening this issue.

**Comment by vivekmenezes** [comment]
The correct table descriptor version usage for an origin timestamp is enforced at the SQL layer, while the transaction commit timestamp deadline is enforced at the KV layer. We have left the enforcement at the KV layer because the commit timestamp used by a transaction when using SNAPSHOT ISOLATION is unknown at the SQL layer.

Closing this issue
