### ISSUE TITLE
v20.2.2 negative int to oid cast semantics makes the jdbc driver unhappy

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#60533]
A customer upgrading their v20.1 to v20.2 ran into hanging queries when connecting to their cluster using `Hibernate` and `IntelliJ`.

These tools use a JDBC query to perform a check on some pg trigger before using the queries, that we believe is leading to the rest of the queries on this cluster hanging.

The query appears to succeed on 20.2 but return zero results, something that actually returns one row in postgres (verified with pg 8.3.23). This seems to be where we differ from postgres because we don't support these triggers and some other pg catalog tables.

I believe that we are able to move past them in v20.1 and prior because of the unsupported oid to integer conversion that we fixed in 20.2 as a result of this pgjdbc test https://github.com/pgjdbc/pgjdbc/blob/01dbbac5b6c43e1079a463119e13c1bee74cbfdb/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L187.

The details of the drivers are below:
```
IntelliJ 2020.1 & 2020.3.1 Ultimate Edition
Runtime Version: 11.0.6
JDBC Driver Version: PostgreSQL - ver. 42.2.5 (latest)
Hibernate: 5.3.10.Final
```

The queries that are issued are:

`SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR ((t.typtype = 'd') AND t.typnotnull), pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class AS c JOIN pg_catalog.pg_namespace AS n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute AS a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type AS t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef AS d ON ((d.adrelid = a.attrelid) AND (d.adnum = a.attnum)) JOIN (SELECT 2699 AS oid, 1 AS attnum UNION ALL SELECT 2699, 2 UNION ALL SELECT 2699, 3 UNION ALL SELECT 2699, 4 UNION ALL SELECT 2699, 5 UNION ALL SELECT 2699, 6 UNION ALL SELECT 2699, 7 UNION ALL SELECT 2699, 8 UNION ALL SELECT 2699, 9 UNION ALL SELECT 2699, 10 UNION ALL SELECT 2699, 11) AS vals ON ((c.oid = vals.oid) AND (a.attnum = vals.attnum))`

`SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR ((t.typtype = 'd') AND t.typnotnull), pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class AS c JOIN pg_catalog.pg_namespace AS n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute AS a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type AS t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef AS d ON ((d.adrelid = a.attrelid) AND (d.adnum = a.attnum)) JOIN (SELECT 2690 AS oid, 1 AS attnum) AS vals ON ((c.oid = vals.oid) AND (a.attnum = vals.attnum))`

This is the output on postgres:

```
PostgreSQL 8.3.23

postgres=# SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR ((t.typtype = 'd') AND t.typnotnull), pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class AS c JOIN pg_catalog.pg_namespace AS n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute AS a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type AS t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef AS d ON ((d.adrelid = a.attrelid) AND (d.adnum = a.attnum)) JOIN (SELECT 2690 AS oid, 1 AS attnum) AS vals ON ((c.oid = vals.oid) AND (a.attnum = vals.attnum));
oid | attnum | attname | relname | nspname | ?column? | ?column?
------+--------+---------+-------------------+------------+----------+----------
2690 | 1 | oid | pg_proc_oid_index | pg_catalog | f |
(1 row)

postgres=# SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR ((t.typtype = 'd') AND t.typnotnull), pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class AS c JOIN pg_catalog.pg_namespace AS n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute AS a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type AS t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef AS d ON ((d.adrelid = a.attrelid) AND (d.adnum = a.attnum)) JOIN (SELECT 2699 AS oid, 1 AS attnum UNION ALL SELECT 2699, 2 UNION ALL SELECT 2699, 3 UNION ALL SELECT 2699, 4 UNION ALL SELECT 2699, 5 UNION ALL SELECT 2699, 6 UNION ALL SELECT 2699, 7 UNION ALL SELECT 2699, 8 UNION ALL SELECT 2699, 9 UNION ALL SELECT 2699, 10 UNION ALL SELECT 2699, 11) AS vals ON ((c.oid = vals.oid) AND (a.attnum = vals.attnum));
oid | attnum | attname | relname | nspname | ?column? | ?column?
------+--------+--------------+-------------------------------+------------+----------+----------
2699 | 1 | tgconstrname | pg_trigger_tgconstrname_index | pg_catalog | f |
```

These metadata queries come from  https://github.com/pgjdbc/pgjdbc/blob/01dbbac5b6c43e1079a463119e13c1bee74cbfdb/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L187

We believe that we're running into this problem when trying to inspect the `pg_trigger_tgconstraint_index` table. (OID 2699) which currently isn't supported in CockroachDB.

cc @vy-ton and @rafiss 

gz#7518

**Comment by rafiss** [comment]
The mystery here is why does CockroachDB returning 0 rows cause the other queries to hang? Are the other queries actually hanging, or is it getting stuck somewhere else within IntelliJ?

**Comment by mattcrdb** [comment]
My suspicion is that it's getting stuck somewhere else within IntelliJ.

The user reported that when using `cockroach sql` the queries go through just fine.

I was on a call with them and we looked at `show all cluster queries`. The only meaningful queries were the two queries posted above.

**Comment by rafiss** [comment]
> My suspicion is that it's getting stuck somewhere else within IntelliJ.

That sounds correct to me also. Let's see if we can reproduce, then we can report this to Jetbrains.

**Comment by rafiss** [comment]
OK I downloaded DataGip (which I'd expect to work in mostly the same way as IntelliJ) and connected to CockroachDB v20.2. I turned on statement execution logging in CockroachDB.

I ran a simple `SELECT 1;` query from DataGrip, and it worked.

Then I ran 'SHOW TABLES;' and saw this query being executed 115 times:
```
SELECT
  c.oid,
  a.attnum,
  a.attname,
  c.relname,
  n.nspname,
  a.attnotnull
  OR ((t.typtype = 'd') AND t.typnotnull),
  pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%'
FROM
  pg_catalog.pg_class AS c
  JOIN pg_catalog.pg_namespace AS n ON (c.relnamespace = n.oid)
  JOIN pg_catalog.pg_attribute AS a ON (c.oid = a.attrelid)
  JOIN pg_catalog.pg_type AS t ON (a.atttypid = t.oid)
  LEFT JOIN pg_catalog.pg_attrdef AS d ON
      ((d.adrelid = a.attrelid) AND (d.adnum = a.attnum))
  JOIN (
      SELECT -97 AS oid, 2 AS attnum UNION ALL SELECT -76, 2
      UNION ALL SELECT -104, 2
      UNION ALL SELECT -39, 3
    )
      AS vals ON
      ((c.oid = vals.oid) AND (a.attnum = vals.attnum));
   ```

So it seems to me that DataGrip is retrying the same query over and over, which maybe explains the "hanging" behavior the user was seeing.

In my case, `SHOW TABLES` completed, but it took 2 seconds. Running `SHOW TABLES` from the CLI completes in 20ms. 

Maybe the customer is somehow seeing behavior that retries the query infinitely, rather than stopping at some point.

**Comment by mattcrdb** [comment]
@rafiss Yes!

I think this got lost in the creation of this ticket (when I ported some of the information over). I ran into a similar problem on datagrip using a jdbc URL and the query id kept changing for a similar query to the one above (might be the same) which led me to believe it was constantly retrying.

This was for a different customer.

**Comment by rafiss** [comment]
Interesting.. when I run `select * from pg_proc` from DataGrip against CRDB v20.2, then it does appear that the query hangs indefinitely. I think this is the behavior originally reported by the user. 

I think part of the issue is that CRDB uses 8 bytes for OIDs, whereas PostgreSQL uses 4 bytes. The pg_catalog tables in CockroachDB have OIDs that are large. For example, the pg_description table has an OID of `4294967213`. That's a valid 64-bit integer, but since PGJDBC treats it as a 32-bit integer, that gets turned into a negative number. This explains why the queries are saw are looking up negative OIDs (`SELECT -97 AS oid, 2 AS attnum UNION ALL SELECT -76, 2 UNION ALL SELECT -104, 2 UNION ALL SELECT -39, 3`). 

I still haven't figured out why these queries get retried so many times, but I think it must be related.

**Comment by rafiss** [comment]
It seems what is happening here is that PGJDBC is running this [metadata query](https://github.com/pgjdbc/pgjdbc/blob/01dbbac5b6c43e1079a463119e13c1bee74cbfdb/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L187) for each row in the resultset. Normally, it would cache the results, but because the OIDs are turned into negative numbers as described above, zero rows are returned, so nothing gets cached. Then for the next row, it tries the query again. I confirmed this by putting different `LIMIT`s on the `select * from pg_proc` query, and seeing how many of these queries get sent.

I see a couple ways this could be addressed:
1. Update PGJDBC to turn the Java int into an unsigned int with `Integer.toUnsignedString()` here: https://github.com/pgjdbc/pgjdbc/blob/01dbbac5b6c43e1079a463119e13c1bee74cbfdb/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L226
2. Update CRDB to assign virtual tables OID that are less than `MaxInt32`. Currently, virtual tables get OIDs that count down from `MaxUint32`. See https://github.com/cockroachdb/cockroach/blob/d485973754bd65c2b504b47d0c22a512b6ce00e0/pkg/sql/catalog/catconstants/constants.go#L35

We'd have to see if PGJDBC would be open to change (1). Change (2) seems a little more robust, since other tools could be affected, but also might not be safe to backport.

**Comment by ajwerner** [comment]
I think I prefer (2). I can't wait for the day when somebody runs out of descriptor IDs. We should probably add a thing to fail to allocate a descriptor ID once you hit `1<<30` or implement https://github.com/cockroachdb/cockroach/issues/48438

**Comment by rafiss** [comment]
hmm one more thing we could possibly consider. postgresql is good at casting a negative int to an unsigned oid:

```
rafiss@127:postgres> select (-1)::oid
+------------+
| oid        |
|------------|
| 4294967295 |
+------------+
```

crdb is not:
```
root@:26257/defaultdb> select (-1)::oid;
  oid
-------
   -1
   ```

**Comment by bobvawter** [comment]
One of my customers reports that this affects Liquibase, DataGrip, DBVisualizer, and SquirrelSQL (and one would expect from this being a JDBC driver interaction).  I can tell them to "use cockroach sql", but this is impacting their entire developer team.
