### ISSUE TITLE
sql: certain statements fail to report to telemetry for statement usage

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#60722]
cc @vy-ton 

While working on #60676 I noticed the following: certain statements executed by end-users are not picked up by telemetry.

There are two separate problems:

- password redaction
- literal redaction

Let's talk about password redaction first. For example, `CREATE USER foo WITH PASSWORD 'abc'` will be skipped entirely.

This is because the telemetry collection occurs as follows:

1. first the statement is pretty-printed with FmtHideConstants to construct a stmt key. 
2. then the app key is re-parsed.
3. then the result of re-parsing is processed via FmtAnonymize to remove identifiers
4. the anonymized statement is included in telemetry

When applied to the CREATE USER statement above we get:
1. `CREATE USER _ WITH PASSWORD ******` - the password is edited out
2. re-parse fails: the five asterisks are not valid syntax
3. because re-parse fails the statement is not included in telemetry

Let's talk now about literal redaction.

The 1,2,3,4 steps described above are the same.
Let's consider this statement: `CREATE SEQUENCE s INCREMENT 123`
Processing steps:

1. `CREATE SEQUENCE s INCREMENT _`
2. re-parse fails: the `_` is not valid after INCREMENT because the grammar only supports a signed integer at that position
3. because re-parse fails the statement is not included in telemetry

It's unclear how many statements are affected in this way. I will try to enhance #60676 so we can measure how many statements are affected, however I will not provide a fix. The fix would require some more investment. I hope @rafiss can advise.

Epic CRDB-7217

**Comment by rafiss** [comment]
I haven't worked with this code before, but I just messed around with `TestSQLStatCollection` here: https://github.com/cockroachdb/cockroach/blob/83e70ce84b740e27e721c3b73c38a4b8b515094a/pkg/server/stats_test.go#L152-L158

It seems like the literal redaction problem doesn't exist, but the password redaction problem does.

I wrote some test cases and debugged the re-parsing code you alluded to: https://github.com/cockroachdb/cockroach/blob/83e70ce84b740e27e721c3b73c38a4b8b515094a/pkg/sql/app_stats.go#L609-L614

The re-parsing logic works fine on strings like `SELECT x FROM y where x = _`. But as you mentioned, it does not work with the `*****` password replacement.

Also of note: when I tested with the statement `CREATE SEQUENCE s INCREMENT 123`, the `123` was not actually replaced with `_` after the FmtHideConstants step that creates the statement key.

**Comment by rafiss** [comment]
Could we just use the quoted literal `'*****'` as the password replacement string, instead of `*****`?

**Comment by rafiss** [comment]
Maybe after #60676 is in, it would be worth adding another step to the datadriven test to make sure that the result of FmtHideConstants can be re-parsed.

**Comment by knz** [comment]
according to my findings in #60676 there are 193 different syntax forms affected by this issue (and which thus do not get telemetry or invalid telemetry)

**Comment by rafiss** [comment]
Here is a rough list of statement types to fix:

- [ ] ALTER SEQUENCE
- [ ] ALTER TABLE
- [ ] ALTER USER/ROLE
- [ ] BACKUP
- [ ] RESTORE
- [ ] CREATE CHANGEFEED
- [ ] COMMENT ON
- [ ] COPY
- [ ] CREATE DATABASE
- [ ] CREATE STATISTICS
- [ ] CREATE SCHEDULE
- [ ] CREATE SEQUENCE
- [ ] CREATE USER
- [ ] DROP USER
- [ ] IMPORT
- [ ] EXPORT
- [ ] PREPARE ... AS
- [ ] SELECT ... WHERE ... IS
- [ ] SELECT ... col AS col_alias
- [ ] SELECT TIMESTAMP x
- [ ] SHOW SYNTAX

This list may not be exhaustive. I think that's fine for now, since here is the plan to deal with this:

1. SQL Experience will give a first pass at fixing the ones that are clearly SQL Experience related, which is most of the ones above. I expect many of them will share the same underlying problems as others, so we should be able to make a large dent.
2. As they are fixed, we will update the testdata introduced in #60676 
3. After this first pass, I'll check again with `grep 'WITHOUT LITERALS' -R pkg/sql/parser/testdata`. Then I'll file specific issues for other teams and reference them here.
