### ISSUE TITLE
sql: `DROP TYPE IF EXISTS integer` should error

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#60749]
The command `DROP TYPE IF EXISTS integer` currently is a no-op.

It should error, similarly to this:

```
> drop type if exists int8;
ERROR: int8 is a system catalog
SQLSTATE: 42501
```

This affects v21.1.
It works correctly on v20.2.2, but not on v20.2.5.

Jira issue: CRDB-3145

**Comment by solongordon** [comment]
@arulajmani Could you investigate if there is a straightforward fix here?

**Comment by arulajmani** [comment]
> It works correctly on v20.2.

I tested this on v20.2.5 and it doesn't seem to work. 

I don't think the fix is straightforward here. The way this is handled for fixed width types such as `int4`, `int8` etc. is using this map : https://github.com/cockroachdb/cockroach/blob/3e3521c89d7fa65f9471ddfa47e1ad74fd8af644/pkg/sql/types/types.go#L2604 Unfortunately, we can't add `integer` and `int` to this map. 


This is because `integer` and `int` are parsed to a `nakedIntType` , which is then converted to a static types.T based on the default integer size in the cluster. This `nakedIntType` stuff is all contained in the lexer, so it isn't immediately obvious to me how we can make it work with the `types` package (where the map I linked above resides). 

@rafi, which minor version of 20.2 did you test this with? Maybe there was a backport that broke this thing, which may serve as a clue to an alternate approach.

**Comment by rafiss** [comment]
@arulajmani it has the correct behavior for me with v20.2.2

```
# Server version: CockroachDB CCL v20.2.2 (x86_64-apple-darwin14, built 2020/11/25 14:50:01, go1.13.14)

root@:26257/defaultdb> drop type if exists integer;
ERROR: integer is a system catalog
SQLSTATE: 42501
```

**Comment by rafiss** [comment]
I just gave it a quick glance, but this PR might be related https://github.com/cockroachdb/cockroach/pull/57558

**Comment by rafiss** [comment]
One more thing I just noticed -- we should make sure that `drop type if exists public.integer` keeps working, since you can in fact make an enum type named `public.integer`.

**Comment by arulajmani** [comment]
I don't think this issue is as straight forward as the title would have you assume. This is what I found on v20.2.2, which doesn't 
have this "ux surprise": 
```
root@127.0.0.1:56421/movr> SET default_int_size = 8;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@127.0.0.1:56421/movr> SELECT 'pg_catalog.int'::regtype;
  regtype
-----------
  bigint
(1 row)

Time: 0ms total (execution 0ms / network 0ms)

root@127.0.0.1:56421/movr> SET default_int_size = 4;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@127.0.0.1:56421/movr> SELECT 'pg_catalog.int'::regtype;
  regtype
-----------
  bigint
(1 row)

Time: 0ms total (execution 0ms / network 0ms)
```

Im unsure of how the resolution was working before the PR you linked above went in, but it wasn't doing the right thing. In particular, it wasn't respecting the naked int type.
