### ISSUE TITLE
SET CLUSTER SETTING times out during tests.

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#60916]
The SET CLUSTER SETTING statement waits 10 seconds for the value to be updated before giving up and returning a timeout error:`pq: setting updated but timed out waiting to read new value`

As it turns out the problem is twofold:
1. we do occasionally hit this timeout in CI
2. most of the time we don't notice it because we often don't assert on errors from SET CLUSTER SETTING statements in tests

However in some cases we do and this leads to flaky tests: https://github.com/cockroachdb/cockroach/pull/60781#issuecomment-782192707
I was tagged for this failure because I changed that test to assert on that timeout error, because in my case I really need that setting to be applied before the test can proceed further.

I strongly suspect that we'd have a lot more flakes if we followed every `db.Exec("SET CLUSTER SETTING ...` with a `require.NoError`. As it is, many tests are probably slightly broken too, after all if the statement times out this means that the new setting hasn't been applied yet.

I don't know if the timeout threshold should be increased or not, honestly. In any case these statements shouldn't time out during testing.

Jira issue: CRDB-3102

**Comment by postamar** [comment]
cc @ajwerner

**Comment by adityamaru** [comment]
@postamar or @ajwerner do we know what the next steps here are?

I'm seeing the same failure mode - https://github.com/cockroachdb/cockroach/issues/69281, and I know this came up in the context of some multi-region logic tests as well
https://github.com/cockroachdb/cockroach/issues/69272. It seems like that was fixed by removing parallelization from logic tests https://github.com/cockroachdb/cockroach/pull/69342.

Reading the comments on the MR issue it seems like more investigation is required into why gossip is not propagating the value within 10s.

**Comment by ajwerner** [comment]
Huh, this is odd. One thing with the gossip is that you need to have no intents on the system config span. It's weird that this is anything new.
