### ISSUE TITLE
schema: drop of column fails because view depends on it when it shouldn't

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#61007]
One of the migrations in CC failed for some engineers with the following error:

```
I210223 09:47:36.747671 1 console/main.go:79  failed to run migrations: error executing 20210218103826_drop_user_hashed_password.up.sql, sql: COMMIT;
BEGIN;

ALTER TABLE users DROP COLUMN IF EXISTS hashed_password;

COMMIT;
BEGIN;
: pq: cannot drop column "hashed_password" because view "product_users_view" depends on it {"service":"console"}
```

The strange part here is that `users.hashed_password` has never been referenced by `product_users_view`. Until recently, we were using 20.1. So it is likely that `product_users_view` was created on a 20.1 cluster. Two different engineers encountered this problem when running the migration. One was running 20.1.0 at the time of the DROP, and another was running 20.2.4.

**Comment by petermattis** [comment]
See https://cockroachlabs.slack.com/archives/C01C3B15GQ1/p1614091887004000 for the `.tar.gz` of a storage directory which demonstrates this problem.

**Comment by ajwerner** [comment]
This is #51782 -- fixed first in v20.1.4. It's a bummer and we've had to do manual repair a number of times. Validation has gotten better and we do have tooling if need be but running repair in 20.1 is also extremely painful.

**Comment by ajwerner** [comment]
I was being silly. There was something else going on in some other dropped databases that caught my eye; in the current database things are ~fine. There are corrupted descriptors in other dropped databases which I don't think will affect prod. This is a more vanilla bug. Dropping the view and then recreating it should solve the problem.

bug is https://github.com/cockroachdb/cockroach/issues/29021 fixed by https://github.com/cockroachdb/cockroach/pull/49872

**Comment by petermattis** [comment]
Thanks for tracking this down, @ajwerner!
