### ISSUE TITLE
cli: Make raft tick interval configurable

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6105]
Increasing the raft tick interval will be necessary for high-latency environments (as in #6046) and is expected to mitigate problems as seen in #5970 which can prevent a cluster from recovering.

**Comment by tschottdorf** [comment]
Not sure if this belongs here, but here's a test failure that seems to involve an endless election loop: https://circleci.com/gh/cockroachdb/cockroach/16447

**Comment by bdarnell** [comment]
Oh, interesting. That tells me what's probably going on in #5970 and it deserves its own thread: #6118.

**Comment by bdarnell** [comment]
#6590 added an environment variable for this, but I think we do want to expose it as a user-visible setting - high-latency deployments like #6046 need some way to tell us what range of latency to expect. We can't just tune it automatically by measuring ping times because all nodes need to agree on the value. A command-line flag isn't ideal because it doesn't enforce that all replicas are using the same value, but I'm not sure if we have any better options - raft has to be up and running for almost everything else. 

If the concern is that `--raft-tick-interval` is too much of an implementation detail, maybe the flag could be something like `--expected-max-latency` and we compute the tick interval as a function of that value.

cc @tamird @tschottdorf

**Comment by tschottdorf** [comment]
Yes, the concern is that it's one of those "odd knobs". Your concern is that by instructing these high-latency test deployments to use the environment variable, the environment variable will become a de facto part of the public interface? If that's not a concern (which hopefully could be achieved by communicating clearly), we should be good for now.

We *could* also adjust the tick interval, but I wouldn't advocate for it now due to the complexity involved (the most straightforward way which comes to mind is gossipping it with an infinite expiration and only changed by a leader, for example the smallest gossipped NodeID, in small enough adjustments).

If you think a proper command-line flag is necessary, I'll trust you that it is.

**Comment by bdarnell** [comment]
Yeah, I think that this is going to be useful often enough (and a "perfect" solution is far enough away) that it should become part of the public interface. (I'm also generally fine with removing the flag later when we come up with something better - it's backwards incompatible but it fails cleanly and it should be easy for people to update their configs)

**Comment by jseldess** [comment]
@bdarnell, @d4l3k, does this section of the readme need to be updated to account for this new configuration option? https://github.com/cockroachdb/cockroach/blob/master/docs/design.md#raft---consistency-of-range-replicas

**Comment by bdarnell** [comment]
I don't think it needs to be mentioned in the design doc/readme - we never mentioned the hard-coded 100ms interval there before, and I don't think we need to add it just because it's configurable now. The new flag just needs to be mentioned in the full documentation so that people who need it (most won't) will be able to find it.
