### ISSUE TITLE
Add a new descriptor after the descriptor monitored by the CDC, such as creating a user table, causing the CDC to resend the DML statement

### ISSUE THREAD

**Issue by xiao-77** [cockroachdb/cockroach#61111]
I think the split of the span caused by the creation of a new user table triggers the operation of re-pulling data.Maybe this commit e0f66ed162e0d5bc1255b6d684b6d6af044bcf22 cause this to happen.Delete the content of this commit, the situation will not happen again.How to solve this situation.

**Comment by xiao-77** [comment]
@andreimatei

**Comment by amruss** [comment]
Did this cause a backfill to occur? Or did it trigger duplicate messages to be sent through the changefeed?

**Comment by ajwerner** [comment]
I think the behavior you're discussing is valid and fine. When the range splits, we internally end up restarting a rangefeed over the LHS of the split which may lead to some duplicate messages. Is that so bad? Remember that the changefeed is allowed to emit messages many times.

**Comment by xiao-77** [comment]
@ajwerner ajwerner Thank you for your answer.
I understand that CDC’s strategy is to ensure that every sentence is sent at least once.
However, repeated transmissions caused by range splitting are not uncertain.
Is it possible to filter out these redundant repeated transmissions?

**Comment by xiao-77** [comment]
@amruss According to my observation, the backfill is not triggered.

**Comment by andreimatei** [comment]
@miretskiy are you it?

**Comment by ajwerner** [comment]
@andreimatei i don’t think this is really an issue per se. like I think it’s saying that after a split we re-emit messages since the last resolved timestamp checkpoint. That seems fine. Given the fact that we re-emit messages in a lot of other contexts, I’m thinking this reporter needs to help us better understand why this case is in some way egregious or problematic but other cases like rebalancing is okay. If you have to deal with duplicate messages, then you have to deal with duplicate messages. Maybe we could do better with emitting some checkpoints pre-split.

**Comment by miretskiy** [comment]
@xiao-77 We think that the system works as intended.  If you have additional information you can provide, feel free to reopen this issue, or file a new one.
