### ISSUE TITLE
sql: additional multiregion telemetry

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61384]
In https://github.com/cockroachdb/cockroach/pull/61168 we added multi-region telemetry particularly focused on DDL. We also need a few other additional telemetry gauges including:

21.1
- [x] How often we use the SQL gateway for inserts
- [x] Plan locality optimized search
- [x] Import into multi-region

Post 21.1
- [ ] How often the values are local vs. found in the fan out

Jira issue: CRDB-3030

**Comment by ajstorm** [comment]
For first issue, assuming all use of SQL gateway is for inserts is sufficient - @otan FYI

@rytaft I think we'll need your help with the second item.

**Comment by rytaft** [comment]
> How often the CBO plans locally vs. fans out

Not sure what this is asking. I can add telemetry for when we plan locality optimized search, but that's no guarantee that the key will be found locally. Determining whether locality optimized search actually resulted in local v. remote access would be much more difficult, because the DistSQL plan currently does not record the fact that it came from a locality optimized search operator, and it just happens to work because of the way limited, local UNION ALL is implemented by the vectorized execution engine. Recording local v. remote access at execution time seems like something that should probably be supported by the SQL observability team, and perhaps telemetry would be part of that. @awoods187 does this make sense? Happy to add telemetry for the optimizer planning part...

**Comment by rytaft** [comment]
I merged #62400 (backport #62408) to count uses of locality optimized search.

**Comment by awoods187** [comment]
Thanks @rytaft . I think collecting the fact that we plan a locality-optimized search is a great starting point. I get the complexity in measuring if the value was found locally vs. in the fan-out and that can wait until we have a better sense of how to collect that information.
