### ISSUE TITLE
storage: Make uninitialized replicas distinct types

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6144]
Uninitialized `Replicas` are currently just a `Replica` with an incomplete `RangeDescriptor`. However, nearly all methods on uninitialized replicas are invalid and result in often-subtle failures like #6027. We should create a separate `uninitializedReplica` type which only contains a `raftGroup` and converts to a full replica when it gets its snapshot. The raft-related functionality in `Store` will need to change to look in both `Store.replicas` and `Store.uninitReplicas` instead of assuming the latter to be a subset of the former.

**Comment by tschottdorf** [comment]
As just discussed with @bdarnell @tamird @arjunravinarayan: We are going to introduce three types (names below are tentative), with @arjunravinarayan and @tamird leading the effort.

All of them would implement the `raft.Storage` interface, and snapshots would only ever be applied completely through Raft. That means we wouldn't ever manually write a `HardState`; instead we `Step()` the snapshot into our `*RawNode` and then the corresponding `Ready` will supply us with our `HardState`.

Correspondingly, we would go back to synthesizing a `HardState` if none is found on-disk, but only for type `Replica`, in `InitialState`.

## Replica

a full-flegded Replica which has on-disk state (i.e. a RangeDescriptor and generally, data) and correspondingly, necessarily a nontrivial HardState (which is synthesized when not present). Naturally, it also has a ReplicaID.

## SnapshotReceiver

Created by incoming messages when the `ReplicaID` is unknown and lives until we receive a Raft snapshot (or get gc'ed). This is essentially a `*raft.RawNode` along with a `ReplicaID`. It does not synthesize any state (but may have a nontrivial HardState as it gets to vote and picks up the term).

## PreemptiveSnapshotReceiver

Morally these live only to write the snapshot to disk and then fade away (though realistically, we may want to hold on to them and delete on-disk state when they get too old, to avoid cluttering the disk with snapshots that never got picked up by proper replicas). Due to their role, they don't have a HardState, or at least none that matters for anything.

**Comment by petermattis** [comment]
`Store` currently maintains `replicas` and `uninitReplicas` maps. How are these new types going to fit in? Will there be separate maps for each type? That seems bad as it allows for the possibility of a single `Store` having both a `Replica` and a `SnapshotReceiver` for the same range ID.

**Comment by tamird** [comment]
We are going to use the `raft.Storage` interface.

**Comment by petermattis** [comment]
Can someone sketch out how a `SnapshotReceiver` and `PreemptiveSnapshotReceiver` transition to become a `Replica`? That transition seems tricky. For a `SnapshotReceiver`, would the `raft.RawNode` be transferred to the `Replica`.

Why does a `PreemptiveSnapshotReceiver` not need a `HardState`? Without the `HardState` how do we know what raft log index the snapshot is at? If they don't have a `HardState`, how do we create the associated `RawNode` when transitioning to a `Replica`?

**Comment by tschottdorf** [comment]
Yeah, would be good to sketch that out (I'm also not clear on achieving the single map).
The `PreemptiveSnapshotReceiver` would never become a replica. There's generally no good reason for holding on to a `*raft.RawNode` when it's fully defined by its on-disk state. I think we would just drop one and create the other, which turns it into an issue of synchronization (which is an issue that we have today, see #7600). Avoiding multiple maps would be good, but not at any price - there is some hierarchy between the types in that we will only ever try to replace one of the two receiver types by a `Replica`, and in that we always check for existence of a `Replica` first, so even accepting multiple maps is feasible without a 3x overhead for everything (that said, it'd be nice to avoid it).
The main benefit of these types are (in that order) a) avoiding ever having to massage HardState manually while b) improving clarity.

> Why does a PreemptiveSnapshotReceiver not need a HardState?

For a receiver, there is no committed-but-unapplied tail, so it's equal to the applied index (which is in the snapshot), so it's not strictly necessary. That said, you're right that it would be silly not to write a HardState because the `Replica` which takes over this snapshot would otherwise have to do weird things. The HardState should come for free if we let it go through `*RawNode` (as we plan to do) - a `raftpb.Ready` which contains a snapshot also contains an updated `HardState`.

**Comment by petermattis** [comment]
So the "drop one and create the other" approach needs to be fleshed out. As you state, this is a synchronization issue. I'm not convinced that is it easier to have separate types to handle this. Or maybe the separate types should exist, but `Replica` remains as the synchronization point which handles the transition from one type to another. 

For a `PreemptiveSnapshotReceiver` I'm not clear on how you'll get the `HardState` "for free" by going through a `*RawNode`. If the `PreemptiveSnapshotReceiver` wrote the replica data, then the `*RawNode` will need a `HardState` in order to access that data. Or do you plan for the `PreemptiveSnapshotReceiver` to not write the replica data but to instead create a temporary `*RawNode` to process the snapshot? I thought that wasn't feasible because you need a replica ID to create a `*RawNode` which you don't have when applying a preemptive snapshot.

It's unfortunate that I missed the discussion today. I'm anxious about introducing these separate replica types as I'm still not clear on what problems they are going to solve while they seem to be introducing new problems of their own.

**Comment by tschottdorf** [comment]
> So the "drop one and create the other" approach needs to be fleshed out. As you state, this is a synchronization issue. I'm not convinced that is it easier to have separate types to handle this. Or maybe the separate types should exist, but Replica remains as the synchronization point which handles the transition from one type to another.

In my mind, the synchronization issue is orthogonal to whether it's separate types or not or three maps or one (a mutex guards any number of maps of any types in the same way, the enemy is always having some activity already queued/running on one of the items in any of the maps as we replace them). That said, the synchronization issue does need to be fleshed out and I hope to have a more concrete proposal after I stop-gap #7600 today.

> Or maybe the separate types should exist, but Replica remains as the synchronization point which handles the transition from one type to another.

A Replica doesn't know about anyone but itself, and so I think the `Store` will need to be the synchronization point always (for example, on a split we create a right-hand side `Replica`, but we have no way of knowing whether the `Store` has an uninitialized version of it already, and whether that version is currently busy). When applying a regular snapshot, it would be convenient to have everything in the same map with the same type (because you wouldn't have to change anything), but we don't do that today and we'd instead have more subtle contracts as to what's valid to call on which one.

> I thought that wasn't feasible because you need a replica ID to create a *RawNode which you don't have when applying a preemptive snapshot.

I don't recall that part of the discussion 100%, but looking at it now I see no obvious reason that this must necessarily get in the way. If we want a `*RawNode` only for applying a snapshot, it seems feasible to create on with `ReplicaID==0` and a trivial configuration (i.e. never talking to anyone else). I don't think the `ReplicaID` is persisted anywhere, so applying a snapshot through `Step`/`Ready` should work out just fine (or at least it would be good if it would, for otherwise I also see no way around a HardState massage).

> I'm anxious about introducing these separate replica types as I'm still not clear on what problems they are going to solve while they seem to be introducing new problems of their own.

As stated above, the main benefit of these types are (in that order) a) avoiding ever having to massage HardState manually while b) improving clarity. We converged on this after deciding that we liked the explicitness of always writing a HardState but strongly disliked the need to keep up Raft invariants when doing so. Prior to writing HardState, we relied on passing `len(r.mu.state.Desc.EndKey) == 0` around everywhere and in particular for synthesizing an `InitialState`. With separate types, that problem becomes trivial - a static `InitialState` per type, with the only nontrivial one being that for `Replica` (which returns `raftInitialLog{Index,Term}` when there isn't a persisted `HardState`), and we wanted separate types anyway for the clarity they provide. This also means that we didn't discuss the Store synchronization issue at length. It's clear that there is an issue, but the solution here at this point appears a general brush-up of the locking/potential parallelism so that there is a clear contract for how one of the moving parts upgrades itself or another one (RHS of split) correctly, which is exactly as difficult as without the other proposed changes as far as I can see.

Appreciate your skepticism here and sorry I didn't pull you into the meeting. I was aware of your interest in it but hoped that the output (i.e. the above text) would be sufficient to catch you up. It clearly isn't, and though the way it's going now ensure that more details are available in the public record, it's less fun for you.

**Comment by petermattis** [comment]
On Thu, Jul 7, 2016 at 7:07 AM, Tobias Schottdorf <notifications@github.com>
wrote:

> Or maybe the separate types should exist, but Replica remains as the
> synchronization point which handles the transition from one type to another.
>
> A Replica doesn't know about anyone but itself, and so I think the Store
> will need to be the synchronization point always (for example, on a split
> we create a right-hand side Replica, but we have no way of knowing
> whether the Store has an uninitialized version of it already, and whether
> that version is currently busy). When applying a regular snapshot, it would
> be convenient to have everything in the same map with the same type
> (because you wouldn't have to change anything), but we don't do that today
> and we'd instead have more subtle contracts as to what's valid to call on
> which one.
>
During a split (or merge) a `Replica` knows about its siblings. It's true
that `Replica.splitTrigger` currently blindly creates a new replica, but
that's just the current implementation. It could lookup that sibling in the
store and act appropriately. I agree that the contracts here are subtle.

> I thought that wasn't feasible because you need a replica ID to create a
> *RawNode which you don't have when applying a preemptive snapshot.
>
> I don't recall that part of the discussion 100%, but looking at it now I
> see no obvious reason that this must necessarily get in the way. If we want
> a *RawNode only for applying a snapshot, it seems feasible to create on
> with ReplicaID==0 and a trivial configuration (i.e. never talking to
> anyone else). I don't think the ReplicaID is persisted anywhere, so
> applying a snapshot through Step/Ready should work out just fine (or at
> least it would be good if it would, for otherwise I also see no way around
> a HardState massage).
>
You currently can't create a `RawNode` with `ReplicaID==0` as
`raft.NewRawNode` will panic. Looking through this code again, my suspicion
is that it will be difficult to create a temporary `RawNode` for the
purposes of applying a preemptive snapshot. If there is such fear of
creating a `HardState` "manually", we could also explicitly pass the
`HardState` in our `RaftSnapshotData`. For a non-preemptive snapshot this
would send the `HardState` twice, but that doesn't seem problematic.

> I'm anxious about introducing these separate replica types as I'm still
> not clear on what problems they are going to solve while they seem to be
> introducing new problems of their own.
>
> As stated above, the main benefit of these types are (in that order) a)
> avoiding ever having to massage HardState manually while b) improving
> clarity.
>
Avoiding creating `HardState` manually seems orthogonal to these new types.
I can see paths to always using `raft` created `HardState` that do not
involve any significant restructuring of the code.

> We converged on this after deciding that we liked the explicitness of
> always writing a HardState but strongly disliked the need to keep up Raft
> invariants when doing so. Prior to writing HardState, we relied on passing len(r.mu.state.Desc.EndKey)
> == 0 around everywhere and in particular for synthesizing an InitialState.
> With separate types, that problem becomes trivial - a static InitialState
> per type, with the only nontrivial one being that for Replica (which
> returns raftInitialLog{Index,Term} when there isn't a persisted HardState),
> and we wanted separate types anyway for the clarity they provide. This also
> means that we didn't discuss the Store synchronization issue at length.
> It's clear that there is an issue, but the solution here at this point
> appears a general brush-up of the locking/potential parallelism so that
> there is a clear contract for how one of the moving parts upgrades itself
> or another one (RHS of split) correctly, which is exactly as difficult as
> without the other proposed changes as far as I can see.
>
> Appreciate your skepticism here and sorry I didn't pull you into the
> meeting. I was aware of your interest in it but hoped that the output (i.e.
> the above text) would be sufficient to catch you up. It clearly isn't, and
> though the way it's going now ensure that more details are available in the
> public record, it's less fun for you.
>
A big part of my skepticism to these changes is that our unit tests are not
failing. Rather the refactoring to improve clarity or avoid massaging
`HardState`, I'd like any refactoring to be motivated by an increased
ability to test these rare scenarios.

**Comment by tschottdorf** [comment]
> During a split (or merge) a `Replica` knows about its siblings. It's true
that `Replica.splitTrigger` currently blindly creates a new replica, but
that's just the current implementation. It could lookup that sibling in the
store and act appropriately. I agree that the contracts here are subtle.

But that's exactly what I'm saying - it has to look in the Store to find any competing Replica. It doesn't know it.

> A big part of my skepticism to these changes is that our unit tests are not
failing. Rather the refactoring to improve clarity or avoid massaging
`HardState`, I'd like any refactoring to be motivated by an increased
ability to test these rare scenarios.

I'm not sure I get that point. Yes, our tests should have failed earlier. But what are the reason they don't?

* writing HardState: we started doing things outside of Raft for which Raft itself usually guarantees integrity. The proposal is to not do that. This went undetected for a while since Raft writes HardStates all the time, so unless it finds one that it doesn't know how to handle, it is mostly self-correcting.
* preemptive snapshots: again, doing stuff outside of Raft and not writing the appropriate amount of test code, especially not concurrent tests. Sure, we need more tests (like #7619, which seems like a very obvious omission with 20/20 hindsight), but doing less out-of-band is going to be a good thing.

All of this is fueled by the confusion inherent with having three types of uninitialized Replicas with dubious contracts and synchronization. Clearer contracts and more common code paths allow for better testing and prevent a whole class of bugs. That _is_ why we're doing this. Let's throw all of the assertions and testing at it that we can. But really the code needs to be better.

> Avoiding creating `HardState` manually seems orthogonal to these new types.
I can see paths to always using `raft` created `HardState` that do not
involve any significant restructuring of the code.

That's true, but that's also because the previous code *was* always using the raft created `HardState` (before I changed it not realizing the impact), and doing so worked by passing `len(EndKey)==0` to many of the methods in the `raft.Storage` implementation throughout many call stacks. This was not legible and while you're right in that we could probably bring that back in a better form (like only making use of `len(r.EndKey)==0` in `InitialState()`) without the separate types (and we should make use of that as an intermediate step), I still think separate types help here. And even if they didn't, the reasons which originally motivated this issue are still valid - an uninitialized replica shouldn't have any surface that isn't valid to act upon because that's a whole array of potential bugs. But you're right, let's decouple the `HardState` update a bit from the separate types.

**Comment by tschottdorf** [comment]
> we could also explicitly pass the `HardState` in our `RaftSnapshotData`.

That sounds manually massaging again, because we want Raft to make the HardState for us from the result of the snapshot (i.e. if Raft has voted and it gets a Snapshot, it should give us a new HardState for that snapshot which has also voted). If Raft doesn't massage, we will have to.

>
You currently can't create a `RawNode` with `ReplicaID==0` as
`raft.NewRawNode` will panic.

Do you mean because of this code:

```go 
// NewRawNode returns a new RawNode given configuration and a list of raft peers.
func NewRawNode(config *Config, peers []Peer) (*RawNode, error) {
	if config.ID == 0 {
		panic("config.ID must not be zero")
	}
// ...
```

I chose `ReplicaID==0` because that seemed most idiomatic. In reality any number should do because it's never used for anything and the raft group will cease to exist after it's given us a `HardState`.
Maybe I'm pulling on the wrong thread here. Curious to hear what the rest of the meeting attendees were thinking we were planning here.

**Comment by bdarnell** [comment]
The motivation here is that the use of one Replica type for everything is demonstrably making it difficult to make changes safely. @tschottdorf's change to write the hard state and the introduction of preemptive snapshots broke things because of the subtleties of the transition from uninitialized to initialized replicas. Separate types would have made those changes somewhat more complicated, but would have forced their authors to confront this issue, hopefully resulting in correct changes in spite of our evident lack of test coverage. (we should also improve testing, but I'm more confident in our ability to force the issue with types than creating sufficiently comprehensive tests)

> we could also explicitly pass the `HardState` in our `RaftSnapshotData`.

No, this would be incorrect. HardState is per-replica state and must not be transferred along with the snapshot. When raft processes a snapshot it performs the necessary updates to its local HardState. 

> I chose ReplicaID==0 because that seemed most idiomatic. In reality any number should do because it's never used for anything and the raft group will cease to exist after it's given us a HardState.

Yeah, I was thinking we would use any bogus non-zero value for the replica ID of preemptive snapshot receivers.

**Comment by petermattis** [comment]
Separate types won't prevent bad changes to `HardState`. We'd also have to ensure that only one type for a given range ID exists at a time and that we transition between types correctly (can a `Replica` over get replaced with a `PreemptiveSnapshotReceiver`?). I agree that we haven't had the proper mechanisms in place to make difficult changes safely, but I'm not seeing separate types as a panacea. Re-reading the original proposal, the different types feel more like states of `Replica` than distinct types.

**Comment by tschottdorf** [comment]
We should probably look at the other parts of the proposal first (esp locking) to see what makes sense.

In a related spirit, I was about to do a quick investigation at avoiding out-of-Raft snapshots (i.e. bringing up the bogus Raft group for preemptive snapshots). I didn't have the impression that anyone was about to look at this, but if I'm mistaken please let me know.

**Comment by tschottdorf** [comment]
See also the section "Transaction interactions" in https://github.com/cockroachdb/cockroach/blob/master/docs/design.md.

**Comment by arjunravinarayan** [comment]
@bdarnell and I sat down to discuss the various replica types. It
seems there are three long-lived types of replicas, along two axes:
whether the "replica" has an ID or not, and whether it has keys on
disk or not.

This gives this diagram:

````
Do I have keys on disk ?
      No           Yes
+-------------------------+
|            |  ReplicaID |
|  Nothing   |  Receiver  | No
|            |    [B]     |      Do I
|    [A]  (2)→    (3)     |      have
+------------+-----↓---↑--+        a
|    [C]     |    [D] (4) |     Replica
|  Snapshot  |            |       ID?
|  Receiver  |  Replica   | Yes
|         (1)→            |
+------------+------------+
````
The four states are labeled with letters, and can be created as
follows:

[A] In the beginning is the void.

[B] A `ReplicaIDReceiver` is created after a preemptive snapshot
arrives (2), but before a ReplicaID is assigned. Once the ID is
assigned, it transitions via (3) to a full-blown Replica. But if this
doesn't ever happen, we will be GC-ed back to state [A] by the Replica
GC Queue.

[C] A `SnapshotReceiver` is created by any raft message that contains
a ReplicaID for a Replica that does not exist on this store. It
persists until it receives its snapshot, participating in elections,
etc. Once it receives the snapshot it transitions via (1) to a
full-blown Replica. Currently will not be GC-ed but it probably should
be.

[D] This is a fully functioning Replica. It can devolve into a
`ReplicaIDReceiver` if it loses its ReplicaID when it applies a
`ChangeReplicas` transaction that removes it (4). If this happens, it gets
queued in the GCQueue to be removed, but until that happens, it lives
as a `ReplicaIDReceiver` since it occupies some keyspace on disk.

The names here can probably be improved.

**Comment by petermattis** [comment]
@arjunravinarayan Nice ascii art! 

To me, the above sounds like 3 different states for a `Replica`, not 3 different types. Given how overloaded the term `state` is (`HardState`, `TruncatedState`, `r.mu.state`), perhaps we could compromise and introduce `r.mu.state.Type` that is one of `ReplicaIDReceiver`, `SnapshotReceiver` or `FullReplica`.

**Comment by arjunravinarayan** [comment]
I'm with @petermattis here. I think the important thing is that every `Replica` method check the type. It doesn't have to be a full type, just an enum as suggested should suffice.

**Comment by tschottdorf** [comment]
> perhaps we could compromise and introduce r.mu.state.Type

If the type is in `r.mu.state.Type` we will need to grab the replica lock for every operation, all the time, so that doesn't seem like an option (but we would need some Replica-global lock).

The upshot of separate types is that the type makes clear which operations are supported - I can already sense a nightmare of random if else checks all over the place coming up. Also, regardless of what operations the Replica allows or declines, the Store should never call the wrong thing (if we have figured out the concurrency).
That means that the Store should probably keep them separate in some way. At that point separate types come cheap but make things much less intricate.

I think it'll be instructive to think about the store side of things more - that'll naturally lead to how the locking would work and how a Replica *actually* upgrades itself while being protected from concurrent moving parts, especially during a split trigger.

So I'm still in the types camp because I think that it enforces clarity both in abstraction and implementation, but as alluded to above I also think we're nerd sniping ourselves over this types-vs-state distinction and should base the decision based on what works best from the view of a version of Store with overhauled concurrency.

**Comment by petermattis** [comment]
Nerd sniping. Heh. I'll try and avoid the type-vs-state discussion. 

The problem I see is that Replicas have 3 different roles (as mentioned above): Full replica, replica ID receiver and snapshot receiver. We have an invariant that on a single store there can only be one role active for a range ID at a time. Currently this is accomplished via the `Store.mu.state.replicas` map. Another invariant (which isn't adequately being enforced at this time) is that the replicas for a store cover distinct key ranges. This invariant could be enforced by the `Store.mu.state.replicasByKey` btree.

Whatever solution we arrive at will have to enforce the above two invariants while also providing the desired clarity of what operations are valid for each role.

**Comment by bdarnell** [comment]
Here's another way to look at things: `Replica` conflates two different roles: the consensus group itself and the state machine managed by the raft commands. What if we made these two different types (tentatively `RaftGroup` and `StateMachine`), so that instead of transitioning through different states, we create the former when we know our replica ID and the latter when we know our key span? I think that most parts of `Replica` will fall naturally into one of the two new types, while things that need both sides would move to `Store` instead.

 The `RaftGroup` type contains a `raft.RawNode` and is roughly responsible for everything that is persisted under a local RangeID key including the raft log and HardState. It implements the `raft.Storage` interface, with the wrinkle that snapshots require coordination with the `StateMachine`. 

The `StateMachine` type contains a `RangeDescriptor` and is responsible for all data between its start and end keys. It implements all the KV commands.

A major goal of this refactoring would be to clarify concurrency, as discussed in #7846. Each of the `StateMachine` and `RaftGroup` types would contain an `RWMutex` which represents the object in the store's map. The store would `RLock` this mutex whenever accessing anything from its maps (this means that methods like `Store.GetReplica` would need to be paired with a `ReleaseReplica`), and write-lock it when updating these maps (so when a split overwrites an uninitialized replica, the write lock guarantees that there are no competing operations).

This would be a big change (and there are plenty more details I haven't worked out), but I think partitioning the responsibilities of `Replica` in this way would have more benefits over the long term than treating it as one object with three states (or three objects that replace each other). What do you think?

**Comment by tschottdorf** [comment]
I think this is generally a good idea. The state-machine portion of `*Replica` should not have access to the unreplicated state (#6286 implicitly proposes a state-machine portion of `*Replica` for that reason), and instead communicate side effects explicitly.
Were you envisioning two completely separate types (i.e. two separate maps at the store level) or are you also considering a `*Replica` which contains the types you describe above?

If you didn't have a container structure (`*Replica`), the timestamp cache, pending commands map, command queue, etc would have to belong to `*RaftGroup` (which in turn would be the entry point for the request when it leaves `*Store`), unless we move them up to `*Store` or introduce a third type (which would feel odd). But the timestamp cache also needs to be updated by reads, so this also touches both ends in that case.

One aspect to keep in mind is that with proposer-evaluted kv, we must query the state machine before proposal, so `*RaftGroup` can't do it any more (even if we passed the `StateMachine` into `.Propose()`, refurbishments must be handled at some level. That suggests that perhaps the right structure is one in which we embed a `*StateMachine` into `*Replica` (so that `Replica` itself is the `RaftGroup`). Perhaps this is roughly what it looks like (the locking story would still be sizable). I'd be interested to see a similar sketch for the scenario in which there's no container `*Replica`.


```go
type Replica struct { // exposes Send
  transient struct { // exposes beginCmd and endCmd
    sync.RWMutex
    tsCache
    cmdQ
    pending map
  }
  RaftGroup // raft-related disk io
  *StateMachine // Apply(raft.Ready) (Batch, *Error)
}
```

Generally I get the impression that this the statemachine-raft refactor mostly serves to put reads into proper synchronization with the remainder (or more generally, to avoid uncontrollable moving parts) by introducing coarsely held read locks.

As far as the interaction between Store and, say, a Split goes, I suspect that communicating side effects back up to the store from `handleRaftReady` (instead of doing them directly from the Replica) will go a long way (see https://github.com/cockroachdb/cockroach/issues/7846#issuecomment-232949731). I'm hoping to experiment with that this week.

**Comment by bdarnell** [comment]
> Were you envisioning two completely separate types (i.e. two separate maps at the store level) or are you also considering a *Replica which contains the types you describe above?

I think two separate maps. Some parts of the code need both objects (e.g. the current `Replica.applyRaftCommand`). These could either be moved to `Store`, become static functions, or become methods of a new `Replica` type that would contain the two new types (and nothing else). If the latter, I think it would be a short-lived type that we'd create from the pair of objects on the fly as needed (so really just a convenient shorthand to not have to pass two extra methods).

> If you didn't have a container structure (*Replica), the timestamp cache, pending commands map, command queue, etc would have to belong to *RaftGroup

Why? I'd think all of that stuff would live on `StateMachine` (and so we'd need to access the StateMachine before proposal whether we have proposer-eval KV or not). I was thinking that commands would enter via the StateMachine, go through the command queue, then be proposed on the RaftGroup, and eventually the RaftGroup would spit out commands to be applied on the StateMachine.

> Generally I get the impression that this the statemachine-raft refactor mostly serves to put reads into proper synchronization with the remainder (or more generally, to avoid uncontrollable moving parts) by introducing coarsely held read locks.

Yeah, that and explicitly modeling the two "uninitialized replica" states we're talking about in this thread.

**Comment by tschottdorf** [comment]
> Why? I'd think all of that stuff would live on StateMachine (and so we'd need to access the StateMachine before proposal whether we have proposer-eval KV or not).

Hmm, interesting. Wouldn't that correspond to a composite `type struct { RequestHandler; StateMachine }` where RequestHandler (the part which handles incoming requests including tsCache, cmdQ, pendingCmds) doesn't do arbitrary disk i/o (but can query the StateMachine for proposed-eval'ed kv) and the actual state machine which owns the disk but can't access anything but replicated state? That seems to make some sens.

**Comment by tschottdorf** [comment]
Attempt at an artistic rendering. Are any `*Replica` components missing (I omitted the Store as not to clutter the diagram)?

```
                           (1) read                  
    RequestHandler   -------------------------+      
    (cmdQ, tsCache)                           |      
         |    ʌ                               |      
         |    |                               |      
         |    |                               v      
   (2)   |    |                         StateMachine 
 propose |    | (4) notify              engine, state
         |    |                               ʌ      
         |    |                               |      
         |    |                               |      
         |    |                               |      
         v    |                               |      
    RaftGroup     ----------------------------+      
    (pendingCmds)          (3) apply                 
    |        ʌ            (via Store)                
    |        |                                       
    +---------                                       
    repropose/                                       
    refurbish                                        
```

**Comment by tschottdorf** [comment]
In https://github.com/cockroachdb/cockroach/issues/7830#issuecomment-233662512, @petermattis and I had a good discussion of reducing free access to `*Store` from `*Replica` by passing a `handler` into `handelRaftReady` or by restricting `*Store` through an interface (brings back memories of `RangeManager`). We didn't exactly agree on the best way forward, but the good thing is that with proposer-eval'ed kv, we can simply look at the concrete proposal(s) "for free" at some point in the near future. That work started in #7915.

**Comment by tschottdorf** [comment]
Quick summary: We've made decent progress on a lot of issues discussed in this thread.

There's the manual writing of the HardState (we'll either go back to faking one in `InitialState()` for uninitialized Replicas, or we can seed through a Raft snapshot application (which in turn replaces `synthesizeRaftState`). Hard to say which one's better without looking into both, but that's tracked in #7875 and while it motivated some of the original discussion here, I think at this point it doesn't need to be a part of it any more.

@arjunravinarayan's going to make sure that as a `*Replica`, I own my keyspace, whether I'm applying a snapshot or splitting, so HardState clobbering is going to be a thing of the past (#7830, along with @bdarnell's recent fix to restore parallelism #7860)

We've made decent process on preemptive snapshots, which look much less scary now (#7833).

I'm picking up proposer-eval'ed kv side effects, which will also let us experiment with some safe refactors that simplify the `Replica-Store` interaction by moving upcalls closer together (without changing the concurrency at all, which would have to be done very carefully).

There's still concern around `*Replica`s being used after they've been removed from the `*Store`, but we're also seeing parts of that addressed (#7879), and as long as mutations go through `*Store` (which has the authoritative index) and avoid tricky shortcuts, the fixes here should be mostly for performance (to avoid getting commands stuck on removed replicas), but not correctness. For example, spurious calls to `(*Replica).proposeRaftCommand` will `Step` the Raft group, so it'll emit a `Ready`, but that is only ever consumed by the `*Store`, so it won't (or at least shouldn't) do anything if we've removed the `*Replica` earlier.

So we have a couple of threads which are being pulled simultaneously, and which (I think) are a beneficial for the "larger" refactoring ideas (such as @bdarnell's proposal just above), regardless of which one it is. I also suspect that with the above threads pulled to completion, we'll have addressed most of the cognitive complexity (of course there's lots to gain in terms of performance still) and centralized it

* at or close to `(*Store).processRaft` and `(*Store).handleRaftReady` for handling anything regarding Replica concurrency and changing of range boundaries
* in `*Replica` (which is now guaranteed to be "alone" on its or its new snapshot's keyspace) all the state-machine application of data on-disk on splits and snapshots (but no difficult-to-track upcalls to `*Store`, which are instead handled close to `*Store` via side effects).

I don't think we need to push forward for an extensive refactor right now as I think we're doing a good job iterating towards one (still interesting to discuss, though). I think we can do better on handling uninitialized Replicas (the original impetus here), though.

**Comment by petermattis** [comment]
Thanks for the summary, @tschottdorf.

**Comment by petermattis** [comment]
@bdarnell Do you think we still want to do this?

**Comment by bdarnell** [comment]
I still support the idea in principle, but I doubt we'll ever actually do it at this point. Might as well close the issue.
