### ISSUE TITLE
sql: add a cluster setting that prevents tables without explicit primary keys

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61495]
CockroachDB does not require a primary key:
```SQL
CREATE TABLE sample_orders (
    order_id        UUID,
    order_date      TIMESTAMP NOT NULL,
    order_mode      STRING(8),
    customer_id     INT,
    order_status    INT
  );
CREATE TABLE
```
However, if you do not create one, we will create one for you:
```SQL
show create table sample_orders;
   table_name   |                                     create_statement
----------------+--------------------------------------------------------------------------------------------
  sample_orders | CREATE TABLE public.sample_orders (
                |     order_id UUID NULL,
                |     order_date TIMESTAMP NOT NULL,
                |     order_mode STRING(8) NULL,
                |     customer_id INT8 NULL,
                |     order_status INT8 NULL,
                |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
                |     CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
                |     FAMILY "primary" (order_id, order_date, order_mode, customer_id, order_status, rowid)
                | )
(1 row)
```
The primary key constraint must be made or specified for every table because it provides an intrinsic structure to the table's data.
From our docs: 
> Each table automatically has an index created called primary, which indexes either its primary key or—if there is no primary key—a unique value for each row known as rowid. We recommend always defining a primary key because the index it creates provides much better performance than letting CockroachDB use rowid.

We should provide a cluster setting that prevents table creation if no primary key is specified so that operators can ensure that developers explicitly create one. We can allow this to be overridden (perhaps by sql_safe_updates).

**Comment by awoods187** [comment]
cc @mwang1026

**Comment by jordanlewis** [comment]
This is another one that would be ideally possible to override with user, schema, and database-level grants. Absent that I think we should make sure to give it its own session setting that's distinct from `sql_safe_updates`, since that is about editing tables, and creating a table is something else entirely.

**Comment by rafiss** [comment]
@awoods187 Should we prioritize this for 21.2?

**Comment by awoods187** [comment]
I think its a good idea (particularly with a separate cluster setting) especially for those orgs that want to ensure developers follow good CRDB best practices. I'll defer to @vy-ton  on prioritization of this vis a vis the rest of the roadmap.

**Comment by rafiss** [comment]
@techytoes thanks for taking this on. here are some instructions that should help you

1. add a new cluster setting in pkg/sql/exec_util.go. for an example, look at `traceSessionEventLogEnabled`. let's name the new setting `sql.require_explicit_primary_keys.enabled`. it should default to false.
2. modify pkg/sql/create_table.go in the `startExec` function so that it checks this setting, and verifies that the input has a primary key. to return an error, use `errors.WithHint`, and make the hint message mention the new cluster setting
3. Add tests for this in the `create_table` logictest

cc @vy-ton for awareness -- my feeling is that this is better as a cluster setting and _not_ as a session setting, since it seems like something a database administrator might want to control, rather than allowing each database user to configure this in their session. what are your thoughts?

**Comment by techytoes** [comment]
@rafiss thanks for helping out. it seems like these changes are already implemented. 
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/create_table.go#L2093. 
Let me know if I am missing anything here. Thanks!

**Comment by vy-ton** [comment]
>my feeling is that this is better as a cluster setting and not as a session setting
I agree
