### ISSUE TITLE
No privileges required for SHOW GRANTS

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6162]
A user without privileges on a database or table can nonetheless view grants on the database or table. Seems like this lets such a user discover other usernames to connect with in order to access/interact with the db/table. 

For example, say I don't want user `jseldess` reading anything from table `keep_out`. User `jseldess` could just view grants on table `keep_out` and then re-connect using a user with read privileges on that table:

**Root user creates db and table and gives user `mroach` SELECT privileges on the table:**
```
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> create database no_access_for_jseldess;
CREATE DATABASE
root@:26257> create table no_access_for_jseldess.keep_out (a int, b string);
CREATE TABLE
root@:26257> insert into no_access_for_jseldess.keep_out values (1, 'blah');
INSERT 1
root@:26257> grant select on no_access_for_jseldess.keep_out to mroach;
GRANT
root@:26257> show grants on no_access_for_jseldess.keep_out;
+----------+--------+------------+
|  Table   |  User  | Privileges |
+----------+--------+------------+
| keep_out | mroach | SELECT     |
| keep_out | root   | ALL        |
+----------+--------+------------+
```

**User `jseldess` connects, tries to read from the new table, and then views grants on the table:**
```
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql --user=jseldess
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
jseldess@:26257> set database = no_access_for_jseldess;
SET
jseldess@:26257> show tables;
+----------+
|  Table   |
+----------+
| keep_out |
+----------+
jseldess@:26257> select * from keep_out;
pq: user jseldess does not have SELECT privilege on table keep_out
jseldess@:26257> show grants on keep_out;
+----------+--------+------------+
|  Table   |  User  | Privileges |
+----------+--------+------------+
| keep_out | mroach | SELECT     |
| keep_out | root   | ALL        |
+----------+--------+------------+
```

**Same person connects as `mroach` user and reads from the new table:**
```
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql --user=mroach
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
mroach@:26257> select * from no_access_for_jseldess.keep_out;
+---+------+
| a |  b   |
+---+------+
| 1 | blah |
+---+------+
```

**Comment by bdarnell** [comment]
> Same person connects as mroach user and reads from the new table:

That's only possible in insecure mode or if this person has the ability to create their own certificates from the master CA, at which point it's game over anyway (even if they couldn't see the grants they could just connect as `root`). We're going to have to design and document best practices for key management to keep the CA key secure (and separate from the CA cert: every user needs a copy of the CA cert, but the CA key grants superpowers).

There's still an information leak here, though: users shouldn't generally be able to discover the existence of databases or tables that they have no access to.

**Comment by jseldess** [comment]
Make sense, Ben. After talking to @mrtracy, I also now understand that this won't be as big an issue once we have password-based authentication. But even in that case, it seems like a bad idea to let all users see grants on all dbs and tables.

**Comment by bdarnell** [comment]
What does password-based authentication have to do with it? If someone can create a certificate, they can create one for `root` (which is always present) so the names in the grants don't actually help them get in.

**Comment by bdarnell** [comment]
To elaborate: cert-based authentication is generally much more secure than password-based authentication, but it can be less secure in practice because users don't understand it. Everyone knows that passwords need to be kept secret, but it's much less clear with certificate auth. We don't currently do a good job of making this clear: After following our instructions, you'll end up with six files that apparently make up a set: the CA key and cert, the node key and cert, and at least one user key and cert. In most cases, the key and its corresponding cert travel together. However, things are different for the CA: the CA cert is published widely within the system (every participant needs a copy), but the CA key is the most sensitive thing in the whole security scheme (it's the master key that lets anyone impersonate anyone else). 

Managing this stuff is not easy, but since this is our security model we need to think about the right way to expose these sensitive files in a way that will encourage users to do the right thing, and educate them about the security requirements involved.

**Comment by jseldess** [comment]
Thanks, Ben. Appreciate the additional context.

I guess I was thinking that, in the case of an insecure cluster, passwords would prevent a user from being able to take advantage of others' privileges; even if the user could see someone else's privileges, the user couldn't connect without the other user's password.

In terms of improving the docs on certs, as discussed over dinner, I THINK you're referring to the instructions on [Secure a Cluster](https://www.cockroachlabs.com/docs/secure-a-cluster.html), which is for securing a single or multi-node local cluster. Our page on [Manual Deployment](https://www.cockroachlabs.com/docs/manual-deployment.html), which assumes deploying on three separate machines, is clearer and closer to what you're asking for, I think. But if that's actually the page you think needs improving, can you open a Docs issue with those suggestions?

**Comment by bdarnell** [comment]
> I guess I was thinking that, in the case of an insecure cluster, passwords would prevent a user from being able to take advantage of others' privileges; even if the user could see someone else's privileges, the user couldn't connect without the other user's password.

Yeah, insecure clusters are wide open and you can't add even the most basic access controls without certificates. This would be difficult to change because of the need for node-to-node communication (even if you needed a password to connect to the sql interface of an insecure cluster, the internal node interfaces would still be unprotected). If you want any security at all you can't run in insecure mode.

**Comment by jseldess** [comment]
Closing, based on @bdarnell's input.
