### ISSUE TITLE
bazel: figure out support for `crdb_test`, `crdb_test_off` tags within Bazel build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61724]
A brute-force solution is to manually identify all the tests that are broken if these tags are not appropriately set, and set the `gotags`.

**Comment by yuzefovich** [comment]
I think we would like to have the same behavior as we currently have with `make` - that all test targets have `crdb_test` build tag set by default - since presence of the flag enables additional verifications and assertions. If with bazel tests we simply not add a tag and see what's broken, I'm pretty sure that nothing will be broken (#61317 is an exception).
