### ISSUE TITLE
sql/ui: add tooltips to explain plans in db console

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61764]
@RaduBerinde outlined a proposal today to help others better understand EXPLAIN. EXPLAIN plans contain a lot of information. It can confusing to consume them directly. It would be great if we could provide tooltips in the DB Console for the various parts of explain and also in the SQL Shell (via verbose mode?). 

cc @Annebirzin

**Comment by Annebirzin** [comment]
Right now we still show the logical plan in db-console correct? So adding tooltips to the explain would rely on us updating the logical plan tab to the new explain plan?

**Comment by RaduBerinde** [comment]
The logical plan in the db-console is pretty much the new explain plan, it's just formatted differently.

**Comment by awoods187** [comment]
As an aside, we should probably update the explain in the db console to match the SQL shell as much as possible. 

This item is about adding tooltips in the db console for defining what a span is, or an index, or distributed, vectorized, etc. Similarly, this could be an option in the SQL shell via verbose but I think its less needed.

**Comment by Annebirzin** [comment]
Designs for adding tooltips to the Explain Plan in the DB console can be found here (cc @maryliag): https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=2727%3A118388

@kevin-v-ngo @ianjevans  I think we'll need your help defining which keywords to add tooltips for and what the messaging should be. 

Note: These designs include a style and structural update to the current Logical Plan visualized in the DB console. This design aligns with the latest Explain plans in the SQL shell (this may need a separate ticket). 

We should also name this tab 'Explain plan' rather than 'Logical plan' to stay consistent with the SQL shell. Let me know any thoughts.

**Comment by maryliag** [comment]
Created the issue for matching the format at https://github.com/cockroachdb/cockroach/issues/67328
