### ISSUE TITLE
stats: table has no histogram statistics created

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#62206]
CRDB 20.2.5.  

Table has no histogram statistics created for any column.  

Table has ~100 columns, 5.4TB and an estimated 1,321,192,796 rows.  This is the largest in the db.

Another large table with 2.1TB and 2,067,670,141 rows is showing histograms.  I have not reviewed the remaining 40+ tables in this db, but I can if needed.  

More details can be found in linked ticket and slack conversation.  

gz#7914

**Comment by rytaft** [comment]
I'm closing this issue since we're working on it internally. We can reopen later if it makes sense to create a public issue.

**Comment by rytaft** [comment]
Reopening now that we know the issue was due to "disabling histogram collection due to excessive memory utilization". 

We should:
- Take this use case into account when building the vectorized statistics operator in the upcoming release cycle (e.g., spill to disk if needed, reduce the number of sampled rows and/or columns, etc) (cc @michae2 who will be working on the vectorized stats operator)
- Update the row-based statistics operator with a back-portable fix that reduces the number of sampled rows and/or columns when the memory limit is hit during sampling. Perhaps we could start with a simple approach of cutting the number of samples (and histogram buckets) in half each time we hit the memory limit, up to some threshold (e.g., 1000 rows). If we hit that threshold, then we could start cutting columns.
