### ISSUE TITLE
roachtest: override (performance) workload flags

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#62303]
It's currently not possible to override individual `workload` flags when run via `roachtest`. For example, it would be nice to override `--duration` for the `kv95` workloads, but `roachtest` uses a fixed `workload --duration 10m`.

Jira issue: CRDB-2810

**Comment by csgourav** [comment]
There seems to be already enviornment variable way of updating duration exists for the two workloads, kv and ycbs, though not add in all tests registered fro them.

PR - https://github.com/cockroachdb/cockroach/commit/b8986e311587ae4a437747132a24ad6a18c0b7eb

Originally added to pass on duration for the kv and YCSB workload
`ROACHTEST_KV_FLAGS` and `ROACHTEST_YCSB_FLAGS` to pass additional flags
to the workloads in order to override the duration (e.g.
`ROACHTEST_KV_FLAGS="--duration 5m"`)

The other way would be using the roachtestflag, which would be global and would need making changes in all the tests. 
Global flag might be confusing for non workload type tests.

**Comment by srosenberg** [comment]
> There seems to be already enviornment variable way of updating duration exists for the two workloads, kv and ycbs, though not add in all tests registered fro them.

Nice, I wasn't aware of that change. We still need to propagate these into the roachtest environment.

> The other way would be using the roachtestflag, which would be global and would need making changes in all the tests.
Global flag might be confusing for non workload type tests.

Agreed, let's leverage the env. vars. You'll need a way to pass them from the client (i.e., entity executing `roachtest` binary) into the (remote) environment of the workload binary. Note that a particular workload could either be run from the `cockroach` binary or the `workload` binary, as is the case with `kv` and `ycsb`; `workload` binary is a superset, i.e., it packages all workloads.

For the `cockroach` binary, env. vars. are injected via the startup script (`start.sh`); see `ClusterSettings.Env` and `generateStartCmd`. We'll probably have to do something similar for the `workload` binary since today it's _not_ invoked via a wrapper script.

**Comment by csgourav** [comment]
I think we won't need to pass these two workload or cockroach binary. That is taken care in this change, while calling the workload binary itself, we are passing updated duration value fetched from the environment value.

Done in this PR https://github.com/cockroachdb/cockroach/commit/b8986e311587ae4a437747132a24ad6a18c0b7eb

To make use of this in the bisect_runner.sh script, we will have to modify that script to make use of the environment variable.
Which is in this repo https://github.com/smg260/roachperf-bisect/tree/72e4ba7a29c2c9267addfdce6170cf6e8f282eda

**Comment by srosenberg** [comment]
> I think we won't need to pass these two workload or cockroach binary. That is taken care in this change, while calling the workload binary itself, we are passing updated duration value fetched from the environment value.
> 

The change in PR https://github.com/cockroachdb/cockroach/commit/b8986e311587ae4a437747132a24ad6a18c0b7eb doesn't facilitate setting an environment variable of a _remote_ process. The (workload) binary executes on a workload VM whereas `bisect` is executed on the same VM as the `roachtest` binary. Thus, you need a way for the (roachtest) framework to inject these env. vars. into the workload process.
