### ISSUE TITLE
Database Backup failing repeatedly 

### ISSUE THREAD

**Issue by akakana** [cockroachdb/cockroach#62374]
**Describe the problem**

Database backup failing when doing a cluster level backup with the below message.
Code: 0, SQL State: XXUUU]  ERROR: failed to resolve targets specified in the BACKUP stmt: duplicate table name: "wfadb"."public"."basic_employee_info" used for ID 1416 and 1415

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by rafiss** [comment]
Hi @akakana! Which version of CockroachDB are you using? This isn't my area of expertise, but if you aren't able to find help anywhere else I can try to give you some pointers for resolving this.

**Comment by dt** [comment]
I think to dig into this more we'd need to know the version, like @rafiss said, since some versions had bugs around some migrations of schema metadata and maintaining some invariants that only backup depended on, which have since been fixed. My guess is this is that issue, and hopefully is already fixed by upgrading to a more recent patch version so I'm going to tentatively close this as already fixed (@ajwerner do you remember when we stopped generating descs with duplicate names?).

If it isn't one of those versions, I think we'd want to look at the contents of system.namespace, system.namesapce2 and system.descriptor. To export these, we'd want to do `cockroach sql -e 'select * from system.namespace' --format=csv` and the same for system.namespace2. For descriptor we'd want to do `select id, encode(descriptor, 'hex') from system.descriptor` since that's a binary field. We can also provide a way to share those privately If you want to dig into this more.

Cheers!
