### ISSUE TITLE
importccl: import pgdump error should be wrapped to point people to ignore option

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#62462]
If you run into an unsupported statement in IMPORT PGDUMP, you get an error like

```
pq: unsupported *tree.SetVar statement: SET statement_timeout = 0
ERROR: unsupported *tree.SetVar statement: SET statement_timeout = 0
```

It'd be ideal to wrap the error with a pointer to the docs which highlights the `ignore_unsupported_statements` and `log_ignored_statements` options. Something along the lines of

`Encountered unsupported statement during IMPORT. To ignore unsupported statements and log them for review post IMPORT see the options listed in the docs: (Link to import docs)`

**Comment by rmloveland** [comment]
hey @mwang1026 and @adityamaru I think due to something in this general area CockroachDB v21.1 now fails to import files that worked with v20.2 and below.

(And/or our docs did not make clear that files that were once accepted will now break.)

For details see https://github.com/cockroachdb/cockroach/issues/70992
