### ISSUE TITLE
Construct a base handler for all HTTP servers to glog.Fatal on panic

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#625]
Construct a base handler for all HTTP servers to glog.Fatal the process with a deferred recover func to prevent HTTP from swallowing panics which might otherwise be holding locks, etc.

**Comment by chrisseto** [comment]
I can take a shot at this if you guys don't mind.

**Comment by tamird** [comment]
By all means!

**Comment by tschottdorf** [comment]
I don't see how the base handler can be of huge help with locks. The defer needs to be aware of the lock held and whether it's being held.

**Comment by tamird** [comment]
I think this issue no longer has meaningful value. Closing.

**Comment by bdarnell** [comment]
This issue is as valid as it ever was: recovering from a panic is risky in production code because it can leave a process unable to make progress on some paths (due to dangling locks, etc) but still looks healthy enough to pass its health checks. It's better to just let panics kill the process so it can be restarted. This is already true by default in most cases, but in places where the standard library inserts a `recover()` call (i.e. the HTTP server) we should intercept panics ourselves to make sure they stay fatal. This is low priority until we see an actual problem related to this, but I think it's worth keeping the issue open.

**Comment by tamird** [comment]
server.Server implements `ServeHTTP()` now, so this handler can be inserted there. @chrisseto care to give this a try?

**Comment by soniabhishek** [comment]
Hi, i am new to this project so requires some guidance.
I was introduced to this topic by @tamird now i would like to know what exactly should be done.
Do  we require to alter all the  deferred recover func to` log.Fatal` or by using `ServeHttp()` method .
also this alteration required to be changed at every occurrence or at only selected locations where locks is coming in scenario.
