### ISSUE TITLE
kv: methods to add metadata fields on table and column

### ISSUE THREAD

**Issue by dmedri** [cockroachdb/cockroach#6278]
It could be useful have generic methods to handle metadata fields on table and column for the following actions:
- kv INSERT metadata field on table or table.column
- kv UPDATE metadata field on table or table.column
- kv DELETE metadata field on table or table.column
- kv EXTRACT metadata fields from table.
- kv SHOW metadata fields from table.

These data will be part of the header of any table, useful to describe the dataset with informative texts (title,subtitle,description,notes,...).

**Comment by petermattis** [comment]
@dmedri Can you expand on how you'd want to access this metadata? In cockroachdb, the term `kv` usually refers to the internal key-value API which is not exposed for public consumption and does not have concepts of tables or columns. I'm guessing this issue is based on [your comment](https://github.com/cockroachdb/cockroach/issues/5194#issuecomment-207782117) in #5194.

It would also be useful if you could expand on the utility you see in baking these metadata fields into CockroachDB. That is, what use case are you imagining for these fields that you couldn't accomplish without them. Or perhaps, the addition of these fields make a particular use case a lot easier.
