### ISSUE TITLE
Read waits on uncommitted write ~5s then returns before write is committed/aborted

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#62888]
**Describe the problem**

I've observed some behavior in CC free tier that confuses me. Specifically, when an uncommitted write is made to a row in one connection, and then the same row is read in another connection, the read waits anywhere from 3-6s and then returns. I would expect the read to return only when the open transaction in the other connection to commit/abort.

When running the same sequence locally on a single node cluster, the read does not return until the transaction is committed/aborted. I have not tested in any other environments.

**To Reproduce**

1. Create a CC free tier cluster.
2. Open 2 connections and run the following SQL statements:

```
connection 1         |          connection 2
---------------------|----------------------
CREATE TABLE t (     |
  k INT PRIMARY KEY, |
  i INT NOT NULL     |
);                   |
                     |
INSERT INTO t        |
  VALUES (1, 1);     |
                     |
BEGIN;               |
                     |
UPDATE t             |
  SET i = i + 1      |
  WHERE k = 1;       |
                     |
                     | SELECT * FROM t
                     |   WHERE k = 1;
                     | (Returns ~5s later)
                     |
COMMIT;              |
(Successful)         |
```

**Environment:**
- CC free tier
- CockroachDB CCL v20.2.7 (x86_64-unknown-linux-gnu, built 2021/03/29 17:52:00, go1.13.14)

**Comment by ajwerner** [comment]
FWIW, this behavior seems "correct" and not like a bug. Is this issue just to understand the dynamics or because these dynamics are causing a problem. So, in general, the reader in cockroach will block until the writer commits, aborts, or gets pushed high enough. So, what's happening here is that in a free tier cluster, the writer is getting pushed.

Ranges which have any rangefeeds running want to make sure that their resolved timestamps progressed. Normally, most ranges don't have any ranges with rangefeeds unless you're using a changefeed on the table. Generally, cockroach splits ranges on table boundaries. In serverless, cockroach splits on tenant boundaries. Cockroach, also because of serverless, runs rangefeeds to tracks updates to descriptors, cluster settings, and some other system-level things. Because those tables are in the tenant keyspace and most tenants have just one range, it means that the tenant range likely has a rangefeed running. Ranges with rangefeeds run their pusher routine here:

https://github.com/cockroachdb/cockroach/blob/30ce153c9b53d93763128b7caf46c2bc38bc21d3/pkg/kv/kvserver/rangefeed/processor.go#L289

**Comment by mgartner** [comment]
Closing.
