### ISSUE TITLE
geomfn: st_simplify with NaN causes node to crash

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#63620]
This query causes the node to crash without leaving any logs behind.

```
SELECT st_simplify('0104000000020000000101000000AC885A457886F9C1C9EEF30F7308F3C101010000007411E55B3F66EDC10BBEFA0ABF45F0C1':::GEOMETRY, 'nan':::FLOAT8);
```

It works on PostGIS though

```
postgres@localhost:postgres> SELECT st_simplify('0104000000020000000101000000AC885A457886F9C1C9EEF30F7308F3C101010000007411E55B3F66EDC10BBEFA0ABF45F0C1'::GEOMETRY, 'NaN'::FLOAT8)
+--------------------------------------------------------------------------------------------------------+
| st_simplify                                                                                            |
|--------------------------------------------------------------------------------------------------------|
| 0104000000020000000101000000AC885A457886F9C1C9EEF30F7308F3C101010000007411E55B3F66EDC10BBEFA0ABF45F0C1 |
+--------------------------------------------------------------------------------------------------------+
SELECT 1

postgres@localhost:postgres> SELECT st_astext(st_simplify('0104000000020000000101000000AC885A457886F9C1C9EEF30F7308F3C101010000007411E55B3F66EDC10BBEFA0ABF45F0C1'::GEOMETRY,
 'NaN'::FLOAT8))
+-----------------------------------------------------------------------------------+
| st_astext                                                                         |
|-----------------------------------------------------------------------------------|
| MULTIPOINT(-6851888213.65837 -5109133567.2458,-3945921247.15838 -4368101551.6714) |
+-----------------------------------------------------------------------------------+
SELECT 1
```

cc @otan @andyyang890

**Comment by otan** [comment]
it works in PostGIS because they a) special case points to return themselves and b) have their own algorithm for simplifying from what i can tell.

we're relying on GEOS instead which does not deliver the goods.

We should make the following changes:
a) Simplify with points/multipoints should return themselves (use ShapeType2D())
b) Simplify with NaN should return themselves.

This can be done before the check to GEOS here: https://github.com/cockroachdb/cockroach/blob/3687e5646d15207e2248c219d725463097167318/pkg/geo/geomfn/topology_operations.go#L98

With tests added here: 
https://github.com/cockroachdb/cockroach/blob/3687e5646d15207e2248c219d725463097167318/pkg/geo/geomfn/topology_operations_test.go#L209

**Comment by techytoes** [comment]
Hey @rafiss, can I pick this up?

**Comment by rafiss** [comment]
@techytoes sure, please do! @otan's directions above should let you work on this but let me know if you are stuck
