### ISSUE TITLE
sql: Investigate float overflows and when decimal should be the natural constant type

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6369]
In the initial implementation of Summer, all non-int numeric constants had a natural type of FLOAT. We should adjust this based on if the FLOAT datatype would lose information. For instance, `9223372036854775808` should probably have a natural type of DECIMAL so that it doesnt lose information without a desired type.

**Comment by nvanbenschoten** [comment]
[constant.Float64Val](https://golang.org/pkg/go/constant/#Float64Val) exposes an "exact" flag, so we could use this to avoid data loss. The issue with this heuristic is that any repeating decimal value will, by definition, lose data. This means that rational numbers like `1/3` will always be forced to become the `DECIMAL` type, which brings up a few questions.
- How much precision do we use for the `DECIMAL`, which is arbitrary precision, but not unlimited precision? This question is also relevant to `DECIMAL` division.
- `INT/INT` is defined as returning a `FLOAT`, but folding `INT` division that would result in a repeating decimal would now give a DECIMAL. Is this ok? This may actually be exactly what we want.

**Comment by JackKrupansky** [comment]
Support for rational numbers would be a way-cool feature, although I wouldn't give it a high priority for 1.0. Sounds like a great free-Friday project.

See:
https://en.wikipedia.org/wiki/Rational_data_type

**Comment by nvanbenschoten** [comment]
After attempting to use the "exact" flag returned from [constant.Float64Val](https://golang.org/pkg/go/constant/#Float64Val), I'm fairly certain that using that flag is not the heuristic we want. The problem is that many values that seem like they should have a natural type of FLOAT cannot actually be exactly represented as a FLOAT. For instance, if we used that heuristic, `1.1` would have a resolvable type set of `[DECIMAL]` (and a natural type of `DECIMAL`). 

Interestingly, Postgres types `1.1` as a numeric
```
SELECT PG_TYPEOF(1.1);
----
numeric
```
which makes me believe that they give all decimals numbers their equivalent of a resolvable type set of `[NUMERIC, REAL]`.

**Comment by knz** [comment]
@JackKrupansky I agree with you a rational type could be a cool feature. However the question would then become "what happens when we cast a rational value to an int or float?" This question would then need an answer, which will be the same answer we need to give to Nathan today.

@nvanbenschoten 
First regarding the type of literals with a decimal point.

Yes I was aware that pg will type all literals with a decimal point as decimal/numeric first, and only cast them to float when float is desirable. 

From the math pespective in general for many decimal literals entered in base 10 you will not have an exact float representation and thus decimal would be the good choice. 

Even ignoring the math argument, from the perspective of a user using a db, it's rather desirable to have decimal numbers handled as such and have decimal arithmetic performed without surprises. So I would be quite confortable having the resolvable type set of literals with a decimal point as [decimal, float] like you propose.

Then regarding the result of converting a rational number with a repeating representation. Educated guess is that decimal will be desirable. This is because a semi-large number divided by a semi-small number will give a number with a large amplitude and as user I'd desire to get a result as close to exact as possible. I can always cast to float afterwards (or perhaps type annotate float if/when we have that option) if that's what I want.

The finally about the type of int/int division. I do not like this to be float. I *really* do not like this. I think that it should be decimal too, with an option for the user to convert to float if so desired. The advantage for you is that it then becomes regular.

Then finally I would also suggest to add a separate integer division operator // in the syntax like in Python, perhaps in a separate PR.
