### ISSUE TITLE
restore: reuse batcher over multiple entries

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#63928]
**Describe the problem**

Today the restore data processor processes each span entry in its own sst_batcher. In our performance tests, we don't see major drawback of this approach. However, when restoring incremental backups, entries may be smaller than a full backup (since makeImportSpans will split them up into spans that are covered by 1 set of files). It would be better if each restore data processor maintained one sst batcher and just added keys to it. The sst batcher itself could decide when it should flush.

The reason that this change is non-trivial today is that progress is reported back to the coordinator of the restore job based on the bulk summary provided by the sst batcher upon each flush. This should be updated so that either a) the restore data processor maintains its own bulk op summary that it can report back to the coordinator or b) update the interface to the sst batcher to store and reset its bulk op summary on some other cadence than over the lifetime of the summary or Reset() of the batcher.

**To Reproduce**

This hasn't been observed in practice yet, and is mainly just theoretical today. Restoring a backup with many incremental layers may reveal this issue.

gz#7731

Jira issue: CRDB-6827

**Comment by adityamaru** [comment]
Some notes after an online conversation with @pbardea. The work to parallelize the processing of import spans makes reasoning about a single, long-lived sst batcher difficult.

- A per data processor SST batcher would result in workers adding out-of-order KVs. If the KVs span range boundaries then the SST batcher would produce several small SSTs.
- A per worker SST batcher could result in overlapping SSTs. This in turn would lead to more compactions at the storage level.
- Considered using a BulkAdder so that we can throw concurrent, out-of-order KVs at it, but the current implementation of the BulkAdder is not thread safe.

**Comment by shermanCRL** [comment]
Is this something we intend to pursue? Has it been obviated by other work in the meantime?
