### ISSUE TITLE
restore: many AddSSTable requests are not handled locally

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#63924]
**Describe the problem**

Adding logging to https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/store_send.go#L58, revealed that many AddSSTable requests are not handled locally as would be expected. When logspying for the added logging on node 1:

```
I210420 13:50:39.675510 166144 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 9
I210420 13:50:39.916820 166237 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 10
I210420 13:50:40.608136 166453 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 4
I210420 13:50:44.367269 167530 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 3
I210420 13:50:45.875002 167985 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 7
I210420 13:50:46.060515 168040 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 2
I210420 13:50:46.580769 168191 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 8
I210420 13:50:48.680334 6801 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 1
I210420 13:50:52.835439 169960 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 7
I210420 13:50:53.349780 170114 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 9
I210420 13:50:58.754842 171531 kv/kvserver/store_send.go:58 ⋮ [n1,s1] got req from 2
```

(This was run on top of https://github.com/cockroachdb/cockroach/pull/63875, which ensures that the flow correctly routes entries from the split and scatter processor to the appropriate range router.)

This might be caused due to either the ranges were rebalanced after the initial split and scattering of the ranges, or that the split and scatter processor is not correctly identifying the location of the scattered entries. Today, it gets this information from the returned `RangeInfo`s on the split and scatter request.

**To Reproduce**

`roachtest run restore2TB/nodes=10` with added logging in the store_send.go listed above, logging the gateway node of the request.

**Expected behavior**
Most requests should be served locally (aka on the same nodes as the restore data processor that issued them).

**Next steps**
Adding logging to track where replicas really are after they are scattered and whether they move by the time the corresponding AddSSTable request is issued may shed some more light on what's going on here.

gz#7731

**Comment by adityamaru** [comment]
Couple of observations:
- Removing the sub chunking in https://github.com/cockroachdb/cockroach/pull/63471/files#diff-920f297c9485022d787aec0116432d7cafaa461a4e005311902d91e850195298R341 seems to alleviate some of the remote AddSST requests. Not sure if you were running with the subchunking, but with:

```
// TODO(pbardea): This tries to cover for a bad scatter by having 2 * the
	// number of nodes in the cluster. Is it necessary?
	splitScatterWorkers := 2
	for worker := 0; worker < splitScatterWorkers; worker++ {
		g.GoCtx(func(ctx context.Context) error {
			for importSpanChunk := range importSpanChunksCh {
				chunkDestination := importSpanChunk.destination
				log.Infof(ctx, "processing a chunk")
				for i, importSpan := range importSpanChunk.entries {
					log.Infof(ctx, "processing a span [%s,%s)", importSpan.Span.Key, importSpan.Span.EndKey)
					var splitKey roachpb.Key
					if i < len(importSpanChunk.entries)-1 {
						splitKey = importSpanChunk.entries[i+1].Span.Key
					}
					destination, err := scatterer.splitAndScatter(ctx, flowCtx.Codec(), db, kr,
						splitKey, importSpan.Span.Key, false /* randomizeLeases */)
					if err != nil {
						return err
					}

					if chunkDestination != destination {
						log.Infof(ctx, "%s: ASSERTION FAILED %d != %d", restorePerfInvestigation,
							chunkDestination, destination)
					}

					scatteredEntry := entryNode{
						entry: importSpan,
						node:  destination,
					}

					select {
					case <-ctx.Done():
						return ctx.Err()
					case ssp.doneScatterCh <- scatteredEntry:
					}
				}
			}
			return nil
		})
	}
```
I think I'm seeing far less misses:
<img width="1596" alt="Screen Shot 2021-04-22 at 1 33 37 PM" src="https://user-images.githubusercontent.com/13837382/115716391-21ccaf80-a347-11eb-99b8-508417f5c09e.png">
<img width="1603" alt="Screen Shot 2021-04-22 at 1 33 19 PM" src="https://user-images.githubusercontent.com/13837382/115716396-242f0980-a347-11eb-8ca4-cc7d40d90d72.png">


- logspying borks the AddSSTable sent rate for a node 🤦  I've added some logging to track how long a processor is taking on remote AddSSTs vs local AddSSTs. Going to let the restore run and then inspect the debug zip.

**Comment by adityamaru** [comment]
Some more ammo proving that we're not really missing requests. I have another run that will print how many requests we processed so that we can calculate a rate of local vs remote requests. Ignore the "rate" in the screenshots below it is incorrect, but the time spent processing local vs remote requests are accurate and seem to suggest far more of them are local than remote.

<img width="1771" alt="Screen Shot 2021-04-22 at 3 22 30 PM" src="https://user-images.githubusercontent.com/13837382/115734187-8132bb80-a357-11eb-9cb7-1f1cecb19e37.png">
<img width="1779" alt="Screen Shot 2021-04-22 at 3 25 28 PM" src="https://user-images.githubusercontent.com/13837382/115734324-9c053000-a357-11eb-9e8b-92af91194766.png">

**Comment by adityamaru** [comment]
For posterity a restore2TB saw the following local vs remote requests:
```
n9: 1450 entries took ‹36.942417165s› (requests: 55) to process remote AddSSTable and ‹11m50.25379643s› (requests: 1395) to process local AddSSTable
n8: 1450 entries took ‹1m42.007663088s› (requests: 117) to process remote AddSSTable and ‹10m43.615405168s› (requests: 1333) to process local AddSSTable
n7: 1450 entries took ‹1m17.082518481s› (requests: 90) to process remote AddSSTable and ‹11m49.378188487s› (requests: 1360) to process local AddSSTable
```

The above shows that we are not really missing that many AddSSTableRequests, most of them are being served locally following the split and scatter, as we expected.
The above data translates to `local 0.5s/req and remote ~0.67s/req`. It's important to remember that this is not a geo distributed cluster, but the conclusion is that we are not performing too many suboptimal remote AddSST requests, and even when we are, the cost is marginally higher.

**Comment by adityamaru** [comment]
Ran a restore2TB where we ignored the chunk destination suggested by the scatter request, and instead sent all the addsstable requests to the node on which we ran the split and scatter processor. We ran this experiment to see if the distribution was more uniform and the workers would stop dropping off sooner. The conclusion is yes, workers work for longer probably because the distribution is more even:

![image](https://user-images.githubusercontent.com/13837382/115778306-72aec900-a384-11eb-8d88-b5db731a4578.png)

BUT as expected, we're sending a lot more remote AddSST requests. In a geo distributed cluster this could really add up and slow down restore. If we can make the distribution more even AND not send too many remote AddSST requests then we end up in a better spot. Stay tuned 😃
