### ISSUE TITLE
Raft should never "lose" proposed commands

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#640]
Currently, it's possible to submit a command to raft and never hear back. This leaves a client waiting, but more importantly, ties up an RCP subsystem goroutine indefinitely. To see this in action, re-enable storage/client_merge_test.go:TestStoreRangeMergeNonConsecutive.

It's simplest to run the test with:

`go test ./storage -v -alsologtostderr -run TestStoreRangeMergeNonConsecutive -timeout 1s`

**Comment by bdarnell** [comment]
`TestStoreRangeMergeNonConsecutive` is doing strange things with internal state, so problems here are representative of real issues. The test calls `RemoveRange`, which stops raft processing for the range without removing the replica from the range descriptor. We might need better error handling for this case, but it would be at the store (or maybe sender) level instead of raft. 

I can no longer reproduce a failure like the one that motivated this issue, so I'll send a PR to re-enable the test.
