### ISSUE TITLE
cli/demo: allow Katakoda end-users to use the DB console for `demo` servers with global latencies

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#64148]
Follow-up to https://github.com/cockroachdb/cockroach/issues/52059#issuecomment-771615312.

We are trying to build an in-browser version of this 21.1 multi-region tutorial: https://www.cockroachlabs.com/docs/v21.1/demo-low-latency-multi-region-deployment.html. However, there's a problem: The DB Console can't be reached from Katacoda right now because `cockroach demo` listens only on `localhost`, whereas Katacoda requires the process to listen on all IPs. Without the DB Console, it's not possible to show users the simulated network latencies and the change in SQL performance before and after applying the multi-region patterns. 

It'd be great to add an option to make `demo` listen on all IPs. 

Jira issue: CRDB-6923

**Comment by jseldess** [comment]
cc @awoods187, @ajstorm, @knz

**Comment by knz** [comment]
I think we should step out a little bit and question the idea to run a 9-node cluster inside a single process in katakoda.

Just looking at latencies is one thing, however as soon as a user is going to see there are multiple nodes they will also start to expect performance scaling across nodes too. 

A single demo process will fail to deliver on that front; or worse, crash due to insufficient resources.

**Comment by jseldess** [comment]
@knz, do you feel the same of the existing docs tutorial, which is all local? In Katacoda, we could provision a larger machine, if needed.

**Comment by knz** [comment]
The existing doc tutorials are silent about requirements on the user's computer hardware. So if a user is disappointed they will properly remain in doubt about whose fault it is. They share the responsibility.

With a CRL-hosted solution, the responsibility that everything works is ostentibly taken by CRL. If the outcome is sub par, the user will be disappointed.

Over-provisioning the katakoda machine is certainly an option, but I wonder what's the $$ price tag.

**Comment by jseldess** [comment]
You raise good questions, @knz. But seperate from this particular multi-region tutorial, it would still be good to force `demo` to listen on all IPs so we can use it in Katacoda. Most other Katacoda tutorials are far less complex. For example, the SQL playground is an ideal case for `demo`, but we need to use `cockroach start-single-node` so that the DB Console is reachable: https://www.cockroachlabs.com/docs/v20.2/sql-playground.html

**Comment by knz** [comment]
a couple of points

1) I still think we are letting the tail wag the dog. The reason why `cockroach demo` is so restricted is because letting an *unsecured* HTTP server on a multi-user network is a security discouraged practice: it can incur instability and detrimental UX. 

(I think if the demo DB console was properly secured using TLS, this wouldn't be an issue.)

As a reminder, the reason why we do not enable TLS is because web browsers do not appreciate a self-signed TLS certificate. Perhaps we could find a way forward if katakoda could help us provision TLS certs with a proper CA?

2) I have requested before whether katakoda would help us with this TLS situation. If, say, katakoda was able to hide the unsecured HTTP server behind a firewall, then subsequently serve the HTTP service over a public IP address using a TLS-enabled proxy, this would also be fine. Are they not providing such a service?

3) in case katakoda doesn't help with this, can we perhaps run such a TLS proxy ourselves? For example, the `nginx` program can be configured on the same machine. This would not require changing crdb to listen on more addresses, as the `nginx` process could connect locally.

**Comment by knz** [comment]
I also have renamed the issue to properly reflect the problem we're trying to solve.

@bdarnell @aaron-crl can you review my comment above and see if I covered all grounds? Also if you have alternate solution, I'd like to hear them.

**Comment by bdarnell** [comment]
> I have requested before whether katakoda would help us with this TLS situation. If, say, katakoda was able to hide the unsecured HTTP server behind a firewall, then subsequently serve the HTTP service over a public IP address using a TLS-enabled proxy, this would also be fine. Are they not providing such a service?

They already do. The katacoda interface embedded in https://www.cockroachlabs.com/docs/v21.1/sql-playground.html allows access to the DB console over HTTPS with a browser-trusted cert (the cockroach process itself is using a self-signed cert; katacoda is proxying). All we need to do is for `demo` to listen on all IPs instead of only localhost.

**Comment by awoods187** [comment]
@knz do you think this is something we can move forward with? We'd like to be able to do this to augment the marketing launch of 21.1

**Comment by knz** [comment]
> The katacoda interface embedded in cockroachlabs.com/docs/v21.1/sql-playground.html allows access to the DB console over HTTPS with a browser-trusted cert

Do y'all know if the katakoda proxy is able to connect to the crdb HTTP port using TLS too, with a self-signed cert?

**Comment by bdarnell** [comment]
It appears to be doing so in that link - scroll back in the terminal and you can see it creating the self-signed certs.

**Comment by knz** [comment]
Thank you.

Can we then say that the `demo` command listens on all addresses with the requirement that the UI port must use TLS?

**Comment by bdarnell** [comment]
I think I'd still make it localhost-only by default but it's fine to add an option for this.

**Comment by knz** [comment]
ok then we can make progress (answering Andy's concern)

**Comment by jseldess** [comment]
That's great news. @awoods187, do we expect this to be in a binary that I can use for Katacoda before the 21.1 marketing GA date? It's fine for the binary not to be officially release yet. We just tell Katacoda which binary to fetch.

**Comment by bdarnell** [comment]
Probably too late for a new feature like this in 21.1.0. But you could probably use `nc` for a workaround in the meantime: run `nc -l -p 8081 -s 0.0.0.0 localhost 8080` and then use `:8081` in the console links instead of `:8080`.

**Comment by knz** [comment]
Yes, a nc-based solution is also a good solution, and it would also work with v20.x clusters and previous versions.

**Comment by jseldess** [comment]
Interesting. I'll give that a try in a bit.

**Comment by jseldess** [comment]
@bdarnell, tried the `ns` approach, but I’m getting errors that `-l` and `-s` aren’t valid together. The man doc also says that:
```
     -l      Used to specify that nc should listen for an incoming connection rather than
             initiate a connection to a remote host.  It is an error to use this option in
             conjunction with the -p, -s, or -z options.  Additionally, any timeouts spec-
             ified with the -w option are ignored.
```

I’m not sure how to adjust the command: `nc -l -p 8081 -s 0.0.0.0 localhost 8080`. Let me know if you have ideas

**Comment by knz** [comment]
Ok Ben and I were mistaken, `nc` cannot be used as a proxy unfortunately. It can either listen and interact with the terminal, or interact with the terminal and connect, but it cannot do both (let alone multiple times, as would be needed with a proxy).

The general approach of using a separate program to expose a port is still possible, with a program designed to act as a TCP proxy. There are many such programs (just not `nc`), for example https://github.com/nccgroup/tcpprox.

Regardless, meanwhile I will still work on a patch as discussed above.

**Comment by bdarnell** [comment]
Right. I misread something in the `nc` man page that made me think it could work in this mode too. We can use `iptables` if it works in this environment, or it looks like `socat` can work as a proxy (not as common as `nc` but we should still be able to install it). `socat TCP4-LISTEN:8081,fork,reuseaddr TCP4:TCP4:127.0.0.1:80` (copied from https://www.redhat.com/sysadmin/getting-started-socat. That doubled `TCP4:TCP4:` looks like it might be a typo)

**Comment by knz** [comment]
I am currently investigating this.

Note that if we change the behavior here, the user will still not have optimal UX when looking at the output of `\demo ls` to list the server addresses: the listed address for the web UI will be a private IP address, not the katakoda HTTPS proxy address.
(If my understanding of katakoda networking is correct)

If we want to smoothen out the UX, in addition to the strict networking change requested here, we will need to teach the `demo` shell about the difference between "listen" and "advertise" addresses. 

Please confirm if my understanding is correct.
