### ISSUE TITLE
stability: node stalled on stopper throttling task from storage/intent_resolver.go:292 due to semaphore

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6415]
build sha: 104228c

Beta cluster has a node (`104.196.13.122`) stuck for a while, with the only indication in the logs being
```
I160429 22:02:54.378010 stopper.go:202  stopper throttling task from storage/intent_resolver.go:292 due to semaphore
```

Lots of long-running tasks as well: https://104.196.13.122:8080/debug/requests?fam=tracing&b=-1&exp=1

I'll leave it up for now if someone wants to take a look.

**Comment by bdarnell** [comment]
It looks similar to #6409, in which two ChangeReplicas in rapid succession leave a node with a version of the range descriptor that is two versions behind. The long-running tasks are stuck in a cycle of NotLeaderErrors (each of which takes 3 seconds to generate because they're talking to a removed node: #5789). 

```
2016/04/29 15:27:23.298134	25663.868438	txn coordinator
15:27:23.298202	 .    67	... meta descriptor lookup
15:27:23.298208	 .     6	... looked up range descriptor
15:27:23.298226	 .    18	... sending RPC to [/Table/53, /Table/54)
15:27:26.298432	3.000206	... error, trying next peer
22:35:01.418980	 .   150	... (34194 events discarded)
22:35:01.418990	 .    10	... sending RPC to [/Table/53, /Table/54)
22:35:04.419143	3.000153	... reply error: *roachpb.NotLeaderError
22:35:04.419149	 .     6	... meta descriptor lookup
22:35:04.419151	 .     2	... looked up range descriptor
22:35:04.419161	 .    11	... sending RPC to [/Table/53, /Table/54)
```

The NotLeaderErrors are supposed to invalidate the range descriptor cache, but we see that the range descriptor lookup never takes more than a few microseconds, suggesting that it's always hitting the cache. I think the problem is the cloning of the eviction token in https://github.com/cockroachdb/cockroach/blob/2f89e7860ada6f76e253481b519c95b647ce564a/kv/range_cache.go#L360. Each of these NotLeaderErrors is reinserting their eviction token's second (i.e. intent) descriptor, so we're never going back to the source of truth until someone wins this race. I think the eviction token needs to clear its callback function after running it once.

**Comment by nvanbenschoten** [comment]
@bdarnell after a quick look into this, I think your analysis is correct. The intention of the shared eviction tokens was that "evicted" state would be consistent across them, but that clearly isnt happening with the boolean flag value. An earlier iteration actually used a `sync.Once` construct to achieve this, but it was removed when we needed to know if the "Once" callback had been run (_see below_). Now that we no longer care about this in `makeLookupRequestKey`, it seems like replacing part of [EvictAndReplace](https://github.com/cockroachdb/cockroach/blob/2f89e7860ada6f76e253481b519c95b647ce564a/kv/range_cache.go#L232) with a `sync.Once` is the easiest solution. I will write up a PR to make this change, and I'll also try to think of a good way to assert the proper behavior in a test.

On a side-note, I came to the conclusion that atomically checking if a `sync.Once` has been run is simply not possible without using another synchronization mechanism, at which point the `sync.Once` becomes cumbersome and unnecessary. If you know a way to achieve this, I'd be very interested.

**Comment by bdarnell** [comment]
No, there is no way to query if a `sync.Once` has been run. 

The reason the `evicted` flag is not consistent is that we pass `evictionTokens` by value (as a member of `lookupResult`). One way to address this is to change `evictedLocker` from a `Locker` (pointer) to a `Mutex` (value). Then `vet` will ensure that `evictionTokens` are always passed by value and their internal state is shared. This would need to be done if the token contains a `sync.Once` as well, but I don't think there is any linter support for that.

**Comment by nvanbenschoten** [comment]
Why would we need to pass the `evictionTokens` by reference if we were using a `sync.Once`? In that case, their internal state would not need to be shared (because we would no longer need an `evicted` flag).

**Comment by bdarnell** [comment]
`sync.Once` is not copyable, so *something* has to be passed by reference: either the `evictionToken` contains a `*sync.Once` instead of a value, or the `evictionToken` itself is passed by reference. I think it would be more idiomatic for the `sync.Once` to be a value (the `Once`, the function it is used to call, and all the state that function closes over make a unit that should be at the same level, instead of having multiple `evictionTokens` that share a `Once` but have function fields that appear to be independent)

I was wrong about the lack of linter support: `sync.Once` contains a `Mutex`, so the check for copying a mutex should apply to `Once` as well.

**Comment by nvanbenschoten** [comment]
Right, when I said "using a sync.Once", I was meaning a `*sync.Once`. But I think you've convinced me that passing the entire `evictionToken` by reference instead is a safer approach (with a `sync.Once` value). It prevents any strange cases where the tokens' states would get out of sync, and will guarantee that we dont face an issue like this again if anything ever gets added to the `evictionToken` struct that also needs to be consistent.
