### ISSUE TITLE
ui: job detail page stuck on loading animation forever

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#64281]
**Describe the problem**

a job detail page like http://my-cluster:26258/#/jobs/653624056872730625 just hangs with the loading animation spinner but no job

**To Reproduce**

1. Navigate to a running `create stats` job detail page, copy the URL.
2. On the jobs list page, change the filter to something else, say, imports or maybe also "all", which excludes stats jobs.
3. go to the URL of the stats job detail.

**Expected behavior**
Load the job detail page for the job in the URL.

**Environment:**
 - CockroachDB version: master (9431aa29a9)
 - Client app: safari

**Comment by oeph** [comment]
@dt I had a brief look at this - it is caused by the combined state of the jobs overview and the job details data handling. There might not be a suitable (not hacky) solution to do this without introducing a separate job endpoint that can return the details for a job by a given id. Is this something that should be looked into?
