### ISSUE TITLE
sql: CHECK constraints should disallow impure functions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6429]
It is currently possible (and arguably [sometimes useful](https://gitter.im/cockroachdb/cockroach?at=5725898c60e2f3e873665fe2)) to use impure functions like `cluster_logical_timestamp()` in `CHECK` constraints. However, these constraints make assumptions about exactly when the constraint is evaluated, and could fail if it were evaluated other than at the time of insert or update. I think we should disallow all impure functions in `CHECK` constraints to avoid this.

**Comment by knz** [comment]
@bdarnell just to clarify, do you think the same argument could be used regarding DEFAULT expressions? For example when you add a column to a table that already exists with a DEFAULT value, I do not believe it is specified that DEFAULT will be evaluated during the ALTER TABLE execution; it might be evaluated only later when the rows are actually queried for the first time.

I personally believe DEFAULT and CHECK are and should be setting the same expectations as to eval time. And then since we allow (and users expect) `NOW()` to be a valid DEFAULT expression, we might want to allow it in `CHECK` too.

**Comment by dt** [comment]
IIRC `DEFAULT` is evaluated during the backfill step of the schema change, not when the row is read.

**Comment by bdarnell** [comment]
No, I don't think the same argument applies to DEFAULT expressions. Defaults are evaluated exactly once per row, either when it is inserted or when the column is added. (We should specify that defaults are evaluated during the ALTER TABLE. Otherwise, an ALTER TABLE that changes the default would have to be responsible for ensuring that all pre-existing rows have been set to the old default before the change takes effect). CHECKs may be evaluated multiple times, and it's important that a row that passed its CHECK when it was last inserted or updated not fail the CHECK later. If a CHECK fails during an insert or update, we abort the change, but what can we do if it fails later, for reasons unrelated to a change being made to the data?

**Comment by spencerkimball** [comment]
@knz I'm assigning this to you. Could you re-assign as appropriate if it is indeed slated for 1.0 inclusion. Otherwise, unassign and set milestone to `Later`.

**Comment by dt** [comment]
@cuongdo I pulled the 1.0 tag off this, unless you think it's a blocker.

**Comment by jordanlewis** [comment]
This is permitted by Postgres, so we probably should continue to support it. Users will probably understand that this is silly and not do it unless they know what they're doing.
