### ISSUE TITLE
kv,sql: expose store IDs and their location on disk and other parameters in vtable

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64326]
There is currently no mechanism to map back store Ids to locations on disk, max size and the other command-line parameters.

The workaround is to assign different store attributes in the command line to each store, and then map the store ID to attribute using APIs, then attribute to file path using the command line.

It would be easier to integrate the two steps somehow.

**Comment by dbist** [comment]
I imagine this being useful to identify slow stores and pinpoint hot ranges.

**Comment by chriscasano** [comment]
I’m noticing more customer and prospect evaluations using multiple stores per node.  Getting ahead of this, it would be good to see the mapping of store id to mount points when debugging issues, especially with disks and mount points.  The only other way to find the store id to the mount is by looking through the rangelog which seems kind of ugly.

**Comment by knz** [comment]
cc @mwang1026 for re-triage

**Comment by nvanbenschoten** [comment]
We currently expose store attributes and capacity information about each store in the `crdb_internal.kv_store_status` virtual table. [Attributes are arbitrary strings](https://www.cockroachlabs.com/docs/v21.1/configure-replication-zones#descriptive-attributes-assigned-to-nodes) that users can specify at startup time. So the following is all supported today:
```
➜ ./cockroach start-single-node --insecure --store=path=cockroach-data,attrs=mount=/mnt

➜ ./cockroach sql --insecure

root@:26257/defaultdb> select store_id, attrs, capacity, available from crdb_internal.kv_store_status;
  store_id |      attrs      |   capacity    |  available
-----------+-----------------+---------------+---------------
         1 | ["mount=/mnt1"] | 1000240963584 | 258395459584
```
@knz could you clarify what more this issue is asking for? Perhaps you're suggesting that we implicitly attach a few attributes to each store, like mountpoint and some other information.

**Comment by lunevalex** [comment]
I am going to close this based on the latest comment from @nvanbenschoten. @knz if you feel this is incorrect, please re-open with an update.
