### ISSUE TITLE
*: properly handle file path != package path  when looking at stack traces

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64383]
1. In multiple places inside CockroachDB (not just in tests) we look at stack traces and take decisions based on the **package path** that a trace entry corresponds to. For example, the `callers` package does this.

2. Separately,  we also like to decorate log messages and error payloads with prefixes that indicate in which file something happened. For this, we want that identically named files in different directories (e.g. `roachpb/errors.go` and `pgerror/errors.go`) can be distinguished at run-time.

**However**

Regarding point 1, we *mistakenly* assume that the **file name** corresponding to a stack PC contains the package path, and **mistakenly derive a package path from the file path** by truncating the last path component. This is incorrect.

This is incorrect because e.g. go module versioning causes go package paths and file paths to diverge. Also in a sandboxed build, the paths get mangled for the sake of reproducibility.

Regarding point 2, we cannot assume files can be disambiguated at run-time because e.g. in a sandboxed build, the files will be compiled in different sandbox and their path fully truncated (see discussion in #64379).

**What can we do about this**

Regarding point 1, we need to derive the package path from the **function name** (which is prefixed by the package path), not the file name. The package `sentry-go` does this internally, for example, and we should modify the rest of our code to do the same.

Regarding point 2, it is a bit more complicated. We need to do approximately 3 things:

- clarify in the various places where the file name is returned (e.g. `callers.Lookup`) that the file name is very approximate information.
- extend these APIs to also return the package path as a separate return value, and encourage its use in docstrings.
- modify the code that previously only embedded the file path, to either: embed the package path instead of file path, or embed both side-by-side (e.g: `roachpb/errors.go`, `NewErrorf`).

**Comment by knz** [comment]
cc @bdarnell @tbg - can you review the above and check if there are additional considerations we should take care of?

(For context, I arrived to this issue after sleuthing through why a bunch of our tests were failing under `bazel` -- see #61913 and  #64379 and https://github.com/cockroachdb/errors/issues/70 )

**Comment by knz** [comment]
An idea from [this comment](https://github.com/cockroachdb/cockroach/issues/64379#issuecomment-830067057):

> modify `callers` and the other packages to construct a fake file path by concatenating the symbol path with the file base name. It wouldn't be correct for renamed packages, but since we have a 1-to-1 mapping inside crdb between absolute paths and package paths currently, it may be sufficient.

**Comment by tbg** [comment]
I'm a little lost here. I think I understand the basic problems and if I wrote them down in plain language it would be

1. when `vendor/foo/bar` calls `runtime.Caller` it gets `/path/to/vendor/foo/bar/somefile.go` back, and not `/path/to/foo/bar`. But we want to extract package paths, so the thing we *really* want is `foo/bar`.
2. bazel completely strips the out-of-build-root prefix, so in bazel we get a file `vendor/foo/bar` instead of `/path/to/vendor/foo/bar`. This doesn't need a vendored dep to cause issues, it also changes all the filenames for non-vendored callers in the same way.

You are probably right to conclude that we shouldn't be using the file names to resolve package paths in the first place. Is there a canonical way to do it and then we just use that? I assume we need to start with a program counter and that then we hit it with various methods in https://golang.org/pkg/debug/gosym/ to arrive at a [Sym](https://golang.org/pkg/debug/gosym/#Sym) whose methods then provide the right answers. Concretely, it looks like we want to grab the `Table`, then call `PCToFunc`, and the resulting `Func` has a symbol. Is that about right? If it's as straightforward as that, that sounds preferrable over trying to hack our path-based handling to handle both vendoring and bazel graciously. It probably isn't as easy, as I don't know where you get the `Table` from and besides, this sounds worrying:

> Starting with Go 1.3, the Go symbol table no longer includes symbol data.

**Comment by tbg** [comment]
Ok. I'm not fully confident here without an full audit neither, but my expectation is that it's fine. We'll change some of the packages in the logs (vendor/..../raft) and we'll do some test finagling, but in the end the package path is what we've always wanted as far as I can tell.

**Comment by rickystewart** [comment]
Any issues with me picking this up and working on it? I'll probably need the support of someone who's better at golang at least for review, but I'm fine doing most of the work here given that the primary benefit is for bazelfication.

I'm probably not capable of doing an "audit" as described above, but if there's a process I can go through which will give us high confidence the change is correct (i.e., making sure unit tests pass in `go test` as well as Bazel, plus that `roachtest`s aren't broken or whatever?), then I'm happy to do that.

**Comment by knz** [comment]
The first order action you can carry out is to rework the util/caller package to use runtime.CallersFrame and extract the package path, as discussed.

However that's just one of the 3-4 projects needed here.

I can probably also help by reworking the errors library to report package paths in stack frames. Then we'll need to rework all the unit tests in the logcrash package.

Then we'll need to work on logging, and on the pgerror package.

Then after all that we can look how far we've got.

**Comment by rickystewart** [comment]
Just following up on that request, I tried to take the first step here and the unit tests immediately started failing. 😅 

```
diff --git a/pkg/util/caller/resolver.go b/pkg/util/caller/resolver.go
index ce3aaab0d6..e3302fd27c 100644
--- a/pkg/util/caller/resolver.go
+++ b/pkg/util/caller/resolver.go
@@ -101,15 +101,28 @@ func NewCallResolver(re *regexp.Regexp) *CallResolver {
 // Lookup returns the (reduced) file, line and function of the caller at the
 // requested depth.
 func (cr *CallResolver) Lookup(depth int) (file string, line int, fun string) {
-	pc, file, line, ok := runtime.Caller(depth + 1)
-	if !ok || cr == nil {
+	pcs := make([]uintptr, 10)
+	n := runtime.Callers(depth + 1, pcs)
+	if n == 0 {
 		return dummyLookup.file, dummyLookup.line, dummyLookup.fun
 	}
+	pc := pcs[0]
+
 	cr.mu.Lock()
 	defer cr.mu.Unlock()
 	if v, okCache := cr.cache[pc]; okCache {
 		return v.file, v.line, v.fun
 	}
+
+	frames := runtime.CallersFrames(pcs)
+	frame, _ := frames.Next()
+	file = frame.File
+	line = frame.Line
+
+	if frame.Func != nil {
+		fun = frame.Func.Name()
+	}
+
 	if matches := cr.re.FindStringSubmatch(file); matches != nil {
 		if len(matches) == 1 {
 			file = matches[0]
@@ -120,13 +133,10 @@ func (cr *CallResolver) Lookup(depth int) (file string, line int, fun string) {
 		}
 	}
 
-	cr.cache[pc] = &cachedLookup{file: file, line: line, fun: dummyLookup.fun}
-	if f := runtime.FuncForPC(pc); f != nil {
-		fun = f.Name()
-		if indDot := strings.LastIndexByte(fun, '.'); indDot != -1 {
-			fun = fun[indDot+1:]
-		}
-		cr.cache[pc].fun = fun
+	if indDot := strings.LastIndexByte(fun, '.'); indDot != -1 {
+		fun = fun[indDot+1:]
 	}
+
+	cr.cache[pc] = &cachedLookup{file: file, line: line, fun: fun}
 	return file, line, fun
 }

```

What I see then is that `go test ./pkg/util/caller` fails with the following:

```
--- FAIL: TestDefaultCallResolver (0.00s)
    resolver_test.go:48: unexpected caller reported: 
```

... i.e., the function name is empty. I've investigated and I've seen that the `Func` pointer in the `Frame` object that we're inspecting is `nil`. This can happen due to inlining, I guess? Not sure how to resolve it, though -- the [documentation](https://golang.org/pkg/runtime/) wasn't helpful in allowing me to determine a workaround. Presumably I'm just missing something obvious, but I don't have enough low-level Go knowledge to be able to figure it out at the moment.

**Comment by knz** [comment]
we've addressed this
