### ISSUE TITLE
FK reference requires redundant constraint if subset is unique

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#64619]
Suppose we have a classic `orders` and `items` schema where `orders` have an account ID, but we also denormalize the account ID into the `items` table (perhaps for partitioning purposes). We want to include the account ID in the foreign key to `orders` to ensure that the denormalized value matches (the one in `items` matches the one in `orders`).

```
CREATE TABLE accounts (
  account_id int PRIMARY KEY
);

CREATE TABLE orders (
  order_id int PRIMARY KEY,
  account_id int NOT NULL REFERENCES accounts (account_id)
);

CREATE TABLE items (
  item_id int PRIMARY KEY,
  order_id int NOT NULL,
  account_id int NOT NULL REFERENCES accounts (account_id),
  FOREIGN KEY (order_id, account_id) REFERENCES orders (order_id, account_id)
);
```
This fails with
```
ERROR: there is no unique constraint matching given keys for referenced table orders
SQLSTATE: 23503
```
We can fix this be creating a `UNIQUE` index on `(order_id, account_id)`, but this is redundant since `order_id` is already unique (as the primary key) and thus any combination of this with other values would also be unique.

**Comment by jordanlewis** [comment]
I don't think this is actually allowed by the SQL spec, which requires that a foreign key have a complete unique constraint on the referenced table.

For example, this doesn't work in Postgres either. I'll close this because I don't think this is something we'll be supporting. But, I'm very curious if you find other databases that do support this situation.
