### ISSUE TITLE
Use net/rpc for the Go cockroach client instead of http

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#647]
RPC networking is significantly faster than http networking. We're already supporting both interfaces due to using RPC for internode communication. Requiring other languages to use RPC would be burdensome, but not using it for the Go client because it isn't easy to use from other languages is unnecessarily punitive to the Go client.

**Comment by bdarnell** [comment]
We should explore gRPC (and plain protobufs over HTTP/2) before making a choice that would make the go client diverge from the other implementations. I'm OK with there being a couple of "tiers" of clients (e.g. ones that can use protobufs vs those that use json), but I'd strongly prefer not to make the go client unique.

Are there any go-isms on the wire if we use the net/rpc framework or is it feasible to implement our protobuf-based codec from other languages?

**Comment by petermattis** [comment]
There are no go-isms on the wire if we use the net/rpc framework. The proto is very simple sets of framed "header" and "body" where the frame is a varint encoded length followed by length bytes and the contents are an encoded proto. Very similar to the sake stuff at Square though without all the connection handling complexity.

Probably worthwhile to benchmark the HTTP/2 stuff that is coming to Go.

**Comment by bdarnell** [comment]
Another point to consider: our current use of net/rpc for raft transport is fairly dumb. Messages are sent as RPC requests with empty responses, even though the raft protocol is defined in terms of request/response pairs (a request message usually results in one response, although the etcd/raft implementation does not facilitate matching them up, and sometimes the one-to-one correspondence is broken). net/rpc does not allow for server-initiated messages, so response messages are sent as a "request" on a separate channel in the other direction. Protocols that support server-initiated messages would be a better fit for raft; this includes GRPC (via its streaming mechanisms) as well as anything based on websockets (Plain HTTP/2 would also work although it would be more cumbersome)

**Comment by petermattis** [comment]
I whipped up a client.RPCSender that allows the client to talk to our servers using our RPC transport. The old numbers are with HTTP and the new numbers are with RPC.

```
benchmark                               old ns/op     new ns/op     delta
BenchmarkClientScan1Version1Row         628375        358319        -42.98%
BenchmarkClientScan1Version10Rows       1379324       1046883       -24.10%
BenchmarkClientScan1Version100Rows      7853647       6872666       -12.49%
BenchmarkClientScan1Version1000Rows     62756522      52614956      -16.16%

benchmark                               old MB/s     new MB/s     speedup
BenchmarkClientScan1Version1Row         1.63         2.86         1.75x
BenchmarkClientScan1Version10Rows       7.42         9.78         1.32x
BenchmarkClientScan1Version100Rows      13.04        14.90        1.14x
BenchmarkClientScan1Version1000Rows     16.32        19.46        1.19x
```

**Comment by spencerkimball** [comment]
@petermattis should we enable this with an option or just close this issue?

**Comment by petermattis** [comment]
We should discuss further. Ben's concerns are valid, but the speed increase cannot be ignored.

**Comment by cloudmode** [comment]
I was quite frankly surprised when I saw the goClient was using http. In my extremely biased opinion, any rpc-style comm is inherently better than http. I personally avoid http at all costs. And I doubt http2 will give that much of a performance improvement.

**Comment by spencerkimball** [comment]
HTTP sure is pokey. On the other hand, it's an absolutely bedrock standard that everyone understands and agrees on, which is why it's our default from the server side for clients. Requiring any client to implement an arbitrary RPC protocol is IMO too steep a cost when compared to ~20% performance hit on traffic.

I agree that http2 is unlikely to see any performance improvements as an RPC protocol for our use case.

**Comment by cloudmode** [comment]
I agree that it is a bedrock that everyone understands. But it is very limited, and dumbed down. Do you really need a web designer to understand how to interface with a hardcore key-value store, where the values have to be marshalled/unmarshalled anyway? But you're talking about client drivers. If you intend to make HTTP the interface, why build clients at all? Only client library developers will need to understand the RPC mechanism, and you want those drivers built by people who are smart enough to understand and implement something that isn't so demand driven. 

Specifically I dislike the request/response nature of HTTP. For example, how are clients notified that the server they are connected to has gone down as opposed to just a keep-alive timeout? Does the client have to poll? With an RPC mechanism, you can ping with just your RPC header (say 12-16 bytes) that seems to be the popular way to do it in go.

As you can tell, I'm a big fan of the RPC style. We use an custom application layer RPC protocol that is extremely lightweight, and very easy to learn, because it maps directly to the semantics of our model layer. I think performance is actually only one of the reasons to go RPC style. The others are control and semantics. Once you have your baseline mechanism in place, it's incredibly easy to extend. And I think they are inherently more secure. And the learning curve provides an obstacle/filter that makes sure the people writing the drivers are qualified. I may be a snob about that, but I think of an HTTP server as something very simple. And you could always build a server that uses an RPC driver to map to the HTTP verbs. Layers are good.

**Comment by soheilhy** [comment]
I just came across this issue. I had the same dilemma but have hesitated to replace http endpoints with `net/rpc` for the same reasons listed here. But there is a considerable tput/latency gain with `net/rpc` specially for raft messages.

I finally came up with a connection multiplexer: [cmux](https://github.com/soheilhy/cmux). You can expose one port and serve the both http and rpc/tcp transparently on the same TCP listener:
https://github.com/kandoo/beehive/blob/master/hive.go#L602-L639

At least cockroachdb's go client and multiraft would see a neat performance bump.

Sorry for the spam BTW. :-)

**Comment by tamird** [comment]
This issue is out of date since we no longer expose a kv client, and cli kv commands already use net/rpc rather than http.
