### ISSUE TITLE
sql: Surface FULL SCAN and Database in node_statement_statistics

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#65285]
We already surface whether a statement fingerprint had a FULL SCAN and the default database (used for filtering) in the DB console. We should have this information via SQL in our internal views as well.  

Epic CRDB-7561

**Comment by maryliag** [comment]
We already surface `full_scan` on `crdb_internal.node_statement_statistics`. 
We currently don't have nodes and regions, so we should add those.

**Comment by maryliag** [comment]
@kevin-v-ngo unfortunately regions is a costly statistics and we don't actually calculate during the statements records/statistics. You can see on db console because we have the value on cache, but you won't have the value to add to the statistics table, so I think this parameter should be removed from this issue

**Comment by kevin-v-ngo** [comment]
Sounds good Marylia! Let me create a separate issue to track regions in statement_statistics.

**Comment by maryliag** [comment]
Kevin, you removed the nodes from this issue. We do have the list of nodes, so we can add them, no problem, is just the regions we can't.
