### ISSUE TITLE
kvserver: intent leak with ABORT_REASON_CLIENT_REJECT

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#65458]
As part of deflaking `TestReliableIntentCleanup` for #65447, by retrying the txn on `TransactionRetryWithProtoRefreshError`, we're seeing consistent intent leaks when a `ABORT_REASON_CLIENT_REJECT` error is retried -- even if the failed transaction is explicitly rolled back after the error is returned.

Related to #60585.

**Comment by erikgrinaker** [comment]
I think this is probably what @nvanbenschoten was saying here: https://github.com/cockroachdb/cockroach/issues/60585#issuecomment-837207701

**Comment by erikgrinaker** [comment]
The intents appear to be left over from the last batch that was written. When we call `abortTxnAsyncLocked` due to the failed `CanCreateTxnRecord()`, the txn has `seq=20001`:

```
abortTxnAsyncLocked: "test" meta={id=df32dd3f key="key\x00\x1bL^\xb8" pri=0.00648713 epo=0 ts=1621515682.683519177,0 min=1621515682.683519177,0 seq=20001} lock=true stat=PENDING rts=1621515682.683519177,0 wto=false gul=1621515683.183519177,0
```

However, by the time we discover `ABORT_REASON_CLIENT_REJECT` the txn has `seq=30001`, so presumably it has laid down another 10k intents in the meanwhile:

```
ABORT_REASON_CLIENT_REJECT: "test" meta={id=df32dd3f key="key\x00\x1bL^\xb8" pri=0.00648713 epo=0 ts=1621515682.683519177,0 min=1621515682.683519177,0 seq=30001} lock=true stat=PENDING rts=1621515682.683519177,0 wto=false gul=1621515683.183519177,0
```

Once `CleanupTxnIntentsAsync` is called (once `EndTxn(commit=false)` sent by `abortTxnAsyncLocked` goes through Raft), the txn has an updated sequence number of `seq=30002`, but only 19501 intents:

```
CleanupTxnIntentsAsync: &{"test" meta={id=df32dd3f key="key\x00\x1bL^\xb8" pri=0.00648713 epo=0 ts=1621515682.683519177,0 min=1621515682.683519177,0 seq=30002} lock=true stat=ABORTED rts=1621515682.683519177,0 wto=false gul=1621515683.183519177,0 int=19501 false true}
```

And the intents left behind have sequence numbers >20k, so they were part of the final batch:

```
        	Error:      	found stale intents
        	Messages:   	len=10000 from={{"key\x00\x00\b\xf5\xcc"} id=df32dd3f key="key\x00\x1bL^\xb8" pri=0.00648713 epo=0 ts=1621515682.683519177,0 min=1621515682.683519177,0 seq=21235} to={{"key\x00\xff\xf7\x18j"} id=df32dd3f key="key\x00\x1bL^\xb8" pri=0.00648713 epo=0 ts=1621515682.683519177,0 min=1621515682.683519177,0 seq=24807}
```

There appears to be a race condition here where the heartbeater sends off an `EndTxn(commit=false)` while the final 10k writes are in-flight, but it isn't executed until after the 10k writes have completed. By that time, the request has an outdated view of the intents, and only cleans up the ones it knows about. This happens even with parallel commits and pipelined writes disabled.

**Comment by erikgrinaker** [comment]
Confirmed the above hypothesis by removing the mutex unlock while sending requests, which made intent cleanup reliable in all cases (except for a deadlock when aborting a txn with a high-priority push during synchronous intent resolution, which we can ignore since this proves the point).

@andreimatei @nvanbenschoten I think the appropriate fix here is to register all in-flight writes _before_ sending any write batch, removing the completed writes when the the response is received, and having any `EndTxn(commit=false)` requests wait for the in-flight writes to return (either with success or failure) before adding the lock spans and sending the request. Does that seem reasonable?

**Comment by nvanbenschoten** [comment]
This is a very nice find!

I do have a few questions about the situation and the proposed fix. I see how the `txnHeartbeater` could send an `EndTxn(commit=false)` which does not include all of the lock spans. But do we not also send another `EndTxn(commit=false)` one the in-flight batch returns with the transaction aborted error. Is this full rollback being suppressed on the client? Or is it being ignored on the server because the aborted record already exists?

It's probably worth asking why the `txnHeartbeater` even sends an `EndTxn(commit=false)` in the first place. We say in the code that:
```
// The purpose of the async cleanup is to resolve transaction intents as soon
// as possible when a transaction coordinator observes an ABORTED transaction.
```
So I guess the idea is that if we're sitting in the application holding open an active transaction that gets ABORTED, we want to clean up its intents quickly. But is this needed if we have a request in flight? I guess this request won't necessarily notice that the transaction is aborted, even if the heartbeat loop does. So we want to make sure we clean up soon after the heartbeat loop notices the transaction abort.

Regarding the solution you proposed, I think it would work, but I'd like to understand the trade-offs and possible alternatives.

For context, we record the writes that a request has performed after the fact because we may not know the precise set of spans that it will write to beforehand. This is turning out to important, as it may provide a path forward for https://github.com/cockroachdb/cockroach/issues/64723, so I'd hate to remove this if we can avoid this. This is also mostly true independent of whether we're adding the writes into the `inFlightWriteSet` or directly into the `lockFootprint`. A good example of where this matters is with a limited DeleteRange request. If we recorded it ahead of time, the span could be excessively large, leading to an excessively large ResolveIntentRange request. So we're careful to use ResumeSpans when adding to the `lockFootprint`. But we also don't do much about [this concern on errors](https://github.com/cockroachdb/cockroach/blob/bf71898e043692cc87d2c232fe3066054275ec29/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L514), so maybe that point is partially moot.

One alternative would be to keep track of any in-flight BatchRequests and add their maximal set of lock spans to the lockFootprint if we issue an `EndTxn(commit=false)` before they return.

Another would be to wait until any in-flight BatchRequests return before calling into `abortTxnAsyncLocked`. Or actually, is this what you are suggesting? I may have misinterpreted your proposal as adding to the `inFlightWriteSet` and `lockFootprint` before sending a request instead of after receiving its response.

**Comment by erikgrinaker** [comment]
> But do we not also send another EndTxn(commit=false) one the in-flight batch returns with the transaction aborted error. Is this full rollback being suppressed on the client? Or is it being ignored on the server because the aborted record already exists?

The in-flight batch doesn't error, it's the subsequent batch which does. The order is typically something like this:

```
1: Client → BatchRequest{Put{1-10000}} → Server
2: Client ← BatchResponse{Put{1-10000}} ← Server
3: Client → BatchRequest{Put{10001-20000}} → Server
4: txnHeartbeater → HeartbeatTxnRequest → Server → CanCreateTxnRecord()
5: txnHeartbeater ← Error{ABORT_REASON_NEW_LEASE_PREVENTS_TXN} ← Server ← CanCreateTxnRecord()
6: txnHeartbeater → go EndTxnRequest{Commit:false,LockSpan{1-10000}} → Server
7: Client ← BatchResponse{Put{10001-20000}} ← Server
8: Client → BatchRequest{Put{20001-30000}} → txnCoordSender.Send() → maybeRejectClientLocked()
9: Client ← TransactionRetryWithProtoRefreshError{ABORT_REASON_CLIENT_REJECT} ← txnCoordSender.Send() ← maybeRejectClientLocked()
```

The contract with the client says that it should now retry using a new transaction:

https://github.com/cockroachdb/cockroach/blob/cfb4b95d94e717e985423d5313c58187fbde5da4/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L79-L89

I suppose it's possible that the SQL session would do something to roll back here (haven't checked), but with `kv.Txn` it has automatically updated itself with the new transaction given by `TransactionRetryWithProtoRefreshError` and the caller should simply retry using it.

>One alternative would be to keep track of any in-flight BatchRequests and add their maximal set of lock spans to the lockFootprint if we issue an EndTxn(commit=false) before they return.

Yes, this is more or less what I appended to my comment above. Seems like the simplest solution.

>Another would be to wait until any in-flight BatchRequests return before calling into abortTxnAsyncLocked. Or actually, is this what you are suggesting?

Yes, that's sort of what I was suggesting -- I mentioned recording them in `inFlightWriteSet`, but we really just need _some_ record of the requests.

It sounds to me like we basically have different variants of these options:

1. Eagerly fire off the `EndTxn(commit=false)` with a lock span that covers all completed and in-flight requests.
2. Wait for in-flight requests to return before sending `EndTxn(commit=false)`.

I'll look into some concrete implementations tomorrow, just wanted to check if you had any quick preferences here. It sounds like waiting probably gives us better flexibility and efficiency (e.g. wrt. locking and pipelining), though with slightly less reliable intent cleanup (e.g. in-flight requests may stall or the coordinator may get shut down first).
