### ISSUE TITLE
Add support for installing CockroachDB on macOS via MacPorts Package Manager

### ISSUE THREAD

**Issue by conradwt** [cockroachdb/cockroach#65472]
@ajstorm  

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would like to see support for installing CoackroachDB via the MacPorts package manager because I would like to automate the process of installing it.  Thus, it requires one to update the documentation and add a new Portfile to the **macports/macports-ports** project.

**Describe alternatives you've considered**

The alternative would be to use Homebrew but I really want to avoid installing yet another package manager.  This would cause the same Unix utilities to be installed across two package managers.

**Additional context**

**Comment by kernfeld-cockroach** [comment]
Hey @conradwt, apologies for the delay in answering this. We don't currently plan to support MacPorts, since (as I think you noticed) Homebrew is our MacOS distribution channel of choice. If you're gung ho about avoiding Homebrew, you could also try [Getting and building CockroachDB from source](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting+and+building+CockroachDB+from+source) with the caveat that it won't be nearly as easy or convenient as using `brew`.
