### ISSUE TITLE
sql: allow system tables to be regional by row tables

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#65536]
In https://github.com/cockroachdb/cockroach/issues/63365, we discuss the need to make some system tables GLOBAL tables. However, there are other cases where it would make sense to make system tables Regional By Row. One example came up in the SQL Persistence RFC in which it was discussed that a regional by row table could lower latency.

@Azhng points out some of the specifics:

> For example, the region-local stats will be written to local regions. This means that the flush operation will be relatively cheap because we can ensure that we only be touching region-local nodes.
 
> Another reason this was suggested was the concerns for using fingerprint_id as the first column of secondary index, because this id is essentially a hash, a single flush operation can potentially touch multiple ranges in different nodes. So an alternative is to use node_id as the first column of the secondary index. However, we decided not to go with this design eventually.

Jira issue: CRDB-7656

Epic CRDB-2526

**Comment by ajwerner** [comment]
We've sorted this out for the most part. To make a system table regional by row, it must be re-configured to have a leading key column which can be made into a region enum. This has now been done three times:

* [#98463](https://github.com/cockroachdb/cockroach/pull/98463): sqlliveness
* #98445: sqlinstance
* #98446: lease 

In all cases, the only writers used low-level KV apis. That made it easier. In the future, we may want to initialize the tables by using such a column or write a migration to migrate the data to a wholly new table rather than trying to re-do the exercise we went through for those tables.
