### ISSUE TITLE
EndTransaction gets wedged inside of raft

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#657]
Using the pmattis/client-bench branch, the client scan benchmark fails to complete due to failing to end the transaction created via auto-wrapping. I traced the problem down to the EndTransaction RPC getting wedged inside of raft. To run the benchmark do:

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/client-bench go test ./client -run=- -bench=ClientScan1Version1Row -logtostderr -vmodule=multiraft=5,raft=1
PASS
BenchmarkClientScan1Version1Row	W0414 15:03:51.401650   34546 tls.go:142] listening via tcp to 127.0.0.1:0 without TLS
I0414 15:03:51.402460   34546 rocksdb.go:87] opening rocksdb instance at "client_bench_1_100000"
I0414 15:03:51.411961   34546 node.go:226] initialized store store=1:1 ([ssd]=client_bench_1_100000): {Capacity:1111826382848 Available:599251443712}
I0414 15:03:51.412002   34546 node.go:317] connecting to gossip network to verify cluster ID...
I0414 15:03:51.412007   34546 node.go:334] node connected via gossip and verified as part of cluster "cluster-1"
I0414 15:03:51.412044   34546 node.go:191] Started node with [[ssd]=client_bench_1_100000] engine(s) and attributes []
I0414 15:03:51.412063   34546 server.go:157] starting http server at 127.0.0.1:57261
I0414 15:03:51.412388   34546 multiraft.go:402] node 4294967297 starting
W0414 15:03:51.414370   34546 tls.go:155] connecting via tcp to 127.0.0.1:57261 without TLS
I0414 15:03:51.415266   34546 client.go:141] client 127.0.0.1:57261 connected
I0414 15:03:51.415314   34546 client.go:211] client 127.0.0.1:57261 starting heartbeat
I0414 15:03:51.418411   34546 rocksdb.go:108] closing rocksdb instance at "client_bench_1_100000"
W0414 15:03:51.419139   34546 tls.go:142] listening via tcp to 127.0.0.1:0 without TLS
I0414 15:03:51.419246   34546 rocksdb.go:87] opening rocksdb instance at "client_bench_1_100000"
I0414 15:03:51.422116   34546 node.go:226] initialized store store=1:1 ([ssd]=client_bench_1_100000): {Capacity:1111826382848 Available:599251443712}
I0414 15:03:51.422138   34546 node.go:317] connecting to gossip network to verify cluster ID...
I0414 15:03:51.422142   34546 node.go:334] node connected via gossip and verified as part of cluster "cluster-1"
I0414 15:03:51.422150   34546 node.go:191] Started node with [[ssd]=client_bench_1_100000] engine(s) and attributes []
I0414 15:03:51.422155   34546 server.go:157] starting http server at 127.0.0.1:57264
I0414 15:03:51.422256   34546 multiraft.go:402] node 4294967297 starting
W0414 15:03:51.422810   34546 tls.go:155] connecting via tcp to 127.0.0.1:57264 without TLS
I0414 15:03:51.423275   34546 client.go:141] client 127.0.0.1:57264 connected
I0414 15:03:51.423325   34546 client.go:211] client 127.0.0.1:57264 starting heartbeat
I0414 15:03:51.423838   34546 txn_coord_sender.go:300] Scan: auto-wrapping in txn and re-executing
I0414 15:03:51.424657   34546 raft.go:390] raft: 100000001 became follower at term 7
I0414 15:03:51.424748   34546 raft.go:207] raft: newRaft 100000001 [peers: [100000001], term: 7, commit: 100030, applied: 62239, lastindex: 100030, lastterm: 7]
I0414 15:03:52.050892   34546 raft.go:620] raft: 100000001 no leader at term 7; dropping proposal
I0414 15:03:56.647797   34546 raft.go:464] raft: 100000001 is starting a new election at term 7
I0414 15:03:56.647820   34546 raft.go:403] raft: 100000001 became candidate at term 8
I0414 15:03:56.647824   34546 raft.go:447] raft: 100000001 received vote from 100000001 at term 8
I0414 15:03:56.647862   34546 raft.go:426] raft: 100000001 became leader at term 8
W0414 15:04:06.441791   34546 dist_sender.go:478] failed to invoke EndTransaction: failed to send RPC: too many errors encountered (1 of 1 total): rpc to Node.EndTransaction timed out after 15s
```

**Comment by bdarnell** [comment]
OK, I think I've figured out what's going on here:
* The range splits during this benchmark, after ~62K keys (out of 100K). The keys are written in sequence, so all of the remaining 38K keys belong in range 2.
* The DistSender still has the pre-split range descriptor in its cache, so it sends all the following RPCs with RaftID 2 in the header.
* The command passes through LocalSender and because it has full addressing information in its header it is passed to Store.ExecuteCommand and to raft.
* After being committed through raft, the command fails because the requested key is no longer in bounds for the range.
* LocalSender intercepts the RangeKeyMismatchError and retries, so the command succeeds and the DistSender doesn't learn to update its range descriptor cache.
* Because the command failed, the raft applied index for the range was not persisted. This means that on subsequent runs (when this benchmark reuses its old data), raft tries to replay the "unapplied" portion of the log: all 38K entries that failed the first time around.
* Simply loading the 38K entries for the raft.Ready struct takes longer than the 1ms raft tick interval used in our tests (including this benchmark). This appears to result in pathological interactions between the multiraft and multinode select loops: the tick channel is always chosen instead of the ready channel. (This seems to contradict the go spec's statement that ties in a select statement are broken pseudorandomly).

**Comment by bdarnell** [comment]
Action items from the above:
* [ ] Remove the retry loop in LocalSender. At best this feels like a premature optimization, and it turns out to undermine DistSender's cache invalidation.
* [ ] Do some basic validation (at least for RangeKeyMismatchError) in Store.ExecuteCommand before forwarding a command to raft, so misdirected requests don't fill the raft log with garbage.
* [ ] Update the applied index even for failed commands.
* [ ] Increase the raft tick interval in tests to a more realistic level (a few tests fail with a 10ms timeout instead of the current 1ms; we need to either increase timeouts in those tests and/or make other changes to trigger elections early)
* [ ] Limit the amount of data loaded in Range.Entries (tricky to do with our reverse-chronological log storage)

**Comment by bdarnell** [comment]
Closing this issue since fixing #681 was sufficient to get the test passing, and all the other tasks have their own tracking issues.
