### ISSUE TITLE
Surface the transaction retry chart more prominently in the DB Console and add documentation and tool tips on the Distributed metric dashboard

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#65856]
We have a Transaction Restarts chart in the DB console under the distributed dashboard. Currently there is no documentation on this part of the console and we should also provide a way to surface this transaction restart view more prominently. One place to consider is the SQL dashboard where there are related counters for statements and transactions.

Documentation we should also update:  https://www.cockroachlabs.com/docs/v21.1/ui-overview.html

Epic CRDB-6570

**Comment by bdarnell** [comment]
We already export a metric txn.restarts as well as a bunch of reason-specifc metrics like txn.restarts.writetooold. These are shown in the KV Transaction Restarts chart on the distributed dashboard in the web console. Are these not what you want?

**Comment by kevin-v-ngo** [comment]
Ah thanks for pointing this out Ben! Did not know this was here 😀 It would be good if this was more discoverable. Are there any differences between "KV" transactions and how we refer to SQL transactions on the SQL dashboard page?

**Comment by bdarnell** [comment]
> It would be good if this was more discoverable.

I may be misremembering but I think we used to have a transactions section of the dashboard (which apparently got folded into "distributed"?). 

> Are there any differences between "KV" transactions and how we refer to SQL transactions on the SQL dashboard page?

There are some, so you won't get the numbers to line up one-to-one. For example, there are some internal KV transactions that weren't initiated by SQL, and when a transaction auto-retries I think one SQL transaction may get counted as two KV transactions (I think it varies depending on exactly why there was a retry). But it's close enough that you can generally ignore the differences. For questions like "am I experiencing retries? and if so, why?" these metrics are what you want.

**Comment by kevin-v-ngo** [comment]
Adding @Annebirzin and @ianjevans for visibility. @Annebirzin, the SQL activity page might be a good place for this when we introduce a metrics tab.

**Comment by ianjevans** [comment]
Pinging @taroface. I'm having trouble finding any docs release note issues for the new metrics dashboards.

I think we're missing docs for the Distributed, Queues, and Slow Queries dashboards, but I think that's because there never was a release note string that triggered a doc issue. I don't know why that occurred, though.
E.g. https://github.com/cockroachdb/docs/issues?page=2&q=is%3Aissue+slow+queries

**Comment by ianjevans** [comment]
So after some digging by Jordan, it appears that the missing dashboards have been in the codebase for quite some time, but have been undocumented. They likely were added before our RN text -> doc issue process began, so that's why we don't have doc issues for them. I'll create a separate issue to handle adding the docs for these dashboards.

**Comment by kevin-v-ngo** [comment]
To update this thread, we are moving the transaction restart chart (broken down by errors) into the SQL dashboard beneath transactions to make this more discoverable. @ianjevans, FYI, we should provide documentation on what to do for each error. I think this many are already captured in this reference documentation: https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html
