### ISSUE TITLE
kvprober: scan meta2 at a historical timestamp

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#65996]
kvprober scans meta2 to make probe plans. Today, it scans meta2 doing a standard strong read: https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/planner.go#L207. This may be fine, but a strong read isn't needed. If the scan was done at a historical timestamp a few seconds back, we'd still generate reasonable probe plans, as our goal is to cover the keyspace *approximately* evenly (when measured over long-ish timescales). In other words, probing some ranges a bit more than others in the presence of merges & splits is not a problem (and this already happens as kvprober makes plans & then holds them in memory).

But why scan meta2 at a historical timestamp? There may be some reliability benefit to doing so, as it reduces the chance of the meta2 workload coming from kvprober contending with some other more important meta2 workload. Even if we don't see a concrete problem with the current behavior, perhaps it makes sense to scan at a historical timestamp, simply bc/ meta2 is a critical part of the keyspace, and as the proposed change is trivial to implement.

This came up in discussion with @jordanlewis!

@tbg, I wonder what you think. Two Qs:

1. Any concerns with me rolling out kvprober to CC **before** closing this issue? I expect no but want to check. I've already rolled out to telemetry btw.
2. Any thoughts in general about this issue? Desirable? Not desirable? Big deal? Not big deal? Rationale interesting to me.

**Comment by tbg** [comment]
> But why scan meta2 at a historical timestamp? There may be some reliability benefit to doing so, as it reduces the chance of the meta2 workload coming from kvprober contending with some other more important meta2 workload. Even if we don't see a concrete problem with the current behavior, perhaps it makes sense to scan at a historical timestamp, simply bc/ meta2 is a critical part of the keyspace, and as the proposed change is trivial to implement.

It wouldn't really contend with anything - I mean it might push the occasional split or merge but that's not a big deal - and the benefit of the strong read is that it verifies that the meta ranges actually work. Historical or weaker reads might get served from followers, which can give you an answer despite the leader being locked up. On the flip side, if a follower is locked up, the kvprober won't find out.
Scanning at a historical timestamp (maybe -10s) but with strong consistency (i.e. not READ_UNCOMMITTED) seems like a good tradeoff.

1. No, occasional strong reads to the meta ranges should not cause issues. Remind me, how often are we making the probe plans? Certainly reading it in a tight loop could be annoying.
2. I'd make the -10s check just because it seems like good practice. Wouldn't say it's a a big deal, operations on meta ranges already are pretty slow (the only strong readers/writers to it are the replication changes, splits, etc, which are not short txns). But it's worth being conservative here. Note also that `crdb_internal.ranges_no_leases` does a full scan over the meta ranges every time they're requested.

**Comment by joshimhoff** [comment]
👍 thanks!

> Remind me, how often are we making the probe plans?

I am shooting to send point read probes between once a second and once every 5 second **per node**.  With 100 "steps" planned at once (the default as per https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/settings.go), this means scanning meta2 between once every 100s and once every 500s. We could push that setting up also and scan more of meta2 at a time but also less often.

**Comment by joshimhoff** [comment]
```
if err := db.Txn(ctx context.Context, func(ctx context.Context, txn *kv.Txn) error {
    if err := txn.SetFixedTimestamp(...); err != nil { return err }
    // ...
}); err != nil { /* ... */ }
```

**Comment by joshimhoff** [comment]
Wrote a PR up (https://github.com/cockroachdb/cockroach/pull/69573) but we've decided to not do this with rationale from @tbg below:

> I've reviewed this and this looks ok, but how do you feel about not doing this (i.e. closing this PR unmerged)? I was sort of lukewarm about this when we last discussed this, but now that I see the code it's starting to look over-engineered. The prober is already very careful, and it's read-only, and user traffic never writes to the meta ranges, so it is unclear what we're doing this for - there is a bit more complexity here as a result which is nice to avoid.
