### ISSUE TITLE
config,kvserver: don't unconditionally split on table boundaries for the host tenant

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#66063]
**Is your feature request related to a problem? Please describe.**

On the host tenant, we unconditionally split on all table/index/partition boundaries. There are two reasons this might have been desirable:
(a) Performance: splitting off each table/index/partition into its own range guarantees independent range processing of the data within that table/index/partition.
(b) Diverging zone configs: if two tables have different zone configs attached to them (remember: the "unit" of what a zone config can apply to is a db/table/index/partition), that necessarily implies a split. By unconditionally splitting on table boundaries, we didn't have to write code to reason about adjacent-keys-but-from-different-tables-with-diverging-zone-configs.

**Describe the solution you'd like**

For (a) we could support syntax for users to specify intentional split on table boundaries [#65903](https://github.com/cockroachdb/cockroach/issues/65903). For (b), we're soon going to introduce zone configs for secondary tenants. By default we don't split on table boundaries for secondary tenants due to the order-of-magnitude ranges that would create, but with secondary tenant zone configs, we're opening the door to tenant-initiated splits in the tenant keyspace. That means we're going to write code that reasons about adjacent-keys-but-from-different-tables-with-diverging-zone-configs, to determine where the necessary split points would be, so we may as well coalesce host tenant tables into single ranges when possible. If secondary indexes or groups of tables are placed on the same range, txns that span them could benefit from 1PC optimizations.

**Describe alternatives you've considered**

Keeping the status quo. I think this issue only really matters for on-prem customers (without multi-tenancy) where each table would today create a new range. For users with many small tables, the overhead of the very many tiny ranges might be undesirable. With tenant zone configs we'll soon be addressing the O(descriptors) bottleneck that today prevent having too many tables. Perhaps it's time to look ahead.

Jira issue: CRDB-7866

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/issues/72389#issuecomment-1092204714. Now that we can have a larger number of tables, doing something here seems worthwhile, even if gated behind a cluster setting.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-7866](https://cockroachlabs.atlassian.net/browse/CRDB-7866) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-66063`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
