### ISSUE TITLE
redis client

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#66121]
hello,  cockroachdb is underlying a good distributed KV store. 
why not implement a redis cluster based on it ?
pure in-memory store like redis sometimes looks too expensive.

**Comment by kernfeld-cockroach** [comment]
Are you looking to replicate some particular Redis-like functionality on a CockroachDB cluster? If you have something like that in mind, please let me know!

Early on, Cockroach Labs [decided](https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/) that SQL support was crucial for powering complex applications. We wanted to support a major SQL dialect, and eventually chose to [support the Postgres protocol](https://www.cockroachlabs.com/blog/why-postgres/). Using SQL is pretty different than the approach of Redis, which is more based around in-memory data structures.

Building a Redis-like data store on top of a Cockroach cluster is an interesting idea. They would be quite different because CockroachDB prioritizes consistency whereas Redis prioritizes availability. My personal favorite explanation of the tradeoffs is [A plain english introduction to CAP Theorem](http://ksat.me/a-plain-english-introduction-to-cap-theorem). But either way, building something like this would be a huge project.

**Comment by kernfeld-cockroach** [comment]
Please see also, [Could CockroachDB Ever Replace Redis? A Flex Fridays Experiment](https://www.cockroachlabs.com/blog/could-cockroachdb-ever-replace-redis-a-free-fridays-experiment/)!

**Comment by carr123** [comment]
well, actually i need a redis variant which features strong consistency, automatic key sharding and rebalancing, automatic failover, persistence to disk which can reduce memory consumption. all these features are already there in cockroachdb.
"running super fast all in memory" is not my concern. 
 on other words, i need a sofisticated distributed KV store that talk redis wire protocol(just because redis client is popular).
by the way, I notify some other newsql like tidb has similar stuff, called tikv.
and yugabytedb also supports redis client.
i guess, if cockroachdb could support redis client, that would be a charming feature.

**Comment by ajwerner** [comment]
> i expect such a cockroach-redis is more faster than current SQL-store 

I would not assume that at all. Cockroach SQL for key-value store workloads does a pretty good just just accessing the key-value store. We've spent a while tuning stuff for pgwire and SQL. To get a redis wire-protocol client up and running and then tuning it would be non-trivial.

`tikv` but it's not necesarily because it makes it fast or better for KV workloads. It's a different set of tradeoffs that allow for things like a separate implementation langauge and more flexbile deployment methodology at the cost of operational ease, shared codebase, etc.

Postgres clients are, I would think, about as ubiquitous as redis clients. Consider making yourself a key-value store sql table and trying it out. I have a feeling it'll work pretty well.
