### ISSUE TITLE
Increasing number of replicas decreases resilience to slow failures

### ISSUE THREAD

**Issue by BenjaminPelletier** [cockroachdb/cockroach#66159]
**Describe the problem**
When the number of available nodes drops below the targeted number of replicas, CockroachDB chooses to maintain dead nodes as part of replicas' Raft groups (presumably in an attempt to meet the target number of replicas) rather than removing dead nodes from Raft groups.  Dead nodes in Raft groups are a liability for those Raft groups, and the resilience of the system is decreased as a result.

Failures can happen in two main ways relevant to this issue: quickly, where there is no opportunity to rebalance the cluster between failures, and slowly, where there is opportunity to rebalance the cluster between failures.  Increasing the number of replicas always increases resilience to quick failures -- the number of nodes the cluster can survive losing is equal to the minority of the replicas.  But, increasing replicas can (and often does) decrease resilience to slow failures -- the number of nodes the cluster can survive losing is still the same as in the quick case, but rebalancing in between failures could easily increase this number (and indeed, the number is higher with a smaller number of replicas).

I suggest this could be fixed by having CockroachDB remove dead nodes from Raft groups even if that causes the number of replicas to drop below the target number.

**To Reproduce**
Generally speaking:
1. Create a 5-node cluster
1. Set `num_replicas` for everything to 5
1. Kill node 5, wait until it is declared dead + some extra time
1. Kill node 4, wait until it is declared dead + some extra time
1. Kill node 3
1. Attempt to query data from the cluster and observe that the query hangs (system is broken)
1. Repeat all previous steps, except setting `num_replicas` to 3 and see that query does not hang at the final step

Specifically:
1. Rename attached [`crdb_5.txt`](https://github.com/cockroachdb/cockroach/files/6611933/crdb_5.txt) to `crdb_5.sh`
1. Run `crdb_5.sh 5`, see that S11 query hangs (system is broken at that point)
1. Run `crdb_5.sh 3`, see that script completes successfully

**Expected behavior**
I expect the increasing replica count targets should never decrease the resiliency of the system.

Specifically, I expect `crdb_5.sh 5` should complete successfully.  I believe this should happen by CRDB dropping down to a Raft group size of 3 (or possibly 4, depending on implementation specifics) at Checkpoint C5c.

**Additional data / screenshots**
N/A

**Environment:**
 - CockroachDB version 20.1.8 (though the issue reproduces with `latest` 21.1.2 as well)
 - Server OS: Mac Big Sur running Docker containers
 - Client app: N/A (direct SQL queries in demo)

**Additional context**
Our use case requires that the system remain available even when the loss of some nodes is not addressed (via decommissioning those nodes) in a timely manner.  To maximize survivability in these circumstances, this bug forces us to choose a small number of replicas which means we lose the multi-failure/fast-failures resiliency of a larger number of replicas.

Jira issue: CRDB-7914

**Comment by a-entin** [comment]
Per conversation with @BenjaminPelletier, this is a case for an automatic removal (decommissioning) of dead nodes in specific conditions ("long time dead", when allowing the dead nodes to linger decreases the overall resiliency of the system).

The argument FOR auto removing [under specific circumstances] is backed by robust arguments.
We also discussed possible concerns. Users make deliberate sizing/design decisions for a cluster (# nodes, replication factors) to tolerate specific failure scenarios and to support the required workload. Automatically removing nodes, albeit "dead" at the moment, effectively overwrites user's decision by shrinking database's storage and processing capacity without user's explicit consent. That may be problematic.
The current design assumes that an operator would not allow a dead node to linger indefinitely or/and would want the dead nodes to be ready to rejoin the cluster automatically and promptly after a fault condition clears.

@bdarnell commented on this topic:
"decommissioning isn't actually that important - most of the things that happen when a node dies happen as soon as it's declared "dead" (after 5 minutes by default). the main thing that decommissioning does is to enable major upgrades (you can't upgrade unless all nodes are either up or decommissioned) and stop the console from alerting you that you have a dead node
 we considered an auto-decommission functionality and decided not to invest time in building it, but i don't think we're particularly opposed to the idea. (i'm a little wary of long timers because they can obscure cause and effect)
 there's also a question of whether all ranges should have the automatic adjustment that system ranges do - if you have 5 nodes and a table with a replication factor of 5, and you lose two nodes, should we leave you at 3/5 and unable to survive any more failures or reconfigure to 3/3? i'm not 100% sure what we do in this case today. It feels wrong to silently adjust the explicitly requested replication factor but it's difficult to identify any concrete downside (vs the concrete upside of being able to tolerate one more failure).
 in the end a lot of this is not "we designed it this way because this is how we think it should be" but "we have not (yet) elected to spend time building things for this scenario" because we assume admins will be staying on top of dead nodes enough that it doesn't become an issue"

**Comment by BenjaminPelletier** [comment]
This issue could be addressed by auto-removing nodes from the cluster, but that does seem unnecessary and overkill.  Instead, this issue would be fixed if dead nodes were simply removed from all Raft groups they were part of.  Are there any advantages to keeping a long-dead node in a Raft group?  Doing so could facilitate slightly quicker recovery when it comes back online, but that scenario seems unlikely/uncommon due to the fact that it is long-dead.  Meanwhile, maintaining its membership in the Raft group has substantive negative impacts, as demonstrated by this bug.

**Comment by mwang1026** [comment]
Hi Benjamin -- thanks for filing. I definitely see the value in having some automated "extra layer of resilience" with this. My question to you -- is there ever a failure that you feel like an human could not act quickly enough to manually dial down replication factor? And are there scenarios where the system decreased the `rf` and it actually isn't something you wanted to do?

My understanding is that if you remove a range from the raft group it won't automatically rejoin the range if the node comes back, e.g.

**Comment by a-entin** [comment]
Fwiw, per conversation w/BenP, a caveat in this case - different legal entities ("partners") are contributing nodes to the cluster. No one "owns" the entire cluster. "Partners" can neglect taking prompt actions or even withdraw their nodes. The designers of the system are striving to achieve max resiliency and being [very diligent](https://github.com/BenjaminPelletier/dss/tree/docs/pooling/build/deploy#survivability) about it.

**Comment by mwang1026** [comment]
Hi @BenjaminPelletier. Courtesy ping on the above questions. Thanks!

**Comment by BenjaminPelletier** [comment]
I think a big part of the "Cockroach" nature of CRDB that we are interested in is that CRDB itself performs many automatic maintenance/resilience operations itself rather than placing that burden on human IT staff and incurring the necessary human-scale delay.  For instance, in a system with an abundance of available nodes, the failure of one node results in the automatic transfer of range responsibility away from the failed node to other nodes without the need for human intervention.  The system would still work if a human had to manually reassign ranges from that failed node to other nodes, but that would be much less "Cockroachish" -- or, in other words, that hypothetical system would be less reliable than CockroachDB actually is because sometimes a more serious outcome would occur because the human was not as fast as the system would have been at mitigating the node failure.  I believe this is the same situation here -- it's true that a human can take this corrective action manually, but that requirement reduces the reliability of the system overall and ties reliability more strongly to IT responsiveness over system design.

In our application, the ability to achieve reliability targets primarily through system design rather than through IT procedures is a key feature.  We have a novel use case where a coordination service (named the Discovery and Synchronization Service; DSS) is provided via collaboration of multiple unaffiliated members of a federation (different companies).  Each different organization hosts a set of CockroachDB nodes, and they are configured to work together to provide a very high reliability system -- this federated system should not fail even with a complete failure of, e.g., Azure services since another member of the federation may be hosting their nodes on Google Cloud (this circumstance actually occurred during a demonstration of this technology and the federated system did successfully survive the Azure outage).  But, the challenge of such a system is that coordination among different organizations is far more difficult than coordination within a single organization.  Other organizations have limited ability to improve the IT capabilities of a lower-performing participant.  For that reason, reliability by design is critical here as compared to reliability by IT responsiveness which is what "act quickly enough" depends on.

We expect this application (the DSS, and in particular the [InterUSS Platform implementation](https://github.com/interuss/dss) which is compliant with the ASTM Remote Identification specification F3411-19 and the draft ASTM specification for flight planning interoperability) to have wide usage in the near future, which means the impact of the outcome of this issue will be substantial.  This technology has already been used by many different organizations to conduct demonstrations and research with the involvement of the FAA, NASA, Swiss aviation authorities, and the UK government.  An officially-recognized rollout of a system built on this technology was [recently announced in Switzerland](https://susi.swiss/2021/08/16/swiss-remote-identification/), after many [past demonstrations](https://www.youtube.com/watch?v=PeJpC3o8JBM) of the technology.  We want to continue to ensure the maximum reliability practical in these use cases given the constraints present.

**Comment by andreimatei** [comment]
> > Per conversation with @BenjaminPelletier, this is a case for an automatic removal (decommissioning) of dead nodes in specific conditions ("long time dead", when allowing the dead nodes to linger decreases the overall resiliency of the system).

> This issue could be addressed by auto-removing nodes from the cluster, but that does seem unnecessary and overkill. 

Indeed, I think an auto-decommissioning feature is probably not what you want in this kind of "federated" cluster as discussed here - because a decommissioned node can't rejoin the cluster if eventually it is restarted and at the moment requires manual intervention to delete the store dirs (and generally the experience on restarting such a node [is not great](#69245)].

> [@bdarnell] there's also a question of whether all ranges should have the automatic adjustment that system ranges do - if you have 5 nodes and a table with a replication factor of 5, and you lose two nodes, should we leave you at 3/5 and unable to survive any more failures or reconfigure to 3/3? 

I don't think the "adaptive" replication factor that we have for system ranges is exactly what's being requested here. That adaptive rf has implications for health reporting that I don't think anybody wants more generally; also I think everybody who's aware of the implementation details of that "feature" thinks it was a bad idea. In contrast to that, this issue doesn't seem to ask for an equivalent changing the replication factor in zone configs directly; I think it's more narrowly asking for a different quorum management policy at the level of individual ranges.

> i'm not 100% sure what we do in this case today. It feels wrong to silently adjust the explicitly requested replication factor but it's difficult to identify any concrete downside (vs the concrete upside of being able to tolerate one more failure).

One downside of down-replicating is the speed/cost of up-replicating in case the respective node(s) comes back - and coming back is supposed to be expected if the node is not decommissioned. And this costs twice what one would expect since, if we were  to down-replicate, we'd down-replicate two voters at a time (i.e. we'd go from 5 voters to 3 voters, not to 4 voters).
However, I think the benefits outweigh the downside; I think we should have another flag, in addition to `server.time_until_store_dead` to control this kind of down-replication in situations where dead voter replacement is not possible because there's not enough live nodes (or enough live nodes meeting the replication constraints for a particular range).

Just fyi, @BenjaminPelletier, I think this issue doesn't come up too much for CRDB in general because you seem to have some particularities for your cluster / application: 
- The difficulty to decommission nodes. We generally don't really have features targeted at this kind of federated clusters where there's not a single admin for all the machines.
- The fact that you have a replication factor equal (or greater!) to the number of nodes in the cluster. Typically, in a CRDB clusters you'd have many more nodes than the replication factor, so replacing is a dead voter is generally expected to be possible. Or, people run a small cluster and leave the replication factor to the minimum of 3.

**Comment by andreimatei** [comment]
@aayushshah15 showed me that we actually used to implement the down-replication logic a while ago, until https://github.com/cockroachdb/cockroach/commit/7e0b8860c7a92ea317667128f96df0856ade6d85
This changed I think under the justification from [this issue](https://github.com/cockroachdb/cockroach/issues/34122#issuecomment-455796623):
> But I think we shouldn't be down-replicating in the first place. StorePool.AvailableNodeCount seems like a problematic signal for the number of nodes in the cluster. For one, it only returns nodes which have gossiped a node descriptor. Second, it only counts non-dead nodes. So after a node has been down for 5 minutes, we may start adjusting the target replication factor for all ranges in the cluster. That doesn't seem like the right thing to do. I think we should consider the cluster node count to be the number of nodes that have been added to the cluster minus the number of decommissioned nodes. If a node dies, it should still be considered part of the cluster until it is decommissioned.

This paragraph doesn't really dig inside anyone's soul. It's true that I was asked about my opinion among others, and I seem to have been silent. I still don't know what my opinion is. I oscillate between thinking that  `server.time_until_store_dead` is enough of a trigger for down-replicating, and also sympathizing with not down-replicating too easily. What I'm exploring is the degree to which there's a conceptual difference between replacing and removing a replica. @petermattis where do you stand two years later?

**Comment by aayushshah15** [comment]
>What is the least surprising behavior?

Dynamically up/downreplicating adds at least a few surprises: 
- If we alter the current implementation to automatically down-replicate when nodes are marked "dead", the same logic will also re-increment the replication factor if those nodes are added back into the cluster. This feels like the right thing to do but it's unclear whether this is desirable to everyone, given that we've had a few customers complain to us about how a large percentage of CRDB's operational costs can be attributed to our high level of cross-AZ network traffic (most of which comes from snapshots during rebalancing). If we down-replicate and up-replicate in this fashion, we're wasting network bandwidth for the (usually significant) subset of quiescent ranges in the system. 

- Conversely, _not_ re-increasing the replication factor as these nodes are added back into the cluster (or the previously dead nodes are brought back online), is arguably quite surprising and dangerous as well.
