### ISSUE TITLE
bulk: adaptively probe into existing data in AddSSTableRequests.checkForKeyCollisions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#66410]
This is an idea that came from @andreimatei during a conversation about recent large-scale IMPORTs.

During IMPORTs, we repeatedly ingest SSTs through `AddSSTableRequests`. These requests set the `DisallowShadowing` flag to `true`, so they must check that none of the keys in their SST overlap with any of the keys in the destination range:

https://github.com/cockroachdb/cockroach/blob/9335ade9ce91ebdab1996d7c818b16df32557ac8/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L49-L57

For IMPORTs where the source is sorted similarly to the destination index, this behavior is fine because the destination keyspace is always empty so the call to `checkForKeyCollisions` is free. However, for portions of the IMPORT where the source is not sorted like the destination index, as is almost always the case for tables with secondary indexes, this repeat conflict checking on each `AddSSTableRequests` is quadratic and can dominate the cost of the IMPORT. This is especially true when the IMPORT creates high read amplification in the destination range, further slowing down the scan in `AddSSTableRequests`.

As an IMPORT continues, it would seem that the ratio of existing to new data would become larger and larger. Eventually, all `AddSSTableRequests` would begin to set their `IngestAsWrites` flag. But beyond this, the "efficiency" of each `checkForKeyCollisions` call would decrease.

It's possible that once we cross some threshold, it would be more efficient to probe into the range to check for conflicts instead of scanning the new data and the existing data in parallel using two iterators. The useful analogy here is to perform a "hash join" instead of a "merge join" once the ratio of existing to new data crosses some threshold. This optimization may be negated to some degree by the fact that we [seek each iterator](https://github.com/cockroachdb/cockroach/blob/9335ade9ce91ebdab1996d7c818b16df32557ac8/pkg/storage/mvcc.go#L3928) in `checkForKeyCollisionsGo` instead of calling next on them (a "zig-zag join", following our analogy). But what this still doesn't give us is the ability to use SST bloom filters to ignore most SSTs in the existing data. The ability to use bloom filters would be particularly important once read amplification grows.

So the proposal here is to take the ratio of `new/existing keys` and maybe the `read amplification` into account in `checkForKeyCollisions` and to switch to a probing mode once we determine that it makes sense to do so.

@adityamaru is this something we have considered?

Epic: CRDB-2556

**Comment by dt** [comment]
I wonder if we (storage?) could do something clever and AND the bloom filters from the new and existing files?

**Comment by sumeerbhola** [comment]
Is there an existing representative benchmark that we can profile? If not, would someone be willing to construct one?

I don't understand the "it would be more efficient to probe into the range to check for conflicts instead of scanning the new data and the existing data in parallel using two iterators" -- we are probing when doing SeekGE on the MVCCIterator. What am I missing?

**Comment by nvanbenschoten** [comment]
> I don't understand the "it would be more efficient to probe into the range to check for conflicts instead of scanning the new data and the existing data in parallel using two iterators" -- we are probing when doing SeekGE on the MVCCIterator. What am I missing?

We are not using a prefix iterator, so my understanding is that a call to SeekGE will be unable to use bloom filters and will need to establish a merging iterator over every overlapping SST. This dominates CPU profiles during IMPORTs, especially as read amplification grows. Is my understanding correct that if we used a prefix iterator then we would be able to use bloom filters for these probes?

**Comment by sumeerbhola** [comment]
> Is my understanding correct that if we used a prefix iterator then we would be able to use bloom filters for these probes?

Yes.
Though there can be tradeoffs, since bloom filters can have false positives and checking them is not free. A representative benchmark could help us understand this better, and explore possibilities.

**Comment by mwang1026** [comment]
@sumeerbhola Can you point me to example of those benchmarks? Are they tests or are they separate things that we run?

cc @vy-ton who mentioned she has a script that hits the slowdown

**Comment by nvanbenschoten** [comment]
Closing, as @itsbilal's change in https://github.com/cockroachdb/cockroach/pull/73514 allows us to use bloom filters in `checkForKeyCollisions`, which is the core of what this issue was about.

**Comment by sumeerbhola** [comment]
I unfortunately lost track of this issue. I'm unsure about the value of bloom filters when most of the data is in L6, which don't have bloom filters. The value may be happening from the fact that there are up to 7 files (in each level) to seek (of which 6 are not actually going to be the top of the heap after the seek, so they are already in the seeked position, but we don't know it), and we have not added an optimization to SeekGE to use Next, while we do have such an optimization for SeekPrefixGE.
I think optimizing SeekGE and continuing with the alternating seeks is probably the more universally performant approach (since iterating over all keys in the sst may be slow in some cases).
I've also added some comments to https://github.com/cockroachdb/cockroach/pull/73514#pullrequestreview-825876449

cc: @itsbilal
