### ISSUE TITLE
kv: release latches before evaluation for read-only requests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#66485]
Related to, but separate from https://github.com/cockroachdb/cockroach/issues/25579.
Related to https://github.com/cockroachdb/cockroach/issues/41720#issuecomment-548163240.
Original discussion in https://forum.cockroachlabs.com/t/why-do-we-keep-read-commands-in-the-command-queue/360.

Currently, read-only requests hold latches across evaluation. These are read-only latches, and so they do not conflict with writes at higher timestamps than the read. However, they do still block writes at lower timestamps than the read (at least until we address #25579) and do still block non-MVCC writes like range splits. This is a problem, as the more we allow requests to block on one another, the more we open ourselves up to unexpected tail latency under rare sequences of events like we saw in https://github.com/cockroachdb/cockroach/pull/66338, where an `Export` (MVCC read), blocked a split (non-MVCC write), blocked a large set of writes (MVCC write).

We should re-evaluate this decision and determine whether we can drop latches earlier for reads, before they spend any time reading data. Doing so would rely on https://github.com/cockroachdb/cockroach/issues/55461. The high-level idea is that we could grab an LSM snapshot and bump the timestamp cache, and then drop the read's latches (and `readOnlyCmdMu`) before proceeding to evaluation.

For context, there are two reasons why we didn't do this in the past, and both have to do with wanting to wait to bump the timestamp cache until after evaluation:
1. we don't want to bump the timestamp cache immediately in case the read runs into intents during evaluation and is forced to retry after pushing/waiting. Bumping the timestamp cache early could cause some form of starvation to writers who lay down and intent and then want to re-write it in a subsequent retry. If readers always bumped the timestamp cache before finding the conflicting intent then they could prevent the writer from every completing.
2. we don't want to bump the timestamp cache for limited scans if we don't know the full extent of what they will (or won't) read. Doing so could cause false-contention.

These concerns are still both valid to some degree, but things have also changed over the past few years.

Regarding the starvation of writers, this is no longer as severe of a problem as it once was. This is because transactions can now refresh their reads if their write timestamp is bumped. While contention can still prevent a read refresh from succeeding and force a transaction to perform a full restart, this is no longer a given like it once was. Additionally, with the `lockTable`, we will soon have the ability to check for conflicting locks over a span of keys without performing a full scan of the data. This opens up the opportunity to scan the `lockTable` upfront, while holding latches, and then only proceed to bump the timestamp cache if no conflicts are found.

The second reason still seems legitimate. We don't want to bump the timestamp cache during a scan if we don't know the full width of the scan ahead of time. Doing so would often lead to limited scans (`SELECT * FROM t LIMIT 1`) bumping the timestamp cache across the entire range, which would trip up otherwise uncontended writes. We have recently landed changes to optimistically latch and lock for limited scans that don't know until evaluation how far they will need to scan. This feels related to me, though I don't have a clear picture about how to take advantage of optimistic evaluation to avoid holding latches across evaluation.

However, one thing that has changed regarding limited scans is that we now have a concept of a closed timestamp, which prevents writes below some fixed interval that lags present time. If a limited scan is run below this timestamp, as `ExportRequests` often do, there is no benefit for bumping the timestamp cache after evaluation.

So with all of these changes, it seems appropriate that we reconsider the synchronization of read-only requests.

/cc. @andreimatei 

Jira issue: CRDB-8063

**Comment by sumeerbhola** [comment]
> Additionally, with the lockTable, we will soon have the ability to check for conflicting locks over a span of keys without performing a full scan of the data. This opens up the opportunity to scan the lockTable upfront, while holding latches, and then only proceed to bump the timestamp cache if no conflicts are found.

(copying the related comment from https://github.com/cockroachlabs/support/issues/1013#issuecomment-858898819)
The current thinking is not to do this in the general case. There is a cost to scanning the lock table key space in the engine twice (the evaluation needs intent interleaving too). So we will only scan the in-memory lockTable data-structure which is an incomplete picture of the intents.

However, for potentially long running reads that don't want any intents and are not transactional or care about uncertainty (and so don't need intent interleaving during evaluation), we can have a different path that does scan the lock table up front since it will only happen once. I believe this applies to ExportRequest.

**Comment by andreimatei** [comment]
> The current thinking is not to do this in the general case. There is a cost to scanning the lock table key space in the engine twice (the evaluation needs intent interleaving too). So we will only scan the in-memory lockTable data-structure which is an incomplete picture of the intents.

I'd like to understand this. You're saying that a read that scans the lock table (scan 1), finds 5 locks which it resolves, and then proceeds to scan the regular key space (scan 2) will need to also scan the locks in parallel with the regular key scan? Because the resolving of the locks will not actually wait for the replication of the cleanup of the respective intents before letting the read do the regular key scan?
The way I imagined we'd handle this is by the reader keeping track of the locks that it resolved as part of scan 1, and interpolating them into scan 2 without actually needing to scan the locks again. No?

**Comment by sumeerbhola** [comment]
> You're saying that a read that scans the lock table (scan 1), finds 5 locks which it resolves, and then proceeds to scan the regular key space (scan 2) will need to also scan the locks in parallel with the regular key scan?

Correct. This is mainly to not overcomplicate the code since the evaluation needs to see one own's intents and do uncertainty checking, that the lock checking does not need to do.

> The way I imagined we'd handle this is by the reader keeping track of the locks that it resolved as part of scan 1, and interpolating them into scan 2 without actually needing to scan the locks again. No?

One way to make this work efficiently is to do a scan and keep in-memory state for all the intents that can be relevant, for lock conflicts, read-your-own-writes, uncertainty checking. We would discard the in-memory state if it became too large, so this would be just the fast path. Then use a subset for the lockTable, and all of it for the request evaluation.

**Comment by sumeerbhola** [comment]
> One way to make this work efficiently is to do a scan and keep in-memory state for all the intents that can be relevant, for lock conflicts, read-your-own-writes, uncertainty checking. We would discard the in-memory state if it became too large, so this would be just the fast path. Then use a subset for the lockTable, and all of it for the request evaluation.

My concern was that we don't want frequent failures on this fast path. I think we can use MVCCStats.IntentCount as a guide. And we're already writing specialized iterators for intent interleaving (e.g. the recent PR for faster ranged intent resolution) so this fits in nicely with that direction.

**Comment by aayushshah15** [comment]
**Summarizing some of our discussions so far:**

For requests evaluating [optimistically](https://github.com/cockroachdb/cockroach/blob/06cc644939f84fcd42914cf7e0f16f7e7076fcee/pkg/kv/kvserver/concurrency/concurrency_control.go#L363-L367) (i.e. batches that have key limits), one of the main obstacles (as also outlined above in the original issue writeup) with “releasing latches early” is that we don’t know which keys to bump the timestamp cache for, since while the request can, at a maximum, read from keys `a` to `z`, it might only end up reading from `a` to `c`.  This is one of the major issues for both this as well as https://github.com/cockroachdb/cockroach/issues/72593.

Today, because we only bump the timestamp cache[ after we’re done evaluating](https://github.com/cockroachdb/cockroach/blob/b630c08339a65976be8a16eef4965b45c5e338da/pkg/kv/kvserver/replica_send.go#L1237-L1252), we know exactly which keys have been read. 

**Next steps:**
The immediate next step is to try to isolate the impact of having optimistically evaluating reads bump the timestamp cache over their entire span, before they begin evaluation. @nvanbenschoten suspects that this might not be as bad as we initially thought. This is because of the following:

Today, reads evaluating via the optimistic path will do the following:
```
Acquire (optimistic [1]) read latches -> evaluate -> bump timestamp cache -> release latches -> check for uninterrupted execution 
```

[1] means that the reads acquiring these optimistic latches won’t block on any current evaluation, but _future_ incoming requests will block on these latches. In effect, this means that incoming writes to such a range do the following:

```
Acquire read-write latches 			-> potentially get bumped by the ts cache -> evaluate and propose -> release latches
(will block on held optimistic latches)
```

So optimistic evaluating requests will do the following: 
```
Acquire (optimistic) latches -> bump timestamp cache -> release latches -> proceed with evaluation
```

Conversely, once we can avoid holding latches during the course of evaluation, reads evaluating via the optimistic path will do the following:
```
Acquire optimistic read latches -> bump ts cache -> release latches -> evaluate -> check for uninterrupted execution 
```

Notice how, here, these reads will only hold these latches for mere nanoseconds as opposed to today, where these latches might be held for an entire range scan [2]. 

Incoming writes to such a range will behave exactly as they do before:
```
Acquire read-write latches -> potentially get bumped by the ts cache -> evaluate & propose -> release latches
```
However, notice how because of [2], these writes will spend much less time waiting for latch acquisition and will instead just be bumped above the optimistic readers’ timestamps.
