### ISSUE TITLE
telemetry: ensure inputs to crdb_internal.increment_feature_counter are sanitized when calling from third party tools

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#66500]
We need to make sure our calls to crdb_internal.increment_feature_counter aren't susceptible to sql injections.

Example: Right now this isn't properly escaped so we're vulnerable to sql injection attacks.
https://github.com/RichardJCai/sqlalchemy-cockroachdb/blob/a83d6b75984881a56251b20f82b60e8c96f1e398/cockroachdb/sqlalchemy/dialect.py#L157

We currently call `crdb_internal.increment_feature_count` for 4 ORMs:
- [x] Sequelize
- [x] SQLAlchemy
- [x] ActiveRecord
- [x] Django

CRDB-2510

**Comment by rafiss** [comment]
django: https://github.com/cockroachdb/django-cockroachdb/pull/228
sqlalchemy: https://github.com/cockroachdb/sqlalchemy-cockroachdb/pull/161
rails: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/215

@vy-ton here is how everything should get reported -- for sqlalchemy and sequelize we'll need to be aware of new releases since those version numbers include major+minor+patch.

| Django 3.2        | django-cockroachdb 3.2.2               |
|-------------------|----------------------------------------|
| sqlalchemy 1.4.22 | sqlalchemy-cockroachdb 1.4.0           |
| ActiveRecord 6.1  | activerecord-cockroachdb-adapter 6.1.3 |
| Sequelize 6.1.0   | sequelize-cockroachdb 6.0.1            |

**Comment by vy-ton** [comment]
Yeah I'm already seeing this in the data. Highest usage for Sequelize is 6.6.5.
