### ISSUE TITLE
changefeedccl: Rangefeeds might fail due to stale range cache

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#66636]
Customer observed changefeeds failing after some of the nodes were
decomissioned

```
ERROR: failed to connect to n4 at 172.31.91.238:26257: initial connection heartbeat failed: rpc error: code = PermissionDenied desc = n4 was permanently removed from the cluster at 2021-05-27 21:08:12.282567682 +0000 U…
```

In addition, error message
```
return args.Timestamp, newSendError(
				fmt.Sprintf("sending to all %d replicas failed", len(replicas)))
```

The hypothesis is that we might not be handling decomissioned nodes correctly.  In particular, perhaps we need to handle `InitialHeartbeatFailed` error in addition to the errors we already handle in `partialRangeFeed` 

1. We need to write tests around decomissioned nodes
2. We need to improve above error message in dist_sender_rangefeed -- we should print all replicas.
3. We need to handle decomissioned nodes

**Comment by erikgrinaker** [comment]
Note that this isn't really about `InitialHeartbeatFailed`, but rather the wrapped `grpcstatus.PermissionDenied`, which is returned for decommissioned nodes. This usually gets classified as a permanent error via `grpcutil.IsAuthenticationError()`, bypassing retries and often cache invalidation.

Also note that #66199 changes the symmetry of `PermissionDenied` for decommissioned nodes. After that change, the decommissioned node itself gets `PermissionDenied` when talking to other nodes, but other nodes talking to a decommissioned node get `FailedPrecondition`. The former should always be considered a permanent error (to avoid hangs and infinite retry loops on decommissioned nodes), but the latter should be retried when talking to a range (since there could be other viable replicas) but not when addressing the decommissioned node specifically.

Most of this applies to `master` and 21.1, where there's been several changes to error handling. It's unclear whether we want to backport all of this to 20.2, so we may need a simpler fix there.

**Comment by erikgrinaker** [comment]
So I've dug into the `RangeFeed` code path here in light of #66199, and I believe this should do the right thing now. Here's my reasoning:

* The error logged by the changefeed was `sending to all %d replicas failed`. This is returned as a `sendError` here:

    https://github.com/cockroachdb/cockroach/blob/0cea9dc28cf5b7855be87b6b38d55d191f1b963f/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L247-L250

* This `sendError` will be caught in `partialRangeFeed()`, invalidating the range cache token and retrying:

    https://github.com/cockroachdb/cockroach/blob/0cea9dc28cf5b7855be87b6b38d55d191f1b963f/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L167-L171

* The retry will get an `PermissionDenied` error when refreshing the range info and hitting the decommissioned node, which is returned to the caller:

    https://github.com/cockroachdb/cockroach/blob/0cea9dc28cf5b7855be87b6b38d55d191f1b963f/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L139-L146

* After #66199, the `IsRangeLookupErrorRetryable()` check here will still trigger on `FailedPrecondition` and return without retrying. However, as discussed in https://github.com/cockroachdb/cockroach/pull/66199#pullrequestreview-683216698, it uses a DistSender as a source of range data which will manage retries of `FailedPrecondition` internally:

    https://github.com/cockroachdb/cockroach/blob/e045f068baa94e2f47c37fe347e41d263d1cbe83/pkg/kv/kvclient/kvcoord/dist_sender.go#L1864-L1870

Thus, I believe this should already be resolved. We may want to change `IsRangeLookupErrorRetryable` to return `true` for `FailedPrecondition` to make this explicit, as long as it doesn't have any adverse effects elsewhere, but it shouldn't really matter either (cc @aliher1911).

In any case, I'll try to write up a unit/integration test to verify this. I've been testing with `roachprod` and so far been unable to reproduce any of these decommissioned node errors with the existing PRs applied, so it's looking promising.
