### ISSUE TITLE
ci: bring back nightly -tags=deadlock stress runs

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66764]
**Is your feature request related to a problem? Please describe.**

We have some tools that catches possible sources of deadlocks (reentrant read locks, or inconsistent lock ordering) but we don't run them regularly. All we need to do is to run the tests under `-tags=deadlock`.

We used to do this back in the day, but for some reason stopped doing it. We have found two deadlocks too late (in prod) as a result, most recently #66759.

**Describe the solution you'd like**

Adjust https://github.com/cockroachdb/cockroach/blob/faf750065fea591f649ac9d61f1701f88f56c4bc/pkg/cmd/teamcity-trigger/main.go#L103-L118 to also start a non-race build with `-tags=deadlock`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by stevendanna** [comment]
We changed how we run the deadlock tests in f4721603efc740d2387212f864aef843234c8d6c perhaps the build script that was added there was never tied into teamcity.

**Comment by RaduBerinde** [comment]
How much slower are tests when the tag is used? Wondering if we shouldn't enable for `crdb_test` builds all the time.

If it's expensive, maybe we can have a separate check just for RLock re-acquisition which should be simpler, and enable that for all `crdb_test` runs.

**Comment by RaduBerinde** [comment]
We should also investigate if there is a static analysis tool (like https://github.com/gnieto/mulint) that would have caught the RLock issue.

**Comment by erikgrinaker** [comment]
Last time I had a look at this we had a bunch of false positives, I believe in the `closedts` package. Will look into whether we can either avoid these false positives or disable checks for specific packages or mutexes.

>How much slower are tests when the tag is used? Wondering if we shouldn't enable for crdb_test builds all the time.

Even if it's slow, I think we can probably enable this for race builds at least, so that it gets run in CI.

**Comment by tbg** [comment]
> Will check. But even if it's slow, I think we can probably enable this for race builds at least, so that it gets run in CI.

I think combining it with the race builds, which are already struggling and skip lots of tests, is problematic.

**Comment by erikgrinaker** [comment]
>I think combining it with the race builds, which are already struggling and skip lots of tests, is problematic.

It's possible. But we tend to enable lots of additional slow assertions during race builds precisely because we skip timing-sensitive tests during race. It seems useful to have a test classification where timing is not important and we can do exhaustive checking, and race currently seems to be it.

Anyway, I'll give it a try and we'll see how it goes.

**Comment by tbg** [comment]
`mulint` does not detect the re-entrant rlock Oleg fixed in

```
$ mulint ./pkg/kv/kvserver/
$ echo $?
0
```

Not clear to me why, according to the README example I would've thought it would catch precisely this:

```go
type someStruct struct {
  m sync.RWMutex
}

func (s *someStruct) A() {
  s.m.RLock()
  s.B()
  s.m.RUnlock()
}

func (s *someStruct) B() {
  s.m.RLock() // This is a recursive lock and it should be detected by this tool
  s.m.RUnlock()
}
```

here `s = Replica` and `B = Desc`.

**Comment by erikgrinaker** [comment]
> `mulint` does not detect the re-entrant rlock Oleg fixed in #66763. Not clear to me why, according to the README example I would've thought it would catch precisely this.

It seems pretty brittle, the example above breaks if the method call is used in an expression, e.g.:

```go
type someStruct struct {
	m sync.RWMutex
}

func (s *someStruct) A() {
	s.m.RLock()
	_ = s.B()
	s.m.RUnlock()
}

func (s *someStruct) B() string {
	s.m.RLock() // This is a recursive lock and it should be detected by this tool
	b := "foo"
	s.m.RUnlock()
	return b
}
```

Only seems to work for bare method calls, where the return value is implicitly discarded.

**Comment by erikgrinaker** [comment]
Ran some tests with/without deadlock detection enabled for `crdb_test`. The complete test suite ran in 18 minutes normally, but with deadlock detection it timed out after 2 hours -- it seemed like certain tests just hung forever with detection enabled, probably because they are timing-sensitive and hit a race condition that blocks forever. Testing `./pkg/kv/kvclient/...` took 54s normally and 1m21s with deadlock detection, so roughly a ~50% slowdown.

Seemed to get lots of deadlock hits as well, will try running each package separately to avoid the hangs and get some idea of the extent of hits and whether they are true or false hits.

**Comment by tbg** [comment]
It is a lot less efficient, but if you wanted to just walk away from it and come back the next day, you could do

```
for t in $(go test -list '^Test' ./pkg/kv/kvserver | grep ^Test); do go test -tags deadlock -timeout 2m -run $t ./pkg/kv/kvserver 2>&1 | tee $t.txt || mv $t.txt $t.failed.txt; done
```
