### ISSUE TITLE
KV: commit deadline exceed error on read-only txn should be retryable

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#6678]
https://github.com/cockroachdb/cockroach/blob/aada6cb/client/txn.go#L663

The fact that it's not, besides being incorrect, confuses the Executor, which can't cope with a `txn.send()` returning a non-retryable error and at the same time leaving the `txn.Proto` in the `PENDING` state.

There was some discussion with Toby about whether having this check done on the client side, and particularly in `Send()` is the right place. Jury's still out.

**Comment by bdarnell** [comment]
A read-only transaction that fails to complete within its table descriptor lease (the current use of commit deadlines) is probably trying to operate on too much data and is unlikely to succeed on retry. We don't want `SELECT * FROM huge_table` to keep retrying endlessly. I think it may be better to resolve this by treating a transaction as ABORTED if its deadline has passed.

**Comment by tschottdorf** [comment]
The same is true for a writing transaction. This issue is more about the KV side of things: a read-only transaction needs to catch a TransactionAbortedError in this case, like commit of a writing transaction would. The current code treats this case like an internal error, which it isn't (a r/o transaction can catch uncertainty restarts, for example).
Agreed that we should perhaps find a way to disable auto-retrying for SQL transactions which fail because of lease violations.

**Comment by andreimatei** [comment]
Agreed that long running txns have a general problem. But note that these errors happen when the txn has been pushed, so it should get stronger with every retry. The fact that it took longer to run than its leases is not automatically a problem for committing; an uncontended txn can run for as long as it wants.

**Comment by kkaneda** [comment]
Closing as we merged #6768, but please reopen if there is any remaining issue. Thanks!
