### ISSUE TITLE
sql: inconsistent typing with sql functions (e.g. count, lower)

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#66862]
**Describe the problem**

This issue was observed while working on #66359.

At logging time (i.e. `logEventsWithOptions`), functions (e.g. `count`, `lower`) were determined to be of type `UnresolvedName` instead of `FunctionDefinition`. 

**To Reproduce**

To reproduce, you'll need to be able to see the type of the query as it is being formatted. Simply adding a print statement in `formatNodeOrHideConstants` is sufficient:

```
func (ctx *FmtCtx) formatNodeOrHideConstants(n NodeFormatter) {
	if ctx.flags.HasFlags(FmtHideConstants) {
                fmt.Println(n)
                fmt.Println(reflect.TypeOf(n)) // or you could use a formatted print with %T
		switch v := n.(type) {
		case *ValuesClause:
			v.formatHideConstants(ctx)
			return
		case *Tuple:
			v.formatHideConstants(ctx)
			return
		case *Array:
			v.formatHideConstants(ctx)
			return
		case *Placeholder:
			// Placeholders should be printed as placeholder markers.
			// Deliberately empty so we format as normal.
		case Datum, Constant:
			ctx.WriteByte('_')
			return
		}
	}
	n.Format(ctx)
}
```
Note: by adding this print statement, your terminal will continuously be printing node types from queries running in the background. Make sure to clear your terminal (i.e. `\! clear`) and run your testing query afterward to see clear results.

Once you've added a print statement. Enter `cockroach demo` and test a query with a function: 
`SELECT lower('foo');`

The result looks like:
```
SELECT lower('foo')
*tree.Select
<nil>
*tree.With
SELECT lower('foo')
*tree.SelectClause
&[{lower('foo') }]
*tree.SelectExprs
&{lower('foo') }
*tree.SelectExpr
lower('foo')
*tree.FuncExpr
lower
*tree.ResolvableFunctionReference
lower
*tree.UnresolvedName
lower
*tree.Name
'foo'
*tree.Exprs
'foo'
*tree.StrVal
&[]
*tree.LockingClause
  lower
---------
  foo
(1 row)

Time: 1ms total (execution 0ms / network 0ms)
```

Note that `lower`'s type is printed as `*tree.UnresolvedName` and eventually `*tree.Name`, rather than `FunctionDefinition`.

**Expected behavior**
I expect that SQL functions (e.g. `count`, `lower`) to be typed as `FunctionDefinition` instead of `UnresolvedName`.

**Additional context**
What was the impact?

These functions do not hold sensitive information, and thereby do not need to be redacted from logs. However, by typing these function names as `UnresolvedName`, they are interpreted as unsafe information, and are incorrectly redacted. Correctly typing these functions as `FunctionDefinition` ensures function names are not redacted from logs.

**Comment by knz** [comment]
@rytaft do you think you have an explanation from the top of your head for the behavior found by Thomas above?

**Comment by rytaft** [comment]
Is this print statement getting called on the AST? I don't think we ever go back and update the AST after resolving the function. For example, this is where the `FunctionDefinition` is resolved for scalar functions in the optimizer: https://github.com/cockroachdb/cockroach/blob/4b1a92a7396081e865d70fa8c51ccb47fa3c9e23/pkg/sql/opt/optbuilder/scalar.go#L489
As you can see in the code, the resolved `def` is not used to update the AST. Instead, it's used to construct the memo (in the `ConstructFunction` call here: https://github.com/cockroachdb/cockroach/blob/4b1a92a7396081e865d70fa8c51ccb47fa3c9e23/pkg/sql/opt/optbuilder/scalar.go#L508
I'm not sure what the solution to this is, because I don't think we necessarily want to update the AST. I think that may have other unintended consequences.

**Comment by knz** [comment]
Ok so @THardy98 as I was explaining elsewhere the best thing to do is to not look at `FunctionDefinition` but instead look at `FuncExpr`.
