### ISSUE TITLE
add OLAP engine ?

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#66937]
cockroachdb is awesome for OLTP workload, is there any plan to support tables with column-store or an OLAP engine ?

**Comment by RaduBerinde** [comment]
Hi! There are no plans to implement columnar storage in the short to medium term. The distinction between OLTP and OLAP is fairly blurry and we are steadily getting better at the more "OLAP-y" queries that are frequently used with an otherwise transactional workload. In particular, our latest execution engine is columnar (it works on batches of values for a column at a time).

I will close this issue. Feel free to use the [forum ](https://forum.cockroachlabs.com/) or [community slack](https://www.cockroachlabs.com/join-community/) for more discussion.
