### ISSUE TITLE
acceptance tests on not master branches fails after go version upgrade

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach#66977]
In https://github.com/cockroachdb/cockroach/pull/66505 we upgraded the go version to `1.16.5`, but still have one outstanding task to upgrade the version on TeamCity agents.

The acceptance test [builds the test binary using docker](https://github.com/cockroachdb/cockroach/blob/53dcc3aec3a62adffc92c4675f80311864c8cc96/build/teamcity-acceptance.sh#L31), what means that for the `20.2` and `21.1` branches they are built using go `1.15.11`.

Then it executes the [`go test` command without docker](https://github.com/cockroachdb/cockroach/blob/53dcc3aec3a62adffc92c4675f80311864c8cc96/build/teamcity-acceptance.sh#L44-L47), what means it uses go `1.16.5`.

As a result the acceptance test fails to start with `flag provided but not defined: -test.paniconexit0`.
See
 https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Acceptance/3119347:id/raw.0.json.txt.tgz!/artifacts/full_output.txt
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Acceptance/3119347

`-test.paniconexit0` is a new flag from https://github.com/golang/go/commit/4f76fe86756841befb6574ce4bf04113d14389d4

Possible solutions:

* Run the acceptance test using `builder.sh`. Not sure if it's possible, because there is a lot of docker related things going under the hood in the acceptance test.
* (temporary solution?) Install go `1.15.11` on the TeamCity agents in parallel with go `1.16.5` and use an absolute path call to `go test` for not master branches.
* (bad idea) Patch go to not pass that flag
* Use bazel

**Comment by jlinder** [comment]
The second solution (install go 1.15.11 on the TeamCity agents in parallel with go 1.16.5 ...) seems like the quickest way to resolve this problem. If we were only to do this, it would likely live until we stop releasing 21.1 in November 2022 (because we are unlikely to replace CI with bazel on master before we cut the `release-21.2` branch in September). 

Using bazel for master forward is ideal, but it will take some time to replace CI with bazel on master (probably until after the `release-21.2` branch is cut in September).

Run the acceptance test using `builder.sh` might work, but running docker in docker seems not so great. And how would it perform?

**Comment by rickystewart** [comment]
+1 to all of the above.

**Comment by rail** [comment]
https://github.com/cockroachdb/dev-inf/issues/484 fixes this.
