### ISSUE TITLE
storage: add setting to reject AddSSTable if store more than x% full

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#66970]
AddSSTable has the ability to fill a disk relatively quickly (by design!). However this makes them good at getting into a out-of-disk situation as well.

Bulk jobs are the only users of AddSSTable and, while we don't _want_ them to fail, we'd rather a bulk job which is always acting on an offline table or part of table to fail, rather than fill the disk to the point critical traffic (like, heartbeats needed to say, be available enough to drop tables / free space) fails instead. Thus we may want these jobs to fail themselves if they try to send an AddSSTable to a store that is, e.g.  >95% full.

As an added bonus, if we used a tagged error type, we could even at some later point detect that error in the job and potentially pause it instead of outright failing (which could let us be more aggressive with the default for this size limit).

Jira issue: CRDB-8309

**Comment by dt** [comment]
cc @jbowens

**Comment by jbowens** [comment]
In https://github.com/cockroachdb/cockroach/issues/66493#issuecomment-861788550 we're exploring rejecting writes more generally when a quorum of a range's replicas' stores are approaching out-of-disk.

> As an added bonus, if we used a tagged error type, we could even at some later point detect that error in the job and potentially pause it instead of outright failing (which could let us be more aggressive with the default for this size limit).

Another thing I've been pondering with #66493 is whether it's desirable to fail versus pause any jobs that are writing to dead keyspaces. If we're about to start rejecting writes, which will start failing SQL queries, it seems preferable to reclaim any disk space in dead keyspaces that we can. I'd rather have my in-progress schema change automatically reverted rather than application queries rejected.

**Comment by dt** [comment]
Yep, I think we (bulk) were just thinking that doing something in `evalAddSStable` might be a quick, easy place to start, since these ops are _only_ ever used by bulk-jobs and failing them should thus not affect production traffic (and they're _likely_ *why* you'd running out of space too), so we could have a setting specific to them that kicks in long before more general write restrictions, special modes, etc. As a first approximation, if it was just checking against the leaseholder's store initially, this could be a <20 line add-only diff that might even backport cleanly. /2¢

**Comment by jbowens** [comment]
Got it, makes sense!
