### ISSUE TITLE
ui: add an alert if upgrade is not finalized for a long time

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#66987]
We have seen at least a case where a user did not finalize a major version upgrade, which manifested much later at the next upgrade.

Upgrade instructions are here: https://www.cockroachlabs.com/docs/v20.2/upgrade-cockroach-version#step-3-decide-how-the-upgrade-will-be-finalized

The DB Console should alert the user if the upgrade is in non-finalized state for a while; e.g. check if `cluster.preserve_downgrade_option` has been set for a long time.

---

2023-02-23 addendum from @rafiss: As we saw in [this incident](https://cockroachlabs.atlassian.net/wiki/x/MgARrg), it would also be useful to show if a cluster was recently upgraded. But the warning about not being finalized is much more important.

---

Jira issue: CRDB-8317

**Comment by thtruo** [comment]
We're tracking another issue that seems related to this https://github.com/cockroachdb/cockroach/issues/67330

**Comment by rafiss** [comment]
Tagging this with O-postmortem since it came up as an action item after [this incident](https://cockroachlabs.atlassian.net/wiki/x/MgARrg). @jordanlewis suggested that @cockroachdb/sql-observability could be a home for this.

**Comment by rafiss** [comment]
I see that the DB Console shows this banner: 
<img width="1630" alt="Screenshot 2023-03-27 at 4 43 06 PM" src="https://user-images.githubusercontent.com/1320573/228130952-0d2adb3a-3d87-498a-a812-2cfe10f56406.png">

But nothing is shown if all the nodes are running on the new version, but the cluster is not finalized.

Perhaps this banner can be enhanced so that it also checks the result of `SHOW CLUSTER SETTING version` and makes sure it matches the binary version.

**Comment by rafiss** [comment]
re-adding label as per convo: https://cockroachlabs.slack.com/archives/C0159JK877C/p1680803962312889?thread_ts=1680803608.397579&cid=C0159JK877C

**Comment by maryliag** [comment]
An alert was added on DB Console on 22.2: https://github.com/cockroachdb/cockroach/pull/82633

**Comment by rafiss** [comment]
@maryliag I don't think that alert covers the case where preserve_downgrade_option is unset, but the upgrade is not finalized because an upgrade is stuck. That scenario was what happened in the two incidents that led to this issue being filed as a postmortem followup.

**Comment by maryliag** [comment]
@rafiss for this specific case, how can we tell the upgrade is stuck? (just looking for what exactly I should be checking to add to the alert)

**Comment by maryliag** [comment]
is there a specific command you use to know that "all nodes are on the same binary version"?

**Comment by rafiss** [comment]
No I don't know how that check is made, but as I pointed out in my comment above, the DB Console already has a way to check that, since it shows this warning if the nodes are not on the same binary version.

<img width="1630" alt="Screenshot 2023-03-27 at 4 43 06 PM" src="https://user-images.githubusercontent.com/1320573/228130952-0d2adb3a-3d87-498a-a812-2cfe10f56406.png">

**Comment by rafiss** [comment]
https://github.com/cockroachlabs/support/issues/2368 and https://github.com/cockroachlabs/support/issues/2295 are two more examples of support cases where this would have helped. Resolving this issue would help a lot with reducing support and customer confusion.
