### ISSUE TITLE
opt: revisit use of round_decimal_values in optbuilder

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#67083]
This issue tracks revisiting the use of `round_decimal_values` in optbuilder, in light of the comments in https://github.com/cockroachdb/cockroach/pull/66885#issuecomment-871447073

We believe that a cast to the target type might do the same thing, and that could be implemented in a more uniform (non-DECIMAL-specific) way (using `ReType` in the right places).

**Comment by mgartner** [comment]
If we can remove `round_decimal_values`, we might be able to avoid [this hack](https://github.com/cockroachdb/cockroach/pull/61578).

----

I spent a few minutes trying to take out the use of `round_decimal_values` by changing [some lines in `optbuilder/values.go`](https://github.com/cockroachdb/cockroach/blob/2e5cce372e402faa2155c6f6e85410a9c7bdd238/pkg/sql/opt/optbuilder/values.go#L74-L77):

```diff
+ texpr := inScope.resolveAndRequireType(expr, desired)
- texpr, err := tree.TypeCheck(b.ctx, expr, b.semaCtx, desired)
- if err != nil {
- 	panic(err)
- }
```

This seemed like it could work, but I saw some immediate issues, such as:

* [This test case](https://github.com/cockroachdb/cockroach/blob/58a6686c1d2e6e30d6d0eb95fca2f727baa670fa/pkg/sql/logictest/testdata/logic_test/insert#L132-L133) resulted in a different error message, probably because type checking fails when the values are type checked before `checkDatumTypeFitsColumnType` is called.
* Tests like [this one](https://github.com/cockroachdb/cockroach/blob/58a6686c1d2e6e30d6d0eb95fca2f727baa670fa/pkg/sql/logictest/testdata/logic_test/insert#L515-L516) succeed instead of failing.
