### ISSUE TITLE
bazel: use `buf protoc` instead of `protoc` in the Bazel build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#67091]
* [Wait for `buf` to support](https://github.com/bufbuild/buf/issues/357) `--descriptor_set_in`, see discussion here: https://github.com/cockroachdb/cockroach/pull/66913, esp https://github.com/cockroachdb/cockroach/pull/66913#issuecomment-870961729
* Add a shim `sh_binary` that depends on `@com_github_bufbuild_buf//cmd/buf` and does nothing except call `buf protoc "$@"`
* In `.bazelrc`, add `build --proto_compiler=//path/to/shim:protoc`
* Patch `rules_go` to allow configuring the `protoc` used (see https://github.com/bazelbuild/rules_go/blob/4cd45a2ac59bd00ba54d23ebbdb7e5e2aed69007/proto/compiler.bzl#L218; rename `_protoc` -> `protoc`)
* We'll probably have to patch `gazelle` to allow configuring a `protoc` as well -- probably something like `gazelle:go_protoc //path/to/shim:protoc`.

Epic CRDB-8036

**Comment by rickystewart** [comment]
Requires https://github.com/bufbuild/buf/issues/357

**Comment by rail** [comment]
We chatted with Ricky about this issue and the consensus is that after the `buf`'s `--descriptor_set_in` feature is implemented, the rest would be very straight forward to implement. We don't even need to change anything in gazelle.

Some notes:
* Need to pass `protoc` to all `go_proto_compiler` entries in `pkg/cmd/protoc-gen-gogoroach/BUILD.bazel`
* Need to patch `@com_github_grpc_ecosystem_grpc_gateway` in order to use the `buf` (we already use patches for this target)
*

**Comment by rail** [comment]
I'm going to return this issue to the pool until we are unblocked.

**Comment by rickystewart** [comment]
`buf protoc` is [deleted](https://github.com/bufbuild/buf/pull/915). We're stuck with `protoc` for now.
