### ISSUE TITLE
gogoproto's customtype is only supported for the byte wire-type

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#671]
See gogo/protobuf#46 which was my stab at fixing the bug. It's not clear that my change will be accepted as it has flaws (e.g. causes the behavior of the reflect-based marshal/unmarshal to differ from generated marshal/unmarshal). I think we should stop using customtype with non-byte wire-types.

**Comment by bdarnell** [comment]
There are issues with custom types for the bytes wire type as well (it generates a pointer to a byte slice and it occasionally gets confused about the difference between the field being nil and the slice pointed to by the field being nil). I'm not sure if it's worth keeping the proto.Key type around. (We could replace proto.Key with `[]byte` but keep using proto.EncodedKey in code since it rarely appears in protos. This would retain most of the safety we currently get from the custom types for bytes fields).

**Comment by petermattis** [comment]
We only use `EncodedKey` in the `RawKeyValue` message which itself is never sent over the wire.

**Comment by spencerkimball** [comment]
Who wants to own this?
