### ISSUE TITLE
kv: Derive default retry options from network latency

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6719]
The default retry options (used in DistSender and other places) are currently hard-coded (in `base/context.go`) However, the optimal retry backoff is a function of network latency (it doesn't really sense to retry after 50ms if making progress requires 100ms round trips). We should either make this configurable (perhaps combined with `--raft-tick-interval`) or automatically tune it based on observed latency (unlike `--raft-tick-interval`, it doesn't have to be consistent across all nodes so we could have each node compute its own observed latency)

See #6689

**Comment by bdarnell** [comment]
SendNextTimeout is not used in retry.Options, but it serves a similar purpose and should also be set in part based on network latency.

**Comment by andreimatei** [comment]
Should there be a mechanism to differentiate between send that's slow for an unknown reason (network), and might benefit from sending to another replica (because maybe we had an old leader in our cache), from a send that got to the right leader and is being processed, but just takes a while?

**Comment by bdarnell** [comment]
@andreimatei That would be beneficial, but it sounds complex. Do you have an idea for how we could introduce this kind of signal that work is in progress? (in theory it's easy with grpc streaming responses, but I think it would be tricky in practice)

**Comment by petermattis** [comment]
Marking this as 1.0 as we might need to do something here for high latency configurations.

**Comment by spencerkimball** [comment]
@bdarnell I don't think it makes sense to set the `DistSender` retry options based on network latency. Those only take effect after `DistSender.sendToReplicas` fails after making efforts to try all replicas in the set (or fails faster because of a non-retryable error). Retrying in `50ms` after a failure of `DistSender.sendToReplicas` seems fine...it's just a near-immediate retry, followed by an exponentially increasing timeout between successive retries. What's key here is that we're not "giving up" on extant RPCs because of high latency.

As to `kv.SendOptions.SendNextTimeout`, I think the default of `500ms` still risks being problematic for very high latency setups (we'd be issuing multiple RPCs per KV request for a cluster spanning Australia and Europe, for example). For that reason, I think we should actually set it to `1s`, which is a safer default for the time being, and not one which is likely to screw up anyone's performance. Note that `SendNextTimeout` only comes into play *before* a replica is considered unhealthy due to `rpc.Context` heartbeat failures. Given that the default Raft election timeout is 9x higher, there's an insignificant (at best) win for latency with `SendNextTimeout=500ms` vs. `1s`. I'm thinking of cases where an RPC to the original leader is "black holed" and we need to retry at another replica to find the new Raft leader.

A better mechanism than the `SendNextTimeout` we currently implement *might* be to instead key the next replica attempt off of the `rpc.Context`'s connection heartbeat failing. Unfortunately, when I looked at doing this, it became clear that the code considers even commands sent to local replicas as being subject to timeouts, so we'd potentially be introducing new failure modes if we suddenly stopped sending to alternate replicas while an RPC to a local replica is still pending.

**Comment by bdarnell** [comment]
Yeah, SendNextTimeout shouldn't be a function of network latency. In fact, I think it might even be obsolete since we shut down the connection on heartbeat timeouts. The idea was to do ["speculative retries"](http://www.bailis.org/blog/doing-redundant-work-to-speed-up-distributed-queries/) to minimize tail latency, but that doesn't really help unless the timeout is very low, and we can't set it too low without causing ambiguous errors. 

We use `retry.Options` a lot less now (after the push txn queue), so I think it's probably fine to leave that with the default 50ms hardcoded. One thing that we *might* want to auto-tune with network latency is the interval used with `refreshReasonTicks`, but that's set so high in comparison that network latency that it's probably not worth it. I don't think there are any retry-related knobs left to adjust for network latency, so we can just close this.
