### ISSUE TITLE
protectedts: support tenants

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#67271]
Protected timestamps do not work as expected when used from inside a tenant.  When a protected timestamp is created, entries are created in the tenant-scoped system.protected_ts_meta and system.protected_ts_records tables. But, the GC system only looks at the system-tenant scoped version of those tables.

Epic CRDB-10558

**Comment by ajwerner** [comment]
Adding more context here. One now understood problem with protected timestamps is that they capture spans but don't provide a means to express hierarchy like protecting a database. Zone configurations do permit expressing KV-level configuration over those hierarchies. I don't honestly recall why we didn't use the zone config infra at the time. I think we were scared of it (for good reason) and worried about writing lots of updates to it.

Much work has been done to adopt zone configurations in tenants https://github.com/cockroachdb/cockroach/pull/66348. In practice, a protected timestamp is, roughly, a timestamp on a zone config and some metadata so we can go clean it up. It'd be cool if we could implement it that way for tenants.

There have been some discussions about the fact that the lack of inheritance means that writing protected timestamp records may lead to write amplification. For the first pass, that seems fine. We can optimize with inheritance later if need be.

**Comment by ajwerner** [comment]
cc @irfansharif

**Comment by irfansharif** [comment]
More of a (lazy) organizational question, is the ask here primarily from CDC? BulkIO? Or Multi-Region?

**Comment by nvanbenschoten** [comment]
> In practice, a protected timestamp is, roughly, a timestamp on a zone config and some metadata so we can go clean it up. It'd be cool if we could implement it that way for tenants.

It's also the ability to go verify that a protected timestamp has propagated to the leaseholders of all ranges that it influences through the `AdminVerifyProtectedTimestamp` API, so that the protection against GC is guaranteed beyond a certain point. That seems like the largest missing piece necessary to unify these two systems. However, this API isn't closely tied to protected timestamps. It's possible to generalize to any system with versioned changes and async propagation. So a more general `AdminVerifySpanConfig` API could be a reasonable replacement.

That said, my recollection is that the practical difference between a protected timestamp system with "eager verification" and "lazy verification" was quite small. With eager verification, we detect cases where the protected timestamp raced with GC and could not provide a guarantee immediately after installing the protected timestamp. Clients could wait for this verification to complete before starting their work with the safety of knowing that their protected timestamp would continue to be respected. But we don't actually take advantage of that to the full extend, as KV operations all still do check the GC threshold. With lazy verification, there was no immediate check, so clients would have to be prepared to handle `BatchTimestampBeforeGCError`s at any time during operation, and all KV operations must check the GC threshold. In theory, this risks expensive rollback operations. But in practice, I'm less sure this is a serious problem.

@ajwerner can you correct me on this? Would protected timestamps without eager verification still provide value to CDC?

**Comment by irfansharif** [comment]
Subsumed by #73727.
