### ISSUE TITLE
backupccl: decouple scheduled backups from the GC TTL

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#67282]
This issue captures a conversation between @dt and @andreimatei about decoupling scheduled backups from GC TTL which would allow us to dramatically reduce the current TTL of 25h.

Scheduled backups, when they run, can include dropping a protected timestamp at the time that they backed up and then *leave it there*, after the backup completes, until the following backup runs which then releases that protected TS and protects the next one, etc. If we did this, we’d never actually rely on the configured TTL at all for inc backups and just protect/release each time span once we’ve archived it out to external storage.

The protected timestamp record itself has the option to ask to protect “at” or “above” — they’re currently both just implemented as “above” under the hood but in theory “at” could allow GC’ing between protected two times as long as it left delete tombstones. If scheduled backups relied on protected ts instead of TTL, then we could leave a `protect_above` only for a `revision_history`  schedule and `protect_at` otherwise. Then it is up to the operator to decide if they want all revisions of all rows archived (which they might need, e.g. for compliance), and if so, they’ll pay associated the MVCC cost of retaining those revisions until they’re archived and can adjust the schedule frequency accordingly to compensate if needed.

A follow-up task might be to indicate to users running ad-hoc (non-scheduled backup) with revision history, to either manually bump their TTL or use scheduled backups.

Jira issue: CRDB-8470

Epic CRDB-14925

**Comment by dt** [comment]
maybe some overlap with #54530

**Comment by adityamaru** [comment]
Initial discussions can be found in #67633 but moving information to the issue instead.

Highlighting some key discussion points after brainstorming with @miretskiy:

1. First full backup will "bootstrap" the protected timestamp chain. `NotifyJobTermination` of the first full backup anyways resolves the incremental schedule to unpause, and so it will also deposit the ID of the timestamp record it has persisted somewhere in the incremental schedule. From then on, only backups triggered by virtue of the incremental schedule will be concerned with updating this persisted timestamp record field and protecting appropriate data for the following incremental backups in the chain. Recurring full backups (as well as FULL BACKUP ALWAYS schedules) do not need to concern themselves with the baton passing of protected timestamps. This simplifies the logic as we do not have to couple the "parent" full schedule and the "child" incremental schedule. We also get a rather clean solution to the "overhang"* scenario by allowing incrementals on either side of a recurring full to do the right thing wrt PTS records, instead of bookkeeping the PTS records across the incremental and full schedules.

2. Every incremental backup on termination will:
    a) Lay down a protected ts record to protect data after its `EndTime`.
    b) Store information about this protected ts record on the incremental schedule in a `protectedRecords` slice.
    c) Check if there are any other running incremental jobs under this schedule, if not release all records in the slice except the latest.

2a) and 2b) warrant further discussion:

Take an example where we have 2 scheduled incremental backups:
- B1 starting at t1
- B2 starting at t2

Assume a backup prior to B1 has laid a protected ts protecting all data after t0. Now imagine a situation in which B1 is planned before B2, but the actual execution of B2 completes before the execution of B1.
Following the steps we enumerated above:
- Both B1 and B2 would start execution relying on the protected ts record of the "previous" backup at t0.
- B2 on job termination would lay a protected ts record at t2, update the `protectedRecords` slice to `{t0, t2}` but cannot release the protected ts record at t0 since B1 is still running.
- B1 on job termination will lay a PTS at t1, , update the `protectedRecords` slice to `{t0, t2, t1}`. The job would then check that there are no other jobs running under this schedule. This gives us the invariant that the next backup job that will run as part of this schedule, will only rely on the latest backup in the chain to build on top off. So, it is safe to drop the protected ts records of everything but the latest record. The truncated `protectedRecords` slice would be `{t2}`.

The above scenario while a corner case is not outlandish; one could imagine 5 mins incrementals, that each take 15 minutes to run, and don't wait for the previous to complete before running.

*overhang is the time window in which we might have incremental backups running concurrently with a scheduled full backup. Until the full backup completes, the incremental backups continue to add to the old chain. As soon as they see a new full in the directory, incrementals switch to the new chain of backups.

**Comment by miretskiy** [comment]
To add a note regarding reconciliation: We can always rely on the next incremental to cleanup; and if the schedule is dropped, then, the PTS record will also be dropped-- and any error dropping the record would bubble up to the caller.

**Comment by dt** [comment]
We could keep the current behavior of the executing _backup_ starting by protecting the lower of its start or end time, independent of any ts protection that is associated with the _schedule_. Then we don't need to worry about what happens if B2 releases the schedule protection record while B1 is still running, right? In practice, this would _likely_ end up with every backup starting by protecting the exact same timestamp the schedule is protecting, but I dunno, that's probably OK?

**Comment by adityamaru** [comment]
Noting a few things I want to do before considering this issue done:

- Add a roachtest that runs a scheduled backup with a very low default GC TTL.
- Add a migration to mark all system tables that we do not backup as `exclude_data_from_backup`. This will prevent a scheduled cluster backup from holding up GC TTL on these tables.
- Discuss if we should add a warning for non-scheduled backups to indicate that they are still coupled with GC TTL.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-8470](https://cockroachlabs.atlassian.net/browse/CRDB-8470) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-67282` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-8470](https://cockroachlabs.atlassian.net/browse/CRDB-8470) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-67282`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date
