### ISSUE TITLE
Some way to see errors that were "hidden behind barrier"

### ISSUE THREAD

**Issue by dpkirchner** [cockroachdb/cockroach#67463]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out the root cause of an error I'm seeing in a cluster but I'm bumping in to a "cause hidden behind barrier" warning, which suggests to me that the real reason for the error is being dropped on the floor.

**Describe the solution you'd like**
Assuming that "cause hidden behind barrier" is hiding useful errors, I would like to be able to disable this permanently, globally.

**Describe alternatives you've considered**
I haven't -- I'm not even sure that the behavior is a problem, although the warning text seems clear enough that it is.

**Additional context**
```
Build Tag:        v21.1.3
Build Time:       2021/06/21 19:57:59
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.15.11
C Compiler:       gcc 6.5.0
Build Commit ID:  af2c90b391faa0e0256b96269a0e3c2e29a0ca7b
Build Type:       release
```

**Comment by rafiss** [comment]
Hm, you are likely running into intended behavior. If you take a look at the errors library used by CockroachDB (https://github.com/cockroachdb/errors/blob/master/barriers/barriers.go) you can see that the "cause hidden by barrier" only is shown if someone intentionally decides to do so. The intended purpose is to avoid revealing sensitive or confusing details, or to avoid showing low-level information if an error from a lower layer is already handled.

But it's possible some part of CockroachDB is incorrectly using `barrierError`. Would you be able to share the error output that you saw?

**Comment by dpkirchner** [comment]
It may be that this was intentional, although I think that's problematic given it means I'm prevented from fully understanding the problem. If we assume that it's necessary to hide information from an administrator because it might be sensitive or confusing, then we automatically assume something about the administrator that may be unwarranted -- that they can't secure their logs or can't perform a good RCA if they were allowed to see the details.

The specific case that led to my feature request involves some infrequent authentication error that affects a bunch of users at once, but does not seem associated with any other conditions. I can't be certain about that last part, though, because some error details are hidden. I've pasted a snippet below.

There are other errors that suggest that there may be connectivity issues between the nodes, but I can't know if that is an actual failure to connect/maintain a TCP/GRPC connection or if it's some other error that manifests itself the same way (cockroachdb is the only code reporting any problems).

In any case, I can probably figure out connectivity issues if they exist, but I can't be sure there won't be some other future error that will be deliberately hidden from me. I'd like to be able to globally disable the hidden-behind-barrier feature entirely so I can be sure I have as much information as is possible when something goes wrong. I can build my own copy from source that does just that, however I'm guessing I'm not the only one that would want error details, hence the feature request.

```
W210711 12:05:31.912781 8662256 sql/user.go:186 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29440  user lookup for ‹"username"› failed: ‹get-login-dependencies›: context canceled
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441  user retrieval failed for user=‹"username"›: internal error while retrieving user account: ‹get-login-dependencies: context canceled›
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +(1) attached stack trace
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  -- stack trace:
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | github.com/cockroachdb/cockroach/pkg/sql.retrieveUserAndPassword
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:187
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | github.com/cockroachdb/cockroach/pkg/sql.GetUserHashedPassword
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:87
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/auth.go:91
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:606
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | runtime.goexit
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |      /usr/local/go/src/runtime/asm_amd64.s:1374
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +Wraps: (2) internal error while retrieving user account
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +Wraps: (3) ‹get-login-dependencies: context canceled›
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | -- cause hidden behind barrier
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | ‹get-login-dependencies›: context canceled
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  | (1) secondary error attachment
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   | ‹get-login-dependencies›: context canceled
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   | (1) attached stack trace
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   |   -- stack trace:
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   |   |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:658
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next.func1
W210711 12:05:31.912965 8662256 sql/pgwire/auth.go:95 ⋮ [n2,client=‹10.44.0.33:54316›,hostssl,user=‹username›] 29441 +  |   |   |      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:273
```

**Comment by rafiss** [comment]
Sorry, I spoke incorrectly before. I shouldn't have said that the reason was to avoid showing sensitive details. My understanding was off before. Let me explain:

Thanks for sharing your error. The error you shared comes from here: https://github.com/cockroachdb/cockroach/blob/af2c90b391faa0e0256b96269a0e3c2e29a0ca7b/pkg/sql/user.go#L184-L188

So line 186 logs the "cause" error and this cause is then passed to the higher level error with `errors.Handled`. The "cause hidden behind barrier" message is only shown when this higher level error is logged here: https://github.com/cockroachdb/cockroach/blob/af2c90b391faa0e0256b96269a0e3c2e29a0ca7b/pkg/sql/pgwire/auth.go#L91-L98

Now the key thing to see is that the `‹get-login-dependencies›: context canceled` error is in fact logged in the stack trace you shared. The [docs from the errors library](https://github.com/cockroachdb/errors/blob/72ec75208141a2b67e79909b28aea29ed2189108/barriers/barriers.go) explain:

```
// Handled swallows the provided error and hides it from the
// Cause()/Unwrap() interface, and thus the Is() facility that
// identifies causes. However, it retains it for the purpose of
// printing the error out (e.g. for troubleshooting). The error
// message is preserved in full.
```

In other words, the "cause hiding" logic only affects comparing errors using `Is()`, and does not affect how the error is formatted. And to confirm, you can see here that the error cause is printed after the "cause hidden" message: https://github.com/cockroachdb/errors/blob/72ec75208141a2b67e79909b28aea29ed2189108/barriers/barriers.go#L100

So your feature request is already resolved (though if the current language is confusing, maybe we should adjust that).

---

To discuss this error specifically, it means that there was a timeout when retrieving the information needed to authenticate a user (like a hashed password or per-user options). The `server.user_login.timeout` cluster setting determines how big the timeout is. It defaults to 10 seconds.

Taking more than 10 seconds to load this information is definitely bad, but the error here is from a context timeout, so it won't have any more information about why it was taking so long. There might be other logs in your cluster that explain why things took so long. You also might be able to go to the Statements page in the DB Console and look for queries against the `system.public.users` or `system.public.role_options` tables to see more information about the queries that timed out.

**Comment by knz** [comment]
@dpkirchner as Rafi explained, the text "cause hidden behind barrier" should not be an impediment to understand the root cause of an issue. The message of the original error is still included.

What do you want to do with this github issue? If you wish to keep this title/focus, there is not much else we can do and I suggest to close the issue. However, if your real concern is to understand the cause of the timeout, we can give the issue a new title and pick it up from there. What would you prefer?

**Comment by dpkirchner** [comment]
Thanks for the clarification @rafiss, that helped. I'll admit the wording did "trigger" me a bit -- feels like half of the errors I run in to on a daily basis have no context (in general, not cockroachdb) and for software to say it deliberately hid details set me off.

@knz I'll close the issue, it sounds like it's resolved in that the error is logged in another place. I'll try to figure out why my (idle) cluster is having so many connectivity issues -- 10s is indeed a long timeout. But it's probably a configuration error on my end rather than an issue with cockroachdb specifically.

Thanks everyone.
