### ISSUE TITLE
opt: grossly incorrect selectivity estimation for correlated columns

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#67573]
A customer noticed a case where we weren't constraining the primary index and doing a full table scan instead. I tracked down the cause to a grossly incorrect row count for a Select - much larger than the number of input rows! This made the constrained Scan (which would be in the same group with the Select) seem much more expensive.

We have a multi column PK and the columns are correlated. We are constraining the first two columns `a,b` to certain values. Statistics are as follows:
 - the table has ~100k rows
 - the first column has ~20k distinct values, but the histogram shows that ~60k rows have the constrained value
 - the second column has ~7k distinct values, but the histogram shows that ~7k rows have the constrained value
 - a multi-column stat for the two columns indicates ~20k distinct composite values.

Looking at the selectivity code, this is what happens:
https://github.com/cockroachdb/cockroach/blob/706f0d260c01093975391c5d0288c899393f3c44/pkg/sql/opt/memo/statistics_builder.go#L808

Input row count: 100,000
First, we apply the selectivity from the histograms: `60/100 * 7/100`.  Row count: 4200
Then we apply the selectivity from the distinct counts. This is a "blend" of the independent formula `(1/20,000 * 1/7,000)` and the multi-col formula `(1/20,000)`. The latter is the dominant term. Row count: 0.189003.
The other steps don't do much until the last one. We "unapply" the selectivity from the single-column distinct counts. But we didn't really apply this selectivity before (it was a part of step 2 but it it had an insignificant effect). So now we multiply back with 20,000*7,000 and row count is now 26M.

I don't quite know why the code does what it does so I am not sure how to change it. At a very high level, it feels that we should fully calculate the final selectivity with different approaches and "blend" those at the end (rather than "blending" inside a step).

In addition, we are missing some safeguards - a higher output count than an input count should be a panic in test builds (with a reasonable fallback in production).

Opt file to reproduce:
```
exec-ddl
CREATE TABLE ab (
  a INT,
  b INT,
  c INT,
  PRIMARY KEY (a,b,c)
)
----

exec-ddl
ALTER TABLE ab INJECT STATISTICS '[
    {
        "columns": [ "a" ],
        "created_at": "2021-07-13 14:04:42.014148",
        "distinct_count": 20000,
        "histo_buckets": [
            {
                "distinct_range": 0,
                "num_eq": 60000,
                "num_range": 0,
                "upper_bound": "1"
            },
            {
                "distinct_range": 1,
                "num_eq": 40000,
                "num_range": 0,
                "upper_bound": "2"
            }
        ],
        "histo_col_type": "INT8",
        "name": "__auto__",
        "null_count": 0,
        "row_count": 100000
    },
    {
        "columns": [ "b" ],
        "created_at": "2021-07-13 14:04:42.014148",
        "distinct_count": 7000,
        "histo_col_type": "",
        "name": "__auto__",
        "histo_buckets": [
            {
                "distinct_range": 0,
                "num_eq": 7000,
                "num_range": 0,
                "upper_bound": "1"
            },
            {
                "distinct_range": 1,
                "num_eq": 93000,
                "num_range": 0,
                "upper_bound": "2"
            }
        ],
        "histo_col_type": "INT8",
        "name": "__auto__",
        "null_count": 0,
        "row_count": 100000
    },
    {
        "columns": [ "a", "b" ],
        "created_at": "2021-07-13 14:04:42.014148",
        "distinct_count": 20000,
        "histo_col_type": "",
        "name": "__auto__",
        "null_count": 0,
        "row_count": 100000
    }
]';
----


norm format=show-stats
SELECT * FROM ab WHERE a=1 AND b=1
----
select
 ├── columns: a:1!null b:2!null c:3!null
 ├── stats: [rows=26460420, distinct(1)=1, null(1)=0, distinct(2)=1, null(2)=0, distinct(1,2)=1, null(1,2)=0]
 │   histogram(1)=  0 60000
 │                <---- 1 -
 │   histogram(2)=  0 7000
 │                <--- 1 -
 ├── key: (3)
 ├── fd: ()-->(1,2)
 ├── scan ab
 │    ├── columns: a:1!null b:2!null c:3!null
 │    ├── stats: [rows=100000, distinct(1)=20000, null(1)=0, distinct(2)=7000, null(2)=0, distinct(3)=10000, null(3)=0, distinct(1,2)=20000, null(1,2)=0]
 │    │   histogram(1)=  0 60000 0 40000
 │    │                <---- 1 ----- 2 -
 │    │   histogram(2)=  0 7000 0 93000
 │    │                <--- 1 ----- 2 -
 │    └── key: (1-3)
 └── filters
      ├── a:1 = 1 [outer=(1), constraints=(/1: [/1 - /1]; tight), fd=()-->(1)]
      └── b:2 = 1 [outer=(2), constraints=(/2: [/1 - /1]; tight), fd=()-->(2)]
```

**Comment by RaduBerinde** [comment]
Note that the number of buckets in the histograms don't match the distinct counts, but that doesn't affect the end result here.

**Comment by RaduBerinde** [comment]
If we look at each column in separation, we know that we're going to get at most `min(60k, 7k)` rows no matter how correlated the columns are. That should be an upper bound on the end result.

**Comment by DrewKimball** [comment]
I tried having `selectivityFromMultiColDistinctCounts` ignore hist cols in the 'single column' portion of its calculation and removed the `Unapply` bit. This fixed the problem query (estimated ~420 rows), but also ruined stats for a bunch of TPCH queries (by an order of magnitude), because applying the histogram estimates and the multi-column stats separately made estimates too selective.

Next, I tried removing the single column logic from `selectivityFromMultiColDistinctCounts` and combining it with the histogram stats - so, under the independence assumption, we use histograms for each column if available and otherwise distinct counts. Then I combined these 'independence assumption' stats with the multi-column stats in a weighted sum as before. This looked more promising - still fixed the problem query, and didn't change TPCH or TPCC stats much, but caused the wrong index to be chosen in some cases (`bad_idx` in `memo/testdata/stats/scan`).

**Comment by rytaft** [comment]
Thanks for looking at this, @DrewKimball. I just posted a PR for a slightly simpler fix that @RaduBerinde and I had discussed that basically introduces some "guardrails" to ensure that the row count is never estimated to be higher than it would be if the most selective individual filter were applied (instead of the conjunction of all filters).

It's still possible we can improve the basic formula of "apply"/"unapply", but I think this will at least be a good backportable fix.
