### ISSUE TITLE
DBConsole with redacted PII

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#67591]
**Is your feature request related to a problem? Please describe.**
We cannot deploy DBConsole in production because of the risk of PII exposure.
In the case of a support issue CRL Support like to use DBConsole to understand the situation and for investigation.

**Describe the solution you'd like**
We would like DBConsole to be sensitive to PII and have the option to redact PII (perhaps based on a cluster setting per environment). If that means some features are not available then that is fine as long as CRL Support can live without it.

**Describe alternatives you've considered**
We have to rely entirely on Grafana and Prometheus for monitoring. DBConsole shows more information.

**Additional context**

Jira issue: CRDB-8620

Epic CRDB-12732

**Comment by thtruo** [comment]
I'm adding this to `Observability Infrastructure` as a nominal home because this idea would involve enhancing and tying together our redaction functionality to play nice with the DB Console cc @nkodali @dhartunian @knz

**Comment by thtruo** [comment]
Hey @cjireland we attempted to make forward momentum here with the following changes: 
https://github.com/cockroachdb/cockroach/issues/74716 for a new `VIEWACTIVITYREDACTED` role option and https://github.com/cockroachdb/cockroach/issues/74482 for a new `NOSQLLOGIN` role option (both backported to 21.1 and 21.2)

`VIEWACTIVITYREDACTED` makes it so that a user can similar access as `VIEWACTIVITY` except that they do not have access to PII such as statement bundles. And then `NOSQLLOGIN` makes it so that a user can access the DB Console but not have the ability to log into a SQL shell to access tables and databases directly. 

Let me know how far along this gets you. Is there anything else missing from your perspective?

**Comment by cjireland** [comment]
Hi @thtruo, that's great news! One concern we had was that reports within the Advanced Debug section may report PII. Possibly this would arise, in one example, as part of a range report. Can you confirm that if someone used some data that was PII as the PK (or another index) of a table then that PII would no longer be displayed?  Thanks
