### ISSUE TITLE
Slow schema migration on single node instance blocking development pipeline

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#67648]
**Describe the problem**

Customer is observing slower than expected schema migration response times during their development cycle testing on v21.1.1. The total schema migration time is multiple seconds and they expect <100ms from initialization to teardown. The cluster is a local CockroachDB instance with zero data in it. This is part of a test suite which is being run locally on MacOS as part of a CI/CD pipeline. This is how the database is initialized:

 ```
   val cmd = List(
            "cockroach",
            "start-single-node",
            "--insecure",
            "--listen-addr=localhost:26257",
            "--http-addr=localhost:8989",
            "--background"
          )
```

The user noted that when they run `cockroach demo` with the following initialization parameters, the test runs faster but still significantly slower than <100MS:

```
          val cmd = List(
            "cockroach",
            "demo",
            "--no-example-database",
            "--insecure",
            "--sql-port=26257",
            "--http-port=8989"
          )
```

Also, during testing they noticed that `cockroach demo` listens on a random IP every time it runs with `--insecure` on Linux machines. This is not the case when running it locally on macOS. They find this behavior unexpected and there's no argument to pass the host even though `--http-port` and `--sql-port` exist.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

See above & attached files

**Expected behavior**

Their expectation is that `cockroach start-single-node` should be fast with a single node running locally. One of the reasons they want initialization logic to be fast is because the test suite creates independent tables to allow test runs to execute in parallel and make every test isolated from each other.

**Additional data / screenshots**
[app_log_demo.txt](https://github.com/cockroachdb/cockroach/files/6820109/app_log_demo.txt)
[app_log_ssn.txt](https://github.com/cockroachdb/cockroach/files/6820111/app_log_ssn.txt)

See attached files

**Environment:**
 - CockroachDB version 21.1.1
 - Server OS: MacOS
 - Client app: Hikari

**Additional context**
Development blocked

Application logs from tests run on single instance database initialized with `cockroach demo` and `cockroach start-single-node` with the parameters described above are attached.

Jira issue: CRDB-8650

**Comment by rafiss** [comment]
Can the user share their migration files and the command they are using to run the migration?

> Their expectation is that `cockroach start-single-node` should be fast with a single node running locally. One of the reasons they want initialization logic to be fast is because the test suite creates independent tables to allow test runs to execute in parallel and make every test isolated from each other.

`start-single-node` runs on disk, while `demo` runs in memory. That is the biggest reason for the performance difference. They can make `start-single-node` run in memory by adding one more argument for `--store=type=mem`:

```
  val cmd = List(
           "cockroach",
           "start-single-node",
           "--insecure",
           "--listen-addr=localhost:26257",
           "--http-addr=localhost:8989",
           "--background"
           "--store=type=mem"
         )
```

> The user noted that when they run cockroach demo with the following initialization parameters, the test runs faster but still significantly slower than <100MS:

Can you please add more details? How much slower?

> Also, during testing they noticed that cockroach demo listens on a random IP every time it runs with `--insecure` on Linux machines. This is not the case when running it locally on macOS. They find this behavior unexpected and there's no argument to pass the host even though `--http-port` and `--sql-port` exist.

This is an entirely different issue than slow schema migrations. For the engineering team to be able to help most effectively, please file a separate Github issue so that the appropriate team can own that issue. (Also, perhaps this will no longer be an issue for them after updating the `start-single-node` command as described above.)

**Comment by ajwerner** [comment]
This likely is not actionable. If you provide more information about the types of changes and the latencies then maybe we could do something. Where does their expectation come from? Cockroach schema changes are more involved in cockroach than in, say, postgres because we need to coordinate cached state and wait for leases to drain. Additionally we set up fault tolerant jobs. This can make individual schema changes orders of magnitude slower than on postgres, but still not "slow" in terms of many seconds or minutes. Slow is in the eye of the beholder.
