### ISSUE TITLE
Configure sarama so that kafka does not reject a full batch when one message is rejected

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#67664]
We recently ran into an issue where a customer was batching a large number of messages. When one message in the batch was rejected, we continually tried to retry sending the entire batch, leading to a whole batch of messages  (minus one) being committed over and over again. 

We should make a configuration change so that if one message in a batch is rejected by kafka, we abort all of them.

Epic CRDB-8665

**Comment by miretskiy** [comment]
I assume batching applies to the kafka sink?
If so, I'm confused.  We configure kafka to batch X messages; but we emit 1 message at a time, and if any message
(in the batch or otherwise) fails, we propagate that error -- and restart the entire changefeed.
So, I guess they are seeing retries because we're never updating our cursor position.
That is: I just don't think we have any visibility into batching done internally by sarama client, and I'm not sure there
is anything we can do about this behavior.  

(Of course, in general, retrying forever is a bad behavior -- but changes in that area are tracked elsewhere)

**Comment by amruss** [comment]
Closing because this would be very hard to implement, we are instead going to rely on a more sophisticated retry policy (https://github.com/cockroachdb/cockroach/issues/67984) to better handle these situations
