### ISSUE TITLE
`system`-database must be deleted before cluster restore, but can't

### ISSUE THREAD

**Issue by DrFelder** [cockroachdb/cockroach#67698]
**Describe the problem**

We noticed the following behaviour when we introduced the BACKUP feature and tested it:
* to restore the full cluster, all existing databases/tables must be removed
* all tables can be deleted except `system`; root does not have sufficient privileges
* the cluster still can *not* be restored due to the following error: `ERROR: full cluster restore can only be run on a cluster with no tables or databases but found n descriptors:`

**Expected behavior**
* The tables that need to be removed to restore the cluster *can* be removed by the user if he has sufficient rights to restore the backup itself
* The tables *do not* need to be removed and CRDB handles the restoration of it's system tables.

Honestly, I have no idea if this behaviour is intended. The backup/restore feauters may not be as refined as we wish, but this is something that was nowhere to be found in any documentation.

**Environment:**
 - CockroachDB version v20.2.9
 - Running w/ 3 nodes inside k8s using the ~3.0.7 chart `cockroachdb` from https://docker-registry.contargo.net/chartrepo/public
 - Client app `cockroach sql`

Any other context? I had freshly brewed coffee on hand and was in a good mood.

Epic CRDB-7993

Jira issue: CRDB-8681

**Comment by pbardea** [comment]
Hi @DrFelder -- sorry for the delayed reply here.

Was a cluster restore previously attempted on this cluster? Cluster restore temporarily creates tables to handle restoring system tables are part of the restore process. It looks like when a RESTORE terminates (is either failed, canceled, or successful) the GC configuration of these tables is the default so they don't get dropped immediately. 

I've opened https://github.com/cockroachdb/cockroach/pull/67936 which should hopefully help this when merged, and the error message could be more helpful since it doesn't necessarily uniquely identify the table.

**Comment by stevendanna** [comment]
I think we've fixed this in a few ways: (1) we now lower the gc.ttl before dropping the relevant tables and (2) we now only care about namespace conflicts so we don't actually even have to wait for the gc.ttl.
