### ISSUE TITLE
sql: match postgres for casting 0 to regtype/regproc/regnamespace/regtype

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#67715]
Discovered through randomized testing. Postgres does this:

```
postgres=# select 0::oid::regproc;
 regproc
---------
 -
(1 row)

postgres=# select 0::oid::regprocedure;
 regprocedure
--------------
 -
(1 row)

postgres=# select 0::oid::regnamespace;
 regnamespace
--------------
 -
(1 row)

postgres=# select 0::oid::regclass;
 regclass
----------
 -
(1 row)

postgres=# select 0::oid::regtype;
 regtype
---------
 -
(1 row)
```

However, CockroachDB outputs `0` for all of these. This should be easy to special case, but let's watch out for possible backwards compat issues.

**Comment by ajwerner** [comment]
Fun! Yay randomized testing! It also works the other direction:

```
postgres=# SELECT '-'::regclass::INT;
 int4 
------
    0
```

**Comment by AnaghHegde** [comment]
@rafiss Is anyone working on this ? Can i take this up ?

**Comment by rafiss** [comment]
@AnaghHegde you definitely can! you will need to modify code in `pkg/sql/sem/tree/casts.go` https://github.com/cockroachdb/cockroach/blob/5c19f73e106fb54ea5c6970dd11baec42da03710/pkg/sql/sem/tree/casts.go#L502

and you can add tests in `pkg/sql/sem/tree/testdata/eval/cast`. i'd recommend starting with the tests first so you can see if your changes are working.

**Comment by rafiss** [comment]
Also, please make sure you've read our contribution guidelines https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072641/What+is+a+Good+CockroachDB+PR

**Comment by lpessoa** [comment]
@rafiss i had a go at this one since it is stalled for some time now. 
Not sure if i tackled it in the proper manner but i changed the 'Format' for 'DOid' structure so that when the 'DInt' value is zero it returns '-' like postgres.

https://github.com/cockroachdb/cockroach/blob/d556001291b4b64a37c2f83449cdaeedb54eb3dc/pkg/sql/sem/tree/datum.go#L808

It works fine using a normal postgres client for the above scenarios but i have some troubles when running the test suite for the _sem/tree_ package. Any hints? 😃
