### ISSUE TITLE
backupccl: add Apache Parquet format to export

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#67710]
**Describe the solution you'd like**
Ability to export to [Apache Parquet format](https://github.com/apache/parquet-format).

```
EXPORT INTO PARQUET
  'azure://acme-co/customer-export-data?AZURE_ACCOUNT_KEY=hash&AZURE_ACCOUNT_NAME=acme-co'
   FROM TABLE bank.customers;
```

**Describe alternatives you've considered**
Using CSV format

**Additional context**
Parquet stores the file schema in the file metadata. CSV files don't store file metadata, so readers need to either be supplied with the schema or the schema needs to be inferred. Supplying a schema is tedious and inferring a schema is error prone / expensive. A couple of large customers are asking for this feature.

Epic CRDB-10340

**Comment by techytoes** [comment]
Hi @livlobo, Can I pick this up? Also would be great if you can give a little context regarding what approach you have in mind?

**Comment by jlevesy** [comment]
Hello, 

I took a stab at this and managed to get a [minimal implementation](https://github.com/jlevesy/cockroach/blob/a8dd238342e68da6d4e01275d364548973c4bfce/pkg/ccl/importccl/exportparquet.go) that [makes this test pass](https://github.com/jlevesy/cockroach/blob/67710/add-parquet-exporter/pkg/ccl/importccl/exportparquet_test.go#L29). 

- I based my implementation on the CSV export. It introduces some duplication I believe could be factorized.
- I made the necessary changes so that `EXPORT INTO PARQUET ...` becomes a valid query. However it does not offer the possibility to pass options (for now).
- It currently only supports exporting `integers` :sweat_smile: (I wanted to make this thing work end to end before extending it, and also get some guidance first)
- I tried to generate the parquet schema based on the output types exposed by the input. From what I understand it seems to be feasible (is it though?) but it relies on naming the parquet column according to their index , which isn't great. It would be interesting to get access to the actual schema of the output from the processor.
- I based this PoC on https://github.com/fraugster/parquet-go as I found it quite easy to use. If you have a preference on another library, please let me know.

I would be happy to continue working on this, but I'm going to need some guidance :sweat_smile:, at lease please let me know If I'm going in the right direction.

Feel free to reach out here or also on the community slack (I'm @jlevesy there too).

Cheers!

**Comment by msbutler** [comment]
@jlevesy thank you for posting this implementation! We've decided to work on this issue internally and use your implementation as a starting point. We'll reach out to you once this feature is ready!

**Comment by jlevesy** [comment]
Alright, my pleasure!

Will look for something else to do then, let me know if I can be of any help.

Cheers!
