### ISSUE TITLE
S3 compatible backup destinations need to support virtual hosted style

### ISSUE THREAD

**Issue by martinkubrak** [cockroachdb/cockroach#67850]
**Describe the problem**
Trying to backup to Alicloud OSS bucket with `s3://cockroachdb-backup/full?AWS_ACCESS_KEY_ID={key_id}&AWS_SECRET_ACCESS_KEY={key_secret}&AWS_REGION=eu-west-2&AWS_ENDPOINT=oss-eu-west-1-internal.aliyuncs.com` results in the following error `ERROR: failed to get s3 object: SecondLevelDomainForbidden: Please use virtual hosted style to access.`

This is because Alicloud OSS supports only virtual hosted style access.

**To Reproduce**
Try to backup into Alicloud OSS bucket.

**Expected behavior**
Backup should succeed.

**Environment:**
 - CockroachDB version: v21.1.5

**Additional context**
This is particularly troublesome when running CockroachDB in China since getting to services located outside is either impossible or severely limited.

Epic CRDB-8816

Jira issue: CRDB-8739

**Comment by dt** [comment]
Hi @martinkubrak, thanks for filing this. I believe this is because we intentionally set PathStyle URIs when using custom/overridden S3 endpoints here: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/cloud/amazon/s3_storage.go#L301. I don't remember all the details of why we do that but I think it was required at least with some s3-clones, that wanted to serve on a very specific address? Given that, I think we only support writing to custom s3-like services if they support s3's Path-Style access, and would be reluctant to remove that as it could break some existing users who are relying on it. That said, there could be room here to do the testing with various s3-likes to show what is required with each and if we could e.g. move that to be a more configurable option, but it isn't clear if or when that work would be prioritized.
