### ISSUE TITLE
jobs: add a pause reason

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#67928]
The ability to pause a job with a specific reason would be useful to increase visibility into why a job was paused.

The strawman syntax would be something like: `PAUSE JOB 123 WITH reason = 'foo'`

**Comment by pbardea** [comment]
This would be useful to have for https://github.com/cockroachdb/cockroach/issues/55856 so there is a pause-reason that can be set by the job.

**Comment by dt** [comment]
@ajwerner you okay with sticking a string field in `Payload` that can be set indicating why a job was paused? Technically I guess it could be revised more than once in a job's execution which we _usually_ don't put in payload, but it is bounded by how often the job is actually paused, not some o(n) aspect of execution, so that seems like it might be okay?

**Comment by ajwerner** [comment]
Seems okay but not amazing to me. Would a new column be so much worse? We've got the frameworks in place.

**Comment by dt** [comment]
I suppose a separate column is fine -- I donno, I see a stronger case for separate columns for anything that'll be accessed separately e.g. any column we might use to find/filter/etc a job. It seems like less of a win vs just packing it in the proto here, where it'd only ever by read when unpacking the payload to render the full SHOW JOBSs output anyway, so seems like less marginal benefit compared to the marginal hassle of doing the migrations vs just adding a line to a proto.

**Comment by rhu713** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/68909
