### ISSUE TITLE
bulk: restore database into a new named database

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#67927]
**Is your feature request related to a problem? Please describe.**
If I have an issue with a database, but want to keep it around as I'm restoring / keep application traffic going, I don't have a great way to do it today. I have to rename that database and point my application to a newly named database so that I can restore that old database, then change application back.

**Describe the solution you'd like**
`RESTORE DATABASE d1 FROM 'file' WITH new_db_name=d1_new`

**Describe alternatives you've considered**
`RESTORE DATABASE d1(into=d1_new), d2(into=d2_new) FROM 'file'`

We need to lock in syntax (cc @livlobo )

**Comment by adityamaru** [comment]
@livlobo @mwang1026 I want to kickstart a bikeshed of the syntax. @msbutler I think this would be an interesting introduction to restore, now that you have dabbled in backup!

How does `rename_db` sound as the option name?

**Comment by livlobo** [comment]
@adityamaru  @msbutler  - `rename_db` sounds like an action, which makes `RESTORE DATABASE d1 FROM 'file' WITH rename_db=my_new_db` sound a bit awkward. 

What do you think about `new_db_name` that @mwang1026 proposed. I prefer that because then it reads like English.

`RESTORE DATABASE d1 FROM 'file' WITH new_db_name=my_new_db`
