### ISSUE TITLE
streaming: update job progress in frontier processor

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#68058]
This tracks the work associated with a refactor in moving the logic that updates the job progress to the frontier processor rather than the job coorinator. This will enable future work to enable the job progress to store per-partition progress.

Jira issue: CRDB-8853

Epic CRDB-6403

**Comment by stevendanna** [comment]
I believe we have per-partition progress. The partition progress is currently only valid for a current stream plan since they are on a "per-partition" basis where the partition is identified by the source cluster node ID, thus it is meaningless for a new plan.  But, we do have it.

So, what is left to do?

**Comment by gh-casper** [comment]
This should be marked as done.
