### ISSUE TITLE
ui,jobs: improve jobs overview page in DBConsole

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#68179]
In https://github.com/cockroachdb/cockroach/issues/44594, Schema is adding a retry mechanism to the jobs infrastructure. During this work, we plan to add additional columns to `crdb_internal.jobs` to surface more job metrics.

These new metrics would be helpful in the DBConsole Jobs Overview page. 

- last execution time
- execution count
- updated status to indicate Retrying

FYI @ajwerner @sajjadrizvi 

Epic CRDB-7912

**Comment by kevin-v-ngo** [comment]
Hi @vy-ton, @maryliag and I were wondering when the additional job metrics will be available so that we can coordinate the UX changes. Do you have an ETA?

**Comment by ajwerner** [comment]
cc @sajjadrizvi

**Comment by sajjadrizvi** [comment]
> Hi @vy-ton, @maryliag and I were wondering when the additional job metrics will be available so that we can coordinate the UX changes. Do you have an ETA?

I am still working on adding the exponential backoff that is a pre-requisite for job metrics. I am expecting that it will take another day or two to complete. After that I can start working on adding the required metrics for observability. So I think the ETA is by the end of next week.

**Comment by sajjadrizvi** [comment]
I am thinking about the following.

We add three columns, `last execution time`, `next execution time`, and, `number of times executed`, that provide quick insights about the job and its current status.

In addition, we add a column that provides insights about each job's lifecycle. A user should be able to see that a job has transitioned from `state_x` to `state_y` at `time_t` due to error `err`. Moreover, what will happen next to the job? If it is going to be retried, when will it be?

To achieve that, we can add a repeated structure in jobs proto that keeps track of job history: 
```
ExecutionLog struct {
  state
  execution_time
  execution_error
}
```
Each time a job runs `stepThroughStateMachine`, it create this structure and adds it in job's payload after populating `state` and `execution_time` fields. When the job finishes its current execution (before leaving `stepThroughStateMachine`), it populates the `execution_error` field with the last error.

This structure can be used to populate a column `job status log` that shows the list of those structures in reverse chronological order, in the form "Job attempt at `execution_time` with status `state` finished with error `execution_error`. If there was no error, the error part can be skipped. If the job will be retried, we should add "The job will be retried at `time`. May be we want to add `next_state` as well if it doesn't add too much complication. 

A question is, how many log entries to show to a user? I think we should show only one log entry by default and provide an option to display N entries in reverse chronological order.

**Comment by ajwerner** [comment]
Can you be more concrete as to when these entries are actually written? I'm having a hard time understanding what happens before Resume/OnFailOrCancel and what happens after in terms of writes to the jobs table. 

Also, let's isolate somewhat the discussion about what values we write to system.jobs from the implied changes to crdb_internal.jobs. The latter is a function of the former, so they are related.

**Comment by sajjadrizvi** [comment]
Currently a resumer runs in states `running` and `reverting`. In `running` state, we add this structure with nil `execution_error` [before resuming](https://github.com/cockroachdb/cockroach/blob/852934c8c9c0cceb65ae5de1be27af9436c53b86/pkg/jobs/registry.go#L1180). `execution_error` field is then [populated here](https://github.com/cockroachdb/cockroach/blob/852934c8c9c0cceb65ae5de1be27af9436c53b86/pkg/jobs/registry.go#L1191) if there is an error.

In `reverting` state, we should add the structure with nil error [before reverting](https://github.com/cockroachdb/cockroach/blob/852934c8c9c0cceb65ae5de1be27af9436c53b86/pkg/jobs/registry.go#L1251). Error is then populated [after onFailOrCancel](https://github.com/cockroachdb/cockroach/blob/852934c8c9c0cceb65ae5de1be27af9436c53b86/pkg/jobs/registry.go#L1267). 

In the cases of `StatusSuceeded`, `StatusFailed`, and `StatusCanceled`, we do not run the resumer. So we don't have to add those log entries.

**Comment by ajwerner** [comment]
That sounds good. In addition, I think it'd be nice to have the coordinator ID. It'd be good to have an invariant that when we write `last_run` then we populate an entry in the log.

**Comment by sajjadrizvi** [comment]
> In addition, I think it'd be nice to have the coordinator ID
Great, that's a good suggestion.

> It'd be good to have an invariant that when we write `last_run` then we populate an entry in the log.
That's precisely what we want.

**Comment by sajjadrizvi** [comment]
> That's precisely what we want.

May be not! There is an exception. We update [`last_run` in `servePauseAndCancel`](https://github.com/cockroachdb/cockroach/blob/8b0b41fbc9b87f7f3c2c09d594b733c9c569e50e/pkg/jobs/adopt.go#L484) as well.  I think we should not add the entry at that time. So the invariant could be to populate an entry whenever we run a resumer.

**Comment by sajjadrizvi** [comment]
Another question is how to add the transition logs in the jobs table? On top of my head, I am thinking to add a column `transition_logs`. Each row then presents the logs as a string:
```
Log number: 1
Execution time: ts
Execution state: status
Execution error: nil or decoded error string
Log number: 2
....
```
An alternative is to have a separate table with jobID and four columns for

**Comment by ajwerner** [comment]
Firstly, when you say jobs table, please indicate which jobs table. 

I don't think separate rows is going to leave to a happy outcome. My guess is the right answer is to use json.

**Comment by sajjadrizvi** [comment]
OK, I meant, crdb_internal.jobs. Sorry for the confusion.

**Comment by sajjadrizvi** [comment]
Also, I wanted to say that a row has. a string that contains the list of the entries. JSON seems appropriate here.

**Comment by kevin-v-ngo** [comment]
Synced with Andrew and for this issue, we'll track adding the 3 metrics (LAST EXECUTION TIME, NEXT EXECUTION TIME, and EXECUTION COUNT to the jobs overview page.

For error details, we'll track it with the following issue: https://github.com/cockroachdb/cockroach/issues/69170.

CC'ing @Annebirzin @vy-ton as FYI

**Comment by Annebirzin** [comment]
I've started putting together some WIP designs for these updates to the jobs page in the DB Console. Feel free to leave comments here or in Figma. I've also left a few notes on the screens to capture questions/considerations.

https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/20.1_obsrv_db-console-jobs?node-id=1892%3A1709

**Comment by ajwerner** [comment]
My sense is that `Next Execution Time` is something that generally we don't want to be showing, it indicates that there's a problem. I have a feeling there's a rough edge we need to sand down on the data provided by the system. Internally (and thus not relevant for your mock) we should probably only expose a `NextExecutionTime` if we have good reason to believe that we've failed a previous execution. Thus, in most cases, it will be NULL and so when we do have it, maybe we want to give it some sort of warning color?

**Comment by Annebirzin** [comment]
@ajwerner Thanks for the feedback. 

I wonder if instead of dedicating an entire column for `Next Execution Time` in the UI, we could reflect the problem as a badge in the Status column (not sure what that status would be called). Maybe if you hover over the status badge you could see a tooltip that shows the `Next Execution Time` (this could also be shown on the job detail page when you click on a job) 

cc @vy-ton for any thoughts

**Comment by ajwerner** [comment]
I like that.

**Comment by vy-ton** [comment]
+1

@ajwerner Any objections to displaying a `Retrying` status even if that doesn't match a job status?

**Comment by ajwerner** [comment]
> @ajwerner Any objections to displaying a Retrying status even if that doesn't match a job status?

Nope, sounds good to me. I have a feeling like getting the data for the UI to be exactly what we want will require a touch of coordination with the schema team. This is very exciting!

**Comment by Annebirzin** [comment]
👍 I've updated the designs to reflect these updates: https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/20.1_obsrv_db-console-jobs?node-id=1892%3A1709

**Comment by ajwerner** [comment]
😞 I think we really missed the mark on this one. I suspect we want the logic to be `status IN ('running', 'reverting') AND next_run > now() AND num_runs > 0`. It's not perfect, but it's something and it can be implemented on the client side. I'll file a database issue to make this more reasonable.

**Comment by jocrl** [comment]
I'll also mention that the filtering for the status dropdown is done in the backend, not front. In my draft branch I added an if block to the request endpoint (https://github.com/jocrl/cockroach/commit/0f64559b05c27af973fe4ceb39e8e0794e41e371#diff-1402bca7aa2ae9e5b623ab3d1e93d918e0f8d652c689c42d644e46611151c9f6L1857). There's still the open question of whether a request for status=running should include or exclude those that are also retrying.

**Comment by ajwerner** [comment]
:) Nice, I'm new to working in this sort of collaboration too. I'm happy with adding the data being in scope. It does mean that this won't make the 21.2 release and instead will be in 22.1, which is totally fine. I don't think we can change these protos in patch versions. 

My vote is that we make retrying decorate `reverting` and `running` somehow and indeed that they show up.
