### ISSUE TITLE
Allow "any" target for ON CONFLICT DO UPDATE

### ISSUE THREAD

**Issue by gnat** [cockroachdb/cockroach#68410]
**Is your feature request related to a problem? Please describe.**
* Frustrating that a target must **always** be specified for `ON CONFLICT DO UPDATE`
* MySQL offers the ability to do a generalized `ON CONFLICT DO UPDATE` via the `INSERT ON DUPLICATE` syntax. https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Describe the solution you'd like**
Allow `ON CONFLICT DO UPDATE` without specifying a target. Any of these would be fine:
* `ON CONFLICT DO UPDATE`
* `ON CONFLICT * DO UPDATE`
* `ON CONFLICT (*) UPDATE`
* `ON CONFLICT ANY DO UPDATE`

**Describe alternatives you've considered**
At this point I'm probably going to end up catching the exception for "duplicate index" whenever I run INSERT, and run an UPDATE manually. Bleh. Suggestions welcome.

**Additional context**
This part of Postgres feels stuck in 2010. Would be very nice if Cockroach offered some sort of solution.

Thank you!

Jira issue: CRDB-9027

**Comment by gnat** [comment]
Possibly related? https://github.com/cockroachdb/cockroach/issues/67893

**Comment by rafiss** [comment]
Moving this to the SQL Queries board. cc @rytaft for further triage

**Comment by mgartner** [comment]
I'm going to close this, because, as mentioned above, it's not obvious how a multi-arbiter `DO UPDATE`s should behave. 

Interestingly, there is one form of multi-arbiter `DO UPDATE` that Postgres does support: when the arbiters are partial unique indexes (see #53170). But in this case there is no ambiguity as to which row gets updated if there is a conflict because the insert can only ever conflict with a single row. If it conflicted with two existing rows, those two rows would conflict with each other, so they could not have been inserted in the first place.
