### ISSUE TITLE
kv: DistSender batch slicing is quadratic with batch size

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#68536]
CPU profiles like the following demonstrate high CPU utilization in `DistSender`. The profile is exemplary of the cost of a `BatchRequest` with a high fanout factor.

<img width="1638" alt="Screen Shot 2021-08-06 at 10 30 01 AM" src="https://user-images.githubusercontent.com/5438456/128525888-5dacb7ca-cfc9-4f4f-91e8-dc5b286f1954.png">

If we look closely, we can see that two of the most pronounced functions are `kvcoord.next` and `kvcoord.truncate`. The first of these is called [here](https://github.com/cockroachdb/cockroach/blob/8e1c310317b362ebcb712f7c3d66bb30b2ed1271/pkg/kv/kvclient/kvcoord/dist_sender.go#L1289) and the second [here](https://github.com/cockroachdb/cockroach/blob/8e1c310317b362ebcb712f7c3d66bb30b2ed1271/pkg/kv/kvclient/kvcoord/dist_sender.go#L1468). We can also assume that if this was a reverse scan, `kvcoord.prev`, called [here](https://github.com/cockroachdb/cockroach/blob/8e1c310317b362ebcb712f7c3d66bb30b2ed1271/pkg/kv/kvclient/kvcoord/dist_sender.go#L1279) would replace `kvcoord.next` as a pronounced use of CPU.

The problem is that all three functions defined in [`pkg/kv/kvclient/kvcoord/batch.go`](https://github.com/cockroachdb/cockroach/blob/8e1c310317b362ebcb712f7c3d66bb30b2ed1271/pkg/kv/kvclient/kvcoord/batch.go) are linear with respect to batch size, and they are called in [a loop](https://github.com/cockroachdb/cockroach/blob/8e1c310317b362ebcb712f7c3d66bb30b2ed1271/pkg/kv/kvclient/kvcoord/dist_sender.go#L1266) that iterates over ranges touched by a batch. This means that with a large batch and a high fanout factor (i.e. each request in the batch touches a different range), the cost of these functions is quadratic with respect to the number of requests in the batch. This is fine for small batches, but not great for large batches, like the ones issued by a lookup join.

We should explore what we can do here to make this efficient. Solutions may include micro-optimizing the internals of these functions (with microbenchmarks) or restructuring their use to avoid the quadratic cost.

Jira issue: CRDB-9072

**Comment by yuzefovich** [comment]
Possibly related issue #70706.

**Comment by yuzefovich** [comment]
I have thought about this problem for some time, and I think the best solution is to sort the requests upfront (because it allows us to only compare the range boundaries against a contiguous subset of all requests), and then keep track of the fully-processed requests (in order to skip key comparisons altogether) as well as the yet-to-be-processed suffixes of other requests such that the ordering of requests is maintained across the truncation. This solution is implemented in #82865.

In terms of time complexity, the existing qudratic approach is `O(N * R)` where `N` is the number of original requests and `R` is the number of ranges those requests touch. The proposed solution is actually worse in the absolute worse case - `O(N * (log N + R))` because of the need to sort the requests up front. However, in practice, it should be much faster and behave like `O(N * log N + T * R)` where `T` is the average number of requests that intersect with a single range.
