### ISSUE TITLE
logging: UMASK cannot be set for log files

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#68736]
**Describe the problem**

the logs files have permission `-rw-r-----` and it seems it's not configurable and not respecting the user's umask:

```
$ id
uid=1002(cockroach) gid=1003(cockroach) groups=1003(cockroach)
$ umask
0002
```

but nonetheless, the files are set to 640

```
-rw-r----- 1 cockroach cockroach   25926 Aug 11 20:50 cockroach..cockroach.2021-08-11T20_49_28Z.021349.log
-rw-r----- 1 cockroach cockroach   35991 Aug 11 20:54 cockroach..cockroach.2021-08-11T20_50_00Z.021367.log
-rw-r----- 1 cockroach cockroach   28931 Aug 11 20:56 cockroach..cockroach.2021-08-11T20_54_16Z.021413.log
```

I'm using systemd. I tried setting `UMask=0022` as well as `Environment='UMASK=0022'` but no luck

Jira issue: CRDB-9216

**Comment by thtruo** [comment]
Thanks Fabio. cc @knz I'm marking this under the DB Server backlog for now. If you think it makes more sense for Observability Infra to take it, let me know!
cc @nkodali for awareness

**Comment by knz** [comment]
Fabio, the first question I'd like to ask is whether the change in PR #68182 would help.

If not, we need to talk about alternatives.
For context,

CockroachDB overrides umask process-wide upon startup in order to protect accessibility of store files, SQL temp files etc. 

We have a lot of sub-components in cockroachdb that write files and they do not have a disciplined permission approach (nor does the Go runtime help us apply policy to all components equally, without relying on individual engineers' good will and skill). We found the umask was the more sure-way to apply policy to all files created by a crdb process regardless of who implements it.

I'm not sure how to make this better for logging without changing the process-wide umask, which in turn would lower the security of all the other components (as per the previous paragraph).

I can see two ways forwards:

- implement a sidecar next to the crdb process whose responsibility is to run `chmod` (change file permissions) on the log files as they get generated.

- rework the architecture of CockroachDB so that all file creations go through an API we control that can apply permission policy consistently. This will require intervention in a dozen of packages from various teams, plus the creation of a linter to prevent use of the basic Go file APIs.

Maybe @bdarnell or @catj-cockroach would have more insights?

**Comment by bdarnell** [comment]
A third option is to just use the umask and rely on the users setting it correctly (i.e. undoing #44043). If we're going to override the umask we must provide a non-umask way of configuring permissions instead, but just using umask is the standard way to do this. Note that with more use of the k8s operator and fewer ad-hoc deployments it becomes more feasible to manage the umask in a central place while still external to the process. 

I don't think a sidecar process is a good idea, so if we don't just go back to relying on the external umask we should update all the places where we create files. (I'm not sure that we need a major refactoring and centralization here, but it wouldn't hurt).

**Comment by catj-cockroach** [comment]
A sidecar would add significant complexity and I suspect the amount of work to maintain it would be greater than the benefit we get from it. Changing the mode at file creation time makes much more sense I'd argue.

Combining what both of you (@bdarnell and @knz) said, what if we wrap the `os.Create` and `ioutil.WriteFile` functions for files that need to be locked down?

We could do something to the effect of:

```golang
const SecureFileMode = 0600

// do something else on windows
func SecureFileCreate(filename string) (*os.File, error) {
     file, err := os.Create(filename, SecureFileMode)
     if err != nil {
         return nil, err
     }
     err = file.Chmod(SecureFileMode)
     if err != nil {
          panic("cannot override umask")
     }
     return file, nil
}

func SecureFileWrite(filename, data string) error {
    // wrap ioutil.WriteFile but in a way that we fail if we can't chmod
}
```

And then use the linter to block the use of `os.Create` and `ioutil.WriteFile` outside of the packages that create data that should be secured.

**Comment by knz** [comment]
@catj-cockroach is gracefully offering to prototype a solution to this.

**Comment by bdarnell** [comment]
> what if we wrap the os.Create and ioutil.WriteFile functions for files that need to be locked down?

(and os.OpenFile, which is the most common one we used based on #44043)

The problem is that we need configurability: Some users have log-management tooling that rely on logs being world-readable, but most users don't want this. So the problem is not that we create files insecurely, it's that we hard-coded the rule "no world-readable files". 

So we could just use the umask and allow people who want world-readable files to get them, but this may leave some users at greater risk if they don't think about their umasks. The alternative is to introduce new `permission` parameters in the log configuration (and for non-log files maybe we can stick to the 0660 permissions we use today).

**Comment by knz** [comment]
> The alternative is to introduce new permission parameters in the log configuration (and for non-log files maybe we can stick to the 0660 permissions we use today).

yes that would be a good idea I agree.

@catj-cockroach if you want we can offload the log configurability part specifically from your team.
cc @rauchenstein

**Comment by knz** [comment]
filed the logging config issue separately  #68799

**Comment by catj-cockroach** [comment]
I've started a draft PR, if anyone has any feedback please let me know! :)

https://github.com/cockroachdb/cockroach/pull/68999
