### ISSUE TITLE
COPY CSV doesn't support bytea column

### ISSUE THREAD

**Issue by steven-sheehy** [cockroachdb/cockroach#68804]
**Describe the problem**
COPY CSV does not support binary data. Since CSV is a text-based format, you have to encode `bytea` columns to hex or octal when generating the CSV. CockroachDB doesn't decode these encoded fields embedded in the CSV and instead inserts them as string into the bytea column.

**To Reproduce**

1. `cockroach demo`
2. `psql "postgres://demo:<password>@127.0.0.1:26257/movr?sslmode=require"`
2. `alter table users add column data bytea;`
3. `COPY users(id,city,data) FROM STDIN CSV;`
4. `8a3d70a3-d70a-4000-8000-00000000001d,seattle,"\x00"`
5. `\.`
6. `select * from users where id = '8a3d70a3-d70a-4000-8000-00000000001d';`
```sql
                  id                  |  city   | name | address | credit_card |    data
--------------------------------------+---------+------+---------+-------------+------------
 8a3d70a3-d70a-4000-8000-00000000001d | seattle |      |         |             | \x5c783030
```
7. `insert into users (id, city, data) values (gen_random_uuid(), 'new york', decode('00', 'hex'));`
8. `select * from users where data = '\x00';`
```sql
                  id                  |     city      |        name         |            address             | credit_card |     data
--------------------------------------+---------------+---------------------+--------------------------------+-------------+--------------
d4272cf3-589d-481b-97bb-ef8712b5d227  | new york      |                     |                                |             | \x00
```

The `data` column should be `\x00` and not `\x5c783030`. `5c783030` is the characters `\x00` encoded to hex, so it's doubly encoded. Regular insert works fine and can insert `\x00`. If you repeat the above steps using COPY in PostgreSQL, you also get `\x00`.

**Expected behavior**
Binary data to be inserted as is without being doubly encoded. In the above example the `data` should be `\x00` and not `\x5c783030`.

It should also probably support octal encoded `\00` format as well to have [parity](https://www.postgresql.org/docs/13/sql-copy.html) with PostgreSQL.

**Additional data / screenshots**

**Environment:**
* CockroachDB version v21.1.6
* Server OS: MacOS
* Client app: JDBC

**Additional context**
What was the impact?

Unable to move forward with the PoC.

cc @rafiss 

Epic CRDB-7217

**Comment by rafiss** [comment]
I looked into this more and found that the problem here is actually https://github.com/cockroachdb/cockroach/issues/26128

In Postgres, you can represent a bytea literal with `'\xAAAA'` (or any hex digits). As that issue describes, CockroachDB doesn't support that syntax.

If you try using octal-encoding in COPY CSV with Postgres, it actually does insert the doubly-encoded bytes. I'll add a test in https://github.com/cockroachdb/cockroach/pull/69066 that demonstrates that

**Comment by rafiss** [comment]
Update: Whoops I had my testing wrong. Using octal-encoded input with a `bytea` column in COPY CSV in Postgres *does* work as you are requesting in this issue. However, it's not because of the CSV escaping rules; rather, it's because of how `bytea` literals are interpreted. See this example, which works in both CockroachDB and Postgres:

```
> create table t(a int primary key, b bytea);
> insert into t values (4,'ab\011\143d');
> select encode(b, 'hex') from t where a = 4;
    encode
--------------
  6162096364
```

So to unblock you here, the workaround is to use octal escapes. The full fix is for us to resolve https://github.com/cockroachdb/cockroach/issues/26128 but unfortunately I don't think we will be able to work on that immediately.

**Comment by rafiss** [comment]
See more details here: https://www.postgresql.org/docs/current/datatype-binary.html#id-1.5.7.12.10

If you need to get this octal-escaped bytea output from postgres, you can set the session variable `bytea=escape`

**Comment by steven-sheehy** [comment]
@rafiss Thanks for investigating. I can switch our CSV encoder to CRDB's specific hex syntax. I can try octal as well though that's way less efficient in terms of overall byte count. If it's just a syntactical difference of representing encoded byte literals, shouldn't one of the below work to store the bytes that represent ASCII 'hi' into the column?

```sql
> create table t(a int primary key, b bytea);
> set bytea_output = 'escape';
> COPY t FROM STDIN WITH CSV;
> 1,X'6869'
> 2,x'6869'
> 3,"\x6869"
> 4,'\x6869'
> 5,\x6869
> 6,\150\151
> 7,"\150\151"
> \.
> select * from t where b = decode(encode('hi', 'hex'), 'hex');
 a | b
---+---
(0 rows)
> select * from t;
 a |     b
---+------------
 1 | X'6869'
 2 | x'6869'
 3 | \\x6869
 4 | '\\x6869'
 5 | \\x6869
 6 | \\150\\151
 7 | \\150\\151
(7 rows)
```

**Comment by rafiss** [comment]
@steven-sheehy The `6,\150\151` or `7,"\150\151"` inputs will work only after https://github.com/cockroachdb/cockroach/pull/69066 is merged. (The commit "fix byte escaping in COPY CSV input" fixes a bug.)

The `1,X'6869'` or `2,x'6869'` inputs unfortunately won't be able to work in COPY at all. the `x'...'` hex syntax is dealt with in the SQL parser, and the COPY protocol doesn't use the SQL parser.

The `> 3,"\x6869"`, `4,'\x6869'`, and `5,\x6869` inputs won't work because of https://github.com/cockroachdb/cockroach/issues/26128.

So unfortunately, there actually isn't a workaround for bytea columns with CSV input at this moment. We'll be backporting the fix to v21.1 as soon as we can.

**Comment by steven-sheehy** [comment]
Thanks! I can wait for the next release, but would like to just understand one thing. If COPY CSV in CRDB doesn't support CRDB's or PostgreSQL's  hex syntax, why can't `copy.go` specifically be updated to support one of those? It seems like #26128 is specific to the SQL parser side of things and is tricky to fix because you guys don't want to break clients depending upon the CRDB format. But in COPY CSV there is no such support for either format so it wouldn't break anyone to add one (preferably "\xaa" format).

**Comment by rafiss** [comment]
To clarify: The `x'...'` syntax is processed in the SQL parser. But if we were to add support for the `'\x...'` syntax, that would be handled internally in the database (in the logic for casting strings to bytes). 

I'm a bit hesitant to special case either of those into the COPY code, just because that feels like creating tech debt.
* Specifically, supporting `x'...'` in COPY is messy because it would be a very special situation where we treat single-quotes as part of the syntax rather than as meaningful data (normally a single quote anywhere in the CSV input just results in a single quote in the data).
* Alternatively, since the `'\x...'` logic would normally be internal casting logic, it is breaking an abstraction if we do it in a pre-processing COPY step. It would make it harder for users who are currently working around the lack of `\x...` syntax and actually would make it harder to input the actual bytes `\` `x` `A` `B` ...
* Also I worry about it breaking again if we do change the hex/bytea story in CockroachDB.

However, your point that there is no way at all to do hex input with COPY CSV is definitely true and a strong reason to consider special-casing it. I'll discuss with the team. cc @otan in case you want to weigh in here directly.

**Comment by steven-sheehy** [comment]
@rafiss I see this was closed. What was the consensus reached on bytea hex encoding by the team? It seems like special casing `'\x...'` in copy would be fine since you can always move its implementation from copy to sql parser later when support for it in sql parser is added without impacting clients. A test that validates CSV input and SQL output could verify any change in either layer doesn't break things.
