### ISSUE TITLE
ui: move dashed-underline styling from SortedTable headers to Tooltip

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#68821]
Because not every header has a Tooltip.

Quick-fix follow on to #68390 

Jira issue: CRDB-9285

**Comment by jocrl** [comment]
There are potentially [multiple Tooltip components](https://cockroachlabs.atlassian.net/browse/CC-5339) being used in table headers, and I think all of them would benefit from moving the dashed line styling in. Alternatively, changing all of them would be easier if/when the multiple Tooltip components are unified.

Also, not all Tooltips are table headers, so one would need to de-duplicate the dashed line implementation for those non-table-header Tooltip usages.

And also, @lindseyjin made a [temporary UI fix](https://github.com/cockroachdb/cockroach/pull/73455) that can be pulled out when this issue is done.

**Comment by xinhaoz** [comment]
@matthewtodd do you know if this is still relevant / have more info on this? I tried to find the styling in sortedtable for the dashed underline styling and it doesn't seem to be there. Or was the problem something else?

**Comment by matthewtodd** [comment]
@xinhaoz oh, good! If it's not there anymore, perhaps this has already been done? We can do a quick test by putting plain text (not a tooltip) in a table header to see how it looks.
