### ISSUE TITLE
backup: memory spikes on backups with many incremental layers

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#69011]
On backups with many incremental layers, we see significant memory spikes during backup planning on the coordinator of the backup job.

Grabbing a heap profile reveals that `makeImportSpans` is responsible for a lot of the allocations (in the profile below ~750 MB, or ~60% of the profile).

<img width="1279" alt="Screen Shot 2021-08-16 at 15 06 11" src="https://user-images.githubusercontent.com/507390/129623524-15b257d6-de3b-4391-947d-94aa89eedcba.png">

During `makeImportSpans`, the `Spans` and `Files` of each backup are re-allocated into coverings and re-allocated again during `OverlapCoveringMerge`.

gz#9594

gz#9617

gz#9813

Epic CRDB-10260

gz#9729

gz#10626

gz#10949

**Comment by shermanCRL** [comment]
Further spitballing, Paul calls out re-allocating `Spans` and `Files` into other structs. Can these be avoided, i.e, re-used?

Possible downside: that’s likely changing the semantics from copy to reference. Any mutability or concurrency concerns?

**Comment by shermanCRL** [comment]
Proper fixes tracked in https://github.com/cockroachdb/cockroach/issues/67128

**Comment by miretskiy** [comment]
Meeting summary between @Aditya Maru and myself: We were looking into memory usage during restore.  We have analyzed some of the larger build manifests we are dealing with.  The below analysis should give everybody a sense of the scale and the severity of the problem. One of the manifests (I assume the base backup) contained  1.8 million files entries (1802895).  Now, each of the incrementals contained roughly 20% of the files (370K).  But, if we have a super long chain of incrementals (150 hourly), we are looking 370K*150+1.8M files; or roughly 57M file entries.  Each file name is 27 bytes long (data/timestamp), so, just an array of strings for the above would use up 1.6GB of ram.  Of course, we’re not storing just string; and as a matter of fact, we’re making multiple copies of that when we construct overlap covering.  In general, constructing a multi-million entry array would likely result in bad time.  I believe that the overlap covering algorithm we are using is extremely inefficient for this particular use case.  I believe it can be made more efficient.  In particular, when we verify spans during backup, we actually do not need any of the file names — so, just clearing out file names would save us 1.6GB (times at least 2 because of copies).  Which is not too shabby.  I further believe that a simpler algorithm can be made more efficient (memory wise); plus we could consider using some of the tricks suggested by @david (e.g. prefix compression of file names… but maybe we could just make things simpler by stripping out “data/” prefix.).  I think it should be possible to make an additive, feature flag gated change that makes backup use less memory.  Restores — probably too.  Ultimately, however, I think anything that relies on loading the entire backup chain in memory is likely not to work correctly, and that changing this would be hard (even using external SSTs to store files might not help us, if we then go ahead and load all of them in memory).  Finally, I want to point out that we are about to release 21.2.  This release will be used by many customers, for quite some time; we are also running at much, much larger scales.  
This might force our hand wrt to back-porting changes that we otherwise would prefer not to backport.

**Comment by adityamaru** [comment]
This is a tracking comment on the work being done to mitigate these memory spikes. In addition to merging all these changes on master we are looking to backport them as follows:

Backport now:

- [ ] https://github.com/cockroachdb/cockroach/pull/73957
- [ ] https://github.com/cockroachdb/cockroach/pull/74150 (behind a cluster setting to enable memory monitoring)
- [ ] https://github.com/cockroachdb/cockroach/pull/74368 (behind a cluster setting to enable memory monitoring)

Backport soon but after some baking time on master since they are more invasive changes:
- [ ] https://github.com/cockroachdb/cockroach/pull/74393
- [ ] https://github.com/cockroachdb/cockroach/pull/74394

Once all these PRs are backported to 21.2, we should see a reduced memory footprint, more guardrails against OOMs because of the memory monitoring, and the ability to bump the file merging queue size that should lead to fewer small SSTs being created during an incremental backup.

Some of the changes that we are not currently considering for backport are:

- [ ] https://github.com/cockroachdb/cockroach/pull/74094
- [ ] https://github.com/cockroachdb/cockroach/pull/73393 (on its own this doesn't help, the next step is to move the planning code to the job execution phase)
