### ISSUE TITLE
opt: infer stats from computed column expression

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#69120]
Hash indexes use a computed column expression such as `crdb_internal_key_col_shard_12 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(key_col AS STRING), '':::STRING)), 12:::INT8)) STORED`. In the optimizer, we can use this expression to create an optional filter that constrains crdb_internal_key_col_shard_12 to `[/0 - /11]`. Although this constraint may look selective, it actually represents a full table scan. Currently, the statistics code only realizes this if there are stats available on crdb_internal_key_col_shard_12. However, it should be able to use the `mod ... 12` expression to determine that `[/0 - /11]` is a full table scan, even when there are no stats available. This will prevent the optimizer from choosing bad plans with the hash index before stats are available.

Epic CRDB-10034

gz#9497

Jira issue: CRDB-9448

Jira issue: CRDB-13892

**Comment by RaduBerinde** [comment]
There was some discussion about the optimizer also inferring the check constraint itself from the computed column expression. Both features would rely on logic to generate the constraint `[0, x)` from the expression `mod(fnv32(<not-null-expression>), x)`. (Note that this does not hold generally for `mod` because the output can be negative).

**Comment by ajwerner** [comment]
An alternative to deriving the stats from the expression would be to derive the stats from the check constraint itself. I have no clue if that's better.

**Comment by rytaft** [comment]
This was addressed by #76893.
