### ISSUE TITLE
sql: ensure that sql.plan API is better error check proof

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6921]
plan.Next() returns a boolean and yet it can encounter an error. The API requires the code to check plan.Err().

The first change here is going to change Next() bool -> Next() (bool, error)

**Comment by dt** [comment]
by the same argument, is is worth considering jumping to `(bool, DTuple, error)` and killing `Values()` too?
It's a similar user-needs-to-check-this-then-that situation, and since `Next` has to do the work (in order to potentially set or return said error) of call anyway, I'm not sure splitting really lets us save work when we don't need values?

**Comment by RaduBerinde** [comment]
Note that there is some interaction with EXPLAIN DEBUG there - in that mode, we don't call `Values()`, we can only call `DebugValues()`, and only if those indicate a full row we can call `Values()`.

**Comment by vivekmenezes** [comment]
I've already made the change to Next() (bool, error). I'll push that forward. I think it's looking okay because there are a number of places where Values() is not being called. We can decide later if we want further consolidation, but at least that fix will prevent misuse.
