### ISSUE TITLE
kvserver: consider cheaper hash function for stats

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#69297]
Currently we use SHA512 for range stats but this can sometimes be expensive enough to show up in profiles, using 4-6% of CPU in some recent observations. A cheaper and/or better hardware accelerated hash function might be beneficial here, perhaps sha256 or blake3, or even something like sha1 given the non-cryptographic usage.

Jira issue: CRDB-9532

**Comment by bdarnell** [comment]
Be sure to benchmark this before changing things. My understanding is that SHA-512 is actually faster than SHA-256 for large inputs on 64-bit processors (this is why SHA-512/256 exists: compute SHA512 and truncate it to 256 bits instead of computing SHA-256). Wikipedia has a nice table: https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions and blake3 has some benchmarks as well (https://github.com/BLAKE3-team/BLAKE3), both of which confirm this. 

SHA-1 is only about 30% faster, which hardly seems worth the downgrade in security (whether or not the security actually matters, we don't want to have to continually justify the use of an outdated hash function). Blake3 is a bigger improvement in performance (based on their benchmarks) which could be worthwhile (I haven't done any research on the suitability of blake3 for our purposes). 

If we're going to go through a migration for this we should lay the groundwork for making it configurable (thinking of government customers who might insist on a FIPS-certified algorithm).
