### ISSUE TITLE
sql: build datadriven framework for testing version gating

### ISSUE THREAD

**Issue by pawalt** [cockroachdb/cockroach#69361]
In `cockroach_versions.go`, we define desired minimum versions to use different features. To test this version gating, you're required to write your own tests where you spin up a testcluster with a specific version, fire commands against it, and check if you got a version error.

These testing steps are consistent across different version gates, so we should write a datadriven test framework to test these changes. Some potential commands:

- `new-cluster`
- `should-error-with-version`
- `should-succeed`
- `upgrade-cluster`

This functionality can be achieved through existing logictests, but changing version settings still requires changing the logictest configuration:
https://github.com/cockroachdb/cockroach/pull/69351

**Comment by rafiss** [comment]
@arulajmani to comment and close

**Comment by arulajmani** [comment]
I was misremembering the ask here when we brought this up in yesterdays meeting. I thought this could be served by the local mixed version configuration we have for our logic tests, but those don't allow an upgrade option. I think what this issue is asking for can be valuable, albeit not super urgent. 

We do have tests that do something similar, such as https://github.com/arulajmani/cockroach/blob/8caad892eef49e2f4687d56e279c8db66982a9b7/pkg/migration/migrations/on_update_test.go#L39, but these can be verbose to write. It would be nice to have a more lightweight solution. I'll move this to the backlog for now.

**Comment by RichardJCai** [comment]
Closing this in favour of https://github.com/cockroachdb/cockroach/issues/72451 which I think is going to be a superset of this.
