### ISSUE TITLE
sql: allow testing of global latencies with start-single-node

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#69586]
A customer shared with us that they really enjoy using CockroachDB demo global to simulate global latencies for testing. They'd like to be able to use it with test containers (a java testing library) and start-single-node to augment their testing capabilities. This would let them try out a lot of the new functionality without spending the cost to set up multiple regions. 

Jira issue: CRDB-9677

**Comment by jordanlewis** [comment]
Why can't they use `demo` for this purpose? It should support test containers just as well as `start-single-node`.

I think it's reasonably unlikely that we'll invest in building the global latency simulator again in a different way for `start-single-node`. It can't really be used as-is with `start-single-node` because it uses the `TestCluster`, which is a way of running multiple in-memory nodes in a single process.
