### ISSUE TITLE
kvserver/rangefeed: only scan separated intents span to bootstrap resolved timestamp

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#69697]
**Is your feature request related to a problem? Please describe.**
Today we initialize the resolved timestamp by iterating all of the intents in the range. We do this by iterating the entire range and only looking at the intents. We set up the iterator here: https://github.com/cockroachdb/cockroach/blob/c4de73f72136e774ec887f3cbc0dda6c37d60dab/pkg/kv/kvserver/replica_rangefeed.go#L387  and we skip over the values here: https://github.com/cockroachdb/cockroach/blob/c4de73f72136e774ec887f3cbc0dda6c37d60dab/pkg/kv/kvserver/rangefeed/task.go#L84

If we were to restrict this scan to only the separated intents on ranges which have been fully migrated to only use separated intents, we could avoid a full data scan during rangefeed startup. This is a big win!

**Describe the solution you'd like**

We should set up the RTS iterator to only look at the separated intents when appropriate.

**Additional context**

There's been talk in the past of storing the resolved timestamp start. I don't think we need to do this with the separated intents.

**Comment by nvanbenschoten** [comment]
> There's been talk in the past of storing the resolved timestamp start. I don't think we need to do this with the separated intents.

Agreed. The [TODO](https://github.com/cockroachdb/cockroach/blob/c4de73f72136e774ec887f3cbc0dda6c37d60dab/pkg/kv/kvserver/replica_rangefeed.go#L389) mentioning this was conceived before the idea of separated intents came around. And the idea was never to use this resolved timestamp to avoid the scan entirely, only to make it more efficient by using a time-bound iterator. But separated intents make this even more efficient, as we can avoid scanning all MVCC data without the need for a time-bound iterator due to the physical partitioning of intents and data.

This will be a significant win.
