### ISSUE TITLE
Prevent users from picking out of range dates for persisted statistics in the console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#69778]
In the V1 of persisted statistics in the DB console, developers can select start and end times where data for persisted statistics does not exist. 

As part of [V2](https://github.com/cockroachdb/cockroach/issues/69718), should provide an experience where the developers cannot select out of range dates and understand why the dates cannot be selected. 

Figma [link](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=2874%3A121906) 

Jira issue: CRDB-9791

**Comment by kevin-v-ngo** [comment]
CC'ing @xinhaoz and @Azhng as FYI

**Comment by Azhng** [comment]
I think how we can implement this is to introduce another field in `StatementResponse` proto and have the RPC endpoint query what's the oldest `aggregated_ts` in the returning result. 

This can be done via a quick 

```sql
SELECT aggregated_ts FROM system.statement_statistics ORDER BY aggregated_ts LIMIT 1
```

The caveat here is that this might produce [a really expensive plan](https://github.com/cockroachdb/cockroach/pull/68434#pullrequestreview-736421336) because of hash sharded index. So we might want to do this per hash shard and find the min across all shards.

**Comment by jocrl** [comment]
I'll figure out how to implement this, but just noting here that querying `system.statement_statistics` will not get the earliest time if no stats have been flushed (i.e. the earliest record we want is in the in-memory table)
