### ISSUE TITLE
kvserver: make sure heartbeats don't take too long

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#69893]
Node heartbeats use a semaphore to prevent multiple requests being sent concurrently:

https://github.com/cockroachdb/cockroach/blob/793b4c8bfc6e9dbf7a05289f3e61035796476cc5/pkg/kv/kvserver/liveness/liveness.go#L862-L872

It is normally called from the main heartbeat loop with a 4.5 second timeout. However, during lease requests it is called explicitly without a context timeout (although it is possibly cancelled early for other reasons):

https://github.com/cockroachdb/cockroach/blob/2e00964f6ba48f190929665c39933148cfaf8592/pkg/kv/kvserver/replica_range_lease.go#L364

We should make sure this heartbeat doesn't take too long. In particular, if the remote IP address does not respond (e.g. because the machine is shut down), then the TCP exponential backoff for the SYN retransmits can eventually cause the retry interval to become very long and exceed the normal 4.5s timeout. This can cause recovery when the node does come back online to take longer than the 4.5s it normally would, because the semaphore will block the normal heartbeat loop from contacting the node in the meanwhile.

We may want to consider setting an hard upper limit for all heartbeat requests equal to the timeouts used by the heartbeat loop. We should make sure this doesn't have any adverse effects on lease acquisition, especially during network or node problems that cause increased latencies.

Related to #53410.

**Comment by nvanbenschoten** [comment]
> then the TCP exponential backoff for the SYN retransmits can eventually cause the retry interval to become very long and exceed the normal 4.5s timeout

Do you know how high the retry interval reached when you saw this?

**Comment by erikgrinaker** [comment]
I've seen in excess of 40 second heartbeat durations before a failure, presumably they could be even larger. I'll have to look at the Linux TCP stack to calculate what the underlying SYN retransmit interval would be at that point, will get back to you on that.

**Comment by nvanbenschoten** [comment]
Thanks. I ask because doing what's proposed here seems a little bit like patching over the root issue, and in a way that will probably never be comprehensive. The essence of this proposal is that TCP retry loops can backoff too far, to the point where we want to retry at a higher frequency somewhere above it in the software stack. That would be reasonable if we only had a single operation necessary to re-establish the health of the cluster. But in practice, there are a series of steps necessary to re-establish cluster health, like sending KV traffic and acquiring leases on various system ranges. Do each of these operations need their own retry loops to guard against excessive TCP backoff? Also, how do timeouts and retries interact with TCP backoff when requests are multiplexed onto the same TCP stream by gRPC?

I wonder whether we should be recommending that deployments of CRDB alter the TCP retransmission configurations on their hosts. https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html indicates that this is tunable on Linux via `/proc/sys/net/ipv4/tcp_retries2` or the sysctl `net.ipv4.tcp_retries2`. The actual maximum retransmission timeout `TCP_RTO_MAX` is fixed at 120 seconds, but the maximum number of retries `tcp_retries` can be tuned.

It defaults to 15, which:
> means that it takes 924.6 seconds before a broken network link is notified to the upper layer

A retry count of 5 would mean that it takes only 6.2 seconds before a broken network link is notified to the upper layer and places an upper bound of 3.2 seconds on any single retransmission timeout.

There's also the `tcp_syn_retries` kernel setting, which I believe is more closely related to what you saw here. I found https://www.hostedgraphite.com/blog/deadlines-lies-and-videotape-the-tale-of-a-grpc-bug to be an interesting read.

**Comment by erikgrinaker** [comment]
You make a good point. Having thought about the circumstances in which this heartbeat would actually block for a long time, I don't think it matters much for recovery whether we reduce the timeout or not. The network would have to go down just as we were doing a lease transfer, but it's overwhelmingly likely to be some other packet that's first in line when that happens, and because of TCP head-of-line blocking and how gRPC stream multiplexing works with TCP, loss of any packet would cause all traffic to halt while it is retried, delaying the recovery heartbeats in the same manner. We may want to consider QUIC for this very reason, but that's a whole other discussion. Going to close this as unnecessary.

We should definitely look into TCP sysctl recommendations instead of trying to patch over long retransmit times in general, added https://github.com/cockroachdb/docs/issues/11716 for this.
