### ISSUE TITLE
Persisted statistics are supported for CockroachDB serverless

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#69930]
We should make sure persisted statistics are supported for CockroachDB serverless both in the console and SQL CLI (CRDB_INTERNAL table). 

This issue currently tracks identifying the gaps we have in persisted stats.

**Comment by xinhaoz** [comment]
We should just be missing resetting SQL stats for tenants.

The combined stats API queries from the virtual statement + transaction tables which should be fine for serverless since it'll utilize pod-to-pod fanout for in-memory stats and just reads from system tables for persisted stats.

Outstanding tasks:

- [ ] https://github.com/cockroachdb/cockroach/issues/68177
- [ ] https://github.com/cockroachdb/cockroach/issues/70214

**Comment by maryliag** [comment]
anything else missing on this issue or can it be closed?
