### ISSUE TITLE
catalog: support table record types in table and type definitions

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#70099]
Table record types are the composite types that are created implicitly for all tables. This issue tracks the ability to do something like this without error:

```
CREATE TABLE a (a INT PRIMARY KEY);
CREATE TABLE b (b INT AS (((1,)::a).a) VIRTUAL);

CREATE TYPE t AS (a a)
```

Epic CRDB-2453

Jira issue: CRDB-9940

**Comment by ajwerner** [comment]
This is part of the broader issue of supporting record types. It is associated with https://github.com/cockroachdb/cockroach/issues/70036 which is ambiguous when it comes to what you may or may not be able to do with those record types. A generous reading of #70036 includes this issue.

**Comment by jordanlewis** [comment]
(I have an incoming PR that references this one with an Unimplemented issue reference.)

**Comment by postamar** [comment]
```
CREATE TABLE a (a INT PRIMARY KEY);
CREATE TABLE b (b INT AS (((1,)::a).a) VIRTUAL);
```
currently fails because we need to add a back-reference to `b` in the `a` record type, which we can't do obviously because there is no such type descriptor. In the short term perhaps we could add a repeated ID field in the table descriptor proto to hold the record-type back-references. In the longer term I'm worried that we haven't properly thought through the implications of altering record types so I'd rather wait until we do before adding further support.

**Comment by postamar** [comment]
Sorry didn't mean to close.

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/90698 and https://github.com/cockroachdb/cockroach/pull/90491
