### ISSUE TITLE
sql: mixed version cluster should be able to run distributed flows

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#70124]
A mixed version cluster, in case a user wants to upgrade nodes slowly, should have DistSQL performance equivalent to the older version.
The `[MinAcceptedVersion, Version]` pair https://github.com/cockroachdb/cockroach/blob/d69481bd61ab5b02207a28ffe2b691abfd329d06/pkg/sql/execinfra/version.go for 21.2 is [48, 50] and for 21.1 is [44, 46], which means
- 21.2 nodes cannot function as leaves for a flow originating at a 21.1 node since the 21.1 node will assign a version 46.
- 21.1 nodes cannot function as leaves for a flow originating at a 21.2 node since the assigned version will be 50.

The first bullet can be addressed by less aggressive bumping of the MinAcceptedVersion. The second requires awareness of versions accepted by nodes that should participate in that flow, and choosing the highest accepted version.

Jira issue: CRDB-9953

**Comment by yuzefovich** [comment]
We're adding this issue to the backlog because of the following observation: the DistSQL version doesn't depend on the binary version, so when performing the rolling upgrade of the cluster (say all nodes over the period of 4 hours), we would only have the mixed-DistSQL-version state for 4 hours, even if the upgrade finalization will take weeks to occur.

For 21.2 the only thing we could do is audit all the bumps and possibly remove some of them, but we're not sure whether it'd be worth it.

**Comment by mgartner** [comment]
@yahor is this still relevant as we remove the distsql versioning?

**Comment by yuzefovich** [comment]
No, we plan to never bump `execinfra.Version` again (#98550), so this issue is no longer relevant. (BTW @ yahor is a different person lol, but I'm pretty sure he's also from Belarus :)

**Comment by mgartner** [comment]
Oops, fixed the comment. Thanks for closing!
