### ISSUE TITLE
sql: `ALTER ROLE...IN DATABASE` applies to all databases

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#70257]
**Describe the problem**

`ALTER ROLE...IN DATABASE` is not limited to the specified database.

**To Reproduce**
```
-- as root
root@localhost:26257/defaultdb> alter role vy in database defaultdb set client_min_messages = warning;
ALTER ROLE
```
```
-- connect as vy in separate session
ubuntu@vy-test-0002:~$ ./cockroach sql --user=vy
vy@:26257/defaultdb> show client_min_messages;
  client_min_messages
-----------------------
  warning

vy@:26257/defaultdb> use db1;
SET

vy@:26257/db1> show client_min_messages;
  client_min_messages
-----------------------
  warning
```

**Expected behavior**
`db1` should not have `client_min_messages = warning`

**Environment:**
 - SHA: `f6848a5fd2168579ee65acff35549f22cc393403`

**Comment by ajwerner** [comment]
What happens if you connect directly to `db1` after making the change? Is the problem maybe that we don't clear it out? I feel like this might come from the fact that in postgres you can't change databases, you have to reconnect. What should we do when the user changes databases? Should we reset all settings, including ones set during the session? I think that that would match postgres behavior, no? Should we reset the settings only which have the value inherited from the old database (that seems complicated)? 

I think we can document our way out of this by saying that you get the role settings of the database your session initially connects to.

**Comment by rafiss** [comment]
The default settings don't apply when using `SET DATABASE = ...` or `SET ROLE = ...`. Only when a new connection is created.

This matches Postgres -- (PG doesn't have SET DATABASE, but that's what it does with SET ROLE)

**Comment by rafiss** [comment]
This is also mentioned in the release note for this change: https://github.com/cockroachdb/cockroach/pull/68128

**Comment by vy-ton** [comment]
> The default settings don't apply when using SET DATABASE = ... or SET ROLE = .... Only when a new connection is created.

I clarified my original reproduction. I did connect as `vy` in a new session. Otherwise for `defaultdb`, I wouldn't have seen `client_min_messages=warning`

**Comment by rafiss** [comment]
`USE db1` is an alias for `SET DATABASE = db1`.

So it sounds like we're all saying the same thing? The default settings do not get applied when you use `SET DATABASE`, nor do any of the existing settings in the session change. 

To see the behavior you seem to be expecting, try this:
```
# Connect as vy to defaultdb
ubuntu@vy-test-0002:~$ ./cockroach sql --user=vy

vy@:26257/defaultdb> show client_min_messages;
  client_min_messages
-----------------------
  warning

vy@:26257/defaultdb> quit;


# Connect as vy to db1
ubuntu@vy-test-0002:~$ ./cockroach sql --user=vy --database=db1

vy@:26257/db1> show client_min_messages;
  client_min_messages
-----------------------
  notice
```

**Comment by vy-ton** [comment]
> So it sounds like we're all saying the same thing? The default settings do not get applied when you use SET DATABASE, nor do any of the existing settings in the session change.

Agree, we can document this for 21.2.

> What should we do when the user changes databases? 

As a user, I might expect `use db` or `set database` to be equivalent to reconnecting to the database. Outside of session defaults, are there other ways this is not true? I would expect the default settings of the connected database regardless of the initial session. @rafiss thoughts?

**Comment by rafiss** [comment]
Here's an analogous situation in Postgres that's similar to your original report. I'm using `SET ROLE` instead of `SET DATABASE` since postgres doesn't support `SET DATABASE`.

```
rafiss@127:postgres> alter role rafiss in database postgres set client_min_messages = warning;
rafiss@127:postgres> quit;

# Reconnect as rafiss
$ pgcli 'postgres://rafiss@localhost/postgres'

rafiss@localhost:postgres> show client_min_messages;
+-----------------------+
| client_min_messages   |
|-----------------------|
| warning               |
+-----------------------+

rafiss@localhost:postgres> set role to 'other_role';

rafiss@localhost:postgres> show client_min_messages;
+-----------------------+
| client_min_messages   |
|-----------------------|
| warning               |
+-----------------------+

rafiss@localhost:postgres> quit;

# Reconnect as other_role
$ pgcli 'postgres://other_role@localhost/postgres'

postgres> show client_min_messages;
+-----------------------+
| client_min_messages   |
|-----------------------|
| notice                |
+-----------------------+
```

Is the confusion around the fact that the postgres cli (both psql and pgcli) have `USE db` commands? That is an alias for ending the current session and creating a new one in a different database. If that's the source of the confusion, then this report is more of an issue about how the `cockroach sql` cli implements `USE` -- it sounds like you are asking for `USE` to reconnect rather than call `SET database`.

**Comment by vy-ton** [comment]
> then this report is more of an issue about how the cockroach sql cli implements USE -- it sounds like you are asking for USE to reconnect rather than call SET database.

Yes, my last comment is alluding to this as well. I would take it a step further in that I expect `USE`, `SET DATABASE`, and connect to initial database all to be equivalent. But I don't know if there's context for why they are not.

**Comment by rafiss** [comment]
> Agree, we can document this for 21.2.
What additional language do you think is needed on the release note? https://github.com/cockroachdb/docs/issues/11249

> As a user, I might expect `use db` or `set database = db` to be equivalent to reconnecting to the database.
I would find it confusing if `set database` created a whole new connection -- this is the syntax for changing a session variable, so creating a new connection for that feels non-standard to me.

I could see creating a new connection to be the expectation for `use db`, since that's what psql does. But then there also could be some confusion since we've always documented `use db` as an alias for `set database = db`, and this would be a departure.

---

If we do want to change what `USE db` does in our CLI, we should either rename this issue or close it and create a new one.

**Comment by vy-ton** [comment]
Release notes LGTM.

I'm good with closing this issue, thanks for helping me understand.

Since our CLI also supports `\c` for a new connection, I'm inclined to do nothing there now.

> I would find it confusing if set database created a whole new connection -- this is the syntax for changing a session variable, so creating a new connection for that feels non-standard to me.

Let's also defer this for now. If we had the full PG-compatible `CONNECT` privilege, I wonder if it would make us reevaluate.
