### ISSUE TITLE
ui: fix common problem of `start` without --insecure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7026]
`cockroach start` without the `--insecure` flag or the certs flags will only listen on localhost. This is done so that a user doesn't accidentally start an insecure cluster that is exposed to the world. Unfortunately, it is a very common new user experience to start such a cluster and then not be able to connect to the admin UI from another host and be confused.

I propose that `cockroach start` (without `--insecure` or certs flags) listens on all addresses (or those specified by `--host`) for the admin UI, but serves some sort of error page on the external addresses with a pointer to the documentation about why `--insecure` or the certs flags need to be specified.

**Comment by jseldess** [comment]
@petermattis, we're getting lots of questions about this, so it's great that we're going to make changes. But I can't wrap my head around why we need to require `--insecure` or certs to make it possible to listen on more than `localhost`. I'm sure I'm missing something, but here's what seems easiest and most intuitive to me:

- **Insecure cluster listening only on `localhost`:** `cockroach start --insecure`, where `--host` defaults to `localhost`.
- **Insecure cluster listening on specific addresses:** `cockroach start --insecure --host=<specific addresses>`
- **Insecure cluster listening on all addresses:** `cockroach start --insecure --host=all` (or something like that)

**Comment by petermattis** [comment]
@jseldess In a word: security. We don't want to listen on external addresses without the user specifying `--insecure`. Note that the issue is when the `--insecure` flag isn't specified. If you specify `--insecure` we listen on all addresses.

**Comment by bdarnell** [comment]
It's easy to give the admin UI special treatment while `--port` and `--http-port` are separate, but when we merge them back together, this proposal will require serving GRPC and pgwire on all interfaces as well. We'll need to modify both of those servers to return errors for non-localhost access (and ensure that in the case of GRPC that this error for joining gossip is reported at least as cleanly as the current "connection refused".

I think it's worth at least considering this alternative:
* No default: either `--insecure` or the certificate flags are always *required* for `cockroach start`
* `--host` doesn't depend on `--insecure`; we always default to listening on all interfaces

This makes the relationship between the flags more transparent. It does make things slightly harder to use in the case of the local development server (you'd have to say `--insecure --host=localhost`; using only `--insecure` without `--host` would be dangerous), but I think that's solvable. Most people don't know or care anything about postgres or mysql's command-line flags because they don't run them by hand; the servers are packaged up in such a way that this is invisible.

**Comment by petermattis** [comment]
The admin UI can still get special treatment when `--port` and `--http-port` are merged. If we create different listeners for local and external addresses, it is straightforward to register different services (e.g. admin UI, grpc, etc) on those listeners. 

That said, your alternatives are worth considering. The current `--insecure` behavior was an attempt to assuage the security conscious. I don't have particular skin in this game.

**Comment by jseldess** [comment]
@bdarnell, in your scenario, which seems more intuitive than what we have now, why wouldn't we default `--host` to `localhost` instead of all interfaces? That would make it harder for users to accidentally expose a local dev server. Have been looking at rethink, and that seems to be what they do. They say "loopback addresses are enabled by default". You have to add additional addresses to listen on.

Also, we could simplify further by saying a cluster is secure if cert flags are present. If not, it's insecure; no `--insecure` flag involved. This is the approach rethinkdb takes as well.

**Comment by bdarnell** [comment]
@petermattis If you have a listener bound to all addresses, that will block the creation of a listener on any single address using the same port (and vice versa), at least on some platforms.

@jseldess Doesn't defaulting to localhost lead to the same problem that prompted this issue? Running on localhost works, but accessing the admin UI from another machine or adding a second node will fail without adding `--host`. Of course, if `--host` is *always* necessary for multi-node clusters instead of being dependent on `--insecure` then we could document it more clearly.

We want the explicit `--insecure` flag instead of just relying on the absence of certs because we want to make sure the user is aware that they are taking a risk by doing so. It's more important for us than for many other databases because we don't support password-based authentication and so there is no security at all without certificates. That said, if we defaulted to localhost-only I might be willing to let go of the `--insecure` flag, since you'd need the explicit `--host` flag to open it up to other nodes.

**Comment by petermattis** [comment]
We've got control over which services are registered on each listener. I was thinking that we would have different listeners for the local and external addresses and internally only register the grpc server on some of those listeners.

**Comment by bdarnell** [comment]
> We've got control over which services are registered on each listener.

Yes, but it doesn't matter if we can't create the two listeners. This fails on linux (but works on mac):

```
func main() {
	if _, err := net.Listen("tcp", ":1234"); err != nil {
		fmt.Printf("failed to bind to all interfaces: %s\n", err)
	}
	if _, err := net.Listen("tcp", "localhost:1234"); err != nil {
		fmt.Printf("failed to bind to localhost: %s\n", err)
	}
}
```

**Comment by petermattis** [comment]
It's mildly irritating, but we can list the local interfaces and from there get the local addresses:

```
	ifaces, err := net.Interfaces()
	if err != nil {
		log.Fatal(err)
	}
	for _, i := range ifaces {
		addrs, err := i.Addrs()
		if err != nil {
			log.Fatal(err)
		}
		for _, addr := range addrs {
			log.Printf("%s: %s\n", i.Name, addr)
		}
	}
```

**Comment by bdarnell** [comment]
Ah, I didn't think there was a portable way to get all the interfaces (well, mostly portable - net.Interfaces() is a noop on plan9 and solaris). That would indeed let us bind different things by interface.

**Comment by mrtracy** [comment]
@jseldess @petermattis is this still an area of confusion, or something we mean to address for 1.0?  This has not been modified or discussed in a long time.

**Comment by mberhault** [comment]
I believe this is no longer a problem. We now always listen on all interfaces by default.
