### ISSUE TITLE
sql: migrate schema object removals and GC to `DeleteRange`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#70427]
Currently, removal of schema objects such as tables, indexes, and tenants are done by changing the descriptor visibility and scheduling a job to remove the object data using `ClearRange` once the GC TTL expires. However, as described in #69380, when `DeleteRange` is changed to use MVCC range tombstones in #70415 we should use `DeleteRange` to remove these objects instead. This includes removing the schema GC jobs entirely, and relying on MVCC GC to remove the data when the TTL expires (requires #70414).

There is a much cheaper initial option in #76105.

Related to #31563.

Epic CRDB-2624

Jira issue: CRDB-10070

**Comment by ajwerner** [comment]
Reflecting on this a bit, the primary challenge will be the migration away from the GC job so that we can delete that code. My instinct is that the way to do it is to:

1) Create a version gate that follows the new DelRange being enabled (`VersionDrainGCJobs`)
    * This version reversion also prevents the creation of GC Job.
2) Add logic in the GC Job in 22.1 that detects the version activation and then issues the new DelRange ops
3) Add a migration with this versions which waits until there are no GC jobs.
   * Probably need to be careful about having a barrier in terms of ongoing transactions and schema change jobs
   
This is still hand wavy.

The problem with this is that it may take 2x GC TTL for data to get removed. Seems fine.

**Comment by erikgrinaker** [comment]
Will we use `DeleteRange` for tenant GC as well? I believe it currently uses its own GC system similar to schema GC, with `ClearRange`. Since we'll be populating tenants using non-MVCC methods (e.g. with streaming replication), I suppose we might be able to keep using `ClearRange` when GCing them. I think I'd prefer to stick with MVCC where possible though.
