### ISSUE TITLE
sql: pg_catalog.set_config with 3 arguments fails on import

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#70583]
**Describe the problem**

using pgdump to import a table where header has the following statement

```sql
SELECT pg_catalog.set_config('search_path', '', false);
```

it gets logged as unsupported in 21.1.9 with the following error

```sql
unsupported 3 fn args in select: ['search_path' '' false]: unsupported by IMPORT
```

Please describe the issue you observed, and any steps we can take to reproduce it:

import a pgdump file with the sql above, it will work if you choose to ignore_unsupported_statements options. Based on https://github.com/cockroachdb/cockroach/pull/35121 it was supposed to be working.

**Expected behavior**
this statement should be supported and not logged as unsupported

**Environment:**
 - CockroachDB version 21.1.9
 - Server OS: OSX
 - Client app cockroach userfile import

**Additional context**
What was the impact?

**Comment by otan** [comment]
i'm guessing this is another case of needing `WITH ignore_unsupported`, but i'm still sad we don't at least have a hint for this kind of thing

**Comment by adityamaru** [comment]
Hey @dbist thanks for filing. I'm not sure that supporting this statement makes sense for import. IMPORT is a long-running job that does not have a session tied to it. This statement resets a session variable  `search_path` that controls name resolution logic for a particular session, and since the background job has no session associated with it, the statement will have no effect. We decided to be explicit about what we ignore rather than silently skipping over some statements, and so we require the user to pass in `ignore_unsupported`.

**Comment by adityamaru** [comment]
I agree @otan, the way pgdump parsing is written today this'll mean wrapping each error site with a hint. We could do it, it'll probably be messy. We plan to do a significant revamp of IMPORT DDL handling in 22.1 so maybe things look better after that. In the meantime, we could just always buffer a pg notice if an import query doesn't have the option set? Very rarely will a customer get through an import without specifying this option.

I'll bring it up with the team, I'm going to close this issue since it is specific to supporting set_config.
