### ISSUE TITLE
cdc: include cdc falling behind in CC alerting

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#70633]
We allow you to configure alerts for your CC cluster - this will email the end user for a set of criteria (ie, running out of capacity). This is used for a small subset of cases to alert the end user so that they can self-serve fix the problem, without having to rely on SRE. It is built of off prometheus metric erroring. https://www.cockroachlabs.com/docs/cockroachcloud/alerts-page.html#configure-alerts 

Since changefeeds are something that today needs to be self-serve dealt with by the end CC user, and we do not have other monitoring/alerting of changefeeds available today, we should include changefeed alerts in this package. 

We should add:
Alert when changefeed is running 50% behind where the gc.ttl is set as (TBD: is 50% the right number?)

Jira issue: CRDB-10153

**Comment by amruss** [comment]
@thtruo filed this issue, re: our conversation this afternoon

**Comment by dhartunian** [comment]
@amruss is this something that can be done by on-prem customers today using the prometheus metrics we publish? If not, this will be a heavy lift since the alerts can currently only be configured based on those metrics. Is your ask to have a per-changefeed alert or some sort of global alert per-cluster?

I took a brief look through metrics and here are some possible candidates for an alert but I'm not very familiar with what will/won't work in this feature space:
```
# HELP changefeed_failures Total number of changefeed jobs which have failed
# TYPE changefeed_failures counter
changefeed_failures 0

# HELP changefeed_max_behind_nanos Largest commit-to-emit duration of any running feed
# TYPE changefeed_max_behind_nanos gauge
changefeed_max_behind_nanos 0

# HELP jobs_changefeed_resume_failed Number of changefeed jobs which failed with a non-retriable error
# TYPE jobs_changefeed_resume_failed counter
jobs_changefeed_resume_failed 0
```

**Comment by amruss** [comment]
@dhartunian this is something that can be alerted on by on prem clusters via prometheus using changefeed_max_behind_nanos (see: https://www.cockroachlabs.com/docs/v20.2/monitoring-and-alerting#changefeed-is-experiencing-high-latency)
