### ISSUE TITLE
sql: inconsistent behaviour when subtracting intervals

### ISSUE THREAD

**Issue by dasrirez** [cockroachdb/cockroach#70698]
**Describe the problem**

Hello! There seems to be some inconsistent behaviour when performing operations on timestamps. Specifically, when subtracting an interval without explicitly declaring that it is an interval.

**To Reproduce**

```
> select now() - '2h';
ERROR: parsing as type timestamp: could not parse "2h"
SQLSTATE: 22007
```

**Expected behavior**
The interval should be parsed and subtracted from the timestamp.

**Additional data / screenshots**

Explicit intervals:
```
> select now() + interval '2h';
            ?column?
---------------------------------
  2021-09-24 18:37:46.420105+00
(1 row)


Time: 50ms total (execution 1ms / network 49ms)

> select now() - interval '2h';
            ?column?
---------------------------------
  2021-09-24 14:37:49.980009+00
(1 row)


Time: 49ms total (execution 1ms / network 48ms)
```

Non explicit intervals:
```
> select now() - '2h';
ERROR: parsing as type timestamp: could not parse "2h"
SQLSTATE: 22007
```

However these work
```
> select now() + '2h';
            ?column?
---------------------------------
  2021-09-24 18:37:58.373903+00
(1 row)


Time: 47ms total (execution 0ms / network 47ms)

> select now() + '-2h';
            ?column?
---------------------------------
  2021-09-24 14:38:11.057845+00
(1 row)
```

**Environment:**
- CockroachDB version
    ```
    cockroach version details:
    Build Tag:        v21.2.0-alpha.00000000-3961-g1346d534c4
    Build Time:       2021/09/13 20:30:51
    Distribution:     CCL
    Platform:         darwin amd64 (x86_64-apple-darwin20.6.0)
    Go Version:       go1.17
    C Compiler:       Apple LLVM 12.0.5 (clang-1205.0.22.11)
    Build Commit ID:  1346d534c4f91ccfde04915d45978da1c3cd5620
    Build Type:       development
    ```
 - Server OS: macOS Big Sur 11.6
 - Client app: `cockroach sql`

Epic CRDB-8948

**Comment by jordanlewis** [comment]
The reason that this bug exists is a detail with our overload resolution algorithm.

When trying to resolve which overload to pick for the `-` operation in the example `now() - '5h'`, we don't have the type information yet for the right-hand-side of expression, since it's an untyped string value.

In the case of the minus overload with a timestamp on the left, we have 3 possiblities:

1. timestamp - timestamp
2. timestamp - timestamptz
3. timestamp - interval

To try to figure out which overload to pick, we apply several heuristics, one of which is to remove any overloads that require a type for a constant in the expression that isn't actually parseable as that type. You'd think that this heuristic would properly trim out the first 2, since we can't parse `5h` as a timestamp or a timestamptz.

However, there's another heuristic that comes first: eliminating any overloads that don't have a "homogeneous set of types", meaning we end up preferring the timestamp - timestamp one (in absence of a constraint on the *return type*, which is not constrained in this case as we're just returning the thing and not passing it into any other expression) before we get to apply the "can constant become" heuristic.

I think a fix for this might be to pull the "can constant become" heuristic higher up than the "homogeneous set of types" heuristic, but I'm not sure yet if this would break other things.

**Comment by rafiss** [comment]
is this the same as https://github.com/cockroachdb/cockroach/issues/57876 ?

thanks for looking into it @jordanlewis!

**Comment by jordanlewis** [comment]
No, it's different.

**Comment by jordanlewis** [comment]
Hilariously, Postgres has this exact same limitation, so I'm now thinking we should close as won't fix.

```
postgres=# select now() - '2h';
ERROR:  invalid input syntax for type timestamp with time zone: "2h"
LINE 1: select now() - '2h';
                       ^
postgres=#
postgres=# select now() - '2h'::interval;
           ?column?
-------------------------------
 2021-09-24 17:05:40.598374-03
(1 row)

postgres=# select array['foo'] || 'foo';
ERROR:  malformed array literal: "foo"
LINE 1: select array['foo'] || 'foo';
                               ^
DETAIL:  Array value must start with "{" or dimension information.

postgres=# select array['foo'] || 'foo'::text;
 ?column?
-----------
 {foo,foo}
(1 row)
```

@dasrirez, the workaround is to cast the interval to an interval, to make sure the database knows we're sending an interval and not a timestamp.

**Comment by dasrirez** [comment]
Woah TIL, fair enough.

**Comment by otan** [comment]
can confirm this is something we're unlikely to fix if it's not going to match postgres. 

(i wish we could, but as it turns out, computers are dumb!)
