### ISSUE TITLE
kvcoord: improve RangeIterator seek for consequent keys from the same range

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#70706]
In https://github.com/cockroachlabs/support/issues/1205 we observed that `RangeIterator.Seek` can take non-trivial amount of time (it was 200ms for 815 keys). In that issue it turned out that all 815 keys belong to the same range, so I wonder whether we can introduce some kind of a hot path for such a scenario that would allow us to speed things up significantly.

As a possible idea we could optimistically assume that each seek key belongs to the previous sought to range. We could also count the number of last keys that are part of the same range and make the optimistic guess that the seek key will belong to that range too, once the count reaches some threshold. I'm shooting in the dark here though, so feel free to edit.

**Comment by erikgrinaker** [comment]
>In cockroachlabs/support#1205 we observed that RangeIterator.Seek can take non-trivial amount of time (it was 200ms for 815 keys). In that issue it turned out that all 815 keys belong to the same range, so I wonder whether we can introduce some kind of a hot path for such a scenario that would allow us to speed things up significantly.

I'm not sure if this is accurate. My read in that issue is that the 815 keys were spread across 584 ranges. The 200ms time is skewed by a cache miss that ended up with a 130ms range descriptor lookup, without that we're down to about 70ms to iterate over 584 cached ranges. This doesn't seem _terrible_, but let's see if we can optimize it.

**Comment by erikgrinaker** [comment]
Replaced this with #71801.
