### ISSUE TITLE
ui/next: makefile proto invalidation maybe not working

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/cockroach#7071]
- What did you do?
Added an entry to `ValueType` in roachpb/data.proto. Ran go generate ./...

- What did you expect to see?
Expected ui/next/app/js/protos.js, ui/next/generated/protos.d.ts, and ui/next/generated/protos.json to be updated.

- What did you see instead?
They weren't. roachpb/data.pb.go and storage/engine/rocksdb/cockroach/roachpb/data.pb.{h,cc} were updated but the ui/next stuff wasn't. Interestingly, if I delete the three ui/next generated files, and then run go generate ./..., it does the right thing, which makes me think the makefile invalidation isn't working.

I bring all this up because circleci fails if the files don't match, but our docs don't really mention (as far as I saw) how to regenerate them.

**Comment by paperstreet** [comment]
cc @mrtracy or @tamird maybe?

**Comment by tamird** [comment]
Discussed in person; this is due to ui/next/Makefile's knowledge of the protos being limited. In other words, it only knows about its direct dependencies, of which data.proto is not one.

We can fix this either by growing ui/next/Makefile's knowledge of our protos or by moving the js target to build/protobuf.mk. I think the latter is probably better, but introduces some tricky dependencies.

**Comment by maxlang** [comment]
It's pretty fast, what about regenerating them from scratch every time?

**Comment by tamird** [comment]
Also a possibility.

**Comment by tamird** [comment]
Hey, this was fixed in https://github.com/cockroachdb/cockroach/pull/7374.
