### ISSUE TITLE
Speed up CircleCI runs

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#708]
CircleCI seems to take between 10 and 20+ minutes. We should see if we can speed that up.
Sample approximate run times for various steps on a 15m run:
- docker load: 3m
- build: 3m
- tests: 2m
- race detection: 2m
- acceptance tests: 2m
- everything else: 3m

Random thoughts:
- start with better timing measurement. we only have per-step breakdowns, we need more details for some steps (eg: docker load, build)
- run various types of tests in parallel (regular/race detection/acceptance)
- faster docker setup? no docker at all?

**Comment by tschottdorf** [comment]
the `make acceptance` step had its caching broken, I think that's easily fixed - I'll take a look at it soon, it shouldn't take more than 30secs. Docker load is slow because CircleCI is slow. We could try to shrink down the image but it's doing to be awkward.
I think parallelization won't help us much (now) because most of the time in CircleCI is spent building the initial image and copying the cached image around. Our best bet if we want to make this faster is to stop actually doing work on CircleCI but instead hooking up to GCE and doing the work there.

The builds on `master` take a lot longer because they build the `cockroachdb/cockroach` image, and that builds a static binary (so it starts mostly from scratch), plus it re-runs all the test. I also think that one's probably best kept on GCE.

Would assume that we could make it to <2min builds on GCE, especially if we build on a machine that either has the cache locally or can just copy 1-2GB in a short amount of time).

**Comment by tschottdorf** [comment]
the issue with `make acceptance` is that this is the first invocation of make, so it's installing the githooks and that breaks the cache. I'll see if adding those to `.dockerignore` is enough.

**Comment by tschottdorf** [comment]
`make acceptance` portion of the CircleCI tests is now down to 20-22sec.

**Comment by tamird** [comment]
Closing now that https://github.com/cockroachdb/cockroach/pull/1115 has landed.
