### ISSUE TITLE
cli: `cockroach sql` should use system CA certs and only be required when necessary

### ISSUE THREAD

**Issue by nvb** [cockroachdb/cockroach#70946]
**Describe the problem**

Currently, `cockroach sql` mandates that users pass the `--certs-dir` flag whenever the `--insecure` flag is not provided. If one of the two flags is not passed, the users is presented with the error:
```
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters
```

This is unnecessarily restrictive in two different cases:

First, it means that the `--certs-dir` flag must be passed even when no client certificates will be used. This case arises when a client uses password auth and opts out of [client verification of server certificates](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBQ-SSL-CERTIFICATES) by passing `sslmode=require`. In such cases, there is no reason to require the `--certs-dir` flag.

Second, it means that `cockroach sql` will never attempt to use system CA certs to perform client verification of server certs for MITM protection. This case arises when a client uses password auth and opts in to client verification of server certificates by passing `sslmode=verify-full` (**our preferred connection strategy for serverless**). In such cases, the system may already have the root certificate available elsewhere, which Go will automatically pick up if given the opportunity, but we currently throw an error before getting to that point.

**Expected behavior**

I would not expect `--certs-dir` to be required in either of these cases.

In the second case, I would expect the system CA certificates to be used for client verification.

**Comment by smcvey** [comment]
In Cockroach v21.1.6 you could start up a demo:

```
# cockroach demo --sql-port 26257
```

and upon startup, you'd get a list of connection parameters:

```
- Connection parameters:
...
(sql)      postgresql://demo:demo4761@127.0.0.1:26257/movr?sslmode=require
...
```

You could then use that to connect:

```
cockroach sql --url "postgresql://demo:demo4761@127.0.0.1:26257/movr?sslmode=require"
```

and it would work fine.

Now in v21.2, if you try and connect:

```
cockroach sql --url "postgresql://demo:demo4761@127.0.0.1:26257/movr?sslmode=require"
```

It complains about not specifying a certificate directory.

```
$ cockroach sql --url "postgresql://demo:demo4822@127.0.0.1:26257/movr?sslmode=require"
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem using security settings: no certificates found; does certs dir exist?
Failed running "sql"
```

You can get around this by specifying a certs dir, but why did this behaviour change?  Is it broken or was the change deliberate?

**Comment by WadeWaldron** [comment]
Related, when using Cockroach Demo along with the --listening-url-file flag, the resulting URL can not be used to connect because it lacks the certificate information.

**Comment by WadeWaldron** [comment]
To give a little more context around the impact of this. Previously I was running a Cockroach Demo instance. I was then executing:

'''ALTER USER demo with password "movr";'''

I did this to ensure that I would have a stable username/password/url in order to connect to that Demo instance.

I could then use the (sql) URL to connect to the DB by running something like:

```
cockroach sql --url " postgresql://demo:movr@127.0.0.1:26257/defaultdb?sslmode=require"
```

Because I have updated the password, this URL is now consistent. I can use it in instructions, documentation, scripts, etc.

This worked fine in 21.1.6.

However with 21.2.x this no longer works because of the certificate requirement.

The result is that I can no longer generate a stable URL, because the certificate folder has a random name that changes with every execution, and there is no way to override it (that I can see).

This means I can't write scripts that rely on the URL being something specific.
I can't write instructions where a user could just copy/paste the URL from the instructions (they'll have to copy/paste from the demo output).
And the instructions that a user receives in the demo output are now wrong because the (sql) url doesn't work and they must instead use the (sql/unix) url.

It also invalidates some of the docs. For example:

https://www.cockroachlabs.com/docs/stable/cockroach-demo.html#connection-parameters (sql)

and

https://www.cockroachlabs.com/docs/stable/cockroach-demo.html#flags (--listening-url-file)

**Comment by jseldess** [comment]
Given that the [connection parameters](https://www.cockroachlabs.com/docs/stable/cockroach-demo.html#connection-parameters) in the `demo` welcome text don't work, I'd consider this a bug. For example, [this example](https://www.cockroachlabs.com/docs/stable/cockroach-demo.html#connect-an-additional-sql-client-to-the-demo-cluster) for connecting an additional SQL client to a demo cluster doesn't work.

@nvanbenschoten, can we label this issue as a bug, not an enhancement?

**Comment by awoods187** [comment]
@abhinavg6 and @vy-ton can the two of you joint triage this issue?

**Comment by vy-ton** [comment]
FYI related Slack thread: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1638394515271600

@abhinav SQL doesn't know if this was an intentional change per the thread above. We can help makes fixes based on what Security recommends.

**Comment by nvanbenschoten** [comment]
This is a complex topic, but I don't think the changes to `demo` are related to the original issue description. The issue was filed to discuss client verification of server certificates, not server verification of client certificates.

`demo`'s behavior does look to have regressed, but that's a different issue. It appears to have something to do with `demo` now using client certificates for authentication. We should open a separate issue to track that behavior change/regression. It may or may not have been intentional. Either way, it's likely a different issue.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten. @smcvey, your comment captures the `demo` bug, I think. Would you mind opening a new issue for that? We can move @WadeWaldron and my comments to the new issue as well.

**Comment by yecs1999** [comment]
@nvanbenschoten What is meant by "server verification of client certificates"? Doesn't the use of sslmode=required force a secure connection without need to verify a certificate?  I'm a bit confused about what is meant by that as it seems to be the same`cockroach sql` command being used as the first example where the client opts out of client verification of server certificates.

**Comment by WadeWaldron** [comment]
What I can say is that the issues with demo seem to be client side, rather than server side.

If you run a 21.1.6 instance of `cockroach demo`, and then try to connect with a 21.1.6 `cockroach sql` command, it will succeed.

If you run a 21.1.6 instance of `cockroach demo`, and then try to connect with a 21.2.x `cockroach sql` command, it will fail.

I.E. no change to the server, only changing the client, causes the failure.

Certainly, the output from the demo issue is identical to the original described issue.

**Comment by abhinavg6** [comment]
We discussed it as part of a scheduled chat to remove the need to download root cert for serverless. @yecs1999 and @catj-cockroach are taking a look at it, including the `certs-dir` issue.

**Comment by abhinavg6** [comment]
And just want to be clear, the need to download root cert won't go away for dedicated yet. We would first need to issue trusted CA certs for those clusters like we do for serverless, which will need proper planning.

**Comment by yecs1999** [comment]
> Will immediately give you the error, even if no server is running. So it's definitely client side.

Digging around I think your issue with demo is some kind of bug with the CLI code itself. The issue here also has the second component where if we want to use verify-full as our sslmode and we DO need the CA certs, we should be able to check for the right System CA certs in our OS root trust store, and not have to specify a --certs-dir

**Comment by rafiss** [comment]
> Digging around I think your issue with demo is some kind of bug with the CLI code itself. The issue here also has the second component where if we want to use verify-full as our sslmode and we DO need the CA certs, we should be able to check for the right System CA certs in our OS root trust store, and not have to specify a --certs-dir

That sounds like what the original issue description from @nvanbenschoten is saying. Is it not?

**Comment by yecs1999** [comment]
@rafiss Yes, I meant that I thought it was a subset of the original description
