### ISSUE TITLE
docs: Include offline copy of docs in the admin UI?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#7109]
Many tools bundle a snapshot of their docs with their releases.

We could potentially serve a snapshot of our docs via the admin UI. We'd probably want to strip the images and include some sort of banner linking to the hosted docs site for the most up-to-date version, but it still might be useful to a user to have offline docs right in the admin UI.

**Comment by dt** [comment]
cc @jseldess any thoughts?

**Comment by jseldess** [comment]
Yeah, this is a great idea - and maybe free Friday project! And if not in the admin UI, it could just be a directory alongside the binary. Users could open `index.html` to access the site locally.

**Comment by couchand** [comment]
Stumbled across this during triage, I think it's brilliant, so I spent a few minutes prototyping it.  I added the entire built `_site` directory to the build within the existing `AssetFS` from `go-bindata`, and updated docs links within the web UI to point to localhost.

It feels pretty awesome to turn off wifi, check out the web UI from a local cluster, click a link to docs, and navigate around our documentation.

On the other hand, since I just bundled the entire built site without care, it doubled the size of the binary, from 130M to 265M.  I'm sure there are a lot of quick wins to be had there, like removing images as suggested by @dt, only serving docs for the binary version, and removing a bunch of JavaScript code not relevant in this context.

The mechanics of embedding something are pretty straightforward, so it seems like most of the effort here will be within cockroachdb/docs, adding some kind of lightweight build option.

Here are a few specific thoughts that came to mind as I was poking around:

- page chrome & remote links
It's actually pretty neat that the header matches our site, and that the non-docs links are absolute.  But we want to be able to exclude some content from the build (like the managed docs and docs for other versions), and then have links to that content be written as absolute in the embedded build.
- landing pages
The website landing page has a nice video intro, which works great on the web.  It's probably appropriate for the embedded landing page to be an outline or textual introduction.
- sidebar table of contents
It looks like JavaScript is currently required to render the table of contents in the sidebar.  It would be very nice to make that static, so that no JS is required to use the embedded docs (and it would be nicer for the website, too).
- images
Some are worth keeping: iconography & the Cockroach logo, maybe also certain key architecture images are useful to embed.  Other images would ideally load from our server, if the user has an Internet connection, and if not, we want to make sure the information is still available.
- local links
It would be cool if the embedded docs description of a feature in the web UI linked straight to that item.
