### ISSUE TITLE
kv: TestProposalNotAcknowledgedOrReproposedAfterApplication is fooling itself, skipped

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#71148]
This test is trying to probabilistically verify something about reproposals. The way in which it tries to verify it is broken - it's using `enableTraceDebugUseAfterFree()` to get `net/trace` to log a message in case of use-after-finish of a `net.Trace`, and then it tries to use tracing to see if that condition triggers. Our tracing by default does not use `net/trace`, though, so the test is fooling itself. 

I've verified that the test doesn't fail when I comment out the code that it relies on:
https://github.com/cockroachdb/cockroach/blob/793b4c8bfc6e9dbf7a05289f3e61035796476cc5/pkg/kv/kvserver/replica_application_state_machine.go#L1228-L1232

The test does fail under stress if I make the `trace.debug.enable` cluster setting default to true.
Rather than having the test use that setting, I'd like to request we find another way for the test to check what it wants. The current approach is too fragile. I recognize that it might not be an easy test to write; perhaps it can be replaced with a lower-level unit test.

I thought about deleting the test completely, but no other test in `kvserver` seems sensitive to the commenting out of the lines above. So I think we probably do need a test here.

cc @tbg @ajwerner @nvanbenschoten 

Jira issue: CRDB-10415

Epic CRDB-25287

**Comment by tbg** [comment]
Test is skipped.

**Comment by tbg** [comment]
I ran into this test today because I was touching `(*Replica).propose` in https://github.com/cockroachdb/cockroach/pull/94105 and wanted to understand

https://github.com/cockroachdb/cockroach/blob/6e4c56547ce45b80d2d1592b5f21da0a8d4e1c5e/pkg/kv/kvserver/replica_raft.go#L330-L338

This lead me to https://github.com/cockroachdb/cockroach/commit/28bee52fbcdd4c6f101115772da852b1a1184a0f which introduced this test (it had a different name then).

I verified that the tracer crashes on use-after-finish, but similar to what Andrei reported above I can't get the test to fail even with the `higherReproposalsExist` bit commented out.

I then set my sights on `TestReplicaReproposalWithNewLeaseIndexError` introduced in https://github.com/cockroachdb/cockroach/commit/aada4fcf3ff410d83a738cf16696e37357cb8d4e. Unfortunately that one doesn't enter that section either.

I'm seeing that all commits that touch this kind of code are outcomes of horrible subtle bugs, so I will spend some time in the area.

**Comment by shralex** [comment]
Hi @tbg, should we look at this closer during stability ? It looks like a test problem, but perhaps by skipping it we're not verifying something important ? assigning to you to decide on the next step, if any.

**Comment by tbg** [comment]
We decided not to rock the boat on reproposals[^1] so let's leave this test alone too as the code it supposedly exercises won't even be around when we clean up reproposals (CRDB-25287).

[^1]: https://github.com/cockroachdb/cockroach/pull/98481

**Comment by erikgrinaker** [comment]
We decided to punt the reproposal refactoring until after the branch cut, so I'm removing the GA-blocker on this since that work will address this test.
