### ISSUE TITLE
db console: bug in jobs ui 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#71563]
When looking at changefeeds in the jobs page in db console, the information shown to the user is stale. See pictures below. The UI shows many changefeeds, many of which it shows as running. When compared with the jobs table, there are only actually two changefeed jobs in the jobs table. 

<img width="1639" alt="Screen Shot 2021-10-13 at 1 16 42 PM" src="https://user-images.githubusercontent.com/13264141/137313595-287c3968-d82d-4bb2-90d7-ef1c5a34a84d.png">
<img width="1370" alt="Screen Shot 2021-10-13 at 1 16 52 PM" src="https://user-images.githubusercontent.com/13264141/137313604-7f8c77f3-25ed-42a1-a0fa-6b959f9cfa8b.png">

The telemetry cluster is where this example is from, you can check the jobs db console page and compare it with the `SHOW CHANGEFEED JOBS;` command output to reproduce

Jira issue: CRDB-10651

**Comment by jocrl** [comment]
So I think two things are going on here.

1. The UI shows more jobs that `SHOW JOBS` does
I believe this is because `SHOW JOBS` [only shows jobs from the last 12 hours](https://www.cockroachlabs.com/docs/v21.2/show-jobs#considerations), whereas the UI queries from `crdb_internal.jobs` (which is the recommendation if you want jobs from before the last 12 hours). The screenshots seems to be consistent with this theory.
@Annebirzin, I'm not sure if we should do anything from a UI/UX perspective about this discrepancy?

2. The "status" column in the UI seems discrepant from the status in `SHOW JOBS`
In the screenshot in the original issue, the second job seems to show in the `SHOW JOBS` as running, but in the UI as cancelled.
And in my attempts to repro locally, the three jobs below are either cancelled or paused, but they show a highwater timestamp. Poking around, I still don't have a good understanding of what a highwater timestamp is. But I'm wondering if we maybe want to show a running/cancelled/paused etc. badge in addition to the highwater timestamp? cc @Annebirzin on this.
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/91907326/166486525-fe09791c-fa5f-4047-b9ed-cf1960a0fe59.png">
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/91907326/166486464-3cb032ef-edc0-449f-9bf3-522f97ed1b93.png">

**Comment by Annebirzin** [comment]
@jocrl 

1. Is there a specific timeframe used to show jobs in the UI? I'm wondering if we could we add a timestamp next to the pagination label that says something like `1-3 of 3 jobs  |  Last cleared May 3, 2021 at 9:14 PM` ?
2. I'm not sure I'm fully understanding the discrepancy but seems like adding the status would make the true status more clear (and assuming this would be consistent with the jobs table in the SQL shell)  

cc @kevin-v-ngo for thoughts

**Comment by jocrl** [comment]
1. I believe that the UI shows all jobs. Unfortunately, it's `SHOW JOBS` that is limited to the last 12 hours, so I'm not too sure on the messaging there.

**Comment by kevin-v-ngo** [comment]
1. SHOW commands are used directly by developers meant for the most commonly used information and extracting quick ad-hoc insights. It doesn't have or surface _all_ information that we have in crdb_internal so i'd classify as expected behavior where docs should be sufficient. Console views pull directly from crdb_internal and we have much more opportunity to surface more information and guide the user to what they need here. In this case, we can surface more jobs since we have gestures such a pagination and quick filtering available in the UI. 

To improve the UX, can we do what @Annebirzin  recommended and text indicating the time frame? 
E.g. `1-3 of 3 jobs | Since May 3, 2021 at 9:14 PM`

I don't think we can clear/reset this page so it'd just be the current time minus 14 days?

**Comment by kevin-v-ngo** [comment]
For 2, I will comment on the other issue. For instance, do we have docs on this "highwater timestamp" and is it only a concept for changefeeds? What does one do with this timestamp?

**Comment by jocrl** [comment]
Ah, I understand the time frame message now. Thanks, that makes sense!
