### ISSUE TITLE
sql: Telemetry ideas for query planning/execution

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#71666]
Some ideas @rytaft and I brainstormed for planning/execution telemetry:

- The optimizer produces a cost estimate, which we don't surface to end-users. However, it would be interesting to capture the cost estimate in product telemetry.
- Capture estimated and actual row count for each statement. The difference would signal how stale stats are.

These could be interesting use cases to try out the new logging telemetry once available

Jira issue: CRDB-10710
Epic: CRDB-15067

**Comment by rytaft** [comment]
It seems like we'll probably want to support this by adding some fields to `CommonSQLExecDetails`, since this is included in the logging-based telemetry: https://github.com/cockroachdb/cockroach/blob/ed0af7e616491b6fe2bbea25308e5c2cb88cb347/pkg/util/log/eventpb/sql_audit_events.proto#L24

The cost estimate and distribution (local v. full) are pretty straightforward to add here. A question I have is how to handle stats. We could certainly compare the estimated and actual row counts returned by the query, but that wouldn't necessarily give us a good idea of how stale the stats are (it might just indicate that the optimizer didn't accurately estimate how the stats would change higher up in the query plan tree). An alternative option is to record this info for one scan in the query plan. We could choose the scan that has the oldest stats (earliest last collected time), or where the q-error between estimated and actual stats is largest: https://github.com/cockroachdb/cockroach/blob/6ca58470efca1e72bf6cec450ec9f386ce0ffd3e/pkg/sql/opt/testutils/opttester/stats_tester.go#L315

Thoughts?

**Comment by vy-ton** [comment]
> An alternative option is to record this info for one scan in the query plan.
Is one scan representative of the entire query?

> We could certainly compare the estimated and actual row counts returned by the query, but that wouldn't necessarily give us a good idea of how stale the stats are (it might just indicate that the optimizer didn't accurately estimate how the stats would change higher up in the query plan tree)
While this might not identify the root cause, could it still be a good signal of how "off" the optimizer was?

**Comment by rytaft** [comment]
> Is one scan representative of the entire query?

Not necessarily, but it would give the best representation of how stale our stats are

> While this might not identify the root cause, could it still be a good signal of how "off" the optimizer was?

This is very query-dependent. For some queries, the final row count estimate could be very close to the actual count (e.g., if there is a LIMIT, we'll probably have a very good idea of the final output), but the internal counts could be way off.

One thing that makes this decision challenging is that every internal node in the query has an estimated and actual row count. Some of these counts may be further off than others. Some may indicate the optimizer chose a bad plan, while in some cases the row count would not have affected the plan either way.

It might be most useful to include several metrics in this case. Here are some suggestions (we'll probably want to pick a subset of these):
- estimated row count, actual row count, q-error for the query output
- estimated, actual, q-error for the internal node with the highest q-error
- average estimated, actual, q-error across all internal nodes
- estimated, actual, q-error, time since last stats collection for the scan with the highest q-error
- estimated, actual, q-error, time since last stats collection for the scan with the oldest stats
- average estimated, actual, q-error, time since last stats collection across all scan nodes
- other ideas?

**Comment by rytaft** [comment]
I just opened #73278 with the easier metrics (cost and distribution) to see if this type of telemetry is what you had in mind. I can open a separate PR for the stats stuff once we agree on what to measure.

**Comment by rytaft** [comment]
Hey @vy-ton have you had a chance to work on this at all? I think this stats telemetry would help inform our stats work in the 22.2 release cycle.

**Comment by vy-ton** [comment]
@rytaft I'm starting to dig into the available data here for cost estimate and distribution.

However for a metric that approximates SQL predictability, we prob need to choose from the list of your ideas - https://github.com/cockroachdb/cockroach/issues/71666#issuecomment-981899953. I'll bring this up in weekly discussion too.

**Comment by vy-ton** [comment]
We plan to add

- [ ] timestamp of last stats collection
- [ ] metric at level of scan, could indicate base table stats - average estimated, actual, q-error, time since last stats collection across all scan nodes
- [ ] metric at higher level of query plan tree - how accurate are optimizer estimates - average estimated, actual, q-error across all internal nodes

**Comment by mgartner** [comment]
> metric at higher level of query plan tree (how accurate are optimizer estimates) - average of estimated row count, actual row count, q-error across all internal nodes

Is this metric tracking counts for all non-scan nodes? Or does it include scan nodes?

**Comment by rytaft** [comment]
> Is this metric tracking counts for all non-scan nodes? Or does it include scan nodes?

Probably easiest to just include all nodes. Do you have an opinion on what would be best?

**Comment by rytaft** [comment]
We should also add telemetry for when stats forecasts are being used

**Comment by rytaft** [comment]
And ideally backport other stats telemetry

**Comment by kevin-v-ngo** [comment]
Hi @rytaft, do you know if this issue can help with this [telemetry improvement](https://github.com/cockroachdb/cockroach/issues/83956) at all? For instance, knowing the max number of rows of a FULL TABLE SCAN?

Are we capturing the attributes and other metadata for each scan node?

**Comment by rytaft** [comment]
Hi @kevin-v-ngo -- sorry for the delay. Sure, I can add telemetry for max number of rows of a full table scan. Do you think it's also useful to count total number of rows scanned (i.e., add the row counts from every scan in the query)?

**Comment by kevin-v-ngo** [comment]
> Hi @kevin-v-ngo -- sorry for the delay. Sure, I can add telemetry for max number of rows of a full table scan. Do you think it's also useful to count total number of rows scanned (i.e., add the row counts from every scan in the query)?

Yes! I was thinking of using the max # rows of a full table scan and the total to compute a ratio we can sort by. I was going to use the total rows logged in our execution stats for this tracked by this [issue](https://github.com/cockroachdb/cockroach/issues/84729). 

Do you happen to know if `numRows` in `crdb_internal.statement_statistics `is the total number of rows from every scan in the query? Our [docs](https://www.cockroachlabs.com/docs/stable/crdb-internal.html#statistics-column) just say number of rows 'returned' or 'observed' and now i'm unsure if it's tracking the rows returned to the client or by each scan. Adding @THardy98 if he knows as well.

**Comment by rytaft** [comment]
> Do you happen to know if `numRows` in `crdb_internal.statement_statistics` is the total number of rows from every scan in the query?

I'm guessing this is the number of rows returned (in case of a select statement) or rows written (in case of a mutation statement).

**Comment by rytaft** [comment]
`rowsRead` is probably what we actually want here. It's technically more than the total number of rows read by scan nodes since it includes rows read by index, lookup, zigzag, and inverted joins, but I think it's probably good enough.

**Comment by kevin-v-ngo** [comment]
That sounds good to me. Thanks Becca!
