### ISSUE TITLE
storage: handle use-after-gc of Replica

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7169]
in #7148, @andreimatei encountered a bug which occurred when a replica was removed while it was the leader: the commit trigger would remove the replica from the store and notify the GC queue; but since it executes that command as the leader, it would asynchronously try to resolve the external intents (which failed since at that point, the replica wasn't able to find itself in the RangeDescriptor).

The above example is only one specific incarnation of a bigger problem: Various goroutines can attempt to handle a `*Replica` (various queues, intent-resolving goroutines, ...) when it's in an unhappy state, and we don't do good enough a job of taking care about that.

**Comment by andreimatei** [comment]
We decided to do nothing for now for the "attempt to resolve intents after replica remove" case for now, pending various Raft refactorings, because we want to find a way to still try to resolve remote intents, but not local intents.
One thing to note is that this particular "use after remove" is a special case: we actually enqueue asyc work after the replica has been removed, as opposed to other theoretical cases where the work has been enqueued before the removal.

**Comment by petermattis** [comment]
#7404 Introduced a `Replica.mu.destroyed` field which prevents Raft usage after `Replica.Destroy` has been called. Is there something else to be done here?

**Comment by bdarnell** [comment]
I think there's some work to be done to ensure that `destroyed` is being checked on all code paths (including reads which don't go through raft). Or we could introduce some new locking as contemplated in #7757.

**Comment by tamird** [comment]
Is this the same as #8630 (which contains more discussion)?

**Comment by andreimatei** [comment]
I believe so. I was actually looking to close this bug the other day, but couldn't find it.
I'm sad that Tobi abandoned his plan to make it impossible to use destroyed replicas.
