### ISSUE TITLE
Statement text sometimes doesn't show on the Transactions page

### ISSUE THREAD

**Issue by lindseyjin** [cockroachdb/cockroach#71876]
**Describe the problem**

Sometimes, the Statements text does not show on the Transactions page for certain transactions. This is not supposed to happen, and also means that we cannot click into the Transaction to see details since the Statement text also serves as a link. This is likely due to an issue with `statementFingerprintIds` being empty for some transactions.

**To Reproduce**

This is pretty difficult to reproduce, but I've been able to see this issue sometimes when doing the following:

1. Run a local Cockroach cluster on the most recent version of master
2. Go to the Transactions page on the new SQL activity page. 
3. Play around with filtering by different columns and try clearing SQL stats a few times. Try clicking into a transaction to view details, and switch between the Statements/Transactions tabs as well (basically just click a lot of stuff). After a while, this issue might appear.

**Expected behavior**
Statements text should show up properly on the Transactions page, and be clickable links.

**Additional data / screenshots**

![image](https://user-images.githubusercontent.com/29153209/138496148-00d48894-0aa0-45ac-83e2-8378e35ab2af.png)
<img width="384" alt="Screen Shot 2021-10-22 at 12 31 37 PM" src="https://user-images.githubusercontent.com/29153209/138496170-2c37d1e7-1305-4697-9951-cba8ca144e63.png">

**Environment:**
 - CockroachDB version [e.g. 2.0.x] 21.2.0
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Epic CRDB-11997

**Comment by Azhng** [comment]
Leaving some thoughts here after some investigation. This bug is quite hard to track down. At first I thought this bug was caused by `cockroach` CLI running transactions like `BEGIN; <observer stmt>; COMMIT` or some variants of  `BEGIN; COMMIT` in the background. That is, until I observed an **implicit** transaction appeared with no stmt fingerprint ID recorded while also has the `$ internal-*` prefix in its `app_name` field. That's telling me something totally different is happening and the bug is probably in the `connExecutor`.

The list of stmt fingerprint IDs for a transaction comes from `connExecutor.extraTxnState.transactionFingerprintIDs`. There are only two places where we set that slice to `nil`:
* when we start recording the transaction in `recordTransactionStart()`
* when the transaction restarts in `onTxnRestart()`. 

So the million dollar question here is:  how do we create a transaction fingerprint entry with `transactionFingerprintIDs=nil` for an implicit transaction?

Possibly, one way to achieve can be: execute the statement in the implicit transaction, the statement encountered an transient error, caused the `connExecutor` to retry the transaction. But before the statement has a chance to retry, the transaction somehow gets aborted, which cause the `transactionFingerprintIDs=nil` at the time of txn stats recording. 

This is only one possibility, I will spend some more time continue investigating.

**Comment by Azhng** [comment]
Found a reliably reprod for this issue: if an optimizer throws any error (not sure why that would happen?), this will cause `dispatchToExecutionEngine` to prematurely return without calling `recordStatementSummary()`. However, since `recordStatementSummary` is responsible for appending the list of statement fingerprint IDs to a transaction, this  cause the later `recordTransaction` to record a nil slice. 

I'm not entirely sure if this is the culprit of this issue, since I'm not familiar with the failure mode of the SQL optimizer. In general, any premature return from `dispatchToExecutionEngine()` can cause this issue to happen, this include `adminRole` check failure when admin audit log is enabled, or the return type check failure. 

The possibility where the transaction retry is another culprit is not ruled out at this point.
