### ISSUE TITLE
Clear SQL stats on the Transactions page does not work on serverless

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#72009]
A user reported that clicking on “clear SQL stats” on the Transactions page doesn’t do anything. On the Statements page, there's at least a spinner to indicate progress when clearing SQL stats.

Epic: CC-5060

**Comment by Azhng** [comment]
Interesting. Seems like both SQL CLI and RPC handler itself are working fine. It's probably the redux state is borked. Investigating more.

**Comment by Azhng** [comment]
Also seems like my transaction page is not rendering anything even though the data is coming back from the RPC 🤔

**Comment by maryliag** [comment]
The clear stats component is the same for both pages. If the user clear stats on Statements page, it takes some time to clear everything (since it clears both statement and transactions page), if then the user went to the Transaction page and clicked clear stats, there wasn't anything persisted to be cleared, so it would probably not show a loading since it would be super fast, just clearing in-memory stats. That could be a reason why it "seems" nothing happened
