### ISSUE TITLE
kvserver: export bytes_read/sec in range status

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#72053]
**Is your feature request related to a problem? Please describe.**
Ranges currently report a useless measure of read QPS, namely BatchRequest/sec. That is, a batch that scans a full 512mb range is counted the same as a point lookup. This causes load balancing problems (https://github.com/cockroachdb/cockroach/issues/50620) but it's also bad for observability (see the `hotranges.sh` script in debug.zip).

**Describe the solution you'd like**
Start accumulating bytes read/sec and add that to range status, so that it makes it into the range reports. This will be automatic for debug.zip, and needs a tiny bit of console work for the UI.

**Describe alternatives you've considered**
We could do nothing. Or we could think of other ways to surface hot ranges. For example, we could have a `hotranges{rank=1} = <rangeid>` family of (prometheus) metrics that we export.

**Additional context**
This issues was triggered by https://github.com/cockroachlabs/support/issues/1253 (internal)

Jira issue: CRDB-10926

**Comment by kvoli** [comment]
We currently record the number of mutations, in writes per second[(wps)](https://github.com/cockroachdb/cockroach/blob/5f43585b052e20aa9aebaccadbf4732e6c185597/pkg/kv/kvserver/replica.go#L222).

Would it make sense in this case, to record the number of keys read per second, instead of bytes reads per second?

This would be consistent with the mutated keys per second we current record.

**Comment by tbg** [comment]
Good question, we'll have to figure out what we want (and maybe we want both). Ultimately, we want useful quantities to make allocator decisions. One range getting hammered with 1mb writes vs one that gets the same qps of 1b writes does make a difference, but there is also a fixed cost per write that is largely independent of the size. We may want both (so hot range reports could be by keys/sec and bytes/sec), but I'm not sure which of the two is the more useful.

**Comment by kvoli** [comment]
> We may want both (so hot range reports could be by keys/sec and bytes/sec)

I agree. Currently, we use [replica stats](https://github.com/cockroachdb/cockroach/blob/3317ca86bcaa4e40d519a3ee2cc085ccbf989f81/pkg/kv/kvserver/replica_stats.go#L61) to record both `queriesPerSecond` and `writesPerSecond` on a per-replica basis.

`writesPerSecond` doesn't seem to be used anywhere currently and is really only used for observability.

This information is then accumulated at the store level, iterating over each replica the store has [here](https://github.com/cockroachdb/cockroach/blob/3317ca86bcaa4e40d519a3ee2cc085ccbf989f81/pkg/kv/kvserver/store.go#L2935). If there is a delta, [it is gossiped ](https://github.com/cockroachdb/cockroach/blob/3317ca86bcaa4e40d519a3ee2cc085ccbf989f81/pkg/kv/kvserver/store.go#L2498) around the cluster.

This then flows through to [metrics at the store level](https://github.com/cockroachdb/cockroach/blob/3317ca86bcaa4e40d519a3ee2cc085ccbf989f81/pkg/kv/kvserver/metrics.go#L284).

How do you feel about reusing this metric *info channel* for additional replica stats?

Do you think we should modify `replicaStats` to be able to record more than one statistic (e.g. one example would be key accesses and bytes), in a generic fashion? Or perhaps its better to just instantiate multiple `replicaStats`? This would include for `writeKeys` (renamed, currently `writeStats`), `writeBytes`, `readKeys` and `readBytes`. These are in addition to `leaseholderStats`, which accounts `qps`.

I currently have a sketch for `readStats`, only recording the keys [here](https://github.com/cockroachdb/cockroach/pull/76609/files?w=1&diff=split).

**Comment by shralex** [comment]
Thanks for tracking down all of this. Maybe what we want are a few basic metric aggregator classes, one for bytes, one for count, maybe one for time, not sure. Then one class where we can add statistics in a general way by specifying their name and type. And handle all of them together, rather each one independently.

**Comment by kvoli** [comment]
> Maybe what we want are a few basic metric aggregator classes, one for bytes, one for count, maybe one for time, not sure. 

That would be nice. Were you thinking something similar to how we have generic metric collection at a store level:

https://github.com/cockroachdb/cockroach/blob/f2a722fa52804874138b29ecf7ca2f97502b5d00/pkg/kv/kvserver/metrics.go#L1278

The only reason `qps` (and preemptively `wps`) are gossipped at the moment, is for rebalancing decisions. The server maintains a `store_pool`, within which the the `StoreDescriptor` is being updated and recv/sent by each store. Range level statistics are not gossiped (qps per range), only store level.

Perhaps initially, we can **not** gossip `readKeys`,`readBytes` and`writeBytes`; possibly removing `writeKeys`, since it is unused. Instead, just collecting these within `ReplicaMetrics`, with the other statistics. This would still be aggregated at the store, for store metrics. The only difference is it wouldn't be used as an input for gossiping `store_pool` redundantly.

https://github.com/cockroachdb/cockroach/blob/f2a722fa52804874138b29ecf7ca2f97502b5d00/pkg/kv/kvserver/replica_metrics.go#L27-L31

Then, we should add another issue for store rebalancing signals separately since I think this issue wasn't initially focused on that topic.

**Comment by rail** [comment]
Manually synced with Jira
