### ISSUE TITLE
Surface index usage statistics in the CC/DB console: Index recommendations

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#72134]
We are capturing index usage statistics: #64740. This issue tracks building an experience around this view by adding index recommendations for unused indexes.

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3498%3A33376

Epic: CRDB-9075

Jira issue: CRDB-10963

**Comment by Azhng** [comment]
I think there is a very important questions we need to answer before jumping onto building this feature:

How are index recommendations being generated? Intuitively, there are a few options:
1. We can generate these recommendations at an ad-hoc basis each time we load the Database Page. This is expensive and wasteful, since these recommendations usually remain in place until there's a change in the index design or there's a change in the workload. This might be increasingly problematic as our index recommendation logic becomes more and more complex in the future.
2. We can generate these recommendations initially at an ad-hoc basis, then we cache the recommendation on a per-node basis to amortize the computation cost. The cache should be configured with a reasonable TTL (say, in the order of hours or days). 
3. We can proactively generate the recommendations in the background, this can happen at the
   a. per node basis using a stopper's [async task](https://github.com/cockroachdb/cockroach/blob/b09aacb92f7856206e7f80b30119ff08859dd7d7/pkg/util/stop/stopper.go#L354). 
   b. use the job system to implement a [daemon job](https://github.com/cockroachdb/cockroach/blob/3ea128d53acb53ab2d79cdbbc0770376f0697921/pkg/sql/sqlstats/persistedsqlstats/scheduled_job_monitor.go#L62) that runs in the background. This might require us to think about how to store the index recommendations? Should we create a new system table for this? Or should we just store the recommendations in the jobs table as the jobs payload. 

This will also lead us better design the SQL CLI's UX for using the index recommendation feature.

@lindseyjin feel free to share what's your thoughts on this

**Comment by THardy98** [comment]
> 

@Azhng Interesting thoughts and suggested options. I think having some idea of how much data we would working with would help inform our decision (average/median indices per db and per table, peak indices per db & per table, as well as # of cases where we should expect peak # of indices). 

Option 1 only sounds viable if we can really expect to not have to process that many indices (unlikely that it would be little enough to warrant per request computation, with future complexity in mind). Options 2 & 3 are fairly similar with just the difference in the level of persistence. I think the level of persistence should depend on how much data we should be expecting. If its enough to be concerned about the size of caching, option 3 sounds ideal, and if not, option 2 sounds simpler.
