### ISSUE TITLE
protos: move {roachpb->keys}.Key, {enginepb->?}.TxnMeta

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7220]
See https://reviewable.io/reviews/cockroachdb/cockroach/7166#-KKCGVOp61vL3EVaG_dT.

**Comment by petermattis** [comment]
@tschottdorf Do you recall what the desired cleanup was? I can't see the reviewable comment anymore.

**Comment by bdarnell** [comment]
The reviewable comments are loading for me. The issues are
- `TxnMeta` contains fields which should be of type `Key`, but can't because `enginepb` can't depend on `roachpb`
- `Key` should probably live in `keys` rather than `roachpb` (I think this is independent of the above dependency cycle; `enginepb` can't depend on `keys` either)
- `enginepb` is arguably the wrong place for `TxnMeta` anyway (I suggested `kvpb`, but I don't know why, and we didn't really like the dependency graph that produces. 

At this point I'd say that `TxnMeta` should  stay in `enginepb` - that's near the bottom of our dependency stack and I don't think we can move it anywhere except to a brand-new package. And I think moving the `Key` type to `keys` would also require moving a bunch of other types (`NodeID`, etc) to make it possible to flip the dependency relationship between `roachpb` and `keys`. Doesn't seem worth the trouble to me.

**Comment by petermattis** [comment]
> Doesn't seem worth the trouble to me.

Ditto.
