### ISSUE TITLE
kv: collapse adjacent span configs to reduce number of necessary splits

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#72389]
After #67679 + enabling the infrastructure by default, we'll get to a place where we'll split on every schema object boundary for all tenants (including, as before, the host tenant). That's mighty expensive and comes with a lot of overhead and is a scalability bottleneck for how many tenants we can pack into the same cluster. #70555 proposes some rudimentary guardrails, but on the KV side we can do better. The spanconfig.Store introduced in #70287 can be augmented to recognize that certain span config entries are adjacent to one another (S1.EndKey == S2.Key) and have the same configs. We expect the majority of span configs to be applicable here, given almost everything inherits from RANGE DEFAULT. When recognizing such an adjacency, we can avoid unconditionally splitting on that boundary. This should let us claw back a low range count with secondary tenants while still enabling multi-tenant zone configs.

Some neighboring issues: 
- #66063 (this same optimization can be applied to the host tenant)
- #65903 (might still be desirable to induce manual splits on table boundaries, for say, perf reasons)
- #65726 (orthogonal issue describing a scheme to reduce the total number of ranges in the system)

Jira issue: CRDB-11130

**Comment by irfansharif** [comment]
We should just do this for 22.1. It's not that difficult and would alleviate many of the concerns around thundering-splits-on-upgrades for multi-tenant clusters. I was originally thinking to coalesce adjacent ranges for tenant tables, leaving system tenant ranges split along table boundaries, but now that we can have >100k tables easily, perhaps gating it behind a cluster setting is better.

**Comment by irfansharif** [comment]
Prototyped this a while ago in #68491.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11130](https://cockroachlabs.atlassian.net/browse/CRDB-11130) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-72389`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
