### ISSUE TITLE
spanconfigjob: exempt requests to checkpoint from billing

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#72440]
**Is your feature request related to a problem? Please describe.**

With the background job for spanconfig reconciliation, we peridically get updates from the rangefeed for checkpoints and we write them to the job progress. That's bad because the user will see their usage go up and up even when they are not doing anything.

**Describe the solution you'd like**
We should exempt the checkpointing. We also should probably rate-limit the checkpointing.

**Additional context**
This relates to https://github.com/cockroachdb/cockroach/issues/70538. We need to make sure also that the span config reconciler does not keep the tenant pod from scaling down.

**Comment by irfansharif** [comment]
This led some valuable discussion [internally](https://cockroachlabs.slack.com/archives/C02HWA24541/p1641914580035100); instead of exempting them from billing/tenant cost control, we should perhaps track background RUs separately down in KV, and use that tracking to determine the rate of free RUs we disburse. But in the short term lets not do anything, certainly nothing for this specific job. Since it's work that's being done on behalf of a tenant (work that's costing us), there's no need to exempt it from billing.
