### ISSUE TITLE
roachperf: `kv95` and `kv0` regression around October 28th

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#72499]
Some versions of `kv95` and `kv0` saw a ~10% performance regression around October 28th, e.g. `kv95/enc=false/nodes=1/cpu=32`:

<a href="https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce"><img width="847" alt="Screenshot 2021-11-06 at 14 25 52" src="https://user-images.githubusercontent.com/644420/140611333-9b2a68b8-fd8e-41bd-8b93-bb0693f4ff2f.png"></a>

This is even more pronounced with 64KB payloads, e.g. `kv95/enc=false/nodes=3/cpu=32/size=64kb`:

<a href="https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsize%3D64kb&tab=gce"><img width="846" alt="Screenshot 2021-11-06 at 14 29 17" src="https://user-images.githubusercontent.com/644420/140611457-78abf2fb-8013-4bcd-b165-3c7ea2d71514.png"></a>

Admission control was enabled by default in #68535, which merged on October 28th, so that seems like a likely culprit. Running a couple of benchmarks to confirm.

**Comment by erikgrinaker** [comment]
Confirmed, comparing 320735422d (admission control disabled) with 7e5741bfc6 (admission control enabled) shows a ~20% ops/sec regression on `kv95/enc=false/nodes=3/cpu=32/size=64kb`:

```
name                                     old ops/sec  new ops/sec  delta
kv95/enc=false/nodes=3/cpu=32/size=64kb   11.0k ± 1%    8.6k ± 2%  -21.82%  (p=0.000 n=10+10)

name                                     old p50      new p50      delta
kv95/enc=false/nodes=3/cpu=32/size=64kb    2.80 ± 0%    1.50 ± 0%  -46.43%  (p=0.001 n=7+7)

name                                     old p95      new p95      delta
kv95/enc=false/nodes=3/cpu=32/size=64kb    35.7 ± 0%    36.7 ± 8%     ~     (p=0.137 n=8+10)

name                                     old p99      new p99      delta
kv95/enc=false/nodes=3/cpu=32/size=64kb     419 ± 0%     481 ± 2%  +14.67%  (p=0.000 n=8+9)
```

@sumeerbhola Is this regression expected and accepted with admission control?

**Comment by tbg** [comment]
cc @sumeerbhola

**Comment by sumeerbhola** [comment]
The regression should only be for cases where the LSM was degrading prior to admission control (admission control is not expected to reduce throughput if the bottleneck was CPU). If one clicks to get details of a run, and sees something like the following where the rate fluctuates, it is because for LSM overload the tokens get adjusted every 15s (unhealthy for 15s, so fewer tokens, resulting in transition to healthy, with unconstrained tokens, and then repeat). Admission control will only affect writes in this case but since we are issuing a sequence of reads and writes from the same workers, reducing write throughput also reduces read throughput.

<img width="980" alt="Screen Shot 2021-11-10 at 11 15 43 AM" src="https://user-images.githubusercontent.com/54990988/141150746-c111b99d-baf2-4c20-b83c-29a9da7053c5.png">

The corresponding no-admission roachtest has a higher mean rate, but note the decline in rate over time as the LSM becomes more and more unhealthy. It is not a sustainable rate, but since we only run for 10min we have overlooked this problem.

<img width="971" alt="Screen Shot 2021-11-10 at 11 20 05 AM" src="https://user-images.githubusercontent.com/54990988/141151593-47088fdb-3fa1-4289-81bc-64f18d5258bc.png">

You should see the same thing with the kv0 slowdowns.

But this is not the case with `kv95/enc=false/nodes=1/cpu=32`, and kv95 typically needs to have larger block sizes to cause write overload, which makes me suspicious that it could be a different root cause. We didn't have an "admission" variant for this test prior to the enabling of admission control, but we did have it for `kv95/enc=false/nodes=3/cpu=32`. See the screenshots below for the with and without admission for a randomly picked day (Oct 17) -- they are close:

<img width="952" alt="Screen Shot 2021-11-10 at 11 27 53 AM" src="https://user-images.githubusercontent.com/54990988/141152780-96c731f0-462d-4ede-8163-49fb9142db77.png">
<img width="945" alt="Screen Shot 2021-11-10 at 11 29 03 AM" src="https://user-images.githubusercontent.com/54990988/141152920-f96da116-9046-4271-b647-15a961bc8630.png">

**Comment by erikgrinaker** [comment]
>The corresponding no-admission roachtest has a higher mean rate, but note the decline in rate over time as the LSM becomes more and more unhealthy. It is not a sustainable rate, but since we only run for 10min we have overlooked this problem.

Interesting find. This seems fine then, since presumably running for another 10 minutes could have shown an overall improvement when admission control is enabled.

> But this is not the case with `kv95/enc=false/nodes=1/cpu=32`, and kv95 typically needs to have larger block sizes to cause write overload, which makes me suspicious that it could be a different root cause.

Interesting, I'll run another bisection and see if something turns up. Thanks!

**Comment by tbg** [comment]
In light of this, should we consider running these perf tests for longer than ten minutes (say thirty minutes)? This will completely shift the graphs we see (since they use total qps or something like that) but it may give us better data in the long run?

**Comment by erikgrinaker** [comment]
Yeah, 30 minutes makes sense. That probably shouldn't be the default though, since people will run these from the command-line as well, but for the nightlies that seems reasonable.

I'll submit a PR.

**Comment by tbg** [comment]
> Yeah, 30 minutes makes sense. That probably shouldn't be the default though, since people will run these from the command-line as well, but for the nightlies that seems reasonable. I'll submit a PR.

Thanks! You don't think that approach will be confusing to people trying to repro the numbers? I would've thought 30m is the default but it should be "easy" to lower that to 10 minutes when desired, perhaps through an env var (I know you love those!) or small code change.

**Comment by erikgrinaker** [comment]
OK, we can make 30 the default.

**Comment by erikgrinaker** [comment]
#72646

**Comment by erikgrinaker** [comment]
Bisected to bba05aabcb.

@ajwerner Looks like #71936 caused a ~10% hit on `kv95/enc=false/nodes=1/cpu=32` and other benchmarks.

**Comment by ajwerner** [comment]
wowza, ack, okay

**Comment by ajwerner** [comment]
I've been benchmarking and tuning this. Indeed #71936 caused a good bit of the pain. However, I don't think it was all 10%, I think it was closer to 7% and then another bit was cause by admission control. I went and tuned the catalog layer more in #72740 such that I think it makes up for both, but I see that the admission control code now shows up prominently in the mutex profile. 

<img width="2345" alt="Screen Shot 2021-11-15 at 9 59 33 AM" src="https://user-images.githubusercontent.com/1839234/141807607-d3e1baf1-1e1e-497b-9055-4b3d8d4bfc0d.png">

Turning off admission control seems to show about a 3-4% improvement in that benchmark. My guess is that we should be running that benchmark at a higher concurrency, at which point I suspect it’d show more. I've run the benchmark with admission control off and on with the patch in #72740 and the results are around `103893.2` vs `99933.6` for total throughput.

**Comment by sumeerbhola** [comment]
@ajwerner thanks for investigating.
What time interval was the mutex profile taken over? And do you know what the cpu utilization value was? It is very possible that contention is dropping cpu utilization peak by a few percent, given that the KV benchmark has tiny work units being subject to admission, similar to the observation in https://github.com/cockroachdb/cockroach/pull/65614#issue-899770131

**Comment by ajwerner** [comment]
> @ajwerner thanks for investigating. What time interval was the mutex profile taken over? And do you know what the cpu utilization value was? It is very possible that contention is dropping cpu utilization peak by a few percent, given that the KV benchmark has tiny work units being subject to admission, similar to the observation in [#65614 (comment)](https://github.com/cockroachdb/cockroach/pull/65614#issue-899770131)

I think the mutex profile covers time since the process started, though I could be wrong. It was probably around a minute into the benchmark run. I wasn't running it for that long. I'm setting it back up now.

----

Turning off admission control had only a very modest impact on CPU utilization. There was an initial throughput bump, but interestingly, it didn't last long. Tail latency went down and stayed down, but from a small number. I turned off admission control at 23:29. 

<img width="881" alt="Screen Shot 2021-11-15 at 6 31 03 PM" src="https://user-images.githubusercontent.com/1839234/141869349-d14a5871-012f-4f03-962c-c9c1bf54bb9c.png">
<img width="881" alt="Screen Shot 2021-11-15 at 6 30 53 PM" src="https://user-images.githubusercontent.com/1839234/141869352-ae9b47a7-3458-4957-9ab0-f5e679952ef6.png">
<img width="773" alt="Screen Shot 2021-11-15 at 6 36 07 PM" src="https://user-images.githubusercontent.com/1839234/141869451-de9fd7a0-845d-484d-bdf1-f3e6a0401f22.png">

**Comment by ajwerner** [comment]
The above were run at `--concurrency 96` with 1000 splits. 96 is probably too many. The original experiment was 64 and this one was at 64. There was a regime change I don't understand which happened with admission control after 23:41. Then another when I turned it off at 23:42.
<img width="773" alt="Screen Shot 2021-11-15 at 6 43 26 PM" src="https://user-images.githubusercontent.com/1839234/141870330-b756de8f-e776-4651-bf79-01bfdfe15da7.png">

<img width="773" alt="Screen Shot 2021-11-15 at 6 45 06 PM" src="https://user-images.githubusercontent.com/1839234/141870336-bef37ce8-acd6-4bc8-bf93-bfaf1ae065a9.png">

I then turned it back on around 23:47, and saw the throughput fall again. The CPU utilization fell a tad, from ~97.4% to ~96.2%. 
<img width="1098" alt="Screen Shot 2021-11-15 at 6 48 43 PM" src="https://user-images.githubusercontent.com/1839234/141870582-cce944a4-90e8-4fcb-9963-ebabb3fc8bd8.png">

**Comment by sumeerbhola** [comment]
With that low number of runnable goroutines, there should be no queueing in admission control (the admission control page in the db console should confirm that), so any affect would be the contention due to acquiring the mutexes `WorkQueue.admitMu`, `WorkQueue.mu`, `GrantCoordinator.mu`. The first one would be contended.

**Comment by tbg** [comment]
> I think the mutex profile covers time since the process started, though I could be wrong. It was probably around a minute into the benchmark run. I wasn't running it for that long. I'm setting it back up now.

Just a drive-by to mention that the mutex profile supports the `?seconds=5s` thing as well.

**Comment by sumeerbhola** [comment]
@ajwerner if admission control is not decreasing cpu utilization, and we are seeing a 3-4% decline in throughput, the admission control code should be showing up as significant in the cpu profile -- do you have one?

**Comment by ajwerner** [comment]
[profile_without.pb.gz](https://github.com/cockroachdb/cockroach/files/7548880/profile_without.pb.gz)
[profile_with.pb.gz](https://github.com/cockroachdb/cockroach/files/7548881/profile_with.pb.gz)

https://share.polarsignals.com/c7ecb30/ -- is with.

I have the binary if you want it to get line info. Looks like admission control is ~1% of CPU samples. It does look like some of the samples are in `_doSpin`/`procYield` on mutexes. 

<img width="1742" alt="Screen Shot 2021-11-16 at 1 27 47 PM" src="https://user-images.githubusercontent.com/1839234/142044085-12ff2ace-4deb-4189-9323-1b0dde175542.png">
