### ISSUE TITLE
MVCCScan works slow

### ISSUE THREAD

**Issue by awesomeleo** [cockroachdb/cockroach#725]
I find that the method MVCCScan in  mvcc.go works very slow.  When you call DBGet() in db.cc form the getInternal()  in rocksdb.go, the DBGet only needs 7us, but the getInternal() needs 28us to return.
I find that the calling from go lang to c lang is slow.
Could i get more than one key from rocksdb at one time  to reduce the communication from go lang to c lang?

**Comment by petermattis** [comment]
Do you have a benchmark which shows this to be a problem? The existing MVCC benchmarks in (which happen to live in `rocksdb_test.go`) do not point to the go<->c crossing to be a significant bottleneck.

Since we control the go<->c crossing we could easily add an API which retrieved more than one key at a time. Using this API from the MVCC code might be tricky. And my guess is that the primary overhead is in performing the copy of key and value bytes from C into Go (i.e. see `cSliceToGoBytes`).

**Comment by tamird** [comment]
Closing as inactive.
