### ISSUE TITLE
backupccl: add support for GCP KMS to encrypt backups

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#72571]
Today we support encrypting our backups using the AWS KMS. We should expand this to support to allow for GCP KMS encryption of backups as well. 

This is part of an ongoing goal [to support all major KMS providers](https://github.com/cockroachdb/cockroach/issues/79890).

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11215](https://cockroachlabs.atlassian.net/browse/CRDB-11215) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-72571`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
