### ISSUE TITLE
opt: add support for "invisible" indexes

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#72576]
The feature request is to add a way to create an index that is never used in queries unless specifically selected with a hint. This would be useful to reproduce issues around index corruption in production environments - we don't want the index affecting production queries but we want to try creating it and checking for corruption.

Epic: CRDB-11155

Jira issue: CRDB-11218

**Comment by glennfawcett** [comment]
It would be great if an index could be made "invisible" to a given fraction of the queries, so that one could induce just a partial outage instead of a full blown outage when experimenting. In other words, instead of a boolean "invisible" flag, one could set a float "invisible" flag between 0.0 and 1.0 (corresponding to 0% invisible and 100% invisible, allowing for all the shades in between)
