### ISSUE TITLE
perf: the more bytes data, the slower cockroach cluster

### ISSUE THREAD

**Issue by bronze1man** [cockroachdb/cockroach#7280]
I am using the same cluster in https://github.com/cockroachdb/cockroach/issues/7275.
I am using the key/value interface from the https://github.com/cockroachdb/cockroach/tree/master/client with golang.

I setup a 5 nodes cluster with 4GPU 4GB memory 40GB ssd disk.
In the test , I write data with 12 length key and 14 length value with 100 threads from another 4GPU 4GB memory machine.
When the data set is under 1GB, the qps is about 2500.
When the data set is under 5GB, the qps is about 2000.
When the data set is under 17GB, the qps is about 800.
When the data set is under 17GB the qps of sql interface is about 100.

**Comment by bronze1man** [comment]
main.go
```
package main

import (
	"github.com/bronze1man/kmg/kmgTest"
	"time"
	"fmt"
	"github.com/bronze1man/kmg/kmgTask"
	"sync"
	"github.com/bronze1man/kmg/kmgRand"
)

func main() {
	fmt.Println("start main")
	var s time.Time
	MustSet("1","2")
	kmgTest.Equal(MustGet("1"),"2")
	s=time.Now()
	tasker:=kmgTask.NewLimitThreadTaskManager(100)
	num:=0
	numLocker:=sync.Mutex{}
	totalTime:=time.Duration(0)
	totalTimeLocker:=sync.Mutex{}
	go func(){
		lastNum:=0
		for {
			time.Sleep(time.Second)
			numLocker.Lock()
			thisNum:=num
			numLocker.Unlock()
			totalTimeLocker.Lock()
			thisTime:=totalTime
			totalTime = 0
			totalTimeLocker.Unlock()
			qps:=thisNum-lastNum
			avgTime:=time.Duration(-1)
			if qps>0{
				avgTime=thisTime/time.Duration(thisNum-lastNum)
			}
			fmt.Println("currentNum",time.Since(s),thisNum-lastNum,thisNum,avgTime)
			lastNum = thisNum

		}
	}()

	for {
		numLocker.Lock()
		num++
		numLocker.Unlock()
		tasker.AddFunc(func(){
			data:=kmgRand.MustCryptoRandToHex(12)
			s:=time.Now()
			MustSet(data,data+"_2")
			dur:=time.Since(s)
			totalTimeLocker.Lock()
			totalTime+=dur
			totalTimeLocker.Unlock()
		})
	}
	tasker.Close()
}
```

kv.go
```
package main

import (
	"sync"
	"github.com/cockroachdb/cockroach/client"
	"github.com/cockroachdb/cockroach/rpc"
	"github.com/cockroachdb/cockroach/util/stop"
	"github.com/cockroachdb/cockroach/base"
	"github.com/cockroachdb/cockroach/security"
	"github.com/cockroachdb/cockroach/roachpb"
	"golang.org/x/net/context"
	"github.com/bronze1man/kmg/kmgRand"
	"github.com/bronze1man/kmg/kmgLog"
)

var gDb *client.DB
var gDbOnce sync.Once

func kvInit(){
	gDbOnce.Do(func(){
		stopper := stop.NewStopper()
		context := &base.Context{
			User:       security.RootUser,
			Insecure:   true,
		}
		rpcCtx:=rpc.NewContext(context, nil, stopper)
		ms:=&mulitSender{}
		for _,addr:=range []string{
			"xxx:26257",
			"xxx:26257",
		}{
			sender, err := client.NewSender(rpcCtx, addr)
			if err != nil {
				stopper.Stop()
				panic(err)
			}
			ms.addSender(sender)
		}

		gDb = client.NewDB(ms)
	})
}

type mulitSender struct{
	senderList []client.Sender
}

func (s *mulitSender) addSender(sender client.Sender){
	s.senderList = append(s.senderList,sender)
}

func (s *mulitSender) Send(ctx context.Context, req roachpb.BatchRequest) (*roachpb.BatchResponse, *roachpb.Error){
	l:=len(s.senderList)
	sender:=s.senderList[kmgRand.Intn(l)]
	return sender.Send(ctx,req)
}

func MustGet(key string) string{
	kvInit()
	r,err:=gDb.Get(key)
	if err!=nil{
		panic(err)
	}
	if r.Value==nil{
		return ""
	}
	return string(r.ValueBytes())
}

func MustSet(key string,value string) {
	kvInit()
	var err error
	for i:=0;i<3;i++{
		err:=gDb.Put(key,value)
		if err!=nil{
			kmgLog.Log("error","[MustSet]",err.Error())
			continue
		}
		return
	}
	if err!=nil{
		panic(err)
	}
}
```

**Comment by bronze1man** [comment]
The public version of github.com/bronze1man/kmg may have some bugs, you can fix it or write your own version of that function.

**Comment by petermattis** [comment]
Thanks, @bronze1man. I've seen performance degrade over time, but never to the degree that you're reporting. I'll attempt to duplicate that degradation in the next day or so.

**Comment by petermattis** [comment]
Tweaking @bronze1man's tool to remove the `kmg*` dependencies, I do so a very gradual performance degradation over time. I'm testing against a single-node cluster. Performance started out at ~6500 ops/sec and has declined over the course of 2 hours to ~4000 ops/sec. Total data size at this point is 1.4GB with 33M KV pairs. 

Memory usage grew linearly up to ~4GB and then stabilized: 
<img width="298" alt="screen shot 2016-06-17 at 1 06 54 pm" src="https://cloud.githubusercontent.com/assets/6201335/16158721/893f78b6-348c-11e6-9361-af8bc105e708.png">

Cpu usage steadily increased up until right around where memory stabilized and is now experience a very gradual decline: 
<img width="307" alt="screen shot 2016-06-17 at 1 06 44 pm" src="https://cloud.githubusercontent.com/assets/6201335/16158733/a2c7a7c2-348c-11e6-948f-7273df2780e9.png">

More interestingly, block cache usage has been steadily climbing. Since the ops/sec is gradually declining, we must be performing more block cache accesses per operation. 
<img width="288" alt="screen shot 2016-06-17 at 1 07 02 pm" src="https://cloud.githubusercontent.com/assets/6201335/16158747/be9d3db8-348c-11e6-8195-c30a95d7f28d.png">

Similarly, we see a steady increase in bloom filter accesses: 
<img width="287" alt="screen shot 2016-06-17 at 1 07 10 pm" src="https://cloud.githubusercontent.com/assets/6201335/16158760/cb87b314-348c-11e6-83d2-9b801a16c815.png">

My suspicion is that we're seeing more sstable levels which is causing an increase in the number of sstables touched per operation. I'm going to write a small utility command that can compact all of the sstables as an offline process and see if this restores performance to a good state. If it does, there is likely RocksDB tuning that can be done to alleviate this problem.

**Comment by petermattis** [comment]
After running the new `cockroach debug compact` command, performance reset to a higher level. I'm now seeing ~6000 ops/sec. Looks like I'll have to spend some quality time with the RocksDB tunables.

Thanks again for the report, @bronze1man. I'm not sure what your intention of this load test was, but note that you could get much better throughput by batching operations. I'd suggest batching 100-1000 ops per batch.

**Comment by petermattis** [comment]
Playing around with RocksDB compaction options has allowed performance to hover in the 4500-5000 ops/sec range after 3 hours. I'm really not sure what I'm doing, though. I think I'll reach out to the RocksDB folks for advice.

Also, we should have a metric for the number of RocksDB levels containing sstables and the number of level-0 sstables. I believe the level-0 sstables need to all be searched because, unlike other levels, the keys in those sstables can overlap. For good performance we want both a minimum number of total levels and minimum number of level-0 sstables, but that needs to be balanced against the write amplification caused by performing more compactions.

**Comment by petermattis** [comment]
Btw, the biggest slowdowns seem to occur when there are a lot (20+) of level-0 sstables. We allow multiple background compactions to occur concurrently, so I'm not sure why this is happening.

**Comment by petermattis** [comment]
@cuongdo Assigning because this is likely related to the performance degradation we see with the `photos` app.  Also see https://github.com/petermattis/cockroach/tree/pmattis/rocksdb-tuning where I started experimenting with various RocksDB tunables. That branch also contains @bronze1man's tool (https://github.com/petermattis/cockroach/blob/pmattis/rocksdb-tuning/tester/main.go) stripped of external dependencies.

**Comment by bronze1man** [comment]
Thanks. @petermattis 
I think the qps is not stable,when the data set is bigger than 1.5*total memory.
I used to see 1500 qps When the data set is under 17GB.

Your testing machine should be better than mine.

**Comment by bronze1man** [comment]
The cockroachdb likes to crash because of out of memory.
I do not test the cockroachdb and use mysql right now.

**Comment by cuongdo** [comment]
@bronze1man: Sorry to hear that but thanks for providing the information that you have. I'm starting to look at it.

**Comment by cuongdo** [comment]
From looking at the `--vmodule=rocksdb=3" logs, it looks like we're always compacting. Compactions happen back-to-back and take tens of seconds at a time.

Here's part of the log output:

```
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(cnt)  KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0       2.23   1.0      0.0     0.0      0.0       0.1      0.1       0.0   0.0      0.0      9.8         9        77    0.117          0       0      0
  L1      7/0     415.76   0.8     15.9     0.1     15.8      15.8      0.0       0.0 182.9     15.9     15.8      1022        37   27.623          0    526M   580K
  L2     13/0    2036.59   0.5      0.7     0.1      0.7       0.7      0.0       0.0  11.8     14.8     13.9        51         1   50.531          0     31M  3134K
 Sum     22/0    2454.59   0.0     16.6     0.1     16.4      16.6      0.1       0.0 192.2     15.7     15.7      1082       115    9.405          0    558M  3715K
 Int      0/0       0.00   0.0      8.2     0.1      8.1       8.1      0.1       0.0 191.8     16.3     16.3       512        57    8.981          0    267M  3415K
```

`Avg(sec)` shows the average time it takes to compact. Each compaction is writing 10-15 MB/s. While the stats don't show any stalls, that IO load could be affecting things. Also, write amplification is *massive*.

Still investigating, but wanted to share results so far.

**Comment by cuongdo** [comment]
I was able to double QPS with this short diff:

```
diff --git a/storage/engine/rocksdb/db.cc b/storage/engine/rocksdb/db.cc
index c1f32f3..4f7337f 100644
--- a/storage/engine/rocksdb/db.cc
+++ b/storage/engine/rocksdb/db.cc
@@ -1371,6 +1371,7 @@ DBStatus DBOpen(DBEngine **db, DBSlice dir, DBOptions db_opts) {
   options.prefix_extractor.reset(new DBPrefixExtractor);
   options.statistics = rocksdb::CreateDBStatistics();
   options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options));
+  options.compaction_style = rocksdb::kCompactionStyleUniversal;

   // File size settings: TODO(marc): investigate and determine better long-term settings:
   // https://github.com/cockroachdb/cockroach/issues/5852
```

That said, I don't understand this well enough (yet) to understand the ramifications. So, I'll dig further.

**Comment by petermattis** [comment]
Reading some of the RocksDB tuning suggestions I discovered that they recommend that the L0 and L1 sizes should be the same. L0 size can be estimated as `write_buffer_size * min_write_buffer_number_to_merge * level0_file_num_compaction_trigger` which translates to `4MB * 2 * 2 == 16 MB`. We have L1 configured as `options.max_bytes_for_level_base = 512 << 20`. Changing `max_bytes_for_level_base` to `16 MB` seems to smooth out performance.

**Comment by cuongdo** [comment]
I've rerun the tests with the fixes from #7532 and #7562. There is somewhat of a slowdown after 12 hours of testing, but nowhere near what it was like before. Average time per op was going from 40 ms to ~150 ms. Now, it's at ~52 ms.

We need a regularly run test for this scenario. I'll file an issue for that.

**Comment by petermattis** [comment]
@cuongdo Yeah, I was thinking we should have a daily `block_writer` and `photos` benchmark. I'd like to run both of those load generators for a couple of hours each, capture the average ops/sec and graph that over time.

**Comment by cuongdo** [comment]
We can have that too. I was thinking that we could easily add a flag to each that causes them to exit after a certain number of operations have been performed. This serves a couple of purposes:

1. It makes performance degradation over time really obvious on teamcity graphs.
2. It makes *really* bad performance degradation a hard test fail, because we'll exceed the test timeout.

**Comment by petermattis** [comment]
@cuongdo `block_writer` now has two such flags: `--max-blocks` and `--duration`. Would be good to standardize all of the load generators to take such flags and to standardize their output.
