### ISSUE TITLE
ui: graphs don't load on 240 node cluster

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#72986]
This is identical to https://github.com/cockroachdb/cockroach/issues/24018, only at a larger scale. We resolved that issue by dropping down the number of query workers by a factor of 8. This increased the per timeseries query memory limit from 1MiB to 8MiB. It should come as no surprise then that we once again see this issue on 240 node clusters (given `30*8=240`).

@mrtracy laid out a few options on that issue https://github.com/cockroachdb/cockroach/issues/24018#issuecomment-374307869. I think we should explore the first one - "Raise the overall limit (currently 64MiB)". Specifically, I think it would make sense to scale this server-wide limit by the available memory on the machine. On a machine with 100s of GiB of available memory (e.g. `n2-standard-48` machines have 192 GiB of memory), 64MiB isn't much. Or instead of a static limit, we should hook this memory budget into the `--max-sql-memory` budget.

cc. @piyush-singh

**Comment by thtruo** [comment]
cc @nkodali assigned to our team label for triage and discussion in next Mondays' backlog grooming session

**Comment by thtruo** [comment]
Confirming that this is in our December milestone

**Comment by dhartunian** [comment]
(sorry repeat comment since I accidentally made it in Jira)

@nvanbenschoten  have you considered running Prometheus alongside these clusters instead of using DB Console for timeseries metrics? That could alleviate this directly. I do want to tackle this issue but Prometheus will likely work for you immediately.

We have a demo configuration with matching dashboards from DB Console under `/monitoring/demo`.

----

I am still going ahead with a proposed solution but just wanted to throw out the workaround above. Some large customers will hit this limit at some point soonish so I definitely want to address it directly.

I like the idea of using an existing memory limit like system-wide or `--max-sql-memory`. I'll put up a quick prototype for review and see if that will be adequate.

**Comment by nvanbenschoten** [comment]
> @nvanbenschoten have you considered running Prometheus alongside these clusters instead of using DB Console for timeseries metrics? That could alleviate this directly. I do want to tackle this issue but Prometheus will likely work for you immediately.

This is a good point. I was planning to run with a patched version of CRDB with a higher `queryMemoryMax` value if this issue wasn't fixed in time, but you're right that Prometheus would also work to get around this issue for the time being.
