### ISSUE TITLE
cdc: test changefeeds in serverless environment to better understand scalability limitations

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73274]
We know there are limitations to the current changefeed serverless deployment due to lack of distsql distributing work amongst nodes. We should run tests to better understand these limits and communicate that to users.

Epic CRDB-8671

Jira issue: CRDB-11507

**Comment by ajstorm** [comment]
@amruss In a world in which we had DistSQL working between tenant pods, would this be an issue?  We're targeting DistSQL support for bulk ops in 22.1, so perhaps this issue could go away?

If we had DistSQL, is there work planned or already completed which would allow changefeeds to scale up and down as new pods are started or shutdown?  Is there anything on the changefeed side that might prevent a pod from shutting down (like maybe a prolonged catchup ¯\_(ツ)_/¯?).

**Comment by miretskiy** [comment]
In case of core changefeeds, in order to use DistSQL effectively, we would need to not only take the query load into account (i.e. higher QPS -> more pods), but also data size itself, so that we can effectively distribute the load during initial scan.

I also feel that we would probably need to do more work to have changefeeds react and adjust to changing modes of operation: i.e. initial scan cares about scanning all data efficiently (so, more pods based on data size), while rangefeed are QPS oriented.

Enterprise changefeeds also start up a job -- which is not ideal in a case you have a tenant that has very low usage.  In that case, we would prevent a pod from shutting down, even if the tenant receives 0 qps.  We might have to implement some sort of "power save" mode where jobs system can be told to try to put some jobs to sleep if possible, and resume when real traffic comes in.

**Comment by ajstorm** [comment]
Thanks for that insight @miretskiy.  Is this last part currently being tracked anywhere?  Or is this issue the tracking location?

>Enterprise changefeeds also start up a job -- which is not ideal in a case you have a tenant that has very low usage. In that case, we would prevent a pod from shutting down, even if the tenant receives 0 qps. We might have to implement some sort of "power save" mode where jobs system can be told to try to put some jobs to sleep if possible, and resume when real traffic comes in.

I don't think we'd be able to enable enterprise changefeeds in MT environments until this "power save" is implemented.

cc @andy-kimball

**Comment by andy-kimball** [comment]
We can exclude certain jobs from the criteria for when a tenant can be suspended. Does that help? In the past, we've talked about adding a DB metric along the lines of `count_of_running_jobs_that_should_prevent_tenant_suspension`. The CDC changefeed job could add itself to that metric, but then remove itself once it had nothing left to do (perhaps after a delay of a couple minutes). Or something...

**Comment by miretskiy** [comment]
I think we would need to do something wrt to protectd timestamp management; I imagine that asking to suspect would involve trying to checkpoint job progress; lay PTS records, etc; on resumption we need to be able to "fast" forward that timestamp so that we can resume rangefeeds...

**Comment by miretskiy** [comment]
> One of my concerns is that even after traffic has dropped to zero, that the CDC job might still be churning away on data that was previously added (say there was a huge burst of traffic before it dropped to zero). It's got to be up to the CDC job to decide when it's "done" and it's safe to suspend.

That's exactly right.  I'm thinking we need to help from jobs system (and serverless).  We need serverless to give jobs sytem a signal that if possible, tenant should be put in "power save" mode.  THe jobs system can provide API for job implementations to add handling for this request.  If the job doesn't implement this -- then it remains running; otherwise, it attempts to do what's necessary (checkpoint, wait for completion, pause itself with special flag indicating that the job ought to be resumed when pods come online).

**Comment by andy-kimball** [comment]
Actually, it needs to be the other way around - a job needs to declare when they have no more work to do and they could be suspended. For the CDC job, that should be based on a simple heuristic like, "I haven't had any work to do for X minutes".

**Comment by miretskiy** [comment]
CDC always has work todo -- it always receives closed timestamp updates and it updates its checkpoints.   Even if CDC job has "real" work todo it can still be shut down if tenant is not receiving live traffic.  For example, if changefeed is doing a backfill due to schema change, this operation can easily be aborted and restarted (after checkpoint).

**Comment by andy-kimball** [comment]
If there's a backfill going on, we don't want to suspend the tenant. Getting closed timestamp updates and updating checkpoints is just busy work once there are no more database changes to report. This is why it needs to be CDC that says, "I've got no more real work to do, I'm ready to be suspended" - it's the only component that has such specific knowledge.
