### ISSUE TITLE
bazel: provide method for constructing `distdir` for bazel build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#73316]
[ref](https://docs.bazel.build/versions/main/guide.html#distribution-files-directories)

the `@additional_distfiles//:archives.tar` rule can be consulted as a reference.

Presumably this rule would be auto-generated. We would consult the URL's and SHA's in `WORKSPACE`, `DEPS.bzl`, and other sources (e.g. toolchains in `build/toolchains`) to construct a list of "all" archives needed to build, and then auto-generate the rule in that way. Also provide documentation on how to build the `distdir`, how to specify `--distdir` on the command-line for building in an airgapped environment, etc.

Epic CRDB-8306

Jira issue: CRDB-11538

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11538](https://cockroachlabs.atlassian.net/browse/CRDB-11538) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73316`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
