### ISSUE TITLE
bazel: make sure that no downloads from untrusted sources are required for bazel build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#73314]
Follow-up to #66163. We've mirrored all the "obvious" stuff, but there might be some stuff that I missed. Easiest way to do this would be to run the build behind a reverse proxy and check for any downloads from sources that aren't our Github repos or GCP buckets.

Epic CRDB-8306

Jira issue: CRDB-11536

**Comment by rickystewart** [comment]
Since #80512 we are now keeping up-to-date in-tree a list of all the files that must be downloaded to build `cockroach`.  Due to our mirroring, every artifact is in either the `cockroach-godeps` or the `public-bazel-artifacts` bucket in GCS, which are indeed sources that we own, and I've checked the offline build works with only these files in the `distdir`.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11536](https://cockroachlabs.atlassian.net/browse/CRDB-11536) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73314`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
