### ISSUE TITLE
sql: placeholders with single-member tuples

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#7331]
`SELECT a FROM d.t WHERE (a) > ($1)`

fails to prepare with:

`pq: could not determine data type of placeholder $1`

Other queries that don't work:

```
SELECT a FROM d.t WHERE a > ($1);
```

Things that do work:

```
SELECT a FROM d.t WHERE (a) > $1;
SELECT a FROM d.t WHERE a > $1;
```

**Comment by mjibson** [comment]
@nvanbenschoten: tagging you because you might have better insight than me about this. If you don't have time assign it back to me.

**Comment by nvanbenschoten** [comment]
The issue that we're seeing here is that the type checker is not recognizing `($1)` as a placeholder because it sees a non-placeholder expression and therefore concludes that that expression can be type checked in isolation. The same problem would be seen with the query `SELECT a FROM d.t WHERE a > (((($1))));`. The two solutions I see are either to add a little bit to our pre-type checking expression folding and unwrap placeholders from `ParenExpr`s like we [do with `Constants`](https://github.com/cockroachdb/cockroach/blob/4fa7a9547aae6249743c043c9a2fd3144264bab3/sql/parser/constant.go#L393), or to improve [`isUnresolvedPlaceholder`](https://github.com/cockroachdb/cockroach/blob/4a3470187c2fb4c14886249bea3516cf6c0d8cd3/sql/parser/placeholders.go#L111) to unwrap nested parentheses while searching if necessary. The first change is probably easier, but I'd hate to add in another visitor or to expand the meaning of `constantFolderVisitor`. I'll make both changes and see which one fits better. 

(interesting note, something like this would have been impossible to address cleanly with our old, strictly bottom-up type system)

**Comment by mjibson** [comment]
Why aren't `(a)` and `($1)` getting typed as 1-element tuples?

**Comment by petermattis** [comment]
I think `(a)` is a parenthesized expression. `ROW (a)` is a 1-element tuple.

**Comment by mjibson** [comment]
Ahh yes. https://www.cockroachlabs.com/docs/sql-grammar.html#explicit_row
