### ISSUE TITLE
cli: Add input testing for the sql interactive prompt.

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7334]
Following up on #7328: there is currently no test of the sql interactive prompt and how the underlying readline library reacts to input. This should change.

Requested by @tamird.

**Comment by knz** [comment]
To test:
- recalling history
- recalling history across DB disconnects / statement errors
- checking what happens on EOF
- checking what happens on signals

**Comment by mjibson** [comment]
Also, assuming my PR that lexes in the sql subcommand is merged:

- multi-line string literals with `\?` and `;` taking up an entire line
- changing syntax (modern, traditional) mid session: verify that the lexer correctly picks up the new syntax mode. Also need to make sure a `SET syntax = whatever` in the middle of a single line with multiple statements is picked up. That's harder because the SET tag is obscured in that case.
