### ISSUE TITLE
changefeedccl: memory accounting for changefeed.backfill.concurrent_scan_requests

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73619]
There are memory accounting gaps for memory used during concurrent scan requests. 16mb * limit is currently unaccounted for. This leaves us open to allowing customers to OOM their cluster. 

Currently we give a configuration using changefeed.backfill.concurrent_scan_requests with no limits. We should add an upper bound for what you can set this value to + add memory accounting (we should fail if we can't allocate the memory)

After conversation, we think the default max should be around 64 

Jira issue: CRDB-11669

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11669](https://cockroachlabs.atlassian.net/browse/CRDB-11669) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73619`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by miretskiy** [comment]
This issue would be particularly terrible when running many (100s, 1000s) of changefeeds.

**Comment by miretskiy** [comment]
Moving this back to triage to make sure we revisit it -- I'm worried that some of the
escalations (OOMs) in situation when we have many changefeeds  might have had this
issue as a culprit.

**Comment by miretskiy** [comment]
Resolved by #97020
