### ISSUE TITLE
kvserver: store with high read amplification should not be a target of rebalancing

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#73714]
Looking at a 6 hour interval of a node with a single store that had consistently high read amplification of > 1600, there are 3055 log entries containing "applying snapshot of type INITIAL".
The allocator should not add replicas to a store that is unhealthy in this manner.

There are also 11804 "removing replica" log statements, so probably the allocator has some signal it is using to shed load.

(the Cockroach Labs internal link for these logs https://upload.cockroachlabs.com/receive/?thread=J0LX-VAFS&packageCode=3V8ZJ2nVEB0zprhPefmADBbjcHJ1YEnIerx9xAyeqdE#keyCode=q1HsA9iW08Ftw0eGrEXYMckv635vIQbmw8s-Y5i3FxI)

cc: @aayushshah15 

Jira issue: CRDB-11703

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11703](https://cockroachlabs.atlassian.net/browse/CRDB-11703) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73714`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and updated
