### ISSUE TITLE
kvserver: improve the accounting of `AddSSTableRequest`s' QPS 

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#73731]
Currently, our QPS accounting is a little broken because we only [record the count of incoming `BatchRequest`s into a replica](https://github.com/cockroachdb/cockroach/issues/50620) (not the actual count of requests in those batches). One of the consequences of this is that `AddSSTTableRequest`s only count as 1 QPS even though their actual load on the receiving hardware is orders of magnitude higher than that. This means that during an import, without any background traffic in the cluster, CRDB's `StoreRebalancer` (which is responsible for QPS based lease and replica rebalancing) doesn't even kick in (because it doesn't try resolving tiny QPS differences between stores). We've seen at least one support case where this all lead to severe load imbalance among the nodes in a customer's cluster. 

One idea by @nvanbenschoten was to consider `AddSSTableRequests` to be something like 1000 requests when recording them in the leaseholder replica's `leaseholderStats`.

This is likely a small change but we'd want to run a few experiments to validate it (same as https://github.com/cockroachdb/cockroach/issues/50620).

cc. @cockroachdb/kv-notifications

**Comment by erikgrinaker** [comment]
Following #72085, once all callers are migrated to use `WriteAtRequestTimestamp`, we'll know during evaluation how many keys the SST contains, and could propagate this back into the stats. As a fallback, we may want a linear cost based on the SST byte size, since they can vary quite a bit.

**Comment by tbg** [comment]
> One idea by @nvanbenschoten was to consider AddSSTableRequests to be something like 1000 requests when recording them in the leaseholder replica's leaseholderStats.

Can't AddSSTableRequests contain the number of keys the SST includes (and perhaps the total length of the keys and/or bytes in case we want to track something based on that later)? That doesn't seem difficult to achieve and then we can properly solve the problem.

**Comment by erikgrinaker** [comment]
>Can't AddSSTableRequests contain the number of keys the SST includes (and perhaps the total length of the keys and/or bytes in case we want to track something based on that later)? That doesn't seem difficult to achieve and then we can properly solve the problem.

Actually, I think they already do most of the time:
 https://github.com/cockroachdb/cockroach/blob/0c8383cbc91da37846584e08eff5060e0e14cdfa/pkg/roachpb/api.proto#L1681-L1685

Notably, this is always provided during bulk ingestion:

https://github.com/cockroachdb/cockroach/blob/2318073a283b8371b7555c519afdb1fbdc6bf519/pkg/kv/bulk/sst_batcher.go#L471

**Comment by erikgrinaker** [comment]
> `AddSSTTableRequest`s only count as 1 QPS

I was under the impression that we recorded reads (QPS) and writes (WPS) separately. `AddSSTable` requests are already accounted for in WPS:

https://github.com/cockroachdb/cockroach/blob/36f61dc34d72257a45a3e775447ba8484c6434da/pkg/kv/kvserver/replica_application_state_machine.go#L645

The proposal here seems to be to also include `AddSSTable` writes in QPS. Wouldn't it be better to change the store rebalancer to take WPS into account for rebalancing decisions too, separately from QPS, instead of including all writes in QPS? Nodes can generally handle much larger amounts of reads than writes, and so even if a replica is seeing a high write volume, it may not get split/rebalanced because it's drowned out by an even higher read volume -- so it seems to make sense to keep these signals separate.

**Comment by erikgrinaker** [comment]
I did a proof of concept of the initial proposal in https://github.com/erikgrinaker/cockroach/tree/sst-qps, where both the number of requests in a batch and also the number of keys in an SST count towards QPS. Note that index backfills do not include MVCC stats by default because they do not hit this branch:

https://github.com/cockroachdb/cockroach/blob/2cce39c20e12e65334dd6176b43fcefd298d1f11/pkg/kv/bulk/sst_batcher.go#L208-L210

This was a marked improvement, where load did get distributed across other nodes as well, although this took a fairly long time to converge (>30 minutes), and even after that the original three nodes were still running about twice as hot than the others. See this [internal Slack thread](https://cockroachlabs.slack.com/archives/C02QJDE1YLT/p1639742842141600) for results and graphs. @aayushshah15 points out that this may also be due to fallout from #65379.

Either way, this approach seems viable, but will need additional testing and tuning. For posterity, this was tested as follows:

```
export GCE_PROJECT=cockroach-ephemeral
cluster=grinaker-index
roachprod create ${cluster} --nodes=10 --gce-machine-type=n2-standard-4 --gce-zones=europe-west1-c --local-ssd=false --gce-pd-volume-size=500 --lifetime=168h
roachprod stage ${cluster} cockroach
roachprod start ${cluster} --racks=10

CREATE TABLE trade (t_id INT8 NOT NULL PRIMARY KEY, t_dts TIMESTAMP NOT NULL, t_st_id VARCHAR(4) NOT NULL, t_tt_id VARCHAR(3) NOT NULL, t_is_cash BOOL NOT NULL, t_s_symb VARCHAR(15) NOT NULL, t_qty INT4 NOT NULL CHECK (t_qty > 0), t_bid_price DECIMAL(8,2) NOT NULL CHECK (t_bid_price > 0), t_ca_id INT8 NOT NULL, t_exec_name VARCHAR(49) NOT NULL, t_trade_price DECIMAL(8,2), t_chrg DECIMAL(10,2) NOT NULL CHECK (t_chrg >= 0), t_comm DECIMAL(10,2) NOT NULL CHECK (t_comm >= 0), t_tax DECIMAL(10,2) NOT NULL CHECK (t_tax  >= 0), t_lifo BOOL NOT NULL, FAMILY (t_id), FAMILY (t_comm, t_dts, t_st_id, t_trade_price, t_exec_name, t_tt_id, t_is_cash, t_s_symb, t_qty, t_bid_price, t_ca_id, t_chrg, t_lifo), FAMILY (t_tax));
IMPORT INTO trade CSV DATA ('gs://cockroach-fixtures/tpce-csv/customers=500000/*/Trade.txt?AUTH=implicit') WITH delimiter = '|', DETACHED;
CREATE INDEX ON trade (t_ca_id, t_dts DESC) STORING (t_st_id, t_tt_id, t_is_cash, t_s_symb, t_qty, t_bid_price, t_exec_name, t_trade_price, t_chrg);
```
