### ISSUE TITLE
jobs: gate job execution on cluster version

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#73808]
**Is your feature request related to a problem? Please describe.**
This is a rather lengthy but important issue from the perspective of correctness. Cockroach's online upgrades are useful, but come with a requirement that developers reason about mixed version states. Cockroach also has an internal, fault-tolerant job subsystem. These jobs, currently, do not provide any mechanism to understand the version in which they were created or any way to enforce that they do not run across multiple versions. 

Mixed-version testing is classically an area for bugs. Most jobs terminate before too too long (ideally less than days). Changefeeds are an exception. In general, we don't expect to have jobs which run across multiple major versions because we generally don't expect major version upgrades to be done that rapidly. It's also worth noting that the 20.1 upgrade had some rather major caveats around schema change jobs.

As we move to introduce the declarative schema changer, we'll want to make stronger claims about versioning and jobs. At this point, we haven't really had major problems with this (or we haven't discovered them). We do know that restores of old backups cause some pain, but that's a somewhat different problem. 

Lastly, we now have a framework for migrations which take a long time. Waiting for jobs might be just that sort of migration. 

**Describe the solution you'd like**
I'd like to version job details and make sure, when upgrading, that no running job is too old. The invariant I'm proposing should be seen as a straw-man. Happy to modify it in favor of stronger or weaker invariants.

#### Invariant 

* No job will execute on a cluster without a version field in its payload which is below the `BinaryMinSupportedVersion` for a binary which has as its `BinaryExecutableVersion` the current active version. If the cluster is in a mixed version state, the job running versions may, at a minimum, be equal to the `BinaryMinSupportedVersion` of the preceding major release.
  * To clarify, if the current cluster is running `22.2` nodes but the active version is `22.1` we may be running jobs as old as `21.2`. When the cluster is in an intermediate state, such as `22.1-10`, the jobs with version `21.2` may still proceed. However, by the time the version `22.2` becomes active, the oldest allowable job version for a running job is `22.1`.
  
#### Implementation  
  
1) Augment the payload of a job with the active version at the time that it was created.
2) Add a migration which is run when finalizing a version which waits for all running jobs to have a version set to something above the minimum binary version allowed for the node executing the job.

Now, how do we deal with `CHANGEFEED` jobs? This issue proposes that we allow jobs to upgrade their representation and thus their version. 

**Describe alternatives you've considered**

We need something here. We may want a tighter invariant.

**Additional context**

This comes up in the context of removing fields from job protos.
Some chatter in this [internal slack thread](https://cockroachlabs.slack.com/archives/CARM0PTK4/p1632871354140400). 

Jira issue: CRDB-11758

Epic: CRDB-15034

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11758](https://cockroachlabs.atlassian.net/browse/CRDB-11758) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73808`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
