### ISSUE TITLE
spanconfig: harden infrastructure for v22.1

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#73874]
#67679 wrapped up the major feature work for span configs (rfc:  #66348). This issue tracks the miscellaneous TODOs/bugs we left along the way; we should try and address them pre-22.1. They're categorized by size+necessity and ordered unscientifically by when we should do them.

**Small:**

- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/72440
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/pull/74171
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/pull/74266
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/pull/76384
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/76608
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/70173
- [ ]  https://github.com/cockroachdb/cockroach/issues/79039
- [ ]  Add a test variant of https://github.com/cockroachdb/cockroach/pull/76466 for secondary tenants 
- [ ] https://github.com/cockroachdb/cockroach/issues/77539
- [ ] Expose the number of [`KVSubscriber` restarts due to internal errors](https://github.com/cockroachdb/cockroach/blob/5e70321fad7ab991791338c21c52201c5957bc44/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L181-L195) as a metric
- [ ] Expose metrics on the KVAccessor; number of invocations, number of spans, how long they take (even if just a counter of total duration)
- [ ] Expose per-store metrics on how many replicas each tenant has

**Medium:**
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/pull/74265
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/pull/73876
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/75639
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/73045
- [x] #77505
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/70555
- [x] *(necessary)* https://github.com/cockroachdb/cockroach/issues/73789
- [ ] https://github.com/cockroachdb/cockroach/issues/73694
- [ ] https://github.com/cockroachdb/cockroach/issues/73749
- [ ] https://github.com/cockroachdb/cockroach/issues/72389
    - [ ] https://github.com/cockroachdb/cockroach/issues/66063
    - [ ] https://github.com/cockroachdb/cockroach/issues/65903

Epic CRDB-10563

Jira issue: CRDB-11795

**Comment by ajwerner** [comment]
@irfansharif can we track https://github.com/cockroachdb/cockroach/issues/73045 somewhere if not here? It's really in the critical path and I need to know when and how it's getting done.

**Comment by irfansharif** [comment]
Added, this list as good as any to track it.

**Comment by irfansharif** [comment]
@ajwerner Since there's already a PR out for #73045 I just removed it from this list (which I've learned looks scary and long, not at all the intent).

**Comment by irfansharif** [comment]
Adding https://github.com/cockroachdb/cockroach/issues/76608 to the list, something we hadn't thought of in the context of index-backfills.

**Comment by irfansharif** [comment]
This thing is done. There are specific issues or PRs for all the remaining nice-to-haves. Two shorter term things we should probably do:
- #80147; track additional metrics we could export, and 
- #80148; add a few builtins that might come in handy during escalations.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11795](https://cockroachlabs.atlassian.net/browse/CRDB-11795) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-73874`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
