### ISSUE TITLE
storage: replica reservation size

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7388]
[This might not be a bug]

Reservation requests currently reserve `max(Replica.GetMaxBytes(), Replica.GetMVCCStats().Total())` shortly before performing a snapshot. I'm not clear on what the purpose of this logic is. I would have expected a reservation to use `Replica.GetMVCCStats().Total()` alone. We should either simplify the code, or add a comment explaining why reserving `Replica.GetMaxBytes()` when the actual number of bytes is tiny is useful.

**Comment by BramGruneir** [comment]
The original idea behind this is that limiting the number of reserved bytes is a better method of control than just a max number of reservations.  And we can combine the two if we use max bytes.  

Also, there is the possibility that the size does increase between requesting a reservation and sending a snapshot (depending on how async the snapshotting is compared to the changeReplicas call).

However, since looking through the logs of many a run now, I'd be confident changes this to just total.  I'll send a PR out shortly.
