### ISSUE TITLE
rpc: do not use the same `Context` for both servers and clients

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#73967]
Refactor/enhancement requested by @catj-cockroach and @andreimatei.

Currently, we use the same `rpc.Context` to support RPC traffic between nodes, and between CLI RPC clients and nodes.

This is a problem because the construction of a `rpc.Context` instance requires a lot of details for servers, which are commonly not available in CLI client code. So when instantiating `rpc.Context` for a CLI client, we need to fill in fields in ways that are hard to understand:

- why does a client need to fill in a tenant ID?
- why does a client need to know about the client CA for TLS?
- why does a client need to know the cluster ID? and node ID container?
 
All these questions are really inconvenient and an artifact of the fact we're using the same Go type for two unrelated purposes.

Instead we should have two different types: `ServerContext` and `ClientContext`  with separate constructors.
The logic common to the two could be shared by a struct inherited from both.

Jira issue: CRDB-11830

**Comment by andreimatei** [comment]
In addition to the all the unnecessary data, I think the bigger problem is that a client using the `rpc.Context` ends up measuring the servers clock skews, and I think also ends up polluting the servers' measurements.

I think I was trying to do something like this here, but I've abandoned it.
https://github.com/cockroachdb/cockroach/pull/14376

Perhaps this has somehow been fixed since, although I don't immediately see it.

**Comment by knz** [comment]
This has been achieved.
