### ISSUE TITLE
dev: recognize multi-package builds

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#74213]
**Is your feature request related to a problem? Please describe.**

I very often run `make XXX  PKG=./pkg/a/b/c/...`
notice the `/...` at the end - this is recognized automatically by `go` (`build` / `test`) to recurse.
I can use this with `build`, `testbuild`, `test`, etc.

Unfortunately, neither `bazel` nor `dev` recognize this.

Would it be possible to extend `dev` to recognize `/...` patterns or something equivalent?

**Describe the solution you'd like**

```
dev testbuild //pkg/a/b/c....
dev test //pkg/a/b/c/...
```

etc

Epic CRDB-8036

**Comment by rickystewart** [comment]
The `/...` syntax will actually usually work, it's just that because our `go_proto_library`s can't be built standalone, that will fail if the directories have any `.proto` files.

We could pretty easily add some logic in `dev build` to recognize the `/...` syntax and filter out only `go_binary`s, `go_test`s, and `go_library`s.
