### ISSUE TITLE
storage: incomplete pebble file registry migration

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#74263]
**Describe the problem**

Looking at the system migration added in #67320, I think we're vulnerable to nodes being added mid-migration. Looking at the migration code here:

https://github.com/cockroachdb/cockroach/blob/182d2d4940a71cc93cb290e43275e23e91fe5f69/pkg/migration/migrations/records_based_registry.go#L25-L29

I see we're using the `ForEveryNode` primitive without a surrounding `UntilClusterStable` block. `ForEveryNode` fans out to all nodes known about at the time, but it may miss new nodes being added in over the loop duration. That's what the `UntilClusterStable` primitive is for. This is documented [here](https://github.com/cockroachdb/cockroach/blob/0dc7f4bb5036ded4a78d3821c7e58071be03dcca/pkg/migration/system_migration.go#L35-L42), though perhaps we'd benefit from a linter/re-working the API.

**Expected behavior**

Surrounding it with a `UntilClusterStable` block should get rid of this unlikely-to-occur IRL bug.

Jira issue: CRDB-12012

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-12012](https://cockroachlabs.atlassian.net/browse/CRDB-12012) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-74263`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
