### ISSUE TITLE
Add CockroachDB support to MikroORM (open-source nodejs project)

### ISSUE THREAD

**Issue by Frank-D** [cockroachdb/cockroach#74564]
Hello crdb team and community!

Would be nice to help [MikroORM](https://mikro-orm.io/) open-source project to get CockroachDB driver added to this very promising ORM (in the nodejs world).

MikroORM is built around [knexjs](https://knexjs.org/), which already supports cockroach, and [MikroORM already supports Postgres](https://github.com/mikro-orm/mikro-orm/tree/master/packages/postgresql), so the effort required to add a new CockroachDB driver inside MikroORM (most likely by copying the Postgres driver, and adapt it where needed..) shouldn't be too much.

Thanks

(ref.: https://github.com/cockroachdb/cockroach/issues/25468)

Jira issue: CRDB-12152

**Comment by otan** [comment]
cc @vy-ton

**Comment by vy-ton** [comment]
fyi @kernfeld-cockroach for prioritization

**Comment by kernfeld-cockroach** [comment]
@Frank-D thanks for sharing! I think this is the first time I've seen the "Unit of Work" ORM architecture and I find it quite interesting. That said, we have a ton of ORM support work ongoing right now so we probably shouldn't start on this yet.

@rafiss do we have any docs on how to test a new ORM with CockroachDB, in case someone from the community is interested in taking a swing at this?

**Comment by rafiss** [comment]
Each ORM has its own way of being tested. I would recommend looking at the documentation and test code for the ORM in question (https://github.com/mikro-orm/mikro-orm/tree/master/tests), which should describe how to run the ORM tests.

To run against CockroachDB, follow one of our guides for starting a local cluster (from the [binary](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html) or [docker image](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html)), then configure the ORM test suite to point at CockroachDB. Since CockroachDB is wire-compatible with PostgreSQL, you can try modifying the PostgreSQL test so it connects to CockroachDB instead of PostgreSQL.
