### ISSUE TITLE
Statements page gives error in multi-region cluster

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#74680]
Tracking JIRA: https://cockroachlabs.atlassian.net/browse/CC-5816

Epic: CC-5816

Jira issue: CRDB-12202

**Comment by Azhng** [comment]
Being multi-region cluster here is very likely not the issue. The issue here is likely due to the fact that our query plan for Statement / Transaction Page is not optimal. Especially since we are using the virtual table as a proxy to query the system table.


Effectively, here's our query plan:


```
root@127.0.0.1:26257/movr> explain select * from system.statement_statistics AS OF SYSTEM TIME follower_read_timestamp() order by metadata ->> 'query', transaction_fingerprint_id;
\                       info
--------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: (aggregated_ts > '1970-01-01 00:00:00+00:00') AND (aggregated_ts < '1970-07-05 04:26:40+00:00')
  └── • sort
      │ order: +column14,+transaction_fingerprint_id
      │
      └── • render
          │
          └── • scan
                missing stats
                table: statement_statistics@primary
                spans: FULL SCAN
(12 rows)
```

The sort on top of the full table scan is going to be very expensive. This is due to the massive amount of data coming from the full table scan and the disk spilling because we are definitely blowing up the in-memory sorter in the SQL Engine. 

We need to pass down the predicate of `aggregated_ts` down into the system table in our query plan here, either by making the virtual table smarter, or by switching away from using virtual table and build our own interface here.

**Comment by maryliag** [comment]
Performance issues improved on 23.1
