### ISSUE TITLE
jobs: Add MarkIdle API

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#74747]
A running job may want to mark itself Idle.  And idle job may be shutdown.
MarkIdle should increment a counter keeping track of the number of idle jobs.

Initial Design for the purposes of allowing CDC to function on Serverless:
- A `jobs_[type]_currently_idle` metric will track the number of idle jobs of that type.  Using metrics allows for serverless to not rely on the jobs table
- For now, idleness state will only be stored in the Registry rather than worrying about persisted state yet.
- Idleness should not be updated more often than twice a minute (so jobs should wait at least 1 minute since becoming active before marking themselves idle again).  This allows changes to idleness state to be logged.

This doesn't allow for observability into individual jobs, but this can easily be added as followup.

Epic CRDB-8671

**Comment by dt** [comment]
Can we stipulate how quickly / often we expect jobs update their idle change state? Is this like progress updates, where a job is expected to keep its own local state and then update after say 15s or 1m in which it did no work, or is it expected to e.g. be able to update in every iteration of a select loop?

What about non-changefeed jobs? Any reason we're making a `jobs_changefeeds_currently_idle` metric vs just a `jobs.currently_idle` metric?

**Comment by samiskin** [comment]
> Can we stipulate how quickly / often we expect jobs update their idle change state? Is this like progress updates, where a job is expected to keep its own local state and then update after say 15s or 1m in which it did no work, or is it expected to e.g. be able to update in every iteration of a select loop?

For Changefeeds I currently have a `changefeed.idle_timeout` cluster setting that defaults to **10 minutes**, where if the frontier hasn't been notified that any aggregators have emitted any kvs since more than 10 minutes ago, it'll mark the job as Idle.  As soon as the frontier is informed that a kv was emitted, it'll set the idleness to false.  Aggregators inform the frontier of how many kvs were emitted at the same time they send resolved spans. 

I don't imagine jobs would realistically changing their idleness state quickly? since the purpose of this "idleness" is "Its been long enough that its unlikely any work will happen in the near future".  I suppose it depends on the cost of tearing down a node/tenant and bringing it back up, which I don't have a good understanding of.

> What about non-changefeed jobs? Any reason we're making a jobs_changefeeds_currently_idle metric vs just a jobs.currently_idle metric?

Ah sorry, edited it now to say `jobs_[type]_currently_idle`, its only that way because all I did was add a `CurrentlyIdle` Gauge to `pkg/jobs/metrics.go`, which is already split by job type.

**Comment by dt** [comment]
If the expected usage in changefeeds is that they won't be setting idleness for 10min, then I'd go ahead and add something to this API contract now that a single job should not switch its idleness more than, say, twice a minute (which leaves room for immediately becoming active after setting idle as long as one waits >1min to set idle). Having that property codified leaves more room for updating persisted progress later and makes it reasonable to log a message when idleness changes (so we can correlate things happening when a job became active, just like when a standard job starts executing for the first time).

**Comment by samiskin** [comment]
Makes sense 👍 , by "add something to this API contract" would a code comment suffice or do you mean enforcing it at runtime?

**Comment by dt** [comment]
Just a comment seems fine to me, ala `A single job should not call this method more than twice per-minute as it logs and may write to persisted job state in the future`

**Comment by irfansharif** [comment]
Posting here to follow along; going to cargo-cult whatever we do for the AUTO SPAN CONFIG RECONCILIATION job: https://github.com/cockroachdb/cockroach/issues/70538.
