### ISSUE TITLE
kv, sql: visualize current lock holders and waiters via sql

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#74834]
Part of #67589.

In order to visualize the locks currently held by transactions in a database, as well as the transactions waiting on locks, we will need a virtual table that can call out to the KV interface to query locks (#74833) and display the results.  This will be a `crdb_internal` table, called `crdb_locks`, that can be joined with existing tables such as `cluster_transactions` and `cluster_queries` to visualize what transactions are currently holding or blocked waiting for a particular lock.

Jira issue: CRDB-12288

**Comment by AlexTalks** [comment]
Design doc (CRL Internal Link): https://docs.google.com/document/d/1Wm_Q7dPfE4Zhg3zFVHuzRBRKkUGEFCAoVDQUoDFeRag/edit?usp=sharing

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-12288](https://cockroachlabs.atlassian.net/browse/CRDB-12288) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-74834`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
