### ISSUE TITLE
crdb_internal.replication_stream_progress(): log-job: UpdateDeadline() called on leaf txn

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#75121]
roachtest.sqlsmith/setup=seed/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4140354&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4140354&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations) on master @ [365b4da8bd02c06ee59d2130a56dec74ffc9ce21](https://github.com/cockroachdb/cockroach/commits/365b4da8bd02c06ee59d2130a56dec74ffc9ce21):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:259,sqlsmith.go:298,test_runner.go:780: error: pq: internal error: crdb_internal.replication_stream_progress(): job -1109278611987283860: log-job: UpdateDeadline() called on leaf txn
		stmt:
		SELECT
			crdb_internal.replication_stream_progress((-1109278611987283860):::INT8::INT8, tab_268._string::STRING)::BYTES
				AS col_644
		FROM
			defaultdb.public.seed@seed__int8__float8__date_idx AS tab_268,
			defaultdb.public.seed AS tab_269
			JOIN defaultdb.public.seed AS tab_270 ON (tab_269._jsonb) = (tab_270._jsonb)
		ORDER BY
			tab_268._inet, tab_268._float4 DESC;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=seed/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/74729#issuecomment-1015142799_

Jira issue: CRDB-12475

Epic CRDB-11732

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-12475](https://cockroachlabs.atlassian.net/browse/CRDB-12475) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-75121`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by stevendanna** [comment]
This was closed out and then reopened by exalate.  We no longer run these functions through SQL smith, and by the time it was reopened the original failure logs were gone.

I've tried to reproduce this failure using similar looking calls to the relevant function and wasn't able to.
