### ISSUE TITLE
storage: `TestPebbleEquivalence` takes an abnormal amount of time to complete

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#75142]
`make test PKG=./pkg/storage/metamorphic TESTS=TestPebbleEquivalence`

takes 10mn+ to complete.

This is abnormal and it unduly inflates our CI time.
(Sometimes even incurring a timeout, e.g. https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/4152243?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true)

Is there a way to have a reduced version of this for CI, and then run the full test on the nightlies/weeklies instead?

cc @itsbilal for triage

**Comment by itsbilal** [comment]
This is a fair concern, and I think the recent clearRangeOp changes to that test (#74317) lengthened that test even more. 

The "shorter main CI run, longer nightly run" is actually already a part of (and the only remaining part of) #70935, but this issue is a good enough reason to prioritize it again.
