### ISSUE TITLE
perf: cockroach performance issue

### ISSUE THREAD

**Issue by amangoeliitb** [cockroachdb/cockroach#7538]
What did I do?
I am running a 4 node cluster. I am trying to create a mock file metadata store.
There are 4 clients. Each node is basically a client as well. Each client tries to create a large number of unique directories. Each directory corresponds to 3 unique entries in the table. 1 directory creation is bundled within a transaction. We are using a schema similar to the one here: [https://github.com/cockroachdb/examples-go/tree/master/filesystem]

What I expect to see?
A stable performance of about 1000 writes per second (or whatever, we are just trying to do some benchmarking). We are testing scalability by running a cluster of 1 node with 1 client, 2 node with 2 clients ... 4 node with 4 clients.

What did I see?
Initially the performance is good (~1000 writes per second). Suddenly performance falls and in the logs of nodes [https://gist.github.com/amangoeliitb/5e53e9f90809a9b6794d99a1d0991500], I see errors. The writes per second eventually fall down to ~700 and later to less than 600.

This is what the UI looks like:

<img width="1310" alt="screen shot 2016-06-29 at 6 08 30 pm" src="https://cloud.githubusercontent.com/assets/6622174/16473676/86344d62-3e24-11e6-9a05-23cbd0bb4fad.png">

Edit: The experiment has been running for a while and this is what I see in the UI:

<img width="1290" alt="screen shot 2016-06-29 at 6 34 25 pm" src="https://cloud.githubusercontent.com/assets/6622174/16474062/37b1e0ba-3e28-11e6-8bce-09b9156a5f1b.png">

Isn't that too much of memory consumption?

Edit 2:
Eventually, My experiment seems to have crashed with this error: `E0630 01:34:49.443269 25429 filecabin.cpp:352]  Transaction failure: 25P02: ERROR:  current transaction is aborted, commands ignored until end of transaction block`
This has been happening a lot of times.
I retry a transaction for 5 times on seeing a `restart transaction:` error. However, this seems to be related to one of the previous issues I reported [https://github.com/cockroachdb/cockroach/issues/7198]
The keys are all different and so, ideally I should never see this error

**Comment by cuongdo** [comment]
Thanks for your report. We're investigating other gradual slowdowns. For example, #7280. This sounds like it might be related. We'll report back as there are developments.

**Comment by tschottdorf** [comment]
This isn't a completely qualified comment because I haven't looked at the actual workload, but one prime culprit of such a slowdown is that what used to be written to one range now hits two ranges (after the first split). I don't see it in the logs, but on Gitter I think you mentioned also seeing some warnings about `AdminSplit` (which are, btw, benign- similar to the ChangeReplicas errors in the logs above).

Would you mind posting `EXPLAIN (TRACE) <insert_your_insert_statement_here>` twice (once right after start when it's fast, and once when it's slow)? You might also be able to corroborate my theory by looking at the "total replica count" on the nodes page (which goes up 1 with every split, though on a four node cluster there could be some movement due to rebalancing). For the purpose of tracking this down, you could likely limit your cluster to three nodes, though (and it should even show on a single-node system).

**Comment by spencerkimball** [comment]
Closing for lack of repro instructions, and many intervening performance updates.
