### ISSUE TITLE
storage: unable to cancel expired Raft command BeginTransaction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7577]
When running `block_writer` I've started to see a lot of warnings in logs that look like:

```
W160701 00:55:09.767296 storage/replica.go:1233  unable to cancel expired Raft command BeginTransaction [/Table/51/1/1256147214164052370/"fa7efbce-4a3f-41a6-ba14-f25f6db1fbf8"/6901/0,/Min), ConditionalPut [/Table/51/1/1256147214164052370/"fa7efbce-4a3f-41a6-ba14-f25f6db1fbf8"/6901/0,/Min), ConditionalPut [/Table/51/1/1256147214164052370/"fa7efbce-4a3f-41a6-ba14-f25f6db1fbf8"/6901/4/1,/Min), EndTransaction [/Table/51/1/1256147214164052370/"fa7efbce-4a3f-41a6-ba14-f25f6db1fbf8"/6901/0,/Min)
```

Seems like something got tweaked incorrectly recently. These messages may be related to a drop of throughput to 0.

**Comment by tschottdorf** [comment]
Interesting. This error means that a client's context expired and it tried to take the command out of the pending commands map, but it wasn't there. Typically that means that the command is just being applied in that very moment. Maybe commands are stalling outside/before Raft for long enough to cancel the context before it's even proposed (which could explain a higher frequency of that).
Dealing with that is what @tamird just discussed in #3299. Might be worth doing to see what the issue here is.
Should also be relatively easy to investigate if it repros easily on a fresh single node: print `ba.String()` with that error, log all applications (around `applyRaftCommand`) which don't have a pendingCmd, and see whether the ones that are printed by the error actually applied just before.

**Comment by petermattis** [comment]
Repros within 1-2min reliably for me on GCE. Strange thing is that I was doing some tests on GCE without problems and then it started happening. I initially suspected some of my tweaks so I reverted to master and it continued happening. Then I reverted some of the recent commits to master and it still continued to happen.

**Comment by tschottdorf** [comment]
What exactly are you running on GCE?

**Comment by petermattis** [comment]
```
./cockroach start
```

and

```
./block_writer --duration 10m
```

This is on a 32 core machine in case that matters. I was playing with the `max_background_compactions` settings.

**Comment by petermattis** [comment]
Note that this doesn't seem to occur when running on my (Mac OS X) laptop.

**Comment by tschottdorf** [comment]
Does running on a 32core machine mean that you're running at high
concurrency? And it's still not happening if you manually run the block
writer on your mac with the same concurrency (probably 32)?

On Thu, Jun 30, 2016 at 9:45 PM Peter Mattis <notifications@github.com>
wrote:

> Note that this doesn't seem to occur when running on my (Mac OS X) laptop.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7577#issuecomment-229834397>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135BfzpbnJvsI9qIMTqX1fA5Wvkhneks5qRHFJgaJpZM4JCup9>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
@tschottdorf Yes, I'm running at high concurrency. `block_writer` now defaults to `2*num-cpu` for concurrency. Going to try with that same level of concurrency on my laptop.

**Comment by petermattis** [comment]
I'm completely unable to reproduce on my laptop. Reproduction on GCE is interesting. The problem went away for a while and now it has reappeared. Furthermore, the problem only seems to occur when I'm writing to an `SSD persistent disk`. When running on top of `local SSD` I don't see an issue. I'm suspicious that the `SSD persistent disk` is using too much network and hitting some sort of throttling.

**Comment by petermattis** [comment]
Closing due to this issue being very old and unreproducible.
