### ISSUE TITLE
kvserver: outgoing replica snapshot is not properly using an engine snapshot

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#75824]
related to the incident mentioned in https://github.com/cockroachdb/cockroach/issues/75728, https://github.com/cockroachlabs/support/issues/1403 (internal)

To send a replica snapshot we construct an engine snapshot at https://github.com/cockroachdb/cockroach/blob/be1b6c4fd4778b784658459f77d28e6ed746c349/pkg/kv/kvserver/replica_raftstorage.go#L420
and then immediately proceed to constructing a `ReplicaEngineDataIterator` that will construct a `pebble.Iterator`
https://github.com/cockroachdb/cockroach/blob/be1b6c4fd4778b784658459f77d28e6ed746c349/pkg/kv/kvserver/replica_raftstorage.go#L577

The lifetime of the `pebble.Iterator` and the `pebble.Snapshot` are the same, so we don't get any benefit from the `pebble.Snapshot` pinning data but not pinning sstables or memtables, since the latter get pinned by the `pebble.Iterator`.
If sending a snapshot can be slow for whatever reason, we should consider periodically closing the `pebble.Iterator` and creating a new one.

cc to folks on that investigation: @aayushshah15 @tbg @nicktrav  

Jira issue: CRDB-12851

**Comment by tbg** [comment]
Your suggestion is to keep the long-lived snapshot but to make sure that the iterator isn't long-lived, right? Could you explain in more detail what the difference is? Both an iterator and a snapshot prevent SSTables that are "reachable" from them to be preserved, is this "pinning" behavior you mention related to how pebble manages its in-memory caches? How big a difference does it make? So far the problems I've observed with slow snapshots were related to SSTs not being deleted, am I missing another dimension? It doesn't seem that this suggestion would make a change there.
Just trying to understand what this would improve in practice, as it seems a little cumbersome to manage the iterator livecycle separately.

**Comment by sumeerbhola** [comment]
> Your suggestion is to keep the long-lived snapshot but to make sure that the iterator isn't long-lived, right?

Correct

> Could you explain in more detail what the difference is?

A pebble.Snapshot only preserves the versions of a key visible to the seqnum of the snapshot. All other old versions can be deleted (these are pebble "versions", not MVCC versions). This is handled via compactions being snapshot aware. So if you consider a typical workload with a low write rate, most versions that are visible to the snapshot will continue to be the latest version, so the snapshot is not causing much "old data" to be retained.
In contrast, a pebble.Iterator causes all memtables and sstables as of the time of the iterator creation to be kept until the iterator is closed. Which means that if these memtables are flushed or sstables are compacted, both the input and output needs to be preserved even if they contain the same key versions. So even the latest version of a key will end up with multiple copies being retained, until the Iterator closes. In addition to consuming more disk space, this can also cause memory pressure and OOMs.

**Comment by erikgrinaker** [comment]
Sumeer points out that this would be straightforward with the new replica data iterator pattern in #84070.

https://github.com/cockroachdb/cockroach/pull/84070#pullrequestreview-1051487457

**Comment by erikgrinaker** [comment]
This fell through the cracks in the pre-stability scramble, unfortunately. Won't get it in for 22.2.

**Comment by pavelkalinnikov** [comment]
Seems doable: `kvBatchSnapshotStrategy.Send` can yield when it spent enough time [reading](https://github.com/cockroachdb/cockroach/blob/f263a765d750e41f2701da0a923a6e92d09159fa/pkg/kv/kvserver/store_snapshot.go#L575) in `IterateReplicaKeySpans`, and let the latter recreate the iter and seek to the position where it stopped.

How necessary is it though, now that `IterateReplicaKeySpans` already creates/closes multiple iterators? Currently 8: point and range iter for each of the [4 spans](https://github.com/cockroachdb/cockroach/blob/1f81f5eb51d09d9e0482b03e5205452bcf3afd4c/pkg/kv/kvserver/rditer/replica_data_iter.go#L77-L92).

If we still want to do this, can this be pushed down to lower levels? For example, the implementation of `EngineIterator` (which here is Pebble iterator) could do that on `NextEngineKey` calls and the like, or even further down the stack: wherever the SSTs are locked.

Can be a bigger change, but the rationale is:
- this is Pebble-specific behaviour,
- doing it on lower levels can benefit other usages of the iterator (can you think of any?)

**Comment by pavelkalinnikov** [comment]
Another fix that I can imagine is that Pebble iterator is tied to a snapshot (instead of pinning memtable and SSTs upfront), but when it scans through things, it dynamically pins the bits it touches. @sumeerbhola is anything like that feasible in Pebble?

**Comment by erikgrinaker** [comment]
> Seems doable: `kvBatchSnapshotStrategy.Send` can yield when it spent enough time [reading](https://github.com/cockroachdb/cockroach/blob/f263a765d750e41f2701da0a923a6e92d09159fa/pkg/kv/kvserver/store_snapshot.go#L575) in `IterateReplicaKeySpans`, and let the latter recreate the iter and seek to the position where it stopped.

Yeah, I was thinking we'd return e.g. `iterutil.Reopen()` from `IterateReplicaKeySpans` whenever we wanted it to reopen the iterator.

> How necessary is it though, now that `IterateReplicaKeySpans` already creates/closes multiple iterators? Currently 8: point and range iter for each of the [4 spans](https://github.com/cockroachdb/cockroach/blob/1f81f5eb51d09d9e0482b03e5205452bcf3afd4c/pkg/kv/kvserver/rditer/replica_data_iter.go#L77-L92).

7 of those iterators are typically trivial. The user point keyspace is the one that takes time.

However, we now have a 1 hour timeout for sending Raft snapshots:

https://github.com/cockroachdb/cockroach/blob/003616079c0b79e97bedeac5fd81510507be9d43/pkg/kv/kvserver/replica_command.go#L60-L68

In the original incident, the snapshot had been stuck for at least 12 days. Now that we have a backstop timeout of 1 hour, I'm not sure if it's worth releasing the iterator pinning periodically. Wdyt @sumeerbhola?

> If we still want to do this, can this be pushed down to lower levels? For example, the implementation of `EngineIterator` (which here is Pebble iterator) could do that on `NextEngineKey` calls and the like, or even further down the stack: wherever the SSTs are locked.

Seeks are expensive, so we definitely don't want to do this for latency-sensitive operations. Also, we can only do it on readers that have consistent iterators since we'd otherwise change the view of the iterator (it would see newer data after being reopened). I think it makes sense to do this above Pebble.

**Comment by pavelkalinnikov** [comment]
Makes sense. Here are a few alternatives.

> Seeks are expensive, so we definitely don't want to do this for latency-sensitive operations.

Maybe on Pebble level there could be a way to avoid re-seeking or do it cheaper (only need to do it for one SST when it's compacted, instead of the whole stack). Also, the latency sensitivity could be a parameter when creating the iterator.

> Also, we can only do it on readers that have consistent iterators

Does Pebble iterator/snapshot also know this info?

**Comment by erikgrinaker** [comment]
> > Also, we can only do it on readers that have consistent iterators
> 
> Does Pebble iterator/snapshot also know this info?

With the exception of Pebble snapshots, consistent iterators are implemented in CRDB via iterator cloning. See e.g. `pebbleBatch`:

https://github.com/cockroachdb/cockroach/blob/5bafe901cd6fd4ceee00ee922e7f13ed95c4134b/pkg/storage/pebble_batch.go#L178-L192

So this may only be viable on Pebble snapshots, that are consistent by definition. Other reader types (e.g. engine and batch) probably won't be viable, because the view of the iterator will change when it's refreshed. I think it kind of has to, because otherwise it won't be able to release the pinned SSTs, but I'll defer to storage here.

**Comment by pavelkalinnikov** [comment]
We are inclined to close this, as 1h timeout does the job, and the initial suggested fix introduces complexity.

@sumeerbhola Still interested in your input though.

**Comment by sumeerbhola** [comment]
Closing sounds fine. No need to add code that we don't really need.
