### ISSUE TITLE
ui: stop refreshing data in `componentDidUpdate`

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#75863]
Currently, when refreshing data from the admin ui, we rely on the `CachedDataReducer` class that manages the state of the data and request response. For any data received and stored in redux we create a `CachedDataReducer`, passing the caching period, request and timeout. The current caching and refreshing process in the admin-ui using this object is as follows:

- the cached data reducer object provides 2 methods of controlling requests: `invalidateData` and `refresh`
- `refresh` is used to update the data by re-issuing a request and storing the results/errors in the object state
- for each request issued by the `CachedDataReducer`, it will first check to see if the current data stored is still `valid`, if true, there will be no request issued and the data will not be updated
- data is invalidated in the following ways: by calling `invalidateData`, by the `CachedDataReducer` after the caching time has elapsed (via calling `invalidateData` from a `setTImeout`), and if a request returns an error

So in theory, we can repeatedly call the  `refresh` functions provided by the `CachedDataReducer` without issuing new requests so long as the data is still valid. In our UI components, we take advantage of this by throwing most of our refresh functions in `componentDidUpdate`. This is bad practice.  The logic here is that `componentDidUpdate` is a function that is frequently called, and so we will eventually update the data once the data is invalidated. 

This practice heavily relies on the knowledge that the refresh function won't issue new requests via the above logic. Note that we provide refresh functions from both cluster-ui wrappers for CC, and via the cachedreducer for admin-ui. In practice, `componentDidUpdate` is mostly used for updates in response to prop changes, but we call `refresh` without any if guards. This current method can easily lead to bugs and infinite updates that will crash the page. 

We should investigate better methods for polling data and transition our components to use the new strategy.
One option is to create a hook that uses intervals that will refresh data, also making the update more explicit in each UI component.

Jira issue: CRDB-12863

**Comment by jocrl** [comment]
Thanks for this clear explanation! This is now clearer in my head 🙂.

To be precise about the title - I think the main issue here is the use of `CachedDataReducer` to do polling, rather than putting poling code in `componentDidUpdate`. Specifically, as you describe, the reliance on knowledge of how calling `refresh` on `CachedDataReducer` works.

The `useInterval` hook [in managed-service](https://github.com/cockroachlabs/managed-service/blob/master/console/assets/js/hooks.ts#L3) is ultimately a `useEffect`. And `useEffect` is the hooks version of `componentDidMount` + `componentDidUpdate` + `componentWillUnmount` (see the Tip box in [these docs](https://reactjs.org/docs/hooks-effect.html)).

So, refreshing data in `componentDidUpdate` is pretty natural (just, hopefully, conditionally!), since you do probably want to change your polling parameters as props and state change. In a world without thunk/sagas, data fetching would usually go in the `componentDidMount/Update`.

One question I have on possible better methods, is when to use thunk/sagas for these side effects and data fetching, vs putting things in these React lifecycle methods.

**Comment by Azhng** [comment]
The `useInterval` hook from managed-service seems quite neat. I feel this is a good starting point to start iterating. From quick search, it appears that there's definitely [solutions](https://medium.com/@nitheeshkr115/polling-with-redux-saga-313cb9c5b34) that implements polling using `redux-sagas`. It might be a bit tricky to get it right since we also need to handle preemptive polling on `props` change but conceptually I think it's doable. 

It's hard to tell at this point what would be better, or what the API is going to look like. But I think we can start building a few prototypes to try out ideas  to see what works and what doesn't.

**Comment by jocrl** [comment]
👍 and to bring this up in the #frontend-learners channel! There are so many different polling solutions across the two repos that I'm sure people have opinions and experience on what they do or don't like. There definitely are existing examples of thunk/sagas doing polling in the repos. Maybe someone might even want to do a presentation, might be a good follow-up.

I'll finally get around to posting 😛.

**Comment by xinhaoz** [comment]
Agree on all the comments thus far. @jocrl  yeah didn't mean to imply making an API req in `componentDidUpdate` was wrong, just the way we are currently doing it - calling it on every update unguarded  / it's not actually clear on what conditions it is supposed to refresh based on the usage. If our use cases are simple enough, I feel we shouldn't bother with polling in redux saga. We can customize hooks quite a bit as well, and I find they are much more straightforward.

Also should mention, on the cluster-ui side of things, we use [throttle with reset (this function is pretty cool IMO)](https://github.com/cockroachdb/cockroach/blob/b8323204a3e13d0ff49b2234f6fa2b8907f5fb4e/pkg/ui/workspaces/cluster-ui/src/store/utils/sagaEffects/throttleWithReset.ts#L54) to achieve similar behaviour so that the provided `refresh` function can be used the same way as the one form `cachedReducer`.

**Comment by xinhaoz** [comment]
Just a note on why this was removed from quick wins: spoke to @kevin-v-ngo  offline on this and based on the above conversation, this probably needs a bit more deliberation so we've removed it from the quick win category.

**Comment by ericharmeling** [comment]
> Just a note on why this was removed from quick wins:

It looks like this issue is still in quick wins. Should we put it in the backlog?

**Comment by maryliag** [comment]
No longer a priority
