### ISSUE TITLE
bazel: roachprod-stress equivalent

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#75902]
**Is your feature request related to a problem? Please describe.**

`make roachprod-stress CLUSTER=... TESTS=... PKG=...` will compile the relevant package under docker for linux and then ship the binary and testadata for the test over to the nodes of the cluster and run it. This can be critically important for shaking out flakey tests. We should have an equivalent for bazel.

**Describe the solution you'd like**

Ideally we could cross-compile without the docker. 

Epic CRDB-8036

Jira issue: CRDB-12873

**Comment by rickystewart** [comment]
@ajwerner I have a draft of this functionality on my fork: https://github.com/rickystewart/cockroach/tree/roachprodstress (the `roachprodstress` branch, commit `c52bbd39092d367697b7353da3d4a80be8abef26`). Right now I think this is mostly working but I'm trying to add a new `-testbin` argument to pass in the path to the test binary, but flag parsing seems not to be working for some reason. 🤷 

If you have time you can pull this and try to get it fully working, otherwise I'll wrap it up when I have time.

**Comment by ajwerner** [comment]
I'm PTO starting tomorrow for a week, so I won't be looking at it before March.

**Comment by rickystewart** [comment]
Ack, I'll probably get back to it next week then.
