### ISSUE TITLE
making gc.ttlseconds default to 90000 if BIG mistake - lower it down to 3600

### ISSUE THREAD

**Issue by dPeS** [cockroachdb/cockroach#75926]
**Describe the problem**

Leaving default to 25h will make huge reception problem for CR. Most of db admins are not used to have tables with trash can sticked to it. Off course that could be great feature - no problem here. But I was tracking perf problem with CR for long time. We have small table (1k rows max) that changes a lot - a lot of hours wasted because of that big default setting. If I would design software to use that historical feature and find out that it is to low - then I could make it bigger. That is far more natural way of doing things.

for new to the CR admins: If you have some strange perf degradation problem checkout lower gc.ttlseconds + disable auto metrics gathering.

and... besides that - CR is great! 

Jira issue: CRDB-12883

**Comment by dPeS** [comment]
![Overview Dashboard _ Cockroach Console (8)](https://user-images.githubusercontent.com/4797605/152317726-92779dc5-823d-42ca-a4f5-fc8caabb0af1.png)

arrows show schema recreate - 3 nodes, with 21.2.3 CR, 2 tables (15rows, 1k rows), 5 workers making selects to those tables

**Comment by rafiss** [comment]
Thanks for sharing your experience!

There is one important thing to watch out for when lowering the `gc.ttlseconds`. If it is lower than the frequency of your BACKUP schedule, then the backup will fail. See https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables

You also mentioned disabling auto metrics gathering. Do you mean the automatic stats collection used by the query planner? That would be reasonable for tables that don't grow very much, but if your workload adds data over time, disabling stats can lead to very bad performance since the query planner can create bad plans that inefficiently access the data (for example, by doing a full table scan instead of using an index).

**Comment by dPeS** [comment]
@rafiss thx for pointing backups - we don't use them. We are using CR to keep state of broker (many concurent workers) which is doing mutual exclusion in CR. There is a lot of concurrent selects/updates/deletes on fairy small table (max 1000 rows).

Probably the TTL was the main problem. Statistics could be re-enabled now. But it works like a charm now (with disabled statistics and TTL 600s)

![Overview Dashboard _ Cockroach Console (13)](https://user-images.githubusercontent.com/4797605/153827152-f35af269-a22e-4c6b-93c1-5e7c81f60aec.png)
.

**Comment by rafiss** [comment]
I will close this, since gc.ttlseconds now defaults to 14400 (4 hours).
