### ISSUE TITLE
storage: test that preemptive snapshots are actually working

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7593]
See #7468. My current thought is to add per-replica counters for preemptive and normal snapshots which we could examine after initial replication is complete. Anyone have a better idea?

**Comment by tamird** [comment]
You could possibly use a pattern similar to this one https://github.com/cockroachdb/cockroach/pull/7534/commits/67d4958e9fe5487c4e07c98f49889483f4ed0c4d#diff-62766858ddaec8a310d2c5f397c93bdbR1495, though it's much easier to write a test that shows preemptive snapshots are _not_ working than it is to show that they _are_.

**Comment by bdarnell** [comment]
The counters seem like a good idea to me (but maybe at the store level instead of the replica level). We'll want this data in the metrics because non-preemptive snapshots should be rare (and after #7551, they may be much more expensive preemptive ones), and we'll want to be able to verify this fact.
