### ISSUE TITLE
Filter by attributes in hot ranges page

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#76159]
When displaying a table of hot ranges (v1), currently users can sort by column headers. We also want to provide the ability for a user to filter for specific attributes, namely: node, store, database, table, and index

Jira issue: CRDB-13003

Epic CRDB-2323

**Comment by koorosh** [comment]
@Annebirzin , want to clarify filtering behavior for every field:
- `Node ID` filter provides list of available node Ids to select (multi-value filter);
- `Store ID` filter allows users to type free text because there might be hundreds or thousands store ids;
- `Database name` filter provides list of available database names (multi-value filter);
- `Table name` filter is free text input form that allows type partial table or schema name (ie, `system.user`, `system.`, or `user`);
- `Index name` filter behaves the same as `Table name` ^^^

Do you think it's a proper behavior?
