### ISSUE TITLE
storage: outside-of-raft snapshots put consistency in jeopardy

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7619]
When we send a snapshot around outside of Raft (preemptive snapshot), we don't check whether the state we're overwriting is ahead of us.
This could lead to a replica being created, acknowledging progress, and then being reset through a snapshot.

Perhaps `canApplySnapshot` is a good place to check that. The necessary information should be deducible from the respective `HardState`s.

**Comment by bdarnell** [comment]
Specifically, there are some checks on the snapshot metadata in [`raft.restore`](https://github.com/coreos/etcd/blob/c7dd74d8d397faac444df23a9cafe1f0ae4be9c7/raft/raft.go#L899) which we don't do for preemptive snapshots. If there is data on disk we should check the term and index of the snapshot and drop it if it's older than what we already have.

Alternately, we could reorganize the checks in `handleRaftMessage` so we only call `applySnapshot` directly when we have no non-trivial local state, and pass the snapshot to `r.raftGroup.Step` otherwise to let raft make the decision.

**Comment by tschottdorf** [comment]
I know this is assigned to @tamird, but it ties in with stuff for #7600, so I'm currently poking around in it too (let's avoid crossing streams).

**Comment by tamird** [comment]
OK. I already have a WIP for this:
https://github.com/cockroachdb/cockroach/compare/master...tamird:preemptive-snap-no-backwards

**Comment by tschottdorf** [comment]
Snagging this issue from you as believed fixed in #7598 (won't merge without a test for this added).
