### ISSUE TITLE
testserver: rename GetHTTPClient to GetUnauthenticatedHTTPClient

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#76241]
Suggested by @dhartunian 

the problem to solve is that it's currently just too easy to create a test for a HTTP API without authentication, which does not invite the implementer to care about authn (nor authorization).

We can nudge this in the right direction by renaming the "simple" method to a longer name with a discouragement in the comment; then renaming the admin method to a "simple" name so that it's easier to find.

Jira issue: CRDB-13044

**Comment by JeremyLZX** [comment]
Hello! Can I help with this? Its my first time contributing but I have used golang before and would like to help!

I believe this would be just a simple renaming of functions rights?

**Comment by knz** [comment]
yes

**Comment by AryanSingh11** [comment]
Hey @knz 🙋‍♂️ I recently started learning GoLang and I believe I can help with this issue with @JeremyLZX but when I try to access the Jira issue, it shows - I don't have access. Since I'm new I don't know if I need to have the access or not. Please can you guide me to the file that needs the improvement and we shall submit the Pull request🙂🙌

**Comment by Alejandrenvrro07** [comment]
someone knows why testserver doesnt work?
