### ISSUE TITLE
kvserver: truncate Raft log if snapshot sending is slow

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#76295]
In a recent escalation, the snapshot transfer rates were set very low (8 B/s rather than 8 MB/s), which essentially caused snapshot transfers to stall. These in-progress snapshots halt Raft log truncation, because the recipient will need log entries to catch up after the snapshot has been applied. However, in this case the snapshots were in progress for days, which caused the Raft log to grow huge and eventually crash the node due to a Pebble batch overflow (#75793).

We should add heuristics to go ahead and truncate the log (and possibly abort the snapshot) if it's taking too long. This does introduce a risk of snapshot starvation, but at a certain point the log catchup would be slower than sending another snapshot anyway, so it seems like the starvation risk remains in that case.

**Comment by bdarnell** [comment]
> We should add heuristics to go ahead and truncate the log (and possibly abort the snapshot) if it's taking too long.

This is a good idea, and yes, it should abort the snapshot, because it will be worthless if it completes after the log has been truncated. We could do this very simply on the snapshot side with a fixed timeout of X minutes (and when the snapshot cancels itself it would automatically free up the raft log for truncation. even if a new snapshot attempt starts soon, the truncation-eligible part of the raft log would keep advancing). It would be more precise to consider the raft log size here instead of a fixed timeout, but I'm not sure it would be worth it.

**Comment by erikgrinaker** [comment]
Yep, that seems like the cheapest way to do this, and should be sufficient. Setting it to something fairly high (e.g. 10-30 minutes) should have us covered both ways.
