### ISSUE TITLE
storage: use `go test -cover` to find significant untested code paths

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7633]
```
~ make coverage PKG=./storage TESTFLAGS="-coverprofile cover.out"
~ go tool cover -html cover.out -o cover.html
```

Targeting 100% code coverage is excessive, yet there is interesting fruit to be plucked here. Some of this code is likely covered by tests in other packages, yet this code is important enough to system stability that we should have targeted tests of significant code paths.

**Comment by d4l3k** [comment]
#7952

**Comment by d4l3k** [comment]
Does it make sense to suppress coverage reports for packages that are only for testing? E.g. acceptance.

Also, the original script that @nvanbenschoten put together a while back filters out all `*.pb.go` files. Not sure if that's desirable or not (or if it even matters).

Having the extra packages/proto files just lowers the total coverage number, but otherwise doesn't hurt. I'm assuming we're only using the test % numbers internally.

@jordanlewis

**Comment by petermattis** [comment]
@d4l3k Yeah, we don't care about testing only packages. And we don't care about coverage of `.pb.go` files either. How hard is it to ignore them for coverage purposes?

**Comment by d4l3k** [comment]
Should be pretty easy, just grep through the coverpkg lists and remove all testing packages.

As for .pb.go, also pretty easy since we already do it for 
https://coveralls.io/github/cockroachdb/cockroach

The reason I asked about that was CodeCov seems like it has a nicer web interface and I'm planning on additionally adding it. https://codecov.io/gh/cockroachdb/cockroach/branch/d4l3k%2Fcoveralls

**Comment by d4l3k** [comment]
Second PR #7967

**Comment by jordanlewis** [comment]
Calling this one done.

https://coveralls.io/github/cockroachdb/cockroach
https://codecov.io/gh/cockroachdb/cockroach
