### ISSUE TITLE
How to improve TPS in sysbench write_read scenario ?

### ISSUE THREAD

**Issue by XiangXiangHotSpot** [cockroachdb/cockroach#76362]
Hi, I am testing CockroahDB via sysbench in write_read OLTP scenario, I started by running a 4 nodes cluster in 1 server behind an Haproxy load balancer ( I am aware such deployment is not recommended ). However, I noticed that TPS are around 840, which far below my expectation. Here’s the details of our deployment:

CPU architecture : ARM ;
CPU : 64 cores , 2 CPU in 1 sever ;
RAM : 32GB * 16 = 512GB ;
Disk : SSD , size 1TB for 1 node ;
network adapter : chelsio 6225 ;

server OS : linux 4.19.90

CockroachDB version : 21.1.9

database startup command:
numactl -N 2,3 cockroach1 start \
 --insecure \
 --cache=5% \
 --max-sql-memory=5% \
 --locality=group=001 \
 --store=path=/data2/1/cock21-1-4/,attrs=ssd \
 --advertise-addr=192.168.100.249:23001 \
 --log-dir=/var/log/cock21-1-4/1 \
 --listen-addr=:23001 \
 --http-addr=:23011 \
 --join=192.168.100.249:23001 \
 --background

numactl -N 4,5 cockroach2 start \
 --insecure \
 --cache=5% \
 --max-sql-memory=5% \
 --locality=group=001 \
 --store=path=/data2/2/cock21-1-4/,attrs=ssd \
 --advertise-addr=192.168.100.249:23002 \
 --log-dir=/var/log/cock21-1-4/2 \
 --listen-addr=:23002 \
 --http-addr=:23012 \
 --join=192.168.100.249:23001 \
 --background

numactl -N 8,9 cockroach3 start \
 --insecure \
 --cache=5% \
 --max-sql-memory=5% \
 --locality=group=001 \
 --store=path=/data3/3/cock21-1-4/,attrs=ssd \
 --advertise-addr=192.168.100.249:23003 \
 --log-dir=/var/log/cock21-1-4/3 \
 --listen-addr=:23003 \
 --http-addr=:23013 \
 --join=192.168.100.249:23001 \
 --background

numactl -N 10,11 cockroach4 start \
 --insecure \
 --cache=5% \
 --max-sql-memory=5% \
 --locality=group=001 \
 --store=path=/data3/4/cock21-1-4/,attrs=ssd \
 --advertise-addr=192.168.100.249:23004 \
 --log-dir=/var/log/cock21-1-4/4 \
 --listen-addr=:23004 \
 --http-addr=:23014 \
 --join=192.168.100.249:23001 \
 --background
sysbench test commend: 
sysbench /usr/local/share/sysbench/oltp_read_write.lua --pgsql-host=192.168.100.243 --pgsql-db=sysbench --pgsql-user=root --pgsql-password= --tables=30 --table-size=500000 --time=90 --report-interval=1 --db-driver=pgsql --pgsql-port=23001 --threads=64 --auto_inc=false run

haproxy commend : 
listen cock21-1-4-cxx
    bind *:23001
    mode tcp
    balance leastconn
    option httpchk GET /health?ready=1
    server 249-1 192.168.100.249:23001 check port 23011 weight 1
    server 249-2 192.168.100.249:23002 check port 23012 weight 1
    server 249-3 192.168.100.249:23003 check port 23013 weight 1
server 249-4 192.168.100.249:23004 check port 23014 weight 1

note: haproxy and sysbench are installed in another server. 

is there have any trick to improve performance in this scenario? thank you in advance.

**Comment by nvanbenschoten** [comment]
Hi @XiangXiangHotSpot, thanks for the report. Does each NUMA node consist of only a single vCPU? So each of the CRDB processes are being run on 2 vCPUs?

The TPS number you cite sounds low. That said, [these oltp_read_write  sysbench transactions are non-trivial](https://github.com/akopytov/sysbench/blob/df89d34c410a2277e19f77e47e535d0890b2029b/src/lua/oltp_read_write.lua#L44), containing 10 statements each including 3 mutations and 4 aggregations. Out of curiosity, have you tried running without the aggregations using the `--range_selects=false` flag?

**Comment by nvanbenschoten** [comment]
@XiangXiangHotSpot I took a look at reproducing your results on a single n1-standard-30 instance (30 x86 vCPUs). The configuration was a little different from what you were running, but it was close enough to give a sense of the workload.

I was able to push to about 1,700 tps / 34,000 qps. With `--range_selects=false`, tps increased to about 2,300 while qps increased to about 37,000. This roughly matches my expectations. The node was CPU-bound, which is the usual bottleneck for OLTP workloads. 37,000 qps across 30 vCPUs means that each vCPU was serving about 1,200 qps. Or put another way, each query consumed on average about `800 vCPU μs`. This is in line with other OLTP benchmarking that we have performed in the past.

We can use this 1,200 qps per vCPU number to make a rough prediction about what TPS your cluster configuration should be able to serve. Using the tps/qps ratio, we get `1200 * 1700/3400 = 60 tps/vcpu`. You are running on ARM without hyperthreading while my test was running on Intel with hyperthreading. There's no easy way to equate the two, but given that the workload was heavily CPU bound, let's say that hyperthreading isn't providing much of a benefit and so we approximate `2 Intel vCPU = 1 ARM CPU`. This gives `60 tps/vcpu * 2 vcpu/cpu = 120 tps`. Finally, you then have 8 CPUs, so we would expect `120 x 8 = 960 tps`.

You were seeing `840 tps` (~`17,000 qps`), which is pretty close to our approximation. So that indicates that nothing was going wrong with your test, you were just CPU bound and would need to add more compute resources to scale up the TPS number.

**Comment by nvanbenschoten** [comment]
@XiangXiangHotSpot given that the benchmark appears to be behaving as expected, I'm going to close this issue. Please feel free to continue the discussion here if you have further questions.

**Comment by XiangXiangHotSpot** [comment]
@nvanbenschoten  much appriciation for your responds

Sorry I didn't write the CPU information clearly before,  my single server contains 2 CPUs, each CPU contains 64 cores，so there are 128 cores total in my single server, and the frequency of each core is 2.1GHz , and each NUMA node consist of 8 cores.

An 4-nodes cluster was running in 1 server，each node bounded  16 cores， Namely 2 NUMA node ( detail can be found 
in the database startup command above).  according to your calculation, one ARM core provide 120tps, in my case l would expect 120tps * 4-nodes * 16cores = 120tps * 64cores = 7680,  can you please point out my mistake?

l will tried the --range_selects=false flag,  and post my results later.

**Comment by XiangXiangHotSpot** [comment]
before using the --range_selects=false flag  733.72   tps and 14922.81 qps 
after using --range_selects=false                  1172.64 tps and  18762.89qps.
