### ISSUE TITLE
bazel: compiler errors report a file path inside the sandbox, gets code editor confused

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#76377]
**Describe the problem**

When the source code contains an error, the Go compiler reports the location of the error as the filename, followed by a colon, followed by the line number.

**Editors need to be able to parse the error output and recognize the filename and open the right file to point to the location of the error.**

Currently, bazel copies certain go files inside the sandbox before they get compiled. as a result, error messages report a filename inside the sandbox. for example:

```
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:749:4: undefined: serverStatusMu
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:750:4: undefined: serverStatusMu
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:751:22: undefined: serverStatusMu
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:752:4: undefined: serverStatusMu
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:777:19: undefined: err
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:777:23: cannot assign error to err in multiple assignment
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:778:8: undefined: err
/tmp/tmp.Dx9OXtly/rules_go_work-193404974/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:779:60: undefined: err
```

This breaks the code editor's ability to automatically recognize the error and open the adequate file.

**To Reproduce**

Put a bug inside e.g. `cli/start.go` then build.

**Expected behavior**

The filename in the build error is relative to the source directory, where the editor can find the file.

Epic CRDB-8036

Jira issue: CRDB-13092

**Comment by mari-crl** [comment]
My findings in exploratory debugging:

When not using cgo, there's no need to adjust the paths because they're already correct - they're passed basically straight from the command line, which uses the relative paths. (The files are indeed moved into the sandbox - trimpath expresses as much - but they aren't ) That looks like this:
```
ERROR: /Users/mari/go/src/github.com/cockroachdb/cockroach/pkg/util/arith/BUILD.bazel:3:11: GoCompilePkg pkg/util/arith/arith.a failed: (Exit 1): builder failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-8cb7c8b9f293/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -tags metamorphic_disable,bazel,gss,bazel,gss -src ... (remaining 17 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Non-CGO: -trimpath=/private/var/tmp/_bazel_mari/faae660bbc8a346044012348cf9e269c/sandbox/darwin-sandbox/2610/execroot/cockroach=>github.com/cockroachdb/cockroach
pkg/util/arith/arith.go:32:9: undefined: Add42WithOverflow
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/compile: exit status 2
```

cgo prefixes all files by copying them into a temporary working directory (here: https://github.com/cockroachdb/rules_go/blob/6b3129782f4cd802ecebf91fc0fc08e1be20917b/go/tools/builders/cgo2.go#L61-L68) 

That looks like this:
```
ERROR: /Users/mari/go/src/github.com/cockroachdb/cockroach/pkg/cli/BUILD.bazel:4:11: GoCompilePkg pkg/cli/cli.a failed: (Exit 1): builder failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -tags bazel,gss,bazel,gss -src pkg/cli/absolute_fs.go -src ... (remaining 427 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
CGO: -trimpath=/var/folders/10/hb608jp91vl4384bh0bdyqq80000gq/T/rules_go_work-2472566133/cgo/github.com/cockroachdb/cockroach/pkg/cli=>github.com/cockroachdb/cockroach/pkg/cli
/var/folders/10/hb608jp91vl4384bh0bdyqq80000gq/T/rules_go_work-2472566133/cgo/github.com/cockroachdb/cockroach/pkg/cli/demo.go:243:2: undefined: initGEOS
/var/folders/10/hb608jp91vl4384bh0bdyqq80000gq/T/rules_go_work-2472566133/cgo/github.com/cockroachdb/cockroach/pkg/cli/mt_start_sql.go:123:2: undefined: initGEOS
/var/folders/10/hb608jp91vl4384bh0bdyqq80000gq/T/rules_go_work-2472566133/cgo/github.com/cockroachdb/cockroach/pkg/cli/start.go:571:2: undefined: initGEOS
/var/folders/10/hb608jp91vl4384bh0bdyqq80000gq/T/rules_go_work-2472566133/cgo/github.com/cockroachdb/cockroach/pkg/cli/statement_bundle.go:155:2: undefined: initGEOS
```

Actually trimming the trimpath would cause the error messages to look like this:
```
github.com/cockroachdb/cockroach/pkg/cli/demo.go:243:2: undefined: initGEOS
github.com/cockroachdb/cockroach/pkg/cli/mt_start_sql.go:123:2: undefined: initGEOS
github.com/cockroachdb/cockroach/pkg/cli/start.go:571:2: undefined: initGEOS
github.com/cockroachdb/cockroach/pkg/cli/statement_bundle.go:155:2: undefined: initGEOS
```

As you can see, trimpath is configured to replace the sandbox's root path with the package path, which is probably useful for error messages but not what we want.

No, we want source paths relative to the workspace path. You know, the relative paths we get as input!

Potentially complicating this are the presence of generated source files. The naive method of making this work is to simply replace the temporary directory with the source directory. This will make source files work, and make generated files no more broken (and indeed slightly less broken) than they are now. 

Outputting proper error messages requires replacing the paths of generated files individually with their generated path, then bulk-replacing the temporary directory's path for whatever's left.

Tomorrow I'll look into how complicated it will be to do either or both to the output of go tool compile from inside the builder. I suspect it's joke, but I might need to thread the logs from the command through in some places.

**Comment by mari-crl** [comment]
```
ERROR: /Users/mari/go/src/github.com/cockroachdb/cockroach/pkg/cli/BUILD.bazel:4:11: GoCompilePkg pkg/cli/cli.a failed: (Exit 1): builder failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -tags bazel,gss,bazel,gss -src pkg/cli/absolute_fs.go -src ... (remaining 427 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
pkg/cli/demo.go:243:2: undefined: initGEOS
pkg/cli/mt_start_sql.go:123:2: undefined: initGEOS
pkg/cli/start.go:571:2: undefined: initGEOS
pkg/cli/statement_bundle.go:155:2: undefined: initGEOS
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/compile: exit status 2
```

GoLand, what do you think of this?

![Screen Shot 2022-04-04 at 5 29 28 PM](https://user-images.githubusercontent.com/102245329/161635459-d3d7e873-68c8-4a0a-bd06-6c99dfda2919.png)

Right on.

That's a success! I'll wrap up the PR and send it out soon.

**Comment by knz** [comment]
thank you!

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13092](https://cockroachlabs.atlassian.net/browse/CRDB-13092) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76377` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13092](https://cockroachlabs.atlassian.net/browse/CRDB-13092) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76377`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
