### ISSUE TITLE
backupccl: backup should create new checkpoint/latest file instead of overwriting old checkpoints/latest

### ISSUE THREAD

**Issue by DarrylWong** [cockroachdb/cockroach#76438]
Currently, backup will delete/overwrite the current checkpoint file. By no longer requiring this, we can allow for a no-ransomware policy on backups.

This can be achieved by writing new checkpoint/latest files next to the old ones, and then teaching backup/restore related statements to look for these new checkpoint/latest files instead.

Another side effect of this, is that backing up files will no longer require delete/update permissions, limiting necessary access to the database for a `BACKUP` role / user.

[Epic CDRB-7586](https://cockroachlabs.atlassian.net/browse/CRDB-7586)

Jira issue: CRDB-13122

**Comment by dt** [comment]
Two thoughts: we should put these under some prefix like `progress/` rather than the root. We should also pick names that will sort newest-first on both s3 / gcs, which I think means utf8 byte order / lexicographic.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13122](https://cockroachlabs.atlassian.net/browse/CRDB-13122) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76438`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
