### ISSUE TITLE
kvnemesis: add MVCC range tombstone tests

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#76435]
Once #70415 lands, and #70412 matures, we should add range tombstone tests to `kvnemesis`.

Jira issue: CRDB-13120

Epic CRDB-20465

**Comment by tbg** [comment]
Hit a snag, probably not a show stopper, but DeleteRange is currently only supported in a txn, but we can't have a txn here. See https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-qUv9iLDNMACdaB8

**Comment by tbg** [comment]
This is related to this code for puts:

https://github.com/cockroachdb/cockroach/blob/24c56dffe866f4252556855731041bf4e070f573/pkg/kv/kvnemesis/validator.go#L645-L663

https://github.com/cockroachdb/cockroach/blob/24c56dffe866f4252556855731041bf4e070f573/pkg/kv/kvnemesis/validator.go#L364-L382

A deletion doesn't return the timestamp at which it materialized, so here we have to go in manually and "do stuff" and if we're not in a txn then we don't even know what timestamp to use.

I will need to get more familiar with the validation code to sort out how this should handle the case we want to add here.

@nvanbenschoten and/or @AlexTalks would be grateful for some pointers here. I still have to make a solid effort diving into this, but maybe you two have an idea of what should or can't work right off the bat.

**Comment by tbg** [comment]
I'm going to try adding this as a new request type.

**Comment by erikgrinaker** [comment]
>I'm going to try adding this as a new request type.

I think this is probably the better approach short-term, given that `UseRangeTombstone` mandates non-txnal semantics, but it's possible that we'll hit similar difficulties with it that we'd have to resolve. +1 on getting some advice, but let's not get pulled into anything laborious here.

**Comment by tbg** [comment]
Erik points out that mvcc rangedels are sidestepping some of the problems above since they physically cover the entire range. We likely still need to teach the verifier how to deal with range keys etc but maybe it's mostly elbow grease after all. Would welcome some expert eyes on this.

**Comment by tbg** [comment]
Here's the relevant code explains why non-transactional DeleteRange is not supported (https://github.com/cockroachdb/cockroach/issues/69642):

https://github.com/cockroachdb/cockroach/blob/6ee6501ccce85a0a9ed416f61ba2feab35478e96/pkg/kv/kvnemesis/validator.go#L383-L416

This seems to suggest that a) if we can figure out the write timestamp of the non-txnal operation and b) can synthesize the set of keys affected by the deletion (or just return it with the result to make these tests work) or find a way to somehow store additional information in the (point or range) tombstone, we can make it work.

I also don't yet understand how non-txnal point deletions work, since they also don't get assigned a timestamp:

https://github.com/cockroachdb/cockroach/blob/6ee6501ccce85a0a9ed416f61ba2feab35478e96/pkg/kv/kvnemesis/validator.go#L654-L662
