### ISSUE TITLE
storage: GC error when racing with a split

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7652]
Found while running a loop of "create database; create table; drop database" against an idle single-node server:

```
I160706 14:57:58.767892 storage/replica_command.go:2127  initiating a split of range=1416 [/Table/1309-/Max) at key /Table/1310
W160706 14:57:58.855717 storage/intent_resolver.go:343  could not GC completed transaction: key range /Table/1309-/Max outside of bounds of range /Table/1309-/Table/1310
```

Requested by @bdarnell:
"""
file an issue for that transaction gc message. it’s harmless, but we can do better by making the intentResolver always use the DistSender instead of blindly writing to its local range (which may no longer be the right one if we’re racing with a split) 
"""

**Comment by bdarnell** [comment]
Pulling on the thread of this message has turned up some interesting things. The message itself is straightforward: if we split several times in succession, a split may race with the asynchronous cleanup of an earlier split's intents and transaction record. This is because `intentResolver` attempts to GC the transaction record by talking to the `Replica` directly instead of going through `DistSender`, which would have found the correct range and retried automatically.

`intentResolver` talks to `Replica` directly for two things: GCing transaction records (which can easily be change to use DistSender) and for resolving intents in a halfway-synchronous way. The first we should definitely fix, and I'm inclined to get rid of the second too, even though it may improve latency a bit under contention. We should generally avoid calling `Replica.addWriteCmd` directly for a number of reasons.

Next, it turns out that even when we don't see this message, we are not able to successfully GC most transaction records created by splits. This is because the split transaction is anchored on the range descriptor for the right-hand side of the split, so the range ID that houses this record changes when the split commits. Again, using DistSender instead of talking to the replica directly would allow the transaction record to be found correctly. However, that's not ideal: putting the transaction record on the right-hand side of the split means that its external intents cannot be resolved until the RHS has completed its first election and range lease. It would be better to anchor the split transaction on the LHS range descriptor, unless there is some reason why the RHS must be used (I can't think of one).

In most cases, this failure is silent instead of logging a message like the above because `intentResolver` constructs an inconsistent request (a key in the payload is outside the range specified in the batch header), but the GC request checks for this inconsistency and silently skips those keys. It should instead fail noisily, and the `intentResolver` should use more standard patterns instead of constructing batches by hand.

Finally, there is one case in which we *can* GC transaction records: when we split range 1, the meta records are local to the range, so there are no external intents and the entire transaction can be GC'd synchronously. This suggests a weak spot in our testing: many of our split tests only split range 1, which behaves a bit different from other splits. We should create default splits at the end of meta1 and meta2 so that these edge cases are experienced in all cases instead of being delayed until a cluster has grown large enough.

**Comment by bdarnell** [comment]
I tried to make the GC method stricter about what keys it accepts, but ran into roadblocks which I've filed separately as #7880.

Swapping the order in which AdminSplit touches the range descriptors leads to the stats being inconsistent with recomputation. I'm still investigating what's going on there.

**Comment by tschottdorf** [comment]
It's expected that you'd need to jiggle the stats around a bit. Note that `EndTransaction` resolves all intents local to both RHS and LHS of the Split. That leads to some awkward computations that probably need some adjustments (though I can't immediately point the finger at what changed).

**Comment by spencerkimball** [comment]
Found the problem. Looks like we weren't flushing the batch iterator when computing stats.
