### ISSUE TITLE
Add SQL Admission stats to Datadog Integration

### ISSUE THREAD

**Issue by whatdoidoherereally** [cockroachdb/cockroach#76600]
**Is your feature request related to a problem? Please describe.**
My company recently decided to enable SQL admission to help stabilize the cluster, but noticed that datadog is not retrieving the stats for SQL Admission (such as wait, delay, and counts) for our clusters. It seems like SQL Admission is a good area to watch for a potentially overloaded cluster to alert our operations group, so it would be good to add these metrics to the datadog agent so they can be slurped from the prometheus endpoint.

**Describe the solution you'd like**
Datadog agent is able to consume and report SQL Admission metrics into Datadog for monitoring and alerting.

**Describe alternatives you've considered**
We could consume directly from the prometheus endpoint via a custom sidecar to the pod, but that seems tedious compared to natively consuming from the datadog agent.

**Additional context**
For clarity, we are running CockroachDB Core 21.2.3 in Kubernetes.

Epic CC-3352

Jira issue: CRDB-13188

**Comment by jalexbarbour** [comment]
I do see the list of supported metrics at https://github.com/DataDog/integrations-core/blob/master/cockroachdb/datadog_checks/cockroachdb/metrics.py, and am happy to open a PR to add in the desired metrics here, but figured I'd ask you all what metrics you'd want to see added here before I do it, or if you all are already on it :D

**Comment by abarganier** [comment]
Just noting here that we've also seen interest in the following storage metrics being exported via the Datadog Agent:
- `sys_host_disk_read_bytes`
- `sys_host_disk_write_bytes`

**Comment by whatdoidoherereally** [comment]
@abarganier appreciate the nudge, sorry it fell off my radar :). I don't have the specific names handy at the moment, but it would be good to start with the metrics that are provided in the CRDB console's dashboard showing the rate, as that indicates when a cluster may be approaching a "hot" situation.

**Comment by abarganier** [comment]
@whatdoidoherereally no problem, that is still helpful! If possible, could you name the specific charts you're referring to? I can easily identify specific metrics that way :) 

I appreciate the follow up!

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13188](https://cockroachlabs.atlassian.net/browse/CRDB-13188) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76600`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
