### ISSUE TITLE
sql: support super regions

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#76622]
We can create super regions for a database using the following syntax.

ALTER DATABASE movr ADD SUPER REGION europe VALUES "europe-north1", "europe-west1", "europe-central2";

Super regions must only specify regions that are already part of the database.

Regional and Regional By Row Tables
Adding a super region causes regional and partitions of regional by row tables homed in that partition to have their replicas be homed in that super region.
If the super region “Europe” corresponds to (“eu-east1”, “eu-west1”), any regional tables or partitions of regional by row tables belonging to either “eu-east1” or “eu-west1” will have their voters and non-voters both restricted to (“eu-east1”, “eu-west1”).

Jira issue: CRDB-13194

Epic CRDB-2533

**Comment by rafiss** [comment]
closing this and tracking follow up work in https://github.com/cockroachdb/cockroach/issues/77454

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13194](https://cockroachlabs.atlassian.net/browse/CRDB-13194) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76622`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
