### ISSUE TITLE
Highlight values that are different from the default in cluster settings

### ISSUE THREAD

**Issue by lidorcarmel** [cockroachdb/cockroach#76626]
**Is your feature request related to a problem? Please describe.**
It's hard to see which cluster settings currently have a value which is different from the default when using the UI.

**Describe the solution you'd like**
When navigating to the cluster settings page (under /#/reports/settings), have a view that only shows the cluster settings that have a value different from the default, and another view for all settings as we have today. Probably the default view should be the new one.

**Describe alternatives you've considered**
I guess highlighting the values that are different from the default is also an option, but it's along scroll so it's easy to miss. In practice I think the main reason to look at settings is to get those values. The defaults are rarely interesting IMO.

**Additional context**
This is how it looks now:
<img width="941" alt="Screen Shot 2022-02-15 at 11 39 53 AM" src="https://user-images.githubusercontent.com/51982110/154136348-3180fa54-4131-440b-b714-617d609d810d.png">

Jira issue: CRDB-13198

Epic CRDB-13054

**Comment by Santamaura** [comment]
Would using https://github.com/cockroachdb/cockroach/blob/a1c1879e01ceee79a81693c67a1dba184b5fc1b1/pkg/settings/cluster/cluster_settings.go#L59 work?

**Comment by lidorcarmel** [comment]
another option can be to have 2 separate tabs maybe? one for the settings that have a value different from the default and one tab for everything.

**Comment by lidorcarmel** [comment]
changed the language of this issue to not use "overridden", it's a bit awkward but hopefully less confusing.
and thanks Alex for looking into this!!

**Comment by Annebirzin** [comment]
@Santamaura @lidorcarmel  I was just looking into [designs](https://www.figma.com/file/kuHnlLQhq9b6itkqX6iRf0/22.1_obsrv-dbconsole-updates?node-id=1378%3A788) for this issue. I'm thinking maybe we could keep everything in one table, but update the table to add a column for 'Last override date'.

The default sort would be by override date (rather than alphabetical as it is today), so all settings with overrides would appear at the top (most recent override first). The 'Setting' column could also include an alphabetical sort so users can still see settings alphabetically. 

These designs would also include an update to our current table styles (including adding a column sort option). 

thoughts? 

<img width="1597" alt="Screen Shot 2022-03-16 at 4 10 36 PM" src="https://user-images.githubusercontent.com/51920721/158681790-fc2af1f9-c43b-43e8-89c6-f191e6e0cb81.png">


cc @thtruo

**Comment by thtruo** [comment]
I had a conversation with TSEs just now - they reacted positively to the proposed designs. They're okay with having the "last override date" and sorting the view to see all non-defaults at the top.

**Comment by ajwerner** [comment]
Designs which require adding new state to the database (like when something was set) are great, but are also take much longer as we'll need to wait a major version release and even then we won't have this data moving backwards. 

For something we can do quickly and use quickly, we have a boolean and just a boolean.

**Comment by Santamaura** [comment]
> For something we can do quickly and use quickly, we have a boolean and just a boolean.

If we instead do `SELECT * FROM system.settings` we could grab the 3rd column (which is the last updated TS ) and return that couldn't we?

**Comment by ajwerner** [comment]
😓 I'm sorry, I didn't realize we had that. I appologize.

**Comment by Santamaura** [comment]
No problem 😄

**Comment by lidorcarmel** [comment]
having the last override date sounds super useful, to see if the change time correlates with the issue we're debugging. and of course one table is better than 2.. thank you :)
