### ISSUE TITLE
backupcl,cloud: support AWS AssumeRole for backup & restore  

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#76708]
**Is your feature request related to a problem? Please describe.**

Customer is moving backups into their own dedicated S3 bucket and AWS account. With instance identity, the customer can use [`AssumeRole`](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) and push backups to a different account easily and not worry about credential management.

**Describe the solution you'd like**

When a user runs the backup command, the following would be passed to CockroachDB

* The IAM user
* The S3 bucket destination
* The user role for `AssumeRole`

CockroachDB would know how to receive the token, and then use that token to write the backup to the aforementioned S3 bucket.

**Describe alternatives you've considered**
N/A

Jira issue: CRDB-13243

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13243](https://cockroachlabs.atlassian.net/browse/CRDB-13243) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76708`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done
