### ISSUE TITLE
import: track and rollback imported data without timestamps

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#76722]
Currently if an IMPORT writing data into an existing, non-empty cluster fails or is cancelled mid-IMPORT, to roll it back, any rows it had written are found and deleted by scanning the table for rows with a timestamp greater than the time at which the IMPORT started. This works since the table is offline to other writes while it is importing, but relies on the fact that the timestamps on rows do not change -- which may not be true if the table were backed up and then restore, after which all keys, both existing and imported, would have times based on when it was restored. Today this is a non-issue as importing tables are not included in backups and are not restored, but we would like to change this, which will thus require finding and rolling back rows imported by a failed import without relying on their MVCC timestamps to have any particular value.

Instead, we should add a field to roaches.Value that can be used to mark values imported by a specific IMPORt, and then later, if we need to rollback that IMPORt, find those values and delete them. This new field could be an arbitrarily tag collection. Being a top-level field will make it easier to do predicate push-down to the likes of DeleteRange so it could be told to delete all rows with this marker value without needing to know how to dig into the packed Value field itself.

Jira issue: CRDB-13248

Epic CRDB-14921

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13248](https://cockroachlabs.atlassian.net/browse/CRDB-13248) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76722`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done

**Comment by msbutler** [comment]
closing, as work will now get tracked in #86054
