### ISSUE TITLE
storage: TestMultinodeCockroach is dead slow waiting for replication

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#7689]
`TestMultinodeCockroach` sometimes runs fast, sometimes takes 30s, sometimes takes 60s.
It's the "waiting for replication" that's slow, and it doesn't seem to be because of #7297.

I looked at logs with Tobi and it seems that, when the waiting is eventually unblocked, it's soon after a gossip update. So a theory is that the gossip update triggers the replication queue, because the range needing replication was in the purgatory. And maybe this happens because there's a race in adding stores and somehow the initial gossiping that happens when a store is added (which should advertise the fact that the store is ready to receive ranges) doesn't correctly advertise that.

**Comment by petermattis** [comment]
FWIW, I had a small test program that started a 3-node cluster (using 3 separate processes) and waited for the initial replication to finish. Last week it was taking 1s. That should be the number we're targeting for `TestMultinodeCockroach`.

**Comment by andreimatei** [comment]
The (now skipped) test has been renamed to `TestWaitForFullReplication`

**Comment by petermattis** [comment]
Ok. I'll take a look at this today (or tomorrow).

**Comment by petermattis** [comment]
If I disable creation of the `Testing` database and the various SQL operations, `TestMultinodeCockroach` reliably passes in less than 4s, usually in less than 3s. 

With the `Testing` database creation left in, `TestMultinodeCockroach` hangs waiting for all of the stores to have 6 replicas. This is curious because there are only 5 initial ranges. Somehow creation of the `Testing` database is creating a 6th range which isn't getting replicated quickly.  Two things to track down are why that 6th range is being created (it could just be a lack of understanding on my part) and why it is taking so long to replicate while the other 5 ranges replicate quickly.

**Comment by petermattis** [comment]
If I disable creation of the `Testing` database and the various SQL operations, `TestMultinodeCockroach` reliably passes in less than 4s, usually in less than 3s. 

With the `Testing` database creation left in, `TestMultinodeCockroach` hangs waiting for all of the stores to have 6 replicas. This is curious because there are only 5 initial ranges. Somehow creation of the `Testing` database is creating a 6th range which isn't getting replicated quickly.  Two things to track down are why that 6th range is being created (it could just be a lack of understanding on my part) and why it is taking so long to replicate while the other 5 ranges replicate quickly.

**Comment by petermattis** [comment]
Ah, `SystemConfig.ComputeSplitKeys` will split the last range based on the largest object ID in the `system.descriptor` table. It doesn't check to see if that largest object ID refers to a table or a database. So a 6th range is expected when the `Testing` database is created.

**Comment by petermattis** [comment]
Hmm, this is suspicious. When the hang occurs, I see:

```
I160713 08:17:27.710338 storage/replica_command.go:2195  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
```

But the split never completes. Still trying to understand what is happening here. Looks like there is some intent resolution failing. And I see:

```
E160713 08:17:29.808071 storage/replica.go:1880  [node=1,store=1,range=5] error executing raft command: storage/replica.go:1821: command observed at lease index 11, but required <= 12
I160713 08:17:29.808102 storage/replica.go:1869  applying command with forced error: storage/replica.go:1821: command observed at lease index 12, but required <= 12
I160713 08:17:29.808225 storage/replica.go:1869  applying command with forced error: storage/replica.go:1821: command observed at lease index 11, but required <= 12
E160713 08:17:29.808250 storage/replica.go:1880  [node=1,store=1,range=5] error executing raft command: storage/replica.go:1821: command observed at lease index 12, but required <= 12
E160713 08:17:29.808433 storage/replica.go:1880  [node=2,store=2,range=5] error executing raft command: storage/replica.go:1821: command observed at lease index 11, but required <= 12
I160713 08:17:29.808481 storage/replica.go:1869  applying command with forced error: storage/replica.go:1821: command observed at lease index 12, but required <= 12
E160713 08:17:29.808651 storage/replica.go:1880  [node=2,store=2,range=5] error executing raft command: storage/replica.go:1821: command observed at lease index 12, but required <= 12
```

@bdarnell, @tschottdorf Are those errors problematic?

**Comment by tschottdorf** [comment]
No, these shouldn't be problematic (unless you see a flurry of them with ever-ascending numbers in them). BTW, try a rebase - the error message for this error was fixed up yesterday (it will now say `12, but required < 12`).

**Comment by petermattis** [comment]
Looks like there is a race in this test between replicating and splitting. If either occurs first everything is fine. But if the replication occurs concurrently but slightly before the split, the split will fail because the descriptor has been updated:

```
E160713 08:36:27.493412 storage/queue.go:475  [split] on range=5 [/Table/14-/Max): unable to split range=5 [/Table/14-/Max) at key "/Table/50/0": storage/replica_command.go:2251: split at key /Table/50 failed: unexpected value: raw_bytes:"0~i\223\003\010\005\022\001\226\032\002\377\377\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\002(\003" timestamp:<wall_time:1468413386005320063 logical:0 >
```

Usually we don't try to replicate when a split is necessary, but it is all about specific timing in this test. The `Testing` database needs to be created at precisely the right time so that `range=5` is already queued for replication. 

When this happens, we don't retry the split until the next scanner cycle. Thoughts on what to do here? We could have the split queue retry failed splits a handful of times. We could try to add replicas to the split queue after replication just as we add replicas to the replicate queue after splitting.

**Comment by petermattis** [comment]
Add a call to `splitQueue.MaybeAdd` in `Replica.changeReplicasTrigger` allowed `TestMultinodeTest` to pass 100 times in a row with the max runtime of 5.2s. I'll send out a change for review in a bit.
