### ISSUE TITLE
changefeedccl: remove tenant gates on pts management once pts works on serverless

### ISSUE THREAD

**Issue by samiskin** [cockroachdb/cockroach#76936]
Once #73727 is complete we need to delete any gates we have on protected timestamp management that restrict it to the system tenant (see `shouldProtectTimestamps` in `pkg/ccl/changefeedccl/changefeed.go`)

Jira issue: CRDB-13335

**Comment by shermanCRL** [comment]
@samiskin is this a dependency for MarkIdle, and the ability to shut down a pod? cc @ajstorm

**Comment by samiskin** [comment]
> @samiskin is this a dependency for [MarkIdle](https://github.com/cockroachdb/cockroach/issues/74747), and the ability to shut down a pod? cc @ajstorm

Nope, the idle tracking is independent from protected timestamps

**Comment by ajstorm** [comment]
The issue here isn't necessarily whether or not the two are related, but rather, whether we need _both_ of them to allow tenant pods to shutdown when they have a CF enabled.

In talking with @stevendanna, he agreed that we needed both, in which case my question is around whether or not this one will also land in 22.1.

**Comment by arulajmani** [comment]
Headsup, everything in https://github.com/cockroachdb/cockroach/issues/73727 is wired up end to end; there's a few small followup items but they shouldn't preclude you from making progress on this.
