### ISSUE TITLE
bazel: staticcheck unused lint not catching some failures

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#76933]
Compare two CI runs, non-Bazel and Bazel, at the same commit:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4432500?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4432517?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

The Bazel CI should be finding the following unused errors:

```
=== RUN   TestLint/TestStaticCheck
    lint_test.go:1733:
        pkg/cmd/publish-artifacts/main.go:53:2: var latestStr is unused (U1000)
    lint_test.go:1733:
        pkg/cmd/publish-artifacts/main.go:126:6: func buildOneWorkload is unused (U1000)
    --- FAIL: TestLint/TestStaticCheck (855.48s)
```

Epic CRDB-8036

Jira issue: CRDB-13332

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13332](https://cockroachlabs.atlassian.net/browse/CRDB-13332) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76933`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rickystewart** [comment]
@ajwerner I've been looking at this. A lot of stuff that is literally unused is not detected by the `unused` lint that does run in GitHub CI. For example, as far as I can tell, exported (public) functions are NEVER identified as unused, even if it's trivially true that they are.

For Bazel CI support, I want to get to parity with what we currently have in GitHub CI.
