### ISSUE TITLE
streamingccl: define job behavior post-cutover and implement it

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#76953]
Currently, many jobs store spans which contain tenant prefixed keys in their payloads or progress.

When we replicate the contents of this table to a new tenant, those spans are invalid. We need to do something about that.

Since we don't know what the keys we are processing are related to on ingestion, it might be cleanest to never store tenant prefixed spans in jobs and solve the problem by not having the problem. Alternatively, we can fix up all the jobs before bringing the tenant online.

We may have fixed this when working on cross-tenant-id restore.  But let's make sure we didn't miss anything.

Further, it may be the case that some jobs simply do not make sense to continue in the new cluster. We should define how the various job types will behave post cutover.

Jira issue: CRDB-13344

Epic CRDB-18753

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13344](https://cockroachlabs.atlassian.net/browse/CRDB-13344) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76953` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13344](https://cockroachlabs.atlassian.net/browse/CRDB-13344) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-76953`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually synced and updated

**Comment by stevendanna** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/73800

**Comment by shermanCRL** [comment]
Still planning on this? @gh-casper mentions we will want this earlier than later (i.e. v22.2).
