### ISSUE TITLE
kvserver: use replica liveness for leases instead of node liveness

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#77035]
Currently, lease liveness is determined by node liveness, and a lease is only relinquished if the node fails to heartbeat. However, this misses a whole class of failures where the leaseholder replica is unable to make progress, but the leaseholder's node is heartbeating just fine. Examples include e.g. deadlocks, application failures, partial network outages, and more.

Instead, we should have a mechanism where the leaseholder replica must actively signal liveness in order to hold onto the lease, such that any failure causes it to passively lose the lease, similarly to how Raft leadership works. Note that the current node-level liveness was implemented to avoid the overhead of explicitly heartbeating hundreds of thousands of leases, so we should attempt to collapse/combine these signals somehow for all leases on a node.

Related to #75944.

Jira issue: CRDB-13379

Epic CRDB-14573

**Comment by ajd12342** [comment]
Hi @erikgrinaker !
I am Anuj Diwan, a Computer Science PhD student at UT Austin. I am part of a team along with @arjunrs1 (Arjun Somayazulu) and we're taking a graduate [Distributed Systems course](https://github.com/vijay03/cs380d-f23). For our course project, we are interested in contributing to CockroachDB. This issue is related to our course material. Could we work on this issue? Any pointers for us to get started would be appreciated as well. 

Thanks and regards,
Anuj.

**Comment by erikgrinaker** [comment]
Hi @ajd12342! This is a complex issue that requires a lot of context and design work, so I don't think it's suitable for external contributors to pick up. You may be more interested in a simpler issue, like https://github.com/cockroachdb/cockroach/issues/99783.

**Comment by nvanbenschoten** [comment]
Will be addressed by https://github.com/cockroachdb/cockroach/issues/123847.
