### ISSUE TITLE
UNIQUE constraint makes different impacts on DELETE statement

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#77086]
I try the following case in Cockroach v21.2.6:
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 INTERVAL UNIQUE);
INSERT INTO t0 VALUES(null);
DELETE FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds');
```
The DELETE statement throws an overflow error. I think there should be no errors in the above case, because the row value is NULL, and it's no need to do the rest comparison. 
 When I remove the column constraint UNIQUE like follows:
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 INTERVAL);
INSERT INTO t0 VALUES(null);
DELETE FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds');
```
The DELETE statement succeeds, and no error happens.

Jira issue: CRDB-13407

**Comment by sayJason** [comment]
I try the same where clause as follows:
```sql
SELECT c0 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 s
econds');
UPDATE t0 SET c0 = null WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minut
es 1 seconds');
```
They both behave like the DELETE statement, when the UNIQUE constraint is added, they all throw an overflow error, and when there is no UNIQUE, they do not throw errors.
I want to know is the same where clause having the same evaluation process in different statements? Thanks!

**Comment by cucaroach** [comment]
For reasons I don't understand we only attempt to construct a constrained span for this query when the index is unique and since we can't encode this out of bounds Interval as a scan key we fail when the index is unique.   The devil in the details is that we can construct Interval values like this but only "enforce" the boundaries when we have to encode one of these values so sometimes they slip through the cracks.   The problem will go away when #45993 is fixed.
