### ISSUE TITLE
bazel: archive prebuilt versions of `krb5`, `geos`

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#77135]
In CI, when the build is cold (it usually is), tests are often bottlenecked on building these two libraries. The logic tests can't start without them and they take a very long time to run, so we can work around the problem by avoiding the build altogether and just downloading prebuilt versions.

`krb5` only needs a Linux build. `geos` needs a Linux build to get the CI advantages but we might just expose it for all OS's so everyone can download a prebuilt version.

Epic CRDB-8306

Jira issue: CRDB-13427

**Comment by petermattis** [comment]
I would expect remote caching to work very well for `krb5` and `geos` which change very rarely. Is that what you're suggesting with downloading prebuilt versions?

**Comment by rickystewart** [comment]
@petermattis This bug isn't about remote caching but about pre-building these assets and adding logic to the Bazel build such that the artifacts can be downloaded rather than built if possible. I agree remote caching should cover these situations but adding an ad-hoc optimization for these libraries could be a quicker win that doesn't require us to get remote caching set up for either CI or developers to get benefits.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13427](https://cockroachlabs.atlassian.net/browse/CRDB-13427) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77135`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
