### ISSUE TITLE
catkv: public and temp schemas should be included in nstree.Catalog returned by `query`

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77160]
This would mean that `query` exhaustively lists all catalog data contained in both `system.namespace` and `system.descriptor`. Presently this is true except for public and temporary schemas; these are special in that they have entries in `namespace` but not in `descriptor`. There's no good reason for this, this is entirely a historical accident.

A bit of context. This `query` method is now the single point of entry to the stored catalog, but until recently this wasn't always the case. There used to be a `catalogkv` package which freely exposed this functionality. Furthermore, `public` schemas have recently undergone changes too, they used to _all_ only exist as namespace entries and, worse than temp schemas, didn't even have distinct IDs (it always was 29). @RichardJCai did a lot of work in the 22.1 release cycle to endow these public schemas with proper descriptors just like any other schema. I believe that at this point, synthetic public schemas only exist to support restoring old backups, and perhaps the system database also I don't know.

This change isn't as simple as it seems and will have many cascading effects in downstream dependencies of `catkv`:
- validation might be weird and might not be expecting these synthetic descriptors,
- `descs.Collection` which is another client of `catkv` also isn't expecting these, and in fact has a bunch of crufty code to work around their absence, which will have to be removed.
- `desctestutils` might also be confused, I don't know.

This issue would resolve https://github.com/cockroachdb/cockroach/issues/57619 , which I'm now closing as a duplicate.

Jira issue: CRDB-13442

**Comment by ajwerner** [comment]
> and perhaps the system database also I don't know.

Correct, the system database. I'd go so far as to suggest that we call the synthetic public descriptor the `SystemPublicSchemaDescriptor` in the next release.

**Comment by Xiang-Gu** [comment]
Afte some digging, here are my findings:

1. method `query` in "catalog_query.go" does not specify logic on what to retrieve from the `system.descriptor` and `system.namespace` table. All that is written in the third argument passed into `query`, so it's not necessarily that `query` method only exhaustively lists entries contained in both tables, but rather how the caller of `query` specified that logic. I think the relevant caller is `GetCatalogUnvalidated` where we can see it has logic to scan both tables.

```
func GetCatalogUnvalidated(...) (...) {
	...
	return cq.query(ctx, txn, func(codec keys.SQLCodec, b *kv.Batch) {
		...
		b.Scan(descsPrefix, descsPrefix.PrefixEnd())
		...
		b.Scan(nsPrefix, nsPrefix.PrefixEnd())
	})
}
```

2. Going back to #57619, the reason that temporary schemas are not shown is *not* because `GetAllDescriptors` (in "collection.go") does not return temporary schemas. It does. But the very next line uses only `byID` mapping and thus dropped entries that only exist in `byName`. I have verified this myself by printing out `all` and `descs`.
```
    all, err := p.Descriptors().GetAllDescriptors(ctx, p.txn) // does return all descriptors, including temporary ones
    descs := all.OrderedDescriptors() // unfortunately this uses `byID` mapping and hence dropped entried contained in `byName` but not in `byID`.
```

3. With the digging listed above, it seems to me we don't need to modify `query` and should close this issue without any action. We should go back and fix #57619 by adding logic to the generator of `crdb_internal.tables` such that it also includes entries in `byName` mapping.

Let me know if I missed anything

**Comment by ajwerner** [comment]
I think what's changed since this issue was written is that we've re-arranged the logic to be more appropriately layered. 
Looking more closely at this issue, I'm going to disagree with the framing: instead of doing anything in `catkv`, we should fix this in the `descs.Collection` layer. That thing should augment what it gets back from catkv with the appropriate additional schemas. It shouldn't need to do much of anything in order to do that, it already has the knowledge of the existence of these thing in memory. The temp schemas are represented in `(*descs.Collection).temporary` and the synthetic public schema only now exists for the system database, so it can just be added with no concern. One nuance that at first worried me was that we'd need to invalidate the `allDescriptors` data structure when new temp schemas are created, but fortunately there's no syntax to create a temp schema, it just happens when you add a new temp object in a database that did not previously have any.

So, I think the answer here is to avoid touching `catkv` at all and instead move the `allDescriptors` cache up out of `kvDescriptors` (for the time being, eventually we'll be hopefully getting rid of it entirely in the work to accomplish https://github.com/cockroachdb/cockroach/issues/64673), and to augment the return value from `catkv.GetCatalogUnvalidated` with the appropriate schemas.

One last nuance is whether we should show temp schemas from other sessions. I don't think we should. If we did, this issue would be a bit harder. We should see what postgres does, but I'm pretty sure they are isolated per session.

**Comment by ajwerner** [comment]
@postamar does that make sense to you?

**Comment by ajwerner** [comment]
Are we sure we should be showing temp schemas from other sessions?

**Comment by ajwerner** [comment]
I do like the idea of making temp schemas deal on descriptors from a purity perspective. How and when to get those descriptors out and add them to the returned catalog remains unclear to me.

**Comment by postamar** [comment]
I think one scenario is, given a database `db` owned by a regular user which currently has a session with a temp schema, a superuser may still swoop in and `DROP DATABASE db CASCADE`.

I encountered something like that in a logic test while debugging DROPs in the declarative schema changer after I rewrote scbuild, so it's possible that this need only ever manifests itself there.

**Comment by postamar** [comment]
Closing in favour of https://github.com/cockroachdb/cockroach/issues/77953.
