### ISSUE TITLE
kv: Support byte size pagination with intent resolution

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#77228]
Intent resolution currently supports `MaxSpanRequestKeys` pagination, but not `TargetBytes` pagination. This means that if each intent is costly to resolve[^1], an intent resolution batch of 100-200 intents ([100 for point resolution](https://github.com/cockroachdb/cockroach/blob/12c968fd34e2347cc10bde75e8501a1e4431fa15/pkg/kv/kvserver/intentresolver/intent_resolver.go#L63), [200 for ranged resolution](https://github.com/cockroachdb/cockroach/blob/12c968fd34e2347cc10bde75e8501a1e4431fa15/pkg/kv/kvserver/intentresolver/intent_resolver.go#L74)) can exceed `kv.raft.command.max_size`.

To address this, we'll need to add byte size pagination to point and ranged intent resolution (`ResolveIntentRequest` and `ResolveIntentRangeRequest`).

We'll also need to add support for such pagination to `requestbatcher`, like we did in https://github.com/cockroachdb/cockroach/commit/cf11645a5d969e09ccdf2841c4e78ffa7d4e28db with `MaxKeysPerBatchReq` for key pagination.

[^1]: for instance, its value may need to be [rewritten](https://github.com/cockroachdb/cockroach/blob/12c968fd34e2347cc10bde75e8501a1e4431fa15/pkg/storage/mvcc.go#L3059) due to an updated timestamp,

Jira issue: CRDB-13492

Epic CRDB-16159

**Comment by erikgrinaker** [comment]
Related to #77270.

**Comment by nvanbenschoten** [comment]
When we address this, we should also do something about https://github.com/cockroachdb/cockroach/issues/77270.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13492](https://cockroachlabs.atlassian.net/browse/CRDB-13492) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77228` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13492](https://cockroachlabs.atlassian.net/browse/CRDB-13492) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77228`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
