### ISSUE TITLE
kvserver: provide escape hatch for per-replica proposal quota pool

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#77251]
**Is your feature request related to a problem? Please describe.**

We've observed instances where a single node/store that gets into high read-amp regimes is able to affect cluster-wide performance for foreground traffic. Draining these nodes to shed leases can help stave off write pressure and allow compactions to catch up, but it's still possible for follower replicas to cause impact. One avenue for this is our use of proposal quota pools: we maintain one per-range to limit how far ahead a majority quorum can get relative to the slowest replica in the group. 

https://github.com/cockroachdb/cockroach/blob/f9dee666fbb1b78bbdeb803b0d55fc6b2bc4c784/pkg/kv/kvserver/replica.go#L568-L574

The quota pool is helpful in making sure that we're not spending all our time generating snapshots to catch up slow replicas. But when a replica is on a sick node and we're looking to limit its blast radius, it works against us. It's possible then for a slow replica (say on one of these high read-amp nodes) to throttle writes to the corresponding ranges. 
https://github.com/cockroachdb/cockroach/issues/75978 is relevant.

**Describe the solution you'd like**

It would useful to have the ability to disable the quota pool out-of-band during escalations, and/or control dynamically how far ahead a majority quorum can get before throttling writes. Strawman: We could power this through a hidden cluster setting, or a more targeted `crdb_internal` built-in to select only specific ranges.

Jira issue: CRDB-13499

Epic CRDB-15069

**Comment by petermattis** [comment]
It has been a long time since I looked at the proposal quota code, but my recollection was that a replica that was too far behind was not considered part of proposal quota and wouldn't hold up the range. Is that not the case? Or perhaps I had thought that we should make proposal quota work that way, but we never did?

**Comment by petermattis** [comment]
> So a node that just slows down will always keep up the quota pool. If a node is down, it will be ignored for the purposes of releasing quota, meaning that when it comes back (and is very far behind) it doesn't satisfy condition three and is thus ignored until it catches up into the quota pool window (this may never happen, but that's a different story).

This behavior is a bit strange. A slow node can keep a range perpetually slow, but if we temporarily kill the node the replica can fall out of the quota pool window and the replica will be ignored for proposal quota until it catches up.

> When a follower is slow and falls back "as much as possible", it seems possible for a log truncation to cut that follower off. It would then continue to be tracked in the quota pool, effectively stalling writes to the range until the snapshot is through. That doesn't seem ideal. Neither does "indefinitely" waiting for a slow node in general. One could consider setting a "leniency", i.e. saying that we'll wait for followers only if they manage to catch up on the log at a rate of X kb/s or something like that. But that's yet another knob.

And this is where my memory was incorrect. I thought we were already excluding very far behind replicas from proposal quota. I can see the challenges in tuning heuristics to do this, though. We get the heuristics wrong and we get into the snapshot-death-spiral loops. Perhaps the current heuristics are right for proposal quota and we should be looking at other mechanisms (e.g. rebalancing heuristics) to fix ranges with one slow replica.

> @irfansharif what if we stopped taking followers that are draining into account for the proposal quota computation (i.e. add a fourth condition: is not draining).

Couldn't that also lead to snapshot-death-spirals? The draining node falls behind and needs a snapshot, we catch it up, but it again falls behind (it is draining for a reason, right?), so we send it another snapshot. This keeps happening and we're consuming more resources than if we'd just slowed down writes to the range.

**Comment by joshimhoff** [comment]
>  what if we stopped taking followers that are draining into account for the proposal quota computation (i.e. add a fourth condition: is not draining).

Is it correct (or roughly correct) to say that today drained nodes are normal nodes except that they don't hold leases? With this change, IIUC draining a node increases the likelihood of that node falling behind on applies, which could lead to LOQ issues down the line, if another node is lost due to infra issues or similar. Right? 

If an operator is willing to do a drain that increases the likelihood of that node falling behind on applies, why not just go all the way & take the node offline, as was discussed at https://github.com/cockroachdb/cockroach/issues/73763?

> Couldn't that also lead to snapshot-death-spirals? The draining node falls behind and needs a snapshot, we catch it up, but it again falls behind (it is draining for a reason, right?), so we send it another snapshot.

Maybe this is a silly Q, but do we need to be sending snapshots to a drained node at all? Ties into the above point.

> Draining these nodes to shed leases can help stave off write pressure and allow compactions to catch up, but it's still possible for follower replicas to cause impact. One avenue for this is our use of proposal quota pools: we maintain one per-range to limit how far ahead a majority quorum can get relative to the slowest replica in the group.

I brought this failure mode up in the thread in #kv, but how often have we seen it happen in practice?

**Comment by irfansharif** [comment]
> A slow node can keep a range perpetually slow, but if we temporarily kill the node the replica can fall out of the quota pool window and the replica will be ignored for proposal quota until it catches up.

+1. This specifically is what I wanted this issue to focus on. It seems backwards to me to have to resort to taking a node offline just to circumvent the quota pool. Perhaps we wouldn't need to if we had a more direct control knobs. I expect this knob to only feature in escalations.

> what if we stopped taking followers that are draining into account for the proposal quota computation (i.e. add a fourth condition: is not draining).

My inclination is to not overload the draining state in this way. The current semantics of "draining sheds all leases + rejects new conns", though imminently useful, seems to consistently trip up lots of folks when super imposed with membership states (decommissioning, decommissioned, active). I have the

 I was trying to understand why internal customers has found draining+decommissioning insufficient and have to resort to taking the node offline (#73763). This avenue of slow+drained+decommissioning node still affecting cluster performance through the quota pool was the only thing I could think of.  If we provide the escape hatch this issue suggests + fix #74691, I think "draining + decommissioning" _should_ be sufficient to quarantine a node entirely.

> If an operator is willing to do a drain that increases the likelihood of that node falling behind on applies, why not just go all the way & take the node offline, as was discussed at https://github.com/cockroachdb/cockroach/issues/73763?

- We’re in a fragile state, another node going offline could cause unavailable ranges. Maybe not so bad given we retain the ability to bring the node back up. Still, not great.
- We can only use this technique for one node at a time. When we’ve seen escalations with high-readamps, its common to see more than one node being affected.
- Taking a node down to upreplicate its contents should be no faster than just draining+decommissioning that node. The leaseholders for ranges on that node are elsewhere, and today snapshots are generated only by leaseholders. So we're not helping MTTR by taking the node down. If taking a node down is faster for whatever reason, that sounds like a bug.

**Comment by irfansharif** [comment]
Here's what I really want to understand about https://github.com/cockroachdb/cockroach/issues/73763. If I have a sick node (misshappen LSM), when is it ever better to (a) take that node down wholly, vs. (b) drain + decommission that node. My argument is that (b) should always be better. If it isn't (because of known issues like this one + #74691) lets go fix those instead.

**Comment by tbg** [comment]
@irfansharif

> My inclination is to not overload the draining state in this way. The current semantics of "draining sheds all leases + rejects new conns", though imminently useful, seems to consistently trip up lots of folks when super imposed with membership states (decommissioning, decommissioned, active).

Does it trip up folks? I know there is a lot of confusion about the need to drain before decommissioning, but that seems more about decommissioning than draining. Are you questioning a need for `drain` to exist as a standalone primitive?

> when is it ever better to (a) take that node down wholly, vs. (b) drain + decommission that node. My argument is that (b) should always be better. 

Decommissioning moves a lot of data (and possibly load) around, including on unaffected nodes. This tends to make it harder to manage the situation. First draining the node as a "cheap" first step and only taking further measures (for example decommissioning) if they are necessary seems useful.

Assuming that Drain+Decommissioning is our only strategy, what happens while it is underway? We can't have the sick node stall the quota pool, so if `drain` doesn't opt out, `decommissioning` will have to [^1][^2].

Or, as you were suggesting, we need an "escape hatch". But is that the right word for it? Making sure a distressed node isn't relied upon by the rest of the cluster seems like a fundamental thing for us to get right. I'd rather develop a coherent story around this concept, and it doesn't affect only the quota pool. The closest to it that we have is `drain`[^3], which is why it has come up in this discussion. Perhaps adding quota-pool opt-out to `drain` is not immediately the right move since it can cause silent "availability risk" in healthy clusters in which the operator uses `drain` for reasons unrelated to this issue. But if operators used `drain` "only" in situations in which they want to protect the rest of the cluster, it seems like the right primitive to augment, and we should consider re-framing what `drain` is (including going as far as renaming it, if necessary).

The strategy could then be

- drain+noquotapool
- if this doesn't help (or the drain gets stuck for some reason), consider stopping or decomissioning

At the second stage, if the node is drained, not taken into account for the quota pool, and still causes trouble across the cluster, I don't see how decommissioning it can really help if the node is still running, so decommission-in-absentia seems like the right next move, if we can afford the loss of the node (but probably the node is already lost as far as quorum is concerned).

[^1]: but then we are opting out of the quota pool when decommissioning a healthy node, thus creating a hidden availability risk should a node fail.
[^2]: for another argument against decommissioning (but a weak one): If you only have three nodes (or you have some multi-region deployment with no local substitute for the node your are trying to take out), the decommissioning option doesn't work. I think in a cloud-first world this argument doesn't carry much weight since we expect the operator to be able to spin up a new CRDB node anywhere on short notice. But it's always going to add latency to add a new node, and latency isn't what we want.
[^3]: are follower reads routed to draining nodes? They shouldn't, but am unsure.

----

@petermattis

> Couldn't that also lead to snapshot-death-spirals? The draining node falls behind and needs a snapshot, we catch it up, but it again falls behind (it is draining for a reason, right?), so we send it another snapshot. This keeps happening and we're consuming more resources than if we'd just slowed down writes to the range.

When a snapshot is in flight to a follower, we won't truncate the log until that snapshot has arrived. It is true that once the snapshot has applied, the follower might be far behind again, so far that we will do a non-cooperative log truncation again, meaning that the follower will need another snapshot. But I wouldn't call that a death spiral: it's just that the follower is so slow in applying log entries that the system decides that catching it up via snapshots is the more effective way to keep that follower "up to date". We may or may not be consuming more resources that way (if each snapshot is 64mb but the log is 6000 mb we'd actually be saving quite a bit by compressing lots of little churny updates periodically), but we are definitely giving the user a better experience by not slowing down writes.

----

I think there's also a conversation to be had about admission control here. Perhaps snapshots to a distressed node should be delayed or throttled more aggressively. Perhaps the quota pool opt-out should be based on the target's admission control state. In the desired end state, an overloaded node will also shed leases and throttles SQL traffic. So it seems that at the end of this, what we might really want is a way to manually mark a node as overloaded, but normally leave such considerations to the admission control system.

**Comment by irfansharif** [comment]
>  I know there is a lot of confusion about the need to drain before decommissioning, but that seems more about decommissioning than draining. Are you questioning a need for drain to exist as a standalone primitive?

Not at all. I want `drain` to be a very useful quarantining tool. I can buy that the confusion stems more for decommissioning. If expanding `drain` to also preclude lagging replicas from holding up the quota pool and/or other mechanisms like it makes it more useful to quarantine sick nodes, that SGTM.

> Making sure a distressed node isn't relied upon by the rest of the cluster seems like a fundamental thing for us to get right. I'd rather develop a coherent story around this concept, and it doesn't affect only the quota pool.

Perhaps in the very short term (i.e. stability) we could add the escape hatch this issue suggests. I don't know how much work it would be to broadcast a node's ephemeral draining state clusterwide for leaseholder to exclude contained replicas from proposal quota pool considerations.

**Comment by tbg** [comment]
> Perhaps in the very short term (i.e. stability) we could add the escape hatch this issue suggests. I don't know how much work it would be to broadcast a node's ephemeral draining state clusterwide for leaseholder to exclude contained replicas from proposal quota pool considerations.

The draining status is already gossiped, via the liveness record:

https://github.com/cockroachdb/cockroach/blob/56ff1ac9f203f984b63e1d0dd34b8ee85ca0d0d3/pkg/server/drain.go#L353-L358

so I don't anticipate it being difficult to use it.

**Comment by tbg** [comment]
Some more discussion of the quota pool on https://github.com/cockroachdb/cockroach/issues/79215#issuecomment-1168103307. I am increasingly critical of its default choice of sacrificing foreground traffic vs sacrificing lagging follower, so adding an escape hatch feels right to me at this point, though I am not sure if in the moment we would realize that we need to pull it in time. We are bound to get metrics on the quota pool though (https://github.com/cockroachdb/cockroach/issues/83263), so we at least have a shot and should see reliably when it's full if we looked at the right metric.

**Comment by irfansharif** [comment]
This issue is a bit aged now and talks about many things. We’re ignoring IO throttled nodes from the quota pool, and I know we want to ignore draining nodes from it too. Do we have an issue for that specifically? Do we also have issues tracking the kinds of metrics we want to expose here? Once those are filed, lets close this. I’ll leave it on the Repl folks to do so.

**Comment by irfansharif** [comment]
#75978 + #55806 are the more targeted issues.
