### ISSUE TITLE
sql: prepared statements cause current database scope to be lost

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7728]
Reproduce with this specific sqllogictest inputs:

```
make test PKG=./sql TESTS=TestLogic \
   TESTFLAGS='-v -max-errors 0 -error-summary -allow-prepare-fail -flex-types 
          -d ..../sqllogictest/test/random/groupby/slt_good_4.test'
```

This will show that:

1) the query on line 47493 fails with a `pq: division by zero`

2) all subsequent queries fail with `pq: no database specified: ...`

Same happens with `slt_good_11.test` on line 46566.

**Comment by knz** [comment]
Note: couldn't reproduce with a smaller input so far.

**Comment by knz** [comment]
Running this test with '-verbosity 1' reveals:

```
SELECT col2 * tab2.col2 AS col2 FROM tab2 GROUP BY tab2.col2;        -- OK;
SELECT + tab0.col2 FROM tab0 WHERE + tab0.col2 / col1 IS NOT NULL GROUP BY tab0.col2 HAVING NULL IS NOT NULL;  -- FAIL
SELECT ALL - 54 FROM tab1 cor0 GROUP BY col0;
W160711 20:46:54.455373 sql/pgwire/v3.go:171  unrecognized configuration parameter "client_encoding"
W160711 20:46:54.455401 sql/pgwire/v3.go:171  unrecognized configuration parameter "datestyle"
W160711 20:46:54.455407 sql/pgwire/v3.go:171  unrecognized configuration parameter "extra_float_digits"
        -- fails prepare: pq: no database specified: tab1       -- XFAIL;
SELECT ALL col2 * 44 FROM tab1 GROUP BY tab1.col2;   -- fails prepare: pq: no database specified: tab1       -- XFAIL;
SELECT DISTINCT + 1 FROM tab1 cor0 GROUP BY cor0.col0;       -- fails prepare: pq: no database specified: tab1       -- XFAIL;
```

So after the "division by zero" is encountered, there is a reconnect (v3.go encounters the various SET statements issued by sql/pq).

**Comment by knz** [comment]
This is strange because the other errors (there are plenty) do not cause such a reconnect.

**Comment by mjibson** [comment]
In `database/sql`, a query error releases a connection (https://github.com/golang/go/blob/release-branch.go1.6/src/database/sql/sql.go#L1095). This happens during the divide by zero error. Since you specify `-max-errors 0`, the next select is executed, which triggers a new connection since the old one was closed.

The oddity here is that other query errors don't trigger the dis- and re-connect. I will investigate more tomorrow, but my current guess is that div-by-zero returns a different error code than other errors, which is causing it to reconnect.

**Comment by mjibson** [comment]
More research: this happens with `select log(0.0)` also. Best guess is parse errors do not cause this problem, but eval errors do.

**Comment by mjibson** [comment]
The important part of the test that is causing this error is `-allow-prepare-fail`. That flag runs a `db.Prepare`, which, although its returned statement is correctly closed, apparently resets something in our connection logic.

Repro:

```
package main

import (
	"database/sql"
	"log"

	_ "github.com/cockroachdb/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgresql://root@localhost:26257?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	if _, err := db.Exec(`
		DROP DATABASE IF EXISTS d;
		CREATE DATABASE d;
		SET DATABASE = d;
		CREATE TABLE t (a INT);
	`); err != nil {
		panic(err)
	}

	if rows, err := db.Query(`SELECT 1 FROM t`); err != nil {
		panic(err)
	} else {
		rows.Close()
	}

	if stmt, err := db.Prepare(`SELECT 0 / 0`); err != nil {
		panic(err)
	} else {
		stmt.Close()
	}

	if rows, err := db.Query(`SELECT 1 FROM t`); err != nil {
		panic(err)
	} else {
		rows.Close()
	}
}
```

**Comment by mjibson** [comment]
Final update:

This isn't our bug: the Go database/sql package sometimes makes new connections. If you ever depend on something working due to state in the session, you may have a bad day.

The `SET DATABASE` syntax is cockroach-specific: Postgres itself doesn't support that. Instead, the `psql` command supports `\c DB`, but that creates a new connection with the current database. If you want to make sure your Go connection stays on a database, put the DB in the connection string URL as the path. Sometimes Go decides to make a new connection (thus with a new session), for example at the end of a prepared statement (I'm not sure why, but it does).

I verified that this exact behavior happens by testing using `SET TIMEZONE` with a go program to a postgres server:

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/cockroachdb/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgresql://postgres@localhost:5432/d?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var tz string

	if err := db.QueryRow(`SHOW TIMEZONE`).Scan(&tz); err != nil {
		panic(err)
	}
	fmt.Println("0 GOT", tz)

	if _, err := db.Exec(`SET TIME ZONE 'PST8PDT'`); err != nil {
		panic(err)
	}

	if err := db.QueryRow(`SHOW TIMEZONE`).Scan(&tz); err != nil {
		panic(err)
	}
	fmt.Println("1 GOT", tz)

	if stmt, err := db.Prepare(`SHOW TIMEZONE`); err != nil {
		panic(err)
	} else {
		if err := stmt.QueryRow().Scan(&tz); err != nil {
			panic(err)
		}
		stmt.Close()
		fmt.Println("2 GOT", tz)
	}

	if err := db.QueryRow(`SHOW TIMEZONE`).Scan(&tz); err != nil {
		panic(err)
	}
	fmt.Println("3 GOT", tz)
}
```

Output:

```
0 GOT UTC
1 GOT PST8PDT
2 GOT PST8PDT
3 GOT UTC
```

The "3 GOT UTC" means shows that a new connection was made with the default timezone, and the old connection with the other timezone went somewhere else.

The use of `-allow-prepare-fail` in the test causes a prepared statement to be executed, which creates a new connection, which comes without a default database because no database was specified in the connection string.

**Comment by mjibson** [comment]
Can we close this?

**Comment by knz** [comment]
Wait I want to have a quick look to see what we can do. There's already some machinery for changing users, perhaps we can reuse that.

**Comment by spencerkimball** [comment]
@knz, ping. This has been lingering for the better part of a year and as @mjibson pointed out, this is not necessarily something that we can / should fix.

**Comment by knz** [comment]
Looked at this; it's hard to fix and only affects a specific test scenario which is not run by default. LEt's close this.

**Comment by tamird** [comment]
Why is it appropriate to close this rather than moving to a future milestone? It's still an issue, especially if the behaviour differs from postgres.

**Comment by knz** [comment]
@tamird the problem is not in our server but rather in our test logic. The problem is that go's sql package (or perhaps pq) will re-open a connection if a prepare fails; this causes any current session configuration (via SET) to be lost, including the current database.

A client application would re-populate its session configuration upon reconnecting (we document this behavior for SET already) so this is not a user-visible problem.

(Also, pg has the same issue!)

**Comment by mjibson** [comment]
This may be solvable by the new Conn stuff coming in go 1.9.
