### ISSUE TITLE
cdc: add telemetry logging for create changefeed 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#77283]
Since the new logging framework is only for serverless. We should do some more detailed logging of create changefeed for majority of users going into 22.1 launch. This will help us better understand what are customers are doing and where they are struggling. 

**Create changefeed event:**
The biggest thing we should log is the sink_type (gs, s3, http, webhook, kafka, gc pubsub). Additionally, logging the number of non-default configurations would be a great thing to log, but its a nice to have not a must have.

**Changefeed fail event**
There are three things we should log
- changefeed failed before changefeed create succeeded
- changefeed failed due to closed connection (core)
- All other failures

Jira issue: CRDB-13517

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13517](https://cockroachlabs.atlassian.net/browse/CRDB-13517) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77283`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
