### ISSUE TITLE
DBConsole: Node Diagnostics report to show only live nodes with an option to include decommissioned nodes

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#77333]
**Is your feature request related to a problem? Please describe.**
The Node Diagnostics report shows all nodes including those that have been decommissioned. This can make it confusing when, for example, you check the tag and updatedAt column and find some nodes haven't been upgraded (because they were previously decommissioned).

**Describe the solution you'd like**
By default the Node Diagnostics should only show active nodes with an option (button?) to include decommissioned nodes if required.

**Describe alternatives you've considered**
As a minmum a row in the Node Diagnostics to indicate that the node is decommissioned. 

Jira issue: CRDB-13531

**Comment by Annebirzin** [comment]
@cjireland and @thtruo I've added designs [here](https://www.figma.com/file/kuHnlLQhq9b6itkqX6iRf0/22.1_obsrv-dbconsole-updates?node-id=1392%3A3059) for including a filter on the Node Diagnostics page:

![Screen Shot 2022-03-21 at 12 43 56 PM](https://user-images.githubusercontent.com/51920721/159312372-95bbba6f-a734-4724-ac17-83f8e2a997dc.png)

- Any thoughts on the term 'Active Nodes'? Not sure if this is a term we would use for 'non-decommissioned nodes' cc @taroface 
- Another approach could be to just remove decommissioned nodes from this view altogether since there is already a page in Advanced debug to see Decommissioned Nodes History. Thoughts?

**Comment by taroface** [comment]
@Annebirzin @thtruo I'm not 100% certain on "Active" yet, but it seems likely. It would help to know which field is being pulled from the backend to filter these nodes.

**Comment by Annebirzin** [comment]
@taroface I _think_ we'd want to show all nodes that are not decommissioned - so Suspect, Dead or Live nodes would still appear. That's why I wasn't so sure what term to use for 'non-decommissioned nodes.' @thtruo let me know if this sounds correct.

**Comment by taroface** [comment]
In that case, "Active Nodes" should be good - it can indicate a live or dead node. It also matches the `membership` field returned in `cockroach node status --decommission`, which lists a node as `active` when it's not `decommissioned`.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13531](https://cockroachlabs.atlassian.net/browse/CRDB-13531) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77333`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
