### ISSUE TITLE
Bring --accept-sql-without-tls flag from experimental to fully supported

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#77361]
We currently are looking at a few Kerberos items in regards to CRDB within our environment and have come across the following:

Our library doesn't speak SSL so we tried the `--accept-sql-without-tls` flag but it doesn't appear to work with gss and we get the following error:

`psql: error: ERROR:  method "gss" required for this user, but unusable over this connection type`

[Based on what we've seen here](https://github.com/cockroachdb/cockroach/blob/c459d395e8bd173cc0791adf3d69a836d601be70/pkg/ccl/gssapiccl/gssapi.go#L174), we don't currently believe that we can change `server.host_based_authentication.configuration` to allow that which leads us to the following:
1. It would be good to explicitly document that the flag does not work with gss as well as documenting this in the binary. Currently as of 21.2.5 it only shows up under the description text of the `--insecure` flag.
2. It would be very nice if the flag did work with gss auth. We're in sort of the situation described in the authentication docs where we don't really care about running TLS and being able to remove it from the mix while we debug other things would be extremely helpful.

We appreciate that this is an experimental flag and the purpose of this feature request is to ask that it become fully fledged. 

Jira issue: CRDB-13550

**Comment by knz** [comment]
@steven-hubbard @a-entin can you check what is meant by "Our library doesn't speak SSL"

There are two different options:
- either they are interested in GSS authentication over a non-encrypted connection (which would be an extremely odd setup)
- or, they are really looking for GSS encryption, described in #52184

Which one is it?

Regarding the use of GSS authn over a non-encrypted link, the problem is not accurately described as "Bring --accept-sql-without-tls flag from experimental to fully supported". Just doing this would not solve the problem. The actual thing your issue description asks for is "extending the `gss` authn method to work over non-TLS connections". That'd be different work.

**Comment by knz** [comment]
After looking at internal customer notes, it appears that the customer wants GSS encryption instead which is the separate issue request #52184. Closing this.

**Comment by andy-dulson** [comment]
We don't want GSS encryption - the only thing that we've raised about GSS encryption is that our logs have a lot of "GSS encryption isn't supported" lines in them, and setting that to "log every N" (or turning it off entirely) would be helpful, since right now those lines are something like 80% of our logs by volume and get in the way when we're looking at interesting things.

We were looking for the first bullet - GSS auth over non-encrypted connections. That's exactly how we run Postgres; we don't want to use passwords, but with everything on prem we are not super concerned about ssl. We may run our prod cluster with ssl enabled (and we may go back and turn on ssl for our postgres instances one day), but the ssl requirement keeps coming up in two contexts:

- We have our own postgres driver and kerberos libraries (there aren't good ones available in the language we use). We've been debugging some things at the intersection of krb auth/dns/postgres and been massively slowed down by the fact that SSL renders traffic captures pretty much useless. (These are the same reasons we don't want gss encryption - I haven't even looked at what we would have to do to support that.)
- We want clients to connect via database-specific dns aliases, so if they're using a database called 'foo' they would connect to 'foodb.internal.com' rather than the dns name of the cluster. With ssl enabled, that means we have to renew the node certs and bounce everything (we think - getting that all working is on my stack for the next week or so), and given the choice of that, or running without ssl, we'd run without ssl. (If there is or was a way to reload node certs without bouncing the node, that would obviate this bullet.)

**Comment by knz** [comment]
As discussed elsewhere the current recommendation for that user's deployment is to try TLS without validating server names.
