### ISSUE TITLE
backupccl: Handling mixed layers by locality

### ISSUE THREAD

**Issue by benbardin** [cockroachdb/cockroach#77369]
Currently, the backup/restore code assumes that all specified localities will have the same incremental layers as the default. This is not necessarily true. A user could write a base layer to localities Default, US, EU; then an incremental to DEFAULT, EU; then an incremental to DEFAULT, US.

We need RESTORE to handle mismatches like this. We can't block them at BACKUP-time, since we obviously won't know about omitted localities. So RESTORE should either fail gracefully, or accommodate mismatched layers.

We need to decide which approach to take, implement it, test it, and document it.

Jira issue: CRDB-13555

**Comment by benbardin** [comment]
We have decided to block this behavior outright. We have some validation in place now to prevent backups/restore with mismatched localities. In the future, we want to check that the _specified target destination_ for each locality actually contains the correct number of incremental backups.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13555](https://cockroachlabs.atlassian.net/browse/CRDB-13555) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77369`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done
