### ISSUE TITLE
storage: large VerifyChecksum requests cause Raft log and memory blow-up

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7739]
Noticed in #7693. 

> The raft log is strange. 9578 of the entries are smaller than 10 KB and consume 3.8 MB of space. The remaining 55 entries are larger than 10 MB and consume 749 MB. The largest is 35 MB. These largest entries are only present in 4 of the 49 ranges. Hand inspection reveals that the largest all correspond to VerifyChecksum operations. Further inspection shows we have 59 VerifyChecksum operations in the raft log. 4 of these operations are tiny, consuming a few hundred bytes. The remaining are gigantic and correspond to a VerifyChecksumRequest containing a RaftSnapshotData which occurs during a consistency check failure. A consistency check failure causing huge data blow-up is less than ideal, though I understand this was necessary to provide better log messages about which keys were causing the consistency failure.

**Comment by vivekmenezes** [comment]
I hope this is not a high priority?

**Comment by petermattis** [comment]
The Raft log and memory blow-up from this are pretty severe. I think its debatable whether this pushes the issue of the high priority threshold. Certainly, this is noticeable by users.

I'm not sure what a good fix is. We could disable the detailed verify-checksum code path by default. Or we could restructure `CheckConsistency` and `VerifyChecksum` so that they operate on smaller chunks of the range. I'm not familiar enough with this code to know how difficult that is.

**Comment by bdarnell** [comment]
Originally, we only collected the full verification information when the consistency checker was running in panic mode, so we'd only run out of memory if we were about to panic anyway. I changed it to always print the details so we'd have more information when/if this failed again even if we hadn't enabled panic mode. 

We could easily undo that change, although we still need to get full consistency reports sometimes. It should be straightforward to make VerifyChecksum work on chunks smaller than a range, although this would still create raft log entries that are much larger than average. 

It's unfortunate that VerifyChecksum writes such huge commands to the raft log; now that we have the ability to address RPCs to individual stores we may be able to move the "details" phase of the consistency checker to use an rpc instead of a raft command.

**Comment by petermattis** [comment]
How would you move the details phase `VerifyChecksum` out of a raft command? We want to get a snapshot at the same raft log index which seems difficult if we don't go through raft.

**Comment by vivekmenezes** [comment]
The first phase BeginChecksum fixes the snapshot at which to compute a checksum and assigns a unique id to it, the verify checksum can out of band pass the id and the checksum for verification. It need not go through raft.

**Comment by bdarnell** [comment]
We don't get a raft snapshot in `VerifyChecksum`. We get the snapshot in `ComputeChecksum` and store it in `Replica.mu.checksums` for later. I think `VerifyChecksum` is a raft command because it was more convenient to do it that way than to introduce a separate kind of RPC (with a then-unprecedented addressing scheme).

**Comment by petermattis** [comment]
Ah, yes, got it. Moving `VerifyChecksum` out of Raft seems like the right thing to do.
