### ISSUE TITLE
Show warning message during cluster upgrade on SQL Activity pages

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#77535]
During a upgrade from a version prior to 21.2 to any after 21.2 a few tables are created for statement statistics, but during the upgrading process if the table is not yet created the ui for SQL Activity pages will not load and show a generic message of "This page had an unexpected error while loading statements".
Change the message to indicate that this page will not be available during the upgrade period.

Jira issue: CRDB-13640

**Comment by maryliag** [comment]
cc @Annebirzin  for how to show the message and the text

**Comment by Annebirzin** [comment]
@maryliag I think we could go with something simple for the messaging like `This page cannot be displayed because an upgrade is in progress for this cluster.`

![Screen Shot 2022-03-10 at 11 45 53 AM](https://user-images.githubusercontent.com/51920721/157712837-dd95d34b-d2fa-4b1a-bd99-30bc280d6196.png)

The KV observability team is currently adding a similar message to DB Console when there are multiple versions of a cluster running (ie. rolling upgrade is in progress): https://github.com/cockroachdb/cockroach/pull/76932#issuecomment-1064232953

I was thinking it might be better to keep it simple for CC console rather than showing the nodes and versions they are running cc @kevin-v-ngo and @stbof for any thoughts.

**Comment by stbof** [comment]
If the knowledge of the nodes and versions cannot be used for anything, my feeling is that there's no reason to display them.

**Comment by jocrl** [comment]
My queue is pretty full right now, so un-assigning at the end of this quick win day and documenting how far I got:

- The only code I have so far is just pulling out a selector for whether we are currently in a cluster upgrade state: https://github.com/jocrl/cockroach/tree/staggered-versions-banner
- A selector will be needed for CC Console as well
- I think a good place to conditionally render the tab content (I'm assuming, for all three tabs) would be `db-console/src/views/sqlActivity/sqlActivityPage.tsx` for DB Console. This is because we don't even to do the logic of attempting to retrieve data, etc, that would trigger when the component mounts. This is not an error message depending on the data, it is a decision of whether it or not this feature even applies.
- I was partway in trying to figure out what the equivalent file in CC Console is. `ConnectedStatementsPage` in `cluster-ui/src/statementsPage/statementsPageConnected.tsx` has usages only in storybook, and my React plugins aren't loading in CC Console for some flaky reason. I almost wonder if the equivalent file is in `managed-service`.
- There should probably be a story for this in storybook, and development can be tested there
- Testing whether this works for real can probably be done by doing a [patch upgrade](https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2441183244/Creating+and+maintaining+the+sql-o11y+and+sql-o11y-severless+clusters#To-upgrade-a-%22latest%22-cluster-to-a-newer-%22latest%22-(i.e.-a-patch-upgrade)) to our SQL Observability clusters

**Comment by maryliag** [comment]
FYI, we do have a sqlActivityPage file on managed-service repo, which is equivalent to the one from DB Console
`console/assets/js/pages/clusterDetail/dbConsole/sqlActivity.tsx`

**Comment by maryliag** [comment]
With the changes added by https://github.com/cockroachdb/cockroach/pull/79795 this error state no longer occurs. So closing this issue since a warning message is no longer required
