### ISSUE TITLE
changefeedccl: Determine if backporting active PTS management makes sense.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#77545]
https://github.com/cockroachdb/cockroach/pull/76605

Determine if we should backport active pts management to 21.2.
without active PTS management makes "on_error_pause" + "protect_gc_on_pause" misbehave when
GC threshold expires.  So, backporting might actually improve product semantics.

Jira issue: CRDB-13645

**Comment by amruss** [comment]
Plan is to backport with a safety value to revert to old behavior

**Comment by amruss** [comment]
@samiskin did we end up doing this?

**Comment by amruss** [comment]
Looks like we did here: https://github.com/cockroachdb/cockroach/pull/77589 , closing this

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13645](https://cockroachlabs.atlassian.net/browse/CRDB-13645) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77545`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
