### ISSUE TITLE
User-defined built-in functions

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#77555]
**Describe the solution you'd like**
An implementation of user-defined built-in functions, written in Go (or perhaps another language) that can be hooked into CockroachDB upon startup, similar to PostgreSQL functionality: https://www.percona.com/blog/2019/04/05/writing-postgresql-extensions-is-fun-c-language/

Jira issue: CRDB-13652

**Comment by jordanlewis** [comment]
Thanks for filing Shaun, sorry that this slipped through the cracks. We'd likely only be able to accomplish this once #58356 and possibly #17511 are finished.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13652](https://cockroachlabs.atlassian.net/browse/CRDB-13652) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77555`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
