### ISSUE TITLE
index_usage_stats: `CREATE INDEX` should not populate its `last_read` column

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#77598]
**Describe the problem**

Currently, `CREATE INDEX` incorrectly populates the index's `last_read` column in the `crdb_internal.index_usage_statistics` table. The `last_read` column should remain unpopulated until the index has been read.

**To Reproduce**

Create an index on a table from the currently used database. 
Check the `last_read` column of the index in the `crdb_internal.index_usage_statistics` table.

Verify that the `last_read` column of the index is populated, and the `total_reads` of the index is 1, despite no queries being made.

**Expected behavior**
Creating an index should not account for a read on the index. When an index is created, its index usage statistics `total_reads` should be 0, and it's `last_read` should not be populated.

**Additional data / screenshots**
[Loom](https://www.loom.com/share/a445f7b989ef4e828e61316289c490fd) video reproducing this issue.

**Environment:**
CockroachDB version [v22.1.0], was reproduced on `master` branch.

Jira issue: CRDB-13673

**Comment by ajwerner** [comment]
I guess this happens because the planner in question is not marked with `isInternalPlanner`. In the places we seem to record the index read, it appears we check that variable. 

I see this comment from Yahor, but I don't understand it. I don't have a clear understanding of when that boolean is set or what it means, but I think it's the problem. I'm pretty certain when we query the index during the schema change we use an internal executor. 
https://github.com/cockroachdb/cockroach/blob/a59751609574548759d2174844270468c3204d10/pkg/sql/conn_executor_exec.go#L1209-L1212

**Comment by THardy98** [comment]
> I guess this happens because the planner in question is not marked with `isInternalPlanner`. In the places we seem to record the index read, it appears we check that variable.
> 
> I see this comment from Yahor, but I don't understand it. I don't have a clear understanding of when that boolean is set or what it means, but I think it's the problem. I'm pretty certain when we query the index during the schema change we use an internal executor.
> 
> https://github.com/cockroachdb/cockroach/blob/a59751609574548759d2174844270468c3204d10/pkg/sql/conn_executor_exec.go#L1209-L1212

Seems like we only set the `isInternalPlanner` flag when we explicitly create a `newInternalPlanner` (https://github.com/cockroachdb/cockroach/blob/0f46ff6a0b85b22601b7d7eba4d9f59019e55146/pkg/sql/planner.go#L293).

The internal executor used during `ValidateForwardIndexes` doesn't use an internal planner. It creates a regular `connExecutor` (https://github.com/cockroachdb/cockroach/blob/f1ce34ce6440b3208e32db095f2ca79e2132f283/pkg/sql/internal.go#L280) whose `planner` is created with a struct literal (https://github.com/cockroachdb/cockroach/blob/5aebc22312f8c6192fee1f7017cb648a5f839442/pkg/sql/conn_executor.go#L956) and is non-internal.

Are internal executors intended to be used with non-internal planners? Or rather, should internal executors be using internal planners exclusively? I'm not clear on what the pattern is. 

If we wanted the `InternalExecutor` to use an internal planner, we could add a param to `newConnExecutor` designating whether it's planner should be internal and set this param to `true` from `initConnEx` (https://github.com/cockroachdb/cockroach/blob/f1ce34ce6440b3208e32db095f2ca79e2132f283/pkg/sql/internal.go#L243).

If not, it looks like the internal executor always designates its session data as internal and we could simply add another check when we record an index read:
```
if !ef.isExplain && !(ef.planner.isInternalPlanner || ef.planner.SessionData().Internal) {
...
}
```
cc @yuzefovich for your thoughts (as it seems like both myself and Andrew aren't very familiar with the usage of the `isInternalPlanner` flag)

**Comment by THardy98** [comment]
Mentioned PR filters out queries from internal sessions, simple fix.

**Comment by yuzefovich** [comment]
> Or rather, should internal executors be using internal planners exclusively?

I'm not sure anyone knows, and I'm not sure myself, but maybe yes? The boolean was introduced in #51865 with only this use case in mind:
https://github.com/cockroachdb/cockroach/blob/c432bd722a5481be3831d64d139fce2b6e875b06/pkg/sql/distsql_running.go#L521-L529

The fact that we started using in more places, probably without understanding of what "isInternalPlanner" means, seems suspicious. What you're doing in #88756 sounds reasonable to me.

**Comment by ZhouXing19** [comment]
> should internal executors be using internal planners exclusively?
I looked at the usages of `planner.isInternalPlanner`, and it seems reasonable (or at least harmless) to me to do so. The only worrying usage is the one that Yahor posted:
https://github.com/cockroachdb/cockroach/blob/c432bd722a5481be3831d64d139fce2b6e875b06/pkg/sql/distsql_running.go#L521-L529

I think we should remove the `!planCtx.planner.isInternalPlanner` check here. Since the internal executor can be run with an outer transaction, thus can inherit the descriptor collection, and we will want to pass it to `localState` as well.
