### ISSUE TITLE
logging: Allow runtime reloading of --log-config-file via SIGHUP

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach#77764]
**Is your feature request related to a problem? Please describe.**
CockroachDB currently needs to be restarted whenever I want to change the YAML logging configuration.

**Describe the solution you'd like**
CockroachDB currently has the ability to reload its certificate configuration from disk by sending the process a SIGHUP signal.

As a user, I would expect all externally loaded configuration files (in this case the logging configuration) to be reloadable via a SIGHUP signal.

This would make configuration via Kubernetes much more ergonomic. Instead of having to perform a rolling restart of the system, users would be able to change a ConfigMap holding their logging config and issue a SIGHUP via `kubectl exec` or utilize a sidecar running `inotify`.

**Describe alternatives you've considered**
We could opt to not support reloading of configurations besides certificates. This would make sense if it's too difficult to reload the logging system at runtime.

**Additional context**
The choice to implement this feature or not has strong implications about the direction of the logging configuration API being proposed in https://github.com/cockroachdb/cockroach-operator/pull/827. We don't need it now but if we agreed that it should be added in the future, logging configurations should be specified via a configmap.

cc @knz @logston 

Jira issue: CRDB-13757

gz#11639

**Comment by knz** [comment]
cc @thtruo for triage

**Comment by knz** [comment]
One challenge in the solution will be to ensure that no log entry is lost during the time the config is switched over.

**Comment by joshimhoff** [comment]
If the logging config isn't valid, what do you think should happen, @chrisseto?

> users would be able to change a ConfigMap holding their logging config and issue a SIGHUP via kubectl exec or utilize a sidecar running inotify.

How do you gradually roll out the change to the CRDB pods when following the sidecar pattern specifically? Certs are per node, right? That is an important diference.

**Comment by chrisseto** [comment]
> If the logging config isn't valid, what do you think should happen, @chrisseto?

I'd suggest copying the behavior of the certificate reloading code, if that's feasible.

> @chrisseto, how do you gradually roll out the change to the CRDB pods when following the sidecar pattern specifically?

If you're using the side car pattern, you'd have to create a new config map and then perform a rolling update of the cluster. Would your concerns be mitigated if there was a `cockroach` subcommand that allowed users to validate a configuration before shipping it out?

> Certs are per node, right? If yes, that is an important difference.

Can you elaborate more here? Certs _can_ be per node but they can also be homogenous, which is the case for many statefulset deployments.

**Comment by dhartunian** [comment]
Discussed this with SRE team. this is currently lower urgency as rolling restarts are ok on their end.
If customers push strongly for this we can bring it up to the top of the priority pile.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13757](https://cockroachlabs.atlassian.net/browse/CRDB-13757) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77764`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira

**Comment by aadityasondhi** [comment]
Closing this issue after discussions on slack resolved to us no longer wanting to have this feature. Here is a summary of the discussion:

- Changing these configs without a restart would mean that there could be an incorrect config that a running node is referencing, which would cause a failure on the next restart.
- Rolling restarts are also a desired behavior in k8s as it has interfaces to support it with `kubectl rollout restart` but no `kubectl killall SIGHUP`. Additionally, these changes are expected to be relatively uncommon and customers are expected to tolerate node restarts.

cc @chrisseto @jreut @knz @andreimatei
