### ISSUE TITLE
backupccl: SHOW BACKUPS IN is busted for base directory (bucket) backups

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#77930]
For Azure, GCS, nodelocal, and S3 a backup collection in a storage location without any prefix, i.e. in the base bucket cannot be inspected using `SHOW BACKUPS IN`.

Steps to reproduce:

`BACKUP INTO gs://<bucket-name>` 
`SHOW BACKUPS IN 'gs://<bucket-name>` <-- returns 0 backups in the collection

This is because the `SHOW BACKUPS IN` command performs a `path.Match("/*/*/*/"+backupManifestName, f)` when looking for the backup manifest. This regex does not match the objects returned when listing objects in the base directory (or bucket) since they are not prefixed with a `/`. 

Jira issue: CRDB-13855

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13855](https://cockroachlabs.atlassian.net/browse/CRDB-13855) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77930`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done

**Comment by kenliu-crl** [comment]
manually reviewed and updated
