### ISSUE TITLE
High memory consumption from explain plan generation for statistics collection

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#77944]
This was raised by [this support ticket](https://github.com/cockroachlabs/support/issues/1430). Turning off the `sql.metrics.statement_details.plan_collection.enabled` cluster settings should fix the customer's immediate issue, but this issue describes the underlying issue with our code. Further details including those private to the customer can be found in that support issue, but the gist of the underlying problem is as follows.

This is on 21.1..12. Memory consumption [ballooned in the function](https://github.com/cockroachlabs/support/issues/1430#issuecomment-1068469457) `BuildProtoTree`, from generation of explain plans for very large statements such as [this one from the customer](https://github.com/cockroachlabs/support/issues/1430#issuecomment-1068326802).

I suspect that the larger or more likely cause of the OOM is this other issue: https://github.com/cockroachdb/cockroach/issues/77963

However, this issue is to describe that one other possible contributor to the OOM might be that very large statements use a lot of memory to generate their explain plan. We can check this by profiling the memory consumption for generating the explain plan for [the customer's statement](https://github.com/cockroachlabs/support/issues/1430#issuecomment-1068326802), and checking whether it is reasonable.

Jira issue: CRDB-13865

Epic CRDB-20388

**Comment by Azhng** [comment]
Now that we are storing the plan gist in our statement statistics, I wonder if it is still necessary to force a sampling of explain plan when they are first executed? 

Previously, this was to ensure that the Statement Detail page always has a query plan to render. Recently, we have moved to render the Statement Detail Page using the new plan gist feature. FWIW, forcing an `explain` plan collection no longer brings the same amount of value that it used. (iirc, I think we don't even use the `plan` column to render anything anymore, @maryliag  can you confirm?)

Since
* user can always generate explain plan manually using `EXPLAIN ANALYZE` or request for statement bundle
* we have moved to using plan gist

I feel we can just drop the whole explain plan collection

**Comment by jocrl** [comment]
👍 I like that idea.

I'll just note that that would fix performance issues, that there would still be many different statement fingerprints from a UI/stats-experience perspective.

**Comment by maryliag** [comment]
That column is no longer sample/generated
