### ISSUE TITLE
Locality-aware backup should return error on locality mismatch

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/cockroach#77969]
**Is your feature request related to a problem? Please describe.**

Currently, this situation is permissible with CRDB:

1. Create a cluster with no localities, or localities set to a particular region (say `us-east-1`)
2. Take a [locality-aware](https://www.cockroachlabs.com/docs/v21.2/take-and-restore-locality-aware-backups) backup, specifying a particular region not in the locality of the cluster: `BACKUP INTO ('nodelocal://1/default?COCKROACH_LOCALITY=default', 'nodelocal://1/us-west?COCKROACH_LOCALITY=region%3Dus-west');`
3. This backup will succeed
4. Restoring this backup into another `us-east-1` or locality-less cluster will result in `expected manifest BACKUP_PART_1_region=us-west-1 not found in backup locations` and error out

**Describe the solution you'd like**

Ideally, the database should not allow the backup to succeed in the first place, instead erroring with some sort of succinct message when it sees that a target bucket location does not match with a locality in the cluster.

**Describe alternatives you've considered**

N/A

**Additional context**

- Began a local 3-node cluster on my machine

<img width="1356" alt="Screen Shot 2022-03-16 at 4 33 28 PM" src="https://user-images.githubusercontent.com/24303643/158685793-9fcb1b36-881f-4e53-9cf9-b77c58b7dca4.png">

- Took a locality-aware backup to a locality not in my cluster: `backup into ('nodelocal://1/default?COCKROACH_LOCALITY=default', 'nodelocal://1/us-west?COCKROACH_LOCALITY=region%3Dus-west');`
- This creates folders for both default and us-west in the extern folder, but no data in us-west:

<img width="499" alt="Screen Shot 2022-03-16 at 4 44 34 PM" src="https://user-images.githubusercontent.com/24303643/158687608-594e6191-23c2-42f8-95df-9f7cd480ff6e.png">

- Restore this into another cluster (I moved the backup into nodelocal 1 in a new cluster to keep it simple): `restore from ('nodelocal://1/default?COCKROACH_LOCALITY=default', 'nodelocal://1/us-west?COCKROACH_LOCALITY=region%3Dus-west');`
- Observe the error:

`ERROR: expected manifest BACKUP_PART_1_region=us-west not found in backup locations`

EDIT: Correction to the above:

This error might not care about the actual regions/localities that the nodes exist in. If you take a locality-aware backup into `us-east` and `us-west`, and you don't specify both of those in the `RESTORE` using that backup, this error should reproduce, regardless of the region in the cluster you're `RESTORE`ing to.

Jira issue: CRDB-13877

**Comment by benbardin** [comment]
Yup, the situation as described is not good! I think I might prefer a different "desired behavior" though - specifically, I don't know that backups should fail if they're backing up a locality that doesn't exist in the database. Rather, I think they should "back up" an empty directory, then "restore" from that directory without fuss. For instance, I can imagine a user expanding operations from US to EU, and needing to become GDPR compliant; such a user might want to set up their backup localities before actually adding data.

But maybe that's not realistic? @livlobo what do you think should be desired behavior here, when a locality-aware backup includes a locality not in the cluster? Is it safe to assume it's 99% a mistake and block it?

**Comment by benbardin** [comment]
In https://github.com/cockroachdb/cockroach/pull/79135, we now prevent incremental backups with mismatched localities. We don't yet check if the specified destinations actually _have_ the right incremental backups - that seems beyond scope of this request, and will be tracked in https://github.com/cockroachdb/cockroach/issues/77369.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-13877](https://cockroachlabs.atlassian.net/browse/CRDB-13877) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-77969`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done
