### ISSUE TITLE
changefeedccl: error when user duplicates targets

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#78285]
When adding duplicate targets (CREATE CHANGEFEED FOR foo, foo) (ALTER CHANGEFEED ADD foo), the statement should error with a message along the lines of "changefeed cannot target the same table twice"

This is more clear behavior vs current behavior (silently deduping the expression), where the user could expect different behavior (two messages for every change) or could be making an error (CREATE CHANGEFEED FOR outbox, outbox instead of FOR db1.outbox, db2.outbox)

Jira issue: CRDB-14045

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14045](https://cockroachlabs.atlassian.net/browse/CRDB-14045) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78285`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
