### ISSUE TITLE
Presto compatibility

### ISSUE THREAD

**Issue by grafael** [cockroachdb/cockroach#78413]
I cannot access tables using Presto `PostgreslConnector`, maybe related to [#20419](https://github.com/cockroachdb/cockroach/issues/20419)

**To Reproduce**

After connecting Presto to CockroachDB only `information_schema` is available.

1. Set up CockroachDB 
2. Set up Presto PostgreSQL connector
3. Try to query any table

When running the same query using cockroachDB client it does work.
I did realize running `SHOW SCHEMAS;` from CRDB client returns 0 records.
What should be the default schema? Even `public` is not being listed on presto.

**Expected behavior**
Default schema being listed on Presto with access to its tables.

**Environment:**
 - CockroachDB version 21.2.7
 - Server OS Ubuntu 20.04
 - Client app  Presto + Postgresql connector JDBC

Jira issue: CRDB-14120

**Comment by rafiss** [comment]
Hi @grafael ! Perhaps this is a permissions issue. Which database are you connecting to? (If you could share the full connection string you're using with passwords removed, that would help.)

You may need to run `GRANT CONNECT ON DATABASE <database name> TO <user>` in order to give the user permission to see objects in the database. Or you could try to connect as an admin, if you don't want to use the CONNECT privilege.

**Comment by grafael** [comment]
Indeed, giving `GRANT CONNECT ON DATABASE` solved the problem. Thanks @rafiss
