### ISSUE TITLE
Enhance the time range selectors for better usability

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#78499]
We should enhance the usability of the time range selectors we have in the console. Specifically, 

- If you were already rendering a custom range, the time picker should expand back to custom range pick when clicked. Today's behavior forces the user to click through the relative duration shorthands menu first. 
- In the time selector menu, we should also have a link to allow the user to quickly go to the relative duration shorthands list if they were at the custom range select view
- ~Allow text entry in the time selector~ broke out into https://github.com/cockroachdb/cockroach/issues/80655

Jira issue: CRDB-14160

**Comment by Annebirzin** [comment]
@jocrl 
1. yep I think opening directly to the custom selector makes sense 
2. We can add a 'back' button ([design here](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=7493%3A120582)) so users can navigate back to the pre-defined time ranges

![Screen Shot 2022-05-06 at 12 05 20 PM](https://user-images.githubusercontent.com/51920721/167170694-2c8e4d94-11a4-473d-a3e3-26850b321934.png)

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14160](https://cockroachlabs.atlassian.net/browse/CRDB-14160) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78499` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14160](https://cockroachlabs.atlassian.net/browse/CRDB-14160) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78499`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by jocrl** [comment]
Hello, amazing and very human clean up team!

I have updated the Jira description with the description in this GitHub issue. Thank you!

**Comment by irfansharif** [comment]
I'll use this issue for a mega nit: 
![image](https://user-images.githubusercontent.com/10536690/170509463-47eec0ce-6973-4973-97c2-e773c15a0413.png)

The timeseries show timestamps in 24h format, but the selector doesn't. When looking to select a specific window manually, having to translate between the two is slight friction. Do we think this is reasonable to unify? Should I file a separate issue?

**Comment by jocrl** [comment]
Thanks, @irfansharif! That's already being addressed in https://github.com/cockroachdb/cockroach/pull/81077 🙂

**Comment by irfansharif** [comment]
Brilliant, thanks!
