### ISSUE TITLE
jobs, sql: Create stats job uses expensive query to ensure single stats job exists 

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#78503]
Stats, and auto stats job verify that no other stats job exists via jobs.RunningJobExists.
Unfortunately, that method uses very expensive query:
```
const stmt = `
SELECT
  id, payload
FROM
  system.jobs
WHERE
  status IN ` + NonTerminalStatusTupleString + `
ORDER BY created`
```
That's a full table table scan.  We can leverage created_by columns to make this check cheap.

Same function used by spanconfig manager.

Jira issue: CRDB-14162

**Comment by amruss** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/77552

**Comment by rytaft** [comment]
Thanks for filing this, @miretskiy

> That's a full table table scan

From what I can tell it's not a full scan since it's constraining the possible statuses using the `jobs_status_created_idx` index. This is the plan I see:
```
explain SELECT
  id, payload
FROM
  system.jobs
WHERE
  status IN ('running', 'pending', 'cancel-requested', 'pause-requested', 'reverting', 'paused')
ORDER BY created;
                                                                                 info
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • sort
  │ order: +created
  │
  └── • index join
      │ table: jobs@primary
      │
      └── • scan
            missing stats
            table: jobs@jobs_status_created_idx
            spans: [/'cancel-requested' - /'cancel-requested'] [/'pause-requested' - /'pause-requested'] [/'paused' - /'paused'] [/'pending' - /'pending'] … (2 more)
(13 rows)
```

Note that the available indexes in the jobs table are:
```
CONSTRAINT "primary" PRIMARY KEY (id ASC),
INDEX jobs_status_created_idx (status ASC, created ASC),
INDEX jobs_created_by_type_created_by_id_idx (created_by_type ASC, created_by_id ASC) STORING (status),
INDEX jobs_run_stats_idx (claim_session_id ASC, status ASC, created ASC) STORING (last_run, num_runs, claim_instance_id) WHERE status IN ('running':::STRING, 'reverting':::STRING, 'pending':::STRING, 'pause-requested':::STRING, 'cancel-requested':::STRING),
```

> We can leverage created_by columns to make this check cheap.

Unfortunately I don't think it's this simple. `created_by_type` and `created_by_id` are currently NULL for stats jobs. We could start setting these columns to take advantage of `jobs_created_by_type_created_by_id_idx`, but then we won't be able to use the `status` or `created` columns to constrain the index. We would need to scan through all stats jobs in the table (which I think includes all stats jobs started over the last 2 weeks, which could be a lot). I'm not convinced this is better than the current approach of using `jobs_status_created_idx`.

If we want to use all predicates to constrain the index, we'll probably need to add a new index on the jobs table like this:
```
INDEX jobs_created_by_type_status_created_idx (created_by_type ASC, status ASC, created ASC),
```
This will require a migration, I think.

Also, old stats jobs will not have `created_by_type` set, so we'll need to be careful about that as well.

There is one quick fix that I think I can make to the query above to use `created` in the where clause in some cases, but if we really want to fix the performance here I think we'll need a new index. Thoughts?

**Comment by miretskiy** [comment]
Even though table query uses jobs@jobs_status_created_idx, it is still reading, and decoding unrelated job records
(changefeeds, schema changes, etc). I understand that we are not setting created_by_type -- it was just an idea.
Because if we set it, then you could simply query that index.  Why do you need to see created column? I thought the goal
was to ensure that there is exactly 1 running auto stats job?  So, if you store e.g. `crdb_auto_stats` in created_by_type column, because that index also stores status, then, you could query that index to find the one and only auto stats job that's currently running?

**Comment by adityamaru** [comment]
Escalating the priority of this issue based on findings in our internal test cluster.

Changes to the jobs system for our upcoming 23.1 release seem to have made this query more expensive to run. The query no longer reads the `system.jobs` table but instead uses the `crdb_internal.system_jobs` virtual table. This virtual table performs a join between the `system.jobs` table and `system.job_info` table that store the control and execution state of each job. During a TPCE workload we have observed auto stats jobs being triggered ~5 times a minute resulting in hot ranges on the `job_info` table primarily because of the payload and progress columns that need to be unmarshalled by this query.

The purpose of this query is to ensure that there is only one stats job running in the cluster at a given time. This can be achieved without having to unmarshal payload/progress bytes and by changing our `jobs_job_type_idx` that is currently defined as an index on `job_type` to also contain the `status` of the job. This way a check for any other running jobs of type x becomes an index only scan on the `system.jobs` table and does not require materializing payload/progress columns from the `system.job_info` table.

**Comment by dt** [comment]
I do think that the created by index should include status as a suffix instead of just storing it, so that we could find _running_ jobs for a given creator, not just all jobs for a given creator, since that was the purpose of persisting "created by" in the first place.

That said, I think in most cases we don't expect a large number of jobs in the running statuses -- even if there are thousands of terminal jobs, I'd expect low double/triple digit numbers of running jobs at any given time in most clusters today, so it shouldn't be _that_ expensive, given we have an index by status to find those <1k jobs, to grab just running jobs and then filter by type after on the relatively small set. I suspect the current issue might be related to specifically virtual tables and the need to get the virtual indexes just right or end up with poor plans. #102171 rewrites the query to avoid the virtual table, so we can see if that alone helps before we change the existing indexes.

**Comment by rytaft** [comment]
I'm going to close this. If it becomes a problem in the future we can open a new issue and consider adding an index.
