### ISSUE TITLE
Update description of `crdb_internal.decode_plan_gist`

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#78510]
Since we are not exposing or documenting `EXPLAIN(GIST)` this description of the `crdb_internal.decode_plan_gist(gist: [string](https://www.cockroachlabs.com/docs/v22.1/string)) → [string](https://www.cockroachlabs.com/docs/v22.1/string)`
function should be updated: 

Returns rows of output similar to EXPLAIN from a gist created by EXPLAIN (GIST)

It should say something like:

Returns rows of output similar to `EXPLAIN` from a gist that appears in the `crdb_internal.statement_statistics->statistics->planGists` field.

**Comment by stbof** [comment]
Per @jordanlewis  and @cucaroach, these options are not user focused.

**Comment by cucaroach** [comment]
Fixed by 923ea964c6cd7a4ea068b4d6552e3ff40720aad8

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14169](https://cockroachlabs.atlassian.net/browse/CRDB-14169) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78510` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14169](https://cockroachlabs.atlassian.net/browse/CRDB-14169) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78510`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
