### ISSUE TITLE
storage: Replica.String fosters deadlocks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7852]
`Replica.String` calls `Replica.Desc` which grabs `r.mu.Mutex`. This makes `Replica.String` unsafe to call from any method which is already holding `r.mu.Mutex`. This issue is exacerbated by any log messages which wish to format a `Replica` using `%s`.

**Comment by arjunravinarayan** [comment]
I think we should change what `Replica.String()` prints. There are times when "safely print out this Replica's state in its entirety without a possibility of a race" is a valid function to want to have, but I'm not sure that function should live in the `String()` method, since `String()` has a predefined semantics (that doesn't involve not-holding a specific lock). Right now a naive logger can unwittingly put us into a deadlock (since, for example, `Store.pendingRaftGroups.Mutex` is downstream from `Replica.mu.Mutex` in the hierarchy of locks (#7736) , and if someone holding that lock unwittingly tries to log a `Replica`, boom.)

Perhaps `Replica.String` should print out something else (after all, ``Replica.mu.state.Desc` is a range descriptor, and probably not the thing people are looking for when printing out a `Replica` using `%s`?) `RangeID` is already copied outside of `Replica.mu` through `Replica.RangeID`, so perhaps we should change `Replica.String()` to print that along with `Replica.store.Ident` to get something minimally useful but that doesn't require acquiring any locks. If they want a more comprehensive string description, we can add a second method that prints the whole `Replica` state that comes from calling `Desc()`, but which has the locking behavior documented, and importantly, won't be called invisibly by a `%s`.

**Comment by bdarnell** [comment]
Once upon a time, a `Replica`'s `RangeDescriptor` was stored in an `atomic.Value` instead of being protected by a `Mutex`. We had to change because we wanted to be able to change the descriptor atomically with other things.

If we want `Desc()` to be available in `String()` (and I think we do; I appreciate seeing the start/end keys in the logs), we could use both an atomic.Value and a Mutex: it can be read at any time via the atomic.Value, but must only be modified while holding the mutex.

**Comment by petermattis** [comment]
I'd like to see the store ID included in `Replica.String()`. Perhaps also the node ID. But at least store ID to make debugging tests which interleave their log messages earlier.

Until we address #1779, I propose that every `log.{Level}*` call from `Replica` be prefixed with `%s` formatting of `Replica`. And if there are multiple replicas involved (i.e. during splits) we include both of them.

@arjunravinarayan Do you want to tackle this?

**Comment by arjunravinarayan** [comment]
Yes, I can take this on. @petermattis can you reconcile your proposal with @bdarnell's?

**Comment by petermattis** [comment]
@bdarnell Has a reasonable suggestion for how to keeping the start/end keys in the logs. I'd like to see the addition of the store ID (which is globally unique in the cluster). Something like:

```
type Replica struct {
  ...
  struct mu {
    ...
    descValue atomic.Value
  }
}
...
func (r *Replica) String() string {
  desc := r.mu.descValue.Load().(*roachpb.RangeDescriptor)
  return fmt.Sprintf("store=%d range=%d [%s-%s)", r.store.Ident.StoreID, desc.RangeID, desc.StartKey, desc.EndKey)
}
...
func (r *Replica) setDescWithoutProcessUpdateLocked(desc *roachpb.RangeDescriptor) {
  if desc.RangeID != r.RangeID {
    panic(fmt.Sprintf("range descriptor ID (%d) does not match replica's range ID (%d)",
      desc.RangeID, r.RangeID))
  }
  r.mu.state.Desc = desc
  r.mu.descValue.Store(desc)
}
```
