### ISSUE TITLE
sql: ORDER BY does not work on pg_type table when sorting by virtual index key

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#78578]
**Describe the problem**

I ran the same query twice, but the ordering was different each time

**To Reproduce**

```
root@:26257/defaultdb> select oid, typname from pg_type order by oid limit 10;
  oid  |   typname
-------+--------------
    17 | bytea
   700 | float4
   869 | inet
  1000 | _bool
  1041 | _inet
  1184 | timestamptz
  1270 | _timetz
  1562 | varbit
  2210 | _regclass
  4097 | _regrole
(10 rows)


root@:26257/defaultdb> select oid, typname from pg_type order by oid limit 10;
   oid  |    typname
--------+----------------
   1008 | _regproc
   1009 | _text
   1043 | varchar
   1083 | time
   1114 | timestamp
   1185 | _timestamptz
   1266 | timetz
   2207 | _regprocedure
  90000 | geometry
  90003 | _geography
(10 rows)
```

**Additional context**
It seems related to virtual indexes. If I order by `typname` instead, if works as expected.

**Environment:**
Using master branch, commit 9c38f656f3
v21.1.13 is also affected.

Jira issue: CRDB-14190

**Comment by jordanlewis** [comment]
This is related to virtual indexes not supporting range scans. The problem is that the optimizer assumes that using a virtual index will provide an ordering. If the execution engine for the virtual index gets a range scan, it just gives up and falls back to the normal way of generating the data in the index. But it doesn't enforce an ordering, even though the optimizer assumes it would.


I think the way to solve this would either be
1. teach the virtual index range scan case to sort its output by the indexed column
2. teach the optimizer that range scans on virtual indexes do not have an ordering
