### ISSUE TITLE
admission: SetPebbleMetrics provider should wait for store initialization

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/cockroach#78672]
Detailed context: https://github.com/cockroachlabs/support/issues/1504#issuecomment-1081117135
Fix: https://github.com/cockroachdb/cockroach/pull/78664

SetPebbleMetricsProvider has this comment:
>// SetPebbleMetricsProvider sets a PebbleMetricsProvider and causes the load
>// on the various storage engines to be used for admission control.

If the function is called before all stores are initialized, then admission control could end up not knowing about some of the stores on a node.
cc @sumeerbhola 

Jira issue: CRDB-14211

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14211](https://cockroachlabs.atlassian.net/browse/CRDB-14211) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78672`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
