### ISSUE TITLE
storage: roll back manual HardState updates

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7875]
I looked into rolling back the manual massaging of `HardState`s this morning. #7833 removes one instance, and the other is in `writeInitialState` (which is used to bootstrap a Raft group).
The reason we call this when bootstrapping a Raft group is because when we call this in the context of the `SplitTrigger`, we may have to absorb a HardState of a right-hand-side of the split which was created early by other consensus members messaging us about it (a common case).

It doesn't seem trivial to roll this one back, and looking at the previous code (`git checkout 5f78d719^`) I think that was actually broken in pretty bad ways. Back then, we didn't actually bootstrap the new range we created (or at least I wouldn't know where). That means that the new group started at log index 0 but with all the data. This works out fine for the replica set at the time of the split (after all they can't receive a RHS snapshot until they've executed the split themselves), but if we added a Replica for the RHS right after the Split, it seems conceivable that we would've been able to catch it up from the log (which would have missed all of the data on the RHS of the split). I.e. our donor group would be at index 1 (the first entry being the ChangeReplicas), the new member starts at 0, so all it thinks it needs to catch up on is the ChangeReplicas itself.

We may never have observed it in the wild, but that seems pretty bad, and there seems no way around bootstrapping the RHS in one way or another.

The way that I think we should discuss is going through Raft again. Bootstrapping the Raft group means essentially writing `HardState{5,10}` but possibly keeping a cast vote. Raft would do that for us if we asked it to apply snapshot at `Term=5` `Committed=10` which contained precisely the correct replicated state (`Truncated=10` `Applied=10`).

**Comment by bdarnell** [comment]
The code before 5f78d719 worked thanks to the dynamic logic in `raftTruncatedState` and `InitialState`. These replicas were initialized, so they'd get a first index of 10 instead of 0. This wasn't completely correct (we could have thrown away votes that were cast before the splitTrigger), but it did prevent any attempts to replay the log from zero.

In principle, sending a dummy snapshot through raft seems like a reasonable way to inform the raft group about the state we inherited from our predecessor range, but I worry that in practice it may expose us to more subtlety than simply forging the initial HardState.

**Comment by tschottdorf** [comment]
Thanks. I wonder how I manage to keep forgetting that we used to synthesize a HardState before. You'd think that was pretty central to it all.

I'll investigate using the Raft group at some point. Should be easy enough to try out this strategy in `writeInitialState`.

**Comment by tschottdorf** [comment]
Not in queue, unassigning.

**Comment by tschottdorf** [comment]
Closing as "will never happen".
