### ISSUE TITLE
Inconsistent node username permissions between versions 22.1 and 21.2

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#78948]
**Describe the problem**
In version 22.1, overriding the internal executor with the `node` username is able to get all database names across the cluster. However, on v21.2 it is only able to get the `system` database (does not get `defaultdb` or `postgres` either).

**To Reproduce**

Run this query on v22.1:
`SELECT database_name FROM [SHOW DATABASES]`
using the internal executor, overriding it with `security.NodeUserName()`.
Verify that you are able to get all database names in the cluster.

Repeat on v21.2, verify that you only get the `system` database name.

**Expected behavior**
`node` username permissions should be the same across versions, either both queries should only return the `system` database or both queries return all database names.

Jira issue: CRDB-14460

**Comment by RichardJCai** [comment]
Did some debugging, uncovered a bug that isn't actually related to the Node user itself...

The `AnyPrivilege` check always passes for databases because for some reason `Public` has an entry in the privilege descriptor but without any privileges - we don't remove the public entry even though it has 0 privileges
```
// Check if 'public' has privileges.
if privs.AnyPrivilege(security.PublicRoleName()) {
   return nil
}

// AnyPrivilege returns true if 'user' has any privilege on this descriptor.
func (p PrivilegeDescriptor) AnyPrivilege(user security.SQLUsername) bool {
	if p.Owner() == user {
		return true
	}
	userPriv, ok := p.FindUser(user)
	if !ok {
		return false
	}
	return userPriv.Privileges != 0
}
```

See here that `public` has `privileges: 0` but is still part of the PrivilegeDesc.
users:<user_proto:"admin" privileges:2 with_grant_option:2 > users:<user_proto:"public" privileges:0 with_grant_option:0 > users:<user_proto:"root" privileges:2 with_grant_option:2 > owner_proto:"root" version:2

**Comment by ajwerner** [comment]
This seems like maybe this is a release blocker or at least a GA blocker, no?

**Comment by RichardJCai** [comment]
> This seems like maybe this is a release blocker or at least a GA blocker, no?

Yeah at least a GA blocker for sure.

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/79048
