### ISSUE TITLE
storageccl: Encryption-at-rest data key rotation gets disabled after a restart

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#79066]
**Describe the problem**

When using encryption at rest, we need to be able to determine when the store and data keys have been rotated last.

**To Reproduce**

Encrypt a cluster.
Set a fast rotation-period
See that the "Created" time does not match the Store Key
See that the "Created" time for the Data Key, is in fact the Store Key.

**Expected behavior**
The "Created" times to match the created Store Key time and Data Key time.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/84391439/160897832-7c3b0892-452e-4581-83cd-3964941d47c3.png)
^Notice how active Store key is 2022, whilst our automatically generated Data key is 2021

**Environment:**
 - CockroachDB version [21.1.12]
 - Linux

Jira issue: CRDB-14528

gz#11893

**Comment by itsbilal** [comment]
Dug into the code, and it looks like there's a bug where we unintentionally disable data key rotation if we restarted the node with the same store key as the last store key. See how we only enable rotation if we're doing a new store key (the conditional for anding on the same store key as the last start has already `return nil`'d earlier in the function):

https://github.com/cockroachdb/cockroach/blob/6c91da48b8da78c13e4cb8675a1a98c5ec75ea06/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L331

The bugfix for this should be straightforward, but it looks like it affects all releases. Would this be a release blocker too for 22.1? /cc @cockroachdb/release

**Comment by jbowens** [comment]
> Would this be a release blocker too for 22.1?

Since it's existing behavior in earlier releases, I don't think it qualifies as a release blocker. We should definitely backport to 22.1.1 though.

**Comment by itsbilal** [comment]
Yep! I think this can be closed now. Thanks for pinging

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14528](https://cockroachlabs.atlassian.net/browse/CRDB-14528) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79066`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
