### ISSUE TITLE
storage: understand causes of "poor LSM health"

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79101]
_This was a follow-up from our Storage 22.1 pre-mortem ([internal doc](https://cockroachlabs.atlassian.net/wiki/spaces/STOR/pages/2496757811/Storage+Pre-Mortem+-+22.1))._

Understanding the circumstances that result in LSM inversion will likely generate a bunch of work in both Pebble and Cockroach.

This is a parent ticket tracking that work.

Jira issue: CRDB-14569

**Comment by joshimhoff** [comment]
Thinking about this on a Flex Friday, partly just as an excuse to poke at storage code.

My understanding from reading various things @sumeerbhola, @bananabrick, & others has written is the key thing is the number of sublevels in L0, as any read must check all those sublevels, which means each sublevel increases readamp. As a result, AC uses L0 sublevels & files as signals to delay writes. No signals from levels lower of the LSM are used.

**As a result of this, would it be useful to know which keys are heavily represented in L0 & above?** 

For example, in a recent-ish rather chaotic outage, we eventually determined that a certain schema change wasn't subject to admission control, due to an integration bug where a certain backfiller component didn't set the correct AC header (or something like that). It took us a long time to figure this out. Would we have figured this out faster if we could see that L0 was filled with keys from a certain user table? We'd correlate that with running jobs (and snapshots & the statements page & etc.) & have a relatively strong idea of proximate cause at least.

How would this work concretely?

I hacked `cockroach debug keys` to only return keys from L0 & above, by adding `NothingBelowL0` to `IterOptions` in `pkg/storage` & `pebble` itself. Here's the incredibly not-prod-ready POC branch, which prob is buggy also: https://github.com/cockroachdb/cockroach/pull/81983

On a local cluster on which I ran `cockroach workload run kv`, I did:

```
cockroach debug keys . > l0orabove
```

Then I did:

```
~/g/s/g/c/cockroach [working] [130] $ cat l0orabove | cut -c-10 | uniq -c
1244 /Local/Ran
   1 /Local/Sto
  59 /System/No
   1 /System/St
1387 /System/ts
  85 /Table/11/
  25 /Table/15/
   4 /Table/20/
  15 /Table/28/
  51 /Table/39/
  34 /Table/42/
  11 /Table/43/
269182 /Table/58/
```

This shows that L0 & above is full of data from the KV workload, as expected. I figure in a production ready version of this we prob want to compute the histogram in golang code, to avoid writing so much to disk. Even if we did that, I don't have a great idea of how much time it might take to scan all of L0 & above on a production cluster.

The main Q I have about this is: Would it actually be useful to know which keys are heavily represented in L0 & above?

Another Q I have is whether @nicktrav's idea in a slack thread is a better version of this:

> Some way of getting the LSM stats for a specific range, table, index, or arbitrary span. Like the /debug/lsm endpoint, but with filtering capability. So we can see if it's a specific workload (index backfill, etc.) that's inducing sadness.

I sort of wonder if the ideas are complimentary. What I'm playing with lets you determine the span that is heavily represented in L0. Nick's idea lets you pull info about some span once you already have one in mind.

**Comment by joshimhoff** [comment]
@dt has pointed out that `./cockroach debug pebble lsm` / `/debug/lsm-viz/<store-id>` (the latter appears to be broken) produces similar data re: what is getting pushed into L0, as it shows start key + end key + size per sstable, etc.!

Getting `/debug/lsm-viz/<store-id>` working would be great for cloud. Much more feasible to grant admin UI access widely than to give devs access to hard disks on which the MANIFESTs are stored. Much more ergonomic for SREs too.

**Comment by joshimhoff** [comment]
Alright, I'm convinced `/debug/lsm-viz/<store-id>` is what we need. David & I don’t see start & end keys in `/debug/lsm-viz/<store-id>`. We do see em when using `cockroach debug pebble lsm`, but that’s not available via the admin UI, and admin UI is easier to access, esp. if you are storage L2 and the outage is in cloud. IIUC, David is fixing a bug that broke `/debug/lsm-viz/<store-id> `: https://github.com/cockroachdb/cockroach/pull/81986. I’ll close a TODO David found from Peter about adding start & end keys to /debug/lsm-viz/<store-id>. Then I vote we backport.

**Comment by nicktrav** [comment]
Another example that @lunevalex ran into with a large import.

Here's a look at one node (note that the AC L0 file count max had already been bumped to 5k):

```console
Store 1:
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1   2.3 M       -    20 G       -       -       -       -    20 G       -       -       -     1.0
      0      5325    19 G    0.33    20 G   297 G   120 K     0 B       0   2.1 G    16 K     0 B      55     0.1
      1         0     0 B   21.98   171 G   300 G    97 K    30 G   9.1 K   200 G    63 K   200 G       0     1.2
      2       504   2.0 G    1.48   393 G   436 G   134 K   183 G    54 K   525 G    97 K   524 G       1     1.3
      3      2019    11 G    1.47   671 G   384 G   107 K   344 G    83 K   906 G    89 K   904 G       1     1.3
      4      8816    60 G    1.48   790 G   288 G    66 K   600 G   100 K   1.1 T    57 K   1.1 T       1     1.4
      5     51057   322 G    1.34   567 G   339 G    64 K   1.0 T   111 K   682 G    21 K   682 G       1     1.2
      6    101934   1.9 T       -   1.2 T   358 G    66 K   418 G    29 K   1.5 T    30 K   1.6 T       1     1.3
  total    169655   2.3 T       -   2.4 T   2.3 T   654 K   2.6 T   385 K   7.2 T   373 K   4.9 T      60     3.1
  flush     12055
compact    536412   1.1 T   3.2 G       3          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype    150089      56    1004  385184      79       0  (default, delete, elision, move, read, rewrite)
 memtbl         1    64 M
zmemtbl         2   128 M
   ztbl       229   3.4 G
 bcache     966 K    14 G   59.1%  (score == hit-rate)
 tcache     156 K   101 M   99.4%  (score == hit-rate)
  snaps         2       - 74785307  (score == earliest seq num)
 titers      1103
 filter         -       -   95.8%  (score == utility)
```

There was ample disk bandwidth available, yet we are limited to 3 compactions. Those three compactions were all spending time compacting levels further down in the LSM than L0. This resulted in L0 getting into Admission Control territory, which affected the overall throughput of the cluster.

After updating the compaction concurrency to 8 (around 18:36), we get far better utilization of the block device and L0 starts clearing out, eventually reaching a nice steady state.

I put the compaction log analysis output [here](https://gist.github.com/nicktrav/0c2b0ea538a1623d1cd750a32cee6d77).

Two things that stood out from this investigation:

- Compaction scoring: despite L0 having a large number of files and subleves, we were continuing to prioritize compactions at lower levels.
- The default number of compaction slots (4) is too low for an LSM of this size. We're always running 3 compactions (the remaining slot is tied up for flushes), and these 3 compactions tend to be compacting at lower levels, leaving L0 unattended. There was ample disk bandwidth available. We bumped the compaction concurrency to 8 and things improved significantly.

The recent work on soft slots will help a lot with the latter point, opening up more compaction slots when resources are available.

The first point may be a little more nuanced to address. We intentionally prioritize lower levels, as compacting higher levels increases the future compaction work (i.e. compacting out of L0 is likely creating redundant compaction work, and increasing write-amp, despite reducing the read-amp).

**Comment by jbowens** [comment]
should we remove the `O-postmortem`? this was actually an output of a _premortem_ exercise.

**Comment by nicktrav** [comment]
Removing the label sgtm.

Reading this again ticket now, it's poorly scoped. Should we consider just closing it?

**Comment by jbowens** [comment]
Sounds good
