### ISSUE TITLE
sql: SQL Stats's metadata column does not report query summary for prepared statements 

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#79152]
**Describe the problem**

The `metadata` column of the `cluster_statement_statistics` table contains two fields:
* `query`: the anonymized query
* `query_summary`: the summary version of the previous field

However, when executing a prepared statements, these two fields show inconsistencies. 

**To Reproduce**

```
root@crlMBP-Q44MFW02P7MTM3.local:26257/defaultdb> prepare tq (int) as select $1;
PREPARE


Time: 1ms total (execution 1ms / network 0ms)

root@crlMBP-Q44MFW02P7MTM3.local:26257/defaultdb> execute tq(3);
  ?column?
------------
         3
(1 row)


Time: 1ms total (execution 0ms / network 1ms)
```

Observing the `cluster_statement_statistics.metadata` column shows that:
- The `query` field contains the underlying prepared SQL Statement fingerprint: `SELECT $1`.
- The `query_summary` field is empty.

```
root@crlMBP-Q44MFW02P7MTM3.local:26257/defaultdb> SELECT metadata->>'query', metadata->>'querySummary' FROM crdb_internal.cluster_statement_statistics WHERE metadata->>'query' LIKE 'SELECT $1';
  ?column?  | ?column?
------------+-----------
  SELECT $1 |
(1 row)


Time: 11ms total (execution 11ms / network 0ms)
```

Jira issue: CRDB-14608

**Comment by ericharmeling** [comment]
Based on the issue description, this is my understanding of the expected/desired behavior: 

In the case of prepared statement executions, the underlying SQL query of each prepared statement execution record in the `statement_statistics` table  (listed in its entirety in the `query` field of the `metadata` column) should be summarized in the `query_summary` field of the `metadata` column, rather than the `EXECUTE` statement that executes the prepared statement.

Is this correct?

**Comment by ericharmeling** [comment]
Update:

As of https://github.com/cockroachdb/cockroach/commit/ce1b42bd341cc5f87357ecf82027b3dd5a3e88c1, the original behavior reported by this issue has changed. I've updated the issue title and description with output from a build on https://github.com/cockroachdb/cockroach/commit/e67e47f72225da1e4b4b895814a4661d3c1a96a3.
