### ISSUE TITLE
Proxying to specific nodes in DB Console errors out for Dedicated clusters

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#79164]
**Describe the problem**

Reported by @dhartunian Proxying to specific nodes from DB Console does not work at all for 21.2 clusters when connecting to a cluster from CockroachDB Dedicated

Jira issue: CRDB-14614

**Comment by dhartunian** [comment]
When testing with a cluster using version `v21.2.7` I received mostly 502 Bad Gateway errors on the cluster.

**Comment by dhartunian** [comment]
I think this is due to the fact that this feature uses the `http-host` field to route requests to nodes, but we set that param to `0.0.0.0` for clusters since they're only accessed through an LB.

**Comment by dhartunian** [comment]
I think we might need to modify the logic of how the `HTTPAdvertiseAddr` is computed.

Currently, there is no CLI Flag that sets this directly so it's set in the following order:
1. If no flags are set, it gets the `os.Hostname()` result
2. If `--advertise-host` is set (but not `--http-host`), it gets that value
3. If `--http-host` is set, it gets that value

I wonder if 3 above should not override 2 for the `HTTPAdvertiseAddr` since it seems more natural for it to be tied to the advertise host, and not the listener host.

@knz what do you think? I could also just add a flag to set it directly that always overrides everything but I'd prefer not to. I'm also unsure what use the `HTTPAdvertiseAddr` has otherwise (to try and think of what this change could break...), I can't find an obvious use for it within the DB itself prior to my proxy code.

**Comment by knz** [comment]
We can't change the override behavior without breaking multi-interface systems behind NAT.

We need a new `--advertise-http-host`.  That was an unreasonable asymmetry and it's a good time to fix it.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14614](https://cockroachlabs.atlassian.net/browse/CRDB-14614) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79164`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
