### ISSUE TITLE
ui: custom charts do not work with tsdumps

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79195]
**Describe the problem**

When booting a cluster with a tsdump (i.e. using the `COCKROACH_DEBUG_TS_IMPORT_*` environment variables), creating custom charts does not work.

Specifically, when attempting to create a chart from the `/debug/chart` page in the console, no metrics are visible in the "Select a metric" drop down. However, metrics _are_ visible when using the main `/metrics` page.

**To Reproduce**

Boot a cluster with a tsdump containing metrics in the past:

```bash
$ COCKROACH_DEBUG_TS_IMPORT_FILE=/path/to/tsdump.gob COCKROACH_DEBUG_TS_IMPORT_MAPPING_FILE=/path/to/tsdump.gob.yaml ./cockroach start-single-node --store $(mktemp -d) --insecure --logtostderr
```

Browse to `http://localhost:8080/#/debug/chart`.

Attempt to select a metric. Nothing is available.

As a workaround, if one knows the metric name(s), the cluster can be booted _without_ the tsdump, and the custom charts can be set up. The cluster can then be rebooted with the tsdumps, and the custom chart page refreshed. The metrics appear.

**Expected behavior**

When viewing metrics from a tsdump with metrics in the past (e.g. when performing diagnostics as part of a support investigation), custom charts should be able to be created.

**Additional data / screenshots**

Example of not being able to select metrics (see bottom left):

![Screenshot from 2022-03-31 18-34-17](https://user-images.githubusercontent.com/804457/161177528-de4a4777-065d-4177-b193-0f900a2c3da1.png)

**Environment:**
 - CockroachDB version: `master` @ ed695f004a
 - Server OS: Linux.

Jira issue: CRDB-14628

**Comment by tbg** [comment]
I ran into this too - I know tsdump is a relatively new tool for us to really embrace, but this turns out to be a fairly severe limitation. We have lots more metrics than we show on the standard graphs, and life would be a lot better if we could use the custom graphing tool. This is likely a small fix (if I knew where to look I would've fixed it already) but with a large upside.

**Comment by nicktrav** [comment]
I just verified this on the tsdumps that I was originally having issues with and it LGTM! Thanks a ton for fixing this!

**Comment by tbg** [comment]
Thank you @zachlite 🥳

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14628](https://cockroachlabs.atlassian.net/browse/CRDB-14628) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79195`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
