### ISSUE TITLE
roachtest: encryption at rest configurations aren't respected when creating clusters

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79265]
**Describe the problem**

A recent change in #76669 altered the way that tests were opted into using encryption at rest (EAR).

Consider a test that should _always_ run with EAR (like [this one](https://github.com/cockroachdb/cockroach/blob/005b6ec40a96c41882f86be355996b1e4cef4dee/pkg/cmd/roachtest/tests/encryption.go#L33)). After the refactor, the test is required to explicitly opt into random EAR by setting `EncryptAtRandom` on the `TestSpec` (a bit of an API wrinkle, as this test _always_ wants EAR, not randomly).

However, even if that flag were `true`, EAR is only on 50% of the time (see [here](https://github.com/cockroachdb/cockroach/blob/005b6ec40a96c41882f86be355996b1e4cef4dee/pkg/cmd/roachtest/cluster.go#L111)), which makes the test flaky.

**Expected behavior**

A roachtest that always wants EAR should be have its settings respected.

Epic: CRDB-10428
Jira issue: CRDB-14664

**Comment by nicktrav** [comment]
Related to #78125.

**Comment by srosenberg** [comment]
The current logic is still too convoluted,

- `encrypt` is a global and defaults to `random` (for nightlies)
- we use it to set `encAtRest` [1] per cluster
- then, we use `encAtRest` to override `startOpts.RoachprodOpts.EncryptedStores` for the same cluster

It bears simplification. Why not lift `encAtRest` into `TestSpec` where `EncryptAtRandom` already lives?

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L602
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/cluster.go#L1796

**Comment by tbg** [comment]
`encrypt` is not only a global variable, it is a flag. This is so that you can run `roachtest run --encrypt ...`.

> It bears simplification. Why not lift encAtRest into TestSpec where EncryptAtRandom already lives?

because then you can't run `roachtest run --encrypt=X` any more, since now the encryption is hard-coded per test. Maybe that is fine - we don't seem to be using the `--encrypt` flag anywhere - but at least when running the test it is highly desirable to stick to one. It would be annoying to have to repro a test that specifies random encryption but only fails in one of the two cases. A local code modification would be necessary and that would create hoops to jump through in order to let CI stress the test for you.

I think there generally is merit to letting tests decide (and we do already [do that](https://github.com/cockroachdb/cockroach/blob/90d5c80e1bfc08dec898e51181dac7cd1509f6ba/pkg/cmd/roachtest/tests/kv.go#L232) until I guess I broke it with this issue), as long as it's deterministic. Maybe what we ought to do is to let the test decide between

- allow both
- allow only on
- allow only off

where the actual determination of randomness (if supported) is made on a test-by-test basis behind `roachtest run --encrypt=random`, which CI would have to pass automatically. (with "on", tests that don't support encryption would be skipped; with off vice versa).

**Comment by renatolabs** [comment]
@tbg's suggestion makes sense to me. If anyone has another suggestion they'd like to discuss, let me know.
