### ISSUE TITLE
sql/importer: IMPORT INTO tables with virtual uniqueness constraints can create duplicates

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#79281]
```
> create table mr.foo (id int primary key) locality regional by row;
CREATE TABLE

> insert into mr.foo (crdb_region, id) values ('europe-west1', 1);
INSERT 1

> import into mr.foo csv data ('http://localhost:8000/one.csv');
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  749928995025092609 | succeeded |                  1 |    1 |             0 |    13

> select * from mr.foo;
  id
------
   1
   1
```

We need to run a post-import validation similar to post-backfill https://github.com/cockroachdb/cockroach/blob/6b50953299b32480bd536279cd79243fcc85020e/pkg/sql/check.go#L529

Jira issue: CRDB-14671

**Comment by dt** [comment]
Initial fix is in https://github.com/cockroachdb/cockroach/pull/79293 but I'm going to keep this open until the release blocker is cleared with backports to 21.2 and 22.1

**Comment by dt** [comment]
#79323 + #79326

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14671](https://cockroachlabs.atlassian.net/browse/CRDB-14671) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79281` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14671](https://cockroachlabs.atlassian.net/browse/CRDB-14671) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79281`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done. couldn't replicate one of the labels but i'm not losing sleep over it
