### ISSUE TITLE
Support multiple clusters in a roach test

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#79305]
We need to support running multiple crdb clusters in single roachtest, either through muliple crdb clusters in a roachprod cluster or multiple roachprod clusters in single roachtest.

Previous efforts: https://github.com/cockroachdb/cockroach/pull/62315

Jira issue: CRDB-14682

Epic CRDB-18751

**Comment by andreimatei** [comment]
There's nothing preventing a test from using roachprod however it wants - e.g. to create a 2nd cluster. Is this issue asking for specific integration of the 2nd cluster into the test framework - like the collection of artifacts?

**Comment by gh-casper** [comment]
Sorry I missed the comment. The integration for the collection of artifacts from 2nd cluster is surely one thing to do. Also, If you already created a cluster with a subset of nodes, you cannot create another cluster with the rest of nodes because the two cluster will join together.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14682](https://cockroachlabs.atlassian.net/browse/CRDB-14682) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79305`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira

**Comment by shermanCRL** [comment]
From a conversation with @stevendanna and @gh-casper: there is a hacky version and a more elegant version, the latter of which will wait for work in roachtest. Let’s do the less-beautiful version now.

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/90051
