### ISSUE TITLE
Unit tests that test sink handles duplicate information from stream

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#79304]
As a db operator, I want the “sink” to gracefully handle duplicate information so that I don’t have to worry about, if I have to restart a stream, getting the timestamp exactly correct so that I can get my system up quickly without having to worry about getting details exactly right.

We should have a test that explicitly tests whether replayed messages cause any corruption problems.  One possible way to do this would be add a testing hook that randomly injects duplicates into our existing tests so that we get a wide amount of coverage.

Jira issue: CRDB-14681
Epic CRDB-7077

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14681](https://cockroachlabs.atlassian.net/browse/CRDB-14681) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79304`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira

**Comment by gh-casper** [comment]
I think we already have [random_stream_client](https://github.com/cockroachdb/cockroach/blob/b96b07db8d7179a1dd7b212af3e7993e5ed66f62/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L320) that generates duplicate events and [TestStreamIngestionJobWithRandomClient](https://github.com/gh-casper/cockroach/blob/1b0b127ac644b7f80a284e84360f40c3b90808bd/pkg/ccl/streamingccl/streamingest/stream_ingestion_test.go#L73) is testing it. 
The scope of this issue becomes we should extend other tests to use random_stream_client by some probability.
