### ISSUE TITLE
decode plan gist returns 'unknown'

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#79429]
`crdb_internal.decode_plan_gist()` is returning `  • <unknown>` for some queries.

Start demo (I started without multi tenant, not sure if makes a difference `./cockroach demo --insecure --multitenant=false`)
The statements of type `alter table ... add foreign key ...` are all returning the same gist that fails to be decoded.

e.g.
```
root@127.0.0.1:26257/movr> explain (gist) ALTER TABLE user_promo_codes ADD FOREIGN KEY (city, user_id) REFERENCES users (city, id);
  info
--------
  Ais=
(1 row)


Time: 4ms total (execution 3ms / network 0ms)

root@127.0.0.1:26257/movr> explain (gist) ALTER TABLE rides ADD FOREIGN KEY (city, rider_id) REFERENCES users (city, id);
  info
--------
  Ais=
(1 row)


root@127.0.0.1:26257/movr> select crdb_internal.decode_plan_gist('Ais=');
  crdb_internal.decode_plan_gist
----------------------------------
  • <unknown>
(1 row)
```

Jira issue: CRDB-14846

**Comment by cucaroach** [comment]
This comes from here:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/exec/explain/emit.go#L262

Basically "alter table" DDL commands are opaque operations that have no substance from an explain perspective, ie here's what normal explain shows:

```
demo@127.0.0.1:26257/movr> explain ALTER TABLE user_promo_codes ADD FOREIGN KEY (city, user_id) REFERENCES users (city, id);
         info
-----------------------
  distribution: local
  vectorized: true

  • alter table
(4 rows)
```

We lose the "alter table" because we don't encode the opaque operator metadata in the gist.  I guess we could but I'm not sure what the point would be, would encoding more information about opaque operations in gists be of any value?

**Comment by maryliag** [comment]
Thank you for explaining this! I'm okay with defining this behaviour (about returning unknown) as work by design
