### ISSUE TITLE
kvserver: proactively enqueue replicas for a decommissioning node

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#79453]
Came up in a conversation with, and proposed by, @lidorcarmel. 

Today, the `replicaScanner` on each store in the [cluster keeps pacing through its replicas](https://github.com/cockroachdb/cockroach/blob/89d5d471bfabe510e9c84d50b33914aca9d7f890/pkg/kv/kvserver/scanner.go#L277-L283) (such that it processes each replica once roughly every 10 mins). The `replicaScanner` keeps optionally queuing these replicas into [each of the store's queues](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/store.go#L713-L723). 

When a node is decommissioning, this status gets broadcast to other nodes in the cluster via gossip. So when the replicateQueue encounters a replica _that is the leaseholder_ for a range that has a [replica on a decommissioning node](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/allocator.go#L739-L746), it decides to take action to move that decommissioning replica away. 

The issue here is that this discovery of decommissioning replicas is limited by the `replicaScanner`s 10 min scanning interval. This means that, generally, even the _discovery_ of all replicas belonging to a decommissioning node will take ~10 mins. Furthermore, if there are any errors [processing any of these decommissioning replicas](https://github.com/cockroachdb/cockroach/issues/79266), they will not be re-processed for another 10 mins. 

This issue proposes that we should actively enqueue all replicas belonging to a decommissioning node, into the `replicateQueue`s of all of a node's stores the moment it learns that a node's liveness record has changed from `LIVE` to `DECOMMISSIONING`. Care will need to be taken to ensure that we're only enqueuing these replicas exactly once when the status of a node changes to `DECOMMISSIONING`. Doing this should considerably cut down on how long it takes to decommission nodes in almost all scenarios, and, anecdotally, it also seems like the behaviour that operators intuitively expect. 

cc @cockroachdb/kv-notifications 

Jira issue: CRDB-14873

Epic: CRDB-14621

**Comment by erikgrinaker** [comment]
Related to #79318.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14873](https://cockroachlabs.atlassian.net/browse/CRDB-14873) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79453` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14873](https://cockroachlabs.atlassian.net/browse/CRDB-14873) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79453` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14873](https://cockroachlabs.atlassian.net/browse/CRDB-14873) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79453`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date
