### ISSUE TITLE
kvserver: disk space utilization thresholds for rebalancing should be tunable

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#79461]
Came up in a conversation with, and proposed by @lidorcarmel. 

Currently, the allocator will stop rebalancing to a node if its [disk is >92.5% full](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/allocator_scorer.go#L54-L61) and it will start actively moving replicas away from the node if its [disk is >95% full](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/allocator_scorer.go#L49-L52). These are unfortunately static constants. 

We should make these tunable and perhaps even consider reducing the default to some degree, since the allocator's reactivity to a store nearing disk saturation is limited by how fast the system can move data off of a given store. It stands to reason that in some cases, we want the allocator to be moving replicas off of a store way before it hits 95% disk utilization, as that might be too late. 

cc @cockroachdb/kv-notifications 

Jira issue: CRDB-14874

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14874](https://cockroachlabs.atlassian.net/browse/CRDB-14874) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79461` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14874](https://cockroachlabs.atlassian.net/browse/CRDB-14874) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79461`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/pull/97409.
