### ISSUE TITLE
storage,admission: io admission uses criteria storage does not act on

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79463]
**Describe the problem**

The IO overload admission control granter considers the number of files in L0. Pebble's compaction heuristic doesn't
consider the number of files in L0. In some cases, the number of files in L0 can be high to the point that IO is limited,
but the LSM will never run a compaction. This can lead to starvation where new writes need to occur to trigger compaction
but all new writes are prevented. 

**Additional context**

Should we really ever let the IO admission control get to a point where we admit no requests over an interval. 

Jira issue: CRDB-14875

**Comment by jbowens** [comment]
Linking to cockroachdb/pebble#1623

**Comment by sumeerbhola** [comment]
I think we've agreed in https://github.com/cockroachdb/pebble/issues/1623#issuecomment-1089271045 that L0 ought to have a score > 1 (significantly) before admission control limits are reached. There is still the inconsistency that admission control is using file count while the Pebble PR is using L0 bytes, so there is the possible pathological case of very tiny files.

**Comment by jbowens** [comment]
Fixed on 22.1. Will be fixed on master by the next Pebble bump.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14875](https://cockroachlabs.atlassian.net/browse/CRDB-14875) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79463`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
