### ISSUE TITLE
bazel: SQLite logic tests not being run with crdb_test_off

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#79478]
The SQLLite logic tests are failing because of checks that are only enabled when crdb_test build tag is on.   This is captured in https://github.com/cockroachdb/cockroach/issues/78615.    Its not clear why the recipe in build/teamcity/cockroach/nightlies/sqlite_logic_test_impl.sh isn't working.

Jira issue: CRDB-14879

**Comment by rickystewart** [comment]
@cucaroach Okay, so the issue is that Bazel is configured to always use the `crdb_test` machinery when running via `bazel test`, even if you have the `crdb_test_off` flag set.

I'll look at some options and see how we can fix it. Probably I can run the test via `bazel run` to work around it.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14879](https://cockroachlabs.atlassian.net/browse/CRDB-14879) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79478` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14879](https://cockroachlabs.atlassian.net/browse/CRDB-14879) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79478`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and updated

**Comment by kenliu-crl** [comment]
manually reviewed and updated (again)
