### ISSUE TITLE
cdc: issue with ALTER CHANGEFEED 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#79502]
When running ALTER CHANGEFEED job_id UNSET resolved, I get the error: ERROR: target "vehicles" cannot be resolved as of the high water mark. Please wait until the high water mark progresses past the creation time of this target in order to add it to the changefeed.

This error does not make sense in my situation, as the changefeed was already successfully running on the vehicles table before I paused it. This looks like it might be a larger issue. 

Went through these steps twice, got the same result. https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2502689706/Acceptance+Testing+Alter+Changefeeds+22.1

Jira issue: CRDB-14894

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14894](https://cockroachlabs.atlassian.net/browse/CRDB-14894) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79502`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
