### ISSUE TITLE
Remove requirement for Admin role.

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#79571]
**Is your feature request related to a problem? Please describe.**
Our users can't use the admin account.

No feature should be gated behind the admin.

Every feature should be grantable, via a role.

In theory, a user with access to all roles, should be equivalent to admin. 

**Describe the solution you'd like**
Every line of code that is gated by things like isAdmin must have an equivalent when we call method hasRoleOption(ctx, userName, roleoption)

**Describe alternatives you've considered**
Giving out admin, which is untenable. 

Jira issue: CRDB-14911
Epic CRDB-17640

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14911](https://cockroachlabs.atlassian.net/browse/CRDB-14911) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79571`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
Done with sync

**Comment by rafiss** [comment]
The internal “isAdmin” functions/names in our code could be changed to include the word "unsafe" or "deprecated" or something like that.
