### ISSUE TITLE
bulkio: rate limit setting(s) for bulk operation using cloud storage

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#79588]
**Is your feature request related to a problem? Please describe.**

When CockroachDB is deployed in an on-premise environment with a dedicated, shared and limited cloud connection (e.g., Google Cloud Interconnect), there is no way to limit the network bandwidth that is used during bulk operations, such as BACKUP and RESTORE. During these operations, CockroachDB can saturate the network connection and impact other applications within the on-premise infrastructure.

**Describe the solution you'd like**

Expose a cluster setting that is a network rate limit on bulk operations using cloud storage. A rate limit already exists for `kv.bulk_io_write.max_rate` - something similar could be created for network usage.

**Describe alternatives you've considered**

* The cluster setting `kv.bulk_io_write.concurrent_export_requests` was lowered to try to reduce BACKUP throughput but had little effect.
* An alternative considered was to rate limit the network connection outside of CockroachDB, but due to limited capabilities in the cloud connections, this was not a viable option.

**Additional context**

As an example, a 64-node cluster with 5 TiB data using a shared 5 GiB/s cloud connection could saturate that connection.

Jira issue: CRDB-14929

---

### Work in progress

- [x] https://github.com/cockroachdb/cockroach/pull/80200
  - [x] https://github.com/cockroachdb/cockroach/pull/80243 
- [x] https://github.com/cockroachdb/cockroach/pull/80261
  - [x] https://github.com/cockroachdb/cockroach/pull/80281

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14929](https://cockroachlabs.atlassian.net/browse/CRDB-14929) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79588`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
Done with sync
