### ISSUE TITLE
Improve IMPORT performance for larger unsorted data sets of

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#79615]
**Is your feature request related to a problem? Please describe.**

When attempting to run IMPORT using un-sorted Avro data, the IMPORT runs very slowly for larger data sets (e.g., > 1 TiB). 

For example, running IMPORT on a 16 x 16vCPU cluster with 64 x 24 GiB un-sorted Avro files (1.5 TiB) takes about 30 hours, which averages ~2.8 MiB/node/sec.

Smaller IMPORTs, such as running IMPORT on a 10 x 16vCPU cluster with 20 x 5.7 GiB un-sorted Avro files (114 GiB) takes about 35 minutes, which average ~17 MiB/node/sec .

**Describe the solution you'd like**

Ideally, there would be higher throughput and predictable scaling for larger un-sorted Avro data sets.

**Describe alternatives you've considered**

Sorting the Avro data within and across files was considered but does not fit into the existing workflow / datasource.

**Additional context**

https://github.com/cockroachlabs/support/issues/1464

Jira issue: CRDB-14945

---

### Work in progress

- [x] https://github.com/cockroachdb/cockroach/pull/79967
  - [x] https://github.com/cockroachdb/cockroach/pull/80386
- [x] https://github.com/cockroachdb/cockroach/pull/81062
  - [x] https://github.com/cockroachdb/cockroach/pull/82746

#### Investigations & prior art

- https://github.com/cockroachdb/cockroach/pull/73514 (mostly reverted below, considering resuscitating)
- https://github.com/cockroachdb/cockroach/pull/73981 (mostly reverts above)

Epic CRDB-16237

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14945](https://cockroachlabs.atlassian.net/browse/CRDB-14945) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79615`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by nicktrav** [comment]
We now have #81062 that adds some heuristics for determining when to use prefix seeks (which will make use of table bloom filters). That PR also enables writing L6 filter blocks by default.

The prefix-seeks heuristic change will be backported. The default L6 filter will not - instead, we've added a parse hook that can be used to enable writing these filters if a user has a workload that we think would benefit from writing L6 filters.

**Comment by nicktrav** [comment]
@jonstjohn - I closed out the remaining task for the collision checks. Is there anything else left to address on this issue?

**Comment by shermanCRL** [comment]
@nicktrav would you add those PRs/issues to the “Work in progress” checklist in the top comment? Thanks.

**Comment by nicktrav** [comment]
@shermanCRL - we had #81062, which I've marked as closed. I believe there's still a backport of the first commit in that PR that's still required. cc: @itsbilal - can you handle the backport and link to the description?

I believe that was all that we had on our end.

**Comment by shermanCRL** [comment]
@nicktrav thanks

**Comment by itsbilal** [comment]
The 22.1 backport PR is ready for review: https://github.com/cockroachdb/cockroach/pull/82746 , and it nets a similar relative improvement in a test run of an unsorted Avro import (with L6 bloom filters manually enabled) as we saw when that change went in on master.

However 22.1 seems to be noticeably slower than master, 11h vs 6h for the same import (something that I'm confirming by running the latest master again side-by-side), and a glance at the CPU profile showed a pretty high rate of false positives from the bloom filter `mayContain` on sstables, higher than what I remember being the case for master. So some threads to continue pulling here.

**Comment by nicktrav** [comment]
Let's plan on closing this out when the backport lands. 

There's likely more work to do around the false positive rate, which we can spin off into a separate issue - if we find something concrete.

**Comment by nicktrav** [comment]
Backport landed, so I'm going to close this out.
