### ISSUE TITLE
ui: update props for raft messages component

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#79614]
**Describe the problem**
The datepicker and graph timewindow selector are broken on `/#/raft/messages/all`. This can be fixed by passing the `RaftMessages` component the `setMetricsFixedWindow` and `setTimeScale` props and passing those into the `MetricsDataProvider`. 

**To Reproduce**

What did you do? Describe in your own words.
Load the raft messages page from the advanced debug tab and try dragging-to-zoom on a timeframe on the graph or selecting a date/time with the datepicker.

**Expected behavior**
Be able to drag-to-zoom to a timeframe and use the datepicker.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - Latest CRDB version

**Additional context**
What was the impact?

Jira issue: CRDB-14944

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14944](https://cockroachlabs.atlassian.net/browse/CRDB-14944) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79614`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
