### ISSUE TITLE
cancel jobs on nodes that are draining

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#79668]
**Is your feature request related to a problem? Please describe.**
When draining node, cancel jobs running on it to avoid blocking shutdown for prolonged periods of time.
Nodes gracefully close client connections as queries complete and move away leases but it can't get rid of background jobs that could be running. Eagerly cancelling job related queries would make restart experience better.
That would also make it better for clients as sometimes cockroach nodes are being killed if they fail to shutdown within some arbitrary timeout as there's no way to figure out if node is stuck or not.

**Additional context**
Motivation for this feature is #79665 where restart tests were significantly slowed down by background stats update queries. Normal draining of leases and foreground traffic is usually fast, but background tasks could take a while.

Jira issue: CRDB-14971

**Comment by miretskiy** [comment]
Actually, this ctx stuff is a red herring; I think jobs/cancel loop does the right thing.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14971](https://cockroachlabs.atlassian.net/browse/CRDB-14971) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79668` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14971](https://cockroachlabs.atlassian.net/browse/CRDB-14971) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79668`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date

**Comment by miretskiy** [comment]
I believe recent changes around handling of transient errors in changefeeds should have addressed this issue.
