### ISSUE TITLE
backupccl: backups with AOST can lead to out of order incremental backups

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#79674]
Currently, we allow a prevvious backup startTime to be greater than a AOST incremental backup endTime. The queries below were executed within 30s of each other. That last inc backup with AOST should fail even if it doesn't have any data in it: 
```
demo@127.0.0.1:26257/movr> BACKUP INTO LATEST IN 'userfile:///baz';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+---------
  751597501272686593 | succeeded |                  1 |   24 |            17 | 493262
(1 row)


Time: 234ms total (execution 233ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE DATABASE boo;
CREATE DATABASE


Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/movr> BACKUP INTO LATEST IN 'userfile:///baz' AS OF SYSTEM TIME '-30s';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  751597592251301889 | succeeded |                  1 |    0 |             0 |     0
(1 row)


Time: 193ms total (execution 193ms / network 0ms)
```

Oh no it gets worse! The next incremental backup fails and the whole chain is ruined:
```
demo@127.0.0.1:26257/movr> BACKUP INTO LATEST IN 'userfile:///baz';
ERROR: new backup would not cover expected time: no backup covers time [1649439708.350216000,0,1649439754.630758000,0) for range [/Table/4/1,/Table/4/2) (or backups listed out of order)

```

When a user attempts to use an AOST when appending -- via latest or explicit subdir -- and that time is less than the start time of the prior backup they are appending, we need to hard fail. End time cannot be before start time, and we should check/test if starttime > endtime explicitly, especially with the new backup syntax.  

This check may require refactoring some of backup planning, described [here](https://github.com/cockroachdb/cockroach/pull/79447#issuecomment-1093071433). 

Jira issue: CRDB-14973

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14973](https://cockroachlabs.atlassian.net/browse/CRDB-14973) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79674` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14973](https://cockroachlabs.atlassian.net/browse/CRDB-14973) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79674`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date
