### ISSUE TITLE
SHOW BACKUP:  Indicate if backup is multi region and how many regions.

### ISSUE THREAD

**Issue by carlsongould** [cockroachdb/cockroach#79681]
### Summary
Working with a partner that has test data management as part of their portfolio.   They were looking to identify if there a way to know if a previously taken backup is multi region? 

_For example:_
Cluster A is multi-region and a cluster backup is created and writes to gcp cloud storage.
We restore to cluster B .       Prior to doing so we want to validate if the backup is multi region or not AND to identify how many regions.   

Currently SHOW BACKUP provides the following output fields:

- database_name
- parent_schema_name
- object_name
- object_type
- backup_type
- start_time
- end_time
- size_bytes
- create_statement
- is_full_cluster
- path

### Request
Can we add 2 columns to the output of SHOW BACKUP: 
_Column_: **is_multi_region** _Description_: Indicate true/false if a cluster backup is multi region. 
_Column_: **has_regions**  _Description_: Indicate the number of regions for.a cluster backup.

**Other methods:**
Indicate the if a backup is multi region and number of regions in the path. 
Example:  <year>/<month>/<day>-<timestamp>/<multi:non-multi>/<number of regions>

Jira issue: CRDB-14976

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14976](https://cockroachlabs.atlassian.net/browse/CRDB-14976) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79681` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14976](https://cockroachlabs.atlassian.net/browse/CRDB-14976) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79681`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by saichatla** [comment]
Can I try my hand at this?

**Comment by msbutler** [comment]
@saichatla thanks for volunteering to take this on! This is pretty straightforward to implement for database regions, but not for cluster regions; see multiregion docs for [reference](https://www.cockroachlabs.com/docs/stable/multiregion-overview.html).  The bulk team (responsible for backup), will chat about this issue in the next week or so and will provide further direction on next steps. Please hold tight for now!

**Comment by saichatla** [comment]
Thank you! I will be waiting for your response.

**Comment by msbutler** [comment]
@saichatla Alright, we think this would be a good issue for you to pick up. It should only a day or 2 of work. Do you have time to work on this in the next two weeks? We'd like to get this in to our next release, which gets finalized in August. 

Here's the idea:
- We want to add an additional column, called `Regions`, to the SHOW BACKUP return table which displays the [ALTER DATABASE](https://www.cockroachlabs.com/docs/stable/alter-database.html) cmds that would create the multi region specs for that backed up database. For rows in the SHOW BACKUP  return table that describe other objects (e.g. schema, table etc), this new column's value should be null. This column should appear if and only if a database in the backup is multiregion. We are not concerned about cluster level regions in this PR. 
- Here's an example of what the new column's value would be for a 3 region database: 
```
ALTER DATABASE movr_4 PRIMARY REGION "aws-us-east-1"; ALTER DATABASE movr_4 ADD REGION "aws-eu-west-2"; ALTER DATABASE movr_4 ADD REGION "aws-eu-west-3";
```
- In terms of implementation:
   - All of your work should occur in the[ pkg/ccl/backupccl/show.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/show.go)
   - Check our restore_job for info on how to reason about multigiion info stored in database descriptors in the backup manifest (the backup metadata file-- the only thing used in SHOW BACKUP)
   
https://github.com/cockroachdb/cockroach/blob/75a18a86e74d7f996011881203edf8107b3decbc/pkg/ccl/backupccl/restore_job.go#L847-L870

   - Check out for how we construct the sql cmds returned when the user runs `SHOW BACKUP ... with privileges`
  
https://github.com/cockroachdb/cockroach/blob/75a18a86e74d7f996011881203edf8107b3decbc/pkg/ccl/backupccl/show.go#L925-L970

- when the feature is ready for testing, I'd create a new test data file in `ccl/backupccl/testdata/show/multiregion`. You can run the data driven test by running `./dev test pkg/ccl/backupccl --filter TestDataDriven`

**Comment by saichatla** [comment]
@msbutler Yep! I will get it done ASAP!

**Comment by msbutler** [comment]
@saichatla how's this going? We may need to pick this up to slip it into our next release unless you have a PR ready.

**Comment by saichatla** [comment]
Sorry. I have been dealing with  some personal family emergency for the past three weeks.

**Comment by saichatla** [comment]
> Sorry. I have been dealing with some personal family emergency for the past three weeks.

I can look at it today but I don’t see the the folder you mention for testing. @msbutler

**Comment by msbutler** [comment]
Sorry to hear about the personal stuff. Again, we're happy to take over from here, if you don't have capacity. Please just let us know!

Within the `pkg/ccl/backupccl/testdata/` directory, I think you should create a `show` subdirectory with a file called `multiregion`.

**Comment by saichatla** [comment]
> Sorry to hear about the personal stuff. Again, we're happy to take over from here, if you don't have capacity. Please just let us know!
> 
> Within the `pkg/ccl/backupccl/testdata/` directory, I think you should create a `show` subdirectory with a file called `multiregion`.

If you want to take over that is fine, since this is on a time crunch. @msbutler I did not expect to be dealing with some of the things I have been dealing with.

**Comment by msbutler** [comment]
Cool, I'll think we'll take over from here!

**Comment by msbutler** [comment]
hey @saichatla. After speaking again with the team, we've decided this issue is no longer high priority and under a time crunch. Please let me know if you'd like to give it a try, and I'll reassign you!

Sorry for all the admin back and forth.
