### ISSUE TITLE
changefeedccl: high watermark advancing with credentials error

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#79695]
When creating a changefeed in gc pubsub, the high watermark advances and the jobs table doesn't show a retryable error, even when I use a topic that does not exist, and credentials that are not associated with the non-existant topic. I do see this error in the logs:

<img width="948" alt="Screen Shot 2022-04-08 at 4 42 35 PM" src="https://user-images.githubusercontent.com/13264141/162527289-db2f91e5-46aa-44a1-a95f-343b5792a40e.png">

To reproduce, follow the steps [here](https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/edit-v2/2504097804?) to set up a changefeed to gc pubsub, then change the topic name you're sending to to one that does not exist.

Jira issue: CRDB-14982

**Comment by amruss** [comment]
Closing, actually looks like it just creates the topic and you don't need credentials tied to the topic

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14982](https://cockroachlabs.atlassian.net/browse/CRDB-14982) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79695` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14982](https://cockroachlabs.atlassian.net/browse/CRDB-14982) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79695`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by kenliu-crl** [comment]
manually reviewed and updated
