### ISSUE TITLE
storage: limit poor LSM health degradation via last line of defense protections in Pebble

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79956]
Currently, Cockroach relies heavily on Admission Control (AC) to protect the store on a node from falling into a "poor health" regime (most typically "LSM inversion", created when are large amount of data is resident in L0, across multiple sublevels, contributing to high read amplification). AC typically "knows more" about operations being executed on a store and can therefore make better decisions on what to allow / throttle than, say, Pebble itself.

However, there exist gaps in AC today that can result in poor LSM health (sometimes significant, as evidenced by a recent example, #79115). These poor health situations are typically difficult to recover from without invasive operator intervention (taking the affected node offline, performing an often lengthy manual compaction; or decommissioning the node entirely).

As a "last line of defense", Pebble could back-pressure or stall writes entirely to prevent a further degradation of health.

Currently, a [hard limit on L0 sublevels exists](https://github.com/cockroachdb/pebble/blob/99d8a549c1a84e8da9873e40fd35078f37528ced/options.go#L533-L537), [defaulting to 12 in Pebble](https://github.com/cockroachdb/pebble/blob/99d8a549c1a84e8da9873e40fd35078f37528ced/options.go#L751), and [1,000 in Cockroach](https://github.com/cockroachdb/cockroach/blob/33d1b296bd5cbb3f8d2d54f74dafa17b55b24dee/pkg/storage/pebble.go#L582). For comparison, AC currently considers a store overloaded with an [20 L0 sublevels and 1,000 L0 files](https://github.com/cockroachdb/cockroach/blob/33d1b296bd5cbb3f8d2d54f74dafa17b55b24dee/pkg/util/admission/granter.go#L1300-L1317).

It should be noted that employing hard limits in Pebble as a last line of defense comes with some risks - writes below raft would be halted, and the failures modes would be less graceful (compared to AC, which still allows some progress in a store overload situation).

Any tuning of hard limits in Pebble should come with associated dynamically adjustable tuning knobs, allowing an operator to raise (or lower) the limits based on the circumstances.

The following have some useful background reading on the topic:
- prior analysis of backpresure in Pebble: cockroachdb/pebble#7
- [write throttling in RocksDB](https://github.com/cockroachdb/pebble/blob/master/docs/rocksdb.md#write-throttling)

Jira issue: CRDB-15710

**Comment by tbg** [comment]
Have we considered being more targeted and failing/pausing liveness heartbeats under these stop conditions? We already do this:

https://github.com/cockroachdb/cockroach/blob/0b7ba562c604d69ed048d86445ba0f27498982cb/pkg/kv/kvserver/liveness/liveness.go#L1257-L1265

and could strengthen it by more aggressively skipping heartbeats when pebble indicates overload.

My default opinion is that engine backpressure is not a good idea. It is much more likely than targeted backpressure to have adverse effects across the cluster. For https://github.com/cockroachdb/cockroach/issues/79215, we are also discussing removing below-raft throttling that exists today in favor of better mechanisms.

I understand the desire to have a catch-all "fallback" but is it clear that the resulting behavior is better? We have a history of putting in mitigations that we don't understand well, and would like to make sure we're not repeating that here. Interested in any conversations that I've missed & experiments that were or could be run.

Assuming nodes reliably fail their heartbeats while in an L0-stop regime, the main source of incoming are raft messages (anything else?). I would be open to exploring ways to delay raft handling (dropping incoming messages is the "easiest" thing we could do, with a bit more elbow grease we could probably properly "pause" replication). Or put differently, if we solve the "follower writes" problem and "backpressure" heartbeats, do we have the catch-all that we're after?

**Comment by jbowens** [comment]
I was thinking about our `MaxConcurrentCompactions` limit. The `MaxConcurrentCompactions` limit currently artificially restricts an engine's ability to reshape the LSM to protect foreground traffic. Recent discussions (plus this issue) are about artificially restricting foreground traffic to protect the engine's ability to reshape the LSM. These appear to be at odds.

I think it's premature to consider hard engine-wide limits before we've made `MaxConcurrentCompactions` adaptive and have a better sense of how it performs to avoid LSM inversion. Lifting `MaxConcurrentCompactions` improves the the rate at which the LSM may be reshaped and implicitly backpressures writes through increased WAL write latency if write bandwidth is exhausted.

I know we're already planning on adaptively tuning `MaxConcurrentCompactions` according to resource utilization in 22.2. Instead of a hard engine stop at a certain level of inversion, we could lift `MaxConcurrentCompactions` up to GOMAXPROCS. This would effectively backpressure LSM writes that need to compete with compactions for write bandwidth and CPU. Even this might not be a good idea, because of the effect broad backpressure can have on cluster stability, like @tbg just mentioned.

Linking @sumeerbhola's a lot [more nuanced thinking on the compaction concurrency limits](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1650070297307479?thread_ts=1649887021.271009&cid=C01SRKWGHG8).
