### ISSUE TITLE
cli: tsdump should also create tsdump.gob.yaml

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80478]
**Is your feature request related to a problem? Please describe.**

To use a `tsdump`, one needs an associated node:store mapping (in a yaml file). However, the `tsdump` command does not produce this. With a `debug.zip` we will produce it like this:

```
tail -n +2 debug/crdb_internal.kv_store_status.txt | awk '{print $2 ": " $1}' > tsdump.gob.yaml
```

**Describe the solution you'd like**

Ideally the `tsdump` command creates one automatically by also loading the node:store mapping from the cluster through a status RPC.

**Describe alternatives you've considered**

The command could at least print the following SQL query to make the tsdump file:

https://github.com/cockroachdb/cockroach/blob/dd0bdf3b149dd170599415d64c2ca607294c734e/pkg/cmd/roachtest/cluster.go#L1207-L1237

We could also add a helper script to debug.zip that does the `tail | awk` above as a partial solution (a debug.zip is not always available or can be very large relative to the tsdump).

**Additional context**

Customer support increasingly relies on tsdump and the need to generate and distribute the yaml files tends to cause friction.

cc @rimadeodhar @daniel-crlabs 

Jira issue: CRDB-15595

**Comment by daniel-crlabs** [comment]
Interestingly enough, it's been so long since this request was made I completely forgot about it. I actually got around to make these changes myself and created a PR last week. See below:

[cli: Enable cockroach debug tsdump to automatically create tsdump.yaml #114046](https://github.com/cockroachdb/cockroach/pull/114046)

Once the PR above has been approved and merged this feature should be available.
