### ISSUE TITLE
ALTER ROLE set application_name.... doesn't set the session level parameter

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#80498]
**Describe the solution you'd like**
Currently when I run the following and it completes without error but is a noop:

```sql
> ALTER ROLE foo SET application_name=bar;
> SET ROLE foo;
> show session application_name;
  application_name
--------------------
  $ cockroach sql
```

Would like to have the role setting actually set the session paramater like so...

```sql
> set application_name=bar;
SET

> show session application_name;
  application_name
--------------------
  bar
```

**Describe alternatives you've considered**
Setting at the session level, but this doesn't allow control at the provisioning level.

**Comment by rafiss** [comment]
@glennfawcett `ALTER ROLE foo SET ...` is for setting the **default value** of a session parameter, which applies when initializing a new session. It specifically does not apply with `SET ROLE`, since we implemented this to be compatible with the PostgreSQL semantics: https://www.postgresql.org/docs/current/sql-alterrole.html

> This only happens at login time; executing [SET ROLE](https://www.postgresql.org/docs/current/sql-set-role.html) or [SET SESSION AUTHORIZATION](https://www.postgresql.org/docs/current/sql-set-session-authorization.html) does not cause new configuration values to be set. Settings set for all databases are overridden by database-specific settings attached to a role.

I'm going to close this out, but we can keep discussing here if there needs to be a documentation improvement.
