### ISSUE TITLE
backup: investigate spans merging behavior with larger span counts

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#80697]
A cluster was observed spending hours in backup planning before eventually failing after ~100 retries. At the time the cluster was observed, the current attempts were all working on computing the merged span coverage, i.e. in SpansForAllIndexes.

The cluster had approximately 800 tables and had truncated two of them approximately 3000 times in hours prior to the incremental revision history backup; with one of those tables having 5 indexes a back of envelope guess on the minimum  number of spans in question, assuming the other 700 tables had on average two indexes, is around 16k. It is possible this was leading to some sort of degenerate performance of the span accumulation/merging function.

We should test, and then potentially optimize, spansForAllIndexes in such cases (e.g. 10k+ spans)

Jira issue: CRDB-15546

**Comment by stevendanna** [comment]
I've made some progress on this in https://github.com/cockroachdb/cockroach/pull/81743 and https://github.com/cockroachdb/cockroach/pull/81754 but I think we'll need some real-world tests rather than microbenchmarks to see if those two fixes solve the problem.  

I'm a little skeptical that those changes alone will fix the real-world use case because in the microbenchmarks, even before the fix, spansForAllIndexes was able to complete deal with 15000 spans in a running time on the order of seconds.
