### ISSUE TITLE
kvserver: persistent outage when liveness leaseholder deadlocks

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80713]
**Describe the problem**

See https://github.com/cockroachdb/cockroach/pull/79648.

Quoting an internal support issue:

> RCA: n1 experienced a disk stall. It held the lease for the liveness range r2, and this information was cached by all nodes. When n1 locked up, all liveness requests continued to get redirected to n1. Since all of these requests had a timeout on them, they returned from DistSender.Send. This did not invalidate the cached leaseholder entry, thus rendering this outage permanent. It is likely that the liveness range wasn't technically unavailable, if only nodes had figured out to talk to the new leaseholder.

**To Reproduce**

See above PR (note that second commit has a hacky fix so to get a repro, remove that)

**Expected behavior**

Failover as usual

**Additional data / screenshots**
**Environment:**
- master at time of writing and all past versions presumably

**Additional context**

Persistent total cluster outage since all nodes failed heartbeats.
Resolved only when deadlocked node was brought down.

Jira issue: CRDB-15539

gz#13737

Epic CRDB-19227

gz#19526

**Comment by tbg** [comment]
What's interesting is that we do have a disk stall roachtest but it didn't catch it: https://github.com/cockroachdb/cockroach/blob/21a286f2b2978b1cc117596865cd680dd268cf74/pkg/cmd/roachtest/tests/disk_stall.go#L1-L139

**Comment by erikgrinaker** [comment]
This seems closely related to #81100, so I'll pick this one up while I'm at it.

**Comment by erikgrinaker** [comment]
Took a first stab at this over in #81137, where DistSender will prioritize available nodes over unavailable ones (since the liveness leaseholder would become unavailable when the disk stalls). However, this has a bunch of issues -- not least that when the liveness leaseholder goes down then _all_ nodes will be considered unavailable, and so it can still get stuck on the old leaseholder anyway if it's sorted first (e.g. by latency).

I think this issue points towards a more fundamental flaw in the whole model we use around lease acquisition, in that we rely on KV clients to detect failed leaseholders and contact new candidates to trigger lease acquisitions. If the clients fail to do either of these two tasks then leases won't move.

Some other random ideas:

* Tag the contexts of internal operations like heartbeats, lease acquisition, and range descriptor lookup. If these contexts time out, invalidate the lease cache. However, it's easy to fail to tag relevant operations, and we'll have to avoid hitting the old leaseholder again on the next attempt.

* Have the server-side RPC stack reject requests when the node fails liveness. However, this requires active cooperation from the server, and won't handle e.g. deadlocks or network outages (black holes).

* Have the distsender track error statistics for replicas and prioritize more functional ones. However, in this case we'd have to include context cancellation errors, so if a bunch of clients disconnect it can severely disrupt performance.

* Pick random replicas when the cached lease is considered invalid. However, this could cause poor tail latencies, since in many cases it would be more efficient to contact the previous leaseholder.

Thoughts or ideas?

**Comment by joshimhoff** [comment]
Looking for something to play with over breather week. Maybe it's this one?

In https://github.com/cockroachdb/cockroach/issues/81100#issuecomment-1131388179, @erikgrinaker says:

> Additionally, system ranges may not recover at all because the RPC caller may time out before the NLHE is returned, preventing anyone else from acquiring the lease (https://github.com/cockroachdb/cockroach/issues/80713)., 

To me, this suggests a slightly different understanding of the outage than what @tbg said in this ticket:

> It is likely that the liveness range wasn't technically unavailable, if only nodes had figured out to talk to the new leaseholder.

Which is right? Was there a new available leaseholder or was there not a new available leaseholder, since no kvclient poked a functional kvserver triggering it to acquire the lease, since the NLHE was never returned? Erik's theory makes concrete sense to me FWIW.

> Some other random ideas:

I like all these ideas.

I have a weird related idea:

- Make batch a streaming RPC.
- Server returns "I'm leaseholder" then actually evaluates the batch and returns any results
- If no "I'm leaseholder" in CRDB-eng-controlled timeout seconds (N=2s), then client invalidate cache + tries a different replica

Then no need for NLHE.

At some level, the problem to me is that we require the kvserver to send a NLHE (as the kvserver may be non-functional), not that we require a kvclient to send a message to kvserver in order to kick off a lease acquisition attempt.

I sort of wonder if the cost of sending back a "I'm a leaseholder" message on every RPC to kvserver is too high to stomach? But IDK; perf stuff like this is hard for me to judge. I thought I'd share the idea anyway.

**Comment by erikgrinaker** [comment]
> Which is right? Was there a new available leaseholder or was there not a new available leaseholder, since no kvclient poked a functional kvserver triggering it to acquire the lease, since the NLHE was never returned? Erik's theory makes concrete sense to me FWIW.

Most likely there was no other leaseholder, since we've found that nodes will keep retrying the previous leaseholder until they get a response. Unless someone else happened to send a request to a different replica, for some reason. Can probably find out by digging through the debug.zip. The no-leaseholder scenario will need a solution in any case, which I suspect will indirectly solve the other-leaseholder scenario.

> > Some other random ideas:
> 
> I like all these ideas.

Meh. I don't think any of them are particularly good, but given the current state this is what I could come up with for short/medium-term fixes. What I'd ideally want here is for replicas to sort out the lease even in the absence of client requests, similarly to how vanilla Raft will transfer leadership even if there are no proposals.

> I have a weird related idea:
> 
> * Make batch a streaming RPC.
> * Server returns "I'm leaseholder" then actually evaluates the batch and returns any results
> * If no "I'm leaseholder" in CRDB-eng-controlled timeout seconds (N=2s), then client invalidate cache + tries a different replica
> 
> Then no need for NLHE.

We sort of have this channel already, in the RPC heartbeats. But it doesn't carry lease information currently.

> At some level, is the problem that we require the kvserver to send a NLHE (as the kvserver may be non-functional), not that we require a kvclient to send a message to kvserver in order to kick off a lease acquisition attempt?

I think both. Ideally, we'd want replicas to sort out the lease between themselves, and for clients to efficiently discover lease changes. These concerns are currently conflated, but they're really separate concerns.

> I sort of wonder if the cost of sending back a "I'm a leaseholder" message on every RPC to kvserver is too high to stomach? But IDK; perf stuff like this is hard for me to judge. I thought I'd share the idea anyway.

Been a while since I looked at RPC heartbeats, but piggybacking on them might be viable. I think doing it per-batch would possibly be too expensive, and it's unclear whether it'd be better than an aggregate signal. We could e.g. send a sparse bitmap of ranges that we're actively asserting leases for, or something. This would have to integrate with quiescence somehow.

**Comment by joshimhoff** [comment]
All makes sense! Good point re: aggregate signal maybe being just as good.

**Comment by tbg** [comment]
> Most likely there was no other leaseholder, since we've found that nodes will keep retrying the previous leaseholder until they get a response. Unless someone else happened to send a request to a different replica, for some reason. Can probably find out by digging through the debug.zip, don't remember the details of the original incident. The no-leaseholder scenario will need a solution in any case, which I suspect will indirectly solve the other-leaseholder scenario.

There may not have been here, but it looks like https://github.com/cockroachlabs/support/issues/1808 is a possible other instance of the same problem. Here, it looks as though only n5 didn't manage to update its cache; other nodes seem to be reaching liveness OK.

But as Erik pointed out, solving one solves the other - the issue is that we can't rely on "proactive" invalidation of a cached leaseholder.
