### ISSUE TITLE
monitoring: export rpc metrics

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8093]
Per-family/method client/server rpc counts and error counts. Probably latencies as well.

**Comment by petermattis** [comment]
@mberhault Are we going to get to this for 1.0?

**Comment by mberhault** [comment]
bumping to 1.1.

**Comment by arjunravinarayan** [comment]
@mberhault Is this relevant any more? Our various methods for tracing through clusters have radically improved in the 1.5 years since this issue was created. We generally have tremendous visibility into internal layers.

In any case, I'm for at least bumping the milestone to "Later", rather than revisiting this every 6 months.

**Comment by mberhault** [comment]
Closing in favor of #5237 (higher-level tracking).
