### ISSUE TITLE
Remove admin requirement for hot ranges in dbconsole

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#81294]
**Is your feature request related to a problem? Please describe.**
Our users would love to use the new hot ranges ui, however we can't give them admin. Please put the functionality behind an assignable role. 

**Describe the solution you'd like**
Make the hot ranges ui available via an assignable role.

**Describe alternatives you've considered**
Giving admin access, which is untenable. 

gz#12357

Jira issue: CRDB-15248

**Comment by thtruo** [comment]
Hey @data-matt we introduced a change in https://github.com/cockroachdb/cockroach/issues/79953 where we gate access to the Hot Ranges UI through the `VIEWACTIVITY` role option. As Kevin alluded to, once the new privilege framework is introduced, we'll have a better fine-grained authz model. But until then, non-admins can access Hot Ranges with `VIEWACTIVITY`

This change was backported to 22.1.x and 21.2.x; I presume we'll want the same for 21.1.x so we'll put in a request to get that done. 

In the meantime, I propose we close this issue since it's already been addressed in #79953. Lmk if you have any objections to that Matt.

**Comment by data-matt** [comment]
Please close :)
