### ISSUE TITLE
cli: provide a command to pre-hash passwords

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#81324]
Requested by @MichaelTrestman and @bdarnell : instead of only explaining to users how to use a 3rd-party library, we should also provide a "canonical" implementation of client-side password hashing.

Something like `cockroach encode-password <method>`

that takes the password on stdin and prints out the hash on stdout.

Jira issue: CRDB-15241

**Comment by rafiss** [comment]
Perhaps it would work as a metacommand, like `\encode_password` or something. It would be a bit easier to implement, and it could easily use the logic that we added for the `\password` command. It's a bit more flexible, since you can still use it from the top level shell with something like `./cockroach sql -e '\encode_password method the_password'`

**Comment by knz** [comment]
that's clever! it would also work with `cockroach-sql` which we now ship standalone.

One thing that's important though is that the input is read from stdin (either via the silent password prompt or straight up stdin, depending on whether the shell is interactive). It should not be passed as an argument. This ensures the password does not show in the output of `ps`.
