### ISSUE TITLE
bazel: pre-built c-deps have sporadic jemalloc failures on Mac M1

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#81581]
```
cockroach$ for i in $(seq 0 100); do ./cockroach version | grep jemalloc; done
<jemalloc>: Error in munmap(): Invalid argument
<jemalloc>: Error in munmap(): Invalid argument
<jemalloc>: Error in munmap(): Invalid argument
```

Epic CRDB-8036

Jira issue: CRDB-15089

**Comment by tbg** [comment]
One negative effect is that this fails roachtest runs (in --local mode) when it happens there, since we parse the output of `./cockroach version`. Other than that, it hasn't been bothering me.

Wanted to mention the workaround @rickystewart mentioned on [slack](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1653060462685159) here as well:

```
# .bazelrc.user
build --config force_build_cdeps
```
