### ISSUE TITLE
kv: unnecessary allocations for result.Rows?

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#81600]
When sending batches for mutation KV requests (CPut, Put, InitPut), the `Batch.initResult` code is invoked with `numRows=1`, which causes the code to reserve slice space for the `result.Rows` slice for each request.

However, as far as I can tell, it's unnecessary to do this, because the result rows are populated with the exact same slice as the requests - the key and value is simply passed from the arguments to the mutation command.

This causes material extra work, and seems unnecessary. I think it can be removed, but I'm not sure - what am I missing?

Jira issue: CRDB-15965

**Comment by nvanbenschoten** [comment]
I don't think you're missing anything — the allocations are an unfortunate artifact of trying to present a clean, uniform library interface. However, in practice I don't think anyone uses `kv.Result.Rows` for mutations, so the associated heap allocations seem difficult to justify.

I don't think we see this as an issue in practice because there is a fast-path that avoids any unnecessary heap allocations for small enough (<= 8 requests) batches:
https://github.com/cockroachdb/cockroach/blob/635792ce48fce393b9b2492cbfabbed3897b5ce7/pkg/kv/batch.go#L67-L71

One easy solution here would be to move `rowsStaticBuf [8]KeyValue` into the `Result` struct as `rowsStaticBuf [1]KeyValue`. Doing so would mean that we still avoid all heap allocations for small batches, but also that once we use up the preallocated `resultsBuf    [8]Result`, we piggyback the `[]KeyValue` allocation for single-key requests on the `Result` allocation.

Which microbenchmark did you see this in? Something in `pkg/sql/tests` that uses larger batch sizes?
