### ISSUE TITLE
backupccl/importer: flush all job progress before pausing bulk job

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#81671]
Currently, bulk jobs (BACKUP / RESTORE / IMPORT) conduct wasted work after getting paused if the job record isn't up to date on what spans have been ingested/exported. To avoid the wasted work, bulk jobs should implement `OnPauseRequest` and force the coordinator node to get updates from worker nodes and flush all progress to the job record. This could address the perf regression observed at https://github.com/cockroachdb/cockroach/issues/81116#issuecomment-1134684294. Down the line, progress should be synced after a graceful node shutdown as well (e.g. https://github.com/cockroachdb/cockroach/issues/50732).

Jira issue: CRDB-16020

**Comment by dt** [comment]
Hm. So we decided _not_ to do this initially since the amount of wasted work _should_ be minor; if it isn't, then an unexpected resumption, such as after a node failure (which is something we should expect all the time in large enough clusters) would end up losing that non-minor amount of work too. As a rule of thumb, we generally expect no more than 30-1min or so of work that hasn't been checkpointed, and that is _probably_ okay to lose on pause. Sure, we _could_ try to avoid losing it, and doing so could make things like dynamic replanning due to cluster changes cheaper, but if we're seeing really large amounts of lost work, that suggests our existing checkpointing isn't performing as expected
