### ISSUE TITLE
sql: Observability improvements meta issue for TTL deletions jobs

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#81905]
- [ ] Include SQL statements in Jobs details page for select and delete queries. See [previous comment](https://github.com/cockroachdb/cockroach/issues/79916#issuecomment-1098542735) but unclear why #79547 impacts what displays for Jobs detail
![image](https://user-images.githubusercontent.com/13694532/170501678-89c10e09-97b2-4e84-8349-5ad67dad5ef8.png)

Jira issue: CRDB-16123
Epic CRDB-14592

**Comment by rafiss** [comment]
@vy-ton we can't include the exact queries in the job description, since the job runs many different queries as it iterates through the rows to be deleted. but, we can show the query templates with something like this

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/1320573/186505627-e388a819-e149-46fa-af30-af3fedd3f814.png">

**Comment by rafiss** [comment]
@vy could you look at the description of https://github.com/cockroachdb/cockroach/pull/86801 and confirm if that is an acceptable solution.

**Comment by vy-ton** [comment]
@rafiss this looks great! Could we make the `<x>` correspond to the TTL setting names?

**Comment by rafiss** [comment]
sure, good idea
