### ISSUE TITLE
Increment op should be non-txn and store an inline value

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#821]
I propose we change how the Increment command stores values. It's currently storing them MVCC, but I'm thinking that Increment will be used chiefly for id allocation and will therefore be inefficient storing historical values via MVCC.

@petermattis @bdarnell @tschottdorf Thoughts?

**Comment by petermattis** [comment]
As discussed in person: what happens if user does `Put("a", "b")`, `Delete("a")`, `Increment("a")`. Will everything work correctly with reading the historical value after the `Increment` occurs?

**Comment by bdarnell** [comment]
I'm thinking that increment will be primarily used for tracking stats that must be kept in sync with other actions (e.g. the "like" count on a photo), so they need to be transactional (I think in most cases I'd use UUIDs for ID generation instead of calling out to a sequential generator). If we want a non-transactional ID allocator we should introduce a new method for it instead of modifying Increment.

**Comment by spencerkimball** [comment]
hmm, good points.
