### ISSUE TITLE
kvserver: include range keys in Raft snapshots

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#82591]
We need to include range keys in Raft snapshots. This involves e.g. supporting them in `ReplicaEngineDataIterator`, supporting them in `kvBatchSnapshotStrategy` (and its snapshot protocol), and ingesting them in `Replica.applySnapshot()`.

Jira issue: CRDB-16531

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
@sumeerbhola Raft snapshots use an `EngineIterator` to read data:

https://github.com/cockroachdb/cockroach/blob/aac9c44d1284fa93877815f61527a76e110dbda5/pkg/kv/kvserver/replica_raftstorage.go#L606

I see you have a `TODO` there to replace `ReplicaMVCCDataIterator` (currently unused for snapshots) with `ReplicaEngineDataIterator`.

We'll have to include range keys in Raft snapshots. Would you prefer exposing range keys via `EngineIterator` too, or move back to using `ReplicaMVCCDataIterator` for MVCC data?

**Comment by sumeerbhola** [comment]
Can you elaborate on the desired behavior for the range key and point iteration: I assume we want them interleaved in some manner since we want to produce non-overlapping sstables for ingestion. However, I am not clear on how the MVCCIterator interface will help us in de-duplicating range keys, without doing comparisons to see if the range-keys changed.

Given that the receiver writes exactly 1 sstable for the the user key span, the sender could iterate over the user key span first using a point iter (with an EngineIterator) and then using a range-key-only iterator (`IterKeyTypeRangesOnly`) and send. The receiver would combine all these batches into the same sstable.

Regarding EngineIterator vs MVCCIterator, the intention at the time the TODO was written was to move to a more universally applicable iterator. I think that this is still true, so I am ok with exposing range keys via `EngineIterator`.

**Comment by erikgrinaker** [comment]
>Can you elaborate on the desired behavior for the range key and point iteration: I assume we want them interleaved in some manner since we want to produce non-overlapping sstables for ingestion. However, I am not clear on how the MVCCIterator interface will help us in de-duplicating range keys, without doing comparisons to see if the range-keys changed.

This has actually come up in a bunch of different contexts, e.g. rangefeed catchup scans, backup/export, etc. We often find ourselves having to constantly do comparisons to figure out if the range keys changed, which is expensive. Pebble has already done this comparison while interleaving, so it could expose an API to detect these changes during iteration -- e.g. `RangeKeysChanged()`. Brought it up with @jbowens over in https://github.com/cockroachdb/cockroach/pull/82691#pullrequestreview-1003068096.

>Given that the receiver writes exactly 1 sstable for the the user key span, the sender could iterate over the user key span first using a point iter (with an EngineIterator) and then using a range-key-only iterator (IterKeyTypeRangesOnly) and send. The receiver would combine all these batches into the same sstable.

Good point, for Raft snapshots we could do this. However, this also came up in the context of export/backup, where we wanted to keep range keys interleaved in the same SSTs as point keys, so we'll need this sort of API for the standard `MVCCIterator` anyway.

>Regarding EngineIterator vs MVCCIterator, the intention at the time the TODO was written was to move to a more universally applicable iterator. I think that this is still true, so I am ok with exposing range keys via EngineIterator.

Yeah, I think I'd agree with this. I'll expose range keys via EngineIterator too, as an engine variant of `RangeKey`.
