### ISSUE TITLE
changefeedccl: Monitoring metrics for PTS

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#82825]
Add monitoring metrics for protected timestamp management; simple counters will suffice.
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeed_processors.go#L1270

In addition, changefeed status should expose the age of the protected timestamp record both in the job status and as a metric..

Jira issue: CRDB-16687

Epic CRDB-20422

**Comment by surahman** [comment]
I am trying to figure out how to add these metrics. The following lines seem to configure the metrics structs to populate:
https://github.com/cockroachdb/cockroach/blob/448bba153720c59958a246da2d2a9a2ff7d73f10/pkg/ccl/changefeedccl/changefeed_processors.go#L251-L252

Do you want to extend the `metrics` struct here:
https://github.com/cockroachdb/cockroach/blob/448bba153720c59958a246da2d2a9a2ff7d73f10/pkg/ccl/changefeedccl/metrics.go#L493-L511
With metrics for the `age` and `status` of the protected timestamp?

This issue seems like it requires a bit more depth with CRDB.

**Comment by miretskiy** [comment]
Thank you @surahman  for contributing.
Yes, my initial thinking was to add simple metrics.  The metric would probably be similar to 
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/metrics.go#L510-L510

we would track how much PTS record is behind; .. .

But  perhaps even more useful would be produce more information when displaying
changefeed status.  Display the age of PTS record when executing `show changefeed job XXX`.
To do that, you'd need to change scary looking query in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/delegate/show_changefeed_jobs.go#L26-L26

**Comment by surahman** [comment]
> Thank you @surahman for contributing.

I am happy to get involved. It is a great way to learn new things and sharpen my skillset.

>Yes, my initial thinking was to add simple metrics. The metric would probably be similar to https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/metrics.go#L510-L510
> 
> we would track how much PTS record is behind; .. .

We would need to set up the gauge similarly to this:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/ccl/changefeedccl/metrics.go#L510-L510
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/ccl/changefeedccl/metrics.go#L538
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/ccl/changefeedccl/metrics.go#L312-L316

I would need to calculate the age since the last protected timestamp and figure out how to update the gauge metric.

> But perhaps even more useful would be produce more information when displaying changefeed status. Display the age of PTS record when executing `show changefeed job XXX`. To do that, you'd need to change scary looking query in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/delegate/show_changefeed_jobs.go#L26-L26

It was a bit intimidating at first glance. From my understanding, the query is gathering data from one of the database catalogue tables.
This sets up a view aliased as `payload` to `join` against:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/sql/delegate/show_changefeed_jobs.go#L28-L37

Columns pulled directly from the table:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/sql/delegate/show_changefeed_jobs.go#L39-L49
Column pulled as test and aliased as `sink_uri`:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/sql/delegate/show_changefeed_jobs.go#L50-L53
Column created as an ARRAY from a `concat` on the table and aliased as `full_table_names`:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/sql/delegate/show_changefeed_jobs.go#L54-L64
Columns loaded as text an aliased as `topics` and `format`:
https://github.com/cockroachdb/cockroach/blob/7d9562d5006981401d95f3893e1e90b8127185c9/pkg/sql/delegate/show_changefeed_jobs.go#L65-L66
If we create and expose a new column which has the age of the PTS in nanoseconds we could update the query by adding the column name somewhere in lines 39-49.

**Comment by surahman** [comment]
I have taken a quick stab at the problem. I am not sure if the protected timestamp for the change feed needs a mutex as it is only updated from on routine. I was not able to find any concurrent calls to the method `manageProtectedTimestamps`.

The remaining work is with the SQL statement. I was unable to locate where the data in the protocol buffer for `cockroach.sql.jobs.jobspb.Payload` is being written.

**Comment by miretskiy** [comment]
We recently added metrics to PTS subsystem.
