### ISSUE TITLE
How to configure column ON UPDATE with Entity Framework

### ISSUE THREAD

**Issue by AlexGivt** [cockroachdb/cockroach#82979]
**Problem**
Cannot configure "ON UPDATE" on a column using EntityFramework

**Description**
I need to support optimistic locking, and thought I could implement that with a TIMESTAMP/TIMESTAMPTZ column like this:
`"ConcurrencyToken" TIMESTAMP DEFAULT now() ON UPDATE now()`

This works, the database provides a new value after every write and should work for my needs

My configuration:
```
builder
    .Property(e => e.ConcurrencyToken)
    .HasColumnType("TIMESTAMPTZ")
    .HasDefaultValueSql("now() ON UPDATE now()") // gets wrapped in ( )
    .IsConcurrencyToken();
```

This produces:
```
"ConcurrencyToken" TIMESTAMP NOT NULL DEFAULT (now() ON UPDATE now()),
```

Nearly there, except for the excess parentheses ( and ). So what I need is either no parentheses, or an .HasUpdateValueSQL() extension to configure that, or something else? How to configure this?
**Thanks for any pointers/solutions!**

regards,
Alex

Jira issue: CRDB-16770

**Comment by rafiss** [comment]
Thanks for the issue! 

The ON UPDATE syntax is unique to Cockroach, so in order to have first-class support for it in the tool, EntityFramework would need to add a new interface analogous to `HasDefaultValueSql`. I think this issue should be tracked on the EntityFramework project. Currently, EntityFramework doesn't have full support for Cockroach (though it mostly works just by using the Postgres dialect), so anything CRDB-specific like this may not get prioritized.
