### ISSUE TITLE
Question about column families

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#8301]
I read that if you want something like a key value store you should use column families.
I would like to know if there is a difference if you use a table with 1 primary key and only one other column or a table with 1 primary key and several other columns. I think if there is only one other column it should be very easy to store this value in RocksDB.
Wouldn't it be possible to store also a STRING column with no length limit under the same column family as long as there is only 1 other primary key column?

**Comment by knz** [comment]
Hi, thanks for your question. The answer is that from the storage perspective it is nearly as efficient to use either one or more columns to store the same amount of data, as long as they are part of the same column family. This is because the data for the multiple columns will be concatenated as a single value for a K/V pair.

The primary key decides the K part, the non-primary columns form the V part of a K/V pair.

So indeed the simplest K/V store in CockroachDB is a table with one primary key and one non-primary column.

A STRING column in CockroachDB does not have a fixed size. 

We have some technical limits related to performance due to our consistency protocol and the underlying RocksDB however we don't have hard numbers yet. In practice you usually can use a couple hundred kilobytes per string safely. Some users report success with much larger values (megabytes) but we do not recommend this for performance due to data amplification during queries. A size greater than a few tens of megabytes per value almost surely doesn't work.

Also in the future do not hesitate to ask our question on our new forum: https://forum.cockroachlabs.com/

**Comment by knz** [comment]
I will close this GitHub issue for now since your questions are not invitations to change our product. Feel free to follow up on the discussion on the forum linked above. Thanks!

**Comment by RaduBerinde** [comment]
@paperstreet is the column family expert. I believe it is possible to store a STRING column in the same column family with other columns, it just has to be explicitly stated when creating the table.

**Comment by WhiteTrashLord** [comment]
Thanks for the fast answers. Maybe it would make sense to change the default behaviour for column families to use only one family under these conditions:

1) A STRING without length limit, DECIMAL without precision or BYTES column is the only other column
2) There is only one column with an unknown length and it is the last column in the table. If it is the last column maybe it doesn't matter if the size is unknown?

From what I currently understand is that you can overwrite the default behaviour. But I think it would be better to make it as best as possible by default because many developers probably don't know the concept of column families.

**Comment by RaduBerinde** [comment]
The default behavior puts any column of variable size (what you listed under 1) in its own single-column "family". It only creates multi-column families for columns, and it uses some heuristics to decide how many.
Feel free to jump on our gitter channel if you want to have a conversation around this.
