### ISSUE TITLE
storage: optimize new SST iterators

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#83051]
The new SST iterators in https://github.com/cockroachdb/cockroach/pull/82799, e.g. `NewPebbleSSTMemIterator()`, are much slower than the existing `NewMemSSTIterator()`, around 80% or so. Some of this is due to CRDB-side overhead, in particular the use of `pebbleIterator` and `VerifyingMVCCIterator`, but the majority appears to be in Pebble via the new `NewExternalIter()` SST iterator. We need to optimize these.

This can be seen with `BenchmarkSSTIterator`, by changing `NewMemSSTIterator()` to `NewPebbleMemSSTIterator()` in `runSSTIterator()` on top of #82799.

Many of the optimizations that address #82559 and #83049 would likely apply here as well.

Jira issue: CRDB-16822

Epic CRDB-2624

**Comment by jbowens** [comment]
I expect most of the slowdown comes from the fact that the Pebble iterator resolves duplicates. This requires copying every key-value pair and an extra key comparison.

**Comment by erikgrinaker** [comment]
Oof, yeah, that isn't great. The probability of duplicates is very low though, I wonder if we could do something cheaper and then backtrack if we find a possible match.

**Comment by jbowens** [comment]
@msbutler what structure do we have in the backups? Is it correct that we within each individual full backup and each individual backup we have an ordered series of nonoverlapping files? I think we should also be able to refactor the interface so that we can propagate this information to the Pebble iterator, and it can create num-backups levels in the merging iterator instead of num-files levels.

**Comment by msbutler** [comment]
The set of files produced by an individual backup may have overlapping key spans, however there will never be overlapping keys across files (i.e. if a@2 is in file foo, then a@anyTimestamp will be in file foo).

**Comment by jbowens** [comment]
I think we'll want to change the interface to accept a `[][]sstable.ReadableFile`, where each subslice must not contain overlapping _point_ keys.

This will allow us to organize each backup into its own 'level', by implementing a simple level iterator that chains all the internal point key iterators within a backup. There's a bit of a complication that `pebble.Iterator` supports seeking, but we don't the bounds of these files. We don't require seeking for this use case, but it's a poor UX to expose a `*pebble.Iterator` that's only intended for forward scans. I think we could support seeking without too much work by binary searching among the level's files, `First()`-ing each to retrieve its smallest point key for comparison.

@nicktrav — did you want to pick this up after the min-table version work, or something else?

**Comment by msbutler** [comment]
@stevendanna I just thought of one wrinkle to my answer to Jackson's question[ above](https://github.com/cockroachdb/cockroach/issues/83051#issuecomment-1201649034). Could you verify this? If the backup retries, we might write several SSTs that contain the same key, however, only one of those SST's will ever get check pointed. So, from RESTORE's perspective, this still holds:
>The set of files produced by an individual backup may have overlapping key spans, however there will never be overlapping keys across files (i.e. if a@2 is in file foo, then a@anyTimestamp will be in file foo).

**Comment by nicktrav** [comment]
> @nicktrav — did you want to pick this up after the min-table version work, or something else?

SGTM.

**Comment by itsbilal** [comment]
@jbowens Just to clarify, we'd still need the pausing behaviour for the simpler point-key levelIter right (i.e. the one that operates on observed file bounds and not `FileMetadata` and only needs to support forward iteration)? Since we could still have range deletes in one fake level that apply to points in another level.

Also on that note, we'd need a similar simpler levelIter for range keys, right? Or is it sufficient to still expose all the range key iterators to its merging iter, with the hope that there aren't many files with range keys?

**Comment by jbowens** [comment]
> Just to clarify, we'd still need the pausing behaviour for the simpler point-key levelIter right (i.e. the one that operates on observed file bounds and not FileMetadata and only needs to support forward iteration)? Since we could still have range deletes in one fake level that apply to points in another level.

Yeah, I guess so. It's not needed for the intended use case of backups, but we should try to keep NewExternalIter very general, even if some of our optimizations are not general.

> Also on that note, we'd need a similar simpler levelIter for range keys, right? Or is it sufficient to still expose all the range key iterators to its merging iter, with the hope that there aren't many files with range keys?

I think that's sufficient since range keys should be relatively rare, and I _think_ range keys are allowed to overlap between backup files from the same backup.

**Comment by erikgrinaker** [comment]
Recent benchmarks comparing the old `sstIterator` vs. the new `pebbleIterator` based one:

```
name                                      old time/op  new time/op  delta
SSTIterator/X/keys=1/verify=false-24      39.8µs ± 1%  45.5µs ± 4%  +14.35%  (p=0.000 n=9+10)
SSTIterator/X/keys=1/verify=true-24       39.8µs ± 1%  44.1µs ± 4%  +10.68%  (p=0.000 n=9+10)
SSTIterator/X/keys=100/verify=false-24    47.8µs ± 0%  57.1µs ± 1%  +19.56%  (p=0.000 n=8+10)
SSTIterator/X/keys=100/verify=true-24     50.3µs ± 1%  61.9µs ± 1%  +22.97%  (p=0.000 n=9+10)
SSTIterator/X/keys=10000/verify=false-24   850µs ± 0%  1498µs ± 1%  +76.28%  (p=0.000 n=8+9)
SSTIterator/X/keys=10000/verify=true-24   1.07ms ± 1%  1.92ms ± 0%  +80.40%  (p=0.000 n=10+9)
```
