### ISSUE TITLE
sql: vectorized engine incorrectly casts UUID to bytes when concatenating with a string

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#83093]
Consider the following difference between the vectorized engine and the row engine:
```
demo@127.0.0.1:26257/defaultdb> create table t (u uuid);
CREATE TABLE


Time: 5ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> insert into t values ('eb64afe6-ade7-40ce-8352-4bb5eec39075');
INSERT 0 1


Time: 5ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select u || 'a' from t;
                     ?column?
--------------------------------------------------
  \xebd\xaf\xe6\xad\xe7@\u0383RK\xb5\xee\u00d0ua
(1 row)


Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> set vectorize = off;
SET


Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select u || 'a' from t;
                ?column?
-----------------------------------------
  eb64afe6-ade7-40ce-8352-4bb5eec39075a
(1 row)
```
The result with `vectorize=off` is what is also returned by Postgres.

Jira issue: CRDB-16859

**Comment by cucaroach** [comment]
Is the problem we shouldn’t be treating a UUID as a BytesFamily type or is the problem we’re not correctly converting the result bytes back into a string?    It seems logical so treat a UUID as a bytes and do concat bytes wise but maybe the plan is just missing a conversion operator of the bytes back into string, here's the plan:

```
demo@127.0.0.1:26257/defaultdb> explain (vec, verbose) select u || 'a' from t;
                          info
---------------------------------------------------------
  │
  └ Node 1
    └ *colflow.BatchFlowCoordinator
      └ *colexecbase.simpleProjectOp
        └ *colexecprojconst.projConcatBytesBytesConstOp
          └ *colexecutils.vectorTypeEnforcer
            └ *colexecutils.CancelChecker
              └ *colfetcher.ColBatchScan
(8 rows)


Time: 1ms total (execution 1ms / network 0ms)
```

**Comment by yuzefovich** [comment]
I think that the problem is that we don't plan the cast of UUID to string before evaluating the Concat operation in the vectorized engine like we [do](https://github.com/cockroachdb/cockroach/blob/fd335c714958ba99d5446a72efdeab599df96154/pkg/sql/sem/eval/binary_op.go#L209) in the row-by-row engine. I looked at the history, and I think the divergence was introduced in #65019 where we only fixed the bug in the row-by-row engine. It would be good to understand why `TestEval/vectorized` in `pkg/sql/sem/eval/eval_test/eval_test.go` doesn't fail for `concat` file (modified in #65019) - my guess is that the string representation just happens to be the same as the bytes representation of `true` and `false` values which is not true for UUIDs.

**Comment by yuzefovich** [comment]
When chatting with Tommy, we realized that only concatenation of a UUID with a STRING is affected - most non-string / string concatenations currently fallback to the row-by-row engine because we haven't defined the corresponding Concat overloads. #85150 will improve that.
