### ISSUE TITLE
sql: introduce a client.Batch wrapper with --vmodule logging of every operation

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#8324]
See the TODO at https://github.com/cockroachdb/cockroach/blob/b4c0d08859ff5f094ab5701c3bc6dfaa0b384368/sql/rowwriter.go#L192

If it gets put in a common location and gets some other uses, we need to remain able to turn it on for only sql. That's been really helpful in developing sql features. I think log.VDepth can be used for that

**Comment by a6802739** [comment]
@paperstreet, you mean when it's sql operation,we should put put `log.V(2)` in `client.Batch`?

**Comment by paperstreet** [comment]
@a6802739, sorry for the delay, I was away when you posted this.

One option is to add the logging directly in `client.Batch` and similarly `client.Txn` and `client.DB`. That's probably the best option if we can convince ourselves that the performance impact of the check is negligible when it is turned off (so the production case). @tamird do you have a gut feeling on whether this is workable?

Otherwise, the original TODO is phrased more in terms of moving the rowwriter.go code to take a new interface and passing in a `LoggingBatch` wrapper.

**Comment by tamird** [comment]
It's probably workable, but we'll want to pass a context so it may be
easier to limit this change to sql for now.

**Comment by RaduBerinde** [comment]
I commented in #9169. I think it may be much easier to simply log the batch when we run it (in `client.Txn.Run`) than to try to log when we construct it.

**Comment by knz** [comment]
This has been replaced by a different approach in SHOW KV TRACE FOR.
