### ISSUE TITLE
storage: new Raft leader not detected

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8344]
See #8176. The general scenario is to kill a node, leave it down for ~30s and then bring it back up. When the node comes back up, we very frequently try to request the lease for range 1 (the details of why aren't super important here). When the Raft group for range 1 is initialized by this restarted node it starts as a follower who doesn't know who the leader is. If the range lease request snuck in before we hear from the leader it will be dropped. This is fine. What isn't fine is that we don't refurbish or repropose this dropped command. As far as I can tell, we never notice that there is a new leader. `Replica.handleRaftReady` is supposed to receive an Raft entry with an empty Data, but that doesn't seem to be happening. I only see the empty Data entries when a config change is performed.

I haven't been able to track down where these empty Data entries are generated. Regardless, this mechanism seems subtle. The Raft leader for a replica is updated about reception and processing of a message (via `raft.RawNode.Step`). A proof of concept shows that we can watch for leader changes after `Step` is called and refresh pending commands. 

@bdarnell Thoughts?

**Comment by bdarnell** [comment]
Empty entries are generated when a new raft leader is *elected*. We're missing the case in which we learn about the new leader through means other than advancing through the log. I think the only other way is when we apply a snapshot, so we should repropose after doing that. 

We could also watch for SoftState.Lead changes in handleRaftReady, but that couldn't replace reproposals on empty entries because proposals could have been dropped even if the previous leader was reelected.

**Comment by petermattis** [comment]
I don't see where in the code that empty entries are generated. Clearly, there are. I suppose I could instrument the raft code. Just curious to trace through how this works. What I do see is that a follower accepts sets its `raft.raft.lead` field from whatever entity sends it `Msg{App,Heartbeat}` requests. As far as I can tell, that's usually how a replica determines the leader after being restarted.

**Comment by petermattis** [comment]
Ah, of course as soon as I send that I see the code in `raft.becomeLeader` which appends an entry with an empt data.

Looking at the `raft.node` code I noticed that it detects leadership changes by noticing changes to the equivalent of `SoftState.Lead`.

**Comment by bdarnell** [comment]
There's also [this block](https://github.com/coreos/etcd/blob/f505bcb91aaac79fb19d6d61ec6b39b5b79064df/raft/raft.go#L671-L678), which overwrites a proposed config change with an empty one if it would conflict with a pending change.

The code in raft/node.go that inspects `.lead` can miss leadership changes if the original leader regains leadership while this node was partitioned away. Since reproposals may be necessary in that case, we still need to watch for empty entries and not just `SoftState.Lead`

**Comment by bdarnell** [comment]
@petermattis Looks like this is done.
