### ISSUE TITLE
cluster not loading correct cluster-ui version when switching on same browser

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#83514]
When switching between cluster with different major versions, doesn't seems to be loading the proper cluster-ui version. Only if you force refresh the page it loads the correct one.

Example:
https://www.loom.com/share/da54c030eb21435d83674ac689bff2bd

Jira issue: CRDB-17117

**Comment by matthewtodd** [comment]
Some observations so far:

1. When I look at the same [brown-sheep](https://cockroachlabs.cloud/cluster/b618a0bd-68eb-445b-b374-7940bcf31bd5/sql-activity?cluster-type=serverless) cluster in @maryliag's [Loom recording](https://www.loom.com/share/672d5352496c435c947d8832372b0dd0), I don't see the fancy "Past 1 Day" preset in the timepicker she did, just a textual representation of the date/time range, with the custom picker. I'm not sure how this is happening. <img width="1372" alt="Screen Shot 2022-06-28 at 1 46 08 PM" src="https://user-images.githubusercontent.com/5261/176249404-89ca2461-4779-47e8-99fe-734ae5ac407b.png">

2. While there's an obvious lack of padding in the custom picker dropdown that we should fix, I can't seem to reproduce the bug here: any value I select or type seems to be accepted.

3. Running v21.1.12 from a local build, the padding looks fine, suggesting the padding issue stems from the cloud styling overrides: <img width="1372" alt="Screen Shot 2022-06-28 at 1 53 18 PM" src="https://user-images.githubusercontent.com/5261/176249994-d57a2c03-ca8f-4857-b074-23208ef347bd.png">

**Comment by matthewtodd** [comment]
Looking further, it appears there's some error in the "switch versions of cluster-ui" mechanism in the cloud code: when I load a [21.2 cluster](https://cockroachlabs.cloud/cluster/b618a0bd-68eb-445b-b374-7940bcf31bd5/sql-activity?cluster-type=serverless), then a [22.1 cluster](https://cockroachlabs.cloud/cluster/60b096f0-057e-4269-9b5e-0f560881a33d/sql-activity?cluster-type=serverless), I see the old 21.2 datepicker until I do a force-reload in the browser. Will loop in the crux team for next steps.

**Comment by matthewtodd** [comment]
Though it would be good to first double-check that we’re not doing anything weird with the cluster-ui loading of that date picker component. Like, maybe it still could be a local problem with our use of the loading mechanism, and not a more general problem with the mechanism itself.

**Comment by maryliag** [comment]
Previously we though the time picker was not properly working, then realized the issue was that it was loading the wrong version. I updated the PR description with the new info.
