### ISSUE TITLE
sqlschema: use job helper function to replan in a multi tenant environment 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#83589]
The jobs v team has created a helper to see if your plan has changed (see: https://github.com/cockroachdb/cockroach/pull/79244/files) and replan. Schema backfills can use this to replan if say, leaseholders move a lot. 

Whether or not to use this right now or leave on the backlog is a judgement call: If not a lot has changed and you need to redo a lot of work if you do replan then it might not be worth it at the current scale of multitenant usage. 

Jira issue: CRDB-17158

Epic CRDB-18923

**Comment by ajwerner** [comment]
We're not likely to do anything here. If we did it would be inside the backfill itself and we'd defer that to the bulk IO team. Any learnings from restores might filter in here, but the bulk IO team would be responsible for making that happen. I'll move this to their board to close.

**Comment by adityamaru** [comment]
I don't think this issue is going to be worked on in its current form. The jobs v-team can't really make decisions for specific job types and how they want to define their planning heuristics.  If this comes up as a slow changefeed because of a bad DistSQL plan I think it will be more actionable egs: https://github.com/cockroachdb/cockroach/issues/114079 it will be more actionable. Closing for now but feel free to reopen if you have more instances of this im unaware of.
