### ISSUE TITLE
storage: create raft replica consistency checker

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#837]
A key guarantee we have is that the underlying raft replicas are identical (there are some caveats in key local space, but still).

We need to create a new Internal command which verifies that replicas are identical.

Periodically, the replica which holds the lease will use the range data iterator to checksum its contents and then issue an InternalConsistencyCheck command with the computed checksum. Replicas which disagree will log errors (fatal?) indicating failed consistency checks.

**Comment by tschottdorf** [comment]
There's an issue here though. If the leader is corrupted, the (healthy) followers should definitely not drink the cool aid. Some synchronization (only nodes which are not in a majority of identical hashes should consider themselves faulty) is necessary and that's unfortunate because you would want to compute the local checksum in a goroutine and not hold up Raft (but you definitely want to send it through Raft to have the same commands persisted).

**Comment by bdarnell** [comment]
The primary purpose of this consistency checker would not be to find corruption in production, but to detect cases (mainly in development/testing) where one of the range commands is not deterministic. 

The synchronization is definitely tricky, since we'd need to ensure that no commands are proposed in raft between starting the checksum and appending the InternalConsistencyCheck.

**Comment by tschottdorf** [comment]
Something that could be done though is to have a command (through Raft) that triggers recomputation of the hash from (hopefully) the same state on all nodes. The scan runs async, but the result is put into range-local addressing, of the form `NodeID -> [last_committed_index, checksum]`. That way each node can individually scan that keyspace every once in a while and see if it's the odd one out.

I didn't realise this was for testing only; I thought the original message suggested this for production/development outside of tests.

**Comment by petermattis** [comment]
See #4317.
