### ISSUE TITLE
import into: give hint when NULL cannot be parsed due to whitespaces.

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#83723]
Steps to reproduce:

1. Make a csv and insert with values
```bash
> touch  ~/local/1/data/extern/test.csv
> echo "'adidas', NULL" > ~/local/1/data/extern/test.csv
```

2. Import the data from the local csv to the table 
```
> CREATE TABLE test(a string, x bool);
> IMPORT INTO test(a, x) CSV DATA ("nodelocal://1/test.csv") WITH nullif="NULL";

ERROR: nodelocal://1/test.csv: error parsing row 1: parse "x" as BOOL: could not parse "NULL" as type bool: invalid bool value (row: 'adidas', NULL)
```

The reason is that NULL cannot be parsed due to the whitespace. Adding a hint would make this more obvious and likely save a lot of time.

The solution here would be to specify `nullif=' NULL'`

Jira issue: CRDB-17225
Epic CRDB-17785

**Comment by andyyang890** [comment]
Question: Do we only want to provide a hint if a parsing error occurs?

e.g. in the above example, if column "x" had been of type string instead of int, the `IMPORT INTO` command would succeed and the resulting row would have the string `" NULL"` as its "x" value instead of a `NULL`. I'd imagine that in most cases this would likely not be the intended result. Would we want to provide a hint in this situation as well?

**Comment by RichardJCai** [comment]
> Question: Do we only want to provide a hint if a parsing error occurs?
> 
> e.g. in the above example, if column "x" had been of type string instead of int, the `IMPORT INTO` command would succeed and the resulting row would have the string `" NULL"` as its "x" value instead of a `NULL`. I'd imagine that in most cases this would likely not be the intended result. Would we want to provide a hint in this situation as well?

Let's focus on the case where it doesn't succeed first - in the case that you stated, it's at least very visible to the user on what is happening.
