### ISSUE TITLE
Insights page V1

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#83774]
Creation on the Insights page.
The V1 version have information about High Wait Time

Figma: https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1086%3A72736

https://www.loom.com/share/daee54ca31644ba4b9b64784c0228b8e?t=83

Jira issue: CRDB-17253

**Comment by maryliag** [comment]
The designs show information about Statements and Transaction contention, but right now we only have Transaction contention information on the level displayed, so for the V1 focus only on the transaction high wait time, using the table `crdb_internal.transaction_contention_events`

**Comment by kevin-v-ngo** [comment]
One call out is that `crdb_internal.transaction_contention_event` only has 1-hour in-memory information. We'll need to call this out in our docs that list out all the insights we have. This may be inconsistent with insights we may introduce that relies on persisted information or real-time snapshot (like unused indexes). 

Adding @Annebirzin. For this V1, we probably wouldn't have a time picker since we only have 1 hour of info.

**Comment by maryliag** [comment]
We will add different tabs on the insights page, this issue is focused on the workload insights tab, while #83829 is focused on schema insights tab.
This issue should be the one creating the structure of the page and the tabs, but only added the first one

**Comment by Annebirzin** [comment]
I added a screen [here](https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1462%3A88367) for how the Insights page could look without a time picker which includes a timestamp: `Timeframe: Past hour (since May 5, 2:23 UTC)`

 
![Screen Shot 2022-07-06 at 2 00 33 PM](https://user-images.githubusercontent.com/51920721/177614036-d148962e-a0df-4b09-a29d-aadee3469dc7.png)
