### ISSUE TITLE
sql: add trigram generators for sqlsmith and TLP

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#83933]
We should ensure that sqlsmith and TLP are testing trigram inverted indexes.

Epic: CRDB-15016

Jira issue: CRDB-17361

**Comment by jordanlewis** [comment]
Notes from investigation:

1. SQLSmith does generate `string % string` bin_ops, which should cover the "similar to" scalar expression.
2. randgen did not generate inverted string indexes; added this as a 1/4 chance when encountering a string column at the end of an index
3. SQLSmith was not generating `string % string` binary operators when being asked for a boolean expression; added this as an option by including the binary operator list in the options for what a boolean expression could generate. This should increase coverage a bit, because there were a few other "binary operators" that I think are actually functioning as comparison operators, like `inet << inet`.
4. SQLSmith does generate arbitrary builtin functions, which should include all recently added trigram builtins as well.
5. SQLSmith wasn't generating LIKE, ILIKE, json path exists, etc as comparison exprs. This is a big oversight for more than just this project and may cause some interesting findings when we enable them.

**Comment by mgartner** [comment]
Thanks for this investigation @jordanlewis!
