### ISSUE TITLE
ui: dragging-to-zoom on graph results in incorrect start time within the DB Console metrics page

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#84001]
**Describe the problem**

When dragging to zoom on a graph within the DB Console, the resulting graph displays the incorrect start time. This makes it challenging to investigate 

**To Reproduce**

1. Go to any metrics dashboard within the DB Console, e.g. Overview dashboard
2. Click and drag to zoom in on a graph
3. Notice that after dragging, the zoomed in graph incorrectly presents the starting time - it does not correspond to the actual start time you picked (the end time is correct)

**Expected behavior**
After dragging to zoom, I expect the new start and end time to reflect the time boundaries that I clicked/dragged.

**Environment:**
 - CockroachDB version 22.1

Jira issue: CRDB-17400

**Comment by nvanbenschoten** [comment]
I noticed this today as well. On v22.1.2, the end time of a drag-to-zoom interval is correct, but the start time is adjusted so that the interval is less than or equal to 1 hour. As a result, drag-to-zoom works correctly for intervals that are less than 1 hour, but is broken for intervals that are greater than 1 hour.

**Comment by maryliag** [comment]
Seems duplicate of https://github.com/cockroachdb/cockroach/issues/71205
