### ISSUE TITLE
sql: errors from ResolveOIDFromOID are ignored

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#84448]
When we hit transaction retry errors the following code paths can end up swallowing errors, which can lead to other issues:
https://github.com/cockroachdb/cockroach/blob/cc5bde5c7abdf732695bc798afb47c6053e922e7/pkg/sql/sem/eval/cast.go#L959
https://github.com/cockroachdb/cockroach/blob/cc5bde5c7abdf732695bc798afb47c6053e922e7/pkg/sql/sem/eval/cast.go#L958

We ran into this scenario in the randomized schema changer workload where OID casts combined with transaction retry errors could lead to failures. 

Jira issue: CRDB-17664
Epic CRDB-14049

**Comment by fqazi** [comment]
Similar problem at : https://github.com/cockroachdb/cockroach/blob/351498d179f6c1cf335fdc2fce304aaeb042edba/pkg/sql/sem/eval/cast.go#L912

**Comment by rafiss** [comment]
@fqazi can you provide a description of what failures or issues this caused?

**Comment by ajwerner** [comment]
This causes the randomized schema change workload to flake because it will no longer see writes. If you continue using a transaction after an error has been swallowed here, the transaction will be internally restarted but the state machine will not observe that. This leads to complete loss of transactionality. This is the greatest source of flakes in https://github.com/cockroachdb/cockroach/issues/78478 and https://github.com/cockroachdb/cockroach/issues/78400. This can cause completely incorrect query results.

**Comment by ajwerner** [comment]
I don’t think this can be a later thing. I can put up a hack, but I don’t feel great about it. I asked Faizan to assign y’all because I think we should have a tight contract about the errors we accept. I don’t know what that set is, and the commentary on the errors we’re willing to accept are lacking. One approach is to just pass through `roachpb.TransactionRetryWithProtoRefreshError`, which I think is enough, but I’m not certain.

**Comment by rafiss** [comment]
Thanks for describing the impact. We can pick it up now, but without knowing those details about the impact, we weren't able to make that decision.
