### ISSUE TITLE
changefeedccl: return error when user doesn't specify a sink on CREATE CHANGEFEED 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#84492]
As described in this thread: https://cockroachlabs.slack.com/archives/C01L5LYD401/p1657833474608799

When you create an enterprise changefeed and leave out the `INTO <sink_uri>` part, the changefeed hangs. We should instead return an error.

Jira issue: CRDB-17691

**Comment by HonoreDB** [comment]
Annoyingly, this is actually working as designed and can't be easily changed. If you don't specify a sink, it just creates a core changefeed. This will look like it's hanging unless there's data in the table and you've either started your console with certain `--format`  tags such as `--format-csv` that cause data to be emitted row by row, or given the changefeed a way to end (either `WITH end_time=<time>` or `WITH initial_scan='only'`. But as with the bytea_output issue, it really would be nice if we could detect user intent better here so that we could safely improve the default behavior.

**Comment by amruss** [comment]
Closing for now - going to clarify in the docs
