### ISSUE TITLE
Discrepancy between active sessions/queries and SQL Statements metrics graph

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#84508]
**Bug Description**
As described in [this Slack thread](https://cockroachlabs.slack.com/archives/C0159JK877C/p1657858893745869), there appears to be a discrepancy between values reported on the `SQL Statements` metrics graph (these values represent a ten-second moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second) and the sessions page (displays active/non-active sessions).

In this case, no sessions were being displayed despite values being actively reported to the `SQL Statement` metrics graph.

**Expected behavior**
We expect the values between the `SQL Statements` metrics graph and Sessions page to be reported accurately and thereby correlate correspondingly.

**Additional data / screenshots**
<img width="883" alt="image (2)" src="https://user-images.githubusercontent.com/15315413/179311703-c74b65d7-fd5a-4fb9-98b7-a89c9b15a4f5.png">
<img width="1131" alt="image (1)" src="https://user-images.githubusercontent.com/15315413/179311708-c1628671-26bd-42be-b102-58d6d0575b91.png">
<img width="980" alt="image" src="https://user-images.githubusercontent.com/15315413/179311710-ad41e7b9-008b-4ec4-9477-e5dfc44bb7ef.png">

**Environment:**
CockroachDB Version 22.1.3

**Additional context**
Suspect/incorrect SQL observability

Jira issue: CRDB-17696

**Comment by xinhaoz** [comment]
I found likely the issue. Checked the default val of the cluster setting for the TTL of an entry in the closed session cache and it's set to 1 minute, when the comment says 1 hour.

**Comment by xinhaoz** [comment]
This _could_ be due to internal sessions kicking out the user sessions. We store both in the same FIFO cache with a default capacity of 1k. I was doing some testing and found the user sessions were evicted quite quickly due to internal sessions filling up the cache. @kevin-v-ngo any input here on whether or not we should continue to store internal sessions or handle them differently?

**Comment by xinhaoz** [comment]
Spoken offline and we definitely want to continue tracking internal sessions. We'll likely split internal and user sessions into different caches so we don't lose user sessions to internal sessions.

**Comment by kevin-v-ngo** [comment]
Another gap that this issue is tracking is the discrepancy a user may see between metrics and the SQL activity pages since we're hiding internal activity in the later. 

We should close this gap with the obs service once we make persistence and retention period consistent across all the data sources that the console pages are pulling from and optionally allow users to enable internal activity in the console.
