### ISSUE TITLE
server: enforce SQL Instance ID = KV node ID for in-memory tenants [CRDB-14537 followup]

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#84602]
When running in-process, we'd like the SQL servers to have the same SQL instance ID as the KV node ID, so that distsql planning can continue equating the two.

(NB: we might be able to obviate this idea once distsql planning uses localities properly)

Jira issue: CRDB-17759

Epic CRDB-23559

**Comment by andreimatei** [comment]
We've had a conversation with @knz and @ajwerner about related topics; dump it here.
There are two somewhat inter-related issue that deserve thought for embedded tenants: the instance ID (and the corresponding row in `system.sql_instances`) and the liveness session in `system.sqlliveness`. I think it's worth considering whether embedded tenants need either of these.
For the instance ID, it seems more clear that an instance ID does not need to be allocated in the same way it is in serverless, and it also doesn't need to be linked to a session (since, if we use the node ID, it never expires).
For the liveness session, I, for one, find it appealing to also not give tenant servers their own sessions, and instead have them piggy-back on the host's session. This seems conceptually simpler than the alternative to me - one process, one session as opposed to one process, many sessions independently heartbeated.
One way I hope this could be done is by "simply" handing the tenant servers the system's `sqlliveness.Liveness` instance. I hope that this would make all uses of sessions transparently go to the system's key space.
When thinking about sessions, I think one thing worth considering is what option makes it simpler to customize the behavior of embedded tenants wrt sessions, compared to serveless. For example, in serverless we want the tenant process to shut down when the tenant's session expires (related to #92739). In the embedded case, we probably do not want that.

**Comment by ajwerner** [comment]
The above proposal from Andrei is sound under the assumption that all sql servers for a given tenant will be embedded. If we ever have a mix of some processes which are embedded and some which are free-standing, we'd be in a pickle.

The sqlinstance separation would be ~fine -- the free-standing sql servers probably never need to communicate with embedded tenant servers. It's not perfect though because we use the knowledge of the previous instance in the tenant to do bookkeeping in tenant rate limiting infrastructure (see the discussion of `next_instance_id` [here](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210604_distributed_token_bucket.md#system-table)). Maybe embedded tenants don't use the rate limiting?

The sqlliveness separation would just not work. The free-standing instances and embedded instances would be searching in a different universe and would each think the other's sessions were not live.

**Comment by knz** [comment]
nit: let's scratch the word "embedded". The word is "shared-process servers" vs "standalone servers".

Agreed that Andrei's approach does not support mixed deployments. That is fine for now. We'll document this restriction. If/when we need more, we can start reserving rows in the liveness table for the (pre-allocated) node IDs, so they don't get reused by instance ID allocation. We can think about this at a later stage.

**Comment by ajwerner** [comment]
I edited the above comment to match the desired terminology.
