### ISSUE TITLE
sql: disallow SRFs in aggregate functions

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#84616]
To reproduce

```
create table t (a int, b int, c STRING[]);
insert into t values (1, 1, ARRAY['a', 'b']);
insert into t values (1, 2, ARRAY['c', 'd']);
insert into t values (2, 2, ARRAY['c']);
insert into t values (1, 1, ARRAY['e', 'f']);
```

It returns an error if try to aggregate the c column with unnest after any other type of aggregation:
```
> select a, max(b), array_agg(unnest(c)) from t group by a;
ERROR: column "c" must appear in the GROUP BY clause or be used in an aggregate function
SQLSTATE: 42803
```

but if the select has that array aggregation before any other aggregation, it works
```
> select a, array_agg(unnest(c)), max(b) from t group by a;
  a |   array_agg   | max
----+---------------+------
  1 | {a,b,c,d,e,f} |   2
  2 | {c}           |   2
```

If I run the unnest first, it also works
```
> select a, max(b), array_agg(x) from (select a, b, unnest(c) as x from t) group by a;
  a | max |   array_agg
----+-----+----------------
  1 |   2 | {a,b,c,d,e,f}
  2 |   2 | {c}
(2 rows)
```

Jira issue: CRDB-17765

**Comment by mgartner** [comment]
The semantics of a set returning functions in projections are questionable. Applying an aggregation to the results of a set returning function add more confusion, which is why I'd guess that Postgres has outlawed it entirely.

Imagine you have a table like:

```
defaultdb> CREATE TABLE t (a INT, b INT, c STRING[], d STRING[]);

defaultdb> SELECT * FROM t;
  a | b |   c   |  d
----+---+-------+------
  1 | 1 | {a,b} | {x}
  1 | 2 | {c,d} | {x}
  2 | 2 | {c}   | {x}
  1 | 1 | {e,f} | {x}
(4 rows)
```

What would you expect the output of `SELECT a, array_agg(unnest(c)), array_agg(unnest(d)) FROM t GROUP BY a` to be? You'd probably think you'd get something like:

```
  a |   array_agg   | array_agg
----+---------------+------------
  1 | {a,b,c,d,e,f} | {x,x,x}
  2 | {c}           | {x}
```

But when there are multiple set returning functions in a projection, they need to return the same number of values, so results are null extended. Observe:

```
defaultdb> select a, unnest(c), unnest(d) from t;
  a | unnest | unnest
----+--------+---------
  1 | a      | x
  1 | b      | NULL
  1 | c      | x
  1 | d      | NULL
  2 | c      | x
  1 | e      | x
  1 | f      | NULL
(7 rows)
```

So with if we allowed `SELECT a, array_agg(unnest(c)), array_agg(unnest(d)) FROM t GROUP BY a`, the result would surprisingly look like:

```
  a |   array_agg   |      array_agg
----+---------------+------------------------
  1 | {a,b,c,d,e,f} | {x,NULL,x,NULL,x,NULL}
  2 | {c}           | {x}
```

So, I think it'd best to disallow SRFs in aggregate functions like Postgres does.

**Comment by yuzefovich** [comment]
@rytaft do you think this can be closed as a dup of #97502?

Or @mgartner do you think this issue should track disallowing SRFs in aggregate functions?

**Comment by rytaft** [comment]
I vote the latter -- just updated the issue title.

**Comment by michae2** [comment]
Looks like this was fixed by https://github.com/cockroachdb/cockroach/pull/105582, closing.
