### ISSUE TITLE
sql: Dropping database with foreign key seems to fail

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#8497]
I first noticed this when a logic test began to time out. It seems like dropping a database which contains a `FOREIGN KEY` can sometimes fail to complete. However, this doesn't always seem to be the case. For instance, I can add a `DROP DATABASE` statement to the end of `testdata/fk` without issue. Below is a series of statements that fails for me.

```
root@:26257> CREATE DATABASE constraints;
CREATE DATABASE
root@:26257> SET DATABASE = constraints;
SET
root@:26257> CREATE TABLE t1 (a INT UNIQUE CHECK (a > 4), CONSTRAINT c2 CHECK (a < 99));
CREATE TABLE
root@:26257> CREATE TABLE t2 (t1_ID INT, CONSTRAINT fk FOREIGN KEY (t1_ID) REFERENCES t1(a), INDEX (t1_ID));
CREATE TABLE
root@:26257> DROP DATABASE constraints;
pq: table "t1" has been deleted
root@:26257> DROP DATABASE constraints;
pq: table "t1" has been deleted
```

However, if the FK is omitted, the database drop works without issue.

```
root@:26257> CREATE DATABASE constraints;
CREATE DATABASE
root@:26257> SET DATABASE = constraints;
SET
root@:26257> CREATE TABLE t1 (a INT UNIQUE CHECK (a > 4), CONSTRAINT c2 CHECK (a < 99));
CREATE TABLE
root@:26257> CREATE TABLE t2 (t1_ID INT, INDEX (t1_ID));
CREATE TABLE
root@:26257> DROP DATABASE constraints;
DROP DATABASE
```

**Comment by knz** [comment]
I've seen something similar without being able to reproduce it:
- create table t1
- create table t2 with a foreign key on t1
- drop table t1 - accepted, although it shouldn't have!
- drop table t2 - fails with "table t1 has been deleted"

**Comment by nvanbenschoten** [comment]
I can still easily reproduce this if I uncomment the `DROP DATABASE` [statement that references this issue](https://github.com/cockroachdb/cockroach/blob/983a481d875fd3311814a7fa20fc7b20c027d40f/pkg/sql/testdata/information_schema#L571) in `sql/testdata/information_schema`.

**Comment by jordanlewis** [comment]
I think I see the problem here. When a table is being dropped, we remove all of its foreign key back references - this modifies the foreign key's referenced table and therefore needs to set its `up_version` marker indicating a schema change. However, if the other table has already been dropped, this operation errors out to prevent mutations to a table being misleadingly accepted when the table is about to be dropped anyway.

This gets us into trouble when dropping a database, because at the moment`DROP DATABASE` drops its tables in the lexicographical ordering given by `table.getTablesNames`, rather than the topological ordering given by the graph of their constraints. So if these two orderings disagree, there's a possibility that we'll drop the tables in the wrong order and run into the error above.

I see two avenues to fixing this problem.

1. Sort the tables topologically by reference before dropping them. This won't work if we plan to or already support reference cycles, of course.
2. Relax the limitation that you can't modify tables that are currently being dropped. I'm not sure what kind of negative effects this might have.

**Comment by dt** [comment]
fwiw, we do support cycles.
I'd suggest we just don't need to edit tables we're about to drop... cc @vivekmenezes ?

**Comment by a-robinson** [comment]
Yeah, I think we may want to just avoid editing references of tables/views that will also be dropped during the same transaction.

**Comment by jordanlewis** [comment]
I have a patch for this forthcoming.

**Comment by vivekmenezes** [comment]
I forget how we implemented this, but I'd recommend an approach where we add hints like "up_version" to all the tables involved so that the schema change intent is reflected in all the involved tables, and then we separately rollout the change.
