### ISSUE TITLE
kvserver/batcheval: no-op `MVCCDeleteRangeUsingTombstone` if there is no live data

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85725]
**Is your feature request related to a problem? Please describe.**
In https://github.com/cockroachdb/cockroach/issues/70427 we're moving the `gcjob` to issue `DeleteRange` operations at the beginning of the job. This logic is not going to do anything smart like checkpoint what has been already deleted. That means that for very large tables, it may redo work if the job coordinator dies. In principle, we ought to be able to make this work idempotent. 

**Describe the solution you'd like**
If the MVCC stats are reliable, we can quickly no-op the operation if the number of live keys is 0. Similarly, even if we have to scan all of the data, if we don't find anything to delete, then we should not need to issue the range deletion operation. 

Jira issue: CRDB-18401

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
I think #85522 will already be close enough to a noop, but will see about adding something in.

**Comment by erikgrinaker** [comment]
>If the MVCC stats are reliable, we can quickly no-op the operation if the number of live keys is 0. Similarly, even if we have to scan all of the data, if we don't find anything to delete, then we should not need to issue the range deletion operation.

I think we may want to ensure that there is an MVCC range tombstone across the span, because the GC would likely be more efficient. Or won't that make much difference @aliher1911?

I was thinking we'd do a quick scan to look for an existing range tombstone, and use range key masking (with block property filters) to quickly scan for live data above it.
