### ISSUE TITLE
Cluster version at top of DBConsole does not use the cluster setting for 'version'

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#85883]
**Describe the problem**

The cluster version shown at the top of the DBConsole only shows the version of each of the binaries (assuming they're all the same), rather than use the cluster setting `version`.  This means it will show the wrong version when a cluster has had all its binaries updated but the version has not been finalized.

**To Reproduce**

Start with a 21.2 cluster, set `cluster.preserve_downgrade_option` to '21.2' and then upgrade all the binaries to the same 22.1 version.

The GUI will now show 22.1 at the top, but the cluster is still technically a 21.2 cluster.

**Expected behavior**

The GUI should use the cluster setting for 'version' instead.

Jira issue: CRDB-18477

**Comment by dhartunian** [comment]
Agree with @dt that this isn't really a bug but maybe a feature request instead.

I could see a use case for displaying both a "binary version" and a "cluster version" but worry that would cause further confusion.

My assumption is that if someone is setting `preserve_downgrade_option` they are an advanced operator and know what they're doing and understand that they're in a state where binary and cluster versions won't match. The majority of clusters will actually match in terms of binary and cluster version "most of the time", right?

🤔 maybe we could only display when they don't match. I think we already have a banner that displays when you've preserved downgrade for too long.

**Comment by a-entin** [comment]
Adding some color...

We have seen operator's errors and misconceptions related to inadvertent mis-matches of versions, or unfinalized major upgrades. This can be alleviated if we displayed important version details in the console UI, such as...

- if a major has not been finalized, have an exclamation mark and/or a text indicating the upgrade has not been finalized

- what we show there is the version of the executable on the node the browser is connected to. other nodes may have mismatched executables. for example, an operator missed a node with a patch release upgrade. would be good to have an indicator that nodes are running mismatched versions and perhaps make the version label into a clickable url to show the list of all node versions across the cluster

- make it clear what we currently display is a node executable version. there is another "version" - on-disk format, which is returned by version cluster setting. It would be nice to have that next to the exe version perhaps. mostly it will match the exe's major, but not necessarily, e.g. until major upgrade is finalized. May be only show the on-disk format during the mis-match period i.e. until finalized.

We have plenty of real-estate next to the current version info and we have obscure version related issues due to operator's errors. It would be good to put the vacant space to a good use.

**Comment by a-entin** [comment]
The gist - above is the suggestion to show all versions if there is a mis-match. could be 2 kinds of mis-matches - between nodes' exe-s and between exes and on-disk format.

**Comment by knz** [comment]
I think we might want to show both version side by side, with a link to the doc page which explains what to do.

**Comment by rafiss** [comment]
This is related to https://github.com/cockroachdb/cockroach/issues/66987 - resolving one might even resolve the other issue

**Comment by rafiss** [comment]
>  if a major has not been finalized, have an exclamation mark and/or a text indicating the upgrade has not been finalized

https://github.com/cockroachdb/cockroach/issues/66987 is now resolved and implements the above.

>  what we show there is the version of the executable on the node the browser is connected to. other nodes may have mismatched executables. for example, an operator missed a node with a patch release upgrade. would be good to have an indicator that nodes are running mismatched versions and perhaps make the version label into a clickable url to show the list of all node versions across the cluster

That warning already existed. It looks like this:
<img width="1630" alt="Screenshot 2023-03-27 at 4 43 06 PM" src="https://user-images.githubusercontent.com/1320573/228130952-0d2adb3a-3d87-498a-a812-2cfe10f56406.png">

>  make it clear what we currently display is a node executable version. there is another "version" - on-disk format, which is returned by version cluster setting. It would be nice to have that next to the exe version perhaps. mostly it will match the exe's major, but not necessarily, e.g. until major upgrade is finalized. May be only show the on-disk format during the mis-match period i.e. until finalized.

The resolution of https://github.com/cockroachdb/cockroach/issues/66987 looks like this:
<img width="1205" alt="Screenshot 2023-06-09 at 5 29 01 PM" src="https://github.com/cockroachdb/cockroach/assets/1017486/cb6f1943-91bd-4528-98f4-bc5704a7e9dc">

Maybe that is enough?

So we might have accomplished enough to close this ticket.

**Comment by knz** [comment]
imho the text of these banners should use words that clarify the difference between the executable version and the cluster setting. If someone doesn't know there's a difference, the current phrasing is a bit confusing and it doesn't clearly indicate what the recommended "next action" is.
