### ISSUE TITLE
sql: `CREATE SCHEMA` fails if cluster setting `server.eventlog.enabled` is set to false

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#86132]
**Describe the problem**

After `SET CLUSTER SETTING server.eventlog.enabled = false`, `CREATE SCHEMA` fails desc validation:

```
demo@127.0.0.1:26257/defaultdb> create schema s;
ERROR: schema "s" (104): expected matching namespace entry, found none
```

**To Reproduce**

Change the cluster setting and try CREATE SCHEMA via SQL.

**Expected behavior**

CREATE SCHEMA works regardless of setting value.

**Environment:**

`master` branch

cc @ajwerner for triage

Jira issue: CRDB-18593

**Comment by ajwerner** [comment]
This one runs deep. It's another internal executor hellscape sort of issue. The bug comes from the fact that writing to the `system.eventlog` table used the internal executor, and when we executed the internal executor as part of performing that write, we moved the transaction's read sequence number up so that we saw the write. This now makes me scared that the halloween problem can be resurrected if you call something which internally invokes an internal executor. We need to find a more sane way to talk about executing queries in the context of statement execution. The "fix" here is straightforward enough: we'll step the transaction during `(*sql.connExecutor).handleAutoCommit`, but the deeper bug implied here is going to be fun.

**Comment by knz** [comment]
Do you want to file that followup internalexec issue, or do you prefer me to do it?

**Comment by ajwerner** [comment]
Yeah, I'll do it. I'm bisecting right now to figure out what changed to reveal this bug.

**Comment by knz** [comment]
@ajwerner we're not out of the woods yet.

1. open  pkg/sql/logictest/testdata/logic_test/rename_atomic
2. add `statement ok` and `set cluster setting server.eventlog.enabled = false` at the beginning
3. run

I get:

```
        ../../../../sql/logictest/testdata/logic_test/rename_atomic:19:
        expected success, but found
        (XXUUU) schema "sc" (110): expected matching namespace entry, found none
        validate.go:463: in validateNamespace()
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6157677?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by ajwerner** [comment]
@knz here you go https://github.com/cockroachdb/cockroach/pull/86461
