### ISSUE TITLE
sql: enable UDF in DistSQL

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#86310]
**Is your feature request related to a problem? Please describe.**
A child of https://github.com/cockroachdb/cockroach/issues/58356

**Describe the solution you'd like**
For now we skip DistSQL for any `tree.RoutineExpr` built from UDF. But we need to add some function resolver to DistSQL so that UDFs can be resolved there for better performance.

Jira issue: CRDB-18689

Epic CRDB-18821

**Comment by mgartner** [comment]
Part of UDF execution is optimization of each statement in the UDF body via a closure that has been provided. This closure cannot be distributed, therefore I don't think distributed execution of UDFs is possible at this time. However, we're aiming to inline simple UDFs when possible which will turn a UDF invocation into a traditional relational expression. When inlined, distribution is possible and should occur automatically.

I'm going to close this issue, because I don't think it's possible.
