### ISSUE TITLE
add session variable to emulate retryable exceptions on commit

### ISSUE THREAD

**Issue by 62mkv** [cockroachdb/cockroach#86370]
**Is your feature request related to a problem? Please describe.**
Currently, there're situations when CDB returns 40001 errors only on COMMIT; for example, `RETRY_SERIALIZABLE`. Reliably reproducing such cases is notoriously tricky. Since v22.1, there's a session variable called `inject_retry_errors_enabled`, that greatly helps reproducing a lot of scenarios. However, when one wants to emulate [some of] contention errors, that only occur during COMMIT, this is of no help, because any statement fails before one could even proceed to COMMIT

**Describe the solution you'd like**
Suggestion: add support for a separate session variable `inject_retry_errors_on_commit_enabled`, that would only fail COMMIT statement with a certain 40001 exception

**Describe alternatives you've considered**
I can only think of each interested user building a reliably reproducible integration test, that (as my experience indicates) can take hours and hours. The only test suite in CDB codebase I've found for this particular ("failed preemptive refresh") exception, adds a column to a table, while transaction is running, in order to reproduce it (https://github.com/cockroachdb/cockroach/blob/ef5ac7f9c76ab08272ffc69a8f19f0992834a828/pkg/sql/catalog/lease/lease_test.go#L917) which is of course, very strange scenario for a regular application to rely on.

Jira issue: CRDB-18721

**Comment by Prashansa-K** [comment]
@rimadeodhar @rafiss @yuzefovich I would like to take this up. I am a beginner here and would like to contribute to cockroachdb. Can I try with this?

**Comment by rafiss** [comment]
@Prashansa-K Sure! To get started take a look at the PR where I added `inject_retry_errors_enabled` https://github.com/cockroachdb/cockroach/pull/71357. Your change will need similar tests. You should add the new logic right before this line: https://github.com/cockroachdb/cockroach/blob/14c9f2a1993b7a26ae6215f4cd0012c87ae5ccc2/pkg/sql/conn_executor_exec.go#L882

Please read our contributing guidelines: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73204033/Contributing+to+CockroachDB

**Comment by quanuw** [comment]
@Prashansa-K Are you currently working on this issue? If not, can I look into this?

**Comment by Prashansa-K** [comment]
@quanuw Sure you can go ahead. I could not take this up yet.

**Comment by quanuw** [comment]
Hi @rafiss,

I am trying to set up my local dev environment and I am running into some issues. When I run ./dev doctor, I get an error creating symlinks `$ ./dev doctor
=============================
=== RUNNING DOCTOR CHECKS ===
=============================
ERROR: symlink C:\Users\quan\repos\cockroach\githooks\commit-msg .git/hooks/githooks\commit-msg: The system cannot find the path specified.
`
Are the above paths supposed to be created by the dev doctor command? I think the second path has issues because of the use of forward and back slashes.

I'm using a windows machine running Version 10.0.19045 Build 19045 with developer mode enabled. 

Do you have some suggestions on how I can resolve this?
