### ISSUE TITLE
build: `go mod tidy` fails on opentelemetry

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#86454]
This is a recent regression:

```
kena@kenax ....com/cockroachdb/cockroach % go mod tidy
go: finding module for package github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/resource/v1
go: finding module for package github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/common/v1
go: finding module for package github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/logs/v1
github.com/cockroachdb/cockroach/pkg/obs imports
        github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/common/v1: no matching versions for query "latest"
github.com/cockroachdb/cockroach/pkg/obs imports
        github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/logs/v1: no matching versions for query "latest"
github.com/cockroachdb/cockroach/pkg/obs imports
        github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/resource/v1: no matching versions for query "latest"
```

Jira issue: CRDB-18766

**Comment by andreimatei** [comment]
This seems to have to do with with the fact that, with a fresh checkout, there's no `.go` file inside `pkg/obsservice/obspb/opentelemetry-proto/resource/v1` - there's only a `.proto` file. If you generate the `pb.go` file with `make buildshort` or `dev generate protobuf`, `go mod tidy` starts working. I think dirs without `.go` files are not recognized by `go` as packages - or something. I put a dummy `.go` file in those dirs, it works. I guess I'll do that.

But I think the real problem here is that we don't check in the `pb.go` files. @rickystewart, any chance I can convince you to change your mind in that? There's a lot of paper cuts caused by the fact that we stopped checking them in. I don't believe that the benefit that we get from not checking them in is worth it. In fact, I didn't really understand at all the build benefit presented [in this thread](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1659391947898569?thread_ts=1659115550.115699&cid=C019A8NANH0).

**Comment by rickystewart** [comment]
To my knowledge `dev generate protobuf` has been necessary to make `go mod tidy` work for a while (due to the missing `.pb.go` files mentioned above -- `opentelemetry` is not the first case of this), so I don't think this is a new issue/everything is working as intended. 

I'll do a poll of the engineering team on the topic of checking in `.pb.go` files. If the feeling is that most people want them back then we can talk about how to make it happen.

**Comment by knz** [comment]
Can we populate an empty go file in that directory, and call it a day?

I recall I have done this in other places already.

Let's not revisit the .pb.go discussion in this ticket. If we want to discuss this, we can do this after stability.

**Comment by andreimatei** [comment]
> Can we populate an empty go file in that directory, and call it a day?

That's what I was suggesting, but it's a bit annoying because the respective directory is supposed to be updated through a script.
I've verified that indeed there are a bunch of other directories blocking `go mod tidy` in the same way; these new ones are not special. I'll let Ricky decide whether to put dummy files in all of them, or just close this issue...

**Comment by knz** [comment]
Can we populate an empty go file in that directory, and call it a day?

I recall I have done this in other places already.

Let's not revisit the .pb.go discussion in this ticket. If we want to discuss this, we can do this after stability.

**Comment by knz** [comment]
> To my knowledge dev generate protobuf has been necessary to make go mod tidy work for a while 

I hadn't paid attention to this.

I consider myself sufficiently informed, and I don't need a solution for this issue any more. Thanks Ricky and andrei for the discussion!
