### ISSUE TITLE
storage: self-service manifest download

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#86455]
**Is your feature request related to a problem? Please describe.**

During outages and escalations, a Pebble MANIFEST file is often useful for determining the sequence of LSM changes that led to the current state - typically during "LSM inversion" events. Collecting the MANIFEST file is currently a manual operation that requires filesystem access (i.e. operator needs to be able to `cp; scp` the file).

**Describe the solution you'd like**

Reduce the friction required in collecting manifest files. This could look something like a link on the advanced debug page that performs the fetching / compression of all the local manifest files, allowing the operator to download from the DB console. Exposing an endpoint would allow other tooling to hook into the manifest file collection.

Any changes here would need to consider appropriate permissions / ACLs for accessing the manifest files, as these contain raw keys, which may contain sensitive information.

Jira issue: CRDB-18767

**Comment by joshimhoff** [comment]
Looks great. There are some CC side concerns too, e.g. in CC devs can't access DB console on a specific node. Maybe we can fix that, or maybe the endpoint described here can allow downloading the MANIFEST of arbitrary nodes. Another thing is that devs don't have access to DB console by default. We prob can't "fix that", as it is by design, but we can make it easier for SREs to grant devs temporary access (it is already pretty easy).

Zooming out, whatever we do on the DB side should be part of a plan on the CC side that realizes the goal. We'll need work done on both sides prob.
