### ISSUE TITLE
storage: consider returning Raft errors across RaftTransport to the initiating store

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#8672]
#8495 changed `RaftTransport` to allow for errors to be returned across the network to remote nodes without shutting down the entire stream. Some more elegant behavior is now possible - for instance, we currently silently drop snapshot messages ([`store.go:2198`](https://github.com/cockroachdb/cockroach/blob/master/storage/store.go#L2198) in`HandleRaftRequest`) if they fail to be ratified by `canApplySnapshotLocked`. Now that we can return errors across nodes, it might be worth returning an error in that situation, although it is unclear to me whether any useful behavioral change would result on the initiating store besides better logging.

**Comment by tamird** [comment]
This doesn't strike me as cleanup - it strikes me as potentially masking correctness issues. Why is it appropriate to mark it "Later"?

**Comment by arjunravinarayan** [comment]
@bdarnell, could you please chime in? I'm unsure.

**Comment by bdarnell** [comment]
@tamird What kind of correctness issues could be masked? It takes more than vague FUD to make this a priority.

In the case of the `canApplySnapshot` check, I think returning an error here is best thought of as an optimization: If `canApplySnapshot` fails, this is a condition that will not be resolved by simply retrying, so we don't want the sender to think the message was dropped by the network. We should return an error here so that the sender can stop retrying (and initiate a ChangeReplicas to remove the node that is unable to accept a snapshot).

This is something that would be useful to us right now on the test clusters; we see some issues where snapshots can't be applied and ranges are stuck (#8942, #8007). But improving error handling here mainly papers over the problem - we should figure out why we're unable to apply the snapshot in the first place (#8944 fixes one case). 

So this is higher priority than a lot of the stuff in "Later", but it's still not something I'd prioritize right now unless we see more evidence that this is a problem in practice.

**Comment by tamird** [comment]
I don't have a specific correctness issue in mind, but the lack of "closed loop" error reporting here is potentially cause for concern simply because we don't know the sender state when such an error occurs.

**Comment by a6802739** [comment]
I can add some error information when handling with `canApplySnapshot `.
