### ISSUE TITLE
Chart tooltip gets squeezed on the right side of the screen

### ISSUE THREAD

**Issue by rsadres** [cockroachdb/cockroach#86778]
Problem:
Seems like the chart width is a bounding box for the hover tooltip? The tooltip width changes as you hover over points on the right side of the chart and squeezes the tooltip content making it hard to read the metrics.

**To Reproduce**
- Login to DB Console
- Go to the Metrics section
- Hover over any chart on that page

**Expected behavior**
Tooltip width stays consistent? I'm not sure exactly. I've seen a few of our charts where the tooltip hangs off of the right side of the chart successfully and some unsuccessfully (tooltip is off the right edge of the screen, display is cut off by browser window.

**Additional data / screenshots**
Two screenshots of the offending squeezed tooltip.
One screenshot of a successful tooltip in CC Console
One screenshot of the same tooltip in CC Console in a narrower browser window to illustrate I am not sure what 'expected behavior' should be. 

![DBConsole-squeezed-tooltip1](https://user-images.githubusercontent.com/10146234/186470864-804da795-79aa-44dc-be6b-25285b802d33.png)
![DBConsole-squeezed-tooltip2](https://user-images.githubusercontent.com/10146234/186470867-9dba724e-7572-4dd5-9791-b366c43f714f.png)
![CCConsole-tooltip-cutoff-by-browser](https://user-images.githubusercontent.com/10146234/186470868-3061edb8-2cee-40cf-acd3-71091bbf735c.png)
![CCConsole-tooltip-not-cutoff-wider-browser-window](https://user-images.githubusercontent.com/10146234/186470870-bfcfff71-6a77-4ca7-9fc3-207482bc4527.png)

**Environment:**
 - Browser: Google Chrome

CC @sjbarag @nathanstilwell FYI

Jira issue: CRDB-18927

**Comment by daniel-crlabs** [comment]
If this is of any consolation, this issue is also observed using firefox. However, on the bright side, this issue does not happen when using safari:

<img width="1415" alt="Screen Shot 2022-08-31 at 10 37 03 AM" src="https://user-images.githubusercontent.com/78774369/187705791-bb2c01c9-c2bf-4eb7-a2ed-5a1a5b4371a9.png">

**Comment by daniel-crlabs** [comment]
I have ran into this issue again today trying to troubleshoot an outage for a customer on cockroach cloud cluster and this time, it makes it impossible to view all the data, since the graph is the last one in the page. 

Please, is there any way this problem can be looked into, this really hinders our capability to provide adequate support.

<img width="978" alt="Screen Shot 2022-11-01 at 9 26 04 AM" src="https://user-images.githubusercontent.com/78774369/199244321-097b6d10-ceee-4ca7-b23a-213a6be411ec.png">

**Comment by nathanstilwell** [comment]
I believe the issue is due to `width: fit-content` being set in [linegraph.styl](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.styl#L40). Modern versions of Safari support this value (supposedly) so it's interesting that this isn't an issue for that browser.

I think the fix is as simple as changing the width to `max-content` to prevent the width from collapsing. I'll try to get a PR up this week.

**Comment by daniel-crlabs** [comment]
Thanks for looking into this, appreciate it.
