### ISSUE TITLE
acceptance: TestDockerCSharp has drifted

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#86852]
**Describe the problem**

The acceptance test TestDockerCSharp was previously skipped due to #58218. Now we've fixed that, if we try to re-enable the test we run into a new failure:

```
/usr/share/dotnet/sdk/2.1.804/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/mnt/data/csharp/acceptance.csproj]
/usr/share/dotnet/sdk/2.1.804/NuGet.targets(123,5): error :   Resource temporarily unavailable [/mnt/data/csharp/acceptance.csproj]

The build failed. Please fix the build errors and run again.
non-zero exit code: 1
```

and

```
No executable found matching command "dotnet-notacommand"
non-zero exit code: 1
```

Jira issue: CRDB-18965

**Comment by rafiss** [comment]
The `No executable found matching command "dotnet-notacommand"` is actually a desired error. See all the `testDockerFail` calls at https://github.com/cockroachdb/cockroach/blob/54bc65f212b9f30184c27a328ab27136d2143934/pkg/acceptance/adapter_test.go#L48

Looks like the other issue is because of referring to an outdated package repo. Thanks for the report.
