### ISSUE TITLE
kvserver: DistSender stack overflow crash

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#87167]
**Describe the problem**

```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc1fb20c480 stack=[0xc1fb20c000, 0xc21b20c000]
fatal error: stack overflow

[...]
```

logs directory https://drive.google.com/file/d/1UengTormF31OqZRkWJQJbL295FhwUPnj/view?usp=sharing

**To Reproduce**

Randomly saw this while running clusters for https://github.com/cockroachdb/cockroach/pull/87106

master @ 634e4b47c9fa4187d90ed6b8f6da1042489ccff9 (plus some unrelated local commits)

Jira issue: CRDB-19188

**Comment by tbg** [comment]
Possibly this is just a way for the node to tell us that it was basically OOMing but still worth a look.

**Comment by tbg** [comment]
panicparse html: 
[foo.html.txt](https://github.com/cockroachdb/cockroach/files/9460460/foo.html.txt)

**Comment by erikgrinaker** [comment]
Something seems off here. The stack trace essentially repeats this sequence:

```
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x171029d1ac2e505d, 0x0, 0x0}, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1389 +0x1393 fp=0xc1fb233800 sp=0xc1fb232f98 pc=0x1916133
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x171029d1ac2e505d, 0x0, 0x0}, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1598 +0x114e fp=0xc1fb2340d0 sp=0xc1fb233800 pc=0x191888e
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x171029d1ac2e505d, 0x0, 0x0}, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1389 +0x1393 fp=0xc1fb234938 sp=0xc1fb2340d0 pc=0x1916133
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x171029d1ac2e505d, 0x0, 0x0}, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1598 +0x114e fp=0xc1fb235208 sp=0xc1fb234938 pc=0x191888e
```

`sendPartialBatch` calls into `divideAndSendBatchToRanges` at `dist_sender.go:1598` because the batch no longer fits into the range:

https://github.com/cockroachdb/cockroach/blob/0402f4764e1fb91283095513a64fae761645d7c1/pkg/kv/kvclient/kvcoord/dist_sender.go#L1587-L1600

`divideAndSendBatchToRanges` the splits the batch to range bounds and sends it via `sendPartialBatch` at `dist_sender.go:1389`:

https://github.com/cockroachdb/cockroach/blob/0402f4764e1fb91283095513a64fae761645d7c1/pkg/kv/kvclient/kvcoord/dist_sender.go#L1382-L1391

However, this then immediately finds that the batch doesn't fit into the range, and tries to split it again by calling `divideAndSendBatchToRanges`. This indicates an issue with the range cache token or some such, since I don't see why a batch that we _just split_ according to range boundaries would no longer fit into the range.

I suppose it's plausible that the processing here blocked on network IO for a long time while there were repeated ongoing range splits of the target span, but it seems rather unlikely.

@arulajmani Do you mind having a look at this, since it could possibly be related to the changes we made back in #85503?

**Comment by erikgrinaker** [comment]
Here's the stack dump: [stack.txt](https://github.com/cockroachdb/cockroach/files/9597657/stack.txt)

**Comment by arulajmani** [comment]
One issue here seems to be the way we're detecting if the range has shrunk or not in `sendPartialBatch` -- the value of `rs` that function is being supplied corresponds to the entire batch request. Instead, I think it should be the span encompassing _just_ the partial batch. Concretely, this diff at the caller:

```
index 0789fae98e..db18a8ee78 100644
--- a/pkg/kv/kvclient/kvcoord/dist_sender.go
+++ b/pkg/kv/kvclient/kvcoord/dist_sender.go
@@ -1392,11 +1392,11 @@ func (ds *DistSender) divideAndSendBatchToRanges(
                // If we can reserve one of the limited goroutines available for parallel
                // batch RPCs, send asynchronously.
                if canParallelize && !lastRange && !ds.disableParallelBatches &&
-                       ds.sendPartialBatchAsync(ctx, curRangeBatch, rs, isReverse, withCommit, batchIdx, ri.Token(), responseCh, positions) {
+                       ds.sendPartialBatchAsync(ctx, curRangeBatch, curRangeRS, isReverse, withCommit, batchIdx, ri.Token(), responseCh, positions) {
                        // Sent the batch asynchronously.
                } else {
                        resp := ds.sendPartialBatch(
-                               ctx, curRangeBatch, rs, isReverse, withCommit, batchIdx, ri.Token(), positions,
+                               ctx, curRangeBatch, curRangeRS, isReverse, withCommit, batchIdx, ri.Token(), positions,
                        )
```

This change should be enough to prevent the stack from growing unboundedly. I'll send out a patch. 

However, I'm still not sure how we're ending up in this regime to begin with. The intersection check is only triggered if the call to `sendToReplicas` invalidated the `EvictionToken`. I haven't quite been able to nail why this keeps happening repeatedly.

**Comment by arulajmani** [comment]
Closing this out as per @nvanbenschoten's comment here: https://github.com/cockroachdb/cockroach/pull/88506#issuecomment-1259512287. Even though the stack doesn't seem to add up to 1GB, we've verified that the `DistSender` goroutine is culpable for the stack overflow.
