### ISSUE TITLE
Why not destroy subsumed range while MergeRange?

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#8760]
Remove and destroy the subsumed range with ```Store.removeReplicaImpl```, but we set the parameter ```destroyed``` with ```false```, why not destroy the subsumed range Replica? I am confused.

**Comment by veteranlu** [comment]
@bdarnell

**Comment by bdarnell** [comment]
The `destroy` argument to `removeReplicaImpl` refers to deleting the data from disk, which we don't want to do in the case of a merge, because that data is now a part of the combined range. We do, however, want to set the `destroyed` attribute of `Replica`. Merges are disabled for now, and we won't be turning them on for a long time, but I've added this to the checklist at #2433.
