### ISSUE TITLE
An Unexpected Error in `CROSS MERGE JOIN`

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#88104]
**Describe the problem**

An unexpected error in `CROSS MERGE JOIN`.

**To Reproduce**

```sql
CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
SELECT * FROM t0 CROSS MERGE JOIN t1; -- ERROR: could not produce a query plan conforming to the MERGE JOIN hint
```

**Expected behavior**
Referring to this [document](https://www.cockroachlabs.com/docs/v22.1/cost-based-optimizer#join-hints), I understand `CROSS MERGE JOIN` is allowed and should not have this error.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [1f24e52aea4195ffe26b97160079bb29f264338a]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-19688

**Comment by rytaft** [comment]
Hi @bajinsheng, thanks for the report! I think this is probably an error in our documentation, since I don't see how it would be possible to perform a `CROSS MERGE JOIN`. A merge join requires that both inputs are sorted on the join key, but in a cross join there is no join key, so the concept doesn't really make sense. I think we should probably change this example to `CROSS HASH JOIN`, or just remove it altogether.

**Comment by rytaft** [comment]
I opened https://github.com/cockroachdb/docs/issues/15120 in the docs repo, so I'll close this one.

**Comment by bajinsheng** [comment]
Thanks for your prompt reply!
