### ISSUE TITLE
cli: version does not list RocksDB version

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8830]
```
cockroach version
Build Tag:   beta-20160728-650-gf09503b
Build Time:  2016/08/25 14:20:33
Platform:    linux amd64
Go Version:  go1.7rc6
C Compiler:  gcc 4.9.2
```

It could be obtained from running with `--deps` and looking up the sha, but this looks fundamental enough to print there directly.

**Comment by bdarnell** [comment]
I don't know; I feel like our version output is too verbose already (is the compiler version really that useful?). To date the rocksdb version has mattered less than the grpc or etcd versions, so this seems like a slippery slope to adding even more. And unlike the stuff we currently print, the build tag always identifies an exact rocksdb version, so including it is somewhat redundant (although rocksdb has the nice property of tagged releases with friendly version numbers, instead of just a git commit id, so it's not completely redundant with the full `--deps` dump). Maybe we should just add the friendly rocksdb version number to `--deps`.

**Comment by dt** [comment]
fwiw, I included go and gcc versions there since, while the the version build tag *almost* uniquely specifies the binary, those two are left up to the user/env that built it.

My goal was that that output could be pasted into an issue report and would tell us essentially everything we needed to know about the binary itself.

**Comment by tschottdorf** [comment]
Yeah, taking a step back I think the status quo is good. We have all the deps pinned and the remaining log lines are exactly what makes it unique. If anyone feels differently, feel free to reopen.
