### ISSUE TITLE
kvserver: TestLeasePreferencesDuringOutage is flaky

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#88769]
Failures generally look like the following assertion error:

```        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/kvserver_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/client_lease_test.go:929
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 5
        	Test:       	TestLeasePreferencesDuringOutage
```

Some failures in TC:
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6634041&buildTypeId=Cockroach_UnitTests_BazelUnitTests
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6609152&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=buildResultsDiv
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6632206&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests#testNameId-4172107706173416798

I was also able to see a failure in under 10 minutes using:

```
./dev test ./pkg/kv/kvserver/ -f TestLeasePreferencesDuringOutage --stress --timeout 10m --ignore-cache
```

Jira issue: CRDB-20009

**Comment by knz** [comment]
one more here on the v22.2 branch: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/7886738?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by aliher1911** [comment]
Fails on master for different reasons than 22.2. I'm fixing 22 cause in #103636 but master failure is happening for other reasons.
First is that it doesn't verify if process in enqueue actually succeeds, and it doesn't because it always fails with 'store throttled' error, so we always check against underreplicated range and fail.
If this operation is retried, then we end up in non-conformance situation after upreplication, but I'm not sure why. Someone from allocator might have a better idea.

**Comment by irfansharif** [comment]
I'm going to let this issue lapse even though it's flakey on master. I expect it appear through TC-generated issues and fall into our L2 triage queues, but I'll ping @cockroachdb/kv-distribution if they want to get ahead of it anyway.

**Comment by kvoli** [comment]
This test is still skipped on master. Reopening and assigning to myself.

https://github.com/cockroachdb/cockroach/blob/7d6600e5b9fef9ab286cd7781d8f3b63025ca676/pkg/kv/kvserver/client_lease_test.go#L919-L919

**Comment by kvoli** [comment]
I'm suspecting initial flaky behavior was due to either bfbf3c7fe4c13b0808afd0738f0ea494c1060d60 or 79886bb56a388b41c3dca327ba0d470d3b79b850. After the test was skipped, f2c3e12c6363ef4cdc929fff5023f85802699b39 merged, which legitimately broke the test. Since the test was skipped, it didn't fail as a result.

xref https://github.com/cockroachdb/cockroach/issues/106102
