### ISSUE TITLE
sql: granularly redact schema change jobs payload information in debug.zip

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#88939]
In 22.2/22.1 patch release, we redacted the payloads from the system.jobs table for PCI compliance. This was a course-grained approach, that obscures important information for debugging. The schema team should decide what information should not be redacted for schema change jobs and implement this in a 22.2 patch release.

For more information, see: https://github.com/cockroachdb/cockroach/issues/88069
For inspiration, see: https://github.com/cockroachdb/cockroach/pull/87839

Jira issue: CRDB-20048

**Comment by ajwerner** [comment]
There are keys in the progress checkpoints which I assume are problematic. Otherwise it's just some IDs IIRC.

**Comment by ajwerner** [comment]
@amruss can we get some intel on the priority for this work and the required timeline?

**Comment by postamar** [comment]
As far as I can tell we need to redact the following, which may contain PII:
- in `TypeSchemaChangeDetails`: `transitioning_members`;
- in `NewSchemaChangeDetails`: `completed_spans` in `BackfillProgress` and `MergeProgress`;
- in `SchemaChangeDetails`: `resume_spans` in `ResumeSpanList`.

**Comment by postamar** [comment]
cc @awoods187 for visibility on this and the overall jobs redaction issue linked somewhere here.

**Comment by awoods187** [comment]
Thanks for the ping. @abhinavg6 or @amruss do you have more specific guidance on what needs to be redacted? We want to redact as little as possible while still safely complying with PCI.

**Comment by abhinavg6** [comment]
I don't have knowledge of what particular customer data is stored in the jobs payload, which could be visible to our employees. But if it helps, this was the high-level direction for the team that did the redaction in debug.zip:

- Let's redact everything in debug.zip including the logs that contain "customer data from user-defined tables", though excluding metadata (table / column / DB names etc.). If a query / statement contains customer data as literals, we need to redact those literals but not the whole query / statement. Same applies to other constructs / objects. More smarter sub-redaction we can do, better it is. But wherever that's not possible in v1, we'll need to redact the whole object for now.
- Additionally, we should redact any customer-provided secrets, like cloud identity credentials, passwords / tokens / certs used for connecting to non-cloud sinks etc. There can't be any reason for our employees to have access to those.
- With the above considerations, we will take conscious decisions to "not redact" specific things, if doing otherwise would generally impact supportability / debuggability. First and only known example of such a construct is "ranges". We don't know of any other construct like that yet. But this can evolve with time. It's just like following least privilege principle - we should first lock everything, and then gradually open up if needed for a valid reason. Though we won't prefer making such exceptions for things that only offer marginal benefit for supportability, and neither for things that are useful in only rare circumstances.

And when we talk about "ranges", we understood that those could contain:
- any primary key columns in SQL tables
- any column included in a secondary index, including computed indexes
- data partitioning keys (used by multi-region and manual sharding by customers)

Also ccing @adbrenn as he has to ensure that it's all kosher with the auditors.

**Comment by rafiss** [comment]
I came across this issue and wonder if we still need this open.

My understanding is that this issue just tracks any un-redaction we want to do in order to improve debuggability. It seems like we've been able to do support for the past ~year, so I think any additional changes in this area can just be made as needed, rather than keeping this open.
