### ISSUE TITLE
storage: performance regression in MVCCKeyCompare

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#89006]
**Describe the problem**

Currently, on the 22.2 release branch there is a ~45 performance regression in EncodeMVCCKey, relative to 22.1:

```
$ benchstat bench-22.1 bench-22.2
name               old time/op  new time/op  delta
MVCCKeyCompare-16  6.16ns ± 2%  8.96ns ± 2%  +45.48%  (p=0.000 n=8+9)
```

**To Reproduce**

```bash
$ ./dev bench ./pkg/storage --filter BenchmarkMVCCKeyCompare --count 10 -v --stream-output
```

Jira issue: CRDB-20075

Epic CRDB-2624

**Comment by nicktrav** [comment]
The regression comes from dbd892505643c47e15e7aacc2f2a4629ab091332, which added two normalization steps before the final byte slice comparison.

The slowdown is not unexpected, and was documented in the patch. However, a 40-50% regression may more than anticipated.

**Comment by nvanbenschoten** [comment]
It looks like we are measuring the [changes to the benchmark](https://github.com/cockroachdb/cockroach/commit/dbd892505643c47e15e7aacc2f2a4629ab091332#diff-8c73ba608e99d883eaaa8779aa0b2ee85808bcc4019d97eec9dc577fa35e1ce9), not changes to the code being benchmarked. That commit increased the size and complexity of the keys being encoded.

Here are some different data points:
| Branch      | Benchmark | Time/op |
| ----------- | ----------- | ---- |
| release-22.1      | Old       | 7.17ns ± 1% |
| release-22.1, with change to `EngineKeyCompare` backported      | Old       | 7.36ns ± 1% |
| release-22.1      | New       | 12.6ns ± 2% |
| release-22.1, with change to `EngineKeyCompare` backported      | New       | 12.3ns ± 1% |
| master   | Old        | 4.74ns ± 1% |
| master, with change to `EngineKeyCompare` reverted   | Old        | 4.93ns ± 1% |
| master   | New        | 9.37ns ± 2% |
| master, with change to `EngineKeyCompare` reverted   | New        | 9.00ns ± 4% |

So there seems to be a significant performance difference between release-22.1 and master (Go 1.19?) and also a significant performance difference between the old and new benchmarking code (larger keys), but no significant performance difference between the implementations of `EngineKeyCompare`. Here's the difference between the last two rows here:
```
name               old time/op  new time/op  delta
MVCCKeyCompare-10  9.00ns ± 4%  9.35ns ± 2%  +3.93%  (p=0.000 n=10+9)
```
That difference is in line with expectations.

The 2.5ns mentioned in the commit message was referring to the change in performance of the key equality function, not the key comparator function. So that was picked up by `BenchmarkMVCCKeyEqual`. That change in performance is also in line with expectations.

**Comment by nicktrav** [comment]
Thanks for digging into this!

> That difference is in line with expectations.

Closing.
