### ISSUE TITLE
ui: logs are displayed from oldest first as the default sort

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#8907]
This should, intuitively be reversed.

Also, we should be able to sort based on all columns.  This might warrant its own issue.

**Comment by bdarnell** [comment]
I'd rather have the display scroll down to the bottom than to reverse the logs.

**Comment by BramGruneir** [comment]
I can understand wanting it to look like a tail, But for long running
clusters, they're going to be very long.  I can't see that loading quickly
or efficiently.  Regardless, it should be easy enough to sort both ways.

**Comment by a-robinson** [comment]
This isn't a black-and-white issue that you can please everyone on. Google's old App Engine log viewer used the most-recent-first approach and got a good deal of negative feedback and confusion about it. There were also anecdotes from people who liked it, but it's worth noting that their current cloud log viewer has settled on ordering the logs from oldest-to-newest but starting with the focus at the bottom of the log, on the most recent entries (as @bdarnell suggested).

**Comment by spencerkimball** [comment]
Removing 1.0, assigning to @mrtracy, adding `ux-surprise`.

**Comment by tschottdorf** [comment]
How is this affected by UI authentication? Logs can contain sensitive information and especially during crashes we don't want to self-censor. Is it possible that we'll just remove the log endpoint completely, or do we have to revamp it so that it feeds off the log protobufs and prints only the format strings? But even that is brittle.

Either way, ISTM that we've stumbled over this too many times, and the log page as is is just plain useless since all you can see are the first few lines (right?). Maybe we should just hide it for now.

**Comment by tschottdorf** [comment]
Moving to 1.2 to do *something* because it's a waste of time to rediscover this issue every now and then. Plus it indicates that we actually would look at the logs in that way if it worked properly.

cc @cuongdo

**Comment by dianasaur323** [comment]
Hmmm.. this is odd behavior. We are doing some bug prioritization heading into 1.2, so we can put this one _relatively_ higher on the list.
