### ISSUE TITLE
stability: investigate stale ranges and potential anomalies

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8942]
Node4 of the rho cluster has a lot of ranges in the following states (shown here are 7 and 8):

![screen shot 2016-08-30 at 10 01 53 am](https://cloud.githubusercontent.com/assets/5076964/18092030/b728ef82-6e98-11e6-8925-a90f5acc4f43.png)

(https://104.196.164.29:8080/#/raft/ranges?_k=k8qesb)

For both of them, Node4 is behind (in ReplicaID), indicating that these Replicas _should_ be GC'ed but aren't.

For the second line, the node4 replica is dormant, which explains why it's just sitting there (the GC queue is not very proactive about this sort of thing).

The logs have _a lot_ of refused snapshots, which makes sense if old ranges aren't getting GC'ed. We should (if we don't already) queue ranges which cause a snapshot to be refused more aggressively. Range 7 is definitely blocking incoming snapshots:

> cockroach@cockroach-rho-4:~$ grep 'intersects existing range' logs/cockroach.stderr | grep 'intersects existing range store=4:4 range=7 ' | wc -l
> 17345

It's entirely possible that there are more problems here, but they would likely get drowned out by the noise, so the above is a good first step to capture any more persistent issues here.

For RangeID=7, the situation appears that the last replica has moved to Node3 a while ago (which doesn't have it, but this could again be due to blocked snapshots).

**Comment by bdarnell** [comment]
Range IDs got cut off in the screenshot; they are ranges 7 and 8. 

These are two different issues. The first line is #8111: the replica on node 4 was removed and subsequently re-added. Because it was re-added, it's a current member of the range and therefore won't be GC'd. Let's move this discussion to #8111. 

In the second line, the replica was not re-added and so it should be GC'd. This is probably just a case of the replica GC queue being slow. We don't have a good way to do a local shouldQueue for replica GC so it ends up being inefficient.
