### ISSUE TITLE
roachprod: validate host before running a command

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#89437]
**Describe the problem**

When running a roachprod command that doesn't synchronize the local cache, it's possible that the underlying cluster may have expired and the IPs associated with the VMs have been reused by a new cluster. In such cases, roachprod will happily run the commands on those hosts thinking it belongs to the old cluster.

This has happened in #88445, and debugging the aftermath of this type of error can be very puzzling and time consuming

**Desired behavior**

`roachprod` could validate the host before running a command. This could be done by checking hostnames, creation timestamps, or something else.

Jira issue: CRDB-20253

**Comment by srosenberg** [comment]
> `roachprod` could validate the host before running a command. This could be done by checking hostnames, creation timestamps, or something else.

One thing we need in support of better observability for roachtests, e.g., [1], is a marker to denote that a given roachprod cluster is under test (i.e., SUT). This can be done simply by leveraging (VM) instance metadata; e.g., `roachtest:foo` would denote that the cluster is currently used by roachtest `foo`. 

Piggybacking, `roachprod` CLI could simply refuse to interact with any cluster if the `roachtest` label is set. This wouldn't prevent API or a parallel test runner from inadvertently wiping a SUT. So, we could add another label, e.g., `attestation_token:uuid`. The general idea is that metadata lookups are fast whereas `roachprod list` is slow.

Also note, if/when we switch to private ips [2], the probability of a `roachprod` race approaches zero because unlike public ips, private ips are rarely reused, if ever.

[1] https://github.com/cockroachdb/roachperf/issues/48
[2] https://github.com/cockroachdb/cockroach/issues/77644

**Comment by srosenberg** [comment]
Similar to the issue in https://github.com/cockroachdb/cockroach/issues/63637

**Comment by srosenberg** [comment]
We had another instance of what I am now calling roachprod "cache incoherence" bug [1], [2]. While it's still surmised to be rare, we should escalate a fix. It doesn't just result in a flaky test; it wastes engineering time to debug what may appear to be an actual issue with SUT.

[1] https://github.com/cockroachdb/cockroach/issues/97100
[2] https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1676461075345639
