### ISSUE TITLE
stability: split-containing snapshot corrupts in-memory state

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8946]
via @bdarnell in #8111:

>
Well, I've found one possible problem: if a node falls behind and then applies a snapshot which carries it across a split command, the store's in-memory state will not get updated. processRangeDescriptorUpdateLocked is a noop in this case. If the new range descriptor has different bounds than the old ones, it needs to do the delete and re-insert dance in Store.SplitRange.
>
This would result in a replica that took up more "space" in the Store.replicasByKeys map than it actually used, and block snapshots to the range that was split off from it. It doesn't quite match the situation just seen on rho, though: there are no log messages that we are unable to apply a snapshot on range 7, and a range blocked by this bug would be unable to become initialized (range 7 is initialized on this node).

**Comment by petermattis** [comment]
Discussed in person with @arjunravinarayan. This is somewhat problematic to fix. `Replica.setDesc` will update `Replica.Desc().endKey` without doing a dance to remove and re-add the replica from `Store.mu.replicasByKey`. `replicasByKey` is a btree keyed by `Replica.Desc().endKey`. It isn't clear to me if we can remove the replica if we change `Replica.Desc().endKey` for a replica in the btree.

Perhaps we need a separate `Replica.endKey` field that is protected by `Store.mu`.

**Comment by petermattis** [comment]
Ok, just inspected the btree code and I think it is kosher to change the end key for a `Replica` while it is in `replicasByKey` because `btree.Item` only exposes a `Less` interface for comparison (i.e. it doesn't know about the keys themselves). 

To reiterate the scenario: a range `[a,c)` splits into ranges `[a,b)` and `[b,c)`. One of the nodes containing `[a,c)` does not get the memo about the split and instead receives a snapshot updating its descriptor to `[a,b)`. I claim this should be perfectly ok given the btree implementation since we disallow overlapping replicas in the `replicasByKey` btree. But, there might be a small problem here. The node which receives the snapshot might have previously processed the right side of the split. That is, the node has replica covering `[a,c)` and then receives the right hand side of the split  (via a snapshot) and updates the `replicasByKey` map (which is indexed by end key) to containing `[b,c)`. This would remove the `[a,c)` entry. When we later receive the snapshot updating the left hand side of the split we never add it to the `replicasByKey` map. 

It's getting late. Am I missing anything here? @bdarnell?

**Comment by bdarnell** [comment]
A store holding range `[a,c)` cannot apply a snapshot for `[b,c)`, thanks to the `canApplySnapshotLocked` check. The right-hand range is stalled until the pre-split range either catches up to the split or is garbage-collected. 

OK, so it sounds like this was a false alarm, although we should add comments to SplitRange and/or replicasByKey to make it clear that we're relying on this property.

**Comment by petermattis** [comment]
Good point about the right-hand side being stalled. @arjunravinarayan I think it would be good to verify that `replicasByKey` works as I describe and enshrine that required behavior in a test. I'm thinking of something simple that uses a `*btree.Tree`, inserts a few manually constructed `Replicas` and then changes the descriptor for one of them similar to how it would change after a split.

**Comment by petermattis** [comment]
The delete and reinsert dance in `Store.SplitRange` might not be necessary. This:

```
	if s.mu.replicasByKey.Delete(origRng) == nil {
		return errors.Errorf("couldn't find range %s in replicasByKey btree", origRng)
	}

	copyDesc := *origDesc
	copyDesc.EndKey = append([]byte(nil), newDesc.StartKey...)
	origRng.setDescWithoutProcessUpdate(&copyDesc)

	if s.mu.replicasByKey.ReplaceOrInsert(origRng) != nil {
		return errors.Errorf("couldn't insert range %v in replicasByKey btree", origRng)
	}
```

Could become:

```
	copyDesc := *origDesc
	copyDesc.EndKey = append([]byte(nil), newDesc.StartKey...)
	origRng.setDescWithoutProcessUpdate(&copyDesc)
```

Along with some commentary explaining why that is kosher.

**Comment by arjunravinarayan** [comment]
Yes, I think the test-first approach is probably best. On it.

Arjun Narayan
