### ISSUE TITLE
 cli: last node fails to drain

### ISSUE THREAD

**Issue by MattMcmullanQumulo** [cockroachdb/cockroach#89872]
I'm spinning the wheels of CockroachDB, and I've created a cluster with three nodes locally. To gracefully stop the cluster, I run the following command for each node.
`cockroach node drain --insecure --self --host localhost:{port} --drain-wait 10s`

It works for the first two, but the third fails to actually stop the server.

It looks like a similar bug existed in the past, but it appears to be broken again.
https://github.com/cockroachdb/cockroach/issues/48492

I'm running...

> Build Tag:        v22.1.8
> Build Time:       2022/09/29 14:21:51
> Distribution:     CCL
> Platform:         linux amd64 (x86_64-pc-linux-gnu)
> Go Version:       go1.17.11
> C Compiler:       gcc 6.5.0
> Build Commit ID:  bdcab67f778617515597f1012f37f14f622b15a0
> Build Type:       release

**Comment by knz** [comment]
Hi Matt,

so there are two parts in your question: 
1) the behavior for the last node is *different* than for the first two
2) the command fails to *stop* the node

I'll start with point 2. In case this wasn't clear, `cockroach node drain` merely *prepares* a node for shutdown.  It is not intended to actually stop the node. 

Also, since v22.1, our recommended way to operate CockroachDB is to use a service/process manager, and rely on that to shut down the process (typically by sending a SIGTERM signal, waiting sufficiently long, then sending SIGKILL).  Note that sending SIGTERM to the process internally implies the same logic as `cockroach node drain`, which means that running the command manually is not needed if you are using a service/process manager.

Then moving to point 1. The behavior works as intended. The `cockroach node drain` command is there to prepare a node for graceful shutdown **while preserving fault tolerance**. It is specified to only complete *if the remainder of the cluster is healthy and still able to process queries*.   Generally, with a 3-node cluster, even attempting to drain the 2nd node (after the 1st node has drained successfully) would fail, because CockroachDB expects a majority of nodes (2/3) to remain up. From an operational perspective, `cockroach node drain` was designed for an always-on CockroachDB, where nodes are only restarted one by one for example during a rolling upgrade.

We do not currently offer a command / facility for a graceful shutdown of an entire cluster at one. This functionality is tracked by the separate issue #58417.

Let us know if you have further questions or comments.
