### ISSUE TITLE
sql/opt: excessive allocations in histogram interactions

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#89982]
**Is your feature request related to a problem? Please describe.**
Some 45+% of allocated objects in YCSB/E come from histogram interactions. See 
<img width="1495" alt="Screen Shot 2022-10-14 at 11 06 01 AM" src="https://user-images.githubusercontent.com/1839234/195880132-f6746e9e-1689-4538-afe8-e8531e907fe7.png">

[profile (38).pb.gz](https://github.com/cockroachdb/cockroach/files/9787614/profile.38.pb.gz)

Jira issue: CRDB-20529

**Comment by mgartner** [comment]
For the `maxDistinctValuesCount` case, it doesn't look like there is any reason we need to allocate a datum here: https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/props/histogram.go#L147

We can use the previous upper bound and subtract one from the distinct values. It'll be a bit more complicated than that because we'll need to determine if there is a value after the last one or not.

Also we iterate and allocate over all the buckets, even if the type of the column isn't `Int` or `Date`, but `maxDistinctValuesInRange` only works for `Int` or `Date`. So there's a lot of unnecessary work happening.

Reducing the allocations under `histogramIter.next` seems a bit more difficult...

**Comment by ajwerner** [comment]
I think we can make the histogram filtering a heck of a lot better with some pooled buffers. Consider that the upper and lower bounds don't outlive the `filter` method. If every time we constructed a key, we did it into some buffer that we could reset when overwriting, and we pooled those buffers it seems like we could avoid some of these allocations. 

There's some other histogram allocations which seem a bit harder to pool, but maybe we can amortize them away.
