### ISSUE TITLE
stability: intestigate memory profiling/stats discrepancy

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9034]
heap profiles and memory allocator stats often diverge by 10-30%, meaning that a sizable chunk of the memory allocated and in use (as opposed to idle) is not seen in heap profiles.
eg: see sample heap profiles and memstats log in https://github.com/cockroachdb/cockroach/issues/8594

We should figure out what's going on there. A few options:
* I'm reporting bad memstats numbers in runtime.go
* heap sampling is hiding things from us. that's fair, but we should figure out if those are representative samples
* other?

**Comment by mberhault** [comment]
CC @cockroachdb/stability

**Comment by petermattis** [comment]
It might be worth experimenting with `runtime.MemProfileRate`. This can be set using the `GODEBUG` env variable. Does the discrepancy go away if you run with `GODEBUG= memprofilerate=1`?

**Comment by cuongdo** [comment]
Setting `GODEBUG=memprofilerate=1` makes `pprof` and memstats much more consistent. The two in-use memory stats are never exactly identical, because we always have goroutines allocating memory. However, with `GODEBUG=memprofilerate=1`, the `pprof` in-use memory sometimes exceeds the in-use figure in memstats -- this never happened without the environment variable.

So, I'm confident the discrepancy has been sufficiently explained. For further reference, see:

https://golang.org/pkg/runtime/#MemProfileRate
