### ISSUE TITLE
copy: copy fails with transaction error

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#90656]
ERROR:
restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT REASON NEW LEASE PREVENTS TXN):
"unnamed" meta=(id=62b88940 key=___REDACTED___ pri=0.00316934 epo=0 ts=1666717645.181476639,1 min=1666717645.1797676790 seq=101} lock=true stat=PENDING rts=1666717645.181476639,1 wto=false gul=1666717645.679767679,0
HINT: See: https://www.cockroachlabs.com/docs/dev/transaction-retry-error-reference.html
abort_reason_new lease prevents_txn

Open questions:

- How does this happen?  
- Can we fix it with a retry?   
- Does it happen in 22.2?

Jira issue: CRDB-20873

Epic CRDB-34178

gz#16766

gz#17451

**Comment by cucaroach** [comment]
Assigning to myself just to triage...

**Comment by cucaroach** [comment]
Some background here, in 22.2 COPY commands were split into 100 row chunks which each got their own transaction, in 22.2 COPY is atomic so it all happens in one big transaction.  If errors like this can happen we might want to retry automatically, the concern is this kind of error might become more common with an atomic COPY so we might want try to work out a fix and get ahead of that.

**Comment by kvoli** [comment]
> 22.2 COPY commands were split into 100 row chunks

Do you mean 22.1?

> How does this happen?

I'm not certain on this one. The lease transfer acquires latches over the keyspace for each range. However the specifics of whether a large copy in a txn will be forced to abort or could just be bumped isn't clear to me.


cc @arulajmani do you know why this is the case?

**Comment by cucaroach** [comment]
> Do you mean 22.1?

Yes sorry, typo

**Comment by otan** [comment]
If it helps in any way, these COPY chunks contain large JSONB blobs (i think up to 10MB)

**Comment by arulajmani** [comment]
> How does this happen?

This happens because we're unable to create the transaction record for the COPY statement because of a lease transfer. The transaction record is created on the first range the statement writes to. This particular error indicates that the creation of the transaction record is failing because the range it is trying to create a transaction record on had a lease change, and the new lease started after the transaction's start timestamp. 

> Can we fix it with a retry?

Yeah, we shouldn't see this if we retry the transaction. If we're seeing this repeatedly, it might be worth digging into what is causing these lease transfers. 

> Does it happen in 22.2?

Yeah, I don't think this stuff has changed at all recently.

**Comment by otan** [comment]
> If we're seeing this repeatedly, it might be worth digging into what is causing these lease transfers.

This seems to happen fairly consistently with a certain user we have, however I'm unable to reproduce this with a 3-node roachprod cluster on v22.1.10 trying these big COPYs like they are. Maybe it's worth diving in.

Posterity for trying to reproduce the issue: https://github.com/otan-cockroach/big-copy/blob/main/copy.go

**Comment by otan** [comment]
ooh actually i was inserting empty json blobs, i've fixed the script above slightly, now copy takes forever!

**Comment by cucaroach** [comment]
I have the pgdump now, will try my hand at reproducing...

**Comment by otan** [comment]
i can hit this reliably in v22.2
```
error with result plan: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE - missing intent on: /Table/116/4/-9182806513006833952/0): "unnamed" meta={id=9dd74a0d key=/Table/116/4/-9183063663728498211/0 pri=0.02945731 epo=0 ts=1673403903.445208120,2 min=1673403898.070322218,0 seq=90512} lock=true stat=PENDING rts=1673403903.445208120,2 wto=false gul=1673403898.570322218,0
```

**Comment by erikgrinaker** [comment]
>`ABORT_REASON_NEW_LEASE_PREVENTS_TXN`

As noted above, this happens when the transaction record creation races with a lease transfer of the range anchoring the txn record. I suppose it's possible that this could also happen in other cases, e.g. where the txn record is removed because of a txn abort or some such, but that's the primary cause. If this happens very frequently, consider disabling e.g. lease-based rebalancing or some such and see if that helps.

> `RETRY_ASYNC_WRITE_FAILURE`

Either an async intent write failed, or someone aborted the transaction and removed the intent.

> `ABORT_REASON_CLIENT_REJECT `

A contending transaction aborted this transaction.

> a transaction has hit the intent tracking limit (kv.transaction.max_intents_bytes); is it a bulk operation?

Indicates that we're writing a lot of data in the transaction, so we're switching from point intent resolution to ranged intent resolution. Could be pretty bad prior to 21.2, when we implemented separated intents, but shouldn't be a huge problem anymore.

> in 22.2 COPY is atomic so it all happens in one big transaction

Large, long-running transactions are problematic, and we regularly discourage our users from using them because of the issues that come with them, instead recommending they break up their writes into batches (like COPY did in 22.1).

The longer the transaction runs, and the larger the number of keys it touches, the more likely it is to run into conflicts with other transactions. From what I see here, it seems likely that the transaction is getting aborted by a different transaction that it contends with. This could be stuff like backups, which will start pushing the long-running transaction, possibly aborting it.

I see from the above that this transaction is running with a fairly low priority (e.g. `pri=0.02945731`). You can consider running it as a high-priority transaction, but note that this can then end up blocking other transactions until it completes (so it may e.g. prevent backups).

**Comment by erikgrinaker** [comment]
We've found some clues over in https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1673441473898339. Something seems off about pipelined writes. The error is always an `RETRY_ASYNC_WRITE_FAILURE`, always happening immediately after hitting `kv.transaction.max_intents_bytes`. Disabling `kv.transaction.write_pipelining_enabled` fixes the problem.

Not sure if this is related to the original problem in this issue, but something's up here.

**Comment by otan** [comment]
There's no temporary table here. This is a direct COPY FROM STDIN to the original table.

**Comment by otan** [comment]
There may be multiple issues at play here, but i can also semi-reliably reproduce the first error message in the ticket.

Using https://github.com/otan-cockroach/big-copy/blob/main/copy.go without changing any cluster settings in a 3 node cluster results in ProtoRefresh errors too fairly consistently, with different results:

```
beginning copy iteration 425
panic: failed to copy: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE - missing intent on: /Table/111/1/41400010001/0): "unnamed" meta={id=ecc1965f key=/Table/111/1/41400000001/0 pri=0.01550750 epo=0 ts=1673489780.173787763,0 min=1673489780.173787763,0 seq=10001} lock=true stat=PENDING rts=1673489780.173787763,0 wto=false gul=1673489780.673787763,0 (SQLSTATE 40001)

goroutine 1 [running]:
main.main()
	/Users/otan/go/src/github.com/otan-cockroach/big-copy/copy.go:52 +0x798
```

```
beginning copy iteration 1054
panic: failed to copy: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_NEW_LEASE_PREVENTS_TXN): "unnamed" meta={id=96a1d198 key=/Table/114/1/104300000001/0 pri=0.04642513 epo=0 ts=1673491134.391573745,1 min=1673491133.911809425,0 seq=10001} lock=true stat=PENDING rts=1673491134.391573745,1 wto=false gul=1673491134.411809425,0 (SQLSTATE 40001)

goroutine 1 [running]:
main.main()
	/Users/otan/go/src/github.com/otan-cockroach/big-copy/copy.go:60 +0x888
```

**Comment by tbg** [comment]
I just tried `bigcopy` against a local 3x cluster (on current master). Didn't manage to repro anything.

I also polished it a bit - it can now produce a giant COPY without holding everything in-mem first. There's a `run.sh` to fire it up incl creating the local cluster for your convenience...

https://github.com/cockroachdb/cockroach/pull/95283

I didn't manage to reproduce anything. I even lowered the range size (to get some more splits) and tried a contending full table scan, but the thing just chugged along until I killed it ~10 minutes later. The best problem I've been able to spot is that we have abandoned the massive txn so the table is essentially blocked until my `COUNT(*)` has cleaned up a bazillion intents, but that's not an issue we care about for the purposes of this thread.

I'm going to give it a quick attempt on GCE as well.

**Comment by otan** [comment]
>  Btw, I'm noticing we have copyfrom roachtests. Do these not exhibit these issues?

not aware of these.

> I just tried bigcopy against a local 3x cluster (on current master). Didn't manage to repro anything.

it only worked for me if i (a) worked on GCE and (b) uploaded the bigcopy binary to one of the GCE workers (`GOOS=linux GOARCH=amd64 go build -v . && roachprod put $CLUSTER:2 big-copy`). it takes a while to repro but it's there. also try increasing the `maxRow` to 100k, which today i found out DMS does.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/blob/bef7580a969b796e9e57f742e3d47d25e1cf40de/pkg/cmd/roachtest/tests/copyfrom.go
