### ISSUE TITLE
acceptance: cross builds don't run in git worktrees

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#90663]
In a [git worktree](https://git-scm.com/docs/git-worktree):
```
./dev acceptance -f TestDockerCLI
...
[0 / 31] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 128
fatal: not a git repository: /home/andrei/src/github.com/cockroachdb/cockroach/.git/worktrees/cockroach
```

Jira issue: CRDB-20876
Epic CRDB-17171

**Comment by cucaroach** [comment]
For what its worth this also happens when doing --cross builds, so the problem is related to docker builds but build/bazelutil/stamp.sh works fine in docker so there's more to it than that.   Maybe there's some bleeding of outside docker paths to inside docker where they don't make sense.  Actually since worktrees use fully qualified paths in the .git/worktrees/<name>/gitdir file that's probably the problem.   Maybe we need the docker filesystem structure to mirror the outside docker filesystem or we need to make worktrees relative?   First I gotta figure out how to get stamp.sh to fail like that, still something missing...

**Comment by cucaroach** [comment]
Okay repro steps:

```
$ ./dev builder
$ build/bazelutil/stamp.sh
```
