### ISSUE TITLE
ttl: consider either disabling or throttling splits caused by DELETEs from the job

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#90713]
**Is your feature request related to a problem? Please describe.**
See this internal Slack post: https://cockroachlabs.slack.com/archives/C028YAH6Y3V/p1666383531536799?thread_ts=1665959426.411949&cid=C028YAH6Y3V

The ttljob was run on a large table. We observed the following:
> Seems like there was an initial impact on latency when the job first ran due to load-based splitting. I don’t think you’d have seen that if you had a lot more data.
> 
> The deal is that the TTL job sends so many requests that it leads to a flurry of splits and then merges which are disruptive.

There is another goal of making splits have less of an adverse impact, but separately from that, we could make a change to the ttljob specifically.

> Certainly we need to do something. We could exempt the load from the splitter, but I’m not sure that that’s right. More generally, I think we ought to be much more cautious about splitting so rapidly. We also probably ought to do work to make splits less disruptive.
> 
> In general I don’t think it’s bad that we split on this traffic per se, it’s bad that the splits harm latency so much
> 
> I think some of the problem here is that way we deal with fsyncs and the commit pipeline. These splits are leading to transfers and snapshots which are using a bunch of disk bandwidth, and, sadly, leading to huge spikes in the fsync latency because when we sync we sync the whole filesystem. There’s some work among kv and storage folks to do something about that too.

Epic CRDB-18322

Jira issue: CRDB-20904

**Comment by ajwerner** [comment]
I don't know if this is something we should do. We turned off splitting and the latency impacts weren't totally mitigated.

**Comment by ajwerner** [comment]
I think that it points at a different problem. The load-based splitter is not very thoughful in how it measures rates. It doesn't do smoothing. In the workload which motivated this issue, the sustained load didn't hit the split threshold. The problem is that the load is bursty. It issues deletes over the index it is scanning in the order it scans. This means ranges get a burst of traffic and then none. The splitter should be slightly more patient or something. I think spending any time on exempting these deletes is wasted effort.

**Comment by rafiss** [comment]
I heard that @kvoli might be doing some work here that will improve the load-based splitter so that the TTL job doesn't encounter an issue here. Is that true + is there an issue for it?

**Comment by kvoli** [comment]
@KaiSun314 is working on https://github.com/cockroachdb/cockroach/issues/90574 a somewhat separate issue. 

We are looking at this though and it does strengthen the case for also doing some work on this half of the splitter.

Kai is working on a doc that addresses some issues on this half as well as the issue above. 

A quick and dirty solution would be to directly reference the actual QPS metric (see `replica_load.go`) when deciding to start recording for splits, rather than trying to maintain the "rate" in a single var, which is moreso used for tracking a maximum.
