### ISSUE TITLE
the performance of hash sharded index insert not good

### ISSUE THREAD

**Issue by chaiyi123** [cockroachdb/cockroach#90749]
In most cases, the insertion performance of hash index is not as good as that of normal index

Start a three node cluster in non security mode

1.create table x(a int,b int,c int);
   create index on x(a,b);
2.create table y(a int,b int,c int);
   create index on y(a,b)using hash with bucket_count = 8;

insert into x select generate_series(1,3000000),generate_series(1,3000000),generate_series(1,3000000);
insert into y select generate_series(1,3000000),generate_series(1,3000000),generate_series(1,3000000);

Insert auto increment data into two tables,The execution time of Table y is longer than that of Table x.

What causes this?

Jira issue: CRDB-20922

**Comment by michae2** [comment]
Hi @chaiyi123. Using a hash-sharded index is a tradeoff. In light workloads, most operations on hash-sharded indexes will have slightly higher latency than the same operation on a normal index, because using a hash-sharded index requires writing to or reading from more ranges / more nodes than a normal index. In heavy workloads with a sequential bias, operations on hash-sharded indexes will have lower latency than the same operation on a normal index, because the heavy load on one end of the index will be spread among multiple ranges / nodes instead of concentrated on one range / node.

In your example, ignoring the primary index and just considering the secondary index, inserting 3m rows into x will only require writing to 1 range. Inserting 3m rows into y, on the other hand, will require writing to (up to) 8 ranges. Assuming nothing else is happening on the cluster, this will take a little longer. Assuming a lot is happening on the cluster, and the total load on that 1 range of x is more than a single node can handle, writing to the 8 ranges of y should be faster.

(Incidentally your specific example prompted me to file https://github.com/cockroachdb/cockroach/issues/91109 but I don't think this changes anything about this explanation.)

**Comment by michae2** [comment]
I'm glad to hear that, @chaiyi123. For now I'll close this issue. Please re-open it if you want to discuss further or you have more examples you want to bring up.
