### ISSUE TITLE
reports: range not covered by spanconfig reported as under-replicated

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#91239]
See https://github.com/cockroachlabs/support/issues/1858.

A range not referenced by the zone configs (result of merging a number of ranges belonging to tables that have been dropped) was using 3x replication (spanconfig default fallback) as opposed to 5x which is what the default zone config specified.

The replication reports reported this range as under-replicated, which is "not correct" (KV considers 3x the correct replication factor since that's what the spanconfig reflects). See also https://github.com/cockroachdb/cockroach/issues/91238, which inquires whether the 3x default is appropriate here.

cc @irfansharif 

Jira issue: CRDB-21169

**Comment by irfansharif** [comment]
The code we're going to be using to generate replication reports in 23.1+ onwards is newly written to be multi-tenant aware, and more coupled to span configs: https://github.com/cockroachdb/cockroach/issues/89987. I mention it because of the following snippet:

https://github.com/cockroachdb/cockroach/blob/05cbd97aa74c89bd99c7ed0196fc597622c97156/pkg/spanconfig/spanconfigreporter/reporter.go#L130-L133

What it's doing is considering the "span config" state as the authoritative state for what configuration to apply for a given range. So there's a well-defined config for "any range not covered by span configs" -- it's a hardcoded[^1] config (modulo [^2] for 23.1, and [^3][^4] 22.2 and 22.1 respectively). So these ranges will just not appear as under-replicated unless KV actually sees the need to upreplicate them, which was not true in the internal support case linked above. https://github.com/cockroachdb/cockroach/issues/91238 (also linked above) tracks the piece of work to make sure that these "unaddressed" ranges actually use the tenant's `RANGE DEFAULT` instead of this hardcoded fallback. I'm going to close this issue as completed because of the new replication report code, and the fact that we're not going to fix this behaviour for the old experimental, and now soon to be deprecated + removed reporting code. We've already worked on a few workarounds linked below. 

[^1]: https://github.com/cockroachdb/cockroach/blob/5931f033fe93a98f0b8af18bba39cffd3f4e2791/pkg/server/server.go#L594-L613

[^2]: https://github.com/cockroachdb/cockroach/pull/92466

[^3]: https://github.com/cockroachdb/cockroach/pull/93092

[^4]: https://github.com/cockroachdb/cockroach/pull/93093
