### ISSUE TITLE
cluster-ui: on CC, explain plan for active stmt is always "Not Available"

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#91247]
On CC, the explain plan always shows as "Not Available" for an active stmt on the details page.
Investigate and fix why this is since this feature works on local builds and in the stmt insights page, which uses the same mechanism to get the plan.

**Environment:**

CockroachDB version [22.2.0-beta.5]

Jira issue: CRDB-21175

**Comment by maryliag** [comment]
Seems like is not trying to get the plan because the plan gist of the statement object is empty, so it's not a problem on decoding the gist, is a problem on getting the gist in the first place

<img width="732" alt="Screen Shot 2022-11-04 at 4 44 56 PM" src="https://user-images.githubusercontent.com/1017486/200071690-6819779d-b4c5-45fd-8b05-4aeb9cdd1930.png">

**Comment by kevin-v-ngo** [comment]
Closing per triage - old CRDB version did not have the gist
