### ISSUE TITLE
storage: get rid of Store.uninitRaftMu

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9128]
After #8941 and #9088 land, we'll be in position to remove `Store.uninitRaftMu`. Instead of creating the right-hand side replica in `splitTriggerPostCommit`, we would create the `*Replica` in `Replica.splitTrigger`. This creation would need to install the `*Replica` in `Store.mu.replicas` and grab `Replica.raftMu`. The open question is figuring out what to do if the split fails to commit. At a minimum, we'd have to unlock this replica (we have to do that on the success case as well). And note that we want to defer the unlocking until after the commit and after the commit triggers have run.

**Comment by petermattis** [comment]
@tschottdorf I started looking at this last night and need some guidance. Both `Replica.{split,merge}Trigger` need to `raftLock` the right hand side range and to hold onto that lock until the post commit trigger is finished. That seems relatively straightforward, we can add a field to `postCommit{Split,Merge}`. But the error handling seemed fragile. In case of any errors in `{split,merge}Trigger` I need to unlock the right-hand side replica. And for splits I think I need to call `Store.RemoveReplica` as well. The fragile part is that we don't seem to always propagate `PostCommitTrigger` back up the call stack in case of errors. Sometimes yes, sometimes now. Thoughts?

Cc @cockroachdb/stability

**Comment by tschottdorf** [comment]
I think realistically the current split triggers must never fail (they're currently allowed to, but really shouldn't except at the beginning). We could let them fail and return a non-nil `*PostCommitTrigger` along with the error to clean up - but also consider that with proposer-eval'ed kv, we want to trim down on post-Raft logic, which to me would suggest keeping it as simple as possible for now (i.e. a splitTrigger fails == log.Fatal).

**Comment by bdarnell** [comment]
You can create the replica in the "uninitialized" state (i.e. a nearly-empty `RangeDescriptor` except for the `RangeID`), just as if it was created in response to a raft message (in `getOrCreateReplicaLocked`), and then you don't have to call `RemoveReplica` on error. You still need to unlock its `raftMu`, though.

It may be simpler to move this up a few levels instead of using the triggers. In `Replica.processRaftCommand`, we could peek into the request to see if it contains a split. If it does, we lock the RHS replica, creating it if necessary, before calling into `applyRaftCommand`. Then we can unlock the RHS at the end of `processRaftCommand`, no matter how `applyRaftCommand` finished. It's a little dirty to peek into the command here, but more foolproof than trying to connect from `splitTrigger` to `splitTriggerPostCommit` reliably.

**Comment by petermattis** [comment]
@bdarnell I like that idea much better. I started trying to propagate the locked Replica back up from `splitTrigger` and it was both a mess and fragile.
