### ISSUE TITLE
sql: support INTERLEAVED on secondary indexes in a CREATE TABLE statement

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#9148]
They work just fine if you create the table and then immediately use a CREATE INDEX to add the index. It'd still be nice to be able to do them in the same statement.

**Comment by a6802739** [comment]
@paperstreet , I have time to fix this now, if you could give me some idea or reference, I would appreciate it.

**Comment by paperstreet** [comment]
This is replacing https://github.com/cockroachdb/cockroach/blob/91096a0b6c98bf5ec9af4cc1f49bbd3ee18a4c3b/sql/create.go#L922 and https://github.com/cockroachdb/cockroach/blob/91096a0b6c98bf5ec9af4cc1f49bbd3ee18a4c3b/sql/create.go#L943 with calls to addInterleave.

Unfortunately, it requires that addInterleave be made into a function instead of a method on planner. To do this, you'll have to plumb down the session database name and a schemaAccessor to it. You could use https://github.com/paperstreet/cockroach/tree/interleaved_createtable as a starting point, but there's a LOT of cleanup left there

**Comment by a6802739** [comment]
ok, I can try it.

**Comment by jordanlewis** [comment]
Closing this as wont fix.
