### ISSUE TITLE
sql: improve handling of conflict error in SPLIT AT

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9157]
The `AdminSplit` that happens as part of a `ALTER TALE .. SPLIT AT` statement can error with "conflict updating range descriptors". One known situation where it happens occasionally is when we try to split soon after table creation.
#9125 adds a retry loop. but it would be ideal if we could prevent the error in the first place (e.g. by somehow queuing the splits).

**Comment by bdarnell** [comment]
Splits can also conflict with rebalances, so this queue would need to cover all range operations, not just splits. 

Rather than introducing a specialized queue, we should consider whether there's a more general solution for making transaction retries event-driven (in common situations) instead of just being retried in a time-based loop. We already have retries on the Store for WriteIntentErrors that can be immediately resolved. We may want to queue up certain error responses for a time at the store level until the conflicting transaction has resolved.

**Comment by jordanlewis** [comment]
This error doesn't seem to exist in the code anymore, so I'm closing it.
