### ISSUE TITLE
security: Non-environment configuration of secrets

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9162]
#9136 pointed out that we currently use environment variables for secret tokens like the lightstep token. (and if this is to be a fully-supported feature rather than just an experiment, it should be settable on the command line too so it doesn't have the silent-failure problem of environment variables. The command-line is even less suitable for secrets). Instead of putting the token directly in the environment, we should consider putting the token in a file and the filename in the environment. We already require that deployments have the capability to manage files containing secrets (for TLS certs), so this is better than requiring that they also be able to configure environment variables with similar security.

**Comment by spencerkimball** [comment]
@bdarnell is this important enough for 1.0? Looks like we're still using environment variables for the lightstep token. But that also appears to be the only env var secret we're specifying. I'm removing the 1.0 milestone because this doesn't feel like a pressing problem. If you want to add it back, please assign someone / provide a more concrete suggestion for work to be done.

**Comment by dt** [comment]
A Settings table might be one way to manage tokens/keys where we want them
per-cluster rather than per-node (e.g. in snowball tracing).

**Comment by bdarnell** [comment]
Yeah, since it's just lightstep it's not critical for 1.0.

**Comment by bdarnell** [comment]
This has been done.
