### ISSUE TITLE
insights bug: transaction overview page duplicate insights

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#91914]
This was reproduced with a clean branch. The insight "high contention" appears twice when it should only be there once.

<img width="1639" alt="Screen Shot 2022-11-15 at 10 33 52 AM" src="https://user-images.githubusercontent.com/8868107/201961941-4dc473f3-6caf-446d-97ae-f62df6713660.png">

Jira issue: CRDB-21483

**Comment by xinhaoz** [comment]
@j82w That's expected right now since there are no execution details available for txns with high contention as their insight. One option is to just not show these fields when they're not available.

**Comment by j82w** [comment]
@xinhaoz should it is say `no sample` like other pages when the info is not available? Is it not possible to calculate by aggregating the insight stmt information?

**Comment by xinhaoz** [comment]
@j82w `no sample` would also work here. We can't aggregate from the statements because there's no guarantee we record insights for executions that appear in the contention table. From my own testing I haven't seen it recorded, as the only time it would appear is if a single stmt in the txn had an execution of over 100ms, but for contention we take the total contention time as the number to compare with the threshold. Since the 2 dsata sources aren't very in sync with which transaction executions they have, for now we just opt to show the contention insight if we have results from both tables for an execution.

**Comment by j82w** [comment]
@maryliag should it say 'N/A' when there is no info or 'no sample' in the top summary card?

**Comment by maryliag** [comment]
if the reason is because we don't have the value (because we didn't collected on trace for example) use `no sample`, if is because the case wouldn't have no matter what, than you can use `N/A`

**Comment by xinhaoz** [comment]
Sounds good, I'll update to `no samples` in my bug fix PR
