### ISSUE TITLE
kvserver: factor out log storage to a package

### ISSUE THREAD

**Issue by pavelkalinnikov** [cockroachdb/cockroach#91979]
Currently the Raft log storage is tightly coupled with `Replica` and log entry application. See [Replica.handleRaftReadyRaftMuLocked](https://github.com/cockroachdb/cockroach/blob/fd486e39a3929aace46e030fc813caf5abe69300/pkg/kv/kvserver/replica_raft.go#L681).

To pave the way towards separating Raft log storage from the rest of the storage, we need to first untangle the current log storage logic into separate types/packages.

This includes write and read paths, notably:
- reading [entries](https://github.com/cockroachdb/cockroach/blob/e8d03667b95157a924d4be0ac606e58a42e87c80/pkg/kv/kvserver/replica_raftstorage.go#L122-L130), term, etc
- appending entries

Eventually, we will arrive at a subset of `raft.Storage`, and will be able to promote a [split](https://github.com/etcd-io/etcd/blob/bba8e6259cb8ad9d8074224ce88e66987a57217e/raft/storage.go#L47) at the `etcd/raft` level too, after better understanding what it would include.

Epic: CRDB-220

Jira issue: CRDB-21505

**Comment by tbg** [comment]
@pavelkalinnikov remind me what we are still missing here? I don't think we want to try splitting `raft.Storage` this time around, and I *think* we've done what we need to do to enable CRDB-220. Smaller refactors aside, the main thing that conceptually bugs me is that because the raft config is represented by the range descriptor, we'll have the config in the state machine engine - and even worse, you can't discover what the config is unless you have the start key: https://github.com/cockroachdb/cockroach/blob/3d8819a85e9b1c668031e7ad294acae9944730bc/pkg/kv/kvserver/replica_raftstorage.go#L81-L90

But that's outside of the scope of this issue anyway.

**Comment by pavelkalinnikov** [comment]
There are a few unit tests to be simplified and moved to `logstore` package as well, and some post-move refactoring/hiding that still needs to happen (e.g. the sideloaded storage can be fully hidden). This issue can be closed though.

Yeah, having bits and bobs stored across log/state storages seems like a bigger and separate issue.
