### ISSUE TITLE
storage: Limit retries of raft snapshots

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9226]
Raft appears to be retrying snapshots too aggressively - I thought it was only supposed to send at most one snapshot per MsgAppResp, but I can't find the code that does this any more, and in #8594 we saw it happening during an asymmetric partition. Once raft has sent a snapshot, it shouldn't try to send another until it has a new MsgAppResp.

**Comment by petermattis** [comment]
Is this happening because we call `RawNode.ReportSnapshot` when the snapshot is sent as opposed to when it has been applied on the remote side? It looks to me like raft will only send a snapshot when the recipient is not `ProgressStateSnapshot`. And the recipient stays in that state (more or less) until `ReportSnapshot` is called.

**Comment by bdarnell** [comment]
That may be it, in which case this will be solved by streaming snapshots. But the way I *thought* this worked is that after ReportSnapshot, the leader will send an MsgApp (for the post-snapshot entries) and only after it gets an MsgAppResp would it retry the snapshot.

**Comment by petermattis** [comment]
We now only call `ReportSnapshot` after the snapshot has been sent and applied.
