### ISSUE TITLE
gossip: revisit DefaultGossipStoresInterval setting

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9242]
#9230 changed `DefaultGossipStoresInterval` from 1m to 5s. The original motivation of the 1m interval was not to overload the network with gossip traffic and also based on the observation that the used space on a store doesn't change quickly. However, rebalancing is currently based on range count, not disk usage. And range counts can change significantly over the course of a minute. Additionally, the concern about gossip traffic is premature for the current cluster sizes (10-100 machines). An encoded `StoreDescriptor` is ~70 bytes. Having each store gossip its descriptor once every 5 seconds is inconsequential in comparison to other periodic traffic such as Raft heartbeats.

Regardless, we should reexamine this setting as cluster sizes grow and as we tweak the rebalancing heuristics.

Cc @cockroachdb/stability

**Comment by spencerkimball** [comment]
Instead of busily gossiping store descriptors, I propose we instead change the trigger to evaluate whether the descriptor has changed "meaningfully" since the last gossip. For now, this would mean we gossip when the range count changes from the formerly gossiped value by more than a threshold percentage.
