### ISSUE TITLE
Secondary tenants should not be started with an EMERGENCY_BALLAST file

### ISSUE THREAD

**Issue by alyshanjahani-crl** [cockroachdb/cockroach#92500]
**Describe the problem**

In CRDB versions < 23.1, secondary tenants did not have an `/auxiliary` subdirectory in their store path (the path provided to `cockroach mt start-sql` with the `--store` flag). 

In 23.1 we see a 1GiB file there
```
[root@tenantpool-default-f775cf8bf-hhx4f cockroach]# ls -l cockroach-data/auxiliary/
total 1048580
-rw-r----- 1 root root 1073741824 Nov 14 21:51 EMERGENCY_BALLAST
```

Secondary tenants should not be started up with a ballast file since stand alone SQL servers will only write intermediate ephemeral data, so if the disk fills up the operator can delete the whole store.

**To Reproduce**

Create a multi tenant setup of CRDB.

**Expected behavior**
No emergency ballast file is created for secondary tenants.

**Additional context**

I ran into this by chance as i was testing out a custom build of CRDB (based off master). SQL pods in the K3D host clusters that we create in cockroach cloud tests were continually being evicted since we had a limit of 380 MiB for ephemeral storage on tenant SQL pods. 
Note that in production environments we have a higher limit (8GiB).

Jira issue: CRDB-21816

**Comment by alyshanjahani-crl** [comment]
cc @knz, I believe this is due to the unification work.

**Comment by knz** [comment]
Can we talk about this? cc @JeffSwenson 

This change came as a side effect of adding the check for disk capacity (`storage.IsDiskFull`) that was missing in secondary tenant servers.

Regardless of the ballast story, this check is important: we don't want to run SQL servers if their disk is full, as it would make SQL execution fail with all kinds of unpleasant errors.

Then, moving on to the ballast story: are you sure we don't want a ballast in that case? As opposed to, say, a _smaller_ ballast?

**Comment by jaylim-crl** [comment]
As an aside, if we wanted to include any sort of ballast, we need to modify the ephemeral storage limits in CC to account for it because back then, the values were calculated to allow users spill queries up to ~7GB of disk.

> As opposed to, say, a smaller ballast?

@knz I'm curious, how would a ballast work in our case if the SQL pods are ephemeral? A related discussion: https://cockroachlabs.slack.com/archives/C02P01CDKKP/p1668466202320649?thread_ts=1668453546.350309&cid=C02P01CDKKP

**Comment by knz** [comment]
Thanks that discussion is helpful. In summary it says that our deployment _guarantees_ that there's always enough disk space for SQL servers.

I'll send a PR.

**Comment by JeffSwenson** [comment]
There are two properties that make ballast files useful for storage nodes and less useful for sql nodes:
1. Pebble and CRDB need free disk space in order to delete data. Creating a ballast file allows the operator to reserve space that is used to clean up the system in an emergency. SQL servers only store ephemeral data. If the sql server runs out os space, the operator can delete the entire pebble store.
2. Each machine only needs a single ballast file. In a traditional CRDB deployment there is one CRDB node per machine. In a multi-tenant deployment there are many sql servers per machine.
