### ISSUE TITLE
upgrade: add flag to allow tests to pretend master is the next binary release

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#92608]
**Describe the problem**

Currently, mixed-version roachtests rely on the fact that `roachprod` always sets the `COCKROACH_UPGRADE_TO_DEV_VERSION` environment variable (#88005), allowing the cluster to upgrade from a previous binary release to `master` during tests. However, that is not ideal for a few reasons: 1. that's not what real clusters would do; and 2. it can lead to upgrades that seem to go "backwards" -- see [Slack discussion](https://cockroachlabs.slack.com/archives/C02HWA24541/p1669655679783139) (internal).

Instead, we want tests to be able to prevent cluster versions from being offset, allowing us to pretend `master` is the next binary release and have our tests run the upgrade path that will actually be used when production clusters are upgraded.

Jira issue: CRDB-21882

**Comment by srosenberg** [comment]
>  2. it can lead to upgrades that seem to go "backwards"

This is owning to the fact that the earliest version is _not_ offset when `COCKROACH_UPGRADE_TO_DEV_VERSION` is set. Thus, if the earliest version is `k`, and the current version is `k + 2`, due to offsetting, the previous version becomes `k + 1 + 1000000`. Since the previous version is higher than current, this would result in a _downgrade_ [1].

[1] https://github.com/cockroachdb/cockroach/blob/ec92c4e580ba8f730f70fda18db3215ec1cf40aa/pkg/clusterversion/cockroach_versions.go#L722-L727
