### ISSUE TITLE
admission: better observability of slot adjustment behavior

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#92673]
There are two things that affect slot adjustment:
- The interval of CPULoad ticks: This can be either 1ms or 250ms. We used to log every change in this interval, but no longer do that since it was spamming the logs. An alternative would be to increment two cumulative duration metrics representing the cumulative duration spent under each regime.
- Interaction between increments and decrements: we have observed slow changes in the total slots in the past e.g. https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1667511459730139?thread_ts=1667418886.450229&cid=C01SRKWGHG8, and been unsure whether it was because we were both increasing and decreasing, or because the increase was rare. Having two counters counting the number of increments and decrements would tell us what happened.

Jira issue: CRDB-21914

**Comment by irfansharif** [comment]
I've also added the following to #82743 
- Metric capturing how long CPU slots are being held for on average, to reason about sudden changes in slot count where total incoming request rate for slots stays unchanged. When requests hold onto slots for longer (due to longer IO wait times, or increased latch/lock wait times), we need to increase slot count to service incoming work. Some times this increase is not fast enough and there's resulting AC queuing like we saw in https://github.com/cockroachlabs/support/issues/1921.
