### ISSUE TITLE
stability: slow performance after restarting cluster with many ranges

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9273]
When we restart gamma and beta, performance is bad for ~5-10 minutes before recovering. I suspect this is due to lazy raft loading. Both clusters have 8.39k ranges. Due to lazy raft loading we won't initialize the raft group for a range until it is accessed. `block_writer` touches ranges randomly and we currently have it configured to perform 50 concurrent requests on these clusters. I'm not sure if I'm following the Raft initialization, but it looks like every range will have to wait for an election because every replica starts as a follower. With 8.39k ranges and 50 concurrent ops we'd expect 167 rounds of waiting for the election timeout and then campaigning. With our current 200ms tick interval and 15 tick election timeout, this translates into 3 sec per round and ~8.5 min for all of the ranges to be woken up.

I'm not sure if this is worth addressing in the short term.

Cc @cockroachdb/stability

**Comment by tschottdorf** [comment]
This is the same issue that motivated #9197.

**Comment by petermattis** [comment]
We could have a replica campaign if a node receives a request that requires the Raft group to be created and the node has been up and connected to gossip for the election timeout. The thinking is that if a node hasn't received a heartbeat for the range after being connected to gossip for the election timeout, then the range is likely idle. Consider that if we disable lazy Raft loading a newly started node will campaign for all replicas after 3 seconds for which it hasn't received a heartbeat. So this would be similar behavior, we're just maintaining the election timeout outside of Raft.

**Comment by petermattis** [comment]
Btw, it is easy to reproduce this campaigning behavior, but you need to have a multi-node cluster. For example:
* Start a cluster using `roachdemo -n 3`
* Create a test table (it doesn't even need any data):
  * `./cockroach sql -e 'create database test; create table test.test (k int);'`
* Stop and restart the nodes in the cluster
* `time ./cockroach sql -e 'select * from test.test'`

I have seen the `select` take from between 6-10 seconds.

**Comment by tschottdorf** [comment]
> Consider that if we disable lazy Raft loading a newly started node will campaign for all replicas after 3 seconds for which it hasn't received a heartbeat. So this would be similar behavior, we're just maintaining the election timeout outside of Raft.

But that's not similar as that takes 3 seconds to get all the raft leaders in place whereas your query wakes them up one after the other (and at least on our clusters we see very long-running timeseries queries that touch over a hundred ranges, so that really adds up).

> We could have a replica campaign if a node receives a request that requires the Raft group to be created and the node has been up and connected to gossip for the election timeout. The thinking is that if a node hasn't received a heartbeat for the range after being connected to gossip for the election timeout, then the range is likely idle.

That sounds like it could work. Your example wouldn't benefit (much) from it, but the behaviour at startup is really much less interesting than that of waking up a range after some uptime.

**Comment by petermattis** [comment]
I experimented with my idea and it works in simple testing. See #9276. Curious to see what holes @bdarnell pokes in it. 

PS #9276 does help my example as long as you wait 3 seconds after starting the cluster.

**Comment by bdarnell** [comment]
Remember that the cold restarts we're doing in beta are an anomaly - by 1.0 all normal restarts will be rolling and so a newly-awakened node will find that most of its ranges have leaders elsewhere. I don't think solving the cold-restart problem is a priority, although I think #9276 is a good idea as long as we're doing lazy raft initialization.

Lazy raft initialization is based on the (untested) theory that letting every range campaign more or less simultaneously at startup would saturate the network and/or the raft/rpc processing goroutines, causing some of those elections to fail. It also reduces heartbeat load after a restart (depending on access patterns). These benefits may not count for much now, but I don't think we want to backtrack on this because we eventually want to allow ranges to go back to sleep.

**Comment by tschottdorf** [comment]
> These benefits may not count for much now, but I don't think we want to backtrack on this because we eventually want to allow ranges to go back to sleep.

In a world in which we get rid of heartbeats completely (whether that's going to happen is a different question) there wouldn't be any point in quiescing, and the recent RFC #8811 has demonstrated (again) that quiescing isn't an easy feat.
That said, I also think #9276 should work well and there's no good reason to consider backtracking at this point.
