### ISSUE TITLE
multi-tenancy: handle ux for session expiration

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#92843]
**Is your feature request related to a problem? Please describe.**
Follow up from https://github.com/cockroachdb/cockroach/pull/92694. A decision should be made on what the user experience should be when a user tries to access a tenant from the admin ui while their session has expired.

**Describe the solution you'd like**
One potential solution is to redirect the user to the login page and have them login for that tenant again.

Jira issue: CRDB-21999

**Comment by dhartunian** [comment]
Here's how things work on the first pass:

### Login

1. User logs in as usual
2. Separate sessions are created on each tenant for which the given creds are valid
3. Tenant switcher allows switching active tenant sessions

### Logout

1. Lose all active sessions on all tenants

### Session expires

Haven't tested this but probably:
1. Session remains listed in switcher
2. Switching to it redirects to logout since session is expired
3. (As above) All sessions are cleared.

----

My preference here is to keep the "all sessions just get cleared on a logout event" logic. Otherwise there's a lot of extra UI that needs to be built to manage login into a particular tenant and merge that tenant's session with the existing cookie etc etc.

I doubt the extra flows provide such an elevated user experience that it's worth thinking it through. Logging in again for the user should be easy enough and is something they'd already have to do with the existing flows on a non-UA cluster. Since by construction all sessions would be for matching credentials anyway, a single login will bring the back to the multi-tenant switcher state they had prior to logout.

cc @thtruo

**Comment by Santamaura** [comment]
cc @knz
