### ISSUE TITLE
[Suggestion] Ability to run cockroach as a service through homebrew

### ISSUE THREAD

**Issue by fletchto99** [cockroachdb/cockroach#9438]
Please follow the steps below to help us help you.
1. Please supply the header (i.e. the first few lines) of your most recent

`cockroach version` output:

```
Build Tag:   beta-20160915
Build Time:  2016/09/17 04:30:39
Platform:    darwin amd64
Go Version:  go1.7.1
C Compiler:  4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)
```
1. Please describe the issue you observed:
- What did you do?

`brew services start cockroach`
- What did you expect to see?

The cockroachdb running as a service in the background. Brew [services](https://github.com/Homebrew/homebrew-services) enables applications installed via brew to easily be run as a service at launch. For example `brew services start postgres` will start running the postgres database in the background as a service and will have it auto-start on boot.
- What did you see instead?

That the cockroachbd has started and is running in the background as a service.

**Comment by knz** [comment]
@fletchto99  So first of all thanks for the suggestion.
But let's do a little more homework and try to work this further out. How do you propose to deal with the fact that you may have multiple computers running cockroach via brew, that need to be part of the same database cluster?

More specifically: *how do you propose to configure the service when you run brew install / brew services start on a new computer for the first time, when you want the cockroach node to join an existing cluster?*

**Comment by bdarnell** [comment]
I think it's fine to assume that a brew installation is for a single node by default (as long as there is *some* way to wipe and reconfigure it otherwise; I don't know what standard practice is for brew packages); brew is primarily for development environments rather than production deployments.

 I'm less comfortable with assuming insecure mode by default ([even if it's localhost-only](http://bouk.co/blog/hacking-developers/)); insecure mode should be opt-in (because TLS certificates are currently the whole of our security model. Other database have passwords to fall back on, which are safe enough without TLS on localhost). But starting in secure mode means generating certificates and establishing conventions about how those certificates are managed, which is something we haven't done yet. 

Also, it's not great that we're claiming port 8080 for our web UI. This was supposed to be a temporary measure until we could get our ports reunified, but since that doesn't seem to be happening soon we may want to reconsider which port we use.

**Comment by fletchto99** [comment]
> I think it's fine to assume that a brew installation is for a single node by default

Yes in this case the installation was for a single node. At hack the north we were planning on using Cockroach DB with our rails app (which didn't end up working due to Active record not being supported). For our development environment I just used the brew script to install cockroach so that it would be ready to go. Now for hack the north my laptop was on most of the time, so in theory starting it once wouldn't be an issue. However if I were to restart my laptop I would need to start it up each time or create a launchd service. However the use of brew services really simplifies this problem for Mac devs who use brew.

> I'm less comfortable with assuming insecure mode by default (even if it's localhost-only); 

Heh nifty attack! I would agree with you about this, though I don't have a direct solution to this problem.

> Also, it's not great that we're claiming port 8080 for our web UI. 

I also found this strange to be the default behavior, especially since I was running nginx through that port for our test environment.
