### ISSUE TITLE
storage: unable to rebalance away from lease holder

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9462]
The allocator heuristics currently disallow rebalancing away from the lease holder for a range. This can cause significant imbalances when a single node holds the range lease for a significant fraction of the ranges in a cluster. As long as those ranges are accessed frequently we'll keep extending the lease. 

Now that we have the ability to transfer leases between nodes we should investigate having the `replicateQueue` transfer its lease to another replica when it encounters a range it wants to remove itself from. Note that `replicateQueue` only has to transfer lease. The new lease holder node will take care of performing the removal.

The big risk in implementing this is that the lease transfer mechanism is currently not used in production, only in testing. Are there any concerns with that code?

Cc @cockroachdb/stability

**Comment by bdarnell** [comment]
The main concern with the lease transfer in production (aside from a general paranoia about any change) is that it causes a short period of unavailability since we must wait for the old lease to expire (exactly the same reason why we excluded lease holders from rebalancing in the first place).

We need to make sure that we only transfer leadership when it's the least-disruptive option and that we don't end up bouncing leadership back and forth between different nodes. Transferring the lease when a store is overloaded relative to the rest of the cluster and lease holder for 100% of its ranges seems safe.

**Comment by spencerkimball** [comment]
Why do we have to wait for expiration? I thought the point of transfer was
to avoid that wait.

**Comment by tschottdorf** [comment]
> The main concern with the lease transfer in production (aside from a general paranoia about any change) is that it causes a short period of unavailability since we must wait for the old lease to expire (exactly the same reason why we excluded lease holders from rebalancing in the first place).

We don't need to wait for anything to expire. We do need to wait for one Raft proposal to go through (the lease transfer itself) and there will be a slight hiccup as proposals bounce from the old leaseholder to the new one. I assume that's what you meant?

>
We need to make sure that we only transfer leadership when it's the least-disruptive option and that we don't end up bouncing leadership back and forth between different nodes.

Why not always chose a follower replica, except when no such option is available (in which case we transfer a lease away)?

**Comment by bdarnell** [comment]
I misremembered - we don't have to wait for the old lease to expire, but we do need to wait for the clock MaxOffset (in addition to the churn as clients get redirected and update)

The lease transfer mechanism was primarily introduced to control lease placement for distsql tests; production use has been a secondary consideration so far which is why we need to hash these things out now.

**Comment by spencerkimball** [comment]
I was also under the impression (haven't read the code though) that we
didn't in fact have to wait for MaxOffset either. A database time from the
original holder is passed with the lease transfer to provide a high water
mark on the physical component of HLC.

**Comment by bdarnell** [comment]
Yeah, the reference to [maxOffset](https://github.com/cockroachdb/cockroach/blob/304a6f5d1fa411ccd0ee62632b02330e1b925961/storage/replica_range_lease.go#L288) in the transfer code is only relative to the store start, so we don't wait for that most of the time. So the disruption is just one raft commit plus all the clients getting bounced to the new lease holder.

**Comment by petermattis** [comment]
This is now fixed.

**Comment by a-robinson** [comment]
For future cross-referencing purposes, the PRs involved were: #10439, #10464, #10730, #10766, #11201, #11664, #11729, and #11757
