### ISSUE TITLE
ui: web interface into the data

### ISSUE THREAD

**Issue by domnulnopcea** [cockroachdb/cockroach#9467]
provide a phpmyadmin like functionality for cockroach where you can create/alter/drop tables, add/edit/delete rows, etc

**Comment by tamird** [comment]
Is there any reason this needs to be part of cockroach? Existing tools that support postgres should just work with cockroach.

**Comment by bdarnell** [comment]
I think a basic built-in web interface to the data makes sense for the same reason that it makes sense for us to have our own monitoring interface when prometheus et al exist. However, exposing the data rather than just metrics over the web is much harder than it looks due to all the security considerations, so we probably won't get to this any time soon.

**Comment by tamird** [comment]
Note that tools like phpMyAdmin include a server-side component. It is not
currently possible to implement the postgres protocol in browser-side
javascript except by tunneling over websockets, which is a significant
complication. It is for this reason that I don't think this issue is
appropriate for cockroachdb/cockroach.
