### ISSUE TITLE
sql: UPSERT overrides column with default value

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9474]
For

```
CREATE TABLE abc (
  a INT,
  b INT,
  c INT DEFAULT 7,
  PRIMARY KEY (a, b),
  INDEX y (b),
  UNIQUE INDEX z (c)
)
```

with rows:

```
query III
SELECT * FROM abc ORDER BY (a, b, c)
----
1 2 7
7 8 6

statement ok
UPSERT INTO abc VALUES (1, 2, 5)

# this UPSERT should not override 5 with 7
statement ok
UPSERT INTO abc VALUES (1, 2)

query III
SELECT * FROM abc ORDER BY (a, b, c)
----
1 2 7
7 8 6
```

**Comment by vivekmenezes** [comment]
Hmmm, I'd argue this is not a bug because the user intends the default value be added via the INSERT path of UPSERT when the row is not present. So it follows that they intend the default value via the UPDATE path as well.

**Comment by bdarnell** [comment]
I find this surprising too, but that's why we have the full `ON CONFLICT DO UPDATE` form (and why postgresql *only* has the full form), so applications can specify exactly what happens when there is a duplicate row. FWIW, MySQL's REPLACE statement also overwrites omitted columns with default values.

**Comment by paperstreet** [comment]
This is working as I intended it. Unfortunately, I think either way would be surprising to someone. I guess we could require the user specify all non-hidden columns when using the UPSERT shorthand
