### ISSUE TITLE
cli/sql: inconsistent error handling between statements

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9502]
Consider the difference between:

```
% echo "select foo; select 42;" | ./cockroach sql
pq: column name "foo" not found
Error: pq: column name "foo" not found
Failed running "sql"
%
```

and

```
% (echo "select foo;"; echo "select 42;") | ./cockroach sql
pq: column name "foo" not found
1 row
42
42
```

In short:
- when two statements are on the same line, both are sent at the same time to the server and the server will avoid executing subsequent statements upon encountering an error;
- when two statements are on separate lines, the cli will send the first to the server, report any error the server has found, then send the 2nd statement to the server for processing regardless of whether an error was encountered with the first.

Arguably the inconsistency is a problem.

Constraint: we can't change the cli sql to always refuse subsequent statements upon encountering an error. This would break UX in the interactive shell.

A couple options remain:

- enable running subsequent statements always, even after encountering a failure. This is what `psql` does. To achieve this we can either:
  - change the sql Executor server-side to allow continuing statements after encountering a failure; or
  - change the cli sql to split statements at semicolons and send them separately to the server for processing.

- add a flag to the cli sql so that it too would stop processing subsequent statements after encountering an error. This flag would be activated by default when running statements non-interactively (either -e or reading from a non-terminal stdin).

@bdarnell do you want to help bikeshed this?

**Comment by bdarnell** [comment]
I am surprised that `psql` always continues after error; `mysql` stops on the first error (I believe this is the first time I've ever seen mysql be more strict in its error handling than postgres). 

If there was a transaction, it will be aborted by the first error, so that's one way to opt into a stricter mode (and arguably you should be doing that anyway if you care about all-or-nothing execution). On the other hand, the CLI in non-interactive mode is not a good tool for doing (write) transactions in cockroachdb because it doesn't give you tools for handling retries. 

I'd prefer to err on the side of strictness here, and when we encounter an error in non-interactive mode, stop immediately.
