### ISSUE TITLE
storage: investigate collapsing reservations into streaming snapshots

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9509]
We should update the RFC as well, since it already mentions this as a possibility.

**Comment by jordanlewis** [comment]
I have a bunch of WIP on this, but in order to complete this we'll need to modify the streaming snapshots RPC return values to include at minimum the count of ranges in the recipient store. That's because the reservations API currently uses each reservation request/response interaction as an opportunity to update the reserving node's estimate of the recipient node's fullness.

@BramGruneir additionally recommends augmenting the return values to include the entire `StoreDescriptor` for future-proofing upgrades to the rebalancing algorithm.

It seems like a potential violation of abstraction boundaries to start adding this kind of side-channel information to the streaming snapshots RPC. I'm curious what other people think about this - cc @bdarnell as the author of the streaming snapshots RFC.

**Comment by petermattis** [comment]
Returning the `StoreDescriptor` is almost certainly overkill. I'm often wary of future-proofing without having a concrete need for using the additional flexibility. Besides, part of the point of protobufs is that we can extend them in the future.

Returning `StoreCapacity` would be more reasonable. The reason for return the range count in the reservation response is that the range count changes rapidly. `StoreCapacity.available` changes relatively slowly and `StoreCapacity.capacity` shouldn't change at all. I don't think it is worth separating out those fields, but we also don't need to make sure they are perfectly up to date when returning a `StoreCapacity`.

**Comment by BramGruneir** [comment]
The only reason to return the full descriptor is it also includes storecapacity available.  As long as we also return that, I think we're good.

**Comment by cuongdo** [comment]
+1 on just including capacity. Including the full descriptor may lead to
undesirable dependency of streaming snapshots on non-capacity fields of
descriptor.

**Comment by jordanlewis** [comment]
Okay, that makes sense to return `StoreCapacity`. I'll get that done.
