### ISSUE TITLE
roachpb,storage: API metaissue

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9538]
Writing down the content of some in-person discussions with @tschottdorf, some of which are motivated directly by #9450.
- `*storage.Replica` implements `client.Sender`. `client.Sender` is synchronous, which makes it necessary to hold a reference to the `*storage.Replica` while any call to `(*storage.Replica).Send` is on the stack. This complicates #9450; a channel-based design would remove the need to hold this reference - the caller would wait on a channel rather than a synchronous method on the `*storage.Replica`.
- `roachpb.BatchRequest` (via `roachpb.RequestUnion`) is a grab bag of unrelated functionality. In particular, it is currently possible to construct a batch mixing "normal" KV requests with admin commands and other internal commands (e.g. GC requests), but such a batch is illegal at runtime. This introduces awkward handling wherever it is necessary to interact with a batch because special care must be taken to correctly handle batch subtypes without compiler help.

Ideally, `BatchRequest` would be replaced with several types, each of which is currently constructed by DistSender at runtime (see `roachpb.BatchRequest.Split`). ISTM that we need:
- ReadBatch
- WriteBatch
- AdminBatch

The batch complication is relevant to the current Sender implementation because all batches "types" are currently handled in `(*storage.Replica).Send`, making it difficult to adapt to a channel-based API.

I propose we start to pursue this agenda, starting with AdminBatch. cc @cockroachdb/stability (this isn't really stability related, but that group contains the relevant people).

**Comment by bdarnell** [comment]
Moving away from the one-size-fits all `client.Sender` interface generally seems like a good idea to me; code that talks directly to a Replica should know it's dealing with a Replica and be able to use a Replica-specific interface.

I'm sympathetic to the second point from an API cleanliness perspective, but it seems like a completely unrelated (and much lower-priority) issue. How far up the stack does this go? In the storage package it would be relatively simple to introduce AdminBatch (or, since no admin requests can meaningfully be batched, just using separate types for each of the admin requests), but if this turns into separate API methods the changes to the `kv` package get very messy. (And even in the storage package I think splitting ReadBatch and WriteBatch might be more trouble than it's worth). What problem are you trying to solve here?

**Comment by petermattis** [comment]
@bdarnell Do you think we're going to tackle anything related to this issue? The issue has been idle for almost 2 years.

**Comment by bdarnell** [comment]
We might move in this direction (we're widening the Replica interface with the introduction of RangeFeed, and contemplating streaming interfaces in #8360), but I don't see much value in keeping this issue open.
