### ISSUE TITLE
sql: support for Google Cloud Storage and Amazon S3 in backup/restore

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/cockroach#9547]
Right now, it only accepts local paths. I think they both have REST-y APIs that we can use, so maybe the code can be shared. Open questions:
- How does the user specify these and how do we pass them around? URIs or something more structured?
- How do we get whatever credentials we need?

**Comment by paperstreet** [comment]
@dt do you think you'd have time to pick this one off?

**Comment by dt** [comment]
Our initial discussions of this expressed hope that could confine complex, providers-specific logic (for aws, s3, hdfs, etc) to the coordinator, by having it calculate an HTTP uri as a base path (plus some headers) and then sending that in our `ExportKeys` command, while replicas which would more or less basically simply append a range-specific filename to that. The coordinator can't easily, safety predict every filename that will end up being generated since a range may split at any time.

However my reading of S3 docs is that each PUT request includes an authorization header, signed with some aws credentials, that is, in part, based on the name of the file being PUT to.

This seems to imply we'll need the logic for authorizing a request to a given name in `ExportKeys`, so we need to go the route of sending along the credentials needed to do so and use an enum, etc. x

@bdarnell Our initial hope was to keep complex, provider-specific logic out of the ReplicaCommand and @paperstreet has expressed concern about adding it, but it looks like both google and amazon strongly encourage using their client libs, and s3's file-specific authorization strings may make it difficult to avoid it... are we being overly paranoid about what we're doing in a ReplicaCommand (and should just add provider handling there0, or should we keep looking

**Comment by bdarnell** [comment]
S3 does have the [option](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html) for you to sign a string containing a prefix of the path to be uploaded instead of the full path. However, even with this it seems very unlikely that we'll be able to get the same uploader code to work for multiple providers by just varying the URL. I think we're going to have to have code that is specific to the storage provider running on the node where the command is being processed (abstracted behind some interface, of course). 

In the long run we may want some sort of plugin or coprocessor system so that storage providers don't have to be linked in to the main binary, but for now (and for a limited set of providers) it's fine to just link it in directly.

**Comment by dt** [comment]
calling this done(ish) -- there's some polish we can do but we can open specific issues when we get there.
