### ISSUE TITLE
SQL Activity page crash during upgrade 22.1 > 22.2

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#95587]
During an upgrade to 22.2 the SQL Activity page is returning an error, because it tries to select index_recommendation column that was only added on 22.2.
A version gate needs to be added to it.

<img width="1269" alt="Screen Shot 2023-01-20 at 11 45 11 AM" src="https://user-images.githubusercontent.com/1017486/213755388-d52566be-22d0-4aad-bd7e-e00167205d32.png">

**Comment by xinhaoz** [comment]
Just an update - this is likely being caused by our `crdb_internal.statement_statistics` view which reads from the system stats table. We're unable to properly version gate it since view definition is quite no frills atm, but [this feature request has been put in and should help with that.](https://github.com/cockroachdb/cockroach/issues/95787)
