### ISSUE TITLE
sql: admin server gives scheduled GC job "Retrying" status

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#95712]
[The query behind the jobs endpoint of the admin server](
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/admin.go#L2242)  assigns a `retrying` status to all jobs that meet the following condition:
`status='running' AND next_run > now() AND num_runs > 1`
or 
`status='reverting' AND next_run > now() AND num_runs > 1`

We need to either change the logic defining the `retry*Condition` here, or, further down, not assign a status of `running` to jobs that are scheduled but have not yet started.

Background thread: https://cockroachlabs.slack.com/archives/CUVEFUU3C/p1674507323054389

Jira issue: CRDB-23683

**Comment by maryliag** [comment]
Seems like other filters are having the same issue: https://cockroachlabs.slack.com/archives/C0159JK877C/p1674533214747149

**Comment by kevin-v-ngo** [comment]
I think it's odd that we aren't consistent with the internal table and SHOW command but I understand we have this behavior because we tried to be more specific into this "running" state. 

It seems like this is more of a sub-status of "running" that we're trying to convey but it caused more confusion because of this inconsistency. In the near term for this issue, let's be consistent and remove this retry status. 

Medium-longer term let's track adding in the UI that this 'running' state is retrying and then reflect this in the internal table as well.
