### ISSUE TITLE
multiregionccl: flake in TestColdStartLatency due to timeout during user login

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#96334]
This is different from previous flakes and refers to the user account retrieval during session authentication.

Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8537864?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
          Error:        Received unexpected error:
                        failed to connect to `host=127.0.0.1 user=foo database=defaultdb`: server error (ERROR: internal error while retrieving user account memberships: operation "get-user-timeout" timed out after 10.002s (given timeout 10s): internal error while retrieving user account: aborted during DistSender.Send: context deadline exceeded (SQLSTATE 28000))
```

cc @rafiss for triage

Jira issue: CRDB-24073

**Comment by rafiss** [comment]
cc @ajwerner as well, in case it relates to some of the changes made for cold starts

**Comment by renatolabs** [comment]
Another one: https://teamcity.cockroachdb.com/viewLog.html?buildId=8563751&buildTypeId=Cockroach_BazelEssentialCi

**Comment by ajwerner** [comment]
Let's skip it. It does repro relatively readily and I haven't been able to debug it. Here's a PR https://github.com/cockroachdb/cockroach/pull/96464

**Comment by ajwerner** [comment]
This is real, and I've put some serious time and effort into trying to sort it out. I am actively unsure of what to do. At the end of the day, it looks like in some edge cases, requests get routed to the wrong place. That can happen because of the global tables not leading enough, which I tried to combat by override the cluster setting. For whatever reason I also saw in some runs that that setting wasn't uniformly taking effect. I have a patch which seems to rectify that problem (https://github.com/cockroachdb/cockroach/pull/100320). 

I stress it for a while and eventually it seems to fail in different places but always because it seems that either there isn't actually a non-voter where there should be one or because the distsender thinks a request needs to go to a leaseholder.

I've found now that disabling load-based rebalancing seems to help. Somehow the non-voters were seemingly getting lost in the face of scatters and load-based rebalancing. 

It's possible that the scatter calls which sped up the test conformance were causing problems, but they helped shorten the very long-running test (90s).

@arulajmani pointed out ([internal](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1680277141151449?thread_ts=1680276765.817609&cid=C0KB9Q03D)) that maybe we should enqueue in the replicate queue here: https://github.com/cockroachdb/cockroach/blob/41e3497400eac758aeb6a7333238e4e3a1aeac35/pkg/kv/kvserver/store.go#L2385-L2390 to avoid the scatter.  

Sometimes it seems like the global reads property doesn't properly propagate to the spans despite the reporter saying that everything is in conformance. 

I have to put this down, but I'm worried about it. There are some steps for how I've been trying to understand what's going on in https://github.com/cockroachdb/cockroach/pull/100320. At this point, my inclination is to say that the problem is somewhere in KV land, either with the reporter being wrong or with the replicas being out of sync with the reports.

**Comment by arulajmani** [comment]
> Sometimes it seems like the global reads property doesn't properly propagate to the spans despite the reporter saying that everything is in conformance.

I just looked at the conformance code, and it seems like the thing doesn't check whether the global reads property has propagated or not. 

You probably know this, but the other thing that could be at play here is that the DistSender may have a stale cache entry in the RangeCache. We only learn about an update to the closed timestamp policy as part of a batch response, so the first request may need to be sent to the leaseholder to learn about a policy update -- is the test resilient to this?

**Comment by arulajmani** [comment]
> This PR changes the default behavior to assume that you can go to a follow: https://github.com/cockroachdb/cockroach/pull/92621.

Ah, I didn't know about this. Sorry for the noise.

**Comment by ajwerner** [comment]
It's not noise. I think you're right about the heart of the problem.

**Comment by arulajmani** [comment]
The other thing to explicitly call out here is that the span config conformance report only runs on a single node -- this is fine for checking replicated state (on range descriptors) against span configurations. However, the global reads property is read from the in-memory SpanConfig stored on the replica struct. So we would have to check all nodes, not just one. Maybe it's easier to add a new method on `TestCluster` that does this instead of trying to teach conformance reports about global reads.

**Comment by ajwerner** [comment]
I'm removing the GA-blocker label.

**Comment by arulajmani** [comment]
> @arulajmani any chance you've been sniped into wanting to look into this?

Enough to atleast give the theory we have above a shot.

**Comment by rafiss** [comment]
ccing @JeffSwenson for help with triaging this.
