### ISSUE TITLE
util/stop: `go` keyword should be expunged from the stopper

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9640]
Currently, whenever we spawn a goroutine via `RunWorker` or `Run{,Limited}AsyncTask` we generate a stack trace anchored on a line of the form "created by ..." referencing the stopper code. This is annoying because it obscures the true creator of the goroutine, making it needlessly difficult to reason about both expected and unexpected goroutines in a stack trace.

ISTM that the only solution is to hoist the `go` keyword out to all the callers. I propose we rename the methods mentioned above from `Run*` to `Get*` and change their semantics so that they return a function which the caller must `go`, rather than `go`ing that function themselves.

Any objections? @bdarnell @petermattis @tschottdorf

**Comment by tschottdorf** [comment]
That means that callers which ask for a task must promise to start it. Could you sketch out the API you're proposing?

**Comment by tamird** [comment]
Yes, they must promise to start it.

**Comment by bdarnell** [comment]
`go stopper.GetWorker(func...)` is fine, but the interface gets ugly for Tasks since you have to handle the error case (whether you return a `func, err` pair or use a nil func to signal error). 

I haven't been finding this to be a problem because it's very rare for us to have the same function started in a goroutine from two different places, so the first line of the stack trace is just as good as the "created by" line to find out where the goroutine came from.

**Comment by tschottdorf** [comment]
Doesn't seem like we're going to do this.
