### ISSUE TITLE
ui: show performance of classes of queries

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9642]
It is very useful to see the performance of a class of queries over time. This could involve placing each query into a bucket and tracking its performance over time. The information need not be accurate, so one can compute stats over every minute or so and write them to storage at that interval.

**Comment by petermattis** [comment]
Can you flesh out what you're thinking here? I don't think my future self will be able to remember the context behind this issue.

**Comment by vivekmenezes** [comment]
For context, checkout Dominik trying to uncover performance problems in his DB.

https://www.justwatch.com/blog/post/debugging-postgresql-performance-the-hard-way/

skipping to the end of the investigation, once he was able to uncover the problematic query, he was able to rewrite the schema to fix the problem. To aid such a user, a solution could consider making suggestions on what to do, but as a first step it's valuable to split up queries into classes (group by unparameterized query?).

As an example, we do not run a lot of different types of queries on our existing beta clusters, so this information can be quite concise. It's nice to know if a particular query performance degrades over time as the data grows, or how a new upgrade of cockroach affects queries.

This can be part of the schema centric views that we've talked about. Or perhaps we want a new "Performance" view.

**Comment by tschottdorf** [comment]
A basic version of this seems fairly easy: we tag each SQL trace with the skeleton stringification of the query (i.e. without placeholders evaluated). Then (assuming the distributed tracing frontend isn't complete crap) you will be able to classify by those.

**Comment by BramGruneir** [comment]
MS SQLServer's query analyzer is pretty amazing.  I haven't found a good video demoing it but it would show not only how your query ran graphically, show which indexes were used by the planner and also suggest where you could add new indexes to improve performance.

**Comment by bdarnell** [comment]
> we tag each SQL trace with the skeleton stringification of the query (i.e. without placeholders evaluated)

That's if the app is using real prepared statements. I don't know about the state of the art for postgres, but at least with mysql it's common for drivers to fake out the prepared statement API calls (because the server didn't support prepared statements for so long), so the server only sees non-prepared statements with all placeholders resolved on the clients side. (also note that the `IN` operator can be difficult to use with prepared statements depending on the driver's capabilities)

`pt-query-digest` does a good job of turning these literal queries back into skeletons; [here](https://www.percona.com/doc/percona-toolkit/2.2/pt-query-digest.html#fingerprints) is the list of transformations it uses. In the past I've used elaborate cron jobs to get periodic query digests; it would be great to have similar functionality built-in.

**Comment by vilterp** [comment]
This seems largely covered by `crdb_internal.node_statement_statistics`, and the work spinning up to expose it to the admin UI (tracked in #26519). Going to close, since that issue has more specifics.
