### ISSUE TITLE
stability: ReplicaGC seems to incur RocksDB write stall

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9663]
On delta, the recently added instrumentation for long-held mutexes (#9638) showed the following:

```
# A Replica is gc'ed.
W161001 13:54:55.276407 183 util/syncutil/timedmutex.go:85  [n2,s3] mutex held for 3.3995
46836s (>500ms):
goroutine 183 [running]:
runtime/debug.Stack(0x244d7e0, 0x344277c3, 0x24503e0)
       /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/util/syncutil.(*TimedMutex).Unlock(0xc4206a2768)
       /go/src/github.com/cockroachdb/cockroach/util/syncutil/timedmutex.go:84 +0xf7
github.com/cockroachdb/cockroach/storage.(*Store).RemoveReplica(0xc42023c2c0, 0xc4206a270

# Many messages of the form
W161001 13:55:10.763072 79 util/syncutil/timedmutex.go:85  [n2,s3] mutex held for 15.668735102s (>500ms):
```

all with the same ~16s duration (which lines up perfectly with the time of the replica deletion, i.e. `13:55:10 - 15.668s == time of replica deletion`. The working theory is that the RocksDB write associated to the duration has blocked further disk writes (in turn stalling anything that needs disk i/o on that store).

@petermattis points out that we configured RocksDB to stall writes when 17 L0-sstables exist. These are targeted at 4mb each, so 68mb of writes would trigger this stall. It's not unlikely that that's what's happening.

@petermattis is going to look into this tonight. A naive solution could be increasing the number `17` or `4mb`, though Pete will know best what to do.

Independently, we should also warn when `(*Batch).Commit` takes a long time (or when RocksDB decides to stall writes).

**Comment by petermattis** [comment]
So far I'm unable to replicate any problem in a test. I tried writing a 64 MB batch composed of tiny keys and 0-length bytes. Worked fine. No stalls. I tried immediately writing another batch which clears the keys written in the first batch. Worked fine. No stalls. I verified that after writing these batches I could continue to write other keys without problems. 

Interestingly, when I write a single large batch like this RocksDB creates a single ~64MB L0 file, not a bunch of smaller L0 files capped at 4MB. It is possible that RocksDB is not the culprit here. Or perhaps there is a more complex scenario that triggers the write stalls.

**Comment by petermattis** [comment]
So instead of trying to write a single 64MB batch, I tried writing 16 4MB batches concurrently. Below is a table showing of the number of concurrent batches written, the time it takes to write them and an optional 3rd column showing how long a small write takes that is invoked shortly (100ms) after the batches are sent to RocksDB:

| batch size | elapsed | write |
| --- | --- | --- |
|  1 |  0.1s |       |
|  2 |  0.1s |       |
|  3 |  0.2s |  2.1s |
|  4 |  2.3s |  2.2s |
|  5 |  2.4s |  4.3s |
|  6 |  4.5s |  4.4s |
|  7 |  4.5s |  6.4s |
|  8 |  6.6s |  6.5s |
|  9 |  6.9s |  8.8s |
| 10 |  8.6s |  8.5s |
| 11 |  8.7s | 10.6s |
| 12 | 11.0s | 10.9s |
| 13 | 10.8s | 12.7s |
| 14 | 12.8s | 12.7s |
| 15 | 12.9s | 14.8s |
| 16 | 15.0s | 14.9s |

We hit an inflection point when writing 4 4MB batches. I believe this corresponds to reaching the RocksDB `max_write_buffer_number` which we currently have configure at 4. A small tweak to the test reveals that if I write batches slightly smaller than 4 MB then the elapsed time to write them is `0.2s`. 

The RocksDB docs say this about `max_write_buffer_number`:

```
  // The maximum number of write buffers that are built up in memory.
  // The default and the minimum number is 2, so that when 1 write buffer
  // is being flushed to storage, new writes can continue to the other
  // write buffer.
  // If max_write_buffer_number > 3, writing will be slowed down to
  // options.delayed_write_rate if we are writing to the last write buffer
  // allowed.
```

If I set `max_write_buffer_number` to 20, then writing 16 4MB batches concurrently takes `0.9s` vs `15.0s`. That seems worthwhile as this memory is only used temporarily to buffer writes.

Before going down that path I think we should verify that the long `handleRaftReady` calls are actually being caused by very slow `Batch.Commit` calls. That's easy enough to instrument.

**Comment by bdarnell** [comment]
In #10494, I saw a commit of 350k keys/23MB take 43 seconds:

    W161107 18:31:26.280307 223 storage/engine/rocksdb.go:1010  batch [357429/23938763/0] commit took 43.530565998s (>500ms):

**Comment by bdarnell** [comment]
There have been several commits to rocksdb in the last couple of weeks relating to range deletion. (actually going back as far as august, but it still looks like it's still incomplete and hasn't been mentioned in the release notes yet). So in a future release of rocksdb we may have a way to make replica gc much cheaper. 

There's also `rocksdb::WriteOptions::disableWAL`, which we could pass when committing the batch that destroys the replica. This means the write might get lost if there's a crash, but the replica GC queue should be able to just pick it up again next time. It reduces write amplification, but may not help if the problem is compacting the memtables.

**Comment by petermattis** [comment]
We could perform the range deletion in pieces. `Replica.destroyDataRaftMuLocked` currently creates a single batch to delete the replica data, but it seems safe to delete the table-data in smaller chunks and then perform a final batch which deletes the non-table data (i.e. range-local keys).

It's mildly curious that we see problems with replica deletion but we don't seem to be seeing similar problems when applying snapshots. 

We should ping the RocksDB folks about the status and timeline for the `DeleteRange` stuff. That looks very interesting, though I'd be apprehensive about being on the bleeding edge.

**Comment by a-robinson** [comment]
As mentioned in chat, DeleteRange is included in their recent 5.0 release - https://github.com/facebook/rocksdb/blob/master/HISTORY.md#500-11172016

We shouldn't necessarily switch to it now, but it'll no longer be quite as bleeding edge when we do decide to.

**Comment by petermattis** [comment]
There are caveats to `DeleteRange`:

```
  // Removes the database entries in the range ["begin_key", "end_key"), i.e.,
  // including "begin_key" and excluding "end_key". Returns OK on success, and
  // a non-OK status on error. It is not an error if no keys exist in the range
  // ["begin_key", "end_key").
  //
  // This feature is currently an experimental performance optimization for
  // deleting very large ranges of contiguous keys. Invoking it many times or on
  // small ranges may severely degrade read performance; in particular, the
  // resulting performance can be worse than calling Delete() for each key in
  // the range. Note also the degraded read performance affects keys outside the
  // deleted ranges, and affects database operations involving scans, like flush
  // and compaction.
  //
  // Consider setting ReadOptions::ignore_range_deletions = true to speed
  // up reads for key(s) that are known to be unaffected by range deletions.
```

Seems feasible for us to keep track of whether `DeleteRange` has been called on a range. I wonder how big that performance hit is. I wonder what the RocksDB folks consider to be "large" and "small".

**Comment by spencerkimball** [comment]
Well I suggest we do some empirical research. :-)

**Comment by tamird** [comment]
Is 5.0 actually released yet? It is strangely absent from
https://github.com/facebook/rocksdb/releases

**Comment by tamird** [comment]
Apparently not:
https://github.com/facebook/rocksdb/pull/1536#issuecomment-261686950.

**Comment by bdarnell** [comment]
> Seems feasible for us to keep track of whether DeleteRange has been called on a range.

Why would we need to? It doesn't seem necessary based on my reading of that comment.

I would interpret this warning as saying that we shouldn't use RocksDB DeleteRange for our KV DeleteRange command (if that would even be possible with MVCC), but I think it should be a good fit for our replica GC. The performance impact should (I hope) be limited to the time until the underlying data has been deleted by a RocksDB compaction. We'll need to verify this empirically, of course, but I think it will be useful to us.

**Comment by petermattis** [comment]
> Why would we need to? It doesn't seem necessary based on my reading of that comment.

In order to set `ReadOptions::ignore_range_deletions = true` in case that option has a significant impact. Certainly, we should experiment first to see whether it is worthwhile. 

We can't use RocksDB DeleteRange for our KV DeleteRange command anyways since the latter needs to create MVCC tombstones (unless we're deleting inline keys). We probably should use RocksDB DeleteRange when truncating or dropping a table.

**Comment by bdarnell** [comment]
Oh, I see. Set ignore_range_deletions for operations on replicas that have never been GC'd before, but leave it off for those with deletion in their history. That could work, but it would lead to subtle performance variations between replicas.
