### ISSUE TITLE
changefeedccl: don't allow changefeed creation on under provisioned cluster

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#96734]
Recently we had a customer run into an issue when starting a changefeed on an under provisioned cluster, leading to a crash. In the case where the cluster is underprovisioned, we should:
- Fail the changefeed create
- Give an error message instructing the user to provision more resources for the cluster 

See: https://github.com/orgs/cockroachlabs/saml/consume 

Jira issue: CRDB-24298

**Comment by miretskiy** [comment]
I don't know if we should refuse creation of changefeed.
We can (and should) work on providing better guidance, getting better understanding ourselves what's
required in terms of resources to run a changefeed; but failing during creation -- I don't know, just doesn't sound right.
Consider the case when we are writing to an underprovisioned kafka cluster? Is it changefeeds place to fail?
I just don't think we'll be able to do a good enough job.

Another area where we can and should invest is to be able to no "crash" an under provisioned cluster.
Perhaps by slowing changefeeds down (due to say pacer), or perhaps migrating to mux rangefeed framework, etc.

**Comment by shermanCRL** [comment]
Well, our ideal state (not just changefeeds, but everything) is graceful degradation. By which I mean, there is not a binary definition of “under provisioned”, it’s just that things will slow down instead of failing.

We _can_ advise / predict something along the lines of “you are likely to be disappointed” or “your changefeed will never catch up”. That seems like something via alert or DB Console, not changefeed creation time.

**Comment by amruss** [comment]
Note: we don't have a good heuristic for what "under provisioned" means and thus we dont have a good way to know when we would destabilize the cluster - we will look to fix particular problems when they come up
