### ISSUE TITLE
admission: make intent resolution subject to admission control

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#97108]
**Is your feature request related to a problem? Please describe.**
Creating enormous delete transaction could produce lots of intents. When transaction is committed, it could produce lots of intent cleanup and ranged intent cleanup requests. Currently those requests doesn't go through admission control and could overload L0 in pebble.

Jira issue: CRDB-24517

Epic CRDB-25458

**Comment by sumeerbhola** [comment]
See https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1676318637939779
This is possibly (would be much easier to confirm if we had https://github.com/cockroachdb/cockroach/issues/65414#issuecomment-1082188947) due to intent resolution having to rewrite the provisional value.

If the intent resolution is happening due to the txn commit and is not subject to the deadlock concerns described in https://github.com/cockroachdb/cockroach/blob/3b9d8cbfe7d7fa996f80ba3c38334ede7350a3ca/pkg/roachpb/api.proto#L2684-L2693 and we know that there are a large number of intents (presumably we have a rough count, even if we are only tracking ranges) that will get rewritten because the commit timestamp is different, then we could use `ROOT_KV` and subject these to admission control.

**Comment by sumeerbhola** [comment]
This is mainly a lack of AC integration and should be picked up by KV team.

**Comment by sumeerbhola** [comment]
(adding stuff from synchronous discussion)
- As mentioned earlier, if the intent resolution is due to txn commit and is async intent resolution, it can be classified as ROOT_KV and there is no deadlock concern. And synchronous intent resolution, on txn commit, should probably already be subject to AC (assuming the txn commit BatchRequest is not somehow avoiding the plumbing for AdmissionHeader_FROM_SQL).
- The other concern is increased lock contention by subjecting intent resolution to AC. Avoiding priority inversion is quite tricky since the lock queueing knowledge in `lockTableImpl` is quite far from the AC queues. Our understanding is that some of these production issues are stemming from large bulk work that the customer knows will not contend with normal priority user facing queries. We already have plumbing for "background" QoS level in SQL, that translates to `UserLowPri` in AC. We could add an assumption in the system (overridable by a cluster setting) that subjecting intent resolution of `UserLowPri` txns to AC is acceptable (i.e., will not cause priority inversion). To do this we have to remember to also change the logic in https://github.com/cockroachdb/cockroach/blob/2f04201df7f9198a6a3cb18921ea557ea64a0ce3/pkg/kv/txn.go#L1542-L1559 since we don't want to increase the priority of such `UserLowPri` txns that have intents.

**Comment by irfansharif** [comment]
Internal incidents:
- https://github.com/cockroachlabs/support/issues/2102
- https://github.com/cockroachlabs/support/issues/2237
- https://github.com/cockroachlabs/support/issues/2249
- https://github.com/cockroachlabs/support/issues/2240

**Comment by sumeerbhola** [comment]
Running some manual experiments. Left ~25M unresolved intents in a table totalling ~3.5GB and then did DROP TABLE.

CPU hits 100% and 99th percentile goroutine scheduling latency of 50ms.
<img width="984" alt="Screenshot 2023-08-09 at 12 11 24 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/53b3c4fc-f2d6-4c10-bbda-e0ccdee71921">
<img width="977" alt="Screenshot 2023-08-09 at 12 12 01 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/a6e45ca1-f479-4c6f-883f-4d861b85fb33">

All the CPU is in the "background work" of dropping the table via a MVCC range tombstone, which involves scanning to find the intents and resolving them.
<img width="1582" alt="Screenshot 2023-08-09 at 12 10 24 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/fbb4417a-9246-429f-bfd4-a554c9229ac7">

**Comment by sumeerbhola** [comment]
After increasing `intentResolverSendBatchTimeout` to 1000 min (before this increase, a txn with 200M intents that committed only resolved 7M of its intents), there is sustained overload. After ~15min (the graphs below are shorter) there are 66 sublevels, since AC is bypassed. As the provisional value has to be rewritten, and the read costs are higher (due to worse read amp) intent resolution is no faster than the original write and is slowing down further.

<img width="739" alt="Screenshot 2023-08-10 at 9 41 06 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/1b9031a4-2a77-42a0-bf99-17d6922cfffd">
<img width="884" alt="Screenshot 2023-08-10 at 9 41 27 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/b72fa581-78ad-45c4-a185-6f9faa99e296">
<img width="740" alt="Screenshot 2023-08-10 at 9 44 37 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/db140d15-5deb-4150-a6d3-ef0d6a6a2547">
