### ISSUE TITLE
oidc: support for matching on group claims from auth provider

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#97301]
**Is your feature request related to a problem? Please describe.**
Currently, the OIDC feature can match on string claims that appear in the JWT token that the auth provider sends in the final step of the OIDC login process. This limits customers to only matching on string claims when they may want to use others.

In particular, group claims which return a list of strings would be useful to match on in order to provide group-level login to DB Console instead of requiring per-user accounts.

**Describe the solution you'd like**
A group claim should be parsed and the regex param should be applied per-item on the individual groups. Once the first match is encountered, that group should be used to match a SQL user to login.

**Describe alternatives you've considered**
* The current parsing scheme returns an error on lists so there's no workaround
* Forcing the selected group to be returned as a custom claim from the auth provider is too complex too maintain on the customer-side.

**Additional context**
Customers would ideally prefer to select between **all** matching groups if there are multiple, but there's no facility for selective login in DB Console. We should consider building this but for now the cost is likely too high.

Jira issue: CRDB-24624

**Comment by cameronnunez** [comment]
In the long term, the plan is to integrate DB Console with CC Console such that the ID tokens in the OAuth exchange are CC-issued tokens. This will make selective login for DB Console possible since the user will simply be redirected to CC Console login. This means that Org SSO will need to be enabled however. This solution will obviate the need to address group claims in these ID tokens since the ID tokens will eventually be CC-issued and Org SSO already handles support with external identity providers via Auth0.
