### ISSUE TITLE
roachprod: allow easy upgrading

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#97311]
A lot of people at Cockroach Labs use `roachprod` to create and manage clusters. However, there's currently no convenient way to upgrade the `roachprod` binary other than pulling the latest changes from the cockroach repo and building it locally. This is not ideal for a few reasons: it's easy to forget; it's distracting and can take quite some time; requires users to have all dependencies installed even if they just want to use the binary.

We want to allow everyone to easily upgrade `roachprod` so that they can get the latest bug fixes and improvements. Some ideas (discussed in an [internal thread](https://cockroachlabs.slack.com/archives/CHVV403F0/p1676670401188349)):

* Manage releases for `roachprod`
* Make it available through `homebrew`
* Build nightly binaries available somewhere (GCS) + a convenient way to download the latest binary.

**Update**: we already have [CI builds](https://cockroachlabs.slack.com/archives/CHVV403F0/p1676673126529859?thread_ts=1676670401.188349&cid=CHVV403F0) of `roachprod`, so we should probably use that. All we need is a convenient way to download the new binaries and replace the old ones.

Jira issue: CRDB-24628
Epic: CRDB-10428

**Comment by srosenberg** [comment]
We could use [1] which has all the boilerplate to orchestrate a self-update. However, it uses github releases to pull the latest binary. We could just publish them (from CI) to the archived repo [2] and apply a ring buffer, since we don't need to keep every nightly there; say last 7 nightly builds?

[1] https://github.com/rhysd/go-github-selfupdate/
[2] https://github.com/cockroachdb/roachprod
