### ISSUE TITLE
sql: switch to single int64 of microseconds for timestamp storage

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9759]
We already round to micros to preserve pgwire compat so we could save 50% of the on-disk space if we switched to storing just micros (rather than seconds and nanos).

This is potentially a breaking change (if we don't want to keep a bunch of legacy code around forever) so we should decide if we want to do that before we get too close to "production ready"

**Comment by knz** [comment]
:+1:

**Comment by dt** [comment]
concluded in sql meeting that we'll want to keep the current types around as well for legacy compat, at least until/if we introduce a migration mechanism.

**Comment by spencerkimball** [comment]
ping

**Comment by dt** [comment]
This one sucks -- we're using twice the space to store timestamps (and durations), but the migration story is bad too. We probably close this and just waste the bytes? /cc @danhhz @knz

**Comment by knz** [comment]
Durations are out of scope because there's not much to compress there. At best we could reduce days and months to use int32 instead of int64, but the rest can't change.

For timestamps I have no opinion other than highlighting we use variable length encoding on disk. Changing the data structure will mainly change memory consumption and perhaps computing speed. I wouldn't be concerned with migrations too much.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dt** [comment]
k, I think we're not doing anything here.
