### ISSUE TITLE
An error is expected for invalid data conversion

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#97672]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
```SQL
CREATE TABLE t0 (c0 DECIMAL);
INSERT INTO t0 VALUES (1);
CREATE TABLE t1 (c0 DECIMAL PRIMARY KEY );
INSERT INTO t1 VALUES (1);
SELECT t0.c0 FROM  t0 LEFT OUTER JOIN t1 ON (t1.c0) IN (('a') ::DECIMAL); -- actual: {1}, expeceted: error
```

**Expected behavior**
The SELECT statement should return an error, because we cannot convert 'a' into a decimal.
By the way, when I remove the PRIMARY KEY constraint in table t1, an error is returned. That’s ERROR: could not parse “a” as type decimal: parse mantissa: a.

**Environment:**
 - CockroachDB 22.2.5
 - Server OS: Ubuntu
 - Client app cockroach sql

Jira issue: CRDB-24811

**Comment by msirek** [comment]
Q: Would it ever be legal in ANSI SQL to interpret a predicate result which errors out for all rows as UNKNOWN?
If no, then this case must error out.
MySQL and SQLite don't error out this case as CAST('a' AS DECIMAL) results in `0`.
The query plan in CRDB is:
```sql
                                    info
----------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    estimated row count: 1 (100% of the table; stats collected 1 hour ago)
    table: t0@t0_pkey
    spans: FULL SCAN
```

**Comment by mgartner** [comment]
This is not a bug.

In this query, the optimizer's [`EliminateJoinUnderProjectLeft `](https://github.com/cockroachdb/cockroach/blob/b9fd02f31a8c087d17b4e301c71bea4ce9f0b5c8/pkg/sql/opt/norm/rules/project.opt#L5-L26) normalization rule can eliminate the join completely because:

1. The join does not produce any columns from the right side of the join.
2. The join does not filter any left rows. The join condition, `(t1.c0) IN (('a') ::DECIMAL)`, filters only right rows.
3. The join does not duplicate any left rows. This is not immediately obvious and requires some explanation: The join condition is equivalent to an equality condition, `t1.c0 = 'a'::DECIMAL`. Because `t1.c0` is a primary key, it is guaranteed that the join condition will be true for at most one row on the right side of the join. Therefore, the join will never duplicate rows on the left side of the join.

With the join eliminated, the join condition is eliminated too, and no error occurs. The optimizer in general is free to eliminate, reorder, and duplicate expressions. It only makes a narrow set of guarantees in this regard, which are described here: https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/props/volatility.go#L30-L86

**Comment by sayJason** [comment]
Thanks for your reply.  That means, after I remove the PRIMARY KEY data constraint, such optimization cannot be applied.  It has to evaluate the join condition, and an error happens.

**Comment by mgartner** [comment]
> That means, after I remove the PRIMARY KEY data constraint, such optimization cannot be applied. It has to evaluate the join condition, and an error happens.

Correct.
