### ISSUE TITLE
sqlschema: Running concurrent schema changes causes livelock

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#97846]
**Describe the problem**

The tpc-e workload typically executes multiple parallel schema changes in parallel. However recently this livelock when running 20+ schema changes at once. The schema changes were each to different descriptors. Each schema change appeared to be querying a large collection of other descriptors and then attempting to modify its own descriptor, transactionally. Under serializable isolation, this is a recipe for deadlock. In CRDB, all transactions were retrying indefinitely due to read refresh failures. In any other 2PL system, that will cause locking deadlocks.

**Additional context**
[Slack thread](https://cockroachlabs.slack.com/archives/CARM0PTK4/p1673277046212599)

Jira issue: CRDB-24918

**Comment by ajwerner** [comment]
The core problem here is that we read far more than we write, and that we don't lock our reads. I think we could do some plumbing to detect whether we're in the context of a schema change, and then lock descriptors we read using `FOR UPDATE` locks. This would be a good use case for `FOR SHARE` locks.

**Comment by ajwerner** [comment]
The livelock does sort itself out because the locks get retained between retries. I think one big and important difference between the declarative schema changer and the legacy schema changer is that concurrent schema changes to the same table are not supported. They weren't really supported before either -- they'd get queued. If all of the schema changes were to be run in a single transaction, they'd be actually parallelized.

**Comment by ajwerner** [comment]
Okay, this is now more understood as https://github.com/cockroachdb/cockroach/issues/97899

**Comment by ajwerner** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/97997.
