### ISSUE TITLE
ui: improve sql stats fingerprints pages response time

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#97875]
On our stmt and txn fingerprints pages, we have seen increasingly long loading times when requesting persisted sql stats for clusters with large amounts of data. This can lead to the page being unusable, as the minimum time range we allow to be requested is the past 1 hour.

We need to provide a fallback so that users can see at least some of their live workload.

Proposed experience:
- Provide a new time window option that is only in-memory stats - this uses the stats endpoint pre persisted sql stats that is still lying around (we can display the exact time period by surfacing the cluster setting value)
- If a request to persisted stats takes over (some threshold), suggest the above view
- Continue to fetch the pending persisted sql stats request in the background -> need to display this to user somehow (stack of previous, cached requests(?) - probably want to keep the cap small as sql stats has large payloads).
- Communicate to user when pending request is completed

cc @kevin-v-ngo , @dongniwang 

## EDIT - NEW APPROACH

We will be reading only from the system table (see discussion below), as the in-memory stats are actually the source of a lot of our response time issues. Limit and sort options will be added as a part of this plan.

Jira issue: CRDB-25071

**Comment by xinhaoz** [comment]
I'm going to include/address the following issues as a part of this:
- https://github.com/cockroachdb/cockroach/issues/97876
- https://github.com/cockroachdb/cockroach/issues/97881

**Comment by j82w** [comment]
1. Why not make the default to load the in memory first to get the page to load the fastest and then in the background pull persisted stats? That way it's always the same workflow. 
2. Won't the exact time cause confusion because different nodes will flush to persisted table at different intervals, and some nodes might even get restarted? Could the date time picker have a in memory option?

**Comment by xinhaoz** [comment]
@j82w Great questions --
> Why not make the default to load the in memory first to get the page to load the fastest and then in the background pull persisted stats? That way it's always the same workflow.

In a lot of our default time picker cases we'll be fetching in-memory stats along with the flushed data already. I think it's best not to always incur an additional request if the sql stats system is performing alright. This feature is moreso to offer a reliable alternative while we stabilize sql stats.

> Won't the exact time cause confusion because different nodes will flush to persisted table at different intervals, and some nodes might even get restarted? Could the date time picker have a in memory option?

I think just labeling 'in memory' might be more confusing since they won't know what the date range is. The flush interval is a cluster setting used by all nodes, so my thinking here was just to surface what that interval is so we could show that when we surface the in-memory option (e.g. 'Last 10 Minutes').

WDYT?

**Comment by j82w** [comment]
> In a lot of our default time picker cases we'll be fetching in-memory stats along with the flushed data already. I think it's best not to always incur an additional request if the sql stats system is performing alright. This feature is moreso to offer a reliable alternative while we stabilize sql stats.

I was hoping this feature would also reduce the initial page load times for everyone and not just the customers with large datasets. If we want to focus on just getting the one scenario to work that is fine. 

> I think just labeling 'in memory' might be more confusing since they won't know what the date range is. The flush interval is a cluster setting used by all nodes, so my thinking here was just to surface what that interval is so we could show that when we surface the in-memory option (e.g. 'Last 10 Minutes').

I'm trying to think of a way to convey that it's not all data from the last 10 minutes, because different nodes will have different times they flush the data. If it just says 'Last 10 Minutes' we will likely get customer issues asking why they don't see a query that ran 2minutes ago because the flush occurred 1 minute ago. @kevin-v-ngo  and/or @dongniwang do you have any suggestions?

**Comment by j82w** [comment]
Data point for `system.statement_statistics` table with 118k rows:
1. Over 3 minutes to return all the results
2. About 8 seconds without an index `select * from system.statement_statistics order by statistics->'execution_statistics'->>'cnt' limit 40;`

Data point for `crdb_internal.cluster_statement_statistics` table with 100k rows:
1. About 3 seconds to just generate the view. Probably longer because it's has to fan out to all the nodes.
2. About 4 seconds to return all the results


Taking the above numbers into consideration would a better solution be to:
1. Add indexes to the system table and only return the top 40 (2 pages) to always get the result in under 7 seconds. Every time a sort or search occurs it would require a query to the db to get the new results.
2. Only show the in memory stats if the time frame is limited to under 30 minutes or the persisted results are less than an hour old. 

This solution would allow users to select time frames and avoids the overhead of sending all the data back to the ui to do the computation. The trade off is that each time there is a sort/filter it will take longer.

WDYT?
