### ISSUE TITLE
ui: time selection interference between the Insights page and the Statement Fingerprint page

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#97952]
Go to the Workload Insights page and select some time interval. Then click on a statement fingerprint to navigate to the Statement Fingerprint page. When you do that, you get a time selection on this page that reads something like `0m 22:10 - 22:10` (an empty interval). Which somehow gets translated into `Showing aggregated stats from 22:00 to 22:59 (UTC)`.

The first funky thing is that, because of the `0m` selection, the arrows for `Previous/next time interval` do not work.

The second funky thing is that, if you now navigate to back to the Insights page (either through the browser's back button or through clicking on the Insights link in the menu), the `0m 22:10 - 22:10`  has overwritten whatever interval you had before on that page.

Jira issue: CRDB-24982

**Comment by ericharmeling** [comment]
Thanks for filing this issue!

We've got 2 changes merged that resolve it:

22.2: https://github.com/cockroachdb/cockroach/pull/98151
23.1: https://github.com/cockroachdb/cockroach/pull/98143

The 22.2 and 23.1 fixes differ because the Insights pages on 22.2 do not have time scale state. 22.2 insights surface executions that span across the lifetime of the insights and contention events internal tables, so we want to update the time scale state on the statement fingerprint details page to reflect the time scale for that "insight execution", and not use the global time scale state (either set to the default, or set earlier in the session on the overview page).
