### ISSUE TITLE
kv: transactions consisting of DelRange with limits should always go through the 2PC path

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9799]
in #9419 we ensure that transactions with DelRange with limits that go through the 2PC resolve the right number of intents. We should ensure that DelRange with limits always go through this path, or else we will unexpectedly see performance problems

**Comment by petermattis** [comment]
> We should ensure that DelRange with limits always go through this path, or else we will unexpectedly see performance problems

Can you expand on this? You're first sentence says that we're doing the right thing for "DelRange with limits" so what is there left to ensure?

**Comment by vivekmenezes** [comment]
I'm actually not sure what needs to be done here. It's been on my plate to look at this for a while, so I thought I'd create an issue before it slips through the cracks.

**Comment by bdarnell** [comment]
Consider a request `DelRange(KeyMin, KeyMax, limit=100)`. This will only touch a small number of keys but will naively try to resolve intents over the entire `(KeyMin, KeyMax)` span. In #9419, we added support in `kv/txn_coord_sender.go` to adjust the intent range based on the keys that were actually deleted, but because this happens on the coordinator it can only come between the DelRange and EndTransaction for 2PC transactions. We should either move this span truncation logic from `kv` to `storage` (in between commands of a batch) so it can affect 1PC transactions or modify the `kv` layer to ensure that it never sends `EndTransaction` in the same batch as a `DelRange` with a limit.

**Comment by spencerkimball** [comment]
I feel like I'm missing something here. A 1PC transaction consisting of `BeginTransaction, DelRange, EndTransaction` will not create intents. I'm closing this issue. Please reopen with a comment further explaining the problem if I have missed something. Also, make a judgement call about the 1.0 milestone if you reopen this.

**Comment by bdarnell** [comment]
The issue is not intents created by the DelRange, it's about how that DelRange resolves intents that already exist. A 1PC DelRange will always try to resolve all intents between its start and end key, even if it has a limit that ensures it would otherwise only touch a small fraction of that span. 

This is still an open issue, because it hurts the performance of dropping tables (either we use 1PC transactions and resolve intents inefficiently, or we do each batch in a 2PC transaction). This issue proposes to eliminate the trap by disallowing the 1PC optimization for transactions that contain DelRange with a limit. Alternately, we could figure out how to make DelRange do the right thing with intents even in the 1PC case (I don't remember why 1PC and 2PC are different here). Either way, I don't think it's a blocker for 1.0.

**Comment by vivekmenezes** [comment]
@bdarnell I'm closing this issue because dropping tables now uses ClearRange().
