### ISSUE TITLE
ui: reset sql stats link disappeared from SQL activity page after staying on the page for a while  

### ISSUE THREAD

**Issue by dongniwang** [cockroachdb/cockroach#97996]
Logged in as admin user and have the SQL activity page opened for a while (around 30 mins), the **reset sql stats** link next to the time window picker suddenly disappeared from the page. Refresh the page brings back the link.

Expected behavior: the **reset sql stats** link should always be visible to admin users 

cc: @maryliag  

Jira issue: CRDB-25009

**Comment by xinhaoz** [comment]
@dongniwang Do you remember what version this was on or any other repro details? I can't seem to reproduce this on master currently.

**Comment by xinhaoz** [comment]
It seems like this is caused by a circular import issue. There are several saga files that import `rootActions` from the `reducers` file. All saga files import actions from their respective reducer files, and `store/reducers.ts` is the where we create the root reducer for cluster-ui. This caused a circular import that looked like `saga <- reducer <- root reducer <- saga` in some files.

This meant that one of those keys (in this case it just so happened to be `uiConfig`) would not get their reducer populated. This explains why when I went to debug this issue using redux dev tools the `uiConfig` key was missing from redux (and also a console error was being shown indicating this).

Extracting `rootActions` into its own file will solve this issue.
