### ISSUE TITLE
Duplicate key when adding computed column to an existing table

### ISSUE THREAD

**Issue by codingconcepts** [cockroachdb/cockroach#98130]
**Describe the problem**

In a table with ~2,000,000 rows, the following alter statement results in a duplicate key error:

```sql
ALTER TABLE account
ADD COLUMN overdrawn BOOL AS (amount < 0) STORED;
```

> ERROR: duplicate key value violates unique constraint "account_pkey" (SQLSTATE 23505)

**To Reproduce**

Using code from [this gist](https://gist.github.com/codingconcepts/d4062bd800bb680ed1849a24f5b28e4a), run the following:

### Tools required to reproduce

* **CockroachDB** v22.2.6
* **Benthos** v4.11.0
* **Make** v3.81

### Steps to reproduce

1. Start a single node (the issue occurs with multi-node clusters too):
```
make node
```

2. Create the database:
```
make create
```

3. Generate some data:
```
make data
```

4. Run a little application (this is where the error will be reported):
```
make app
```

5. Perform the schema migration:
```
make alter
```

If the error doesn't present, run step 3 again to add more data to the database.

**Expected behavior**
A computed column is added to the table, with values calculated from the `amount` column. No errors.

Jira issue: CRDB-25093

**Comment by fqazi** [comment]
This also reproduces on master, let me dig into this problem more. But we are seeing primary key violations:

`2023/03/07 10:08:04 error udpating data: ERROR: duplicate key value violates unique constraint "account_pkey" (SQLSTATE 23505)`

**Comment by ajwerner** [comment]
The bug is now understood. @fqazi will be writing up more and fixing it. A workaround for the moment is to use `SET use_declarative_schema_changer = off`.

**Comment by fqazi** [comment]
So the issue observed here is a flaw inside the declarative schema changer which occurs when we are swapping primary indexes as a part of an ADD COLUMN statement, and concurrent DML is issued (UPDATE in this case). Specifically, when an UPDATE statement was run concurrently with the new primary index accepting writes, we incorrectly used a conditional put without accounting for the new column within the expected value. So, any updates during this transition point would fail with an incorrect duplicate key value error, since our conditional puts are ignoring the new column.

The correct behaviour here is to use a put operation (non-conditional) for updates on the new primary index since no hazard exists for UPDATE operations (the new column is not a part of the key). So, we should be able to safely be able to write any value.
