### ISSUE TITLE
ui: cookies preventing me from login into roachprod cluster with the same name as a previous cluster

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#98355]
I had a roachprod cluster and logged into the console. Then I make a new cluster with the same name. Presumably I have some cookies from the old one.
Now I can't log into the new cluster. But it works in incognito, and it also works on a different node. In regular browser, when clicking on `log in`, I get back to the same page without any error. But the console is full of 401 errors for random endpoints. I see these errors even before pressing the `log in` button. In contrast, when loading the login page in incognito, I don't see such errors.

This is with `23.1.alpha-1`.

Jira issue: CRDB-25215

**Comment by abarganier** [comment]
Similar to https://github.com/cockroachdb/cockroach/issues/98356, This was related to https://github.com/cockroachdb/cockroach/issues/97786, which was fixed in https://github.com/cockroachdb/cockroach/pull/97940.

This error appeared on v23.1-alpha.1, which did not contain the SHA that fixed the backwards compatibility issues that originally existed with multitenant session cookies.

I ran through the reproduction steps with a `master` build and was able to login without issue, so I think we're good here.

Marking as closed, but if this somehow appears again on master let's reopen.
