### ISSUE TITLE
cockroachdb does not support case sensitive names for ttl definition

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#98435]
```
CREATE TABLE  "shortener" ("id"   UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(), "uri" VARCHAR  NOT NULL, "createdAt" timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP(), "expiredAt" timestamptz  , FAMILY "static" ("id"))  WITH (ttl_expiration_expression = 'expiredAt');
ERROR: relation "shortener" (2513): row-level TTL expiration expression "expiredAt" refers to unknown columns
```

Jira issue: CRDB-25267

**Comment by chengxiong-ruan** [comment]
Thanks for filing the issue. The bug is probably that we didn't respect quoted column names in the ttl expression. I tested that the statement works after removing the double quote on `expiredAt`.

**Comment by wzrdtales** [comment]
yes the bug is that you do not interpret the TTL section case sensitive when put in quotes.

**Comment by chengxiong-ruan** [comment]
heh, looks like we're good here, just that you need to double quote the column name within the single quoted string...
like `'"expiredAt"'`, then it should work. Some internal code treat the expression string as a string datum...
Closing this since there is a workaround.

**Comment by wzrdtales** [comment]
will that be fixed though, or is this now "as intended"

**Comment by chengxiong-ruan** [comment]
Yeah, this is intended as how the expression is stored it is stored as a string internally, which means that both `"expiredAt"` adn `'expiredAt'` are stored as `expiredAt` in the meta data. The error we were seeing was during a meta data validation where the expression string is parsed but found that "hmm, the column name is not double quoted".

**Comment by ecwall** [comment]
The `ttl_expression` is consistent with the column definitions where the column names are case insensitive unless double quoted.

`"expiredAt" timestamptz` requires `ttl_expiration_expression = '"expiredAt"'`

`expiredAt timestamptz` can be used with `ttl_expiration_expression = 'expiredAt'`, `ttl_expiration_expression = 'expiredat'`, etc

**Comment by wzrdtales** [comment]
may be true, but you could argue, that the single quotes are contradictory to this and don't really add any benefit.

**Comment by wzrdtales** [comment]
however since you decided that the redundant quoting is correct, it wont be revertable anymore now. I was asking especially since we will implement this in our migration driver like this now.

**Comment by ecwall** [comment]
The two layers of quotes are not redundant:
- The inner double quotes are to make a [quoted identifier](https://www.cockroachlabs.com/docs/stable/keywords-and-identifiers.html#rules-for-identifiers ) which you need for case sensitivity.
- The outer single quotes exist because of how `WITH (name = value)` is parsing is implemented. The value cannot be a complex expression itself, but it can be a string literal of a complex expression (that is parsed later) which is what the outer `'...'` is for.

In some cases (like if you do not need case-sensitivity) you can omit one or both sets of quotes and the `ttl_expiration_expression` value can be correctly parsed and interpreted, but in this case you need both sets.
