### ISSUE TITLE
Unexpected Contention during multiple DELETE's

### ISSUE THREAD

**Issue by SomeDatabaseDude** [cockroachdb/cockroach#98484]
**Describe the problem**

I am experiencing an issue where I observe high contention (multiple seconds) on a `DELETE FROM table WHERE (pk1, pk2) IN (...)` on a single table.

**To Reproduce**

Message bus with a strong partitioning strategy that ensures data is well spread out to the different consumers/jdbc clients. The nature of the data requires that we "broadcast" deletes to several tables, but the contention only reported on a single table that is the largest in the database.

**Expected behavior**
If the deletes only ever contain a unique subset of PKs to be deleted, I wouldn't necessarily expect a lot of contention to occur. Is there some situation where if multiple deletes affect the same range, can they lock each other up?

**Environment:**
 - CockroachDB 22.1.13
 - Server OS: Linux
 - JDBC

**Additional context**
We saw several DELETE statements experience multiple seconds of contention in a high-volume period of work, leading to degraded update performance.

Jira issue: CRDB-25293

**Comment by chengxiong-ruan** [comment]
Hi @SomeDatabaseDude thanks for filing the issue. But it's not clear that this is a specific bug. If you're current a enterprise user please file support tickets so that engineers would be able to help you better by either lookin at your cluster or debugging info. You could also visit our community slack and people also help you there. But still more specific debugging info would be helpful (at least a debug zip). I'm closing this for now.
