### ISSUE TITLE
sql: trying to use UDF with interval arithmetic results in parser error

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#98604]
**Describe the problem**

When I try to use a function I created to generate a random date, it fails to parse.

**To Reproduce**

On a single-node local cluster, run:
```
CREATE OR REPLACE FUNCTION f_random_date()
RETURNS date AS
$body$
SELECT date(now() - trunc(random() * 365)::int * '1 day'::interval - trunc(random() * 100)::int * '1 year'::interval)
$body$
LANGUAGE sql;

select f_random_date();
```
It produces the error:
```
ERROR: date(): could not parse "1 day" as type int: strconv.ParseInt: parsing "1 day": invalid syntax
SQLSTATE: 22P02
```

**Expected behavior**
Using the UDF should not fail. It succeeds on Postgres:
```
postgres=# select f_random_date();
 f_random_date 
---------------
 1937-03-10
(1 row)
```
Running the raw SELECT query also succeeds on CockroachDB:
```
root@localhost:26257/defaultdb> SELECT date(now() - trunc(random() * 365)::int * '1 day'::interval - trunc(random() *        
                             -> 100)::int * '1 year'::interval)                                                              
                             -> ;                                                                                            
     date
--------------
  1974-10-08
(1 row)

Time: 1ms total (execution 1ms / network 0ms)
```

**Environment:**

 - CockroachDB version: master (i.e. 23.1 alpha)
 - Server OS: MacOS Ventura (Apple M1 Pro)
 - Client app: cockroach sql

Jira issue: CRDB-25356

**Comment by lyang24** [comment]
I think this is caused by cast to interval missing from expression which caused type checker determine desired type as int
in [overloading code](https://github.com/cockroachdb/cockroach/blob/7d02e061759599a2b054ee06c71524443f77d20a/pkg/sql/sem/tree/overload.go#L1321) 
I printed some struct right after, the expression looks strange the case to interval is missing
```
s.exprs=[trunc(random() * 365.0)::INT8 '1 day']
des=int
```
In fact the expression with out interval cast happen to scalar building prior to building the udf function [code](https://github.com/cockroachdb/cockroach/blob/7d02e061759599a2b054ee06c71524443f77d20a/pkg/sql/opt/optbuilder/scalar.go#L333)

with some print statement it yields
```
	case *tree.FuncExpr:
		if strings.Contains(t.ResolvedOverload().Body, "1 day") {
                         // build expr statement: SELECT date((now() - (trunc(random() * 365.0)::INT8 * '1 day')) - (trunc(random() * 100.0)::INT8 * '1 year'));

			fmt.Println("build expr statement: " + t.ResolvedOverload().Body)
		}
		return b.buildFunction(t, inScope, outScope, outCol, colRefs)
```
we will get the same error if we directly execute `SELECT date((now() - (trunc(random() * 365.0)::INT8 * '1 day')) - (trunc(random() * 100.0)::INT8 * '1 year'));` in sql shell.

**Comment by rytaft** [comment]
Nice find, @lyang24!

**Comment by lyang24** [comment]
getting closer to root cause, approaching from show function result
```
  function_name |                                                  create_statement
----------------+---------------------------------------------------------------------------------------------------------------------
  f_random_date | CREATE FUNCTION public.f_random_date()
                |     RETURNS DATE
                |     VOLATILE
                |     NOT LEAKPROOF
                |     CALLED ON NULL INPUT
                |     LANGUAGE SQL
                |     AS $$
                |     SELECT date((now() - (trunc(random() * 365.0)::INT8 * '1 day')) - (trunc(random() * 100.0)::INT8 * '1 year'));
                | $$
(1 row)
```

It looks like when we create the udf the parser was not able parse the inner function statement correctly at this line https://github.com/cockroachdb/cockroach/blob/ed08739c22ecd246c9745d0f301976023c0d004b/pkg/sql/opt/optbuilder/create_function.go#L158 to here

**Comment by yuzefovich** [comment]
This works on 23.2.0.
