### ISSUE TITLE
ensure we're linking jemalloc for rocksdb

### ISSUE THREAD

**Issue by strangemonad** [cockroachdb/cockroach#99]

**Comment by tamird** [comment]
Looks like jemalloc support was added upstream in https://github.com/facebook/rocksdb/commit/fd7a35731854528dde10deb3444a82ae4c1a9206. We'd need to update https://github.com/cockroachdb/c-rocksdb to 3.11 or higher to pick it up.

**Comment by bdarnell** [comment]
That rocksdb commit doesn't add support for jemalloc to the code, just the build script, which we don't use anyway (I could've sworn an earlier version of the build script did include jemalloc support; that's why I wrote #98 to begin with). If we link in jemalloc, rocksdb will use it and this is the recommended configuration. The question is whether we can even do that with go. It may be more trouble than it's worth; I don't know how jemalloc's performance compares to the modern glibc malloc.
