### ISSUE TITLE
tsdb: include TenantStorageMetrics per-tenant

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#99228]
**Is your feature request related to a problem? Please describe.**
`TenantStorageMetrics` appears to [record storage level metrics at the tenant level](https://github.com/cockroachdb/cockroach/blob/f33f404ebaa6c6f092c4ef47a36380c00236f341/pkg/kv/kvserver/metrics.go#L2088-L2115). However, our recent work to [update the MetricsRecorder with tenant registries](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L146) does not capture these metrics. 

These metrics [neither exist in the the store level registries within the recorder](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L142), because the `TenantStorageMetrics` [exist outside of the StoreMetrics registry](https://github.com/cockroachdb/cockroach/blob/f33f404ebaa6c6f092c4ef47a36380c00236f341/pkg/kv/kvserver/metrics.go#L1751-L1756). 

As it stands today, [when we register store-level metrics with the MetricsRecorder](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L237-L244), we don't include any of these TenantStorageMetrics from what I can tell.

Because of this, tenant-level storage metrics that a tenant would naturally want to see, such as `livebytes`, `keybytes`, etc. are not available in TSDB (and therefore, neither in DB Console). 

An app tenant will naturally want to know how much live data they have in their tenant DB, so we will need to find a way to record this information into TSDB so it can be exposed in DB Console.

**Describe the solution you'd like**
Find a way to get these tenant-level storage metrics into TSDB, so that app tenants can view metrics such as `livebytes` in DB Console.

Jira issue: CRDB-25773

**Comment by tbg** [comment]
Don't we just need https://github.com/cockroachdb/cockroach/pull/99353? I don't have all the internals paged in but it seems that once the registry knows about the metrics, everything else should "just work"?

**Comment by tbg** [comment]
I take that back (and closed that PR). We already add the `StoreMetrics` to the registry, and since the `TenantStoreMetrics` is within, it is getting picked up:

https://github.com/cockroachdb/cockroach/blob/50c58b01ec90da0e398670a68c88589f785c42c6/pkg/kv/kvserver/metrics.go#L2657

It's clear that this is working, since we see all of these metrics exported on the prometheus endpoint.

**Comment by tbg** [comment]
So I think this is all working, it's just a different paradigm than the one here:

https://github.com/cockroachdb/cockroach/blob/2353a6a25a9750188a3a02dfee067fe2601b4278/pkg/server/status/recorder.go#L351-L360

The snippet above works for metrics that exist "only" for the tenant (i.e. are not aggregated across tenants). But we don't have a `*Registry` per tenant in the KV server, and the set of tenants is not static - we collect metrics for any tenant for which we have a range (and even some extra ones, for example if we have tenant 123 but not 124, we'll still track something for 124 because there is a range split at the end of 123's keyspace).

Instead, we use `aggmetrics`. You basically have a top-level metric which tracks the sum of all of its children, each child being a tenant that we collect metrics for. The top-level metrics are pretty fundamental KV metrics, like how many bytes are in the keyspace, etc.

These children are currently surfaced on the prometheus endpoint when the `server.child_metrics.enabled` cluster setting is set[^1].

I think we could still use the `tenantRegistries` here:

- we update `tenantStoreMetrics`[^2] (i.e. the thing we have in kvserver for each tenant for which we have replicas) to also have a `*Registry` in it that has all of the metrics on the struct registered to it
- any mutation to the map holding the `tenantStoreMetrics` is mirrored into the `MetricsRecorder`[^3] (which would need to be passed down via an interface)

[^1]: https://github.com/cockroachdb/cockroach/blob/2353a6a25a9750188a3a02dfee067fe2601b4278/pkg/server/status/recorder.go#L289-L296
[^2]: https://github.com/cockroachdb/cockroach/blob/f33f404ebaa6c6f092c4ef47a36380c00236f341/pkg/kv/kvserver/metrics.go#L2254
[^3]: https://github.com/cockroachdb/cockroach/blob/2353a6a25a9750188a3a02dfee067fe2601b4278/pkg/server/status/recorder.go#L185-L199
