### ISSUE TITLE
kvserver: expired expiration leases prevent closed timestamp updates

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#99812]
Expired expiration leases can prevent closed timestamp updates:

https://github.com/cockroachdb/cockroach/blob/60b7440ec5b5d4647c53d180152e625e65e24a74/pkg/kv/kvserver/replica_closedts.go#L61-L67

This can be problematic when enabling `kv.expiration_leases_only.enabled`, because we don't eagerly extend leases unless there's traffic on the range, preventing the closed timestamp from advancing. The lease scheduler in #98433 would mitigate this.

Jira issue: CRDB-26097

Epic CRDB-25200

**Comment by tbg** [comment]
In addressing this we should also address the TODO introduced in https://github.com/cockroachdb/cockroach/pull/97710 in `testcluster.go`:

> // WaitFor5NodeReplication ensures that zone configs are applied and
// up-replication is performed with new zone configs. This is the case for 5+
// node clusters.
// TODO: This code should be moved into WaitForFullReplication once #99812 is
// fixed so that all test would benefit from this check implicitly.
// This bug currently prevents LastUpdated to tick in metamorphic tests
// with kv.expiration_leases_only.enabled = true.

**Comment by erikgrinaker** [comment]
I am marking this as a GA blocker, since it blocks use of `kv.expiration_leases_only.enabled`. This would allow us to land #100430 for 23.1.0.
